risingwavelabs/risingwave

src/frontend/src/optimizer/plan_node/stream_exchange.rs
src/frontend/src/optimizer/plan_node/stream_hash_agg.rs
src/frontend/src/optimizer/plan_node/stream_hash_join.rs
src/frontend/src/optimizer/plan_node/utils.rs

refactor(explain): merge two branch of `formatter_debug_plan_node`

---

src/stream/src/executor/over_window/eowc.rs
src/stream/src/executor/over_window/state/aggregate.rs
src/stream/src/executor/over_window/state/lag.rs
src/stream/src/executor/over_window/state/lead.rs
src/stream/src/executor/over_window/state/mod.rs

perf(over window): split `WindowState::output` to `curr_output` and `slide_forward` to avoid computation on recovery

---

java/connector-node/README.md

doc(java-binding): add docs for running java-binding unit test

---

src/tests/sqlsmith/develop.md
src/tests/sqlsmith/src/validation.rs

Unblock https://github.com/risingwavelabs/risingwave/pull/9977
</details>

fix(sqlsmith): ignore neg exponential

---

src/rpc_client/src/meta_client.rs

try to fix #9334 
This pull request adds several changes to the code, primarily the addition of a member monitor event enum which is used to manipulate the behavior of the `MetaMemberMonitor` loop. The goal is to implement a graceful shutdown, which is achieved by adding a new `drop()` function. Once called, this function sends a shutdown event to the member monitor, just before the instance is dropped.
In addition to the new `drop()` function, the `force_refresh_receiver()` function has been updated to receive the newly added member monitor event. The function is also updated to match the new member monitor event type. …

fix: Add graceful shutdown functionality to `GrpcMetaClient` 

---

e2e_test/streaming/basic.slt
src/frontend/planner_test/src/lib.rs
src/frontend/src/handler/create_mv.rs
src/frontend/src/handler/create_view.rs
src/frontend/src/handler/mod.rs
src/sqlparser/src/ast/mod.rs
src/sqlparser/src/parser.rs
src/sqlparser/tests/sqlparser_common.rs
src/tests/sqlsmith/src/sql_gen/mod.rs

feat(frontend): support create [materialized] view if not exists

---

src/common/src/field_generator/mod.rs

fix(connector/datagen): don't panic on unknown type generation

---

ci/docker-compose.yml
docker/docker-compose-s3-compatible.yml
docker/docker-compose.yml
integration_tests/prometheus/docker-compose.yml

Missed modifications in #10126 .
</details>

fix: fix healthcheck scripts in docker compose yaml

---

.github/workflows/doc.yml
.github/workflows/license_check.yml
.github/workflows/typo.yml
src/cmd/src/bin/compactor.rs

- use sccache (on GHA cache) for doc build
- bump typos & skywalking-eyes for faster startup
</details>

chore: speedup some GHA 

---

src/stream/src/executor/backfill.rs

refactor(backfill): check `current_pos` outside of loop

---

src/stream/src/executor/backfill.rs

Thanks to @chenzl25 for finding the reason and suggesting the fix.
</details>

fix(backfill): handle backwards compatibility case

---

proto/hummock.proto
src/meta/src/hummock/compactor_manager.rs
src/meta/src/hummock/manager/mod.rs
src/meta/src/hummock/manager/tests.rs
src/storage/benches/bench_compactor.rs
src/storage/hummock_sdk/src/compact.rs
src/storage/src/hummock/compactor/compactor_runner.rs
src/storage/src/hummock/compactor/mod.rs
src/storage/src/hummock/compactor/shared_buffer_compact.rs
src/storage/src/hummock/compactor/task_progress.rs

feat(storage): cherry pick #10183

---

e2e_test/source/cdc/cdc.check.slt
e2e_test/source/cdc/cdc.load.slt

For example: https://buildkite.com/risingwavelabs/main/builds/4425
It might be caused by the recently introduced tests case and #10206.
I tried to read some code of Debezium but cannot find a root cause. Let's just remove this test case now to fix main's CI test.
My PR **DOES NOT** contain user-facing changes.
- Other (please specify in the release …

fix: source e2e test failure

---

ci/workflows/pull-request.yml

So that the whole pipeline fail faster and maybe also save some costs. https://buildkite.com/changelog/160-failing-builds-fast
</details>

ci: make some slow steps cancel_on_build_failing

---

e2e_test/batch/catalog/issue_10177.slt.part
e2e_test/batch/catalog/pg_type.slt.part
src/frontend/planner_test/tests/testdata/output/pg_catalog.yaml
src/frontend/src/catalog/system_catalog/mod.rs
src/frontend/src/catalog/system_catalog/pg_catalog/mod.rs
src/frontend/src/catalog/system_catalog/pg_catalog/pg_proc.rs
src/frontend/src/catalog/system_catalog/pg_catalog/pg_type.rs

Resolve #10177 . This PR only introduced a dummy system catalog `pg_proc` to support dotnet Postgres client Npgsql firstly. Check the result in `issue_10177.slt.part` for required query.
introduce system catalog `pg_proc`, refer https://www.postgresql.org/docs/current/catalog-pg-proc.html.
</details>

feat: introduce system catalog pg_proc

---

java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/JsonDeserializer.java
java/connector-node/risingwave-connector-test/src/test/java/com/risingwave/connector/sink/jdbc/JDBCSinkTest.java
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java
java/java-binding/src/main/java/com/risingwave/java/binding/BaseRow.java
java/java-binding/src/main/java/com/risingwave/java/binding/Binding.java
src/java_binding/src/lib.rs

In this PR, we change to return byte array instead of byte array input stream to make the sink row API more general.
</details>

refactor(connector-node): return byte array instead of byte stream on getBytea

---

Cargo.lock
Cargo.toml

fix: update version 0.19.1

---

Makefile.toml

The error like "log size is significantly large" is a little confusing. (It's a error, but look like a warning)
</details>

ci: optimize log dump

---

Cargo.lock
ci/scripts/release.sh
src/cmd_all/Cargo.toml
src/cmd_all/build.rs
src/cmd_all/src/bin/risingwave.rs
src/cmd_all/src/lib.rs

Display GIT SHA in CLI `risingwave -V`. This will always present. Original uses are unchanged (so `SELECT version()` can still be `unknown`). See comment for more info.
Also add some checks/fixes related with release.
</details>

feat: provide git sha for cmd_all

---

integration_tests/presto-trino/README.md
integration_tests/presto-trino/docker-compose.yml
integration_tests/presto-trino/etc/risingwave.properties

feat(demo): add demo to query risingwave from presto or trino pg connector

---

src/meta/src/hummock/compaction_schedule_policy.rs
src/meta/src/hummock/compaction_scheduler.rs
src/meta/src/hummock/compactor_manager.rs
src/meta/src/hummock/manager/mod.rs
src/meta/src/hummock/manager/tests.rs
src/meta/src/hummock/test_utils.rs
src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
src/storage/hummock_sdk/src/lib.rs
src/storage/hummock_test/src/compactor_tests.rs
src/storage/hummock_test/src/hummock_storage_tests.rs
src/storage/hummock_test/src/state_store_tests.rs
src/storage/hummock_test/src/sync_point_tests.rs
src/storage/src/hummock/compactor/shared_buffer_compact.rs
src/storage/src/hummock/shared_buffer/shared_buffer_batch.rs
src/tests/compaction_test/src/delete_range_runner.rs

This reverts commit 237ed2e38719454722864ed6d05b43d4cab27855.
revert https://github.com/risingwavelabs/risingwave/pull/9794 to close https://github.com/risingwavelabs/risingwave/issues/10240
</details>

fix(meta): fix level not exist

---

java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzCdcEventConsumer.java

- close https://github.com/risingwavelabs/risingwave/issues/9891
- we now consider the `schema` field in the cdc json not useful, therefore we remove it
- this is a pr that only changed a single word 🤣
Reference:
- https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-create-events …

fix(cdc): remove schema field for debezium json converter

---

src/frontend/planner_test/tests/testdata/output/temporal_join.yaml
src/frontend/src/optimizer/plan_node/logical_join.rs

chore(typo): refine the error message

---

.github/labeler.yml
.github/pull_request_template.md

The template is a little weird. I think one reason is that previously all tasks need to be ticked. Now this is not required to merge a PR and I think making some changes can make it more natural.
</details>

chore: improve PR template checklist

---

ci/scripts/release.sh
ci/workflows/docker.yml
src/cmd_all/src/bin/risingwave.rs

fix https://github.com/risingwavelabs/risingwave/issues/10277
</details>

fix: build without git but GIT_SHA is provided & fix nightly binary doesn't have SHA

---

ci/workflows/pull-request.yml

It may timeout sometimes, since we added updates and deletes. Unblock https://github.com/risingwavelabs/risingwave/pull/10279.
</details>

chore(sqlsmith): bump fuzzing time

---

ci/scripts/release.sh

As the title.
fix: https://buildkite.com/risingwavelabs/docker/builds/13791#0188ad4a-064b-4efc-9f7d-d845ffc559ef

fix(ci): maven bump in release script

---

src/stream/src/cache/managed_lru.rs
src/stream/src/executor/aggregation/distinct.rs

Remove the metrics if the executor is droped.
</details>

fix: clean dropped executor cache metrics

---

src/meta/src/hummock/metrics_utils.rs

as title
- fix https://github.com/risingwavelabs/risingwave/issues/10297
</details>

fix(storage): fix panic caused by non-exist compaction group

---

e2e_test/batch/basic/range.slt.part
src/frontend/src/binder/relation/mod.rs

fix #10273 fix #8829
</details>

fix: use alias as table function's column name

---

ci/scripts/release.sh

fix `BUILDKITE_TAG` env if condition

fix(ci): fix release script

---

src/common/proc_macro/src/lib.rs

Previously the following code will fail to build:
```rust
#[derive(EstimateSize)]
struct Foo(Bar);
```
Now it works.
~~- [ ] My PR contains user-facing changes.~~ …

fix(macro): support `derive(EstimateSize)` on tuple struct

---

src/utils/runtime/src/lib.rs

refactor(log): change `aws_credential_types::cache::lazy_caching` log level to WARN

---

.github/workflows/typo.yml
.typos.toml
Makefile.toml
integration_tests/datagen/sink/sink.go
integration_tests/tidb-cdc-sink/docker-compose.yml
risedev.yml
src/expr/src/table_function/mod.rs
src/expr/src/vector_op/array_length.rs
src/frontend/src/binder/expr/mod.rs
src/frontend/src/binder/relation/watermark.rs
src/frontend/src/optimizer/plan_node/logical_agg.rs
src/frontend/src/optimizer/plan_node/logical_multi_join.rs
src/frontend/src/scheduler/distributed/stats.rs
src/meta/src/rpc/metrics.rs
src/storage/src/filter_key_extractor.rs
src/storage/src/hummock/compactor/mod.rs
src/storage/src/hummock/compactor/shared_buffer_compact.rs
src/tests/sqlsmith/src/validation.rs

chore: bump typos version and fix typos

---

integration_tests/mysql-sink/create_mv.sql
integration_tests/mysql-sink/create_source.sql
integration_tests/mysql-sink/data_check
integration_tests/mysql-sink/mysql_prepare.sql
integration_tests/mysql-sink/query.sql
integration_tests/postgres-sink/create_mv.sql
integration_tests/postgres-sink/create_source.sql
integration_tests/postgres-sink/data_check
integration_tests/postgres-sink/postgres_prepare.sql
integration_tests/postgres-sink/query.sql

close #9918
close #9919
Test run: https://buildkite.com/risingwavelabs/integration-tests/builds/140
</details>

test(integration-test): jdbc sink data type tests

---

src/common/src/catalog/schema.rs
src/frontend/src/optimizer/plan_node/batch_source.rs
src/frontend/src/optimizer/plan_node/logical_now.rs
src/frontend/src/optimizer/plan_node/logical_share.rs
src/frontend/src/optimizer/plan_node/logical_source.rs
src/frontend/src/optimizer/plan_node/stream_delta_join.rs
src/frontend/src/optimizer/plan_node/stream_dml.rs
src/frontend/src/optimizer/plan_node/stream_share.rs
src/frontend/src/optimizer/plan_node/stream_source.rs
src/frontend/src/optimizer/plan_node/utils.rs

This is a folllllllow up of #10132, #10155, #10157, #10253, #10280, #10281, #10291, #10296.
- Yes

refactor(plan_node_fmt): 6 more impls for Distill, refactor all `columns_name` functions

---

src/risedevtool/kafka.toml

as title
ref https://buildkite.com/risingwavelabs/main-cron/builds/599#0188c0ae-bd86-49c5-a034-d66741452efd
~~- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).~~
~~- [ ] My PR changes performance-critical code. (Please run …

chore: fix kafka download path in risedev

---

e2e_test/source/cdc/cdc.check.slt
e2e_test/source/cdc/cdc.load.slt
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/MySqlValidator.java
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/PostgresValidator.java

fix(connector): validator: allow extra columns in source table (#10170)

---

src/connector/src/parser/debezium/avro_parser.rs
src/connector/src/parser/mod.rs

fix(connector): support kafka log compaction for debezium avro (#9944)

---

ci/scripts/backwards-compat-test.sh
src/risedevtool/kafka.toml

Backwards compat tests failing because older kafka cannot be downloaded via risedev.
This PR provides a workaround prior to 1.0. It will just not use kafka when starting cluster. It does not affect our tests anyway, since we don't have any SOURCE in backwards compat tests yet.
This PR also provides a long term fix by changing the source we pull kafka from.
- RisingWave cluster configuration …

fix(ci): disable kafka for backwards compat test + fix kafka download source

---

src/batch/benches/hash_agg.rs
src/batch/src/executor/hash_agg.rs
src/batch/src/executor/sort_agg.rs

feat(batch): add shutdown check in agg

---

src/common/proc_macro/src/lib.rs

~- [ ] My PR contains user-facing changes.~

fix(macro): support `derive(EstimateSize)` on tuple struct (#10318)

---

src/risedevtool/kafka.toml

cherry pick https://github.com/risingwavelabs/risingwave/pull/10411
</details>

fix(risedevtool): try download kafka from archive.apache if downloads.apache does not work

---

.github/workflows/doc.yml

ref https://github.com/actions/deploy-pages/issues/188#issuecomment-1597613954
</details>

ci: fix rustdoc deployment

---

ci/workflows/pull-request.yml

Fix udf dependency for e2e-test
</details>

chore(ci): fix deps for e2e test

---

src/common/src/memory/mem_context.rs

Pre-requisite of https://github.com/risingwavelabs/risingwave/pull/10425

fix: Batch memory maybe negative (#10338)

---

ci/scripts/deterministic-e2e-test.sh
src/tests/sqlsmith/src/runner.rs

Catch queries which take too long to execute.
Closes https://github.com/risingwavelabs/risingwave/issues/10334
</details>

fix(sqlsmith): timeout if queries take longer than 3s

---

integration_tests/ad-click/docker-compose.yml
integration_tests/ad-ctr/docker-compose.yml
integration_tests/cdn-metrics/docker-compose.yml
integration_tests/clickstream/docker-compose.yml
integration_tests/debezium-mongo/docker-compose.yaml
integration_tests/debezium-mysql/docker-compose.yml
integration_tests/debezium-postgres/docker-compose.yml
integration_tests/delivery/docker-compose.yml
integration_tests/iceberg-sink/docker-compose.yml
integration_tests/kafka-cdc-sink/docker-compose.yml
integration_tests/livestream/docker-compose.yml
integration_tests/mysql-cdc/docker-compose.yml
integration_tests/mysql-sink/docker-compose.yml
integration_tests/pinot-sink/docker-compose.yml
integration_tests/postgres-cdc/docker-compose.yml
integration_tests/postgres-sink/docker-compose.yml
integration_tests/presto-trino/docker-compose.yml
integration_tests/prometheus/docker-compose.yml
integration_tests/schema-registry/docker-compose.yml
integration_tests/superset/docker-compose.yml
integration_tests/tidb-cdc-sink/docker-compose.yml
integration_tests/twitter-pulsar/docker-compose.yml
integration_tests/twitter/docker-compose.yml
integration_tests/upsert-avro/docker-compose.yml

fix(integration-test): fix docker compose file directory

---

src/risedevtool/kafka.toml

Recent checks failing, I suspect is caused by this.
</details>

chore(risedevtool): use cdn to download kafka for recent versions

---

Cargo.lock

build: bump openssl, try to fix CI

---

ci/scripts/pr-fuzz-test.sh

I think now is a good time to start running sqlsmith e2e fuzzing per PR again before v1.0 major release.
We can just re-run the job if it fails, since it is random.
</details>

chore(ci): run sqlsmith per pr again

---

src/frontend/planner_test/tests/testdata/output/append_only.yaml
src/frontend/planner_test/tests/testdata/output/share.yaml
src/frontend/planner_test/tests/testdata/output/stream_dist_agg.yaml
src/frontend/planner_test/tests/testdata/output/temporal_join.yaml
src/frontend/src/optimizer/plan_node/batch_delete.rs
src/frontend/src/optimizer/plan_node/batch_limit.rs
src/frontend/src/optimizer/plan_node/generic/dedup.rs
src/frontend/src/optimizer/plan_node/generic/delete.rs
src/frontend/src/optimizer/plan_node/generic/except.rs
src/frontend/src/optimizer/plan_node/generic/expand.rs
src/frontend/src/optimizer/plan_node/generic/filter.rs
src/frontend/src/optimizer/plan_node/generic/limit.rs
src/frontend/src/optimizer/plan_node/generic/mod.rs
src/frontend/src/optimizer/plan_node/generic/over_window.rs
src/frontend/src/optimizer/plan_node/generic/project_set.rs
src/frontend/src/optimizer/plan_node/generic/top_n.rs
src/frontend/src/optimizer/plan_node/generic/update.rs
src/frontend/src/optimizer/plan_node/stream_simple_agg.rs
src/frontend/src/optimizer/plan_node/stream_topn.rs

refactor(plan_node_fmt): uniform pretty printing of `[ append_only ]` as of #10100

---

Cargo.lock
proto/hummock.proto
src/meta/src/hummock/compaction/level_selector.rs
src/meta/src/hummock/compaction/mod.rs
src/meta/src/hummock/compaction/picker/space_reclaim_compaction_picker.rs
src/meta/src/hummock/manager/compaction_group_manager.rs
src/meta/src/hummock/manager/mod.rs
src/meta/src/hummock/manager/tests.rs
src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
src/storage/hummock_test/src/compactor_tests.rs

cherry-pick https://github.com/risingwavelabs/risingwave/pull/10258
</details>

fix(compaction): support trivial reclaim

---

src/meta/src/manager/catalog/mod.rs

fix: drop all connections for drop database

---

src/frontend/planner_test/tests/testdata/output/nexmark.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_source.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml
src/frontend/planner_test/tests/testdata/output/over_window_function.yaml
src/frontend/src/optimizer/plan_node/generic/top_n.rs
src/frontend/src/optimizer/plan_node/logical_union.rs
src/frontend/src/optimizer/plan_node/mod.rs
src/frontend/src/optimizer/plan_node/stream_group_topn.rs
src/frontend/src/optimizer/plan_node/stream_hash_join.rs
src/frontend/src/optimizer/plan_node/stream_materialize.rs
src/frontend/src/optimizer/plan_node/stream_table_scan.rs
src/frontend/src/optimizer/plan_node/stream_topn.rs
src/frontend/src/optimizer/plan_node/stream_watermark_filter.rs

Finish the implementation of `Distill`

refactor(plan_node_fmt): Now `PlanNode : Distill`!!!

---

src/batch/benches/hash_join.rs
src/batch/src/executor/join/distributed_lookup_join.rs
src/batch/src/executor/join/hash_join.rs
src/batch/src/executor/join/local_lookup_join.rs
src/batch/src/executor/join/lookup_join_base.rs

feat: Add mem counter for batch join executors (#10044)

---

Cargo.lock
src/cmd/src/bin/compactor.rs
src/cmd/src/bin/compute_node.rs
src/cmd/src/bin/ctl.rs
src/cmd/src/bin/frontend_node.rs
src/cmd/src/bin/meta_node.rs
src/cmd/src/lib.rs
src/cmd_all/Cargo.toml
src/cmd_all/src/bin/risingwave.rs

refactor(cmd): unify entry points for `cmd_all` and `cmd` (#10073)

---

src/batch/src/executor/source.rs
src/compute/tests/integration_tests.rs
src/connector/src/source/base.rs
src/connector/src/source/filesystem/s3/source/reader.rs
src/connector/src/source/kafka/source/reader.rs
src/connector/src/source/kinesis/source/reader.rs
src/connector/src/source/pulsar/source/reader.rs
src/stream/src/executor/source/fs_source_executor.rs
src/stream/src/executor/source/source_executor.rs
src/stream/src/from_proto/source.rs

chore: make source max chunk size consistent with `devlop.chunk_size`

---

Cargo.lock
Cargo.toml
src/bench/Cargo.toml
src/bench/s3_bench/main.rs
src/connector/Cargo.toml
src/connector/src/aws_utils.rs
src/connector/src/common.rs
src/connector/src/source/kinesis/config.rs
src/connector/src/source/kinesis/enumerator/client.rs
src/connector/src/source/kinesis/source/message.rs
src/connector/src/source/kinesis/source/reader.rs
src/meta/src/error.rs
src/meta/src/rpc/cloud_provider.rs
src/object_store/Cargo.toml
src/object_store/src/object/error.rs
src/object_store/src/object/s3.rs
src/tests/simulation/Cargo.toml
src/utils/runtime/src/lib.rs
src/workspace-hack/Cargo.toml

refactor(aws): bump aws sdk version (#10091)

---

ci/workflows/main.yml
ci/workflows/pull-request.yml

chore(ci): increase timeout for unit test and end-to-end deterministic test

---

Cargo.lock
src/connector/Cargo.toml
src/connector/src/parser/avro/util.rs
src/connector/src/parser/unified/avro.rs

fix: support variable scale decimal in avro (#10368)

---

ci/scripts/deterministic-e2e-test.sh
ci/scripts/pr-fuzz-test.sh
ci/scripts/run-fuzz-test.sh
ci/workflows/pull-request.yml
ci/workflows/sqlsmith-snapshots.yml
src/tests/sqlsmith/README.md
src/tests/sqlsmith/scripts/gen_queries.sh
src/tests/sqlsmith/src/runner.rs
src/tests/sqlsmith/src/sql_gen/dml.rs
src/tests/sqlsmith/src/sql_gen/expr.rs
src/tests/sqlsmith/src/sql_gen/mod.rs
src/tests/sqlsmith/src/sql_gen/query.rs
src/tests/sqlsmith/src/sql_gen/relation.rs
src/tests/sqlsmith/src/sql_gen/time_window.rs
src/tests/sqlsmith/tests/frontend/mod.rs

```
commit 1c0e052a088c2f464faee9cd2a2cc1e1c3a7a8a7
Author: xxchan <xxchan22f@gmail.com>
Date:   Tue Jun 20 03:51:24 2023 +0200
refactor(sqlsmith): refactor FROM generation (#10343)
Co-authored-by: Noel Kwan <47273164+kwannoel@users.noreply.github.com>
commit de577c1ccc1bee6cb9a9b62f9ba68518c8fddeb0
Author: Noel Kwan <47273164+kwannoel@users.noreply.github.com>
Date:   Fri Jun 23 19:07:27 2023 +0800
fix(sqlsmith): test execution time for pre-generated queries + increase coverage (#10430)
commit c55b4842bd8141d6c441ebd79362f3ef22d35880
Author: Noel Kwan <47273164+kwannoel@users.noreply.github.com>
Date:   Fri Jun 23 …
```

chore: merge 10422, 10424, 10444, 10491, 10430, 10343 into v0.19.0-rc

---

src/common/src/estimate_size/collections/lru.rs
src/common/src/estimate_size/mod.rs

fix(estimate_size): return correct value size

---

java/connector-node/risingwave-connector-test/src/test/java/com/risingwave/connector/sink/iceberg/IcebergSinkFactoryTest.java
java/connector-node/risingwave-sink-iceberg/src/main/java/com/risingwave/connector/IcebergSinkFactory.java
java/connector-node/risingwave-sink-iceberg/src/main/java/com/risingwave/connector/IcebergSinkUtil.java

fix(iceberg):  Add schema type check before creating sink finished (#10299)

---

e2e_test/source/basic/nosim_kafka.slt
integration_tests/upsert-avro/create_mv.sql
integration_tests/upsert-avro/create_source.sql
integration_tests/upsert-avro/datagen.py
integration_tests/upsert-avro/docker-compose.yml
integration_tests/upsert-avro/query.sql
scripts/source/avro_producer.py
scripts/source/test_data/upsert_student_avro_json.1
scripts/source/test_data/upsert_student_key_not_subset_of_value_avro_json.1
src/connector/src/parser/avro/parser.rs
src/frontend/src/handler/create_source.rs

feat(connector): avro key as column (#9926)

---

java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/JsonDeserializer.java
java/connector-node/risingwave-connector-test/src/test/java/com/risingwave/connector/sink/jdbc/JDBCSinkTest.java
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java
java/java-binding/src/main/java/com/risingwave/java/binding/BaseRow.java
java/java-binding/src/main/java/com/risingwave/java/binding/Binding.java
src/java_binding/src/lib.rs

refactor(connector-node): return byte array instead of byte stream on getBytea (#10207)

---

e2e_test/ddl/invalid_operation.slt
e2e_test/streaming/basic.slt
e2e_test/streaming/bug_fixes/issue_10448.slt
src/frontend/planner_test/src/lib.rs
src/frontend/src/binder/mod.rs
src/frontend/src/binder/relation/mod.rs
src/frontend/src/handler/create_index.rs
src/frontend/src/handler/create_mv.rs
src/frontend/src/handler/create_table.rs
src/frontend/src/handler/create_table_as.rs
src/frontend/src/handler/create_view.rs
src/frontend/src/handler/mod.rs
src/frontend/src/session.rs
src/sqlparser/src/ast/mod.rs
src/sqlparser/src/parser.rs
src/sqlparser/tests/sqlparser_common.rs
src/tests/sqlsmith/src/sql_gen/mod.rs

chore: merge 10449, 10128 into `v0.19.0-rc`

---

src/meta/src/manager/catalog/mod.rs

fix: drop all connections for drop database (#10474)

---

Cargo.lock
src/common/src/config.rs
src/compute/Cargo.toml
src/compute/src/server.rs
src/config/example.toml
src/expr/Cargo.toml
src/expr/src/expr/expr_udf.rs
src/object_store/Cargo.toml
src/storage/Cargo.toml
src/storage/src/monitor/monitored_store.rs
src/stream/Cargo.toml
src/utils/runtime/Cargo.toml

feat: enable verbose await-tree by default in production (#10144)

---

.github/workflows/cherry-pick-to-release-branch.yml

see https://github.com/risingwavelabs/github-action-cherry-pick/tree/master
https://github.com/risingwavelabs/github-action-cherry-pick/blob/master/action.yml#L12-L15
https://github.com/risingwavelabs/github-action-cherry-pick/blob/master/entrypoint.sh#L3-L11
`with:` are the inputs to the GitHub Action

chore: provide pr body for the github action

---

ci/workflows/pull-request.yml

- https://buildkite.com/risingwavelabs/pull-request/builds?branch=dylan%2Frefactor_dml_table_stream_reader failed many times.
</details>

chore(ci): increase timeout for e2e opendal test

---

src/object_store/src/object/opendal_engine/azblob.rs
src/object_store/src/object/opendal_engine/fs.rs
src/object_store/src/object/opendal_engine/gcs.rs
src/object_store/src/object/opendal_engine/hdfs.rs
src/object_store/src/object/opendal_engine/oss.rs
src/object_store/src/object/opendal_engine/webhdfs.rs

feat(object_store): add retry for OpenDAL storage (#10519)

---

Cargo.lock
Cargo.toml

chore: update version 0.19.2

---

ci/workflows/main-cron.yml

as title,
according to @lmatz , there might be some problem with the account quota.
since we have ran the s3 compatible test for a period of time, I think it is ok to disable it. 
resolve #10498
</details>

chore: disable lyvecloud s3 test

---

ci/scripts/release.sh

fix(cherry-pick): cherry pick 10287 10325

---

ci/workflows/integration-tests.yml
integration_tests/debezium-sqlserver/create_mv.sql
integration_tests/debezium-sqlserver/create_source.sql
integration_tests/debezium-sqlserver/data_check
integration_tests/debezium-sqlserver/docker-compose.yml
integration_tests/debezium-sqlserver/query.sql
integration_tests/debezium-sqlserver/sql_server/init.sql
integration_tests/debezium-sqlserver/sql_server/run_init.sh
integration_tests/debezium-sqlserver/sql_server/sql_dbz.sh

A demo about sqlserver cdc via debezium and kafka. It has been tested on my aws ec2, a x86 ubuntu.
Will resolve #9330 
@hengm3467 @CharlieSYH You may want to add it to our document: 
https://www.risingwave.dev/docs/current/create-source-cdc/

test: add sqlserver + debezium demo

---

src/connector/src/source/manager.rs

Set `is_row_id` flag for batch source.
</details>

fix(source): correctly set is_row_id flag

---

src/ctl/src/cmd_impl/scale/resize.rs
src/ctl/src/lib.rs

As title, first, the input will be parsed as a u32. If it fails, it will be treated as a host, and will be compared with the existing hosts.
</details>

feat: support host in risectl scale resize command

---

src/ctl/src/cmd_impl/meta/reschedule.rs
src/ctl/src/lib.rs

chore: refine unregister worker command

---

src/meta/src/manager/catalog/mod.rs
src/meta/src/rpc/cloud_provider.rs
src/meta/src/rpc/ddl_controller.rs
src/meta/src/rpc/service/ddl_service.rs

fix(connection): delete vpc endpoint when drop connection (#10455)

---

Cargo.lock
Cargo.toml

chore: update version 0.19.3

---

ci/scripts/release.sh

fix(cherry pick): cherry pick 10287 10325

---

ci/scripts/release.sh

fix(ci): maven version bump 3.9.3

---

Cargo.lock
src/object_store/Cargo.toml

As we are testing stability of storage supported by OpenDAL, I think it's ok to bump version this week. 
</details>

chore: bump OpenDAL to v0.38

---

src/stream/src/executor/over_window/delta_btree_map.rs
src/stream/src/executor/over_window/general.rs
src/stream/src/executor/over_window/state/aggregate.rs

- Fix check for unbounded frame end (no need any more)
- Fix `lag/lead(x, 0)` case
- Fix cases where the _delta_ is at the beginning or end of partition …

fix(over window): fix some bugs on corner cases for general over window executor

---

src/compute/tests/integration_tests.rs
src/stream/src/executor/integration_tests.rs
src/stream/src/executor/lookup/sides.rs
src/stream/src/executor/lookup_union.rs
src/stream/src/executor/project_set.rs
src/stream/src/executor/temporal_join.rs
src/stream/src/executor/union.rs

feat(streaming): handle all watermark in executors

---

src/utils/runtime/src/lib.rs

chore: suppress risingwave_sqlparser log level

---

integration_tests/schema-registry/create_source.sql

fix(source demos): typo

---

src/batch/src/executor/delete.rs
src/batch/src/executor/insert.rs
src/batch/src/executor/update.rs
src/batch/src/task/env.rs
src/common/src/config.rs
src/compute/src/server.rs
src/compute/tests/integration_tests.rs
src/config/example.toml
src/source/src/dml_manager.rs
src/source/src/table.rs
src/stream/src/executor/dml.rs
src/stream/src/executor/stream_reader.rs
src/stream/src/task/env.rs

chore(stream): make dml channel initial permits configurable

---

proto/meta.proto
src/ctl/src/cmd_impl/scale/resize.rs
src/ctl/src/lib.rs
src/meta/src/dashboard/mod.rs
src/meta/src/hummock/vacuum.rs
src/meta/src/manager/cluster.rs
src/meta/src/model/cluster.rs
src/meta/src/rpc/metrics.rs
src/meta/src/rpc/service/cluster_service.rs
src/meta/src/rpc/service/notification_service.rs
src/meta/src/rpc/service/scale_service.rs
src/meta/src/stream/stream_graph/actor.rs
src/meta/src/stream/stream_manager.rs
src/meta/src/stream/test_fragmenter.rs
src/rpc_client/src/meta_client.rs
src/tests/simulation/src/cluster.rs
src/tests/simulation/src/ctl_ext.rs
src/tests/simulation/tests/integration_tests/scale/schedulability.rs

chore: refine cordon/uncordon semantics

---

e2e_test/udf/udf.slt
java/udf/README.md
src/frontend/src/handler/create_function.rs
src/udf/python/README.md

Currently users are required to specify the `language` in create function statements. But actually it is unnecessary in external function approach. So this PR makes the `language` an optional field. If specified, it will be ignored for compatibility.
The `language` parameter is no longer required in create function statements.
</details>

feat(udf): allow to ignore "language" in create function statements

---

src/expr/src/vector_op/crc.rs

refactor(sqlsmith): refactor FROM generation (#10343)

---

e2e_test/sink/remote/jdbc.check.pg.slt
e2e_test/sink/remote/jdbc.load.slt
e2e_test/sink/remote/pg_create_table.sql
java/connector-node/assembly/scripts/start-service.sh
java/connector-node/python-client/integration_tests.py
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/SinkValidationHandler.java
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSinkConfig.java
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSinkFactory.java
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JdbcUtils.java
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/jdbc/JdbcDialect.java
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/jdbc/JdbcDialectFactory.java
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/jdbc/MySqlDialect.java
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/jdbc/MySqlDialectFactory.java
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/jdbc/PostgresDialect.java
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/jdbc/PostgresDialectFactory.java
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/jdbc/SchemaTableName.java
java/pom.xml

fix(jdbc-sink): cherry-pick #10326 and #10576 to v0.19.0-rc

---

src/frontend/planner_test/tests/testdata/output/agg.yaml
src/frontend/planner_test/tests/testdata/output/column_pruning.yaml
src/frontend/planner_test/tests/testdata/output/distribution_derive.yaml
src/frontend/planner_test/tests/testdata/output/emit_on_window_close.yaml
src/frontend/planner_test/tests/testdata/output/except.yaml
src/frontend/planner_test/tests/testdata/output/intersect.yaml
src/frontend/planner_test/tests/testdata/output/join.yaml
src/frontend/planner_test/tests/testdata/output/nexmark.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_source.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml
src/frontend/planner_test/tests/testdata/output/over_window_function.yaml
src/frontend/planner_test/tests/testdata/output/predicate_pushdown.yaml
src/frontend/planner_test/tests/testdata/output/share.yaml
src/frontend/planner_test/tests/testdata/output/stream_dist_agg.yaml
src/frontend/planner_test/tests/testdata/output/subquery.yaml
src/frontend/planner_test/tests/testdata/output/temporal_filter.yaml
src/frontend/planner_test/tests/testdata/output/time_window.yaml
src/frontend/planner_test/tests/testdata/output/tpch.yaml
src/frontend/planner_test/tests/testdata/output/tpch_variant.yaml
src/frontend/planner_test/tests/testdata/output/union.yaml
src/frontend/planner_test/tests/testdata/output/watermark.yaml
src/frontend/src/optimizer/plan_node/generic/hop_window.rs
src/frontend/src/optimizer/plan_node/mod.rs

refactor(plan_node_fmt): use new fmt for `identity`

---

integration_tests/debezium-sqlserver/create_source.sql

a confliction between https://github.com/risingwavelabs/risingwave/pull/10556 and https://github.com/risingwavelabs/risingwave/pull/10561
</details>

fix: demo with new ddl syntax

---

ci/scripts/integration-tests.sh

https://buildkite.com/risingwavelabs/integration-tests/builds/171#018916b6-b7f8-4250-b0d9-93151caef26e
```
ci/scripts/integration-tests.sh: line 42: RW_IMAGE_VERSION: unbound variable
```
</details>

fix: integration test unbounded variable

---

src/meta/src/barrier/mod.rs

chore: update barrier number metrics regularly

---

src/stream/src/executor/lookup/sides.rs

- This recovery test failed to proceed because it panicked in the delta join assertion. However, it is possible to violate this assertion during the recovery test, so it should throw an error instead of panic.  https://buildkite.com/risingwavelabs/main/builds/4727
</details>

refactor(stream): refactor delta join align_barrier method

---

Cargo.lock
src/utils/pgwire/Cargo.toml
src/utils/pgwire/src/error.rs
src/utils/pgwire/src/pg_protocol.rs

Follow-up of #10066. Close #10060.
Catch the panic during the processing of any pgwire message in the protocol layer. Return the panic as an error gracefully to users and always terminate the current session for safety.
Preview:
```
psql (14.8 (Homebrew), server 8.3.0)
dev=> select $1;
ERROR:  Panicked when processing: internal error: entered unreachable code: Parameter should not appear here. It will be replaced by a literal before this step..
This is a bug. We would appreciate a bug report at https://github.com/risingwavelabs/risingwave/issues/new?labels=type%2Fbug&template=bug_report.yml
server closed the connection …
```

feat(pgwire): catch panic from frontend

---

src/tests/sqlsmith/src/sql_gen/functions.rs
src/tests/sqlsmith/src/sql_gen/scalar.rs

Limit overlay `start`, `count` to avoid TLE.
Closes https://github.com/risingwavelabs/risingwave/issues/10695
</details>

fix(sqlsmith): constrain overlay arguments

---

src/meta/src/manager/streaming_job.rs
src/meta/src/stream/stream_graph/fragment.rs

fix: binding the correct owner to internal tables

---

src/stream/src/executor/hash_join.rs

refactor: print join side in stack when panic

---

src/expr/src/vector_op/cast.rs
src/frontend/planner_test/tests/testdata/output/range_scan.yaml

chore(expr): refine parsing error report

---

src/common/src/session_config/mod.rs
src/frontend/planner_test/tests/testdata/input/agg.yaml
src/frontend/planner_test/tests/testdata/input/nexmark.yaml
src/frontend/planner_test/tests/testdata/input/nexmark_source.yaml
src/frontend/planner_test/tests/testdata/output/agg.yaml
src/frontend/planner_test/tests/testdata/output/nexmark.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_source.yaml
src/frontend/src/optimizer/logical_optimization.rs
src/frontend/src/optimizer/plan_node/generic/expand.rs
src/frontend/src/optimizer/plan_node/stream_expand.rs

feat(optimizer): add force split distinct agg flag

---

src/object_store/src/object/mod.rs

Trace streaming upload and streaming read.
</details>

chore(trace): add more trace for object store

---

src/stream/src/executor/dynamic_filter.rs

perf(stream): concurrently create_iter and fetch in dynamic filter

---

.github/workflows/cherry-pick-to-release-branch.yml

chore: add cherry-pick action for v1.0

---

src/meta/src/stream/source_manager.rs

resolve #10718
although it cannot handle timeout either, it still serves as an alternative to handle an unconnectable endpoint. 
</details>

fix: add timeout in force tick

---

src/frontend/planner_test/tests/testdata/input/join.yaml
src/frontend/planner_test/tests/testdata/output/join.yaml
src/frontend/src/binder/relation/join.rs

Fixes #10617.
- ~~[ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details]~~(https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBU …

fix(binder): ignore hidden column for natural join

---

docker/aws.env
docker/docker-compose-with-s3.yml

fix: fix docker compose on s3

---

integration_tests/iceberg-sink/docker-compose.yml

fix docker build error.
</details>

fix(integration_tests): fix docker build error

---

src/storage/src/hummock/state_store.rs
src/storage/src/hummock/store/state_store.rs
src/storage/src/lib.rs
src/storage/src/mem_table.rs
src/storage/src/memory.rs
src/storage/src/monitor/monitored_store.rs
src/storage/src/monitor/traced_store.rs
src/storage/src/panic_store.rs
src/storage/src/store.rs
src/storage/src/store_impl.rs

As in https://github.com/risingwavelabs/risingwave/issues/10554.
</details>

refactor(storage): simplify associated type in state store trait

---

src/expr/src/vector_op/length.rs

refactor(expr): simplify octet_length

---

src/compute/src/server.rs

chore: refine memory config log print

---

src/frontend/planner_test/tests/testdata/input/agg.yaml
src/frontend/planner_test/tests/testdata/output/agg.yaml
src/frontend/src/optimizer/plan_node/batch_hash_agg.rs
src/frontend/src/optimizer/plan_node/batch_sort_agg.rs
src/frontend/src/optimizer/plan_node/generic/agg.rs
src/frontend/src/optimizer/plan_node/logical_agg.rs
src/frontend/src/optimizer/plan_visitor/cardinality_visitor.rs
src/frontend/src/optimizer/rule/apply_agg_transpose_rule.rs
src/frontend/src/optimizer/rule/distinct_agg_rule.rs
src/frontend/src/optimizer/rule/min_max_on_index_rule.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/10790
</details>

fix(optimizer): cherry pick 10790 to_v1.0-rc

---

ci/workflows/main-cron.yml
ci/workflows/main.yml

https://buildkite.com/risingwavelabs/main-cron/builds/628
https://buildkite.com/risingwavelabs/main/builds/4788
12 minutes are enough most of time, but the timeout is pretty close
</details>

chore: increase timeout for unit tests in main and main-cron

---

src/meta/src/hummock/manager/versioning.rs
src/meta/src/manager/catalog/fragment.rs
src/meta/src/stream/scale.rs
src/meta/src/stream/source_manager.rs
src/meta/src/stream/test_scale.rs
src/source/src/dml_manager.rs
src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
src/storage/src/filter_key_extractor.rs
src/stream/src/executor/dispatch.rs
src/stream/src/executor/source/source_executor.rs
src/stream/src/executor/top_n/top_n_cache.rs
src/stream/src/executor/top_n/topn_cache_state.rs

`drain_filter` is used to consuming a part of the collection, so its performance is likely worse then `retain`. Also after rust 1.72.0, unused `DrainFilter` will become a compile-time warning.
</details>

refactor(*): use retain as far as possible

---

src/frontend/src/optimizer/plan_node/batch_hash_agg.rs
src/frontend/src/optimizer/plan_node/batch_sort_agg.rs
src/frontend/src/optimizer/plan_node/generic/agg.rs
src/frontend/src/optimizer/plan_node/logical_agg.rs
src/frontend/src/optimizer/plan_node/stream.rs
src/frontend/src/optimizer/plan_node/stream_hash_agg.rs
src/frontend/src/optimizer/plan_node/stream_stateless_simple_agg.rs
src/frontend/src/optimizer/plan_visitor/cardinality_visitor.rs
src/frontend/src/optimizer/rule/agg_project_merge_rule.rs
src/frontend/src/optimizer/rule/apply_agg_transpose_rule.rs
src/frontend/src/optimizer/rule/distinct_agg_rule.rs
src/frontend/src/optimizer/rule/except_to_anti_join_rule.rs
src/frontend/src/optimizer/rule/intersect_to_semi_join_rule.rs
src/frontend/src/optimizer/rule/min_max_on_index_rule.rs
src/frontend/src/planner/select.rs
src/frontend/src/utils/index_set.rs
src/frontend/src/utils/mod.rs

Fix #10788.
- ~~[ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details]~~(https://github.com/risingwavelabs/risingwave/blob/m …

refactor(optimizer): introduce `IndexSet` to represent deduplicated column indices

---

src/frontend/src/optimizer/plan_node/batch_hash_agg.rs
src/frontend/src/optimizer/plan_node/batch_sort_agg.rs
src/frontend/src/optimizer/plan_node/stream_hash_agg.rs

To avoid possible bug if we add other `Distribution` variants later.
- ~~[ ] My PR contains critical fixes that are necessary to be merged …

refactor(optimizer): remove unnecessary match when rewriting distribution

---

docs/developer-guide.md

`pkg-config` and `libssl-dev` are required when running `risedev install-tools`
</details>

chore: add pkg-config and libssl-dev as the dependencies

---

src/tests/sqlsmith/README.md

doc(sqlsmith): make it clear how to test changes

---

ci/workflows/main-cron.yml
ci/workflows/pull-request.yml

- Fix timeout of unit test
- Fix timeout of backwards compat test
Just bump timeouts.
We also make PR timeouts stricter for these two jobs in PR, so that `main-cron` can be stable.
</details>

chore(ci): fix timeouts

---

ci/workflows/main-cron.yml
ci/workflows/pull-request.yml

Closes https://github.com/risingwavelabs/risingwave/issues/10841
</details>

chore(ci): Increase timeouts

---

src/storage/src/hummock/compactor/mod.rs

…(#10833)
cherry pick https://github.com/risingwavelabs/risingwave/pull/10833
</details>

fix(storage): revert xor8 filter builder because of bad performance

---

proto/common.proto
src/frontend/src/scheduler/distributed/query.rs
src/frontend/src/scheduler/worker_node_manager.rs
src/meta/src/manager/cluster.rs
src/meta/src/model/cluster.rs

as title, Resolve #10442 .
This pull request introduces a new field called "transactional_id" to the WorkerNode message in the "common.proto" file. This field enables various parts of the code to utilize and assign values to it for multiple purposes.
Furthermore, this PR also ensures that "transactional_id" is appropriately utilized in several code sections, including "query.rs," "worker_node_manager.rs," and "cluster.rs" files.
Additionally, the ClusterManagerCore struct in "cluster.rs" receives a new field called "available_transactional_ids" to keep track of available machine IDs.
These changes enhance the …

feat: Added transactional_id to WorkerNode

---

ci/plugins/docker-compose-logs/hooks/post-command

chore(ci): add connector node logs for integration test

---

src/object_store/src/object/s3.rs

chore: remove some previous compatibility code

---

e2e_test/streaming/basic_agg.slt
src/frontend/src/expr/agg_call.rs
src/stream/src/executor/aggregation/agg_impl/foldable.rs
src/stream/src/executor/aggregation/agg_impl/mod.rs
src/tests/sqlsmith/src/sql_gen/agg.rs

Mitigate panic in #10838 before #10753 is ready
</details>

fix(stream): agg `count` missing for some types

---

Cargo.lock
Cargo.toml

chore: update version 1.0.0

---

ci/scripts/connector-node-integration-test.sh
java/connector-node/README.md
java/connector-node/python-client/.gitignore
java/connector-node/python-client/build-venv.sh
java/connector-node/python-client/format-python.sh
java/connector-node/python-client/gen-stub.sh
java/connector-node/python-client/integration_tests.py
java/connector-node/python-client/proto/.gitignore
java/connector-node/python-client/proto/__init__.py
java/connector-node/python-client/pyspark-util.py

As titled.
Refactor on the integration test code is included.
</details>

chore(sink): add format check for integration test script

---

ci/scripts/release.sh

fix CI release build
</details>

fix(ci): install cyrus-sasl in release build

---

src/tests/sqlsmith/src/sql_gen/query.rs

feat(test): support grouping set for sql-smith

---

src/tests/compaction_test/src/compaction_test_runner.rs
src/tests/state_cleaning_test/data/agg.toml

Fix typo sreported by the latest typo check that blocks my ./risedev check
</details>

chore: fix typos reported by the latest typo check

---

src/tests/sqlsmith/src/sql_gen/query.rs

Follow up from https://github.com/risingwavelabs/risingwave/pull/10918#issuecomment-1632653330
Keep the limit 0 fix, and the grouping set generation logic (so we can easily re-enable it again later).
</details>

fix(sqlsmith): stub grouping set gen

---

docker/docker-compose.yml

Data is stored in container, instead of volume. So data will get lost if the container is destroyed, e.g., by `docker compose down`
</details>

fix(docker-compose): etcd data is not persisted

---

docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-s3.yml

as title, follow https://github.com/risingwavelabs/risingwave/pull/10922
</details>

fix(docker-compose): persist etcd data for all docker compose cases

---

src/storage/backup/integration_tests/common.sh

Fix backup test scripts failure after IO redirection in #10880.
</details>

fix(test): fix failed tests due to previous ctl io redirection

---

src/frontend/src/handler/transaction.rs
src/frontend/src/session.rs
src/utils/pgwire/src/pg_message.rs
src/utils/pgwire/src/pg_protocol.rs
src/utils/pgwire/src/pg_server.rs

- https://www.postgresql.org/docs/current/protocol-message-formats.html `ReadyForQuery`
- #10736 
</details>

feat(pgwire): report transaction status

---

.github/workflows/assign-issue-milestone.yml

Now it's built-in by GitHub Project: https://github.com/orgs/risingwavelabs/projects/13/workflows/10455198
</details>

fix(workflow): no need to manually add project now

---

src/sqlparser/src/ast/statement.rs

fix: display source format correctly

---

e2e_test/sink/remote/jdbc.check.pg.slt
e2e_test/sink/remote/jdbc.load.slt
e2e_test/sink/remote/pg_create_table.sql
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/jdbc/JdbcDialect.java
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/jdbc/MySqlDialect.java
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/jdbc/PostgresDialect.java
src/connector/src/sink/remote.rs

As title.
close: https://github.com/risingwavelabs/risingwave/issues/10948
</details>

fix(jdbc-sink): generate insert into stmt for append-only sink (cherrypick)

---

src/common/src/array/arrow.rs
src/common/src/array/error.rs
src/expr/src/expr/expr_udf.rs
src/expr/src/table_function/user_defined.rs
src/frontend/src/handler/create_function.rs
src/udf/src/external.rs

https://github.com/risingwavelabs/risingwave/pull/10903#discussion_r1262071736
> This into currently panics on unsupported types. We need to update it to a TryFrom and handle those cases.
This PR update from to TryFrom for data_type to arrow data_type
Please …

refactor(common): switch to try_into for data to arrow data

---

docs/developer-guide.md
docs/microbenchmarks.md

https://github.com/risingwavelabs/risingwave/issues/10863
</details>

doc(bench): How to generate Microbench flamegraph

---

src/frontend/planner_test/tests/testdata/output/emit_on_window_close.yaml
src/frontend/planner_test/tests/testdata/output/nexmark.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_source.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml
src/frontend/planner_test/tests/testdata/output/watermark.yaml
src/frontend/src/utils/stream_graph_formatter.rs

feat(explain): add explain dist sql for over window

---

ci/scripts/gen-flamegraph.sh
ci/scripts/sql/nexmark/q12.drop.sql
ci/scripts/sql/nexmark/q12.sql
ci/scripts/sql/nexmark/q16.sql
ci/scripts/sql/nexmark/q17.sql
ci/scripts/sql/nexmark/q19-rewrite.drop.sql
ci/scripts/sql/nexmark/q19-rewrite.sql
ci/scripts/sql/nexmark/q19.drop.sql
ci/scripts/sql/nexmark/q19.sql
ci/scripts/sql/nexmark/q3-no-condition.drop.sql
ci/scripts/sql/nexmark/q3-no-condition.sql
ci/scripts/sql/nexmark/q5-many-windows.drop.sql
ci/scripts/sql/nexmark/q5-many-windows.sql
ci/scripts/sql/nexmark/q6-group-top1.sql
ci/workflows/gen-flamegraph-cron.yml
ci/workflows/gen-flamegraph.yml
ci/workflows/pull-request.yml

Some queries left out of flamegraph generation because of bad regex / not synced with kube-bench sink templates.
Fixes q6 as well to use blackhole sink.
</details>

fix(ci): fix flamegraph generation for rewritten queries

---

src/frontend/planner_test/tests/testdata/output/column_pruning.yaml
src/frontend/planner_test/tests/testdata/output/nexmark.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_source.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml
src/frontend/planner_test/tests/testdata/output/over_window_function.yaml
src/frontend/src/optimizer/plan_node/logical_over_window.rs

So that affected range can be shrunk.
- ~~[ ] My PR contains critical fixes that are necessary to be merged into the latest release. …

perf(over window): optimize `row_number` window frame

---

.github/workflows/assign-issue-milestone.yml

The action is not updated for several days... Trying to specify a version.
</details>

fix(pipeline): assign-issue-milestone

---

src/utils/pgwire/src/lib.rs
src/utils/pgwire/src/pg_protocol.rs
src/utils/runtime/src/lib.rs

chore: configurable query log truncate len

---

ci/scripts/sql/nexmark/q13.drop.sql
ci/scripts/sql/nexmark/q13.sql
ci/scripts/sql/nexmark/q19-no-rank-number.drop.sql
ci/scripts/sql/nexmark/q19-no-rank-number.sql
ci/scripts/sql/nexmark/q5.sql

q19 was wrong, it was the rewritten version originally. I have split it into q19 and q19-no-rank-number.
q5 has some minor format issues.
q13 is a new query added by @st1page .
</details>

chore(ci): update flamegraph generation queries q5, q13, q19

---

.github/dependabot.yml

chore: disable auto rebase of dependabot

---

src/ctl/src/cmd_impl/meta/backup_meta.rs

So that we can tell whether backup succeeds by checking the exit code of ctl.
</details>

chore(ctl): specify non-zero exit code when meta backup fails

---

e2e_test/batch/transaction/read_only_multi_conn.slt

As explained in https://github.com/risingwavelabs/risingwave/issues/10928#issuecomment-1633719872.
Close #10928.
</details>

fix(test): fix session consistency in read-only transaction test

---

src/stream/src/executor/temporal_join.rs

- Fix temporal join cache.  Lookup might refill the cache before the `insert` messages from the temporal side upstream. 
</details>

fix(stream): temporal join cache

---

ci/scripts/run-fuzz-test.sh
ci/workflows/pull-request.yml
ci/workflows/sqlsmith-tests.yml

https://github.com/risingwavelabs/risingwave/issues/11074#issuecomment-1645109697
</details>

chore(ci): split sqlsmith pr workflow

---

src/connector/src/source/kinesis/source/message.rs
src/connector/src/source/pulsar/source/message.rs
src/frontend/src/handler/create_source.rs

feat: enable upsert for kinesis & pulsar

---

src/sqlparser/src/ast/statement.rs

correct error in the prompt message
</details>

chore: correct error in the prompt message

---

docker/Dockerfile

fix(docker): minor fix: chmod +x jeprof

---

integration_tests/datagen/ad_click/ad_click.go
integration_tests/datagen/ad_ctr/ad_ctr.go
integration_tests/datagen/cdn_metrics/nics.go
integration_tests/datagen/cdn_metrics/tcp.go
integration_tests/datagen/clickstream/clickstream.go
integration_tests/datagen/delivery/delivery.go
integration_tests/datagen/ecommerce/ecommerce.go
integration_tests/datagen/gen/generator.go
integration_tests/datagen/livestream/livestream.go
integration_tests/datagen/load_gen.go
integration_tests/datagen/main.go
integration_tests/datagen/nexmark/auction.go
integration_tests/datagen/sink/kafka/kafka.go
integration_tests/datagen/sink/kinesis/kinesis.go
integration_tests/datagen/sink/mysql/mysql.go
integration_tests/datagen/sink/postgres/postgres.go
integration_tests/datagen/sink/pulsar/pulsar.go
integration_tests/datagen/sink/s3/s3.go
integration_tests/datagen/sink/sink.go
integration_tests/datagen/twitter/twitter.go

Enhancements for integration_tests/datagen:
1. Generate data and upload to S3 buckets every 10 seconds (`Flush()`)
2. Filter events by `--topic [topic]`
- Refactored some code to support get topic from record 
- Use fixed random seed so that I can use multiple `datagen` processes to generate multiple topics (a better approach is generating once and outputting to multiple sink, but that requires further refactoring on arguments)
- Example: `./datagen --mode ad-ctr --topic ad_impression` & `./datagen --mode ad-ctr --topic ad_click`
Please keep the types that apply …

feat(integration_tests/datagen): Generate data to S3 and filter events by topic

---

src/frontend/planner_test/tests/testdata/input/nexmark.yaml
src/frontend/planner_test/tests/testdata/output/nexmark.yaml

We've already supported q6, q12, q13, just add them to planner_test.
Also add a new query q19_no_rank
</details>

test(planner): update nexmark q6/q12/q13/q19-no-rank in planner test

---

src/meta/src/hummock/manager/mod.rs

chore(storage): remove redundency log

---

src/frontend/planner_test/tests/testdata/output/emit_on_window_close.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml
src/frontend/src/optimizer/plan_node/convert.rs
src/frontend/src/optimizer/plan_node/logical_over_window.rs
src/frontend/src/optimizer/plan_node/mod.rs
src/frontend/src/optimizer/plan_node/stream_sort.rs

Fix #10591
- ~~[ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the …

refactor(eowc): better notice and explain for eowc queries

---

src/common/src/session_config/mod.rs

feat(config): add bytea_output support (only hex)

---

src/frontend/src/binder/expr/function.rs

Fix #11053 
Used by DataGrip
</details>

feat(binder): add fake *_description admin functions

---

src/stream/src/common/table/state_table.rs

chore(watermark): change state cleaning interval

---

src/common/src/session_config/mod.rs

Resolves #11181, followup of #11114.
The canonical name is `UTF8` but PostgreSQL also accepts `utf-8` or even `u==!T>f?8`.
</details>

fix(frontend): tolerate special chars in encoding value

---

src/meta/src/hummock/manager/mod.rs

close https://github.com/risingwavelabs/risingwave/issues/10996
</details>

chore: enhance object storage error message when creating meta node

---

src/frontend/planner_test/tests/testdata/input/basic_query.yaml
src/frontend/planner_test/tests/testdata/output/basic_query.yaml
src/frontend/src/binder/delete.rs

Fix #10986
`WHERE` should be followed by a boolean expression. We used to only check `SELECT` but not `DELETE`.
related: #7325
</details>

fix(binder): enforce `WHERE` of `DELETE` to be `bool`

---

ci/workflows/main-cron.yml

Closes https://github.com/risingwavelabs/risingwave/issues/11217.
Can also be triggered via label `ci/upload-micro-benchmark`.
</details>

chore(ci): only upload microbench on `main`

---

src/storage/src/hummock/compactor/compaction_utils.rs
src/storage/src/hummock/compactor/compactor_runner.rs
src/storage/src/hummock/compactor/iterator.rs
src/storage/src/hummock/compactor/mod.rs

`estimate_state_for_compaction` should be after `generate_splits`, because the latter may modify `split` while the former depends on `split`.
</details>

fix(metric): fix estimated memory usage of compaction task

---

e2e_test/batch/catalog/pg_roles.slt.part
src/frontend/src/catalog/system_catalog/pg_catalog/pg_roles.rs

feat(catalog): add missing fields in pg_roles

---

src/frontend/src/catalog/system_catalog/information_schema/columns.rs
src/frontend/src/catalog/system_catalog/information_schema/mod.rs

feat(catalog): add missing fields in information_schema.columns

---

integration_tests/citus-cdc/cdc_check
integration_tests/citus-cdc/citus_prepare.sh
integration_tests/citus-cdc/citus_prepare.sql
integration_tests/citus-cdc/create_mv.sql
integration_tests/citus-cdc/create_source.sql
integration_tests/citus-cdc/docker-compose.yml
integration_tests/citus-cdc/query.sql
integration_tests/citus-cdc/worker-wait-for-manager.sh
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/SourceValidateHandler.java
src/frontend/src/handler/create_source.rs

- added an integration test for citus cdc
- fixed bugs
- close https://github.com/risingwavelabs/risingwave/issues/11183

test(citus-cdc): add integration test for citus cdc

---

docs/memory-profiling.md

Fix a link in a doc
</details>

feat(doc): Fix link in doc

---

Cargo.lock
Cargo.toml
e2e_test/batch/catalog/pg_postmaster_start_time.slt.part
src/common/src/util/runtime.rs
src/frontend/Cargo.toml
src/frontend/src/binder/expr/function.rs
src/utils/runtime/Cargo.toml
src/utils/runtime/src/lib.rs
src/utils/runtime/src/variables.rs
src/utils/variables/Cargo.toml
src/utils/variables/src/lib.rs

feat(catalog): support pg_postmaster_start_time()

---

ci/scripts/docker-hdfs.sh
docker/Dockerfile.hdfs

fix(docker): fix hdfs dockerfile

---

e2e_test/streaming/values.slt
src/frontend/planner_test/tests/testdata/output/basic_query.yaml
src/frontend/planner_test/tests/testdata/output/expr.yaml
src/frontend/src/optimizer/plan_node/stream_values.rs
src/stream/src/executor/values.rs

Fix #10879.
- ~~[ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the …

fix(values): fix pk indices and output watermark cols of StreamValues

---

src/common/src/array/stream_record.rs
src/frontend/src/optimizer/plan_node/logical_over_window.rs
src/stream/src/executor/aggregation/agg_group.rs
src/stream/src/executor/hash_agg.rs
src/stream/src/executor/simple_agg.rs

- Avoid row count cast from `i64` to `usize` directly, fixes #11216. This also fixes over window function call like `lag(x, -1)` and `lead(x, -1)`;
- Add some tracing log to help locate bug. …

fix(stream agg): avoid lossy row count cast to help locate possible bug

---

src/connector/src/aws_auth.rs

chore: refine error message for empty aws auth

---

src/batch/src/executor/sort_agg.rs
src/common/src/array/iterator.rs
src/common/src/array/mod.rs
src/common/src/hash/dispatcher.rs
src/common/src/hash/key_v2.rs
src/common/src/test_utils/rand_array.rs
src/common/src/types/macros.rs
src/common/src/types/mod.rs
src/common/src/types/ordered.rs
src/common/src/types/scalar_impl.rs
src/common/src/types/to_text.rs
src/common/src/util/sort_util.rs
src/expr/src/expr/value.rs
src/storage/src/filter_key_extractor.rs

**To reviewers: hide whitespaces when reviewing.**
Introduce the unified macro for the type system. All relationships between type terms in our system should be recorded in this macro.
https://github.com/risingwavelabs/risingwave/blob/fd98649808750f3c6638ade56f284bcb40206535/src/common/src/types/macros.rs#L15-L63
Previous `for_all_xx` is now a projection of this macro.
https://github.com/risingwavelabs/risingwave/blob/fd98649808750f3c6638ade56f284bcb40206535/src/common/src/types/macros.rs#L65-L82
Also, introduce several _magical_ (😄) `dispatch` macros. The outstanding part is that it can help us to bind some type …

refactor: unified macro for type system

---

Cargo.lock
src/connector/Cargo.toml
src/connector/src/sink/iceberg.rs
src/connector/src/sink/mod.rs
src/meta/src/stream/sink.rs
src/stream/src/executor/sink.rs
src/workspace-hack/Cargo.toml

related issue: #10642
This PR implement the init version of iceberg sink. The iceberg sink use [icelake](https://github.com/icelake-io/icelake).
I set the ICEBERG_SINK as "iceberg_v2". So it will not impact our original iceberg sink.
This PR only contain the init process for creating. 
- ~~[ ] My PR contains critical fixes that are necessary to be merged into the latest …

feat: support init version of iceberg sink

---

ci/workflows/main-cron.yml

https://github.com/risingwavelabs/risingwave/pull/11218
</details>

chore(ci): cherry pick only upload micro bench on `main` #11218

---

ci/workflows/pull-request.yml

All our adhoc ci commands are prefixed with `ci/run-workflow-name`. Previous we use `cpu_flamegraph` and `heap_flamegraph` to trigger the workflows. This just does a simple renaming.
</details>

chore(ci): add `ci/run-cpu-flamegraph`, `ci/run-heap-flamegraph` to trigger flamegraph gen

---

src/common/src/catalog/mod.rs
src/connector/src/parser/mod.rs
src/connector/src/source/manager.rs
src/frontend/src/catalog/mod.rs
src/frontend/src/handler/create_source.rs
src/frontend/src/optimizer/plan_node/logical_source.rs
src/frontend/src/optimizer/plan_node/mod.rs

reminded by https://github.com/risingwavelabs/risingwave/pull/11300
</details>

feat(binder): reserve column name prefix `_rw_`

---

.github/workflows/cherry-pick-to-release-branch.yml

chore: update cherry-pick github action

---

docs/memory-profiling.md

Add more contents about testing pipeline and Kubernetes environment.
Add more contents about testing pipeline and Kubernetes environment.
Preview: https://github.com/risingwavelabs/risingwave/blob/eric/improve-memory-profiling-docs/docs/memory-profiling.md
</details>

feat(docs): update memory-profiling.md

---

docker/Dockerfile.hdfs

feat(docker): support setting config map when packaging RisingWave with HDFS

---

ci/workflows/docker.yml

ci: fix docker workflow format

---

ci/scripts/connector-node-integration-test.sh
ci/workflows/pull-request.yml

ci: fix connector integration test script

---

dashboard/mock-server.js
dashboard/mock/fetch.sh
src/common/src/util/stream_graph_visitor.rs
src/meta/src/barrier/command.rs
src/meta/src/barrier/recovery.rs
src/meta/src/dashboard/mod.rs
src/meta/src/manager/catalog/database.rs
src/meta/src/manager/catalog/fragment.rs
src/meta/src/manager/catalog/mod.rs
src/meta/src/rpc/metrics.rs
src/meta/src/rpc/server.rs
src/meta/src/rpc/service/scale_service.rs
src/meta/src/rpc/service/stream_service.rs
src/meta/src/stream/scale.rs
src/meta/src/stream/source_manager.rs
src/meta/src/stream/stream_graph/fragment.rs

Part of #11335 . Avoid calling `list_table_fragments` everywhere, because this function will copy all `TableFragments`. The biggest overhead associated with this function is the metrics collection part.
Note that calling `get_fragment_read_guard` incorrectly can easily cause a deadlock, we need to introduce some other functions to replace the original call logic in the future.
- RisingWave …

refactor: avoid clone all table fragments everywhere

---

src/risedevtool/connector.toml

Seems like 3.9.0 is no longer available. Bumped to 3.9.3.
https://downloads.apache.org/maven/maven-3/
</details>

chore(connector): bump maven version + exit on failure for build script

---

src/common/src/config.rs
src/meta/src/rpc/ddl_controller.rs

Currently it will panicked in assertion: (https://github.com/risingwavelabs/risingwave/blob/ac7cb9a99ab2f489149aee20af3b713f53addf66/src/common/src/hash/consistent_hash/mapping.rs#L70)
1. use 256 instead if there are too many available parallel units exist.
2. limit config `default_parallelism` upper to 256.
- Other (please specify in the release note …

fix: fix panic when available parallel units number is larger than 256

---

ci/scripts/gen-flamegraph.sh

Now it gets cancelled. Not sure why. See if throttle events can help.
Edit: Throttle events help. See CI run.
</details>

chore(ci): throttle nexmark events for flamegraph gen

---

src/common/src/system_param/mod.rs

chore: improve error reporting for unrecognized system params

---

Cargo.lock

chore(deps): bump once_cell from 1.17.1 to 1.18.0

---

src/frontend/src/binder/expr/function.rs

Please see comments for the hack part.
</details>

feat(binder): hack {obj/col}_description for bytebase

---

ci/workflows/docker.yml
ci/workflows/main-cron.yml
ci/workflows/main.yml
ci/workflows/pull-request.yml

cherry pick 11345 11379 to v1.1
</details>

ci: cherry pick 11345 11379 to v1.1

---

src/rpc_client/src/meta_client.rs

fix: config max decoding message size for some meta clients

---

src/frontend/src/session.rs

Fix #11419
This is a quick fix hoping to be included in v1.1. Things to consider after this PR:
* Tests
* Wrap `Vec<Format>` in a newtype so that caller would not forget about `FormatIterator`
* Maybe better interface than the current `infer`
</details>

fix(pgwire): respond `Describe portal` with correct format codes

---

Cargo.lock
e2e_test/udf/udf.slt
src/batch/src/executor/hop_window.rs
src/expr/src/error.rs
src/expr/src/expr/test_utils.rs
src/expr/src/vector_op/arithmetic_op.rs
src/expr/src/vector_op/date_trunc.rs
src/expr/src/vector_op/encdec.rs
src/expr/src/vector_op/extract.rs
src/expr/src/vector_op/jsonb_info.rs
src/expr/src/vector_op/overlay.rs
src/expr/src/vector_op/split_part.rs
src/expr/src/vector_op/substr.rs
src/expr/src/vector_op/timestamptz.rs
src/expr/src/vector_op/trim_array.rs
src/frontend/src/optimizer/plan_node/generic/hop_window.rs
src/rpc_client/Cargo.toml
src/rpc_client/src/connector_client.rs
src/rpc_client/src/error.rs
src/rpc_client/src/lib.rs
src/rpc_client/src/meta_client.rs
src/stream/src/error.rs
src/stream/src/executor/error.rs
src/stream/src/executor/hop_window.rs
src/udf/Cargo.toml
src/udf/src/error.rs
src/udf/src/external.rs
src/udf/src/lib.rs

cherry-pick refactor(error): reduce error type size (#11275)

---

src/frontend/src/binder/expr/function.rs

feat(binder): add dummy pg_is_in_recovery

---

src/common/src/session_config/mod.rs

feat(config): accept yes/no,on/off,1/0 as bool config value

---

src/common/src/config.rs
src/config/example.toml
src/storage/benches/bench_compactor.rs
src/storage/benches/bench_multi_builder.rs
src/storage/src/hummock/sstable/builder.rs
src/storage/src/hummock/sstable/multi_builder.rs
src/storage/src/hummock/test_utils.rs
src/storage/src/opts.rs

cherry pick 11482 to v1.1-rc
close https://github.com/risingwavelabs/risingwave/issues/11494
</details>

chore(storage): cherry pick 11482 to v1.1-rc

---

src/meta/src/manager/cluster.rs

As title, also fix two minor issues:
1. only update ttl on success registration.
2. remove cached available parallelism units, which is error-prone. This also fixed pu extensions for existing compute nodes.
</details>

fix: ignore pu reduction when re-registering existent compute nodes

---

Cargo.lock
Cargo.toml

chore(release): update version to v1.1.0

---

ci/scripts/run-fuzz-test.sh

feat(ci): extract failing queries for fuzz-test

---

e2e_test/source/basic/kafka.slt
src/frontend/src/handler/create_table.rs

feat(binder): check source format for append only table

---

proto/stream_plan.proto
src/expr/benches/expr.rs
src/expr/src/expr/mod.rs
src/frontend/planner_test/tests/testdata/output/emit_on_window_close.yaml
src/frontend/planner_test/tests/testdata/output/generated_columns.yaml
src/frontend/planner_test/tests/testdata/output/nexmark.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml
src/frontend/planner_test/tests/testdata/output/watermark.yaml
src/frontend/planner_test/tests/testdata/output/window_join.yaml
src/frontend/src/expr/utils.rs
src/frontend/src/optimizer/plan_node/stream.rs
src/frontend/src/optimizer/plan_node/stream_project.rs
src/frontend/src/optimizer/plan_node/stream_project_set.rs
src/frontend/src/optimizer/plan_node/stream_watermark_filter.rs
src/frontend/src/optimizer/rule/stream/filter_with_now_to_join_rule.rs
src/meta/src/stream/test_fragmenter.rs
src/stream/src/executor/integration_tests.rs
src/stream/src/executor/project.rs
src/stream/src/from_proto/project.rs

Cherry picking https://github.com/risingwavelabs/risingwave/pull/11454 onto branch v1.1-rc
Fix #11524

feat(watermark): implicitly derive watermark for nondecreasing columns (`proctime`) (#11454)

---

Makefile.toml
ci/workflows/docker.yml
ci/workflows/integration-tests.yml
ci/workflows/main-cron.yml
ci/workflows/main.yml
ci/workflows/pull-request.yml
ci/workflows/sqlsmith-tests.yml

- change risedev kill to synchronous wait(fix #11519)
- add back retry for exit code 255
</details>

fix(ci): change risedev kill to synchronous wait && add back retry for exit code 255

---

src/frontend/planner_test/tests/testdata/input/subquery_expr_correlated.yaml
src/frontend/planner_test/tests/testdata/output/subquery_expr_correlated.yaml
src/frontend/src/optimizer/logical_optimization.rs
src/frontend/src/optimizer/plan_node/generic/top_n.rs
src/frontend/src/optimizer/plan_node/logical_topn.rs
src/frontend/src/optimizer/rule/apply_topn_transpose_rule.rs
src/frontend/src/optimizer/rule/mod.rs

chore(optimizer): cherry pick 11491 to v1 1 rc

---

src/utils/pgwire/src/pg_protocol.rs

fix(pgwire): ignore msg when encouter errror in extended protocol util sync

---

Makefile.toml
src/meta/src/rpc/server.rs

See https://github.com/risingwavelabs/risingwave/pull/11520/files#r1286632767
</details>

fix(ci): kill and wait for tmux sessions to shut down

---

ci/scripts/integration-tests.sh
ci/workflows/docker.yml
ci/workflows/integration-tests.yml
ci/workflows/main-cron.yml
ci/workflows/main.yml
ci/workflows/pull-request.yml
ci/workflows/sqlsmith-tests.yml

- CI EC2 AMI updated to amazon linux 2023, so need to update script.
- remove 255 retry, because 255 cancel(`cancel_on_build_failing: true`) is is set by ourselves, no necessary to retry.
</details>

fix(ci): update integration test script in linux 2023

---

Cargo.lock
ci/scripts/e2e-iceberg-sink-v2-test.sh
ci/workflows/main.yml
ci/workflows/pull-request.yml
e2e_test/sink/iceberg_sink_v2.slt
src/connector/Cargo.toml
src/connector/src/sink/iceberg.rs
src/connector/src/sink/mod.rs
src/meta/src/stream/sink.rs
src/stream/src/executor/sink.rs

support append only writer for now …

feat: support iceberg_v2 sink writer

---

src/frontend/src/binder/bind_param.rs
src/frontend/src/binder/mod.rs
src/frontend/src/handler/extended_handle.rs
src/frontend/src/handler/query.rs
src/frontend/src/session.rs
src/utils/pgwire/src/pg_message.rs
src/utils/pgwire/src/pg_protocol.rs
src/utils/pgwire/src/pg_server.rs

fix #11392
Fix two corner case missing in message process:
1. https://www.postgresql.org/docs/15/protocol-message-formats.html#:~:text=Placing%20a%20zero%20here%20is%20equivalent%20to%20leaving%20the%20type%20unspecified.
2. https://www.postgresql.org/docs/15/protocol-message-formats.html#:~:text=%2D1%20indicates%20a%20NULL%20parameter%20value.
- ~~[ ] My PR …

fix(pgwire): fix corner case processing in parse and bind msg

---

integration_tests/kinesis-s3-source/docker-compose.yml

Sometimes the `latest` image may cause:
```
Error response from daemon: manifest unknown 
```
Tested: https://buildkite.com/risingwavelabs/integration-tests/builds/223
</details>

fix(integration-test): fixed localstack image tag

---

docs/cpu-profiling.md
docs/memory-profiling.md
integration_tests/kinesis-s3-source/docker-compose.yml
proto/monitor_service.proto
src/compute/Cargo.toml
src/compute/src/memory_management/policy.rs
src/compute/src/rpc/service/monitor_service.rs
src/ctl/src/cmd_impl/profile.rs
src/ctl/src/lib.rs
src/rpc_client/src/compute_client.rs
src/storage/compactor/src/rpc.rs

- dump heap profile result with risedev.
</details>

feat(risectl): risectl heap dump

---

src/common/src/session_config/mod.rs

resolve #7556, after this, Superset can connect to Risingwave.
Although it still cannot fetch the info of a table due to #11567 
</details>

feat: support standard_conforming_strings parameter

---

src/common/common_service/src/observer_manager.rs
src/rpc_client/src/meta_client.rs

fix: config subscribe client decoding limit and add more logs

---

Cargo.lock
src/batch/Cargo.toml
src/cmd/Cargo.toml
src/cmd_all/Cargo.toml
src/common/src/config.rs
src/compute/Cargo.toml
src/compute/src/lib.rs
src/compute/src/memory_management/memory_manager.rs
src/compute/src/memory_management/mod.rs
src/compute/src/memory_management/policy.rs
src/compute/src/server.rs
src/config/example.toml
src/tests/simulation/Cargo.toml

feat: dump heap prof (#11164)

---

src/frontend/planner_test/tests/testdata/output/nexmark.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_source.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml
src/frontend/planner_test/tests/testdata/output/over_window_function.yaml
src/frontend/planner_test/tests/testdata/output/tpch.yaml
src/frontend/src/optimizer/plan_node/generic/top_n.rs
src/frontend/src/optimizer/plan_node/logical_topn.rs
src/frontend/src/optimizer/plan_node/stream_topn.rs
src/stream/src/from_proto/group_top_n.rs

close https://github.com/risingwavelabs/risingwave/issues/11602
</details>

fix(stream): add group key into stream group topN's stream key (#11587) to branch v1.1-rc

---

src/frontend/src/catalog/system_catalog/pg_catalog/pg_attribute.rs

feat: add atthasdef to pg_attribute

---

src/frontend/planner_test/tests/testdata/output/nexmark.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_source.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml
src/frontend/planner_test/tests/testdata/output/over_window_function.yaml
src/frontend/planner_test/tests/testdata/output/tpch.yaml
src/frontend/src/optimizer/plan_node/generic/top_n.rs
src/frontend/src/optimizer/plan_node/logical_topn.rs
src/frontend/src/optimizer/plan_node/stream_topn.rs
src/stream/src/executor/watermark_filter.rs
src/stream/src/from_proto/group_top_n.rs

fix(watermark): align watermark for idle input #11554 to v1.1

---

Cargo.lock
Cargo.toml

chore(release): update version to v1.1.1

---

src/frontend/src/binder/expr/function.rs

feat: add dummy system function pg_type_is_visible

---

Makefile.toml
src/meta/src/rpc/server.rs

fix(ci): kill and wait for tmux sessions to shut down (#11538)

---

Makefile.toml
ci/scripts/integration-tests.sh
ci/workflows/docker.yml
ci/workflows/integration-tests.yml
ci/workflows/main-cron.yml
ci/workflows/main.yml
ci/workflows/pull-request.yml
ci/workflows/sqlsmith-tests.yml

cherry-pick: 11436 11520

---

src/rpc_client/src/meta_client.rs

The use case is `risectl hummock list-version` may return a message of several tens of megabytes, which exceeds the default 4MB limit required by the new version of tonic.
</details>

chore: remove decoding message size limit from hummock rpc client

---

Makefile.toml
src/risedevtool/src/risectl_env.rs

Add the alias for convenience when developing.
```
./risedev d
./risedev psql -c "SELECT 1;"
```
</details>

feat(risedev): add psql command

---

src/frontend/src/catalog/system_catalog/pg_catalog/pg_index.rs

feat: add dummy indisprimary to pg_index

---

Cargo.lock
src/common/Cargo.toml
src/common/src/util/resource_util.rs

Multiple users reported 'err: "not a number'. This isn't helpful at all.
Also improve code style.
Note: I don't fully understand the logic, especially the "max", "min"... Just rewrite equivalently. 
closes #11040 
</details>

refactor: improve error logging for resource_util

---

src/stream/src/executor/backfill/no_shuffle_backfill.rs

Cherry pick https://github.com/risingwavelabs/risingwave/pull/11625.
Closes https://github.com/risingwavelabs/risingwave/issues/11631.
</details>

chore(stream): cherry pick #11625 into v1.1-rc

---

src/stream/src/executor/backfill/no_shuffle_backfill.rs

chore(stream): add assertion for backfill invariant

---

docs/developer-guide.md
src/tests/simulation/tests/integration_tests/README.md

doc(test): how to reproduce simulation integration tests results from ci

---

.github/labeler.yml
.github/pull_request_template.md

Remove the documentation categories, and level up the Release note section.
</details>

chore(doc): Improve the documentation section in the PR template

---

e2e_test/batch/basic/generate_subscripts.slt.part
proto/expr.proto
src/expr/src/table_function/generate_subscripts.rs
src/expr/src/table_function/mod.rs

feat: support generate_subscripts function

---

src/frontend/src/binder/expr/function.rs

feat: add dummy pg_get_constraintdef that returns NULL

---

.github/workflows/nightly-rust.yml

Helpful to know when it does not compile, so that we can fix it more easily. And we don't need to manually bisect for a regression.
</details>

ci: add a GHA to build with latest nightly rust

---

ci/workflows/main-cron.yml
ci/workflows/main.yml
ci/workflows/pull-request.yml

More unit tests added overtime -> ci will naturally timeout.
</details>

chore(ci): bump unit test timeouts

---

src/meta/src/rpc/server.rs

To adapt to tonic version upgrade.
</details>

chore(meta): tune hummock service message decoding size limit

---

.github/dependabot.yml

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
also add Group updates on Semantic Versioning
https://github.com/dependabot/dependabot-core/issues/7795
</details>

ci(dependabot): add grouped updates

---

src/rpc_client/src/compute_client.rs

chore(meta): tune monitor service client message decoding size limit

---

Cargo.lock
Cargo.toml
e2e_test/sink/iceberg_sink_v2.slt
src/connector/Cargo.toml
src/connector/src/sink/iceberg.rs
src/connector/src/sink/mod.rs

Closes #10642 #10643 
</details>

feat: Introduce iceberg coordinated committer

---

src/frontend/src/catalog/system_catalog/information_schema/columns.rs

- Fix DBT related issue https://github.com/risingwavelabs/dbt-risingwave/issues/8
</details>

fix(frontend): fix varchar data type for information schema columns

---

src/common/src/array/vis.rs
src/common/src/buffer/bitmap.rs

a part of https://github.com/risingwavelabs/risingwave/pull/11070, which wants to modify the Vis in place and avoid clone. And be safe to forbid change the length
</details>

feat(common): add VisMut

---

ci/Dockerfile
ci/build-ci-image.sh
ci/docker-compose.yml

ci: Upgrade ci image to install poetry

---

ci/scripts/docker-hdfs.sh
docker/Dockerfile.hdfs
docker/docker-compose-with-hdfs.yml
docker/hdfs_env.sh

feat(docker): support docker compose with hdfs

---

src/meta/src/hummock/manager/mod.rs
src/meta/src/rpc/metrics.rs
src/meta/src/rpc/server.rs
src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs

feat: show compaction group id in Materialized View Info panel in

---

src/common/src/config.rs
src/config/example.toml
src/meta/src/hummock/manager/compaction_group_manager.rs
src/meta/src/hummock/manager/mod.rs
src/meta/src/hummock/manager/tests.rs
src/meta/src/manager/env.rs
src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs

cherry-pick #11683 to v1.1-rc
</details>

fix(meta): cherry-pick #11683 to v1.1-rc

---

.github/dependabot.yml

Because current behavior of leading zeros are not good for rust. https://github.com/dependabot/dependabot-core/issues/7795#issuecomment-1677622707
e.g., https://github.com/risingwavelabs/risingwave/pull/11680
</details>

ci(dependabot): remove semver grouping

---

integration_tests/debezium-mysql/docker-compose.yml
integration_tests/debezium-postgres/docker-compose.yml
integration_tests/debezium-sqlserver/docker-compose.yml

fix(test): fix integration test debezium cases

---

ci/workflows/main-cron.yml
ci/workflows/main.yml
ci/workflows/pull-request.yml
src/tests/simulation/tests/integration_tests/main.rs
src/tests/simulation/tests/integration_tests/storage.rs

Related https://github.com/risingwavelabs/risingwave-test/issues/431. See backgroud there.
This is a very first version. I'll try to add more actions, such as triggering compaction and group splitting later.
</details>

feat(deterministic-test): add tests of random writes and consistency

---

Cargo.lock
Cargo.toml
src/connector/src/sink/iceberg.rs

Close #11702 #11652 
</details>

feat: Allow user to config iceberg table client.

---

src/rpc_client/src/connector_client.rs
src/rpc_client/src/meta_client.rs

Known issue after tonic upgrade. Now it hits connector grpc client. This PR remove the limit for connector and telemetry grpc client.
</details>

fix: remove decoding message size limit in telemetry and connector grpc client

---

src/frontend/planner_test/tests/testdata/input/subquery.yaml
src/frontend/planner_test/tests/testdata/output/subquery.yaml
src/frontend/src/optimizer/plan_visitor/cardinality_visitor.rs

- The `logical_pk` is empty() means there is no pk.
</details>

fix(optimizer): fix cardinality visitor -- filter

---

src/meta/src/hummock/manager/mod.rs
src/storage/src/hummock/compactor/mod.rs

chore(storage): remove log

---

src/batch/src/executor/insert.rs
src/ctl/src/cmd_impl/hummock/list_kv.rs
src/storage/hummock_test/benches/bench_hummock_iter.rs
src/storage/hummock_test/src/compactor_tests.rs
src/storage/hummock_test/src/failpoint_tests.rs
src/storage/hummock_test/src/hummock_storage_tests.rs
src/storage/hummock_test/src/state_store_tests.rs
src/storage/hummock_test/src/sync_point_tests.rs
src/storage/src/hummock/utils.rs
src/storage/src/table/batch_table/storage_table.rs
src/stream/src/common/table/state_table.rs

1. Easier to refactor `ReadOptions` to introduce new fields, without having to refactor all the instantiation sites.
2. Reduce noise from extra fields which are unimportant in that context.
</details>

refactor(storage): refactor read options instantiation to use `..Default::default()`

---

Cargo.lock
Cargo.toml

chore(release): update version to v1.1.3

---

Makefile.toml
src/cmd_all/src/README.md
src/cmd_all/src/bin/risingwave.rs
src/cmd_all/src/lib.rs
src/cmd_all/src/standalone.rs

`monolithic-mode` -> `standalone`.
And resolve https://github.com/risingwavelabs/risingwave/pull/11755#pullrequestreview-1583874325
</details>

chore(cmd_all): fix naming + remove hardcoded path

---

ci/workflows/main-cron.yml
ci/workflows/main.yml
ci/workflows/pull-request.yml
src/tests/simulation/tests/integration_tests/storage.rs

Now we have 4 deterministic integration test steps:
They use the same compiled binary but running with different filters. I think this is not necessary, and let's put them together to save EC2 instances.
By the way, the `TEST_NUM` is unified.
</details>

test: merge deterministic integration tests into one step

---

e2e_test/batch/basic/dml.slt.part
e2e_test/ddl/invalid_operation.slt
e2e_test/ddl/table/generated_columns.slt.part
proto/batch_plan.proto
src/batch/src/executor/delete.rs
src/batch/src/executor/update.rs
src/frontend/planner_test/tests/testdata/input/update.yaml
src/frontend/planner_test/tests/testdata/output/update.yaml
src/frontend/src/binder/delete.rs
src/frontend/src/binder/update.rs
src/frontend/src/catalog/table_catalog.rs
src/frontend/src/optimizer/plan_node/batch_update.rs
src/frontend/src/optimizer/plan_node/generic/update.rs
src/frontend/src/planner/delete.rs
src/frontend/src/planner/relation.rs
src/frontend/src/planner/update.rs
src/source/src/table.rs

It is just a temporal solution, we still need https://github.com/risingwavelabs/risingwave/issues/11738
close https://github.com/risingwavelabs/risingwave/issues/11708
close https://github.com/risingwavelabs/risingwave/issues/11692
</details>

feat(binder): allow dml on table with generated column

---

e2e_test/streaming/watermark.slt
src/stream/src/executor/watermark_filter.rs

- yield watermark
- don't check last committed watermark when idle.
</details>

fix(watermark): yield watermark when input is idle

---

e2e_test/streaming/watermark.slt

Resolve #11798 
Let's run CI for several times in the PR.
</details>

test(e2e): add flush for watermark test and skip the test for in memory cluster

---

src/common/common_service/src/tracing.rs
src/common/src/types/decimal.rs
src/expr/macro/src/parse.rs
src/expr/src/agg/string_agg.rs
src/expr/src/expr/expr_some_all.rs
src/frontend/src/binder/expr/function.rs
src/frontend/src/expr/type_inference/func.rs
src/frontend/src/handler/create_table.rs
src/frontend/src/optimizer/rule/push_calculation_of_join_rule.rs
src/frontend/src/utils/condition.rs
src/frontend/src/utils/with_options.rs
src/java_binding/src/lib.rs
src/stream/src/executor/backfill/no_shuffle_backfill.rs
src/stream/src/executor/over_window/delta_btree_map.rs
src/stream/src/executor/rearranged_chain.rs
src/tests/simulation/src/ctl_ext.rs

Latest rustfmt contains support for `let-else`. Part of #11809. Use a separate PR to make it smaller.
</details>

chore: fmt let-else

---

Makefile.toml
ci/Dockerfile
ci/build-ci-image.sh
ci/docker-compose.yml

fix(ci): sqllogictest error cause is not shown

---

ci/scripts/run-e2e-test.sh
src/storage/backup/integration_tests/test_set_config.sh

- Update expected value in assertion, to match modified display format in other earlier commit.
- Move ci-meta-backup-test to the last of e2e test, because his test is prone to failure due to changes in external dependencies.
</details>

fix(test): update expected value in assertion

---

src/common/src/util/value_encoding/column_aware_row_encoding.rs

The default value will incorrectly overwrite a contained `NULL` value.
</details>

fix(value_encoding): incorrect default value handling in column-aware encoding

---

src/frontend/src/handler/create_function.rs
src/tests/simulation/tests/integration_tests/sink/basic.rs

Related #10608 
Unspecified language is allowed here for external function, but we only allow `python` and `java` for named language. Otherwise, the backward compatibility may be broken easily while we add some native function engine.
</details>

fix(frontend/handler): forbid unknown language in function creation

---

src/storage/hummock_test/src/vacuum_tests.rs
src/storage/src/hummock/compactor/mod.rs
src/storage/src/hummock/vacuum.rs

refactor(compaction): extract reporting progress of vacuum task

---

e2e_test/iceberg/iceberg_sink_v2.slt
e2e_test/sink/iceberg_sink.slt
integration_tests/iceberg-sink/create_sink.sql
integration_tests/iceberg-sink2/python/init.py
java/connector-node/python-client/integration_tests.py
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/SinkUtils.java
src/connector/src/sink/iceberg.rs
src/connector/src/sink/remote.rs

Closes #11776.
`iceberg` sink now uses rust version.
`iceberg_java` sink still uses java version.
</details>

chore: Rename iceberg_v2 as iceberg

---

src/storage/hummock_test/src/vacuum_tests.rs
src/storage/src/hummock/compactor/mod.rs
src/storage/src/hummock/vacuum.rs

fix(compaction): report a log when vacuum task fails

---

src/connector/src/source/kinesis/source/reader.rs

chore: refine kinesis error & sleep when shard iter is None

---

src/meta/src/hummock/manager/mod.rs
src/meta/src/manager/catalog/mod.rs

close https://github.com/risingwavelabs/risingwave/issues/11825
</details>

fix(compaction): do not split creating table

---

src/connector/src/parser/json_parser.rs
src/connector/src/parser/unified/util.rs

fix(json parser): fill None when parse error

---

scripts/check/check-trailing-spaces.sh

Fixes #11448
- ~~[ ] All checks passed in `./risedev check` (or alias, `./risedev c`)~~
- ~~[ ] My PR contains critical fixes that are …

chore(check): `egrep` -> `grep -E`

---

ci/workflows/gen-flamegraph-cron.yml

Recently it has been timing out. Even if there's performance degradation, we don't want this job to fail, so we can still examine the generated flamegraph.
More queries were added as well which explains the longer run time.
https://buildkite.com/risingwavelabs/cpu-flamegraph-weekly-cron
</details>

chore(ci): bump flamegraph gen timeout

---

e2e_test/streaming/watermark.slt
src/frontend/src/handler/create_source.rs

Currently it will panic when watermark return data type does not match the watermark column type.
Now return an error in front end.
</details>

fix(watermark): return error when watermark return data type does not match the watermark column type

---

src/stream/src/executor/mod.rs

fix(watermark): correct data type in transform_with_expr

---

Cargo.lock
ci/scripts/check.sh
e2e_test/streaming/watermark.slt

fix(ci): make ci in v1.1 pass

---

java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/PostgresValidator.java
java/connector-node/risingwave-connector-service/src/main/resources/validate_sql.properties

Check whether postgres user is granted as `rds_superuser` or `rds_replication`;
</details>

fix(cdc): fix postgres privilege check for AWS RDS

---

e2e_test/streaming/watermark.slt
src/frontend/src/handler/create_source.rs

fix(watermark): cherry pick watermart ret check

---

Cargo.lock
scripts/source/prepare_ci_pubsub/Cargo.toml
src/connector/Cargo.toml
src/risedevtool/Cargo.toml

chore(deps): bump google-cloud apis and pubsub

---

docs/batch-local-execution-mode.md
docs/developer-guide.md
docs/memory-profiling.md
docs/multi-object-store.md
docs/state-store-overview.md
docs/streaming-overview.md
grafana/risingwave-dev-dashboard.dashboard.py
src/object_store/src/object/mod.rs
src/stream/src/executor/actor.rs
src/stream/src/executor/hash_join.rs

fix: change Chinese quotation marks into English

---

src/meta/src/hummock/manager/tests.rs
src/meta/src/hummock/metrics_utils.rs

Fix failed deterministic test.
</details>

fix(test): fix unclean metrics state in deterministic unit test

---

ci/scripts/run-e2e-test.sh
ci/scripts/standalone-utils.sh
ci/workflows/main-cron.yml

Wait for standalone cluster to restart. Otherwise test can be flaky https://buildkite.com/risingwavelabs/main-cron/builds/787#018a3375-0160-4e7d-b97c-6f6306c44322
</details>

fix(ci): wait for standalone cluster to restart

---

Cargo.lock
src/storage/Cargo.toml

chore: bump foyer

---

ci/scripts/e2e-test-parallel-in-memory.sh
risedev.yml
src/common/src/config.rs
src/config/ci-mem.toml
src/config/example.toml

This PR sets default visibility_mode to `checkpoint`. 
- We keep the cluster level `visibility_mode` as `Default`, which means to follow each frontend level `visibility_mode` setting.
- We changes frontend's `enable_barrier_read` to false, which is equivalent to set `visibility_mode` to `checkpoint`.
</details>

chore(config): set default visibility_mode to checkpoint for frontend

---

Cargo.lock
e2e_test/streaming/rate_limit.slt
proto/stream_plan.proto
src/common/src/session_config/mod.rs
src/frontend/src/optimizer/plan_node/stream_table_scan.rs
src/stream/Cargo.toml
src/stream/src/executor/flow_control.rs
src/stream/src/executor/mod.rs
src/stream/src/from_proto/chain.rs

Closes #11861 
Rate limit is disabled by default. Credit to @chenzl25 , used similar library and code for flow control as his PR: https://github.com/risingwavelabs/risingwave/pull/8300/files.
You may try it as follows, should take around 10s:
```sh
./risedev d
./risedev psql -c "
CREATE TABLE t(v1 int);
SET RW_STREAMING_RATE_LIMIT=2000;
CREATE MATERIALIZED VIEW m as SELECT * FROM t;
INSERT INTO t SELECT * FROM generate_series(1, 20000);
FLUSH;"
```
Without the rate limit takes around 3s.
```sh
./risedev d
./risedev psql -c "
CREATE TABLE t(v1 int);
CREATE MATERIALIZED VIEW m as SELECT * FROM t;
INSERT INTO t SELECT * …
```

feat(streaming): flow control executor

---

src/frontend/planner_test/tests/testdata/input/project_set.yaml
src/frontend/planner_test/tests/testdata/output/agg.yaml
src/frontend/planner_test/tests/testdata/output/project_set.yaml
src/frontend/src/binder/expr/function.rs
src/frontend/src/binder/expr/mod.rs

Fixes #11905
PostgreSQL also includes a hint:
```
HINT:  You might be able to move the set-returning function into a LATERAL FROM item.
```
We also supported `lateral` recently (despite not all syntax variations), but using it would not produce the desired behavior mentioned in issue. It just make the fact explicit that set-returning functions always execute before `case`/`coalesce`. Actually, behavior of multiple set-returning functions is [defined](https://www.postgresql.org/docs/15/xfunc-sql.html#XFUNC-SQL-FUNCTIONS-RETURNING-SET) by `lateral rows from`. …

fix(binder): disallow set-returning function in JoinOn/Having/Filter/Case/Coalesce as in PostgreSQL

---

docs/developer-guide.md
src/README.md

As per title.
Include 2 examples: `commit_meta!` and `#[aggregate]`.
</details>

doc: Understanding RisingWave Macros

---

Cargo.lock
Cargo.toml
src/common/Cargo.toml
src/common/src/array/arrow.rs
src/connector/Cargo.toml
src/expr/Cargo.toml
src/frontend/Cargo.toml
src/udf/Cargo.toml

Upgrade to latest icelake version for 1.2 relase.
</details>

chore: Upgrade icelake version

---

CODEOWNERS

After setting code owners for `Cargo.lock` file, we may turn on "Require review from Code Owners" in the GitHub repository settings. This is to prevent `Cargo.lock` from being accidentally changed, which may lead to confusion.
</details>

chore: add code owners for Cargo.lock

---

.github/workflows/doc.yml

fix(ci): fix rustdoc site

---

src/storage/src/hummock/compactor/mod.rs
src/storage/src/hummock/vacuum.rs

refactor(compaction): extract reporting full scan task logic

---

src/stream/src/common/log_store/kv_log_store/writer.rs

Work around #11864.
Because there is a flaw in storage supporting left-excluded or right-included delete range, this PR eliminates the only right-included use case in the system, to work around the issue temporarily.
As `serialize_truncation_offset_watermark` already calls `next_key`, simply change from `included` to `excluded` for right end is enough. …

refactor(log_store): make delete range end excluded

---

src/compute/tests/cdc_tests.rs
src/connector/src/source/mock_external_table.rs

fix(ci): fix unit test deterministic test

---

src/stream/src/common/builder.rs
src/stream/src/common/log_store/in_mem.rs
src/stream/src/executor/aggregation/agg_group.rs
src/stream/src/executor/dynamic_filter.rs
src/stream/src/executor/hash_agg.rs
src/stream/src/executor/hash_join.rs
src/stream/src/executor/hop_window.rs
src/stream/src/executor/lookup/impl_.rs
src/stream/src/executor/over_window/general.rs
src/stream/src/executor/project_set.rs
src/stream/src/executor/sink.rs
src/stream/src/executor/sort.rs
src/stream/src/executor/temporal_join.rs

Previously, the `StreamChunkBuilder` is over-designed for Join executors, now in this PR it's split to a general `StreamChunkBuilder` (used in Sort, HashAgg, OverWindow and DynamicFilter) and `JoinStreamChunkBuilder` (used in Join-related executors). `StreamChunkBuilder` is reused in the implementation of `JoinStreamChunkBuilder`.
- ~~[ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue …

refactor(stream common): split `StreamChunkBuilder` and `JoinStreamChunkBuilder`

---

src/batch/src/task/task_manager.rs
src/meta/src/hummock/manager/tests.rs
src/meta/src/hummock/test_utils.rs
src/meta/src/rpc/metrics.rs

Inject dedicated metric instance for tests that need assert metric values.
</details>

fix(test): fix test failure caused by shared metric instance

---

.github/workflows/cherry-pick-to-release-branch.yml

chore: cherry pick action for v1.2

---

README.md

Updated Doc and Cloud site links in README. I see there are references to these links in code and test cases. These will be updated in a separate PR. 
risingwave.dev -> docs.risingwave.com
risingwave.com/cloud -> cloud.risingwave.com
</details>

chore(doc): update doc site and cloud site links in README

---

src/batch/src/task/task_manager.rs

test: Remove busy loop tests

---

src/object_store/src/object/opendal_engine/opendal_object_store.rs

fix(storage): fix opendal object store error handle

---

scripts/check/check-trailing-spaces.sh

Time reduced from 10s to 0.4s on my machine. May fix #11457.
- ~~[ ] My PR contains critical fixes that are necessary to be merged into the …

chore(ci): optimize trailing space check

---

e2e_test/source/basic/kinesis.slt
src/connector/src/source/kinesis/enumerator/client.rs
src/connector/src/source/kinesis/source/reader.rs

fix: reject kinesis source if the start up mode is not sequence number but sequence number is provided

---

src/connector/src/source/kinesis/source/reader.rs

chore: refine error message on unhandled error in kinesis

---

Cargo.lock
Cargo.toml

chore: update version to 1.1.4

---

src/stream/src/from_proto/over_window.rs

Closes https://github.com/risingwavelabs/risingwave/issues/12095
</details>

fix(streaming): handle missing `cache_policy` field in `OverWindow`

---

Cargo.lock
proto/hummock.proto
src/storage/Cargo.toml
src/storage/src/hummock/compactor/mod.rs

chore(storage): remove compactor workload

---

ci/scripts/backwards-compat-test.sh

fix(ci): fix backwards compat with `ci-release` profile

---

src/sqlparser/src/parser.rs
src/sqlparser/tests/sqlparser_common.rs
src/sqlparser/tests/sqlparser_postgres.rs
src/sqlparser/tests/testdata/create.yaml
src/sqlparser/tests/testdata/select.yaml

fix(parser): more error reporting with locations

---

e2e_test/streaming/watermark.slt
src/stream/src/executor/sort_buffer.rs

- ~~[ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)
If …

fix(eowc): fix SortBuffer when there are multiple records having same timestamp

---

src/connector/src/common.rs
src/connector/src/source/nats/mod.rs

Add [multiple server url](https://docs.rs/async-nats/latest/async_nats/fn.connect.html#connect-with-vec-of-serveraddr) feature into nats, test it and work correctly in sink, source, source recovery.
Tips: When you test it, if your consumer client connect 2 url, when you publish message, your client also need to conenct 2 url. If not, for example your publisher client only conenct 1 url, (not related to risingwave) the consumer may or may not get message. …

feat(stream): add multiple server url feature into nats, delete useless field

---

src/object_store/src/object/opendal_engine/gcs.rs
src/object_store/src/object/opendal_engine/oss.rs

chore(object store): change streaming write buffer size to 16MB for gcs

---

ci/workflows/integration-tests.yml
integration_tests/mysql-sink/create_mv.sql

Fix the test case due to update of parsing logic of timestamptz: #12084 
Passed: https://buildkite.com/risingwavelabs/integration-tests/builds/271
</details>

fix: mysql-sink integration test

---

src/risedevtool/src/bin/risedev-dev.rs

fix(risedev): typo fixing

---

src/stream/src/executor/source/source_executor.rs

fix: temporarily remove the assert checking for split migration

---

.github/workflows/cherry-pick-to-release-branch.yml

chore: trigger cherry-pick when the label is added

---

e2e_test/schema_registry/pb.slt
src/connector/src/parser/avro/parser.rs
src/connector/src/parser/debezium/avro_parser.rs
src/connector/src/parser/json_parser.rs
src/connector/src/parser/protobuf/parser.rs
src/connector/src/parser/schema_registry/client.rs
src/connector/src/parser/schema_registry/util.rs

Cherry picking https://github.com/risingwavelabs/risingwave/pull/11982 onto branch v1.2-rc. Required by one of our users.

feat: HA for schema registry (#11982)

---

src/ctl/src/cmd_impl/hummock/validate_version.rs
src/ctl/src/lib.rs
src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
src/storage/hummock_sdk/src/lib.rs

feat: risectl hummock validate-version

---

risedev.yml

fix(risedev): Reset risedev.yml

---

Cargo.lock
Cargo.toml

chore: update version to 1.2.0

---

.github/workflows/nightly-rust.yml

https://github.com/risingwavelabs/risingwave/actions/workflows/nightly-rust.yml
</details>

ci: fix disk out of space for GHA

---

src/common/src/row/mod.rs

`impl<R1: Row, R2: Row> Row for either::Either<R1, R2>`
</details>

feat(common): impl `Row` for `Either`

---

proto/meta.proto
src/common/src/system_param/mod.rs
src/meta/src/manager/system_param/mod.rs

We can hardly do anything for deprecated system parameters, so just print a warning.
Context: https://github.com/risingwavelabs/risingwave/pull/12156#discussion_r1319666704
Resolves #12196
Resolves #11382 
</details>

refactor: ignore unrecogized/deprecated system params

---

Cargo.lock
Cargo.toml
src/connector/src/sink/kafka.rs
src/workspace-hack/Cargo.toml

Fix https://github.com/risingwavelabs/risingwave/issues/12256
Fix increased latency after upgrading to v1.2
</details>

fix: cherry-pick #12013 to branch v1.2-rc

---

e2e_test/streaming/eowc/eowc_select.slt

Add SLT test for
```
select tm, foo from t emit on window close;
```
Expect the rows to be emitted in their timestamp order.
I'll update the [document](https://docs.risingwave.com/docs/current/emit-on-window-close/) after it merges.
</details>

test: add an slt test for select with eowc

---

Cargo.lock
src/connector/Cargo.toml

There was a update in [jsonschema-transpiler](https://github.com/mozilla/jsonschema-transpiler) which would fix #11951. 
</details>

chore: bump `jsonschema-transpiler` version

---

ci/scripts/regress-test.sh

fix(ci): fix regress test download of `locales`

---

src/frontend/planner_test/tests/testdata/input/lateral_subquery.yaml
src/frontend/planner_test/tests/testdata/output/lateral_subquery.yaml
src/frontend/src/optimizer/plan_node/generic/scan.rs
src/frontend/src/optimizer/plan_node/logical_scan.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/12298
</details>

fix(optimizer): relax scan predicate pull up mapping inverse restriction

---

src/meta/src/hummock/compaction/level_selector.rs
src/meta/src/hummock/compaction/mod.rs
src/meta/src/hummock/compaction/picker/base_level_compaction_picker.rs
src/meta/src/hummock/compaction/picker/compaction_task_validator.rs
src/meta/src/hummock/compaction/picker/manual_compaction_picker.rs
src/meta/src/hummock/compaction/picker/min_overlap_compaction_picker.rs
src/meta/src/hummock/compaction/picker/mod.rs
src/meta/src/hummock/compaction/picker/space_reclaim_compaction_picker.rs
src/meta/src/hummock/compaction/picker/tier_compaction_picker.rs
src/meta/src/hummock/compaction/picker/tombstone_reclaim_compaction_picker.rs
src/meta/src/hummock/compaction/picker/trivial_move_compaction_picker.rs
src/meta/src/hummock/compaction/picker/ttl_reclaim_compaction_picker.rs

cherry-pick-5a8866d
</details>

refactor(storage): cherry-pick v1.2rc seperate validator logic from picker (#11984)

---

.config/hakari.toml
Cargo.lock
src/workspace-hack/Cargo.toml

fix(ci): exclude tikv-jemalloc-sys in hakari check

---

src/expr/src/vector_op/regexp.rs

As titled, `start` should be greater than 0.
As an example, will panic under below case.
</details>

fix(regexp): substraction overflow when incorrectly speicifying `start`

---

src/rpc_client/src/meta_client.rs

4MB preset limit was reached when I tried list table in risectl.
</details>

chore: lift decoding message size limit for ddl client

---

src/frontend/planner_test/tests/testdata/input/subquery_expr.yaml
src/frontend/planner_test/tests/testdata/output/subquery_expr.yaml
src/frontend/src/binder/query.rs

- Before this PR, sql order by clauses referring to correlated columns would cause a panic. This PR fix this issue.
- Resolve https://github.com/risingwavelabs/risingwave/issues/11807.
</details>

feat(optimizer): support correlated column in order by

---

src/connector/src/sink/kafka.rs

fix: handle kafka sink message timeout error

---

src/connector/src/lib.rs
src/connector/src/sink/formatter/append_only.rs
src/connector/src/sink/formatter/mod.rs
src/connector/src/sink/formatter/upsert.rs
src/connector/src/sink/kafka.rs
src/connector/src/sink/kinesis.rs
src/connector/src/sink/mod.rs
src/connector/src/sink/utils.rs

Part B of #12125 targeting #11995 (earlier parts: #12264):
* Introduce trait `SinkFormatter` and its implementations `AppendOnlyFormatter` and `UpsertFormatter`
* Introduce `FormattedSink` and implement it for kafka and kinesis
In later parts:
* refactor debezium to `SinkFormatter`
* onboard nats to `FormattedSink`
* refactor concrete formatter construction based on sink params. …

refactor(sink): impl SinkFormatter for AppendOnly and Upsert

---

src/sqlparser/src/ast/statement.rs

fix https://github.com/risingwavelabs/risingwave/issues/12370
```SQL
dev=> create table s1 (vi int)  with (
connector = 'datagen',
) ROW FORMAT JSON;
CREATE_TABLE
dev=> select definition from rw_catalog.rw_tables;
definition                               
-----------------------------------------------------------------------
CREATE TABLE s1 (vi INT) WITH (connector = 'datagen') ROW FORMAT JSON
(1 row)
``` …

fix: fix source schema display

---

src/expr/src/expr/expr_udf.rs
src/udf/src/error.rs
src/udf/src/external.rs

refactor(udf): connect lazily to get rid of `block_in_place`

---

src/meta/src/hummock/manager/mod.rs

Previously, when compute node call `rpc ListVersionDeltas` to fetch version updates, `HummockManager` in meta node reads meta store (e.g. use etcd if enabled) but not its memory data structures. This PR fix the problem.
</details>

fix: hummock manager list version deltas by memory

---

src/compute/src/rpc/service/stream_service.rs
src/stream/src/task/stream_manager.rs

- use the first barrier current epoch as the initial watermark epoch.
</details>

fix: give more reasonable initial watermark epoch

---

src/common/src/array/compact_chunk.rs
src/common/src/array/stream_chunk.rs
src/stream/src/executor/sink.rs

different kinds of sinks have handed the visibility in stream chunks. 
</details>

feat(sink): do not compact chunk's vis in sink

---

src/meta/src/manager/catalog/database.rs
src/meta/src/rpc/service/notification_service.rs

`StreamJobStatus` field will default to `uninitialized` on old cluster. So we should filter for it as well.
Caught in recent main-cron backwards compatibility test.
</details>

fix(meta): fix backwards compat issues for `Table::stream_job_status` field

---

ci/scripts/run-backfill-tests.sh
ci/scripts/sql/backfill/insert.sql
ci/scripts/sql/backfill/insert_recurse.sql
ci/scripts/sql/backfill/insert_seed.sql
ci/workflows/main-cron.yml
ci/workflows/pull-request.yml

Simplify the tests. Make it easier to adjust snapshot size as well. Using the recursive way is not really ergonomic when we have `generate_series`.
</details>

refactor(test): simplify backfill tests

---

Cargo.lock
Cargo.toml
src/workspace-hack/Cargo.toml

[CHANGELOG](https://github.com/sfackler/rust-postgres/blob/c5ff8cfd86e897b7c197f52684a37a4f17cecb75/tokio-postgres/CHANGELOG.md)
</details>

chore(deps): update tokio-postgres to v0.7.10

---

Cargo.lock
Cargo.toml
e2e_test/iceberg/iceberg_sink_v2.slt
src/connector/src/sink/iceberg.rs

See https://buildkite.com/risingwavelabs/main-cron/builds/861#018aaf19-2ac2-4d4f-9331-40f910d0c36d
</details>

fix(ci): iceberg sink test failure

---

ci/scripts/run-e2e-test.sh
e2e_test/background_ddl/basic.slt

Just skip it in standalone mode. Seems like ddl progress cannot be produced under heavy workload in standalone mode. We can skip it for now. Tracked in https://github.com/risingwavelabs/risingwave/issues/12445
</details>

fix(ci): fix standalone e2e test breakage

---

src/common/src/array/arrow.rs
src/common/src/array/stream_chunk.rs
src/connector/src/sink/clickhouse.rs
src/connector/src/sink/remote.rs
src/connector/src/sink/utils.rs

after https://github.com/risingwavelabs/risingwave/pull/12428
fix https://github.com/risingwavelabs/risingwave/issues/12460
</details>

fix(sink): handle visibility in remote sink

---

e2e_test/streaming/watermark.slt
src/stream/src/executor/backfill/no_shuffle_backfill.rs
src/stream/src/executor/watermark_filter.rs
src/stream/src/from_proto/chain.rs
src/stream/src/from_proto/watermark_filter.rs

refactor(watermark): avoid sending min watermark

---

e2e_test/ddl/table/generated_columns.slt.part
src/frontend/src/handler/create_table.rs

fix(generated_column): correct the output message when use impure expr in generated columns.

---

ci/docker-compose.yml
ci/scripts/e2e-pulsar-sink-test.sh
ci/workflows/main-cron.yml
ci/workflows/pull-request.yml
e2e_test/sink/pulsar_sink.slt
risedev.yml

Implement e2e pulsar sink test.
</details>

test(sink): add e2e test for pulsar-sink

---

dashboard/components/BackPressureTable.tsx
dashboard/components/FragmentGraph.tsx
dashboard/components/metrics.tsx
src/meta/src/dashboard/prometheus.rs

Show streaming back-pressure in fragment level. Based on #12353. 
Resolves #12345
</details>

refactor(dashboard): show backpressure in fragment level

---

src/meta/src/hummock/compaction/picker/base_level_compaction_picker.rs
src/meta/src/hummock/compaction/picker/compaction_task_validator.rs

cherry-pick v1.2rc fix condition of compaction task validator
close https://github.com/risingwavelabs/risingwave/issues/12519
</details>

fix(storage): cherry-pick v1.2rc fix condition of compaction task validator (#12473)

---

src/frontend/src/catalog/system_catalog/rw_catalog/rw_hummock_version.rs

Remove key range from `rw_catalog.rw_hummock_current_version` and `rw_catalog.rw_hummock_checkpoint_version`.
We rely on other method to analyze key range anyway.
</details>

refactor(frontend): don't expose key range in rw_hummock_*_version

---

src/rpc_client/src/compactor_client.rs
src/storage/compactor/src/server.rs

feat(serverless compaction): add retry strategy for grpc proxy client

---

src/meta/src/hummock/metrics_utils.rs

fix(metric): fix metric for branched sst info

---

proto/backup_service.proto
src/ctl/src/cmd_impl/meta/backup_meta.rs
src/meta/src/backup_restore/backup_manager.rs
src/meta/src/rpc/service/backup_service.rs
src/rpc_client/src/meta_client.rs

Previously the backup-meta RPC doesn't return detailed error message. We have to check it via meta node's log. It's inconvenient for debugging.
This PR records the latest backup job info and exposes it to RPC client.
</details>

refactor(backup): refine error message

---

src/connector/src/parser/debezium/mongo_json_parser.rs
src/connector/src/parser/unified/debezium.rs

chore: fix typo: MongoProjection

---

src/stream/src/executor/over_window/over_partition.rs

chore(over window): make some logs trace level

---

src/compute/src/lib.rs
src/meta/src/lib.rs
src/storage/compactor/src/lib.rs

Refine server start log to reduce misleading.
</details>

chore: refine start log

---

src/expr/impl/src/scalar/tumble.rs

fix(expr): return error when get_window_start_with_offset overflows

---

src/object_store/src/object/mod.rs

chore: update error message of object storage

---

src/connector/src/sink/kafka.rs

feat(sink): await on kafka delivery future on QueueFull

---

Makefile.toml

- Since those connector RPCs depending on the Rust dynamic library have been replaced by JNI. We can disable dynamic library building to speed up connector node compile time in development.
```
before:
[INFO] java-binding ....................................... SUCCESS [02:09 min]
now:
[INFO] java-binding ....................................... SUCCESS [  1.057 s]
``` …

chore(connector): no-build-rust

---

src/storage/backup/integration_tests/common.sh

Test failed because the risectl output changes.
</details>

fix(test): fix meta recovery test

---

e2e_test/sink/pulsar_sink.slt

Add some delay, it takes a while for records to be sinked into RW.
</details>

fix(ci): fix pulsar tests

---

src/connector/src/source/kinesis/source/reader.rs

Fix: https://github.com/risingwavelabs/risingwave/issues/12589 
</details>

chore: display AWS kensis error details

---

.github/dependabot.yml

chore: ignore semver-patch in dependabot

---

ci/scripts/run-e2e-test.sh

chore(ci): enable basic background_ddl test in standalone mode

---

Makefile.toml
ci/scripts/run-e2e-test.sh
ci/scripts/standalone-utils.sh
risedev.yml
src/cmd_all/scripts/e2e-full-standalone-demo.sh
src/cmd_all/scripts/standalone-demo-dev.sh
src/cmd_all/scripts/standalone-demo-full.sh
src/cmd_all/src/standalone.rs

Closes https://github.com/risingwavelabs/risingwave/issues/12382
</details>

feat(standalone): add compactor

---

ci/scripts/run-e2e-test.sh
ci/scripts/standalone-utils.sh
ci/workflows/pull-request.yml
risedev.yml
src/cmd_all/src/common.rs
src/cmd_all/src/standalone.rs

closes https://github.com/risingwavelabs/risingwave/issues/12383
</details>

feat(standalone): support optionally including components

---

src/meta/src/barrier/progress.rs

After #12355 we also report collated rows for actors which are done. So we need to handle the offset accordingly, to avoid double counting rows.
</details>

fix(meta): handle case where progress is done

---

proto/stream_plan.proto
src/common/src/session_config/mod.rs
src/frontend/src/optimizer/plan_node/stream_table_scan.rs
src/stream/src/executor/backfill/no_shuffle_backfill.rs
src/stream/src/from_proto/chain.rs

feat(stream): support snapshot read over N barriers

---

src/object_store/src/object/s3.rs

feat(object storage): add is_https_endpoint for minio

---

.github/workflows/doc.yml

chore: fix "No space left" for GHA

---

Cargo.lock
Cargo.toml
ci/scripts/e2e-iceberg-sink-v2-test.sh
e2e_test/iceberg/test_case/partition_append_only.toml
e2e_test/iceberg/test_case/partition_upsert.toml
src/connector/src/sink/iceberg.rs

- ~~[ ] My PR needs documentation updates. (Please use …

feat: support iceberg sink partition write

---

src/storage/src/hummock/block_cache.rs
src/storage/src/hummock/store/version.rs

feat: enable verbose instrument for iter rewind and block I/O

---

src/meta/src/hummock/manager/mod.rs

Introduce the `compact_task::TaskType::Tombstone` to `auto_pick_type` so that the compact tasks of type TaskType::Tombstone can be triggered  by `PullTask` Event.
</details>

fix(storage): auto_pick_type should cover Tombstone type

---

ci/scripts/check.sh

chore: speedup doctest

---

docs/developer-guide.md

fix(doc): fix debian-like installation guide

---

.github/workflows/cherry-pick-to-release-branch.yml

chore: update cherry pick action version

---

README.md

Update the Slack workspace links in readme.
</details>

chore: Update Slack link in README.md

---

README.md

Update the Slack again to a permanent one, so that we won't need to update it again when it expires.
</details>

chore: Update Slack link to a permanent one in README

---

Cargo.lock
src/common/Cargo.toml
src/common/src/heap_profiling/mod.rs
src/common/src/heap_profiling/profiler.rs
src/compute/src/memory_management/memory_manager.rs
src/compute/src/memory_management/mod.rs
src/compute/src/memory_management/policy.rs
src/compute/src/server.rs
src/storage/compactor/src/lib.rs
src/storage/compactor/src/server.rs

- use background heap profiling and enable auto dump for compute and compactor
</details>

refactor(heap_profiling): use background heap profiling and enable auto dump for compute and compactor

---

e2e_test/batch/aggregate/with_over_window.slt.part
e2e_test/over_window/generated/batch/create.slt.part
e2e_test/over_window/generated/batch/drop.slt.part
e2e_test/over_window/generated/batch/mod.slt.part
e2e_test/over_window/generated/streaming/create.slt.part
e2e_test/over_window/generated/streaming/drop.slt.part
e2e_test/over_window/generated/streaming/mod.slt.part
e2e_test/over_window/templates/create.slt.part
e2e_test/over_window/templates/drop.slt.part
e2e_test/over_window/templates/mod.slt.part
src/frontend/planner_test/tests/testdata/input/agg.yaml
src/frontend/planner_test/tests/testdata/output/agg.yaml
src/frontend/src/optimizer/plan_node/logical_agg.rs

Cherry picking https://github.com/risingwavelabs/risingwave/pull/12551 onto branch v1.3-rc

fix(over window): fix error in using aggregate function result as win… (#12551)

---

src/stream/src/executor/backfill/no_shuffle_backfill.rs

Patch https://github.com/risingwavelabs/risingwave/pull/12654/files into #12644 
</details>

chore: patch  #12654

---

ci/scripts/s3-source-test.sh
ci/workflows/main-cron.yml
e2e_test/s3/fs_source_v2.py
proto/stream_plan.proto

Add e2e test for s3_v2 source.
</details>

test(sink): add e2e test for s3_v2 source

---

src/meta/src/hummock/manager/mod.rs

revert(storage): auto_pick_type should cover Tombstone type
</details>

fix(storage): auto_pick_type should cover Tombstone type - Revert

---

src/meta/src/rpc/ddl_controller.rs

- Drop source should drop streaming jobs if it is in cascade mode.
</details>

fix(meta): fix drop source cascade

---

e2e_test/batch/functions/cast.slt.part
src/frontend/src/binder/expr/function.rs

feat: support cast function `date`

---

src/meta/src/hummock/manager/mod.rs

Due to the bug in tombstone compaction, we revert it.
</details>

fix: Revert "fix(storage): auto_pick_type should cover Tombstone type (#12670)

---

src/stream/src/executor/source/fetch_executor.rs
src/stream/src/executor/source/state_table_handler.rs

Refactor fetch executor.
</details>

fix(source): refactor fetch executor

---

src/stream/src/executor/managed_state/join/mod.rs
src/stream/src/executor/monitor/streaming_stats.rs

chore(metrics): fix executor cache miss ratio metrics

---

src/connector/src/source/base.rs
src/meta/src/stream/source_manager.rs

open scale switch for kinesis and other connectors remain no scale in
</details>

fix: allow scale in for kinesis

---

src/connector/src/sink/kafka.rs

resolve https://github.com/risingwavelabs/risingwave/issues/12365
support kafka sink auto creating topic if the topic not exists
ref https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md
add new props `properties.allow.auto.create.topics` for kafka sink only
this field is optional and the default value sets to `false` according to the …

feat: allow kafka auto creating topics by `properties.allow.auto.create.topics`

---

ci/scripts/backfill-test.sh
ci/scripts/run-backfill-tests.sh
src/stream/src/executor/backfill/no_shuffle_backfill.rs

As per title. Only when 1 snapshot read pass, we will permit barrier to pass. This is so we don't lose tombstone iteration progress for that epoch.
</details>

fix(streaming): stall barrier until at least 1 snapshot read passed

---

e2e_test/batch/basic/generate_series.slt.part
e2e_test/batch/basic/range.slt.part
src/expr/impl/src/table_function/generate_series.rs

fix https://github.com/risingwavelabs/risingwave/issues/10820
</details>

fix(expr): reject inf/-inf/nan decimal in generate_series and range

---

src/connector/src/common.rs

According to the [nats docs](https://docs.nats.io/nats-concepts/jetstream/streams), stream != subject. Each stream can include several subjects. In previous implementation, we use the nats subject name as the stream name. But actually we should provide a field named stream and then assign stream name in config. 
Also, in nats jetstream stream creation, it can accept multiple subjects, but we only support one subject before. So we should provide this feature.  …

fix(connector): add nats stream field, and change subject into several input

---

proto/hummock.proto
src/ctl/src/cmd_impl/hummock/compaction_group.rs
src/ctl/src/lib.rs
src/meta/src/hummock/compaction/mod.rs
src/meta/src/hummock/compaction/picker/tombstone_reclaim_compaction_picker.rs
src/meta/src/hummock/compaction/selector/tombstone_compaction_selector.rs
src/meta/src/hummock/manager/compaction_group_manager.rs
src/meta/src/hummock/manager/mod.rs
src/storage/src/hummock/compactor/compactor_runner.rs

1. fix endless loop 
2. fix max_compact_bytes config of tombstone picker
3. fix tombstone picker auto trigger
</details>

fix(storage): fix tombstone picker

---

ci/scripts/release.sh
docker/Dockerfile
docker/Dockerfile.hdfs

- Related issue https://github.com/risingwavelabs/risingwave/issues/12090
</details>

chore(docker): connector node no-build-rust for docker

---

src/connector/src/sink/iceberg.rs

~~- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).~~
~~- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)~~
~~- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)~~ …

fix: fix empty ops case in iceberg sink

---

proto/stream_plan.proto
src/common/src/session_config/mod.rs
src/frontend/src/optimizer/plan_node/stream_table_scan.rs
src/stream/src/executor/backfill/no_shuffle_backfill.rs
src/stream/src/from_proto/chain.rs

It is no longer needed after https://github.com/risingwavelabs/risingwave/pull/12780
</details>

chore(streaming): deprecate `BACKFILL_SNAPSHOT_BARRIER_INTERVAL`

---

src/common/src/config.rs
src/common/src/telemetry/mod.rs
src/common/src/util/resource_util.rs
src/compute/src/lib.rs
src/jni_core/src/jvm_runtime.rs
src/meta/src/lib.rs
src/storage/compactor/src/server.rs

We strongly recommend users to specify memory limit according to their actual use cases. However, when `total_memory_bytes` is absent anyway, to avoid OOM, it's better to use a proportion of total system memory instead of all.
As a reference, Redis's `maxmemory` is set to 80% of a data node's available memory. While RisingWave has more components than Redis, 70% seems a reasonable number.
Also renamed `total_memory_available_bytes` to `system_memory_available_bytes` to avoid ambiguity. …

refactor(memory): use 0.7 * system memory as default `total_memory_bytes`

---

docs/developer-guide.md
src/cmd_all/src/README.md

doc(cmd_all): add docs on standalone mode

---

src/connector/src/sink/remote.rs

- Related issue https://github.com/risingwavelabs/risingwave/issues/12090.
</details>

fix(connector): add connector sink metric back

---

src/connector/src/sink/formatter/append_only.rs
src/connector/src/sink/formatter/mod.rs
src/connector/src/sink/kafka.rs
src/connector/src/sink/kinesis.rs

See https://github.com/risingwavelabs/risingwave/issues/9443#issuecomment-1759072979
Kafka and Pulsar both allow key to be optional. They would use round-robin without key.
https://kafka.apache.org/documentation/#producerconfigs_partitioner.class
https://pulsar.apache.org/docs/3.1.x/concepts-messaging/#routing-modes
Kinesis marks the key as required. There is no builtin support for round-robin.
https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecord.html#Streams-PutRecord-request-PartitionKey …

fix(sink): append-only without `primary_key` should not partition by dummy `{}` key

---

src/tests/sqlsmith/src/sql_gen/functions.rs
src/tests/sqlsmith/src/sql_gen/types.rs

We cannot generate `decode` in a general way, since it's second argument (the format string) needs to be one of: "hex", "base64", "escape".
This caused the recent sqlsmith-generate-snapshot workflow to fail: https://buildkite.com/risingwavelabs/generate-sqlsmith-snapshots-weekly/builds/125#018b35f6-3b94-4efe-853e-07589d68a48d
</details>

fix(sqlsmith): fix generation of decode

---

src/frontend/planner_test/tests/testdata/input/union.yaml
src/frontend/planner_test/tests/testdata/output/share.yaml
src/frontend/planner_test/tests/testdata/output/union.yaml
src/frontend/planner_test/tests/testdata/output/watermark.yaml
src/frontend/src/optimizer/plan_node/generic/union.rs
src/frontend/src/optimizer/plan_node/logical_union.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/11851
</details>

feat(optimizer): improve union stream key

---

src/meta/src/hummock/compaction/picker/space_reclaim_compaction_picker.rs
src/meta/src/hummock/compaction/picker/tombstone_reclaim_compaction_picker.rs
src/meta/src/hummock/compaction/picker/ttl_reclaim_compaction_picker.rs
src/meta/src/hummock/compaction/selector/tombstone_compaction_selector.rs
src/meta/src/hummock/compaction/selector/ttl_selector.rs
src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs

fix(meta): do not select several file

---

src/compute/src/rpc/service/exchange_metrics.rs
src/compute/src/rpc/service/exchange_service.rs
src/stream/src/executor/exchange/input.rs
src/stream/src/executor/monitor/streaming_stats.rs

chore(streaming): remove unused metrics

---

src/storage/src/monitor/hummock_state_store_metrics.rs
src/storage/src/monitor/monitored_storage_metrics.rs

chore(storage): reduce state store metrics report bucket

---

src/meta/src/hummock/compaction/picker/space_reclaim_compaction_picker.rs
src/meta/src/hummock/compaction/picker/tombstone_reclaim_compaction_picker.rs
src/meta/src/hummock/compaction/picker/ttl_reclaim_compaction_picker.rs
src/meta/src/hummock/compaction/selector/tombstone_compaction_selector.rs
src/meta/src/hummock/compaction/selector/ttl_selector.rs
src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs

fix(meta): do not select several file (#12869)

---

proto/meta.proto
src/frontend/src/catalog/system_catalog/rw_catalog/rw_fragments.rs
src/meta/src/rpc/service/stream_service.rs

Resolve #12841 .
add column `parallelism` in system table `rw_fragments`.

feat: add parallelism column in rw_fragments

---

src/common/src/config.rs
src/config/example.toml

chore: disable fast compaction by default

---

integration_tests/scripts/check_data.py

- Refactor `check_mv` function in `check_data.py` to return a boolean instead of using an assertion
- Introduce a list to store failed test cases in `check_data.py`
- Add functionality to add failed test cases to the list in `check_data.py`
- Throw an exception with a message containing the failed test cases if any exist in `check_data.py`
</details>

chore: run all data check even some fail

---

e2e_test/batch/subquery/tab_completion.slt.part
src/frontend/src/optimizer/plan_visitor/cardinality_visitor.rs

fix: fix tab completion for relation

---

ci/scripts/run-micro-benchmarks.sh
ci/workflows/pull-request.yml

Only upload results on m6i instance. Performance fluctuates between m5 and m6, with m6 being high performance instance. As a result our microbenchmark pipeline fluctuates, giving false regressions. Now we just upload records for m6.
Thanks to @cyliu0 's investigation.
</details>

fix(ci): stabilize microbenchmark

---

e2e_test/batch/functions/greatest_least.slt.part
proto/expr.proto
src/expr/impl/src/scalar/cmp.rs
src/expr/impl/tests/sig.rs
src/frontend/src/binder/expr/function.rs
src/frontend/src/expr/pure.rs
src/frontend/src/expr/type_inference/func.rs

cherry-pick https://github.com/risingwavelabs/risingwave/pull/12838 to v1.3
</details>

refactor: cherry pick #12838 to v1.3-rc to support greatest and least function

---

e2e_test/s3/fs_source_v2.py
src/connector/src/source/filesystem/nd_streaming.rs

Refer to https://github.com/risingwavelabs/risingwave/issues/12786.
Fix offset miscounting in `src/connector/src/source/filesystem/nd_streaming.rs`.
</details>

fix(connector): offset miscounting in nd_streaming

---

src/meta/src/hummock/manager/mod.rs
src/object_store/src/object/s3.rs

close https://github.com/risingwavelabs/risingwave/issues/12778
</details>

feat(s3): ban new cluster startup if s3 bucket has retention configured

---

Cargo.lock
Cargo.toml

chore: update version to 1.3.0

---

src/compute/src/memory_management/mod.rs

cherry pick #12941
close #12945 
</details>

chore: cherry-pick #12941 (fix: don't count file cache buffer pool size if disabled)

---

src/frontend/src/expr/expr_visitor.rs
src/frontend/src/expr/mod.rs
src/frontend/src/expr/order_by_expr.rs
src/frontend/src/expr/pure.rs
src/frontend/src/expr/utils.rs
src/frontend/src/optimizer/plan_expr_visitor/expr_counter.rs
src/frontend/src/optimizer/plan_expr_visitor/input_ref_counter.rs
src/frontend/src/optimizer/plan_node/logical_over_window.rs
src/frontend/src/optimizer/plan_node/logical_scan.rs
src/frontend/src/optimizer/plan_visitor/input_ref_validator.rs
src/frontend/src/optimizer/plan_visitor/plan_correlated_id_finder.rs
src/frontend/src/optimizer/rule/index_selection_rule.rs
src/frontend/src/optimizer/rule/rewrite_like_expr_rule.rs
src/frontend/src/utils/condition.rs

refactor(frontend/expr): use associated type for ExprVisitor design

---

src/connector/src/parser/avro/parser.rs
src/connector/src/parser/debezium/avro_parser.rs
src/connector/src/parser/protobuf/parser.rs
src/connector/src/parser/schema_registry/mod.rs

Just minor code style tweaks around `get_subject_by_strategy`:
* Key and value handling are separated ([doc](https://docs.confluent.io/platform/current/schema-registry/fundamentals/serdes-develop/index.html#configuration-details)).
* Clarify the fact that key encode cannot be protobuf.
* Clarify the fact that debezium avro is hardcoded to TopicNameStrategy.
* We may be able to extend it to other strategies, but better paired with tests in a dedicated PR, rather than this refactor.
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release …

refactor(source): cleanup schema registry name strategy handling

---

src/meta/src/model_v2/migration/src/m20230908_072257_init.rs

fix: fix table object foreign key in init migration

---

src/frontend/src/optimizer/plan_rewriter/share_source_rewriter.rs
src/frontend/src/optimizer/plan_visitor/cardinality_visitor.rs
src/frontend/src/optimizer/plan_visitor/execution_mode_decider.rs
src/frontend/src/optimizer/plan_visitor/input_ref_validator.rs
src/frontend/src/optimizer/plan_visitor/max_one_row_visitor.rs
src/frontend/src/optimizer/plan_visitor/mod.rs
src/frontend/src/optimizer/plan_visitor/plan_correlated_id_finder.rs
src/frontend/src/optimizer/plan_visitor/relation_collector_visitor.rs
src/frontend/src/optimizer/plan_visitor/share_parent_counter.rs
src/frontend/src/optimizer/plan_visitor/side_effect_visitor.rs
src/frontend/src/optimizer/plan_visitor/sys_table_visitor.rs
src/frontend/src/optimizer/plan_visitor/temporal_join_validator.rs

refactor(optimizer): refactor plan visitor with associated type

---

.github/workflows/nightly-rust.yml

ci: use fixed branch for nightly rust action

---

src/batch/src/task/task_execution.rs

Fixes #12815: `Debug` contains the stacktrace, but `Display` does not.
</details>

fix(batch): do not send stacktrace to frontend on error

---

.github/ISSUE_TEMPLATE/config.yml
CONTRIBUTING.md
README.md
docs/developer-guide.md

refactor(readme): make the readme doc more user friendly

---

README.md

chore: beautify readme.

---

docker/docker-compose.yml

chore: upgrade the docker image version

---

ci/docker-compose.yml
ci/scripts/e2e-kafka-sink-test.sh
ci/scripts/e2e-sink-test.sh
e2e_test/sink/kafka/create_sink.slt
e2e_test/sink/kafka/protobuf.slt
risedev.yml

ci(sink): as source, start kafka with docker-compose rather than risedev

---

Cargo.lock
src/common/src/util/future_utils.rs
src/common/src/util/mod.rs
src/connector/src/sink/remote.rs
src/jni_core/Cargo.toml
src/jni_core/src/lib.rs
src/rpc_client/src/lib.rs

Implement a RemoteLogSinker, which is basically a copy of the `LogSinkerOf<impl SinkWriter>`, except that when polling the next item from log reader, it will also poll the error of the response stream. When the response stream gets an error, it will return with error immediately. The same mechanism is used in the methods remote sink writer to detect the error from response stream as soon as possible.
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting …

feat(sink): monitor error in remote sink response stream

---

src/batch/src/executor/source.rs
src/common/src/util/chunk_coalesce.rs

fix(batch): avoid empty chunk in source executor

---

README.md
src/connector/src/common.rs
src/connector/src/source/nats/mod.rs
src/connector/src/source/nats/source/reader.rs

1. change `stream` filed into optional, in source, we require nats jetstream, the stream is required. But in sink, we support nats, then stream can be empty. So we change `stream` into optional and add check logic in source code.
2. Nats require no `.` in consumer name, we add replace logic in code to avoid this situation happend.
</details>

fix(nats-connector): change stream into optional string, add replace stream name logic

---

src/meta/model_v2/migration/src/m20230908_072257_init.rs
src/meta/model_v2/src/table.rs
src/meta/src/controller/catalog.rs

Related #12849 , support sql version comment function in catalog controller.
</details>

feat: implement comment function in catalog controller

---

Cargo.lock

https://github.com/risingwavelabs/risingwave/security/dependabot/107
https://github.com/risingwavelabs/risingwave/security/dependabot/110
</details>

chore(deps): bump rustix 0.37.23 to 0.37.26 reported by dependabot alerts

---

Cargo.lock
src/tests/e2e_extended_mode/Cargo.toml
src/tests/simulation/Cargo.toml

We need https://github.com/madsim-rs/madsim/pull/175
</details>

chore(deps): bump madsim-tokio to 0.2.24

---

e2e_test/ddl/show.slt
e2e_test/extended_mode/basic.slt
src/frontend/src/utils/infer_stmt_row_desc.rs

feat: fix missing column description in row desc for show columns command

---

src/stream/src/executor/flow_control.rs

Otherwise it will flood the stdout in ci, because stdout is not captured.
</details>

chore(stream): change `FlowControlExecutor` to print WARN logs in `madsim`

---

README.md

Add docker info in README.md

---

Cargo.lock
Cargo.toml

* Bump reqsign, related https://github.com/Xuanwo/reqsign/pull/374
* Remove patches introduced in #12992 
</details>

chore(deps): bump reqsign to 0.14.3 and remove patches

---

src/tests/sqlsmith/src/sql_gen/types.rs

Internal agg not meant to be user-facing.
</details>

chore(test): ban `AggKind::InternalLastSeenValue` for sqlsmith

---

ci/workflows/main-cron.yml

Add `ci/main-cron/skip-ci` for `main-cron` as well. It can be used to debug and fix `main-cron` tests.
Rather than reuse `ci/skip-ci` for both `pull-request` and `main-cron` workflows, we add `ci/main-cron/skip-ci`.
`ci/skip-ci` will skip pull-request tests, but all of them should be run before merging. So it should only be used for draft PRs.
On the other hand, `ci/main-cron/skip-ci` can be used to run some main-cron tests relevant to the PR. Not all `main-cron` tests must be run before merging a PR. We can just select those we want to test, e.g. failing steps and their dependencies. …

chore(ci): add skip-ci for `main-cron`

---

.git-blame-ignore-revs

chore: ignore let-chains fmt in git blame

---

src/common/src/metrics/guarded_metrics.rs
src/common/src/metrics/relabeled_metric.rs
src/storage/src/monitor/hummock_state_store_metrics.rs
src/storage/src/monitor/local_metrics.rs

Previously for some local metrics in storage, it is created by `LabelGuardedMetrics::with_label_values(...).local()`. We only guard on the metric returned from `with_label_values`, but the local metric returned from `local` is not guarded, and the guarded metric is dropped immediately, which causes the loss of metrics reported in local metrics.
In this PR we also guard the local metrics returned from `local`. …

fix(metrics): guard label of local metrics

---

src/stream/benches/stream_hash_agg.rs

fix #13181
This line is needed to ensure functions are linked to the binary.
```rust
risingwave_expr_impl::enable!();
```
</details>

fix: `hash_agg` bench

---

src/connector/src/sink/remote.rs

Currently in the validate of remote sink, it call jni method in a blocking way, which will block the tokio worker and affect other tasks. In this PR, we move the logic of calling validate jni method to a separate thread via spawn_blocking to fix the issue.
</details>

fix(sink): spawn blocking in remote validation

---

Cargo.lock

fix https://github.com/risingwavelabs/risingwave/security/dependabot/107
</details>

chore: bump rustix 0.38.11->0.38.21

---

src/frontend/planner_test/tests/testdata/input/subquery_expr.yaml
src/frontend/planner_test/tests/testdata/output/cse_expr.yaml
src/frontend/planner_test/tests/testdata/output/explain.yaml
src/frontend/planner_test/tests/testdata/output/expr.yaml
src/frontend/planner_test/tests/testdata/output/subquery_expr.yaml
src/frontend/planner_test/tests/testdata/output/with_ordinality.yaml
src/frontend/src/optimizer/logical_optimization.rs
src/frontend/src/optimizer/plan_visitor/plan_correlated_id_finder.rs
src/frontend/src/optimizer/rule/mod.rs
src/frontend/src/optimizer/rule/values_extract_project_rule.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/12231
- Support `ValueExtractProjectRule` to extract CorrelatedInputRef from values so that we can unnest it.
</details>

feat(optimizer): support value extract project rule

---

src/meta/src/hummock/manager/mod.rs
src/meta/src/hummock/manager/versioning.rs
src/storage/src/hummock/write_limiter.rs

Fix https://github.com/risingwavelabs/risingwave/issues/12610#issuecomment-1790470589
</details>

chore: suppress storage log on back-pressure

---

.github/workflows/cherry-pick-to-release-branch.yml

chore: update cherry pick action

---

Cargo.lock
src/jni_core/Cargo.toml
src/jni_core/src/jvm_runtime.rs
src/jni_core/src/macros.rs

refactor(jni): refactor and add doc and expect_test for jni macro

---

Cargo.lock
Cargo.toml
src/connector/src/sink/iceberg.rs

fix: update icelake upsert query

---

src/cmd_all/src/standalone.rs
src/meta/node/src/lib.rs

chore(standalone): pass `prometheus_listener_addr` to meta

---

CODEOWNERS

chore: remove CODEOWNERS in the release branch

---

Makefile.toml

build(tools): bump cargo-udeps

---

backwards-compat-tests/scripts/run_local.sh
backwards-compat-tests/scripts/utils.sh
ci/scripts/backwards-compat-test.sh

Thanks to @lmatz for pointing this out.
</details>

chore(ci): use release branch rather than release candidate branch for backwards compat tests

---

docker/docker-compose-standalone.yml

need https://github.com/risingwavelabs/risingwave/issues/13235 to integrate it into the test pipeline later
</details>

chore: miss a double quote in the command of docker-compose-standalone.yml

---

src/cmd_all/src/standalone.rs
src/meta/node/src/lib.rs

chore(standalone): pass prometheus_listener_addr to meta (#13236) 

---

src/common/src/session_config/mod.rs

Just add session variable first. No actual arrangement backfill support in frontend yet.
Incrementally opening changes from https://github.com/risingwavelabs/risingwave/pull/10400
</details>

chore: add session variable to enable / disable arrangement backfill

---

src/expr/impl/src/scalar/overlay.rs

fix(expr): fix `overlay` function with large range input

---

src/connector/src/sink/remote.rs
src/connector/src/source/cdc/enumerator/mod.rs
src/connector/src/source/cdc/source/reader.rs
src/jni_core/src/jvm_runtime.rs
src/jni_core/src/lib.rs
src/jni_core/src/macros.rs

Previously, we call java methods from rust by passing the class name and signature string together with a list of `JValue` enum method parameters to `call_static_method` and we cast the return `JValue` to a concrete type, which is trouble some and may accidentally use the wrong type.
In this PR, we provide a macro `call_static_method`. When we use this macro, we should provide the method signature. The macro will parse the signature to get the method name, parameter list and return type. Later when it calls the `call_static_method` method, It will generate the jni signature automatically, and it will cast the parameter …

feat(jni): implement macro to type safe call java method

---

src/stream/src/executor/agg_common.rs
src/stream/src/executor/aggregation/mod.rs
src/stream/src/executor/hash_agg.rs
src/stream/src/executor/integration_tests.rs
src/stream/src/executor/simple_agg.rs
src/stream/src/executor/stateless_simple_agg.rs
src/stream/src/executor/test_utils.rs
src/stream/src/from_proto/hash_agg.rs
src/stream/src/from_proto/simple_agg.rs
src/stream/src/from_proto/stateless_simple_agg.rs

As mentioned in #13292, some of our streaming executors are not using `schema` passed in by frontend through protobuf, instead they infer output schemas by themselve. This is very error-prone. This PR fix this issue for streaming Agg executors which means `HashAggExecutor`, `SimpleAggExecutor` and `StatelessSimpleAggExecutor`.
To summarize the changes:
1. `generate_agg_schema` becomes a test utility. `XxxExecutor::new`s don't rely on it any more.
2. `info: ExecutorInfo` field is added to `AggExecutorArgs`, which `XxxExecutor::new`s should use as `Executor::schema()` output. …

fix(stream agg): use executor schema derived by optimizer instead of generating again in agg executors

---

ci/scripts/integration-tests.sh

fix specify risingwave image tag env

fix(ci): fix specify risingwave image tag env

---

ci/scripts/pulsar-source-test.sh

we test pulsar with both astra streaming and stream native. 
It seems the stream native part run out of free credits and I think it is ok to disable it.
</details>

chore(test): skip test with vendor because of invalid auth

---

src/connector/src/sink/iceberg.rs
src/connector/with_options.yaml

fix: ignore unknow field in config

---

src/expr/impl/src/scalar/array_contain.rs
src/frontend/planner_test/tests/testdata/input/array.yaml
src/frontend/planner_test/tests/testdata/output/array.yaml
src/frontend/src/expr/type_inference/func.rs

fix: array contains does not support nested types

---

src/meta/src/hummock/manager/mod.rs
src/storage/hummock_sdk/src/compact.rs
src/storage/src/hummock/compactor/compactor_runner.rs

as title
close #13312 
</details>

fix(storage): Handle heartbeat cancel in fast compactor runner

---

docs/developer-guide.md

Migrate docs for ci labels from notion
</details>

docs: add quick reference for ci labels

---

Cargo.lock
Cargo.toml
docker/docker-compose.yml

chore: update version to 1.4.0

---

src/stream/src/executor/integration_tests.rs
src/stream/src/executor/project.rs
src/stream/src/executor/project_set.rs
src/stream/src/from_proto/project.rs
src/stream/src/from_proto/project_set.rs
src/stream/src/task/stream_manager.rs
src/stream/tests/integration_tests/project_set.rs

This is part of the executor info consistency work https://github.com/risingwavelabs/risingwave/issues/13292.
Summary:
- Add `info: ExecutorInfo` field to `ExecutorParams`, deprecate `schema`, `pk_indices` and `identity` (will finally be removed soon).
- Use `params.info` in `Project` and `ProjectSet` executors.
</details>

refactor(stream): use `ExecutorInfo` constructed by stream manager in `Project` and `ProjectSet`

---

src/meta/src/manager/cluster.rs

fix(meta): collect meta node count as worker node

---

src/compute/tests/cdc_tests.rs
src/stream/src/executor/backfill/cdc/cdc_backfill.rs
src/stream/src/executor/backfill/no_shuffle_backfill.rs
src/stream/src/executor/chain.rs
src/stream/src/executor/flow_control.rs
src/stream/src/executor/rearranged_chain.rs
src/stream/src/from_proto/mod.rs
src/stream/src/from_proto/source/trad_source.rs
src/stream/src/from_proto/stream_scan.rs

This is part of the executor info consistency work https://github.com/risingwavelabs/risingwave/issues/13292.
Summary:
- Directly use `ExecutorParams::info` added in #13342 instead of deriving `schema` in `ChainExecutorBuilder`.
- Clarify the naming of `table schema` and `schema`, `table pk` and executor `pk_indices` in `ChainExecutorBuilder::new_boxed_executor`.
- Rename `ChainExecutorBuilder` to `StreamScanExecutorBuilder`, which seems to be forgotten in #13242. …

refactor: use `ExecutorParams::info` in stream scan executors

---

e2e_test/background_ddl/basic.slt
src/meta/src/barrier/mod.rs
src/meta/src/barrier/progress.rs

Closes https://github.com/risingwavelabs/risingwave/issues/12971.
As per title, instead of waiting for first barrier, immediately report progress. Thanks @BugenZhao for suggestion.
</details>

feat(meta): report background_ddl progress immediately

---

Cargo.lock

https://rustsec.org/advisories/RUSTSEC-2023-0070
</details>

chore(deps): bump self_cell for RUSTSEC-2023-0070

---

src/meta/src/hummock/manager/mod.rs
src/object_store/src/object/s3.rs

fix(s3): more accurate expiration judgment when starting the cluster

---

src/stream/src/executor/over_window/eowc.rs
src/stream/src/executor/over_window/general.rs
src/stream/src/executor/top_n/group_top_n.rs
src/stream/src/executor/top_n/group_top_n_appendonly.rs
src/stream/src/executor/top_n/top_n_appendonly.rs
src/stream/src/executor/top_n/top_n_plain.rs
src/stream/src/executor/top_n/utils.rs
src/stream/src/from_proto/eowc_over_window.rs
src/stream/src/from_proto/group_top_n.rs
src/stream/src/from_proto/over_window.rs
src/stream/src/from_proto/top_n.rs
src/stream/tests/integration_tests/eowc_over_window.rs
src/stream/tests/integration_tests/over_window.rs

This is part of the executor info consistency work https://github.com/risingwavelabs/risingwave/issues/13292.
Summary:
- Directly use `params.info` for `GroupTopN`, `TopN`, `OverWindow`, `EowcOverWindow` executors.
</details>

refactor(stream): use `ExecutorParams::info` in over window related executors

---

src/connector/src/parser/plain_parser.rs
src/frontend/planner_test/tests/testdata/output/create_source.yaml
src/frontend/planner_test/tests/testdata/output/emit_on_window_close.yaml
src/frontend/planner_test/tests/testdata/output/explain.yaml
src/frontend/planner_test/tests/testdata/output/generated_columns.yaml
src/frontend/planner_test/tests/testdata/output/watermark.yaml
src/frontend/src/handler/create_source.rs

fix #13378 
This is just a quick fix. Later we will implement `_rw_key` for encode json and csv.
</details>

fix(conn): fix throw error msg of connector when encode Json or Csv

---

docker/docker-compose-standalone.yml
docker/docker-compose.yml

chore: update image version in docker

---

src/compute/tests/integration_tests.rs
src/stream/src/executor/dml.rs
src/stream/src/executor/row_id_gen.rs
src/stream/src/executor/source/fetch_executor.rs
src/stream/src/executor/source/fs_source_executor.rs
src/stream/src/executor/source/list_executor.rs
src/stream/src/executor/source/source_executor.rs
src/stream/src/from_proto/dml.rs
src/stream/src/from_proto/row_id_gen.rs
src/stream/src/from_proto/source/fs_fetch.rs
src/stream/src/from_proto/source/trad_source.rs

This is part of the executor info consistency work https://github.com/risingwavelabs/risingwave/issues/13292.
Summary:
- Directly use `params.info` for source, `Dml` and `RowIdGen` executors.
</details>

refactor(stream): use `ExecutorParams::info` in source-related executors

---

e2e_test/ddl/alter_owner.slt
src/frontend/src/handler/alter_owner.rs
src/meta/src/manager/catalog/mod.rs
src/meta/src/manager/catalog/user.rs
src/meta/src/rpc/ddl_controller.rs

Related #13216 . We should automatically alter owner for related internal tables, indexes and associated sources. In postgreSQL, the indexes will be changed automatically as well. Refer: https://www.postgresql.org/docs/current/sql-alterindex.html
```
There was formerly an ALTER INDEX OWNER variant, but this is now ignored (with a warning). An index cannot have an owner different from its table's owner. Changing the table's owner automatically changes the index as well.
```
Besides, this PR also fixed a bug for user reference initialization in user manager. …

fix: alter owner automatically for internal table, index and associated source

---

ci/scripts/e2e-source-test.sh
e2e_test/source/cdc/cdc.share_stream.slt
e2e_test/source/cdc/cdc_share_stream_drop.slt
src/frontend/src/handler/create_table.rs
src/meta/src/manager/catalog/mod.rs

- record dependence in `table.dependent_relations` for table-on-source
- drop internal tables correctly
</details>

fix(cdc): fix drop source for cdc source job

---

src/object_store/src/object/s3.rs

fix(object store): make lifecycle expiration rule more reasonable

---

src/meta/src/controller/catalog.rs

chore: add some unit test for alter relation rename in catalog controller

---

e2e_test/udf/udf.slt

https://buildkite.com/risingwavelabs/pull-request/builds/35493#018bd259-edad-457d-b942-c0b7750da7a5
https://buildkite.com/risingwavelabs/main-cron/builds/1145#018bd497-97ba-40ad-a399-14061e812201
https://buildkite.com/risingwavelabs/pull-request/builds/35520#018bd659-bf73-4594-b997-e78579d1a390
</details>

fix(test): missing rowsort in udf.slt

---

src/frontend/planner_test/tests/testdata/output/cse_expr.yaml
src/frontend/planner_test/tests/testdata/output/explain.yaml
src/frontend/src/optimizer/logical_optimization.rs

- Related https://github.com/risingwavelabs/risingwave/issues/13459
</details>

fix(optimizer): skip subquery optimization if no apply

---

e2e_test/streaming/group_top_n/main.slt

fix https://github.com/risingwavelabs/risingwave/issues/13461
https://github.com/risingwavelabs/risingwave/issues/13461#issuecomment-1814171982
</details>

fix(test): fix non deterministic group topn test

---

src/frontend/planner_test/tests/testdata/output/cse_expr.yaml
src/frontend/planner_test/tests/testdata/output/explain.yaml
src/frontend/planner_test/tests/testdata/output/expr.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_source.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml
src/frontend/planner_test/tests/testdata/output/share.yaml
src/frontend/src/optimizer/logical_optimization.rs
src/frontend/src/optimizer/optimizer_context.rs

- Related issue https://github.com/risingwavelabs/risingwave/issues/13459
- Reduces `predicate_pushdown` frontend CPU from 4.85% to 1.95% under the sysbench benchmark.
</details>

feat(optimizer): avoid predicate pushdown for batch queries if unnecessary

---

src/frontend/planner_test/tests/testdata/input/create_source.yaml
src/frontend/planner_test/tests/testdata/output/create_source.yaml
src/frontend/src/handler/create_index.rs
src/frontend/src/handler/create_table.rs
src/frontend/src/optimizer/plan_node/generic/cdc_scan.rs
src/frontend/src/optimizer/plan_node/generic/mod.rs
src/frontend/src/optimizer/plan_node/generic/scan.rs
src/frontend/src/optimizer/plan_node/logical_cdc_scan.rs
src/frontend/src/optimizer/plan_node/logical_scan.rs
src/frontend/src/optimizer/plan_node/mod.rs
src/frontend/src/optimizer/plan_node/stream_cdc_table_scan.rs
src/frontend/src/optimizer/rule/index_selection_rule.rs
src/frontend/src/planner/relation.rs
src/frontend/src/scheduler/distributed/query.rs

Part of https://github.com/risingwavelabs/risingwave/issues/13146.
Later we can also rename `Scan` to `RwTableScan` to make the distinction clearer.
</details>

refactor: separate `CdcScan` from `Scan` in `logical` and `core`

---

README.md

Updated version from 1.3.0 to 1.4.0, and used the all-in-one binary package instead of the common one. 
</details>

chore: version update and typo fixes in readme

---

src/common/src/telemetry/mod.rs

`system_memory_available_bytes` returns total memory available. Maybe we should just remove `SystemData::Memory::available`?
</details>

fix(telemetry): fix memory stats

---

src/meta/src/hummock/compaction/picker/min_overlap_compaction_picker.rs

https://github.com/risingwavelabs/risingwave/issues/11746
This pr minimizes the probability of exceptions by lowering the priority of unexpected programs.
</details>

fix(storage): avoid select unexpected sub level count

---

dashboard/next.config.js
src/cmd_all/src/standalone.rs
src/meta/node/src/lib.rs
src/meta/node/src/server.rs
src/meta/src/dashboard/mod.rs
src/meta/src/dashboard/prometheus.rs
src/meta/src/manager/env.rs

Support specifying additional selector in the PromQL queried by Meta dashboard, which is useful when using a shared Prometheus.
Tested locally. 
</details>

feat(dashboard): support specifying additional selector in PromQL

---

proto/stream_plan.proto
src/common/src/util/stream_graph_visitor.rs
src/frontend/src/optimizer/plan_node/stream_cdc_table_scan.rs
src/frontend/src/optimizer/plan_node/stream_table_scan.rs
src/frontend/src/stream_fragmenter/mod.rs
src/frontend/src/utils/stream_graph_formatter.rs
src/meta/service/src/ddl_service.rs
src/meta/src/model/stream.rs
src/meta/src/stream/stream_graph/actor.rs
src/meta/src/stream/stream_graph/fragment.rs
src/stream/src/from_proto/mod.rs
src/stream/src/from_proto/stream_cdc_scan.rs
src/stream/src/from_proto/stream_scan.rs
src/stream/src/task/stream_manager.rs

Refactors:
- Add a new proto definition for cdc scan. `StreamCdcScan`.
- Refactor `from_proto` to add `stream_cdc_scan`.
- Refactor frontend to build `StreamCdcScan` rather than `StreamScan`.
- Deprecate old fields from `StreamScan` specific to cdc.
- Refactor `meta` for cdc scan specific things.
Breaks create table with cdc source. It is fine because it is …

refactor(proto): use separate proto for cdc scan

---

README.md

Add a diagram showing real-time data pipelines without and with RisingWave.
</details>

chore: add a diagram to README.md

---

dashboard/components/Layout.tsx
dashboard/components/Relations.tsx
dashboard/pages/api/streaming.ts
dashboard/pages/sources.tsx
dashboard/pages/views.tsx
src/meta/src/dashboard/mod.rs

feat(dashboard): add a new panel: views

---

src/meta/src/barrier/mod.rs
src/meta/src/hummock/manager/mod.rs
src/meta/src/hummock/manager/tests.rs
src/meta/src/hummock/mock_hummock_meta_client.rs
src/meta/src/hummock/test_utils.rs

As titled.
Part of https://github.com/risingwavelabs/risingwave/pull/13429
</details>

refactor(meta): merge commit_epoch parameter to a struct

---

src/storage/hummock_test/benches/bench_hummock_iter.rs
src/storage/hummock_test/src/bin/replay/replay_impl.rs
src/storage/hummock_test/src/compactor_tests.rs
src/storage/hummock_test/src/failpoint_tests.rs
src/storage/hummock_test/src/hummock_read_version_tests.rs
src/storage/hummock_test/src/hummock_storage_tests.rs
src/storage/hummock_test/src/snapshot_tests.rs
src/storage/hummock_test/src/state_store_tests.rs
src/storage/hummock_test/src/sync_point_tests.rs
src/storage/hummock_trace/src/collector.rs
src/storage/hummock_trace/src/opts.rs
src/storage/hummock_trace/src/record.rs
src/storage/hummock_trace/src/replay/mod.rs
src/storage/hummock_trace/src/replay/worker.rs
src/storage/src/hummock/event_handler/hummock_event_handler.rs
src/storage/src/hummock/event_handler/mod.rs
src/storage/src/hummock/store/local_hummock_storage.rs
src/storage/src/mem_table.rs
src/storage/src/monitor/monitored_store.rs
src/storage/src/monitor/traced_store.rs
src/storage/src/panic_store.rs
src/storage/src/store.rs
src/storage/src/store_impl.rs
src/stream/src/common/log_store_impl/kv_log_store/writer.rs
src/stream/src/common/table/state_table.rs
src/tests/compaction_test/src/delete_range_runner.rs

Part of https://github.com/risingwavelabs/risingwave/pull/13429
Add an empty `SealCurrentEpochOptions` to the `seal_current_epoch` method of local state store for future development.
</details>

refactor(storage): add options for seal_current_epoch

---

src/frontend/planner_test/tests/testdata/input/subquery_expr.yaml
src/frontend/planner_test/tests/testdata/output/subquery_expr.yaml
src/frontend/src/planner/select.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/13543
- Previously, we used the same correlated id to multi scalar subqueries which is incorrect. We need to assign a unique id for each of them.
</details>

fix(optimizer): fix multi scalar subqueried correlated id

---

src/common/src/metrics/guarded_metrics.rs
src/meta/src/rpc/metrics.rs

fix: source_status_is_up still reporting after `Drop Source`

---

src/meta/model_v2/migration/src/m20230908_072257_init.rs
src/meta/model_v2/src/object.rs
src/meta/model_v2/src/table.rs
src/meta/src/controller/catalog.rs

This PR added `alter_owner` function in catalog controller, it also:
1. added a new column `belongs_to_job_id` in table catalog, which is used to record which streaming job the internal table belongs to. We haven't record such information in catalog in current implementation, it's really necessary and helpful for some further sql functions in frontend.
2. fixed a bug in `drop_relation` about dropping the internal tables. …

feat: support alter owner in catalog controller

---

src/risedevtool/connector.toml

chore(risedev): vaildate java 21 for connector node

---

e2e_test/batch/basic/null_range_scan.slt.part
src/batch/src/executor/row_seq_scan.rs

Fix a missing case of https://github.com/risingwavelabs/risingwave/pull/13524
</details>

fix(batch): fix batch range scan for nulls with consideration for `NULLS FIRST|LAST`

---

src/meta/src/controller/cluster.rs

feat: expose resource info in cluster controller

---

.github/workflows/auto-create-doc-issue-by-issue.yml

Fix the workflow: [auto-create-doc-issue-by-issue](https://github.com/risingwavelabs/risingwave/actions/workflows/auto-create-doc-issue-by-issue.yml)

chore(ci): fix workflow: auto-create-doc-issue-by-issue

---

e2e_test/batch/join/natural_and_cross_join.slt
src/batch/src/executor/join/hash_join.rs

- Fix https://github.com/risingwavelabs/risingwave/issues/13572
</details>

fix(batch): fix join executor nullify build side function

---

src/batch/src/monitor/stats.rs
src/batch/src/task/context.rs
src/batch/src/task/env.rs
src/batch/src/task/task_execution.rs
src/batch/src/task/task_manager.rs
src/compute/src/server.rs

chore: Make batch mpp task num metrics more accurate.

---

src/frontend/planner_test/tests/testdata/input/sink.yaml
src/frontend/planner_test/tests/testdata/output/sink.yaml
src/frontend/src/optimizer/plan_node/stream_sink.rs

force the same primary key be written into the same sink shard to make sure the sink pk mismatch compaction effective
https://github.com/risingwavelabs/risingwave/blob/6d88344c286f250ea8a7e7ef6b9d74dea838269e/src/stream/src/executor/sink.rs#L169-L198
</details>

fix(sink): force sink shuffle with the sink pk

---

src/expr/macro/src/context.rs

refactor(expr/macro): refine `capture_context` generated code

---

ci/scripts/run-e2e-test.sh
e2e_test/error_ui/README.md
e2e_test/error_ui/extended/main.slt
e2e_test/error_ui/simple/main.slt
src/error/src/tonic.rs
src/utils/pgwire/src/error.rs
src/utils/pgwire/src/pg_extended.rs
src/utils/pgwire/src/pg_protocol.rs
src/utils/pgwire/src/pg_response.rs
src/utils/pgwire/src/types.rs

- Refine error messages in `pgwire`, use better variant names.
- Add UI test for extended mode.
- BTW, slightly refine the error message of `TonicStatusWrapper`.
</details>

refactor(error): refine error reporting in pgwire

---

src/common/src/types/timestamptz.rs

feat(expr): support parsing `timestamptz` without timezone minutes

---

src/storage/src/hummock/event_handler/hummock_event_handler.rs

When a new local state store is registering a read version, it may happen that the executor under creation has been dropped before the event handler is sending back the read version, which causes a send err. Currently, we panics on the send err, and in this PR we change to simply log the error. The read version that is failed to send will send a deregister event when it gets dropped, so the read version won't be leaked. …

fix(storage): avoid event handler panics

---

src/storage/src/hummock/event_handler/hummock_event_handler.rs
src/storage/src/hummock/event_handler/uploader.rs

The uploader code is relatively stable now. Previously we have several info log per epoch in uploader and hummock event handler, which we won't look at in most cases. 
This PR changes the per epoch logs from info to debug and only log uploder task info when the task is large than 50MB or the task is related to spilling.
</details>

chore(storage): only log spilled task and large task in uploader

---

java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/EsSink.java

resolve https://github.com/risingwavelabs/risingwave/issues/13585.
Can't work when `Time` type data has a fractional second precision value, e.g. `'01:00:00.1'`.https://github.com/risingwavelabs/risingwave/issues/13637
</details>

fix(elasticsearch-sink): convert `Time/Timestamp/Timestamptz` type into string

---

proto/batch_plan.proto
src/batch/src/executor/join/local_lookup_join.rs
src/batch/src/executor/row_seq_scan.rs
src/compute/tests/cdc_tests.rs
src/compute/tests/integration_tests.rs
src/frontend/planner_test/tests/testdata/output/basic_query.yaml
src/frontend/planner_test/tests/testdata/output/except.yaml
src/frontend/planner_test/tests/testdata/output/index_selection.yaml
src/frontend/planner_test/tests/testdata/output/intersect.yaml
src/frontend/planner_test/tests/testdata/output/limit.yaml
src/frontend/planner_test/tests/testdata/output/order_by.yaml
src/frontend/planner_test/tests/testdata/output/union.yaml
src/frontend/src/optimizer/mod.rs
src/frontend/src/optimizer/plan_node/batch_seq_scan.rs
src/frontend/src/optimizer/plan_node/logical_scan.rs
src/frontend/src/optimizer/rule/batch/batch_push_limit_to_scan_rule.rs
src/frontend/src/optimizer/rule/batch/mod.rs
src/frontend/src/optimizer/rule/mod.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/13506#issuecomment-1825061006
- Use `BatchPushLimitToScanRule` to pass limit to the scan, so that `RowSeqScanExecutor` can return early and avoid prefetching in this case.
</details>

feat(batch): support batch limit push down

---

docker/README.md
docs/developer-guide.md
e2e_test/README.md
src/risedevtool/README.md

https://github.com/orgs/community/discussions/16925
</details>

doc: update to new github note syntax

---

java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/EsSink.java

fix https://github.com/risingwavelabs/risingwave/issues/13079
</details>

fix(esSink): Fix es sink jsonb error

---

src/connector/src/source/kinesis/mod.rs

as title, in prev impl, `serde` will not do the type conversion. 
</details>

fix: correctly handle `scan.startup.timestamp.millis` as `Option<i64>`

---

src/frontend/src/scheduler/worker_node_manager.rs

- Related Issue https://github.com/risingwavelabs/risingwave/issues/13459
- Sysbench shows that `get_workers_by_parallel_unit_ids` consumes about 2.7% CPU. We can use a cache to improve it.
</details>

feat(batch): add a pu_to_worker cache for worker node manager

---

ci/workflows/integration-tests.yml
integration_tests/redis-sink/README.md
integration_tests/redis-sink/create_sink.sql
integration_tests/redis-sink/docker-compose.yml
integration_tests/redis-sink/sink_check
integration_tests/scripts/check_data.py
integration_tests/scripts/run_demos.py

test: add `redis-sink` test into the integration test workflow

---

e2e_test/batch/basic/null_range_scan.slt.part
src/frontend/planner_test/tests/testdata/output/range_scan.yaml
src/frontend/src/utils/condition.rs

fix #13601 
If the number is out of bounds, we just let it process by filter.
~~- [ ] I have added test labels as necessary.~~ See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
~~- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).~~
~~- [ ] My PR changes performance-critical code. …

fix: remove replace outbound cond

---

src/frontend/src/handler/alter_system.rs
src/frontend/src/handler/variable.rs
src/sqlparser/src/ast/mod.rs
src/sqlparser/src/parser.rs
src/sqlparser/tests/sqlparser_postgres.rs
src/sqlparser/tests/testdata/set.yaml

- report error when `set to default`
- fix parse alter system parameter.
- correctly parse parse `SetVariableValue`
</details>

fix(frontend): correct handle set to default and parse `SetVariableValue`

---

ci/scripts/build-simulation.sh
ci/scripts/build.sh
ci/scripts/unit-test.sh
ci/workflows/pull-request.yml

ci: increase timeout for sim build temporarily

---

.github/workflows/nightly-rust.yml

Before, the CI fails strangely:
After this, we can see rustc actually hangs... (https://github.com/rust-lang/rust/issues/118437
)
</details>

ci(nightly-rust): reserve more swap space

---

src/meta/src/barrier/progress.rs

chore(meta): remove obsolete doc comment for `StreamJob`

---

ci/scripts/notify.py
ci/workflows/main-cron.yml

fix(ci): fix notification format

---

ci/scripts/run-backfill-tests.sh
e2e_test/backfill/sink/create_sink.slt
e2e_test/backfill/sink/validate_sink.slt

Test failed in CI because rate limit was not set in the same session. Now we just put all the initial sql into a single slt file, so it will be run in a single session.
</details>

fix(test): rate limit must be set in same session for backfill test

---

src/tests/sqlsmith/src/sql_gen/functions.rs

fix(sqlsmith): `encode` should take in `Bytea` as its first argument instead of `varchar`

---

src/storage/src/hummock/compactor/mod.rs

refactor(storage): unify sstable writer in normal compaction

---

src/meta/node/src/server.rs
src/meta/src/barrier/command.rs
src/meta/src/barrier/recovery.rs
src/meta/src/hummock/manager/compaction_group_manager.rs
src/meta/src/hummock/test_utils.rs
src/meta/src/stream/stream_manager.rs

Before this PR, `unregistering a table from compaction group` after cancelling a streaming job may fail, due to etcd issue, which is rare though. If it fails, we give a warning to restart the meta node to purge the dirty state. Before that restarting, there can be compaction task failing repeatedly, due to inconsistency between table catalog and compaction group member table definition, required by compactor's `FilterKeyExtractor`.
This PR make the `unregistering a table from compaction group` step fail fast, instead of giving a warning only.
If this PR includes changes that directly affect users or other significant …

refactor(meta): make unregister compaction group member fail fast

---

src/meta/src/manager/catalog/database.rs
src/meta/src/manager/catalog/mod.rs

fix: don't clean in-memory tracker when clean persist table catalog

---

e2e_test/udf/udf.slt
java/udf-example/pom.xml
java/udf/CHANGELOG.md
java/udf/pom.xml
java/udf/src/main/java/com/risingwave/functions/TypeUtils.java

When outputting a large string or string array, Java UDF throws this exception:
```
java.lang.IndexOutOfBoundsException: index: 0, length: 50000 (expected: range(0, 32768))
at org.apache.arrow.memory.ArrowBuf.checkIndex(ArrowBuf.java:701)
at org.apache.arrow.memory.ArrowBuf.setBytes(ArrowBuf.java:765)
at org.apache.arrow.vector.BaseVariableWidthVector.setBytes(BaseVariableWidthVector.java:1251)
at org.apache.arrow.vector.BaseVariableWidthVector.set(BaseVariableWidthVector.java:1032)
at com.risingwave.functions.TypeUtils.fillVector(TypeUtils.java:291)
at com.risingwave.functions.TypeUtils.fillVector(TypeUtils.java:384) …
```

fix(udf): fix index-out-of-bound error when string or string list is large.

---

integration_tests/mysql-cdc/mysql-datatypes.yml

https://github.com/risingwavelabs/risingwave/pull/13546#discussion_r1403916068
</details>

chore(integration_tests): remove invalid mysql type alias

---

src/utils/runtime/src/lib.rs

Previously, `RW_WORKER_THREADS` is only applied to the runtime we start in `main_okk` and does not affect those for running batch tasks or streaming actors. This is kind of counterintuitive. In this PR, we make it an alias of `TOKIO_WORKER_THREADS`, which will be automatically read each time when building a tokio runtime.
In some sense, we're actually deprecating `RW_WORKER_THREADS` and users should prefer `TOKIO_WORKER_THREADS` instead.
Note that this only affects the default worker thread value. It can still be overridden by per-module runtime worker thread settings in the config file (like `batch.worker_threads_num` …

fix: apply `RW_WORKER_THREADS` for all runtimes

---

src/expr/core/src/expr/expr_udf.rs
src/udf/src/error.rs

resolve #13791 by implementing https://github.com/risingwavelabs/risingwave/issues/13791#issuecomment-1839261633

fix(udf): prevent continuous retries on connection error

---

proto/meta.proto
src/frontend/src/catalog/system_catalog/rw_catalog/rw_event_logs.rs
src/meta/service/src/event_log_service.rs
src/meta/src/manager/event_log.rs
src/rpc_client/src/lib.rs
src/rpc_client/src/meta_client.rs

feat(meta): try to record panic info from worker nodes (#13779)

---

ci/workflows/pull-request.yml
java/connector-node/python-client/integration_tests.py
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/SinkWriterStreamObserver.java
java/connector-node/risingwave-connector-test/src/test/java/com/risingwave/connector/sink/SinkStreamObserverTest.java
proto/connector_service.proto
src/connector/src/sink/remote.rs
src/rpc_client/src/connector_client.rs

Currently in remote sink request, epoch is included in the WriteBatch and Barrier request. Therefore, we don't need an extra StartEpoch request at the beginning. We only need to call start the epoch when we see the first item with the new epoch.
</details>

refactor(sink): remove unnecessary StartEpoch of remote sink

---

Cargo.lock
Cargo.toml
src/batch/Cargo.toml
src/batch/src/rpc/service/task_service.rs
src/common/src/config.rs
src/compute/src/server.rs
src/config/example.toml

Close #13708. 
Now we make the pending rst stream configurable. See https://buildkite.com/risingwave-test/sysbench/builds/615#018c38f2-ec9b-4fc1-8834-67f669df3c8f
</details>

fix: Configure grpc max pending reset stream.

---

src/tests/simulation/src/cluster.rs
src/tests/simulation/tests/integration_tests/recovery/background_ddl.rs

As per title. Closes https://github.com/risingwavelabs/risingwave/issues/13418
Cancel stream jobs has 2 paths:
1. `CANCEL JOBS`
2. `ctrl-c` / `kill <pid>`.
1) is already tested. 2) is tested here.
</details>

test(stream): add `kill` cancel test for foreground ddl

---

src/connector/src/common.rs

- Refactor variable name `message_max_bytes` to `receive_message_max_bytes` in `common.rs` file in `src/connector/src` directory.
as title, the `receive.message.max.bytes` is set to `message.max.bytes` by mistake
</details>

fix: kafka props mismatch

---

src/meta/src/hummock/manager/mod.rs
src/meta/src/hummock/metrics_utils.rs

fix(storage): fix compaction metrics remove

---

src/storage/src/hummock/store/local_hummock_storage.rs

chore: remove some spill log

---

src/stream/src/cache/managed_lru.rs
src/stream/src/executor/monitor/streaming_stats.rs

- use guarded gauge for lru metrics to avoid hash collision
</details>

refactor(metrics): use guarded gauge for lru metrics

---

src/meta/service/src/ddl_service.rs
src/meta/src/manager/catalog/mod.rs
src/meta/src/rpc/ddl_controller.rs
src/meta/src/stream/source_manager.rs
src/meta/src/stream/stream_manager.rs

chore(meta): add some comments for source & stream manager

---

src/storage/hummock_sdk/src/compact.rs

chore: log range tombstone count

---

proto/batch_plan.proto
src/batch/src/executor/join/local_lookup_join.rs
src/batch/src/executor/row_seq_scan.rs
src/frontend/src/optimizer/plan_node/batch_seq_scan.rs
src/frontend/src/optimizer/plan_node/generic/scan.rs
src/frontend/src/optimizer/plan_node/logical_scan.rs
src/frontend/src/optimizer/rule/batch/batch_push_limit_to_scan_rule.rs
src/frontend/src/optimizer/rule/top_n_on_index_rule.rs

- As we have `limit` which can be used to decide the chunk size of the scan, we can deprecate the `chunk_size` field in proto.
</details>

chore(batch): deprecate chunk size in scan

---

Cargo.lock
Cargo.toml
README.md
docker/docker-compose-distributed.yml
docker/docker-compose.yml

chore: update version to 1.5.0

---

docker/Dockerfile

fix(docker): fix apt install failed (#13873)

---

risedev.yml
src/object_store/src/object/mod.rs
src/risedevtool/src/task/utils.rs

The path of Hummock with FS is separated into 2 parts to be consistent with other state store backend configurations.
1. bucket: root path
2. data directory: directory in root path
</details>

fix(storage): make path of hummock with FS customisable

---

docker/Dockerfile

fix: add apt-get update to fix dockerfile

---

Cargo.lock
src/common/fields-derive/Cargo.toml
src/common/fields-derive/src/gen/test_output.rs
src/common/fields-derive/src/lib.rs
src/common/src/types/with_data_type.rs

Follow up to #13862 
</details>

fix(types): fix Serial in Fields derive and add tests

---

src/sqlparser/src/ast/legacy_source.rs
src/sqlparser/src/ast/mod.rs
src/sqlparser/src/ast/statement.rs

Motivation: People working on new things shall focus on `ConnectorSchema` and not to be confused with `ProtobufSchema`, `AvroSchema`, `DebeziumAvroSchema`, `CsvInfo`, which are beyond sqlparser's responsibility.
</details>

refactor(sqlparser): move create source v1 compatible code to its own mod

---

src/frontend/planner_test/tests/testdata/input/emit_on_window_close.yaml
src/frontend/planner_test/tests/testdata/output/emit_on_window_close.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml
src/frontend/src/optimizer/plan_node/stream_hash_join.rs

- Previously, we only derived watermark from one side of the inequalities of the interval join which could miss some possible watermark columns.
</details>

fix(optimizer): fix interval join watermark derive

---

docker/docker-compose-with-local-fs.yml

as title, verified.
rated to https://github.com/risingwavelabs/risingwave-docs/issues/1635
</details>

feat(docker): add local fs docker compose

---

src/stream/src/executor/agg_common.rs
src/stream/src/executor/aggregation/distinct.rs
src/stream/src/executor/hash_agg.rs
src/stream/src/executor/simple_agg.rs
src/stream/src/executor/test_utils.rs
src/stream/src/from_proto/hash_agg.rs
src/stream/src/from_proto/simple_agg.rs

This PR is just a regular cleanup to remove unnecessary `metrics` and `metrics_info` fields from agg-related structures. They can be removed because they can be accessed via `ActorContext`.
</details>

refactor(streaming): clean up unnecessary `metrics` field in agg executor

---

src/object_store/src/object/mod.rs

The object not found error is expected sometimes.
~~We may refactor [read](https://github.com/risingwavelabs/risingwave/blob/064f04dd5009e559f50376558b90755326b51f64/src/object_store/src/object/mod.rs#L604) to return Result\<Option\<Bytes\>\>, to avoid handle `is_object_not_found_error` here and there.~~ @wcy-fdu 
</details>

chore: don't warn on object not found error

---

src/meta/node/src/server.rs
src/meta/src/barrier/command.rs
src/meta/src/barrier/schedule.rs
src/meta/src/stream/stream_manager.rs
src/tests/simulation/tests/integration_tests/recovery/background_ddl.rs

An improvement on the behaviour of cancel stream job. We immediately drop the table catalog for a recovered stream job. If recovery is triggered, it will still cleanup the stream job.
</details>

fix(meta): drop `TableCatalog` in `cancel_stream_jobs`

---

src/meta/node/src/server.rs
src/meta/src/barrier/command.rs
src/meta/src/stream/stream_manager.rs
src/tests/simulation/tests/integration_tests/recovery/background_ddl.rs

cherry pick https://github.com/risingwavelabs/risingwave/pull/13938
Closes #13976 
Excludes https://github.com/risingwavelabs/risingwave/pull/13938#issuecomment-1852034141, since that's not part of v1.5.0.
</details>

fix(meta): drop TableCatalog in cancel_stream_jobs

---

.github/workflows/cherry-pick-to-release-branch.yml

chore(ci): Update cherry-pick-to-release-branch.yml for v1.5.1

---

docker/Dockerfile

Cherry pick https://github.com/risingwavelabs/risingwave/pull/13925 otherwise can't build docker image from v1.5.1
</details>

 fix: add apt-get update to fix dockerfile (#13925)

---

proto/hummock.proto
src/meta/src/hummock/manager/compaction_group_manager.rs
src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs

As titled. Previously we did not remove the table watermarks of dropped tables, and then the hummock version will keep growing.
</details>

feat(storage): remove table watermarks of dropped tables

---

Cargo.lock
src/frontend/src/catalog/system_catalog/mod.rs

Fix rust-analyzer warnings
</details>

chore(deps): bump ctor to v0.2.6

---

src/connector/src/common.rs
src/connector/with_options_sink.yaml
src/connector/with_options_source.yaml

as title, add an SSL related config for `ssl.endpoint.identification.algorithm` to resolve handshake failure reported from community https://risingwave-community.slack.com/archives/C03BW71523T/p1702506779695839
The solution is from https://github.com/confluentinc/librdkafka/discussions/4204 
as described above
add …

feat: allow kafka source/sink config `ssl_endpoint_identification_algorithm`

---

src/frontend/src/binder/create.rs
src/frontend/src/binder/relation/table_or_source.rs
src/frontend/src/handler/comment.rs
src/frontend/src/handler/create_source.rs
src/frontend/src/handler/create_table.rs
src/frontend/src/handler/describe.rs
src/frontend/src/handler/show.rs
src/frontend/src/optimizer/plan_node/logical_scan.rs
src/frontend/src/optimizer/plan_node/stream_table_scan.rs
src/frontend/src/optimizer/rule/index_selection_rule.rs
src/frontend/src/planner/relation.rs

As per title. Some places in the code were cloning the underlying table catalog, rather than a shared reference.
</details>

refactor(frontend): clone shared table catalog reference

---

ci/workflows/main-cron.yml

fix(ci): fix `main-cron.yml` format

---

Cargo.lock
src/common/Cargo.toml
src/common/src/lib.rs
src/common/src/log.rs
src/connector/Cargo.toml
src/connector/src/parser/avro/util.rs
src/connector/src/parser/mod.rs
src/connector/src/parser/mysql.rs
src/connector/src/parser/unified/avro.rs
src/connector/src/parser/unified/json.rs
src/connector/src/parser/unified/protobuf.rs
src/connector/src/parser/util.rs
src/workspace-hack/Cargo.toml

Closes #13328
Introduced a `LogSuppresser` to limit and suppress logs to given rate. The default is 1 log per 10 seconds. Suppressed logs will be counted in `suppressed_count` and outputted in next non-suppressed log.
It's easy to enhance this to support keyed suppression (for example, by different error types) by using a keyed `RateLimiter` (the 1st generic parameter in `governer::RateLimiter`). …

feat(source): suppress parser log

---

e2e_test/source/cdc/cdc.share_stream.slt
e2e_test/source/cdc/mysql_create.sql
src/connector/src/parser/mysql.rs
src/connector/src/source/external.rs
src/stream/src/executor/backfill/cdc/cdc_backfill.rs
src/stream/src/executor/backfill/upstream_table/external.rs

**The PR is merging to v1.5.1-rc, and will be picked to main after merge.**
1. To fix https://github.com/risingwavelabs/risingwave/issues/14018
2. set column to `NULL` and print error log if cannot parse it to `Datum`
3. quote column in the filter expression
Caveat: `bit(1)` cannot be parsed into Rust `boolean` due to https://github.com/blackbeam/rust_mysql_common/issues/113, which will be set to `NULL`
~- [ ] I have added test labels as necessary. See [details]~(https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
~- [ ] I have added fuzzing tests or opened an issue to track …

fix(cdc): fix mysql row parsing errors for v1.5

---

proto/backup_service.proto
src/ctl/src/cmd_impl/meta/backup_meta.rs
src/ctl/src/lib.rs
src/frontend/src/catalog/system_catalog/rw_catalog/rw_meta_snapshot.rs
src/meta/service/src/backup_service.rs
src/meta/src/backup_restore/backup_manager.rs
src/meta/src/backup_restore/restore.rs
src/rpc_client/src/meta_client.rs
src/storage/backup/src/lib.rs
src/storage/backup/src/storage.rs

Add support for specifying optional `remarks` for new meta snapshot during creation. It helps to distinguish between meta snapshots.
`ctl meta backup-meta --remarks 123
`
```
dev=> select * from rw_meta_snapshot;
meta_snapshot_id | hummock_version_id | safe_epoch | safe_epoch_ts | max_committed_epoch | max_committed_epoch_ts  | remarks 
------------------+--------------------+------------+---------------+---------------------+-------------------------+---------
1 |                124 |          0 |               |    5612686570225664 | 2023-12-18 05:40:00.449 | 
2 |                128 |          0 |               | …
```

feat(meta): add remarks field for metadata backup.

---

Cargo.lock
Cargo.toml
README.md
docker/docker-compose-distributed.yml
docker/docker-compose.yml

chore: update version v1.5.1

---

src/object_store/src/object/mod.rs

`try_update_failure_metric` always log error, which is not appropriate.
To work around it, unlike #13935, this PR only log `object not found error` for state store, because there're more cases where the error is expected, e.g. hummock version checkpoint during first startup.
</details>

chore(log): filter out object not found error

---

e2e_test/source/cdc/cdc.share_stream.slt
e2e_test/source/cdc/mysql_create.sql
src/connector/src/parser/mysql.rs
src/connector/src/source/external.rs
src/stream/src/executor/backfill/cdc/cdc_backfill.rs
src/stream/src/executor/backfill/cdc/upstream_table/external.rs

cherry pick #14023 to main
close https://github.com/risingwavelabs/risingwave/issues/14018
</details>

fix(cdc): cherry pick PR#14023 fix mysql row parsing errors

---

e2e_test/iceberg/start_spark_connect_server.sh
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/JniSinkWriterHandler.java
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/deserializer/StreamChunkDeserializer.java
java/java-binding/src/main/java/com/risingwave/java/binding/Binding.java
java/java-binding/src/main/java/com/risingwave/java/binding/JniSinkWriterStreamRequest.java
java/java-binding/src/main/java/com/risingwave/java/binding/StreamChunk.java
proto/connector_service.proto
src/connector/src/sink/remote.rs
src/jni_core/src/lib.rs
src/jni_core/src/macros.rs
src/rpc_client/src/connector_client.rs
src/rpc_client/src/lib.rs

feat(jni): pass stream chunk directly without serde (#13430)

---

src/stream/src/executor/over_window/general.rs
src/stream/src/executor/over_window/over_partition.rs

_Pre_-cherry-pick https://github.com/risingwavelabs/risingwave/pull/14045 to v1.5.1-rc.
</details>

fix(1.5.1, over window): fix range cache when some of order by and input stream key columns are in partition by columns

---

codecov.yml

We don't run UTs on main now, and codecov doesn't have data for the base commit. So the report looks bad and is noisy. (BTW, I don't like it even if it's precise. Never checked it before 🤪)
</details>

ci: disable codecov comment

---

.github/workflows/cherry-pick-to-release-branch.yml

update cherry pick version to release-1.5 and release-1.6
</details>

chore: update cherry pick version to release-1.5 and release-1.6

---

src/expr/impl/benches/expr.rs

In previous benchmark, we always test the same sub and target, e.g.  position('1000', '1000').
</details>

test(expr): refine position bench

---

.cargo/audit.toml
Cargo.lock

* ahash 0.7.6 -> 0.7.7 & 0.8.3 -> 0.8.6 https://github.com/tkaitchuck/aHash/wiki/Yanked-versions
* dependency on `time` has been upgraded
* dependency on aws has been upgraded
</details>

chore(deps): bump ahash and cleanup stale audit ignores

---

Cargo.lock
src/meta/Cargo.toml
src/meta/src/barrier/recovery.rs
src/meta/src/lib.rs
src/meta/src/stream/stream_manager.rs
src/stream/src/executor/test_utils.rs

perf(meta): make GlobalStreamManager::build_actors concurrent

---

backwards-compat-tests/scripts/utils.sh

fix(ci): fix version check in backwards compatibility tests

---

Cargo.lock
src/expr/udf/src/external.rs
src/frontend/src/scheduler/distributed/stage.rs
src/meta/Cargo.toml
src/meta/src/barrier/recovery.rs
src/meta/src/lib.rs
src/meta/src/stream/stream_manager.rs
src/object_store/src/object/mem.rs
src/object_store/src/object/opendal_engine/opendal_object_store.rs
src/storage/hummock_test/src/bin/replay/replay_impl.rs
src/storage/hummock_test/src/state_store_tests.rs
src/tests/state_cleaning_test/src/bin/main.rs

Gain a better understanding of `Stream`
</details>

chore: remove useless for_await

---

src/frontend/src/scheduler/worker_node_manager.rs

Fix a corner case where cache is not updated as expected.
</details>

fix(batch): fix pu2worker cache

---

src/expr/core/src/expr/wrapper/non_strict.rs
src/stream/src/executor/actor.rs

refactor: supress log "failed to evaluate expression"

---

src/frontend/src/session.rs

Fix #14102 
Introduced in #13999 
</details>

fix(frontend): wrong RowDescription for `SHOW TRANSACTION ISOLATION LEVEL`

---

src/connector/src/parser/mysql.rs

Follow-up of #14005.
</details>

feat: suppress logs of mysql cdc source

---

src/meta/src/barrier/recovery.rs
src/meta/src/barrier/schedule.rs
src/meta/src/rpc/ddl_controller.rs

Together with pre-apply optimization for `CANCEL`.
</details>

feat: allow drop streaming jobs during recovery (#12317)

---

src/frontend/planner_test/tests/testdata/input/distinct_on.yaml
src/frontend/planner_test/tests/testdata/output/distinct_on.yaml
src/frontend/src/binder/select.rs
src/frontend/src/planner/select.rs

The `distinct: BoundDistinct` in `BoundSelect` should be based on the input schema of the `BoundSelect` instead of the output schema of the `BoundSelect`
fix https://github.com/risingwavelabs/risingwave/issues/14099
fix https://github.com/risingwavelabs/risingwave/issues/14113
</details>

fix(binder): bind distinct

---

src/sqlparser/src/keywords.rs
src/sqlparser/src/parser.rs

feat(parser): accept `cancel job`

---

src/meta/src/rpc/ddl_controller.rs

fix: cancel background stream job if table fragment not persist

---

Cargo.lock
Cargo.toml
README.md
docker/docker-compose-distributed.yml
docker/docker-compose.yml

chore: update version to 1.5.2

---

src/sqlparser/src/ast/statement.rs
src/sqlparser/tests/testdata/create.yaml

it influences the definition in the system table
```
dev=> select definition from rw_sinks;
definition                                      
--------------------------------------------------------------------------------------
CREATE SINK s INTO t FROM tt WITH (type = 'append-only', force_append_only = 'true')
(1 row)
```
</details>

fix(parser): display of sink into table

---

src/stream/src/executor/now.rs
src/stream/src/executor/top_n/group_top_n.rs
src/stream/src/executor/top_n/group_top_n_appendonly.rs
src/stream/src/executor/top_n/top_n_appendonly.rs
src/stream/src/executor/top_n/top_n_cache.rs
src/stream/src/executor/top_n/top_n_plain.rs
src/stream/src/executor/top_n/top_n_state.rs

cherry-pick #13271 and #13832 to release-1.5
</details>

fix: cherry-pick #13271 and #13832 to release-1.5

---

e2e_test/batch/functions/to_char.slt.part
src/expr/impl/src/scalar/to_char.rs

feat(expr): support interval `to_char()` (#14071)

---

src/meta/model_v2/migration/src/m20230908_072257_init.rs
src/meta/model_v2/src/function.rs
src/meta/model_v2/src/index.rs
src/meta/model_v2/src/lib.rs
src/meta/model_v2/src/sink.rs
src/meta/model_v2/src/table.rs
src/meta/src/controller/catalog.rs
src/meta/src/controller/cluster.rs
src/meta/src/controller/fragment.rs
src/meta/src/controller/mod.rs
src/meta/src/controller/user.rs
src/meta/src/controller/utils.rs

Part 1 of #13949 . Introduced some functions that are necessary for RPC services, dashboard, metrics and other managers like hummock etc. Together with some bug fixes during test upon #13949 .
</details>

feat: [Part 1] add more functions for sql-based controllers and some bug fix

---

ci/scripts/deterministic-recovery-test.sh
src/connector/src/source/nexmark/mod.rs
src/connector/src/source/nexmark/source/reader.rs
src/connector/with_options_source.yaml

refactor(source): remove unnecessary Box for NexmarkProperties

---

src/meta/src/controller/catalog.rs

Related #13341, sql version of alter object schema.
</details>

feat: support alter object schema in catalog controller

---

src/storage/src/hummock/store/hummock_storage.rs

Remove necessary `use` without test profile.
</details>

chore: fix building warning without test

---

Cargo.lock
Cargo.toml
README.md
docker/docker-compose-distributed.yml
docker/docker-compose.yml

chore: update version to 1.5.4

---

.github/workflows/doc.yml

related:
- https://github.com/rust-lang/rust/issues/117622
- This is fixed in latest `tokio` https://github.com/tokio-rs/tokio/pull/6120, but I don't want to upgrade `tokio` just for this.. 
I don't remember what exactly  `--cfg docsrs` do, but I guess it will just make the doc a little bit less pretty
</details>

ci(rustdoc): remove `--cfg docsrs`

---

e2e_test/udf/sql_udf.slt
src/frontend/src/binder/expr/function.rs
src/frontend/src/handler/create_sql_function.rs

As titled, the current implementation is just treating the return expression as a normal select function body definition, since currently return sql udf will not involve complex syntax.
See the test cases for supported syntax & example use cases.
</details>

feat(sql-udf): support basic anonymous sql udf return expression

---

e2e_test/sink/kafka/protobuf.slt
src/connector/src/parser/avro/parser.rs
src/connector/src/parser/json_parser.rs
src/connector/src/parser/protobuf/parser.rs
src/connector/src/parser/protobuf/schema_resolver.rs
src/connector/src/parser/util.rs

* All 3 parsers now call `crate::parser::util::bytes_from_url`.
* `crate::parser::util::read_schema_from_s3` removed as duplicate of `crate::aws_utils::load_file_descriptor_from_s3`.
* All 3 parsers load from bytes rather than string
* avro: `Schema::parse_str` -> `Schema::parse_reader`
* json-schema: `serde_json::from_str` -> `serde_json::from_slice` …

refactor(source): consolidate duplicate schema loading logic for avro/protobuf/json-schema

---

src/utils/pgwire/src/lib.rs
src/utils/pgwire/src/pg_protocol.rs

Fixes #14283.
Seems no existing lint rules to help find similar string slicing operations.
</details>

fix(pgwire): `TruncatedFmt` should respect utf8 char boundary

---

src/meta/src/rpc/ddl_controller.rs

Fix #14297 . The root cause is that in #14191 we forward storing table fragments in ddl controller for compatibility but forget to do it for `DROP SINK` when merging main branch. 🥵 
</details>

fix: dummy table fragments are not persist when drop sink with table replacement

---

src/batch/src/executor/mod.rs
src/batch/src/executor/test_utils.rs
src/batch/src/executor/update.rs
src/common/proc_macro/src/lib.rs
src/connector/src/sink/doris.rs
src/meta/src/stream/scale.rs
src/storage/src/hummock/sstable/block.rs

chore: fix typos linted by cSpell

---

src/meta/src/stream/source_manager.rs

revert back to the old behavior to mitigate #14333 (not resolve).
explanation https://github.com/risingwavelabs/risingwave/issues/14333#issuecomment-1875200358
example of the occurrence with the old behavior https://github.com/risingwavelabs/risingwave/issues/14324#issuecomment-1875033158
</details>

fix: revert to random source split assignment when there are too many actors

---

src/batch/src/executor/update.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/14339
- Compare the before row and after row of an update to decide whether to send it downstream.
</details>

feat(dml): recognize no op updates

---

src/meta/Cargo.toml
src/meta/model_v2/migration/src/m20231008_020431_hummock.rs
src/meta/model_v2/src/hummock_sequence.rs
src/meta/model_v2/src/lib.rs
src/meta/src/hummock/manager/mod.rs
src/meta/src/hummock/manager/sequence.rs

This PR adds a sequence generator dedicated to Hummock. Because the original common `IdGenerator` will be removed in sql meta store, while Hummock still need one.
</details>

refactor(meta): seq generator for Hummock model v2

---

src/meta/src/barrier/command.rs
src/meta/src/manager/catalog/fragment.rs

As title. If the meta is restarted, the actor's split assignment information will need to rely on a config change by the source manager to be restored.
</details>

fix: actor split assignment is not persist when replace command is collected

---

src/stream/src/executor/mview/materialize.rs

fix(stream/materialize): enforce update_cache when modify fixed_changes

---

e2e_test/sink/sink_into_table/rename.slt

test: fix flaky sink_into_table test

---

src/stream/src/executor/mview/materialize.rs

- Related https://github.com/risingwavelabs/risingwave/issues/14339
- recognize no op update for table.
</details>

feat(stream): recognize no op update for table

---

ci/scripts/cron-e2e-test.sh
src/meta/src/barrier/recovery.rs
src/meta/src/manager/catalog/fragment.rs

fix: Do not recover background streaming jobs whose table fragments have been marked as created (#14367)

---

docker/docker-compose-with-s3.yml

fix(docker): s3 docker compose use correct env file

---

src/frontend/planner_test/tests/testdata/input/temporal_filter.yaml
src/frontend/planner_test/tests/testdata/output/temporal_filter.yaml
src/frontend/src/optimizer/logical_optimization.rs
src/frontend/src/optimizer/rule/mod.rs
src/frontend/src/optimizer/rule/stream/filter_with_now_to_join_rule.rs
src/frontend/src/optimizer/rule/stream/mod.rs
src/frontend/src/optimizer/rule/stream/split_now_and_rule.rs

split temporal filters into multiple filter plan node to support multiple temporal filter with or such as `(now_cond OR e1) AND (now_cond OR e2)`
</details>

feat: support multiple temporal filter with or

---

src/frontend/planner_test/tests/testdata/output/subquery.yaml
src/frontend/src/catalog/system_catalog/pg_catalog/pg_class.rs

as title. In [pg](https://www.postgresql.org/docs/current/catalog-pg-class.html), there're three types of result.
```
p = permanent table/sequence, 
u = unlogged table/sequence, 
t = temporary table/sequence
```
As currently we only support persisted table/index/index, always returning `p` is OK.
</details>

feat(catalog): add relpersistence in pg_class

---

ci/scripts/notify.py
ci/workflows/main-cron.yml

Since there's a notification system done for `main-cron`, we can use it to notify on failure for differential tests as well.
Previously it was `soft-failed` as I didn't have much time to maintain it.
</details>

chore(ci): enable differential tests

---

docker/docker-compose-with-hdfs.yml

long term work: https://github.com/risingwavelabs/risingwave/issues/12723
</details>

chore: update rw version with hdfs

---

ci/scripts/notify.py
ci/scripts/s3-source-test-for-opendal-fs-engine.sh
ci/workflows/main-cron.yml
e2e_test/s3/gcs_source.py
src/connector/src/source/base.rs
src/connector/src/source/filesystem/opendal_source/gcs_source.rs
src/connector/src/source/filesystem/opendal_source/mod.rs
src/connector/with_options_source.yaml

Cherry picking https://github.com/risingwavelabs/risingwave/pull/14373 onto branch release-1.6
</details>

fix(connector): fix gcs source connector(#14373) 

---

src/frontend/src/scheduler/snapshot.rs
src/meta/src/hummock/manager/mod.rs

chore: remove some periodical logs (#14427)

---

src/frontend/src/optimizer/plan_node/stream_dynamic_filter.rs

fix: fix dyn filter's always relax workaround

---

e2e_test/udf/udf.slt
src/expr/core/src/sig/mod.rs
src/expr/impl/tests/sig.rs
src/frontend/src/binder/expr/function.rs
src/frontend/src/catalog/root_catalog.rs
src/frontend/src/catalog/schema_catalog.rs
src/frontend/src/expr/mod.rs
src/frontend/src/expr/type_inference/func.rs
src/frontend/src/expr/type_inference/mod.rs

cherry-pick #14338 to release-1.6.
This PR fixes an issue which is important to the UDF user experience.
</details>

feat(udf): support implicit cast for UDF arguments (#14338)

---

src/meta/src/model/stream.rs

As title, `Custom` is not that radical.
</details>

chore(meta): change default parallelism for already existed streaming job to Custom

---

java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/DbzConnectorConfig.java
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/DbzSourceUtils.java
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzCdcEngineRunner.java
java/connector-node/risingwave-connector-service/src/main/resources/debezium.properties
java/connector-node/risingwave-connector-service/src/main/resources/mysql.properties
src/jni_core/src/jvm_runtime.rs

Fix https://github.com/risingwavelabs/risingwave/issues/14394
- Turn on [schema.history.internal.store.only.captured.tables.ddl](https://debezium.io/documentation/reference/2.5/connectors/mysql.html#mysql-property-database-history-store-only-captured-tables-ddl) to only read schemas for captured tables for `mysql-cdc`, e.g. `mydb.*`. We don't need to modify this config for `postgres-cdc`, since the shared pg source won't snapshot table schemas from upstream.
- Increase the waiting timeout for the start of debezium streaming source …

fix(mysql-cdc): only read table schema of captured tables instead of all tables for shared source

---

integration_tests/kinesis-s3-source/docker-compose.yml

there are joins in the query and it may produce nothing if the data volume is too small
</details>

fix: increase data generator qps to produce more data in MV

---

ci/workflows/main-cron.yml

fix(test): fix the wrong suffix in cron test

---

docker/Dockerfile

chore: pack telnet kcat in release image

---

src/common/src/util/memcmp_encoding.rs

A handy piece of code for decoding encoded key when debugging.
</details>

chore: add `test_decode_row` for memcomparable encoding

---

src/meta/src/barrier/command.rs

As title, the source split changes are not applied in source manager after replacing table. It will make config change not work for table with connector that has been altered with columns. Already tested it locally with some debugging logs and didn't find a right place to add tests. Let's fix it at first.
</details>

fix: missing apply of source split discovery info after replacing table

---

ci/scripts/run-backfill-tests.sh

Sink should no longer have any progress
</details>

chore(ci): fix `backfill-tests`

---

e2e_test/batch/explain.slt
src/frontend/src/handler/explain.rs

Closes https://github.com/risingwavelabs/risingwave/issues/13989
</details>

feat(frontend): return `NotSupportedError` for `EXPLAIN CREATE VIEW`

---

src/common/src/util/sort_util.rs

Just simply expose `OrderType::direction()` method and `Direction` type, as a preparation for `RANGE` frame.
</details>

feat(common): expose `OrderType::direction()`

---

src/expr/core/src/window_function/state/buffer.rs
src/expr/core/src/window_function/state/mod.rs
src/expr/core/src/window_function/state/range_utils.rs

`range_except` and `range_diff` functions are relatively independent to `WindowBuffer`, so moving them to separate module called `range_utils`.
</details>

refactor(over window): extract `range_utils` which handles `Range` operations

---

Cargo.lock
Cargo.toml
README.md
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose.yml

chore: update version to 1.6.0

---

backwards-compat-tests/scripts/utils.sh
ci/scripts/backwards-compat-test.sh

fix(ci): build from source when not released on github

---

src/common/src/session_config/mod.rs
src/frontend/planner_test/tests/testdata/input/subquery_expr_correlated.yaml
src/frontend/planner_test/tests/testdata/output/subquery_expr_correlated.yaml
src/frontend/src/binder/query.rs
src/frontend/src/binder/relation/mod.rs
src/frontend/src/expr/subquery.rs

- Fix https://github.com/risingwavelabs/risingwave/issues/14423
- Previously, we only supported subquery in a single parenthesis. This PR extends it to multiple parentheses.
</details>

fix(optimizer): fix subquery with multiple parentheses

---

ci/scripts/upload-micro-bench-results.sh

`contains` only accepts strings, it will error on the `null` cases. So we just filter them ahead of time.
</details>

fix(ci): fix microbenchmark upload step

---

src/meta/service/src/ddl_service.rs
src/meta/src/rpc/ddl_controller.rs

fix: fix fill table id for cdc backfill source (#14516) (cherry pick)

---

integration_tests/kinesis-s3-source/docker-compose.yml

Sometimes, the datagen will fail to put records into localhost:2.2
such as `2024/01/12 07:31:13 failed to write record to kinesis: RequestError: send request failed`
and when I try to get records from the host machine, aws cli may complains:
```
An error occurred (500) when calling the GetRecords operation (reached max retries: 4): Internal Server Error
```
Localstack's log seems not useful to us:
After upgrade,
https://buildkite.com/risingwavelabs/integration-tests/builds/576#018cfc93-c928-4ef3-ac00-b231fd04fbc1 succeeds
If this PR includes changes that directly affect users or other significant modifications relevant …

chore: upgrade localstack in integration tests to `3.0`

---

src/expr/core/src/window_function/call.rs

Use `parse_display` to impl `Display` for `FrameBound`-related types, to simplify code.
</details>

refactor(over window): use `parse_display` to impl `Display` for window frame types

---

Makefile.toml

https://risingwave-labs.slack.com/archives/C04S2HVU99V/p1705047925083899?thread_ts=1705042591.573429&cid=C04S2HVU99V
</details>

chore: increase log size limit in ci

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose.yml

chore: upgrade docker image version

---

src/stream/src/executor/backfill/cdc/cdc_backfill.rs

A quick patch for an anonymous user.
</details>

feat(cdc-backfill): support pause_on_startup

---

src/common/src/util/future_utils/buffered_with_fence.rs
src/common/src/util/future_utils/mod.rs
src/common/src/util/mod.rs
src/stream/src/executor/project.rs

feat(stream): make Project expr evaluation concurrent

---

dashboard/pages/heap_profiling.tsx

fix(dashboard): show error in web frontend when heap dump not enabled

---

Cargo.lock
Cargo.toml

icelake has fix #14106. This version update the icelake version to fix it.
</details>

fix: update icelake

---

src/common/src/config.rs
src/config/example.toml
src/object_store/src/object/s3.rs

We've encountered S3-compatible object store that returns "slow down" 503, which cannot be recognized by AWS S3 SDK, e.g.
`Hummock error: ObjectStore failed with IO error s3 error: service error: unhandled error: unhandled error: Error (ServiceError(ServiceError { source: Unhandled(Unhandled { source: ErrorMetadata { code: None, message: None, extras: None }, meta: ErrorMetadata { code: None, message: None, extras: None } })`.
This PR introduces a retry option for these unhandled 503 errors.
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft …

feat(s3): retry unhandled 503 error

---

src/stream/src/executor/backfill/no_shuffle_backfill.rs
src/tests/simulation/src/cluster.rs
src/tests/simulation/tests/integration_tests/backfill_tests.rs
src/tests/simulation/tests/integration_tests/recovery/background_ddl.rs

 fix(stream): read exactly a single row if no snapshot read on barrier

---

ci/workflows/pull-request.yml
src/frontend/src/scheduler/plan_fragmenter.rs

- fix batch default scheduler parallelism
</details>

fix(batch): fix batch default scheduler parallelism

---

src/storage/src/hummock/compactor/mod.rs

chore(storage): enable check compaction result on dedicated compaction

---

src/common/src/util/future_utils/buffered_with_fence.rs
src/common/src/util/future_utils/mod.rs
src/common/src/util/mod.rs
src/stream/src/executor/project.rs

feat(stream): make Project expr evaluation concurrent (#14558)

---

src/common/src/config.rs
src/config/example.toml
src/storage/src/hummock/event_handler/uploader.rs
src/storage/src/hummock/store/local_hummock_storage.rs

chore: disable merge imm and memtable spill
