risingwavelabs/risingwave

- clippy.toml
- e2e_test/batch/functions/abs.slt.part
- proto/expr.proto
- src/common/src/types/decimal.rs
- src/common/src/types/interval.rs
- src/common/src/types/num256.rs
- src/common/src/types/ops.rs
- src/common/src/types/ordered_float.rs
- src/expr/src/vector_op/arithmetic_op.rs
- src/expr/src/vector_op/round.rs
- src/frontend/src/binder/expr/function.rs
- src/frontend/src/expr/pure.rs
- src/tests/regress/data/sql/float8.sql
Support PostgreSQL expression `sign` for `decimal` and `double precision` (Resolves #8900). Input numeral of other types would be implicitly casted to `double precision` as in PostgreSQL.
It does not map to rust `signum` directly:
| value | sign | signum | is_positive | is_negative | is_sign_positive | is_sign_negative | num_traits is_positive | num_traits is_negative |
|-|-|-|-|-|-|-|-|-|
| -0.0 | 0 | -1 | x | x | false | true | false | true |
| 0.0 | 0 | 1 | x | x | true | false | true | false |
| 0 | 0 | 0 | false | false | x | x | false | false |
Given that `num_traits::Signed` confuses between `is_positive` and …
> feat(expr): support `sign` and distinguish `is_positive` vs `is_sign_positive`

- src/meta/src/hummock/compaction/picker/min_overlap_compaction_picker.rs
- src/storage/hummock_test/src/compactor_tests.rs
The compact task will create iter for every sub-level in time. So we shall not select too much sub-level
</details>
> fix(compaction): avoid compaction task use too much memory

- src/stream/src/executor/exchange/permit.rs
- src/stream/src/lib.rs
Previously, if the sender is blocking on acquiring the permits, it won't get notified about the closing of the (inner unbounded) channel immediately. This may break the assumption that the error of actor exiting should be naturally propagated to its downstream and upstream.
In this PR, we close the permit semaphores on the drop of the receiver to resolve this problem. …
> fix(streaming): fail the sender of permit channel on receiver closed

- e2e_test/streaming/eowc/eowc_over_window.slt
- e2e_test/streaming/over_window/over_window/create.slt.part
- e2e_test/streaming/over_window/over_window/drop.slt.part
- e2e_test/streaming/over_window/over_window/mod.slt.part
- src/frontend/planner_test/tests/testdata/input/over_window_function.yaml
- src/frontend/planner_test/tests/testdata/output/over_window_function.yaml
- src/frontend/src/optimizer/plan_node/generic/over_window.rs
- src/frontend/src/optimizer/plan_node/logical_over_window.rs
- src/stream/src/executor/over_window/state/mod.rs
- src/stream/src/executor/over_window/state/row_number.rs
- Support general `row_number` window function that doesn't match TopN pattern
- ~~[ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details]~~(https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md)) …
> feat(over window): support general streaming `row_number` window function

- src/meta/src/barrier/progress.rs
- Recently, we used `rw_ddl_progress` to track the mview creation progress in customers' environment and found that it could be inaccurate in some cases. For example, when the mview contains a lot of joins and most of the tables are small tables and one or two tables are large tables, our `progress` will show `99%` all the time, because we assume each backfill actor has the same data volume, but that is not true. Therefore, we should calculate progress by `consumed_rows` / `upstream_total_key_count`.  …
> fix(meta): refine ddl progress based on consumed row

- Cargo.lock
- src/ctl/Cargo.toml
- src/ctl/src/cmd_impl.rs
- src/ctl/src/cmd_impl/debug.rs
- src/ctl/src/cmd_impl/debug/meta_store.rs
- src/ctl/src/lib.rs
- src/meta/src/lib.rs
A simple utility tool that can dump the current stored meta information from etcd, including worker, table, user, using the 
```
risectl debug dump --etcd-endpoints "localhost:2388" user
- kind: user
item:
id: 1
name: root
isSuper: true
canCreateDb: true
canCreateUser: true
canLogin: true
- kind: user
item:
id: 2
name: postgres
isSuper: true
canCreateDb: true
canCreateUser: true
canLogin: true
risectl debug dump --etcd-endpoints "localhost:2388" user -o json
[
{
"item": {
"canCreateDb": true,
"canCreateUser": true,
"canLogin": true,
"id": 1,
"isSuper": true,
"name": "root"
},
"kind": "user"
},
{
"item": {
"canCreateDb": …
```
> feat: dump etcd meta store in risectl

- ci/scripts/release.sh
- ci/workflows/integration-tests.yml
- disable integtarion test debezium mongo because it always fails now.
- install cyrus-sasl-devel in release build
> chore(ci): disable integtarion test debezium mongo && install cyrus-sasl-devel in release build

- integration_tests/postgres-cdc/postgres_prepare.sql
When creating two CDC tables with `publication.create.enable=true` (default value), each debezium connector will try to create the publication with the same name `rw_publication`. And the concurrent requests may lead to the second one connector fails to create the publication, thus the source db would not emit changes of the second CDC table.
To avoid the race condition, we should recommend users to create the publication on postgres in advance by themselves.
Test run passed:
https://buildkite.com/risingwavelabs/integration-tests/builds/188
related: https://github.com/risingwavelabs/risingwave/pull/10804 …
> fix(integration-test): create pg publication in advance to avoid race condition

- src/storage/src/hummock/iterator/forward_user.rs
This PR changes the logic in `UserIterator::next()` to return early if the key is already out of the provided key range. This can avoid unnecessary access on the range tombstones under some cases.
For exmaple, , if the key range of UserKeyIterator is `[0x0a, 0x0c)` and the current key is `0xff`, we will access range tombstones in `[0x0c, 0xff]` prior to this PR, which is a waste of work.
- …
> fix: return early in UserIterator::next() if key is already out of range

- src/utils/pgwire/src/pg_protocol.rs
- Since query log truncates sql, I think tracing span might also need to do so. Noticed via developing #10910, where I passed a BASE64 encoded binary in a SQL.
- Also add an `...(truncated)` indicator.
- Also replace some `format!` with `format_args`, which might reduce allocation.
- Error log still contains full sql.
```
2023-07-12T23:40:57.915277+02:00 ERROR risingwave_frontend::session: failed to handle sql:
INSERT INTO t VALUES (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), (1), …
```
> refactor(pgwire): truncate sql in tracing

- proto/meta.proto
- src/frontend/src/catalog/system_catalog/rw_catalog/mod.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_fragments.rs
- src/meta/src/rpc/service/stream_service.rs
as title
```
dev=> select * from rw_fragments;
fragment_id | table_id | distribution_type |      state_table_ids       | upstream_fragment_ids |       flags
-------------+----------+-------------------+----------------------------+-----------------------+--------------------
1 |     1001 | HASH              | {1001}                     | {2}                   | {MVIEW}
2 |     1001 | HASH              | {}                         | {}                    | {SOURCE,DML}
3 |     1002 | HASH              | {1003,1002}                | {1}                   | {MVIEW,CHAIN_NODE}
4 |     1004 | HASH              | {1005,1004} …
```
> feat: show flags in `rw_fragments`

- src/common/src/types/decimal.rs
- src/connector/src/parser/avro/util.rs
- src/connector/src/parser/unified/avro.rs
- src/expr/src/vector_op/round.rs
Fix #9417
Just like in PostgreSQL, the 2nd arg of `round` can now be negative, which means to round to the left of the decimal point.
> fix(expr): `round` to left of decimal point when 2nd arg is negative

- src/utils/runtime/src/lib.rs
- Remove `ENABLE_QUERY_LOG_FILE`, since `RW_QUERY_LOG_PATH` is more useful and general. No need to configure it statically.
- Don't create `slow_query.log` unconditionally, as I don't find any reason to do so. It can create garbage files everywhere and cause confusion.
- Enhance doc comments. …
> chore(log): don't create slow_query.log unconditionally

- src/connector/src/parser/json_parser.rs
- src/connector/src/parser/unified/util.rs
https://github.com/risingwavelabs/risingwave/issues/10840
It is the newly introduced cost ~18%:
</details>
> perf(source): optimize op for `json_parser`

- src/sqlparser/src/ast/mod.rs
- src/sqlparser/src/keywords.rs
- src/sqlparser/src/parser.rs
- src/sqlparser/tests/sqlparser_postgres.rs
This PR adds `create aggregate` syntax for user-defined aggregate functions.
The syntax is a mix of current `create function` and [postgres `create aggregate`](https://www.postgresql.org/docs/15/sql-createaggregate.html):
```sql
CREATE [ OR REPLACE ] AGGREGATE name ( [ argmode ] [ argname ] arg_data_type [ , ... ] ) # same as pg
[ RETURNS return_data_type ] [ APPEND ONLY ]
[ LANGUAGE language ] [ AS identifier ] [ USING LINK link ]; # same as function
```
Examples:
```sql
create aggregate sum(int) returns bigint
as sum using link 'http://localhost:8815';
create aggregate max(int) append only
as max using link …
```
> feat(parser): parse `create aggregate`

- src/frontend/planner_test/tests/testdata/input/tpch.yaml
- src/frontend/planner_test/tests/testdata/output/tpch.yaml
reference: https://github.com/dragansah/tpch-dbgen/tree/master/tpch-queries
```
Test #17 (id: tpch_q17) failed, SQL:
select
sum(l_extendedprice) / 7.0 as avg_yearly
from
lineitem,
part,
(select l_partkey as agg_partkey, 0.2 * avg(l_quantity) as avg_quantity from lineitem group by l_partkey) part_agg
where
p_partkey = l_partkey
and p_brand = 'Brand#13'
and p_container = 'JUMBO PKG'
and l_quantity < avg_quantity;
Error: unexpected stream_error: Not supported: streaming nested-loop join
HINT: The non-equal join in the query requires a nested-loop join executor, which could be very expensive to run. Consider rewriting the …
```
> chore: use original tpch

- src/connector/src/parser/common.rs
```
json_parser             time:   [297.47 ms 298.17 ms 298.88 ms]
change: [-11.671% -10.436% -9.4821%] (p = 0.00 < 0.05)
Performance has improved.
```
As shown from flamegraph this happens twice:
</details>
> perf(source): compare key once for `json_object_smart_get_value`

- src/tests/sqlsmith/src/sql_gen/types.rs
```
-- Failing SQL query:
--
  | CREATE MATERIALIZED VIEW m13 AS WITH with_0 AS (WITH with_1 AS (SELECT max(DISTINCT t_4.col_2) FILTER(WHERE false) AS col_0, sum0(DISTINCT t_4.col_1 ORDER BY t_4.col_1 DESC) FILTER(WHERE true) AS col_1 FROM m4 AS t_4 WHERE false GROUP BY t_4.col_2, t_4.col_1) SELECT (INT '-1909674191') AS col_0, CAST(NULL AS STRUCT<a DATE, b TIME>) AS col_1 FROM with_1 WHERE true) SELECT TIMESTAMP '2023-07-18 04:43:58' AS col_0, 'ZL8jMtunt8' AS col_1 FROM with_0;
  |  
  | ---- END
  |  
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failed { msg: Some("Error Reason:\nBind error: …
```
> fix(sqlsmith): do not generate `sum0`

- src/tests/sqlsmith/src/sql_gen/types.rs
Recently fuzz test failed. Reason was that it treated a `Sum` expression as `Sum(Int64) -> Int64`, instead of `Sum(Int64) -> Numeric`, and subsequently the sql could not be bound.
We can just ban `Sum(Int64) -> Int64` since it is just used internally by 2phase agg.
</details>
> fix(sqlsmith): ban `Sum(Int64) -> Int64`

- e2e_test/streaming/temporal_join/temporal_join_with_index.slt
- proto/plan_common.proto
- src/common/src/catalog/physical_table.rs
- src/frontend/planner_test/tests/testdata/input/temporal_join.yaml
- src/frontend/planner_test/tests/testdata/output/temporal_join.yaml
- src/frontend/src/optimizer/plan_node/logical_join.rs
- src/stream/src/executor/temporal_join.rs
- src/stream/src/from_proto/temporal_join.rs
- Support index selection for temporal join. Related issue. https://github.com/risingwavelabs/risingwave/issues/8123
```sql
create table stream(id1 int, a1 int, b1 int) APPEND ONLY;
create table version(id2 int, a2 int, b2 int, primary key (id2));
create index idx on version (a2);
CREATE materialized VIEW v AS
SELECT id1,
a1,
id2,
a2
FROM stream
LEFT JOIN idx
FOR SYSTEM_TIME AS OF PROCTIME() ON b1 = b2
AND a1 = a2;
```
- Support index selection for …
> feat(optimizer, stream): support index selection for temporal join

- e2e_test/batch/aggregate/grouping_sets.slt.part
- e2e_test/streaming/grouping_sets.slt
- proto/expr.proto
- src/expr/src/agg/def.rs
- src/frontend/planner_test/tests/testdata/input/grouping_sets.yaml
- src/frontend/planner_test/tests/testdata/output/grouping_sets.yaml
- src/frontend/src/expr/agg_call.rs
- src/frontend/src/expr/mod.rs
- src/frontend/src/optimizer/plan_node/logical_agg.rs
- src/frontend/src/optimizer/rule/grouping_sets_to_expand_rule.rs
- Support `Grouping` agg call. Related issue https://github.com/risingwavelabs/risingwave/issues/9284
- PG Grouping operations doc. https://www.postgresql.org/docs/9.5/functions-aggregate.html
- > Grouping operations are used in conjunction with grouping sets (see [Section 7.2.4](https://www.postgresql.org/docs/9.5/queries-table-expressions.html#QUERIES-GROUPING-SETS)) to distinguish result rows. The arguments to the GROUPING operation are not actually evaluated, but they must match exactly expressions given in the GROUP BY clause of the associated query level. Bits are assigned with the rightmost argument being the …
> feat(stream,batch,optimizer): support grouping agg call

- src/stream/src/executor/backfill/utils.rs
- It seems this bug is introduced by a previous refactoring PR. Need to cherry-pick to the release.
</details>
> fix(stream): fix mark_chunk_inner in backfill

- src/utils/pgwire/src/pg_message.rs
- src/utils/pgwire/src/pg_protocol.rs
Avoid panic mentioned in #10827.
Note this PR does not intend to resolve the root cause of failed writes. It just fails the offending connection gracefully rather than kills the whole frontend node. Details are discussed in that issue.
Implementation is mostly substitution:
* `return true` -> `return None` for early termination
* `.unwrap()` -> `.ok()?` to terminate on `Err`/`None`
E2E test to demonstrate the expected behavior after fix is not included because a good client library refuses to send such invalid request. The PR was tested by returning a dummy error containing `\0` on simple queries like `select 1 + 1;` …
> fix(pgwire): terminate connection rather than panic when write fails

- Cargo.lock
- src/bench/Cargo.toml
- src/bench/file_cache_bench/main.rs
- src/utils/runtime/src/lib.rs
So that we don't need to depend on `opentelemetry-jaeger`.
- Close #11062
- Close #11066
</details>
> refactor: reuse logger initialization in file-cache bench

- src/common/src/session_config/mod.rs
For pgadmin #11048 and tableau #10459
As of now, `client_min_messages` accepts any value but is not effective, while `client_encoding` only accepts utf8.
</details>
> feat(frontend): stub session `client_min_messages` and `client_encoding`

- Cargo.toml
- src/tests/simulation/tests/integration_tests/scale/nexmark_q4.rs
`cargo nextest` has been [failing to detect](https://buildkite.com/risingwavelabs/main/builds/4321#01885d6e-de8e-450e-a867-46c9d3794c74) the deterministic integration tests after #10029. It turns out that `debug="line-tables-only"` is not compatible. Switch to `debug=1` for `ci-sim` profile as a workaround.
- Other (please specify in the release note …
> fix(test): enable deterministic integration tests

- src/utils/runtime/src/lib.rs
Use [`Full` format](https://docs.rs/tracing-subscriber/0.3.17/tracing_subscriber/fmt/format/struct.Full.html) instead of `Pretty` (#10633) for logs in local deployments to make it less verbose.
> This formatter shows the span context before printing event data. Spans are displayed including their names and fields.
```
2023-07-24T11:11:22.642603+08:00 DEBUG actor{otel.name="Actor 29" actor_id=29 prev_epoch=4779742372823040 curr_epoch=4779742438359040}:executor{otel.name="RowIdGenExecutor 1D00000003 (actor 29, operator 3)" actor_id=29}:executor{otel.name="SourceExecutor 1D000027A7 (actor 29, operator 10151)" actor_id=29}: …
```
> chore(runtime): replace `Pretty` with `Full` format

- src/common/src/config.rs
- src/config/example.toml
- src/meta/src/hummock/compaction/compaction_config.rs
- src/meta/src/hummock/manager/compaction_group_manager.rs
- src/meta/src/lib.rs
- src/meta/src/manager/env.rs
Previously default compaction config used by meta node is hard-coded, and can only be updated by risectl afterwards. Thus it is inconvenient for setting compaction config for new compaction group created by group splitting.
This PR allows setting default compaction config via config file. Each new compaction group will use this config.
**Note that below compaction configs are not available in config file, i.e. they are still hard-coded only.** Because I've not verified whether it's correct or necessary for those configs to have different values across compaction groups.
- max_level
- compression_algorithm
- …
> refactor(config): support setting default compaction config in config file

- e2e_test/batch/functions/to_timestamp.slt.part
- src/common/src/types/timestamptz.rs
- src/expr/src/expr/build.rs
- src/expr/src/expr/expr_to_timestamp_const_tmpl.rs
- src/expr/src/vector_op/to_timestamp.rs
- src/frontend/src/expr/session_timezone.rs
Fix #7780 
Backward compatibility: The old `to_timestamp(varchar, varchar) -> timestamp` would not be generated by frontend, but is still accepted by backend, despite lacking the constant template optimization.
Tested locally: (1) create a mview with `to_timestamp` on main branch; (2) kill the cluster, switch to PR branch, and start cluster; (3) query the mview, insert new rows to its upstream and query again
Given the initial request to support `to_timestamp` comes from superset, it is likely this expr is not used in a mview yet. If we do find it is necessary to optimize this legacy variant with constant template as …
> fix(expr): `to_timestamp` should return timestamptz

- src/connector/src/aws_auth.rs
- src/connector/src/aws_utils.rs
- src/connector/src/source/filesystem/s3/enumerator.rs
resolve #11086 
access_key and corresponding secret_key become a must for all aws auth components. 
</details>
> fix: enforce user must specify access_key and secret_key using aws auth

- src/frontend/src/optimizer/plan_visitor/cardinality_visitor.rs
As title, previously table completion in psql will cause panic in frontend. It generates a sql as follows:
```sql
SELECT pg_catalog.quote_ident(c.relname) FROM pg_catalog.pg_class AS c WHERE c.relkind IN ('r', 'S', 'v', 'm', 'f', 'p') AND SUBSTRING(pg_catalog.quote_ident(c.relname) FROM 1 FOR 3) = 'xxx' AND pg_catalog.pg_table_is_visible(c.oid) AND c.relnamespace <> (SELECT oid FROM pg_catalog.pg_namespace WHERE nspname = 'pg_catalog') UNION SELECT pg_catalog.quote_ident(n.nspname) || '.' FROM pg_catalog.pg_namespace AS n WHERE SUBSTRING(pg_catalog.quote_ident(n.nspname) || '.' FROM 1 FOR 3) = 'xxx' AND (SELECT …
```
> fix: fix panic when visit predicate meet empty output col idx in pg_namespace

- proto/catalog.proto
- src/connector/src/sink/catalog/desc.rs
- src/connector/src/sink/catalog/mod.rs
- src/frontend/src/catalog/index_catalog.rs
- src/frontend/src/catalog/source_catalog.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_indexes.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_materialized_views.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_relation_info.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_sinks.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_sources.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_tables.rs
- src/frontend/src/catalog/table_catalog.rs
- src/frontend/src/handler/create_index.rs
- src/frontend/src/handler/create_source.rs
- src/frontend/src/handler/create_table.rs
- src/frontend/src/optimizer/plan_node/stream_materialize.rs
- src/frontend/src/optimizer/plan_node/utils.rs
- src/meta/src/manager/catalog/mod.rs
- src/meta/src/manager/streaming_job.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/stream_manager.rs
- src/storage/src/filter_key_extractor.rs
- src/tests/compaction_test/src/delete_range_runner.rs
```
dev=> select name,initialized_at,created_at from rw_sources;
name |        initialized_at         |          created_at
------+-------------------------------+-------------------------------
s    | 2023-07-25 10:53:30.128+00:00 | 2023-07-25 10:53:30.130+00:00
(1 row)
dev=> select name,initialized_at,created_at from rw_sinks;
name |        initialized_at         |          created_at
------+-------------------------------+-------------------------------
ss   | 2023-07-25 10:53:32.176+00:00 | 2023-07-25 10:53:43.238+00:00
(1 row)
dev=> select name,initialized_at,created_at from rw_tables;
name |        initialized_at …
```
> feat: add optional `created_at` and `initialized_at` for rw relations

- src/expr/macro/src/gen.rs
- src/expr/macro/src/lib.rs
- src/expr/macro/src/parse.rs
- src/expr/src/agg/mod.rs
- src/expr/src/expr/build.rs
- src/expr/src/expr/expr_to_timestamp_const_tmpl.rs
- src/expr/src/sig/agg.rs
- src/expr/src/sig/func.rs
- src/expr/src/sig/mod.rs
- src/expr/src/sig/table_function.rs
- src/expr/src/table_function/mod.rs
- src/expr/src/vector_op/array_length.rs
- src/expr/src/vector_op/cardinality.rs
- src/expr/src/vector_op/position.rs
- src/expr/src/window_function/state/mod.rs
- src/frontend/src/expr/type_inference/func.rs
- src/tests/sqlsmith/src/sql_gen/types.rs
This PR introduces `deprecated` attribute to `#[function]` macro. Deprecated functions should not be used in the frontend, but for backward compatibility, they are still in the signature map and are available in the backend.
Current deprecated functions:
- to_timestamp1(varchar, varchar) -> timestamp
- array_length(list) -> int64
- cardinality(list) -> int64
- strpos(varchar, varchar) -> int32
With this feature, can we remove these cases from `infer_type_for_special`? @xiangjinwu
> feat(expr): introduce `deprecated` to `#[function]` macro

- src/frontend/src/binder/expr/column.rs
Related #11222 
We return an empty string here to support DataGrip (tested).
</details>
> fix(binder): return an empty string for CTID

- src/frontend/src/handler/create_table.rs
- src/sqlparser/src/parser.rs
Some of our users need to define watermark on table.
</details>
> feat: open append only table in release

- Cargo.lock
- Cargo.toml
After upgrading tonic to v0.9 #11088, meta service failed to get data larger than 4MB from etcd. Etcd-client hasn't exposed any interface to change the limit. So we have to fork etcd-client and remove this limit.
https://github.com/risingwavelabs/etcd-client/commit/d55550a182f2119e39e64858771468e1b26f6777
> fix(etcd): patch etcd-client to unlimit message size

- e2e_test/source/basic/kafka.slt
- src/connector/src/common.rs
- src/connector/src/sink/kafka.rs
- src/connector/src/source/kafka/enumerator/client.rs
- src/connector/src/source/kafka/mod.rs
- src/connector/src/source/kafka/source/reader.rs
Expose these configurations for the convenience of debugging in the future.
I'll set better parameters in a separate PR, after sufficient performance test, etc. 
related #10888 
allow user specify kafka params in rw SQL (description in details available [here](https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md))
valid for both source and sink
| config name in RW | config name in Kafka | type |
|--|--|--|
| `properties.message.max.bytes` | …
> feat(kafka source): expose rdkafka fetch params

- e2e_test/ddl/system_columns.slt
- src/frontend/src/binder/expr/column.rs
- src/frontend/src/catalog/mod.rs
- src/frontend/src/handler/create_mv.rs
Resolves #11242
https://www.postgresql.org/docs/current/ddl-system-columns.html
PostgreSQL reserves `tableoid`, `xmin`, `cmin`, `xmax`, `cmax`, `ctid` as column names.
|context|PostgreSQL|RisingWave|
|-|-|-|
|table column|err|err|
|mview column|err|err|
|composite type field|ok|ok|
|batch select alias|ok|err<sup>1</sup>|
|view column|ok|ok<sup>2</sup>|
|source column<sup>3</sup>||err|
|avro/proto source column||4|
|sink column||ok<sup>2</sup>|
1. Just a side effect of code reuse. No decision was made yet but being conservative.
2. Allowed but only when not using select alias. For example, `create view(ctid) as select 1` …
> feat(binder): reserve system column names

- .git-blame-ignore-revs
- ci/workflows/pull-request.yml
It was removed in #8852. Add back because it's too frequent and thus manual retry isn't friendly. I've checked some failures on recent PRs and only found 255, so did not add -1.
It *might be possible* that 255 is not "agent terminated", but I've never met it.
Only added retry for PRs first, because it caused most troubles. For other pipelines, maybe it's worth checking errors and retrying manually.
> Exited with status 255 (after intercepting the agent’s termination signal, sent because the agent was stopped)
> ci: add back auto-retry for status 255

- src/udf/python/risingwave/udf.py
```
> python3 e2e_test/udf/test.py
added function: int_42, corresponding SQL:
CREATE FUNCTION int_42() RETURNS INT AS 'int_42' USING LINK 'http://0.0.0.0:8815';
added function: gcd, corresponding SQL:
CREATE FUNCTION gcd(INT,INT) RETURNS INT AS 'gcd' USING LINK 'http://0.0.0.0:8815';
added function: gcd3, corresponding SQL:
CREATE FUNCTION gcd3(INT,INT,INT) RETURNS INT AS 'gcd3' USING LINK 'http://0.0.0.0:8815';
added function: series, corresponding SQL:
CREATE FUNCTION series(INT) RETURNS TABLE(output INT) AS 'series' USING LINK 'http://0.0.0.0:8815';
added function: split, corresponding SQL:
CREATE FUNCTION …
```
> feat(udf): print CREATE FUNCTION in the py server's log

- src/common/src/config.rs
- src/config/example.toml
- src/meta/src/hummock/manager/gc.rs
- src/meta/src/hummock/manager/mod.rs
- src/meta/src/hummock/vacuum.rs
- src/meta/src/lib.rs
- src/meta/src/manager/env.rs
- src/meta/src/rpc/service/hummock_service.rs
This PR enables automatic hummock full GC. Previously user need to trigger full GC via risectl manually. 
Detailed changes are
- Move GC code from VacuumManager to HummockManager, so that hummock timer can invoke full GC easily.
- Add `full_gc_interval_sec` config.
- Reduce `min_sst_retention_time_sec` from 7 days to 1 days.
- Other (please specify in …
> refactor(meta): enable periodic full GC

- src/frontend/planner_test/tests/testdata/input/subquery.yaml
- src/frontend/planner_test/tests/testdata/output/subquery.yaml
- src/frontend/src/binder/relation/mod.rs
- src/frontend/src/optimizer/plan_visitor/plan_correlated_id_finder.rs
- Ban correlated input ref in project set or table function.
</details>
> fix(optimizer): ban subquery in project set and table function

- src/frontend/src/binder/expr/value.rs
- src/frontend/src/utils/with_options.rs
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/src/ast/statement.rs
- src/sqlparser/src/ast/value.rs
- src/sqlparser/src/parser.rs
- src/sqlparser/src/tokenizer.rs
- src/sqlparser/tests/sqlparser_common.rs
As explained in #11260 and https://github.com/risingwavelabs/risingwave/pull/11195#discussion_r1274553446.
Close #11260.
</details>
> refactor(frontend): escape `E'..'` in tokenizer

- src/frontend/planner_test/tests/testdata/input/array.yaml
- src/frontend/planner_test/tests/testdata/output/array.yaml
- src/frontend/src/binder/expr/value.rs
Fixes #11351 `array[]::timestamptz[]`
Fixes #11352 `array[]::STRUCT<s1_c1_integer INT>[]`
The problem originated from this line:
https://github.com/risingwavelabs/risingwave/blob/9f73f907fcc8fce275332e070001ecc88043e3ac/src/frontend/src/binder/expr/value.rs#L119
Casting from a dummy `varchar[]` does not work for timestamptz https://github.com/risingwavelabs/risingwave/issues/7175#issuecomment-1381314486 or struct #7369 currently.
The offending assumption was introduced by #5402 but a later enhancement #6096 can actually handle it without the assumption. So the issues are fixed simply by removing the special handling …
> fix(binder): cast of empty array literal

- ci/workflows/docker.yml
- ci/workflows/main-cron.yml
- ci/workflows/main.yml
- ci/workflows/pull-request.yml
In #11304 , the auto-retry(exit code 255) of pull-request workflow was added back.
Here I add back the retry of main, main-cron and docker workflows, and also retry when the exit code is -1.
> ci: add back auto-retry for main and docker pipeline

- integration_tests/kinesis-s3-source/docker-compose.yml
- src/frontend/planner_test/tests/testdata/output/emit_on_window_close.yaml
- src/frontend/planner_test/tests/testdata/output/generated_columns.yaml
- src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml
- src/frontend/planner_test/tests/testdata/output/watermark.yaml
- src/frontend/planner_test/tests/testdata/output/window_join.yaml
- src/frontend/src/optimizer/plan_node/stream_source.rs
- src/frontend/src/optimizer/plan_node/stream_watermark_filter.rs
Fix #11412
- ~~[ ] My PR contains user-facing changes.~~
Please keep the types …
> fix(watermark): fix watermark-related panic when there's generated column on source definition

- src/expr/macro/src/gen.rs
- src/expr/src/lib.rs
- src/prost/src/lib.rs
- src/storage/src/store_impl.rs
It's annoying when developing. Not sure why it did not happen previously.
</details>
> fix: warnings on naming from rust analyzer in generated code

- e2e_test/batch/basic/union.slt.part
- src/frontend/src/binder/select.rs
- src/frontend/src/binder/set_expr.rs
- Related issue https://github.com/risingwavelabs/risingwave/issues/7768 https://github.com/risingwavelabs/risingwave/issues/7577
- Currently only support type alignment between `Select` and `Select` for set operation.
</details>
> feat(binder): support align types for set operation

- src/common/src/session_config/search_path.rs
- src/frontend/src/binder/expr/function.rs
Fix #11470 
The PR includes a minor fix, which is not the root cause.
</details>
> fix(binder): don't error when search_path is empty

- src/common/src/session_config/mod.rs
configs for pg_dump
</details>
> feat(config): support dummy synchronize_seqscans,statement_timeout,lock_timeout,row_security

- src/frontend/src/binder/relation/table_or_source.rs
It is especially useful when the system table's sql can not match the schema(
</details>
> feat(binder): schema check when binding view

- src/storage/backup/integration_tests/test_query_backup.sh
> chore(test): add log to help debug a flaky test

- src/meta/src/stream/source_manager.rs
cherry-pick to v1.1 
</details>
> fix: failed source should not block the startup of the meta

- java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java
Better handling on jdbc sink drop. Currently implementation will get null pointer exception.
</details>
> fix(jdbc): fix jdbc sink drop

- src/common/src/system_param/mod.rs
- src/connector/src/parser/unified/avro.rs
- src/connector/src/sink/clickhouse.rs
- src/connector/src/sink/coordinate.rs
- src/connector/src/source/kafka/private_link.rs
- src/frontend/src/handler/create_connection.rs
- src/frontend/src/handler/create_table.rs
- src/frontend/src/session.rs
- src/meta/src/rpc/cloud_provider.rs
- src/rpc_client/src/lib.rs
- src/sqlparser/src/ast/statement.rs
- src/stream/src/common/log_store/in_mem.rs
- src/stream/src/executor/source/fs_source_executor.rs
- src/stream/src/executor/source/source_executor.rs
- src/stream/src/task/stream_manager.rs
Fix https://github.com/risingwavelabs/risingwave/issues/11580 https://github.com/risingwavelabs/risingwave/issues/11445
</details>
> fix: fix incorrect usage of ok_or with anyhow

- src/stream/src/executor/backfill/no_shuffle_backfill.rs
As per title. Thanks to @Little-Wallace for discovering and reporting this bug. Found in https://github.com/risingwavelabs/risingwave/pull/11398.
The observation was that multiple rows with the same PK were inserted into upstream mview.
Consider the following sequence of events:
1. Upstream update for row with `pk=123`. -------> Upstream buffer contains `pk=123`
2. Snapshot read no progress in this epoch.
3. Barrier (and upstream buffer not cleaned)
4. new snapshot with current_pos=None. Pk will be at least `123`.
5. snapshot read with 123, flush `pk=123` to downstream.
6. No more snapshot. 
7. Flush remaining rows in …
> fix(stream): clear upstream buffer if no snapshot progress

- src/stream/src/executor/backfill/no_shuffle_backfill.rs
Reverts risingwavelabs/risingwave#11633
Realize it's not actually needed. The bug was caused by a refactoring, that is not present in `v1.1`. So we can leave it out.
> Revert "chore(stream): cherry pick #11625 into v1.1-rc"

- Cargo.toml
- src/tests/simulation/Cargo.toml
Resolver 2 means dev-dependency are not unified.
https://rust-lang.github.io/rfcs/2957-cargo-features2.html#feature-unification
This needs to be opted-in. And there's a warning when it's not specified in latest toolchain:
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
Please …
> build: add resolver=2 to workspace

- src/meta/src/stream/stream_manager.rs
Fix #11638 . `unimplemented!` in `wait_epoch_commit` might cause uncertain recovery while running the unit test.
</details>
> fix: fix flaky drop mview unit test

- e2e_test/batch/functions/pow.slt.part
- e2e_test/batch/functions/scale.slt.part
- proto/expr.proto
- src/common/src/array/arrow.rs
- src/common/src/types/decimal.rs
- src/expr/src/expr/expr_literal.rs
- src/expr/src/vector_op/arithmetic_op.rs
- src/frontend/src/binder/expr/function.rs
- src/frontend/src/expr/pure.rs
https://www.postgresql.org/docs/15/functions-math.html
`trim_scale` enables the `1.20` -> `1.2` normalization.
Support decimal expressions: `scale`, `min_scale` and `trim_scale`.
</details>
> feat(expr): `scale`, `min_scale` and `trim_scale` for decimal

- Makefile.toml
- src/cmd_all/src/playground.rs
- src/compute/src/lib.rs
- src/meta/src/lib.rs
- src/meta/src/rpc/server.rs
- src/risedevtool/common.toml
- src/risedevtool/src/bin/risedev-compose.rs
- src/risedevtool/src/bin/risedev-dev.rs
- src/risedevtool/src/lib.rs
- src/risedevtool/src/risedev_env.rs
Also generate `risedev-env` for playground launches, so that we can leverage `risedev ctl` or `risedev psql` for it. 
Also some minor fixes:
- Reuse the logic for sourcing env vars for `ctl` and `psql`.
- Do not `unwrap` the joining result of the dashboard task.
- Suggest users about other `risedev` commands only if launched with RiseDev.
- Follows the configuration of all-in-one binary when launching risectl. …
> feat(risedev): generate `env` file also for playground

- integration_tests/debezium-mongo/docker-compose.yaml
- integration_tests/debezium-mysql/docker-compose.yml
- integration_tests/debezium-postgres/docker-compose.yml
- integration_tests/debezium-sqlserver/docker-compose.yml
- Modify the docker-compose files in the `integration_tests/debezium-mysql`, `integration_tests/debezium-postgres`, `integration_tests/debezium-mongo`, and `integration_tests/debezium-sqlserver` directories
- Add and remove various services, such as `compactor-0`, `compute-node-0`, `etcd-0`, `frontend-node-0`, `grafana-0`, `meta-node-0`, `minio-0`, `prometheus-0`, `message_queue`, `datagen`, `register-mongodb-connector`, and `kafka-connect-ui`
- Update environment variables, ports, volumes, and healthcheck configurations for the services
- Remove the `risingwave` service from the Docker compose files
- Adjust service dependencies and volumes
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa …
> chore: unify docker compose from integration test to unified settings

- e2e_test/batch/catalog/pg_size.slt.part
- src/frontend/src/binder/expr/function.rs
> feat: support pg_relation_size

- src/frontend/planner_test/tests/testdata/input/limit.yaml
- src/frontend/planner_test/tests/testdata/output/limit.yaml
- src/frontend/src/optimizer/plan_node/logical_limit.rs
- Convert `LogicalLimit` into `StreamTopN` for streaming queries instead of throwing an error.
- Support using limit clauses in streaming queries.
</details>
> feat(optimizer): support streaming query with limit clause

- src/connector/src/parser/json_parser.rs
- src/connector/src/parser/unified/json.rs
As explained in #10772. Now we can parse
```json
{
"nested": "{\"v1\": 10, \"v2\": \"hello\"}"
}
```
as `CREATE SOURCE .. (nested struct<v1 int, v2 varchar>) FORMAT JSON`.
Close #10772.
Support parsing "string containing JSON" as a struct type.
> feat(connector): support parsing "string containing JSON" as a struct type

- src/common/src/config.rs
- src/config/example.toml
- src/meta/src/hummock/manager/compaction_group_manager.rs
- src/meta/src/hummock/manager/mod.rs
- src/meta/src/hummock/manager/tests.rs
- src/meta/src/manager/env.rs
- src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
Fix two problem
* split several small group
* split several state-table to one group. For example: we split state-table 1 and 5 to group-4. And then we split state-table 3 to group-4. There may exist a sstable with table-id [1, 5] and the new sstable with table-id 3 would overlap with it. This problem may cause iterator can not read the correct data
We check whether need to split a small group by these code:
```rust
is_low_write_throughput = window_total_size
< (HISTORY_TABLE_INFO_WINDOW_SIZE as u64)
* self.env.opts.min_table_split_write_throughput;
```
But there may be some empty write between we just create the table …
> fix(meta): fix split  group

- e2e_test/batch/catalog/pg_type.slt.part
- src/common/src/types/postgres_type.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_types.rs
Generate the PostgreSQL-compatible DataType info functions from a single macro:
* `common::types::postgres_type`
* `type_len`
* `from_oid`
* `to_oid`
* `pg_name`
* `frontend::catalog::system_catalog::rw_catalog::rw_types`
* `RW_TYPE_DATA`
Despite the intention of being an equivalent refactor, some minor logic fixes / changes are included:
* `type_len` of `Interval` fixed from `-1` to `16`, which is true in both PostgreSQL and RisingWave
* `from_oid` of `time[]` fixed from `1266` to `1183`, where `1266` is actually the discouraged `timetz`
* `from_oid` of `text[]` (`1009`) in addition to existing `text` (`25`)
More …
> refactor(common): unified macro for pg-compatible data type info

- src/meta/src/stream/scale.rs
- src/meta/src/stream/source_manager.rs
as title, made some adjustments to the annoying logs and extended the tick period of the source worker to 30 seconds.
----
Code changes in `scale.rs`, `source_manager.rs`, and `ConnectorSourceWorker`
**Summary:** This pull request introduces several code changes across multiple files. In the `scale.rs` file, the `reallocate_splits` function now accepts an additional parameter `fragment_id`. The `DEFAULT_TICK_TIMEOUT` constant has been removed from the `source_manager.rs` file. The `ConnectorSourceWorker` struct now includes a new constant `DEFAULT_SOURCE_WORKER_TICK_INTERVAL`. Additionally, the `diff_splits` function …
> chore: refine log & timeout in SourceManager

- Cargo.lock
- ci/scripts/check.sh
```
Crate:     rustls-webpki
--
  | Version:   0.101.3
  | Title:     rustls-webpki: CPU denial of service in certificate path building
  | Date:      2023-08-22
  | ID:        RUSTSEC-2023-0053
  | URL:       https://rustsec.org/advisories/RUSTSEC-2023-0053
  | Severity:  7.5 (high)
  | Solution:  Upgrade to >=0.100.2, <0.101.0 OR >=0.101.4
```
#11842 …
> chore: bump `rustls-webpki` & temporarily ignore security vulnerability

- e2e_test/ddl/show.slt
- src/frontend/planner_test/tests/testdata/output/batch_index_join.yaml
- src/frontend/planner_test/tests/testdata/output/distribution_derive.yaml
- src/frontend/planner_test/tests/testdata/output/index_selection.yaml
- src/frontend/planner_test/tests/testdata/output/temporal_join.yaml
- src/frontend/src/handler/create_index.rs
- src/frontend/src/handler/describe.rs
- Change index default distributed by column from whole index columns into the first index column., so that users can always benefit from the batch lookup join when they use the prefix columns of the index.
-  Change index default distributed by column from whole index columns into the first index column.
</details>
> feat(frontend): change index default distributed by columns

- src/connector/src/common.rs
as title
resolve #11910 
add a new property for kafka client (validate for both source and sink but only kafka)
* `properties.client.id`: Optional, String, as client identifier, have no effect on runtime settings. 
</details>
> feat: add new props `client.id` for kafka

- src/expr/src/expr/expr_binary_nullable.rs
- src/frontend/planner_test/tests/testdata/input/cse_expr.yaml
- src/frontend/planner_test/tests/testdata/output/cse_expr.yaml
- src/frontend/src/optimizer/plan_expr_visitor/expr_counter.rs
Fix / improve:
* SomeAllExpression are no longer broken up in the middle. Fixes #11766
* `coalesce` is also a short-circuit expr that should not have children extracted, just like `case when`
* `and` / `or` are not guaranteed to have short-circuit behavior. Actually other optimizer rules already break it (in both PostgreSQL and RisingWave).
* Allows `coalesce` and `case when` to be extracted as sub-expression in whole.
Limitation:
* In SomeAllExpression `v op SOME(arr)`, we could attempt to extract lhs `v` or rhs `arr`. But this is not done. It is [a little bit …
> fix(optimizer): common sub-expression extraction on special exprs

- src/frontend/src/catalog/system_catalog/rw_catalog/rw_ddl_progress.rs
- src/frontend/src/meta_client.rs
- src/frontend/src/test_utils.rs
- src/stream/src/executor/backfill/arrangement_backfill.rs
```
ddl_id |                 ddl_statement                 | progress |        initialized_at
--------+-----------------------------------------------+----------+-------------------------------
1002 | CREATE MATERIALIZED VIEW m AS SELECT * FROM t | 0.00%    | 2023-08-29 11:30:12.623+00:00
(1 row)
```
> feat: add `initialized_at` to ddl_progress

- e2e_test/source/cdc/cdc.load.slt
- src/common/src/session_config/mod.rs
- src/stream/src/executor/backfill/cdc_backfill.rs
- Seems CDC backfill is not quite stable right now, disable it by default (enabled in CI and integration test).
- Enable more logs
</details>
> chore: set default value of cdc_backfill to false

- e2e_test/batch/basic/func.slt.part
- proto/expr.proto
- src/expr/src/expr/build.rs
- src/expr/src/expr/expr_regexp.rs
- src/expr/src/expr/expr_regexp_count.rs
- src/expr/src/expr/mod.rs
- src/frontend/src/binder/expr/function.rs
- src/frontend/src/expr/pure.rs
- src/frontend/src/expr/type_inference/func.rs
resolve #11735
support `regexp_count`
</details>
> feat(expr): add `regexp_count`

- src/common/src/util/chunk_coalesce.rs
- src/storage/src/table/mod.rs
- src/stream/src/executor/backfill/arrangement_backfill.rs
- src/stream/src/executor/backfill/no_shuffle_backfill.rs
- src/stream/src/executor/backfill/upstream_table/snapshot.rs
- src/stream/src/executor/backfill/utils.rs
Sqlsmith found a bug in arrangement backfill where the same row is read twice in snapshot. That's because initial buffer is not flushed.
To be defensive, the same is done for no_shuffle_backfill, although it's not strictly necessary.
Additionally, we also refactor some interfaces for `DataChunkBuilder`, making sure they are safe.
</details>
> refactor(common): Use safe interfaces for `DataChunkBuilder`

- Cargo.lock
- src/connector/Cargo.toml
- src/connector/src/common.rs
#12040
exactly the same issue as https://github.com/loyd/clickhouse.rs/issues/58
Need to test it with Clickhouse Cloud
</details>
> fix: clickhouse https url

- proto/meta.proto
- proto/stream_plan.proto
- src/common/src/config.rs
- src/common/src/system_param/mod.rs
- src/common/src/system_param/reader.rs
- src/config/example.toml
- src/meta/src/backup_restore/restore.rs
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/recovery.rs
- src/meta/src/barrier/schedule.rs
- src/meta/src/model/barrier.rs
- src/meta/src/rpc/service/scale_service.rs
- src/meta/src/stream/scale.rs
- src/meta/src/stream/stream_manager.rs
- src/stream/src/executor/chain.rs
- src/stream/src/executor/dml.rs
- src/stream/src/executor/mod.rs
- src/stream/src/executor/source/fs_source_executor.rs
- src/stream/src/executor/source/source_executor.rs
- src/stream/src/executor/values.rs
- src/tests/simulation/src/cluster.rs
- src/tests/simulation/src/ctl_ext.rs
- src/tests/simulation/tests/integration_tests/recovery/mod.rs
- src/tests/simulation/tests/integration_tests/recovery/pause_on_bootstrap.rs
> feat(meta): add system parameter `pause_on_next_bootstrap` (cherry-pick #11936)

- docs/developer-guide.md
- src/common/Cargo.toml
- src/common/src/array/data_chunk.rs
- src/common/src/array/stream_chunk.rs
- src/stream/src/executor/dispatch.rs
- src/stream/src/executor/merge.rs
- src/stream/src/executor/receiver.rs
- src/stream/src/executor/wrapper/trace.rs
- src/stream/src/task/barrier_manager.rs
- src/stream/src/task/barrier_manager/managed_state.rs
- src/stream/tests/integration_tests/snapshot.rs
- src/utils/runtime/src/logger.rs
- Reconstruct more traces into `events::stream` target. For example, developers can launch the developing cluster with `RUST_LOG=events::stream::message::chunk=trace` to get all chunks printed in the logs.
- Log the chunks with the field name of each column.
- Refactor `Chunk::to_pretty_string` to `Chunk::to_pretty` returning `impl Display`. …
> refactor(streaming): better traces for development

- src/stream/src/executor/over_window/over_partition.rs
Avoid unnecessary sentinel nodes on cache initialization.
- ~~[ ] My PR contains critical fixes that are necessary to be merged into the …
> perf(over window): fix over window performance degradation after #11576

- src/rpc_client/src/stream_client.rs
The response of barrier_complete RPC can be very large due to `synced_sstables` field, which is mostly compromised of large storage keys.
For example, this source can reproduce a large response size failing the barrier collection.
```
create table t_large_key (k varchar, v int, primary key(k)) with (
connector = 'datagen',
fields.k.length = 4194304,
datagen.rows.per.second='1',
datagen.split.num = '1'
);
``` …
> chore(rpc): set message size to max for stream client

- src/compute/src/server.rs
- src/storage/compactor/src/server.rs
- src/storage/hummock_test/src/compactor_tests.rs
- src/storage/hummock_test/src/sync_point_tests.rs
- src/storage/src/hummock/compactor/compaction_utils.rs
- src/storage/src/hummock/compactor/compactor_runner.rs
- src/storage/src/hummock/compactor/context.rs
- src/storage/src/hummock/compactor/mod.rs
- src/storage/src/hummock/compactor/shared_buffer_compact.rs
- src/storage/src/hummock/event_handler/hummock_event_handler.rs
- src/storage/src/hummock/mod.rs
- src/tests/compaction_test/src/delete_range_runner.rs
> refactor(compaction): remove meta client from compactor context

- src/stream/src/from_proto/over_window.rs
cherry pick https://github.com/risingwavelabs/risingwave/pull/12110
</details>
> chore(cherry-pick): handle missing cache_policy field in OverWindow

- src/connector/src/sink/nats.rs
In previous code, we add [`context`](https://docs.rs/async-nats/latest/async_nats/jetstream/context/struct.Context.html) and [`stream`](https://docs.rs/async-nats/latest/async_nats/jetstream/stream/struct.Stream.html) those two fileds in nats sink struct. But in sink, the stream is useless. Use context can satisfied our requirement.
The `stream` is useless, but the previous code need initialize it. That means the code only can work correctly under `nats-server -js`. After remove, it also can also work correctly under normal nats model without jetstream `nats-server`.
Thanks for the remind of @neverchanje 
BTW, the nats …
> fix(stream): remove useless stream in nats sink

- src/frontend/src/catalog/system_catalog/information_schema/mod.rs
- src/frontend/src/catalog/system_catalog/information_schema/views.rs
- src/frontend/src/catalog/system_catalog/mod.rs
Cherry-picking https://github.com/risingwavelabs/risingwave/pull/12045 onto v1.2-rc, so that we can have the support for Beekeeper Studio in 1.2.
> feat: support information_schema.views (#12045)

- src/frontend/src/scheduler/worker_node_manager.rs
This PR adds a fallback for node mask in batch query: if no candidate node is available after filtering original nodes by node mask, use all original nodes instead, even some of them are unreachable earlier.
</details>
> fix(batch): fallback for node mask

- Cargo.lock
- src/batch/Cargo.toml
- src/cmd/Cargo.toml
- src/cmd_all/Cargo.toml
- src/common/src/config.rs
- src/compute/Cargo.toml
- src/compute/src/memory_management/memory_manager.rs
- src/compute/src/memory_management/mod.rs
- src/compute/src/memory_management/policy.rs
- src/config/example.toml
- src/tests/simulation/Cargo.toml
As title.
By default, as long as `MALLOC_CONF=prof:true` is set, auto heap dump will be produced. Otherwise, a line of log will be printed
```
Cannot dump heap profile because Jemalloc prof is not enabled
```
This makes it easier to use auto heap dump and also facilitates https://linear.app/risingwave-labs/issue/CLOUD-1791/feature-enable-auto-heap-dump.
The default dump path is inherited from `prof.prefix` in `MALLOC_CONF`, but you may override it by the option `server.auto_dump_heap_profile.dir`. For example:
```toml
[server.auto_dump_heap_profile]
enabled = true
dir = "/my/dump/path"
threshold = 0.9
```
If this PR …
> feat: auto heap dump by default if `MALLOC_CONF=prof:true`

- e2e_test/ddl/table/generated_columns.slt.part
- risedev.yml
- src/frontend/src/handler/create_source.rs
- src/frontend/src/handler/create_table.rs
close  #11741
The generated columns should not be part of the defined primary key in a table.
</details>
> fix: ban pk comprising generated column

- src/config/ci-compaction-test-meta.toml
- src/config/ci-compaction-test.toml
- src/config/ci-meta-backup-test.toml
To avoid error like "error binding to 127.0.0.1:1260: error creating server listener: Address already in use".
</details>
> chore(test): disable prometheus in some tests

- src/udf/src/error.rs
- src/udf/src/external.rs
> fix(udf): check udf schema fields num and total records

- Cargo.lock
- src/utils/workspace-config/Cargo.toml
https://github.com/risingwavelabs/risingwave/pull/12198
Don't know how to fix it quickly
</details>
> build: downgrade to openssl@1 temporarily

- src/connector/src/source/kafka/mod.rs
- src/connector/src/source/kafka/source/reader.rs
introducing a new option `properties.enable.auto.commit` in kafka consumer, which sets `enable.auto.commit` in Kafka client. It is an option bool, and the default is `true`. 
please remove the `group.id` option in kafka consumer. Risingwave will automatically generate one to work with `enable.auto.commit` without affecting the normal consuming process.
</details>
> feat: make `enable.auto.commit` configurable

- src/common/src/types/mod.rs
- src/common/src/types/struct_type.rs
- src/expr/src/expr/expr_udf.rs
- src/expr/src/table_function/user_defined.rs
> fix(udf): check the data type returned from UDF server

- src/tests/state_cleaning_test/data/agg.toml
- src/tests/state_cleaning_test/data/join.toml
- src/tests/state_cleaning_test/data/temporal_filter.toml
As titled. Otherwise `rows_per_second` doesn't take effect, and the actual rows_per_second is 10 by default.
After correct this, the state_cleaning_test fails: `Error: Table __internal_mv_tumble_join_9_hashjoinleft_1027 has 676 rows, which is more than limit 300`.
</details>
> fix(test): set correct row per second

- ci/workflows/main-cron.yml
- ci/workflows/pull-request.yml
Closes https://github.com/risingwavelabs/risingwave/issues/11879.
Save CI costs and make it more stable.
Pruned 8 tests (iceberg sink tests share a common label, java connector node tests share a common label).
</details>
> chore(ci): prune tests which should run occasionally

- ci/workflows/main-cron.yml
- ci/workflows/pull-request.yml
> chore(ci): bump timeouts for bulid-release and unit test and e2e-sink-test

- .cargo/config.toml
- .vscode/launch.json.example
- Makefile.toml
- scripts/coredump/coredump.entitlements
- scripts/coredump/sign-and-run
- src/risedevtool/config/src/main.rs
Add an option for enabling core dump for development purposes. After it's enabled in `risedev configure`, we'll do the following stuff:
- (always) `ulimit -c unlimited` to unlimit the core file sizes
- (on Apple Silicon) `codesign` binaries (https://developer.apple.com/forums/thread/694233?answerId=695943022#695943022)
Also add an example for debugging the core file in VS Code. …
> feat(risedev): core dump on panics for development

- src/batch/src/exchange_source.rs
- src/batch/src/execution/grpc_exchange.rs
- src/batch/src/execution/local_exchange.rs
- src/batch/src/executor/test_utils.rs
- src/batch/src/lib.rs
- src/connector/src/source/external.rs
- src/connector/src/source/mock_external_table.rs
- src/stream/src/executor/backfill/upstream_table/snapshot.rs
- src/stream/src/executor/dispatch.rs
**_Hide the whitespaces and you'll find few changes._**
As `return-position-impl-trait-in-trait` is now complete, we can replace more GAT-based async trait with that.
- #10554
</details>
> refactor: replace more GAT-based async trait with RPITIT

- Cargo.lock
- src/connector/Cargo.toml
- src/connector/src/common.rs
- src/connector/src/source/nats/enumerator/mod.rs
- src/connector/src/source/nats/mod.rs
- src/connector/src/source/nats/source/message.rs
- src/connector/src/source/nats/source/reader.rs
- src/connector/src/source/nats/split.rs
This PR try to add several deliver policies (latest, earliest, ~~by sequence~~, by timestamp). 
Test the policy under
1. normal source
2. recover the data after CN break down. And also can correctly consume data
We decide to merge it into the #12227 firstly. Will use that branch to build a image for user. 
Add the `latest`, `earliest`, `by timestamp` …
> feat(stream): support set nats consumer deliver policy as latest, earliest, by sequence, by timestamp

- e2e_test/sink/elasticsearch/elasticsearch_sink.slt
- integration_tests/elasticsearch-sink/README.md
- integration_tests/elasticsearch-sink/create_es7_sink.sql
- integration_tests/elasticsearch-sink/create_es8_sink.sql
- integration_tests/elasticsearch-sink/create_mv.sql
- integration_tests/elasticsearch-sink/create_source.sql
- integration_tests/elasticsearch-sink/docker-compose.yml
- java/connector-node/python-client/integration_tests.py
- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/SinkUtils.java
- java/connector-node/risingwave-connector-test/src/test/java/com/risingwave/connector/sink/elasticsearch/EsSinkTest.java
- java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/EsSink.java
- java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/EsSink7.java
- java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/EsSinkConfig.java
- java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/EsSinkFactory.java
- src/connector/src/sink/remote.rs
Fix #12234
This PR adds `setApiCompatibilityMode(true)` for the RestHighLevelClient in the es 7 client library to make it compatible with es8 server. This is a simple workaround suggested in the es [doc](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/8.9/migrate-hlrc.html#migrate-hlrc).
I have manually tested this PR with es 7.17 and es 8.10 server. Both work.
TODO:
Support elasticsearch 7 and elasticsearch 8 sink. SQL Example:
```
CREATE SINK es_sink
FROM test_mv WITH (
connector = 'elasticsearch',
index = 'test',
url = 'http://elasticsearch8:9200',
username = 'elastic',
password = 'risingwave' …
```
> feat(sink): support elasticsearch 8 sink

- Cargo.lock
- src/compute/Cargo.toml
- src/compute/src/memory_management/memory_manager.rs
- src/compute/src/memory_management/mod.rs
- src/compute/src/rpc/service/monitor_service.rs
- src/workspace-hack/Cargo.toml
Make it more friendly for development. IDE will not hide code on non-linux env.
</details>
> chore: use cfg! to instead of #cfg[] for jemalloc control policy

- e2e_test/streaming/temporal_join/temporal_join_watermark.slt
- src/stream/src/executor/temporal_join.rs
- Resolve https://github.com/risingwavelabs/risingwave/issues/10621#event-10330006525
- Simply maps LHS watermark messages of temporal join to the output and ignore watermark messages from RHS.
</details>
> feat(stream): handling watermark in temporal join

- src/storage/src/hummock/event_handler/refiller.rs
- src/storage/src/hummock/sstable/mod.rs
As titled. Tiny fixes.
</details>
> chore: fix comment and metrics

- Cargo.lock
- Cargo.toml
- ci/scripts/release.sh
- docker/Dockerfile
- docker/Dockerfile.hdfs
As explained in https://github.com/risingwavelabs/risingwave/issues/11592#issuecomment-1713521903. Enable `full` debug info for release build and split it into a single `packed` `DWP` file on Linux.
Also, bump version to v1.3.0-alpha.
</details>
> chore: split full debug info for release build

- proto/catalog.proto
- src/connector/src/sink/catalog/mod.rs
- src/frontend/src/catalog/index_catalog.rs
- src/frontend/src/catalog/table_catalog.rs
- src/frontend/src/handler/create_index.rs
- src/storage/src/filter_key_extractor.rs
- src/tests/compaction_test/src/delete_range_runner.rs
Support identifying `CREATING` / `CREATED` tables.
Part of #8051 
</details>
> feat(meta): Add `creating_status` field for stream jobs

- e2e_test/udf/udf.slt
- src/common/src/array/arrow.rs
- src/common/src/array/data_chunk.rs
- src/expr/src/table_function/mod.rs
- src/expr/src/table_function/user_defined.rs
The current implementation of UDTF ignores visibility within the chunks. This PR fixes this bug and adds a test to ensure it works.
This should be a part of #9003. But I forgot to fix it in UDTF as well.
> fix(udf): handle visibility of input chunks in UDTF

- src/meta/src/backup_restore/meta_snapshot_builder.rs
This PR fixes a bug during taking meta backup.
Previously it lists all delta logs from meta store, and then applies them to hummock checkpoint version one by one, **without sorting them by log id first**, which is incorrect. Because log id is encoded by prost (no memcomparable) and treated as bytes in meta store, so raw list doesn't follow integer order.
The impact of this bug is, 
- either backup op may be rejected by sanity check.
- or backup op succeeds, but the hummock version may be inconsistent with other metadata in the same backup.
If this PR includes changes that directly affect users or other significant …
> fix(backup): ensure correct delta log order

- src/frontend/planner_test/tests/testdata/input/agg.yaml
- src/frontend/planner_test/tests/testdata/output/agg.yaml
- src/frontend/planner_test/tests/testdata/output/batch_index_join.yaml
- src/frontend/planner_test/tests/testdata/output/except.yaml
- src/frontend/planner_test/tests/testdata/output/intersect.yaml
- src/frontend/planner_test/tests/testdata/output/nexmark.yaml
- src/frontend/planner_test/tests/testdata/output/subquery.yaml
- src/frontend/planner_test/tests/testdata/output/subquery_expr_correlated.yaml
- src/frontend/src/optimizer/logical_optimization.rs
- src/frontend/src/optimizer/rule/agg_group_by_simplify_rule.rs
- src/frontend/src/optimizer/rule/mod.rs
- Resolve https://github.com/risingwavelabs/risingwave/issues/9578
- Use `first_value` to replace redundant group by key, so that `first_value` could be purged by the following column pruning optimization.
Example:
```sql
before:
select count(*) from sbtest1 group by id, k, c;
use functional dependencies  (id) ==> (k, c)
after:
select count(*) from sbtest1 group by id;
``` …
> feat(optimizer): support agg group by simplify rule

- ci/workflows/docker.yml
- ci/workflows/main-cron.yml
We want to run main-cron pipeline when we push a new tag and release.
> chore(ci): move release jobs to main-cron pipeline

- backwards-compat-tests/slt/tpch-backwards-compat/seed.slt
- e2e_test/batch/issue_7324.slt
- e2e_test/batch/tpch.slt
- src/common/src/field_generator/numeric.rs
- src/risedevtool/src/bin/risedev-docslt.rs
- src/tests/regress/src/schedule.rs
This PR allows to specify `start` and `end` of `datagen` connector  to the same value as below:
```
fields.v.start = 123,
fields.v.end  = 123,
```
Thus we can get `v` in range [123, 123].
This PR also remove all `set CREATE_COMPACTION_GROUP_FOR_MV to true;` from tests, because `CREATE_COMPACTION_GROUP_FOR_MV` is default to false in production, and none of these tests are designed to test `CREATE_COMPACTION_GROUP_FOR_MV` in the first place. …
> chore(test): tune datagen range

- e2e_test/udf/udf.slt
- src/common/src/array/arrow.rs
- src/common/src/array/data_chunk.rs
- src/common/src/types/mod.rs
- src/common/src/types/struct_type.rs
- src/expr/src/expr/expr_udf.rs
- src/expr/src/table_function/mod.rs
- src/expr/src/table_function/user_defined.rs
- src/udf/src/error.rs
- src/udf/src/external.rs
cherry pick 3 fixes on UDF to v1.2:
- #12206
- #12202
- #12357
resolve #12360
</details>
> cherrypick fix(udf): handle visibility of input chunks in UDTF (#12357)

- ci/scripts/multi-arch-docker.sh
- ci/workflows/docker.yml
Support use `SKIP_TARGET_AMD64=true` or `SKIP_TARGET_AARCH64=true` to skip build on the specific arch when building with docker pipeline.
</details>
> chore: support docker build skip target

- java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/EsSink.java
so that json can be written to ES with the correct structure.
Example:
RW:
```
dev=> create table rw_table(k int primary key, v jsonb);
CREATE_TABLE
dev=> insert into rw_table values(1, '{"nested": {"array_field":[1, 2, 3], "normal_field": 3.14}}');
INSERT 0 1
dev=> create sink es_sink from rw_table with (connector='elasticsearch', index='test_index', url='http://localhost:9200', username='elastic', password='risingwave');
CREATE_SINK
```
ES:
```
{
"took": 2,
"timed_out": false,
"_shards": {
"total": 1,
"successful": 1,
"skipped": 0,
"failed": 0
},
"hits": {
"total": {
"value": 1,
"relation": "eq"
},
"max_score": 1, …
```
> feat: use Map to represent json field when building doc in es sink

- e2e_test/batch/catalog/metabase.slt.part
- e2e_test/ddl/search_path.slt
- proto/buf.yaml
- proto/expr.proto
- src/expr/macro/src/gen.rs
- src/expr/macro/src/lib.rs
- src/expr/src/table_function/mod.rs
- src/expr/src/table_function/pg_expandarray.rs
- src/frontend/src/binder/expr/function.rs
Added a new table function `_pg_expandarray`.
fix https://github.com/risingwavelabs/risingwave/issues/12204
Add a new table function:
```
_pg_expandarray(array anyarray) → record(x anyelement, n int)
```
Returns the input array as a set of rows with an index.
> feat(expr): add `_pg_expandarray` function

- ci/scripts/check.sh
For issue #11986, it is solved at #12227 . So remove the cargo audit specific ignore. 
</details>
> fix: remove cargo audit --ignore RUSTSEC-2022-0093

- src/batch/src/monitor/stats.rs
related: #12489
Just ignore it to avoid panic, fix it later. …
> fix: ignore when fail to remove label in batch monitor

- .github/workflows/hakari_fix.yml
- Cargo.lock
- src/connector/Cargo.toml
- src/connector/src/sink/kafka.rs
This aims to support setting `compression.codec` in kafka sink.
Closes https://github.com/risingwavelabs/risingwave/issues/12435
Support setting kafka producer `compression.codec` in kafka sink
</details>
> feat(sink): support compression codec in kafka sink

- ci/workflows/pull-request.yml
Timeouts frequently
For unit test, although some timeouts are due to flaky test (https://github.com/risingwavelabs/risingwave/issues/11979), we can see it's still very close to timeout.
build-other
</details>
> ci: increase timeout for unit test/buid-other

- src/frontend/src/catalog/system_catalog/mod.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_hummock_version.rs
This PR adds a flattened view of all SSTables. 
Key range is stored as bytea, and thus we can query/compare/transform key range as needed.
```
select * from rw_catalog.rw_hummock_sstables;
sstable_id | object_id | compaction_group_id | level_id |   sub_level_id   | level_type |                                                                                            key_range_left                                                                                            |                                                    key_range_right                                                     | right_exclusive | file_size …
```
> feat(frontend): add rw_catalog.rw_hummock_sstables

- docker/docker-compose.yml
- docs/memory-profiling.md
In #12200, we bumped the version for the compactor from 1.0.0 to 1.2.0. It could be problematic if we use version 1.0.0 for the rest nodes.
</details>
> chore: bump risingwave version in docker compose to 1.2.0

- proto/catalog.proto
- proto/ddl_service.proto
- src/frontend/src/catalog/catalog_service.rs
- src/frontend/src/catalog/table_catalog.rs
- src/frontend/src/handler/create_mv.rs
- src/frontend/src/test_utils.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/rpc/service/ddl_service.rs
- src/rpc_client/src/meta_client.rs
- src/storage/src/filter_key_extractor.rs
- src/tests/compaction_test/src/delete_range_runner.rs
Add `create_type`, so we can distinguish between background and foreground mvs, when deciding which to persist.
Foreground mvs' backfill progress will not be recovered.
Note that we have breaking change for the proto `CreateMaterializedViewRequest`. Its `stream_job_execution_mode` field is deleted in this PR.
This is only introduced recently https://github.com/risingwavelabs/risingwave/pull/12355, and it is not persisted, so we can just remove it.
This field is now maintained in `Table`'s proto definition. …
> feat(meta): add create_type to `Table`

- src/stream/src/executor/over_window/general.rs
Previously OverWindowExecutor expects stream keys of `UpdateDelete` row and `UpdateInsert` row the same, but in reality some of our executors produce chunks that don't match the expectation (and seems we never reached any consensus on this). So change it to ensure correctness.
</details>
> fix(over window): don't expect stream keys in UpdateDelete and UpdateInsert the same

- e2e_test/streaming/temporal_join/temporal_join_watermark.slt
> fix(test): temporal join watermark test select eowc skipif in-memory and inc sleep time

- ci/scripts/e2e-iceberg-sink-test.sh
> fix(test): prepare connector libs path for iceberg sink test

- integration_tests/kafka-cdc-sink/risingwave.sql
- src/connector/src/sink/kafka.rs
- Expose `message.timeout.ms` and `max.in.flight.requests.per.connection` for kafka sink.
- Change the default `max.in.flight.requests.per.connection` to 5, which is recommended in the [confluent doc](https://docs.confluent.io/platform/current/installation/configuration/producer-configs.html#max-in-flight-requests-per-connection). Note that the [previous default](https://github.com/confluentinc/librdkafka/blob/32747f5eb7aea23d79d31bcd56747dd5aa694d72/src/rdkafka_conf.c#L436) set by librdkafka is `1000000`, which is not reasonable since it will create excessive produce requests that can potentially overload kafka broker …
> fix: allow configure message.timeout.ms and max.in.flight for kafka sink

- ci/workflows/main-cron.yml
Seems like a bunch of workflows were duplicated in `main-cron`. Perhaps changes from #12233 and https://github.com/risingwavelabs/risingwave/pull/12232 were duplicated because of slightly different test headings and different orderings.
```
> cat ci/workflows/main-cron.yml | grep label: | sort | sed -E 's/ \(release\)//' | uniq -c | grep '[2-9]  '
2   - label: "S3 source check on AWS (json parser)"
2   - label: "connector node integration test Java {{matrix.java_version}}"
2   - label: "e2e java-binding test"
2   - label: "end-to-end iceberg sink test"
2   - label: "end-to-end iceberg sink v2 test"
2   - label: …
```
> chore(ci): remove duplicated workflows in `main-cron`

- src/common/src/heap_profiling/mod.rs
- src/compute/src/memory_management/policy.rs
- src/compute/src/rpc/service/monitor_service.rs
As required by the dump collector, memory profile dump files must end with `.heap`.
https://github.com/risingwavelabs/k8s-continuous-debugging-tools/blob/db1b7466f92992f59390b5af470db769abda9ae9/tools/archive/common/consts.go#L19
Additionally, `dump_seq` doesn't work, so I removed it.
</details>
> fix: memory dump must end with `.heap`

- Makefile.toml
> chore: risedev clean java targets

- e2e_test/source/basic/kafka_batch.slt
- src/frontend/src/optimizer/plan_node/logical_source.rs
Fix #12523. During `LogicalSource::predicate_pushdown`, it should avoid pushdown rather than panic on evaluation error, no matter the error is:
* missing timezone context (`'2023-09-25 10:34:33.000000'::timestamptz`)
* malformed date/time string (`'abc'::timestamptz`)
* overflow (`TO_TIMESTAMP(2147483647 + 1)`)
Note that when the condition contains timezone-dependent exprs, like in #12523, the condition would not be pushdown to source plan node, and the performance may not be ideal. We would still need #12633 to enable better performance. But that can be decoupled from a bug fix and added in a more controlled and …
> fix(optimizer): handle eval error in `LogicalSource::predicate_pushdown`

- src/stream/src/executor/backfill/no_shuffle_backfill.rs
Follow up of #12644 .
For backfill spanning N >= 2 barriers, we must make sure not to drop updates until the start of the next interval.
That could happen currently, if the update record's PK is larger than the current backfill position.
If that happens, the update gets dropped, even though we may read its snapshot record within the barriers.
This also means now more memory will be used, since we buffer it all the way until the first barrier of the next interval, and if there are heavy updates incoming during backfill, we could contribute to oom. …
> fix(stream): yield upstream updates for backfill after last barrier in the interval

- src/tests/sqlsmith/src/bin/main.rs
- src/tests/sqlsmith/src/lib.rs
fix #12577
This bug was introduced by #12485, where we separated function implementations into the new `expr_impl` crate, but it was not linked into the sqlsmith(test) target. So when running cargo-test for sqlsmith, it can't find any functions. 🥲
> fix(sqlsmith): recover functions for sqlsmith

- src/tests/regress/data/schedule
- src/tests/regress/data/sql/regex.sql
After #12329 , we support more regex features in postgresql, so we enable the testcases.
</details>
> test(regress): enable regex testcases

- Cargo.lock
- src/common/Cargo.toml
- src/common/src/types/mod.rs
- src/common/src/util/memcmp_encoding.rs
- src/common/src/util/value_encoding/mod.rs
- src/expr/core/src/aggregate/def.rs
- src/expr/core/src/expr/expr_field.rs
- src/expr/core/src/expr/expr_in.rs
- src/expr/core/src/expr/expr_literal.rs
- src/expr/core/src/expr/test_utils.rs
- src/frontend/src/expr/literal.rs
- src/frontend/src/optimizer/plan_node/generic/agg.rs
- src/stream/src/executor/mod.rs
To avoid writing serialization/deserialization logic explicitly. 💦
</details>
> refactor(common): implement `Datum::[from|to]_protobuf`

- src/storage/src/hummock/compactor/compactor_runner.rs
- src/storage/src/hummock/compactor/fast_compactor_runner.rs
- src/storage/src/monitor/compactor_metrics.rs
> fix(storage): fix compact_fast_runner_bytes unused

- Cargo.lock
- src/connector/Cargo.toml
- src/connector/src/parser/canal/simd_json_parser.rs
- src/connector/src/parser/csv_parser.rs
- src/connector/src/parser/debezium/debezium_parser.rs
- src/connector/src/parser/debezium/mongo_json_parser.rs
- src/connector/src/parser/debezium/simd_json_parser.rs
- src/connector/src/parser/json_parser.rs
- src/connector/src/parser/maxwell/maxwell_parser.rs
- src/connector/src/parser/mod.rs
- src/connector/src/parser/plain_parser.rs
- src/connector/src/parser/unified/mod.rs
- src/connector/src/parser/unified/util.rs
- src/connector/src/parser/upsert_parser.rs
- src/meta/src/barrier/mod.rs
See #12366 for the background.
The error-handling path in the connector parser is kind of complicated, and users often complain about the confusion of the behavior when parsing a message fails. We've had some attempts before (like #10454). In this PR, we further unify the error handling strategy and code path, then provide tracing observability on that.
Specifically,
- To write a record to the chunk builder, the only way is through `SourceStreamChunkRowWriter`. Based on a similar idea to #12542, we can also unify the error handling to the `do_action` method. This means that …
> feat(connector): structural logging for parsing error

- src/meta/src/hummock/manager/compaction_group_manager.rs
- src/meta/src/hummock/manager/mod.rs
We've already lowered the default limit for write limit in #12183, and to prevent older clusters from continuing to use the outdated configuration, we've introduced a new logic to rewrite it in a uniform way.
</details>
> chore(storage): upgrade write limit

- src/common/src/array/data_chunk_iter.rs
- src/common/src/row/mod.rs
- src/common/src/row/project.rs
**_Hide the whitespaces to review this PR._**
- Make `RowRef` and `RowRefIter` defined in a private module to ensure `unsafe` soundness.
- Introduce `Row::hash_into_datums` to ensure consistency between `std::hash::Hash` implementations.
</details>
> refactor(common): refine `Row` changes in #11070

- .github/workflows/doc.yml
- .github/workflows/nightly-rust.yml
> ci: fix disk out of space for GHA (attempt 2)

- src/common/src/estimate_size/collections/hashmap.rs
- src/common/src/estimate_size/collections/lru.rs
- src/common/src/estimate_size/collections/mod.rs
- src/common/src/estimate_size/mod.rs
- src/stream/src/executor/hash_agg.rs
See https://github.com/risingwavelabs/risingwave/pull/12453#discussion_r1335624855.
We introduced `MutGuard` for collections with estimated sizes in #9134, which holds a mutable reference to a value in a collection and will update the `total_size` of the collection after dropped. 
Everything worked well except for `iter_mut`, where we had to _split_ the mutable reference of the collection into multiple entries. While this is not an issue for the collection itself, it becomes problematic when trying to split the mutable reference to `total_size`, which is impossible (and certainly, unsafe) in Rust. So we further introduced `UnsafeMutGuard`, where callers had to manually turn it into a `MutGuard` before using it, based on the guarantee that there's no concurrent or parallel accessing.
To …
> refactor(common): eliminate `unsafe` for iteration with estimated sizes by atomics

- e2e_test/batch/transaction/now.slt
- src/stream/src/executor/mod.rs
- src/stream/src/executor/now.rs
- src/stream/src/executor/values.rs
- src/tests/simulation/src/cluster.rs
- src/tests/simulation/tests/integration_tests/recovery/pause_on_bootstrap.rs
Follow-up of #11936, it seems that we didn't handle the `pause_on_bootstrap` logic in `Now` and `Values` executors. Could at least help us to diagnose https://github.com/risingwavelabs/risingwave/issues/12715.
</details>
> fix(streaming): handle pause on bootstrap for `Now` and `Values`

- src/stream/src/common/log_store_impl/kv_log_store/buffer.rs
- src/stream/src/common/log_store_impl/kv_log_store/writer.rs
- src/tests/simulation/tests/integration_tests/sink/basic.rs
Fix https://github.com/risingwavelabs/risingwave/issues/12650
Current storage implementation has an assumption that a key inserted in an epoch cannot be range-deleted in the same epoch. Therefore, in this PR we will not do range delete to storage if the current truncate offset has the same epoch as the current epoch. The data will be truncated in the next epoch instead. …
> fix(log-store): avoid truncate storage data written in the same epoch

- e2e_test/batch/basic/table_with_default_columns.slt.part
- proto/plan_common.proto
- src/frontend/src/catalog/table_catalog.rs
- src/frontend/src/expr/mod.rs
- src/frontend/src/handler/create_table.rs
- src/storage/src/row_serde/value_serde.rs
Add a `snapshot_value` field to the `DefaultColumnDesc`, which is the evaluation result of the default expression at the time when it's created or added with `ALTER TABLE`. The column-aware serde will now directly use this `snapshot_value` instead of evaluating the expression every time.
This has no effect on pure expressions, but matters for the correctness of `ALTER TABLE ADD COLUMN now()`: Historical data will have the same default value of `snapshot_value`, while newly inserted records will fill in the current timestamp by evaluating `now()` in the `BatchInsert` executor. This follows the behavior of PostgreSQL. …
> feat: support impure `DEFAULT` expressions for columns

- src/batch/src/task/task_manager.rs
- src/compute/src/rpc/service/exchange_service.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/manager/cluster.rs
- src/rpc_client/src/meta_client.rs
- src/storage/src/hummock/sstable/forward_sstable_iterator.rs
- src/storage/src/table/mod.rs
- src/stream/src/executor/dispatch.rs
- src/stream/src/executor/lookup/impl_.rs
- src/stream/src/executor/merge.rs
- src/stream/src/executor/receiver.rs
- src/stream/src/executor/wrapper/trace.rs
- src/stream/src/task/barrier_manager.rs
- src/stream/src/task/barrier_manager/managed_state.rs
- src/utils/runtime/src/logger.rs
- Make `stream` and `storage` follow the default level, i.e., `INFO` in production and `DEBUG` for development. `Re`solve #12610.
- Set the level for logs with target `event::` from `TRACE` to `DEBUG`. Considering `release_max_level_debug`, this gives us the possibility to enable them in production without hurting the performance too much (note that the overall max level is `INFO` now, so they can be filtered out in the fast path normally). …
> chore: tweak log level in production

- src/stream/src/executor/backfill/no_shuffle_backfill.rs
There should not be a mix of finished / unfinished states. If some partitions are unfinished, on recovery the stream job will be cleaned. But if we scale in after finishing / reschedule the actors in some way to merge partitions, perhaps the current_pos could be different.
Follow up: https://github.com/risingwavelabs/risingwave/issues/12768
</details>
> fix(streaming): assert all states finished, or all not finished for backfill

- src/common/src/array/list_array.rs
- src/expr/core/src/aggregate/def.rs
- src/expr/impl/src/aggregate/bit_and.rs
- src/expr/impl/src/aggregate/bit_or.rs
- src/expr/impl/src/aggregate/bit_xor.rs
- src/expr/impl/src/aggregate/general.rs
- src/expr/impl/src/aggregate/mod.rs
- src/expr/impl/src/scalar/array_access.rs
- src/expr/impl/src/table_function/generate_subscripts.rs
- src/expr/macro/src/gen.rs
- src/expr/macro/src/lib.rs
- src/expr/macro/src/parse.rs
resolve #9281 
This PR adds streaming version `bit_and` and `bit_or` aggregate functions. The state of both functions is a list of 0/1 counts for each bit, so that input values can be retracted.
Limitation: Due to the difference of state and output type, 2-phase aggregation for both functions are disabled.
Support the following aggregate functions in materialized views:
```
bit_and ( smallint ) → smallint
bit_and ( integer ) → integer
bit_and ( bigint ) → bigint
bit_or ( smallint ) → smallint
bit_or ( integer ) → integer
bit_or ( bigint ) → bigint
```
> feat(expr): support streaming `bit_and` and `bit_or` aggregate

- src/stream/src/executor/backfill/cdc_backfill.rs
Persist current binlog offset when upstream snapshot is empty, so that we can recover the consumption of upstream CDC events. The persisted offset cannot be null in any scenarios.
</details>
> fix(cdc-backfill): fix recovery of cdc table that subscribed to an empty table

- src/frontend/planner_test/tests/testdata/output/bushy_join.yaml
- src/frontend/planner_test/tests/testdata/output/ch_benchmark.yaml
- src/frontend/planner_test/tests/testdata/output/delta_join.yaml
- src/frontend/planner_test/tests/testdata/output/distribution_derive.yaml
- src/frontend/planner_test/tests/testdata/output/lateral_subquery.yaml
- src/frontend/planner_test/tests/testdata/output/nexmark.yaml
- src/frontend/planner_test/tests/testdata/output/nexmark_source.yaml
- src/frontend/planner_test/tests/testdata/output/nexmark_temporal_filter.yaml
- src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml
- src/frontend/planner_test/tests/testdata/output/over_window_function.yaml
- src/frontend/planner_test/tests/testdata/output/pk_derive.yaml
- src/frontend/planner_test/tests/testdata/output/share.yaml
- src/frontend/planner_test/tests/testdata/output/subquery.yaml
- src/frontend/planner_test/tests/testdata/output/temporal_join.yaml
- src/frontend/planner_test/tests/testdata/output/tpch.yaml
- src/frontend/planner_test/tests/testdata/output/tpch_variant.yaml
- src/frontend/planner_test/tests/testdata/output/with_ordinality.yaml
- src/frontend/src/optimizer/plan_node/generic/join.rs
- Resolve https://github.com/risingwavelabs/risingwave/issues/12820
</details>
> feat(optimizer): optimize join stream key

- Cargo.lock
- Cargo.toml
- src/workspace-hack/Cargo.toml
As title. Please also review the change in https://github.com/madsim-rs/madsim/pull/173, and see what's changed from the original rdkafka in [this commit](https://github.com/madsim-rs/madsim/pull/173/commits/05dc6619df762c9b9ee57c4d02d000472e7d0edd).
</details>
> chore(deps): bump rdkafka to v0.34.0 and librdkafka to v2.2.0

- src/common/src/monitor/connection.rs
Temporarily resolve https://github.com/risingwavelabs/risingwave/issues/12848
On server side, each client connection will be assigned a new port. Therefore every new client request will assign a new label in the connection metrics, and when the connection is finished, the metrics is leaked, causing the large volume of connection metrics.
In this PR, we temporarily fix this issue by only using the ip as the label, so that different port will not result in multiple labeled metrics. In the future we can leverage reference counting on the label metrics and automatically remove the label metrics when the reference counting …
> fix(metrics): avoid port in connection metrics label

- src/connector/Cargo.toml
- src/connector/src/lib.rs
- src/connector/src/sink/encoder/avro.rs
- src/connector/src/sink/encoder/json.rs
- src/connector/src/sink/encoder/mod.rs
- src/connector/src/sink/encoder/proto.rs
- src/connector/src/sink/mod.rs
For both avro and proto, we validate between RisingWave and Encoder schema during `Encoder::new`. The duplicated logic (mostly m x n match between data type combinations) between validate-with-type-only and encode-with-actual-data is shared with the help of `MaybeData` and `encode_field`. The call graph of core functions is as follows ([dot-src](https://bit.ly/46M6icg)):
There are some encoding specific complexities:
* Proto3 allows any field to be omitted. For list (repeated), it cannot be nested, and cannot contain nulls in the list.
* Avro represents optional field as `["null", T]` (union of null and T). The upstream …
> feat(sink): ProtoEncoder and AvroEncoder

- ci/scripts/pr-fuzz-test.sh
- ci/workflows/pull-request.yml
Closes #12733 
Allows us to run PR workflow steps selectively.
For instance with this:
We have the following steps run:
Even if PR is in `draft`:
</details>
> feat(ci): support opt-in workflow for pull-requests

- src/frontend/src/binder/statement.rs
- Fix dml output fields
- Resolve https://github.com/risingwavelabs/risingwave/issues/12781#issuecomment-1763900002
</details>
> fix(frontend): fix dml output fields

- e2e_test/batch/basic/func.slt.part
- proto/expr.proto
- src/expr/impl/src/scalar/regexp.rs
- src/frontend/src/binder/expr/function.rs
- src/frontend/src/expr/pure.rs
- src/tests/regress/data/sql/strings.sql
> feat(expr): add `regexp_split_to_array`

- src/cmd_all/src/common.rs
- src/cmd_all/src/standalone.rs
Closes https://github.com/risingwavelabs/risingwave/issues/12851.
</details>
> feat(cmd_all): provide common options `config-path` and `prometheus-listen-addr`

- ci/workflows/integration-tests.yml
This case is an old version. We disable it first, and @liurenjie1024  will introduce a new version of the case later.
https://github.com/risingwavelabs/risingwave/issues/12893
> fix(integration-test): disable iceberg-sink case

- src/common/src/session_config/mod.rs
BI and data analytic platforms Intergration: Aliyun DMS
DMS platform allow to create a self-building database connection on the VPC internal.
So when we create a cluster on the Aliyun, We can use the DMS to connect the RisingWave Frontend Service Port.
But we need to support the initial query by `current_setting('server_encoding')` first.
As of now, while `server_encoding` only accepts utf8.
Installation and deployment
Connector (sources & sinks)
SQL commands, functions, and operators
RisingWave cluster configuration changes
Other (please specify …
> feat(frontend): stub session server_encoding

- e2e_test/batch/functions/greatest_least.slt.part
- proto/expr.proto
- src/expr/impl/src/scalar/cmp.rs
- src/expr/impl/tests/sig.rs
- src/frontend/src/binder/expr/function.rs
- src/frontend/src/expr/pure.rs
- src/frontend/src/expr/type_inference/func.rs
Complete https://github.com/risingwavelabs/risingwave/issues/12761
The code of cmp unit test is refactored accordingly.
Support `greatest` and `least` pg function.
```
GREATEST(value [, ...])
```
```
LEAST(value [, ...])
```
The GREATEST and LEAST functions select the largest or smallest value from a list of any number of expressions. The expressions must all be convertible to a common data type, which will be the type of the result.
NULL values in the argument list are ignored. The result will be NULL only if all the expressions evaluate to NULL. (This is a deviation from the SQL standard. According to the standard, …
> feat(expr): implement greatest and least function

- src/stream/src/executor/over_window/general.rs
- src/stream/src/executor/over_window/over_partition.rs
After https://github.com/risingwavelabs/risingwave/pull/12364 we now have a new and handy `StateTable::iter_with_prefix` method to iterate a given range within a pk prefix. This PR utilize it to simplify `OverPartition`. Fixes #12583.
</details>
> refactor(over window): use new `table.iter_with_prefix` in streaming OverWindow

- src/compute/src/memory_management/mod.rs
Don't count file cache buffer pool size if disabled.
close #12943 
</details>
> fix: don't count file cache buffer pool size if disabled

- proto/hummock.proto
- src/ctl/src/cmd_impl/hummock/list_version.rs
- src/ctl/src/lib.rs
- src/meta/service/src/hummock_service.rs
- src/meta/src/hummock/manager/versioning.rs
- src/rpc_client/src/meta_client.rs
> feat(ctl): support rebuild table stats with approximate value

- Cargo.lock
- Cargo.toml
- Makefile.toml
- dashboard/pages/await_tree.tsx
- src/compute/src/rpc/service/monitor_service.rs
- src/ctl/src/cmd_impl.rs
- src/ctl/src/cmd_impl/await_tree.rs
- src/ctl/src/cmd_impl/trace.rs
- src/ctl/src/lib.rs
- src/meta/src/dashboard/mod.rs
- src/prost/build.rs
- src/storage/compactor/src/rpc.rs
Add a new API for dumping await-trees for all compute nodes, support it in dashboard UI. Also some minor refinements for this:
- Generate `BTreeMap` for maps in async stack trace responses, so that they're naturally ordered.
- Add authority (`127.0.0.1:5687`) to the key of RPC traces, so that we can directly merge the await-trees from different worker nodes without collision on the key.
- Rename `risectl trace` to `risectl await-tree`. `trace` is still available as an alias.
If this PR includes changes that directly affect users or other significant modifications relevant to …
> feat(dashboard): dump await-tree for all compute nodes

- ci/scripts/release.sh
fix connector compilation error.
https://buildkite.com/risingwavelabs/main-cron/builds/948#018b41e4-2a53-4f4d-9c57-92daf8cd93d7
> fix(release): install javadoc in release script

- Cargo.lock
- src/common/proc_macro/Cargo.toml
- src/prost/helpers/Cargo.toml
To avoid many dependencies compiled twice, once as normal dependency and once as build-dependency (including very heavy onces, like zstd, aws-sdk-s3).
**This reduces fresh debug build's compile time from >400s to <300s on my mac.**
I'm not 100% sure about the mechanism yet, but it's clear that feature selection and dependency selection work differently for build-dependencies (incl proc-macros). When `workspack-hack` is used as a proc-macro crate's dependency, all its dependencies *can be* compiled twice.
See https://github.com/risingwavelabs/risingwave/issues/9553#issuecomment-1771100231 for more details.
If this PR …
> build: remove `workspace-hack` from proc-macro crates' dependencies

- src/jni_core/src/jvm_runtime.rs
related: https://github.com/pgjdbc/pgjdbc/issues/1458
</details>
> chore: remove the `-ea` from jvm options

- src/frontend/planner_test/tests/testdata/input/update.yaml
- src/frontend/planner_test/tests/testdata/output/update.yaml
- src/frontend/src/planner/delete.rs
- src/frontend/src/planner/select.rs
- src/frontend/src/planner/update.rs
- Support subquery in update and delete statement.
- Resolve https://github.com/risingwavelabs/risingwave/issues/12847
</details>
> feat(planner): support dml subquery

- ci/workflows/pull-request.yml
- e2e_test/batch/catalog/pg_size.slt.part
CI e2e timeout was bumped from 15m to 17m in #12858, on suspicion that there was perf regression #12825. It ran consistently slower (batch taking 8m50s) during 2023-10-20T15:06Z - 2023-10-21T07:27Z but came back to 7m30s after that.
https://buildkite.com/risingwavelabs/pull-request/builds/33837
https://buildkite.com/risingwavelabs/pull-request/builds/33835
https://buildkite.com/risingwavelabs/pull-request/builds/33834
Ideally there should be no such ci performance fluctuation. Still no clue what happend.
At the same time started an attempt to reduce test time #12984
If this PR includes changes that directly affect users …
> revert(ci): e2e timeout 15 -> 17

- src/utils/workspace-config/Cargo.toml
It’s broken since the workspace-hack change (#12961).
Openssl-sys is compiled twice on Linux, because features are not unified.
The one for build-dependency doesn’t have openssl-sys feature. It’s depended by tls-native, which is depended by sql-x, which is build-dependency in workspace-hack. (Since we didn't configure hakari to unify target os-specific dependencies, hakari unified it only *partialy*, and this cause them unnecessarily compiled twice.)
Simply put, it’s now a build-dependency so
- Feature is not unified. This can be fixed easily and is done in this PR.
- It will be compiled twice in release mode. Unless #12362, but it’s broken. Not a large problem(? Well, I’m not sure But it has been so). Just slower…
This only happens on linux, but not mac, because native-tls works …
> fix: openssl is compiled twice, once not vendored in linux

- src/stream/src/from_proto/source/fs_fetch.rs
- Modify `FsFetchExecutorBuilder` to handle `FlowControlExecutor`
- Add rate limiting to `FsFetchExecutor` (the plan part is done [here](https://github.com/singularity-data/risingwave/blob/633e89f1cd4d32a9371b32f9c0e2820f9b59f062/src/frontend/src/optimizer/plan_node/stream_fs_fetch.rs#L114-L119) but left the exec part)
</details>
> chore: Refactor FsFetchExecutorBuilder to handle rate limiting

- Cargo.lock
- src/storage/Cargo.toml
- src/storage/src/hummock/file_cache/store.rs
Bump foyer to a version before toolchain bump to fix config changes issue.
Later foyer will follow the rust version rules to avoid breaking changes within the same version.
</details>
> chore: bump foyer

- integration_tests/redis-sink/create_sink.sql
- proto/plan_common.proto
- src/connector/src/sink/catalog/mod.rs
- src/connector/src/sink/encoder/template.rs
- src/connector/src/sink/formatter/mod.rs
- src/connector/src/sink/redis.rs
- src/frontend/src/handler/create_sink.rs
- src/sqlparser/src/ast/statement.rs
use 'create sink ... format ... encode' to create redis sink like kafka.
And add Template encode to support custom format for strings input into redis
create table 
```
create table t1(v1 int, v2 int);
```
create redis sink with append_only and json
```
CREATE SINK s1 AS t1 WITH (
primary_key = 'v1 ',
connector = 'redis',
redis.url= 'redis://127.0.0.1:6379/',
)FORMAT PLAIN ENCODE JSON(force_append_only='true');
```
create redis sink with upsert and json
```
CREATE SINK s1 AS t1  WITH (
primary_key = 'v1 ',
connector = 'redis',
redis.url= 'redis://127.0.0.1:6379/',
)FORMAT UPSERT ENCODE JSON;
```
create redis sink with …
> feat(sink): use 'create sink ... format ... encode' to create redis sink

- ci/workflows/pull-request.yml
- src/meta/src/manager/catalog/mod.rs
- src/meta/src/rpc/ddl_controller.rs
It follows the same path as materialized view. Its `TABLEs` have to be persisted as well. Otherwise if CN down, and meta tries to cancel the `CREATE TABLE` ddl, it will encounter errors when trying to delete the internal tables for state cleanup.
Separately make the update of tables transactional, so that either `clean_dirty_table` or `cancel_create_table_procedure` will remove tables from meta store, but not both.
Finally, also remove assertions for create table with source, because if recovery happens, before stream job is cancelled, the in memory creation trackers could already have been cleared. …
> fix(meta): persist internal tables of `CREATE TABLE`

- src/meta/service/src/ddl_service.rs
- src/meta/src/rpc/ddl_controller.rs
> fix: `WAIT` should return error if timeout

- src/cmd/Cargo.toml
- src/cmd_all/Cargo.toml
- src/meta/node/Cargo.toml
💦💦💦
So that we can avoid them being compiled twice when running unit tests.
No tests are ignored after the change (still 1575 tests, but 84 binaries -> 67 binaries)
Note: there aren't significant improvements, because the bottleneck is not improved.
ref: https://github.com/risingwavelabs/risingwave/issues/9878#issuecomment-1767954989
</details>
> chore: disable tests by default for some heavy lib/bins without UTs

- src/frontend/planner_test/tests/testdata/input/subquery.yaml
- src/frontend/planner_test/tests/testdata/output/subquery.yaml
- src/frontend/src/binder/relation/table_function.rs
- Resolve https://github.com/risingwavelabs/risingwave/issues/12998
- We apply the same strategy as DuckDB when handling subqueries.
- In detail, we use apply to support various subqueries, but apply need a source as input. For this sql `SELECT * FROM generate_series(1, (select 1));` we don't have any input for the apply, since table function here itself is the source and depends on the subquery to give them the parameters.
```
-- This sql should be forbided.
-- Only table-in-out functions can have subquery parameters - generate_series only accepts constant parameters
SELECT * FROM generate_series(1, (select 1));
-- …
```
> fix(binder): only table-in-out functions can have subquery parameters

- src/common/src/metrics/guarded_metrics.rs
Previously we remove the label immediately when the metrics is dropped. In this PR, we change to only adding the labels to a buffer, and remove the labels after the metrics is collected.
</details>
> feat(metrics): remove metrics labels after being collected

- proto/expr.proto
- src/common/src/types/jsonb.rs
- src/expr/impl/src/scalar/jsonb_info.rs
- src/frontend/src/binder/expr/function.rs
- src/frontend/src/expr/pure.rs
- src/risedevtool/src/bin/risedev-docslt.rs
- src/tests/regress/data/sql/jsonb.sql
As title. based on #11805 
Support `jsonb_pretty` function.
```
jsonb_pretty ( jsonb ) → text
Converts the given JSON value to pretty-printed, 4 spaces indented text.
jsonb_pretty('[{"f1":1,"f2":null}, 2]') →
[
{
"f1": 1,
"f2": null
},
2
]
```
> feat(expr): add `jsonb_pretty` function

- src/batch/src/executor/generic_exchange.rs
- src/batch/src/executor/group_top_n.rs
- src/batch/src/executor/hash_agg.rs
- src/batch/src/executor/join/hash_join.rs
- src/batch/src/executor/row_seq_scan.rs
- src/batch/src/lib.rs
- src/batch/src/monitor/stats.rs
- src/batch/src/task/context.rs
- src/common/src/estimate_size/collections/heap.rs
- src/common/src/memory/mem_context.rs
- src/common/src/metrics/guarded_metrics.rs
Remove possible panic in metrics cleanup.
Close #12489  
</details>
> fix: Remove possible panic in metrics clean up.

- e2e_test/streaming/bug_fixes/issue_12140.slt
- proto/stream_plan.proto
- src/frontend/planner_test/tests/testdata/input/agg.yaml
- src/frontend/planner_test/tests/testdata/output/agg.yaml
- src/frontend/src/optimizer/plan_node/generic/agg.rs
- src/frontend/src/optimizer/plan_node/stream.rs
- src/frontend/src/optimizer/plan_node/stream_hash_agg.rs
- src/frontend/src/optimizer/plan_node/stream_simple_agg.rs
- src/frontend/src/optimizer/plan_node/stream_stateless_simple_agg.rs
- src/stream/src/executor/agg_common.rs
- src/stream/src/executor/aggregation/agg_group.rs
- src/stream/src/executor/aggregation/agg_state.rs
- src/stream/src/executor/aggregation/minput.rs
- src/stream/src/executor/hash_agg.rs
- src/stream/src/executor/simple_agg.rs
- src/stream/src/executor/test_utils.rs
- src/stream/src/from_proto/hash_agg.rs
- src/stream/src/from_proto/simple_agg.rs
Cherry picking https://github.com/risingwavelabs/risingwave/pull/13015 onto branch v1.3-rc
> fix(stream): fix the minput's indicies when it's for distinct call (cherry-pick #13015)

- ci/scripts/e2e-iceberg-cdc.sh
- ci/scripts/e2e-iceberg-sink-test.sh
- ci/scripts/e2e-sink-test.sh
- ci/scripts/e2e-source-test.sh
- Since we have already support embedded connector node, we don't need to start connector services in most ci tests.
</details>
> chore(ci): remove connector start service from ci

- src/expr/impl/src/scalar/cast.rs
- src/frontend/planner_test/tests/testdata/output/range_scan.yaml
Resolves #11059
```
dev=> insert into sales values (1, '{name: "Alice", paying: true, tags: ["admin"]}');
ERROR:  QueryError: Expr error: Parse error: jsonb key must be a string at line 1 column 2
```
</details>
> fix(expr): include data type in parse error message

- src/connector/src/source/pulsar/mod.rs
- src/connector/src/source/pulsar/source/reader.rs
> fix: iceberg.enabled in pulsar connector should be optional

- Cargo.lock
- src/object_store/Cargo.toml
- src/object_store/src/object/mod.rs
- src/object_store/src/object/opendal_engine/gcs.rs
- src/object_store/src/object/opendal_engine/opendal_object_store.rs
https://opendal.apache.org/docs/rust/opendal/docs/upgrade/index.html
Some break changes.
</details>
> refactor(object store): bump OpenDAL to v0.41

- e2e_test/batch/types/jsonb.slt.part
- src/frontend/src/binder/expr/mod.rs
- src/frontend/src/binder/select.rs
- src/sqlparser/src/ast/data_type.rs
- src/sqlparser/src/keywords.rs
- src/sqlparser/src/parser.rs
This PR add a variant `AstDataType::Jsonb` in parser, so that we can use `jsonb` as typed string.
```sql
select jsonb '{}';
```
This syntax is used in regress tests.
added a new way to create jsonb value:
```sql
jsonb '{"key": 1}'
```
This can be added as an example in the [table](https://docs.risingwave.com/docs/current/sql-data-types/).
> feat(parser): support "jsonb" as typed string

- proto/expr.proto
- src/common/src/types/jsonb.rs
- src/expr/impl/src/scalar/jsonb_access.rs
- src/frontend/planner_test/tests/testdata/output/cse_expr.yaml
- src/frontend/src/binder/expr/binary_op.rs
- src/frontend/src/binder/expr/function.rs
- src/frontend/src/expr/pure.rs
- src/tests/regress/data/sql/jsonb.sql
This PR adds support for jsonb path extraction:
```
jsonb #> text[] → jsonb
jsonb #>> text[] → text
```
support the following operators:
```
jsonb #> text[] → jsonb
Extracts JSON sub-object at the specified path, where path elements can be either field keys or array indexes.
'{"a": {"b": ["foo","bar"]}}'::json #> '{a,b,1}' → "bar"
jsonb #>> text[] → text
Extracts JSON sub-object at the specified path as text.
'{"a": {"b": ["foo","bar"]}}'::json #>> '{a,b,1}' → bar
```
> feat(expr): support `#>` and `#>>` operator for extracting jsonb at a path

- src/common/src/util/column_index_mapping.rs
- src/frontend/src/handler/alter_table_column.rs
- src/frontend/src/optimizer/mod.rs
- src/frontend/src/optimizer/plan_node/eq_join_predicate.rs
- src/frontend/src/optimizer/plan_node/generic/agg.rs
- src/frontend/src/optimizer/plan_node/generic/expand.rs
- src/frontend/src/optimizer/plan_node/generic/join.rs
- src/frontend/src/optimizer/plan_node/generic/project.rs
- src/frontend/src/optimizer/plan_node/generic/project_set.rs
- src/frontend/src/optimizer/plan_node/logical_agg.rs
- src/frontend/src/optimizer/plan_node/logical_expand.rs
- src/frontend/src/optimizer/plan_node/logical_join.rs
- src/frontend/src/optimizer/plan_node/logical_multi_join.rs
- src/frontend/src/optimizer/plan_node/logical_now.rs
- src/frontend/src/optimizer/plan_node/logical_project.rs
- src/frontend/src/optimizer/plan_node/logical_project_set.rs
- src/frontend/src/optimizer/plan_node/logical_scan.rs
- src/frontend/src/optimizer/plan_node/logical_source.rs
- src/frontend/src/optimizer/rule/apply_join_transpose_rule.rs
- src/frontend/src/optimizer/rule/apply_offset_rewriter.rs
- src/frontend/src/optimizer/rule/push_calculation_of_join_rule.rs
- src/frontend/src/optimizer/rule/translate_apply_rule.rs
fix https://github.com/risingwavelabs/risingwave/issues/13100
</details>
> refactor(optimizer): remove some ColIndexMapping::without_tar_size usage

- e2e_test/batch/basic/pg_regrex_match_op.slt.part
- proto/expr.proto
- src/expr/impl/src/scalar/regexp.rs
- src/frontend/planner_test/tests/testdata/output/subquery.yaml
- src/frontend/src/binder/expr/binary_op.rs
- src/frontend/src/expr/pure.rs
Fixes #5136
We used to rewrite `a ~ b` to `regexp_match(a, b) is not null` in frontend. This works in most cases except when either `a` or `b` is null, where the former is expected to return `null` but the rewritten form returns `false`. Thanks to `prebuild` of function macro, we can now support a native `~` implementation without rewriting.
</details>
> fix(expr): `null` input of `~` / `!~`

- ci/scripts/release.sh
- src/jni_core/src/jvm_runtime.rs
- Resolve https://github.com/risingwavelabs/risingwave/issues/13089
- Release all-in-one binary with connector libs.
> build(release): release risingwave all-in-one

- proto/expr.proto
- src/expr/impl/src/scalar/jsonb_delete.rs
- src/frontend/src/binder/expr/function.rs
- src/frontend/src/expr/pure.rs
- src/tests/regress/data/sql/jsonb.sql
As title.
Add this function:
```
jsonb_strip_nulls ( jsonb ) → jsonb
Deletes all object fields that have null values from the given JSON value, recursively. Null values that are not object fields are untouched.
json_strip_nulls('[{"f1":1, "f2":null}, 2, null, 3]') → [{"f1":1},2,null,3]
```
> feat(expr): add `jsonb_strip_nulls` function

- src/common/proc_macro/src/lib.rs
Currently the following will fail to compile because of the missing of `estimated_heap_size`.
```rust
#[derive(EstimateSize)]
struct Foo {}
```
This PR fixes this.
</details>
> fix(EstimateSize): impl missing `estimated_heap_size` method for empty struct

- src/storage/src/hummock/sstable/builder.rs
This PR adds warning on too large key value during building SST, so that we can identify the cause of exceeding 4GB, which is the hard limit.
</details>
> chore(storage): issue a warning when key value is too large

- Cargo.lock
- src/batch/src/executor/source.rs
- src/common/src/util/chunk_coalesce.rs
- src/object_store/Cargo.toml
- src/object_store/src/object/s3.rs
> fix: cherry-pick #13078 and #13046

- src/tests/sqlsmith/src/sql_gen/functions.rs
> fix(sqlsmith): use `encoded` string as input to `decode`

- e2e_test/batch/functions/issue_12072.slt.part
- src/expr/impl/src/scalar/date_trunc.rs
- src/expr/impl/src/scalar/timestamptz.rs
For context, `2023-11-05 01:59:59-07:00` is followed by `2023-11-05 01:00:00-08:00` in `US/Pacific`.
There are two `2023-11-05 01:40:00` in local time, corresponding to UTC time `2023-11-05T08:40:00Z` (1699173600s since the unix epoch) and `2023-11-05T09:40:00Z` (1699177200s since the unix epoch).
And also two `2023-11-05 01:00:00` in local time, corresponding to UTC time `2023-11-05T08:00:00Z` (1699171200s since the unix epoch) and `2023-11-05T09:00:00Z` (1699174800s since the unix epoch).
Fixes #12072
In short:
* `date_trunc` to `hour` of `2023-11-05 01:40:00` in Pacific **Daylight** Time (`-07:00`) shall return …
> fix(expr): `date_trunc` and `+/-` on `timestamptz` during DST jump-back

- Cargo.lock
- Cargo.toml
- src/expr/core/src/expr/expr_udf.rs
- src/expr/core/src/table_function/user_defined.rs
- src/udf/Cargo.toml
- src/udf/src/error.rs
- src/udf/src/external.rs
- src/udf/src/lib.rs
As explained in #13215. Introducing the `thiserror-ext` proc-macros.
- `Box`: Derive a new type wrapping the `enum` with `Box`. Automatically implement all `From`s and forward error implementation.
- `Construct`: Derive constructors on the new type.
This is a first attempt so I only refactor the `udf::Error` as a demo.
Will release the proc-macros on crates.io after it gets more stable.
----
Derived:
- `Box`
```rust
/// The boxed type of [`ErrorInner`].
#[derive(thiserror_ext::__private::thiserror::Error, Debug)]
#[error(transparent)]
pub struct Error(
#[from]
#[backtrace]
thiserror_ext::__private::ErrorBox<ErrorInner>, …
```
> refactor: introduce `thiserror-ext` for boxed error wrapper definition

- e2e_test/streaming/values.slt
- src/frontend/planner_test/tests/testdata/output/array.yaml
- src/frontend/planner_test/tests/testdata/output/basic_query.yaml
- src/frontend/planner_test/tests/testdata/output/expr.yaml
- src/frontend/planner_test/tests/testdata/output/with_ordinality.yaml
- src/frontend/src/optimizer/plan_node/stream_values.rs
Fixes #13184. Same as batch:
https://github.com/risingwavelabs/risingwave/blob/801582bf8b3b7ef6d245b18ceb0f6377a77f9afa/src/frontend/src/optimizer/plan_node/batch_values.rs#L102-L117
</details>
> fix(optimizer): impl ExprRewritable for StreamValues

- docker/docker-compose-standalone.yml
add a docker-compose file for standalone mode. Will update the docs.
resolve #12538 
</details>
> chore: add a docker compose file for standalone mode

- e2e_test/batch/basic/collation.slt.part
- src/frontend/src/binder/expr/mod.rs
- src/frontend/src/handler/create_table.rs
We don't support real collations, but we ignore it when the collation is "C" or "POSIX" as it is RisingWave's current default behavior.
The purpose of this PR is to make dremio work properly. resolve #13171.
When writing e2e test, I discovered a parser problem: `select varchar 't' collate "C"` cannot be parsed normally.
In order to make this PR easier, the parser problem will be solved in other PRs in the future.
</details>
> feat: ignore `collate` in `select` and `create table`

- ci/scripts/e2e-source-test.sh
- e2e_test/source/cdc_inline/postgres_create_drop.slt
- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzCdcEngineRunner.java
- proto/connector_service.proto
- src/connector/src/source/cdc/mod.rs
- src/connector/src/source/cdc/source/reader.rs
- src/connector/src/source/cdc/split.rs
- src/jni_core/src/jvm_runtime.rs
- src/source/src/connector_source.rs
- Make sure connector is inited before yielding the initial barrier (injected by the `CREATE TABLE`). Otherwise, the connector may start to run even after a `DROP TABLE` has been executed and cause unexpected race condition happen on upstream DB.
- other: migrate the `-Ddebezium.embedded.shutdown.pause.before.interrupt.ms` to embedded jvm
Fix the unstable [citus-cdc integration test](https://buildkite.com/risingwavelabs/integration-tests/builds/319#018b6c49-bbd3-4f54-9d41-6321d14fc68b)  …
> fix(cdc): ensure connector is inited after the CREATE TABLE is finished

- docker/docker-compose-standalone.yml
There's no static dashboard assets in the docker image. By specifying `ui-path` (which is meant to be used by developers), the dashboard service will fail to proxy the requests to GitHub user contents.
https://github.com/risingwavelabs/risingwave/blob/9bfa04cf25f4bf8ce5d7e6dc6e6333cceb81ab1a/src/meta/src/dashboard/mod.rs#L370-L400
This is a quick fix. However, I still think we should avoid external network requests in production and maybe we should pack the assets in the image. What do you think? @xxchan …
> fix(standalone): should not specify dashboard ui path

- ci/scripts/integration-tests.sh
specify rw image tag for integration test: `RW_IMAGE_TAG `
> chore(ci): specify rw image tag for integration test

- src/tests/regress/data/expected/delete.out
- src/tests/regress/data/schedule
- src/tests/regress/data/sql/delete.sql
enable the `delete.sql` PG regress test
Unsupported: 
`alias for the target table`
</details>
> test(regress): enable delete

- src/frontend/planner_test/tests/testdata/input/over_window_function.yaml
- src/frontend/planner_test/tests/testdata/output/nexmark.yaml
- src/frontend/planner_test/tests/testdata/output/over_window_function.yaml
- src/frontend/src/optimizer/logical_optimization.rs
- src/frontend/src/optimizer/plan_node/logical_over_window.rs
- src/frontend/src/optimizer/rule/mod.rs
- src/frontend/src/optimizer/rule/over_window_merge_rule.rs
Mentioned in https://github.com/risingwavelabs/risingwave/pull/13183#discussion_r1377554347.
Background:
1. Each `GroupTopN` can handle one rank function call, while `OverWindow` can handle multiple calls as long as they have the same `PARTITION BY` and `ORDER BY`.
2. We want to convert `row_number` and `rank` calls to `GroupTopN` as best as we can, so we split `OverWindow` with multiple rank function calls to multiple `OverWindow`s so that each `OverWindow` only handles one rank function.
3. After trying to convert split `OverWindow`s to `GroupTopN`s, some may remain unconverted due to not matching TopN pattern.
So, we …
> feat(optimizer): merge chaining `OverWindow`s with same partition by and order by

- src/connector/src/source/monitor/metrics.rs
- src/connector/src/source/nexmark/source/reader.rs
> chore: report stream chunk size as `partition_input_bytes` for workload generator

- e2e_test/streaming/aggregate/jsonb_agg.slt
- src/expr/impl/src/aggregate/jsonb_agg.rs
- src/expr/macro/src/gen.rs
As titled. 
With this PR, `Aggregation` can now use `Context` to get `arg_type/return_type`, just like what `Function` can do.
Aggregates values, including nulls, as a JSON array. The `ORDER BY` clause is optional and specifies the order of rows processed in the aggregation, which determines the order of the elements in the result array.
```bash title=Syntax
jsonb_agg ( expression ) -> jsonb    
```
~~Currently, input types include boolean, smallint, int, bigint, real, double precision, varchar and jsonb.~~
Aggregates name/value pairs as a JSON object.
```bash title=Syntax
jsonb_object_agg ( key , value ) -> jsonb …
```
> feat(expr): support list and struct in `jsonb_agg`/`jsonb_object_agg`

- Cargo.lock
- src/utils/pgwire/Cargo.toml
- src/utils/pgwire/src/lib.rs
- src/utils/pgwire/src/net.rs
- src/utils/pgwire/src/pg_server.rs
- src/workspace-hack/Cargo.toml
Allow listening on a unix socket for pgwire. Not much useful now but it's the default behavior of the Postgres server.
</details>
> feat(pgwire): listen on unix socket

- src/frontend/planner_test/tests/testdata/output/batch_index_join.yaml
- src/frontend/planner_test/tests/testdata/output/ch_benchmark.yaml
- src/frontend/planner_test/tests/testdata/output/distributed_lookup_join.yaml
- src/frontend/planner_test/tests/testdata/output/distribution_derive.yaml
- src/frontend/planner_test/tests/testdata/output/except.yaml
- src/frontend/planner_test/tests/testdata/output/index_selection.yaml
- src/frontend/planner_test/tests/testdata/output/intersect.yaml
- src/frontend/planner_test/tests/testdata/output/join.yaml
- src/frontend/planner_test/tests/testdata/output/nexmark.yaml
- src/frontend/planner_test/tests/testdata/output/subquery.yaml
- src/frontend/planner_test/tests/testdata/output/time_window.yaml
- src/frontend/planner_test/tests/testdata/output/tpch.yaml
- src/frontend/src/optimizer/plan_node/batch_lookup_join.rs
- Add lookup table to batch lookup join explain, so that we can easily see which indexes is selected to lookup.
</details>
> refactor(optimizer): add lookup table to batch lookup join explain

- src/connector/src/source/kafka/mod.rs
- src/connector/with_options.yaml
resolve #12846
ref `fetch.queue.backoff.ms` in https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md 
add `properties.fetch.queue.backoff.ms`, not required. accept `(0 .. 300000)`, default 1000 (1s)
</details>
> feat: add `properties.fetch.queue.backoff.ms` for kafka source

- ci/scripts/run-e2e-test.sh
- e2e_test/udf/graceful_shutdown_python.slt
- e2e_test/udf/test.py
- java/udf-example/src/main/java/com/example/UdfExample.java
- src/udf/python/CHANGELOG.md
- src/udf/python/pyproject.toml
- src/udf/python/risingwave/udf.py
This PR introduces a change to the Python UDF server's behavior in Kubernetes during a rolling update. Previously, the server would terminate immediately on receiving a SIGTERM signal, potentially leaving some RPCs incomplete, which could lead to expression errors and NULL outputs. The updated code now includes a SIGTERM hook that enables the Python UDF server to shut down gracefully, ensuring all RPCs are completed before exit.
Please note, this update only applies to the Python server. The Java UDF server still exits immediately on receiving SIGINT (from ctrl-c) or SIGTERM (from kill). A solution for the Java server …
> fix(udf): add graceful shutdown for python UDF server

- java/common-utils/src/main/java/com/risingwave/java/utils/MetaClient.java
- java/connector-node/risingwave-connector-test/src/test/java/com/risingwave/connector/sink/iceberg/IcebergSinkFactoryTest.java
- java/connector-node/risingwave-sink-cassandra/src/main/java/com/risingwave/connector/CassandraFactory.java
- java/connector-node/risingwave-sink-deltalake/src/main/java/com/risingwave/connector/DeltaLakeSinkFactory.java
- java/connector-node/risingwave-sink-iceberg/src/main/java/com/risingwave/connector/IcebergSinkFactory.java
- java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSinkFactory.java
- java/udf-example/pom.xml
- proto/catalog.proto
- proto/common.proto
- proto/ddl_service.proto
- proto/hummock.proto
- proto/plan_common.proto
- proto/stream_plan.proto
- src/common/src/catalog/mod.rs
- src/connector/src/parser/debezium/avro_parser.rs
- src/connector/src/schema/schema_registry/mod.rs
- src/frontend/src/handler/create_source.rs
- src/frontend/src/optimizer/plan_node/stream_table_scan.rs
- src/stream/src/from_proto/stream_scan.rs
Naming of `Enum`s should follow one of the below styles:
- Uppercase underscore style e.g. `STREAM_JOB_STATUS_UNSPECIFIED`
- Place the `Enum` in smaller namespace
This PR cleans the occurrences that doesn't follow either of them.
> chore(proto): standardize name of enums

- docker/docker-compose-standalone.yml
- docker/docker-compose-with-hdfs.yml
- docker/docker-compose.yml
> chore: add memory limit & restarts in docker-compose.yml

- docker/docker-compose-standalone.yml
- docker/docker-compose-with-azblob.yml
- docker/docker-compose-with-gcs.yml
- docker/docker-compose-with-hdfs.yml
- docker/docker-compose-with-oss.yml
- docker/docker-compose-with-s3.yml
- docker/docker-compose.yml
- docker/prometheus.yaml
Remove connector-node from docker-compose file.
Actually, #13067 has already removed it ([here](https://github.com/risingwavelabs/risingwave/pull/13067/files#diff-423deb13b7c401b1a7f41ee91c77f722e11d2f317d6a66b546524e8a04cc8b03L298))... cc. @neverchanje 
</details>
> fix: remove connector-node from docker

- .github/workflows/dashboard_main.yml
The dashboard artifacts are accessed if there're no local assets. They should also be rebuilt if there're changes under `proto/**`. Otherwise, changes like #13336 will break the UI as it uses pb-generated JSON as the protocol when communicating with the meta service.
Also add a manual rebuild button.
</details>
> fix(ci): rebuild dashboard artifacts on proto changes

- e2e_test/streaming/bug_fixes/issue_13094.slt
- src/meta/src/stream/stream_graph/schedule.rs
Fix #13094.
There's a singleton requirement on the fragment 6, and no-shuffle edges of 6-5 and 6-8. Then fragment 5 and 8 should also be singleton. Previously we don't have this rule.
</details>
> fix(meta): singleton requirement should be propagated through no-shuffle edges in scheduler

- ci/workflows/main-cron.yml
- src/tests/compaction_test/Cargo.toml
> fix: compaction test open enable_test_epoch flag

- src/connector/src/parser/protobuf/schema_resolver.rs
Before:
```
Protocol error: build_file_descriptor_set failed, operation failed
```
After:
```
Protocol error: build_file_descriptor_set failed. Errors:
aaa/common.proto: error: File not found.
```
`build_file_descriptor_set` returns an `OperationFailedError`, whose doc comment says:
> This error does not contain details about why the operation failed or what the operation was. Unfortunately this is a limitation of the underlying `libprotobuf` APIs.
> In some cases, you may be able to find an alternative API that returns a more descriptive error type (e.g., the APIs that return [`compiler::FileLoadError`])
The error …
> fix(source): informative error on protobuf `build_file_descriptor_set` failure

- docker/docker-compose-standalone.yml
- docker/docker-compose-with-hdfs.yml
- docker/docker-compose.yml
fix (https://buildkite.com/risingwavelabs/integration-tests/builds/335) caused by[#13343 ]
> fix(docker): fix memory limit suffix in docker compose

- e2e_test/udf/udf.slt
- src/common/src/types/mod.rs
- src/common/src/types/struct_type.rs
- src/connector/src/parser/json_parser.rs
- src/connector/src/parser/unified/json.rs
- src/frontend/planner_test/tests/testdata/output/struct_query.yaml
Undefined top-layer fields will we warned in a unified path after #12659, but nested field in struct of the JSON format will still be silently ignored. I don't find a way to also unify the path for this so manually add another `warn` here. (Maybe it's possible since a struct builder is essentially a `Vec` of nested builders?)
</details>
> fix(connector): warn on undefined nested field in struct when parsing JSON

- src/meta/src/serving/mod.rs
- src/meta/src/stream/scale.rs
- Solve https://github.com/risingwavelabs/risingwave/issues/13349
</details>
> fix(scale): fix serving fragment bitmap for scale

- src/common/src/config.rs
- src/config/example.toml
- src/meta/src/hummock/manager/mod.rs
- src/storage/src/hummock/local_version/pinned_version.rs
- src/storage/src/hummock/store/hummock_storage.rs
- src/storage/src/opts.rs
This PR adds an upper limiter for hummock version pinning duration, to avoid blocking storage GC infinitely.
A long hummock pinning duration can be caused by
- slow hummock iteration.
- bug that doesn't unpin version as expected.
The new config `max_version_pinning_duration_sec` is 3 hours by default. A version pinned by compute node will be unpinned after `max_version_pinning_duration_sec`. After that, there is no guarantee of success for hummock reading upon this version, because SSTs referenced by it may have been GCed.
If this PR includes changes that directly affect users or other significant modifications relevant …
> feat(storage): support max version pinning duration

- src/stream/src/executor/flow_control.rs
To reveal the real name of the wrapped executor in await-tree and tracing spans:
```diff
[Actor 21]
Actor 21: `CREATE MATERIALIZED VIEW mv AS SELECT * FROM t` [48.585s]
Epoch 5419982432698368 [889.601ms]
Materialize 1500000001 (actor 21) [889.601ms]
-     FlowControlExecutor 1500002743 (actor 21) [889.579ms]
+     StreamScan 1500002743 (flow controlled) (actor 21) [889.579ms]
ReceiverExecutor (actor 21) [889.579ms]
``` …
> fix(streaming): avoid shadowing identity when flow controlled

- src/connector/src/source/external.rs
- src/frontend/planner_test/tests/testdata/output/create_source.yaml
- src/frontend/src/optimizer/plan_node/stream_cdc_table_scan.rs
- src/sqlparser/README.md
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/tests/testdata/create.yaml
- src/stream/src/executor/backfill/cdc/cdc_backfill.rs
- src/stream/src/from_proto/source/trad_source.rs
- src/stream/src/from_proto/stream_scan.rs
- drop the database connection after backfill is done
- fix the distribution of `StreamCdcTableScan` to `SomeShard`, otherwise the mview fragment will be limited to singleton but actually mv needs to be sharded.
- fix https://github.com/risingwavelabs/risingwave/issues/13354
</details>
> fix(cdc): fix some cdc backfill issues

- src/storage/src/hummock/sstable_store.rs
Temporarily disable file cache insert when memory cache eviction, because it may cause tokio spawn when task drop, which madsim cannot support for now.
FYI: https://github.com/madsim-rs/madsim/issues/182
CI failure: https://buildkite.com/risingwavelabs/pull-request/builds/35387#018bcd05-4da3-488f-839c-412e04b84180
</details>
> fix: panic if spawn when task drop with madsim

- src/meta/src/manager/catalog/database.rs
- src/meta/src/manager/catalog/mod.rs
- Resolve https://github.com/risingwavelabs/risingwave/issues/13416
- Currently, both `in_progress_creation_streaming_job` and tables in the database manager could contain creating streaming jobs. We need to check them together.
</details>
> fix(meta): fix ctrl c cancels streaming job

- src/frontend/src/optimizer/plan_node/stream_sink.rs
> fix(frontend): refine error message on missing `force_append_only`

- src/common/src/field_generator/mod.rs
- src/common/src/field_generator/timestamp.rs
- src/connector/src/source/datagen/source/reader.rs
In preparation for `timestamptz` support #8550, we refactor the existing `TimestampField` generator (without time zone) to a generic one `ChronoField`. This PR intends to be a pure equivalent refactor without any new feature / bug fix.
The handling logic of `basetime` and `max_past_mode` has also been simplified.
</details>
> refactor(datagen): generalize `TimestampField` to `ChronoField`

- src/risedevtool/src/bin/risedev-dev.rs
- src/risedevtool/src/task.rs
- src/risedevtool/src/task/task_etcd_ready_check.rs
- src/risedevtool/src/task/task_kafka_ready_check.rs
- src/risedevtool/src/wait.rs
- Disable backtrace for risedev-dev itself to make it more user-friendly.
- Provide more error context if possible.
- Minor refactor to `wait_http` to reduce duplication.
- Avoid repeating the error after `main` returns.
</details>
> refactor(risedev): refine error reporting

- e2e_test/source/basic/datagen.slt
- src/common/src/array/data_chunk.rs
- src/common/src/field_generator/mod.rs
- src/common/src/field_generator/timestamp.rs
- src/connector/src/source/datagen/source/reader.rs
Resolves #8550. The same set of `timestamp` options can be used for `timestamptz` fields:
* `max_past`
* `max_past_mode`
* `basetime`
https://docs.risingwave.com/docs/current/ingest-from-datagen/#with-options---column_parameter
The `datagen` source can now generate `timestamptz` columns.
> feat(datagen): support `timestamptz`

- e2e_test/ddl/throttle.slt
- e2e_test/schema_registry/pb.slt
- e2e_test/source/basic/kafka.slt
- e2e_test/source/basic/old_row_format_syntax/kafka.slt
- src/frontend/src/utils/with_options.rs
> fix: reject duplicate entries in with clause

- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/progress.rs
- src/meta/src/barrier/recovery.rs
- src/meta/src/manager/catalog/fragment.rs
- src/tests/simulation/tests/integration_tests/recovery/background_ddl.rs
Previously we use all actors of the stream job, even those not used for `StreamTableScan`.
Since actors from other executors will never report they are finished, this means the stream job will also never complete.
We should only wait for actors from `StreamTableScan` to report their completion.
I ran the newly-added test without the fix, and with the fix.
Without the fix it will not complete.
It only affects background_ddl stream jobs after recovery. It won't affect background_ddl stream jobs which did not undergo cluster recovery, because they follow the same code path as foreground stream jobs. …
> fix(meta): use only `StreamTableScan` actors on recovery to track progress

- src/common/heap_profiling/src/profiler.rs
- src/common/src/config.rs
- src/compute/src/server.rs
- src/storage/compactor/src/server.rs
On compute nodes and compactor nodes, incorrect `total_memory` is used in auto heap dump.
</details>
> fix: incorrect auto dump threshold

- Cargo.lock
- src/storage/hummock_sdk/Cargo.toml
- src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
Simplify the `HummockVersionExt` and other related traits with `easy_ext`.
</details>
> refactor(storage): use easy_ext for HummockVersionExt

- ci/workflows/main-cron.yml
- ci/workflows/pull-request.yml
Similar to #12870, but without the need to create a PR (e.g. #13457).
Example usage:
https://buildkite.com/risingwavelabs/pull-request#new
`CI_STEPS=build,build-other,docslt,e2e-test`
Notes about regular expression:
Buildkite conditionals ([doc](https://buildkite.com/docs/pipelines/conditionals) [src](https://github.com/buildkite/conditional)) uses golang [regexp](https://pkg.go.dev/regexp) package:
> Metacharacters: `*+?()|`
> The operator precedence, from weakest to strongest binding, is first alternation, then concatenation, and finally the repetition operators.
* `(^|,)` and `(,|$$)` are used to prevent suffix and …
> ci: opt-in steps with build.env rather than pr labels

- proto/common.proto
- proto/meta.proto
- src/ctl/src/cmd_impl/await_tree.rs
- src/ctl/src/cmd_impl/meta/serving.rs
- src/frontend/src/catalog/system_catalog/mod.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_worker_nodes.rs
- src/frontend/src/meta_client.rs
- src/frontend/src/scheduler/distributed/query.rs
- src/frontend/src/scheduler/worker_node_manager.rs
- src/frontend/src/test_utils.rs
- src/meta/node/src/lib.rs
- src/meta/service/src/cluster_service.rs
- src/meta/service/src/notification_service.rs
- src/meta/service/src/scale_service.rs
- src/meta/src/controller/cluster.rs
- src/meta/src/dashboard/mod.rs
- src/meta/src/hummock/manager/gc.rs
- src/meta/src/hummock/manager/tests.rs
- src/meta/src/hummock/mock_hummock_meta_client.rs
- src/meta/src/hummock/test_utils.rs
- src/meta/src/manager/cluster.rs
- src/meta/src/manager/env.rs
- src/meta/src/model/cluster.rs
- src/meta/src/rpc/metrics.rs
- src/meta/src/stream/stream_manager.rs
- src/rpc_client/src/meta_client.rs
- src/storage/hummock_test/src/compactor_tests.rs
This PR extends rw_catalog.rw_worker_nodes by
- including all types of nodes, i.e. meta node/compactor node/compute node/frontend node. Before it only includes compute nodes.
- adding more columns: 
- `rw_version/total memory bytes/total cpu cores`, which is reported by worker node when it starts.
- `started_at`, which is populated by meta node when a worker node starts.
- These info are not persisted in meta store. They'll be updated whenever worker node restarts.
```
dev=> select * from rw_worker_nodes;
id |   host    | port |           type           |  state  | parallelism | is_streaming | is_serving | …
```
> refactor(rw_catalog): make rw_worker_nodes list all nodes and resource

- e2e_test/source/basic/kafka.slt
- e2e_test/source/basic/kafka_batch.slt
- e2e_test/source/basic/nosim_kafka.slt
- e2e_test/source/basic/old_row_format_syntax/kafka.slt
- e2e_test/source/basic/old_row_format_syntax/kafka_batch.slt
- e2e_test/source/basic/old_row_format_syntax/nosim_kafka.slt
- src/frontend/planner_test/tests/testdata/input/batch_source.yaml
- src/frontend/planner_test/tests/testdata/output/batch_source.yaml
- src/frontend/planner_test/tests/testdata/output/struct_query.yaml
- src/frontend/src/handler/create_source.rs
fix https://github.com/risingwavelabs/risingwave/issues/13503
</details>
> fix(source): make _rw_key not hidden column

- e2e_test/batch/functions/encdec.slt.part
- proto/expr.proto
- src/expr/impl/src/scalar/encdec.rs
- src/frontend/src/binder/expr/function.rs
- src/frontend/src/expr/pure.rs
resolve #13306.
Support text conversion function `convert_from` and `convert_to`. But only encoding `UTF8` is supported.
RisingWave uses UTF8 encoding to store text, so all that is done here is just type conversion.
</details>
> feat: support `convert_from`/`convert_to` function that only support UTF8 encoding

- integration_tests/big-query-sink/README.md
- integration_tests/big-query-sink/append-only-sql/create_source.sql
- integration_tests/cassandra-and-scylladb-sink/create_source.sql
- integration_tests/redis-sink/create_source.sql
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#datetime_type
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#timestamp_type
> To represent an absolute point in time, use a timestamp.
> To represent a Gregorian date and time as they might appear on a watch, use a datetime value.
https://cassandra.apache.org/doc/stable/cassandra/cql/types.html#timestamps
https://opensource.docs.scylladb.com/stable/cql/types.html#working-with-timestamps
> it is recommended that the time zone always be specified for timestamps when feasible
The following sinks will be handled in a followup: …
> fix(integration_tests): use `timestamptz` for BigQuery, Cassandra and Redis

- docker/Dockerfile
Install perf flamegraph in docker image
> feat: add perf-flamegraph tools in docker image

- Cargo.lock
- proto/meta.proto
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_event_logs.rs
- src/meta/Cargo.toml
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/manager/event_log.rs
part of #12826
Failed barrier doesn't write a event log.
Event log table only records latest 10 events for each type by default. We can customize it on demand.
```
dev=> select * from rw_catalog.rw_event_logs where event_type='BARRIER_COMPLETE';
unique_id               |           timestamp           |    event_type    |                                                                                       info                                                                                       
--------------------------------------+-------------------------------+------------------+------------------------------------- …
```
> feat(meta): record barrier latency in event table

- src/common/src/types/jsonb.rs
- src/common/src/util/value_encoding/mod.rs
resolve #8915 
With #11805, we can get accurate jsonb value size now. This PR fixes the estimated jsonb value encoding size. But notice that it is not exact, because the value encoding is the json string, not the internal jsonbb encoding.
> fix: estimate jsonb's value encoding size

- src/compute/src/rpc/service/exchange_service.rs
As explained in #13592.
</details>
> fix(streaming): use correct label for `stream_fragment_exchange_bytes` metrics

- src/rpc_client/src/lib.rs
- Related Issue https://github.com/risingwavelabs/risingwave/issues/13459
- Sysbench shows that RPC connection pool `get_by_addr` consumes about 3.25% CPU. We can use a `Arc` value to avoid the expensive `Vec` clone.
</details>
> feat(batch): improve connection pool value

- integration_tests/cassandra-and-scylladb-sink/docker-compose.yml
- integration_tests/clickhouse-sink/docker-compose.yml
- integration_tests/redis-sink/docker-compose.yml
Likely resulted from careless copy-pasta. Saves some building time during tests without breaking any:
https://buildkite.com/risingwavelabs/integration-tests/builds/392
By the way we have at least three different variants of `datagen` in integration tests:
* `integration_tests/datagen` written in Go.
* `connector = 'datagen'` as part of kernel.
* Custom scripts. (eg `debezium-mysql`, `debezium-postgres`, `schema-registry`, `upsert-avro`)
These 3 cases use the kernel one but declares the Go one as dependency. …
> chore(integration_tests): cleanup unused datagen.go build

- src/compute/src/memory/config.rs
The `reserved_memory` is designed for the difference between actual usage (`jemalloc_allocated`) and process usage (`process_resident_memory`).
https://github.com/risingwavelabs/risingwave/blob/b640bc99952d4541a6f43213f57883f2798d76b6/src/compute/src/memory/config.rs#L40-L42
As being observed in #13610,
> - jemalloc_allocated_bytes: 8.59 GB
> - jemalloc_active_bytes: 9.93 GB
> - Node memory (RSS): 12.3 GB
The ratio is `8.59/12.3 = 0.698 ≈ 0.7`.
Passed longevity test: https://buildkite.com/risingwave-test/longevity-test/builds/818 (Previously this would OOM for 2 times) …
> fix(memory): increase reserved mem to 30%

- integration_tests/clickhouse-sink/create_source.sql
- src/connector/src/sink/clickhouse.rs
https://clickhouse.com/docs/en/sql-reference/data-types/datetime64
> Internally, stores data as a number of ‘ticks’ since epoch start (1970-01-01 00:00:00 UTC) as Int64.
https://clickhouse.com/docs/en/interfaces/formats#data-format-avro
> | Avro data type INSERT | ClickHouse data type | Avro data type SELECT |
> | - | - | - |
> | long (timestamp-millis) ** | DateTime64(3) | long (timestamp-millis) ** |
> | long (timestamp-micros) ** | DateTime64(6) | long (timestamp-micros) ** |
There is no corresponding type for avro `local-timestamp-millis` or `local-timestamp-micros`.
- …
> fix(sink): ClickHouse DateTime64 should be timestamptz

- ci/scripts/check.sh
Tracked by: https://github.com/risingwavelabs/risingwave/issues/13703
There's no solution for it currently. So just ignore it for now else all PRs are blocked.
</details>
> chore(ci): skip `rsa` crate warning temporarily

- ci/scripts/run-e2e-test.sh
Temporarily disable the flaky test on CI.
> fix(ci): disable python udf retry test

- .github/workflows/cherry-pick-to-release-branch.yml
Update cherry pick action version to v1.5.0
> chore: update cherry pick action version to v1.5.0

- proto/meta.proto
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_event_logs.rs
- src/meta/service/src/event_log_service.rs
- src/meta/src/manager/event_log.rs
- src/rpc_client/src/lib.rs
- src/rpc_client/src/meta_client.rs
This PR records panic from worker nodes in system event table. It updates the panic hook when the meta RPC client is created, and sends panic info to meta node via RPC on panic.
```
dev=> select * from rw_event_logs where event_type='WORKER_NODE_PANIC';
unique_id               |           timestamp           |    event_type     |                                                                                                                                 info …
```
> feat(meta): try to record panic info from worker nodes

- Makefile.toml
as title
The main motivation is that check-trailing-spaces (and hakari) often breaks, and I don't want to run clippy as it's slow.
Maybe we can also add `check-fast` to pre-commit hook, and/or CI auto fix (like hakari-fix)
</details>
> chore(risedev): split some tasks from `check` to `check-fast`

- src/meta/service/src/scale_service.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/rpc/ddl_controller.rs
When a DDL request is sent to the meta service which is under failure recovery, the failure cause will be included in the error message as well. Thanks to the progress made on #11443, all we need to do is to correctly return the error in meta.
```
2: The cluster is recovering
3: gRPC request to stream service failed: Internal error
4: Actor 4 exited unexpectedly
5: Executor error
6: Chunk operation error
7: Division by zero
```
It's worth noting that after #12999, the message will …
> feat(meta): show recovery cause when request is rejected

- e2e_test/udf/test.py
- e2e_test/udf/udf.slt
- java/udf-example/pom.xml
- java/udf-example/src/main/java/com/example/UdfExample.java
- java/udf/CHANGELOG.md
- java/udf/pom.xml
- java/udf/src/main/java/com/risingwave/functions/TypeUtils.java
- src/expr/core/src/expr/expr_udf.rs
- src/udf/python/CHANGELOG.md
- src/udf/python/pyproject.toml
- src/udf/python/risingwave/udf.py
This PR fixed the panic:
```
failed to convert UDF output to DataChunk: FromArrow("invalid decimal: \"-5.10043e-05\"")
```
First of all, as mentioned in #9002, compute nodes must not panic on errors caused by UDF servers. cc @KveinAxel 
Next, after #11839, decimal values are stored as strings in the arrow array. However, the panic message indicates that a float number with scientific notation `-5.10043e-05` was written by Python, and it couldn't be parsed by rust decimal. It turned out that user defined a function returning `NUMERIC`, but the actual return value is a `float` rather than `Decimal`. Even it returns a …
> fix(udf): avoid panic on invalid output and fix decimal output scale lost

- e2e_test/batch/basic/make_timestamptz.slt.part
- e2e_test/streaming/expr_context.slt
- proto/plan_common.proto
- proto/stream_plan.proto
- proto/task_service.proto
- src/batch/src/execution/grpc_exchange.rs
- src/batch/src/rpc/service/task_service.rs
- src/batch/src/task/task_execution.rs
- src/batch/src/task/task_manager.rs
- src/expr/core/Cargo.toml
- src/expr/core/src/expr_context.rs
- src/expr/core/src/lib.rs
- src/expr/impl/src/scalar/make_timestamptz.rs
- src/expr/macro/src/context.rs
- src/expr/macro/src/lib.rs
- src/frontend/src/scheduler/distributed/stage.rs
- src/frontend/src/scheduler/local.rs
- src/meta/model_v2/src/actor.rs
- src/meta/model_v2/src/lib.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/model/stream.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/stream_graph/actor.rs
- src/meta/src/stream/test_fragmenter.rs
- src/rpc_client/src/compute_client.rs
- src/stream/src/executor/actor.rs
- src/stream/src/executor/integration_tests.rs
- src/stream/src/task/stream_manager.rs
As title, followup of https://github.com/risingwavelabs/risingwave/pull/13647.
```
make_timestamptz (year int, month int, day int, hour int, min int, sec double precision [, timezone text ]) → timestamptz
Create timestamp with time zone from year, month, day, hour, minute and seconds fields (negative years signify BC). If timezone is not specified, the current time zone is used; the examples assume the session time zone is Europe/London.
make_timestamptz(2013, 7, 15, 8, 15, 23.5) → 2013-07-15 08:15:23.500+01:00
make_timestamptz(2013, 7, 15, 8, 15, 23.5, 'America/New_York') → 2013-07-15 13:15:23.500+01:00
```
> feat(expr): support streaming make_timestamptz

- docker/Dockerfile
It seems that we must update before apt-get install, otherwise will failed.
failed pipeline: https://buildkite.com/risingwavelabs/docker/builds/14838
test pipeline: https://buildkite.com/risingwavelabs/docker/builds/14849
</details>
> fix(docker): fix apt install failed

- src/meta/src/manager/catalog/fragment.rs
- src/meta/src/model/stream.rs
Fix https://github.com/risingwavelabs/risingwave/issues/13883.
</details>
> fix(compatibility): always fill expr_context in `StreamActor`

- src/expr/core/src/expr/build.rs
- src/expr/core/src/expr/mod.rs
- src/expr/impl/src/scalar/case.rs
- src/expr/impl/src/scalar/mod.rs
Sometimes the CASE expression fails to short circuit, causing the last matching value to be returned instead of the first one. 
```diff
dev=> create table t(x boolean, a int, y boolean, b int);
CREATE_TABLE
dev=> insert into t values (true, 1, true, 2);
INSERT 0 1
dev=> select *, case when x then a when y then b end from t;
x | a | y | b | case 
---+---+---+---+------
- t | 1 | t | 2 |    2
+ t | 1 | t | 2 |    1
```
The reason is that some expressions **ignore the visibility and return non-null values for invisible rows.** Examples include literal expression and simd-optimized expressions such as `=`. The CASE …
> fix(expr): fix a critical bug in case expression

- proto/meta.proto
- proto/stream_plan.proto
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_relation_info.rs
- src/frontend/src/handler/create_mv.rs
- src/frontend/src/stream_fragmenter/graph/fragment_graph.rs
- src/meta/service/src/stream_service.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/model/stream.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/test_fragmenter.rs
As mentioned in https://github.com/risingwavelabs/risingwave/pull/13702#discussion_r1414859020, in `stream_manager`, we have two different data structure both called `StreamEnvironment`, which is confusing. This PR rename one to `StreamContext` to avoid the ambiguity.
Simply renaming one message should not cause compatiblity issues. As protobuf use type and serial number to recognize one message. …
> chore(stream): rename StreamEnvironment to StreamContext

- src/common/src/util/epoch.rs
- src/storage/hummock_sdk/src/lib.rs
#13696 fixes the max epoch bug for range tombstone but introduces a overflow panic when the provided epoch is u64::MAX. For example, the HummockEpoch::MAX epoch [here](https://github.com/risingwavelabs/risingwave/blob/798c36f5bccfe981db4c14a85f6e54dd77db856f/src/stream/src/common/log_store_impl/kv_log_store/reader.rs#L133) will be later used to [create EpochWithGap with MAX_SPILL_TIMES](https://github.com/risingwavelabs/risingwave/blob/798c36f5bccfe981db4c14a85f6e54dd77db856f/src/storage/src/hummock/iterator/forward_user.rs#L187), which will cause a u64 overflow. This panic will be 100% triggered for sinks with log …
> fix: use EpochWithGap::new_max_epoch if the provided epoch is max epoch

- docker/docker-compose-with-azblob.yml
- docker/docker-compose-with-gcs.yml
- docker/docker-compose-with-oss.yml
- docker/docker-compose-with-s3.yml
- docker/multiple_object_storage.env
As title, has verified via oss.
</details>
> feat(docker): standalone mode for docker compose with different object storage

- Cargo.lock
- Cargo.toml
- src/common/Cargo.toml
- src/common/fields-derive/Cargo.toml
- src/common/fields-derive/src/lib.rs
- src/common/src/catalog/schema.rs
- src/common/src/lib.rs
- src/common/src/types/fields.rs
- src/common/src/types/mod.rs
- src/common/src/types/with_data_type.rs
- src/frontend/src/lib.rs
Resolve #13851 
https://github.com/risingwavelabs/risingwave/blob/585f6379c65649f92c4f71dfe5747714d6429ee3/src/common/src/types/fields.rs#L38-L76
</details>
> feat(types): add Fields trait and derive macro

- src/storage/hummock_sdk/src/key.rs
- src/storage/src/hummock/sstable/mod.rs
- src/storage/src/hummock/sstable/utils.rs
Currently, the encoder function of `Sstable` only receives `&Vec<u8>`. It has met most cases before, but we still have cases that requires it can be directly encoded to an existing buffer to avoid buffer copy. For example, file cache requires `Key` and `Value` to implement `fn write(&self, buf: &mut [u8])` to encode data directly into the preallocated buffer. With the current buffer, it can only be encoded to a `Vec<u8>` then copied to the buffer.
`ButMut` provides interfaces like `put_xxx` which are very useful for serialization. But for `ButMut` is designed for both block and stream, it does not provide either the …
> refactor(storage): refactor sstable encode function receiver

- Makefile.toml
- ci/workflows/pull-request.yml
- src/tests/simulation/tests/integration_tests/recovery/event_log.rs
The ignored tests are not critical but hurt CI performance.
</details>
> chore: disable failpoint test in simulation integration test

- src/common/proc_macro/src/session_config.rs
- src/common/src/session_config/mod.rs
#13265 
- allow adding alias for parameter name 
</details>
> feat(session_config): allow add alias for parameter name 

- src/common/src/config.rs
- src/common/src/session_config/mod.rs
- src/config/example.toml
- src/frontend/src/handler/query.rs
- src/frontend/src/scheduler/distributed/query.rs
- src/frontend/src/scheduler/distributed/query_manager.rs
- src/frontend/src/scheduler/error.rs
- src/frontend/src/scheduler/local.rs
- src/frontend/src/scheduler/mod.rs
- src/frontend/src/session.rs
Close #7409 .
Releated #9732.
In this pr we add `statement_timeout` for dql statement, other ddl, dml statements are not affected. The default value is 1 hour.
User can run `set statement_timeout = 10` to set the value for session. And the default value is in config `batch.statement_timeout_in_sec`, default value is 1 hour.
</details>
> feat: Add statement_timeout for query.

- .github/workflows/cherry-pick-to-release-branch.yml
@Jianwei just found that a few PRs skipped the cherry-pick Github Action and thus they are not merged into the release branch.
It is because the PR is already merged and does not include the changes in the yaml config file of the action, e.g.: https://github.com/risingwavelabs/risingwave/blob/main/.github/workflows/cherry-pick-to-release-branch.yml#L9-L23
Therefore the label is not recognized and cannot pass the `if` condition and gets skipped.
We disable this trigger of cherry-picking to avoid confusion. …
> chore: disable cherry-picking through labeling after PR is merged

- src/meta/src/hummock/compaction/picker/min_overlap_compaction_picker.rs
close https://github.com/risingwavelabs/risingwave/issues/10109
When there are too many small files in base level, meta-node may cost too much time to pick one task. Because the time complexity of `MinOverlappingPicker` is O(N^2*k), where k represent the overlap size of next level.
But most of case could be solved by trivial move, so we can pick trivial move file at the beginning of picker. The time complexity of `TrivialMovePicker` is O(N*logN).
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of …
> fix(meta): reduce time complexity of MinOverlappingPicker

- src/stream/src/executor/over_window/general.rs
- src/stream/src/executor/over_window/over_partition.rs
Over window locality-based range cache was introduced in https://github.com/risingwavelabs/risingwave/pull/11576. After that, we switched to use the new state table interface `iter_with_prefix` that accepts `pk_prefix` and `pk_subrange` as arguments, in https://github.com/risingwavelabs/risingwave/pull/12872. In the latter PR, the logic of projection from `StateKey` (range cache key) to state table sub pk, which is used to construct `pk_subrange`, should be modified to handle a corner case of key deduplication but NOT. The case is that, when `order by` columns and input stream key columns contain duplicated columns in …
> fix(over window): fix range cache when some of `order by` and input stream key columns are in `partition by` columns

- src/frontend/planner_test/tests/testdata/input/subquery.yaml
- src/frontend/planner_test/tests/testdata/input/subquery_expr_correlated.yaml
- src/frontend/planner_test/tests/testdata/output/subquery.yaml
- src/frontend/planner_test/tests/testdata/output/subquery_expr_correlated.yaml
- src/frontend/src/binder/expr/mod.rs
- src/frontend/src/expr/subquery.rs
- src/frontend/src/planner/select.rs
- Support array subquery which leads to supporting `\du` automatically.
- Resolve #13519
Example:
```
dev=> \du
List of roles
Role name |                         Attributes                         | Member of
-----------+------------------------------------------------------------+-----------
postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {NULL}
root      | Superuser, Create role, Create DB, Replication, Bypass RLS | {NULL}
``` …
> feat(optimizer): support array subquery and \du

- src/stream/src/executor/over_window/general.rs
- src/stream/src/executor/over_window/over_partition.rs
Previously we calculate the projection from `StateKey` (over window cache key type) to state table sub pk (used to do prefixed table scanning) for each over window partition, which can cost unnecessary CPU time. This PR moves the calculation to executor `new`, so that each `OverWindowExecutor` instance only need to calculate the projection once.
Some explanation for the words:
- `StateKey`: Over window range cache key type, containing order key and input pk.
- State table sub-PK: State table PK = PK prefix (partition key) + sub-PK (order key + input pk).
- Input/output row: Input schema is the prefix of output schema. …
> refactor(over window): reduce repeated calculation of projection from state key to table sub-pk

- e2e_test/batch/aggregate/ordered_set_agg.slt.part
- src/frontend/planner_test/tests/testdata/input/agg.yaml
- src/frontend/planner_test/tests/testdata/output/agg.yaml
- src/frontend/src/binder/expr/function.rs
> Docs for background info:
> - https://docs.risingwave.com/docs/current/sql-function-aggregate/#ordered-set-aggregate-functions
> - https://www.postgresql.org/docs/current/xaggr.html#XAGGR-ORDERED-SET-AGGREGATES
> - https://www.postgresql.org/docs/current/functions-aggregate.html#FUNCTIONS-ORDEREDSET-TABLE
Previously we don't support `NULL` and expression as direct arguments of ordered-set aggregate function. E.g.
```sql
create table t (a int);
select percentile_cont(null) within group (order by a) from t;
select percentile_cont(0.1 + 0.2) within group (order by a) from t;
```
This PR supports this syntax.
Variables in …
> feat(ordered-set agg): allow constant expression and NULL as direct argument

- e2e_test/sink/sink_into_table.slt
- src/connector/src/sink/catalog/mod.rs
- src/connector/src/sink/formatter/mod.rs
- src/frontend/src/handler/create_sink.rs
- src/sqlparser/src/keywords.rs
Current behaviors
```
dev=> create sink s into t as select * from tt;
Caused by:
Bind error: Only append-only sinks can sink to a table without primary keys. Please try to add "FORMAT PLAIN ENCODE NATIVE"
dev=> create sink s into t as select * from tt with (type='append-only');
Caused by:
Bind error: connector table does not support `type = '...'`, please use syntax `FORMAT ... ENCODE ...` instead.
dev=> create sink ss into t as select max(v) from tt FORMAT PLAIN ENCODE NATIVE;
Caused by these errors (recent errors listed …
```
> feat(sink): support format encode syntax for sink into table

- src/expr/core/src/expr/build.rs
- src/expr/core/src/expr/wrapper/non_strict.rs
quick fix for #14027 
This PR introduces a `NonStrictNoFallback` wrapper for `UdfExpression`. It won't fallback to evaluation by row, but will return NULL for all rows instead.
Now UDF server failures no longer block the stream and can be recovered quickly.
Note that this is still an ad-hoc solution which may be refactored completely in the future.
> fix(udf): don't fallback to row-based evaluation for udf

- src/meta/src/hummock/compaction/mod.rs
- src/meta/src/hummock/compaction/picker/min_overlap_compaction_picker.rs
Although https://github.com/risingwavelabs/risingwave/pull/14036 has optimize the performance of pick trivial move task of MinOverlappingPicker, it is still not enough. Because the PR above only assume that most of files could trivial moved to next level, we do not need to calculate scores for all possible task. But when there are really a large data in hummock, and most of them can not be compacted to next level by trivial-move, hummock will cost a long time to pick one task, and meta-node would hold the mutex for a long time, too.
In original algorithm, we iterator all possible interval for select-level, and we check …
> feat(meta): optimize the complexity of MinOverlappingPicker

- src/storage/hummock_test/src/state_store_tests.rs
- src/storage/hummock_trace/src/opts.rs
- src/storage/src/hummock/store/local_hummock_storage.rs
- src/storage/src/hummock/utils.rs
- src/storage/src/mem_table.rs
- src/storage/src/store.rs
- src/stream/src/common/log_store_impl/kv_log_store/mod.rs
- src/stream/src/common/table/state_table.rs
- src/stream/src/executor/mview/materialize.rs
Previously in local state store, for case `is_consistent_op=true`, we compare the serialized bytes of old value, which may fail the sanity check after schema check. In this PR, we change to pass a dynamic old value checker to perform the old value sanity check. In this way, we can create a dynamic old value checker in state table to deserialize the raw value bytes and compare the row value. 
We change the bool `is_consistent_op` in `NewLocalOptions` to an enum `OpConsistentLevel`. 
The state table of materialized executor has `is_consistent_op=true` even after schema check. …
> feat(storage): compare deserialized row value in sanity check

- src/common/src/monitor/connection.rs
Add rpc client dns resolve info log.
#14207 
</details>
> chore(monitor): add info log for client dns resolve

- src/common/src/array/data_chunk.rs
- src/common/src/types/mod.rs
- src/expr/core/src/expr/expr_some_all.rs
fix #14214, which was introduced by #13402.
```diff
dev=> select a = any(b) from (values (1, array[1,2]), (1, array[2,1])) as t(a, b);
?column? 
----------
t
- f
+ t
(2 rows)
dev=> select a = all(b) from (values (1, array[2,3]), (1, array[1])) as t(a, b);
?column? 
----------
f
- f
+ t
(2 rows)
```
When short-circuit occurred, the `resolve_bools` function did not consume all items in the input iterator, causing subsequent booleans to be misaligned.
Fixes the correctness of SOME/ALL/ANY expressions. **The fix introduces a breaking change** for versions from v1.5.0 to v1.5.3. It is recommended to drop and recreate any …
> fix(expr): fix `SOME/ALL/ANY` expression

- src/connector/src/macros.rs
- src/connector/src/source/base.rs
- src/connector/src/source/filesystem/opendal_source/mod.rs
- src/connector/src/source/filesystem/opendal_source/s3_source.rs
- src/connector/src/source/filesystem/s3/enumerator.rs
- src/connector/src/source/filesystem/s3/mod.rs
- src/connector/src/source/filesystem/s3/source/reader.rs
1. remove the `if` in `extract`
IIUC, previously we need the `if` here because `s3_v2` and `s3` shares the same config struct, and thus the macro cannot dispatch correctly. Since we have separated types now, the special treatment seems unnecessary and confusing.
2. Share a `S3PropertiesCommon`, instead of the top-level `S3Properties`. This corresponds to the pattern described in https://github.com/risingwavelabs/risingwave/pull/13654#discussion_r1435967669 . (We need to add `unknown_fields` in both the top-level structs later..) …
> refactor(source): refactor s3 source `WITH` options handling

- src/common/src/config.rs
> chore: disable fast compaction by default

- src/stream/src/executor/aggregation/agg_group.rs
As widely and deeply discussed in #14031 and many slack threads, seems we finally decided to tolerate inconsistent data in the stream. So this PR makes HashAgg not panic when encounter inconsistent `DELETE`s. In the future we may introduce a sys param or session variable to allow user turn on [**strict mode**](https://github.com/risingwavelabs/risingwave/issues/14031#issuecomment-1864342006) to ensure consistency. …
> chore(agg): comment out `bad row count` panic

- Cargo.lock
- src/meta/Cargo.toml
- src/meta/service/src/scale_service.rs
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/recovery.rs
- src/meta/src/stream/scale.rs
- src/meta/src/stream/source_manager.rs
- src/meta/src/stream/stream_manager.rs
> refactor(meta): readability improvements on source manager

- src/expr/core/src/error.rs
- src/expr/core/src/expr/build.rs
- src/expr/core/src/expr/wrapper/mod.rs
- src/expr/core/src/expr/wrapper/non_strict.rs
- src/expr/core/src/expr/wrapper/strict.rs
- src/expr/impl/src/scalar/arithmetic_op.rs
- src/expr/macro/src/gen.rs
resolve #14027 and replace #14147
This PR introduces a `MultiExprError` to collect function errors by each row. The `NonStrict` wrapper can identify this error and return partial results without falling back to evaluation row by row.
> refactor(expr): don't fallback to evaluation by row on error

- e2e_test/sink/sink_into_table.slt
- src/connector/src/sink/catalog/mod.rs
- src/connector/src/sink/formatter/mod.rs
- src/frontend/src/handler/create_sink.rs
- src/sqlparser/src/keywords.rs
This reverts commit 29e62e6d27f1f028509819cba445e6524af07db5.
Because we have not reached a consensus If we will use the `FORMAT ... ENCODE ...` for all the sinks. And declare `FORMAT ENCODE` for a sink to the table is a little strange
</details>
> feat: Revert "feat(sink): support format encode syntax for sink into table (#14134)

- src/storage/hummock_test/src/compactor_tests.rs
- src/storage/src/hummock/compactor/fast_compactor_runner.rs
- src/storage/src/hummock/sstable/builder.rs
In fast compact, if the last key is added to sstable one by one, we must check the start key of next block before we copy it into new sstable. Because if the last key is a tombstone and we have removed it, all keys of next block must check whether they share the same user key with the last key.
This bug may be one of the reasons which cause stream inconsistant: https://github.com/risingwavelabs/risingwave/issues/14031
Because if one tombstone is deleted but we keep the put key following it, streaming state may find a deleted key in query result.
If this PR includes changes that directly affect users or other significant …
> fix(compactor): fix put key miss tombstone

- src/common/src/types/decimal.rs
- src/frontend/planner_test/tests/testdata/input/expr.yaml
- src/frontend/planner_test/tests/testdata/output/expr.yaml
- src/frontend/src/binder/expr/value.rs
- src/sqlparser/src/tokenizer.rs
- src/sqlparser/tests/testdata/select.yaml
Resolves #14096. The new syntax was added in PostgreSQL 16 for SQL 202x.
Limitations:
* Underscores as separators are not supported (eg `0xdead_beef`)
* Only during sqlparsing but not execution (eg `'0x20'::int` / source ingestion / pgwire text protocol)
Breaking change:
* For `0b10`, older version interprets it as `0 as b10` but new versions interprets it as binary `10` (= `2` in decimal). It was not an issue in PostgreSQL because such input has always been considered invalid and we are now rejecting `0c10` similarly.
Integer literals can now be given in hex `0x`, oct `0o` and bin `0b`.
> feat(sqlparser): support literal integers in hex / oct / bin

- java/connector-node/tracing/pom.xml
- java/connector-node/tracing/src/main/java/com/risingwave/tracing/TracingSlf4jAdapter.java
- java/pom.xml
Output after fix:
```
2023-12-29T14:29:15.488752+08:00 ERROR risingwave_connector_node: Internal error on source validation: org.postgresql.util.PSQLException: The connection attempt failed.
at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:331)
at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:247)
at org.postgresql.Driver.makeConnection(Driver.java:434)
at org.postgresql.Driver.connect(Driver.java:291)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
at …
```
> fix(connector): print Java exception stacktrace in log

- src/stream/src/executor/source/fs_source_executor.rs
- src/stream/src/executor/source/source_executor.rs
When the parallelism is high, the log can easily fill up several pages.
The logs seem only useful for developers who want to do debugging. 
</details>
> chore: make some source log debug instead of info

- proto/catalog.proto
- src/frontend/src/binder/expr/function.rs
- src/frontend/src/catalog/function_catalog.rs
- src/frontend/src/expr/user_defined_function.rs
- src/frontend/src/handler/create_function.rs
- src/frontend/src/handler/create_sql_function.rs
- src/meta/model_v2/migration/src/m20230908_072257_init.rs
- src/meta/model_v2/src/function.rs
- src/meta/src/controller/mod.rs
As titled.
This branch is based on #14139, just for review convenience.
</details>
> feat(udf): add `body` field for udf body definition

- src/frontend/src/optimizer/plan_node/generic/scan.rs
- Resolve https://github.com/risingwavelabs/risingwave/issues/14301
- Internal tables have no stream key, so we just return a None for stream_key of internal table. Otherwise, functional dependencies could be derived from the wrong info.
```
dev=> explain select count(*) from __internal_v_4_hashjoinleft_1003 group by t_a;
QUERY PLAN
---------------------------------------------------------------------------------------
BatchExchange { order: [], dist: Single }
└─BatchProject { exprs: [count] }
└─BatchSortAgg { group_key: [__internal_v_4_hashjoinleft_1003.t_a], aggs: [count] }
└─BatchScan { table: …
```
> fix(optimizer): internal tables return no stream key

- e2e_test/streaming/over_window/main.slt
- src/stream/src/executor/over_window/general.rs
- src/stream/src/executor/over_window/over_partition.rs
Previously the `extend_cache_by_range(self, table, range: RangeInclusive<&StateKey>)` method wrongly shortcut returned after loading the left half of `range`, pseudo-code like below:
```rust
if left_extendable && range.start < first_key_in_cache {
return extend_cache_by_range_inner(Range(Include(range.start), Exclude(first_key_in_cache)));
}
if right_extendable && range.end > last_key_in_cache {
return extend_cache_by_range_inner(Range(Exclude(last_key_in_cache), Include(range.end)));
}
```
But it actually should be:
```rust
if left_extendable && range.start < first_key_in_cache { …
```
> fix(over window): fix over window range cache shortcut return

- src/stream/src/executor/mview/materialize.rs
Have checked the memtable's consistent check taking effect by deliberately introducing some bugs in the materialize executor.
</details>
> test(streaming): add fuzz test for materialize handle conflict

- src/compute/src/rpc/service/stream_service.rs
- src/stream/src/executor/actor.rs
- src/stream/src/executor/chain.rs
- src/stream/src/executor/values.rs
- src/stream/src/from_proto/barrier_recv.rs
- src/stream/src/from_proto/now.rs
- src/stream/src/from_proto/source/trad_source.rs
- src/stream/src/from_proto/values.rs
- src/stream/src/task/barrier_manager.rs
- src/stream/src/task/barrier_manager/progress.rs
- src/stream/src/task/barrier_manager/tests.rs
- src/stream/src/task/mod.rs
- src/stream/src/task/stream_manager.rs
Previously, we implement our local barrier manager as a struct shared by `Arc<Mutex<LocalBarrierManager>>`. In this PR, we implement the local barrier manager as a worker loop spawned as tokio task, and all original operations on it will be sent as worker events. In this way, there will be less contention between actors, and it is better for the implementation of partial checkpoint that will report the barrier progress in a finer granularity.
Some refactors are done accordingly.
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release …
> refactor: implement local barrier manager as event handler

- src/stream/src/executor/mview/materialize.rs
Fix #14347 
1. We still need to store the value in cache when the stream is retractable even if we use the ignore behavior.
2. We need to update cache value to None when deleting a row.
</details>
> fix(stream/materialize): incorrect implementation in ignore-conflict behavior

- ci/scripts/notify.py
- ci/scripts/s3-source-test-for-opendal-fs-engine.sh
- ci/workflows/main-cron.yml
- e2e_test/s3/gcs_source.py
- src/connector/src/source/base.rs
- src/connector/src/source/filesystem/opendal_source/gcs_source.rs
- src/connector/src/source/filesystem/opendal_source/mod.rs
- src/connector/with_options_source.yaml
As title. It seems to be caused by PR merging. 
</details>
> fix(connector): fix gcs source connector

- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/progress.rs
After https://github.com/risingwavelabs/risingwave/pull/13665, sink immediately is created after first barrier passes. We don't need to track backfill progress as such, and can remove it to avoid confusion, and hanging stream job progress, when sink is dropped.
Closes: https://github.com/risingwavelabs/risingwave/issues/14341, https://github.com/risingwavelabs/risingwave/issues/14387 …
> feat(meta): remove stream job progress for sink

- e2e_test/batch/transaction/same_session.slt
- proto/batch_plan.proto
- src/batch/src/executor/delete.rs
- src/batch/src/executor/insert.rs
- src/batch/src/executor/update.rs
- src/compute/tests/integration_tests.rs
- src/frontend/src/optimizer/plan_node/batch_delete.rs
- src/frontend/src/optimizer/plan_node/batch_insert.rs
- src/frontend/src/optimizer/plan_node/batch_update.rs
- src/frontend/src/scheduler/distributed/stage.rs
- src/frontend/src/scheduler/local.rs
- src/frontend/src/scheduler/plan_fragmenter.rs
- src/source/src/dml_manager.rs
- src/source/src/table.rs
- src/stream/src/executor/dml.rs
- src/stream/src/executor/stream_reader.rs
… and let group batch perserve transaction order
- Resolve https://github.com/risingwavelabs/risingwave/issues/14370
- ensure the same session transaction sends data to the same worker node and let the group batch preserve the transaction order. PS: only hold if there's no scaling on the table.
</details>
> feat(dml): sent dml data from the same session to a fixed worker node/channel

- e2e_test/streaming/delta_join/delta_join_upstream_with_index_different_types.slt
- proto/stream_plan.proto
- src/frontend/src/optimizer/plan_node/stream_delta_join.rs
- src/stream/src/from_proto/lookup.rs
In #9843, when enable delta join, the join will cause panic because of the data type mismatch. For delta join, the input data may come from the upstream or from the storage table. The data from the upstream has already been filtered. But for data from storage table, it is not filtered. 
Root cause: 
When building the `StorageTable`, the input `column_ids` directly using the full table column ids. 
Example:
* create table A (c1, c2, c3, _row_id), table B(c1,c2,c3, _row_id)
* join key c1, select c3
* Error result: row A (c1, c3, _row_id), row B (c1,c2,c3, _row_id)
* Reason: index map A is correct, but index map B should …
> fix: column index mapping bug of stream_delta_join

- src/connector/src/parser/plain_parser.rs
- src/frontend/src/scheduler/snapshot.rs
- src/meta/src/hummock/manager/mod.rs
https://github.com/risingwavelabs/risingwave/issues/13953
</details>
> chore: remove some periodical logs

- e2e_test/batch/functions/similar_to_escape.slt.part
- src/expr/impl/src/scalar/similar_to_escape.rs
No functional changes.
Correct previous erroneous tests comment and update some tests to more obviously demonstrate the functionality of disabling escape (by `ESCAPE ''`).
ref: https://www.postgresql.org/docs/16/functions-matching.html#FUNCTIONS-SIMILARTO-REGEXP
> As with `LIKE`, a backslash disables the special meaning of any of these metacharacters. A different escape character can be specified with `ESCAPE`, or the escape capability can be disabled by writing `ESCAPE ''`. …
> test: update `similar-to-escape` to test explicitly disable escape

- Cargo.lock
- Cargo.toml
So there'll be detailed documentation... 
- https://docs.rs/thiserror-ext
- https://github.com/risingwavelabs/risingwave/pull/14435#discussion_r1445713415
</details>
> chore: bump `thiserror-ext` to 0.0.11

- src/common/src/error.rs
- src/frontend/planner_test/tests/testdata/output/expr.yaml
- src/frontend/planner_test/tests/testdata/output/nexmark.yaml
- src/frontend/planner_test/tests/testdata/output/nexmark_source.yaml
- src/frontend/planner_test/tests/testdata/output/nexmark_temporal_filter.yaml
- src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml
- src/frontend/src/binder/expr/function.rs
- src/frontend/src/expr/type_inference/func.rs
resolve #9273
This PR replaces `unsupported function` error by `function does not exist`:
```diff
dev=> select foo();
1: Failed to bind expression: foo()
+  2: function foo() does not exist
-  2: Feature is not yet implemented: unsupported function: "foo"
-Tracking issue: https://github.com/risingwavelabs/risingwave/issues/112
```
> chore: improve error message for function argument mismatch

- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/recovery.rs
- src/meta/src/barrier/rpc.rs
Previously in global barrier manager, the finish of barrier_complete rpc is notified by a mpsc channel, which may receive stale rpc result after recovery. 
In this PR, we change to use a oneshot channel to notify the barrier completion of each epoch. The oneshot receiver will be pushed to a FuturesUnordered and gets polled in the global barrier manager worker loop. In this way, during failure recovery, we can avoid receiving stale completion result.
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary …
> feat: poll barrier complete rpc in barrier manager worker loop

- e2e_test/udf/sql_udf.slt
As titled, since implicit type cast for udf has been supported in #14338.
P.S. Create function will be much slower (~4x) after supporting implicit type cast, but it's alright.
The previous docs for sql udf in #14139 needs to be updated, specifically we don't need to explicit cast multiple types when calling sql udf.
</details>
> chore(sql-udf): update test cases for implicit type cast support

- src/meta/model_v2/migration/src/m20231008_020431_hummock.rs
- src/meta/src/backup_restore/backup_manager.rs
- src/meta/src/hummock/compactor_manager.rs
- src/meta/src/hummock/error.rs
- src/meta/src/hummock/manager/compaction_group_manager.rs
- src/meta/src/hummock/manager/context.rs
- src/meta/src/hummock/manager/gc.rs
- src/meta/src/hummock/manager/mod.rs
- src/meta/src/hummock/manager/sequence.rs
- src/meta/src/hummock/manager/tests.rs
- src/meta/src/hummock/manager/utils.rs
- src/meta/src/hummock/manager/versioning.rs
- src/meta/src/hummock/model/ext/hummock.rs
- src/meta/src/manager/env.rs
- src/meta/src/model/mod.rs
This PR makes HummockManager support both metadata model V1 and model V2. 
- Add/Refactor macro `create_trx_wrapper` and `commit_multi_var`. 
- It can commit both V1 and V2. Whether to use V1 o r V2 depends on whether `sql_meta_store` is provided.
- `check_context` is moved out of `commit_multi_var`, explicitly called in pin/unpin methods.
- Add wrappers like `BTreeMapTransactionWrapper`, which dispatches requests to `BTreeMapTransaction<V1>` or `BTreeMapTransaction<V2>`. …
> feat(sql-backend): integrate HummockManager with model V2

- e2e_test/batch/subquery/array_construct.slt.part
- src/frontend/planner_test/src/lib.rs
- src/frontend/src/optimizer/mod.rs
- src/frontend/src/planner/insert.rs
- src/frontend/src/planner/relation.rs
- src/frontend/src/planner/select.rs
- src/frontend/src/planner/set_expr.rs
Fix #14153. In most cases, the output order of a subquery has no impact of the outer query except for `array(...)` construction.
* Rename `into_subplan` to `into_unordered_subplan` for clarity.
* Handle `order` properly in the latter case by leveraging `order by` of `PlanAggCall`
</details>
> fix(planner): preserve order in array-construction subquery

- src/stream/src/task/barrier_manager.rs
- src/stream/src/task/barrier_manager/managed_state.rs
- src/stream/src/task/barrier_manager/tests.rs
- src/stream/src/task/stream_manager.rs
Split from https://github.com/risingwavelabs/risingwave/pull/14377 as suggested in https://github.com/risingwavelabs/risingwave/pull/14377#issuecomment-1878369468
Refactor includes the following changes:
- use `prev_epoch` as the key of barrier state map. Previously we use `curr_epoch`.
- observe barrier inflight latency when barrier has been collected from all actors. Previously we observe the latency in the collect_barrier rpc handler when we get notified on collecting barriers from all actors.
- maintain failure actor in local barrier worker instead of the managed state. …
> refactor: local barrier manager use prev epoch to track barrier state

- src/common/src/array/data_chunk.rs
- src/common/src/array/list_array.rs
- src/common/src/array/struct_array.rs
- src/common/src/types/mod.rs
- src/expr/core/src/expr/build.rs
- src/frontend/src/binder/bind_param.rs
- src/frontend/src/expr/function_call.rs
As title. These two methods do something similar. We merge them to remove duplicate code.
> chore(type): merge `ScalarImpl::from_text` and `from_literal`

- src/meta/service/src/ddl_service.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/rpc/ddl_controller_v2.rs
> fix: fix fill table id for cdc backfill source

- src/batch/src/executor/join/distributed_lookup_join.rs
- src/batch/src/executor/row_seq_scan.rs
- src/ctl/src/cmd_impl/table/scan.rs
- src/storage/src/table/batch_table/storage_table.rs
- src/storage/src/table/mod.rs
- src/stream/src/common/table/test_storage_table.rs
- src/stream/src/executor/watermark_filter.rs
- src/stream/src/from_proto/batch_query.rs
- src/stream/src/from_proto/lookup.rs
- src/stream/src/from_proto/stream_scan.rs
- src/stream/src/from_proto/temporal_join.rs
In our current call path on `StorageTable::new_partial`, we always have the following duplicate logic that generates some storage table information from `StorageTableDesc` before calling `new_partial`, and then pass all these information to `new_partial`. 
```
let table_id = TableId {
table_id: table_desc.table_id,
};
let column_descs = table_desc
.columns
.iter()
.map(ColumnDesc::from)
.collect_vec();
let order_types: Vec<OrderType> = table_desc
.pk
.iter()
.map(|order| OrderType::from_protobuf(order.get_order_type().unwrap()))
.collect();
let pk_indices = table_desc
.pk
.iter()
.map(|k| k.column_index as usize) …
```
> refactor(storage): create storage table from desc

- src/common/src/lib.rs
- src/common/src/session_config/mod.rs
- src/utils/pgwire/src/pg_protocol.rs
In #11265
1. we need to refactor the `current_cluster_version` function which used in `function / streaming job / ddl controller` which should get from the `ConfigMap`. 
2. When setting the pgwire for `ParameterStatus`, we hard code the `server version / client encoding / StandardConformingString / ApplicationName`. 
This PR try to refactor the above two parts. 
1. Firstly move some default value of the `ConfigMap` into common and make they as pub const. Use this const when initialize the `ConfigMap`. 
2. Secondly, in theory,  we should read `ParameterStatus` from the `session_config`. But we use const value to init …
> refactor(frontend): Move some pg wire value into common and make them const

- src/common/src/row/project.rs
- src/storage/src/table/mod.rs
- src/stream/src/executor/hash_join.rs
- src/stream/src/executor/managed_state/join/join_entry_state.rs
- src/stream/src/executor/managed_state/join/mod.rs
- print join key and pk for cache error.
close #14456 
</details>
> refactor(streaming): improve hash join error message

- proto/ddl_service.proto
- proto/stream_plan.proto
- src/meta/src/controller/fragment.rs
- src/meta/src/manager/catalog/fragment.rs
- src/meta/src/manager/metadata.rs
- src/meta/src/manager/streaming_job.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/stream_graph/fragment.rs
Mainly because when I trying to add source backfill, I found it's not easy to understand how to handle `TableJobType` correctly.
</details>
> refactor(meta): refactor how upstream fragment is handled when creating stream job

- src/expr/core/src/window_function/call.rs
- src/expr/core/src/window_function/state/buffer.rs
- src/frontend/src/binder/expr/function.rs
- src/stream/src/executor/over_window/general.rs
- src/stream/src/executor/over_window/over_partition.rs
- Introduce a new type `RowsFrameBounds` to represent `ROWS` frame bounds;
- Add short circuit logic in `find_affected_ranges` to avoid wasted computation.
This is a preliminary work for `RANGE` frame support.
</details>
> refactor(over window): add some short-circuit logic in `find_affected_ranges` and some other refactoring

- src/connector/src/source/nats/enumerator/mod.rs
In #12942, once a time, there is some connection error in source between rw and nats which result in the compute node crash. The root cause: when source executor call the `list_splits` function, nats didn't provide the API for it, so currently we directly return `0`. But if the connection has error, executor will crash in the following logic. 
So I add a `client` in `NatsSplitEnumerator`, and when call `list_splits`, will check the [connection state](https://docs.rs/async-nats/latest/async_nats/client/struct.Client.html#method.connection_state) first. If return …
> fix(connector): add additional check in nats list_splits

- dashboard/components/CatalogModal.tsx
- dashboard/components/FragmentDependencyGraph.tsx
- dashboard/components/FragmentGraph.tsx
- dashboard/components/RelationDependencyGraph.tsx
- dashboard/components/Relations.tsx
- dashboard/lib/layout.ts
- dashboard/pages/api/streaming.ts
- dashboard/pages/dependency_graph.tsx
- dashboard/pages/fragment_graph.tsx
Improve the relation dependency graph. Act as a follow-up of #14446 for inter-job investigations.
- Show relation types in dep graph.
- Click the relation point to see its catalog.
- Navigate to fragment graph from catalog modal.
Also include some necessary refactors:
- Add type annotation for SVG of fragment dep graph and relation dep graph.
- Make layout algorithms generic on items, instead of mocking `RelationPoint` into `FragmentBox`. Correctly rename copy-pasted codes. …
> feat(dashboard): improvements on the relation dep graph

- src/stream/src/executor/top_n/topn_cache_state.rs
add estimate size for topn cache extract_if
close #14530
</details>
> fix: estimate size for topn cache extract_if

- src/frontend/src/optimizer/plan_node/generic/source.rs
- src/frontend/src/optimizer/plan_node/stream_fs_fetch.rs
- src/frontend/src/optimizer/plan_node/stream_source.rs
* **bug**: in prev impl, the distribution key is missing and we apply all state changes to vnode0 in the runtime. This behavior leads to only one fs fetch exec will work (not introducing correctness problem but low efficiency). 
* The root cause is that the fs fetch exec will do range scan on assigned vnodes but all data is written to one vnode. 
* **fix**: set the distribution key in the frontend before writing to catalog. Do NOTHING to existing jobs, preventing data consistency problem.  …
> fix: specify distribution key for fs source

- src/expr/macro/src/lib.rs
> chore: fix expr macro doc

- src/storage/src/hummock/iterator/forward_user.rs
Prior to this PR, each returned key will be counted towards `skip_multi_version_key_count` in the following `next()` call even though there are no actual multi-versions for the key.  Also, there will be one unnecessary `self.last_key.user_key` and `full_key.user_key` comparison per returned key. 
</details>
> refactor: fix incorrect skip multi-version key metric and save unneccessary key comparison

- src/storage/src/hummock/store/version.rs
> fix(storage): should use epoch with the maximum offset when get

- Cargo.lock
- src/utils/delta_btree_map/Cargo.toml
- src/utils/delta_btree_map/src/lib.rs
Use `educe` to derive `Copy` for `DeltaBTreeMap` so that it can be copied despite the copiability of `T`.
</details>
> feat(common): derive `Copy` for `DeltaBTreeMap`

- src/common/src/config.rs
- src/common/src/system_param/common.rs
- src/common/src/system_param/mod.rs
- src/common/src/system_param/reader.rs
- src/compute/src/memory/manager.rs
- src/compute/src/server.rs
- src/frontend/src/handler/alter_system.rs
- src/frontend/src/handler/create_function.rs
- src/meta/node/src/server.rs
- src/meta/src/backup_restore/backup_manager.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/controller/system_param.rs
- src/meta/src/hummock/manager/mod.rs
- src/meta/src/manager/system_param/mod.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/stream_manager.rs
- src/storage/compactor/src/server.rs
- src/storage/src/hummock/backup_reader.rs
- src/storage/src/opts.rs
- src/stream/src/executor/source/fs_source_executor.rs
- src/stream/src/executor/source/source_executor.rs
- src/tests/compaction_test/src/delete_range_runner.rs
When I was working on #14528, I find a lot of places have to be updated when trying to introduce a new system parameter. This PR is an attempt to improve that.
- Generate `SystemConfig` and initial system params.
- Generate `SystemParamsRead` trait, so developers will be reminded to add a new method on `SystemParamsReader` after introducing a new system param.
- Generate unwrapped default value functions, as suggested by @xxchan in https://github.com/risingwavelabs/risingwave/pull/14528#discussion_r1449908549. …
> refactor(common): generate more code on system params with macro

- src/storage/hummock_sdk/src/compact.rs
Prior to this PR, we mistakenly use the `max sst meta size in the level / current sstable size` to calculate the max meta ratio, which can be very large when there is a small file. This PR fixes the issue by using `current sstable meta size / current sstable size` to calculate the ratio instead.
Example task that can cause the issue:
```
Level 5:
SST1: meta_size = 100KB, SST size = 100MB
SST2: meta_size = 100B, SST size = 1KB
max_meta_ratio  = 100KB / 1KB = 100
``` …
> fix: fix incorrect compact task memory estimation

- src/frontend/planner_test/tests/testdata/input/agg.yaml
- src/frontend/planner_test/tests/testdata/output/agg.yaml
- src/frontend/src/optimizer/plan_node/generic/agg.rs
Fixes https://github.com/risingwavelabs/risingwave/issues/14620.
</details>
> fix: incorrect batch sort agg on ordered input when group key is not prefix of input order columns

- Cargo.lock
- src/stream/src/executor/dispatch.rs
- src/stream/src/executor/wrapper/trace.rs
Create a new span for every message yielded from executors, to make the tracing visualization more detailed.
As we made tracing disabled by default after #14528, I guess we don't have to worry about the performance impact from the number of spans so this should be acceptable.
Before:
After:
</details>
> feat(streaming): create a new span for every yielded message

- Cargo.toml
- ci/workflows/main-cron.yml
30 min is barely enough for the `cargo build` command, but sometimes it timeouts due to the fluctuation and other phases.
https://buildkite.com/risingwavelabs/main-cron/builds/1559#018d1d50-28d4-4f64-8175-e842dd03e634
</details>
> fix(ci): disable LTO for `ci-release` to resolve build timeout in main-cron

- ci/rust-toolchain
- lints/Cargo.lock
- lints/Cargo.toml
- lints/README.md
- lints/rust-toolchain
Resolve #14304. The toolchain version for `lints` does not have to match that for RisingWave components. Added comments for reference.
</details>
> chore(lints): bump toolchain to make it work again

- src/storage/src/hummock/compactor/mod.rs
> fix(storage): fix check compaction task opportunity

- ci/scripts/e2e-clickhouse-sink-test.sh
> fix(sink): fix ci clickhouse sink

- Cargo.lock
- Cargo.toml
- src/common/Cargo.toml
- src/common/src/estimate_size/collections/lru.rs
- src/stream/Cargo.toml
- src/stream/src/cache/managed_lru.rs
- src/tests/simulation/Cargo.toml
- src/workspace-hack/Cargo.toml
Only cherry-pick some commits from the upstream.
</details>
> chore(deps): bump lru to 95f347b

- src/frontend/src/binder/expr/function.rs
- src/frontend/src/binder/mod.rs
- src/frontend/src/handler/create_sql_function.rs
As titled, move `extract_udf_expression` & `create_udf_context` inside `UdfContext`.
</details>
> refactor(udf-context): assemble sql udf related functions inside `UdfContext`

- Cargo.lock
- src/frontend/Cargo.toml
- src/frontend/src/session.rs
> feat: add heap profiling for frontend

- Makefile.toml
- ci/scripts/backfill-test.sh
- ci/scripts/deterministic-recovery-test.sh
- ci/scripts/run-backfill-tests.sh
- ci/workflows/main-cron.yml
- ci/workflows/pull-request.yml
- risedev.yml
- src/common/src/config.rs
- src/config/ci.toml
- src/config/example.toml
- src/object_store/src/object/s3.rs
This should fix the backfill tests. Previously these errors are not handled in the object store. Now we simply add a retry for them.
</details>
> feat(object_store): add retry for `Minio` `SlowDown` and `TooManyRequests` errors

- src/meta/src/stream/stream_graph/fragment.rs
As title. Previously the sink/cdc source id will be filled into state table ids of table fragment incorrectly. 
</details>
> fix: only fill state table id of materialize node in table fragments

- src/frontend/planner_test/tests/testdata/input/subquery.yaml
- src/frontend/planner_test/tests/testdata/output/subquery.yaml
- src/frontend/src/binder/relation/table_function.rs
> fix(optimizer): ban using subquery in non-table-in-out function.

- src/frontend/planner_test/tests/testdata/input/agg.yaml
- src/frontend/planner_test/tests/testdata/output/agg.yaml
- src/frontend/src/optimizer/plan_node/generic/agg.rs
Cherry-picking #14621 to `release-1.6`.
> fix(cherry-pick #14621): incorrect batch sort agg on ordered input when group key is not prefix of input order columns

- src/storage/hummock_sdk/src/key.rs
- src/storage/src/hummock/compactor/compactor_runner.rs
- src/storage/src/hummock/compactor/shared_buffer_compact.rs
- src/storage/src/hummock/iterator/forward_user.rs
This PR adds assertion in the following places to ensure monotonically decreasing user key epoch:
- user key iterator
- compaction iterator
- imm merge iterator
</details>
> chore: add assertion to ensure monotonically decreasing user key epoch

- ci/plugins/upload-failure-logs-zipped/hooks/post-command
- ci/scripts/common.sh
- ci/scripts/deterministic-recovery-test.sh
- ci/workflows/main-cron.yml
- ci/workflows/pull-request.yml
- src/common/src/session_config/mod.rs
- src/stream/src/executor/backfill/arrangement_backfill.rs
- src/stream/src/executor/backfill/no_shuffle_backfill.rs
- src/tests/simulation/src/main.rs
Fixes 2 bugs:
1. Arrangement backfill would not complete previously after recovery as it will be stuck due to incorrect logic.
2. arrangement backfill should not need to commit its internal state table on barrier anymore, after barrier is complete.
Adds background ddl + arrangement backfill as a test step in `main-cron.yml`.
Reduces the logs being uploaded by:
1. Filtering stack traces.
2. Only uploading a zip of the logs. …
> fix(stream): arrangement backfill background ddl

- docker/Dockerfile
- docker/Dockerfile.hdfs
#14761 introduced a clang dependency at build time. It was missing in the main dockerfile.
> fix: add clang to dockerfile

- src/storage/src/hummock/sstable/block.rs
The original copy check should be flipped.
</details>
> fix: fix unneccessary copy in block decode

- src/connector/src/parser/avro/util.rs
- src/connector/src/parser/debezium/avro_parser.rs
> fix(avro): fix parsing of avro ref type

- proto/stream_service.proto
- src/compute/src/rpc/service/stream_service.rs
- src/meta/src/controller/cluster.rs
- src/meta/src/dashboard/mod.rs
- src/meta/src/manager/cluster.rs
- src/meta/src/stream/stream_manager.rs
- src/rpc_client/src/stream_client.rs
In #13830, we want to embedded a back pressure rate metrics for dashbaord UI. In this PR, I add a API to get the back pressure from all compute node to meta node. 
But I still need to implement the calculation steps. The way to calculate the rate:
1. Get the (previous) back pressure metrics 1 in time 1.
2. Get the (current) back pressure metrics 2 in time 2. Do `(metrics 2 - metrics 1)/(time2 - time1)`. 
3. Then make the current back pressure as the previous metrics and repeat step 1 and step 2 every 15 seconds.
In meta node, I didn't find a good way to do this crobjob, also not find a good place to storage the previous …
> feat(meta): add get back pressure RPC for UI dashboard

- src/connector/src/parser/unified/avro.rs
- src/connector/src/parser/unified/json.rs
Correctly handle the situation when the length of bytes is greater than 4.
defore:
`1.1234567891` -> `18848476.8633979091`
after:
`1.1234567891` -> `1.1234567891`
</details>
> fix: extract decimal correctly when bytes len >= 5

- proto/batch_plan.proto
- src/batch/src/executor/generic_exchange.rs
- src/batch/src/executor/join/local_lookup_join.rs
- src/batch/src/task/task_execution.rs
- src/frontend/planner_test/tests/testdata/output/basic_query.yaml
- src/frontend/planner_test/tests/testdata/output/except.yaml
- src/frontend/planner_test/tests/testdata/output/intersect.yaml
- src/frontend/planner_test/tests/testdata/output/limit.yaml
- src/frontend/planner_test/tests/testdata/output/order_by.yaml
- src/frontend/planner_test/tests/testdata/output/union.yaml
- src/frontend/src/optimizer/plan_node/batch_exchange.rs
- src/frontend/src/optimizer/plan_node/batch_limit.rs
- src/frontend/src/scheduler/distributed/stage.rs
- Try to resolve https://github.com/risingwavelabs/risingwave/issues/14634
- For the exchange of 2 phase (small) limit, we apply a sequential exchange to avoid OOM.
</details>
> feat: support sequential exchange

- Cargo.lock
- Cargo.toml
- ci/Dockerfile
- docker/Dockerfile
- docker/Dockerfile.hdfs
This PR reverts #14761 and uses the upstream rquickjs-sys (unpublished) to fix build on arm64 linux.
> fix: patch rquickjs-sys and remove clang dependency

- docker/docker-compose-distributed.yml
- docker/docker-compose-with-azblob.yml
- docker/docker-compose-with-gcs.yml
- docker/docker-compose-with-hdfs.yml
- docker/docker-compose-with-local-fs.yml
- docker/docker-compose-with-obs.yml
- docker/docker-compose-with-oss.yml
- docker/docker-compose-with-s3.yml
- docker/docker-compose.yml
Configure the URL of the Prometheus service for dashboard service in meta node, to enable functionalities such as diagnostic report that rely on Prometheus service.
</details>
> chore: configure Prometheus service URL in docker compose files

- src/common/src/types/datetime.rs
- src/connector/src/parser/avro/util.rs
- src/connector/src/parser/unified/avro.rs
before:
insert timestamp before Epoch, will get error:
e.g. `1969-01-01 00:00:00`:
```
WARN   rw-streaming actor{otel.name="Actor 18" actor_id=18 prev_epoch=5850098781323264 curr_epoch=5850098793119744}:executor{otel.name="Source 1200002715 (actor 18)" actor_id=18}:source_parse_chunk{actor_id=18 source_id=1002}: risingwave_connector::parser: failed to parse non-pk column, padding with `NULL` error=Expected type `Some(Timestamptz)` but got `TimestampMillis(-31536000000)` for `` split_id="0" offset="2" column="c_timestamp" suppressed_count=0
```
Note:
While for the ancient `timestamp` data, it is incorrect:
`0001-01-01 …
> fix(avro): correct parse `timestamp` data before Epoch

- src/storage/src/hummock/compactor/mod.rs
Previously the check is only enabled when ReportTask RPC fails.
</details>
> fix: enable compaction output check regardless of the ReportTask rpc status

- src/frontend/planner_test/tests/testdata/output/temporal_join.yaml
- src/frontend/src/optimizer/plan_node/logical_join.rs
- Resolve https://github.com/risingwavelabs/risingwave/issues/14843
- Enforcing a shuffle no matter what kind of distribution the temporal join LHS is.
</details>
> fix(optimizer): fix temporal join shuffle

- src/expr/impl/src/scalar/array_positions.rs
- src/expr/impl/src/scalar/array_remove.rs
- src/expr/impl/src/scalar/array_replace.rs
- src/expr/impl/src/scalar/format_type.rs
- src/expr/impl/src/scalar/string_to_array.rs
- src/expr/macro/src/gen.rs
- src/expr/macro/src/lib.rs
- src/expr/macro/src/parse.rs
Currently `#[function]` only accepts all arguments as `Option` or none of them as `Option`. This PR breaks this limitation, allowing partial `Option` arguments.
For example:
```rust
#[function("array_remove(anyarray, any) -> anyarray")]
fn array_remove(array: ListRef<'_>, elem: Option<ScalarRefImpl<'_>>) -> ListValue {...}
```
which will be called when `elem` is null, but not when `array` is null.
> feat(expr): allow partial option arguments in functions

- risedev.yml
- src/common/src/session_config/mod.rs
- src/stream/src/executor/backfill/arrangement_backfill.rs
- src/stream/src/executor/backfill/utils.rs
- src/tests/simulation/src/cluster.rs
- src/tests/simulation/tests/integration_tests/backfill_tests.rs
- src/tests/simulation/tests/integration_tests/main.rs
- src/tests/simulation/tests/integration_tests/recovery/background_ddl.rs
- src/tests/simulation/tests/integration_tests/utils.rs
Supports recoverable row count for arrangement backfill. We will persist and recover it.
It's to ensure that arrangement backfill remains compatible with background ddl. We must persist the row count so that after recovery, we can recover the estimated progress for the materialized view in `show jobs`.
The meta-side logic is the same as with `NoShuffleBackfill`, after recovery, meta will receive updates from `NoShuffleBackfill` executors to reconstruct the progress bar.
Progress is calculated with: `total_snapshot_row_count / total_upstream_row_count` in meta. …
> feat(stream): support row count for arrangement backfill

- src/compute/src/rpc/service/config_service.rs
- src/compute/src/rpc/service/exchange_service.rs
- src/compute/src/rpc/service/monitor_service.rs
- src/compute/src/rpc/service/stream_service.rs
- src/compute/src/server.rs
- src/meta/src/stream/stream_manager.rs
- src/stream/src/task/barrier_manager.rs
- src/stream/src/task/barrier_manager/progress.rs
- src/stream/src/task/stream_manager.rs
- src/utils/futures_util/src/misc.rs
Previously we have a `LocalStreamManagerCore` that keeps track of actor states. The `core` is wrapped by `Arc<Mutex<...>>` and shared by grpc handlers. To handle each grpc request, we will have to acquire the lock on `core` to fetch or modify the states.
In this PR, the `LocalStreamManagerCore` is renamed to `StreamActorManagerState` and owned by `LocalBarrierWorker` loop so that we don't need to acquire lock to access it. All streaming control rpc request will be sent to `LocalBarrierWorker` as an event to handle the request. `LocalStreamManager` is renamed to `StreamActorManager` to handle actor creation, and the …
> feat: handle streaming control rpc in worker loop

- src/stream/src/common/table/state_table.rs
- src/stream/src/executor/backfill/arrangement_backfill.rs
- src/stream/src/executor/backfill/utils.rs
- src/stream/src/executor/dedup/append_only_dedup.rs
- src/stream/src/executor/dynamic_filter.rs
- src/stream/src/executor/now.rs
- src/stream/src/executor/simple_agg.rs
- src/stream/src/executor/sort.rs
- src/stream/src/executor/watermark_filter.rs
To me, the `StateTable::commit_no_data_expected` introduced unnecessary mental burden. Developers have to somehow track whether the state is dirty or not in executors, while this information is clearly known by state table itself.
This PR removes the unnecessary method, and uniformly uses `commit` instead. Inside `commit`, the state table will branch according to `StateTable::is_dirty` so that the calling cost is not changed.
I'm doing benchmark to test the performance impact.
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note …
> refactor(state table): remove `commit_no_data_expected`

- e2e_test/udf/sql_udf.slt
- src/frontend/src/handler/create_sql_function.rs
As titled, now the below definition will be rejected at creation time.
```sql
create function type_mismatch(INT) returns varchar language sql as 'select $1 + 114514 + $1';
```
</details>
> feat(sql-udf): add type mismatch check at definition time

- Cargo.lock
- Cargo.toml
- ci/scripts/e2e-iceberg-sink-v2-test.sh
- e2e_test/iceberg/start_spark_connect_server.sh
- e2e_test/iceberg/test_case/iceberg_sink_upsert.slt
- e2e_test/iceberg/test_case/partition_append_only.toml
- e2e_test/iceberg/test_case/partition_upsert.toml
- e2e_test/iceberg/test_case/range_partition_append_only.toml
- e2e_test/iceberg/test_case/range_partition_upsert.toml
- proto/stream_plan.proto
- src/common/src/array/arrow/arrow_iceberg.rs
- src/common/src/array/arrow/arrow_impl.rs
- src/common/src/array/arrow/mod.rs
- src/common/src/array/mod.rs
- src/connector/Cargo.toml
- src/connector/src/sink/catalog/desc.rs
- src/connector/src/sink/iceberg/mock_catalog.rs
- src/connector/src/sink/iceberg/mod.rs
- src/connector/src/sink/mod.rs
- src/frontend/Cargo.toml
- src/frontend/planner_test/src/lib.rs
- src/frontend/planner_test/tests/testdata/input/sink.yaml
- src/frontend/planner_test/tests/testdata/output/sink.yaml
- src/frontend/src/handler/create_sink.rs
- src/frontend/src/handler/explain.rs
- src/frontend/src/optimizer/mod.rs
- src/frontend/src/optimizer/plan_node/mod.rs
- src/frontend/src/optimizer/plan_node/stream_sink.rs
- src/stream/src/executor/sink.rs
- src/stream/src/from_proto/sink.rs
This is the final part of #13898:
1. support get partition info at frontend 
2. add the project node to compute the partition value and exchange node to shuffle by it 
</details>
> feat: support precompute partition for iceberg

- src/common/src/config.rs
- src/meta/node/src/lib.rs
- src/meta/node/src/server.rs
- src/meta/service/src/system_params_service.rs
- src/meta/service/src/telemetry_service.rs
- src/meta/src/backup_restore/utils.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/recovery.rs
- src/meta/src/hummock/compactor_manager.rs
- src/meta/src/hummock/manager/compaction_group_manager.rs
- src/meta/src/hummock/manager/mod.rs
- src/meta/src/hummock/manager/tests.rs
- src/meta/src/hummock/manager/utils.rs
- src/meta/src/lib.rs
- src/meta/src/manager/catalog/database.rs
- src/meta/src/manager/catalog/fragment.rs
- src/meta/src/manager/catalog/mod.rs
- src/meta/src/manager/catalog/user.rs
- src/meta/src/manager/cluster.rs
- src/meta/src/manager/env.rs
- src/meta/src/manager/notification.rs
- src/meta/src/manager/notification_version.rs
- src/meta/src/model/catalog.rs
As title, to enable sql-backend user can configure two options as follows:
1. `--sql-endpoint  [endpoint address]`
2. `--backend sql`
For example, the endpoint address could be `postgres://postgres:@localhost:5432/postgres` for PG and `sqlite://posts.sqlite?mode=rwc` for SQLite.
Besides, I will support adapt it in `risedev` in another PR.
</details>
> feat(sql-backend): disable etcd meta store initialization when sql backend is enabled

- ci/scripts/cron-e2e-test.sh
- ci/scripts/pr.env.sh
- ci/scripts/run-e2e-test.sh
- risedev.yml
- src/config/ci-delete-range-test.toml
- src/tests/compaction_test/Makefile.toml
- src/tests/compaction_test/src/bin/delete_range.rs
Since we do not support write delete ranges in `ingest_batch` interface, this test will always fail. So let's disable it
</details>
> fix(tests): remove delete range runner test

- ci/scripts/regress-test.sh
- src/tests/regress/data/expected/contrib-pgcrypto-rijndael.out
- src/tests/regress/data/schedule
- src/tests/regress/data/sql/contrib-pgcrypto-rijndael.sql
Supplement to #14717
Passed tests for AES/Rijndael:
https://buildkite.com/risingwavelabs/pull-request/builds/41122
Also tried blowfish, only to find out openssl 3.0 considers it **`legacy`** and not enabled by default:
https://buildkite.com/risingwavelabs/pull-request/builds/41124
https://www.openssl.org/docs/man3.0/man7/crypto.html#OPENSSL-PROVIDERS
Btw postgresql regress tests also include `3des` / `des` / `cast5` which are undocumented. It is likely `blowfish` will join them soon. …
> test(regress): pgcrypto `encrypt`/`decrypt` for AES (aka Rijndael)

- Cargo.lock
- src/expr/core/Cargo.toml
- src/expr/core/src/codegen.rs
- src/expr/core/src/lib.rs
- src/expr/core/src/sig/mod.rs
- src/expr/impl/Cargo.toml
- src/expr/impl/src/lib.rs
- src/expr/macro/src/gen.rs
- src/frontend/Cargo.toml
- src/frontend/src/catalog/system_catalog/mod.rs
- src/frontend/src/lib.rs
This PR replaces ctor by [linkme](https://docs.rs/linkme/latest/linkme/), which simplifies the code and initialization process.
> refactor: replace ctor by linkme

- Cargo.lock
- Cargo.toml
This PR removes the patch of rquickjs, as the upstream has released a new version.
related #14817
> chore(deps): bump rquickjs

- src/common/src/error.rs
- src/connector/src/parser/debezium/debezium_parser.rs
- src/connector/src/parser/debezium/mongo_json_parser.rs
- src/connector/src/parser/protobuf/parser.rs
- src/connector/src/parser/unified/avro.rs
- src/connector/src/parser/unified/debezium.rs
- src/connector/src/parser/unified/mod.rs
- src/connector/src/parser/unified/protobuf.rs
- Avoid `anyhow` in `AccessError`, as it's used in parsing and capturing backtraces per record is not acceptable in performance. This PR uses a plain `String` instead and provide similar experience to `anyhow` for constructing leaf errors by `thiserror_ext::Macro`.
- Use `AccessError` as much as possible for parsing-related code logic, instead of using `RwError`. …
> refactor(connector): avoid anyhow in `AccessError` and avoid using `RwError` if possible

- src/meta/src/barrier/recovery.rs
- src/meta/src/controller/cluster.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/stream/scale.rs
> fix: fix todo & corner case for scaling in sql backend

- src/expr/impl/src/scalar/case.rs
As titled, reference: https://github.com/risingwavelabs/risingwave/pull/14586/files#r1467219238.
</details>
> refactor(expr): refactor constant lookup optimization for case-when expression

- src/frontend/src/catalog/system_catalog/rw_catalog/rw_columns.rs
Not sure whether source columns should be included in `rw_columns`. But as the columns of sinks are encompassed, I suppose source columns should also be included. 
Example:
```
> create source src (v int) with (
connector = 'datagen',
fields.v.kind = 'sequence',
fields.v.start = '1',
fields.v.end  = '10',
datagen.rows.per.second='15',
datagen.split.num = '1'
) FORMAT PLAIN ENCODE JSON;
> SELECT column_name, data_type, table_name FROM information_schema.columns WHERE 
table_schema = 'public';
column_name | data_type | table_name 
-------------+-----------+------------
v           | integer   | src
``` …
> feat(catalog): add source columns to rw_columns

- src/cmd_all/src/standalone.rs
- src/compute/src/lib.rs
- src/connector/src/source/filesystem/opendal_source/opendal_reader.rs
- src/connector/src/source/filesystem/s3/source/reader.rs
- src/frontend/src/lib.rs
- src/meta/node/src/lib.rs
- src/storage/compactor/src/lib.rs
> refactor: rename `prometheus_host` to `prometheus_listener_addr`

- Cargo.lock
- src/stream/Cargo.toml
- src/stream/src/executor/source/executor_core.rs
- src/stream/src/executor/source/fetch_executor.rs
- src/stream/src/executor/source/fs_source_executor.rs
- src/stream/src/executor/source/source_executor.rs
- src/stream/src/executor/source/state_table_handler.rs
> refactor(stream): SourceExecutor minor refactor

- dashboard/next.config.js
Seems format of `dashboard/next.config.js` had some problems and `npm run lint` reported an error, blocking any PR that changed proto files.
</details>
> fix(dashboard): fix file format to pass linting

- ci/workflows/main-cron.yml
See background at https://github.com/risingwavelabs/risingwave/issues/14707#issuecomment-1922750222
> Did some experiments, but the failure rate seems to be random to me 😅
> 
> I'd like to separate the test into multiple parts: backfill_tests storage sink, so that we can know the failure in a finer granularity. Furthermore, it's easier to assign a true responsible person for any new failures.
Also renaming the test names to make it shorter. …
> chore(test): separate deterministic integration tests others

- src/meta/model_v2/migration/src/m20230908_072257_init.rs
- src/meta/model_v2/src/actor.rs
- src/meta/node/src/server.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/recovery.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/controller/utils.rs
> feat: cherry-pick some feature and fix to release 1.7 (#14958, #14962)

- Cargo.lock
- Cargo.toml
- ci/Dockerfile
- ci/build-ci-image.sh
- ci/docker-compose.yml
- ci/scripts/build-other.sh
- docker/Dockerfile
- docker/Dockerfile.hdfs
- e2e_test/udf/wasm_udf.slt
- src/expr/core/src/expr/expr_udf.rs
- src/frontend/src/handler/create_function.rs
- src/sqlparser/src/ast/mod.rs
This PR allows users to inline their Rust UDF code in the create-function statement.
```sql
create function gcd(int, int) returns int language rust as $$
fn gcd(mut a: i32, mut b: i32) -> i32 {
while b != 0 {
let t = b;
b = a % b;
a = t;
}
a
}
$$;
```
The function will be [built](https://github.com/risingwavelabs/arrow-udf/blob/765aecd70223a90066dce7f9943b697d641feb96/arrow-udf-wasm/src/build.rs) into a wasm binary in the frontend. This requires the Rust toolchain (with the wasm32-wasi target) installed in frontend's environment. The build process will run for at least 10s, during which time the command is blocking from …
> feat(udf): support inlined Rust UDF

- proto/expr.proto
- src/common/src/types/interval.rs
- src/common/src/types/mod.rs
- src/expr/core/src/window_function/call.rs
- src/expr/core/src/window_function/state/aggregate.rs
- src/frontend/planner_test/tests/testdata/input/over_window_function.yaml
- src/frontend/planner_test/tests/testdata/output/over_window_function.yaml
- src/frontend/src/binder/expr/function.rs
- src/frontend/src/optimizer/plan_node/logical_over_window.rs
- src/frontend/src/optimizer/rule/over_window_to_agg_and_join_rule.rs
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/src/parser.rs
This PR:
- Adds `RANGE` frame support in parser and binder;
- Adds necessary structs in `call.rs` to represent concepts related to range frame, including `RangeFrameBounds` and `RangeFrameOffset`.
15x out of 6xx lines of addition are planner tests, reviewers plz don't panic.
</details>
> feat(over window): window function `RANGE` frame support in frontend

- ci/docker-compose.yml
- ci/scripts/release.sh
- ci/workflows/docker.yml
- ci/workflows/main-cron.yml
https://github.com/risingwavelabs/risingwave/issues/14898
</details>
> ci(chore): build arm binary in release and docker

- e2e_test/over_window/generated/batch/basic/cross_check.slt.part
- e2e_test/over_window/generated/batch/basic/mod.slt.part
- e2e_test/over_window/generated/batch/basic/setup.slt.part
- e2e_test/over_window/generated/batch/basic/teardown.slt.part
- e2e_test/over_window/generated/streaming/basic/cross_check.slt.part
- e2e_test/over_window/generated/streaming/basic/mod.slt.part
- e2e_test/over_window/generated/streaming/basic/setup.slt.part
- e2e_test/over_window/generated/streaming/basic/teardown.slt.part
- e2e_test/over_window/templates/basic/cross_check.slt.part
- e2e_test/over_window/templates/basic/mod.slt.part
- e2e_test/over_window/templates/basic/setup.slt.part
- e2e_test/over_window/templates/basic/teardown.slt.part
- src/batch/src/executor/sort_over_window.rs
- src/common/src/types/mod.rs
- src/common/src/types/sentinel.rs
- src/expr/core/src/window_function/call.rs
- src/expr/core/src/window_function/state/aggregate.rs
- src/expr/core/src/window_function/state/buffer.rs
- src/expr/core/src/window_function/state/mod.rs
- src/frontend/planner_test/tests/testdata/input/over_window_function.yaml
- src/frontend/planner_test/tests/testdata/output/over_window_function.yaml
- src/frontend/src/optimizer/plan_node/logical_over_window.rs
- src/stream/src/executor/over_window/frame_finder.rs
- src/stream/src/executor/over_window/general.rs
- src/stream/src/executor/over_window/over_partition.rs
This PR implements the real `RANGE` frame support in backend executors. Resolves #11109.
The basic idea to support `RANGE` frame in `find_affected_ranges` is to:
1. Calculate the logical order column values of the first and last *current row/key* for a given set of delta;
2. Try to find the cache keys that are closest to the logical order values calculated in step 1;
3. Compare with the first/last *current key* of `ROWS` frames, choose the minimum/maximum one as the final first/last *current key*;
4. Calculate the logical order column values of the first frame start and last frame end, similar to step 1;
5. Try to find …
> feat(over window): window function `RANGE` frame support - backend part

- e2e_test/udf/sql_udf.slt
- src/frontend/src/handler/create_sql_function.rs
As titled, refactor the current sql udf test suite to five sections, to improve the readability & future maintainability.
See the updated test for details.
Just a reminder of the naming convention of sql udf, now we will stick with: SQL udf with [unnamed / named] parameters, instead of the original [anonymous / named] sql udf. The documentation may be updated accordingly.
Reference: https://github.com/risingwavelabs/risingwave/pull/14941#discussion_r1477166182.
</details>
> refactor(test): refactor sql udf test

- lints/Cargo.lock
- lints/Cargo.toml
- lints/src/format_error.rs
- lints/ui/format_error.rs
- lints/ui/format_error.stderr
See the test for more details.
</details>
> feat(lints): improve help message when formatting error in `anyhow` macro

- src/meta/src/hummock/compaction/picker/emergency_compaction_picker.rs
- src/meta/src/hummock/compaction/picker/intra_compaction_picker.rs
> feat(compaction): compact partitioned level for EmergencyCompactionPicker

- src/frontend/planner_test/tests/testdata/output/case_when_optimization.yaml
> fix(test): fix case_when_optimization test

- src/connector/src/lib.rs
- src/connector/src/parser/mod.rs
- src/connector/src/parser/mysql.rs
- src/connector/src/parser/postgres.rs
- src/connector/src/parser/unified/json.rs
- src/connector/src/sink/clickhouse.rs
- src/connector/src/sink/deltalake.rs
- src/connector/src/sink/doris.rs
- src/connector/src/sink/doris_starrocks_connector.rs
- src/connector/src/sink/encoder/avro.rs
- src/connector/src/sink/encoder/json.rs
- src/connector/src/sink/iceberg/mod.rs
- src/connector/src/sink/kafka.rs
- src/connector/src/sink/mod.rs
- src/connector/src/sink/nats.rs
- src/connector/src/sink/redis.rs
- src/connector/src/sink/remote.rs
- src/connector/src/sink/starrocks.rs
- src/connector/src/source/base.rs
- src/connector/src/source/cdc/enumerator/mod.rs
- src/connector/src/source/cdc/external/mod.rs
- src/connector/src/source/cdc/external/postgres.rs
- src/connector/src/source/cdc/source/reader.rs
- src/connector/src/source/cdc/split.rs
- src/connector/src/source/datagen/source/reader.rs
- src/connector/src/source/filesystem/s3/source/reader.rs
- src/connector/src/source/google_pubsub/enumerator/client.rs
- src/connector/src/source/google_pubsub/source/reader.rs
- src/connector/src/source/kafka/source/reader.rs
Follow-up of #14713. All direct error formatting should be cleaned up after this PR, and the lints for `connector` crate is also enabled.
</details>
> refactor(error): clean-up direct error formatting (part 5, done)

- src/frontend/planner_test/tests/testdata/output/lateral_subquery.yaml
- src/frontend/planner_test/tests/testdata/output/subquery.yaml
- src/frontend/planner_test/tests/testdata/output/subquery_expr_correlated.yaml
- src/frontend/planner_test/tests/testdata/output/tpch.yaml
- src/frontend/planner_test/tests/testdata/output/tpch_variant.yaml
- src/frontend/src/optimizer/logical_optimization.rs
- src/frontend/src/optimizer/rule/mod.rs
- src/frontend/src/optimizer/rule/pull_up_correlated_predicate_agg_rule.rs
- Link https://github.com/risingwavelabs/risingwave/issues/14797
- Support `PullUpCorrelatedPredicateAggRule` to unnest a common subquery pattern in tpch. Pull up correlated predicates from the right agg side of Apply to the `on` clause of Join.
</details>
> feat(optimizer): support PullUpCorrelatedPredicateAggRule

- src/tests/simulation/tests/integration_tests/recovery/background_ddl.rs
When there's high barrier latency, test that arrangement backfill can be cancelled.
The fix ensures there's some progress, to ensure latency is high when we issue a cancel command. Otherwise the cancel command will succeed quickly.
</details>
> fix(integration_tests): separate test for arrangement backfill cancel with high barrier latency

- src/connector/src/common.rs
- src/connector/with_options_sink.yaml
- src/connector/with_options_source.yaml
following https://github.com/risingwavelabs/risingwave/pull/13990
add kafka props `enable.ssl.certificate.verification` (optional, default `true`)
</details>
> feat: add kafka props enable.ssl.certificate.verification

- Cargo.lock
- src/connector/src/error.rs
- src/error/Cargo.toml
- src/error/src/anyhow.rs
- src/error/src/lib.rs
Make `ConnectorError` a wrapper of `anyhow::Error` **without implicit casting**, so that developers are forced to provide default or ad-hoc context messages when doing conversion.
Check the documentation on `def_anyhow_wrapper` macro for the motivation and the design.
This is another attempt to resolve https://github.com/risingwavelabs/risingwave/pull/15031#discussion_r1480863169. …
> refactor(connector): make `ConnectorError` a wrapper of `anyhow::Error`

- e2e_test/batch/catalog/issue_8791.slt.part
- e2e_test/batch/catalog/pg_settings.slt.part
- src/frontend/src/catalog/system_catalog/mod.rs
- src/frontend/src/catalog/system_catalog/pg_catalog/pg_settings.rs
- src/frontend/src/scheduler/local.rs
- src/frontend/src/scheduler/mod.rs
- src/frontend/src/scheduler/task_context.rs
> feat(catalog): implement `pg_settings`

- src/common/src/system_param/reader.rs
- src/frontend/src/handler/variable.rs
- src/frontend/src/utils/infer_stmt_row_desc.rs
Add `description` column to `SHOW PARAMETERS`. Use `ParameterInfo` to represent it to make it more consistent with session variables.
</details>
> feat(frontend): add description column for `SHOW PARAMETERS`

- e2e_test/batch/catalog/pg_settings.slt.part
- src/frontend/src/catalog/system_catalog/mod.rs
- src/frontend/src/catalog/system_catalog/pg_catalog/pg_settings.rs
- src/frontend/src/scheduler/task_context.rs
- src/frontend/src/session.rs
Based on #15113 and #15108. Resolve #8850.
----
Note that the session variables is always a subset of system parameters in Postgres' configuration system (Grand Unified Configuration, GUC), which does not hold in RisingWave.
As a result, `psql` will also auto-complete session variables for `ALTER SYSTEM SET` that are false positives. There's no elegant way to fix that as the query for auto-completion is automatically sent by the client. However, this is not a significant issue so we may simply leave it as it is.
Support tab-completion for `SET` and `ALTER SYSTEM SET` commands in `psql` client.
> feat(frontend): support tab-completion for `[ALTER SYSTEM] SET`

- src/object_store/src/object/opendal_engine/opendal_object_store.rs
Object metadata `ContentContent` is actually never used in object store `list`. We've confirmed that requesting it during `list` will cause N additional requests to be sent where N is the number of objects returned by `list`. It dramatically slows down `list`, e.g. several thousand times slower found in my case.
</details>
> fix(storage): remove unnecessary metadata io during list

- proto/expr.proto
- src/expr/impl/benches/expr.rs
- src/expr/impl/src/scalar/timestamptz.rs
- src/expr/impl/src/scalar/to_timestamp.rs
- src/frontend/src/binder/expr/function.rs
- src/frontend/src/expr/pure.rs
- src/frontend/src/expr/session_timezone.rs
- src/frontend/src/expr/utils.rs
After #15030 (for SQL-backend based meta store) tightens the compatibility rule from `WIRE` to `WIRE_JSON` such renames would not be possible. So the rename has to happen before SQL-backend based meta store (and `single_node` mode which depends on it with sqlite) goes into production.
For these 2 functions in PostgreSQL:
https://www.postgresql.org/docs/16/functions-datetime.html#id-1.5.8.15.6.2.2.38.1.1.1
`to_timestamp ( double precision ) → timestamp with time zone`
https://www.postgresql.org/docs/16/functions-formatting.html#id-1.5.8.14.4.2.2.6.1.1.1
`to_timestamp ( text, text ) → timestamp with time zone`
We used to …
> refactor: rename `TO_TIMESTAMP{,1}` in expr.proto for clarity

- e2e_test/batch/catalog/version.slt.part
- e2e_test/batch/functions/setting.slt.part
- src/common/src/lib.rs
For `atlasgo` to work. cc @neverchanje 
</details>
> chore: upgrade declared pg version to 13.14.0

- src/object_store/src/object/opendal_engine/opendal_s3.rs
as title, we don't need to set ak sk anymore.
</details>
> refactor(object store): use AssumeRoleWithWebIdentity for opendal s3

- integration_tests/http-sink/README.md
- integration_tests/http-sink/create_mv.sql
- integration_tests/http-sink/create_sink.sql
- integration_tests/http-sink/create_source.sql
- integration_tests/http-sink/docker-compose.yml
- java/connector-node/risingwave-connector-service/pom.xml
- java/connector-node/risingwave-sink-mock-flink/risingwave-sink-mock-flink-http-sink/src/main/java/com/risingwave/mock/flink/http/HttpFlinkMockSinkFactory.java
Add an http sink demo
</details>
> feat(sink demo): Add http sink demo

- Makefile.toml
Sometimes the Zookeeper cluster can't start up, making it unable to kill the cluster.
</details>
> chore: fix `risedev kill`

- src/meta/src/stream/scale.rs
- src/meta/src/stream/test_scale.rs
Signed-off-by: Shanicky Chen <peng@risingwave-labs.com>I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).
This PR attempts to reduce meta memory usage during the scaling process by substituting the original `PbStreamActor` and `PbFragment` with custom-designed `CustomActorInfo` and `CustomFragmentInfo`, thereby reducing memory usage by minimizing the memory replication of nodes.
> feat: try to reduce memory usage in scaling

- proto/buf.yaml
See #15030 for the background.
Again, the check is not enforced in CI. We can safely ignore it...
- if the message is never persisted,
- or any time before the SQL meta store is released and marked as stable.
</details>
> chore: set `buf breaking` rule back to `WIRE_JSON`

- e2e_test/batch/catalog/pg_settings.slt.part
- src/common/fields-derive/src/gen/test_empty_pk.rs
- src/common/fields-derive/src/gen/test_no_pk.rs
- src/common/fields-derive/src/gen/test_output.rs
- src/common/fields-derive/src/lib.rs
- src/common/src/types/fields.rs
- src/frontend/macro/src/lib.rs
- src/frontend/src/catalog/system_catalog/pg_catalog/pg_cast.rs
- src/frontend/src/catalog/system_catalog/pg_catalog/pg_settings.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_hummock_branched_objects.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_hummock_pinned_snapshots.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_hummock_pinned_versions.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_hummock_version.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_meta_snapshot.rs
See #15125 for the background.
We should not default to empty primary key for `#[derive(Fields)]` without specifying primary keys, or the semantics will be "at most one row".
The ultimate solution could be making the `pk` field of `TableDesc` and `TableCatalog` to be an `Option`. However, this may require a much more significant refactor. Note that we're only misusing the primary key of the system table, so I simply add a requirement for specifying the primary key for `system_table` proc macro in this PR. …
> fix(frontend): require primary key for system table

- e2e_test/streaming/bug_fixes/issue_15198.slt
- src/frontend/src/expr/utils.rs
> fix(optimizer): visit ternary ops when offset is specified for `tumble`

- src/cmd_all/src/bin/risingwave.rs
- src/cmd_all/src/single_node.rs
Closes https://github.com/risingwavelabs/risingwave/issues/15062
Just create `state_store`, `meta_store` directories, if they did not exist.
The default store directory is:
```
~/.risingwave
```
So by default, the following directories are created:
```
noelkwan@Noels-MacBook-Pro risingwave % tree ~/.risingwave 
/Users/noelkwan/.risingwave
├── meta_store
│   └── single_node.db
└── state_store
└── hummock_001
├── checkpoint
│   └── 0
└── cluster_id
└── 0
```
Also separate `single_node` from `standalone_mode`. …
> feat(cmd_all): create directories in `single_node` mode

- Cargo.lock
- lints/src/format_error.rs
- lints/src/lib.rs
- lints/ui/format_error.rs
- lints/ui/format_error.stderr
- src/cmd/src/lib.rs
- src/cmd_all/Cargo.toml
- src/cmd_all/build.rs
- src/common/src/config.rs
- src/connector/src/sink/nats.rs
- src/connector/src/source/cdc/source/reader.rs
- src/connector/src/source/kafka/enumerator/client.rs
- src/error/src/lib.rs
- src/frontend/planner_test/src/lib.rs
- src/frontend/src/handler/create_source.rs
- src/meta/src/dashboard/mod.rs
- src/meta/src/manager/sink_coordination/coordinator_worker.rs
- src/risedevtool/src/bin/risedev-dev.rs
- src/risedevtool/src/preflight_check.rs
- src/tests/regress/src/lib.rs
- src/tests/simulation/tests/integration_tests/recovery/background_ddl.rs
`anyhow::Error` does not implement `Error` trait, so they were not covered previously. This PR takes `anyhow::Error` into consideration, and also improves the help message for it.
</details>
> feat(lints): lint `format_error` on `anyhow::Error`

- src/storage/src/hummock/compactor/compactor_runner.rs
- src/storage/src/hummock/compactor/fast_compactor_runner.rs
fix https://github.com/risingwavelabs/risingwave/issues/15057#issuecomment-1961343919
When we put some keys and then delete them in one epoch, if hummock enable "spill memtable", and then compact them in the last level of LSM tree, compactor may lost DELETE keys when and only when the safe watermark keeps same with just flushed epoch. We used to assume that the epoch of current keys must be larger than the follower keys, but it is wrong since we start using pure epoch to decide whether it shall be dropped.
So compactor drops the delete keys and left the put key because they share the same `pure_epoch` and it exactly …
> fix(storage): fix leaving put key after delete keys are dropped cause inconsistent

- e2e_test/ddl/search_path.slt
- src/frontend/src/handler/create_index.rs
- src/frontend/src/handler/explain.rs
Fixes #15195.
This PR splits the `resolve_index_schema` part out of `gen_create_index_plan`, and moves the `check_relation_name_duplicated` step between them to correctly use the resolved schema.
Note:
According to #5791 there was a similar constraint on sink, which has been lifted after support of `create sink as query` https://github.com/risingwavelabs/risingwave/pull/6648#discussion_r1034551748.
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting …
> fix(frontend): index `if not exists` check shall use table's schema

- src/object_store/src/object/mod.rs
- src/object_store/src/object/s3.rs
- src/storage/backup/src/storage.rs
- src/storage/benches/bench_compactor.rs
- src/storage/benches/bench_multi_builder.rs
- src/storage/src/hummock/iterator/test_utils.rs
Previously, we only pass object store config to S3 object store only. This makes the timeout config to be None for all other object stores including all object store backends implemented via OpenDAL.
This should be the cause for #15209 and #15239.
</details>
> fix: pass correct object store config to monitored object store for all backends

- src/storage/Cargo.toml
- src/storage/benches/bench_compactor.rs
> fix(storage): fix  failed micro-bench

- e2e_test/ddl/search_path.slt
- src/frontend/src/handler/create_index.rs
- src/frontend/src/handler/explain.rs
Cherry picking #15249 onto branch release-1.7
The action ([src](https://github.com/risingwavelabs/github-action-cherry-pick/blob/f5f70b8eee18ebf4dd85f285819a300ed4a0fe58/entrypoint.sh#L62)) failed:
https://github.com/risingwavelabs/risingwave/actions/runs/8046033730/job/21973800816
```
This is NOT a dry run. We output and execute the command:
hub pull-request -b release-1.7 -h auto-release-1.7-1dd2c3d3c1c764a1f4d8595f253722f0b1863471 -l cherry-pick -a xiangjinwu -m "fix(frontend): index `if not exists` check shall use table's schema (#152[49](https://github.com/risingwavelabs/risingwave/actions/runs/8046033730/job/21973800816#step:4:50))" -m "Cherry picking \#15249 onto branch release-1.7" -r xiangjinwu
/entrypoint.sh: eval: line 26: syntax error: unexpected end of file (expecting "then") …
```
> fix(frontend): index `if not exists` check shall use table's schema (#15249)

- src/storage/hummock_test/src/local_state_store_test_utils.rs
- src/storage/hummock_trace/src/opts.rs
- src/storage/hummock_trace/src/replay/runner.rs
- src/storage/hummock_trace/src/replay/worker.rs
- src/storage/src/hummock/store/local_hummock_storage.rs
- src/storage/src/hummock/store/version.rs
- src/storage/src/mem_table.rs
- src/storage/src/monitor/monitored_store.rs
- src/storage/src/monitor/traced_store.rs
- src/storage/src/panic_store.rs
- src/storage/src/store.rs
- src/storage/src/store_impl.rs
- src/stream/src/common/log_store_impl/kv_log_store/writer.rs
- src/stream/src/common/log_store_impl/subscription_log_store.rs
- src/stream/src/common/table/state_table.rs
- src/stream/src/executor/sink.rs
This PR lets local state store aware of the vnodes it is responsible for by storing vnode bitmap in read version. The vnode bitmap will be initialized during state store init and updated on state table `update_vnode_bitmap`. This PR also adds an extra assertion on read version to ensure there is no staging uncommitted data on `update_vnode_bitmap`.
#15099  …
> feat: store vnode bitmap in local state store

- e2e_test/batch/catalog/pg_user.slt.part
- src/frontend/src/catalog/system_catalog/pg_catalog/pg_user.rs
Reverts risingwavelabs/risingwave#15266
Resolve #15250 .
Already fixed in https://github.com/risingwavelabs/risingwave-cloud/pull/6244
> chore(revert): add name column back in pg_user for backward compatibility

- ci/scripts/run-e2e-test.sh
- ci/workflows/pull-request.yml
- e2e_test/udf/always_retry_python.slt
- proto/catalog.proto
- proto/expr.proto
- src/expr/core/src/expr/expr_udf.rs
- src/expr/udf/src/external.rs
- src/frontend/src/catalog/function_catalog.rs
- src/frontend/src/expr/user_defined_function.rs
- src/frontend/src/handler/create_function.rs
- src/frontend/src/handler/create_sql_function.rs
- src/frontend/src/handler/mod.rs
- src/meta/model_v2/migration/src/m20230908_072257_init.rs
- src/meta/model_v2/src/function.rs
- src/meta/src/controller/mod.rs
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/src/parser.rs
- src/sqlparser/tests/sqlparser_postgres.rs
cherry pick #15163
Closes https://github.com/risingwavelabs/risingwave/issues/15295
</details>
> feat(udf): support always_retry_on_network_error config for udf functions (#15163)

- Cargo.lock
- Makefile.toml
- ci/scripts/build.sh
- docker/Dockerfile
- docker/Dockerfile.hdfs
- docs/developer-guide.md
- src/cmd_all/Cargo.toml
- src/expr/core/Cargo.toml
- src/expr/core/src/expr/expr_udf.rs
- src/expr/core/src/table_function/user_defined.rs
This PR makes `embedded-python-udf` an optional feature. This feature is not enabled by default so that developers are not required to have Python 3.12 installed. To enable it, you can run `ENABLE_PYTHON_UDF=1 ./risedev d` or `cargo build --features embedded-python-udf`. This feature is enabled in production build.
</details>
> fix(udf): add `embedded-python-udf` feature and fix dockerfile

- backwards-compat-tests/scripts/utils.sh
We need to include it in backwards compat tests as well.
Context https://github.com/risingwavelabs/risingwave/pull/11538.
If we didn't wait for process to exit, the previous meta node could still be running and occupying the meta node port. Then test fails.
</details>
> fix(ci): add `wait_process_exit` in backwards compat test

- Cargo.lock
to fix #15235
https://github.com/confluentinc/librdkafka/releases/tag/v2.3.0
</details>
> chore(deps): update librdkafka to v2.3.0

- src/stream/src/from_proto/mod.rs
As simple as title.
</details>
> refactor(stream): make `new_boxed_executor` an async trait function

- src/common/src/log.rs
- src/connector/src/parser/avro/util.rs
- src/connector/src/parser/mysql.rs
- src/connector/src/parser/postgres.rs
Make `LogSuppressor::check` returns `Option<NonZeroUsize>` and record the option value in tracing events. When the suppressed count is zero, the field will be omitted in the event.
Also fixed direct error formatting in `mysql` and `postgres` parser. These are corner cases that are not covered by the lints. Tracked in https://github.com/risingwavelabs/risingwave/issues/15330. …
> refactor: do not output suppressed count when it's zero

- Cargo.lock
- src/jni_core/Cargo.toml
- src/jni_core/src/jvm_runtime.rs
This acts as a preparation step of https://github.com/risingwavelabs/homebrew-risingwave/issues/28.
- Canonicalize the path of `current_exe` before looking for the sibling `libs` directory. So it's based on the real path of the binary (like `/opt/homebrew/Cellar/risingwave/1.6/bin/risingwave`), instead of the symbolic link (`/opt/homebrew/bin/risingwave`). `opt/homebrew/bin/libs` will make no sense.
- Use `fs_err` as the replacement of `std::fs` to provide better error reporting.
- Use `LazyLock::get_or_try_init` instead of storing the `Err` variant into the static variable …
> fix(connector): better locating and error reporting for connector library

- e2e_test/source/basic/kafka.slt
- e2e_test/source/basic/old_row_format_syntax/kafka.slt
- src/frontend/src/handler/create_source.rs
The current implementation is far from best practice. #12871 Effectively we shall consider it as not supported at all.
Existing sources continue working (in the undesired way). And it is easy to recover the code path in case someone relies on it or we support it in another way later.
Creating sources/table with avro encoding now requires usage of schema registry. The avro definition can no longer come from `http[s]://`/`s3://`/`file://`. The `schema.location` option shall not be used.
Do **NOT** document or suggest usage of the option `with_deprecated_file_header`. It is purely internal to keep the current …
> refactor(frontend): disallow creating new avro sources without schema registry

- dashboard/pages/fragment_graph.tsx
- src/meta/src/dashboard/prometheus.rs
For back-pressure visualization in dashboard from the Prometheus data source, issue an instant query instead of a range query with a 30 min window, to fetch the real-time value of the recent 1 min.
Also remove the option for sampling algorithms as they're not applicable any more.
</details>
> fix(dashboard): only show real-time back-pressure rate from Prometheus data source

- Cargo.lock
- Cargo.toml
alternative solution to replace #15368, without introducing feature flag. 
The main motivation is to make the dependency aws-sdk-ec2 optional.
It is very rarely used in development, but contributes to more than half of the compile time.
Check https://github.com/risingwavelabs/rw-aws-sdk-ec2/commits/main/ to see what's changed.
Before  (4m 41.2s total)
After (4m 17.6s total) …
> build: use patched version of aws-sdk-ec2

- src/common/src/array/arrow/arrow_impl.rs
- src/frontend/src/handler/create_source.rs
- src/sqlparser/src/ast/statement.rs
- Related issue https://github.com/risingwavelabs/risingwave/issues/14742
- Automatically derive columns for iceberg source.
Example:
```sql
create source s
with (
connector = 'iceberg',
catalog.type = 'storage',
warehouse.path = 's3a://hummock001/',
s3.endpoint = 'http://127.0.0.1:9301',
s3.access.key = 'minioadmin',
s3.secret.key = 'minioadmin',
s3.region = 'us-east-1',
database.name='demo_db',
table.name='demo_table'
);
``` …
> feat(frontend): derive columns from iceberg source automatically

- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/SourceValidateHandler.java
Allow passwords to be empty for CDC connectors. Tested with my local PostgresQL instance.
Before:
```
dev=> CREATE SOURCE pg_mydb WITH (
connector = 'postgres-cdc',
hostname = '127.0.0.1',
port = '5432',
username = 'eric',
password = '',
database.name = 'test',
slot.name = 'rw_slot'
);
2: failed to create source worker
3: failed to create SplitEnumerator
4: source cannot pass validation
5: INVALID_ARGUMENT: 'password' not found, please check the WITH properties
```
After:
```
dev=> …
```
> fix(cdc-connector): allow empty passwords

- ci/scripts/check.sh
- ci/scripts/release.sh
- src/connector/src/lib.rs
As titled.
The compile error is introduced in https://github.com/risingwavelabs/risingwave/pull/15365. Previously we use `cargo build --bin risectl` to build risectl without specifying the crate via `-p risingwave_cmd`, which makes cargo use the union of features used in all crates in the workspace. `risingwave_simulation` enables `enable_test_epoch` in its dependency list rather than in the dev dependency, which makes the feature union includes the `enable_test_epoch` by accidence. In this PR, by specifying the crate via `-p risingwave_cmd`, the feature enabled in `risingwave_simulation` will not be included in the …
> fix: fix compile err in release build of risectl

- ci/scripts/backwards-compat-test.sh
Broken in https://github.com/risingwavelabs/risingwave/pull/15356. In older version of RisingWave, `risedev` will try to find the individual binaries for `meta-node` etc... so we just include that config to make sure it is linked, if it's in a older version.
</details>
> chore(ci): fix backwards compat tests

- e2e_test/streaming/bug_fixes/issue_15302.slt
- src/stream/src/from_proto/dynamic_filter.rs
> fix(dynfilter): cherrypick left table with singleton dist panic bug (#15406) to branch release-1.6

- integration_tests/starrocks-sink/README.md
- src/connector/src/sink/starrocks.rs
In our implementation of starrocks sink, the type of the array stored in table `nformation_schema.columns` is `UNKNOWN`, which was recently fixed by starrocks, so we are fixing it as well, and we are still keeping `UNKNOWN` for the sake of compatibility with the old version.
</details>
> fix(sink): fix starrocks sink array check

- lints/Cargo.lock
- lints/Cargo.toml
- lints/src/format_error.rs
- lints/ui/format_error.rs
- lints/ui/format_error.stderr
- src/frontend/planner_test/src/lib.rs
- src/frontend/planner_test/tests/planner_test_runner.rs
- src/meta/src/barrier/mod.rs
- src/stream/src/lib.rs
- src/stream/src/task/barrier_manager.rs
Inspired by #15109:
`format_error` lint should not be simply workarounded by adding an `.as_report()` method call. For example, we've started to instruct developers to use `anyhow::Context` if they're formatting errors in an `anyhow!` macro call since #14957.
This PR further enforce this by also adding the lints on the `Report`s in `anyhow!` calls. The UI test clearly shows the changes:
https://github.com/risingwavelabs/risingwave/blob/294b520b2a1ff00023b634b981c8731f8657da0a/lints/ui/format_error.stderr#L347-L378 …
> feat(lints): lint on formatting `Report` in anyhow construction

- src/connector/src/parser/protobuf/parser.rs
- src/connector/src/schema/schema_registry/util.rs
> fix: parsing the header of confluent protobuf message incorrectly

- src/storage/hummock_sdk/src/key.rs
- src/storage/hummock_sdk/src/table_watermark.rs
- src/storage/hummock_test/src/compactor_tests.rs
- src/storage/hummock_test/src/failpoint_tests.rs
- src/storage/hummock_test/src/hummock_read_version_tests.rs
- src/storage/hummock_test/src/hummock_storage_tests.rs
- src/storage/hummock_test/src/local_state_store_test_utils.rs
- src/storage/hummock_test/src/snapshot_tests.rs
- src/storage/hummock_test/src/state_store_tests.rs
- src/storage/hummock_trace/src/opts.rs
- src/storage/src/hummock/event_handler/hummock_event_handler.rs
- src/storage/src/hummock/event_handler/mod.rs
- src/storage/src/hummock/iterator/test_utils.rs
- src/storage/src/hummock/store/hummock_storage.rs
- src/storage/src/hummock/store/local_hummock_storage.rs
- src/storage/src/hummock/store/version.rs
- src/storage/src/mem_table.rs
- src/storage/src/store.rs
- src/stream/src/common/log_store_impl/kv_log_store/mod.rs
- src/stream/src/common/log_store_impl/kv_log_store/writer.rs
- src/stream/src/common/log_store_impl/subscription_log_store.rs
- src/stream/src/common/table/state_table.rs
- src/stream/src/from_proto/subscription.rs
Given that we already ensure storage iter won't read across vnodes in executors, we add strict assertion check in `HummockStorage::iter` and `LocalHummockStorage::iter` to ensure the provided key range is within one vnode to make this assumption explicit. There are several benefits:
- We can better filter read versions based on vnode for batch query to ensure at most one read version is involved. This can avoid issues related to resolving results from multiple read versions like #14659 and #15099
- The version pruning logic for batch and streaming queries can be unified. See `version.rs`.
- The read path logic involving …
> feat: ensure each storage read only involves one vnode

- src/expr/core/src/expr/expr_udf.rs
- src/expr/udf/examples/client.rs
- src/expr/udf/src/external.rs
- src/expr/udf/src/lib.rs
- src/expr/udf/src/metrics.rs
1. Extract the UDF metrics into a higher layer.
2. Then metrics can work for every kinds of the udf
3. The external UDF call logic is little complicated. But we decide to count each trigger as only one call. Event it actually do several call, we can still infer this info from the latency metrics.
4. For embeded udf call, the `link` label will be empty ``. Show in following example, the first three record udf is external udf, the last one are embeded udf:
5. Also add `language` labels: `wasm`, `javascript`, `python`, `external`, for example, the first three is `external`, the last one is `javascript` …
> feat(udf): add udf metrics to embeded udf, refactor external udf metrics.

- integration_tests/big-query-sink/create_sink.sql
- integration_tests/cassandra-and-scylladb-sink/create_source.sql
- java/connector-node/risingwave-sink-cassandra/src/main/java/com/risingwave/connector/CassandraConfig.java
- java/connector-node/risingwave-sink-cassandra/src/main/java/com/risingwave/connector/CassandraSink.java
- src/connector/src/common.rs
- src/connector/src/sink/big_query.rs
- src/connector/src/sink/doris.rs
- src/connector/src/sink/encoder/json.rs
- src/connector/src/sink/encoder/mod.rs
- src/connector/src/sink/starrocks.rs
- src/connector/with_options_sink.yaml
in this pr, we add bigquery's `max_batch_rows`  and cassandra's `max_batch_rows` `request_timeout` to fix problems of excessive data size.
And we fix bigquery array null can't insert error,(the array null will be converted to []. )
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types
`In cassandra sink.` Add two optional option. 
`cassandra.max_batch_rows: `Number of batch rows sent at a time defaults is 512, 
It should be less than 65535 according to cassandra, and ensures that the size of each batch(max_batch_rows * size of each row) is less than 50kb (Configuration items for cassandra: …
> fix(sink): add cassandra batch size and fix bigquery array null

- Cargo.lock
- dashboard/lib/api/metric.ts
- dashboard/lib/api/streaming.ts
- src/meta/Cargo.toml
- src/meta/src/dashboard/mod.rs
Add a `CompressionLayer` for the API backend. This should effectively reduce the transmit size and relieve #15127 in the fastest way.
Take the response size of `/fragments/` as an example, which is used for visualizing the stream fragment graph:
| Workload | Before this PR | After this PR |
|-|-|-|
| Table (1 parallelism) | 4.3 kB | 1.5 kB |
| Table (100 parallelism) | 559 kB | 9.5 kB |
| Nexmark Q7 (1 parallelism) | 28.5 kB | 3.7 kB |
| Nexmark Q7 (100 parallelism) | 3.3 MB | 49.8 kB |
So I think there's no more need to do manual compression any more, mentioned as a candidate …
> feat(dashboard): enable compression for API & minor refactors

- e2e_test/batch/subquery/array_construct.slt.part
- src/frontend/planner_test/tests/testdata/output/subquery.yaml
- src/frontend/planner_test/tests/testdata/output/subquery_expr_correlated.yaml
- src/frontend/src/optimizer/mod.rs
Fix one of the problems identified by #14735.
Previously, we rewrite `array(select ...)` into `(select array_agg(...) ...)`. This is not equivalent when the input is empty, where `array_agg` is expected to return `null` ([doc](https://www.postgresql.org/docs/16/functions-aggregate.html#:~:text=array_agg%20returns%20null%20rather%20than%20an%20empty%20array%20when%20there%20are%20no%20input%20rows)) but `array(select ...)` is expected to return `{}`. So we have to include an extra step to `coalesce` the `null` into an empty list. …
> fix(planner): array-construction subquery shall return `{}` rather than `null`

- src/frontend/planner_test/tests/testdata/input/insert.yaml
- src/frontend/planner_test/tests/testdata/output/insert.yaml
- src/frontend/src/binder/bind_context.rs
- src/frontend/src/binder/expr/column.rs
- src/frontend/src/binder/expr/function.rs
- src/frontend/src/binder/insert.rs
> fix(binder): pick 15597

- ci/scripts/common.sh
- ci/scripts/gen-flamegraph.sh
- src/risedevtool/kafka.toml
Cherry picking #15514 onto branch release-1.7
... or `end-to-end {source,sink} test` timeout with 15+ min spent on downloading kafka:
https://buildkite.com/risingwavelabs/pull-request/builds/44163
https://buildkite.com/risingwavelabs/pull-request/builds/44172
> fix(risedev): always download latest Kafka (#15514)

- src/connector/src/lib.rs
- src/connector/src/source/base.rs
- src/connector/src/source/kafka/private_link.rs
- src/connector/src/with_options.rs
- src/frontend/src/catalog/connection_catalog.rs
- src/frontend/src/handler/alter_source_with_sr.rs
- src/frontend/src/handler/create_source.rs
- src/frontend/src/handler/create_table.rs
- src/frontend/src/handler/util.rs
- src/frontend/src/optimizer/plan_node/generic/source.rs
- src/frontend/src/utils/with_options.rs
- src/stream/src/from_proto/source/trad_source.rs
> refactor: introduce Get and WithPropertiesExt

- src/batch/src/executor/row_seq_scan.rs
> fix(batch): make batch range scan sequentially to avoid OOM

- Makefile.toml
- ci/scripts/standalone-utils.sh
- dashboard/README.md
- src/cmd_all/scripts/standalone-demo-full.sh
- src/risedevtool/common.toml
- src/risedevtool/config/src/main.rs
- src/risedevtool/src/task/meta_node_service.rs
See https://github.com/risingwavelabs/risingwave/issues/15280#issuecomment-1993795653 for the background. This is a preparation for #15656.
Assets will be embedded into the binary and built with Rust build script, so there'll be no step for manually build them.
</details>
> refactor(risedev): deprecate steps for building dashboard

- proto/stream_service.proto
- src/compute/src/rpc/service/stream_service.rs
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/recovery.rs
- src/meta/src/barrier/rpc.rs
- src/meta/src/stream/scale.rs
- src/meta/src/stream/stream_manager.rs
- src/rpc_client/src/lib.rs
- src/rpc_client/src/stream_client.rs
- src/storage/src/memory.rs
- src/stream/src/task/barrier_manager.rs
- src/stream/src/task/barrier_manager/tests.rs
- src/stream/src/task/stream_manager.rs
- src/tests/simulation/src/slt.rs
Reverts risingwavelabs/risingwave#15652 and re-merge #14887
sysbench that failed previously succeeds with the fix in this PR https://buildkite.com/risingwave-test/sysbench/builds/707
The previous failure is caused when meta node try to connect to a newly registered CN worker. It seems that there is latency in the dns information propagation in the k8s cluster. As a result, the meta node will fail to resolve the dns information of the newly registered CN worker that may just get booted and then the initial command will fail.
The fix in this PR is to retry when fail to create a new control stream with the newly registered CN worker.
Most LOC in this PR is from the previous merged PR. Fix can be reviewed in the commit [8e52b83](https://github.com/risingwavelabs/risingwave/pull/15653/commits/8 …
> feat: re-merge #14887 (inject and collect barrier in bidi stream)

- Cargo.lock
- src/connector/Cargo.toml
- src/connector/src/sink/redis.rs
- src/risedevtool/Cargo.toml
- src/workspace-hack/Cargo.toml
In some cases, there may be `Parse error` problems that we can't reproduce,
> ResponseError: Parse error at 1
Unexpected 84
Unexpected 72
so we go to the community for help, and based on the community's answers https://github.com/redis-rs/redis-rs/issues/1075, we use `aio::MultiplexedConnection` instead of `aio::Connection`
</details>
> fix(sink): fix redis sink parse error

- e2e_test/source/cdc/cdc.share_stream.slt
- src/connector/src/source/cdc/external/mod.rs
- src/connector/src/with_options.rs
- src/frontend/src/binder/relation/table_or_source.rs
- src/frontend/src/handler/create_source.rs
- src/frontend/src/planner/relation.rs
fix https://github.com/risingwavelabs/risingwave/issues/13955
</details>
> fix: deny create MV on shared CDC source

- src/frontend/src/session/transaction.rs
- src/storage/backup/integration_tests/common.sh
- src/storage/backup/integration_tests/test_query_backup.sh
- src/storage/hummock_sdk/src/lib.rs
The meta backup test failed because it used an arbitrary epoch in batch query over backup and failed an assertion in storage layer `debug_assert!((epoch & EPOCH_SPILL_TIME_MASK) == 0);` 
This PR ensures batch query always uses a pure epoch.
#15600
</details>
> fix(batch): always use pure epoch in query

- src/common/src/session_config/mod.rs
- src/common/src/util/column_index_mapping.rs
- src/stream/src/common/table/state_table.rs
The i2o_mapping is used to find output columns and use them to build the replicated data chunk, with a schema same as the base table's schema.
The "o" part is the pruned output indices from upstream side.
The "i" part is the base table's indices.
The target size previously used `output_column_indices`. This is actually just a partial mapping of indices, rather than the full set of output indices. It is constrained by the "i" part, since we iterate on `table_catalog.columns`.
What we want instead is for the target size to come from the "o" part. Which is simply `output_column_ids.len()`.
This is an issue when output …
> fix(backfill): fix arrangement backfill's target size for i2o_mapping of replicated rows

- Cargo.lock
- src/object_store/Cargo.toml
> chore: bump opendal to v0.45.1

- src/batch/src/task/task_execution.rs
Otherwise the query will be stuck forever.
https://github.com/risingwavelabs/risingwave/pull/15735#issuecomment-2002888628
</details>
> fix(batch): notify frontend on execution panic

- src/stream/src/executor/backfill/utils.rs
Close https://github.com/risingwavelabs/risingwave/issues/14910.
Recovery test will always retry currently. And so if it encounters this error, it can typically retry. But we `panic` instead of `bail`, so it was unable to.
We can just let it `bail` and retry instead.
This is because this error can be due to a race condition, where the metadata of the stream job was dropped before the CN actor is dropped.
Then the CN actor tries to get row, but the state table has already been deregistered, so it will just return `None`.
So we can just let the CN undergo recovery, to go back into a consistent state. …
> fix(backfill): use `bail` instead of panic in arrangement backfill's assertion

- src/meta/src/backup_restore/restore.rs
This PR prevents user from accidentally restoring a metadata backup to a running cluster.
The restore process now writes to meta store first and then object store. Because writing to a non-empty meta store will be rejected.
</details>
> refactor(backup): restore object store after meta store

- Cargo.lock
- src/storage/Cargo.toml
- src/storage/benches/bench_block_cache.rs
As title.
Results:
```
> RUST_BACKTRACE=1 cargo bench -p risingwave_storage --bench bench_block_cache
Finished bench [optimized + debuginfo] target(s) in 0.55s
Running benches/bench_block_cache.rs (target/release/deps/bench_block_cache-5eef57be0565b6eb)
Gnuplot not found, using plotters backend
10000 keys cost time: [58.7025ms, 73.819638ms, 74.843664ms, 61.132846ms, 64.005928ms, 69.41919ms, 70.693193ms, 57.888342ms,
io count: 0
block-cache             time:   [22.031 µs 22.049 µs 22.073 µs]
Found 9 outliers among 100 measurements (9.00%)
4 (4.00%) high mild
5 (5.00%) high severe
10000 keys cost time: [50.792286ms, …
```
> perf(storage): add foyer memory cache to block cache bench

- ci/docker-compose.yml
- ci/scripts/release.sh
In #4556, we switched to the `manylinux2014` Linux distro to ensure that the released artifact can run on systems with GLIBC versions as old as 2.17. However, this is becoming troublesome as the toolchain is also affected as described in #15749.
After some consideration and discussion with @xxchan, I think it's the time to bump the minimal GLIBC version to 2.28. Reasons:
- Originally, Amazon Linux 2 with GLIBC 2.26 was set to reach its EOL in June 2023 but was later postponed to June 2025. However, the default image used for launching a new EC2 instance is now Amazon Linux 2023, which has GLIBC 2.34. So problems similar …
> chore: bump mimimal glibc version to 2.28 for linux binary release

- src/common/estimate_size/src/collections/mod.rs
- src/common/estimate_size/src/collections/vec.rs
- src/stream/src/executor/lookup/cache.rs
- src/stream/src/executor/lookup/impl_.rs
As simple as title, so that we will keep the `estimate_size::collections` module neat.💦
</details>
> refactor(common): rename `VecWithKvSize` to `EstimatedVec`

- src/storage/src/error.rs
- src/storage/src/hummock/error.rs
Normalize the error message from `storage` crate to make `thiserror_ext::Report` works better with that.
When formatting the source chain of an error with `thiserror_ext::Report`, the `source` part will be trimmed if it's a suffix of the message of its parent. This requires us to avoid adding any trailing characters like `.` in the message.
```diff
- ObjectStore failed with IO error Internal error: read timeout.: Internal error: read timeout
+ ObjectStore failed with IO error: Internal error: read timeout
``` …
> refactor(storage): normalize error message

- src/common/estimate_size/src/collections/hashset.rs
- src/common/estimate_size/src/collections/mod.rs
- src/stream/src/executor/lookup/cache.rs
Seems previously `LookupEntryState` is just a simple `EstimateSize` wrapper for `HashSet`, this PR generalize it to `EstimatedHashSet` so that other modules can reuse it in the future.
</details>
> refactor(common): generalize `LookupEntryState` to `EstimatedHashSet`

- src/common/src/field_generator/varchar.rs
- src/stream/src/common/table/state_table.rs
- src/stream/src/executor/mod.rs
- src/stream/src/executor/troublemaker.rs
- src/stream/src/from_proto/mview.rs
- src/stream/src/from_proto/source/trad_source.rs
- src/stream/src/from_proto/stream_scan.rs
- src/stream/src/lib.rs
RFC: https://www.notion.so/risingwave-labs/RFC-Tolerate-Inconsistency-in-Stream-f6233f46da2c458f9f03b415b9d82cc1?pvs=4
This PR introduces "insane" mode to produce inconsistent stream on `StreamScan` and `Source`. This mode can be turned on by setting env var `RW_UNSAFE_ENABLE_INSANE_MODE=true`. The purpose is to help locate panic points in executors that will panic when facing inconsistent stream.
When "insane" mode is enabled, a `TroublemakerExecutor` will be attached right behind each `StreamScan` and `Source`. The "troublemaker" will randomly change the `Op` and row data in stream chunks pass through it.
State tables …
> feat(stream): introduce "insane" mode to generate inconsistent data on the stream

- src/meta/src/barrier/recovery.rs
Thanks to @yezizp2012 for proposing and discussing this solution.
Close #15296 
The issue occurs because drop statement is executed while recovery is in progress.
Then:
1. Recovery cannot proceed because it cannot acquire the reschedule lock.
2. Drop cannot proceed because it waits for recovery of barrier manager.
Solution:
1. To resolve this deadlock, we let the recovery fail its current loop.
2. At this point, the drop command has already queued the `DropStreamingJob` command.
3. In the next recovery loop, we have the `pre_apply_drop_cancel` which occurs before the `scale_actors` step.
4. The queued drop command will …
> fix(meta): avoid reschedule deadlock with `drop` / `cancel` stream job

- src/common/src/array/arrow/arrow_default.rs
- src/common/src/array/arrow/arrow_impl.rs
ToArrow version of #15820 
</details>
> feat: add to arrow convert

- Cargo.lock
- integration_tests/iceberg-source/python/main.py
- src/connector/src/source/iceberg/mod.rs
- src/frontend/Cargo.toml
- src/frontend/src/optimizer/plan_node/batch_source.rs
- src/frontend/src/optimizer/plan_node/generic/source.rs
- src/frontend/src/optimizer/plan_node/logical_source.rs
- src/frontend/src/planner/relation.rs
- src/frontend/src/scheduler/plan_fragmenter.rs
- Support time travel for iceberg source https://github.com/risingwavelabs/risingwave/issues/15846 https://github.com/risingwavelabs/risingwave/issues/14742 https://github.com/risingwavelabs/risingwave/issues/15822
```sql
-- FOR SYSTEM_TIME AS OF [STRING | NUMBER] 
-- the timestamp should be a format like [YYYY-MM-DD HH:MM:SS] or an unix timestamp in second
select * from s for system_time as of '2100-01-01 00:00:00+00:00';
select * from s for system_time as of 4102444800;
-- FOR SYSTEM_VERSION AS OF [SNAPSHOT_ID]
select * from s for system_version as of 3023402865675048688;
``` …
> feat(batch): support time travel for iceberg source

- Cargo.lock
- src/connector/Cargo.toml
- src/connector/src/source/filesystem/opendal_source/opendal_reader.rs
Supplement to #15744.
Note that icelake specifies `>=0.40`, causing dependabot to automatically bump it to `0.45`. But our connector requires `0.44`, leading to all dependabot PRs blocked.
</details>
> chore: bump opendal to v0.45.1 for connector/icelake

- e2e_test/batch/types/pg_catalog.slt.part
- src/frontend/src/binder/expr/mod.rs
In new version of `psql` client (15+ ?), the query for tab-completing the table name has changed, where table names and schema names now reside in different columns and the other one will be filled with `NULL::pg_catalog.text`.
We are currently unable to bind the `pg_catalog.text` type, which is preventing us from supporting those completions.
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact …
> feat(binder): support binding `pg_catalog.text`

- src/cmd_all/src/single_node.rs
#15897 switched `playground` to `single-node` mode and there's a regression that the dashboard is disabled since `dashboard_host` is not set. This actually applies to all single node deployments.
</details>
> fix(playground): should enable dev dashboard

- ci/scripts/release.sh
Some user reported that RisingWave binary for aarch64 cannot run on his/her system, saying "unsupported page size". This is because the configured page size on that system is 64K instead of 4K. Searched around and found several other projects using `jemalloc` encountered this issue too: [swc](https://github.com/swc-project/swc/pull/6541), [polars](https://github.com/pola-rs/polars/pull/5694), [arrow](https://github.com/apache/arrow/pull/10940).
So this PR fixes it, just like what other projects did. I tested the binary built with the `JEMALLOC_SYS_WITH_LG_PAGE=16` on system with 4K page size, and it worked, so hopefully …
> fix(jemalloc): support large page size for aarch64

- src/config/ci-mem.toml
These tests use an in-memory object store per CN instance. See: https://github.com/risingwavelabs/risingwave/blob/1e848526ba487836d72a29b5390689f712b50e0d/src/risedevtool/src/task/meta_node_service.rs#L131
In Arrangement Backfill, when we read from checkpointed data, and it can be from a different CN instance.
Given the following scenario:
```
create materialized view Y as ...;
create materialized view X as select * from Y;
```
1. singleton arrangement backfill executor X scheduled to worker node A.
2. singleton materialize executor Y scheduled to worker node B.
3. Later Y writes vnode=0 (because its singleton) and …
> chore(ci): disable arrangement backfill for in-memory e2e parallel tests

- src/batch/Cargo.toml
- src/batch/src/error.rs
- src/batch/src/lib.rs
- src/batch/src/worker_manager/mod.rs
- src/batch/src/worker_manager/worker_node_manager.rs
- src/frontend/src/catalog/system_catalog/mod.rs
- src/frontend/src/handler/explain.rs
- src/frontend/src/handler/query.rs
- src/frontend/src/observer/observer_manager.rs
- src/frontend/src/optimizer/property/distribution.rs
- src/frontend/src/scheduler/distributed/query.rs
- src/frontend/src/scheduler/distributed/query_manager.rs
- src/frontend/src/scheduler/distributed/stage.rs
- src/frontend/src/scheduler/error.rs
- src/frontend/src/scheduler/local.rs
- src/frontend/src/scheduler/mod.rs
- src/frontend/src/scheduler/plan_fragmenter.rs
- src/frontend/src/session.rs
- Move the worker node manager from frontend to batch, so that we can `mask_worker_node` for batch queries executed in local mode. Previously #10328 only masked worker node for distributed queries.
</details>
> refactor(batch): move worker node manager from frontend to batch

- src/cmd_all/src/bin/risingwave.rs
In #15847 and #15897 we made `single-node` the default in CLI if there's no other explicit subcommand specified. However, the approach that matches on the error kind leads to some unexpected side effects like #16065.
This PR utilizes a more recommended approach ([ref](https://github.com/clap-rs/clap/blob/731d18f300919a396eee62253f31239b9b02a943/examples/git.rs#L32-L39)) to achieve the same behavior, which resolves #16065 and also improves the help messages like the following:
```
All-in-one executable for components of RisingWave
Usage: risingwave [OPTIONS]
risingwave …
```
> fix: correctly implement default subcommand for `single-node`

- src/meta/src/controller/streaming_job.rs
- src/meta/src/lib.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/rpc/ddl_controller_v2.rs
- src/meta/src/stream/stream_graph/fragment.rs
Resolve https://github.com/risingwavelabs/risingwave/issues/15900#issuecomment-2021859103 and supplement #11388.
To reproduce:
1. Start RisingWave with a compute node of `--parallelism 9999`
2. `set streaming_parallelism to 8888`
3. then create a streaming job
Also rename the parallelism specified by session variable from `default_parallelism` into `specified_parallelism` to avoid confusion with the meta opt with the same name. …
> fix(meta): do not panic on specified parallelism greater than vnode count

- e2e_test/batch/transaction/cursor.slt
- e2e_test/batch/transaction/cursor_multi_conn.slt
- src/frontend/planner_test/src/lib.rs
- src/frontend/src/handler/close_cursor.rs
- src/frontend/src/handler/declare_cursor.rs
- src/frontend/src/handler/fetch_cursor.rs
- src/frontend/src/handler/mod.rs
- src/frontend/src/handler/query.rs
- src/frontend/src/handler/transaction.rs
- src/frontend/src/session.rs
- src/frontend/src/session/cursor.rs
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/src/parser.rs
- src/tests/simulation/src/slt.rs
- src/utils/pgwire/src/pg_response.rs
Introduce `CURSOR` in this PR. Currently, the cursors are mainly used by [fdw](https://github.com/risingwavelabs/risingwave/issues/14318).  So, to simplify, only the minimum function/syntax set required by `fdw` is added in this PR. 
However, this PR is still imperfect due to two reasons:
- The `fdw` allows PgSQL to access a foreign database like a normal table. When there is data access, the `fdw` will convert SQL to AST, then convert AST into SQL query, and then fetch data using a cursor from RW. The conversion can sometimes include some unsupported features/syntax. For example, the `fdw` will convert `LIMIT 5` in the …
> feat(batch): initial cursor implementation

- src/stream/src/executor/aggregation/agg_group.rs
- src/stream/src/executor/join/hash_join.rs
- src/stream/src/executor/managed_state/join/join_entry_state.rs
- src/stream/src/lib.rs
In "insane" and non-strict consistency mode, there'll be too many duplicate inconsistency error logs, this PR use `LogSuppresser` to rate limit them.
</details>
> feat(stream): use `LogSuppresser` for consistency error log

- .github/dependabot.yml
https://github.com/dependabot/dependabot-core/issues/4364#issuecomment-2002406602
https://github.com/risingwavelabs/risingwave/pull/16101#discussion_r1548916995
</details>
> chore(dependabot): try to ignore some directories

- Cargo.lock
- src/meta/dashboard/Cargo.toml
- src/meta/dashboard/src/embed.rs
Based on #16129, resolve the comment.
</details>
> refactor(meta): use `axum-embed` to embed dashboard assets

- src/meta/src/controller/fragment.rs
- src/meta/src/controller/user.rs
- src/meta/src/manager/metadata.rs
Fixes from #16090 .
</details>
> fix(meta): fix column binding for fragment ids

- src/meta/src/manager/sink_coordination/coordinator_worker.rs
As titled.
Resolved the comment https://github.com/risingwavelabs/risingwave/issues/16140#issuecomment-2036105607
</details>
> feat(sink): include more info in coordinator err response

- ci/scripts/e2e-iceberg-sink-v2-test.sh
- e2e_test/iceberg/main.py
- e2e_test/iceberg/test_case/append_only_with_checkpoint_interval.slt
- e2e_test/iceberg/test_case/append_only_with_checkpoint_interval.toml
- src/connector/src/lib.rs
- src/connector/src/sink/iceberg/log_sink.rs
- src/connector/src/sink/iceberg/mod.rs
- src/connector/with_options_sink.yaml
> feat: decouple iceberg commit from risingwave commit

- Cargo.lock
- Cargo.toml
- e2e_test/udf/rust_udf.slt
- src/frontend/src/handler/create_function.rs
This PR resolves #16125. Previously the stdio of WASM UDF container is inherited from the parent process (i.e. RisingWave), causing the panic messages to be printed in the RisingWave log but not included in the error message. We change this behavior in arrow-udf-wasm v0.2.1 ([code](https://github.com/risingwavelabs/arrow-udf/commit/cbd0dc34c8bccb572c0be3c6398e5d891918b202)). Now stdio is no longer inherited. Instead, we use in-memory files to collect stdout and stderr of user functions. These information will be included as context of error when user function exits abnormally.
```sql
dev=> create function panic() …
```
> feat(udf): show panic message in Rust UDF

- Cargo.lock
- src/common/src/config.rs
- src/compute/src/memory/config.rs
- src/storage/src/hummock/block_cache.rs
- src/storage/src/hummock/sstable_store.rs
https://github.com/MrCroxx/foyer/pull/303#issuecomment-2041324998
The s3fifo eviction policy (Without ghost queue, maybe just fifo with reinsertion?) shows a good hit ratio among others. Let's try it with RW.
</details>
> feat(storage): support s3fifo for block cache

- src/connector/src/source/base.rs
- src/stream/src/executor/source/fs_source_executor.rs
- src/stream/src/executor/source/state_table_handler.rs
`SplitImpl::into_fs` and `SplitImpl::as_fs` are only used by `fs_source_executor` which seems to be deprecated. Also as we derived `EnumAsInner` for `SplitImpl`, the two methods are unnecessary even not deprecated.
</details>
> refactor(source): remove `into_fs` and `as_fs` methods from `SplitImpl`

- Cargo.lock
- Cargo.toml
- src/common/common_service/Cargo.toml
- src/common/common_service/src/metrics_manager.rs
- src/meta/Cargo.toml
- src/meta/dashboard/Cargo.toml
- src/meta/dashboard/src/proxy.rs
`hyper::Server` is removed in `hyper v1` because it has [problems](https://arc.net/l/quote/yxmapqii).
We'd better switch to `axum` for high-level HTTP server.
Also remove `hyper v1` dep in `meta/dashboard` because it's only used for re-exporting interfaces from `http v1`, which is re-exported by `axum v0.7` as well.
Verified the functionality locally. …
> refactor(metrics): replace hyper server implementation with axum

- Cargo.lock
> fix: fix s3fifo panics by bump foyer-memory

- ci/workflows/pull-request.yml
- e2e_test/ddl/index.slt
- e2e_test/streaming/basic.slt
- e2e_test/streaming/bug_fixes/mv_on_singleton_mv_4153.slt
- e2e_test/streaming/demo/ecommerce.slt
- e2e_test/streaming/demo/metric_analysis.slt
- e2e_test/streaming/natural_and_cross_join.slt
- e2e_test/streaming/non_strict_mode.slt
- e2e_test/streaming/rate_limit/basic.slt
- e2e_test/streaming/time_window.slt
- e2e_test/streaming/time_window_join.slt
- src/tests/simulation/src/client.rs
- src/tests/simulation/src/slt.rs
Enabling `RW_IMPLICIT_FLUSH` at the beginning of each session in recovery test is no longer required, since we have retained this setting after restart.
Previously we might kill the cluster in all commands except for some on the whitelist. Even a `comment` record could trigger a kill. (cc @xxchan 😄) This is unnecessary and will cause unexpected kill between `insert` and `flush`. So after discussion with @yezizp2012, we decide not to kill by default, and only enable killing in specific `create` and `drop` statements. This will make recovery test more precise and efficient. …
> fix(test): remove auto setting implicit flush from recovery test

- ci/scripts/e2e-deltalake-sink-rust-test.sh
- e2e_test/sink/deltalake_rust_sink.slt
- src/common/src/array/arrow/arrow_deltalake.rs
- src/common/src/array/arrow/arrow_impl.rs
> fix: decimal convert in deltalake

- integration_tests/snowflake-sink/README.md
- integration_tests/snowflake-sink/create_mv.sql
- integration_tests/snowflake-sink/create_sink.sql
- integration_tests/snowflake-sink/create_source.sql
- integration_tests/snowflake-sink/snowflake_prep.sql
- src/connector/src/sink/snowflake.rs
as titled.
related: #15429, https://github.com/risingwavelabs/risingwave/pull/15429#issuecomment-2046252624.
official documentation for snowflake sink could refer to this pr.
</details>
> feat(snowflake-sink): add example use case & detailed spec; fix a subtle problem regarding `file_suffix`

- src/storage/src/hummock/iterator/forward_user.rs
- src/storage/src/hummock/iterator/mod.rs
- src/storage/src/storage_failpoints/test_iterator.rs
Reverts risingwavelabs/risingwave#16027
Revert due to performance issue. Some key bound comparisons can be avoided.
Resolves #16243 hopefully.
> fix: Revert "refactor(storage): extract logic of key bounded iterator"

- src/ctl/src/cmd_impl/debug.rs
- src/ctl/src/cmd_impl/debug/fix_table_fragments.rs
- src/ctl/src/lib.rs
Background: we found that in the environment of a certain customer, when the `create sink into table` statement failed unexpectedly, the deleted fragment information still remained in the streaming graph of the downstream table, which caused cluster recovery to fail. They should be cleaned by kernel automatically but not. The root cause has not been identified yet. This PR adds a fix script to solve this problem. The user's environment has been fixed, and the root cause is still being investigated.
Usage:
```
./risedev ctl debug fix-dirty-upstreams --table-d 1 --dirty-fragment-ids 1
``` …
> feat(rise-ctl): add fix dirty upstream fragment ids for streaming job

- Cargo.lock
- src/batch/src/error.rs
- src/batch/src/execution/grpc_exchange.rs
- src/common/common_service/src/observer_manager.rs
- src/error/src/tonic.rs
- src/frontend/src/scheduler/distributed/stage.rs
- src/frontend/src/scheduler/error.rs
- src/rpc_client/Cargo.toml
- src/rpc_client/src/compactor_client.rs
- src/rpc_client/src/compute_client.rs
- src/rpc_client/src/connector_client.rs
- src/rpc_client/src/error.rs
- src/rpc_client/src/lib.rs
- src/rpc_client/src/meta_client.rs
- src/rpc_client/src/sink_coordinate_client.rs
- src/rpc_client/src/stream_client.rs
- src/stream/src/executor/exchange/input.rs
In #13282, we introduced `ServerError` to be encoded inside the gRPC (HTTP) response and passed through the wire, so that the client could gain more information about the error occurred on the server. The most significant part is the `service_name`, so that we can know the target of the failing gRPC request.
However, [`tonic::Status`] is used for both client and server side. If there's something wrong with the server side and the error is directly created on the client side, the approach above is not applicable. In this case, the caller should set a "client side" service name to provide better error message. This is …
> feat(error): provide service name on the client side of gRPC

- e2e_test/source/basic/handling_mode.slt
- scripts/source/test_data/json_timestamptz_handling_mode.1
- src/connector/benches/parser.rs
- src/connector/src/parser/debezium/debezium_parser.rs
- src/connector/src/parser/debezium/simd_json_parser.rs
- src/connector/src/parser/json_parser.rs
- src/connector/src/parser/maxwell/simd_json_parser.rs
- src/connector/src/parser/mod.rs
- src/connector/src/parser/plain_parser.rs
- src/connector/src/parser/unified/json.rs
- src/connector/src/schema/mod.rs
- src/connector/src/source/datagen/source/generator.rs
- src/frontend/src/handler/create_source.rs
- src/stream/src/executor/backfill/cdc/cdc_backfill.rs
Similar to sink, we allow specifying timestamptz number units:
* `micro`
* `milli`
* `guess_number_unit`: This has been the default, but limits the range to `[1973-03-03 09:46:40, 5138-11-16 09:46:40)`
* `utc_string`: This format is least ambiguous and can mostly be inferred correctly without the need to be specified.
* `utc_without_suffix`: This allows the user to acknowledge naive timestamp is in UTC rather than local time.
Note the corresponding `format` has to be one of `plain | upsert | debezium`. The following `format`s do NOT accept this option as of now:
* `debezium_mongo`
* `canal`
* `maxwell` …
> feat(source): `encode json` option `timestamptz.handling.mode`

- java/connector-node/risingwave-connector-service/src/main/resources/debezium.properties
According to Debeizum docs,
- `adaptive_time_microseconds` or `adaptive`: using either millisecond, microsecond, or nanosecond precision values based on the database column’s type.
- `connect` always represents time and timestamp values using Kafka Connect’s built-in representations for Time, Date, and Timestamp, which use millisecond precision regardless of the database columns' precision.
Our implementation simply inherits the implementation of [Kafka Connect's JsonConverter](https://github.com/a0x8o/kafka/blob/master/connect/json/src/main/java/org/apache/kafka/connect/json/JsonConverter.java) …
> fix(direct cdc): use `time.precision.mode=connect`

- proto/meta.proto
- src/frontend/src/handler/mod.rs
- src/frontend/src/handler/recover.rs
- src/frontend/src/meta_client.rs
- src/frontend/src/test_utils.rs
- src/meta/service/src/stream_service.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/error.rs
- src/meta/src/manager/notification.rs
- src/rpc_client/src/meta_client.rs
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/src/keywords.rs
- src/sqlparser/src/parser.rs
- src/tests/simulation/tests/integration_tests/backfill_tests.rs
- src/utils/pgwire/src/pg_response.rs
Closes https://github.com/risingwavelabs/risingwave/issues/14700
The current shortcoming of this approach is that while recovery is triggered, the command does not wait for recovery to complete, it operates in an async way. Welcome any ideas for improvement. If not we can improve it later.
Path of recover command:
```
Frontend -> Meta Client -> Stream Manager -> Notification Service -> Barrier Manager -> trigger recovery
```
The user can use the command: `RECOVER` to trigger an adhoc `recovery`. This can be used in cases where barrier latency is high, and we want to force a recovery to kick-in, so commands like `cancel, …
> feat(frontend, meta): support `RECOVER` command to trigger recovery

- src/meta/src/hummock/manager/checkpoint.rs
- src/meta/src/hummock/manager/gc.rs
- src/meta/src/hummock/manager/mod.rs
- src/meta/src/hummock/manager/tests.rs
- src/meta/src/hummock/vacuum.rs
- src/meta/src/manager/env.rs
- src/storage/backup/src/lib.rs
- src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
Previously in full gc, in the `extend_objects_to_delete_from_scan` method, we marked the sst objects in the latest version plus the `gc_object_ids` of hummock version delta as tracked object ids, so that the gc will not remove these sst objects that are potentially used by some pinned version. 
However, hummock version delta will be truncated at hummock version checkpoint. Therefore, we only track the sst objects in the versions between the checkpoint version and the latest version, and the versions between the min pinned version and the checkpoint version will not be tracked, and we may potentially remove some sst …
> fix(meta): fix potentially removing sst objects between min pinned and checkpoint version

- src/connector/src/source/cdc/external/postgres.rs
A quick solution to https://github.com/risingwavelabs/risingwave/issues/16316
</details>
> fix(postgres-cdc): disable certificate verification for `prefer` and `require`

- src/meta/src/rpc/metrics.rs
Reset metrics to clean the stale labels e.g. invalid lease ids.
Closes #15869
</details>
> fix: stale metrics of meta leader election

- e2e_test/backfill/sink/create_sink.slt
- e2e_test/streaming/rate_limit/snapshot_amplification.slt
- e2e_test/streaming/rate_limit/upstream_amplification.slt
- src/connector/src/sink/catalog/desc.rs
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/progress.rs
- src/meta/src/manager/streaming_job.rs
- src/meta/src/stream/stream_manager.rs
- src/tests/simulation/tests/integration_tests/recovery/background_ddl.rs
Part of #15587 
1. Change sink to block by default again, until backfill completes.
2. If background ddl set, then we let create sink immediately succeed.
This PR contains user-facing-changes to the behaviour of sink creation.
After this PR, we will block until backfill completes.
Before this PR, we will immediately let sink finish creating, once first barrier completes. After this PR, if this is the desired behaviour, set `BACKGROUND_DDL=true`.
</details>
> feat(meta): make blocking sink default + support background sink

- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/rpc/ddl_controller_v2.rs
- src/tests/simulation/src/slt.rs
If we return at the same time as background MV, at that point in time, the sink's barrier may not be collected yet.
Proper long term fix is to unify sink and mv creation paths.
</details>
> fix(meta): only return for background sink once initial barrier collected

- Cargo.lock
- Cargo.toml
- src/frontend/src/error.rs
- src/meta/src/error.rs
- src/object_store/src/object/error.rs
- src/storage/src/error.rs
- src/storage/src/hummock/error.rs
- src/stream/src/error.rs
- src/stream/src/executor/error.rs
Notable changes:
- https://docs.rs/thiserror-ext/0.1.2/thiserror_ext/derive.ReportDebug.html
- https://github.com/risingwavelabs/thiserror-ext/pull/6 for #16362
</details>
> chore: bump `thiserror-ext` to v0.1

- src/batch/src/executor/sys_row_seq_scan.rs
- src/common/src/catalog/mod.rs
- src/frontend/macro/src/lib.rs
- src/frontend/src/catalog/system_catalog/mod.rs
System catalog table could be large. Currently we return the entire table as a single chunk. It may lead to very large arrays and even panics in jsonb array. This PR makes it return a stream of chunks.
> fix(frontend): split chunks in system catalog

- Makefile.toml
- ci/scripts/integration-tests.sh
- src/utils/runtime/src/logger.rs
close https://github.com/risingwavelabs/risingwave/issues/14539
</details>
> chore: disable hyper hyper::client::connect::http by default

- e2e_test/source_inline/kafka/consumer_group.slt
- src/connector/src/source/base.rs
- src/connector/src/source/kafka/mod.rs
- src/connector/src/source/kafka/source/reader.rs
- src/connector/with_options_source.yaml
We use `assign` to manually assign topics and partitions to Kafka consumers, instead of `subscribe`. In this case, consumer group related features are not used at all.
https://github.com/risingwavelabs/risingwave/blob/65440fb67754a5c8a47eec4a2c4a7dfcef1be75e/src/connector/src/source/kafka/source/reader.rs#L115
- This change is **safe**: There will be no conflicts between different actors in the same group. 
- (**most importantly**) When they read data, the committed offsets in the group are not used at all. (Unless using group offset on startup. For existing sources, stored offsets will be used)
- Note that even if we …
> feat(source): use fragment id only as Kafka consumer group id

- src/frontend/src/optimizer/logical_optimization.rs
- src/frontend/src/optimizer/mod.rs
- src/frontend/src/optimizer/plan_node/batch_iceberg_scan.rs
- src/frontend/src/optimizer/plan_node/logical_iceberg_scan.rs
- src/frontend/src/optimizer/plan_node/logical_source.rs
- src/frontend/src/optimizer/plan_node/mod.rs
- src/frontend/src/optimizer/rule/mod.rs
- src/frontend/src/optimizer/rule/source_to_iceberg_scan_rule.rs
- src/frontend/src/scheduler/distributed/stage.rs
- src/frontend/src/scheduler/local.rs
- src/frontend/src/scheduler/plan_fragmenter.rs
- https://github.com/risingwavelabs/risingwave/issues/16354
- Add logical and batch iceberg scan operators so that we can support column pruning and predicate push-down for iceberg in the future.
</details>
> feat(optimizer): add logical and batch iceberg scan operator

- src/meta/src/hummock/manager/compaction.rs
- src/meta/src/hummock/manager/compaction_group_manager.rs
- src/meta/src/hummock/manager/gc.rs
- src/meta/src/hummock/manager/mod.rs
- src/meta/src/hummock/manager/tests.rs
- src/meta/src/hummock/metrics_utils.rs
- src/meta/src/hummock/test_utils.rs
- src/meta/src/rpc/metrics.rs
- src/storage/hummock_sdk/src/compact.rs
- src/storage/src/hummock/compactor/compactor_runner.rs
cherry-pick #15523. Though this is a feat, it actually fixes the meta event loop starvation issue when there are excessive trivial move tasks generated. Therefore, we should pick it to 1.8.
</details>
> feat(cherry-pick): batch get_compact_task/apply_compact_task in once transaction (#15523)

- src/frontend/src/optimizer/plan_node/logical_iceberg_scan.rs
- Related issue https://github.com/risingwavelabs/risingwave/issues/14742
- Support column pruning for iceberg source
</details>
> feat(batch,optimizer): support column pruning for iceberg source

- src/stream/src/error.rs
- src/stream/src/executor/error.rs
- src/stream/src/executor/exchange/error.rs
- src/stream/src/executor/exchange/input.rs
- src/stream/src/executor/exchange/mod.rs
- src/stream/src/executor/exchange/output.rs
- src/stream/src/executor/merge.rs
- src/stream/src/task/barrier_manager.rs
An actor will exit when an error occurs. Subsequently, all upstream or downstream actors that are connected with the failed actor will exit as well, since the exchange channel will be closed.
Therefore, we often see a flood of `ERROR` lines in the log saying that multiple actors have exited, where the backtrace can be really verbose and prevent us from identifying the root cause in a glance.
Since the backtrace for "exchange channel closed" is insignificant, this PR now prevents printing it by providing a fake `Disabled` backtrace when requested. This could make the error log …
> refactor(streaming): do not print backtrace for exchange channel closed error

- src/tests/sqlsmith/src/sql_gen/types.rs
As per title. Disabled functions are all tracked here: https://github.com/risingwavelabs/risingwave/issues/16293
</details>
> chore(sqlsmith): ban `stddev_samp`, `var_samp` since they use `sqrt`

- Makefile.toml
It was broken in a refactor: https://github.com/risingwavelabs/risingwave/pull/16152/files.
The build will always default to `debug` path. So we should also use `debug` path to launch it.
</details>
> fix(risedev): use `debug` path for `risedev-dev`

- e2e_test/error_ui/simple/recovery.slt
Supplement of #16397.
- Increase the delay before checking the recovery event. Hope this can resolve [recent CI failure](https://buildkite.com/risingwavelabs/main-cron/builds/2394#018f016e-44f0-445c-bdf9-9163b1760449/3804-3898).
- Show error message in the query result (instead of comparing them then getting `t` or `f`) to provide better observability. …
> test: refine root cause identification test of recovery

- src/cmd_all/src/standalone.rs
- src/compute/src/lib.rs
- src/compute/src/memory/config.rs
- src/compute/src/server.rs
Related #16130
Prior to this PR, reserved memory for compute node is hardcoded to 30% * total available memory, which may be too much under certain workload and machine set-up. This PR adds a compute node opt for user to configure the reserved memory bytes explicitly, with the default behavior unchanged.
`reserved_memory_bytes` startup opt and `RW_RESERVED_MEMORY_BYTES` env are introduced for compute node to override the reserved memory configuration.
The default setup remains unchanged, which is compute node using 30% of its total memory as the reserved memory.
> feat(memory): add reserved_memory_bytes opt

- src/expr/impl/src/scalar/jsonb_record.rs
- src/frontend/planner_test/tests/testdata/input/expr.yaml
- src/frontend/planner_test/tests/testdata/output/expr.yaml
- src/frontend/planner_test/tests/testdata/output/subquery_expr.yaml
- src/frontend/planner_test/tests/testdata/output/with_ordinality.yaml
- src/frontend/src/planner/relation.rs
A panic mentioned in `jsonb_populate_record` #13421 but actually affects all scalar functions returning structs:
```
dev=> select * from jsonb_populate_record(
null::struct<a int, b int>,
'{"a": 1, "b": 2}' 
);
ERROR:  Panicked when processing: insert at index 1 exceeds fixbitset size 1
```
On the binder side, it is already flattened: #10317 `binder/relation/table_function.rs`.
When planned into a `LogicalTableFunction`, it is also flattened: #8644 `LogicalTableFunction::new`.
But when planned into a `LogicalValues`, it is single column and mismatching the binder's schema. …
> fix(planner): from-scalar-function shall also flatten struct fields similar to from-table-function

- docker/Dockerfile
- src/cmd_all/src/standalone.rs
- src/frontend/src/lib.rs
1. `single_node` should be docker file entrypoint
2. frontend should listen on `0.0.0.0` rather than `127.0.0.1`, otherwise psql may not be able to connect to single node running in docker.
</details>
> fix(docker): use `single_node` as dockerfile entrypoint

- src/connector/src/sink/kafka.rs
- src/connector/with_options_sink.yaml
Requested by user.
https://kafka.apache.org/documentation/#producerconfigs_acks
>This field indicates the number of acknowledgements the leader broker must receive from ISR brokers before responding to the request: 0=Broker does not send any response/ack to client, -1 or all=Broker will block until message is committed by all in sync replicas (ISRs). If there are less than min.insync.replicas (broker configuration) in the ISR set the produce request will fail.
Default value `-1`
rdkafka parameter name: `request.required.acks`
rw parameter name `properties.request.required.acks` …
> feat(connector): add request.required.acks for kafka connector producer

- e2e_test/source/cdc/cdc.validate.postgres.slt
- src/connector/src/source/cdc/mod.rs
- src/rpc_client/src/connector_client.rs
The generated column is produced in risingwave and it will not be accessed from the external connector. So during the validation, the columns should be ignore.
</details>
> feat: do not valid rw's generated column on source

- lints/ui/format_error.rs
- src/frontend/src/error.rs
- src/frontend/src/handler/query.rs
- src/frontend/src/scheduler/distributed/query_manager.rs
- src/frontend/src/scheduler/local.rs
- src/frontend/src/session/cursor_manager.rs
Background:
@arkbriar encountered such an error message when running e2e tests of operators, where the cause (source) for the creation failure was missing.
```
Caused by:
internal error: failed to create RPC client to e2e-compute-0.e2e-compute:5688
``` 
----
Following the [guidelines](https://www.notion.so/risingwave-labs/A-Guide-to-Error-Handling-that-Just-Works-Part-I-e108f8d0845b4bddaa0e5843791a8cac?pvs=4#571b6922de894ed78d1a6b00df0f3de4), we should not directly format an error type.
This should be covered by the lints. Due to limited knowledge of the compiler, however, I don't find …
> fix(error): do not directly format `BoxedError`

- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/DbzConnectorConfig.java
- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/MySqlValidator.java
- java/connector-node/risingwave-connector-service/src/main/resources/mysql.properties
- java/connector-node/risingwave-sink-iceberg/pom.xml
- java/connector-node/risingwave-sink-jdbc/pom.xml
- java/connector-node/risingwave-source-cdc/pom.xml
- java/pom.xml
- src/connector/src/source/cdc/external/mod.rs
- src/connector/src/source/cdc/external/postgres.rs
- Add `ssl.mode` to allow user configure the ssl behavior ([ref](https://dev.mysql.com/doc/connector-j/en/connector-j-connp-props-security.html#cj-conn-prop_useSSL))
related: #15690 
Updated by @neverchanje 
This PR involves a change on Postgres connector. It rename the values of [`ssl.mode`](https://docs.risingwave.com/docs/dev/ingest-from-postgres-cdc/) from "disable, prefer, and require" to "disabled, preferred, and required".
On the other hand, the `ssl.mode` option is also supported for the MySQL connector, enabling a SSL/TLS encrypted connection to the upstream MySQL. …
> feat(mysql-cdc): support `ssl.mode` to allow configure the ssl behavior

- src/connector/src/schema/avro.rs
- src/connector/src/sink/formatter/mod.rs
Split the monolithic `SinkFormatterImpl::new` into extensible `EncoderBuild` & `FormatterBuild` pieces. The dispatcher logic in `SinkFormatterImpl::new` is now simply matching from `(format, encode)` into a variant of the `SinkFormatterImpl` enum.
This is NOT a purely equivalent refactor. By reducing the repetition, it also:
* supported `schemas.enable` option for `format plain encode json`, which was only available for `format upsert encode json` [#12113](https://github.com/risingwavelabs/risingwave/pull/12113).
* fixed partition skew problem when `encode template` is used with `format plain` without key. The `encode …
> refactor(sink): DRY `SinkFormatterImpl::new`

- docs/developer-guide.md
_INFO_ is an invalid markdown alert extension. Replacing it with _TIP_.
Valid alerts are _Note_, _Tip_, _Caution_, _Warning_, _Important_ 
**Before**
**After**
> doc: remove invalid markdown alert

- Cargo.lock
- src/connector/src/source/filesystem/opendal_source/s3_source.rs
This PR 
- remove `enable_virtual_host_style` so that both `virtual_path_style: s3.endpoint_url = 'http://127.0.0.1:9301'` and `force_path_style: s3.endpoint_url = 'http://<bucket>.127.0.0.1:9301'` can work well with minio. (Before this pr neither method works for minio. )
- fix/update `backon`, refer to https://github.com/Xuanwo/backon/pull/68
</details>
> fix(source): make s3 source compatible with minio

- src/frontend/src/handler/show.rs
Close #16564 . After this PR, `show cluster` will return rows as follows:
```sql
dev=> show cluster;
Id |      Addr      |           Type           |  State  | Parallel Units | Is Streaming | Is Serving | Is Unschedulable |        Started At
----+----------------+--------------------------+---------+----------------+--------------+------------+------------------+---------------------------
0 | 127.0.0.1:5690 | WORKER_TYPE_META         | RUNNING |                |              |            |                  | 2024-05-07 07:57:18+00:00
1 | 127.0.0.1:5688 | WORKER_TYPE_COMPUTE_NODE | RUNNING | 0, 1, 2, 3     | t …
```
> chore: unify show cluster result with system catalog

- e2e_test/batch/catalog/pg_settings.slt.part
- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/DbzConnectorConfig.java
- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/DbzSourceUtils.java
- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzCdcEngineRunner.java
- java/connector-node/risingwave-source-test/src/test/java/com/risingwave/connector/source/SourceTestClient.java
- src/common/src/session_config/mod.rs
- src/connector/src/source/cdc/mod.rs
- src/frontend/src/handler/create_source.rs
- src/jni_core/src/jvm_runtime.rs
In our production environment, we found one case that the upstream system's table schema was too complicated so that takes long time to fetch. The time required exceeded the preset timeout threshold in https://github.com/risingwavelabs/risingwave/pull/14406 and leads to the failure of source creation. In this PR, we add a runtime parameter to control it. If a user encounter a error like this when creating cdc source:
```
RROR:  Failed to run the query
2: get error from control stream: worker node {}, gRPC request …
```
> feat(cdc): add a parameter to control timeout of cdc source waiting time

- src/connector/Cargo.toml
- src/connector/src/sink/google_pubsub.rs
- src/connector/src/sink/mod.rs
- src/connector/with_options_sink.yaml
- src/frontend/src/handler/create_sink.rs
Add new sink Goolge Pub/Sub with only support `Plain => Json` in append-only mode.
e.g.
```sql
CREATE TABLE IF NOT EXISTS personnel (id integer, name varchar);
CREATE SINK ggps_sink
FROM
personnel
WITH
(
connector = 'google_pubsub',
endpoint = 'localhost:8900',
emulator_host = 'localhost:8900',
project_id = 'demo',
topic = 'test',
type = 'append-only',
) FORMAT PLAIN ENCODE JSON (
force_append_only='true',
);
```
Support new sink `google_pubsub`.
</details>
> feat(sink): add Google Pub/Sub support

- src/stream/src/error.rs
- src/stream/src/executor/error.rs
- src/stream/src/task/barrier_manager.rs
...since it's also likely to be caused by actor exit.
Also
- Expand all arms of `match`.
- Rename `Internal` to `Uncategorized` since all `bail` will go this path. It may not be "internal" at all.
- Assign the same score to `Internal` as other variants.
</details>
> fix(streaming): assign lower score to `BarrierSend` error in root cause discovery

- e2e_test/batch/catalog/has_privilege.slt.part
- proto/user.proto
- src/common/src/acl/mod.rs
- src/frontend/src/handler/handle_privilege.rs
- src/frontend/src/user/user_catalog.rs
- src/frontend/src/user/user_privilege.rs
- src/meta/service/src/user_service.rs
- src/meta/src/controller/catalog.rs
- src/meta/src/controller/utils.rs
- src/meta/src/manager/catalog/database.rs
- src/meta/src/manager/catalog/mod.rs
Allow `grant/revoke` privileges on views.
</details>
> fix(catalog): grant view when grant table

- e2e_test/source_inline/kafka/shared_source.slt
- src/connector/src/source/kafka/enumerator/client.rs
- src/connector/src/source/kafka/source/reader.rs
- src/connector/src/source/kafka/split.rs
- src/stream/src/executor/source/source_executor.rs
https://github.com/risingwavelabs/risingwave/issues/16576#issuecomment-2095571890
mentioned by Eric, this is also his original idea in his RFC
</details>
> feat(source): let shared SourceExecutor start from latest instead of specified offset

- src/connector/src/connector_common/common.rs
- src/connector/src/with_options_test.rs
- src/connector/with_options_sink.yaml
- src/connector/with_options_source.yaml
As mentioned in https://github.com/risingwavelabs/risingwave/pull/16625#discussion_r1594200891, the original connector field name can be ambiguous in non AWS context. 
In pulsar, bigquery and msk documentation, those field name should be changed:
external_id -> aws.credentials.role.external_id
endpoint_url -> aws.endpoint_url
access_key -> aws.credentials.access_key_id
secret_key ->aws.credentials.secret_access_key
session_token -> aws.credentials.session_token
profile-> aws.region.profile
arn -> aws.credentials.role.arn
If this PR includes changes that directly affect users or other significant modifications relevant …
> refactor(connector): add proper prefix for aws related properties for connector 

- ci/scripts/build-simulation.sh
- ci/scripts/build.sh
Upload build timings on CI to help analysis how to optimize build time.
</details>
> feat(ci): upload timings

- e2e_test/sink/remote/jdbc.check.pg.slt
- e2e_test/sink/remote/jdbc.load.slt
- e2e_test/sink/remote/pg_create_table.sql
- java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java
- java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/jdbc/JdbcDialect.java
- java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/jdbc/MySqlDialect.java
- java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/jdbc/PostgresDialect.java
As title.
close: https://github.com/risingwavelabs/risingwave/issues/16739
</details>
> fix(jdbc-sink): fix primary key bindings for the DELETE statement

- ci/workflows/pull-request.yml
- src/stream/src/executor/hash_join.rs
- src/stream/src/executor/join/hash_join.rs
Adapted from @yuhao-su's commit 4132beeaad6d42cce606807bfe2abaa20d239ed7, so we can have a general mechanism to debug this case.
It can be enabled with `RUST_LOG="hash_join_amplification=debug"`
</details>
> feat(stream): add debug logs for join key with high amplification

- backwards-compat-tests/scripts/run_local.sh
- ci/scripts/backwards-compat-test.sh
> fix: missing specified meta backend for backwards compat test config

- e2e_test/ddl/schema.slt
- src/frontend/planner_test/src/lib.rs
- src/frontend/src/handler/create_schema.rs
- src/frontend/src/handler/mod.rs
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/src/parser.rs
- src/sqlparser/tests/sqlparser_postgres.rs
- src/sqlparser/tests/testdata/create.yaml
Close #15680 .
Support syntax as follows:
```
CREATE SCHEMA [ IF NOT EXISTS ] schema_name [ AUTHORIZATION user_name ]
CREATE SCHEMA [ IF NOT EXISTS ] AUTHORIZATION user_name
```
Examples:
```sql
dev=> create schema if not exists authorization joe;
CREATE_SCHEMA
dev=> create schema if not exists new_schema authorization joe;
CREATE_SCHEMA
dev=> show schemas;
Name
--------------------
information_schema
public
pg_catalog
joe
new_schema
rw_catalog
(6 rows)
``` …
> feat: support authorization syntax for CREATE SCHEMA and omitted schema name

- Cargo.lock
- src/expr/core/Cargo.toml
- src/expr/core/src/error.rs
- src/expr/core/src/lib.rs
- src/expr/impl/src/scalar/encrypt.rs
- src/expr/macro/src/gen.rs
This PR allows any error type returned by functions (as a simpler solution of #14159).
One of the benefit is that the openssl dependency can be removed from `expr_core`, speeding up the build slightly.
</details>
> feat(expr): allow any Error returned by functions

- src/connector/src/sink/snowflake.rs
- src/object_store/src/object/mem.rs
- src/object_store/src/object/mod.rs
- src/object_store/src/object/opendal_engine/opendal_object_store.rs
- src/object_store/src/object/s3.rs
- src/object_store/src/object/sim/mod.rs
- src/storage/src/hummock/sstable_store.rs
Removed `#[async_trait]` on `StreamingUploader` trait, and avoid using box dyn on streaming uploader, so that each call on `write_bytes` won't create a boxed future. `StreamingUploader` now becomes an associated type of `ObjectStore`. An `StreamingUploaderImpl` enum will be used to manually dispatch to different variant.
Refined the macro used in object store trait. Previously, we have many macros that lists all variants of object store. With this PR, we only need to declare the list of all variants in a single macro `for_all_object_store`, and all other macros will call `for_all_object_store` to get the list of object …
> refactor(object-store): remove async_trait macro on StreamingUploader and refine object store macro

- java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java
When building a JDBC sinker, `getTransactionIsolation` is call after `autocommit` was set to `false`. It will result in an idle transaction until the first sinked data was committed.
</details>
> fix(connector): idle transaction `SHOW TRANSACTION ISOLATION LEVEL` when no sinked data

- java/connector-node/risingwave-connector-service/src/main/resources/debezium.properties
This reverts commit 5fb6f698d7bcee376e420bd0f35d46a437be80d6.
PR #16119 will truncate PG `timestamp` precision from microseconds to milliseconds, which is unexpected. We should not truncate the value if RW data type can fully store the upstream value.
A better solution is suggested in https://github.com/risingwavelabs/risingwave/issues/16097#issuecomment-2033945986
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have …
> fix(cdc): Revert "fix(direct cdc): use `time.precision.mode=connect` (#16119)"

- src/utils/pgwire/src/pg_server.rs
- Resolve https://github.com/risingwavelabs/risingwave/issues/16837
</details>
> fix(frontend): use dedicated runtime to accept connection

- src/risedevtool/common.toml
- src/risedevtool/grafana.toml
Grafana now releases binary for `darwin-arm64`. Let's directly use it instead of relying on Rosetta 2 to run `amd64` binary.
This also fixes the problem that the previous implementation will download `linux-amd64` for `linux-arm64`. 🤡
</details>
> fix(risedev): use correct arch when downloading Grafana

- src/frontend/src/catalog/system_catalog/pg_catalog/pg_tables.rs
Avoid the `rw_catalog.rw_*` tables in the `pg_catalog.pg_tables`. 
The reason for this is that metabase will list all the normal tables by filtering out `pg_catalog.pg_*` and `information schema.*` from the result of `pg_catalog.pg_tables` and check the privileges of these tables using `has_table_privileges`. `has_table_privilege` requires the table's `oid` to check privileges. Some of `rw_catalog.rw_` have no `oid`, as a result, metabase will stuck at `syncing tables` stage due to the failure of `has_table_privilege` check. So to avoid this, I removed all the `rw_catalog.rw_*` tables from `pg_catalog.pg_tables`'s …
> chore(catalog): avoid rw_catalog in pg_tables

- src/meta/src/stream/scale.rs
Fragment 6144 has multiple downstream materialized views and it mixes no shuffle backfill with arrangement backfill. This causes the fragment to have multiple types of dispatchers (hash and no_shuffle). During the recovery phase, while propagating upstream no shuffle, we only check if the upstream is a no shuffle source. This inaccurately copies the downstream hash dispatcher's target scale plan to this fragment. This PR fixes the issue.
AKA
> A no_shuffle downstream of a no_shuffle upstream should be connected through a no_shuffle link.
> fix: Mixing arrangement backfill and no shuffle backfill can lead to scale failure.

- Cargo.lock
- src/sqlparser/Cargo.toml
- src/sqlparser/src/lib.rs
- src/sqlparser/src/parser.rs
- src/sqlparser/src/parser_v2/data_type.rs
- src/sqlparser/src/parser_v2/impl_.rs
- src/sqlparser/src/parser_v2/mod.rs
- src/sqlparser/src/parser_v2/number.rs
- src/sqlparser/tests/testdata/array.yaml
- src/sqlparser/tests/testdata/create.yaml
- src/sqlparser/tests/testdata/select.yaml
- src/sqlparser/tests/testdata/struct.yaml
Introducing a new parser with [winnow](https://github.com/winnow-rs/winnow).
This is the first version of the new parser, with only the datatype parsing. However, it's also the most complicated part of our Parser. Due to our wrong design previously, we use `<` and `>` to define struct type, then introduce a necessary state `angle_number` during parsing. Fortunately, the new framework handle it perfectly.
winnow-rs is a parser-combinator crate, and it's forked by me for a simple patch https://github.com/winnow-rs/winnow/pull/525.
**The new framework can progressively replace the original parser, see `Parser::parse_v2` …
> feat(parser): the 1st version of a new combinator style parser

- src/stream/src/executor/join/hash_join.rs
This PR converts some `panic`s related to join degree maintenance in HashJoin. Will resolve #16823.
</details>
> feat(consistency): tolerate bad join degree

- ci/docker-compose.yml
- ci/workflows/pull-request.yml
- e2e_test/source/basic/nosim_kafka.slt
- scripts/source/prepare_ci_kafka.sh
We already have redpanda, why another kafka?
related with https://github.com/risingwavelabs/risingwave/issues/16903
</details>
> ci: remove unnessary kafka & zookeeper

- src/stream/src/common/log_store_impl/kv_log_store/buffer.rs
- src/stream/src/common/log_store_impl/kv_log_store/mod.rs
- src/stream/src/common/log_store_impl/kv_log_store/reader.rs
Indirect cause of https://github.com/risingwavelabs/risingwave/issues/16984
In current code, truncate offset is only written when we are consuming newly added buffered data, which means that when we have a great number of historical data to consume, we won't be able to write the truncate offset before finishing consuming the historical data, and if recovery happens, we will start from the very beginning, which may makes the unconsumed data more and more and make the situation worse and worse.
In this PR, we fix the error by also writing the truncate offset when we are consuming historical data. In this way, the error …
> fix(log-store): write truncate offset when consuming persistented data

- e2e_test/source/cdc/cdc.share_stream.slt
- src/frontend/src/handler/create_table.rs
as title.
close https://github.com/risingwavelabs/risingwave/issues/17003
</details>
> fix(frontend): fix primary key check for cdc table

- src/stream/src/common/log_store_impl/kv_log_store/reader.rs
- src/stream/src/common/log_store_impl/kv_log_store/serde.rs
Resolve https://github.com/risingwavelabs/risingwave/issues/16984
In log store, we may have iters that consume a large number of historical data, which may exist for long time. The iter will keep pinning a hummock version, and causes stale sst unable to be reclaimed.
In this PR, we set a fixed 10 minutes timeout for the log store iter. On timeout, the iter will be rebuilt starting from the latest offset, so that we can iter on the same data from the original progress but  by with a newer version. In this way we can avoid pinning the hummock version for too long time. …
> fix(log-store): rebuild log store iter when exists for a timeout

- e2e_test/subscription/main.py
- src/frontend/src/handler/declare_cursor.rs
- src/frontend/src/optimizer/plan_node/generic/log_scan.rs
- src/frontend/src/session/cursor_manager.rs
- src/utils/pgwire/src/pg_field_descriptor.rs
In this pr
1. fix alter table, but cursor table schema dont change
2. support fetch n from cursor
3. fix fetch cursor's columns name(table_name.column_name => column_name)
</details>
> feat(frontend): support fetch n from subscription cursor

- .typos.toml
- scripts/source/schema_registry_producer.py
- src/connector/src/parser/avro/parser.rs
- src/connector/src/parser/avro/schema_resolver.rs
- src/connector/src/parser/debezium/avro_parser.rs
- src/connector/src/parser/json_parser.rs
- src/connector/src/parser/unified/avro.rs
> refactor: minor refactor on avro

- src/connector/benches/json_vs_plain_parser.rs
- src/connector/src/parser/json_parser.rs
- src/connector/src/parser/mod.rs
- src/connector/src/source/base.rs
Following up #16996, this PR removes `JsonParser` from production code. Close #16968.
- Refactor all unit tests in `json_parser.rs` to use `ByteStreamSourceParserImpl` to create a (plain) parser to cover the real path.
- Move `JsonParser` to the benchmark of `json_vs_plain_parser`.
</details>
> refactor(connector): remove `JsonParser` from production code

- Cargo.lock
- proto/expr.proto
- src/expr/core/src/codegen.rs
- src/expr/impl/Cargo.toml
- src/expr/impl/src/table_function/mod.rs
- src/expr/impl/src/table_function/pg_get_keywords.rs
- src/expr/macro/src/gen.rs
- src/frontend/src/binder/relation/table_function.rs
- src/frontend/src/catalog/system_catalog/pg_catalog/mod.rs
- src/frontend/src/catalog/system_catalog/pg_catalog/pg_keywords.rs
- src/sqlparser/src/keywords.rs
Signed-off-by: Runji Wang <wangrunji0408@163.com>I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).
resolve #17023
This PR implements `pg_get_keywords()` function and `pg_keywords` system catalog.
However, the implementation is not entirely correct. There are many rows in the output that have a different category than postgres. I don't fully understand how to map our reserved keyword tables to the category defined by PG. But if it's just to resolve the problem mentioned in #17023, maybe non-empty output is enough.
Support `pg_get_keywords()` function and `pg_keywords` system catalog.
> feat(expr): implement `pg_get_keywords()` and `pg_keywords`

- src/sqlparser/src/parser.rs
- src/sqlparser/src/parser_v2/compact.rs
- src/sqlparser/src/parser_v2/expr.rs
- src/sqlparser/src/parser_v2/mod.rs
* Introduce `ParseV1` as a compatible trait for parser v2
* Write `expr_case` as an example
</details>
> refactor(parser): introduce a compactible layer for parser v2 to call v1

- src/frontend/planner_test/tests/testdata/input/index_selection.yaml
- src/frontend/planner_test/tests/testdata/output/index_selection.yaml
- src/frontend/src/optimizer/plan_node/logical_scan.rs
- Resolve https://github.com/risingwavelabs/risingwave/issues/17038
- After we support index on expressions, we need to handle the case where the column is not in the `s2p_mapping`. 
</details>
> fix(optimizer): fix functional index selection

- src/utils/runtime/src/logger.rs
idea is from https://github.com/risingwavelabs/risingwave/issues/16905
But not support persisting config in risedev yet.
</details>
> feat: support enabling pretty log via env var

- src/stream/src/common/log_store_impl/kv_log_store/reader.rs
Fix https://github.com/risingwavelabs/risingwave/issues/17017
</details>
> fix: cherry-pick rebuild log store iter when exists for a timeout (#17009)

- proto/hummock.proto
- src/ctl/src/cmd_impl/hummock/compaction_group.rs
- src/ctl/src/lib.rs
- src/meta/src/hummock/manager/compaction_group_manager.rs
as title
related to https://github.com/risingwavelabs/risingwave/issues/16203
</details>
> feat(ctl): support mutable compression_algorithm

- src/connector/src/sink/kafka.rs
- src/connector/src/sink/remote.rs
- src/connector/src/source/kafka/mod.rs
- src/connector/src/source/reader/reader.rs
This PR is a quick fix. I went through all `tracing::` in connector crate, to find any potential ones.
1. `rdkafka::ClientConfig::conf_map` is not strong-typed. This PR simply removes it from log. We may leverage secure-string in the rdkafka lib in the future.
2. For `ConnectorProperties` and `SinkParam`, this PR again simply removes them from log. After SECRETS hopefully there's no more sensitive info in them. The reasons why I don't leverage secure-string now are
- changes like #14760 requires verbose serde implementation
- `SinkParam::properties` is not strong-typed. …
> fix(connector): don't log config/props that may contain sensitive information

- e2e_test/error_ui/simple/recovery.slt
- e2e_test/streaming/bug_fixes/issue_12474.slt
- src/batch/src/executor/project_set.rs
- src/expr/core/src/table_function/mod.rs
- src/stream/src/executor/project_set.rs
- src/stream/src/from_proto/project_set.rs
- src/stream/tests/integration_tests/project_set.rs
> fix(expr): evaluate scalar expr non-strictly in streaming

- src/connector/src/source/pulsar/source/reader.rs
Make pulsar initial subscription mode to [nondurable](https://pulsar.apache.org/docs/3.2.x/concepts-messaging/#what-is-a-subscription-mode) to avoid "Durable subscription with the same name already exists." error during recovery.
</details>
> fix: pulsar error during recovery

- src/batch/src/lib.rs
- src/batch/src/spill/spill_op.rs
- src/compute/src/server.rs
- src/frontend/src/session.rs
- Issue: https://github.com/risingwavelabs/risingwave/issues/16615
- In the event of a cluster crash during batch query spilling, there may be residual, uncleaned spill files. These files should be promptly cleaned up upon the restart of frontend and compute nodes.
</details>
> feat(batch): clean spill directory at the start

- e2e_test/streaming/bug_fixes/issue_11915.slt
- src/batch/src/executor/project_set.rs
- src/batch/src/executor/table_function.rs
- src/common/src/array/bytes_array.rs
- src/common/src/array/utf8_array.rs
- src/common/src/buffer/bitmap.rs
- src/expr/core/src/codegen.rs
- src/expr/core/src/table_function/mod.rs
- src/expr/impl/src/scalar/format.rs
- src/expr/impl/src/table_function/generate_series.rs
- src/expr/macro/src/gen.rs
- src/stream/src/executor/project_set.rs
- src/stream/src/from_proto/project_set.rs
- src/stream/tests/integration_tests/project_set.rs
Signed-off-by: Runji Wang <wangrunji0408@163.com>I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).
partially fix_ #11915 
Currently, when an error occurs in a table function call, the returned stream stops and the streaming actor will exit. This PR makes streaming tolerant to table function errors. When an error occurs, an error column will be appended to the returned chunk. (see the example in [arrow-udf](https://github.com/risingwavelabs/arrow-udf/tree/main/arrow-udf#fallible-functions)) The batch side will raise error immediately when seeing this column, while the streaming side will report errors and keep going. If some rows have been output when the error occurs, …
> fix(expr): don't panic on table function errors

- Cargo.toml
- src/common/src/types/cow.rs
- src/common/src/types/mod.rs
- src/connector/benches/json_vs_plain_parser.rs
- src/connector/benches/nexmark_integration.rs
- src/connector/codec/src/decoder/avro/mod.rs
- src/connector/codec/src/decoder/mod.rs
- src/connector/src/parser/common.rs
- src/connector/src/parser/mod.rs
- src/connector/src/parser/unified/json.rs
- src/connector/src/parser/unified/kv_event.rs
- src/connector/src/parser/unified/mod.rs
Add a new method named `access_cow` to `Access` trait, allowing implementors to return a borrowed `DatumRef`, to achieve zero-copy parsing.
Currently only `Varchar` field in `JSON` returns a borrowed `ScalarRef`. This improves the performance by ~11% in micro-benchmark `nexmark_integration`. Will adopt it more in following PRs.
</details>
> perf(connector): support zero-copy `access` during parsing

- Cargo.lock
- src/common/src/types/cow.rs
- src/connector/benches/json_vs_plain_parser.rs
- src/connector/codec/Cargo.toml
- src/connector/codec/src/decoder/avro/mod.rs
- src/connector/codec/src/decoder/mod.rs
- src/connector/src/parser/avro/parser.rs
- src/connector/src/parser/bytes_parser.rs
- src/connector/src/parser/debezium/avro_parser.rs
- src/connector/src/parser/debezium/simd_json_parser.rs
- src/connector/src/parser/json_parser.rs
- src/connector/src/parser/mod.rs
- src/connector/src/parser/plain_parser.rs
- src/connector/src/parser/protobuf/parser.rs
- src/connector/src/parser/unified/bytes.rs
- src/connector/src/parser/unified/debezium.rs
- src/connector/src/parser/unified/json.rs
- src/connector/src/parser/unified/kv_event.rs
- src/connector/src/parser/unified/maxwell.rs
- src/connector/src/parser/unified/mod.rs
- src/connector/src/parser/unified/protobuf.rs
- src/connector/src/parser/upsert_parser.rs
Follow-up of #17153.
- Adopt `access_cow` in all implementors of `Access`.
- Use `access_cow` everywhere if possible.
- Rename `access_cow` to `access` and make it the only method that need/can be implemented in the trait.
- Rename `access` to `access_owned` to implicitly show the intention of requiring an owned datum in the callsite. Make it an extension trait, so that it cannot be overridden.
- Some minor tweaks. …
> refactor(connector): migrate to zero-copy access implementation

- proto/expr.proto
- src/expr/impl/src/scalar/jsonb_set.rs
- src/expr/impl/src/scalar/mod.rs
- src/frontend/src/binder/expr/function.rs
- src/frontend/src/expr/pure.rs
- src/frontend/src/optimizer/plan_expr_visitor/strong.rs
- src/tests/regress/Cargo.toml
- src/tests/regress/data/sql/jsonb.sql
resolve #17103
The logic is similar to #13118 
Support `jsonb_set` function.
> feat(expr): add `jsonb_set` function

- Cargo.toml
- src/connector/benches/nexmark_integration.rs
Add a new benchmark function in `nexmark_integration.rs` that takes combined events as input, where each event is represented with a single composed struct field.
This covers the real path of our nexmark benchmark, as described in https://github.com/risingwavelabs/risingwave/pull/17153#discussion_r1630904806.
Here's a snapshot of the current performance (with LTO off):
```
parse_nexmark           time:   [19.251 ms 19.297 ms 19.348 ms]
parse_nexmark_with_tracing
time:   [19.268 ms 19.342 ms 19.426 ms]
parse_nexmark_struct_type
time:   [28.135 ms 28.340 ms 28.547 ms]
``` …
> test(connector): add benchmark for parsing combined (struct type) nexmark events

- src/common/src/types/cow.rs
- src/common/src/types/jsonb.rs
- src/connector/codec/src/decoder/avro/mod.rs
- src/connector/src/parser/protobuf/parser.rs
- src/connector/src/parser/unified/json.rs
- src/connector/src/parser/unified/protobuf.rs
Follow-up of #17165. Avoid allocation of `Datum` as much as possible for protobuf and avro parsing.
</details>
> refactor(connector): adopt zero-copy access for protobuf & avro parsing

- src/stream/src/executor/sink.rs
to make sure the optimization in  https://github.com/risingwavelabs/risingwave/pull/12250 is correct.
more context here.
https://github.com/risingwavelabs/risingwave/pull/17154#discussion_r1631077335
</details>
> fix(sink): do compaction in chunk for upsert sink

- src/frontend/src/optimizer/plan_node/stream_sink.rs
A user asked about the force append only semantics and I found the warning somehow misleading.
</details>
> chore(sink): improve force append only warning

- ci/workflows/main-cron.yml
- ci/workflows/pull-request.yml
- docs/developer-guide.md
Closes https://github.com/risingwavelabs/risingwave/issues/17182.
Improvements:
1. User has less tags to add now to trigger specific workflows. They no longer need to add labels for the dependent steps.
2. The tags are more straightforward `run-selected` is clearer than `skip-ci`.
See the developer guide for more info, or the labels in this PR.
</details>
> chore(ci): rework ci labels used to trigger workflows

- src/stream/src/executor/merge.rs
Might be the cause of #16914
1. `with_label_values` only call once instead of each time during `poll_next`.
2. when `metric_level` is lower than `debug`, the metric will not be recorded and there will be no overhead related to this metric at all.
</details>
> fix(metrics): reduce overhead of `merge_barrier_alignment_duration`

- src/storage/hummock_test/src/hummock_storage_tests.rs
- src/storage/hummock_test/src/state_store_tests.rs
- src/storage/src/hummock/event_handler/hummock_event_handler.rs
- src/storage/src/hummock/event_handler/mod.rs
- src/storage/src/hummock/event_handler/uploader.rs
- src/storage/src/hummock/store/hummock_storage.rs
- src/storage/src/hummock/store/local_hummock_storage.rs
- src/stream/src/executor/actor.rs
- src/stream/src/executor/backfill/arrangement_backfill.rs
- src/stream/src/executor/backfill/no_shuffle_backfill.rs
> feat(storage): avoid uploader depending on seal_epoch

- proto/hummock.proto
- src/common/src/config.rs
- src/ctl/src/cmd_impl/hummock/compaction_group.rs
- src/ctl/src/lib.rs
- src/meta/src/hummock/compaction/compaction_config.rs
- src/meta/src/hummock/compaction/picker/base_level_compaction_picker.rs
- src/meta/src/hummock/compaction/picker/compaction_task_validator.rs
- src/meta/src/hummock/compaction/picker/intra_compaction_picker.rs
- src/meta/src/hummock/compaction/picker/min_overlap_compaction_picker.rs
- src/meta/src/hummock/compaction/picker/mod.rs
- src/meta/src/hummock/compaction/picker/tier_compaction_picker.rs
- src/meta/src/hummock/manager/compaction_group_manager.rs
1. remove magic number MAX_COMPACT_LEVEL_COUNT
2. remove the overlapping file count limitation of MAX_COMPACT_LEVEL_COUNT. Because the number of SSTs in each overlapping level may exceed 1, it is inaccurate to use level count to limit
- related https://github.com/risingwavelabs/risingwave/issues/16494
</details>
> feat(storage): remove magic number MAX_COMPACT_LEVEL_COUNT

- proto/backup_service.proto
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_meta_snapshot.rs
- src/meta/src/backup_restore/meta_snapshot_builder_v2.rs
- src/meta/src/backup_restore/restore_impl/v2.rs
- src/storage/backup/integration_tests/common.sh
- src/storage/backup/integration_tests/test_query_backup.sh
- src/storage/backup/src/lib.rs
- src/storage/src/hummock/backup_reader.rs
- src/storage/src/hummock/store/hummock_storage.rs
After #17161, batch query over metadata backup won't work correctly, because it `try_get_hummock_version` (find a queryable backup) using global safe_epoch and MCE, while `validate_safe_epoch` using per table safe_epoch and MCE.
This PR fixes it by storing and using per table safe_epoch and MCE.
</details>
> fix(meta): use per table mce and safe epoch in metadata backup

- src/frontend/planner_test/tests/testdata/output/temporal_join.yaml
- src/frontend/src/optimizer/plan_node/stream_temporal_join.rs
- src/stream/src/executor/temporal_join.rs
- Fix https://github.com/risingwavelabs/risingwave/issues/17238
</details>
> fix(stream): fix temporal join append only property

- src/connector/src/lib.rs
- src/connector/src/sink/decouple_checkpoint_log_sink.rs
- src/connector/src/sink/log_store.rs
- src/connector/src/sink/mod.rs
- src/connector/src/sink/remote.rs
- src/connector/src/sink/trivial.rs
- src/connector/src/sink/writer.rs
- src/stream/src/common/log_store_impl/in_mem.rs
- src/stream/src/executor/sink.rs
This PR includes several refinements to the await-tree of sink & log-store:
- Add some new finer-grained spans.
- Unify the style of instrumenting function calls with other occurrences.
- Remove duplicated information that is already provided by upper levels (like actor id and executor id).
- Change the return type of long-running tasks to `!` (the never type) to make it more explicit. …
> refactor(streaming): refine sink await-tree

- dashboard/pages/await_tree.tsx
- java/connector-node/connector-api/src/main/java/com/risingwave/connector/api/Monitor.java
- java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSinkFactory.java
- proto/monitor_service.proto
- src/common/src/util/prost.rs
- src/compute/src/rpc/service/monitor_service.rs
- src/jni_core/src/jvm_runtime.rs
Closes #17236
- Get JVM stack traces via the Java function `Monitor.dumpStackTrace()`
- BTW, improved an error message of connection failure in CDC connector
Web Dashboard:
`risectl trace`:
</details>
> feat(diagnosis): Dump JVM stack trace in await-tree-dump

- ci/scripts/e2e-sink-test.sh
- e2e_test/sink/kafka/avro.slt
- src/connector/src/sink/formatter/mod.rs
- src/frontend/src/handler/create_sink.rs
A missing piece from #13007. The refactor was done by #16575.
For kafka, `format plain encode avro` is supported in addition to previously supported `format upsert encode avro`.
> feat(sink): support `format plain encode avro` for kafka

- e2e_test/batch/catalog/pg_indexes.slt.part
- src/frontend/src/catalog/system_catalog/pg_catalog/pg_index.rs
- src/frontend/src/catalog/system_catalog/pg_catalog/pg_indexes.rs
> feat: expose PK info in index system catalog

- src/meta/src/barrier/recovery.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/rpc/ddl_controller_v2.rs
Previously we didn't unregister state table ids when we pre apply drop streaming job command during recovery. In this PR, we fix it by calling `purge_state_table_from_hummock` after the `pre_apply_drop_cancel`.
</details>
> fix(meta): purge hummock state table after pre apply drop command

- Cargo.lock
- src/common/src/array/arrow/arrow_impl.rs
- src/common/src/hash/key.rs
- src/common/src/types/datetime.rs
- src/common/src/types/mod.rs
- src/common/src/util/value_encoding/mod.rs
- src/connector/src/parser/avro/parser.rs
- src/connector/src/parser/mysql.rs
- src/connector/src/parser/unified/json.rs
- src/connector/src/sink/encoder/json.rs
- src/connector/src/source/iceberg/mod.rs
- src/ctl/src/cmd_impl/meta/migration.rs
- src/expr/impl/src/scalar/extract.rs
- src/expr/impl/src/scalar/to_char.rs
- src/expr/impl/src/scalar/tumble.rs
- src/meta/src/controller/mod.rs
As titled. 
Some methods in `NativeDateTime` are deprecated in `chrono` and this PR adopts the new methods accordingly by following chrono's doc.
This currently blocks OpenDAL upgrade (#17198)
</details>
> chore: upgrade chrono to 0.4.38

- e2e_test/iceberg/main.py
- e2e_test/iceberg/test_case/iceberg_sink_no_partition_append_only_table_verify.slt
- e2e_test/iceberg/test_case/iceberg_sink_partition_append_only_table_verify.slt
- e2e_test/iceberg/test_case/iceberg_sink_range_partition_append_only_table_verify.slt
- e2e_test/iceberg/test_case/no_partition_append_only.toml
- e2e_test/iceberg/test_case/partition_append_only.toml
- e2e_test/iceberg/test_case/range_partition_append_only.toml
> chore: add e2e test for iceberg source scan
