risingwavelabs/risingwave

src/meta/src/hummock/manager/checkpoint.rs

Fix the type error introduced in #14101.
Stale objects are grouped by version id.
</details>

fix: fix incorrect type alias

---

src/storage/hummock_test/src/hummock_storage_tests.rs
src/storage/hummock_trace/src/opts.rs
src/storage/src/hummock/store/local_hummock_storage.rs
src/storage/src/mem_table.rs
src/storage/src/store.rs
src/stream/src/common/log_store_impl/kv_log_store/writer.rs
src/stream/src/common/table/state_table.rs

In https://github.com/risingwavelabs/risingwave/pull/14655 the materialized executor will adjust the op consistency level on the flight. In this PR we will support enabling consistent op in state table and the underlying local state store before it. The `StateTable` can now call `commit_with_enable_consistent_op` to enable consistent op on the flight. …

feat(storage): support enabling consistent op on the flight

---

java/connector-node/risingwave-connector-test/src/test/java/com/risingwave/connector/sink/jdbc/JDBCSinkTest.java
proto/stream_plan.proto
src/frontend/src/optimizer/plan_node/stream_cdc_table_scan.rs
src/stream/src/from_proto/stream_cdc_scan.rs

Allow user to flow control cdc backfill via `streaming_rate_limit` session variable (#11919)
```
dev=> set streaming_rate_limit=1000;  // 1000 rows/s
SET_VARIABLE
dev=> CREATE TABLE orders_rw (
O_ORDERKEY BIGINT,
O_CUSTKEY BIGINT,
O_ORDERSTATUS VARCHAR,
O_TOTALPRICE DECIMAL,
O_ORDERDATE DATE,
O_ORDERPRIORITY VARCHAR,
O_CLERK VARCHAR,
O_SHIPPRIORITY BIGINT,
O_COMMENT VARCHAR,
PRIMARY KEY (O_ORDERKEY)
) from pg_source table 'public.orders_new';
```
close #14552  …

feat: support flow control for cdc backfill executor

---

docker/docker-compose-with-hdfs.yml

chore: update RisingWave version for docker compose with HDFS 

---

src/frontend/src/handler/create_source.rs
src/frontend/src/handler/create_table.rs
src/frontend/src/optimizer/mod.rs
src/frontend/src/optimizer/plan_node/generic/source.rs
src/frontend/src/optimizer/plan_node/logical_source.rs
src/frontend/src/planner/relation.rs

`LogicalSource` is quite hard to understand, because it does too many things.
This PR removes a lot of unnecessary functions to make it more straightforward.
- replace `gen_row_id` and `for_table` with `kind`
- remove `wrap_with_optional_generated_columns`, and `dispatch_new_s3_plan`. Create plan nodes directly. 
</details>

refactor(frontend): improve readability of LogicalSource

---

src/object_store/src/object/mod.rs
src/object_store/src/object/s3.rs

Previously it just used `ObjectStoreConfig::default`, so the user supplied configurations were ignored.
</details>

fix(object_store): pass user-supplied configurations to `with_minio`

---

.typos.toml

The checker will check the commit hash, so we should ignore it in `Cargo.toml/Cargo.lock`.
```
Warning: "ba" should be "be" or "by".
error: `ba` should be `be`, `by`
--> ./Cargo.toml:136:83
|
136 | arrow-udf-js = { git = "https://github.com/risingwavelabs/arrow-udf.git", rev = "7ba1c22" }
|                                                                                   ^^
|
``` …

chore(ci/typos): ignore checks on Cargo files

---

risedev.yml
src/risedevtool/src/service_config.rs
src/risedevtool/src/task/minio_service.rs

These configuration will be used to stably reproduce the case where minio request rate is too high, triggering `SlowDown` errors from minio / s3. Following PRs will try to fix the reproduced case.
</details>

feat(risedev): add configurations to rate limit minio request rate

---

src/storage/hummock_test/src/hummock_read_version_tests.rs
src/storage/src/hummock/compactor/shared_buffer_compact.rs
src/storage/src/hummock/event_handler/uploader.rs
src/storage/src/hummock/shared_buffer/shared_buffer_batch.rs
src/storage/src/hummock/store/local_hummock_storage.rs
src/storage/src/hummock/store/version.rs
src/storage/src/hummock/test_utils.rs

fix: dedup staging sst on storage table read

---

risedev.yml

As per title. Although there's retry, there's still a max retry cap that we hit. So we have to make the concurrent api requests limit more relaxed.
</details>

chore(risedev): increment `api-requests-deadline` to avoid `SlowDown` in `no_shuffle_backfill`

---

e2e_test/batch/types/interval.slt.part
src/common/src/types/interval.rs

resolve https://github.com/risingwavelabs/risingwave/issues/14704
</details>

feat: support ISO 8601 interval parsing

---

Cargo.lock
e2e_test/sink/kafka/avro.slt
src/connector/Cargo.toml
src/connector/src/parser/avro/schema_resolver.rs
src/connector/src/schema/avro.rs
src/connector/src/schema/mod.rs
src/connector/src/schema/protobuf.rs
src/connector/src/schema/schema_registry/client.rs
src/connector/src/schema/schema_registry/mod.rs
src/connector/src/schema/schema_registry/util.rs
src/connector/src/sink/formatter/mod.rs

* `InvalidOptionError` is returned by `handle_sr_list`, `schema_registry::Client::new`, `get_subject_by_strategy` and avro/protobuf sink. It can be converted into `SchemaFetchError` (for sink) and `RwError` (for source).
* `ConcurrentRequestError` (multiple `RequestError`s) is returned by schema registry API calls and can be converted into `SchemaFetchError` and `RwError`.
* `SchemaFetchError::YetToMigrate` for protobuf sink will be made into `InvalidOption` / `Request` / `SchemaCompile` in the next PR.
* `extract_schema_id` and `WireFormatError` is only used in source (`RwError`).
Refer to …

refactor: avoid `RwError` in schema registry client

---

src/storage/src/hummock/sstable/backward_sstable_iterator.rs
src/storage/src/hummock/sstable/block.rs

fix: fix block hitmap clone, fix unused pub

---

Cargo.lock
Cargo.toml
ci/Dockerfile
ci/build-ci-image.sh
ci/docker-compose.yml

Enable the "bindgen" feature of rquickjs-sys to prevent compile error on arm64 linux. https://github.com/risingwavelabs/arrow-udf/commit/ea7664da1a130bdd04bc22bb5146f52b2aa89f03
```
error: couldn't read /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rquickjs-sys-0.4.2/src/bindings/aarch64-unknown-linux-gnu.rs: No such file or directory (os error 2)
--> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rquickjs-sys-0.4.2/src/lib.rs:16:1
|
16 | include!(concat!("bindings/", bindings_env!("TARGET"), ".rs"));
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: this error …
```

fix: update arrow-udf to fix compile error on arm64 linux

---

src/common/src/cache.rs
src/ctl/src/cmd_impl/hummock/sst_dump.rs
src/storage/benches/bench_lru_cache.rs
src/storage/hummock_test/src/compactor_tests.rs
src/storage/src/hummock/block_cache.rs
src/storage/src/hummock/compactor/compaction_utils.rs
src/storage/src/hummock/compactor/compactor_runner.rs
src/storage/src/hummock/compactor/fast_compactor_runner.rs
src/storage/src/hummock/compactor/iterator.rs
src/storage/src/hummock/mod.rs
src/storage/src/hummock/sstable/backward_sstable_iterator.rs
src/storage/src/hummock/sstable/builder.rs
src/storage/src/hummock/sstable/delete_range_aggregator.rs
src/storage/src/hummock/sstable/forward_sstable_iterator.rs
src/storage/src/hummock/sstable/xor_filter.rs
src/storage/src/hummock/sstable_store.rs
src/storage/src/hummock/store/version.rs
src/storage/src/storage_failpoints/test_iterator.rs

For there is `Deref` on `CachedEntry`, `fn value()` can be removed.
</details>

chore(storage): remove cached entry value, use deref

---

src/stream/src/from_proto/source/trad_source.rs

Resolve #14755.
The `StreamSourceInfo` in `SourceExecutorBuilder` is actually from `FragmentManager` in Meta, whereas we only do the backward compatibility check in `CatalogManager`.
A quick fix that copies fields from `with_properties` to `format_encode_options`, may move the logic to FragmentManager::init and commit in the meta store in the future. …

fix: missing columns in format_encode_options

---

e2e_test/batch/catalog/sysinfo.slt.part
src/frontend/planner_test/tests/testdata/input/index_selection.yaml
src/frontend/planner_test/tests/testdata/output/basic_query.yaml
src/frontend/planner_test/tests/testdata/output/explain.yaml
src/frontend/planner_test/tests/testdata/output/index_selection.yaml
src/frontend/planner_test/tests/testdata/output/insert.yaml
src/frontend/planner_test/tests/testdata/output/range_scan.yaml
src/frontend/planner_test/tests/testdata/output/subquery.yaml
src/frontend/src/handler/create_index.rs
src/frontend/src/optimizer/mod.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/14762
- Since our batch queries will do constant folding and timezone transformation, functional indexes should store expression in the same form to make index selection happy.
</details>

feat: do constant folding and timezone transformation before create funtional indexes

---

src/stream/src/from_proto/source/trad_source.rs

Resolves #14778. Cherry-picking #14771.
</details>

fix: cherry-pick missing columns in format_encode_options

---

src/stream/src/executor/source/source_executor.rs

Cherry picking #14792 onto branch release-1.6

fix(error): log error field in stream reader retry loop (#14792)

---

src/storage/src/monitor/monitored_storage_metrics.rs

fix(metric): fix checkpoint size use small buckets

---

src/ctl/src/cmd_impl/profile.rs

Found some minor problems when doing heap profiling today. Here is the fix. Another one is  https://github.com/risingwavelabs/risingwave-operator/pull/592.
</details>

fix(risectl): cpu profiling: PREFIX_PROFILING not set

---

docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose.yml
docker/prometheus.yaml

Closes https://github.com/risingwavelabs/risingwave/issues/14802
</details>

chore(standalone): use 1 metrics port and rename store id to `standalone`

---

proto/monitor_service.proto
proto/stream_service.proto
src/compute/src/rpc/service/monitor_service.rs
src/compute/src/rpc/service/stream_service.rs
src/meta/src/controller/cluster.rs
src/meta/src/dashboard/mod.rs
src/meta/src/manager/cluster.rs
src/meta/src/stream/stream_manager.rs
src/rpc_client/src/compute_client.rs
src/rpc_client/src/stream_client.rs
src/storage/compactor/src/rpc.rs

In #14790, as mentioned in review, I move the `get_back_pressure` into monitor service and perform RPC calls concurrently. Also fix some nits.
</details>

refactor(meta): move get_back_pressure into monitor service and make it concurrent

---

Cargo.lock
src/connector/Cargo.toml

as title, fix https://github.com/risingwavelabs/risingwave/issues/14787
</details>

feat: enabling pulsar compression `lz4`

---

ci/scripts/gen-integration-test-yaml.py

https://buildkite.com/risingwavelabs/integration-tests/builds/601
</details>

feat(ci): add concurrency control for integration test

---

src/meta/src/hummock/compaction/picker/min_overlap_compaction_picker.rs

The expected SSTs can be a subset of the actual SSTs so we slice the actual SSTs using the expected SSTs len to check.
</details>

fix: fix compact task overlap check

---

src/stream/src/executor/project.rs

Revert #14558 to fix #14828.
Found by comparing
- [`nightly-20240115-fix-compaction`](https://buildkite.com/risingwave-test/longevity-test/builds/1001) 5.20 MB/s ⚠️
- [`nightly-20240115-fix-compaction-revert-14558`](https://buildkite.com/risingwave-test/longevity-test/builds/1010) 6.52 MB/s ✅
------------
Verifying on latest nightly build. So far so good.
- [`nightly-20240129`](https://buildkite.com/risingwave-test/longevity-test/builds/1008) Running
- [`nightly-20240129-revert-14558` (2 hour)](https://buildkite.com/risingwave-test/longevity-test/builds/1011) 6.43 MB/s ✅
- [`nightly-20240129-revert-14558` (12 …

revert: feat(stream): make Project expr evaluation concurrent (#14558)

---

src/cmd_all/src/standalone.rs
src/compute/src/lib.rs

`mem_table_spill_threshold` is specified in ComputeNodeOpts but it is actually unused. `mem_table_spill_threshold` in storage config will be used.
</details>

chore: remove the unused mem_table_spill_threshold opt

---

src/expr/impl/src/scalar/encrypt.rs

Intended to be part of #14717 which I am a reviewer of.
Several minor improvements:
* Prebuild `Cipher` (but not `Cryptor`)
* Compile Regex once.
* Handle error earlier to avoid deep indentation.
* Fix typos:
* comment: default mode is cbc rather than ecb
* error: expected padding is pkcs or none, rather than cbc or ecb
* Replace wildcard match with `Some(mode)`/`Some(padding)` to avoid `unwrap()`
* Replace wildcard match with `(Algorithm::Aes, n, Mode::Cbc | Mode::Ecb)` to avoid checking the same error twice.
* Parameterize the duplicate logic between encrypt and decrypt. …

refactor(expr): DRY encrypt/decrypt implementation

---

java/connector-node/risingwave-connector-service/src/main/resources/mysql.properties
java/connector-node/risingwave-connector-service/src/main/resources/postgres.properties

close #14818
- Make the default value of `transactional` property to `true` for MySQL and Postgres CDC
</details>

chore: enable transactional cdc for mysql and postgres by default

---

src/expr/core/src/window_function/call.rs
src/stream/src/executor/over_window/frame_finder.rs
src/stream/src/executor/over_window/general.rs
src/stream/src/executor/over_window/mod.rs
src/stream/src/executor/over_window/over_partition.rs

This PR:
1. Merges all `ROWS` frames into one super frame;
2. Rewrites the `find_affected_ranges` method to make things clear.
3. Some corner cases are hopefully corrected, e.g. frame `ROWS BETWEEN CURRENT ROW AND CURRENT ROW`, cache `[Smallest, 5, Largest]`, delta `[Delete 5]`
This is a prerequisition of `RANGE` frame support.
Please read https://risingwave.com/blog/risingwave-window-functions-the-art-of-sliding-and-the-aesthetics-of-symmetry/ before reviewing, so that you can get some basic background info.
66x out of 11xx lines of addition are unit tests, reviewers plz don't panic. …

refactor(over window): simplify `find_affected_ranges` and correct some corner cases

---

src/connector/src/source/filesystem/opendal_source/opendal_reader.rs
src/connector/src/source/filesystem/s3/source/reader.rs

Introduced by #14870 accidentally, because the branch protection rule was disabled.
</details>

chore: fix clippy

---

e2e_test/source/basic/alter/kafka.slt
src/frontend/src/handler/alter_source_column.rs
src/frontend/src/handler/alter_source_with_sr.rs

fix: using `alter source add column` on a table with conn will panic

---

proto/batch_plan.proto
src/frontend/src/optimizer/plan_node/batch_exchange.rs
src/frontend/src/scheduler/distributed/stage.rs

- Fix sequential exchange.
</details>

fix(batch): fix sequential exchange

---

src/common/src/config.rs

Related #14784 , to fix release in-memory e2e in main-cron: https://buildkite.com/risingwavelabs/main-cron/builds/1665#018d55f3-937f-4367-9bcb-7c1582e274fe
</details>

fix: initialize backup system parameter for in memory mode

---

src/connector/src/common.rs
src/connector/src/sink/kafka.rs
src/connector/src/source/base.rs
src/connector/src/source/kafka/enumerator/client.rs
src/connector/src/source/kafka/mod.rs
src/connector/src/source/kafka/private_link.rs
src/connector/src/source/kafka/source/reader.rs
src/connector/with_options_sink.yaml
src/connector/with_options_source.yaml

fix: remove `privatelink.targets` from with_options in frontend

---

src/meta/model_v2/migration/src/m20230908_072257_init.rs
src/meta/model_v2/src/actor.rs
src/meta/src/barrier/mod.rs
src/meta/src/barrier/recovery.rs
src/meta/src/controller/fragment.rs
src/meta/src/controller/streaming_job.rs
src/meta/src/controller/utils.rs

Add `worker_id` column in table `actor`, keep consistent with the parallelism unit id. It will make the SQL backend more compatible with the current implementation of scale in and down without causing panic. Although this information is redundant, it can be easily deleted when replaced by ensemble.
</details>

feat(sql-backend): add worker id in actor table to support auto scale in and down in sql backend

---

src/frontend/src/optimizer/plan_expr_rewriter/cse_rewriter.rs

chore(typo): fix license typo

---

src/meta/node/src/server.rs

Previously there will be error reports occasionally, resulting in DDL failure:
```sql
dev=> create table t1(v1 int);
2: Execution Error
3: error returned from database: (code: 5) database is locked
```
</details>

fix(sql-backend): force sqlite connection singleton to avoid database lock error

---

e2e_test/batch/basic/logical_view.slt.part
e2e_test/ddl/alter_rename.slt
e2e_test/ddl/dependency_check.slt
e2e_test/source/basic/ddl.slt
e2e_test/source/basic/old_row_format_syntax/ddl.slt
src/frontend/src/observer/observer_manager.rs
src/meta/model_v2/src/table.rs
src/meta/src/controller/catalog.rs
src/meta/src/controller/streaming_job.rs

Fixed some bugs when running e2e for alter rename and alter schema in SQL backend.
</details>

fix(sql-backend): fix some corner cases in alter rename and schema in sql backend

---

.github/workflows/cherry-pick-to-release-branch.yml

chore: re-enable cherry-pick by label even after the PR is closed

---

proto/plan_common.proto
src/common/src/catalog/column.rs
src/common/src/catalog/test_utils.rs
src/connector/src/parser/avro/util.rs
src/connector/src/parser/debezium/simd_json_parser.rs
src/connector/src/parser/json_parser.rs
src/connector/src/parser/mod.rs
src/connector/src/parser/protobuf/parser.rs
src/connector/src/parser/unified/upsert.rs
src/connector/src/parser/upsert_parser.rs
src/connector/src/source/kafka/source/reader.rs
src/connector/src/source/manager.rs
src/connector/src/source/reader/desc.rs
src/frontend/src/binder/expr/mod.rs
src/frontend/src/catalog/table_catalog.rs
src/frontend/src/handler/create_source.rs
src/frontend/src/handler/create_table.rs
src/storage/src/row_serde/mod.rs
src/stream/src/executor/source/mod.rs
src/stream/src/from_proto/source/trad_source.rs

refactor: additional_columns -> additional_column

---

src/meta/node/src/server.rs
src/meta/src/hummock/manager/mod.rs

chore(storage): cherry-pick 9e90eeb

---

proto/telemetry.proto

add `go_package` command to pass compiling to golang
following https://github.com/risingwavelabs/risingwave/pull/14952
telemetry backend: https://github.com/risingwavelabs/telemetry-backend/pull/24
</details>

chore: add go pkg in telemetry proto

---

src/connector/src/common.rs
src/connector/src/sink/kafka.rs
src/connector/src/source/base.rs
src/connector/src/source/kafka/enumerator/client.rs
src/connector/src/source/kafka/mod.rs
src/connector/src/source/kafka/private_link.rs
src/connector/src/source/kafka/source/reader.rs
src/connector/with_options_sink.yaml
src/connector/with_options_source.yaml

fix: remove `privatelink.targets` from with_options in frontend (#14907)

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose.yml

chore: update workspace version

---

docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-hdfs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose.yml

wait for release v1.6.1 first: https://buildkite.com/risingwavelabs/main-cron/builds/1820
and then merge
recommend all users to use v1.6.1 instead of v1.6.0
</details>

chore: update docker image version from v1.6.0 to v1.6.1

---

src/frontend/planner_test/tests/testdata/output/case_when_optimization.yaml
src/storage/hummock_test/src/compactor_tests.rs
src/storage/hummock_test/src/sync_point_tests.rs
src/storage/src/hummock/compactor/compactor_runner.rs
src/storage/src/hummock/compactor/mod.rs
src/storage/src/hummock/sstable/builder.rs

part of https://github.com/risingwavelabs/risingwave/pull/14949
related to https://github.com/risingwavelabs/risingwave/issues/15022
</details>

fix(storage): fix compactor oom 0206

---

src/storage/benches/bench_compactor.rs

Try increase key count to make the test more stable. https://github.com/risingwavelabs/risingwave/issues/14908 could not be reproduced locally by @Little-Wallace.
</details>

chore(bench): increase key count

---

scripts/install/install-risingwave.sh

fix(scripts): update the install script to be POSIX compliant, support linux-aarch64, pin brew install version

---

e2e_test/udf/sql_udf.slt

Some features in future roadmap maybe further discussed.
Related: https://github.com/risingwavelabs/risingwave/issues/10151#issue-1738509282.
Reference: https://www.postgresql.org/docs/current/sql-createfunction.html
</details>

refactor(test): assemble unimplemented tests together & add future roadmap for sql udf

---

src/utils/runtime/src/logger.rs

Resolve #15064 . We can enable debug for it by `RUST_LOG`, i.e: `export RUST_LOG="debug,sqlx=warn"`.
</details>

feat: configure WARN default log level for sqlx

---

scripts/install/install-risingwave.sh

chore(scripts): support brew install via script

---

src/common/src/session_config/sink_decouple.rs
src/connector/src/source/pulsar/topic.rs
src/connector/src/source/reader/fs_reader.rs
src/expr/core/src/expr/build.rs
src/expr/macro/src/parse.rs
src/meta/src/barrier/progress.rs
src/meta/src/hummock/compaction/picker/manual_compaction_picker.rs
src/meta/src/hummock/compaction/picker/min_overlap_compaction_picker.rs
src/meta/src/hummock/compaction/picker/space_reclaim_compaction_picker.rs
src/meta/src/hummock/compaction/picker/ttl_reclaim_compaction_picker.rs
src/meta/src/hummock/compaction/selector/level_selector.rs
src/storage/benches/bench_fs_operation.rs
src/storage/hummock_test/src/test_utils.rs
src/storage/hummock_trace/src/write.rs
src/storage/src/hummock/block_cache.rs
src/stream/src/common/table/state_table_cache.rs
src/stream/src/executor/over_window/over_partition.rs
src/stream/src/executor/top_n/top_n_plain.rs
src/stream/src/executor/top_n/top_n_state.rs
src/utils/pgwire/src/pg_server.rs

chore: fix nightly clippy

---

src/stream/src/executor/source/source_executor.rs

fewer indent levels is more readable.
Please hide witespace changes to review
</details>

refactor: reduce indent level for source_executor

---

ci/Dockerfile
ci/build-ci-image.sh
ci/docker-compose.yml
ci/workflows/pull-request.yml

as title, 
command: `ci/scripts/e2e-test.sh -p ci-dev -m ci-3streaming-2serving-3fe`
as continuously met timeout issue in https://github.com/risingwavelabs/risingwave/pull/15073 but it does not have time consuming logic
</details>

chore: longer timeout for e2e test

---

src/storage/hummock_sdk/src/key.rs
src/storage/src/hummock/iterator/forward_user.rs

Don't panic when UserIterator sees same full key. This PR should be reverted after #15099 is resolved.
</details>

chore: temporarily bypass FullKeyTracker for #15099

---

src/meta/model_v2/migration/src/m20230908_072257_init.rs
src/meta/src/controller/catalog.rs
src/meta/src/controller/streaming_job.rs

fix(sql-backend): clean up dirty source catalogs for failed table with connectors and recovery

---

src/storage/src/monitor/hummock_state_store_metrics.rs

Both `spill_task_size` and `spill_task_counts` have only 1 label - `uploader_stage = sealed or unsealed`, which should not be relabelled.
</details>

chore: fix incorrect metric relabel

---

src/expr/core/src/expr/expr_udf.rs
src/expr/udf/src/external.rs

In this case, UDF can be part of join key, so their call to UDF server must never fail, otherwise it will lead to inconsistent error and the MV will need to be recreated.
</details>

fix: always retry on connection error

---

e2e_test/batch/catalog/pg_cast.slt.part
src/common/src/types/serial.rs
src/expr/impl/src/scalar/cast.rs
src/frontend/src/expr/type_inference/cast.rs

#15008 
We only allow an explicit casting in the PR, we can extend the behavior later, but we need that for testing.
</details>

feat(expr): allow explicit cast serial to bigint

---

src/meta/node/src/lib.rs

fix(storage): fix expired timeout sec

---

e2e_test/error_ui/simple/main.slt
src/common/src/system_param/mod.rs
src/meta/src/controller/system_param.rs

fix(sql-backend): fix error message for altering unrecognized system parameter

---

java/connector-node/risingwave-sink-cassandra/src/main/java/com/risingwave/connector/CassandraConfig.java
java/pom.xml

Bump version of spotless plugin to make it work in JDK21.
</details>

chore: bump version of spotless plugin

---

src/meta/src/barrier/mod.rs

looks like tracing's bug https://github.com/tokio-rs/tracing/issues/1873
</details>

fix(tracing): fix missing new barrier enqueued event

---

src/meta/model_v2/src/table.rs
src/meta/node/src/server.rs
src/meta/src/controller/catalog.rs
src/meta/src/controller/fragment.rs
src/meta/src/dashboard/mod.rs
src/meta/src/manager/catalog/fragment.rs
src/meta/src/manager/diagnose.rs
src/meta/src/manager/metadata.rs

feat(sql-backend): support diagnose in sql-backend

---

dashboard/mock-server.js
dashboard/mock/fetch.sh
dashboard/pages/api/metric.ts
src/meta/src/dashboard/mod.rs
src/meta/src/dashboard/prometheus.rs

As [suggest](https://github.com/risingwavelabs/risingwave/pull/14863#discussion_r1502114941) in #14863 comments, do some refactor to seperate the embeded back pressure and prometheus back pressure.
Change `/metrics/actor/back_pressures` to `/metrics/fragment/prometheus_back_pressures`
Change `/metrics/back_pressures` to `/metrics/fragment/embedded_back_pressures` …

refactor(dashboard): refactor back pressure api path name

---

src/meta/src/controller/catalog.rs
src/meta/src/rpc/ddl_controller_v2.rs

feat(sql-backend): add missing failure event records in sql backend

---

ci/workflows/docker.yml
ci/workflows/gen-flamegraph-cron.yml
ci/workflows/gen-flamegraph.yml
ci/workflows/main-cron.yml
ci/workflows/pull-request.yml
ci/workflows/sqlsmith-snapshots.yml

chore(ci): bump buildkite docker-compose plugin version to v5.1.0

---

src/meta/model_v2/migration/src/m20230908_072257_init.rs
src/meta/src/controller/catalog.rs

Previously the column `arg_types` in table `function` is defined as `json` type, which will fail the query of function duplicate check in PostgreSQL:
```rust
let count = Function::find()
.inner_join(Object)
.filter(
object::Column::DatabaseId
.eq(pb_function.database_id as DatabaseId)
.and(object::Column::SchemaId.eq(pb_function.schema_id as SchemaId))
.and(function::Column::Name.eq(&pb_function.name))
.and(function::Column::ArgTypes.eq(DataTypeArray(pb_function.arg_types.clone()))),
)
.count(db)
.await?;
```
The error message is like: `operator does not exist: json = jsonb`, the parameter will be treated as `jsonb` by …

fix(sql-backend): fix some function column types and change json column to jsonb

---

src/expr/core/src/expr/expr_udf.rs
src/expr/udf/src/external.rs

cherry-pick #15076 to release-1.7
resolve #15318
</details>

fix(udf): fix "udf returned no data" error (#15076)

---

Cargo.lock

cherry-pick #15313 to release-v1.6
</details>

chore(deps): update librdkafka to v2.3.0

---

src/frontend/src/handler/drop_view.rs

fix(frontend): wrong stmt type while `DROP VIEW IF EXISTS`

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose.yml

chore: update version to 1.7.0

---

src/tests/libpq_test/Cargo.lock
src/tests/libpq_test/Cargo.toml

fix dependabot alert
</details>

chore(deps): bump deps in libpq_test

---

src/frontend/src/binder/bind_param.rs
src/tests/e2e_extended_mode/src/test.rs

fix(frontend): add subquery rewrite for parameter rewriter

---

ci/scripts/run-e2e-test.sh
ci/scripts/single-node-utils.sh
ci/workflows/main-cron.yml
ci/workflows/pull-request.yml

Also tests sqlbackend, since that's used by single-node mode.
</details>

test: add `single-node` binary tests

---

ci/workflows/pull-request.yml

Tests from https://github.com/risingwavelabs/risingwave/pull/15163 will increase e2e test runtime by ~1min.
I'm not sure if there's other tests added which will increase runtime as well. Bumping it since it's blocking PRs.
</details>

chore(ci): increase pull request timeout

---

java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/PostgresValidator.java

Fix for a PG behinds a privatelink endpoint which ends with "vpce.amazonaws.com".
</details>

fix(pg-cdc): fix AWS RDS endpoint behind a privatelink

---

ci/scripts/run-e2e-test.sh
ci/scripts/single-node-utils.sh
ci/workflows/main-cron.yml
ci/workflows/pull-request.yml

Add e2e `single-node` binary tests. This also tests the `sqlbackend` and `local fs state store`.
Same as https://github.com/risingwavelabs/risingwave/pull/15016
</details>

test: add single-node binary tests

---

ci/scripts/notify.py

test: fix integration test notify

---

.github/workflows/cherry-pick-to-release-branch.yml

chore(ci): add cherry pick for `v1.7.0-standalone`

---

java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/PostgresValidator.java

cherry-pick #15348 
</details>

 fix(pg-cdc): fix AWS RDS endpoint behind a privatelink (#15348)

---

integration_tests/starrocks-sink/README.md
integration_tests/starrocks-sink/create_sink.sql
integration_tests/starrocks-sink/sink_check.py
integration_tests/starrocks-sink/starrocks_prepare.sql

Duplicate Key table, Aggregate table, Unique Key table
</details>

feat(integration_test): add other starrocks table test

---

src/frontend/src/catalog/system_catalog/rw_catalog/mod.rs
src/frontend/src/catalog/system_catalog/rw_catalog/rw_actor_infos.rs
src/frontend/src/catalog/system_catalog/rw_catalog/rw_fragment_parallelism.rs
src/frontend/src/catalog/system_catalog/rw_catalog/rw_hummock_version.rs
src/frontend/src/catalog/system_catalog/rw_catalog/rw_sinks.rs
src/frontend/src/test_utils.rs
src/storage/hummock_sdk/src/table_watermark.rs
src/tests/simulation/tests/integration_tests/sink/basic.rs

For https://github.com/risingwavelabs/risingwave/issues/14824
Added a system table `rw_hummock_table_watermark` to query table watermark. Another system table `rw_actor_info` is added to query actor information so that we can get whether the sink has enabled decouple.
</details>

feat(frontend): support system table to query storage table watermark

---

src/batch/src/executor/group_top_n.rs
src/batch/src/executor/hash_agg.rs
src/batch/src/executor/join/hash_join.rs
src/batch/src/executor/join/lookup_join_base.rs
src/common/benches/bench_hash_key_encoding.rs
src/common/src/hash/key.rs
src/common/src/hash/key_v2.rs
src/stream/src/executor/hash_agg.rs
src/stream/src/executor/hash_join.rs
src/stream/src/executor/temporal_join.rs
src/stream/src/executor/top_n/group_top_n.rs
src/stream/src/executor/top_n/group_top_n_appendonly.rs

refactor(hash): remove Result in HashKey::build

---

scripts/install/install-risingwave.sh

Only merge after 1.7 released.
</details>

chore(scripts): update risingwave install script `version`

---

e2e_test/batch/catalog/rw_depend.slt.part
src/frontend/src/catalog/system_catalog/rw_catalog/mod.rs
src/frontend/src/catalog/system_catalog/rw_catalog/rw_depend.rs

Added a system table `rw_depend` to record the dependency relationships between tables, mviews, sources, and sinks.
</details>

feat(catalog): add system catalog `rw_depend`

---

Cargo.lock

to fix the stuck issue https://github.com/DelSkayn/rquickjs/issues/268
</details>

chore(deps): bump arrow-udf-js and rquickjs

---

src/stream/src/executor/backfill/arrangement_backfill.rs
src/stream/src/executor/backfill/no_shuffle_backfill.rs
src/stream/src/executor/backfill/utils.rs

fix(metric): fix backfill snapshot read metric

---

src/connector/src/lib.rs

(ignore) dummy change to test cherry-pick script

---

src/frontend/src/lib.rs

(ignore) another `dummy` change to test cherry-pick script with `if` / `pwd` title

---

src/common/src/cast/mod.rs

fix: handle negative int cast to `timestamptz`

---

src/frontend/planner_test/tests/testdata/input/dynamic_filter.yaml
src/frontend/planner_test/tests/testdata/output/dynamic_filter.yaml
src/frontend/src/optimizer/plan_visitor/cardinality_visitor.rs

fix https://github.com/risingwavelabs/risingwave/issues/15445
</details>

fix(optmizer): add some missing node for CardinalityVistor

---

e2e_test/streaming/bug_fixes/issue_15302.slt
src/stream/src/from_proto/dynamic_filter.rs

fix(dynfilter): cherrypick left table with singleton dist panic bug (#15406) to branch release-1.7.0-standalone

---

ci/scripts/deterministic-e2e-test.sh
ci/workflows/main-cron.yml

Bump timeout for some `main-cron` tests
</details>

chore(ci): bump main-cron timeout

---

ci/scripts/gen-flamegraph.sh

fix: change kafka download url

---

ci/scripts/run-e2e-test.sh
ci/workflows/main-cron.yml

chore(ci): skip flaky test for `single-node`, increase `e2e-test` timeout

---

src/frontend/src/optimizer/plan_node/batch_delete.rs
src/frontend/src/optimizer/plan_node/batch_insert.rs
src/frontend/src/optimizer/plan_node/batch_source.rs
src/frontend/src/optimizer/plan_node/batch_update.rs
src/frontend/src/optimizer/plan_visitor/distributed_dml_visitor.rs
src/frontend/src/optimizer/plan_visitor/mod.rs

- Related https://github.com/risingwavelabs/risingwave/issues/14742
- Auto decide distributed dml for iceberg ingestion. 
</details>

feat(batch): auto decide distributed dml for iceberg ingestion

---

src/storage/backup/integration_tests/common.sh

fix(test): suppress expected error message

---

ci/workflows/pull-request.yml
e2e_test/streaming/bug_fixes/issue_15302.slt
src/stream/src/from_proto/dynamic_filter.rs

fix(dynfilter): cherrypick left table with singleton dist panic bug (#15406) to branch release-1.7

---

ci/scripts/common.sh
ci/scripts/gen-flamegraph.sh
src/risedevtool/kafka.toml

As title. Bumping Kafka all the time is annoying.
This should fix some of the timeout problem in [main-cron test](https://buildkite.com/risingwavelabs/main-cron/).
</details>

fix(risedev): always download latest Kafka

---

docker/Dockerfile.hdfs
src/object_store/src/object/mod.rs
src/object_store/src/object/opendal_engine/mod.rs

fix(docker): fix java env in Dockerfile.hdfs

---

src/common/src/config.rs
src/config/example.toml

Feel annoying of OOM problems recently...
</details>

fix: cherry-pick to v1.7: chore: enable mem table spill (#15240)

---

src/connector/src/sink/doris_starrocks_connector.rs

I'm assuming this should be `future` rather than `feature`.
</details>

chore(sink): fix typo

---

src/connector/src/aws_utils.rs

subfolder path got `/` in it
</details>

fix(source): don't replace all '/' in s3 path to empty str

---

integration_tests/big-query-sink/create_sink.sql
java/connector-node/risingwave-sink-cassandra/src/main/java/com/risingwave/connector/CassandraConfig.java
java/connector-node/risingwave-sink-cassandra/src/main/java/com/risingwave/connector/CassandraSink.java
src/connector/src/common.rs
src/connector/src/sink/big_query.rs
src/connector/src/sink/doris.rs
src/connector/src/sink/encoder/json.rs
src/connector/src/sink/encoder/mod.rs
src/connector/src/sink/starrocks.rs
src/connector/with_options_sink.yaml

fix(sink): add cassandra batch size and fix bigquery array null (#15516)

---

integration_tests/iceberg-source/docker/hive/config.ini
integration_tests/iceberg-source/docker/hive/docker-compose.yml
integration_tests/iceberg-source/docker/hive/spark-script/spark-connect-server.sh
integration_tests/iceberg-source/python/main.py

- Add hive integration test for iceberg source.
</details>

test(batch): support hive catalog for iceberg source

---

risedev.yml
src/common/src/config.rs
src/config/full-with-batch-query-limit.toml
src/frontend/src/scheduler/distributed/query.rs
src/frontend/src/scheduler/distributed/query_manager.rs
src/frontend/src/session.rs

cherry pick.
Closes https://github.com/risingwavelabs/risingwave/issues/15578.
</details>

feat(frontend): add max_batch_queries_per_frontend_node config (#15574)

---

e2e_test/iceberg/test_case/iceberg_sink_upsert.slt

fix: ci e2e test

---

e2e_test/batch/subquery/array_construct.slt.part
src/frontend/planner_test/tests/testdata/output/subquery.yaml
src/frontend/planner_test/tests/testdata/output/subquery_expr_correlated.yaml
src/frontend/src/optimizer/mod.rs

Cherry picking #15593 onto branch release-1.7

fix(planner): array-construction subquery shall return `{}` rather than `null` (#15593)

---

e2e_test/batch/subquery/subquery.slt.part
src/frontend/planner_test/tests/testdata/input/subquery_expr_correlated.yaml
src/frontend/planner_test/tests/testdata/output/subquery_expr_correlated.yaml
src/frontend/src/optimizer/rule/apply_agg_transpose_rule.rs

Cherry picking #15590 onto branch release-1.7

fix(optimizer): decorrelate SimpleAgg with `array_agg`/`jsonb_agg`/`jsonb_object_agg` (#15590)

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose.yml

chore: update version to 1.7.1

---

integration_tests/citus-cdc/create_source.sql

No need to recreate table in the functionality test
</details>

fix(integration-test): fix citus-cdc case

---

ci/scripts/cron-e2e-test.sh
ci/scripts/pr.env.sh
ci/scripts/run-e2e-test.sh
ci/scripts/run-meta-backup-test.sh
ci/workflows/main-cron.yml

They can take a long time, and sometimes stuck. Split it so tests can run in parallel, and make sure that core e2e tests are passing.
</details>

chore(ci): split meta backup tests from e2e tests

---

ci/workflows/pull-request.yml

Reverts risingwavelabs/risingwave#15630

chore(ci): revert always run `single-node` tests per PR 

---

docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-hdfs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose.yml

chore: update docker image to 1.7.1

---

src/frontend/src/binder/expr/function.rs

feat(expr): implement dummy `pg_stat_get_numscans` function

---

proto/stream_service.proto
src/compute/src/rpc/service/stream_service.rs
src/meta/src/barrier/command.rs
src/meta/src/barrier/mod.rs
src/meta/src/barrier/recovery.rs
src/meta/src/barrier/rpc.rs
src/meta/src/stream/scale.rs
src/meta/src/stream/stream_manager.rs
src/rpc_client/src/lib.rs
src/rpc_client/src/stream_client.rs
src/storage/src/memory.rs
src/stream/src/task/barrier_manager.rs
src/stream/src/task/barrier_manager/tests.rs
src/stream/src/task/stream_manager.rs
src/tests/simulation/src/slt.rs

This reverts commit 72d37ef040bb31717d74aaa40d9d18910ce5f070.
Related #15650
Reverting #14887 can make the longevity testing passed. Currently, we have no conclusion about the root cause.
</details>

revert: "feat(meta): inject and collect barrier in bidi stream (#14887)"

---

src/ctl/src/cmd_impl/meta/reschedule.rs

https://linear.app/risingwave-labs/issue/CLOUD-2493/daily-e2e-test-failed-2024-03-11#comment-a7c3773b
Our E2E test crashes if we try to delete a CN that does not exist, which may happen on retry. 
</details>

feat(fix): Avoid exit 1 in risectl if ignore not found (CLOUD-2493)

---

src/meta/src/controller/user.rs

Even thought we have defined on conflict for inserting new user privileges, seaORM still issues `RecordNotInserted` and `RecordNotUpdated` errors if no rows are affected. Adding `on_conflict` fixes it.
</details>

fix: correctly handle on conflict for inserting user privilege

---

src/common/src/config.rs
src/config/example.toml
src/meta/src/hummock/manager/mod.rs
src/object_store/src/object/mod.rs
src/object_store/src/object/opendal_engine/fs.rs
src/object_store/src/object/opendal_engine/hdfs.rs

Previously for fs and hdfs object store, we set `atomic_write_dir` , but actually it's only needed in meta side.
</details>

refactor(object store): only the object store used by meta needs to set `atomic_write_dir`

---

src/common/src/vnode_mapping/vnode_placement.rs
src/frontend/src/scheduler/worker_node_manager.rs
src/meta/src/serving/mod.rs

As titled. 
Otherwise max batch scan parallelism is limited by that of stream parallelism, which only makes sense for singleton.
close #15572
</details>

fix(batch): avoid setting max_parallelism for batch scan that is no singleton

---

ci/scripts/e2e-pulsar-sink-test.sh
e2e_test/sink/pulsar_sink.slt

resolve https://github.com/risingwavelabs/risingwave/issues/15336
the bug may introduced in https://github.com/risingwavelabs/risingwave/pull/14142 
</details>

fix: fix pulsar e2e network failure

---

src/connector/src/source/cdc/external/mock_external_table.rs
src/connector/src/source/cdc/external/mod.rs
src/connector/src/source/cdc/external/postgres.rs
src/stream/src/executor/backfill/cdc/cdc_backfill.rs
src/stream/src/executor/backfill/cdc/upstream_table/snapshot.rs

- Limit each table snapshot to 10k rows to avoid consuming a large number of rows when dropping a result set
- Ensure the result stream has been consumed once
Tested with 6M rows `lineitem` table locally.
related: #15500 #15173 
</details>

fix(cdc-backfill): limit the number of rows for each table snapshot 

---

ci/scripts/notify.py

Btw, for changes relevant to sql backend, recommend you add the label: `ci/run-e2e-single-node-tests` to your PR. Those tests will cover sql backend.
</details>

chore(ci): notify single node mode test failure

---

.github/workflows/cherry-pick-to-release-branch.yml

chore: add 1.8 cherry pick label

---

ci/scripts/run-e2e-test.sh

Fix test failure found in https://buildkite.com/risingwavelabs/main-cron/builds/2062#018e4d25-146b-4a41-90a2-2f0c1de6aa72
The root cause is that there's `ExponentialBackoff` retry strategy with a upper bound 5s for meta client to register itself to meta. At that time the compute node might not register itself yet before running any e2e tests.
</details>

chore: wait longer to make sure single-node is ready

---

src/storage/hummock_sdk/src/key.rs
src/storage/src/hummock/store/hummock_storage.rs
src/storage/src/hummock/store/local_hummock_storage.rs
src/storage/src/memory.rs
src/storage/src/monitor/monitored_store.rs
src/storage/src/monitor/traced_store.rs
src/storage/src/panic_store.rs
src/storage/src/store.rs
src/storage/src/store_impl.rs
src/storage/src/table/mod.rs
src/stream/src/common/table/state_table.rs

Define iter_log method as followed
```
fn iter_log(
&self,
epoch_range: (u64, u64),
key_range: TableKeyRange,
options: ReadLogOptions,
) -> impl Future<Output = StorageResult<Self::ChangeLogIter>> + Send + '_;
```
Add trivial implementation for in-memory and sled state store and add unit test.
</details>

feat(storage): define iter_log method and in-mem trivial implementation

---

src/risedevtool/connector.toml

The original version 3.9.3 has been removed from https://downloads.apache.org/maven/maven-3/ . Update it to 3.9.6 to make it work again.
</details>

chore: update maven version in download script

---

.github/aws-config/Dockerfile
ci/build-ci-image.sh
ci/docker-compose.yml
ci/scripts/common.sh
ci/scripts/e2e-deltalake-sink-rust-test.sh
ci/scripts/e2e-iceberg-sink-test.sh
ci/scripts/release.sh
ci/workflows/main-cron.yml
ci/workflows/pull-request.yml

test pipeline：https://buildkite.com/risingwavelabs/migrate-aws-account-test
</details>

chore(ci): migrate ci to new aws account

---

.github/aws-config/Dockerfile
ci/build-ci-image.sh
ci/docker-compose.yml
ci/scripts/common.sh
ci/scripts/e2e-deltalake-sink-rust-test.sh
ci/scripts/e2e-iceberg-sink-test.sh
ci/scripts/release.sh
ci/workflows/main-cron.yml
ci/workflows/pull-request.yml

chore(ci): migrate ci to new aws account (#15753)

---

ci/docker-compose.yml
ci/workflows/main-cron.yml
ci/workflows/pull-request.yml

fix(ci): remove doris sink ci (#15332)

---

Cargo.lock
Cargo.toml

chore: update risingwave version

---

docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose.yml

wait for  https://buildkite.com/risingwavelabs/main-cron/builds/2069 then merge
</details>

chore: update docker compose image version to v1.7.2

---

src/meta/src/hummock/compaction/picker/intra_compaction_picker.rs
src/meta/src/hummock/manager/mod.rs
src/storage/hummock_sdk/src/compact.rs

cherry-pick (#15659)
</details>

fix(meta): trivial move bug 

---

src/connector/src/sink/iceberg/mod.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/15393
</details>

fix(sink): fix iceberg sink missing deletes

---

src/frontend/src/catalog/system_catalog/rw_catalog/rw_hummock_version.rs

Bug introduced by https://github.com/risingwavelabs/risingwave/pull/14947.
This PR fixes it by showing sub level id for level 0.
</details>

fix: show sub_level_id for level 0 in rw_hummock_sstables

---

src/common/src/util/env_var.rs
src/object_store/src/object/mod.rs

As title, we can set `RW_USE_OPENDAL_FOR_S3=false` to switch to aws sdk.
</details>

refactor(object store): use opendal to access s3 by default

---

src/meta/service/src/cluster_service.rs

Fix https://github.com/risingwavelabs/risingwave/issues/15803
Previously in https://github.com/risingwavelabs/risingwave/pull/15748 we changed to wait for resolving the dns of newly registered nodes. However, in k8s, the cluster only propagate the node dns information after it sees the CN port is up and healthy, and CN server is up before able to register to the cluster, which is deadlock and CN can never get started.
In this PR we change to wait for resolving the dns when handling the activate worker node request. …

fix(meta): try resolve dns when activating node

---

src/frontend/src/handler/create_source.rs

feat: allow format plain encode bytes for Nats connector

---

src/connector/src/source/pulsar/source/reader.rs

refactor: unify subscription name to `rw-consumer-{fragment id}-{actor id}` with kafka reader

---

src/storage/hummock_test/src/hummock_read_version_tests.rs
src/storage/src/hummock/event_handler/hummock_event_handler.rs
src/storage/src/hummock/store/version.rs

Prior to this PR, on finishing data spill or sync task in event handler, we will deep copy the sstable info for number of read version times. Given that there are multiple Vecs inside sstable info and the number of read versions is proportional to number of actors in the CN, the deep copy overhead can be significant, resulting in slowness in hummock event handler. which will affect barrier latency.
This PR uses Arc to wrap `StagingSstableInfo` to avoid deep copy of sstable info to fix the issue.
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly …

perf: avoid sstable info copy in event handler

---

java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzCdcEngineRunner.java
src/jni_core/src/lib.rs

fix(connector): fix null pointer in connector

---

src/frontend/src/optimizer/plan_node/batch_seq_scan.rs
src/frontend/src/optimizer/plan_node/generic/mod.rs
src/frontend/src/optimizer/plan_node/generic/table_scan.rs
src/frontend/src/optimizer/plan_node/logical_scan.rs
src/frontend/src/optimizer/plan_node/stream_table_scan.rs
src/frontend/src/optimizer/rule/index_selection_rule.rs

Part of https://github.com/risingwavelabs/risingwave/issues/13146#issuecomment-1805229754.
`Scan` is too generic. We have other types of scans as well, e.g. `CdcScan`.
It should only be used for scan on RisingWave tables. So rename to `TableScan`.
</details>

refactor(frontend): rename `generic::Scan` to `generic::TableScan`

---

src/frontend/planner_test/tests/testdata/output/agg.yaml
src/frontend/planner_test/tests/testdata/output/ch_benchmark.yaml
src/frontend/planner_test/tests/testdata/output/distribution_derive.yaml
src/frontend/planner_test/tests/testdata/output/emit_on_window_close.yaml
src/frontend/planner_test/tests/testdata/output/except.yaml
src/frontend/planner_test/tests/testdata/output/intersect.yaml
src/frontend/planner_test/tests/testdata/output/join.yaml
src/frontend/planner_test/tests/testdata/output/nexmark.yaml
src/frontend/planner_test/tests/testdata/output/over_window_function.yaml
src/frontend/planner_test/tests/testdata/output/share.yaml
src/frontend/planner_test/tests/testdata/output/sink.yaml
src/frontend/planner_test/tests/testdata/output/stream_dist_agg.yaml
src/frontend/planner_test/tests/testdata/output/temporal_filter.yaml
src/frontend/planner_test/tests/testdata/output/tpch.yaml
src/frontend/planner_test/tests/testdata/output/union.yaml
src/frontend/src/optimizer/plan_node/stream_table_scan.rs

Previously we have the following column names in backfill state:
```
<table_name>_backfill_finished
<table_name>_row_count
```
We don't need these prefixes.
Now it's just:
```
backfill_finished
row_count
```
</details>

refactor(frontend): remove table name from the backfill column as prefix

---

Cargo.lock
src/rpc_client/Cargo.toml
src/rpc_client/src/meta_client.rs

Change `lru` version to `workspace = true` in `rpc_client` so that we can uniformly manage the use of `lru` crate.
</details>

chore(rpc client): use workspace version of `lru` in `rpc_client`

---

src/storage/backup/integration_tests/test_query_backup.sh

The expected error message has been changed due to previous refactor.
</details>

fix(test): fix expected error message

---

src/expr/udf/src/error.rs

Previously `FlightError` can mask `Tonic` errors as well.
This PR fixes that by handling these errors too.
</details>

fix(expr): handle another `Tonic` error path for `always_retry_on_network_error`

---

Makefile.toml
src/cmd_all/src/bin/risingwave.rs
src/cmd_all/src/single_node.rs
src/cmd_all/src/standalone.rs
src/meta/node/src/lib.rs

Part of unifying single node mode and playground. https://github.com/risingwavelabs/risingwave/issues/14997
Just provide this first, then @mikechesterwang can try to migrate our web playground to use this config. We can deprecate `playground` mode once we are sure this satisfies all requirements.
You can do the following to run it:
```
./risingwave --in-memory --max-idle-secs=1800
``` …

feat(cmd_all): add `in-memory` mode to single-node mode

---

src/frontend/src/catalog/system_catalog/rw_catalog/rw_functions.rs

Adds `always_retry_on_network_error` to the function catalog in meta.
That way we can query `rw_functions` to see if it is set.
```
select name, always_retry_on_network_error from rw_functions;
name                   | always_retry_on_network_error 
-----------------------------------------+-------------------------------
gcd                                     | t
``` …

feat(frontend): add `always_retry_on_network_error` to function catalog

---

src/meta/node/src/server.rs

Dashboard task does not have a shutdown handle. We can just abort it once other meta services are aborted.
Otherwise meta node can't exit in playground / single-node mode, when idle manager issues timeout.
</details>

fix(cmd_all): abort dashboard task on exit

---

scripts/install/install-risingwave.sh

As per title. Otherwise Users may find Java Connectors do not work without it.
</details>

chore(scripts): update install script to tell users to install `Java`

---

e2e_test/batch/catalog/rw_depend.slt.part
src/tests/simulation/src/slt.rs

Since `sink into table` reused the replacement logic used by `alter table column` which doesn't guarantee the atomicity, we need to ignore kill during recovery test for it. Note that, the atomicity is guaranteed in sql-backend already and it's not that easy to fix in current etcd version. Let's ignore it for now like `alter table column`.
</details>

fix(ci): ignore kill for sink into table

---

java/connector-node/risingwave-connector-service/src/main/resources/mysql.properties

Debezium [v2.x](https://debezium.io/documentation/reference/2.4/connectors/mysql.html#debezium-mysql-connector-pass-through-database-driver-configuration-properties) changed the prefix to `driver.`
</details>

fix(mysql-cdc): set timezone for snapshot loading

---

src/connector/src/sink/clickhouse.rs
src/connector/src/sink/kafka.rs
src/connector/src/sink/kinesis.rs
src/connector/src/sink/mod.rs
src/connector/src/sink/mqtt.rs
src/connector/src/sink/nats.rs
src/connector/src/sink/pulsar.rs
src/connector/src/sink/remote.rs
src/frontend/src/optimizer/plan_node/stream_sink.rs

context: https://github.com/risingwavelabs/risingwave/pull/15634#discussion_r1529973502
refine the decouple interface so that we can decide whether use decouple mode or return an error if the config has some conflict.
~~- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).~~
~~- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)~~
~~- [ ] My PR contains critical fixes …

refactor(frontend): refine decouple config

---

src/ctl/src/common/hummock_service.rs

https://github.com/risingwavelabs/risingwave/pull/15682#issuecomment-2011306745
</details>

fix(ctl): fix sst_dump

---

e2e_test/batch/transaction/read_only.slt
src/frontend/src/catalog/system_catalog/pg_catalog/pg_attribute.rs
src/frontend/src/handler/transaction.rs

Three prerequisite features for fdw.
1. allow isolation level, but proceed ignoring it.
2. `attcollation` in `pg_catalog.pg_attribute`
3. allow `Read-write` transaction but proceed as `Read-only` transaction.
1 & 3 are not really implemented here. They are allowed to support Risingwave as pg fdw. The corresponding notices are thrown to notify users.
example:
```
START TRANSACTION ISOLATION LEVEL REPEATABLE READ;
COMMIT;
---------------
NOTICE:  Transaction with given Isolation Level is not supported yet.
For compatibility, this statement will still proceed with RepeatableRead.
NOTICE:  Read-write transaction is not …
```

feat(frontend): add prerequisite feats for fdw

---

Cargo.lock
Cargo.toml

chore: update version to 1.7.3

---

src/connector/src/sink/clickhouse.rs

https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication
Replicated*tree for ck is supported, while the previous batch of sending once per chunk was too small, so here it is modified to send by barriers
</details>

feat(Sink): support ck Replicated*tree

---

java/connector-node/risingwave-connector-test/src/test/java/com/risingwave/connector/sink/elasticsearch/EsSinkTest.java
java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/EsSink.java
java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/EsSinkConfig.java
java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/EsSinkFactory.java
src/connector/src/sink/elasticsearch.rs
src/connector/src/sink/remote.rs

https://github.com/risingwavelabs/risingwave/issues/15626
Add option index_column
This option is mutually exclusive with `index`, and only one can and must be set; when index is set, the write index of es is `index`, and when index_column is set, the index of es is the value of this column
Note: the column corresponding to index_column must be of type `string`, and since es sink defaults to the first column as key, it is not recommended that this column be placed in the first column
</details>

feat(Sink): support es dynamic index

---

ci/scripts/check.sh
ci/scripts/release.sh
src/connector/src/lib.rs

Resolve https://github.com/risingwavelabs/risingwave/issues/15970
</details>

fix: compile err in release build of risectl (#15412)

---

src/common/src/config.rs
src/config/example.toml
src/object_store/src/object/mod.rs

Previously the only way to switch whether or not to use opendal for s3 is via a env. In some cases, like kube-bench, it requires code changes to pass env for the cluster so I think it is more intuitive to make it a developer config.
</details>

chore: expose a config to switch to opendal for s3 backend

---

src/meta/src/barrier/info.rs
src/meta/src/barrier/mod.rs
src/meta/src/barrier/recovery.rs
src/meta/src/manager/metadata.rs

When migrating actors, when there is no enough worker node, we wait in a loop to wait for new worker node to join. Previously in each loop we list the active streaming nodes and try to generate a new migration plan. The listed active streaming nodes will be changed when there is new worker node joined. In https://github.com/risingwavelabs/risingwave/pull/15033, we change to pass a fixed snapshot of worker nodes, and then we cannot get the newly joined node. 
In this PR, we change to wait for the newly joined node. We pass the `ActiveStreamingWorkerNodes` to the `migrate_actors` method, and we wait for newly joined nodes …

fix(meta): wait for new worker join in migrate workers

---

Cargo.lock

We have accumulated 22 ignores. Some of them are no longer necessary and it is better to keep this list at minimal.
Job definition from https://github.com/risingwavelabs/risingwave/network/updates/806296346
`.job["ignore-conditions"] | sort_by(.["updated-at"])`
@xxchan Could you help review this list and see whether each entry is still valid or not?
```
[
{
"dependency-name": "thiserror",
"source": "@dependabot ignore command",
"update-types": null,
"updated-at": "2023-08-16T18:46:19.000Z",
"version-requirement": "> 1.0.44"
},
{
"dependency-name": "anyhow",
"source": "@dependabot ignore command",
"update-types": null, …
```

chore(deps): Bump `thiserror` and `anyhow` to unignore them from dependabot

---

src/meta/src/barrier/info.rs
src/meta/src/barrier/mod.rs
src/meta/src/barrier/recovery.rs
src/meta/src/manager/metadata.rs

Resolve https://github.com/risingwavelabs/risingwave/issues/15981
</details>

fix: wait for new worker join in migrate workers (#15967)

---

src/storage/backup/integration_tests/common.sh

The test started to fail after #15893.
</details>

fix(test): ensure cluster is stopped

---

src/connector/src/source/kinesis/source/reader.rs

fix: handle kinesis unhandled error: InternalError

---

src/connector/src/source/kinesis/source/reader.rs

resolve https://github.com/risingwavelabs/risingwave/issues/15997
</details>

fix: handle kinesis unhandled error: InternalError (#15979)

---

src/batch/src/task/context.rs
src/batch/src/task/env.rs
src/compute/src/server.rs

fix: Disable batch query metrics by default

---

Cargo.lock
src/workspace-hack/Cargo.toml

https://github.com/tokio-rs/tokio/pull/5952
https://github.com/tokio-rs/tokio-metrics/pull/55
</details>

chore(deps): Bump tokio-metrics 0.3.0 -> 0.3.1 to unblock tokio

---

Cargo.lock

chore(deps): Bump socket2 from 0.5.3 to 0.5.6

---

e2e_test/batch/transaction/read_only.slt
src/frontend/src/handler/transaction.rs

https://github.com/risingwavelabs/risingwave/pull/15911/files changed the logic in rw transaction, forbiding the write operations in rw txns, which is widely used in our CI pipeline. So we enable writes again in rw txns in this PR(basically revert the rw txn part).
fix https://github.com/risingwavelabs/risingwave/issues/16011
</details>

fix(frontend): allow write in rw txn for CI usage

---

e2e_test/batch/transaction/read_only.slt
src/frontend/src/handler/transaction.rs

cherry-pick https://github.com/risingwavelabs/risingwave/pull/16012 to `release-1.8`
fix https://github.com/risingwavelabs/risingwave/issues/16011 and https://github.com/risingwavelabs/risingwave/issues/16015
</details>

fix(frontend): allow write in rw txn for CI usage, cherry pick 16012 to release-1.8

---

src/common/src/config.rs
src/config/example.toml

We have confirmed that opendal will use more memory in compactor than aws sdk during longevity test. Before we dig out the root cause, we should switch back the default to aws sdk first.
</details>

fix: donot use opendal for s3 by default

---

docker/Dockerfile
docker/Dockerfile.hdfs

I don't know why but it seems that `apt update` should be run in the same RUN of `apt install`.
</details>

fix: fix DockerFile

---

src/frontend/src/utils/condition.rs

refer: https://buildkite.com/risingwavelabs/pull-request/builds/45593#018e7b6b-9167-4eca-b878-d5572a85c3a8
</details>

feat(test): add unit test for `self_eq_eliminate`

---

e2e_test/batch/order/test_limit.slt.part
src/sqlparser/src/parser.rs

In PgSQL, a common statement with limit and offset:
```
select * from t limit {num} offset {num}
```
`num` should be constant expr. However, currently we only support a single literal number. As we are recently supporting [fdw](https://github.com/risingwavelabs/risingwave/pull/15968) and cursor, syntax like `limit 5::bigint offset 5::bigint` is required. Since supporting `expr` is much more complicated and might make the frontend parser buggy, here we only support `{num}::bigint`, temporarily.
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly …

feat(frontend): allow type conversion to bigint in limit and offset

---

src/stream/src/executor/mview/materialize.rs

After expose on conflict clause,  ignore conflict should not check old value and delete value are consistent.
</details>

fix(on conflict):  ignore conflict should not check old value and delete value are consistent

---

risedev.yml
src/meta/model_v2/src/lib.rs
src/meta/service/src/stream_service.rs
src/meta/src/barrier/recovery.rs
src/meta/src/controller/fragment.rs
src/meta/src/controller/streaming_job.rs
src/meta/src/stream/scale.rs

feat(meta): add Custom to StreamingParallelism (#16033)

---

src/frontend/src/session.rs
src/utils/pgwire/src/pg_protocol.rs
src/utils/runtime/src/logger.rs

- Log error only once in `pgwire`, to avoid duplicated lines.
- Do not print the current span but only include the span list ([ref](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/format/struct.Json.html#method.with_current_span)) as suggested by @fuyufjh, to avoid duplicated span fields. Preview:
```diff
{
"timestamp": "2023-06-28T17:17:35.404904+08:00",
"level": "DEBUG",
"fields": {
"message": "take snapshot",
"actor_id": 42,
"state": "[Nexmark(NexmarkSplit { split_index: 2, split_num: 4, start_offset: Some(315394) })]"
},
"target": "risingwave_stream::executor::source::source_executor",
-   "span": { …
```

fix(frontend): deduplicate error logs

---

.github/labeler.yml
.github/pr-title-checker-config.json

fix: allow cherry pick as PR title

---

src/object_store/src/object/s3.rs

Previously it only apply to S3-compatible and MinIO, not S3.
</details>

fix(object_store): apply identity_resolution_timeout_s

---

src/meta/src/hummock/compaction/picker/compaction_task_validator.rs
src/meta/src/hummock/compaction/picker/intra_compaction_picker.rs
src/meta/src/hummock/compaction/picker/min_overlap_compaction_picker.rs
src/meta/src/hummock/manager/mod.rs

fix(meta): fix trivial loop bug

---

src/connector/src/source/kafka/enumerator/client.rs

Currently in RW `offset` means last consumed offset, so the offset fetched from Kafka using timestamp offset should be decreased by 1 (later will add 1 back when reading from Kafka).
Fixes #16046.
</details>

fix(source): fix kafka `scan.startup.timestamp.millis` timestamp offset bug

---

src/stream/src/task/stream_manager.rs

Incorrect value was given to `dispatch_num` in #15544.
The impact is the optimization of #14655 doesn't take effect.
</details>

fix: pass correct param

---

ci/scripts/multi-arch-docker.sh

Fix the image tag missing when using buildkite API to trigger the docker pipeline.
</details>

fix: image tag when using api trigger the pipeline

---

src/meta/src/hummock/compaction/picker/compaction_task_validator.rs
src/meta/src/hummock/compaction/picker/intra_compaction_picker.rs
src/meta/src/hummock/manager/compaction_group_manager.rs
src/meta/src/hummock/manager/tests.rs

If picker give a task with only one input-level, and the target-level is also itself, hummock-manager may stay in a dead-loop
</details>

fix(meta): fix pick one sub-level cause dead-loop

---

Cargo.lock
Cargo.toml

chore: update version to 1.7.4

---

e2e_test/udf/rust_udf.slt
src/frontend/src/handler/create_function.rs

fix #16095 
I also fixed a bug where Rust table functions with multiple return columns could not be built. But the fix is entirely done in arrow-udf https://github.com/risingwavelabs/arrow-udf/commit/d134e73767956e015a7206e0902c8e5db742c69b and there is no need to modify risingwave. A new test for this is added in this PR.
</details>

fix(udf): make field name case-insensitive in Rust UDF

---

Cargo.lock
Cargo.toml

chore: update version to 1.8.0

---

risedev.yml
src/risedevtool/src/bin/risedev-compose.rs
src/risedevtool/src/bin/risedev-dev.rs
src/risedevtool/src/config.rs
src/risedevtool/src/service_config.rs
src/risedevtool/src/task/meta_node_service.rs

Close #16127 . #16048 was cherry-picked but depends on #15693. This PR cherry-picked it as well.
</details>

feat(risedev): support starting cluster with sqlite meta backend (#15693)

---

docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose.yml

chore: update image version to 1.8.0

---

ci/workflows/main-cron.yml

TLE: https://buildkite.com/risingwavelabs/main-cron/builds/2271#018ea9d7-7561-4653-ac47-81f2a402add5
</details>

chore(ci): bump deterministic recovery test timeout

---

src/tests/sqlsmith/src/test_runners/diff.rs
src/tests/sqlsmith/src/test_runners/utils.rs

As per title. Skip timeout queries.
</details>

chore(sqlsmith): skip timeout queries

---

src/storage/hummock_test/src/hummock_read_version_tests.rs
src/storage/src/hummock/event_handler/hummock_event_handler.rs
src/storage/src/hummock/store/version.rs

cherry-pick #15811 to `release-1.8`
</details>

perf: avoid sstable info copy in event handler (cherry-pick #15811)

---

src/frontend/src/catalog/system_catalog/rw_catalog/rw_hummock_version.rs
src/storage/Cargo.toml
src/storage/benches/bench_table_watermarks.rs
src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
src/storage/hummock_sdk/src/table_watermark.rs
src/storage/hummock_sdk/src/version.rs
src/storage/hummock_test/src/hummock_storage_tests.rs
src/storage/src/hummock/event_handler/uploader.rs
src/storage/src/hummock/local_version/pinned_version.rs
src/storage/src/hummock/store/hummock_storage.rs
src/storage/src/hummock/store/version.rs

After #16172
Cherry-pick #15931 to `release-1.8`
</details>

perf(storage): simplify table watermark index (cherry-pick #15931)

---

.github/labeler.yml
.github/workflows/labeler.yml

1. Run single-node tests on any changes to meta source files (*.rs)
2. Rerun labeller on `synchronize` events: https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=synchronize#pull_request
> A pull request's head branch was updated. For example, the head branch was updated from the base branch or new commits were pushed to the head branch. …

chore(ci): add labeller for single node tests

---

docs/shared-buffer.md

Not sure who is the original author, the quip doc doesn't write it. I assume it is @hzxa21. I migrated it from those docs on shared buffer in quip.
I have done some light edits to refer to the shared buffer in a present tense, and to clarify some parts.
For reviewers, please leave comments on outdated parts if any.
</details>

doc: add shared buffer doc

---

src/storage/src/hummock/event_handler/uploader.rs

As discussion https://github.com/risingwavelabs/risingwave/issues/16190#issuecomment-2042004441.
Resolve https://github.com/risingwavelabs/risingwave/issues/16190
</details>

fix(storage): add seal epoch when no data

---

src/meta/node/src/lib.rs
src/meta/src/backup_restore/backup_manager.rs
src/meta/src/hummock/manager/mod.rs
src/meta/src/manager/env.rs
src/object_store/src/object/mod.rs
src/storage/src/hummock/backup_reader.rs
src/storage/src/hummock/store/hummock_storage.rs

Previously meta node doesn't apply object_store_config when creating object store client. 🥵 
</details>

fix(object_store): apply config in meta node

---

src/object_store/src/object/mod.rs
src/storage/src/hummock/iterator/mod.rs

As titled. To remove an unsafe code.
</details>

chore(storage): remove Sync requirement on HummockIterator

---

proto/meta.proto
src/common/common_service/src/observer_manager.rs
src/frontend/src/observer/observer_manager.rs
src/frontend/src/session.rs
src/meta/src/barrier/recovery.rs
src/rpc_client/src/lib.rs

- Related PR: https://github.com/risingwavelabs/risingwave/pull/16014
- Resolve https://github.com/risingwavelabs/risingwave/issues/14569
- After meta recovery, notify frontend nodes to invalidate all connections between frontend and compute nodes.
</details>

feat(frontend): meta notifies frontend after recovery

---

proto/catalog.proto
src/common/src/catalog/mod.rs
src/connector/src/sink/catalog/desc.rs
src/connector/src/sink/catalog/mod.rs
src/frontend/src/catalog/table_catalog.rs
src/frontend/src/optimizer/plan_node/stream_materialize.rs
src/frontend/src/optimizer/plan_node/stream_sink.rs
src/frontend/src/optimizer/plan_node/utils.rs
src/frontend/src/scheduler/distributed/query.rs
src/meta/src/controller/mod.rs

Add frontend changes first. Part of https://github.com/risingwavelabs/risingwave/issues/15587.
We simply add the `create_type` field to the `SinkCatalog` protobuf, since that is sent to meta, and we can determine how to manage the sink using this field.
</details>

feat(frontend): update `SinkCatalog` to support background ddl

---

src/frontend/src/binder/expr/function.rs

- fix https://github.com/risingwavelabs/risingwave/issues/16056
</details>

fix(binder): fix binder panic on function arg wildcard

---

src/connector/src/sink/starrocks.rs

https://github.com/risingwavelabs/risingwave/issues/16036
</details>

fix(sink): fix array<bool> error

---

src/meta/src/hummock/manager/tests.rs
src/storage/hummock_sdk/src/compact.rs

- Add back basic task information for "Finish compaction"
- Only print dropped table ids, not all table ids for a compaction group
- Only print table vnode partition for table ids included in the input
</details>

fix: reduce compactor task logs

---

src/storage/src/hummock/iterator/forward_user.rs
src/storage/src/hummock/iterator/mod.rs
src/storage/src/storage_failpoints/test_iterator.rs

Part of https://github.com/risingwavelabs/risingwave/pull/15666
In the current `UserIterator`, we have some logics to bound the key of an inner iterator to be within an end bound. In this PR, we extract this common logic to a separate `UserKeyEndBoundedIterator` so that we can reuse this logic in future PRs.
</details>

refactor(storage): extract logic of key bounded iterator

---

e2e_test/batch/keyword/user.slt
src/frontend/src/binder/expr/mod.rs
src/sqlparser/src/ast/mod.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/16228
</details>

fix(binder): fix user keyword

---

Cargo.lock
ci/redis-conf/redis-7000.conf
ci/redis-conf/redis-7001.conf
ci/redis-conf/redis-7002.conf
ci/scripts/e2e-redis-sink-test.sh
e2e_test/sink/redis_cluster_sink.slt
src/connector/Cargo.toml
src/connector/src/sink/redis.rs
src/workspace-hack/Cargo.toml

cherry pick 1.8
https://github.com/risingwavelabs/risingwave/issues/16224
</details>

feat(sink): support redis cluster url (#16034)

---

e2e_test/streaming/nexmark_snapshot.slt

To fix https://buildkite.com/risingwavelabs/main-cron/builds/2310#018ec8bd-ae19-4e05-9ec2-5ab7fcf40698.
After #16211, we find flush is missing in a test case.
</details>

fix(test): fix recovery test case

---

src/connector/src/source/base.rs
src/connector/src/source/cdc/split.rs
src/connector/src/source/datagen/split.rs
src/connector/src/source/filesystem/file_common.rs
src/connector/src/source/google_pubsub/split.rs
src/connector/src/source/iceberg/mod.rs
src/connector/src/source/kafka/split.rs
src/connector/src/source/kinesis/split.rs
src/connector/src/source/mqtt/split.rs
src/connector/src/source/nats/split.rs
src/connector/src/source/nexmark/split.rs
src/connector/src/source/pulsar/split.rs
src/connector/src/source/test_source.rs
src/meta/src/stream/source_manager.rs

Previously the `SplitMetaData::update_with_offset` method is confusing if one doesn't know thoroughly about how the source works, causing bugs (#16046). This PR renames the method and its argument to be more comprehensible, so that developers changing source-related code can know better what they are doing.
</details>

refactor(source): rename `update_with_offset(start_offset)` to `update_offset(last_read_offset)`

---

src/ctl/src/cmd_impl/meta/migration.rs
src/meta/model_v2/migration/src/m20230908_072257_init.rs

When the user sets a global increment step, the assumption of the id in the previous initialization script is not valid. Note that directly changing this migration file doesn't introduce any incompatible issues, because the initialization will fail if the user has set the auto increment step.
</details>

fix(sql-backend): specify the initialized self-increment id to avoid the effect of having set the self-increment step

---

.github/dependabot.yml

chore(dependabot): don't update arrow in dependabot

---

ci/scripts/backwards-compat-test.sh
ci/scripts/build.sh
ci/scripts/common.sh
ci/scripts/connector-node-integration-test.sh
ci/scripts/deterministic-e2e-test.sh
ci/scripts/deterministic-it-test.sh
ci/scripts/deterministic-recovery-test.sh
ci/scripts/e2e-pulsar-sink-test.sh
ci/scripts/e2e-source-test.sh
ci/scripts/e2e-test-parallel-for-opendal.sh
ci/scripts/e2e-test-parallel-in-memory.sh
ci/scripts/e2e-test-parallel.sh
ci/scripts/gen-flamegraph.sh
ci/scripts/integration-tests.sh
ci/scripts/java-binding-test.sh
ci/scripts/multi-arch-docker.sh
ci/scripts/regress-test.sh
ci/scripts/release.sh
ci/scripts/run-e2e-test.sh
ci/scripts/run-micro-benchmarks.sh
ci/scripts/run-unit-test.sh
ci/scripts/s3-source-test-for-opendal-fs-engine.sh
ci/scripts/s3-source-test.sh

shellcheck -f diff ci/**/*.sh | git apply
</details>

style: apply shellcheck autofix to sh scripts

---

Cargo.lock

https://github.com/risingwavelabs/risingwave/security/dependabot/155
However the automatic update only checks for `h2 0.3.26`. So updating `h2 0.4.x` manually.
https://github.com/risingwavelabs/risingwave/network/updates/813816612
</details>

chore(deps): Bump h2 from 0.4.3 to 0.4.4

---

src/ctl/src/cmd_impl/debug.rs
src/ctl/src/cmd_impl/debug/fix_table_fragments.rs
src/ctl/src/lib.rs
src/meta/src/manager/catalog/fragment.rs

As title, together with fragment clean ctl tool.
</details>

fix: ignore unregister state table ids of dummy table fragments that are used to replace table

---

src/connector/src/source/cdc/external/mod.rs

Set default to `disable` for backward compatibility
related: #15690 
</details>

fix(postgres-cdc): set default ssl.mode to disable

---

java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzCdcEngine.java
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzCdcEngineRunner.java
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzChangeEventConsumer.java
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzSourceHandler.java
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/JniDbzSourceHandler.java
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/JniDbzSourceRegistry.java
java/connector-node/risingwave-source-cdc/src/main/java/io/debezium/embedded/EmbeddedEngineChangeEventProxy.java
src/connector/src/lib.rs
src/connector/src/source/base.rs
src/connector/src/source/cdc/jni_source.rs
src/connector/src/source/cdc/mod.rs
src/connector/src/source/cdc/source/reader.rs
src/connector/src/source/reader/reader.rs
src/stream/src/common/table/state_table.rs
src/stream/src/executor/source/fetch_executor.rs
src/stream/src/executor/source/fs_source_executor.rs
src/stream/src/executor/source/source_executor.rs
src/stream/src/executor/source/state_table_handler.rs

close https://github.com/risingwavelabs/risingwave/issues/16297
</details>

fix(cdc): commit offset to upstream after checkpoint has commit (cherry-pick)

---

src/meta/src/manager/catalog/fragment.rs

fix: cherry-pick ignore unregister state table ids for dummy table fragments (#16300)

---

src/ctl/src/cmd_impl/meta/migration.rs

fix(sql-backend): fix setval function call for postgreSQL backend in migration

---

ci/scripts/multi-arch-docker.sh

Fix the image tag missing when using buildkite API to trigger the docker pipeline.
</details>

fix: image tag when using api trigger the pipeline (#16089)

---

Makefile.toml
ci/scripts/e2e-source-test.sh
src/cmd_all/scripts/e2e-full-standalone-demo.sh
src/risedevtool/src/risedev_env.rs

trivial part picked from  #16244
</details>

style: minor improvements for source test and risedev

---

src/meta/src/manager/session_params.rs

When the cluster is upgraded from a version where system wide session parameter was not supported, we should warm instead of panic since it's a legitimate operation.
fix  #16292
</details>

fix(compatibility): backwards compatibility of session params

---

src/stream/src/executor/backfill/arrangement_backfill.rs
src/stream/src/executor/backfill/no_shuffle_backfill.rs

Close https://github.com/risingwavelabs/risingwave/issues/16113
Just check for the throttle mutation and apply it.
</details>

feat(streaming): support alter rate limit for arrangement backfill

---

Cargo.lock
Cargo.toml

chore: update version to 1.8.1

---

src/connector/src/parser/json_parser.rs
src/connector/src/parser/unified/json.rs

cdc json parser supports `interval` with `second/seconds...` string format.
</details>

fix: use interval parse instead of from_iso_8601

---

src/ctl/src/cmd_impl/meta/migration.rs

fix(sql-backend): reset worker auto increment id offset for worker table

---

docker/docker-compose-with-sqlite.yml

chore: use v1.8.1 for sqlite docker compose file by default

---

scripts/install/install-risingwave.sh

Remove adhoc version for RisingWave single node. We can just use the latest versions.
</details>

chore(scripts): update install script

---

docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose.yml

wait after the image is built
</details>

chore: update docker image version to 1.8.1

---

src/stream/src/task/barrier_manager.rs

`try_find_root_failure` does not actually find the root failure of recovery,
because we wrap the error with `ErrorKind::UnexpectedExit` which was not taken into consideration. This PR fixes the issue.
I believe it's necessary to introduce e2e tests for this to ensure it works as expected as the codebase evolves. This will also cover issues like #16278. Will attempt to do this in follow-up PRs. …

fix(streaming): really find the root cause of recovery

---

docs/keys.md

[Rendered](https://github.com/risingwavelabs/risingwave/blob/fd019916fd39561aa96883533b424a17483b36a3/docs/keys.md)
Any other keys we should document? Just start off with the two most confusing ones (for me at least, when I first get started with RW).
</details>

doc: document different RisingWave keys

---

src/cmd_all/src/standalone.rs

Close https://github.com/risingwavelabs/risingwave/issues/16323
Tested locally with:
```
RW_SINGLE_NODE_MAX_IDLE_SECS=10 cargo run --bin risingwave playground
```
</details>

fix(cmd_all): immediately exit if `idle_exit_secs` is set, and meta node has stopped

---

ci/scripts/integration-tests.sh

ci: fix poetry in integration test

---

src/meta/src/hummock/mock_hummock_meta_client.rs
src/meta/src/stream/stream_manager.rs
src/rpc_client/src/hummock_meta_client.rs
src/rpc_client/src/meta_client.rs
src/storage/hummock_sdk/src/lib.rs
src/storage/hummock_test/src/bin/replay/replay_impl.rs
src/storage/hummock_test/src/compactor_tests.rs
src/storage/hummock_test/src/failpoint_tests.rs
src/storage/hummock_test/src/hummock_storage_tests.rs
src/storage/hummock_test/src/snapshot_tests.rs
src/storage/hummock_test/src/state_store_tests.rs
src/storage/hummock_test/src/test_utils.rs
src/storage/src/hummock/event_handler/hummock_event_handler.rs
src/storage/src/hummock/event_handler/mod.rs
src/storage/src/hummock/hummock_meta_client.rs
src/storage/src/hummock/store/hummock_storage.rs
src/storage/src/memory.rs
src/storage/src/monitor/monitored_store.rs
src/storage/src/monitor/traced_store.rs
src/storage/src/panic_store.rs
src/storage/src/store.rs
src/storage/src/store_impl.rs
src/stream/src/common/log_store_impl/kv_log_store/mod.rs
src/stream/src/common/table/test_state_table.rs
src/stream/src/task/barrier_manager.rs
src/stream/src/task/barrier_manager/managed_state.rs
src/tests/compaction_test/src/delete_range_runner.rs

Pass `SyncResult` in `commit_epoch` in test, so that when we add more fields in `SyncResult`, the new field can be handled in `commit_epoch` without modifying the code that calls `commit_epoch`.
</details>

refactor(storage): pass sync result in commit epoch in test

---

risedev.yml

Needed to test the virtual compactor locally https://github.com/risingwavelabs/risingwave-extensions/pull/36/
</details>

feat(chore): dev-compactor

---

ci/scripts/run-e2e-test.sh
e2e_test/error_ui/simple/recovery.slt

As described in https://github.com/risingwavelabs/risingwave/pull/16376#issue-2250063434. This PR adds an e2e test to cover it.
</details>

test: add test for root cause identification of recovery

---

integration_tests/snowflake-sink/create_sink.sql
integration_tests/snowflake-sink/create_source.sql
integration_tests/snowflake-sink/snowflake_prep.sql

as titled - actually the only important change is removing the previously configurable `max_batch_row_num` from `create_sink.sql`, the rest is just to improve format / comments.
</details>

chore(snowflake-sink): update spec and related demo sql(s)

---

ci/scripts/e2e-deltalake-sink-rust-test.sh
e2e_test/iceberg/start_spark_connect_server.sh
e2e_test/iceberg/test_case/append_only_with_checkpoint_interval.slt
e2e_test/iceberg/test_case/append_only_with_checkpoint_interval.toml
e2e_test/sink/deltalake_rust_sink.slt
src/common/src/array/arrow/arrow_deltalake.rs
src/common/src/array/arrow/arrow_impl.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/16352
</details>

fix: fix delta decimal array

---

src/meta/src/hummock/compaction/mod.rs
src/meta/src/hummock/manager/compaction.rs
src/meta/src/hummock/manager/mod.rs
src/meta/src/hummock/manager/versioning.rs

cherry-pick #15954. After #16419.
</details>

fix(cherry-pick): refactor emergency picker (#15954)

---

Cargo.lock
Cargo.toml

chore: update Cargo workspace package version to `1.9.0-alpha`

---

src/cmd_all/src/standalone.rs
src/common/metrics/src/monitor/connection.rs
src/meta/node/src/lib.rs
src/meta/node/src/server.rs

Alternative to #16341. Follow the idea of https://github.com/risingwavelabs/risingwave/pull/16341#issuecomment-2063438847. Make @xxchan happy happy.
Resolve #11169.
</details>

fix(standalone): ensure meta service successfully bound to the listen address before starting other services

---

src/meta/src/hummock/manager/tests.rs
src/storage/hummock_sdk/src/compact.rs

cherry-pick #16124. After #16420
</details>

fix(cherry-pick): reduce compactor task log (#16124) 

---

ci/scripts/run-e2e-test.sh

Try to resolve https://github.com/risingwavelabs/risingwave/pull/16397#discussion_r1574765529
</details>

fix(ci): fix killing command of error ui test

---

src/common/fields-derive/Cargo.toml
src/common/fields-derive/src/gen/test_empty_pk.rs
src/common/fields-derive/src/gen/test_no_pk.rs
src/common/fields-derive/src/gen/test_output.rs

Seems these three tests fail in my local env but pass on CI, I don't know why. cc @BugenZhao 
</details>

fix(test): fix fields derive unit test

---

src/connector/src/parser/mysql.rs
src/connector/src/parser/postgres.rs
src/connector/src/parser/util.rs

chore(cdc): use macro to log in cdc

---

src/meta/model_v2/migration/src/m20230908_072257_init.rs
src/meta/model_v2/migration/src/m20240304_074901_subscription.rs

fix: fix missing FK and wrong column type for subscription table (#16468)

---

src/common/src/array/data_chunk.rs
src/common/src/array/stream_chunk.rs
src/common/src/array/stream_chunk_builder.rs
src/stream/src/executor/backfill/cdc/upstream_table/snapshot.rs
src/stream/src/executor/source/mod.rs

Because when producing `StreamChunk` in `StreamChunkBuilder`, we allow, in fact force, consecutive `U-` and `U+` in the same chunk, a stream chunk may have `limit + 1` rows even we have set `max_chunk_size` to `limit`. In this case, `chunk.split(limit)` still produces chunk with size `limit + 1`, and that can cause `limiter.until_n_ready(chunk_size)` fail.
Fixes #16451. …

fix(source): rate limit fail when size of chunk ends with `Update` is limit + 1

---

src/common/src/array/stream_chunk.rs
src/common/src/array/stream_chunk_builder.rs
src/stream/src/common/log_store_impl/in_mem.rs

This PR changes the `StreamChunkBuilder` to ensure the chunks yield out have size less than equal to `max_chunk_size`, or `max_chunk_size + 1` when the ending operation is `Update`. This is not ensured previously actually, if we encountered some inconsistency like `append(UpdateDelete), append(UpdateDelete)`.
And to resolve some misusage, introduces `StreamChunkBuilder::unlimited` that creates a chunk builder without size limit, so that only manual `.take()` calls yield chunks.
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note …

refactor(stream common): introduce `StreamChunkBuilder::unlimited`

---

src/stream/src/executor/source/list_executor.rs

fix(connector): do not panic when file source list fail

---

Cargo.lock

https://github.com/risingwavelabs/risingwave/security/dependabot/165
https://github.com/risingwavelabs/risingwave/security/dependabot/164
#16417 only bumped `0.23.{4,5}`.
Similar problem happened for `h2` before, where `0.3.x` was automatically updated but `0.4.x` required manual update #16276
</details>

chore(deps): Bump rustls 0.21.{10,11} and 0.22.{3,4}

---

src/meta/src/manager/env.rs

doc(meta): add more concrete examples of `prometheus_endpoint` usage

---

src/frontend/src/handler/create_table.rs

Some parameter such as watermark or APPEND ONLY is lost sliently in CDC table.
I am trying to improve the code to handle them(maybe unify the path handling the table with conn and cdc table). But before it, we can return an error to reject those create table statements.
</details>

feat: reject some param for creating cdc table

---

src/frontend/src/optimizer/plan_node/generic/source.rs
src/frontend/src/optimizer/plan_node/stream_fs_fetch.rs
src/frontend/src/optimizer/plan_node/stream_source.rs
src/frontend/src/optimizer/plan_node/stream_source_scan.rs
src/frontend/src/optimizer/plan_node/utils.rs
src/meta/src/barrier/command.rs
src/stream/src/common/table/state_table.rs
src/stream/src/executor/source/source_backfill_state_table.rs
src/stream/src/executor/source/state_table_handler.rs

Signed-off-by: xxchan <xxchan22f@gmail.com>I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).
</details>

doc: add comments for source executor's state table

---

src/common/src/array/stream_chunk_builder.rs
src/connector/src/parser/mod.rs
src/connector/src/source/cdc/split.rs

This PR:
1. Simplifies the CDC transaction control message handling.
2. Simplifies the heartbeat message handling by merge `SourceStreamChunkBuilder` and `HeartbeatChunkBuilder`.
</details>

refactor(cdc source): simplify CDC transaction and heartbeat messages handling

---

e2e_test/source/cdc/cdc.check_new_rows.slt
e2e_test/source/cdc/cdc.share_stream.slt
e2e_test/source/cdc/postgres_cdc.sql
e2e_test/source/cdc/postgres_cdc_insert.sql
e2e_test/source_inline/kafka/shared_source.slt
src/connector/src/parser/postgres.rs

fix the bug found in [previous discussion](https://github.com/risingwavelabs/risingwave/pull/16423#discussion_r1576421593).
</details>

fix(cdc): allow null in list in pg-cdc backfill

---

src/storage/src/mem_table.rs

It was missed before. 💦
Together with some minor renaming to better distinguish `op` from `value`.
</details>

fix(state table): use `value_checker` in `MemTable::delete`

---

src/storage/src/hummock/compactor/compactor_runner.rs
src/storage/src/hummock/iterator/skip_watermark.rs
src/storage/src/monitor/local_metrics.rs

fix https://github.com/risingwavelabs/risingwave/issues/15906#issuecomment-2081424443
close #15906
</details>

fix(storage): correctly update table stats in SkipWatermarkIterator

---

ci/plugins/docker-compose-logs/hooks/post-command
ci/scripts/integration-tests.sh

chore(ci): fix integration test docker logs

---

Cargo.lock
Cargo.toml

chore: update version to 1.8.2

---

ci/scripts/e2e-redis-sink-test.sh
e2e_test/sink/redis_cluster_sink.slt
src/connector/src/sink/redis.rs

error : Sink error: Redis error: Received crossed slots in pipeline- CrossSlot
Instead of using pipe, cluster uses cluster_pipe, which unfortunately doesn't support asynchrony.
</details>

fix(Sink): fix redis  sink Cluster error

---

ci/scripts/check-dylint.sh
lints/Cargo.toml
src/connector/src/sink/mod.rs
src/connector/src/sink/snowflake.rs
src/connector/src/sink/snowflake_connector.rs
src/stream/src/executor/source/list_executor.rs

Lints have failed to compile since https://github.com/risingwavelabs/risingwave/pull/16213, however the CI step does not fail but only emits a warning. This PR fixes that by checking the results of `cargo dylint list`.
Also fix anti-patterns introduced during the period.
</details>

fix(error): fix compiling of lints

---

e2e_test/source_inline/kafka/shared_source.slt

example of the failure
https://buildkite.com/risingwavelabs/pull-request/builds/48716#018f297b-38f1-40e8-9df9-549352e7895c
</details>

fix(test): make kafka/shared_source.slt less flaky

---

integration_tests/kinesis-s3-source/create_mv.sql
integration_tests/kinesis-s3-source/data_check

fix: name mis-align for `kinesis-s3-source` in main cron

---

src/meta/src/hummock/manager/checkpoint.rs

Previously we only collect the object size for ssts added to L0. Now we also collect the object size of ssts added to change log.
Bug found by @xxhZs when testing subscription.
</details>

fix(storage): include change log sst in object size map

---

src/risedevtool/config/src/main.rs
src/risedevtool/src/compose.rs
src/risedevtool/src/task/compactor_service.rs
src/risedevtool/src/task/compute_node_service.rs
src/risedevtool/src/task/frontend_service.rs
src/risedevtool/src/task/meta_node_service.rs
src/risedevtool/src/util.rs

Previously when running `risedev d`, we will add `RUST_BACKTRACE=1` anyway to the command. However, in my environment (mac OS 13.0, Apple M2), when I run `risedev d`, nodes will fail to launch and exit with status 134 with log `libunwind: stepWithCompactEncoding - invalid compact unwind encoding`. Only if I manually remove the code that sets the env var, or run in release mode, the nodes can be launched successfully.
In this PR, I added a new risedev configure option to determine whether to disable backtrace so that the configuration can be persisted and any developers with similar problem don't have to always manually …

chore(risedev): provide option to disable backtrace

---

.github/workflows/cherry-pick-to-release-branch.yml

chore: update cherry pick bot to release-1.9

---

src/meta/model_v2/migration/src/m20240506_112555_subscription_partial_ckpt.rs

https://github.com/risingwavelabs/risingwave/pull/16563#discussion_r1591026351
</details>

fix(meta): Delete first and then rebuild for subscription modle v2 table

---

ci/scripts/run-meta-backup-test.sh

fix(test): install sqlite in ci script

---

src/storage/hummock_sdk/src/change_log.rs
src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs

Previously we will drop the change log of a table if the table has no new change log in the version delta. However, version delta can come from compaction, which won't add any new change log, and unexpectedly drop the change log. In this PR, the drop logic is only for cases when there is a new committed epoch.
</details>

fix(storage): fix unexpected dropping change log on compaction version delta

---

ci/scripts/run-meta-backup-test.sh

fix(test): set missing env var for ci test script

---

dashboard/components/Relations.tsx
dashboard/lib/api/api.ts
dashboard/lib/api/fetch.ts
dashboard/lib/api/streaming.ts
src/meta/src/controller/catalog.rs
src/meta/src/dashboard/mod.rs
src/meta/src/manager/catalog/database.rs
src/meta/src/manager/catalog/mod.rs

As title. Closes #16556
Before this PR I tried to introduce a dedicated proto message for dashboard, as described in #16556, but it turns out to be too complicated. You may take a look at [eric/dashboard_model](https://github.com/risingwavelabs/risingwave/compare/eric/dashboard_model) if interested. 
</details>

feat: add database and schema in dashboard

---

src/meta/src/manager/catalog/user.rs

fix: fix user manager refcount on startup

---

src/batch/src/error.rs
src/batch/src/executor/group_top_n.rs
src/batch/src/executor/hash_agg.rs
src/batch/src/executor/join/hash_join.rs
src/batch/src/executor/join/lookup_join_base.rs
src/batch/src/executor/join/nested_loop_join.rs
src/batch/src/executor/merge_sort_exchange.rs
src/batch/src/task/env.rs
src/batch/src/task/task_manager.rs
src/common/src/memory/alloc.rs
src/common/src/memory/mem_context.rs
src/common/src/memory/monitored_heap.rs
src/compute/src/memory/config.rs
src/compute/src/server.rs
src/frontend/src/session.rs

- Related issue: https://github.com/risingwavelabs/risingwave/issues/16615
- Add batch memory limit to the `MemoryContext` so that batch queries can know whether they have exceeds the memory limit. In the current implementation, all batch queries will compete for the same memory quota on the same (frontend/compute) node.
- Memory check currently is in the same place as batch query memory monitoring, e.g. Hash Join, Hash Agg, MergeSortExchange.
- For the frontend node, the batch query memory limit is 50% of the frontend node memory. For the compute node, it is 30%  of the compute memory.
Example:
```
dev=>  select …
```

feat: support memory limit for batch queries

---

src/frontend/src/handler/create_source.rs
src/frontend/src/handler/create_table.rs

chore: refactor bind connector props for create source and create table with conn

---

src/meta/model_v2/src/subscription.rs
src/meta/src/controller/mod.rs

In the model of sea-orm, it is not allowed to define the column type as an unsigned integer, as this will cause the mapping of the column value to fail.
</details>

fix: fix dependent table id column type in the model

---

src/frontend/src/handler/create_sink.rs

chore: a typo

---

src/object_store/src/object/mod.rs

fix(object_store): fix delete objects timeout config

---

src/sqlparser/src/ast/statement.rs

close https://github.com/risingwavelabs/risingwave/issues/14693
```
dev=> create source my (*, x timestamp as proctime()) with (
connector = 'mysql-cdc',
hostname = 'localhost',
port = '8306',
username = 'test',
password = '',
database.name = 'mydb',
server.id = '5601'
);
Caused by:
sql parser error: CDC source cannot define columns and constraints
``` …

fix(parser):  cdc source cannot define columns and constraints

---

src/frontend/planner_test/tests/testdata/output/dynamic_filter.yaml
src/frontend/planner_test/tests/testdata/output/expr.yaml
src/frontend/planner_test/tests/testdata/output/over_window_function.yaml
src/frontend/planner_test/tests/testdata/output/subquery.yaml
src/frontend/planner_test/tests/testdata/output/with_ordinality.yaml
src/frontend/src/optimizer/plan_node/logical_join.rs

I'm planning to add more information in the user-doc regarding how to fix this error.

chore: replace the rfc link in nested-loop errors with the user doc link

---

src/frontend/planner_test/tests/testdata/output/agg.yaml
src/frontend/planner_test/tests/testdata/output/cse_expr.yaml
src/frontend/src/expr/agg_call.rs
src/frontend/src/optimizer/plan_node/logical_agg.rs
src/frontend/src/optimizer/plan_node/logical_over_window.rs

Previously we have almost duplicated code in `LogicalAggBuilder::try_rewrite_agg_call` and `LogicalOverWindowBuilder::try_rewrite_window_function`, this PR merge the logic so that future updates won't miss any of the two.
This closes #11507.
</details>

refactor(optimizer, agg): reuse agg call rewriting logic between agg and over window

---

e2e_test/sink/sink_into_table/specify_column.slt
src/frontend/src/catalog/table_catalog.rs
src/frontend/src/handler/create_mv.rs
src/frontend/src/handler/create_sink.rs
src/frontend/src/optimizer/plan_node/stream_sink.rs
src/sqlparser/src/ast/statement.rs

close https://github.com/risingwavelabs/risingwave/issues/16704
</details>

cherry-pick feat: specify column when sink into table (#16587)

---

README.md

- Update banner img in README.md
-  Add `real-time data`
</details>

chore(docs): update banner img in README.md 

---

.github/workflows/auto-update-helm-and-operator-version-by-release.yml

test: https://github.com/risingwavelabs/risingwave/actions/runs/9058431703
</details>

fix: change token and refactor auto-update pipeline

---

src/storage/src/hummock/sstable_store.rs

fix(storage): fix compactor oom by count the memory for cache in compactor

---

src/object_store/src/object/s3.rs

fix(object_store): fix sdk error downcast

---

src/meta/src/controller/streaming_job.rs

Fix #16749 . Related: https://github.com/postgres/postgres/blob/7559d8ebfa11d98728e816f6b655582ce41150f3/src/interfaces/libpq/fe-exec.c#L1304
</details>

fix: avoid panic when auto scaling hit the maximum number of bind parameters in sql backend

---

docker/Dockerfile
docker/Dockerfile.hdfs
docker/aws/Dockerfile

https://buildkite.com/risingwavelabs/docker/builds/15768#018f7693-5d4c-4faf-a21b-a81684250e9a
resolve #16139
24.04 is now the LTS version
</details>

chore: upgrade Ubuntu from 22.04 to 24.04

---

Cargo.lock

This PR bumps madsim-rdkafka to apply https://github.com/madsim-rs/madsim/pull/209.
may be helpful for #16693
</details>

fix(kafka): wrap some rdkafka functions in `spawn_blocking`

---

docker/Dockerfile
docker/Dockerfile.hdfs

Python 3.12 is default in Ubuntu 24.04 and no longer needs to install from third-party registry.
</details>

chore(build): update python3.12 installation in dockerfile

---

src/frontend/src/handler/create_source.rs

fix: bind source do not need pk bug introduced in 16665

---

Cargo.lock
Cargo.toml

chore: update version to 1.9.0

---

src/meta/src/controller/catalog.rs

As title, subscription doesn't have a running streaming job and not present in table `streaming_job`.
</details>

fix: list subscription without filtering in streaming job

---

src/storage/src/hummock/compactor/mod.rs

After #16387, compactor will re-create the meta grpc stream when max parallelism is met, which is unnecessary and will cause task failures. 
</details>

fix(compactor): fix unneccessary compactor meta grpc stream re-creation

---

ci/scripts/run-meta-backup-test.sh

fix meta backup test
</details>

fix(test): fix test script

---

e2e_test/source/cdc/cdc.load.slt
e2e_test/source/cdc/postgres_cdc.sql
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/PostgresValidator.java

close https://github.com/risingwavelabs/risingwave/issues/16677
</details>

fix(postgres-cdc): fix validation of PK with uppercase

---

docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

chore: update docker image version to v1.9.0

---

java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java

Lower the log level
</details>

chore(jdbc-sink): adjust log level

---

Makefile.toml

Similar to https://github.com/risingwavelabs/risingwave/pull/16755, if `--timings` don't have any overheads, why not also enable it by default locally so that we can check the profile report from time to time?
</details>

feat(risedev): include --timings when compiling

---

ci/scripts/backwards-compat-test.sh

fix(ci): backwards compat test for 1.9 should use etcd

---

src/frontend/src/handler/create_mv.rs
src/frontend/src/optimizer/plan_node/stream_materialize.rs
src/frontend/src/optimizer/plan_node/stream_sink.rs
src/frontend/src/optimizer/plan_node/utils.rs
src/meta/src/rpc/ddl_controller.rs

Instead of manually modifying it in the create mv handler, we can do so earlier, when we first construct the table catalog.
Then we can reuse this code path for background index as well.
Minor:
- meta: If background_ddl is not supported for the type of stream job, we will now return an error.
- frontend: make sure that sink also has backfill nodes, otherwise don't use background ddl for it.
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact …

refactor(frontend): derive `create_type` when generating the table catalog

---

src/stream/src/executor/hash_join.rs

Always log it, because these issues may only be around for a short time. If we missed the chance to log it, we may not catch the root cause in time. We also use log suppression, to ensure not too many records get logged.
cr @lmatz / @fuyufjh for the log suppression idea.
</details>

feat(stream): always log hash join large amplification records

---

src/connector/src/source/filesystem/opendal_source/s3_source.rs

some users using the S3 bucket name with dot `.` and will meet error here because of the invalid bucket name https://github.com/apache/opendal/blame/ac694375da955ea6d3461aee0bfafd5a5d774541/core/src/services/s3/backend.rs#L600-L614
This fix has been included in the https://github.com/risingwavelabs/risingwave/pull/16521 on the main branch. But it also includes some other crate's upgrades. So I'd like to create another PR for it. …

feat: disable s3's virtual_host_style on release-1.9

---

docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

fix: switch back from 1.9.0 to 1.8.2

---

ci/workflows/main-cron.yml

We currently default to arrangement backfill. We can just sunset background-ddl tests, because we already have arrangement backfill background ddl tests.
</details>

chore(ci): remove background-ddl test

---

src/meta/src/hummock/compaction/picker/min_overlap_compaction_picker.rs

as title
fix https://github.com/risingwavelabs/risingwave/issues/16835
</details>

fix(test): fix min_overlap panic

---

src/connector/src/sink/decouple_checkpoint_log_sink.rs
src/connector/src/sink/deltalake.rs
src/connector/src/sink/iceberg/mod.rs
src/connector/src/sink/mod.rs
src/connector/with_options_sink.yaml

Borrowing iceberg related logic to implement delta lake checkpoint decouple
https://github.com/risingwavelabs/risingwave/issues/16546
</details>

feat(sink): support delta lake checkpoint decouple

---

src/frontend/planner_test/tests/testdata/input/short_circuit.yaml
src/frontend/planner_test/tests/testdata/output/expr.yaml
src/frontend/planner_test/tests/testdata/output/short_circuit.yaml
src/frontend/src/expr/mod.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/16837
</details>

refactor(optimizer): simplify short circuit optimization

---

src/stream/src/executor/backfill/arrangement_backfill.rs

- Remove `actor_id`, these are already provided by the actor span.
- Improve logging messages.
- Expose the `finished` logs as `debug` level logs rather than trace. So we can debug if some users encounter backfill stuck.
</details>

refactor(stream): improve arrangement backfill logs

---

Cargo.lock
Cargo.toml

chore: update version to 1.9.1-rc.1

---

ci/scripts/release.sh

#16759 enabled Python UDF and deno UDF on release build by accident. This PR reverts this change.
</details>

fix(build): disable python udf and deno udf on release

---

src/storage/src/hummock/compactor/mod.rs

as title 
Thanks for Wallace
</details>

fix(compactor): fix the calculation of pending_pull_task_count

---

proto/expr.proto
src/common/src/types/to_text.rs
src/expr/impl/src/scalar/string.rs
src/frontend/src/binder/expr/function.rs
src/frontend/src/expr/pure.rs
src/frontend/src/optimizer/plan_expr_visitor/strong.rs
src/tests/regress/data/sql/text.sql

Closes #16792
References:
- https://www.postgresql.org/docs/9.1/functions-string.html#quote_literal
- https://www.postgresql.org/docs/current/datatype-binary.html
- [src/backend/utils/adt/quote.c](https://github.com/postgres/postgres/blob/be5942aee7a012ce7f30bc7a6617903127f29e89/src/backend/utils/adt/quote.c#L64)
</details>

feat(func): impl quote_literal & quote_nullable

---

e2e_test/udf/always_retry_python.slt

Currently this test takes more than 2min to run in ci ([link](https://buildkite.com/risingwavelabs/pull-request/builds/50127#018f9fdb-36f2-4774-a113-4f753b05ccb1/4825-4939)). This PR tries to reduce its run time to ~50s.
</details>

chore(ci): reduce sleep time for `always_retry_python.slt`

---

docker/Dockerfile
docker/Dockerfile.hdfs

to fix the docker build broken by #16761
</details>

fix(build): add openssl and pkg-config to dockerfile

---

src/connector/src/parser/avro/parser.rs
src/connector/src/parser/avro/util.rs
src/connector/src/parser/mod.rs
src/connector/src/parser/plain_parser.rs
src/connector/src/parser/unified/avro.rs
src/connector/src/source/base.rs
src/connector/src/source/cdc/source/reader.rs
src/connector/src/source/common.rs
src/connector/src/source/datagen/source/reader.rs
src/connector/src/source/filesystem/opendal_source/opendal_reader.rs
src/connector/src/source/filesystem/s3/source/reader.rs
src/connector/src/source/google_pubsub/source/reader.rs
src/connector/src/source/kafka/source/reader.rs
src/connector/src/source/kinesis/source/reader.rs
src/connector/src/source/mqtt/source/reader.rs
src/connector/src/source/nats/source/reader.rs
src/connector/src/source/pulsar/source/reader.rs

The motivation is that: I feel confused why `into_chunk_stream` is not shared by all sources. Then I found only S3 connector doesn't use it, and I think it's unnecessary.
Also added some comments on parsers
</details>

refactor(connector): improve common split reader to chunk stream logic

---

ci/workflows/pull-request.yml

To mitigate https://github.com/risingwavelabs/risingwave/issues/15872
Previously deleted in #9619
</details>

ci: add back cargo cache

---

java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/PostgresValidator.java
java/connector-node/risingwave-connector-service/src/main/resources/postgres.properties
java/connector-node/risingwave-source-test/src/test/java/com/risingwave/connector/source/PostgresSourceTest.java

- Check upstream PG version is less than 16, which is the newest supported by Debezizum
close https://github.com/risingwavelabs/risingwave/issues/16697
</details>

fix(cdc): add heartbeat action query to solve WAL accumulation on AWS

---

src/common/src/config.rs
src/storage/hummock_test/src/hummock_read_version_tests.rs
src/storage/src/hummock/event_handler/hummock_event_handler.rs
src/storage/src/hummock/event_handler/mod.rs
src/storage/src/hummock/event_handler/uploader.rs
src/storage/src/hummock/shared_buffer/shared_buffer_batch.rs
src/storage/src/hummock/store/version.rs
src/storage/src/opts.rs

resolve https://github.com/risingwavelabs/risingwave/issues/16916
</details>

feat: cherry-pick only update related read version on flush finish (#16725) to release-1.9

---

scripts/install/install-risingwave.sh

Previously the regex filtered out `vX.Y.Z-rc.1`.
</details>

chore(scripts): Patch regex for install scripts, to allow installing release candidates

---

e2e_test/ddl/show.slt
src/common/src/session_config/mod.rs
src/frontend/src/handler/show.rs

fix: use the search path when show tables

---

src/meta/src/controller/catalog.rs

as title
related to https://github.com/risingwavelabs/risingwave/issues/16881
</details>

fix(storage): fix get_created_table_ids

---

src/common/src/session_config/mod.rs

doc(stream): update `streaming_use_arrangement_backfill` session variable docs

---

src/meta/src/manager/catalog/database.rs

a mimic of https://github.com/risingwavelabs/risingwave/pull/16928
merge into https://github.com/risingwavelabs/risingwave/pull/16288 for fix, note that the secret ref part has not been impl, no need to update the usage part. 
</details>

fix: use dedicated `secret_ref_count` instead of `relation_ref_count`

---

src/common/src/util/stream_graph_visitor.rs
src/ctl/src/cmd_impl/debug/fix_table_fragments.rs
src/meta/src/controller/catalog.rs
src/meta/src/manager/catalog/fragment.rs
src/meta/src/model/mod.rs
src/meta/src/rpc/ddl_controller.rs

chore: deprecate tree_mut in BTreeMapTransaction

---

ci/scripts/release.sh

fix #16938
QQ: how to trigger release on this PR?
</details>

fix(build): install openssl on release

---

src/risedevtool/src/task/docker_service.rs

💦 To improve the bootstrap time.
</details>

feat(risedev): only pull docker image if not exists

---

Cargo.lock
Cargo.toml
src/object_store/src/object/opendal_engine/opendal_object_store.rs

fix(object store): do not call abort when streaming upload finish error and fix azure workload identity

---

src/common/src/config.rs
src/config/example.toml
src/stream/src/executor/hash_join.rs
src/stream/src/from_proto/hash_join.rs

Seems like 10K is too high, even at 2K it can be a problem. Reducing the log level to something lower. But changing the rate of emission to 1 per minute.
Then we also allow it to be configurable.
Closes https://github.com/risingwavelabs/risingwave/issues/16890
</details>

feat(streaming): lower high join amplification logging to > 2048 records, and rate limit at 1 per minute

---

Cargo.lock
Cargo.toml

chore: update version to 1.9.1-rc.2

---

src/connector/src/parser/json_parser.rs
src/connector/src/parser/plain_parser.rs
src/connector/src/parser/unified/upsert.rs
src/connector/src/parser/unified/util.rs

refactor(source): remove some useless indirection

---

ci/workflows/main-cron.yml
ci/workflows/pull-request.yml
e2e_test_slow/udf/always_retry_python.slt

Seems like it can still timeout https://buildkite.com/risingwavelabs/main-cron/builds/2549
</details>

chore(ci): increase timeout for slow e2e tests

---

src/expr/impl/src/udf/external.rs

Improve the udf logs to also include timing.
</details>

feat(expr): add backoff time to logs for udf

---

Cargo.lock
src/sqlparser/Cargo.toml
src/sqlparser/src/parser_v2/data_type.rs

Thanks to maintainer of winnow, we have the crucial feature https://github.com/winnow-rs/winnow/pull/525 and it's released in v0.6.9, just bump to it.
We also remove an unnecessary customized function `fold1`, since the original functionality can meet our requirements with low overhead.
The PR also includes a minor fix to the dependency tokio declaration, to make `cargo test -p risingwave_sqlparser` work. …

chore(deps): use upstream winnow

---

java/connector-node/risingwave-sink-iceberg/src/main/java/com/risingwave/connector/catalog/JniCatalogWrapper.java
src/batch/src/task/task_execution.rs

chore: fix typo and remove deadcode

---

src/compute/src/server.rs
src/storage/compactor/src/server.rs
src/storage/hummock_test/src/compactor_tests.rs
src/storage/src/hummock/compactor/compaction_utils.rs
src/storage/src/hummock/compactor/compactor_runner.rs
src/storage/src/hummock/compactor/context.rs
src/storage/src/hummock/compactor/mod.rs
src/tests/compaction_test/src/delete_range_runner.rs

as title
close https://github.com/risingwavelabs/risingwave/issues/16989
</details>

fix(storage): cherrypick fix compactor task parallelism race

---

ci/scripts/run-backfill-tests.sh
ci/workflows/main-cron.yml
ci/workflows/pull-request.yml
e2e_test/backfill/sink/create_sink.slt
risedev.yml

fix(ci): fix backfill test to use ci kafka

---

Cargo.lock
Cargo.toml
src/object_store/src/object/opendal_engine/opendal_object_store.rs

fix(object store): do not call abort when streaming upload finish error and fix azure workload identity (#16961)

---

.pre-commit-config.yaml

Motivation: I found I frequently forgot fix typos/rustfmt when pushing changes. Checking the CI and fix it is both wasting CI resource and my time. Having a pre-commit hook is helpful to exclude some trivial errors. (And I don't want to run `risedev c` because clippy is slow..)
Note that this is not mandatory but opt-in.
Alternatively we can do something like auto push a fix commit in CI, but some people may not like it. :p …

chore: add precommit hook

---

ci/Dockerfile
ci/scripts/release.sh
docker/Dockerfile
docker/Dockerfile.hdfs
integration_tests/iceberg-sink/Dockerfile

as title.
Test build: https://buildkite.com/risingwavelabs/docker/builds/15879
</details>

chore: upgrade to openjdk17 in dockerfile 

---

src/batch/src/executor/hash_agg.rs

- Related issue https://github.com/risingwavelabs/risingwave/issues/16615
- Add spill at least memory for HashAgg, so the algorithm won't recursively spill.
</details>

feat(batch): add spill at least memory for hash agg

---

src/connector/src/parser/avro/parser.rs
src/connector/src/parser/avro/schema_resolver.rs
src/connector/src/parser/avro/util.rs
src/connector/src/parser/debezium/avro_parser.rs
src/connector/src/parser/json_parser.rs

refactor(source): explain writer_schema and union handling for avro

---

src/meta/src/hummock/compaction/mod.rs
src/meta/src/hummock/manager/compaction.rs

as title
After https://github.com/risingwavelabs/risingwave/pull/15547 , we introduce a new strategy for reorganizing the SST in terms of throughput and size. It is a more intuitive approach. However, in another branch, the base-level target_file_base_size has been altered, which is inconsistent, let us eliminate it.
</details>

feat(compaction): adjust target_file_base calculation for base level

---

src/meta/src/hummock/manager/compaction_group_manager.rs
src/meta/src/hummock/manager/tests.rs

Resolve https://github.com/risingwavelabs/risingwave/issues/17061
Added a unit test to cover the panic case. In the main branch, the unit test will fail with the same error in the issue.
</details>

fix(meta): fix panic on unregistering tables moved to new group

---

e2e_test/sql_migration/check.slt
e2e_test/sql_migration/prepare.slt
src/ctl/src/cmd_impl/meta/migration.rs

feat: support secret in migration script from etcd to sql

---

src/connector/benches/json_vs_plain_parser.rs
src/connector/src/parser/csv_parser.rs
src/connector/src/parser/json_parser.rs
src/connector/src/parser/mod.rs
src/connector/src/parser/plain_parser.rs
src/connector/src/parser/protobuf/parser.rs
src/connector/src/parser/unified/avro.rs
src/connector/src/parser/unified/bytes.rs
src/connector/src/parser/unified/debezium.rs
src/connector/src/parser/unified/json.rs
src/connector/src/parser/unified/kv_event.rs
src/connector/src/parser/unified/maxwell.rs
src/connector/src/parser/unified/mod.rs
src/connector/src/parser/unified/protobuf.rs
src/connector/src/parser/unified/upsert.rs
src/connector/src/parser/unified/util.rs
src/connector/src/parser/upsert_parser.rs

- Remove the `Option` on `type_expected`, because it's always present except for checking `op` for upsert. 
- This helps us removing a lot of dead code in converting different encodings to Datum. This is a large source of confusion when implementing the conversion.
- ~~Added `is_null` for checking `op` instead, which is also more efficient.~~ Checking `op` is dead code. `UpsertChangeEvent` is now removed. …

refactor(source): refactor Access trait and Upsert related code

---

src/expr/impl/src/window_function/buffer.rs

Just a simple renaming, to keep future PR for session window clean.
</details>

refactor(over window): rename `buffer_ref` to `window` to better reflect the semantic

---

src/storage/src/hummock/iterator/backward_user.rs
src/storage/src/hummock/iterator/forward_user.rs

close https://github.com/risingwavelabs/risingwave/issues/16967
Allow executor pass exclude bound for range scan.
</details>

feat(storage): support exclude for scan

---

src/frontend/planner_test/tests/testdata/output/over_window_function.yaml
src/frontend/src/optimizer/plan_node/logical_over_window.rs

As simple as title, fixes #16924.
</details>

chore(over window): improve error message for empty partition by

---

Cargo.lock
src/sqlparser/Cargo.toml

Bump winnow for some new features
Bump borsh to reduce some duplicated deps.
</details>

chore(deps): bump borsh/winnow

---

src/connector/src/sink/kafka.rs
src/connector/src/sink/remote.rs
src/connector/src/source/kafka/mod.rs
src/connector/src/source/reader/reader.rs

fix(connector): don't log config/props that may contain sensitive info

---

src/connector/src/sink/kinesis.rs

As titled. Previously, we call `put_record` and await for delivery for each message one by one, which is slow. In this PR, we change to use `put_records` to add the data in a stream chunk in batch, and we will leverage the async truncate sink writer to asynchronously wait for the delivery, so that the data can be handled more concurrently.
</details>

feat(sink): batch add data to kinesis and async wait for delivery

---

Cargo.lock

foyer disk cache engine got "invalid arguments (code: 22)" on ARM-based targets.
The new foyer version will fix it.
https://github.com/MrCroxx/foyer/pull/554
</details>

fix: upgrade foyer-storage to fix direct io on arm

---

src/batch/src/executor/delete.rs
src/batch/src/executor/generic_exchange.rs
src/batch/src/executor/hash_agg.rs
src/batch/src/executor/hop_window.rs
src/batch/src/executor/insert.rs
src/batch/src/executor/join/chunked_data.rs
src/batch/src/executor/join/hash_join.rs
src/batch/src/executor/join/local_lookup_join.rs
src/batch/src/executor/join/mod.rs
src/batch/src/executor/join/nested_loop_join.rs
src/batch/src/executor/merge_sort_exchange.rs
src/batch/src/executor/row_seq_scan.rs
src/batch/src/executor/table_function.rs
src/batch/src/executor/test_utils.rs
src/batch/src/executor/top_n.rs
src/batch/src/executor/values.rs
src/batch/src/lib.rs

chore(batch): remove crate level expect(dead_code)

---

risedev.yml
src/risedevtool/src/risedev_env.rs
src/risedevtool/src/service_config.rs
src/risedevtool/src/task/meta_node_service.rs

As title, this PR added a new field `application` for docker-backed mysql and pg to To distinguish whether it is as a metastore or cdc. Also support mysql as meta store in risedev in this PR.
</details>

fix: support co-exist for sql backend with cdc and support mysql sql backend in risedev

---

docker/Dockerfile

We don't have a Rust toolchain installed in our docker image. So currently users can not write Rust UDFs in our cloud. It will show the following error.
```
failed to query rows: 
ERROR: Failed to run the query Caused by these errors (recent errors listed first): 
1: failed to build rust function 
2: failed to run `rustup target add wasm32-wasi` 
3: No such file or directory (os error 2) (SQLSTATE XX000)
```
Having a stable Rust toolchain pre-installed in docker image can resolve this problem. But the Rust toolchain is very large. It will bloat our RisingWave image. Therefore, this PR only installs rustup into the image …

feat(build): add rustup to the release image

---

Cargo.lock
src/connector/Cargo.toml
src/connector/src/parser/avro/parser.rs
src/connector/src/parser/avro/util.rs
src/connector/src/parser/debezium/avro_parser.rs
src/connector/src/parser/debezium/simd_json_parser.rs
src/connector/src/parser/json_parser.rs
src/connector/src/parser/mod.rs
src/connector/src/parser/unified/avro.rs
src/connector/src/parser/unified/mod.rs
src/frontend/src/handler/create_source.rs

cherry-pick feat(source): parse avro map into jsonb (#16948)

---

src/connector/src/source/pulsar/source/reader.rs

cherry-pick fix: pulsar error during recovery (#17112)

---

docker/Dockerfile

#17126 cherry-picked #17100 to release-1.9. But 1.9 is using Ubuntu 22.04, which doesn't have rustup in apt. So this PR installs it from rustup.rs instead.
</details>

fix(build): install rustup on ubuntu 22.04

---

Cargo.lock
src/batch/src/executor/mod.rs
src/batch/src/task/task_manager.rs

https://github.com/madsim-rs/madsim/pull/215
</details>

chore(deps): upgrade madsim

---

src/batch/src/executor/join/lookup_join_base.rs

- Related issue https://github.com/risingwavelabs/risingwave/issues/16615
- Fix lookup join memory count, we can release the memory early.
- Do not throw an OOM during lookup join, because we expect lookup join memory usage is low and shouldn't cause OOM.
</details>

fix(batch): fix lookup join memory count

---

.github/workflows/auto-update-helm-and-operator-version-by-release.yml

ci: add signoff in auto-pr

---

ci/scripts/backwards-compat-test.sh

`git checkout -` checkouts to main branch which works for main-cron jobs but not for pre-release test and PR. Because the binary and yaml are mismatch. We should use `RW_COMMIT` instead.
</details>

fix: start new cluster with target commit version in backwards compat test

---

src/storage/backup/integration_tests/common.sh

Fix test, because after #15896 there'll be multiple (MCE, safe epoch).
</details>

fix(test): fix meta backup test

---

src/stream/src/common/table/state_table.rs
src/stream/src/executor/over_window/over_partition.rs

Main-cron e2e parallel in-memory test failed after #16958, which is highly possibly the cause. Let's revert it first since it may not currently required by any user.
</details>

chore: revert "perf(over window): optimize range cache with state table reverse iterator"

---

src/ctl/src/common/hummock_service.rs
src/jni_core/src/hummock_iterator.rs
src/storage/benches/bench_compactor.rs
src/storage/benches/bench_multi_builder.rs
src/storage/hummock_test/src/bin/replay/main.rs
src/storage/src/hummock/iterator/test_utils.rs
src/storage/src/hummock/sstable_store.rs
src/storage/src/store_impl.rs
src/tests/compaction_test/src/delete_range_runner.rs

As title.  Tiny refactor. 💦
</details>

chore(storage): rename field with _v2

---

docs/backfill.md

doc(stream): add docs on initializing the replicated state table

---

ci/scripts/run-backfill-tests.sh
e2e_test/backfill/sink/create_sink.slt

As per title. Otherwise the topic may not have been created yet.
</details>

fix(ci): increase sleep duration before restarting cluster in backfill sink test

---

src/tests/simulation/tests/integration_tests/backfill_tests.rs

test(backfill): adjust the measured progress bounds for backfill test

---

README.md

Not sure how to prevent it from happening again. 2 Options:
* Do not skip trailing space check for README PRs.
* Skip README in trailing space check.
</details>

chore: fix README trailing space ci failure

---

src/frontend/src/handler/create_table.rs

~Encode the `frontend` into error message~
```
dev=> create table supplier (*) from mysql_source table 'mydb.supplier';
1: failed to auto derive table schema
2: pool timed out while waiting for an open connection
```
</details>

refactor(cdc): refine error report when fail to derive table schema

---

src/batch/src/executor/merge_sort_exchange.rs
src/batch/src/executor/order_by.rs

- Fix memory limit for batch sort executor.
- Do not throw an OOM error at SortMergeExecutor, because this is unlikely to trigger an OOM.
- Related issue https://github.com/risingwavelabs/risingwave/issues/16615
</details>

fix(batch): fix memory limit for batch sort executor

---

ci/scripts/run-e2e-test.sh

They keep failing, let @yezizp2012 re-enable them once the root cause is found.
</details>

chore(ci): disable e2e visibility mode tests in single node mode

---

.github/workflows/stale.yml

There are too many inactive PRs now.
</details>

chore: close inactive PRs and allow manual trigger

---

ci/workflows/pull-request.yml
proto/backup_service.proto
src/meta/model_v2/src/secret.rs
src/meta/src/backup_restore/meta_snapshot_builder_v2.rs
src/meta/src/backup_restore/restore_impl/v2.rs
src/storage/backup/src/lib.rs
src/storage/backup/src/meta_snapshot_v2.rs

1. Add a macro to simplify adding new models to metadata backup. Just add a new item in the end of `for_all_metadata_models_v2`.
2. Include `Secret` to metadata backup.
3. Include RW_VERSION in metadata backup manifest.
</details>

fix(meta): include secrets in metadata backup

---

java/pom.xml

close https://github.com/risingwavelabs/risingwave/issues/17231
</details>

chore: bump mysql java library

---

proto/expr.proto
src/expr/core/src/window_function/call.rs
src/expr/core/src/window_function/mod.rs
src/expr/core/src/window_function/session.rs
src/expr/impl/src/window_function/aggregate.rs
src/expr/impl/src/window_function/buffer.rs

This PR introduces session frame definition and supports session frame in `WindowBuffer` structure.
As a brief intro, session frame is very similar to range frame. While instead of `start` and `end` bounds in range frame, session frame has a key concept called `gap`. When appending rows to `WindowBuffer`, the buffer will keep recognizing sessions according to the difference between the newly appended row and previous row. When sliding the current window, the buffer will move the current window to next recognized or recognizing session if needed.
This is the first step to implement the requested Session Window feature. …

feat(over window): WindowBuffer support for session window

---

src/frontend/planner_test/tests/testdata/output/temporal_join.yaml
src/frontend/src/optimizer/plan_node/stream_temporal_join.rs
src/stream/src/executor/temporal_join.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/17241
</details>

fix: cherry pick 17239

---

Cargo.lock
Cargo.toml

chore: update Cargo workspace package version to 1.10.0-alpha

---

.github/workflows/package_version_check.yml

ci: add a github action to ensure no package version regression

---

src/storage/backup/integration_tests/common.sh

Fix regex after a new field introduced in #17125 
</details>

fix(test): fix regex

---

docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

chore: update docker image version to v1.9.1

---

src/meta/src/hummock/manager/compaction.rs

The unscheduled logic is not triggered when the batch compaction fails to get any task. This results in the flag not being cleared, and the same type of compaction being triggered all the time, leading to starvation.
</details>

fix(compactor): fix unschedule groups

---

Cargo.lock
Cargo.toml

chore: update package version to 1.11.0-alpha

---

src/batch/src/executor/row_seq_scan.rs
src/storage/src/table/batch_table/storage_table.rs
src/stream/src/common/table/test_storage_table.rs

This PR adds a public method `batch_chunk_iter_with_pk_bounds` in `StorageTable` to create an `DataChunk`  iterator with the provided `chunk_size`. In its implementation, `chunk_iter_with_pk_bounds` is used, which creates an iterator of `Vec<ArrayRef>` (`ArrayRef` is essentially a column). `RowSeqScanExecutor` is refactored to use this new interface instead of relying on `collect_data_chunk` to convert original row iterator into data chunks.
Though this is a feat from the `StorageTable`'s perspective, it is a pure refactoring from the overall functionality point of view. In other words, this PR won't change any existing …

feat(storage): support data chunk iter in storage table

---

src/meta/model_v2/migration/README.md

chore: update migration doc, add DATABASE_URL env example

---

integration_tests/sqlserver-sink/README.md
integration_tests/sqlserver-sink/docker-compose.yml

test(connector): add integration test for sql server sink

---

src/meta/src/controller/fragment.rs

https://buildkite.com/risingwavelabs/pull-request/builds/52048#01902763-f040-4124-ba63-ae711338a8e4
`resolve actor info failed error=Type Error: i32 unsupported by sqlx-sqlite`
</details>

fix(migration): use correct type I32Array instead of Vec<i32>

---

.github/workflows/cherry-pick-to-release-branch.yml

chore: install cherry pick action for v1.10

---

java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java
src/stream/src/executor/sink.rs

fix(jdbc-sink): relax the check for UPDATE_DELETE op (#17289) (cherry-pick)

---

src/connector/src/sink/big_query.rs
src/connector/with_options_sink.yaml

https://github.com/risingwavelabs/risingwave/issues/17214
</details>

fix(sink): add bigquery append_rows retry times

---

e2e_test/source/cdc/mysql_cdc.sql
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/MySqlValidator.java
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/PostgresValidator.java
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/ValidatorUtils.java

Revert back the modifications to validation in https://github.com/risingwavelabs/risingwave/pull/16986/files
Because MySQL column name is case-insensitive https://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html
close https://github.com/risingwavelabs/risingwave/issues/17292
</details>

fix(mysql-cdc): validate column names in case-insensitive way

---

.github/pr-title-checker-config.json

so that both "cherry pick: XXX" and "cherry pick XXX" can work
</details>

fix: make cherry-pick pr title checker more tolerant

---

Cargo.lock
src/common/src/array/arrow/arrow_impl.rs
src/common/src/hash/key.rs
src/common/src/types/datetime.rs
src/common/src/types/mod.rs
src/common/src/util/value_encoding/mod.rs
src/connector/src/parser/avro/parser.rs
src/connector/src/parser/mysql.rs
src/connector/src/parser/unified/json.rs
src/connector/src/sink/encoder/json.rs
src/connector/src/source/iceberg/mod.rs
src/ctl/src/cmd_impl/meta/migration.rs
src/expr/impl/src/scalar/extract.rs
src/expr/impl/src/scalar/to_char.rs
src/expr/impl/src/scalar/tumble.rs
src/meta/src/controller/mod.rs

We would like to include opendal 0.47 bump (required by azure) in release-1.10. This is the prerequisite. I will cherry-pick #17290 and finally #17198 after this PR. 
</details>

cherry-pick chore: upgrade chrono to 0.4.38 (#17279)

---

proto/catalog.proto
proto/secret.proto
src/connector/src/sink/catalog/desc.rs
src/connector/src/sink/catalog/mod.rs
src/frontend/src/utils/with_options.rs
src/meta/model_v2/src/lib.rs
src/prost/build.rs

move SecretRef to secret.proto for secret management.
Will be cherry-picked to v1.10 to avoid break change
</details>

refactor: move SecretRef to secret.proto

---

src/common/src/config.rs
src/config/example.toml
src/object_store/src/object/opendal_engine/fs.rs
src/object_store/src/object/opendal_engine/opendal_s3.rs
src/object_store/src/object/s3.rs
src/storage/src/hummock/compactor/compactor_runner.rs

We would like to include opendal 0.47 bump (required by azure) in release-1.10. This is the prerequisite. I will cherry-pick #17198 next.
</details>

cherry-pick chore: remove the object_store prefix in the object store config naming (#17290)

---

ci/workflows/main-cron.yml

chore(ci): fix sqlserver labels

---

src/meta/model_v2/migration/src/lib.rs
src/meta/model_v2/migration/src/m20240618_072634_function_compressed_binary.rs

fix(cherry-pick): fix type mismatch of compressed_binary column in function table (#17312)

---

Cargo.lock
Cargo.toml
src/common/src/config.rs
src/config/example.toml
src/connector/src/sink/snowflake_connector.rs
src/object_store/Cargo.toml
src/object_store/src/object/mod.rs
src/object_store/src/object/opendal_engine/azblob.rs
src/object_store/src/object/opendal_engine/fs.rs
src/object_store/src/object/opendal_engine/gcs.rs
src/object_store/src/object/opendal_engine/hdfs.rs
src/object_store/src/object/opendal_engine/obs.rs
src/object_store/src/object/opendal_engine/opendal_object_store.rs
src/object_store/src/object/opendal_engine/opendal_s3.rs
src/object_store/src/object/opendal_engine/oss.rs
src/object_store/src/object/opendal_engine/webhdfs.rs

After #17325 and #17326
</details>

cherry-pick feat: upgrade to opendal 0.47 in object store (#17198)

---

src/common/src/config.rs

doc(common): fix `enable_arrangement_backfill` docs

---

src/risedevtool/src/bin/risedev-dev.rs

`Ready for start up` is not present when docker based mysql get restarted, which leads to the misjudgment that mysql did not start in risedev.
</details>

chore(risedev): fix docker based mysql log ready check pattern

---

src/common/src/util/chunk_coalesce.rs
src/stream/src/common/log_store_impl/kv_log_store/serde.rs

As titled.
Previously, due to the hard size limit of data chunk builder, it may happen that, the UpdateDelete and UpdateInsert of a single update is put at the end of a chunk and at the beginning of the next chunk.
In this PR, we will ensure that the two rows will always be put in the same chunk.
</details>

fix(log-store): ensure UpdateDelete and UpdateInsert in the same chunk

---

src/stream/src/executor/sink.rs

refactor: move some sink param determined in new

---

e2e_test/source/cdc_inline/auto_schema_map_mysql.slt
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzChangeEventConsumer.java
src/connector/src/source/cdc/external/mysql.rs
src/connector/src/source/cdc/external/postgres.rs

Previously we didn't init the upstream MySQL version to the `SchemaDiscovery`, so when it query the `information_schema.statistics`, it [would not select the `expression` column](https://github.com/SeaQL/sea-schema/blob/f03ee2c980cd25a4cfe1a1102dbf1303de6896fe/src/mysql/query/index.rs#L58-L66).
The documentation and example of sea-schema  doesn't reveal this details.
This PR reimplement the auto schema discovery of mysql-cdc, which only discover columns and would not discover indexes and foreign keys. …

fix(mysql-cdc): fix auto schema mapping 

---

e2e_test/source/basic/ttl_table_with_con.slt
src/frontend/src/handler/create_table.rs
src/frontend/src/handler/create_table_as.rs
src/frontend/src/utils/with_options.rs

fix https://github.com/risingwavelabs/risingwave/issues/17380
1. the connector properties should filter the retention_seconds option
2. the table's with option should be get from the optimizer context instead of source catalog. 
</details>

fix: append only table with connector having retention seconds

---

src/common/src/catalog/column.rs
src/connector/src/parser/additional_columns.rs
src/connector/src/parser/mod.rs
src/connector/src/source/manager.rs
src/connector/src/source/reader/desc.rs
src/frontend/src/handler/create_source.rs
src/frontend/src/optimizer/plan_node/stream_source.rs
src/frontend/src/optimizer/plan_node/stream_source_scan.rs

Background: When I'm learning how is `Access` used, I found it's used with `SourceColumnDesc`. Then I checked how it is created, and found some unreasonable usage.
The change is straightforward.
</details>

refactor: minor refactor on source column desc

---

e2e_test/source_inline/kafka/include_key_as.slt

https://buildkite.com/risingwavelabs/pull-request/builds/52660#01904dfc-a3ac-47e9-8cef-507a1e115f72
The order doesn't seem to be fixed:
</details>

test: fix include header flaky test

---

grafana/README.md

I was queried about the question: how to set up a Grafana dashboard in a self-hosted cluster within an existing Grafana & Prometheus. This document would be helpful.
</details>

feat(docs): improve docs of multi-cluster deployment

---

Cargo.lock
Cargo.toml
src/common/src/config.rs
src/config/example.toml
src/connector/src/sink/snowflake_connector.rs
src/object_store/Cargo.toml
src/object_store/src/object/mod.rs
src/object_store/src/object/opendal_engine/azblob.rs
src/object_store/src/object/opendal_engine/fs.rs
src/object_store/src/object/opendal_engine/gcs.rs
src/object_store/src/object/opendal_engine/hdfs.rs
src/object_store/src/object/opendal_engine/obs.rs
src/object_store/src/object/opendal_engine/opendal_object_store.rs
src/object_store/src/object/opendal_engine/opendal_s3.rs
src/object_store/src/object/opendal_engine/oss.rs
src/object_store/src/object/opendal_engine/webhdfs.rs

I think it is better not block 1.10 release while we are investigating the opendal 0.47 issue causing #17432. This PR reverts #17327 and pin the reqsign commit according to #17442 to make sure azure identity resolution can work in release 1.10.
</details>

revert: "cherry-pick feat upgrade to opendal 0.47 in object store (#17198) (#17327)"

---

Cargo.lock
Cargo.toml

As title, for 1.9.2.
</details>

fix(object store): ensure the stability of Azure Blob

---

src/risedevtool/connector.toml

chore(risedev): vaildate java 22

---

src/tests/simulation/src/slt.rs

fix(simulation): do not run background ddl on skipped tests

---

src/storage/src/hummock/event_handler/hummock_event_handler.rs

Since Hummock implements batch report compact tasks, one notification may result in multiple version deltas (corresponding to multiple compact tasks). Therefore, the current implementation causes some version deltas to be ignored and only the last version delta is processed, resulting in incomplete cache refill data.
</details>

fix(storage): fix meta cache refill

---

src/frontend/planner_test/tests/testdata/input/generate_series_with_now.yaml
src/frontend/planner_test/tests/testdata/output/generate_series_with_now.yaml
src/frontend/src/optimizer/plan_node/logical_now.rs

`LogicalNow` didn't handle column pruning, causing mismatch before and after column pruning process. This PR fixes it, which resolves #17461.
</details>

fix(optimizer): fix LogicalNow column pruning

---

src/connector/src/parser/csv_parser.rs

One user asked that why `true` in CSV cannot be parsed😄.
</details>

feat(parser): support `t`, `true`, etc. in csv parser

---

src/batch/benches/hash_join.rs
src/batch/src/executor/join/hash_join.rs

- Related issue https://github.com/risingwavelabs/risingwave/issues/16615
</details>

test(batch): add tests for batch spill hash join

---

Cargo.lock
Cargo.toml

chore: update version to 1.10.0-rc.1

---

docs/developer-guide.md

https://github.com/risingwavelabs/risingwave/issues/17436
My first round of revising the developer guide. Basically I just browsed the doc, and made some trivial changes. Other larger reorganization will be made later.
The main intention is to make it more concise (simplify language and removing unnecessary subtitles), because this is a very long doc, containing quite a few topics.  …

doc: improve developer guide (round 1)

---

src/frontend/src/handler/create_source.rs

fix: remove column id check

---

src/connector/src/sink/mqtt.rs

fix(connector): replace blocking sleep with async sleep in MQTT sink

---

src/common/src/config.rs
src/config/example.toml
src/stream/src/task/stream_manager.rs

To debug tokio-related issues, enabling actor tokio metrics by setting metrics level to Debug will introduce too much not related metrics overhead.
This PR add a new config field to enable actor tokio metrics.
</details>

refactor(config): add config to force enable actor tokio metrics

---

src/batch/benches/hash_agg.rs
src/batch/src/executor/hash_agg.rs

- https://github.com/risingwavelabs/risingwave/issues/16615
- Add units test for spill hash agg.
</details>

test(batch): add unit test for spill hash agg

---

Cargo.lock
Makefile.toml
ci/Dockerfile
ci/build-ci-image.sh
ci/docker-compose.yml
e2e_test/source_inline/kafka/add_partition.slt
e2e_test/source_inline/kafka/avro/alter_source.slt
e2e_test/source_inline/kafka/b.sh
e2e_test/source_inline/kafka/consumer_group.slt
e2e_test/source_inline/kafka/include_key_as.slt
e2e_test/source_inline/kafka/protobuf/alter_source.slt
e2e_test/source_inline/kafka/protobuf/basic.slt
e2e_test/source_inline/kafka/shared_source.slt
src/tests/simulation/Cargo.toml

test: bump sqllogictest to 0.21

---

e2e_test/source/cdc_inline/auto_schema_map_mysql.slt
e2e_test/source/cdc_inline/auto_schema_map_pg.slt
src/connector/src/source/cdc/external/mysql.rs
src/connector/src/source/cdc/external/postgres.rs

fix(cdc): quote postgres primary key and make mysql column name case-insensitive

---

src/stream/src/executor/sink.rs

From my local test, I observed that the current logic of processing stream chunk in sink may produce empty stream chunk. Fixed in this PR by checking non-empty cardinality before pushing to the result vec.
</details>

fix(sink): avoid sinking empty stream chunk

---

src/meta/model_v2/src/object.rs
src/meta/src/controller/catalog.rs

fix: fix the query in get_table_by_name

---

docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

chore: update image version from `v1.9.1` to `v1.10.0-rc.1`

---

.cargo/config.toml

build: use shallow clone for git dependencies

---

src/object_store/src/object/opendal_engine/hdfs.rs

chore: upgrade hdfs builder

---

src/meta/src/rpc/ddl_controller.rs

fix: fix a corner case about sink in creating process

---

src/batch/src/executor/join/mod.rs
src/common/src/util/scan_range.rs
src/frontend/src/optimizer/plan_node/generic/agg.rs
src/frontend/src/optimizer/plan_node/mod.rs
src/frontend/src/optimizer/property/distribution.rs
src/frontend/src/scheduler/distributed/query.rs
src/frontend/src/scheduler/distributed/stage.rs
src/frontend/src/scheduler/local.rs
src/frontend/src/scheduler/plan_fragmenter.rs

Just a pr of water.
</details>

chore: rename `XxxPb` to `PbXxx`

---

src/storage/src/hummock/event_handler/hummock_event_handler.rs

fix(storage): refill all version delta

---

Cargo.lock
Cargo.toml
src/storage/benches/bench_block_cache.rs
src/storage/src/hummock/sstable_store.rs

Cherry pick #17513 
</details>

fix(storage): fix abnormal file cache miss on fetch (#17513)

---

src/meta/model_v2/migration/src/lib.rs
src/meta/model_v2/migration/src/m20240702_080451_system_param_value.rs
src/meta/model_v2/migration/src/m20240702_084927_unnecessary_fk.rs

1. the value of `license_key` will hit the limit length of `value` column when using `MySQL` as the metastore. Changed it to `text`.
2. the unnecessary FKs will fail the drop cascade operation when using `MySQL` :melting_face: . Other backends will not have this problem, the solution is to drop this FK or add an on delete cascade action. Because when we drop, we always check dependencies, deleting these FKs would be a bit safer. …

fix(sql-backend): fix system_parameter value column type and remove unnecessary FKs in mysql metastore

---

src/meta/model_v2/migration/src/lib.rs
src/meta/model_v2/migration/src/m20240702_080451_system_param_value.rs
src/meta/model_v2/migration/src/m20240702_084927_unnecessary_fk.rs

fix(cherry-pick): fix system_parameter value column type and remove unnecessary FKs in mysql metastore (#17535)

---

.github/workflows/stale.yml

ci: fix stale bot scheduled run

---

Cargo.lock
src/batch/Cargo.toml
src/batch/src/spill/spill_op.rs

- Tracking issue: https://github.com/risingwavelabs/risingwave/issues/16615
- Bump opendal to 0.47 for batch spill out.
</details>

feat(batch): bump opendal for batch spill out

---

proto/telemetry.proto
src/meta/node/src/server.rs
src/meta/src/hummock/manager/mod.rs
src/meta/src/telemetry.rs
src/object_store/src/object/mod.rs

feat(telemetry): add object store media type in mete telemetry report

---

Cargo.lock
src/object_store/Cargo.toml
src/object_store/src/object/opendal_engine/hdfs.rs

hdfs will create jvm when start, and this will cause double created issue as connector node also create one.
</details>

fix(object store): try get_or_init jvm before creating hdfs builder

---

src/storage/src/hummock/compactor/compaction_executor.rs

Otherwise, if user allocate less then 1 core to compactor (doable in docker/k8s environment), compactor won't pull any compaction task from meta.
</details>

fix(compactor): make sure compaction worker num is strictly larger than 0

---

src/meta/src/barrier/recovery.rs

The target parallel units may not be unique in the following situations:
1. If some new worker nodes are already utilized in the migration plan and only a portion of the streaming jobs have been migrated to them.
2. Before the completion of migration, the worker nodes expire and are removed. The meta restarts.
3. When additional new worker nodes join, resulting in the migration plan incorporating duplicate target parallel units. Generating this plan is to ensure the distribution of no-shuffle.
Taking the following as an example of the migration plan:
1. `p1` -> `p2`, `p2` is the parallel unit on new worker.
2. `p1` -> …

fix: fix inappropriate assertion in migration

---

Cargo.lock
Cargo.toml
src/common/src/config.rs
src/config/example.toml
src/connector/src/sink/snowflake_connector.rs
src/object_store/Cargo.toml
src/object_store/src/object/mod.rs
src/object_store/src/object/opendal_engine/azblob.rs
src/object_store/src/object/opendal_engine/fs.rs
src/object_store/src/object/opendal_engine/gcs.rs
src/object_store/src/object/opendal_engine/hdfs.rs
src/object_store/src/object/opendal_engine/obs.rs
src/object_store/src/object/opendal_engine/opendal_object_store.rs
src/object_store/src/object/opendal_engine/opendal_s3.rs
src/object_store/src/object/opendal_engine/oss.rs
src/object_store/src/object/opendal_engine/webhdfs.rs

Resolve #17565 
Opendal 0.47.2 has been released and fixed the gcs issue (See #17563)
This PR re-introduces https://github.com/risingwavelabs/risingwave/pull/17327 and upgrades opendal to 0.47.2 in releaes-1.10
</details>

cherry-pick fix: update opendal to 0.47.2 for gcs fix (#17563)

---

README.md
docs/dev/src/intro.md

doc(dev-guide): update link in README to the site

---

Cargo.toml
src/batch/Cargo.toml
src/connector/Cargo.toml
src/object_store/Cargo.toml

- Unify opendal version for all crates to 0.47
</details>

chore(storage): unify opendal version

---

docs/dev/src/SUMMARY.md
docs/dev/src/connector/intro.md
docs/dev/src/connector/source.md
docs/dev/src/design/data-model-and-encoding.md
docs/dev/src/design/meta-service.md
docs/dev/src/design/multi-object-store.md
docs/dev/src/design/mv-on-mv.md
docs/dev/src/design/shared-buffer.md
docs/dev/src/design/state-store-overview.md
docs/dev/src/design/streaming-overview.md

doc(dev-guide): reorg design docs

---

src/risedevtool/src/bin/risedev-dev.rs
src/risedevtool/src/task/kafka_service.rs
src/risedevtool/src/task/schema_registry_service.rs

Before this pr schema registry fail to start. Fixed by setting `KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1`
Correct `SCHEMA_REGISTRY_LISTENERS` because it should listen to the connection inside docker container.
</details>

fix(risedev): correct docker schema registry configurations

---

java/connector-node/risingwave-connector-test/pom.xml
java/connector-node/risingwave-sink-iceberg/pom.xml
java/pom.xml

This reverts commit 5bbb5c83be73a4826cf4c64866576ac9ff2ee81f.
- Revert #17642
</details>

fix(connector): revert  adding hive-exec jar (#17642)

---

proto/hummock.proto
src/ctl/src/cmd_impl/hummock/sst_dump.rs
src/ctl/src/cmd_impl/hummock/trigger_full_gc.rs
src/ctl/src/lib.rs
src/meta/service/src/hummock_service.rs
src/meta/src/hummock/manager/gc.rs
src/meta/src/hummock/manager/timer_task.rs
src/meta/src/hummock/mock_hummock_meta_client.rs
src/rpc_client/src/hummock_meta_client.rs
src/rpc_client/src/meta_client.rs
src/storage/hummock_test/src/vacuum_tests.rs
src/storage/src/hummock/hummock_meta_client.rs
src/storage/src/hummock/sstable_store.rs
src/storage/src/hummock/vacuum.rs

Previously a hummock full GC would always scan the whole hummock data dir in object store. This could lead to performance issues when the total number of object is large, especially now that Hummock time travel is supported.
This PR adds an optional `prefix` when scanning the data dir in object store during full GC.
Note that the periodic auto full GC fired by meta node still doesn't specify the prefix. We can specify a prefix rotation strategy for it later. …

feat(ctl): support prefix in hummock full gc

---

e2e_test/subscription/create_table_and_subscription.slt
e2e_test/subscription/drop_table_and_subscription.slt
e2e_test/subscription/main.py
src/meta/src/controller/catalog.rs
src/meta/src/manager/catalog/mod.rs
src/meta/src/manager/metadata.rs
src/meta/src/stream/mod.rs
src/meta/src/stream/stream_manager.rs

https://github.com/risingwavelabs/risingwave/pull/17664
</details>

cherry-pick fix(meta): Fix sink_into_table causes mv's depended_subscription_ids to be empty. (#17664) to branch release-1.9

---

e2e_test/subscription/create_table_and_subscription.slt
e2e_test/subscription/drop_table_and_subscription.slt
e2e_test/subscription/main.py
src/meta/src/controller/catalog.rs
src/meta/src/manager/catalog/mod.rs
src/meta/src/manager/metadata.rs
src/meta/src/stream/mod.rs
src/meta/src/stream/stream_manager.rs

https://github.com/risingwavelabs/risingwave/pull/17664
</details>

cherry-pick fix(meta): Fix sink_into_table causes mv's depended_subscription_ids to be empty. (#17664) to branch release-1.10.0

---

src/storage/backup/integration_tests/common.sh

fix(test): adapt to ctl change

---

src/connector/src/sink/iceberg/mod.rs

- Fix https://buildkite.com/risingwavelabs/integration-tests/builds/850#0190b18c-e51f-4853-9b06-764ac0bc85c7
- Put S3 relevant properties into the rest catalog.
</details>

fix(iceberg): fix iceerg source with rest catalog

---

src/batch/src/executor/row_seq_scan.rs
src/common/src/util/epoch.rs
src/meta/src/hummock/manager/time_travel.rs

fix 2 issues:
- time travel may create a Epoch earlier than UNIX_RISINGWAVE_DATE_SEC.
- incorrectly retrieving only partial columns from meta store.
</details>

fix(batch): fix time travel issue

---

src/meta/src/barrier/mod.rs
src/meta/src/barrier/progress.rs
src/meta/src/barrier/recovery.rs
src/meta/src/controller/catalog.rs
src/meta/src/controller/streaming_job.rs
src/meta/src/manager/catalog/database.rs
src/meta/src/manager/catalog/mod.rs
src/meta/src/manager/metadata.rs
src/meta/src/manager/streaming_job.rs
src/meta/src/rpc/ddl_controller.rs
src/meta/src/stream/stream_manager.rs

refactor(meta): commit finish streaming job in barrier manager

---

Cargo.lock
Cargo.toml

chore: update version to 1.10.0-rc.2

---

src/frontend/src/optimizer/plan_node/stream_changelog.rs
src/frontend/src/optimizer/plan_node/stream_delta_join.rs
src/frontend/src/optimizer/plan_node/stream_expand.rs
src/frontend/src/optimizer/plan_node/stream_group_topn.rs
src/frontend/src/optimizer/plan_node/stream_hop_window.rs
src/frontend/src/optimizer/plan_node/stream_project.rs
src/frontend/src/optimizer/plan_node/stream_project_set.rs
src/frontend/src/optimizer/plan_node/utils.rs

Some misc cleanup for better readability.
</details>

refactor(optimizer): some clean up for stream nodes' constructors

---

ci/workflows/main-cron.yml

As per title the timeout is flaky.
</details>

chore(ci): bump backfill test timeout

---

src/frontend/src/optimizer/plan_node/generic/dynamic_filter.rs
src/frontend/src/optimizer/plan_node/stream_dynamic_filter.rs
src/stream/src/executor/dynamic_filter.rs

Some methods are moved, some variables are renamed, but no actual logic is changed.
</details>

refactor(dyn-filter): refactor dynamic filter for better readability

---

src/meta/service/src/notification_service.rs

Previously meta will attempt to get the `secret_store_private_key` even when there is no secret and throw error when secret_store_private_key was not set.
</details>

fix(secret): avoid trying to get the secret_store_private_key when there is no secret

---

src/connector/src/sink/encoder/json.rs

- put configs in a struct `JsonEncoderConfig`
</details>

refactor(sink): use `JsonEncoderConfig` for json encoder

---

java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/BulkProcessorAdapter.java
java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/ElasticBulkProcessorAdapter.java
java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/EsSink.java
java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/EsSinkConfig.java
java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/OpensearchBulkProcessorAdapter.java

fix(sink): add es sink max task num

---

ci/workflows/main-cron.yml
e2e_test/s3/fs_source_v2.py
e2e_test/s3/fs_source_v2_new_file.py
src/stream/src/executor/source/list_executor.rs

resolve https://github.com/risingwavelabs/risingwave/issues/17705
</details>

fix: s3_v2 connector cannot read incremental files  (#17702)

---

src/frontend/src/optimizer/plan_node/stream_dynamic_filter.rs
src/frontend/src/optimizer/plan_node/stream_exchange.rs

Derive `condition_always_relax` property of DynamicFilter from column monotonicity property of plan node introduced in #17600.
</details>

feat(dyn-filter): derive `condition_always_relax` from column monotonicity

---

src/storage/src/hummock/sstable/multi_builder.rs

as title
should collect all the result when `finish`
</details>

fix(storage): fix multi builder data loss

---

src/storage/src/hummock/sstable/multi_builder.rs

fix(storage): fix multi builder data loss (cherry pick #17730)

---

Cargo.lock
Cargo.toml

chore: update version to 1.10.0-rc.3

---

docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

chore: update docker image from `v1.10.0-rc.1` to `v1.10.0-rc.3`

---

ci/workflows/main-cron.yml

fix(ci): fix trigger condition for `s3-v2-source-check` step

---

src/batch/src/executor/log_row_seq_scan.rs
src/batch/src/lib.rs
src/common/src/row/mod.rs
src/storage/src/lib.rs
src/storage/src/store.rs
src/storage/src/table/batch_table/storage_table.rs
src/storage/src/table/mod.rs
src/stream/src/common/table/state_table.rs
src/stream/src/executor/batch_query.rs

Previously, when reading log store in subscription, UpdateInsert and UpdateDelete are treated as independent items, and may be not next to each other when merging multiple streams. In this PR, the two rows are combined into a single item in the raw stream, and only split into two rows when we use them in higher level logic.
Some codes are refactored by the way to simplify the code and reduce unnecessary memory allocation when creating temporary OwnedRow and passing the unused key emitted from iterator. …

refactor(storage-table): ensure UpdataInsert emit next to UpdateDelete when reading change log

---

README.md

doc: fix space in README.md

---

src/rpc_client/src/meta_client.rs

To fix flaky test in main-cron: https://buildkite.com/risingwavelabs/main-cron/builds/3020#0190e053-81af-473e-ae99-fb99828f7cda 
The test failed because compute node has not been fully registered yet.
</details>

chore: optimize retry interval for meta client to speed up cluster init

---

src/common/src/config.rs
src/config/example.toml
src/object_store/src/object/mod.rs
src/object_store/src/object/s3.rs

feat(storage): Supports configurable upload part size

---

e2e_test/source_inline/kafka/avro/glue.slt
src/connector/src/parser/mod.rs
src/license/src/feature.rs

feat(source): license check for AWS Glue Schema Registry

---

src/batch/src/executor/join/hash_join.rs

- Fix `LeftNonEquiJoinState` management for left outer join
</details>

fix(batch): fix batch left outer join with equal condition

---

src/storage/hummock_sdk/src/key_range.rs
src/storage/hummock_sdk/src/sstable_info.rs

fix(storage): fix sstable info stripped

---

src/batch/src/executor/order_by.rs
src/common/src/array/arrow/arrow_impl.rs
src/common/src/array/chrono_array.rs
src/common/src/array/proto_reader.rs
src/common/src/hash/key.rs
src/common/src/test_utils/rand_array.rs
src/common/src/types/datetime.rs
src/common/src/types/mod.rs
src/common/src/util/value_encoding/mod.rs
src/connector/codec/src/decoder/avro/mod.rs

refactor(common): rename `Date::with_days` to `with_days_since_ce` for clarity

---

src/risedevtool/src/risedev_env.rs

feat(risedev): allow dbname of pg in risedev

---

src/tests/sqlsmith/src/sql_gen/types.rs

chore(sqlsmith): ban `approx_percentile` from being generated

---

src/risedevtool/src/task/schema_registry_service.rs

https://github.com/risingwavelabs/risingwave/pull/17653#issuecomment-2222066987
</details>

feat(risedev): check both or neither kafka & sr are user-managed

---

Cargo.lock
Cargo.toml

chore: update version to 1.10.0

---

src/common/src/array/arrow/arrow_impl.rs

- It seems this is a bug introduced by a refactoring before
</details>

fix(iceberg): fix decimal type for iceberg source

---

docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

Will merge after `v1.10.0` is released
</details>

chore: update docker image from `v1.10.0-rc.3` to `v1.10.0`

---

src/meta/node/src/server.rs
src/meta/service/src/ddl_service.rs
src/meta/src/barrier/command.rs
src/meta/src/barrier/mod.rs
src/meta/src/barrier/progress.rs
src/meta/src/barrier/recovery.rs
src/meta/src/rpc/ddl_controller.rs
src/meta/src/stream/stream_manager.rs

Previously, the `CreateMviewProgressTracker` is wrapped by a `Arc<Mutex<..>>` in a shared manner. However, most of its usage can be in non-async context within the global barrier manager worker loop. The only exception is when handling the `get_ddl_progress` rpc. 
In this PR, we change to let global barrier manager worker loop own the tracker. The `get_ddl_progress` is handled by sending a request to the worker loop in a request channel and get the response from a oneshot channel.
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release …

refactor(meta): let global barrier manager own create mview tracker

---

src/connector/src/sink/big_query.rs
src/connector/src/sink/clickhouse.rs
src/connector/src/sink/doris.rs
src/connector/src/sink/doris_starrocks_connector.rs
src/connector/src/sink/nats.rs
src/connector/src/sink/redis.rs
src/connector/src/sink/sqlserver.rs

cherry-pick refactor: Use error instead of unwrap (#17777) to branch release-1.10

---

src/stream/src/executor/hash_join.rs

Resolves #17858. See background there.
</details>

fix: remove the log suppression for join amplification

---

src/expr/core/src/scalar/like.rs
src/tests/regress/data/sql/strings.sql

feat:support underline as escape char

---

src/storage/src/hummock/event_handler/refiller.rs
src/storage/src/hummock/iterator/change_log.rs
src/storage/src/hummock/store/version.rs
src/storage/src/monitor/local_metrics.rs

Collect `StoreLocalStatistic` for `iter_log` iter. Suppress the frequent log of `local stats lost` in e2e.
</details>

feat(storage): collect and report iter log local metrics

---

.github/labeler.yml
.github/pr-title-checker-config.json

fix: pr title checker allows `cherrypick`

---

src/meta/src/manager/diagnose.rs

In #17842 when listing source/table/sink definition in diagnostic report, the whole definition would be replaced with the string [REDACTED] if no secret is found in the definition. Otherwise the original definition is printed.
The PR refactors the redaction behavior, by always redacting SqlOptions included in WITH clause and Connector Schema, while leaving the other part as it is. Whether secret is being used becomes irrelevant.
```
TABLE
+----+------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```

refactor(dashboard): redact options when listing definition

---

src/ctl/src/cmd_impl/hummock/list_version.rs
src/ctl/src/cmd_impl/hummock/validate_version.rs
src/frontend/src/catalog/system_catalog/rw_catalog/rw_hummock_version.rs
src/meta/src/hummock/compaction/picker/base_level_compaction_picker.rs
src/meta/src/hummock/compaction/picker/emergency_compaction_picker.rs
src/meta/src/hummock/compaction/picker/intra_compaction_picker.rs
src/meta/src/hummock/compaction/picker/manual_compaction_picker.rs
src/meta/src/hummock/compaction/picker/min_overlap_compaction_picker.rs
src/meta/src/hummock/compaction/picker/space_reclaim_compaction_picker.rs
src/meta/src/hummock/compaction/picker/tier_compaction_picker.rs
src/meta/src/hummock/compaction/picker/tombstone_reclaim_compaction_picker.rs
src/meta/src/hummock/compaction/picker/ttl_reclaim_compaction_picker.rs
src/meta/src/hummock/compaction/selector/level_selector.rs
src/meta/src/hummock/compaction/selector/mod.rs
src/meta/src/hummock/manager/compaction.rs
src/meta/src/hummock/manager/tests.rs
src/meta/src/hummock/manager/timer_task.rs
src/meta/src/hummock/manager/versioning.rs
src/meta/src/hummock/metrics_utils.rs
src/meta/src/hummock/test_utils.rs
src/meta/src/manager/diagnose.rs
src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
src/storage/hummock_sdk/src/level.rs
src/storage/hummock_sdk/src/time_travel.rs
src/storage/hummock_test/src/compactor_tests.rs
src/storage/src/hummock/local_version/pinned_version.rs
src/tests/compaction_test/src/delete_range_runner.rs

Current in `Levels`, `l0` has type `Option<OverlappingLevel>`. However, the `Option` is unnecessary, and in most cases we directly unwrap on it. In this PR, we change to use the `OverlappingLevel` type directly.
</details>

refactor(storage): remove unnecessary wrap L0 with Option in Levels

---

src/compute/src/server.rs
src/frontend/src/session.rs

fix(batch): disable spill directory cleaning when enable_batch = false

---

.github/labeler.yml
ci/scripts/single-node-utils.sh

https://buildkite.com/risingwavelabs/main-cron/builds/3035#01910985-cd9e-4f66-9b4d-5e7b22d813bf
caused by #17870
Also change labeler to append only https://github.com/srvaroa/labeler/tree/master/?tab=readme-ov-file#append-only-mode
</details>

fix(ci): fix single node test

---

src/meta/src/backup_restore/restore.rs
src/meta/src/backup_restore/restore_impl/v1.rs
src/meta/src/backup_restore/restore_impl/v2.rs
src/meta/src/backup_restore/utils.rs

Fix 2 issues in restoring meta backup:
- Support the configuration of object store read timeout
- Suppress the verbose log which can be costly in terms of both CPU time and memory usage.
</details>

fix(ctl): support the configuration of read timeout for restoring meta backup

---

src/stream/src/executor/mod.rs

Found in #17651 , the CNs will panic if we're trying to create sink into table when the cluster is paused. BTW scaling also encountered this issue in one of our cluster's env, but maybe not related. Still need some investigation. 
</details>

fix: fix panic when creating sink into table under pause

---

src/connector/src/sink/encoder/json.rs
src/connector/src/sink/encoder/mod.rs
src/connector/src/sink/formatter/debezium_json.rs
src/connector/src/sink/formatter/mod.rs
src/connector/src/sink/kafka.rs
src/connector/src/sink/mqtt.rs
src/connector/src/sink/nats.rs
src/connector/src/sink/snowflake.rs

cherry-pick #17706 #17693
</details>

feat: cherry pick sink dynamic json type

---

src/frontend/planner_test/tests/testdata/output/agg.yaml
src/frontend/src/optimizer/plan_node/logical_agg.rs

It must be present, otherwise multiple instances of approx percentile's global executor are instantiated, when it should be a singleton.
</details>

fix(frontend): add exchange for two-phase `approx_percentile` agg

---

src/meta/src/backup_restore/meta_snapshot_builder.rs
src/meta/src/backup_restore/restore_impl/v1.rs
src/meta/src/model/mod.rs
src/storage/backup/src/meta_snapshot_v1.rs

This PR fixes the issue where the new metadata `secret` was not included in meta backup.
</details>

fix(meta): include secret in meta backup for etcd meta store

---

src/connector/src/sink/sqlserver.rs
src/license/src/feature.rs

Make SQL Server sink a paid tier feature.
</details>

fix(sink): license SQL Server sink

---

src/storage/backup/src/lib.rs

fix #17926
After this fix, the `state_table_info` field from backup taken prior to v1.10 will be empty, which is fine because this field is only used in query backup validation.
</details>

fix(meta): fix meta backup backward compatibility

---

e2e_test/streaming/rate_limit/alter_rate_limit.slt
src/frontend/src/handler/alter_streaming_rate_limit.rs

Users can now do the following for a running MV:
```
alter materialized view mv1 set backfill_rate_limit=0; // pause backfilling
alter materialized view mv1 set backfill_rate_limit=1; // rate limit backfilling
alter materialized view mv1 set backfill_rate_limit=default; // disable backfilling
```
</details>

feat(streaming): support alter mv backfill rate limit

---

src/connector/src/sink/clickhouse.rs
src/license/src/feature.rs

support shared tree for clickhouse, and it is a paid future
</details>

feat(sink): support shared tree for clickhouse

---

Cargo.lock
src/meta/model_v2/migration/Cargo.toml
src/meta/model_v2/migration/README.md

Without this dependency, we can't run the migration.
</details>

fix(migration): include missing `sea-orm` dependency

---

src/frontend/src/handler/create_sink.rs

chore: add col name when type mismatch in sink

---

Cargo.lock
Cargo.toml

- Bump iceberg-rust to a version can reuse a global HTTP client which can increase the performance so much because previously each HTTP request to iceberg storage will initiate its own TCP connection. By reusing the TCP connection, we can greatly improve the performance by **10 times** (**from 1500ms to 150ms** the benchmark is performed in a local MINIO server).
- Resolve https://github.com/risingwavelabs/risingwave/issues/17937
- Code changed in iceberg-rust https://github.com/risingwavelabs/iceberg-rust/blob/24bd5869f2779a8b9786b5a6e1f9723844f5a82c/crates/iceberg/src/io.rs#L438-L440 …

feat(iceberg): reuse http client for iceberg

---

src/meta/src/manager/catalog/mod.rs
src/tests/simulation/tests/integration_tests/recovery/background_ddl.rs

Related #17920 . I've also made adjustments to the background DDL integration tests to decrease the testing duration.
</details>

fix: clear in progress creation tracker when recovery to avoid recovering failed foreground ddl in some corner cases

---

src/meta/src/controller/catalog.rs
src/meta/src/controller/streaming_job.rs

Partially fix #17944 when using sql backend. Two issues:
1. incorrect query on internal tables.
2. should not notify delete about dummy tables when cleaning.
</details>

fix: fix incorrect notification info when sink into table fails

---

src/connector/src/sink/clickhouse.rs

in https://github.com/risingwavelabs/risingwave/issues/17932
we need cherry-pick https://github.com/risingwavelabs/risingwave/commit/ecc84478e5ff76c0450ea6e66b82f0a61deff77a to 1.10, but too many conflicts, and also this is a minor change, so update it directly on the branch
</details>

feat(sink): support ck shared tree

---

src/stream/src/executor/top_n/top_n_cache.rs
src/stream/src/executor/top_n/top_n_plain.rs
src/stream/src/executor/top_n/top_n_state.rs

In this PR, I carefully audited every line in `executor/top_n/top_n_cache.rs` to ensure the cache maintain logic is correct. During this process, I refactored the code and added some necessary comments to make it understandable.
A potential bug of TopN with tie is fixed.
</details>

refactor(topn): audit and refactor `TopNCache` and fix a potential bug

---

integration_tests/clickhouse-sink/clickhouse_prepare.sql
integration_tests/clickhouse-sink/create_sink.sql
integration_tests/clickhouse-sink/sink_check.py
src/connector/src/sink/clickhouse.rs

cherry-pick #17899 
</details>

cherry-pick feat(sink): add Clickhouse Null engine (#17899)

---

src/stream/src/error.rs
src/stream/src/executor/error.rs
src/stream/src/executor/sink.rs
src/stream/src/from_proto/sink.rs
src/stream/src/task/barrier_manager.rs

https://github.com/risingwavelabs/risingwave/issues/17715
</details>

fix(error): add sink_id in sinkerror

---

src/stream/src/executor/aggregation/agg_group.rs
src/stream/src/executor/simple_agg.rs

It's required by `row merge + approx percentile`. On receiving a barrier, we need to construct a full row, merging outputs of approx percentile and normal aggs. As `row merge`, the operator doing this, is entirely stateless, we rely on both sides outputting chunks to construct the full row. If one side doesn't output anything, we can't construct the full row. …

feat(stream): output chunks on every barrier for simple agg

---

Cargo.lock
Cargo.toml
src/batch/Cargo.toml
src/connector/Cargo.toml
src/prost/Cargo.toml
src/prost/build.rs
src/prost/src/lib.rs

See background in https://github.com/risingwavelabs/risingwave/pull/17906#discussion_r1705056943 and https://github.com/risingwavelabs/risingwave/issues/17922.
To reveal the fields, developers should use `SystemParamsReader` as in [`343cdae` (#17936)](https://github.com/risingwavelabs/risingwave/pull/17936/commits/343cdaecdd739415018ac0440a583bfff0c6d421). …

refactor: use a dummy `Debug` impl for `SystemParams` message

---

docs/dev/book.toml
docs/dev/src/design/consistent-hash.md

Just a minor fix for dev docs, as title. I've previewed the generated html in my local env, looks OK.
</details>

fix(docs): display of math equations in dev docs

---

ci/scripts/common.sh
ci/scripts/deterministic-recovery-test.sh
src/stream/src/executor/approx_percentile/global.rs

This will fix the `main-cron` recovery test: https://buildkite.com/risingwavelabs/main-cron/builds/3057#019145c7-8b84-470e-a512-db15b92c82f7.
It happens because after https://github.com/risingwavelabs/risingwave/pull/17945, we output chunks on every epoch in simple agg. `approx_percentile` must do the same as well.
The performance may worsen after this PR, but it is fine. Once we have cache implemented, the approximated percentile can just be read from it.
We also leave the first 10 lines of stack trace, rather than first 3 when filtering recovery test logs. …

fix(stream): let approx percentile output its results every epoch

---

Cargo.lock
src/connector/Cargo.toml

Change `vendored-openssl` to `rustls` for `tiberus`. `rustls` is more friendly for compling, previous [discussion](https://github.com/risingwavelabs/risingwave/pull/16761). After double checking, both of them can work and it was `native-tls` doesn't work for Azure Sql Server. Thanks to @xxchan's [remind](https://github.com/risingwavelabs/risingwave/pull/17429#discussion_r1706310112). …

fix(mssql-cdc): remove vendored-openssl of tiberus

---

src/frontend/src/catalog/system_catalog/pg_catalog/pg_indexes.rs

In PG:
```
postgres=# create table test (id int primary key, name varchar);
create materialized view mv as select * from test;
create index test_index on test (id);
create index mv_index on mv (id);
postgres=# select * from pg_indexes where schemaname <> 'pg_catalog';
schemaname | tablename | indexname  | tablespace |                           indexdef
------------+-----------+------------+------------+---------------------------------------------------------------
public     | test      | test_pkey  |            | CREATE UNIQUE INDEX test_pkey ON public.test USING btree (id)
public     | test      | test_index | …
```

fix(catalog): add mv indexes to pg_indexes

---

e2e_test/source/cdc_inline/sql_server_cdc/sql_server_cdc.slt
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/SqlServerValidator.java
java/connector-node/risingwave-connector-service/src/main/resources/validate_sql.properties

Sql server supports db, column, condition level collation, which decides whether the db, column or condition is case sensitive. In this PR, we only support db level case sensitiveness for now, which means, if a db is created with collation like `COLLATE SQL_Latin1_General_CP1_CS_AS`, the tables in this db will be case sensitive.
</details>

fix(mssql-cdc): support case sensitve db, schema, table name

---

e2e_test/batch/types/map.slt.part
proto/expr.proto
src/common/src/array/list_array.rs
src/common/src/array/map_array.rs
src/expr/impl/src/scalar/array.rs
src/expr/impl/src/scalar/array_positions.rs
src/expr/impl/src/scalar/case.rs
src/expr/impl/src/scalar/cast.rs
src/expr/impl/src/scalar/coalesce.rs
src/expr/impl/src/scalar/external/iceberg.rs
src/expr/impl/src/scalar/field.rs
src/expr/impl/src/scalar/jsonb_record.rs
src/expr/macro/src/gen.rs
src/frontend/src/binder/expr/function/builtin_scalar.rs
src/frontend/src/binder/mod.rs
src/frontend/src/expr/literal.rs
src/frontend/src/expr/mod.rs
src/frontend/src/expr/pure.rs
src/frontend/src/expr/type_inference/cast.rs
src/frontend/src/expr/type_inference/func.rs
src/frontend/src/expr/type_inference/mod.rs
src/frontend/src/optimizer/plan_expr_visitor/strong.rs

part of #17743
- test `to_jsonb(map)`. This was already supported at the beginning (via `ToJsonb` trait)
- support `map_access`. The main work is about type inference.
</details>

feat: support `map_access`

---

src/connector/src/source/kinesis/source/reader.rs

cherry pick fix from #18038
</details>

fix: not bail! on kinesis's state if scan.startup.mode set to timestamp (#18038)

---

src/connector/src/sink/kinesis.rs

Resolve https://github.com/risingwavelabs/risingwave/issues/18021
</details>

fix(sink): handle Kinesis PutRecords partial success and throttle (cherry-pick #17983)

---

Cargo.lock
src/meta/Cargo.toml
src/meta/src/hummock/model/compact_task_assignment.rs
src/meta/src/hummock/model/pinned_snapshot.rs
src/meta/src/hummock/model/pinned_version.rs
src/meta/src/hummock/model/version_delta.rs
src/meta/src/hummock/model/version_stats.rs
src/meta/src/model/mod.rs

Cherrypick #17315 into v1.10.
</details>

 feat(meta): compress the encoded model if it's too large in kv meta store (#17315)

---

src/common/metrics/Cargo.toml

fix(common): fix hyper-014 compile

---

.github/workflows/cherry-pick-to-release-branch.yml

ci: add cherry-pick 2.0

---

e2e_test/streaming/aggregate/two_phase_approx_percentile_merge_stateless_agg.slt
src/frontend/planner_test/tests/testdata/input/agg.yaml
src/frontend/planner_test/tests/testdata/output/agg.yaml
src/frontend/src/optimizer/plan_node/stream_global_approx_percentile.rs
src/frontend/src/optimizer/plan_node/stream_local_approx_percentile.rs
src/frontend/src/optimizer/plan_node/stream_project.rs
src/frontend/src/optimizer/plan_node/stream_row_merge.rs

Add test case to demo the fix. Basically it will panic because the functional dependency is wrongly derived. The output size of the fd did not match the expected input size to the project plan.
That's because the fd previously is just a clone of the lhs. This PR fixes it.
</details>

fix(stream): fix functional dependencies for row merge

---

Cargo.lock
Cargo.toml

chore: update Cargo package version to 2.1.0-alpha

---

e2e_test/batch/types/map.slt.part
src/common/src/array/map_array.rs
src/expr/impl/src/scalar/array.rs
src/frontend/src/binder/expr/mod.rs
src/frontend/src/binder/expr/value.rs
src/frontend/src/binder/select.rs
src/meta/src/controller/rename.rs
src/sqlparser/src/ast/mod.rs
src/sqlparser/src/keywords.rs
src/sqlparser/src/parser.rs

feat: support constructor `MAP {..}` and index operator `m[k]` for map

---

src/common/src/array/iterator.rs
src/common/src/array/mod.rs
src/common/src/test_utils/rand_array.rs
src/common/src/types/macros.rs
src/common/src/types/mod.rs
src/common/src/util/schema_check.rs
src/expr/core/src/expr/value.rs

The problem was recorded at:
https://youtrack.jetbrains.com/issue/RUST-14907/Cannot-resolve-types-generated-in-complex-nested-macrorules-calls
I accidentally discovered that this issue is related to these macro in `common/src/types/macros.rs`:
```
#[macro_export(local_inner_macros)]
macro_rules! for_all_scalar_variants {
($macro:ident $(, $x:tt)*) => {
for_all_variants! { project_scalar_variants, $macro, [ $($x, )* ] }
};
}
#[macro_export]
macro_rules! project_scalar_variants {
($macro:ident, [ $($x:tt, )* ], $( { $data_type:ident, $variant_name:ident, $suffix_name:ident, $scalar:ty, $scalar_ref:ty, $array:ty, …
```

chore: fix RustRover macro expansion

---

.github/workflows/auto-create-doc-issue-by-pr.yml

remind doc team to decide if it is an experimental feature
</details>

chore: remind labeling new features or improvements as experiemental if needed

---

src/frontend/planner_test/tests/testdata/input/agg.yaml
src/frontend/planner_test/tests/testdata/output/agg.yaml
src/frontend/src/binder/expr/function/aggregate.rs

Let the relative_error = 0.01 (`1%`), if it is not set.
</details>

feat(frontend): bind default value for `approx_percentile` relative_error

---

ci/scripts/e2e-source-test.sh
src/meta/src/barrier/mod.rs
src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs

refactor: reduce periodical logs

---

src/frontend/planner_test/tests/testdata/input/agg.yaml
src/frontend/planner_test/tests/testdata/output/agg.yaml
src/frontend/src/optimizer/plan_node/logical_agg.rs

It is not supported. Only single phase two phase agg is supported. Here we just add the testcase to confirm this, and some minor tweaks to the error message.
</details>

test(frontend): test two phase approx percentile with group key is banned

---

e2e_test/batch/types/map.slt.part
proto/expr.proto
src/common/src/array/list_array.rs
src/common/src/array/map_array.rs
src/common/src/array/struct_array.rs
src/common/src/test_utils/rand_array.rs
src/common/src/types/map_type.rs
src/common/src/types/mod.rs
src/common/src/util/value_encoding/mod.rs
src/connector/codec/src/decoder/avro/mod.rs
src/expr/impl/src/scalar/array.rs
src/expr/impl/src/scalar/cast.rs
src/frontend/src/binder/expr/function/builtin_scalar.rs
src/frontend/src/binder/expr/mod.rs
src/frontend/src/binder/expr/value.rs
src/frontend/src/expr/mod.rs
src/frontend/src/expr/pure.rs
src/frontend/src/expr/type_inference/func.rs
src/frontend/src/optimizer/plan_expr_visitor/strong.rs

- support `map_keys/values/entries` (list functions)
- also change `map_from_entries` to accept `list<struct>` to correspond to `map_entires`, and rename previous impl to `map_from_key_values` (In DuckDB, it's just called `map`)
- support `map_length/contains/cat/insert/delete` (element functions)
</details>

feat: support more map functions

---

src/meta/src/controller/fragment.rs

fix: overwrite splite assignment for config change

---

Cargo.toml

Remove unnecessary configurations.
</details>

chore: patch cargo `patch-production` profile

---

ci/workflows/main-cron.yml

fix(ci): fix bad indent of `cassandra sink test`

---

src/frontend/planner_test/tests/testdata/input/agg.yaml
src/frontend/planner_test/tests/testdata/output/agg.yaml
src/frontend/src/optimizer/plan_node/logical_agg.rs

Closes https://github.com/risingwavelabs/risingwave/pull/18085.
Cherry pick.
</details>

 test(frontend): test two phase approx percentile with group key is banned (#18085)

---

e2e_test/streaming/aggregate/shuffle_approx_percentile.slt
e2e_test/streaming/aggregate/two_phase_approx_percentile_merge_stateless_agg.slt
src/frontend/planner_test/tests/testdata/input/agg.yaml
src/frontend/planner_test/tests/testdata/output/agg.yaml
src/frontend/src/optimizer/plan_node/batch_simple_agg.rs

closes https://github.com/risingwavelabs/risingwave/issues/18145.
</details>

feat(frontend): support single phase approx percentile in batch (#18083)

---

src/meta/src/hummock/manager/time_travel.rs

The fix in #18103 is incorrect. See comments.
</details>

fix(meta): fix time travel metadata for partial checkpoint

---

src/stream/src/common/log_store_impl/kv_log_store/mod.rs
src/stream/src/common/log_store_impl/kv_log_store/reader.rs

fix: fix log store truncate offset incorrect check

---

docs/dev/src/benchmark-and-profile/cpu-profiling.md

doc: add docs on profiling on osx

---

docs/dev/src/benchmark-and-profile/cpu-profiling.md

chore: remove whitespace from `ci-profiling.md`

---

docs/dev/src/benchmark-and-profile/cpu-profiling.md
src/connector/src/source/filesystem/opendal_source/mod.rs
src/connector/src/source/reader/reader.rs
src/connector/with_options_source.yaml

introduce `refresh.interval.sec` option for S3, GCS, and POSIX source, allowing config the time interval between two list object actions. The config affects the time delay for discovering new files
</details>

feat: allow config the interval of list files 

---

src/connector/src/sink/iceberg/mod.rs
src/license/src/feature.rs

- add license for iceberg sink with glue
</details>

feat(iceberg): add license for iceberg sink with glue

---

src/frontend/src/handler/create_source.rs

- Use load table v2 instead of v1 to extract columns from iceberg
</details>

refactor(iceberg): use load table v2 to extract iceberg columns

---

src/meta/src/barrier/mod.rs
src/meta/src/barrier/progress.rs
src/meta/src/manager/catalog/database.rs
src/meta/src/manager/catalog/mod.rs
src/meta/src/manager/metadata.rs
src/meta/src/rpc/ddl_controller.rs

refactor: add some comments for MV progress tracking

---

docker/Dockerfile

Just found myself use it frequently during on-call.
</details>

chore(build): add curl & less into docker image

---

e2e_test/batch/basic/join.slt.part
e2e_test/batch/basic/lookup_join.slt.part

This PR is not intended as a fix. It aims to help troubleshoot [these flaky tests](https://github.com/risingwavelabs/risingwave/issues/16796#issuecomment-2306060214). Specifically, I want to tell whether any async op following DDL (e.g. notification) is causing the random test failure.
</details>

chore(test): sleep after flaky test

---

e2e_test/sink/license.slt
src/connector/src/sink/file_sink/opendal_sink.rs
src/license/src/feature.rs

chore: add license to file sink

---

src/frontend/src/stream_fragmenter/mod.rs

resolve https://github.com/risingwavelabs/risingwave/issues/18180
the expected pipeline is
```
(singleton) List Exec -> Dedup -> (parallel) Fetch Exec
```
There is a Dedup exec in the pipeline to remove dup files, so does not make a really bug. 
</details>

fix: make fs list exec singleton

---

src/ctl/src/cmd_impl/meta/migration.rs
src/meta/model_v2/src/worker_property.rs
src/meta/src/controller/cluster.rs

Fix updates and backward compatible issues about rpc host addr of FEs.
</details>

fix: fix fe internal rpc host addr issues

---

Cargo.lock
src/frontend/src/handler/query.rs
src/utils/pgwire/Cargo.toml
src/utils/pgwire/src/pg_extended.rs
src/utils/pgwire/src/pg_protocol.rs
src/utils/pgwire/src/pg_response.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/18246
- Our implicit transaction guard is expected to be dropped after we construct the `PgResponse` and `PgResponse` is expected to be created quickly without waiting for the query to finish. Previously DML and CTAS(create table as select) will calculate the affected rows and must wait until all data has been ingested into the table when constructing `PgResponse`. 
- To resolve this issue, we will defer the calculation of affected rows until after run_one_query, aligning the access pattern with DQL. …

fix(batch): fix CTAS pins snapshot too long

---

.github/workflows/auto-create-doc-issue-by-pr.yml

chore: create an issue in the doc repo if it is a breaking change

---

src/frontend/src/session/cursor_manager.rs
src/meta/src/hummock/manager/versioning.rs
src/storage/hummock_sdk/src/change_log.rs

When we call `list_change_log_epochs`, we return epochs with no data, and the cursor's epochs are pushed one by one, leading to multiple meaningless rpc's
</details>

fix(meta): fix list changed log epoch retrun null epoch

---

src/meta/src/hummock/manager/versioning.rs
src/storage/hummock_sdk/src/change_log.rs

cherry-pick https://github.com/risingwavelabs/risingwave/pull/18273/files
</details>

cherry-pick: fix list changed log epoch retrun null epoch

---

e2e_test/source_inline/kafka/protobuf/basic.slt
e2e_test/source_inline/kafka/protobuf/pb.py
src/frontend/src/handler/create_source.rs

resolve https://github.com/risingwavelabs/risingwave/issues/18274
as requested by customer
</details>

fix: enable upsert protobuf combination (#17624)

---

src/compute/src/server.rs
src/storage/compactor/src/server.rs
src/storage/src/hummock/sstable/writer.rs
src/storage/src/hummock/sstable_store.rs
src/storage/src/hummock/utils.rs

refactor(storage): reorg writer code

---

src/frontend/planner_test/tests/testdata/output/agg.yaml
src/frontend/planner_test/tests/testdata/output/append_only.yaml
src/frontend/planner_test/tests/testdata/output/bushy_join.yaml
src/frontend/planner_test/tests/testdata/output/ch_benchmark.yaml
src/frontend/planner_test/tests/testdata/output/cse_expr.yaml
src/frontend/planner_test/tests/testdata/output/dynamic_filter.yaml
src/frontend/planner_test/tests/testdata/output/lateral_subquery.yaml
src/frontend/planner_test/tests/testdata/output/limit.yaml
src/frontend/planner_test/tests/testdata/output/mv_column_name.yaml
src/frontend/planner_test/tests/testdata/output/nexmark.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_source.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_temporal_filter.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml
src/frontend/planner_test/tests/testdata/output/share.yaml
src/frontend/planner_test/tests/testdata/output/stream_dist_agg.yaml
src/frontend/planner_test/tests/testdata/output/temporal_join.yaml
src/frontend/planner_test/tests/testdata/output/tpch.yaml
src/frontend/src/optimizer/plan_node/logical_agg.rs

noop updates are always yielded from simple agg to materialize which results needless processing.
We now add a project after simple agg to resolve this.
</details>

fix(frontend): add project after simple agg to avoid noop updates

---

e2e_test/source_inline/kafka/protobuf/basic.slt
src/connector/src/source/base.rs
src/frontend/src/handler/create_source.rs

fix(connector): upsert+protobuf source

---

src/connector/src/source/reader/reader.rs

chore: remove unnecessary debug info

---

e2e_test/s3/fs_parquet_source_and_sink.py
e2e_test/s3/fs_source_v2.py
e2e_test/s3/fs_source_v2_new_file.py
src/connector/src/source/filesystem/opendal_source/mod.rs
src/connector/src/source/reader/reader.rs
src/connector/with_options_source.yaml
src/stream/src/executor/source/list_executor.rs

cherry pick #18017  onto release 2.0.
</details>

fix: s3 source cannot read incremental files 

---

src/frontend/src/handler/create_source.rs

fix: allow ENCODE BYTES use generated columns

---

src/meta/model_v2/src/index.rs
src/meta/src/controller/mod.rs

fix: fix column nullable definition for index column properties

---

risedev.yml

fix(risedev): fix risedev

---

java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/ElasticBulkProcessorAdapter.java
java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/EsSink.java
java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/EsSinkConfig.java
java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/OpensearchBulkProcessorAdapter.java
src/risedevtool/connector.toml

https://github.com/risingwavelabs/risingwave/pull/17867
</details>

cherry-pick: cherry-pick 17867 to wangzheng/release-1.10-es-fix

---

e2e_test/batch/transaction/now.slt
e2e_test/batch/transaction/read_only_multi_conn.slt

Fix the flaky test introduced in https://github.com/risingwavelabs/risingwave/pull/18230 after deprecating consistency support for barrier read.
</details>

fix(ci): fix flaky barrier read e2e transaction test

---

src/meta/src/manager/metadata.rs
src/meta/src/stream/scale.rs

Previously the streaming compute nodes are incorrectly used when updating serving vnode mapping in meta node, after scaling.
</details>

fix(meta): correctly update serving vnode mapping after scaling

---

src/storage/src/hummock/compactor/compaction_utils.rs
src/storage/src/hummock/compactor/fast_compactor_runner.rs
src/storage/src/hummock/compactor/iterator.rs
src/storage/src/hummock/sstable_store.rs
src/storage/src/hummock/test_utils.rs
src/storage/src/storage_failpoints/test_iterator.rs
src/storage/src/storage_failpoints/test_sstable.rs

related to https://github.com/risingwavelabs/risingwave/issues/18323
By design, fast compaction only handles single table tasks, so I've rejected it for split sst cases in this pr as well.
In this context, we no longer need to deal with sst boundaries, consisting of：
1. table_ids
2. key_range
</details>

fix(compaction): disable fast compact for split sst

---

src/meta/src/manager/catalog/mod.rs

fix: fix backward data compatible for job status

---

src/compute/src/memory/config.rs
src/compute/src/server.rs

- give 60% of the total memory for the compute node with a serving role.
</details>

feat(compute): give more batch memory for serving node

---

Cargo.lock
src/license/Cargo.toml
src/license/src/feature.rs
src/license/src/lib.rs

re-do changes in https://github.com/risingwavelabs/risingwave/pull/18102 for code struct issues
rely on https://github.com/risingwavelabs/risingwave/pull/18192
</details>

feat(telemetry): add telemetry data point when checking license

---

Cargo.lock
Cargo.toml

chore: update Cargo version

---

src/risedevtool/src/task/configure_tmux_service.rs

Based on #18358, resolve https://github.com/risingwavelabs/risingwave/pull/15893#discussion_r1540529793.
Attempt to kill existing session when launching `risedev-dev`. Only if it fails, prompt users to kill it manually.
</details>

feat(risedev): attempt to kill existing session when launching `risedev-dev`

---

proto/meta.proto
proto/stream_plan.proto
src/connector/src/with_options.rs
src/frontend/src/handler/create_source.rs
src/meta/src/barrier/command.rs
src/meta/src/model/stream.rs

refactor: add some comments for source splits 

---

e2e_test/s3/fs_parquet_source_and_sink.py

fix: parquet test missing comma

---

ci/workflows/pull-request.yml
e2e_test/iceberg/test_case/append_only_with_checkpoint_interval.slt
e2e_test/iceberg/test_case/iceberg_sink_no_partition_append_only_table.slt
e2e_test/iceberg/test_case/iceberg_sink_no_partition_upsert_table.slt
e2e_test/iceberg/test_case/iceberg_sink_partition_append_only_table.slt
e2e_test/iceberg/test_case/iceberg_sink_partition_upsert_table.slt
e2e_test/iceberg/test_case/iceberg_sink_range_partition_append_only_table.slt
e2e_test/iceberg/test_case/iceberg_sink_range_partition_upsert_table.slt
e2e_test/sink/iceberg_sink.slt
integration_tests/iceberg-sink2/python/main.py
src/connector/src/lib.rs
src/connector/src/sink/iceberg/mod.rs
src/connector/with_options_sink.yaml

- https://github.com/risingwavelabs/risingwave/issues/18390
</details>

fix(test): cherry pick 18259 to 2.0

---

proto/catalog.proto
src/common/src/catalog/mod.rs
src/frontend/planner_test/src/lib.rs
src/frontend/src/catalog/table_catalog.rs
src/frontend/src/handler/alter_table_column.rs
src/frontend/src/handler/create_sink.rs
src/frontend/src/handler/create_table.rs
src/frontend/src/handler/create_table_as.rs
src/frontend/src/handler/explain.rs
src/frontend/src/handler/mod.rs
src/frontend/src/optimizer/mod.rs
src/frontend/src/optimizer/plan_node/stream_materialize.rs
src/frontend/src/optimizer/plan_node/utils.rs
src/frontend/src/scheduler/distributed/query.rs
src/meta/model_v2/src/table.rs
src/meta/src/controller/mod.rs
src/sqlparser/src/ast/mod.rs
src/sqlparser/src/keywords.rs
src/sqlparser/src/parser.rs
src/storage/src/filter_key_extractor.rs
src/tests/compaction_test/src/delete_range_runner.rs
src/tests/sqlsmith/src/lib.rs

- Support creating a table with a primary key with iceberg engine. Internally, it will create a sink and a source.
</details>

feat(iceberg): support create table with primary key

---

Cargo.lock
Cargo.toml
src/common/Cargo.toml
src/common/src/telemetry/mod.rs
src/common/src/telemetry/report.rs
src/common/telemetry_event/Cargo.toml
src/common/telemetry_event/src/lib.rs
src/common/telemetry_event/src/util.rs
src/frontend/src/telemetry.rs
src/license/Cargo.toml
src/license/src/feature.rs
src/license/src/lib.rs
src/meta/src/telemetry.rs
src/storage/compactor/src/telemetry.rs
src/stream/src/telemetry.rs

as title, cherry pick https://github.com/risingwavelabs/risingwave/pull/18192 and https://github.com/risingwavelabs/risingwave/pull/18371
redo https://github.com/risingwavelabs/risingwave/pull/18376
</details>

feat(telemetry): add telemetry when checking license (#18371)

---

src/frontend/src/binder/mod.rs
src/frontend/src/binder/relation/table_or_source.rs
src/frontend/src/catalog/table_catalog.rs

- Support DQL for nimtable.
- Replace table with iceberg source if the table engine is iceberg for the batch query.
</details>

feat(iceberg): support dql for nimtable

---

src/frontend/planner_test/tests/testdata/output/cse_expr.yaml
src/frontend/src/optimizer/plan_node/generic/project.rs
src/frontend/src/optimizer/plan_node/stream_project.rs

(cherry picked from commit ed73a52ccf6ee2caa2bd475efb5414eca40cd8a9)
cherry pick #18065
</details>

perf(stream): set `noop_update_hint` when jsonb access exists (#18065)

---

src/frontend/src/handler/create_source.rs
src/frontend/src/handler/create_table.rs

- Hide _row_id for iceberg sources.
</details>

feat(nimtable): nimtable hide iceberg row

---

src/storage/hummock_sdk/src/sstable_info.rs

The assertion is not applicable to time travel, where all fields except sst_id is the default value.
</details>

fix(storage): fix assertion

---

src/stream/src/executor/error.rs

https://github.com/risingwavelabs/risingwave/pull/17969/files/a286d2ef8de2f17697e4f93ff0eff2c40a80b476#r1745038355
</details>

fix(error): fix sinkError and connector error 

---

src/meta/src/backup_restore/restore_impl/v2.rs

Restore order should adhere to the foreign key dependencies.
The issue is revealed by PG backend. The tests based on SQLite backend failed to reveal it.
</details>

fix(backup): fix restore order

---

src/frontend/src/catalog/table_catalog.rs
src/frontend/src/handler/create_index.rs
src/frontend/src/handler/mod.rs
src/frontend/src/handler/util.rs

feat(nimtable): support ban ddl for iceberg engine table

---

src/meta/src/hummock/manager/commit_epoch.rs

after https://github.com/risingwavelabs/risingwave/pull/18431 , `split_sst` will consume two sst_id
</details>

fix(storage): fix commit_epoch new_sst_id_number

---

e2e_test/batch/catalog/pg_settings.slt.part
proto/meta.proto
src/common/src/config.rs
src/common/src/session_config/mod.rs
src/common/src/util/cluster_limit.rs
src/common/src/util/mod.rs
src/config/example.toml
src/frontend/src/catalog/system_catalog/rw_catalog/mod.rs
src/frontend/src/catalog/system_catalog/rw_catalog/rw_worker_actor_count.rs
src/frontend/src/handler/create_mv.rs
src/frontend/src/handler/create_sink.rs
src/frontend/src/handler/create_table.rs
src/frontend/src/meta_client.rs
src/frontend/src/session.rs
src/frontend/src/test_utils.rs
src/meta/node/src/lib.rs
src/meta/node/src/server.rs
src/meta/service/src/cluster_limit_service.rs
src/meta/service/src/lib.rs
src/meta/src/manager/env.rs
src/rpc_client/src/meta_client.rs

cherry-pick: feat: introduce cluster limit (#18383)

---

ci/scripts/e2e-iceberg-sink-v2-test.sh
e2e_test/iceberg/test_case/append_only_with_checkpoint_interval.slt
e2e_test/iceberg/test_case/iceberg_select_empty_table.slt
e2e_test/iceberg/test_case/iceberg_select_empty_table.toml
src/connector/src/source/iceberg/mod.rs

fix(nimtable): cherry-pick fix select empty iceberg table

---

src/common/src/session_config/mod.rs
src/common/src/session_config/sink_decouple.rs

feat(nimtable): implicit flush and no sink decouple

---

docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

chore: update image version to 2.0.0-rc.1

---

src/expr/impl/src/scalar/array.rs

#18073 only added in frontend. Forgot to add in backend
</details>

feat(expr): support map keys/values/entries

---

src/storage/hummock_sdk/src/lib.rs
src/storage/src/hummock/sstable_store.rs

See how far we can get.
#18464 
</details>

perf: optimize memory allocation on building object path

---

e2e_test/sink/license.slt
src/connector/src/sink/file_sink/opendal_sink.rs
src/license/src/feature.rs

chore: make file sink publicly accessible

---

src/common/src/array/arrow/arrow_iceberg.rs

fix(iceberg): fix decimal overflow for iceberg arrow

---

src/expr/impl/src/udf/external.rs

- Use a dedicated tokio runtime to create udf flight client. We meet similar issue in https://github.com/risingwavelabs/risingwave/pull/17764/files
</details>

fix(udf): use a dedicated runtime to create udf flight client

---

src/frontend/src/handler/mod.rs

By allowing indexes on iceberg tables, we can use indexes to speed up delete and update.
</details>

feat(nimtable): enable create index on iceberg table

---

ci/scripts/e2e-cassandra-sink-test.sh

Cassandra only support python 3.11
</details>

fix(ci): fix cassandra ci

---

e2e_test/source/opendal/posix_fs.slt
src/connector/src/source/filesystem/opendal_source/mod.rs
src/connector/src/source/filesystem/opendal_source/opendal_enumerator.rs
src/connector/src/source/reader/reader.rs
src/connector/with_options_source.yaml
src/frontend/src/scheduler/plan_fragmenter.rs

Actually we do not need to expose this configuration item because it can be determined by the glob pattern in the match pattern. 
For example, if match_patten is `a/b/*/d/**/`, we will extract prefix(a/b/) and matcher,  then we first made a full (prefix) list under `a/b/`, and then filtered it according to the matcher. So the origin logic is what we need. …

refactor: revert "#18324 configure whether to recursively scan file source"

---

Cargo.lock
Cargo.toml

chore: update package version

---

src/expr/impl/src/aggregate/approx_percentile.rs
src/frontend/planner_test/tests/testdata/input/agg.yaml
src/frontend/planner_test/tests/testdata/output/agg.yaml
src/frontend/src/binder/expr/function/aggregate.rs
src/stream/src/executor/approx_percentile/global_state.rs

cherry pick https://github.com/risingwavelabs/risingwave/pull/18546 into 2.0.
</details>

 fix(stream): handle 0.0 case of approx percentile, and fix computation of quantile_count (#18546)

---

src/common/src/array/map_array.rs
src/connector/codec/src/decoder/avro/mod.rs
src/connector/src/sink/big_query.rs
src/connector/src/sink/clickhouse.rs
src/connector/src/sink/dynamodb.rs
src/connector/src/sink/encoder/avro.rs
src/connector/src/sink/encoder/bson.rs
src/connector/src/sink/encoder/json.rs
src/connector/src/sink/encoder/proto.rs
src/connector/src/sink/encoder/template.rs
src/connector/src/sink/encoder/text.rs
src/expr/impl/src/scalar/array.rs

and minor refactors
</details>

fix(sink): remove some todo!() with error

---

risedev.yml

As title. Because I usually use `d full` than `d` 😄
</details>

chore: use Postgres meta backend for `risedev d full`

---

ci/scripts/backwards-compat-test.sh
e2e_test/backwards-compat-tests/scripts/utils.sh

fix(test): fix version sort and handle case where release branch is current branch

---

ci/workflows/main-cron.yml
ci/workflows/pull-request.yml
e2e_test/backwards-compat-tests/scripts/utils.sh

Already included in the cherrypick branch to release-2.0: https://github.com/risingwavelabs/risingwave/pull/18564/files.
Just upstreaming it into `main`.
</details>

fix(test): fix `current_branch` for backwards compat test

---

src/meta/src/backup_restore/restore_impl/v2.rs

fix(backup): fix restore order (#18423)

---

ci/docker-compose.yml
docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-hdfs.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml
risedev.yml

https://hub.docker.com/r/vectorized/redpanda is deprecated
</details>

fix: fix message_queue image tag in docker compose

---

src/connector/src/source/kinesis/source/reader.rs

…mestamp`  (#18038)
cherry pick
</details>

fix: not bail! on kinesis if starts with timestamp (#18038)

---

docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

will let a bot to do so going forward
</details>

chore: update image version to v2.0.0

---

src/stream/src/common/table/state_table.rs

Previously `StateTable::seal_current_epoch` contains three parts:
1. flush local store (`local_store.flush().await`)
2. commit table watermark
3. seal local store epoch (`local_store.seal_current_epoch`)
which is unmatched with what the name suggests (intuitively it should only call `local_store.seal_current_epoch` as a wrapper function or sth).
This PR moves 1 and 3 to `commit_inner`, renames `StateTable::seal_current_epoch` to `StateTable::commit_pending_watermark`. …

refactor(state table): cleanup `StateTable::seal_current_epoch`

---

src/connector/src/source/base.rs
src/frontend/src/catalog/catalog_service.rs
src/frontend/src/handler/alter_source_column.rs
src/frontend/src/handler/alter_source_with_sr.rs
src/frontend/src/handler/create_source.rs
src/frontend/src/test_utils.rs
src/meta/service/src/ddl_service.rs
src/meta/src/controller/catalog.rs
src/meta/src/manager/catalog/mod.rs
src/meta/src/rpc/ddl_controller.rs
src/rpc_client/src/meta_client.rs
src/sqlparser/src/ast/statement.rs
src/stream/src/executor/source/source_backfill_executor.rs

refactor: minor refactor on create/alter source

---

src/common/src/hash/consistent_hash/vnode.rs
src/meta/src/manager/sink_coordination/coordinator_worker.rs
src/meta/src/manager/sink_coordination/manager.rs
src/storage/benches/bench_table_watermarks.rs
src/storage/hummock_sdk/src/key.rs
src/storage/hummock_sdk/src/table_watermark.rs
src/storage/hummock_test/src/compactor_tests.rs
src/storage/hummock_test/src/hummock_read_version_tests.rs
src/storage/hummock_test/src/hummock_storage_tests.rs
src/storage/hummock_test/src/state_store_tests.rs
src/storage/hummock_trace/src/opts.rs
src/storage/src/hummock/event_handler/hummock_event_handler.rs
src/storage/src/hummock/event_handler/uploader/mod.rs
src/storage/src/hummock/shared_buffer/shared_buffer_batch.rs
src/storage/src/hummock/sstable/multi_builder.rs
src/storage/src/store.rs
src/stream/src/common/log_store_impl/kv_log_store/mod.rs
src/stream/src/common/log_store_impl/kv_log_store/serde.rs
src/stream/src/common/log_store_impl/kv_log_store/writer.rs

This is a progress towards https://github.com/risingwavelabs/risingwave/issues/15900.
This PR refactors the storage part.
</details>

feat(storage): variable vnode count support

---

src/tests/simulation/tests/integration_tests/recovery/background_ddl.rs

As titile, `KILL <process id>` will return immediately without waiting for the cancel command to take effect, and creating mv before this will fail.
</details>

fix: fix flaky simulation integration test cancel ddl

---

Cargo.lock
src/connector/Cargo.toml
src/connector/src/source/cdc/external/postgres.rs

resolve https://github.com/risingwavelabs/risingwave/issues/18481. required by https://github.com/risingwavelabs/risingwave/pull/18456
</details>

chore(cdc): update sea-schema version to 0.15

---

src/common/src/config.rs
src/config/example.toml

In OpenDAL's implementation, if currency > part numbers, the `FinishMultipartUpload` operation incurs  two IO operations: the first round waits for `task.execute`, and the second waits for all tasks in the batch to complete.
In our scenario, the file in object store has a soft limit of 256MB, and the default part size is 16MB. Therefore, to avoid redundant IO, all parts should be uploaded in parallel, just like the AWS SDK. This PR adjusts the concurrency to 32(at most 512MB file size).
The longevity test passed. …

refactor(object store): OpenDAL write concurrent = 256

---

dashboard/components/Layout.tsx
dashboard/components/RelationGraph.tsx
dashboard/components/Relations.tsx
dashboard/pages/relation_graph.tsx

Minor rename. https://github.com/risingwavelabs/risingwave/pull/18280#discussion_r1767809223
</details>

chore(dashboard): rename relation dependency graph to relation graph

---

src/meta/src/controller/catalog.rs

The original incorrect i32 to u32 conversion causes error in postgres meta backend, but not sqlite meta backend.
</details>

fix(meta): fix type conversion

---

java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/DbzSourceUtils.java

fix(pg-cdc): fix postgres.publication_exist, found in issues#18628

---

Cargo.lock
Cargo.toml

chore: update package version to 1.10.2

---

e2e_test/backwards-compat-tests/scripts/utils.sh

work around https://github.com/risingwavelabs/risingwave/issues/18650#issuecomment-2370004294
more detail in [slack](https://risingwave-labs.slack.com/archives/C034TRN6A49/p1727143882804699)
</details>

fix(test): fix backward compatibility test

---

ci/scripts/connector-node-integration-test.sh

fix(ci): fix java connector node ci (#18229)

---

e2e_test/s3/fs_source_v2.py

regarding https://buildkite.com/risingwavelabs/main-cron/builds/3315#01921f9d-f855-4ef3-ad51-09c0c4f98485
</details>

fix: s3 source main-cron

---

ci/scripts/common.sh
ci/scripts/e2e-cassandra-sink-test.sh
e2e_test/sink/cassandra_sink.slt
java/connector-node/risingwave-sink-cassandra/src/main/java/com/risingwave/connector/CassandraConfig.java
java/connector-node/risingwave-sink-cassandra/src/main/java/com/risingwave/connector/CassandraSink.java
java/connector-node/risingwave-sink-cassandra/src/main/java/com/risingwave/connector/CassandraUtil.java

cherry-pick fix: a few fixes to Cassandra e2e test

---

ci/scripts/backwards-compat-test.sh

Same as https://github.com/risingwavelabs/risingwave/pull/18562/files#diff-2cd274f1db89f49e0ff90c98f5b8cbbd66241f386285b2193b5121d5c4aacbeaR105.
Currently 2.0.0 is dynamicaly linked, and openssl 1.1 is not present in the environment. So we can just build it from source.
2.0.1 onwards it should be statically linked thanks to https://github.com/risingwavelabs/risingwave/pull/18569. …

fix(ci): build 2.0.0 from source in backwards compat test

---

ci/workflows/main-cron.yml
e2e_test/s3/fs_parquet_source_and_sink.py

refactor(test): migrate s3 parquet test from s3 to minio

---

src/risedevtool/schemas/profile.json

Supplement to #18396.
</details>

chore(risedev): add `env` fields in schema of risedev profile

---

ci/scripts/release.sh

Fix https://github.com/risingwavelabs/risingwave/issues/18664
</details>

fix(ci): correct release check

---

ci/scripts/backwards-compat-test.sh

As per title. Similar to https://github.com/risingwavelabs/risingwave/pull/18649
</details>

chore(ci): build v1.10.2 from source for backwards compat tests

---

Cargo.lock
Cargo.toml

chore: update package version to 2.0.1

---

.github/workflows/cherry-pick-to-release-branch.yml

Grant write permission to reduce the 403 error in cherry-pick GitHub Action like this one https://github.com/risingwavelabs/risingwave/actions/runs/11024843712/job/30620827387.
Refer to https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
</details>

fix(ci): add contents write permission cherry pick workflow

---

Cargo.lock
Cargo.toml
src/common/Cargo.toml
src/common/src/array/arrow/arrow_53.rs
src/common/src/array/arrow/arrow_iceberg.rs
src/common/src/array/arrow/mod.rs

Rebased our fork to upstream latest main, and fixed up some commits.
https://github.com/risingwavelabs/iceberg-rust/commits/dev-rebase-main/
Prev: https://github.com/risingwavelabs/iceberg-rust/commits/dev (I've contributed some commits to upstream, so dropped)
</details>

build(deps): bump iceberg-rust to latest main

---

Cargo.lock
Cargo.toml
src/storage/src/store_impl.rs

As title. FYI: https://github.com/foyer-rs/foyer/blob/main/CHANGELOG.md
</details>

fix(foyer): upgrade foyer to involve some bug fixes

---

Cargo.lock

```sql
create table test (
foo text
)
include offset as seq
with (
connector='kinesis',
aws.region='ap-southeast-1',
aws.credentials.access_key_id='',
aws.credentials.secret_access_key='',
stream='test',
scan.startup.mode='earliest'
)
format plain encode json;
2: failed to create source worker
3: failed to list kinesis shards
4: dispatch failure
5: other
6: UserAgentInterceptor modify_before_signing interceptor encountered an error
7: The UserAgentInterceptor requires ApiMetadata to …
```

fix(kinesis): bump `aws-sdk-kinesis` to 1.18.0 to fix creation failure

---

src/connector/src/parser/unified/debezium.rs
src/connector/src/source/cdc/external/mysql.rs

- add missing mysql data types when parsing schema change event
</details>

fix(mysql-cdc): add missing data types when parse schema change event

---

java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/DbzSourceUtils.java

fix(pg-cdc): fix compatibility issue of publish_via_partition_root

---

.github/workflows/cherry-pick-to-release-branch.yml

To solve 403 error during `hub create issue` like this one https://github.com/risingwavelabs/risingwave/actions/runs/11031850661/job/30639476128
</details>

fix(ci): change GITHUB_TOKEN permission to write-all

---

.github/workflows/cherry-pick-to-release-branch.yml

fix(ci): add write-all permission

---

e2e_test/batch/catalog/pg_class.slt.part
src/frontend/src/catalog/system_catalog/information_schema/mod.rs
src/frontend/src/catalog/system_catalog/information_schema/table_constraints.rs

- Support `information_schema.table_constraints`
- Reference https://www.postgresql.org/docs/current/infoschema-table-constraints.html
- Support `information_schema.table_constraints` and currently only primary key constraints will be shown.

feat: support information_schema.table_constraints

---

e2e_test/source/cdc_inline/auto_schema_map_mysql.slt
e2e_test/source/cdc_inline/auto_schema_map_pg.slt
src/common/src/catalog/column.rs
src/connector/src/parser/unified/debezium.rs
src/connector/src/source/cdc/external/mysql.rs
src/connector/src/source/cdc/external/postgres.rs

cherry pick #18571 and #18706 to release-2.0
</details>

feat(cdc): cherry pick #18571 and #18706 to release-2.0

---

ci/scripts/release.sh

cherry pick https://github.com/risingwavelabs/risingwave/pull/18666
</details>

fix(ci): correct release check (#18666)

---

src/frontend/planner_test/tests/testdata/input/temporal_join.yaml
src/frontend/planner_test/tests/testdata/output/temporal_join.yaml
src/frontend/src/binder/relation/mod.rs

fix(binder): disallow CTE in right table of temporal join

---

docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

chore: update image version to 2.0.1

---

Cargo.lock
src/connector/Cargo.toml
src/connector/src/sink/iceberg/compaction.rs
src/connector/src/sink/iceberg/mod.rs

nim table iceberg compaction client that triggers compaction by aws emr serverless.
</details>

feat(nimtable): implement nimtable iceberg compaction client

---

src/connector/src/source/kafka/split.rs

chore: add comment for KafkaSplit's start_offset

---

src/license/src/lib.rs

🥵🥵 as title, a stupid error
</details>

fix: telemetry event at paywall not reporting

---

src/config/ci-meta-backup-test.toml
src/config/ci-time-travel.toml
src/storage/backup/integration_tests/test_pin_sst.sh

The test fails because an additional sanity check has been added in #18757.
</details>

fix(meta): fix test

---

Cargo.lock
Cargo.toml
risedev.yml
src/connector/Cargo.toml
src/connector/src/connector_common/iceberg/mod.rs

This PR replace jdbc catalog with sql catalog when create and read 
- rewrite jdbc catalog to sql catalog
- use sql catalog when create and read 
related to https://github.com/risingwavelabs/iceberg-rust/pull/7
</details>

feat(nimtable): support iceberg sql catalog for create and read

---

Cargo.lock
Cargo.toml
risedev.yml

- upgrade dep https://github.com/risingwavelabs/iceberg-rust/pull/7
- use pg default deploy
</details>

feat(nimtable): use pg default deploy

---

src/expr/core/src/window_function/states.rs
src/stream/src/executor/over_window/general.rs
src/stream/src/executor/over_window/over_partition.rs

1. Extract `WindowStates::just_slide_to` method as a preparation for optimization.
2. Move `OverWindowExecutor::build_changes_for_partition` to `OverPartition::build_changes` for better modularity.
</details>

refactor(over window): move `build_changes` to `OverPartition` for better modularity

---

java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/MySqlValidator.java
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/PostgresValidator.java
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/SqlServerValidator.java

As titled. Enhance it since so many customers have asked questions about primary key mismatch.
</details>

chore(cdc): enhance cdc primary key error message
