- src/frontend/src/binder/bind_param.rs
- src/frontend/src/expr/expr_rewriter.rs
- src/frontend/src/expr/expr_visitor.rs
- src/frontend/src/expr/mod.rs
- src/frontend/src/optimizer/plan_expr_rewriter/const_eval_rewriter.rs
- src/frontend/src/optimizer/plan_expr_visitor/expr_counter.rs
- src/frontend/src/optimizer/plan_node/mod.rs
- src/frontend/src/optimizer/plan_rewriter/mod.rs
- src/frontend/src/optimizer/plan_visitor/mod.rs
Follow-up of #16279. Based on some actual queries provided by users, this PR adopts fearless recursion to more places to provide better support for complicated plan in optimizer, including:
- Expression visitor / rewriter
- Plan visitor / rewriter
The theory behind why this will work by only touching the optimizer code may be that, the final **physical** plan and expression tree executed on the compute nodes could be less complex than what we have to handle in the optimizer, thus requiring less stack depth. This is further because...
- we have common sub-expression elimination …
> feat(optimizer): grow stack for complicated plan in more places

- src/common/src/config.rs
- src/config/example.toml
- src/object_store/src/object/opendal_engine/fs.rs
- src/object_store/src/object/opendal_engine/opendal_s3.rs
- src/object_store/src/object/s3.rs
- src/storage/src/hummock/compactor/compactor_runner.rs
As titled.
To ensure backward compatibility, alias is added for the modified configs.
</details>
> chore: remove the object_store prefix in the object store config naming

- src/storage/src/row_serde/value_serde.rs
- src/storage/src/table/batch_table/storage_table.rs
- Deserialize only the required column in StorageTable's get and iter.
- Fix a bug in `ColumnAwareSerde::new` when calculating `column_with_default`.
Find more details in
#https://github.com/risingwavelabs/risingwave/issues/16763#issuecomment-2123882211
</details>
> refactor(storage): deserialize output columns only

- Cargo.lock
- Cargo.toml
- src/common/src/config.rs
- src/config/example.toml
- src/connector/src/sink/snowflake_connector.rs
- src/object_store/Cargo.toml
- src/object_store/src/object/mod.rs
- src/object_store/src/object/opendal_engine/azblob.rs
- src/object_store/src/object/opendal_engine/fs.rs
- src/object_store/src/object/opendal_engine/gcs.rs
- src/object_store/src/object/opendal_engine/hdfs.rs
- src/object_store/src/object/opendal_engine/obs.rs
- src/object_store/src/object/opendal_engine/opendal_object_store.rs
- src/object_store/src/object/opendal_engine/opendal_s3.rs
- src/object_store/src/object/opendal_engine/oss.rs
- src/object_store/src/object/opendal_engine/webhdfs.rs
- Upgrade to opendal 0.47 in object store
- Adopt the new reader writer API in opendal object store
- support streaming uploader metrics via the new executor trait
</details>
> feat: upgrade to opendal 0.47 in object store

- src/meta/model_v2/migration/src/lib.rs
- src/meta/model_v2/migration/src/m20240618_072634_function_compressed_binary.rs
The column `compressed_binary` of table `function` was defined as `varchar` in sql backend but as `Vec<u8>` in rust type, which will cause cluster unable to get recovered if any UDFs with compressed binary was created:
```
mismatched types; Rust type `core::option::Option<alloc::vec::Vec<u8>>` (as SQL type `BYTEA`) is not compatible with SQL type `VARCHAR`
```
Already tested it locally with three kinds of sql backends. Haven't found a suitable way to test and cover it yet. …
> fix: fix type mismatch of compressed_binary column in function table

- proto/catalog.proto
- proto/secret.proto
- src/connector/src/sink/catalog/desc.rs
- src/connector/src/sink/catalog/mod.rs
- src/ctl/src/cmd_impl/meta/migration.rs
- src/frontend/src/utils/with_options.rs
- src/meta/model_v2/migration/src/m20240525_090457_secret.rs
- src/meta/model_v2/src/lib.rs
- src/meta/model_v2/src/sink.rs
- src/meta/model_v2/src/source.rs
- src/meta/src/controller/mod.rs
- src/prost/build.rs
to avoid breaking change
cherry pick #17330 #17269
</details>
> cherry-pick refactor: secret ref columns in protobuf

- Cargo.lock
- src/meta/Cargo.toml
- src/meta/src/hummock/model/compact_task_assignment.rs
- src/meta/src/hummock/model/pinned_snapshot.rs
- src/meta/src/hummock/model/pinned_version.rs
- src/meta/src/hummock/model/version_delta.rs
- src/meta/src/hummock/model/version_stats.rs
- src/meta/src/model/mod.rs
- src/storage/src/hummock/store/hummock_storage.rs
Implement the idea in https://github.com/risingwavelabs/risingwave/issues/11072#issuecomment-1643075574, as a quick hack to reduce the possibility of exceeding the max request size.
</details>
> feat(meta): compress the encoded model if it's too large in kv meta store

- src/connector/src/sink/clickhouse.rs
- src/connector/with_options_sink.yaml
- ClickHouse now supports [1] a `is_deleted` column (optional) when creating a `ReplacingMergeTree`.
- Adds new `clickhouse.delete.column` config option, which when set will enable `upsert` to a `ReplacingMergeTree`
- When the value is deleted the value of this column is set to `1` instead of the default `0`.
[1] https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replacingmergetree#is_deleted
This patch adds the ability for propagating `DELETE` operations to a ClickHouse table backed by a `ReplacingMergeTree`. When using the `type='upsert'` you will need to specify a `clickhouse.delete.column` …
> feat(sink): Support Deletes for ClickHouse ReplacingMergeTree

- e2e_test/batch/functions/at_time_zone.slt.part
- src/frontend/src/binder/expr/mod.rs
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/src/parser.rs
- src/sqlparser/tests/testdata/select.yaml
Before: `t.local AT TIME ZONE 'US/Pacific'`
After: `t.local AT TIME ZONE t.zone`
Resolves #17384
The time zone parameter of `AT TIME ZONE` is no longer limited to literals and can be arbitrary varchar expression.
> feat(sqlparser): allow rhs of `AT TIME ZONE` to be non-literal

- src/batch/benches/sort.rs
- src/batch/src/executor/hash_agg.rs
- src/batch/src/executor/join/hash_join.rs
- src/batch/src/executor/join/local_lookup_join.rs
- src/batch/src/executor/order_by.rs
- src/batch/src/spill/spill_op.rs
- src/common/src/memory/mem_context.rs
- Add spill sort test: Use memory backend and force spill out by setting memory limit to 0.
</details>
> test(batch): add unit test for spill sort

- src/storage/src/mem_table.rs
- src/storage/src/memory.rs
- src/stream/src/common/table/state_table.rs
- src/stream/src/executor/over_window/over_partition.rs
…tate table reverse iterator" (#17158)"
This reverts commit f52d17777a05ca9a8e904759f02f50d80dac0a5d.
close https://github.com/risingwavelabs/risingwave/issues/17209
</details>
> fix(storage): fix reverse scan

- e2e_test/batch/functions/at_time_zone.slt.part
- src/frontend/src/binder/expr/mod.rs
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/src/parser.rs
- src/sqlparser/tests/testdata/select.yaml
Cherry picking \#17395 onto branch release-1.9\n\nThis PR/issue was created by cherry-pick action from commit 70eb3d08c454ae1483d7c369ca106478b9892791.
> feat(sqlparser): allow rhs of `AT TIME ZONE` to be non-literal (#17395)

- src/bench/sink_bench/main.rs
- src/connector/src/parser/bytes_parser.rs
- src/connector/src/parser/debezium/debezium_parser.rs
- src/connector/src/parser/debezium/simd_json_parser.rs
- src/connector/src/parser/maxwell/simd_json_parser.rs
- src/connector/src/parser/mod.rs
- src/connector/src/parser/util.rs
- src/connector/src/source/datagen/source/generator.rs
- src/connector/src/source/datagen/source/reader.rs
- src/connector/src/source/filesystem/s3/source/reader.rs
- src/stream/src/executor/backfill/cdc/cdc_backfill.rs
Resolves #12974. The field is always filled as `None` but causing unnecessary complexity to downstreams.
</details>
> refactor(source): cleanup unused `ParserProperties::key_encoding_config`

- e2e_test/source_inline/kafka/include_key_as.slt
Root cause is #17448, which needs a more careful fix.
</details>
> test: workaround include_key_as flaky test

- e2e_test/ddl/show.slt
- src/frontend/src/handler/create_sql_function.rs
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/src/parser.rs
- src/sqlparser/src/parser_v2/mod.rs
- src/sqlparser/tests/testdata/select.yaml
- src/sqlparser/tests/testdata/show.yaml
See #17461. Somehow a user wrote the invalid SQL `Date t::date` but it was interpreted by our sqlparser as `(Date 't')::date` and resulting in evaluation error.
The root cause is upstream https://github.com/sqlparser-rs/sqlparser-rs/pull/235 support of HiveSQL where an unquoted identifier can be treated as a literal string value. It is never the case for PostgreSQL.
After the fix, we report the following error message:
```
dev=> select date t::date from generate_series('2024-01-01 00:00:00+00'::timestamptz, now(), interval '1 month') as s(t);
Caused by:
sql parser error: expected end of …
```
> fix(sqlparser): typed string must be single quoted

- e2e_test/streaming/changelog.slt
- integration_tests/snowflake-sink/README.md
- integration_tests/snowflake-sink/upsert/create_mv.sql
- integration_tests/snowflake-sink/upsert/create_sink.sql
- integration_tests/snowflake-sink/upsert/create_source.sql
- proto/stream_plan.proto
- src/frontend/src/optimizer/plan_node/generic/changelog.rs
- src/frontend/src/optimizer/plan_node/logical_changelog.rs
Forgot to add _changelog_row_id records in out_col_change , this is an error.
Added demo that implements snowflake upsert sink using changelog 
Need to add the demo to the documentation
</details>
> fix(frontend): fix changelog out_col_change error and add snowflake upsert sink demo

- Cargo.lock
- src/batch/Cargo.toml
- src/batch/src/error.rs
- src/batch/src/executor/iceberg_scan.rs
- src/connector/src/sink/iceberg/mod.rs
- Tracking issue: https://github.com/risingwavelabs/risingwave/issues/17548
- Use iceberg rust instead of icelake in batch crate. `IcebergScanExecutor` will only depend on iceberg-rust after this PR.
</details>
> feat(batch): use iceberg rust in iceberg scan

- docs/dev/src/SUMMARY.md
- docs/dev/src/connector/intro.md
- docs/dev/src/tests/intro.md
- e2e_test/README.md
- e2e_test/commands/README.md
- e2e_test/source/README.md
- e2e_test/source_inline/README.md
> doc: add connector dev guide

- src/cmd/src/lib.rs
- src/cmd_all/src/standalone.rs
- src/compute/src/server.rs
- src/ctl/src/common/context.rs
- src/frontend/src/lib.rs
- src/frontend/src/meta_client.rs
- src/frontend/src/session.rs
- src/frontend/src/test_utils.rs
- src/meta/service/src/cluster_service.rs
- src/meta/src/controller/cluster.rs
- src/meta/src/manager/cluster.rs
- src/rpc_client/src/meta_client.rs
- src/tests/simulation/src/cluster.rs
- src/utils/pgwire/src/lib.rs
- src/utils/pgwire/src/pg_server.rs
Follow-up of #17533. Implements graceful shutdown on frontend node, which
- stops all existing sessions
- unregisters from the meta service
Also improves the logging for unregistration.
</details>
> refactor: graceful shutdown on frontend node

- integration_tests/snowflake-sink/upsert/create_sink.sql
- src/frontend/src/optimizer/plan_node/stream_changelog.rs
The changelog will convert all delete/update to insert, so its append_only will all be true
</details>
> fix(frontend): fix changelog append_only

- src/frontend/src/catalog/catalog_service.rs
- src/frontend/src/handler/drop_subscription.rs
- src/frontend/src/meta_client.rs
- src/frontend/src/session.rs
- src/frontend/src/session/cursor_manager.rs
- src/frontend/src/test_utils.rs
The current behavior is that after deleting the sub, the cursor will still consume cached data, but the next pull will report an error
invalid cursors will be deleted when creating a new cursor
</details>
> fix(subscription): fix drop subscription not clear cursor

- src/meta/src/manager/catalog/mod.rs
As mentioned: https://github.com/risingwavelabs/risingwave/pull/17576#issuecomment-2209453665.
The following sequence of events can occur:
1. MV with id 2000 failed after its catalogs were initially committed.
2. FE killed.
3. CN killed
4. From (3), Finish stream job fails.
5. From (2) FE restarted, subscribe to meta.
6. From (3), Meta cleans up catalogs, removing id=2000.
7. From (2) Meta notifies the newly subscribed frontend node of the existing catalogs. This does not include 2000 since it's already cleaned.
8. From (3), Meta issues a clean stream job command for 2000, but it's not in the FE catalog at all, only …
> fix(meta): make drop streaming job catalog and notify frontend transactional

- src/connector/src/parser/mod.rs
- src/connector/src/source/cdc/source/reader.rs
- src/connector/src/source/common.rs
- src/connector/src/source/datagen/source/reader.rs
- src/connector/src/source/filesystem/opendal_source/opendal_reader.rs
- src/connector/src/source/filesystem/s3/source/reader.rs
- src/connector/src/source/kafka/enumerator/client.rs
- src/connector/src/source/kafka/source/reader.rs
- src/connector/src/source/monitor/metrics.rs
- src/connector/src/source/nexmark/source/reader.rs
> refactor(connector): make source connector's metrics guarded

- src/common/common_service/Cargo.toml
- src/common/common_service/src/metrics_manager.rs
To reduce the response size when there's too many metrics data, in the same way as #15558.
Only added one line of `.layer(CompressionLayer::new())`, while other changes are made by `cargo fmt`.
</details>
> feat(metrics): enable http compression for prometheus metrics service

- Cargo.lock
- Cargo.toml
- src/common/src/config.rs
- src/compute/src/memory/config.rs
- src/storage/src/opts.rs
- src/storage/src/store_impl.rs
> fix(storage): add disk cache buffer threshold to mitigate OOM (#17595)

- Cargo.lock
- Cargo.toml
- src/batch/Cargo.toml
- src/batch/src/error.rs
- src/batch/src/executor/mod.rs
- src/batch/src/executor/s3_file_scan.rs
- src/connector/Cargo.toml
- src/connector/src/source/filesystem/opendal_source/mod.rs
- https://github.com/risingwavelabs/risingwave/issues/14742
- Support s3 parquet file batch executor. After that, we can implement the frontend part to provide a user-friendly sql table value function to load a parquet from s3 to risingwave.
</details>
> feat(batch): support batch s3 parquet file executor

- risedev.yml
- src/common/src/array/stream_chunk.rs
- src/stream/src/executor/hash_join.rs
- src/stream/src/executor/join/builder.rs
to solve https://github.com/risingwavelabs/risingwave/issues/17450
use the SQL to test if is takes effect.
```SQL
create table t1(v int, k int primary key);
create table d(vv int, k int primary key);
INSERT into t1 VALUES (1,1);
INSERT into d values (1,1);
create materialized view mv as 
select t1.v, t1.k 
from t1 
full outer join d d1 using(k)
full outer join d d2 using(k)
full outer join d d3 using(k)
full outer join d d4 using(k)
full outer join d d5 using(k)
full outer join d d6 using(k)
full outer join d d7 using(k)
full outer join d d8 using(k)
full outer join d d9 using(k)
full outer join d d10 using(k);
UPDATE …
```
> feat: compact_noop_update_after_outer_join

- src/cmd/src/lib.rs
- src/cmd_all/src/standalone.rs
- src/storage/compactor/src/lib.rs
- src/storage/compactor/src/server.rs
- src/tests/compaction_test/src/compaction_test_runner.rs
- src/tests/simulation/src/cluster.rs
Follow-up of #17574. Implements graceful shutdown on frontend node, which
- unregisters from the meta service
</details>
> refactor: graceful shutdown on compactor node

- e2e_test/commands/sr_register
- e2e_test/source_inline/kafka/avro/alter_source.slt
- e2e_test/source_inline/kafka/avro/union.slt
- src/common/src/types/mod.rs
- src/connector/codec/src/decoder/avro/mod.rs
- src/connector/codec/src/decoder/avro/schema.rs
- src/connector/codec/src/decoder/mod.rs
- src/connector/codec/tests/integration_tests/avro.rs
- src/connector/src/parser/debezium/avro_parser.rs
- src/connector/src/parser/unified/json.rs
fix #16273
Note: real LoC change of this PR is very short. Mostly tests.
TODO
Support Avro Union type in `SOURCE`s.
There's a example in `e2e_test/source_inline/kafka/avro/union.slt`
> feat(source): support Avro Union type

- src/cmd/src/lib.rs
- src/cmd_all/src/standalone.rs
- src/meta/node/src/lib.rs
- src/meta/node/src/server.rs
- src/meta/service/src/meta_member_service.rs
- src/meta/src/manager/idle.rs
- src/meta/src/rpc/election/dummy.rs
- src/meta/src/rpc/election/etcd.rs
- src/meta/src/rpc/election/mod.rs
- src/meta/src/rpc/election/sql.rs
- src/meta/src/rpc/metrics.rs
- src/tests/compaction_test/src/compaction_test_runner.rs
- src/tests/simulation/src/cluster.rs
Follow-up of #17533, based on the ideas proposed in https://github.com/risingwavelabs/risingwave/issues/17351#issuecomment-2199698056.
- Add a "dummy" election client that always claims we are the leader, unifying the code path no matter whether there's HA.
- Not joining sub-tasks any more, since I've reviewed all of their implementations and found almost all of them are only designed to print a message when exiting (correct me if I'm wrong 🙏).
Still leave some TODOs which requires all components to be ready for graceful shutdown, or whose function signatures will change and …
> refactor: graceful shutdown on meta node & unify election path

- src/ctl/src/cmd_impl/meta/migration.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_hummock_version_deltas.rs
- src/meta/src/hummock/manager/compaction.rs
- src/meta/src/hummock/model/ext/hummock.rs
- src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
- src/storage/hummock_sdk/src/version.rs
Resolve https://github.com/risingwavelabs/risingwave/issues/17655
Previously we only clean the table watermark of tables that have changed their safe epoch, which causes https://github.com/risingwavelabs/risingwave/issues/17655. In this PR, we change to always check if there is table watermark below the table safe epoch, regardless of whether the the table watermark have changed.
The `safe_epoch` field of `HummockVersionDelta` is marked private to avoid misuse. We can instead access it with `visible_table_safe_epoch` method. …
> fix(storage): always clean table watermark below table safe epoch

- Cargo.lock
- Cargo.toml
- src/meta/src/storage/wrapped_etcd_client.rs
We switched to a forked version of `etcd-client` in #11277. Later, the upstream version resolved the issue (https://github.com/etcdv3/etcd-client/pull/69) so I guess we can switch back to it.
This is a preparation of https://github.com/risingwavelabs/risingwave/issues/13695#issuecomment-2219905182.
</details>
> refactor(meta): use upstream version of `etcd-client`

- e2e_test/subscription/create_table_and_subscription.slt
- e2e_test/subscription/drop_table_and_subscription.slt
- e2e_test/subscription/main.py
- src/meta/service/src/ddl_service.rs
- src/meta/src/controller/catalog.rs
- src/meta/src/manager/catalog/mod.rs
- src/meta/src/manager/metadata.rs
- src/meta/src/stream/mod.rs
- src/meta/src/stream/stream_manager.rs
1. Fixed the get_mv_depended_subscriptions method not really querying all subscription
2. Use old_table_fragments.table_id to get subscriptions instead of table_fragments.table_id when replacing table
</details>
> fix(meta): Fix sink_into_table causes mv's depended_subscription_ids to be empty.

- src/meta/src/rpc/ddl_controller_v2.rs
- src/stream/src/task/barrier_manager.rs
After a source executor fails, the barrier manager may first realize that by finding the rx side is closed when injecting barriers, instead of receiving the error reported by the actor. This is because the barrier channel rx is immediately dropped when an executor exits, while error reporting happens later.
This PR makes it also call `try_find_root_failure` on barrier injection failure, making the error reporting more accurate.
Should address https://github.com/risingwavelabs/risingwave/issues/17389. The error message now looks like:
```
Caused by these errors (recent errors listed …
```
> fix(streaming): find and return root actor failure when injection failed

- src/common/src/array/arrow/arrow_impl.rs
- src/common/src/array/proto_reader.rs
- src/common/src/types/macros.rs
- src/common/src/types/mod.rs
- src/frontend/src/catalog/system_catalog/pg_catalog/pg_cast.rs
minor
- make private some internal traits (due to my mysophobia)
- add comments
</details>
> refactor(types): remove dead code and minor

- ci/workflows/main-cron.yml
- e2e_test/s3/fs_source_v2.py
- e2e_test/s3/fs_source_v2_new_file.py
- src/stream/src/executor/source/list_executor.rs
resolve https://github.com/risingwavelabs/risingwave/issues/17671
as title, the list exec just list the file list once due to wrong impl, here introducing a loop to make it keep listing
</details>
> fix: s3_v2 connector cannot read incremental files 

- src/common/src/types/datetime.rs
- src/common/src/types/decimal.rs
- src/common/src/types/interval.rs
- src/common/src/types/mod.rs
- src/common/src/types/serial.rs
- src/common/src/types/timestamptz.rs
- src/common/src/types/to_binary.rs
- src/common/src/types/to_text.rs
- src/connector/src/parser/mysql.rs
- src/expr/impl/src/scalar/cast.rs
- src/utils/pgwire/src/types.rs
> refactor(types): doc & refine ToBinary/Text

- .github/workflows/typo.yml
- .typos.toml
- Makefile.toml
- src/connector/src/sink/clickhouse.rs
- src/storage/src/hummock/sstable/block.rs
> chore: bump typos

- src/connector/src/source/kinesis/enumerator/client.rs
…ption: NextToken and StreamName cannot be provided together."
* why did this happen? 
* We did not meet a Kinesis has over 1k shards before. And we wrongly use the ListShards pagination API. 
as title, the constraint is described in API doc
https://docs.rs/aws-sdk-kinesis/latest/aws_sdk_kinesis/operation/list_shards/struct.ListShardsInput.html
> When the number of shards in the data stream is greater than the default value for the MaxResults parameter, or if you explicitly specify a value for MaxResults that is less than the number of shards in the data stream, the response includes a pagination token named NextToken. …
> fix: Kinesis: NextToken and StreamName cannot be provided together

- src/connector/src/sink/encoder/json.rs
- src/connector/src/sink/encoder/mod.rs
- src/connector/src/sink/formatter/debezium_json.rs
- src/connector/src/sink/formatter/mod.rs
- src/connector/src/sink/kafka.rs
- src/connector/src/sink/mqtt.rs
- src/connector/src/sink/nats.rs
- src/connector/src/sink/snowflake.rs
close #11699
Add a option for `ENCODE JSON` in `WITH` clause .
`jsonb.handling.mode` can be set to either `string` or `dynamic`
- `string`: encode the `jsonb` type as a string. example: `{"k": 2} -> "{\"k\": 2}"`. Here a json object `jsonb` was encoded to a string.
- `dynamic`: dynamically encode the `jsonb` type as json type. example: `{"k": 2} -> {"k": 2}`. Here a json object `jsonb` was encoded to a json object. …
> feat(sink): support encode jsonb data as dynamic json type in sink

- proto/hummock.proto
- src/meta/src/hummock/compaction/compaction_config.rs
- src/meta/src/hummock/compaction/mod.rs
- src/meta/src/hummock/compaction/picker/base_level_compaction_picker.rs
- src/meta/src/hummock/compaction/picker/compaction_task_validator.rs
- src/meta/src/hummock/compaction/picker/intra_compaction_picker.rs
- src/meta/src/hummock/manager/compaction_group_manager.rs
Previously, we stored `max_l0_compact_level_count` as a config in CompactionConfig, and the default value will change to 0 after upgrading the old cluster.
And `max_l0_compact_level_count = 0` would cause the task to be passed over by the validator, which triggered a bug in the `pick_whole_level` function. `pick_whole_level` picks out the tasks that contain only one sublevel, which triggers the in-place trivial-move, and the meta gets bogged down.
This PR
1. Fix the default value of `max_l0_compact_level_count`
2. Avoid the task maintaining sublevels less than 2 , picking by `pick_whole_level` 
3. Deprecate the …
> fix(storage): fix the trivial-move loop caused by config and pick_whole_level

- docs/dev/src/ci.md
> doc: fix `main-cron-bisect` docs

- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/MySqlValidator.java
MySQL 8.4 introduces some breaking changes: https://dev.mysql.com/doc/relnotes/mysql/8.4/en/news-8-4-0.html#mysqld-8-4-0-deprecation-removal
We may support MySQL 8.4 in future, this pr adds a check to validate the mysql version.
#16701
</details>
> fix(mysql-cdc): validate mysql version less then 8.4

- Makefile.toml
Always use dev profile for `risedev-dev` in `ci-start`. This is because `risedev-dev` is always build in dev profile to reduce compiling time.
- Caused by #16152
- Similar to #16427
</details>
> fix(risedev): always use dev profile for `risedev-dev` in `ci-start`

- src/frontend/planner_test/tests/testdata/input/temporal_filter.yaml
- src/frontend/planner_test/tests/testdata/output/expr.yaml
- src/frontend/planner_test/tests/testdata/output/temporal_filter.yaml
- src/frontend/src/expr/mod.rs
- src/frontend/src/optimizer/plan_node/logical_filter.rs
Support complex expressions like `ts + interval '1 hour' > date_trunc('day', ('2024-07-18 00:00:00+00:00'::timestamptz - ('2024-07-18 00:00:00+00:00'::timestamptz - now()))`.
Fixes #17630.
</details>
> feat(temporal-filter): support more now expressions in temporal filter pattern

- e2e_test/error_ui/simple/recovery.slt
- src/error/src/tonic.rs
- src/error/src/tonic/extra.rs
- src/meta/src/barrier/rpc.rs
- src/rpc_client/src/error.rs
- src/stream/src/task/barrier_manager.rs
Close #17368. Pass streaming error score to meta service to locate cluster-level root error. Instead of concatenating erros from all compute nodes, only show the root error in the recovery reason.
```
2: get error from control stream, in worker node 2
3: gRPC request to stream service failed: Internal error
4: failed to collect barrier for epoch [6802214756352000]
5: Actor 13 exited unexpectedly
6: Executor error
7: Chunk operation error
8: Numeric out of range
```
For …
> feat(meta): pass streaming error score to meta to locate cluster-level root error

- Cargo.toml
- ci/scripts/release.sh
- docker/Dockerfile
- docker/Dockerfile.hdfs
- docker/aws/aws-build.sh
- docs/dev/src/SUMMARY.md
- docs/dev/src/build-and-run/profiles.md
Resolve https://github.com/risingwavelabs/risingwave/issues/17725 in another way.
Rename `release` profile to `production`. Make `release` more friendly for local testing on optimized builds, like enabling incremental compilation and disabling LTO.
Add a separate page in developer docs introducing and comparising all our profiles. …
> chore: add `production` profile for version release & add developer docs

- e2e_test/source_inline/kafka/avro/name_strategy.slt
- src/connector/src/parser/avro/parser.rs
- src/connector/src/parser/debezium/debezium_parser.rs
- src/connector/src/parser/maxwell/maxwell_parser.rs
- src/connector/src/parser/mod.rs
- src/connector/src/parser/plain_parser.rs
- src/connector/src/parser/upsert_parser.rs
Resolves #17670
* The boolean `AvroProperties::enable_upsert` is not useful
* The option `AvroParserConfig::key_schema` is always `None` (after boolean removal above)
* The enum `encoding_type` is always hardcoded as `EncodingType::Value` except for DebeziumAvro.
* Removes non-existent Debezium + Protobuf.
</details>
> fix(source): cleanup unused key schema logic & requirements for `format upsert encode avro`

- src/batch/src/task/env.rs
- src/common/src/config.rs
- src/compute/src/server.rs
- src/ctl/src/cmd_impl/await_tree.rs
- src/ctl/src/cmd_impl/profile.rs
- src/frontend/src/scheduler/distributed/query.rs
- src/frontend/src/session.rs
- src/meta/node/src/server.rs
- src/meta/src/manager/diagnose.rs
- src/meta/src/manager/env.rs
- src/rpc_client/src/compute_client.rs
- src/rpc_client/src/lib.rs
- src/stream/src/executor/exchange/input.rs
- src/stream/src/executor/merge.rs
- src/stream/src/task/barrier_manager.rs
- src/stream/src/task/env.rs
- src/stream/src/task/mod.rs
A `connection_pool_size` can be specified to establish multiple connections to the same server. We didn't pass this configuration field to the client pool used by streaming exchange, which is the issue to address in this PR.
This can help to mitigate potential streaming stuck due to the deadlock caused by HTTP/2 streaming vs connection-level flow control.
Remove `Default` impl to make specifying the `connection_pool_size` explicit to caller. Use `adhoc()` or `new(1)` if the caller doesn't care about the pool size. …
> feat(streaming): follow `server.connection_pool_size` config for exchange service

- src/common/secret/src/secret_manager.rs
Creating secret directories will cause file creation conflict in concurrent simulation tests.
This will not happen in any deployment because we use cluster id (uuid) to distinguish files from different cluster. But we are running `deterministic-it-test.sh` concurrently, and nextest is running multiple ut concurrently. So even with different madsim seed for each deterministic-it-test.sh, two ut in the same run share the same seed, causing the same uuid in different cluster (bc madsim hook the random function in uuid::new_v4)
We currently do not have e2e for secret file. Should skip testing secret files in simulation …
> fix(test): skip creating secret file dir in simulation test

- src/storage/src/hummock/store/local_hummock_storage.rs
- src/storage/src/hummock/store/version.rs
- src/storage/src/mem_table.rs
- src/storage/src/monitor/monitored_store.rs
- src/storage/src/monitor/traced_store.rs
- src/storage/src/panic_store.rs
- src/storage/src/store.rs
- src/storage/src/store_impl.rs
For https://github.com/risingwavelabs/risingwave/issues/17741.
</details>
> feat(storage): support get_table_watermark for LocalStateStore

- src/storage/hummock_sdk/src/table_watermark.rs
- src/storage/src/hummock/event_handler/uploader/mod.rs
- src/storage/src/hummock/store/version.rs
- src/storage/src/hummock/utils.rs
In HummockReadVersion update, we still use the global max committed epoch. In this PR we will change to use the per table committed epoch
</details>
> fix(storage): use per-table committed epoch in read version update

- src/frontend/src/binder/create_view.rs
- src/frontend/src/binder/mod.rs
- src/frontend/src/binder/query.rs
- src/frontend/src/binder/statement.rs
- src/frontend/src/handler/create_mv.rs
- src/frontend/src/handler/extended_handle.rs
- src/frontend/src/handler/privilege.rs
- src/frontend/src/handler/query.rs
- src/frontend/src/planner/query.rs
- src/frontend/src/planner/statement.rs
- src/tests/e2e_extended_mode/src/test.rs
Resolves part of #16653
Supports `CREATE MATERIALIZED VIEW` with parameters as prepared statements.
> feat: support prepared statements for `create MV`

- proto/expr.proto
- src/common/src/catalog/schema.rs
- src/expr/core/src/aggregate/def.rs
- src/expr/impl/src/aggregate/approx_percentile.rs
- src/expr/impl/src/aggregate/mod.rs
- src/frontend/planner_test/tests/testdata/input/agg.yaml
- src/frontend/planner_test/tests/testdata/output/agg.yaml
- src/frontend/src/binder/expr/function.rs
- src/frontend/src/binder/mod.rs
- src/frontend/src/expr/agg_call.rs
- src/frontend/src/optimizer/plan_node/generic/agg.rs
- src/frontend/src/optimizer/plan_node/generic/mod.rs
- src/frontend/src/optimizer/plan_node/logical_agg.rs
- src/frontend/src/optimizer/plan_node/mod.rs
- src/frontend/src/optimizer/plan_node/stream_global_approx_percentile.rs
- src/frontend/src/optimizer/plan_node/stream_keyed_merge.rs
- src/frontend/src/optimizer/plan_node/stream_local_approx_percentile.rs
- src/frontend/src/optimizer/plan_node/stream_share.rs
- src/frontend/src/optimizer/rule/apply_agg_transpose_rule.rs
- src/frontend/src/optimizer/rule/distinct_agg_rule.rs
*30% the changes in this PR are planner tests + binder tests*
This is part of #17531.
We add stateless two-phase simple approx percentile, integrating it with `gen_stateless_two_phase_streaming_agg_plan`.
`StreamLocalApproxPercentile` is the local phase for `approx_percentile`.
`StreamGlobalApproxPercentile` is the global phase.
We do not implement a `core` for either of these, since the fields they use are different (global step does not require any parameters, local step requires the parameters). Further, there's also no `logical` plan node which corresponds to these stream nodes, so there's no need to add a `core`, …
> feat(frontend): add stateless two-phase `ApproxPercentile`

- proto/batch_plan.proto
- src/batch/src/executor/s3_file_scan.rs
- src/connector/src/source/iceberg/parquet_file_reader.rs
- src/frontend/src/expr/table_function.rs
- src/frontend/src/optimizer/plan_node/generic/file_scan.rs
- src/frontend/src/optimizer/plan_node/logical_file_scan.rs
- src/frontend/src/optimizer/rule/table_function_to_file_scan_rule.rs
- src/frontend/src/scheduler/distributed/stage.rs
- src/frontend/src/scheduler/local.rs
- src/frontend/src/scheduler/plan_fragmenter.rs
- Follow up https://github.com/risingwavelabs/risingwave/pull/17673
- Related issue https://github.com/risingwavelabs/risingwave/issues/14742
- Support file scan a directory of parquet files. The schema would be the first parquet file listed. Users should ensure all parquet files in the directory share the same schema.
Example:
```sql
-- function signature …
```
> feat(batch): support file scan a directory of parquet files

- src/connector/src/sink/big_query.rs
- src/connector/src/sink/clickhouse.rs
- src/connector/src/sink/doris.rs
- src/connector/src/sink/doris_starrocks_connector.rs
- src/connector/src/sink/nats.rs
- src/connector/src/sink/redis.rs
- src/connector/src/sink/sqlserver.rs
Replace unnecessary panic with error
</details>
> refactor(sink): Use error instead of unwrap 

- src/connector/src/source/cdc/external/mod.rs
- src/connector/src/source/cdc/external/postgres.rs
- src/stream/src/from_proto/stream_cdc_scan.rs
- Move the prepare statement step to snapshot read, so that we don't need to prepare the select statement if the table has finished backfill. And can avoid problem caused by upstream #17807
- currently mysql cdc doesn't need to prepare statement, since we don't need to convert data type to mysql data type.
</details>
> fix(postgres-cdc): only prepare statement in the backfill process

- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/DbzConnectorConfig.java
- java/connector-node/risingwave-source-cdc/pom.xml
- java/pom.xml
- src/connector/src/parser/unified/json.rs
Due to some fixes/fetures requirements, tentatively upgrade the dependent version of debeizum from `2.4.2.Final` to `2.6.2.Final`.
1. https://issues.redhat.com/browse/DBZ-7933?jql=component%20%3D%20sqlserver-connector%20AND%20text%20~%20%22time%22 It's a time precision issue from Debezium. The debezium developers fix it in `2.7.0`  ([PR](https://github.com/debezium/debezium/pull/5603)). So I was planning to upgrade to `2.7.0.Final` directly, which was released on June 27. After testing, it still contains some weird bugs in `mysql-cdc` support. THe error log is [here](https://buildkiteartifacts.com/28c1f7f6-3369-436d-b28d …
> feat(debeizum): upgrade version of debeizum from 2.4.2 to 2.6.2

- Cargo.lock
- proto/telemetry.proto
- src/common/src/telemetry/report.rs
- src/compute/Cargo.toml
- src/connector/src/sink/catalog/mod.rs
- src/frontend/src/telemetry.rs
- src/meta/Cargo.toml
- src/meta/src/barrier/mod.rs
- src/meta/src/telemetry.rs
- src/storage/compactor/Cargo.toml
- src/storage/compactor/src/telemetry.rs
- src/stream/Cargo.toml
- src/stream/src/from_proto/sink.rs
- src/stream/src/from_proto/source/mod.rs
- src/stream/src/from_proto/source/trad_source.rs
- src/stream/src/from_proto/source_backfill.rs
- src/stream/src/lib.rs
- src/stream/src/telemetry.rs
Signed-off-by: tabversion <tabversion@bupt.icu>
Co-authored-by: tabversion <tabversion@bupt.icu>I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).
resolve #17834
</details>
> feat(telemetry): support report event to telemetry (#17486)

- Makefile.toml
- ci/Dockerfile
- ci/build-ci-image.sh
- ci/docker-compose.yml
- src/risedevtool/common.toml
- https://github.com/risingwavelabs/risingwave/issues/17830#issuecomment-2255057966
- https://github.com/sagiegurari/cargo-make#global-lock-of-versions
</details>
> feat(ci/risedev): install --locked

- src/meta/src/manager/diagnose.rs
List definition of all sources/tables/materialized views/sinks in dashboard's diagnose report, **if sql meta backend is enabled**.
- The definition of source/table/sink will be redacted if no `secret` is used. i.e. the usage of secrets suggests that it's safe to display the definition.
- The diagnose report for the legancy etcd meta backend is not affected.
Sample diagnose report output:
```
TABLE
+----+------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id | name | …
```
> feat(dashboard): include table definition in diagnose report

- e2e_test/ddl/secret.slt
- src/frontend/src/handler/create_secret.rs
- src/frontend/src/handler/drop_secret.rs
- src/license/src/feature.rs
Require paid tier for secret management feature. Only disallow create/drop secret when unlicensed.
</details>
> feat(secret): license the secret management feature

- src/stream/src/executor/sink.rs
- Resolve https://github.com/risingwavelabs/risingwave/issues/17824
- Try to merge small chunks for sink executor, if we need to buffer chunks within a epoch.
</details>
> feat(sink): merge small chunks for sink executor

- Cargo.lock
- ci/scripts/deterministic-recovery-test.sh
- e2e_test/streaming/aggregate/approx_percentile.slt
- src/expr/core/src/aggregate/def.rs
- src/expr/impl/Cargo.toml
- src/expr/impl/src/aggregate/approx_percentile.rs
- src/frontend/src/optimizer/plan_node/generic/agg.rs
As per title. This is the unoptimized version which just uses a single datum to encode the state per group key.
We also just keep the entire state in-memory, rather than cache part of it.
For shuffle approx_percentile, we can just support it as part of the agg framework.
</details>
> feat(expr): support shuffle approx_percentile

- ci/workflows/main-cron.yml
Prerequistie to re-enable: https://github.com/risingwavelabs/risingwave/issues/17855
</details>
> chore(ci): disable cassandra sink test

- src/frontend/src/catalog/system_catalog/rw_catalog/mod.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_secrets.rs
add rw_catalog.rw_secrets table
One problem is secret backend was encrypted. So no backend info in the system table. @tabVersion 
</details>
> feat(secret): add rw_catalog.rw_secrets table

- src/utils/runtime/src/lib.rs
...because Kubernetes will send `SIGTERM` when killing a pod.
As described in https://github.com/risingwavelabs/risingwave/pull/17662, this can empower more seamless scaling-in in Kubernetes deployments. (correct me if I'm wrong)
> After this PR, I suppose we can get rid of the extra manual step of `risingwave ctl meta unregister-worker` when scaling-in, as described in the [doc](https://arc.net/l/quote/nmndgyum).
The step 1 of manual unregistration of the compute node when scaling-in ([doc](https://docs.risingwave.com/docs/current/k8s-cluster-scaling/#scale-in)) is not necessary any more. Users can directly apply the …
> feat: also gracefully shutdown on SIGTERM

- ci/scripts/single-node-utils.sh
- src/cmd_all/scripts/e2e-full-standalone-demo.sh
- src/cmd_all/src/lib.rs
- src/cmd_all/src/standalone.rs
> fix(standalone): write `risedev-env` file in standalone mode

- proto/meta.proto
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/recovery.rs
- src/meta/src/stream/scale.rs
> refactor: add some comments for scaling

- integration_tests/clickhouse-sink/clickhouse_prepare.sql
- integration_tests/clickhouse-sink/create_sink.sql
- integration_tests/clickhouse-sink/sink_check.py
- src/connector/src/sink/clickhouse.rs
Added support for the Clickhouse Null engine, which is useful for situations when source data does not need to be retained. 
Since the Null engine does not write to disk, it should also allow for better [performance](https://double.cloud/blog/posts/2022/12/performance-impact-of-materialized-views-in-clickhouse/) since it eliminates the impact of disk bound IO.
Tested locally: …
> feat(sink): add Clickhouse Null engine

- src/batch/src/executor/iceberg_scan.rs
- src/batch/src/executor/source.rs
- src/connector/src/sink/iceberg/mod.rs
- src/connector/src/sink/iceberg/storage_catalog.rs
- src/connector/src/source/iceberg/mod.rs
- src/frontend/src/scheduler/plan_fragmenter.rs
- https://github.com/risingwavelabs/risingwave/issues/17938
- Currently, we need to load iceberg table during each iceberg scan parallelism. We can pass the metadata from frontend to the compute node for storage catalog.
</details>
> feat(iceberg): reduce iceberg catalog fetch rpc number for iceberg scan

- src/frontend/src/handler/create_source.rs
As titled.
the `slot.name` of postgres cdc source should follow this rule:
```
Valid replication slot name must contain only digits, lowercase characters and underscores with length <= 63
```
> fix(pg-cdc): add validation for slot name of pg cdc source

- src/connector/src/source/kinesis/source/reader.rs
as title, it can help reduce CPU usage. 
the details are included in the code comments. 
=== digest ===
* Shard Splitting: When you split a shard, it results in the creation of two new child shards. The original (parent) shard becomes inactive and will not accept any new data. The new records are written to the child shards instead.
* Shard Merging: When you merge two shards, they form a single new shard. The original shards stop accepting new data and the new shard becomes the active shard for both reads and writes.
=> conclusion: If a shard has a child shard, it is inactive.  …
> fix: early terminate when reach the end of inactive shard

- e2e_test/streaming/aggregate/two_phase_approx_percentile_merge_normal_agg.slt
- src/stream/src/executor/row_merge.rs
Row Count column will not have a corresponding mapping in the i2o map. So if we chance upon a column without a mapping, we can just ignore it.
Also added a test for approx percentile mixed with normal agg. Subsequent PR will also add support for stateful agg e.g. min/max.
</details>
> fix(stream): let `Row Merge` executor handle extra row count column in input

- Cargo.lock
- e2e_test/error_ui/simple/license.slt
- src/common/src/config.rs
- src/common/src/system_param/common.rs
- src/common/src/system_param/diff.rs
- src/common/src/system_param/mod.rs
- src/common/src/system_param/reader.rs
- src/license/src/key.rs
- src/license/src/lib.rs
- src/license/src/manager.rs
- src/meta/Cargo.toml
- src/meta/src/barrier/mod.rs
- src/meta/src/controller/system_param.rs
- src/meta/src/manager/system_param/mod.rs
- src/risedevtool/src/task/task_pubsub_emu_ready_check.rs
Use a newtype wrapper `LicenseKey` to replace `String` for the system parameter `license_key`, with its `Debug` `Display` and `Serialize` implementation overridden. This ensures that it gets redacted when displaying to users.
See e2e tests for the user behavior.
Close #17922.
</details>
> feat: redact license key when displaying to users

- src/cmd_all/src/standalone.rs
- src/meta/node/src/lib.rs
- src/meta/src/controller/system_param.rs
- src/meta/src/manager/system_param/mod.rs
As title. Since `license_key` is a system parameter, we reuse the code path for initializing system parameters with env var.
</details>
> feat: support initializing license key from env var

- e2e_test/batch/distribution_mode.slt
- e2e_test/batch/local_mode.slt
- e2e_test/batch/types/list.slt.part
- e2e_test/batch/types/map.slt.part
- e2e_test/batch/types/struct.slt.part
- src/expr/impl/src/scalar/cast.rs
- src/frontend/planner_test/tests/testdata/output/insert.yaml
- src/frontend/src/binder/expr/mod.rs
- src/frontend/src/binder/insert.rs
- src/frontend/src/binder/select.rs
- src/frontend/src/expr/type_inference/cast.rs
- src/frontend/src/handler/create_mv.rs
- src/frontend/src/utils/mod.rs
- src/sqlparser/src/ast/data_type.rs
- src/sqlparser/src/parser.rs
- src/sqlparser/src/parser_v2/data_type.rs
part of #17743
- parser: support parsing `map(k,v)` type.
- expr/type: support map cast
</details>
> feat: support parsing map type: `map(k,v)`

- e2e_test/sink/kafka/protobuf.slt
- src/connector/src/sink/formatter/mod.rs
- src/frontend/src/handler/create_sink.rs
When creating a sink, `format upsert encode protobuf (...) key encode text` is now allowed but the `key encode text` part is required.
> feat(sink): allow upsert protobuf with text key

- e2e_test/s3/fs_source_batch.py
- src/frontend/src/scheduler/distributed/stage.rs
- src/frontend/src/scheduler/plan_fragmenter.rs
Previously for batch read from file source, the task_parallelism is set to `(self.batch_parallelism / 2) as u32`, which by default is 2, and this will cause 2 issues:
- when their is only one file, another parallelism can not cancel normally.
- when their is no files in source, the  parallelism can not cancel.
This pr fix these two issues by
1. set the `task_parallelism` to `min(file_nums, (batch_parallelism / 2))`, and minimum value is 1.
2. When their is no files in source, schedule an empty task to prevent stuck.
close #17984 …
> fix(connector): fix batch file source when there are no files

- e2e_test/source/cdc_inline/alter/cdc_backfill_rate_limit.slt
- proto/meta.proto
- src/connector/src/source/cdc/source/reader.rs
- src/frontend/src/handler/alter_streaming_rate_limit.rs
- src/frontend/src/handler/mod.rs
- src/meta/service/src/stream_service.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/manager/catalog/fragment.rs
- src/sqlparser/src/ast/ddl.rs
- src/sqlparser/src/parser.rs
- src/stream/src/executor/backfill/cdc/cdc_backfill.rs
Support `alter table t1 set backfill_rate_limit = xx` for cdc table.
- Extend `update_mv_rate_limit_by_table_id` to modify the `rate_limit` of `StreamCdcScan` node
#17913 
Support altering `backfill_rate_limit` of cdc table.
</details>
> feat(cdc): rate limit for cdc backfill

- src/common/src/array/map_array.rs
- src/common/src/types/map_type.rs
- src/common/src/types/mod.rs
- src/common/src/util/value_encoding/mod.rs
- src/connector/codec/src/decoder/avro/mod.rs
- src/connector/codec/src/decoder/avro/schema.rs
- src/connector/codec/tests/integration_tests/avro.rs
- src/connector/codec/tests/integration_tests/utils.rs
Part of #17743
Previously: (#16948) `FORMAT ... ENCODE AVRO (map.handling.mode = 'jsonb')` will convert Avro map type to RisingWave jsonb type. Other values of `map.handling.mode`, or unspecified will be rejected.
Now `map.handling.mode = 'map'` or unspecified will convert it to the native map type.
As title and description
</details>
> feat(source): support ingesting Avro map type to RisingWave map type

- src/meta/src/controller/rename.rs
We didn't iterate over all components of a function call before this PR when doing relation-renaming.
</details>
> fix(meta): fix query rename visitor for complex func calls

- e2e_test/batch/basic/func.slt.part
- src/frontend/src/binder/expr/function/builtin_scalar.rs
- src/frontend/src/binder/expr/function/mod.rs
> feat: support current_catalog sys function

- src/connector/src/source/kinesis/source/reader.rs
introduced in https://github.com/risingwavelabs/risingwave/pull/12048 
the create split gonna fail
* if user set `scan.startup.mode` to `timestamp`
* a new shard is discovered and ready to consume
-> lead to create source task failure
</details>
> fix: not `bail!` on kinesis's state if `scan.startup.mode` set to `timestamp` 

- proto/meta.proto
- src/compute/src/server.rs
- src/ctl/src/common/meta_service.rs
- src/frontend/src/session.rs
- src/meta/service/src/cluster_service.rs
- src/rpc_client/src/error.rs
- src/rpc_client/src/meta_client.rs
- src/storage/compactor/src/server.rs
- src/tests/compaction_test/src/compaction_test_runner.rs
Match the error variant when registering the worker node to the meta service, only retry if it's believed to be an issue of connection.
This eliminates the need for storing error in a separate field of `Status` in the RPC response.
This is an alternative of https://github.com/risingwavelabs/risingwave/pull/18049 and helps #18022.
</details>
> refactor(meta): only retry on connection error when registering worker node

- e2e_test/streaming/aggregate/shuffle_approx_percentile.slt
- e2e_test/streaming/aggregate/two_phase_approx_percentile_merge_stateless_agg.slt
- src/frontend/planner_test/tests/testdata/input/agg.yaml
- src/frontend/planner_test/tests/testdata/output/agg.yaml
- src/frontend/src/optimizer/plan_node/batch_simple_agg.rs
Just support single phase version for batch first.
If there's a real demand to two phase batch approx percentile, we can consider it then.
</details>
> feat(frontend): support single phase approx percentile in batch

- src/license/src/cpu.rs
- src/license/src/lib.rs
- src/license/src/manager.rs
- src/meta/src/controller/cluster.rs
- src/meta/src/manager/cluster.rs
- src/rpc_client/src/meta_client.rs
Add a new field of `cpu_core_limit` in the license content to limit the total CPU cores in the cluster. This is checked every time a new compute node is registering.
Note that it's desired that an unlicensed cluster does not adopt this limit, and a cluster with invalid (including expired) license key will always fail the check. Can check the unit tests for the user interface. …
> feat(license): add limit for total cpu cores in the cluster

- src/sqlparser/src/ast/mod.rs
- src/sqlparser/tests/testdata/create.yaml
And when executing the `ALTER TABLE`. reparsing the SQL like this will causing error
```
dev=> explain CREATE TABLE t (a int) ON CONFLICT DO UPDATE IF NOT NULLINCLUDE timestamp AS ts_col WITH (connector = 'kafka') FORMAT PLAIN ENCODE JSON;
Caused by:
sql parser error: expected end of statement, found: DO
LINE 1: explain CREATE TABLE t (a int) ON CONFLICT DO UPDATE IF NOT NULLINCLUDE timestamp AS ts_col WITH (connector = 'kafka') FORMAT PLAIN ENCODE JSON;
``` …
> fix(parser): fix unparse of include columns

- e2e_test/error_ui/simple/main.slt
> fix: udf error ui

- src/stream/src/executor/stream_reader.rs
The assertion is overly strict. For example, source executor may pause by itself due to barrier backpressure.
</details>
> fix: remove overly strict assertion during stream pause/resume

- src/meta/src/controller/cluster.rs
`enum` is stored as string instead of number with sea-orm. Resolve #18113.
</details>
> fix(meta): fix cpu core limit check query

- src/error/src/tonic.rs
- src/rpc_client/src/meta_client.rs
In #18061 we made a list to decide whether an error is a "connection error" in terms of retrying of worker node registration. However, the list can be incomplete, causing some transient errors not to be retried.
Instead, this PR is an alternative implementation, which uses a list to decide whether an error is initiated by **us** in the gRPC server-side implementation (i.e., through `ToTonicStatus::to_status`). This can lead to more accurate results.
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary …
> refactor(meta): only bail out on server-side error when registering worker node

- src/common/src/system_param/mod.rs
- src/common/src/system_param/reader.rs
- src/meta/src/manager/system_param/model.rs
Follow-up of #17936.
Previously the `new_value: String` returned by `set_system_param` is redacted for `license_key`, which will be further used to persist into the SQL backend. This is not expected. This PR fixes that and adds a unit test to clarify the semantics of the returned `String` type value.
</details>
> fix(meta): correctly persist license key system param in SQL backend

- Cargo.lock
- src/cmd_all/src/standalone.rs
- src/frontend/src/lib.rs
- src/utils/pgwire/Cargo.toml
- src/utils/pgwire/src/net.rs
- src/utils/pgwire/src/pg_server.rs
It's common for an SQL statement not returning any data from the pgwire server for a long time (typically when executing DDL). If the connection is proxied through a load balancer, the LB may consider the connection idle and drop it unexpectedly.
To resolve this issue, we may set the tcp keepalive idle time to a lower value. Here we take a reference to the value in AWS ELB, which is 350 seconds. Note that this can be done in any place dealing with the connection, but doing it on the pgwire server eliminates the need for any additional configuration.
The value is configurable through CLI args and defaults to 300 seconds. …
> fix(pgwire): allow configuring tcp keepalive idle time

- ci/scripts/e2e-kafka-sink-test.sh
- e2e_test/sink/kafka/avro.slt
- e2e_test/sink/kafka/protobuf.slt
> refactor(test):  kafka sink with protobuf/avro as inline style

- src/expr/core/src/aggregate/def.rs
- src/expr/core/src/window_function/kind.rs
- src/frontend/planner_test/tests/testdata/output/agg.yaml
- src/frontend/planner_test/tests/testdata/output/over_window_function.yaml
- src/frontend/src/binder/expr/function/aggregate.rs
- src/frontend/src/binder/expr/function/mod.rs
- src/frontend/src/binder/expr/function/window.rs
- src/sqlparser/src/ast/mod.rs
Previously our `bind_function` is a mess. An example is #17560, which is because we bind UD(A/T)F and window function in different path, and we never considered a combination of the two.
This PR re-organizes `bind_function` and is a pre-requisition for fixing #17560.
</details>
> fix(binder): fix function call binding

- e2e_test/udf/bug_fixes/17560_udaf_as_win_func.slt
- src/frontend/src/expr/window_function.rs
> fix(udf): allow udaf as window function

- e2e_test/udf/bug_fixes/18202_sql_udf_aggregate_prefix.slt
- src/frontend/src/binder/expr/function/mod.rs
- src/frontend/src/binder/mod.rs
> fix(udf): allow `aggregate:` prefixed sql udf

- dashboard/README.md
- dashboard/lib/api/metric.ts
- dashboard/pages/fragment_graph.tsx
See the demo: https://www.notion.so/risingwave-labs/Backpressure-Graph-improvements-a11b0c5c74d54202922acb071aca72a0?pvs=4
Currently dashboard calculates the backpressure with the following mechanism.
1. Poll the `actor_buffer_output_blocking_ns` metric from `meta` / `prometheus` at a fixed duration (5s).
2. After polling, get the difference between previous and current `blocking_duration`.
3. Then backpressure rate is calculated as:
```
delta_blocking_duration / fixed_duration
```
4. This means if the blocking duration is a few minutes, it will show up on the graph for 5s, but in the subsequent epoch, it shows up `0`, …
> feat(dashboard): visualize average backpressure rather than spot backpressure

- e2e_test/subscription/main.py
- src/batch/src/executor/log_row_seq_scan.rs
- src/common/src/array/stream_chunk.rs
- src/frontend/src/handler/declare_cursor.rs
- src/frontend/src/handler/show.rs
- src/frontend/src/optimizer/plan_node/generic/log_scan.rs
- src/frontend/src/session/cursor_manager.rs
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/src/ast/statement.rs
- src/sqlparser/src/keywords.rs
- src/sqlparser/src/parser.rs
https://github.com/risingwavelabs/risingwave/issues/18208
1. Change the default behavior of DECLARE cursor_name SUBSCRIPTION CURSOR FOR subscription_name to SINCE now() without backfilling historical data.
2. Change op column type from int16 to varchar to make it more understandable: 1 -> insert, 2 -> update_insert, 3 -> delete, 4 -> update_delete
3. support` show cursors` and `show subscription cursors`:
`show cursors` will return all query cursor in this seesion
`show subscription cursors` will return all subscription cursor and subscription name in this seesion
after this pr
1. **BREAKING CHANGE:** `DECLARE …
> feat(suscription): Improving usability of subscription

- src/connector/src/sink/log_store.rs
- src/stream/src/executor/monitor/streaming_stats.rs
Resolve https://github.com/risingwavelabs/risingwave/issues/18224
The previous bug is because the latest read epoch is 0 when no data is read, and if the latest write epoch is set before collecting metrics, the subtraction between latest write epoch and latest read epoch will be huge, and cause false alerting on log store lag too large.
In this PR, we fix this by setting the initial read epoch to the current timestamp so that the initial log store lag will be small.
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide …
> fix(log-store): fix incorrect lag caused by invalid initial read epoch

- src/connector/Cargo.toml
- src/connector/src/sink/file_sink/azblob.rs
- src/connector/src/sink/file_sink/mod.rs
- src/connector/src/sink/file_sink/opendal_sink.rs
- src/connector/src/sink/mod.rs
- src/connector/with_options_sink.yaml
- src/frontend/src/handler/create_sink.rs
As title, test passed locally.
Please update the document, and this newly added sink is parallel with the GCS sink and S3 sink. For the Azure Blob sink fields, although the `account key` and `account name` are optional, they can only be left blank in one case: when the workload identity token is already configured (in other words, even cloud users need to configure these two fields). If you need assistance, please contact me.  cc@hengm3467 for scheduling this task. …
> feat(connector): introduce azblob sink

- src/storage/src/hummock/sstable/block.rs
- src/storage/src/hummock/sstable/builder.rs
The `add_raw_block` function is a feature introduced by the fast compaction optimization , which tries to optimize small blocks in the block copy process. This PR fixes the problem of switching table ids, which can break the constraint that a block contains only one table's data.
</details>
> fix(storage): Fix the bug that switch table_id breaks block data constraints.

- e2e_test/streaming/aggregate/wrap_scalar.slt
- src/expr/core/src/aggregate/def.rs
- src/frontend/src/optimizer/plan_node/generic/agg.rs
- src/stream/src/executor/aggregation/minput.rs
After several previous PRs:
- https://github.com/risingwavelabs/risingwave/pull/18177
- https://github.com/risingwavelabs/risingwave/pull/18203
we can now easily support using `aggregate:` prefixed scalar function (including UDF) as streaming aggregate function. This resolves #16767.
- Support `AGGREGATE:` prefixed scalar function in streaming aggregation
> feat(agg): support `aggregate:` prefixed scalar function in streaming agg

- src/connector/src/source/nats/mod.rs
- src/connector/with_options_source.yaml
Currently, the `backoff` and `filter_subjects` fields are required due to a missing `default` attribute, causing source creation to fail when they are not defined.
However, these fields should are supposed to be optional and should allow the creation of the source to proceed, even if they are not defined. 
This PR adds the missing `default` attribute, which fixes the above issue.
Related to  https://github.com/risingwavelabs/risingwave/pull/17615
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of …
> fix(source/nats): add missing `default` attribute for vectors

- src/storage/src/hummock/compactor/shared_buffer_compact.rs
- src/storage/src/hummock/event_handler/hummock_event_handler.rs
- src/storage/src/hummock/event_handler/uploader/mod.rs
- src/storage/src/hummock/local_version/pinned_version.rs
After https://github.com/risingwavelabs/risingwave/pull/18053, hummock can split CN submitted ssts based on table stats, so there is no longer the problem of multiple compaction groups being interfered with due to inaccurate sizes. 
So we can remove the logic of submitting ssts by compaction group on the CN side to reduce logic complexity and upload iops. This isn't a radical optimization , but I think it simplifies the logic on the CN side and is worth making as a separate change.
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release …
> feat(storage): remove shared buffer compaction grouped payload

- src/stream/src/executor/source/source_backfill_executor.rs
A minor refactor: previously `unfinished_splits` and `states` contains duplicated information (which splits are finished), and we need to update both whenever splits change, which is error-prone.
This PR changes `unfinished_splits` to `splits`, which contain all splits, and do not need careful maintainance any more.
</details>
> refactor: simplify SourceBackfill's memory state

- src/connector/src/macros.rs
- src/connector/src/parser/additional_columns.rs
- src/connector/src/source/base.rs
- src/connector/src/source/filesystem/opendal_source/azblob_source.rs
- src/connector/src/source/filesystem/opendal_source/mod.rs
- src/connector/src/source/filesystem/opendal_source/opendal_enumerator.rs
- src/connector/src/source/mod.rs
- src/connector/src/source/reader/reader.rs
- src/connector/src/with_options.rs
- src/connector/with_options_source.yaml
- src/frontend/src/handler/create_source.rs
- src/frontend/src/scheduler/plan_fragmenter.rs
- src/stream/src/executor/source/fetch_executor.rs
- src/stream/src/from_proto/source/fs_fetch.rs
As title, aligned with risingwave-cloud.
Add azblob file source, which is parallel to the existing s3 source, gcs source
</details>
> feat(connector): support azblob file source

- src/connector/src/sink/trivial.rs
Sink decoupling is not applicable to trivial sink because it introduces overhead with no benefits.
Sink decoupling will also make "Write Ops" > 0 even if source throughput drops to 0 because sink log store will write one row per barrier regardless of whether the barrier is empty, which may confuse the perf pipeline.
Related: #18181, #18268
</details>
> fix: disable sink decouple for trivial sink

- java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/BulkProcessorAdapter.java
- java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/ElasticBulkProcessorAdapter.java
- java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/EsSink.java
- java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/EsSinkConfig.java
- java/connector-node/risingwave-sink-es-7/src/main/java/com/risingwave/connector/OpensearchBulkProcessorAdapter.java
max_task_num：Maximum number of lines written to es at the same time
retry_on_conflict：Number of retries for es ooc
We add two optional option for es sink
`retry_on_conflict `: default is 3. The num of retries after an optimistic lock failure for es
`batch_size_kb  `: the max size of each request batch
`batch_num_messages`: the max rows of each request batch
（batch exceeds the limit of `batch_size_kb   `or `batch_num_messages`, we will send a batch）
`concurrent_requests `:the max number of threads per degree of parallelism
</details>
> feat(sink): add es retry_on_conflict and max_task_num

- src/connector/src/sink/kafka.rs
- src/connector/with_options_sink.yaml
Currently, if user does not specify the `properties.message.timeout.ms` in the options, the default message timeout is 5 seconds, which seems too small. In this PR, we will not explicitly set a default value for this property when not specified, and the default value will be used.
In this PR, we change the default behavior of kafka sink message timeout when `properties.message.timeout.ms` is not explicitly specified when creating a sink. Previously, the default message timeout was 5 seconds. After this PR, we will change it to the 5 minutes, which is the default value of the official kafka library.
</details>
> feat(sink): use official default message_timeout_ms

- proto/stream_service.proto
- src/compute/src/rpc/service/stream_service.rs
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/creating_job/mod.rs
- src/meta/src/barrier/creating_job/status.rs
- src/meta/src/barrier/recovery.rs
- src/meta/src/barrier/rpc.rs
- src/meta/src/model/stream.rs
- src/meta/src/stream/scale.rs
- src/meta/src/stream/stream_manager.rs
- src/rpc_client/src/stream_client.rs
- src/stream/src/task/barrier_manager.rs
- src/stream/src/task/stream_manager.rs
After https://github.com/risingwavelabs/risingwave/pull/18104, when handling `BuildActor` request, we simply spawn the actors and save the join handle. After the process of building actors is simplified, we can further postpone spawning actor till inject barrier, so that
* stream service rpc `broadcast_actor_info_table`, `update_actors` and `build_actors` can be removed, and the works of these rpc can be done together in `InjectBarrier`.
* on CN side, all spawned actors are part of the streaming graph, and we don't need to handle the case of actors that are spawned but not joined in the streaming graph
* we can avoid …
> refactor(meta): build actors in inject barrier

- src/common/metrics/src/relabeled_metric.rs
- src/storage/src/monitor/local_metrics.rs
- src/storage/src/monitor/monitored_storage_metrics.rs
- src/stream/src/executor/barrier_align.rs
- src/stream/src/executor/dispatch.rs
- src/stream/src/executor/hash_join.rs
- src/stream/src/executor/merge.rs
- src/stream/src/executor/monitor/streaming_stats.rs
- src/stream/src/executor/union.rs
Preparation for following works.
- Adopt `easy_ext` to simplify construction.
- Rename `with_label_values` to `with_guarded_label_values` to make the interface consistent with the un-relabelled ones.
</details>
> refactor(metrics): refine relabelled metrics interfaces

- Makefile.toml
- risedev
- src/risedevtool/common.toml
- src/risedevtool/src/bin/risedev-dev.rs
- src/risedevtool/src/task/configure_tmux_service.rs
- src/risedevtool/src/task/etcd_service.rs
- src/risedevtool/src/task/grafana_service.rs
- src/risedevtool/src/task/minio_service.rs
- src/risedevtool/src/task/prometheus_service.rs
- src/risedevtool/src/task/pubsub_service.rs
- src/risedevtool/src/task/redis_service.rs
- src/risedevtool/src/task/tempo_service.rs
- src/risedevtool/src/util.rs
Developers may install `risedev` to PATH with a custom name like `r+`. In this case, it would be better if we prompt users with the actual name of the executable.
</details>
> feat(risedev): prompt user with `argv[0]` instead of hard-coded `./risedev`

- src/stream/src/executor/source/source_backfill_executor.rs
step 1 of #18299, see there for the motivation and a state diagram of the new design.
The main idea of the code change is to consolidate logic into `handle_upstream_row` and `handle_backfill_row`.
</details>
> refactor: add target_offsets to determinine if source backfill finished

- e2e_test/source/cdc_inline/alter/cdc_table_alter.slt
- e2e_test/source/cdc_inline/auto_schema_change_mysql.slt
- src/common/src/catalog/column.rs
- src/connector/src/parser/unified/debezium.rs
- src/connector/src/source/manager.rs
- src/frontend/src/handler/alter_table_column.rs
- src/frontend/src/handler/create_sink.rs
- src/frontend/src/handler/create_table.rs
- src/frontend/src/rpc/mod.rs
- src/meta/service/src/ddl_service.rs
- Add `bind_sql_column_constraints` to the support default value during `ALTER TABLE` process
- Parse the `defaultValueExpression` field of schema change message to handle default value in auto schema change
**We only handle constant default value expression.**
```json
"tableChanges": [
{
"type": "ALTER",
"id": "\"mydb\".\"t2\"",
"table":
{
"defaultCharsetName": "utf8mb4",
"primaryKeyColumnNames":
[
"id"
],
"columns":
[
{
"name": "v5",
"jdbcType": 8,
"nativeType": null,
"typeName": "DOUBLE",
"typeExpression": "DOUBLE",
"charsetName": null,
"length": 5,
"scale": 2,
"position": 6,
"optional": true,
"autoIncremented": …
```
> feat(cdc): support constant default value for alter table ADD COLUMN

- java/connector-node/risingwave-sink-iceberg/src/main/java/com/risingwave/connector/catalog/JniCatalogWrapper.java
- src/connector/src/sink/iceberg/jni_catalog.rs
- Related https://github.com/risingwavelabs/risingwave/issues/18363
- Support create table and exists interface for iceberg jdbc catalog.
</details>
> feat(iceberg): support create table for jdbc catalog

- e2e_test/s3/fs_parquet_source_and_sink.py
- e2e_test/s3/fs_source_v2.py
- e2e_test/s3/fs_source_v2_new_file.py
- src/connector/Cargo.toml
- src/connector/src/source/filesystem/opendal_source/mod.rs
- src/connector/src/source/reader/reader.rs
- src/connector/with_options_source.yaml
- src/stream/src/executor/source/list_executor.rs
Co-authored-by: congyi <15605187270@163.com>
Co-authored-by: congyi wang <58715567+wcy-fdu@users.noreply.github.com> \
resolve https://github.com/risingwavelabs/risingwave/issues/18327
</details>
> fix: s3 source cannot read incremental files (#18017)

- proto/stream_plan.proto
- src/frontend/planner_test/tests/testdata/output/agg.yaml
- src/frontend/planner_test/tests/testdata/output/append_only.yaml
- src/frontend/planner_test/tests/testdata/output/bushy_join.yaml
- src/frontend/planner_test/tests/testdata/output/ch_benchmark.yaml
- src/frontend/planner_test/tests/testdata/output/cse_expr.yaml
- src/frontend/planner_test/tests/testdata/output/dynamic_filter.yaml
- src/frontend/planner_test/tests/testdata/output/lateral_subquery.yaml
- src/frontend/planner_test/tests/testdata/output/limit.yaml
- src/frontend/planner_test/tests/testdata/output/mv_column_name.yaml
- src/frontend/planner_test/tests/testdata/output/nexmark.yaml
- src/frontend/planner_test/tests/testdata/output/nexmark_source.yaml
- src/frontend/planner_test/tests/testdata/output/nexmark_temporal_filter.yaml
- src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml
- src/frontend/planner_test/tests/testdata/output/share.yaml
- src/frontend/planner_test/tests/testdata/output/stream_dist_agg.yaml
- src/frontend/planner_test/tests/testdata/output/temporal_join.yaml
- src/frontend/planner_test/tests/testdata/output/tpch.yaml
- src/frontend/src/optimizer/plan_node/logical_agg.rs
- src/frontend/src/optimizer/plan_node/stream_simple_agg.rs
- src/frontend/src/optimizer/plan_node/stream_stateless_simple_agg.rs
- src/stream/src/executor/agg_common.rs
- src/stream/src/executor/integration_tests.rs
- src/stream/src/executor/simple_agg.rs
- src/stream/src/executor/test_utils.rs
- src/stream/src/from_proto/simple_agg.rs
- fix https://github.com/risingwavelabs/risingwave/issues/18055#issuecomment-2325326447 introduced in https://github.com/risingwavelabs/risingwave/pull/17945
- revert #18292 
</details>
> feat(streaming): add `must_output_per_barrier` flag for stream simple agg

- e2e_test/source_inline/kafka/shared_source.slt
- src/connector/src/source/base.rs
- src/connector/src/source/kafka/enumerator/client.rs
- src/connector/src/source/kafka/source/reader.rs
- src/connector/src/source/reader/reader.rs
- src/stream/src/executor/source/source_backfill_executor.rs
step 2 & 3 of https://github.com/risingwavelabs/risingwave/issues/18299, see there for the motivation and a state diagram of the new design.
</details>
> refactor: use high watermark to finish backfill faster

- e2e_test/batch/types/map.slt.part
- proto/expr.proto
- src/common/src/types/jsonb.rs
- src/expr/impl/src/scalar/jsonb_record.rs
- src/frontend/src/binder/expr/function/builtin_scalar.rs
- src/frontend/src/expr/pure.rs
- src/frontend/src/optimizer/plan_expr_visitor/strong.rs
https://github.com/risingwavelabs/risingwave/issues/17743
Support converting jsonb -> map by `jsonb_populate_map(map,jsonb)->map`. (This is similar to #13421)
- Why not `jsonb_to_map(jsonb)->map`? Because we can't do the type inference (can't infer return type from the input type).
- Why not `cast(jsonb) -> map`? This seems OK, but might increase the complexity of type inference. Cast is a deep dark area. …
> feat(expr): support `jsonb_populate_map`

- risedev.yml
- src/risedevtool/src/bin/risedev-compose.rs
- src/risedevtool/src/bin/risedev-dev.rs
- src/risedevtool/src/config.rs
- src/risedevtool/src/task/configure_tmux_service.rs
> feat(risedev): support providing env var in yaml config

- src/frontend/src/handler/create_table.rs
- Create a table without primary with engine iceberg. In this case, we will use _row_id as primary key.
</details>
> feat(iceberg): support create table without pk for nimtable

- src/batch/src/executor/join/distributed_lookup_join.rs
- src/batch/src/executor/join/local_lookup_join.rs
- src/batch/src/executor/log_row_seq_scan.rs
- src/batch/src/executor/row_seq_scan.rs
- src/common/src/hash/consistent_hash/bitmap.rs
- src/common/src/hash/consistent_hash/vnode.rs
- src/common/src/hash/table_distribution.rs
- src/common/src/util/scan_range.rs
- src/ctl/src/cmd_impl/table/scan.rs
- src/frontend/src/scheduler/plan_fragmenter.rs
- src/storage/hummock_test/src/state_store_tests.rs
- src/storage/src/hummock/iterator/change_log.rs
- src/stream/src/common/log_store_impl/kv_log_store/serde.rs
- src/stream/src/common/table/test_state_table.rs
- src/stream/src/executor/watermark_filter.rs
- src/stream/src/from_proto/mview.rs
- src/stream/src/from_proto/watermark_filter.rs
This is a progress towards #15900.
Specifically in the upcoming PRs, we aim to decrease the direct references on `VirtualNode::COUNT` within the codebase. The total vnode count will be provided as a parameter in the refactored functions, although it will remain hardcoded as `VirtualNode::COUNT` at the call-site. Eventually, it will be made user-facing.
This PR refactors the `TableDistribution`. Logic changes are:
- Will use bitmaps with all high bits and of length 1 for singleton table. Note that it's not 256 any more.
If this PR includes changes that directly affect users or other significant modifications relevant to …
> feat: variable vnode count support in table distribution

- Cargo.lock
- src/connector/Cargo.toml
- src/connector/codec/src/decoder/mod.rs
- src/connector/src/parser/protobuf/parser.rs
- src/connector/src/parser/unified/mod.rs
- src/connector/src/parser/unified/protobuf.rs
Revert #12291 which attempts to reinvent canonical JSON for `google.protobuf.Any` with ugly and buggy code.
https://protobuf.dev/reference/protobuf/google.protobuf/#json
This is a pre-req to fix (via refactoring) the parsing of normal message/struct according to expected RisingWave column data type. Right now the expected RisingWave column data type is ignored and it could potentially return a different Datum causing mismatch panic.
The unit tests will be updated to expect-test in a follow-up.
Given the documentation has been wrong since day 0 the feature was "finished", I think we can keep it as hidden / unreleased …
> fix(source): Protobuf `Any` as canonical JSON

- src/connector/src/connector_common/common.rs
- src/connector/with_options_sink.yaml
- src/connector/with_options_source.yaml
> feat: support more SSL related configurations in Kafka connector

- src/batch/src/task/consistent_hash_shuffle_channel.rs
- src/common/src/hash/consistent_hash/mapping.rs
- src/common/src/hash/consistent_hash/vnode.rs
- src/common/src/hash/table_distribution.rs
- src/common/src/util/row_id.rs
- src/common/src/util/scan_range.rs
- src/common/src/vnode_mapping/vnode_placement.rs
- src/expr/impl/src/scalar/vnode.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/stream/stream_graph/schedule.rs
- src/meta/src/stream/stream_manager.rs
- src/meta/src/stream/test_scale.rs
- src/stream/src/common/log_store_impl/kv_log_store/test_utils.rs
- src/stream/src/executor/dispatch.rs
This is a progress towards #15900.
This PR refactors the `VirtualNode` and `VnodeMapping`. Logic changes are:
- Derive vnode count from the input (like the length of a vnode mapping or bitmap), instead of using `VirtualNode::COUNT`.
</details>
> feat: variable vnode count support in vnode structure

- src/meta/src/hummock/manager/commit_epoch.rs
- src/meta/src/hummock/manager/tests.rs
- src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
- src/storage/hummock_sdk/src/sstable_info.rs
- src/storage/hummock_test/src/hummock_storage_tests.rs
The main branch will directly commits the sst directly to both cgs (when match_ids is a subset of group_table_ids) , the sst_id is not changed and something goes wrong when merge is triggered.
https://github.com/risingwavelabs/risingwave/blob/cb29fe0a3221638b5dc62c3ea543b08dd567135d/src/storage/src/hummock/utils.rs#L112
Hummock `filter_single_sst` via binary_search which rely on the ordering of sstable_info.table_ids. I made some mistakes before this PR that broke ordering, so I'm reviewing the code and adding restrictions and doc to ensure ordering of table_ids. Thanks @hzxa21 for help …
> fix(storage): fix correct_commit_ssts with sst table_ids

- Cargo.lock
- src/meta/Cargo.toml
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/progress.rs
- src/meta/src/manager/metadata.rs
- src/meta/src/model/stream.rs
- src/meta/src/stream/scale.rs
- src/stream/src/executor/source/source_backfill_executor.rs
- src/stream/src/executor/source/source_backfill_state_table.rs
- src/stream/src/from_proto/source_backfill.rs
- src/stream/src/task/barrier_manager/managed_state.rs
Support blocking DDL for source #18338
Core changes:
1. Add `SourceScan` to `tracking_progress_actor_ids` of a MV. So a MV will not enter `Created` state until the `SourceBackfillExecutor`'s actor reported progress.
2. In `SourceBackfillExecutor`, the progress reporting is a dummy one: it simply reused MV's mechanism, and only uses `finish`.
---
A subtle case to consider: whether to report `finish` after entering `SourceCatchingUp` state, or after `Finished` state? 
- `Finished` might be more intuitive and safe. However, it may make a foreground DDL blocked forever until upstream messages come. (See state diagram in …
> feat: track progress for SourceBackfill (blocking DDL)

- src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
> fix(storage): fix duplicated sst_id generated by split_sst function

- src/meta/src/hummock/manager/commit_epoch.rs
- src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
as title
related to https://github.com/risingwavelabs/risingwave/pull/18431
</details>
> fix(storage): cherry-pick fix duplicated sst_id generated by split_sst function

- src/meta/src/serving/mod.rs
When the streaming parallelism of a fragment is updated, its serving parallelism should be updated accordingly.
However after #14191, all fragments's serving parallelism will be updated whenever any fragment's streaming parallelism is updated. It is both unnecessary and computationally intensive.
</details>
> fix(meta): correctly update serving parallelism mapping

- src/common/src/array/arrow/arrow_iceberg.rs
- Convert RW decimal to iceberg decimal(28,10)
</details>
> feat(nimtable): fix decimal(28, 10)

- src/frontend/src/handler/create_table.rs
- src/frontend/src/handler/drop_table.rs
- Make drop table more robust. Creating a table could be failure in the middle, so we need to drop table can handle the partially created table more robust.
</details>
> feat(nimtable): nimtable make drop table more robust

- src/batch/src/worker_manager/worker_node_manager.rs
- src/common/src/bitmap.rs
- src/common/src/config.rs
- src/common/src/vnode_mapping/vnode_placement.rs
- src/frontend/src/handler/alter_parallelism.rs
- src/frontend/src/scheduler/distributed/stage.rs
- src/frontend/src/scheduler/local.rs
- src/frontend/src/scheduler/plan_fragmenter.rs
- src/jni_core/src/lib.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/serving/mod.rs
- src/meta/src/stream/scale.rs
- src/meta/src/stream/stream_graph/schedule.rs
- src/meta/src/stream/test_scale.rs
- src/stream/src/executor/dispatch.rs
- src/stream/src/executor/row_id_gen.rs
This is a progress towards #15900.
This PR refactors the batch & streaming scheduler.
</details>
> feat: variable vnode count support in batch/streaming scheduler

- src/meta/model_v2/migration/src/lib.rs
- src/meta/model_v2/migration/src/m20240909_101830_nimtable_dev.rs
> fix(nimtable): fix sql backend with new column `Engine`

- src/frontend/src/handler/create_index.rs
- src/frontend/src/handler/create_mv.rs
- src/frontend/src/handler/create_sink.rs
- src/frontend/src/handler/create_source.rs
- src/frontend/src/handler/create_table.rs
- src/frontend/src/handler/create_table_as.rs
- src/frontend/src/stream_fragmenter/graph/fragment_graph.rs
- src/frontend/src/stream_fragmenter/mod.rs
Refactor to extract common code for filling some fields in the fragment graph.
</details>
> refactor(frontend): extract filling fields in fragment graph

- docker/docker-compose.yml
as title, we do a license check when bootstrap, we actually get an empty string and try to interpret it as a license key, leading to a check error on compute node. 
We expect it to be NULL and start the server as a free-tier. 
The case does not cause any trouble because the check is introduced in v2.0, which has not been rolled out. 
</details>
> fix: empty string as license key stuck docker compose

- src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
Otherwise the error `unable to get size of removed object id` will arise.
</details>
> fix(metric): include table_change_log when calculating object size

- proto/hummock.proto
- src/meta/model_v2/migration/src/lib.rs
- src/meta/model_v2/migration/src/m20240820_081248_add_time_travel_per_table_epoch.rs
- src/meta/model_v2/src/hummock_epoch_to_version.rs
- src/meta/service/src/hummock_service.rs
- src/meta/src/hummock/manager/commit_epoch.rs
- src/meta/src/hummock/manager/time_travel.rs
- src/meta/src/hummock/manager/transaction.rs
- src/meta/src/hummock/mock_hummock_meta_client.rs
- src/rpc_client/src/hummock_meta_client.rs
- src/rpc_client/src/meta_client.rs
- src/storage/src/hummock/hummock_meta_client.rs
- src/storage/src/hummock/store/hummock_storage.rs
This PR is meta node part of the work to support time travel query on a per-table basis.
#18214
</details>
> feat(meta): support time travel query on a per-table basis (part1)

- .gitignore
- Cargo.lock
- Cargo.toml
- e2e_test/iceberg/main.py
- e2e_test/iceberg/start_spark_connect_server.sh
- e2e_test/iceberg/test_case/iceberg_sink_no_partition_append_only_table.slt
- e2e_test/iceberg/test_case/no_partition_append_only.toml
- e2e_test/iceberg/test_case/no_partition_upsert.toml
- e2e_test/iceberg/test_case/partition_upsert.toml
- e2e_test/iceberg/test_case/range_partition_upsert.toml
- src/common/src/array/arrow/arrow_impl.rs
- src/common/src/array/arrow/arrow_udf.rs
- src/connector/src/sink/iceberg/mod.rs
- fix #18451
- fix #16545
- Note: source with nested type is not supported yet, because not implemented in iceberg-rs #18474
- Note: create table in risingwave side is not supported yet https://github.com/risingwavelabs/risingwave/issues/18363#issuecomment-2340432750
</details>
> fix(iceberg): fix map - arrow convert & fix sink nested types to iceberg

- proto/connector_service.proto
- src/connector/src/sink/coordinate.rs
- src/connector/src/sink/decouple_checkpoint_log_sink.rs
- src/meta/src/manager/sink_coordination/coordinator_worker.rs
- src/meta/src/manager/sink_coordination/handle.rs
- src/meta/src/manager/sink_coordination/manager.rs
- src/meta/src/manager/sink_coordination/mod.rs
- src/rpc_client/src/sink_coordinate_client.rs
Our sink coordinator worker determine whether all sink metadata of an epoch are collected by checking if all vnodes are collected. The coordinator worker handles epochs one by one. When receiving a commit request from one parallelism, it will blocking await on the commit request from all other parallelisms, and then commit all, and then wait for the next epoch. In the current implementation there won't be concurrent epoch. 
The current implementation works in normal case, but doesn't work in the case of scale out, because when scale out happens, the newly created parallelism may send a commit request of a later epoch …
> feat(sink): reimplement sink coordinator worker and support scale

- e2e_test/source_inline/kafka/protobuf/recover.slt
- src/connector/src/parser/protobuf/parser.rs
- src/connector/src/parser/unified/protobuf.rs
Previously, the source protobuf parser is ignoring the expected column data type, and returning whatever protobuf value is on the wire. This can potentially cause a data type - scalar variant mismatch panic, especially during schema evolution.
This PR fixed the protobuf parsing logic to be guided by expected column data type, which is aligned with json and avro parser.
As mentioned in #18380 (pre-req of this refactor/fix), the unit tests will be DRY-ed in a follow-up. …
> fix(source): parse protobuf into expected struct/array

- Cargo.lock
- e2e_test/source_inline/kafka/protobuf/recover.slt
- src/connector/Cargo.toml
- src/connector/codec/src/decoder/mod.rs
- src/connector/src/parser/protobuf/parser.rs
- src/connector/src/parser/unified/mod.rs
- src/connector/src/parser/unified/protobuf.rs
Cherry picking #18419 and its pre-req #18380 onto branch release-2.0
The 2 commits can actually be sequentially cherry-picked cleanly without conflict by the automation, but I am melting them into 1 single cherry-pick to emphasize their tight relation.
> fix(source): parse protobuf into expected struct/array (#18419) and its pre-req #18380

- src/batch/src/worker_manager/worker_node_manager.rs
If the serving mapping of a fragment is temporarily unavailable due to asynchronous notification, we fallback to use the streaming mapping to schedule. Note that the streaming mapping must be available, even if the table is just created, as we guarantee its notification goes prior to the catalog.
The reason for this change is to enable support for per-fragment variable vnode count. If we lack information about a fragment's mapping, it can be challenging to create a dummy vnode mapping with an unknown length.
This is an alternative of https://github.com/risingwavelabs/risingwave/pull/10815.
If this PR includes changes …
> refactor(batch): schedule with streaming mapping if serving is temporarily unavailable

- src/connector/codec/src/decoder/protobuf/parser.rs
- src/connector/codec/tests/integration_tests/protobuf.rs
- src/connector/codec/tests/test_data/all-types.proto
> feat(source): support ingesting protobuf map

- src/meta/src/barrier/command.rs
- src/meta/src/stream/source_manager.rs
prev #18134 (#18167, #18158) does not fix the case completely. 
In the prev fix, we check each mutation and removed the dup one from the assignment. But we have no way to know the prev assignment and it can cause the dup assignment as well. 
Giving a more concrete example here
`T0: actor_1(split_1, split_2), actor_2(split_3)`
and we have a dup assignment, the mutation looks like `{"actor_1"; ["split_1, split_2"], "actor_2": [split_2, split_3]}`, after the check impl, the mutation may look like `{"actor_1"; ["split_1], "actor_2": [split_2, split_3]}` as we **RANDOMLY** remove the dup split from the assignment. 
So …
> fix: dup split assignment in source

- src/expr/impl/src/aggregate/approx_percentile.rs
- src/frontend/planner_test/tests/testdata/input/agg.yaml
- src/frontend/planner_test/tests/testdata/output/agg.yaml
- src/frontend/src/binder/expr/function/aggregate.rs
- src/stream/src/executor/approx_percentile/global_state.rs
Closes https://github.com/risingwavelabs/risingwave/issues/18545
As per title. There were two bugs discovered.
First, `0.0` is not properly handled. It will result in a logarithmic base of `1`, and the behaviour is undefined. So we will just ban it first, until streaming `percentile_cont` is supported, then we can remap it to that instead.
Next, for `quantile_count` should be `q(n-1)` as mentioned in the ddsketch paper. This PR fixes it. …
> fix(stream): handle `0.0` case of approx percentile, and fix computation of `quantile_count`

- src/meta/src/controller/streaming_job.rs
As title.
This is the root cause of duplicated source splits. Resolves https://github.com/risingwavelabs/risingwave/issues/16235.
1. Assume there is only 1 source split and 4 source actors at the beginning.
2. Run `alter materialized view ... set parallelism = 8`. There is 50% chance that the only 1 split is assigned to a new actor.
3. Because of this bug, the old actor's split assignment was not updated, causing duplication.
4. Once recovery or restarts, the duplicated splits will cause duplicated state table writes, causing assertion failure of #16235. …
> fix(metadata v2): existing actor splits were not updated

- src/meta/src/barrier/command.rs
- src/meta/src/stream/source_manager.rs
Revert #18541 and #18134. It turns out that the problem was not there. 
The issue was finally fixed by #18553.
</details>
> fix: revert split assignment check

- src/frontend/planner_test/tests/testdata/input/topn.yaml
- src/frontend/planner_test/tests/testdata/output/topn.yaml
- src/frontend/src/optimizer/plan_visitor/cardinality_visitor.rs
Previously we forgot to check whether there's a group key, treating all `LogicalTopN` as plain top-n, leading to incorrect results. Before this PR, the newly-added test case produced an incorrect result of 1, because we mistakenly believed that the group top-n yielded a constant number of rows.
https://github.com/risingwavelabs/risingwave/blob/49f4ab8e1cd08ae59434462e1950b2e5d39cd39a/src/frontend/src/optimizer/rule/trivial_project_to_values_rule.rs#L33 …
> fix(optimizer): correctly derive cardinality for group top-n

- proto/stream_service.proto
- src/meta/src/barrier/creating_job/mod.rs
- src/meta/src/barrier/creating_job/status.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/recovery.rs
- src/meta/src/barrier/rpc.rs
- src/meta/src/barrier/state.rs
- src/meta/src/manager/catalog/fragment.rs
- src/meta/src/manager/metadata.rs
- src/meta/src/stream/mod.rs
- src/meta/src/stream/stream_manager.rs
- src/rpc_client/src/stream_client.rs
- src/stream/src/executor/actor.rs
- src/stream/src/task/barrier_manager.rs
- src/stream/src/task/barrier_manager/managed_state.rs
- src/stream/src/task/stream_manager.rs
Previously when build actor and inject barrier are not done together, we have to include the barrier information together with the `StreamActor` to a combined `BuildActorInfo` when we build the actor. After we change to build actor when inject barrier in https://github.com/risingwavelabs/risingwave/pull/18270, we are able to get the subscription information from local barrier worker.
Therefore, in this PR, we won't generate the actor subscription info on meta node to generate the `BuildActorInfo`, but instead include only the `StreamActor` in the `InjectBarrierRequest`. Meanwhile, we incrementally maintain the global …
> refactor: maintain subscriptions in local barrier worker

- proto/hummock.proto
related to https://github.com/risingwavelabs/risingwave-extensions/blob/main/pkg/compaction/drive/driver.go
The driver changes the task status in two ways
1. Send faill https://github.com/risingwavelabs/risingwave-extensions/blob/123845fc61d9815216e6647173e2af2c6e4c94cd/pkg/compaction/drive/driver.go#L312
2. Unable to fetch the table catalogs for the task https://github.com/risingwavelabs/risingwave-extensions/blob/123845fc61d9815216e6647173e2af2c6e4c94cd/pkg/compaction/drive/driver.go#L403
This PR introduces a separate task status type to serve the serverless compaction module, to make it easier to distinguish the …
> feat(compaction): introduce new task status for serverless compaction

- risedev.yml
- src/connector/src/sink/encoder/avro.rs
- src/connector/src/sink/encoder/mod.rs
- src/connector/src/sink/encoder/proto.rs
- src/connector/src/sink/formatter/mod.rs
- src/connector/src/sink/mod.rs
Improve the error message. Motivated by a community enquiry as the error can't clearly show the error happened when building the **message key encoder**.
Before:
```
2: failed to validate sink
3: Encode error: encode sort error: field not present but required
```
After:
```
2: failed to validate sink
3: Failed to build key encoder
4: Encode error: encode sort error: field not present but required
```
If this …
> feat: improve error of building key encoder

- src/common/src/array/map_array.rs
- src/common/src/array/struct_array.rs
- src/common/src/types/mod.rs
- src/connector/src/sink/encoder/avro.rs
> feat(sink): support sink map to avro

- proto/meta.proto
- src/ctl/src/cmd_impl/meta/pause_resume.rs
- src/meta/service/src/stream_service.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/notifier.rs
- src/meta/src/barrier/schedule.rs
Previously in global barrier manager, we call `notify_started` providing with `BarrierInfo`. The `BarrierInfo` is ultimately used in the `println!` of `resume` and `pause` command of `risectl`.
In a future development, we may change to skip some commands when the cluster is empty (no streaming job) so that we won't call `commit_epoch` to hummock with empty table id list. In this case, we are be able to generate this `BarrierInfo` for these skipped command. Therefore, in this PR, we change to not providing `BarrierInfo` for `notify_started`, in the cost of reducing the log output of `pause` and `resume` for `risectl`.
If …
> refactor(meta): remove BarrierInfo and reduce pause and resume log output

- src/common/src/hash/consistent_hash/vnode.rs
- src/common/src/util/row_id.rs
- src/stream/src/executor/row_id_gen.rs
This is a progress towards https://github.com/risingwavelabs/risingwave/issues/15900.
This PR supports vnode count up to 16-bit in row-id generator.
Previously we reserved 10 bits for the vnode part in row-id, which limits the vnode count to 1024. This PR extends the format to dynamically allocate bits between the vnode part and the sequence part in row-id, allowing arbitrary vnode count up to 16-bit.
This does not affect the maximum throughput we support in row-id generator, i.e., still `1 << 22` rows per millisecond.
Note that there are some subtle cases that need to pay attention to, majorly in backward …
> feat(streaming): support up to 16-bit vnode count in row id gen

- src/storage/src/hummock/error.rs
- src/storage/src/hummock/store/hummock_storage.rs
- src/storage/src/hummock/time_travel_version_cache.rs
After partial checkpoint, the time travel's hummock version cache should use `(table_id, epoch)` as key rather than original `epoch`.
**The cache is necessary because a batch query may trigger many iterators in a compute node due to multiple vnodes.**
This PR also optimizes the lock used in cache implementation.
</details>
> refactor(storage): adapt time travel cache to partial checkpoint

- ci/scripts/build.sh
- ci/scripts/check.sh
- ci/scripts/common.sh
- ci/scripts/release.sh
cherry pick to v1.10 for future releases if any.
Close #18670
</details>
> fix(ci): fix static link for `openssl` (#18569)

- e2e_test/udf/bug_fixes/17560_udaf_as_win_func.slt
- proto/expr.proto
- src/expr/core/src/aggregate/def.rs
- src/expr/core/src/window_function/kind.rs
- src/expr/impl/src/window_function/aggregate.rs
- src/frontend/src/binder/expr/function/mod.rs
- src/frontend/src/optimizer/plan_node/generic/over_window.rs
Fixes #18436.
As a quick fix, currently the `retract` method of embedded UDAF, if defined, is not utilized. Let's fix the functionality first, and optimize the performance in later PR, which requires some more work to do.
</details>
> fix(agg): fix embedded UDAF as window function

- dashboard/next-env.d.ts
- e2e_test/sink/sink_into_table/basic.slt
- e2e_test/streaming/on_conflict.slt
- src/frontend/planner_test/tests/testdata/input/explain.yaml
- src/frontend/planner_test/tests/testdata/output/explain.yaml
- src/frontend/src/handler/create_sink.rs
- src/frontend/src/handler/create_table.rs
- src/frontend/src/optimizer/mod.rs
Much more complex than I think, more details in https://github.com/risingwavelabs/risingwave/pull/12240
The PK can be used to deduplicate the incoming records.
</details>
> feat: allow append only table with pk

- e2e_test/batch/catalog/pg_class.slt.part
- e2e_test/ddl/schema.slt
- src/frontend/src/catalog/system_catalog/information_schema/mod.rs
- src/frontend/src/catalog/system_catalog/information_schema/schemata.rs
- Resolve https://github.com/risingwavelabs/risingwave/issues/18708
</details>
> feat: support information_schema.schemata

- .github/workflows/audit.yml
- .github/workflows/auto-create-doc-issue-by-issue.yml
- .github/workflows/auto-update-helm-and-operator-version-by-release.yml
- .github/workflows/connector-node-integration.yml
- .github/workflows/dashboard.yml
- .github/workflows/license_check.yml
- .github/workflows/nightly-rust.yml
- .github/workflows/pr-title-checker.yml
- .github/workflows/typo.yml
There are warnings on the GitHub Actions due to Node.js 16
deprecation. Update the version of the actions to get rid of the warnings.
link: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20
Chore the GitHub Actions versions to get rid of the warning for node.js 16 EOL
Also will update  `fuyufjh/automatically-set-milestone-to-issue` when its done.
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact …
> chore(ci): fix the warning due to Node 16 EOL for GitHub Actions.

- src/connector/src/source/kinesis/enumerator/client.rs
- src/connector/src/source/kinesis/source/reader.rs
- src/connector/src/source/kinesis/split.rs
As part of #18697, this PR revisits the kinesis source connector and makes the offset semantics explicit in `KinesisOffset` and `KinesisSplit`. Backward-compatibility is achieved by `#[serde(alias = "...")]`.
</details>
> refactor(kinesis): rename fields of `KinesisOffset` and `KinesisSplit` to make everything explicit

- ci/scripts/e2e-sink-test.sh
- e2e_test/sink/file_sink.slt
- src/connector/src/sink/file_sink/opendal_sink.rs
as title, otherwise it will not raise error as we enable sink decouple.
close https://github.com/risingwavelabs/risingwave/issues/18228
</details>
> chore(sink): validate file sink when creating

- risedev.yml
- src/connector/src/sink/clickhouse.rs
- src/connector/src/sink/decouple_checkpoint_log_sink.rs
- src/connector/src/sink/deltalake.rs
- src/connector/src/sink/doris.rs
- src/connector/src/sink/file_sink/opendal_sink.rs
- src/connector/src/sink/iceberg/mod.rs
- src/connector/src/sink/log_store.rs
- src/connector/src/sink/mod.rs
- src/connector/src/sink/mongodb.rs
- src/connector/src/sink/remote.rs
- src/connector/src/sink/snowflake.rs
- src/connector/src/sink/sqlserver.rs
- src/connector/src/sink/starrocks.rs
- src/connector/src/sink/test_sink.rs
- src/connector/src/sink/writer.rs
- src/stream/src/executor/monitor/streaming_stats.rs
- src/stream/src/executor/sink.rs
- src/stream/src/from_proto/sink.rs
In other places (such as source), the usage of metrics is generally as follows:
- Inside `SourceMetrics`, there is a pair of `MetricsVec` instead of actual Metrics.
- Only when it comes to the specific working struct, build the actual `Metrics` from `MetricsVec` with particular labels.
While, on the sink side, `SinkMetrics` directly consist of a collection of Metrics.
- Refactor `SinkMetrics` from a set of **Metrics** to a set of **MetricVec**
- Introduce a `GLOBAL_SINK_METRICS`
- Move the real Metrics into separated places:
- `SinkWriterMetrics` for general sink metrics
- `LogWriterMetrics` 
- `LogReaderMetrics`
- …
> refactor: sink metrics

- src/connector/src/connector_common/common.rs
- src/connector/src/source/kinesis/mod.rs
- src/connector/src/source/kinesis/source/reader.rs
- src/connector/src/source/nats/mod.rs
- src/connector/src/source/nats/source/reader.rs
- src/connector/src/source/nats/split.rs
- src/connector/with_options_source.yaml
Seems we now prefer the following style of connector properties:
```
scan.startup.mode='timestamp',
scan.startup.timestamp.millis='123456'
```
This PR refines the NATS source connector to align with this style.
https://github.com/risingwavelabs/risingwave-docs/pull/2643
> fix(nats): align offset and property fields between NATS and others for better ux and dx

- src/connector/src/connector_common/common.rs
For source connector offset `XxxOffset::Latest`, we always mean to start from the next future record after the most recently available one. This applies for Kafka, Kinesis and Pulsar. This PR fixes the semantics for NATS.
</details>
> fix(nats): align the semantics of `scan.startup.mode=latest` of NATS with others

- src/meta/src/controller/fragment.rs
The previous query in #18515 works for SQLite but will be rejected by PostgreSQL. Rewritten with `sea-query`. Tested locally.
</details>
> fix(meta): fix query for `running_fragment_parallelisms` in postgres backend

- src/meta/src/hummock/manager/time_travel.rs
- src/storage/hummock_sdk/src/time_travel.rs
As time travel version is always retrieved for a specific table, its size can be minimized by only retaining `SstableInfo` relevant to this table.
</details>
> refactor(meta): reduce time travel hummock version size

- risedev.yml
- src/risedevtool/src/bin/risedev-dev.rs
- src/risedevtool/src/task/task_log_ready_check.rs
- Bump version to `17-alpine` (just released!), which seems to fix #18663 .
- Also check the logs for `listening on IPv4 address` to ensure readiness. This prevents the meta service from starting and being unable to connect to the SQL backend while the Postgres is still running its init process.
Here is the log when launching the Postgres container for the first time:
```
waiting for server to start....2024-09-27 07:42:09.361 UTC [114] LOG:  starting PostgreSQL 17.0 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 32-bit
2024-09-27 07:42:09.370 UTC [114] LOG:  listening on …
```
> fix(risedev): fix log check and startup failure for postgres

- src/frontend/src/catalog/catalog_service.rs
- src/frontend/src/handler/alter_rename.rs
- src/frontend/src/test_utils.rs
> refactor: unify duplicated alter_*_name methods

- Makefile.toml
- src/risedevtool/src/wait.rs
For the reason when use `./risedev d` failed to start, when the server and port is in used the error only shows `failed to wait for closing` This patch make the message better. Also make docker kill the containers named risingwave(which started by docker-compose.
when start docker-compose
```cli
cd risingwave/integration_tests/ad-ctr
docker compose up -d
```
then forget to close the docker container by `compose down`
./risedev d  error message only `failed to wait for closing` this path make the error message better
also fix the `./risedev k` only kill the container named `risedev` this patch add `risingwave` name to
`./risedev k` to make it easy to use
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License …
> fix: better error message for `./risedev d` timeout

- e2e_test/ddl/max_parallelism.slt
- proto/catalog.proto
- proto/meta.proto
- proto/stream_plan.proto
- src/ctl/src/cmd_impl/meta/migration.rs
- src/frontend/src/stream_fragmenter/graph/fragment_graph.rs
- src/frontend/src/stream_fragmenter/mod.rs
- src/meta/model_v2/migration/src/m20240911_083152_variable_vnode_count.rs
- src/meta/model_v2/src/streaming_job.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/manager/metadata.rs
- src/meta/src/model/stream.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/rpc/ddl_controller_v2.rs
- src/meta/src/stream/stream_graph/actor.rs
- src/meta/src/stream/stream_graph/fragment.rs
- src/meta/src/stream/stream_manager.rs
- src/meta/src/stream/test_fragmenter.rs
- src/tests/simulation/tests/integration_tests/scale/streaming_parallelism.rs
This is a progress towards https://github.com/risingwavelabs/risingwave/issues/15900.
Persist the max parallelism (vnode count) specified through session variable when a streaming job was created. Use that to check if a future parallelism change (with `ALTER .. SET PARALLELISM`) is valid, ensuring the behavior is consistent with setting session variable `streaming_parallelism` when the job was created.
Note that in some cases when there are no-shuffle exchanges between subgraphs, the `vnode_count` adopted by some fragment may not follow the job's `max_parallelism` at all. The subtle difference will be addressed when …
> refactor(meta): persist job-level max parallelism & check when `ALTER .. SET PARALLELISM`

- e2e_test/ddl/max_parallelism.slt
- proto/meta.proto
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_fragment_parallelism.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_fragments.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_streaming_parallelism.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_table_fragments.rs
- src/meta/service/src/stream_service.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/controller/utils.rs
- src/tests/simulation/tests/integration_tests/scale/shared_source.rs
This is a progress towards https://github.com/risingwavelabs/risingwave/issues/15900. Sequel to #18740.
Allow users to inspect max parallelism through system tables.
</details>
> feat(frontend): show job's max parallelism in system tables

- ci/scripts/deterministic-it-test.sh
- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/rpc.rs
Fix recovery test panic.
In `ControlStreamManager`, we always maintain that workers in field `nodes` are consistent to workers in `response_streams`. However, in method `remove_partial_graph`, we use `retain` when trying to send request, and will remove the node when failing to send the request, but we didn't remove the corresponding stream in `response_streams`, which causes inconsistency and causes subsequent panics. In this PR, we fix this inconsistency by storing the response_stream together with the request sender in the `ControlStreamNode`. Previously we have to introduce a `FutureUnordered` to concurrently poll …
> fix(meta): avoid removing control stream node when failed to send request

- ci/workflows/main-cron.yml
- e2e_test/s3/fs_sink.py
- src/connector/src/sink/file_sink/opendal_sink.rs
- src/frontend/src/handler/create_sink.rs
The implementation detail is almost the same with snowflake sink, and the difference is
- in snowflake sink, the file name contains a `uuid` to distinguish the parallelism, while the file sink directly uses `executor_id`.
- in snowflake sink, there are no line breaks between lines, but the file sink has.(I think it's more friendly with user)
Todo: 
Add json encode for file sink, which allow user to sink json files into object storage. …
> feat(sink): add json encode for file sink

- src/meta/src/controller/streaming_job.rs
This is a progress towards https://github.com/risingwavelabs/risingwave/issues/15900.
The table catalogs of internal tables are immediately persisted and broadcasted to other nodes when ids are allocated during the creation of a new streaming job. However, at that time we don't have scheduling info, i.e., the `vnode_count` of each fragment (then internal tables) hasn't been determined yet. As a result, we failed to persist the correct `vnode_count` in table catalogs.
In this PR, we fix this issue by updating that field in a separate step afterwards, together with other fields like `fragment_id`. Note that this only …
> fix(meta): persist correct vnode count for table catalogs in sql backend

- src/frontend/src/scheduler/distributed/stage.rs
Fix #18790.
#18786, which is previously blocked by this issue will demonstrate that the bug is fixed correctly.
</details>
> fix(batch): fix distributed batch query not properly throwing errors to PG client

- .cargo/config.toml
- docs/dev/src/build-and-run/intro.md
Signed-off-by: xxchan <xxchan22f@gmail.com>I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).
```
brew info llvm
`lld` is now provided in a separate formula:
brew install lld
```
wanted to use system linker, but #15407
</details>
> build(mac): brew install llvm -> lld

- e2e_test/batch/basic/generate_series.slt.part
- src/frontend/planner_test/tests/testdata/input/generate_series_with_now.yaml
- src/frontend/planner_test/tests/testdata/output/generate_series_with_now.yaml
- src/frontend/src/expr/type_inference/func.rs
> fix(expr): cast untyped `start` and `step` when inferring type for `generate_series`

- src/frontend/src/handler/alter_parallelism.rs
- src/frontend/src/handler/alter_source_column.rs
- src/frontend/src/handler/alter_source_with_sr.rs
- src/meta/model_v2/src/source.rs
- src/meta/service/src/stream_service.rs
- src/meta/src/controller/catalog.rs
- ban ALTER SOURCE (schema change) for shared source
- also examined all ALTER clauses for shared source, refined some behaviors
- alter state table for ALTER OWNER/SCHEMA
- ALTER RATE LIMIT: source rate limit is the same as non-shared source; backfill rate limit is not supported
- ALTER parallelism is not suppoorted
- Only meta V2 (SQL) is updated. Do not bother to update V1 …
> feat: ban ALTER SOURCE for shared source, and refine all ALTER clauses

- src/sqlparser/src/ast/legacy_source.rs
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/src/ast/statement.rs
- src/sqlparser/src/parser.rs
- src/sqlparser/tests/testdata/create.yaml
Resolves #18800
The `Display` logic had 3 bugs making it inconsistent with `parse_include_options`:
* Multiple items shall not be separated by comma.
* Header key shall be singled quoted.
* Header data type shall not be omitted for varchar. (Seems [undocumented](https://docs.risingwave.com/docs/current/include-clause/) feature)
For example,
* User input: `INCLUDE header 'foo' VARCHAR INCLUDE timestamp`
* Meta catalog `definition` contains: `INCLUDE header foo, INCLUDE timestamp`
Besides fixing the 3 issues, we also update the parsing logic to tolerate the extra comma caused by 1st bug. It is impossible to tolerate the …
> fix(sqlparser): `Display` multiple source `INCLUDE` columns correctly

- proto/hummock.proto
- src/meta/service/src/hummock_service.rs
- src/meta/src/hummock/manager/gc.rs
- src/meta/src/hummock/manager/mod.rs
- src/meta/src/hummock/mock_hummock_meta_client.rs
- src/rpc_client/src/hummock_meta_client.rs
- src/rpc_client/src/meta_client.rs
- src/storage/src/hummock/compactor/mod.rs
- src/storage/src/hummock/hummock_meta_client.rs
- src/storage/src/hummock/vacuum.rs
After the LIST pagination refactor #18737, the meaning of `ReportFullScanTaskRequest::total_object_count` has changed from "total object count in the object store" to "total object count of current page in the object store". 
To correctly set the metric `total_object_count` for prometheus, `ReportFullScanTaskRequest::total_object_count` should be accumulated on a per-page basis, and then updated in prometheus at the end. …
> fix(metric): correctly update storage object metric

- src/sqlparser/src/ast/legacy_source.rs
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/src/ast/statement.rs
- src/sqlparser/src/parser.rs
- src/sqlparser/tests/testdata/create.yaml
Cherry picking https://github.com/risingwavelabs/risingwave/pull/18813 onto branch release-2.0
> fix(sqlparser): `Display` multiple source `INCLUDE` columns correctly (#18813)

- .typos.toml
- Cargo.lock
- Cargo.toml
- src/common/Cargo.toml
- src/common/src/config.rs
- src/compute/src/rpc/service/monitor_service.rs
- src/connector/src/sink/catalog/desc.rs
- src/ctl/src/common/hummock_service.rs
- src/java_binding/src/hummock_iterator.rs
- src/storage/benches/bench_block_cache.rs
- src/storage/benches/bench_compactor.rs
- src/storage/benches/bench_multi_builder.rs
- src/storage/hummock_test/src/bin/replay/main.rs
- src/storage/src/hummock/iterator/test_utils.rs
- src/storage/src/hummock/sstable_store.rs
- src/storage/src/hummock/test_utils.rs
- src/storage/src/opts.rs
- src/storage/src/store_impl.rs
Changes:
- Upgrade foyer to 0.12
- Upgrade hashbrown to 0.15. (https://github.com/rust-lang/hashbrown/issues/564)
- Fix typos with latest typo-cli.
</details>
> refactor(cache): upgrade foyer to 0.12 and related deps

- src/meta/node/src/server.rs
- src/meta/service/src/system_params_service.rs
- src/meta/src/manager/env.rs
When `--license-key-path` is specified, license key from initial system parameters or future `ALTER`ing can easily get overwritten. In this PR, we reject such cases to avoid confusion.
</details>
> refactor(meta): reject directly setting license key when it's managed by watching a file

- Cargo.lock
- Cargo.toml
- ci/scripts/deterministic-recovery-test.sh
- src/tests/simulation/src/main.rs
Apply patch: https://github.com/madsim-rs/madsim/pull/231 which fixes an upstream bug: https://github.com/madsim-rs/madsim/issues/228.
This patch fixes madsim-sqlx's drop on spawn error, and fixes one of the bugs in the meta recovery tests.
</details>
> fix(ci): fix there is no reactor running in meta recovery tests, when kill-meta enabled

- src/cmd_all/src/standalone.rs
- src/meta/node/src/lib.rs
The new argument introduced in https://github.com/risingwavelabs/risingwave/pull/18768 was mistakenly named `--license-key-file`, while the env var and internal names are `license_key_path`. This PR unifies the naming.
See also:
- https://github.com/risingwavelabs/risingwave/pull/18768#discussion_r1794983086
- https://github.com/risingwavelabs/risingwave-operator/pull/732 …
> fix(meta): rename `--license-key-file` to `--license-key-path`

- src/expr/impl/src/udf/external.rs
The previous default 4MB limit by tonic seems too small. After https://github.com/arrow-udf/arrow-udf/pull/62, we can finally increase it to `usize::MAX`.
</details>
> fix(udf): unlimit external udf message size

- ci/scripts/build-other.sh
- e2e_test/udf/rust_udf.slt
- e2e_test/udf/wasm/Cargo.toml
- src/expr/impl/src/udf/wasm.rs
> fix(udf): upgrade arrow-udf to 0.5 which fixes rust udf compilation

- src/meta/src/hummock/manager/transaction.rs
- src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
Since sublevel ids no longer ensure a monotonically increasing order, and the time travel doesn't keep version delta of compaction, for time travel it's possible the newly inserted sub level id is smaller than the smallest one in the current version. For example:
1. The version has 3 sublevels [1, 2, 3].
2. The version is compacted to 0 sublevels [].
3. A new sublevel is inserted, [using committed_epoch as sub_level id](https://github.com/risingwavelabs/risingwave/blob/52f233186b73d60f6d150b5da57946c729537711/src/meta/src/hummock/manager/transaction.rs#L163). Say committed_epoch is 2, resulting sublevels [2].
The …
> fix(storage): fix sub level id for time travel

- src/tests/simulation/tests/integration_tests/scale/nexmark_q4.rs
As title. Motivated by #18553.
</details>
> test: add recovery in nexmark q4 sim test

- src/sqlparser/src/parser_v2/data_type.rs
- src/sqlparser/tests/testdata/create.yaml
When parsing `CHARACTER VARYING` the current sqlparser consumes the 2nd keyword unconditionally, leading to `CHARACTER AS` accepted as `char` unexpectedly.
</details>
> fix(sqlparser): keyword after `char` shall not be consumed on error

- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/DbzConnectorConfig.java
- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/SqlServerValidator.java
- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/ValidatorUtils.java
- java/connector-node/risingwave-connector-service/src/main/resources/sql_server.properties
- src/connector/src/source/cdc/external/mod.rs
- src/connector/src/source/cdc/external/mysql.rs
- src/connector/src/source/cdc/external/postgres.rs
- src/connector/src/source/cdc/external/sql_server.rs
As titled.
At https://github.com/risingwavelabs/risingwave-docs/blob/38a20f52702649437c5d5eb62dd41551da230f69/docs/guides/ingest-from-sqlserver-cdc.md?plain=1#L118,
please add one more line
```
| database.encrypt | Optional. Specify whether you want to enable SSL encryption. Currently, `trustServerCertificate` is enabled, regardless of the value of `database.encrypt`. |
```
> feat(mssql-cdc): add ssl support for sqlserver-cdc

- src/frontend/src/optimizer/plan_node/stream_materialize.rs
- src/frontend/src/optimizer/plan_node/stream_sink.rs
- src/frontend/src/optimizer/plan_node/utils.rs
- src/meta/src/rpc/ddl_controller_v2.rs
follow up of #18112, where we only implemented the track mechanism in meta, but it's banned in frontend
https://github.com/risingwavelabs/risingwave/issues/18338
</details>
> feat: support background DDL for MV on shared source

- e2e_test/source_legacy/basic/kafka.slt
- src/frontend/src/handler/create_source.rs
Since #18437 we have supported `INCLUDE payload` to ingest the whole json payload as a single `jsonb` column:
```
create [source | table] my_source (
foo varchar,
bar int)
include payload as root
with (...)
format plain encode json;
```
However, when there is no need to extract `foo` or `bar`, an empty column list would result in the following error:
```
Schema definition is required, either from SQL or schema registry.
```
This PR enables such usage by moving the empty column list check after handling `INCLUDE` additional columns. …
> fix(frontend): allow `INCLUDE payload` without other columns

- e2e_test/source_inline/kafka/avro/glue.slt
- e2e_test/source_inline/kafka/temporary_kafka_batch.slt
- `temporary_kafka_batch.slt`: In #18894, we moved data generation from ci script (generate before tests) to `slt` (generate inline), which may cause the test fail.
- `glue.slt`: Alter license may not take effect immediately.
</details>
> fix(test): fix some flaky e2e source tests

- src/batch/src/error.rs
- src/batch/src/executor/iceberg_scan.rs
- src/batch/src/executor/s3_file_scan.rs
- src/error/src/anyhow.rs
Closes https://github.com/risingwavelabs/risingwave/issues/18860
This PR adds a new macro `def_anyhow_variant`. The semantics of it is to construct a newtype error (same as `def_anyhow_newtype`), and also implement the `From` trait for each variant of the newtype to the parent error, which the newtype is a variant of.
Using this, we create the `BatchExternalSystemError`, and also allow types which are variants of it to be cast into `BatchError`, which `ExternalSystemError` is a variant of. …
> feat(batch): ensure user-facing context is always present for external system errors

- e2e_test/streaming/changelog.slt
- src/frontend/src/binder/query.rs
- src/meta/src/controller/rename.rs
- src/sqlparser/src/ast/query.rs
- src/sqlparser/src/parser.rs
Close issue #18747 by using ObjectName for table instead of Ident.
As the doc https://docs.risingwave.com/docs/current/sql-as-changelog/ 
`from` case is the table name, I think its better and less effort changing for changing to solve
this problem.
```diff
pub enum CteInner {
Query(Query),
-    ChangeLog(Ident),
+    ChangeLog(ObjectName),
}
```
Also change one test for this case. …
> fix: changelog does not support fully qualified path

- e2e_test/batch/catalog/pg_settings.slt.part
- e2e_test/source_inline/kafka/alter/add_column.slt
- e2e_test/source_inline/kafka/alter/rate_limit_source_kafka.slt
- e2e_test/source_inline/kafka/avro/alter_source.slt
- e2e_test/source_inline/kafka/avro/glue.slt
- e2e_test/source_inline/kafka/protobuf/alter_source.slt
- e2e_test/source_inline/kafka/shared_source.slt.serial
- e2e_test/source_legacy/basic/kafka.slt
- src/common/src/config.rs
- src/common/src/session_config/mod.rs
- src/config/example.toml
- src/frontend/planner_test/tests/testdata/input/shared_source.yml
- src/frontend/planner_test/tests/testdata/output/shared_source.yml
- src/frontend/src/handler/alter_source_column.rs
- src/frontend/src/handler/alter_source_with_sr.rs
- src/frontend/src/handler/create_source.rs
- src/frontend/src/optimizer/plan_node/logical_source.rs
- src/frontend/src/test_utils.rs
- src/tests/simulation/src/cluster.rs
- Can use session variable `streaming_use_shared_source` to control whether to use shared feature:
```sql
SET streaming_use_shared_source=[true|false];
ALTER SYSTEM SET streaming_use_shared_source=[true|false];
```
- There’s also a cluster config `stream_enable_shared_source` (`[streaming.developer]` in `risingwave.toml`). Set it to `false` can completely disable this feature in the cluster.
The config is similar to `streaming_use_arrangement_backfill` (session) and `stream_enable_arrangement_backfill` (cluster)
For more discussions see https://risingwave-labs.slack.com/archives/C06AL46R10S/p1729051215981299
- Rename …
> feat: enable shared source in session variable by default, and add cluster-level config to disable

- src/frontend/src/catalog/schema_catalog.rs
- src/frontend/src/observer/observer_manager.rs
- src/meta/src/controller/catalog.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/controller/utils.rs
- src/meta/src/model/stream.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/stream_graph/fragment.rs
- src/meta/src/stream/test_fragmenter.rs
When creating a streaming job, the internal tables directly scraped from the frontend's `StreamFragmentGraph` are incomplete, because several fields like `fragment_id` or `vnode_count` are not filled yet and will be determined later.
~~Previously, we notified the frontend nodes with these catalogs but did not update them afterward. This will cause problems since variable vnode count support is introduced, as the vnode count of a table is a significant property when scheduling a batch scan over it.~~
~~This PR changes to notify the internal table catalogs only after a `TableFragments` is build, where all information is …
> refactor(meta): clarify the completeness of internal table catalogs

- .gitignore
- e2e_test/source_inline/kafka/shared_source.slt.serial
- src/stream/src/executor/source/source_backfill_executor.rs
- src/stream/src/executor/source/source_backfill_state_table.rs
Follow up of #18925
If we don't persist, after recovery the progress will start from 0 again. 
However, TBH I'm a little hesitant about this change, since it is a little ugly. And we have to persist it just for SHOW JOBS.
---
This changes the state table representation, and should be a **breaking change**. But if we can get this into 2.1, then we don't need to consider compatibility.
---
Besides `SHOW JOBS`, this also benefits scanning from state table, making it more informative. (See diff on `slt`) …
> feat: persist processed rows for SourceBackfill for SHOW JOBS

- proto/stream_service.proto
- src/meta/src/barrier/progress.rs
- src/meta/src/barrier/recovery.rs
- src/meta/src/model/stream.rs
- src/stream/src/executor/source/source_backfill_executor.rs
- src/stream/src/task/barrier_manager/progress.rs
- src/tests/simulation/tests/integration_tests/README.md
- src/tests/simulation/tests/integration_tests/backfill_tests.rs
- src/tests/simulation/tests/integration_tests/recovery/background_ddl.rs
Previous discussion here: https://github.com/risingwavelabs/risingwave/pull/18112#discussion_r1741571151
Previously, `progress` in `SHOW JOBS` is a percentile string. After we introduced different type of backfill, things become tricker:
- For some types, like SourceBackfill, we cannot even tell what's the end position, thus no percentile at all.
- We may have different type of backfills in one MV. How to display them together is a problem.
- Snapshot backfill introduced complex string as `progress`: https://github.com/risingwavelabs/risingwave/blob/05b68bcd11a901e2e580f61bdcee799c860b6948/src/meta/src/barrier/creating_j …
> feat: improve progress msg in SHOW JOBS for source backfill

- ci/docker-compose.yml
- ci/scripts/e2e-source-test.sh
- ci/workflows/pull-request.yml
- e2e_test/source_inline/tvf/postgres_query.slt
- risedev.yml
- src/risedevtool/src/risedev_env.rs
> test: refactor pg tvf tests into inline tests

- src/connector/src/source/nats/mod.rs
- src/connector/with_options_source.yaml
as title, `consumer_durable_name` is introduced but `consumer.durable_name` already exists before.  Thanks to @WanYixian for finding the issue. 
</details>
> fix: remove redundant `consumer_durable_name`

- src/stream/src/executor/over_window/general.rs
- src/stream/src/executor/over_window/over_partition.rs
When iterating a sub-range on state table, we should've used deduplicated partition key as table pk prefix, but the original partition key was actually used. This PR fixes it.
</details>
> fix(over window): fix table iter pk prefix to use deduped partition key

- src/meta/src/controller/fragment.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/rpc/ddl_controller.rs
Since it's not possible to alter the `vnode_count` of existing table, we should align the `max_parallelism` specified in the `ReplaceTable` request with the original one. This applies to table schema change and sink-into-table.
Test coverage will be added together with the main functionality.
</details>
> fix(meta): align job's max parallelism while replacing table

- src/common/src/types/from_sql.rs
Support mapping `citext` data type and other string compatible data types
ref: [link](https://github.com/sfackler/rust-postgres/blob/6ae17e0f2d174fc4d5592ac7869909d7bdd346d9/postgres-types/src/lib.rs#L699-L723)
close: https://github.com/risingwavelabs/risingwave/issues/18844
</details>
> fix(pg-cdc): handle citext data type and other string compatible data types

- e2e_test/background_ddl/basic.slt
- e2e_test/source_inline/kafka/background_ddl/basic.slt.serial
- src/frontend/src/optimizer/plan_node/stream_materialize.rs
- src/frontend/src/optimizer/plan_node/stream_sink.rs
- src/frontend/src/optimizer/plan_node/utils.rs
Closes https://github.com/risingwavelabs/risingwave/issues/19115
cherry pick #19099 into release-2.0.
</details>
>  feat(stream): enable background ddl for StreamNow, StreamSource (#19099)

- ci/scripts/run-e2e-test.sh
They need to wait for the `minio` service to start, before they can run. Otherwise the meta node just panics and we cannot start.
Honestly, this is a quick fix, rather than a proper fix. We should do #16601, but I don't have time recently..
</details>
> fix(ci): fix standalone tests startup

- src/meta/node/src/server.rs
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/creating_job/mod.rs
- src/meta/src/barrier/creating_job/status.rs
- src/meta/src/barrier/info.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/progress.rs
- src/meta/src/barrier/recovery.rs
- src/meta/src/barrier/rpc.rs
- src/meta/src/barrier/schedule.rs
- src/meta/src/barrier/state.rs
- src/meta/src/rpc/ddl_controller.rs
This PR includes some general refactors on the global barrier manager.
First, currently we have `GlobalBarrierManager` and `GlobalBarrierManagerContext`. `GlobalBarrierManager` is actually a owned worker that works in a loop to handle different async barrier event, and `GlobalBarrierManagerContext` holds some shared structs and is used by both the `GlobalBarrierManager` worker and other external usages (e.g. DdlController and etc). In this PR, the `GlobalBarrierManager` worker is renamed to `GlobalBarrierWorker`, and `GlobalBarrierManagerContext` is renamed to `GlobalBarrierWorkerContext`, and will be used by only …
> refactor(meta): reorganize global barrier manager field

- Cargo.lock
- Cargo.toml
We use patched sqlx from the madsim fork, instead of the one in my personal fork of sqlx.
Please review the changes in that fork prior to reviewing this PR.
This accomplishes two things:
1. Let the Madsim Org manage the fork. We can have PR reviews each time we rebase the patch.
2. Inside the fork will adopt a rebase workflow, and continually patch for madsim on top of the tagged commit corresponding to the latest sqlx version. …
> chore(madsim,deps): use patched `sqlx` managed by the `madsim-rs` organization instead of a personal repository

- src/meta/src/controller/utils.rs
Otherwise, we will get following error message when querying it with Postgres meta backend:
```
mismatched types; Rust type `core::option::Option<i64>` (as SQL type `INT8`) is not compatible with SQL type `INT4`
```
This bug is not revealed in CI because there seems to be no coverage for running end-to-end tests with Postgres meta backend, which will be addressed in #19152. …
> fix(meta): fix vnode count data type when querying system table `rw_fragments`

- src/expr/core/src/window_function/kind.rs
- src/frontend/src/optimizer/plan_node/logical_over_window.rs
- src/frontend/src/optimizer/rule/over_window_split_rule.rs
- src/frontend/src/optimizer/rule/over_window_to_topn_rule.rs
- src/stream/src/executor/over_window/general.rs
- src/stream/src/executor/over_window/over_partition.rs
For example:
```sql
rank() over (
partition by ...
order by val
)
```
Rows:
```
row_id | val | rank
--------|-----|------
100    | 2   | 1
101    | 6   | 2
102    | 7   | 3
103    | 9   | 4
```
When changing `val` of row `101`, it will potenrially affect row `102` and `103`. Previously, no matter what the `val` is changed to, we will re-compute all outputs from row `101` to the end of the partition (row `103`). After this PR, if the output of row `102` is not changed, we will stop the re-computation. …
> perf(over window): skip remaining affected rows when rank is not changed

- dashboard/components/Relations.tsx
- dashboard/pages/indexes.tsx
- dashboard/pages/internal_tables.tsx
- dashboard/pages/materialized_views.tsx
- dashboard/pages/tables.tsx
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_fragments.rs
As title. Note that this is not the `max_parallelism` for streaming jobs.
</details>
> feat(dashboard): show vnode count for mv/table/internal-table

- .github/labeler.yml
- ci/docker-compose.yml
- ci/scripts/run-e2e-test.sh
- ci/workflows/pull-request.yml
- risedev.yml
When there's changes under `src/meta`, a new label `ci/run-e2e-test-other-backends` will be attached to the PR. Then, end-to-end tests against postgres/mysql meta backends will be triggered.
Developers can also manually attach the label to trigger the tests.
**NOTE**: This PR only enables Postgres backend, as I found several bugs blocking the tests under the MySQL backend. Will address them and enable it in next PRs. …
> feat(ci): run e2e tests against postgres/mysql backends on demand

- src/stream/src/executor/source/fs_source_executor.rs
- src/stream/src/executor/source/source_backfill_executor.rs
- src/stream/src/executor/source/source_executor.rs
Unlike other executor that only pause/resume based on command of barrier, the source executor additionally pauses/resumes based on [self_paused](https://github.com/risingwavelabs/risingwave/blob/main/src/stream/src/executor/source/source_executor.rs#L640). However, there's a corner case where this `self_paused` method will resume the source executor incorrectly:
1. A new stream job is created, resulting in 3 barriers: [pause, configchange, resume].
2. The source executor receives the first [pause] barrier. Somehow the following 2 barriers are delayed.
3. `self_paused` …
> fix(source): pause source correctly

- dashboard/components/Relations.tsx
- dashboard/lib/api/streaming.ts
- dashboard/package-lock.json
- dashboard/package.json
- dashboard/pages/_app.tsx
- dashboard/pages/fragment_graph.tsx
- dashboard/tsconfig.json
- src/meta/service/src/stream_service.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/dashboard/mod.rs
- src/meta/src/manager/metadata.rs
List streaming jobs in dashboard by querying the `streaming_job` table in meta store, instead of querying different catalog tables separately. This gives more accurate results and extra info about streaming jobs.
</details>
> feat(dashboard): list streaming job from `streaming_job` table & show info

- src/frontend/planner_test/tests/testdata/input/lateral_subquery.yaml
- src/frontend/planner_test/tests/testdata/input/subquery_expr_correlated.yaml
- src/frontend/planner_test/tests/testdata/output/lateral_subquery.yaml
- src/frontend/planner_test/tests/testdata/output/subquery_expr_correlated.yaml
- src/frontend/src/binder/expr/column.rs
- src/frontend/src/binder/relation/mod.rs
- Resolve https://github.com/risingwavelabs/risingwave/issues/19161
- CTE query will be wrapped as a `Share` Relation in the binder and it should be visited when transforming the CorrelatedInputRef.
- Lateral subquery context depth should be calculated as upper context index + lateral context index.
</details>
> fix(optimizer): fix lateral subquery with cte

- src/stream/src/executor/over_window/frame_finder.rs
- src/stream/src/executor/over_window/over_partition.rs
- src/utils/delta_btree_map/src/lib.rs
Previous implementation of `CursorWithDelta` used a O(logN) algorithm in `move_next` and `move_prev`. This PR replace them with a O(1) algorithm utilizing `btree_map::Cursor`.
A local performance benchmark running a user-provided query showed a significant improvement.
Before:
After:
Average inflight barrier number dropped 30.7%, p99 barrier latency dropped 30%, source throughput increased 24.8%. …
> perf(over window): O(1) impl for `delta_btree_map::CursorWithDelta::move_next `

- e2e_test/source_inline/cdc/mysql/mysql_create_drop.slt.serial
- src/connector/src/with_options.rs
- src/frontend/src/handler/create_source.rs
- src/meta/src/rpc/ddl_controller.rs
motivation is to simplify create stream job process in meta (prepare for  #19171, where we will completely remove `fill_table_stream_graph_info`)
Also made a behavior change: previously, auto assign `server.id` will only for legacy `CREATE TABLE` CDC, but not shared `CREATE SOURCE`.
previous work: #13031
</details>
> refactor: move server.id for MySQL CDC from meta to fe

- .config/nextest.toml
```
warning: ignoring unknown configuration keys in config file /Users/xxchan/Projects/risingwave/.config/nextest.toml: profile.ci.junit.overrides
```
`profile.ci.junit` is a subtable of `profile.ci`. Not a profile.
</details>
> chore: fix nextest warning

- src/expr/impl/src/window_function/aggregate.rs
- src/expr/impl/src/window_function/buffer.rs
Previously we reuse batch aggregator for `first_value` and `last_value` in OverWindow, and this required an O(n) iteration through the "current window" when evaluating output for each row. This PR introduces shortcut implementations fro these two special aggregate types to avoid the need of O(n) iteration.
This also benefits `lag` and `lead` because they are implemented with `first_value` and `last_value` under the hood.
A rough benchmark with a dumb query based on nexmark source showed a 392% source throughput increase introduced by this PR, during the first 10 minutes after streaming job creation.
Query:
```sql
CREATE …
```
> perf(over window): shortcut implementation for `first_value` and `last_value` in over window

- e2e_test/source_legacy/cdc_inline/auto_schema_map_mysql.slt
- src/connector/src/source/cdc/external/mysql.rs
as title. And for unexpected default value, we just set to null instead of throw errors during CREATE TABLE.
</details>
> fix(mysql-cdc): fix mysql enum type default value

- Cargo.lock
- Cargo.toml
- src/meta/model/migration/Cargo.toml
- src/meta/model/migration/src/lib.rs
- src/meta/model/migration/src/m20230908_072257_init.rs
- src/meta/model/migration/src/m20231008_020431_hummock.rs
- src/meta/model/migration/src/m20240304_074901_subscription.rs
- src/meta/model/migration/src/m20240506_112555_subscription_partial_ckpt.rs
- src/meta/model/migration/src/m20240525_090457_secret.rs
- src/meta/model/migration/src/m20240617_070131_index_column_properties.rs
- src/meta/model/migration/src/m20240617_071625_sink_into_table_column.rs
- src/meta/model/migration/src/m20240618_072634_function_compressed_binary.rs
- src/meta/model/migration/src/m20240630_131430_remove_parallel_unit.rs
- src/meta/model/migration/src/m20240701_060504_hummock_time_travel.rs
- src/meta/model/migration/src/utils.rs
- src/meta/model/src/actor.rs
- src/meta/model/src/actor_dispatcher.rs
- src/meta/model/src/catalog_version.rs
- src/meta/model/src/fragment.rs
- src/meta/model/src/function.rs
- src/meta/model/src/lib.rs
- src/meta/model/src/object.rs
- src/meta/model/src/secret.rs
- src/meta/model/src/sink.rs
- src/meta/model/src/table.rs
- src/meta/model/src/user_privilege.rs
- src/meta/model/src/worker.rs
Bump `sea-orm` to `1.0`, along with its dependencies.
The motivation is https://github.com/risingwavelabs/risingwave/pull/19156, where the necessary fix (https://github.com/SeaQL/sea-orm/pull/2244) is only included since `1.0`.
The only worth-noting breaking change is that, there is no longer a backend-agnostic method to specify `longblob` for MySQL, `blob` for SQLite, and `bytea` for Postgres simultaneously (https://github.com/SeaQL/sea-query/pull/743, a regression to me). As a workaround, add a helper method which dispatches the type based on the backend variant.
Although the latest version of `sea-orm` is `1.1`, we …
> chore(meta): bump sea-orm to 1.0

- src/stream/src/executor/project.rs
- src/stream/src/executor/project_set.rs
- src/stream/src/executor/watermark_filter.rs
- src/stream/tests/integration_tests/project_set.rs
> cherry-pick fix(watermark): stop generating watermark messages when stream is paused (#19199) to branch release-2.1

- Cargo.lock
- Cargo.toml
- src/connector/Cargo.toml
Closes https://github.com/risingwavelabs/risingwave/issues/18853.
This PR updates sqlx to v0.8.2 (https://github.com/risingwavelabs/sqlx/pull/2). We have to update it sooner or later, since other projects e.g. iceberg-rs depend on it.
We also have to bump `sea-orm`, because it depends on `sqlx`. Otherwise the `sqlx` version it uses will have conflicts. …
> chore(deps): update sqlx to 0.8.2, sea-orm to 1.1, sea-orm-migration to 1.1

- .git-blame-ignore-revs
- proto/catalog.proto
- src/frontend/src/handler/alter_table_column.rs
- src/frontend/src/handler/create_sink.rs
- src/frontend/src/handler/create_table.rs
- src/meta/service/src/ddl_service.rs
- src/meta/src/manager/streaming_job.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/source_manager.rs
- src/meta/src/stream/stream_graph/fragment.rs
We fill table_id/source_id in several places, which seems unnecessary. This PR tries to remove unnecessary codes to make it more understandable and maintainable.
We leave it with 2 steps:
1. In `create_job_catalog`, we assign id to `StreamingJob`
2. In `StreamFragmentGraph::new` (`fill_job`), we traverse the nodes, and set the id to corresponding plan nodes. (Note that previously we traverse the nodes multiple times) …
> refactor(meta): simplify stream job table/source id assignment

- src/frontend/src/handler/create_index.rs
Fixed #13534 . Make the behavior of creating an index consistent with PostgreSQL.
</details>
> fix: fix index create privilege check and ensure consistency between the owner and its associated table

- e2e_test/source_legacy/cdc/cdc.share_stream.slt
- src/connector/src/parser/mysql.rs
A `mysql` cdc-source may specify `mysql:boolean` to map to `rw:boolean`. In such case we have to handle it as [we did previously](https://github.com/risingwavelabs/risingwave/blob/b2b5a335a421667fd072add96617058aba52f361/src/connector/src/parser/mysql.rs#L62-L64), to avoid breaking this semantic.
</details>
> fix(connector): handle backwards compat parsing for `boolean` datatype

- src/batch/src/executor/group_top_n.rs
- src/batch/src/executor/hash_agg.rs
- src/batch/src/executor/join/hash_join.rs
- src/batch/src/executor/join/lookup_join_base.rs
- src/common/src/bitmap.rs
This PR introduces `filter_by_bitmap` for `ExactSizeIterator`s, and replaces `if !visible { continue; }` with it. 💦
</details>
> refactor(common): simplify chunk iteration with `filter_by_bitmap`

- src/meta/src/hummock/manager/commit_epoch.rs
- src/meta/src/hummock/manager/time_travel.rs
- src/meta/src/hummock/manager/versioning.rs
There's an optimization in time travel metadata: it will drop any delta log that doesn't add any SSTs. Because previously a new delta log from `commit_epoch` always belongs to either compaction group 2 or 3, which must exist.
However, during snapshot backfill it's possible that a delta log adds a new compaction group without adding any SSTs, e.g. it includes `GroupConstruct` but doesn't include any `NewL0SubLevel`.
This PR fixes the bug by enforcing a new version for time travel for the above new case, similar to how it is handled for delta logs generated by compaction.
This PR also removes useless …
> fix(meta): record delta for new compaction group

- ci/scripts/e2e-test-parallel.sh
- e2e_test/source_inline/kafka/secret_dep.slt
- src/meta/src/controller/catalog.rs
resolve https://github.com/risingwavelabs/risingwave/issues/19260
</details>
> fix: none-shared source to secret dependence

- src/meta/src/barrier/command.rs
- src/meta/src/manager/catalog/mod.rs
> fix: don't panic and trigger recovery when applying cancel command for created job

- e2e_test/source_inline/fs/posix_fs.slt
- src/frontend/src/optimizer/plan_node/stream_fs_fetch.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/stream/stream_graph/fragment.rs
- src/stream/src/executor/source/fetch_executor.rs
- src/stream/src/executor/source/source_executor.rs
resolve https://github.com/risingwavelabs/risingwave/issues/19296
The pr fix two places: 
* plan for fs fetch exec does not access rate limit from the catalog `(src/frontend/src/optimizer/plan_node/stream_fs_fetch.rs)`
* FsFetch Exec is not assigned to the correct source_id when building fragments `(src/meta/src/stream/stream_graph/fragment.rs)`
</details>
> fix: table with fs connector cannot work with rate limit

- proto/meta.proto
- src/meta/src/barrier/checkpoint/control.rs
- src/meta/src/barrier/checkpoint/mod.rs
- src/meta/src/barrier/checkpoint/state.rs
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/context/mod.rs
- src/meta/src/barrier/manager.rs
- src/meta/src/barrier/progress.rs
- src/meta/src/barrier/rpc.rs
- src/meta/src/barrier/utils.rs
- src/meta/src/barrier/worker.rs
In https://github.com/risingwavelabs/risingwave/pull/19334, we refactor the code of global barrier manager by simply moving the code to different files, without modifying any of the logics.
In this PR, we further refactor the code of global barrier manager to hide the visibility of some structs or fields to have better encapsulation.
</details>
> refactor(meta): reorganize code of global barrier manager (part 2)

- src/stream/src/executor/dispatch.rs
The logic for rewriting update `Op`s in the hash dispatcher relies on the invariant held in `update_check`, which is not enforced in production.
Some users encounter an assertion failure when executing this line,
https://github.com/risingwavelabs/risingwave/blob/9a01f67f7d6b84d57382e5b47df1fdea14249897/src/stream/src/executor/dispatch.rs#L835
where `col.len()` is 256 while `ops.len()` is 255, so I highly suspect there might be something wrong during the `Op` rewrite.
This PR adds some mroe assertions to help narrow down the scope of the issue.
We may also consider enabling `update_check` in production, or thoroughly …
> refactor(stream): add more assertion on update op handling in hash dispatcher

- src/meta/src/barrier/context/recovery.rs
- src/meta/src/manager/metadata.rs
- src/meta/src/model/stream.rs
Fixed a bug found in https://buildkite.com/risingwavelabs/main-cron/builds/3843#01931e2c-869a-4314-aa99-849e4747f72c, will open another PR to fix `release-2.0`.
As title, we need to complete the background materialized view without backfilling during recovery; otherwise, it will be logged in the barrier runtime information and remain unfinished because of the absence of progress reports from actors. Similar logic in normal creation:
https://github.com/risingwavelabs/risingwave/blob/3c2e81b53a8411451a5f999ca3313654d98c9586/src/meta/src/barrier/progress.rs#L511-L516
Furthermore, it should be noted that `Value` cannot be …
> fix: background mview without backfilling should not tracked in barrier runtime info

- src/stream/src/task/barrier_manager.rs
Previously we cache the actor failure so that if the newly spawned actor failed before the inject barrier request, we can know about the failure and return error. However, after we change to spawn new actors along with the inject barrier request, this becomes unnecessary. Besides, we reset the streaming control stream immediately after we receive any actor failure. Therefore, there is no need to cache the actor failure in local barrier worker any more.  …
> refactor(barrier): not cache actor failure in local barrier worker

- java/connector-node/risingwave-connector-service/src/main/resources/postgres.properties
Previously we used a non-transactional message, but it cannot transition the debezium to message processing mode during some connector restart scenario. So  [debezium rejects to commit offset](https://github.com/debezium/debezium/blob/1cd4110afac46a41ae134521b13a5ca9e8c84258/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java#L427) to upstream PG. This will cause the RDS PG accumulates WAL that generated by AWS background workload.
This pr changes to write transactional message into the upstream WAL, which is confirmed that can work.
related: …
> fix(pg-cdc): write transactional WAL message as heartbeat action

- proto/stream_service.proto
- src/meta/src/barrier/checkpoint/control.rs
- src/meta/src/barrier/context/context_impl.rs
- src/meta/src/barrier/context/mod.rs
- src/meta/src/barrier/rpc.rs
- src/meta/src/barrier/worker.rs
- src/rpc_client/src/stream_client.rs
- src/stream/src/task/barrier_manager.rs
- src/stream/src/task/barrier_manager/managed_state.rs
- src/stream/src/task/stream_manager.rs
Previously, in local barrier manager, we create a new partial graph state when we see a partial graph id that does not previously exist. In this PR, we will change to add a new control stream request to explicitly create new partial graph, and in recovery when we initialize the control stream, we will specify the initial partial graph.
The set of subscriptions is maintained globally in the local barrier manager. In this PR, we will maintain it per partial graph. …
> refactor(barrier): add control request to explicitly create partial graph

- .github/dependabot.yml
Follow-up of #19208. See #19165 for the motivation.
</details>
> chore: enable dependabot for java

- src/connector/src/sink/starrocks.rs
Previously in #16816, we used a `try_join_all` directly on the `JoinHandle`, which only returns the `JoinError`, while the error in the output of `JoinHandle` is ignored, because it is treated as `Ok(Err(...))`.
In this PR, we transform the future of `JoinHandle` to a single layer result, so that the error in join handle output will be treated as error. …
> fix(starrocks): fix starrocks coordinator incorrect try_join_all on join handle

- ci/scripts/deterministic-it-test.sh
- ci/workflows/main-cron.yml
- src/tests/simulation/tests/integration_tests/sink/basic.rs
- src/tests/simulation/tests/integration_tests/sink/err_isolation.rs
- src/tests/simulation/tests/integration_tests/sink/recovery.rs
- src/tests/simulation/tests/integration_tests/sink/scale.rs
- src/tests/simulation/tests/integration_tests/sink/utils.rs
Previous in sink decouple madsim test, we assume that the sink writer of all sink parallelisms should be created after the create sink SQL returns. However, when sink decouple is enabled, the sink writer will be created in the log reader side, which is decoupled from the upstream. Therefore, it may happen that when the create sink SQL returns, not all sink writer have been created, and some related tests become flaky. In this PR, we change to explicitly wait for all sink writer parallelisms to be created before proceeding to next step, and the flaky tests will be fixed. …
> fix(test): incorrect flaky madsim initial sink parallelism

- src/frontend/src/scheduler/distributed/query.rs
- src/frontend/src/scheduler/plan_fragmenter.rs
As titled. Fix the potential race between FE and CN on pinned epoch. This fix is valid for version <= 2.0 because in 2.1 we already deprecate safe epoch completely.
See https://github.com/risingwavelabs/risingwave/issues/17965#issuecomment-2274915561
</details>
> fix(batch): unpin snapshot until the end of distributed batch query

- src/storage/hummock_test/src/bin/replay/replay_impl.rs
- src/storage/hummock_trace/src/collector.rs
- src/storage/hummock_trace/src/record.rs
- src/storage/hummock_trace/src/replay/mod.rs
- src/storage/hummock_trace/src/replay/runner.rs
- src/storage/hummock_trace/src/replay/worker.rs
- src/storage/src/hummock/event_handler/hummock_event_handler.rs
- src/storage/src/hummock/event_handler/mod.rs
- src/storage/src/hummock/event_handler/uploader/mod.rs
- src/storage/src/hummock/event_handler/uploader/spiller.rs
- src/storage/src/hummock/store/hummock_storage.rs
- src/storage/src/memory.rs
- src/storage/src/monitor/monitored_store.rs
- src/storage/src/monitor/traced_store.rs
- src/storage/src/panic_store.rs
- src/storage/src/store.rs
- src/storage/src/store_impl.rs
- src/stream/src/task/barrier_manager/managed_state.rs
Previously in the `sync` of hummock, we only sync on each partial graph one by one. In partial checkpoint, we may include multiple partial graphs in a checkpoint. Therefore, we should support calling `sync` on multiple partial graphs at once, so that we can reduce the object store write and the number of SST files.
Since `sync` is actually a method specially for hummock, in this PR we by the way move `sync` out of the `StateStore` trait, and make it a method only for hummock.
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note …
> feat(storage): support sync on multiple partial graph

- e2e_test/extended_mode/1dim_list.slt.part
- e2e_test/extended_mode/README.md
- e2e_test/extended_mode/type.slt
- src/common/src/types/jsonb.rs
- src/common/src/types/mod.rs
- src/common/src/types/num256.rs
- src/common/src/types/to_binary.rs
- src/tests/e2e_extended_mode/README.md
> feat(pgwire): support 1-dimension array in extended mode

- e2e_test/ddl/alter_session_params.slt
- src/common/src/session_config/mod.rs
This PR permits to set the runtime parameter `query_mode` gloablly. Sometimes it's helpful to easily alter this parameter globally for queries sent from a client process, which otherwise need code change and rebuild for client process.
</details>
> refactor: allow modification of the query mode

- e2e_test/batch/distribution_mode.slt
- e2e_test/batch/local_mode.slt
- e2e_test/batch/subquery/scalar_subquery.slt.part
- src/frontend/planner_test/tests/testdata/input/subquery_expr.yaml
- src/frontend/planner_test/tests/testdata/output/subquery_expr.yaml
- src/frontend/src/optimizer/plan_node/batch_max_one_row.rs
As title. This is missed in #13880, and can only be reproduced when 2 records resides in different shard.
Also, `e2e_test/batch/subquery` does not seems to be covered in CI.
</details>
> fix(optimizer): enforce input of `BatchMaxOneRow` to be singleton

- .cargo/config.toml
- src/ctl/src/cmd_impl/meta/migration.rs
> fix: ignore migration for streaming catalogs that table fragments are missing

- e2e_test/source_inline/kafka/avro/alter_table.slt
- src/frontend/src/handler/alter_table_column.rs
- src/frontend/src/handler/create_sink.rs
- src/frontend/src/handler/create_table.rs
It is required that an `UPSERT` source (actually table) to `INCLUDE key` and use it as primary key. However, when `REFRESH SCHEMA`, the `INCLUDE`s are always lost, effectively resulting in `UPSERT` tables cannot evolve their schemas.
</details>
> fix(source): `REFRESH SCHEMA` shall keep `INCLUDE` pk for `UPSERT`

- e2e_test/source_inline/cdc/mysql/mysql_create_drop.slt.serial
- e2e_test/source_inline/kafka/shared_source.slt.serial
- src/batch/src/executor/source.rs
- src/connector/src/source/base.rs
- src/connector/src/source/cdc/mod.rs
- src/connector/src/source/kafka/enumerator/client.rs
- src/connector/src/source/kafka/source/reader.rs
- src/connector/src/source/kafka/split.rs
- src/connector/src/source/reader/reader.rs
- src/stream/src/executor/source/fetch_executor.rs
- src/stream/src/executor/source/source_backfill_executor.rs
- src/stream/src/executor/source/source_executor.rs
- src/stream/src/from_proto/source/trad_source.rs
- src/stream/src/task/barrier_manager/progress.rs
Set up: Create a shared kafka source, and 1 MV on the source.
Data loss happens when:
1. alter source set rate limit to 0
2. push some new data to the kafka topic
3. resume the source. Then we can find the MV don't get the data. If we push more data to the topic, only new data comes.
Reason:
In #16626 we introduced an optimization to let shared SourceExecutor start from latest, but the implementation is problematic. Specifically, `hack_seek_to_latest` will not only take effect at the beginning, but will also when rebuilding the source reader (which happens when rate limit is applied).
The new implementation in this PR: …
> fix: fix potential data loss for shared source

- e2e_test/source_inline/kafka/alter/rate_limit_source_kafka_shared.slt
- proto/stream_plan.proto
- src/connector/src/sink/encoder/json.rs
- src/meta/service/src/stream_service.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/manager/metadata.rs
- src/stream/src/executor/source/source_backfill_executor.rs
- src/stream/src/executor/source/source_executor.rs
fix #19297
This is a missing feature. We support source_rate_limit for shared source executor, but cannot rate limit source backfill before this PR.
</details>
> feat: support backfill_rate_limit for source backfill

- e2e_test/source_inline/fs/posix_fs.slt
- e2e_test/source_inline/kafka/alter/rate_limit_source_kafka.slt.serial
- e2e_test/source_inline/kafka/alter/rate_limit_source_kafka_shared.slt.serial
- e2e_test/source_inline/kafka/alter/rate_limit_table_kafka.slt.serial
- proto/meta.proto
- proto/stream_plan.proto
- src/frontend/src/catalog/system_catalog/rw_catalog/mod.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_fragments.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_rate_limit.rs
- src/frontend/src/meta_client.rs
- src/frontend/src/stream_fragmenter/mod.rs
- src/frontend/src/test_utils.rs
- src/meta/service/src/stream_service.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/manager/metadata.rs
- src/prost/src/lib.rs
- src/rpc_client/src/meta_client.rs
- src/sqlparser/src/parser.rs
It's not easy to know what jobs are rate limited, so add this.
I want to avoid iterating over all fragments, so I introduced a new fragment flag for FsFetch. This means `rw_rate_limit` won't show fs fragments created before this PR, and I think it's acceptable.
</details>
> feat: add rw_rate_limit system catalog

- src/meta/src/hummock/manager/time_travel.rs
- src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
- src/storage/hummock_sdk/src/sstable_info.rs
- src/storage/hummock_sdk/src/time_travel.rs
- src/storage/hummock_sdk/src/version.rs
Both `IncompleteHummockVersion` and `HummockVersion` use `PbHummockVersion` as the meta store type for persistence. 
In `time_travel.rs`, whenever reading `PbHummockVersion` from the meta store, the counterpart in-mem structs should be `IncompleteHummockVersion`. Because in time_travel metadata, only `sst_id` and `object_id` of a `SstableInfo` are stored in `PbHummockVersion`, while other fields are left to default.
However, currently in `time_travel.rs`, `HummockVersion` is incorrectly used instead of `IncompleteHummockVersion`. This generates an `SstableInfo` with correct `sst_id` and `object_id` fields, but other …
> refactor(meta): use correct type for the pb counterpart

- src/storage/compactor/src/server.rs
- src/storage/src/hummock/compactor/mod.rs
If the `shutdown_tx` returned by the function is not retained, then `shutdown_rx` will receive an exit message and the shared compactor loop will be terminated.
This pr maintains the lifetime of the `start_shared_compactor` return value to avoid this problem.
This PR is just a hot fix, and does not prevent serverless compactor v2.0.x from being tested.
If necessary, a separate PR will be launched to address the compactor graceful shutdown and cancel task issues. …
> fix(compactor): Fix an unexpected termination of shared compactor

- src/meta/src/barrier/command.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/stream_manager.rs
I mistakenly thought "dummy" means placeholder. But it actually means a temporary id which will be replaced later. So I think "tmp" is a more proper name.
</details>
> refactor: rename dummy table id to tmp table id

- src/connector/src/connector_common/iceberg/mod.rs
- src/connector/src/sink/iceberg/mod.rs
- src/connector/with_options_sink.yaml
- src/connector/with_options_source.yaml
- Resolve https://github.com/risingwavelabs/risingwave/issues/19405
- Allow users to specify credentials, token, oauth2-server-uri, and scope in rest catalog for iceberg. This is a common authentication way in iceberg rest catalog.
```
CREATE SOURCE iceberg_t1
WITH (
connector = 'iceberg',
s3.endpoint = 'https://s3.ap-southeast-2.amazonaws.com',
s3.region = 'ap-southeast-2',
s3.access.key = 'xxxx',
s3.secret.key = 'xxxx',
s3.path.style.access = 'true',
catalog.type = 'rest',
catalog.uri = 'http://localhost:8181/api/catalog',
warehouse.path = 'quickstart_catalog',
database.name = 'ns',
table.name = 't1', …
```
> feat(iceberg): support rest authentication

- e2e_test/source_inline/kafka/avro/alter_table.slt
- src/frontend/src/handler/alter_table_column.rs
- src/frontend/src/handler/create_sink.rs
- src/frontend/src/handler/create_table.rs
Cherry picking \#19384 onto branch release-2.1,
This PR/issue was created by cherry-pick action from commit c1e8f9a2d177d8a9c9733e06f1c9ce77517582d3.,
> fix(source): `REFRESH SCHEMA` shall keep `INCLUDE` pk for `UPSERT` (#19384)

- proto/catalog.proto
- proto/ddl_service.proto
- proto/meta.proto
- src/frontend/src/catalog/table_catalog.rs
- src/meta/src/barrier/checkpoint/control.rs
- src/meta/src/barrier/checkpoint/creating_job/mod.rs
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/context/context_impl.rs
- src/meta/src/barrier/context/recovery.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/progress.rs
- src/meta/src/barrier/schedule.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/hummock/manager/compaction/compaction_group_manager.rs
- src/meta/src/manager/metadata.rs
- src/meta/src/model/stream.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/source_manager.rs
- src/meta/src/stream/stream_graph/fragment.rs
- src/meta/src/stream/stream_manager.rs
- src/meta/src/stream/test_fragmenter.rs
What does "table" mean is quite confusing
- Added some comments in proto to clarify. Didn't modify proto in case of incompatibility.
- Renamed some type and field that only exist in memory.
</details>
> refactor: clarify the meaning of table in TableCatalog and TableFragments

- e2e_test/sink/sink_into_table/parallelism.slt
- src/frontend/planner_test/src/lib.rs
- src/frontend/planner_test/tests/testdata/input/sink_into_table.yaml
- src/frontend/planner_test/tests/testdata/output/emit_on_window_close.yaml
- src/frontend/planner_test/tests/testdata/output/sink.yaml
- src/frontend/planner_test/tests/testdata/output/sink_into_table.yaml
- src/frontend/src/handler/create_sink.rs
- src/frontend/src/optimizer/mod.rs
- src/frontend/src/optimizer/plan_node/stream_sink.rs
> fix: when target is table, the sink downstream pk is not set

- CONTRIBUTING.md
- docs/dev/src/contributing.md
> doc(dev-guide): note good first issue

- Cargo.lock
- Cargo.toml
- e2e_test/batch/basic/dml_update.slt.part
- src/frontend/planner_test/tests/testdata/input/cast.yaml
- src/frontend/planner_test/tests/testdata/output/array.yaml
- src/frontend/planner_test/tests/testdata/output/cast.yaml
- src/frontend/planner_test/tests/testdata/output/expr.yaml
- src/frontend/planner_test/tests/testdata/output/struct_query.yaml
- src/frontend/planner_test/tests/testdata/output/update.yaml
- src/frontend/src/catalog/system_catalog/pg_catalog/pg_cast.rs
- src/frontend/src/error.rs
- src/frontend/src/expr/function_call.rs
- src/frontend/src/expr/mod.rs
- src/frontend/src/expr/type_inference/cast.rs
- src/frontend/src/expr/type_inference/mod.rs
Record contexts for error when recursively calling `cast` on composite types, to provide better error messages.
Preview:
https://github.com/risingwavelabs/risingwave/blob/fc4223348295f029a4d88d0d9f64b4de8a760ac8/src/frontend/planner_test/tests/testdata/output/cast.yaml#L92-L115
</details>
> refactor(optimizer): record error contexts when casting composite types

- e2e_test/python_client/main.py
> test(pgwire): complete the test cases to cover all data types

- src/frontend/src/utils/with_options.rs
- src/meta/src/manager/diagnose.rs
- src/sqlparser/src/ast/legacy_source.rs
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/src/ast/statement.rs
- src/sqlparser/src/ast/value.rs
- src/sqlparser/src/parser.rs
- src/sqlparser/tests/sqlparser_common.rs
- src/sqlparser/tests/sqlparser_postgres.rs
context: https://github.com/risingwavelabs/risingwave/pull/19270#discussion_r1849974081
</details>
> refactor: make object ref outside `ast::Value`

- src/meta/service/src/ddl_service.rs
- src/meta/src/barrier/checkpoint/control.rs
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/context/context_impl.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/progress.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/error.rs
- src/meta/src/manager/streaming_job.rs
- src/meta/src/model/stream.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/stream_manager.rs
Although it was only for sink into table/ alter table now, actually in most places, `replace_table` is as general as `replace_stream_job`.
I noticed this after renaming `TableFragments` to `StreamJobFragments` in #19510. 
This can pave way for #18935 
Also include some minor style refactoring.
</details>
> refactor(meta): rename replace_table to replace_stream_job where appropriate

- src/batch/src/executor/insert.rs
- src/batch/src/executor/order_by.rs
- src/batch/src/executor/values.rs
- src/common/src/array/struct_array.rs
- src/common/src/types/mod.rs
- src/common/src/util/sort_util.rs
- src/connector/src/sink/formatter/debezium_json.rs
- src/frontend/src/binder/expr/value.rs
- src/frontend/src/catalog/table_catalog.rs
- src/frontend/src/expr/literal.rs
- src/frontend/src/handler/create_mv.rs
- src/frontend/src/handler/create_source.rs
- src/frontend/src/handler/create_table.rs
- src/stream/src/executor/values.rs
Before:
* `Struct::new`
* `Struct::unnamed` (possibly via `DataType::new_unnamed_struct`)
* `Struct::from_parts` (via `DataType::new_struct`)
Goal:
* Deprecate `Struct::from_parts` in favor of `Struct::new` (done in Part 2/2)
* (minor) Avoid introducing unnecessary associated functions on `DataType` and interact with `StructType` directly.
Separated into 2 PRs so that we can focus on core changes in Part 2/2 #19570. This one is trivial and may distract people if squashed together with the latter part. …
> refactor(common): consolidate `StructType` constructors (Part 1/2: trivial ones)

- e2e_test/batch/basic/strict_mode.slt.part
- e2e_test/batch/catalog/pg_settings.slt.part
- proto/plan_common.proto
- src/batch/src/executor/filter.rs
- src/batch/src/executor/project.rs
- src/batch/src/task/task_manager.rs
- src/common/src/session_config/mod.rs
- src/expr/core/src/expr/build.rs
- src/expr/core/src/expr_context.rs
- src/frontend/src/scheduler/distributed/stage.rs
- src/frontend/src/scheduler/local.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/model/stream.rs
- src/meta/src/stream/test_fragmenter.rs
- src/stream/src/executor/integration_tests.rs
Resolves #17844. See https://github.com/risingwavelabs/risingwave/issues/17844#issuecomment-2330694033.
Currently, the error is printed to logs only (with `LogSuppressor` to avoid flooding). It would be better to notice to users via psql's `NOTICE`, but it requires more work to pass these messages from compute nodes to frontend nodes. Left a `TODO` in the code now.
- Added a session variable `batch_expr_strict_mode` to control whether to let the entire query fail or fill `NULL` values for expression evaluation failures.
> feat(batch): add `batch_expr_strict_mode` to ignore expression error in batch query

- src/common/src/array/arrow/arrow_impl.rs
- src/common/src/catalog/column.rs
- src/common/src/types/mod.rs
- src/common/src/types/struct_type.rs
- src/connector/codec/src/decoder/avro/schema.rs
- src/connector/codec/src/decoder/protobuf/parser.rs
- src/frontend/src/binder/expr/mod.rs
- src/frontend/src/binder/update.rs
- src/frontend/src/expr/subquery.rs
- src/frontend/src/handler/create_function.rs
- src/frontend/src/handler/create_sql_function.rs
- src/tests/sqlsmith/src/sql_gen/expr.rs
Before:
* `Struct::new`
* `Struct::unnamed` (possibly via `DataType::new_unnamed_struct`)
* `Struct::from_parts` (via `DataType::new_struct`)
Goal:
* Deprecate `Struct::from_parts` in favor of `Struct::new`
* (minor) Avoid introducing unnecessary associated functions on `DataType` and interact with `StructType` directly.
As we can see, most real callers (contrast to dummy / testing callers in Part 1/2 #19569) were iterating the same thing twice to obtain types and names separately (or `unzip`). Now they are doing it in one pass. Exceptions are where `zip_eq_fast` is used - namely `From<&PbDataType>` and `bind_update`. …
> refactor(common): consolidate `StructType` constructors (Part 2/2)

- e2e_test/source_inline/kafka/avro/ref.slt
- src/connector/codec/src/decoder/avro/schema.rs
- src/connector/codec/tests/integration_tests/avro.rs
- src/connector/src/parser/avro/parser.rs
Part of #17020. `Ref` in avro used to be supported by a hack we added in our apache_avro fork. This PR avoids the hack (replacing `Ref` with their referee in-place, resulting in an invalid tree containing duplicate definitions). The hack fails to work when there is `Ref` inside `Ref` - resulting in either unresolved `Ref` or infinite recursion.
This PR only corrects part of the usage - in `avro_schema_to_column_descs` to derive RisingWave column data types from avro schema. There will be a follow-up to correct the usage in `convert_to_datum`/`AvroAccess`. Without the latter part, simple data types like `int` (inside a …
> fix(source): resolve avro `Ref` during `avro_schema_to_column_descs` without hack

- dashboard/package-lock.json
- dashboard/package.json
- dashboard/pages/explain_distsql.tsx
https://github.com/risingwavelabs/risingwave/issues/19542
new ui for rendering graphviz output to replace explain distsql. 
example usage:
1. run explain (format dot, distsql) xxx and copy the dot output.
2. paste the dot output to dashboard and click parse generate graphviz visualization.
</details>
> feat(frontend): support explain with graphviz visualization in dashboard

- proto/stream_service.proto
- proto/task_service.proto
- src/common/src/catalog/mod.rs
- src/compute/src/rpc/service/exchange_service.rs
- src/meta/src/barrier/checkpoint/control.rs
- src/meta/src/barrier/rpc.rs
- src/rpc_client/src/compute_client.rs
- src/stream/src/executor/dispatch.rs
- src/stream/src/executor/exchange/input.rs
- src/stream/src/executor/integration_tests.rs
- src/stream/src/executor/merge.rs
- src/stream/src/executor/receiver.rs
- src/stream/src/from_proto/barrier_recv.rs
- src/stream/src/from_proto/merge.rs
- src/stream/src/from_proto/now.rs
- src/stream/src/from_proto/source/trad_source.rs
- src/stream/src/from_proto/values.rs
- src/stream/src/task/barrier_manager.rs
- src/stream/src/task/barrier_manager/managed_state.rs
- src/stream/src/task/barrier_manager/progress.rs
- src/stream/src/task/barrier_manager/tests.rs
- src/stream/src/task/mod.rs
- src/stream/src/task/stream_manager.rs
To simplify the implementation to support database failure isolation, we should isolate different databases for fields in local barrier worker. Previously, we isolate the barrier injection and collection of different partial graphs. Ideally, it will be great to isolate the fields of local barrier worker by partial graph, so that the local barrier worker won't be aware of the concept of database. 
However, after some efforts, I found it complicated to directly support isolation in different partial graphs. In snapshot backfill, during the stage of backfill, the streaming job has its own partial graph, but after the …
> refactor(barrier): explicitly maintain database barrier state separately in local barrier manager

- src/common/src/catalog/internal_table.rs
- src/frontend/src/catalog/mod.rs
- src/frontend/src/catalog/root_catalog.rs
- src/frontend/src/catalog/schema_catalog.rs
- src/frontend/src/catalog/system_catalog/pg_catalog/pg_constraint.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_columns.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_description.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_relation_info.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_tables.rs
- src/frontend/src/catalog/table_catalog.rs
- src/frontend/src/handler/alter_swap_rename.rs
- src/frontend/src/handler/drop_schema.rs
- src/frontend/src/handler/show.rs
follow up of #19510. 
We've commented that `TableCatalog` contains different kinds of tables. In this PR we highlight `user_tables` (I think this name is not very cool, but cannot come up with a better one.)
</details>
> refactor: further clarify types of tables

- src/meta/src/barrier/checkpoint/control.rs
- src/meta/src/barrier/rpc.rs
- src/meta/src/barrier/worker.rs
As titled. 
Previously, in method `recovery_inner` of global barrier worker, we have code that take and rebuild runtime information of each database and inject the initial barriers. In this PR, we extract the code to be a separate methods, so that we can reuse the similar logic when support database failure isolation.
We also introduce an optimization in this PR. Previously during recovery, we will inject and wait collect initial barrier for each database one by one, and actually the work can be done concurrently. In this PR, we change to inject the initial barriers to all databases all at once, and then wait for …
> refactor(meta): extract common method to inject initial barrier

- proto/catalog.proto
- src/frontend/src/catalog/system_catalog/rw_catalog/mod.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_fragment_id_to_ddl.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_internal_table_info.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_internal_tables.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_streaming_parallelism.rs
- src/frontend/src/catalog/table_catalog.rs
- src/frontend/src/optimizer/plan_node/stream_materialize.rs
- src/frontend/src/optimizer/plan_node/utils.rs
- src/frontend/src/scheduler/distributed/query.rs
- src/meta/model/src/table.rs
- src/meta/src/controller/mod.rs
- src/meta/src/controller/streaming_job.rs
- src/storage/src/compaction_catalog_manager.rs
as title. Introduced a new system view `rw_internal_table_info`. For example:
```sql
dev=> select * from rw_internal_table_info ;
id |             name              | job_id | job_name |     job_type      | schema_name | owner
----+-------------------------------+--------+----------+-------------------+-------------+-------
8 | __internal_mv1_3_streamscan_0 |      7 | mv1      | materialized view | public      | root
(1 row)
``` …
> feat: add rw_internal_table_info to identity which streaming job the internal table belongs

- src/frontend/src/handler/create_sink.rs
- src/frontend/src/handler/create_source.rs
- src/frontend/src/telemetry.rs
- src/frontend/src/utils/with_options.rs
- src/meta/src/controller/catalog.rs
> feat: telemetry for connection create and ref

- src/meta/src/barrier/command.rs
- src/meta/src/barrier/progress.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/manager/streaming_job.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/stream_graph/fragment.rs
- src/meta/src/stream/stream_manager.rs
They are the same thing
</details>
> refactor(meta): unify DdlType and StreamingJobType

- proto/stream_plan.proto
- src/meta/model/src/prelude.rs
- src/meta/service/src/ddl_service.rs
- src/meta/src/barrier/command.rs
- src/meta/src/controller/catalog.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/manager/metadata.rs
- src/meta/src/manager/streaming_job.rs
- src/meta/src/model/stream.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/stream_graph/fragment.rs
- src/prost/src/lib.rs
Style improvements (e.g., extract logic into methods) to make the code easier to understand and able to generalize to replace job.
prepare for #19063
</details>
> refactor(meta): generalize replace table to replace job

- src/frontend/planner_test/tests/testdata/output/sink.yaml
- src/frontend/src/handler/create_sink.rs
- Resolve https://github.com/risingwavelabs/risingwave/issues/19470
</details>
> fix(iceberg): bypass iceberg partition table optimization

- e2e_test/source_inline/kafka/issue_19563.slt.serial
- src/compute/tests/cdc_tests.rs
- src/connector/src/source/cdc/external/mock_external_table.rs
- src/connector/src/source/cdc/external/mod.rs
- src/stream/src/executor/backfill/cdc/cdc_backfill.rs
- src/stream/src/executor/backfill/cdc/upstream_table/external.rs
- src/stream/src/executor/backfill/cdc/upstream_table/snapshot.rs
- src/stream/src/executor/source/mod.rs
- src/stream/src/executor/source/source_executor.rs
- src/stream/src/from_proto/stream_cdc_scan.rs
cherry pick #19467 
</details>
> feat(stream): create cdc table reader and source data stream with retry (#19467)

- e2e_test/source_inline/connection/schema_registry.slt
- src/connector/src/connector_common/connection.rs
- src/connector/src/connector_common/mod.rs
- src/connector/src/macros.rs
- src/connector/src/schema/schema_registry/client.rs
- src/connector/src/schema/schema_registry/util.rs
- src/frontend/src/handler/create_connection.rs
- src/frontend/src/utils/with_options.rs
confluent schema registry doc: https://docs.confluent.io/platform/current/schema-registry/develop/api.html
support connection for schema registry 
```
create connection sr_conn with (
type = 'schema_registry',
schema.registry = 'http://...',
schema.registry.username = '...',
schema.registry.password = '...'
)
```
</details>
> feat: connection for schema registry

- src/connector/src/parser/chunk_builder.rs
- src/connector/src/parser/mod.rs
- src/connector/src/parser/plain_parser.rs
- src/connector/src/source/base.rs
Due to some historical reason, we build data chunk and heartbeat chunk for CDC source with different `SourceStreamChunkBuilder`s, however, it seems that:
1. If a split is not active, then only possible msg to produce is heartbeat msg.
2. If a split is active, heartbeat msg should be ignored.
Merging heartbeat chunk builder with data chunk builder seems do no harm. …
> refactor(cdc source): merge cdc heartbeat chunk builder & data chunk builder

- Cargo.lock
- ci/scripts/run-e2e-test.sh
- e2e_test/batch/catalog/pg_settings.slt.part
- e2e_test/dml/inserts.slt.part
- e2e_test/dml/rate_limit_no_limit.slt
- e2e_test/dml/rate_limit_pause_resume.slt
- e2e_test/dml/rate_limit_set.slt
- proto/meta.proto
- proto/stream_plan.proto
- src/common/src/session_config/mod.rs
- src/compute/tests/integration_tests.rs
- src/frontend/src/handler/alter_streaming_rate_limit.rs
- src/frontend/src/handler/mod.rs
- src/frontend/src/optimizer/plan_node/stream_dml.rs
- src/frontend/src/utils/overwrite_options.rs
- src/meta/service/src/stream_service.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/hummock/manager/time_travel.rs
- src/meta/src/manager/metadata.rs
- src/prost/src/lib.rs
- src/sqlparser/src/ast/ddl.rs
- src/sqlparser/src/parser.rs
- src/stream/Cargo.toml
- src/stream/src/executor/dml.rs
- src/stream/src/executor/source/mod.rs
- src/stream/src/executor/utils.rs
- src/stream/src/from_proto/dml.rs
(cherry picked from commit f0a91dfa5bef8474aa6f93ed4b71ef6b37d39327)
This PR shouldn't block release process.
This PR adds an optional feature. 
Cherry pick https://github.com/risingwavelabs/risingwave/pull/19679
</details>
> feat: add support for dml_rate_limit (#19679)

- e2e_test/source_inline/kafka/avro/ref.slt
- src/connector/codec/src/decoder/avro/mod.rs
- src/connector/src/parser/debezium/avro_parser.rs
Previously, when recursively handling an avro value, its associated schema is extracted with `extract_inner_schema` (wrapper over `avro_extract_field_schema`). It handles `Record`/`Array`/`Union`/`Map` together and allows `None` as output - meaning we may have a value with unknown schema.
This PR revisits all places extracting child schema and ensures the corresponding schema is always present:
* `AvroParseOptions::schema` is no longer an `Option`. It cannot be `None`.
* Extraction of `Record`/`Array`/`Union`/`Map` are handled in their corresponding context. Removes `avro_extract_field_schema` and …
> refactor(source): extract avro inner schema precisely

- src/meta/node/src/server.rs
- src/meta/src/backup_restore/utils.rs
- src/meta/src/controller/mod.rs
- src/meta/src/lib.rs
Extract function for connecting to a SQL meta store from a backend configuration.
</details>
> refactor(meta): extract code for connecting sql meta store

- src/connector/src/source/filesystem/opendal_source/opendal_reader.rs
- src/stream/src/executor/source/fetch_executor.rs
#19654 changed the `OpendalReader::stream_read_object` to yield lines instead of byte buffers, but there's a accidental change of the semantics of the `SourceMessage::offset` for file source, which caused main-cron to [fail](https://buildkite.com/risingwavelabs/main-cron/builds/4047#0193a700-f6c8-4059-b6b1-d272a0ce4e82).
The change is that, previously, when `OpendalReader::stream_read_object` yield `SourceMessage`s of byte buffers, the `offset` is the STARTIG position of the BYTES, and after `split_stream` which splits these bytes by new-line, the new `offset` will be set to the ENDING position of each LINE, which is …
> fix(file source): fix message offset of opendal source

- proto/ddl_service.proto
- proto/frontend_service.proto
- proto/stream_plan.proto
- src/frontend/src/catalog/catalog_service.rs
- src/frontend/src/handler/create_sink.rs
- src/frontend/src/handler/drop_sink.rs
- src/frontend/src/rpc/mod.rs
- src/frontend/src/test_utils.rs
- src/meta/service/src/ddl_service.rs
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/context/context_impl.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/manager/metadata.rs
- src/meta/src/manager/streaming_job.rs
- src/meta/src/model/stream.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/scale.rs
- src/meta/src/stream/source_manager.rs
- src/meta/src/stream/stream_graph/fragment.rs
- src/meta/src/stream/stream_manager.rs
- src/rpc_client/src/meta_client.rs
Finish the meta part of #19063: 
- 1. extend `match &stream_job` from Table to Source
- 2. handle split assignment for replace (need to align to prev actors, because of source backfill is aligned)
- Also changed the grpc interface from table to job.
e2e tests can be seem in #19649
</details>
> feat(meta): support replace source

- src/ctl/src/cmd_impl/debug.rs
- src/ctl/src/cmd_impl/debug/fix_create_definition.rs
- src/ctl/src/lib.rs
#18393 fixed an issue where certain source/table definition was invalid SQL (see tests in commit c0f95c8d30c2c4962e9e78ed116ee98310ca01e9 for examples).
This PR provides a tool to fix the definition in-place for sources/table created before v2.0.1, when drop and recreate is not feasible.
```shell
./risedev ctl debug fix-create-definition --etcd-endpoints localhost:2388 --dry-run
./risedev ctl debug fix-create-definition --etcd-endpoints localhost:2388
--enable-etcd-auth --etcd-username xxxx --etcd-password yyyy
```
Example:
```
source: id=1, name=src:
old definition: CREATE SOURCE IF NOT EXISTS src (*WATERMARK FOR …
```
> chore: add fix create definition cmd in rise ctl

- e2e_test/source_inline/kafka/issue_19563.slt.serial
This test becomes flaky. e.g., https://buildkite.com/risingwavelabs/pull-request/builds/63945
Probable reason: After https://github.com/risingwavelabs/risingwave/pull/19467, `CREATE SOURCE` returns earlier than before (previously, it will wait for source reader created, i.e., connection established). Now it doesn't wait for that.
See also https://github.com/risingwavelabs/risingwave/issues/19681#issuecomment-2527123971 …
> test: workaround a flaky source test

- src/meta/src/controller/mod.rs
Resolve https://github.com/risingwavelabs/risingwave/issues/19522.
The connection options to meta store exposed in #19040 do not apply to in-memory SQLite (typically used by `playground`). Therefore, default values from `sea-orm` or `sqlx` were used, where `max_lifetime` is set to 30 minutes. This means that #19522 will always occur after launching `playground` and waiting for 30 minutes, no matter whether there is any activity or not. …
> fix(meta): do not release connection to in-memory SQLite for meta store

- e2e_test/source_inline/kafka/alter/add_column_shared.slt
- proto/ddl_service.proto
- src/frontend/src/catalog/catalog_service.rs
- src/frontend/src/handler/alter_source_column.rs
- src/frontend/src/handler/create_source.rs
- src/frontend/src/test_utils.rs
- src/rpc_client/src/meta_client.rs
> feat(frontend): support alter add column for shared source

- e2e_test/iceberg/test_case/iceberg_engine.slt
- src/connector/src/source/iceberg/mod.rs
- src/frontend/src/planner/relation.rs
- https://github.com/risingwavelabs/risingwave/issues/19418
- Fix time travel for iceberg. Iceberg supports different time travel syntax from hummock table, so we should check the syntax accordingly.
</details>
> fix(iceberg): fix iceberg engine table time travel

- proto/stream_service.proto
- src/error/src/tonic/extra.rs
- src/meta/src/barrier/checkpoint/control.rs
- src/meta/src/barrier/checkpoint/mod.rs
- src/meta/src/barrier/checkpoint/recovery.rs
- src/meta/src/barrier/complete_task.rs
- src/meta/src/barrier/context/context_impl.rs
- src/meta/src/barrier/context/mod.rs
- src/meta/src/barrier/context/recovery.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/rpc.rs
- src/meta/src/barrier/worker.rs
- src/stream/src/task/barrier_manager.rs
In this PR, we implement the logic of database failure isolation in meta global barrier manager part. 
We will add a new variant `ReportDatabaseFailureResponse` in `StreamingControlStreamResponse` to report the failure of single database. After receiving such response, instead of triggering a global recovery, we will only recover the streaming job of the failed database, and other databases won't be affected by this failure. Note that, the per-database recovery is only triggered by receiving a `ReportDatabaseFailureResponse` from CN, and when receiving an error from bidi-stream to any compute node will still trigger …
> feat(barrier): support database failure isolation (part 1, meta)

- e2e_test/source_inline/kafka/protobuf/alter_source.slt
- e2e_test/source_inline/kafka/protobuf/alter_source_shared.slt
- src/frontend/src/handler/alter_source_with_sr.rs
follow up of #19649  (#19063). basically the same
</details>
> feat(frontend): support alter source refresh schema for shared source

- src/meta/src/backup_restore/restore_impl/v2.rs
When restoring metadata into the metastore, maintaining the insertion order is essential for tables that have additional constraints. This PR fixes these missing order.
</details>
> fix(meta): ensure order when restoring metadata

- ci/scripts/run-backfill-tests.sh
- e2e_test/backfill/snapshot_backfill/drop_mv.slt
- e2e_test/backfill/snapshot_backfill/run_test.slt.part
- src/stream/src/executor/backfill/snapshot_backfill.rs
Previously after snapshot backfill finishes and when the executor is recreated in recovery, we incorrectly do a `recv_next_barrier`, which will cause the recover to be stuck forever.
In this PR, we fix this bug and add test for the case of recovery.
</details>
> fix(snapshot-backfill): fix incorrect recv barrier and add test for recover

- e2e_test/source_inline/kafka/avro/ref.slt
- src/connector/codec/src/decoder/avro/mod.rs
- src/connector/codec/src/decoder/avro/schema.rs
- src/connector/codec/tests/integration_tests/avro.rs
- src/connector/src/parser/avro/parser.rs
- src/connector/src/parser/debezium/avro_parser.rs
Sequel to #19601 and resolves #17020.
The recursive call is changed from `Self {schema: inner, relax_numeric: self.relax_numeric}.convert_to_datum(v, field_type)` into `self.convert_to_datum(inner, v, field_type)` so that
* The changing part `schema: inner` is passed as argument rather than keep reconstructing new `AvroParseOptions`.
* `self: AvroParseOptionsInner` captures the immutable "global" context: `relax_numeric: bool` and `refs: NamesRef<'a>`
On the use site, `self.schema` is changed to `self.lookup_ref(unresolved_schema)`. Note that introducing a new type to distinguish `resolved` from `unresolved` would not …
> fix(source): resolve avro `Ref` during `access` without hack

- Cargo.lock
- ci/scripts/e2e-sink-test.sh
- risedev.yml
- src/common/src/config.rs
- src/config/ci-jdbc-to-native.toml
- src/config/example.toml
- src/stream/Cargo.toml
- src/stream/src/from_proto/sink.rs
We can switch from `jdbc:postgres` to native postgres sink by enabling a config under `[streaming.developer]`.
See Release Notes below for more details.
We support switching from `connector='jdbc'` for jdbc postgres sinks to `connector='postgres'`.
This can be done by enabling a streaming developer config:
```
[streaming.developer]
stream_switch_jdbc_pg_to_native = true
```
> feat(common): support switching from pg jdbc to pg native sinks

- e2e_test/error_ui/simple/recovery.slt
- src/stream/src/task/barrier_manager.rs
- src/stream/src/task/barrier_manager/managed_state.rs
- src/stream/src/task/stream_manager.rs
After https://github.com/risingwavelabs/risingwave/pull/19664. The local barrier manager part of database failure isolation.
Previously in `ManagedBarrierState`, all databases are in a `Running` status, as a `DatabaseManagedBarrierState`, because in case of any failure, we will wait for a global recovery. To support database failure isolation, besides the `Running` status, we will have the following statuses.
```
pub(crate) enum DatabaseStatus {
Running(DatabaseManagedBarrierState),
Suspended(SuspendedDatabaseState),
Resetting(ResettingDatabaseState),
}
```
The lifecycle of a `DatabaseStatus` will be
1. Get created when …
> feat(barrier): support database failure isolation (part 2, local)

- ci/docker-compose.yml
- ci/workflows/main-cron.yml
- ci/workflows/pull-request.yml
- risedev.yml
- src/risedevtool/src/task/meta_node_service.rs
- Use `meta-backend: env` for all CI RiseDev profiles.
* use a persisted SQLite database as a fallback when env var is not set, behaving as if `meta-backend: sqlite` is specified, ensuring compatibility with the behavior prior to this PR.
- Extend coverage for PG/MySQL meta backends on `main-cron` to
* slow e2e test
* parallel e2e test
* e2e source test
* e2e sink test
Note that although there are many other steps for specific connectors, I suppose it may not be necessary to cover them all, as the execution path on the meta node should not differ significantly. …
> feat(ci): more meta backend agnostic e2e tests in `main-cron`

- src/meta/src/backup_restore/restore_impl/v2.rs
#19763 didn't fix the issue correctly, since `alter table set schema` may result in a row of with obj_type=TABLE and schema_id > oid, which still violates the constraint `FK_object_schema_id`.
This PR ensures rows with obj_type=DATABASE are inserted first, then obj_type=SCHEMA, lastly others.
<details>
</details>
> fix(meta): fix order when restoring metadata

- java/connector-node/tracing/src/main/java/com/risingwave/tracing/TracingSlf4jAdapter.java
`LOG.error("Failed to execute JDBC statements, retried {} times", retryCount, e);` doesn't print the stack trace. This pr fixes it.
<details>
</details>
> fix(log): print java exception stack trace in logger

- e2e_test/source_inline/kafka/issue_19563.slt.serial
- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/DbzSourceUtils.java
- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/PostgresValidator.java
- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/JniDbzSourceHandler.java
- src/stream/src/executor/source/source_executor.rs
Previously we reverted the retry for source executor #19754. This PR we re-introduce the retry mechanism but only during recovery process. Because when source job create in the first time, it should fail if cannot reach the upstream system.
And we merge the patch https://github.com/risingwavelabs/risingwave/pull/19714 into this PR
passed main-cron https://buildkite.com/risingwavelabs/main-cron/builds/4092
close https://github.com/risingwavelabs/risingwave/issues/19681
<details>
</details>
> feat(source): create source stream with retry during recovery

- docs/dev/src/design/relational-table.md
- src/batch/executors/src/executor/source.rs
- src/connector/src/connector_common/iceberg/storage_catalog.rs
- src/frontend/src/handler/util.rs
fix typos
<details>
</details>
> chore: fix typos in func && doc && comment

- src/connector/benches/json_parser_case_insensitive.rs
- src/connector/benches/nexmark_integration.rs
- src/connector/src/parser/chunk_builder.rs
- src/connector/src/parser/mod.rs
- src/connector/src/parser/plain_parser.rs
- src/connector/src/source/base.rs
- src/connector/src/source/cdc/source/reader.rs
- src/connector/src/source/common.rs
- src/connector/src/source/datagen/source/reader.rs
- src/connector/src/source/filesystem/opendal_source/opendal_reader.rs
- src/connector/src/source/filesystem/s3/source/reader.rs
- src/connector/src/source/filesystem/s3/source/split_stream.rs
- src/connector/src/source/google_pubsub/source/reader.rs
- src/connector/src/source/iceberg/mod.rs
- src/connector/src/source/kafka/source/reader.rs
- src/connector/src/source/kinesis/source/reader.rs
- src/connector/src/source/mqtt/source/reader.rs
- src/connector/src/source/nats/source/reader.rs
- src/connector/src/source/nexmark/source/reader.rs
- src/connector/src/source/pulsar/source/reader.rs
- src/connector/src/source/reader/fs_reader.rs
- src/connector/src/source/reader/reader.rs
- src/connector/src/source/test_source.rs
- src/stream/src/executor/source/fetch_executor.rs
- src/stream/src/executor/source/fs_source_executor.rs
- src/stream/src/executor/source/mod.rs
- src/stream/src/executor/source/source_backfill_executor.rs
- src/stream/src/executor/source/source_executor.rs
To make code more understandable.
<details>
</details>
> refactor(source): rename some source parser related types and methods

- src/utils/runtime/src/lib.rs
The original aws_lc_rs provider may default to FIPS mode in certain situations, where FIPS may not be available, leading to panic due to `error:12800067:DSO support routines:dlfcn_load:could not load the shared library:../crypto/dso/dso_dlfcn.c:118:filename(/usr/lib/x86_64-linux-gnu/ossl-modules/fips.so): /usr/lib/x86_64-linux-gnu/ossl-modules/fips.so: cannot open shared object file: No such file or directory, error:12800067:DSO support routines:DSO_load:could not load the shared library:../crypto/dso/dso_lib.c:152:, error:07880025:common libcrypto …
> fix: use ring as default provider

- src/frontend/src/lib.rs
- src/frontend/src/optimizer/optimizer_context.rs
- src/frontend/src/optimizer/plan_node/mod.rs
In `OptimizerContext`, we have some fields representing the last assigned optimizer element IDs, e.g. plan node ID. Previously we use `RefCell` for these fields, but what we actually want is just interior mutability, not runtime borrow checking. This PR changes these fields to use `Cell` instead.
<details>
</details>
> refactor(optimizer): use `Cell` instead of `RefCell` for interior mutability

- ci/docker-compose.yml
- ci/scripts/run-e2e-test.sh
- ci/workflows/main-cron.yml
- ci/workflows/pull-request.yml
- src/meta/model/migration/clippy.toml
- src/meta/model/migration/src/m20241125_043732_connection_params.rs
- src/meta/model/migration/src/utils.rs
Follow up of #19595. Address bugs for MySQL meta backend and re-enable it.
<details>
</details>
> fix(meta): fix & enable e2e tests with MySQL meta backend

- e2e_test/source_inline/kafka/avro/alter_table.slt
- src/common/src/catalog/column.rs
- src/common/src/catalog/mod.rs
- src/common/src/catalog/schema.rs
- src/frontend/src/handler/alter_source_with_sr.rs
- src/frontend/src/handler/create_source.rs
- src/frontend/src/handler/create_table.rs
- src/frontend/src/handler/create_table_as.rs
- src/frontend/src/session.rs
When generating column ID for existing columns (by name), also check and reject if the data type changes. Otherwise, the persisted data will be incompatible and lead to undefined behavior.
Note that for struct types, the nested fields are encoded with value-encoding (instead of column-aware encoding) under current implementation. As a result, adding new nested fields cannot be supported and should be rejected as well. Close https://github.com/risingwavelabs/risingwave/issues/19736.
This won't be hit for a regular table as we don't provide syntax support for …
> fix(frontend): check data type in column id generator

- src/meta/src/hummock/manager/time_travel.rs
During commit_epoch for newly created table, a `GroupConstruct` delta is expected, which triggers [a false alarm](https://github.com/risingwavelabs/risingwave/blob/3cbc231b002eeef2e370ae15d067e4518b0f57dd/src/storage/hummock_sdk/src/time_travel.rs#L219). The alarm was added to assert only `NewL0SubLevel` delta was kept for time travel.
This PR resolves this issue by skipping delta contaning `GroupConstruct` for time travel, because for that delta a complete version snapshot is ensured to be created for time travel, based on …
> fix(meta): skip unnecessary delta persistence

- src/connector/src/sink/mongodb.rs
in doc https://www.mongodb.com/zh-cn/docs/manual/reference/method/db.collection.bulkWrite/#mongodb-method-db.collection.bulkWrite 
The correct error is `writeErrors` and `writeConcernErrors`
And you shouldn't use n to check if the write was successful, because there are times when n will be 0.
Let's say we delete a piece of mongodb non-existent data
<details>
</details>
> fix(sink): fix mogodb write error handling

- Makefile.toml
- e2e_test/sink/pg_native_vs_jdbc.slt
- src/connector/src/sink/postgres.rs
Just measure the throughput for both via grafana.
The performance improvement of unoptimized to optimized native pg sink went from 30r/s to 10K r/s.
The performance is around the same as JDBC. LHS is for native pg sink. RHS is for jdbc sink. Toggle the screenshot below.
---
<details>
<summary>screenshot</summary>
</details>
---
Implementation details:
1. We batch inserts and deletes in this PR, with up to 32768 parameters, since that's the max parameter supported by PG.
2. We use transactions to delimit each batch.
3. We remove `updateInsert` handling path, since compaction will normalizze `updateInsert` to `Insert`.
4. …
> perf(stream): optimize native pg sink

- e2e_test/batch/catalog/information_schema.slt
- e2e_test/batch/catalog/pg_class.slt.part
- src/frontend/src/catalog/system_catalog/information_schema/key_column_usage.rs
- src/frontend/src/catalog/system_catalog/information_schema/mod.rs
- src/frontend/src/catalog/system_catalog/information_schema/table_constraints.rs
- src/frontend/src/catalog/system_catalog/pg_catalog/mod.rs
- src/frontend/src/catalog/system_catalog/pg_catalog/pg_stat_user_tables.rs
> feat: support pg_stat_user_tables and key_column_usage

- src/storage/src/hummock/event_handler/uploader/mod.rs
- src/storage/src/hummock/event_handler/uploader/task_manager.rs
Currently in uploader, when an local instance is destroyed, we will remove the instance from the uploader immediately, even if there is some unsync data in the instance. The logic works in current code, because an instance can be destroyed in 3 scenarios: drop streaming job, configuration change, and actor exit on error or recovery. When dropping streaming job, the table will be removed soon, and therefore the loss of data is invisible. In configuration change, before the barrier to drop actors, we will have a pause barrier to ensure that there is no data in …
> feat(storage): lazily remove instance data in uploader to avoid data loss

- e2e_test/batch/types/jsonb.slt.part
- e2e_test/batch/types/map.slt.part
- src/common/src/types/jsonb.rs
close #19918
<details>
</details>
> fix: support string to number type in JSONB_POPULATE_RECORD

- proto/stream_service.proto
- src/meta/src/barrier/checkpoint/control.rs
- src/meta/src/barrier/rpc.rs
- src/meta/src/barrier/worker.rs
- src/stream/src/executor/dispatch.rs
- src/stream/src/executor/merge.rs
- src/stream/src/executor/receiver.rs
- src/stream/src/task/barrier_manager.rs
- src/stream/src/task/barrier_manager/managed_state.rs
- src/stream/src/task/mod.rs
- src/stream/src/task/stream_manager.rs
Root cause of https://github.com/risingwavelabs/risingwave/issues/19536.
Resolve https://github.com/risingwavelabs/risingwave/issues/19884
Previously for newly added node, we won't broadcast the existing actor info to the node. When actors that are spawned later on this node try to get the actor info in other nodes, it will get the `actor id not found` error.
In this PR, we fix this by including all the existing actor infos in the initial request for the newly add node. 
By the way, we also change the way to broadcast inflight subscription infos in recovery. …
> fix(barrier): broadcast actor info to newly added node

- ci/workflows/pull-request.yml
- e2e_test/batch/order/negative_offset.slt.part
- e2e_test/batch/order/test_limit.slt.part
- src/frontend/src/binder/query.rs
- src/frontend/src/planner/query.rs
- src/sqlparser/src/ast/query.rs
- src/sqlparser/src/parser.rs
- src/sqlparser/tests/sqlparser_common.rs
- src/tests/sqlsmith/src/sql_gen/query.rs
fix #19830 
required by SQLMesh's CI test
The fix is to evaluate the expression during binding stage so that we either accept the result (it is a number >=0 after casting to bigint) or reject it (all the other cases)
<details>
</details>
> feat: support expression in limit clause

- src/frontend/src/catalog/table_catalog.rs
- src/frontend/src/expr/function_impl/pg_get_viewdef.rs
- src/frontend/src/handler/alter_table_column.rs
- src/frontend/src/handler/alter_table_with_sr.rs
- src/frontend/src/handler/create_sink.rs
As title.
<details>
</details>
> refactor(frontend): extract code for parsing table def sql into single stmt

- src/common/src/util/chunk_coalesce.rs
- src/stream/src/common/log_store_impl/kv_log_store/serde.rs
- src/stream/src/executor/backfill/snapshot_backfill/executor.rs
- src/stream/src/executor/backfill/snapshot_backfill/mod.rs
- src/stream/src/executor/backfill/snapshot_backfill/vnode_stream.rs
Part of https://github.com/risingwavelabs/risingwave/pull/19720.
For snapshot backfill, in the main branch and the future PR https://github.com/risingwavelabs/risingwave/pull/19720, the stage of consuming snapshot and consuming log store have the similar logic of consuming a stream of row with op and convert the stream into stream chunk. In this PR, we will extra the common logic and let them share the same code.
Previously, the row streams of multiple vnodes are combined in the stream returned from `StorageTable` method. In this PR we will change to combine …
> refactor(snapshot-backfill): extract common logic of consuming snapshot and log store

- src/connector/src/parser/config.rs
The PR #17456 (commit 96de66440d5f8238d920ac76ce04cbd6247bcb21) updated one occurrence below but missed the other two fixed in this PR.
https://github.com/risingwavelabs/risingwave/blob/96de66440d5f8238d920ac76ce04cbd6247bcb21/src/connector/src/parser/mod.rs#L1287
<details>
</details>
> refactor(source): prefer `options_with_secret` over `with_properties` in `SpecificParserConfig::new`

- src/stream/benches/stream_hash_join.py
- src/stream/benches/stream_hash_join_mem.rs
- src/stream/benches/stream_hash_join_rt.rs
- src/stream/src/executor/test_utils.rs
Add more benchmarks:
1. Different amplification sizes.
2. Different cache properties (not in cache / in cache).
3. Different join types (outer / inner).
<details>
</details>
> feat(bench): add bench with join type and cache workload

- src/cmd_all/src/single_node.rs
- src/compute/src/lib.rs
- src/compute/src/memory/config.rs
Follow up of #19477. This makes it work in `single-node` mode.
<details>
</details>
> feat(single-node): add memory allocation

- src/connector/src/sink/postgres.rs
Closes https://github.com/risingwavelabs/risingwave/issues/19913
<details>
</details>
> refactor(connector): use `pk IN (...)` instead of `AND/OR` in DELETE for pg sink

- src/cmd_all/src/standalone.rs
- src/compute/src/server.rs
- src/frontend/src/lib.rs
- src/frontend/src/session.rs
- src/meta/src/hummock/test_utils.rs
- src/storage/benches/bench_compactor.rs
- src/storage/benches/bench_multi_builder.rs
- src/storage/compactor/src/compactor_observer/observer_manager.rs
- src/storage/compactor/src/lib.rs
- src/storage/compactor/src/server.rs
- src/storage/hummock_test/src/bin/replay/main.rs
- src/storage/hummock_test/src/compactor_tests.rs
- src/storage/hummock_test/src/sync_point_tests.rs
- src/storage/hummock_test/src/test_utils.rs
- src/storage/src/compaction_catalog_manager.rs
- src/storage/src/hummock/compactor/compaction_utils.rs
- src/storage/src/hummock/compactor/compactor_runner.rs
- src/storage/src/hummock/compactor/fast_compactor_runner.rs
- src/storage/src/hummock/compactor/mod.rs
- src/storage/src/hummock/compactor/shared_buffer_compact.rs
- src/storage/src/hummock/event_handler/hummock_event_handler.rs
- src/storage/src/hummock/observer_manager.rs
- src/storage/src/hummock/sstable/builder.rs
- src/storage/src/hummock/sstable/multi_builder.rs
- src/storage/src/hummock/sstable/xor_filter.rs
- src/storage/src/hummock/store/hummock_storage.rs
- src/storage/src/hummock/test_utils.rs
- src/storage/src/lib.rs
- src/storage/src/store_impl.rs
cherry-pick 
- https://github.com/risingwavelabs/risingwave/pull/19372
- https://github.com/risingwavelabs/risingwave/pull/19059
<details>
</details>
> feat(memory): cherry-pick  #19372 and #19059 to branch release-2.1

- Cargo.lock
- Cargo.toml
- src/batch/executors/src/executor/iceberg_scan.rs
- src/connector/src/sink/iceberg/mod.rs
> feat: update iceberg version

- src/storage/hummock_sdk/src/change_log.rs
- src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
- src/storage/hummock_sdk/src/frontend_version.rs
- src/storage/hummock_sdk/src/time_travel.rs
- src/storage/hummock_sdk/src/version.rs
- src/storage/src/hummock/store/version.rs
May alleviate the issue mentioned in https://github.com/risingwavelabs/risingwave/issues/19960.
Previously we use `Vec` to store all table change log. When applying version delta, we use `Vec::retain` to clean the stale change log. However, for subscription with large retention time, the `Vec` can be large, and the `Vec::retain` called in `truncate` will incur great cost. In this PR, we change to use `VecDeque` to store the change log, so that the cost of `truncate` will reduce from `O(N)` to `O(1)`.
<details>
</details>
> perf(storage): use VecDeque for TableChangeLog to avoid large clone on truncate

- .git-blame-ignore-revs
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/context/context_impl.rs
- src/meta/src/controller/catalog/drop_op.rs
- src/meta/src/controller/catalog/mod.rs
- src/meta/src/controller/utils.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/source_manager.rs
1. rename some fields to make it clearer
2. remove a duplicated method
<details>
</details>
> refactor(meta): minor refactors 

- src/meta/src/barrier/command.rs
- src/meta/src/barrier/context/context_impl.rs
- src/meta/src/barrier/context/recovery.rs
- src/meta/src/controller/catalog/mod.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/scale.rs
- src/meta/src/stream/source_manager.rs
Previously, we have multiple code paths for different kinds of source changes: e.g., `unregister_source`, `drop_source_fragments`, and `apply_source_change`. Actually they have some overlap, and some missing cleanup tasks forgotten to do. 
Since what they did is really similar: update states after some operations, in this PR, I try to merge them in to one func call, and dispatch by `enum` variant. This makes it easier for caller to choose what to call, and can help maintain consistency in the cleanup impl.
Prepare for …
> refactor(meta): unify code for different kinds of source change

- src/common/src/array/stream_chunk.rs
- src/connector/src/sink/log_store.rs
- src/stream/src/executor/dml.rs
- src/stream/src/executor/source/mod.rs
After #19698, we can expect chunks yielded to `SourceExecutor`s to be smaller than `SourceCtrlOpts::chunk_size`, so we don't need to split chunks in `apply_rate_limit` (used by `FetchExecutor`, `FsSourceExecutor`, `SourceBackfillExecutor` and `SourceExecutor`) anymore.
This PR removes the chunk splitting logic from `apply_rate_limit`.
<details>
</details>
> refactor(source): remove chunk splitting logic in `apply_rate_limit`

- src/stream/src/executor/backfill/snapshot_backfill/executor.rs
- src/stream/src/executor/backfill/snapshot_backfill/vnode_stream.rs
Part of https://github.com/risingwavelabs/risingwave/pull/19720
Measure the row count of each vnode stream, so that the row count can be saved in the state to be introduced in https://github.com/risingwavelabs/risingwave/pull/19720.
This PR will also fix a bug found in the CI https://github.com/risingwavelabs/risingwave/pull/19720. In short, the bug is caused by the use of `FuturesUnordered`. In `FuturesUnordered`, pending futures will be stored separately and will not be polled until a special cx generated in `FuturesUnordered::poll_next` is awakened. …
> feat(snapshot-backfill): measure accumulated row count for each vnode stream

- e2e_test/ddl/show.slt
- e2e_test/ddl/show_purify.slt
- e2e_test/source_inline/kafka/avro/alter_table.slt
- src/common/src/catalog/column.rs
- src/frontend/src/catalog/mod.rs
- src/frontend/src/catalog/purify.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_tables.rs
- src/frontend/src/catalog/table_catalog.rs
- src/frontend/src/handler/alter_table_column.rs
- src/frontend/src/handler/create_table_as.rs
- src/frontend/src/handler/show.rs
- src/frontend/src/utils/data_type.rs
- src/frontend/src/utils/mod.rs
- src/sqlparser/src/ast/mod.rs
See #17472 for the background. This PR initially introduces SQL purification for table definition, and adopt it in `SHOW CREATE TABLE`. Further adoption (like for replacing table plan) will be done in future PRs, as they require additional work that is not directly relevant to the current scope to ensure a complete end-to-end implementation.
It turns out that we only need to restore the `ColumnDef` (specifically, the `DataType`, which is already contributed by @StrikeW). This makes the procedure much simpler than initially thought.
<details> …
> feat(frontend): initially introduce table def sql purification

- e2e_test/source_inline/kafka/protobuf/alter_source.slt
- src/frontend/src/catalog/purify.rs
- src/frontend/src/catalog/source_catalog.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_sources.rs
- src/frontend/src/catalog/table_catalog.rs
- src/frontend/src/handler/show.rs
Sequel to #19949. Extract the purification snippet to reuse for `CREATE SOURCE`.
<details>
</details>
> feat(frontend): purification for source def sql

- ci/scripts/e2e-mongodb-sink-test.sh
- e2e_test/sink/mongodb_sink.slt
- src/connector/src/sink/mongodb.rs
Before: 
If mongodb's data is 
```
id: 1
v1:1
v2:1
v3:1
```
our table is` v1,v2 (v1 is pk)`, we `insert 1,1`
mongodb's data will be 
```
id: 1
v1:1
v2:1
```
Or we `update v2 = 100 where v1 = 1`;
mongodb's data will be 
```
id: 1
v1:1
v2:100
```
After this pr: 
`insert 1,1` mongodb's data will be 
```
id: 1
v1:1
v2:1
v3:1
```
`update v2 = 100 where v1 = 1`; mongodb's data will be 
```
id: 1
v1:1
v2:100
v3:1
```
<details>
</details>
> feat(sink): Support updates rather than overrides for mongodb sink upsert

- src/stream/benches/stream_hash_join_rt.rs
- src/stream/src/executor/test_utils.rs
If we commit to state store, we will end up measuring the memory consumption of writing the amplified chunks to the in-memory state store.
In production, state store is on top of object storage / disk. The in-memory state store is only used in benchmark / tests. So we shouldn't benchmark the memory consumption.
Further, the amplified chunks are not written in a large batch typically. The scenario we care about is OOM from dimension table update. In such a scenario, the fact table side's memory consumption will be high due to reads from the update side, rather …
> fix(stream): avoid committing to in-memory state store in join benchmark

- ci/scripts/run-backfill-tests.sh
- e2e_test/backfill/snapshot_backfill/scale.slt
- src/frontend/src/optimizer/plan_node/stream_table_scan.rs
- src/stream/src/common/table/state_table.rs
- src/stream/src/executor/backfill/snapshot_backfill/executor.rs
- src/stream/src/executor/backfill/snapshot_backfill/mod.rs
- src/stream/src/executor/backfill/snapshot_backfill/state.rs
- src/stream/src/executor/backfill/snapshot_backfill/vnode_stream.rs
- src/stream/src/task/stream_manager.rs
In this PR, we will introduce state to track the progress of snapshot backfill. The progress state table will have the following schema
```
| vnode | `epoch` | `row_count` | `is_epoch_finished` | pk ...
```
* The pk of the state is `vnode`, which means we track the snapshot backfill progress in per-vnode way. 
* `epoch` is the epoch that the `vnode` is currently consuming on. We can assume that `epoch >= snapshot_epoch`. When `epoch == snapshot_epoch`, the `vnode` will be consuming the snapshot, and when `epoch > snapshot_epoch`, the `vnode` will be consuming the change log on `epoch`.
* `row_count` is the number of …
> feat(snapshot-backfill): introduce state to snapshot backfill

- src/frontend/src/handler/query.rs
- src/frontend/src/planner/mod.rs
- src/frontend/src/planner/relation.rs
- We should only convert the iceberg table to iceberg source for batch dql, since other batch sql (especially dml update and delete) should read the hummock table and use indexes to improve the performance and freshness.
<details>
</details>
> fix(iceberg): only convert iceberg table to iceberg source for batch dql

- src/stream/src/common/table/state_table.rs
- src/stream/src/executor/mview/materialize.rs
The point of `StateTable::get_compacted_row` is that, when a table is using value-encoding, we can save a roundtrip of parsing the encoded row bytes into an `OwnedRow` and serializing it back.
This function is currently used only by `MaterializeCache` when a state table has an on-conflict behavior set. However, in such cases, the state table must be a user `TABLE` that adopts column-aware encoding. As a result, the optimized branch is effectively dead.
In this PR, we remove this function and inline it to its only caller.
This shows us that there's no …
> refactor(streaming): remove `get_compacted_row` from `StateTable`

- src/sqlparser/src/parser.rs
- src/sqlparser/tests/testdata/select.yaml
Fixes https://github.com/risingwavelabs/risingwave/issues/19732
- Before: Parsing was only possible when LIMIT preceded OFFSET.
- After: LIMIT and OFFSET can now be parsed in any order.
I found a similar implementation in [datafusion-sqlparser-rs](https://github.com/apache/datafusion-sqlparser-rs/blob/94ea20628fbc9950e87d165e3b4f904419ec03f0/src/parser/mod.rs#L9535-L9545) and couldn’t think of a better way, so this one’s basically the same.
<details>
</details>
> fix(sqlparser): make LIMIT and OFFSET order flexible

- e2e_test/sink/elasticsearch/elasticsearch_sink.slt
- src/connector/src/sink/elasticsearch_opensearch/elasticsearch.rs
- src/connector/src/sink/elasticsearch_opensearch/elasticsearch_converter.rs
- src/connector/src/sink/elasticsearch_opensearch/elasticsearch_opensearch_client.rs
- src/connector/src/sink/elasticsearch_opensearch/elasticsearch_opensearch_config.rs
- src/connector/src/sink/elasticsearch_opensearch/elasticsearch_opensearch_formatter.rs
- src/connector/src/sink/elasticsearch_opensearch/opensearch.rs
- src/connector/src/sink/remote.rs
- src/connector/with_options_sink.yaml
We didn't support type for es sink, and this pr support it like other sink
<details>
</details>
> feat(sink): support force_append_only for es sink

- src/meta/src/hummock/manager/gc.rs
- src/meta/src/hummock/manager/time_travel.rs
[The SeaORM crate has a bug](https://github.com/SeaQL/sea-orm/issues/1790) that causes the meta node to panic when using MySQL as the meta store. Specifically, the `OnConflict do_nothing` doesn't work for MySQL.
The bug has been fixed in SeaORM of newer version. This PR provides a workaround for the bug instead of [upgrading the SeaORM version](https://github.com/risingwavelabs/risingwave/pull/19207).
<details>
</details>
> fix(meta): work around sea-orm bug

- src/meta/src/hummock/manager/gc.rs
- src/meta/src/hummock/manager/time_travel.rs
[The previous PR](https://github.com/risingwavelabs/risingwave/pull/20099) fixes the ORM issue for MySQL but break PG..
<details>
</details>
> fix(meta): work around sea-orm bug for PG

- src/meta/src/hummock/manager/gc.rs
- src/meta/src/hummock/manager/time_travel.rs
- src/meta/src/hummock/manager/versioning.rs
cherry pick #20108
<details>
</details>
> fix(meta): fix time travel GC bug

- src/meta/src/hummock/manager/tests.rs
- src/meta/src/hummock/mock_hummock_meta_client.rs
- src/meta/src/hummock/test_utils.rs
- src/rpc_client/src/hummock_meta_client.rs
- src/rpc_client/src/lib.rs
- src/rpc_client/src/meta_client.rs
- src/storage/hummock_sdk/src/change_log.rs
- src/storage/hummock_test/src/compactor_tests.rs
- src/storage/hummock_test/src/failpoint_tests.rs
- src/storage/hummock_test/src/hummock_storage_tests.rs
- src/storage/hummock_test/src/snapshot_tests.rs
- src/storage/hummock_test/src/state_store_tests.rs
- src/storage/hummock_test/src/test_utils.rs
- src/storage/src/hummock/error.rs
- src/storage/src/hummock/hummock_meta_client.rs
- src/storage/src/hummock/store/hummock_storage.rs
- src/storage/src/memory.rs
- src/storage/src/monitor/monitored_store.rs
- src/storage/src/monitor/traced_store.rs
- src/storage/src/panic_store.rs
- src/storage/src/store.rs
- src/storage/src/store_impl.rs
- src/storage/src/table/batch_table/storage_table.rs
- src/stream/src/executor/backfill/snapshot_backfill/executor.rs
Support `next_epoch` method for `StateStoreReadLog`. The method returns the `next_epoch` of the given `epoch` in the table change log.
<details>
</details>
> feat(storage): support next_epoch method for StateStoreReadLog

- src/connector/src/source/iceberg/parquet_file_handler.rs
The bug is miss previously overlooked because builder = builder.disable_config_load(); was not added. As a result, during local testing, it was able to access S3 normally since it was reading from the local AWS environment variables.
In other words, if the AWS config is correctly configured locally, it can also be read normally.
The main branch has already been fixed.
<details>
</details>
> fix(connctor):  fix file scan s3 access issue in release-2.2

- Cargo.lock
- Makefile.toml
- ci/Dockerfile
- ci/build-ci-image.sh
- ci/docker-compose.yml
- ci/scripts/common.sh
- ci/scripts/e2e-source-test.sh
- ci/scripts/e2e-test-parallel-for-opendal.sh
- ci/scripts/e2e-test-parallel-in-memory.sh
- ci/scripts/e2e-test-parallel.sh
- e2e_test/source_inline/README.md
- src/tests/simulation/Cargo.toml
https://github.com/risinglightdb/sqllogictest-rs/pull/246
The motivation is that currently when test failed, the end of the log is usually some error like "table not found", and we need to scroll up to find the real error.
<details>
</details>
> ci: fail fast sqllogictest

- src/common/src/config.rs
- src/config/example.toml
- src/meta/node/src/lib.rs
- src/meta/src/hummock/manager/time_travel.rs
- src/meta/src/manager/env.rs
To reduce RTT.
<details>
</details>
> refactor(meta): use insert_many to reduce latency

- src/frontend/src/expr/mod.rs
- src/frontend/src/expr/user_defined_function.rs
Display only `the_function_name(arg1, arg2)` instead of the full debug info of `FunctionCatalog`. Fix #18588.
<details>
</details>
> feat(frontend): display UDF calls more concisely

- e2e_test/source_inline/kafka/avro/name_strategy.slt
- e2e_test/source_inline/kafka/protobuf/opentelemetry.slt
> test: add retry to flaky test

- src/connector/src/macros.rs
- src/connector/src/source/base.rs
- src/connector/src/source/filesystem/opendal_source/mod.rs
- src/connector/src/source/kinesis/mod.rs
- src/connector/src/source/mod.rs
- src/connector/src/source/mqtt/mod.rs
- src/connector/src/source/nats/mod.rs
- src/connector/src/source/reader/fs_reader.rs
- src/connector/src/source/reader/reader.rs
- src/meta/service/src/cloud_service.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/source_manager.rs
- src/meta/src/stream/source_manager/worker.rs
- src/stream/src/executor/source/source_backfill_executor.rs
- src/stream/src/executor/source/source_executor.rs
Previously we use `dispatch_source_prop` macro to dispatch a large enum, and use a generic function inside the macro. This PR moved these lines into method of `ConnectorProperties`, and make it return `dyn`. The traits are refactored to be `dyn-compatible` (aka object safe)
benefits:
- This is not IDE friendly, and hard to maintain. <img width="1002" alt="image" src="https://github.com/user-attachments/assets/a487fa2c-db09-402f-84a4-990e7b7ab02b" />
- (not sure) `dyn` may slightly compile faster than generics, because generics will lead to code bloat. And …
> refactor(connector): make SplitEnumerator/Reader dyn

- src/frontend/src/catalog/purify.rs
- src/frontend/src/handler/create_table.rs
- src/sqlparser/src/ast/ddl.rs
- src/sqlparser/src/parser.rs
- src/sqlparser/tests/sqlparser_postgres.rs
In #19949 we mentioned that
> convert `ExprNode` back to ast can be a bit tricky.
which is the very missing piece of definition purification.
In this PR, we allow converting persisted `DefaultColumnDesc` back to `ast::ColumnOption::DefaultValue` losslessly, by simply storing the encoded value temporarily into the AST.
Apparently this is somehow hacky, as unparsing the AST back to SQL will still lose such information. However, this can still be beneficial for...
- reusing the purification code for `get_new_table_definition_for_cdc_table`
- resolv-ing …
> feat(frontend): lossy "purify" column default value

- src/frontend/src/catalog/mod.rs
- src/frontend/src/catalog/purify.rs
- src/frontend/src/catalog/table_catalog.rs
- src/frontend/src/handler/alter_table_column.rs
- src/frontend/src/handler/alter_table_with_sr.rs
- src/frontend/src/handler/create_sink.rs
- src/frontend/src/handler/create_table.rs
- src/frontend/src/rpc/mod.rs
As title. Also simplify the arguments of related functions.
<details>
</details>
> refactor(frontend): reuse def purification for assembling cdc table def when auto schema change

- e2e_test/ddl/show_purify.slt
- e2e_test/sink/sink_into_table/ctas.slt
- src/frontend/src/catalog/table_catalog.rs
Allow performing schema changes (`ALTER TABLE ... [ADD | DROP] COLUMN`) on or create a sink into a table created by `CREATE TABLE AS` statement.
----
After #19949, we now have two different methods for retrieving the definition of a table: `create_sql` and `create_sql_purified`. Prior to this PR, `create_sql` always directly return the persisted definition string, while `create_sql_purified` will re-assemble a definition with all columns qualified based on the `TableCatalog`.
However, the definitions for CTAS tables are missing, causing `create_sql_ast` to …
> feat(frontend): allow schema change & sink into a CTAS table

- src/storage/src/hummock/store/local_hummock_storage.rs
- src/storage/src/lib.rs
- src/storage/src/memory.rs
- src/storage/src/monitor/monitored_store.rs
- src/storage/src/monitor/traced_store.rs
- src/storage/src/panic_store.rs
- src/storage/src/store.rs
- src/storage/src/store_impl.rs
- src/stream/src/common/log_store_impl/kv_log_store/mod.rs
- src/stream/src/common/log_store_impl/kv_log_store/reader.rs
Previously in the sink log store, for log reader, we use methods in `StateStore` to access the data flushed by log writer. Methods in `StateStore` will read all shards (aka HummockReadVersion) of the `table_id` on the same CN. However, since the log reader is always in the same SinkExecutor as  log writer, it actually only needs to read the shard that belongs to the writer, and using `StateStore` will unnecessarily read more unrelated data.
In this PR, we will add a new method `new_flushed_snapshot_reader` to `LocalStateStore`, whose return type is a new …
> feat(storage): refactor and support local state store flushed snapshot reader

- e2e_test/source_inline/kafka/avro/glue.slt.serial
- src/connector/src/parser/protobuf/parser.rs
- src/connector/src/schema/loader.rs
- src/connector/src/schema/mod.rs
- src/connector/src/schema/protobuf.rs
- src/connector/src/sink/encoder/avro.rs
- src/connector/src/sink/formatter/mod.rs
Supports loading schema from and encoding metadata for AWS Glue Schema Registry, in addition to Confluent Schema Registry, when using `encode avro`.
Notes:
* Glue Schema Registry has no references (eg `import` in protobuf).
* Glue Schema Registry has no name strategy. So it would require an additional `aws.glue.key_schema_arn`. This is left unimplemented in favor of real use case `KEY ENCODE [TEXT | BYTES]`.
Related: #17605 for source
Refactor to come next: {Confluent, Glue} x {Source, Sink} x {Avro, Protobuf}
Added support for AWS Glue Schema Registry when …
> feat(sink): Avro with AWS Glue Schema Registry

- src/meta/service/src/scale_service.rs
- src/meta/service/src/stream_service.rs
- src/meta/src/barrier/context/recovery.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/manager/metadata.rs
- src/meta/src/model/stream.rs
Currently, when loading table fragments from meta store, we will first compose the `PbTableFragments`, and then convert it into `StreamJobFragments`. This is for code sharing for both etcd backend and sql backend. However, after etcd backend is deprecated, the code sharing is not required anymore. Therefore, in this PR, we change to directly compose the `StreamJobFragments` when we load from the meta store. The method `StreamJobFragments::from_protobuf` is removed, because it's not used anywhere.
<details>
</details>
> refactor(meta): use in memory struct for table fragments

- e2e_test/source_inline/commands.toml
- e2e_test/source_inline/kafka/consumer_group.slt.serial
- e2e_test/source_inline/kafka/consumer_group_non_shared.slt.serial
- e2e_test/source_inline/kafka/shared_source.slt.serial
- src/connector/src/source/base.rs
- src/connector/src/source/kafka/enumerator.rs
- src/connector/src/source/kafka/source/reader.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/source_manager.rs
- src/meta/src/stream/source_manager/worker.rs
- src/meta/src/stream/stream_manager.rs
- src/stream/src/executor/source/source_backfill_executor.rs
as title
<details>
Now Kafka consumer groups created by RisingWave Kafka source during backfill will be deleted when the backfill process is finished.
</details>
> feat: delete Kafka consumer group when source backfill is finished

- src/frontend/src/handler/drop_database.rs
- src/frontend/src/handler/drop_user.rs
To maintain consistency with pg's behavior: https://www.postgresql.org/docs/current/sql-droprole.html
<details>
</details>
> fix: add privilege check for drop user

- src/meta/src/controller/cluster.rs
`WorkerType::Meta` will be converted to 4 which should be 5.
The impact of this bug is, the worker_type of meta node will be displayed as Compactor when `select * from rw_worker_nodes`.
<details>
</details>
> fix(meta): fix incorrect displayed worker type

- src/batch/executors/src/executor/iceberg_scan.rs
- src/connector/src/connector_common/iceberg/mod.rs
- src/connector/src/source/iceberg/mod.rs
> refactor(iceberg): remove unnecessary JSON serde

- e2e_test/source_inline/kafka/alter/add_column_shared.slt
- e2e_test/source_inline/kafka/avro/alter_source.slt
- e2e_test/source_inline/kafka/protobuf/alter_source_shared.slt
- src/frontend/src/catalog/source_catalog.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_relation_info.rs
- src/frontend/src/handler/alter_source_column.rs
- src/frontend/src/handler/alter_source_with_sr.rs
No user-facing changes.
- Remove unnecessary code after we have purification.
- Add more test cases for snapshot testing.
<details>
</details>
> refactor(frontend): use purified definition for altering source

- integration_tests/debezium-mysql/docker-compose.yml
- integration_tests/debezium-postgres/docker-compose.yml
- integration_tests/debezium-sqlserver/docker-compose.yml
the origin docker repo has been removed and migrated to https://hub.docker.com/r/debezium/connect
when you pull debezium-connect, will get the following error
```
debezium Warning pull access denied for debezium-connect, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
<details>
</details>
> chore: change debezium-connect image name

- src/frontend/src/handler/show.rs
- src/frontend/src/session.rs
1. ensure the commands "show objects" and "show create object" function correctly within `search_path`, rather than use `public` schema by default.
2. make the `public` schema also managed by grant and revoke commands, which means that when creating a new non-super user, it is necessary to explicitly grant them the privilege of the `public` schema, which is also the default behavior of pg.
<details>
</details>
> fix: fix several issues about the public schema

- ci/scripts/e2e-sink-test.sh
- e2e_test/sink/postgres_sink.slt
- src/connector/src/sink/postgres.rs
- src/stream/src/common/compact_chunk.rs
Closes #20178. Also the tests were only running on my machine previously and not CI, and hence there were several regressions. I have added them to `e2e-sink-test.sh` in this PR.
<details>
</details>
> fix(connector): handle update insert and delete + subset pk + handle delete mapping

- src/connector/src/connector_common/connection.rs
- src/connector/src/lib.rs
- src/connector/src/macros.rs
use less macros, similar to #20098
<details>
</details>
> refactor(connector): use dyn for connection

- e2e_test/batch/transaction/cursor.slt
- e2e_test/subscription/check_sql_statement.slt
- src/frontend/src/binder/declare_cursor.rs
- src/frontend/src/handler/close_cursor.rs
- src/frontend/src/handler/declare_cursor.rs
- src/frontend/src/handler/explain.rs
- src/frontend/src/handler/fetch_cursor.rs
- src/frontend/src/session/cursor_manager.rs
- src/sqlparser/src/ast/statement.rs
According to Postgres' specification, `CURSOR`s are session-scoped objects and are not schema-bound. We should reject the following statement; however, we currently accept it.
```
postgres=# declare a.b cursor for select 1;
ERROR:  syntax error at or near "."
LINE 1: declare a.b cursor for select 1;
```
This PR fixes this by changing the AST type of `cursor_name` from `ObjectName` to `Ident`.
This should not be considered a breaking change, as cursors are temporary and only active within a session.
<details> …
> fix(frontend): cursor should not be schema-bound

- dashboard/package-lock.json
- dashboard/package.json
- dashboard/pages/heap_profiling.tsx
Since `crypto.randomUUID` may not exist in some browser version, we switch to use `uuid` library.
<details>
</details>
> fix(dashboard): randomUUID does not exist in some browser version

- e2e_test/source_inline/kafka/shared_source.slt.serial
- src/connector/src/source/kafka/source/reader.rs
This is a follow up of #18342.
For "there's no history data to backfill at all", we just checked `low_watermark == high_watermark`, but `start_offset == high_watermark-1` is also a case.
We may meet this case when `scan.startup.mode=latest`: https://github.com/risingwavelabs/risingwave/issues/20083#issuecomment-2609422824
<details>
</details>
> fix: finish source backfill immediately for scan.startup.mode=latest

- src/connector/src/source/filesystem/opendal_source/opendal_enumerator.rs
- src/connector/src/source/filesystem/s3/enumerator.rs
as title, we don't need to list all files in fs source enuerator
<details>
</details>
> fix: list one page in fs source executor

- src/risedevtool/src/bin/risedev-dev.rs
- src/risedevtool/src/service_config.rs
- src/risedevtool/src/task.rs
- src/risedevtool/src/util.rs
We can start e.g., Kafka and RisingWave in parallel.
`risedev d` is a highly frequent command for dev, so it's beneficial to speed it up.
https://github.com/user-attachments/assets/5c7e4e30-cc58-4d3a-8c1c-51425bbdcfb8
<details>
</details>
> feat(risedev): parallel service startup

- src/cmd_all/src/bin/risingwave.rs
- src/cmd_all/src/single_node.rs
`risedev d` listens on `127.0.0.1` while playground (single-node) listens on `0.0.0.0`. As a result, when there's a `risedev d` running in the background, starting `risedev p` can be confusing:
- meta node of `p` listens on `0.0.0.0`, which does not conflict with `risedev d` and starts successfully
- then, compute node and frontend may connect to the meta node of `d`
- no error will occur as long as the wire protocol is compatible between the build of `d` and `p`, but the behavior can be quite weird
This PR changes the gRPC listen addresses of playground …
> fix(playground): listen to `127.0.0.1` instead of `0.0.0.0` for gRPC services

- src/common/src/util/stream_graph_visitor.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/model/stream.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/stream_graph/fragment.rs
- src/meta/src/stream/stream_graph/schedule.rs
Currently we have only a `visit_stream_node` method to visit the stream node, which takes the mutable reference of `StreamNode`. However, in some scenarios we only have immutable reference to the stream node, which forces us to unnecessarily take the mutable reference of stream node.
In this PR, we change the `visit_stream_node` to `visit_stream_node_mut`, and provide a counterpart method `visit_stream_node` to only take the immutable reference of stream node. 
Besides, the two `visit_stream_node_xxx` methods are only a special case of …
> refactor: refactor series of visit_stream_node method

- .typos.toml
- proto/meta.proto
- src/common/common_service/src/observer_manager.rs
- src/compute/src/observer/observer_manager.rs
- src/frontend/src/observer/observer_manager.rs
- src/license/src/cpu.rs
- src/license/src/feature.rs
- src/license/src/lib.rs
- src/license/src/manager.rs
- src/meta/service/src/notification_service.rs
- src/meta/src/controller/cluster.rs
- src/meta/src/manager/notification.rs
- src/storage/compactor/src/compactor_observer/observer_manager.rs
- src/storage/src/hummock/observer_manager.rs
- src/tests/simulation/tests/integration_tests/license_cpu_limit.rs
- src/tests/simulation/tests/integration_tests/main.rs
In #18022, we introduced CPU core limit for license keys, where we would reject new compute nodes from joining the cluster if the limit was exceeded. This led to some confusing behavior like https://github.com/risingwavelabs/risingwave/issues/18401.
In this PR, we modify the behavior so that the license key is temporarily invalidated (thus all `Paid` features unavailable) when the CPU exceeds its limit. This requires the information of "cluster size" is broadcast to all worker nodes. For simplicity, a new notification variant of `compute_node_total_cpu_count` …
> feat(license): invalidate license when cpu exceeds limit instead of rejecting new compute nodes from joining

- src/connector/src/connector_common/connection.rs
- src/connector/src/connector_common/iceberg/mod.rs
- src/connector/src/sink/iceberg/mod.rs
- src/connector/with_options_sink.yaml
- src/connector/with_options_source.yaml
* add `glue.id` to `src/connector/src/connector_common/iceberg/mod.rs` and `src/connector/src/connector_common/connection.rs`
* allow users to optionally specify glue catalog id
<details>
</details>
> feat(iceberg): add 'glue.id' to iceberg sink config

- ci/workflows/main-cron.yml
- ci/workflows/pull-request.yml
- e2e_test/streaming/bug_fixes/issue_20342.slt
- e2e_test/streaming/bug_fixes/issue_20342.slt.part
- src/common/src/util/sort_util.rs
- src/stream/src/executor/backfill/utils.rs
Closes: https://github.com/risingwavelabs/risingwave/issues/20342
The bug is that stream_key and storage_key can mismatch for an MV, and can result in UpdateDelete + UpdateInsert pairs being split up.
```
dev=> explain create materialized view m1 as select * from t order by v2, v3;
QUERY PLAN                                                       
-----------------------------------------------------------------------------------------------------------------------
StreamMaterialize { columns: [v1, v2, v3, v4, v5], stream_key: [v1], pk_columns: [v2, v3, v1], …
```
> feat(stream): normalize unmatched updates

- src/stream/src/executor/backfill/utils.rs
Should construct with new_ops rather than old ops.
This has been included in the cherry-pick PRs for 2.1 and 2.2.
- https://github.com/risingwavelabs/risingwave/pull/20363
- https://github.com/risingwavelabs/risingwave/pull/20365
<details>
</details>
> test(stream): add unit test for normalizing unmatched updates + fix typo

- e2e_test/s3/fs_sink.py
- src/connector/src/parser/parquet_parser.rs
- src/connector/src/source/iceberg/parquet_file_handler.rs
As title.
<details>
</details>
> fix(parquet): handle nested data types correctly

- proto/stream_plan.proto
- proto/stream_service.proto
- src/ctl/src/cmd_impl/meta/cluster_info.rs
- src/meta/src/barrier/checkpoint/creating_job/status.rs
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/context/recovery.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/rpc.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/manager/metadata.rs
- src/meta/src/model/stream.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/scale.rs
- src/meta/src/stream/stream_graph/actor.rs
- src/meta/src/stream/test_fragmenter.rs
- src/stream/src/executor/actor.rs
- src/stream/src/from_proto/merge.rs
- src/stream/src/task/barrier_manager/managed_state.rs
- src/stream/src/task/stream_manager.rs
Previously we store the upstream actors information of each actor in the `upstream_actor_id` of `NodeBody::Merge`  of `StreamNode` of each `StreamActor`. This is the only difference of `StreamNode` for each actor in a same fragment. In this PR, we will change to store the upstream actor information in a separate field besides `StreamActor`.
We define type alias
```
pub type ActorUpstreams = BTreeMap<FragmentId, HashSet<ActorId>>;
pub type StreamActorWithUpstreams = (StreamActor, ActorUpstreams);
```
In code of meta node, most appearance of `StreamActor` will …
> refactor(meta): do not store upstream actors in merge node

- e2e_test/source_legacy/cdc/cdc.share_stream.slt
- e2e_test/source_legacy/cdc_inline/sql_server_cdc/sql_server_cdc.slt
- src/frontend/src/handler/create_table.rs
Fix the bug introduced in https://github.com/risingwavelabs/risingwave/pull/19354. Resolve https://github.com/risingwavelabs/risingwave/issues/20346
The bug will cause two problems:
1. Differences in the orders of rw schema and pg schema can lead to wrong default value assigned.
2. Due to `zip_eq_fast`, if the numbers of columns in rw schema and pg schema are different, panic happens.
<details>
</details>
> fix(cdc): fix wrong default column matching

- src/meta/node/src/server.rs
- src/meta/src/hummock/manager/mod.rs
I'm trying to see why meta takes >2s to start
<details>
</details>
> chore: add some log for meta startup

- src/meta/src/barrier/command.rs
- src/meta/src/barrier/context/context_impl.rs
- src/meta/src/barrier/progress.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/source_manager.rs
- src/meta/src/stream/source_manager/split_assignment.rs
- src/meta/src/stream/stream_graph/actor.rs
- src/meta/src/stream/stream_graph/fragment.rs
- src/meta/src/stream/stream_manager.rs
Previously, when we handle ddls that mutate the streaming graph, we store the all dispatcher and merge update in a single vec or map. In this PR, we change to store and pass these information in per-fragment granularity, so that we can get finer-grained information when we handle these updates.
<details>
</details>
> refactor: make actor graph builder fragment aware

- e2e_test/s3/file_sink.py
As title, the cherry-picked dependency is too long, so remove related test first.
<details>
</details>
> chore(test): fix test issue caused by no cherry picked pr in release 2.2

- src/meta/src/hummock/manager/compaction/compaction_group_schedule.rs
as title
see https://grafana.test.risingwave-cloud.xyz/a/grafana-lokiexplore-app/explore/service/benchmark-risingwave-compactor-c/logs?patterns=%5B%5D&from=2025-02-06T21:48:25.000Z&to=2025-02-06T23:20:33.000Z&var-ds=87981a45-1e5a-a649-c39e-c075d3f38b24&var-filters=namespace%7C%3D%7Cch-benchmark-pg-cdc-daily-20250206&var-filters=service_name%7C%3D%7Cbenchmark-risingwave-compactor-c&var-fields=&var-levels=&var-metadata=&var-patterns=&var-lineFilterV2=&timezone=browser&urlColumns=%5B%22Time%22,%22Line%22%5D&visualizationType=%22logs%22&displayedFields=%5B%5D&sort …
> fix(storage): reset partition_vnode_count after merge

- Cargo.lock
- src/connector/Cargo.toml
- src/connector/src/lib.rs
- src/connector/src/sink/elasticsearch_opensearch/elasticsearch_opensearch_formatter.rs
- src/connector/src/sink/encoder/template.rs
- src/connector/src/sink/formatter/mod.rs
- src/connector/src/sink/redis.rs
in this pr, we support geospatial type for redis sink
https://redis.io/glossary/geospatial-indexing/
We can use geospatial like 
```
create table t1(v1 float, v2 float,v3 varchar, v4 varchar);
CREATE SINK s1
FROM
t1 WITH (
primary_key = 'v3,v4',
connector = 'redis',
redis.url= 'redis://127.0.0.1:6379/',
)FORMAT UPSERT ENCODE TEMPLATE
(redis_value_type ='geospatial', 
longitude = 'v1', 
latitude = 'v2', 
member = 'v3',
key_format = 'abcd3:{v4}'
);
insert into t1 values(1.1, 1.1, 'test','test');
```
then we can get it in …
> feat(sink): support geospatial for redis sink

- e2e_test/source_inline/kafka/handling_mode.slt
- e2e_test/source_inline/tvf/mysql_query.slt
- e2e_test/source_inline/tvf/postgres_query.slt
- src/frontend/src/binder/expr/function/mod.rs
- src/frontend/src/expr/table_function.rs
- src/risedevtool/src/risedev_env.rs
allow `postgres_query` and `mysql_query` by reusing the params of cdc-source
part of https://github.com/risingwavelabs/risingwave/issues/18583
<details>
```
create source some_cdc_source with (
connector='postgres-cdc' / 'mysql-cdc',
hostname = 'aaa',
port = 1122,
username = 'bbb',
password = 'ccc',
database.name = 'dddd',
...
);
select * from postgres_query('some_cdc_source', 'select * from upstream table')
```
Note that we only take the (hostname, port, username, password, database_name) from the source, ignoring the …
> feat: tvf with cdc source

- src/license/src/key.rs
Based on https://github.com/risingwavelabs/risingwave/pull/20276, a license key with `Paid` tier and CPU limit of 4 is set by default for production cluster in this PR. This allow users' evaluation of paid features on a small scale.
<details>
RisingWave now includes a trial of paid features for clusters with up to 4 compute node CPUs for users to evaluate those features on a small scale. When there are more CPUs in the cluster, the trial will be unavailable for both existing and future jobs, and users will need to …
> feat(license): set default key in production to enable paid features in clusters with a maximum of 4 CPU cores

- src/stream/src/executor/backfill/snapshot_backfill/consume_upstream/executor.rs
- src/stream/src/executor/backfill/snapshot_backfill/consume_upstream/mod.rs
- src/stream/src/executor/backfill/snapshot_backfill/consume_upstream/stream.rs
- src/stream/src/executor/backfill/snapshot_backfill/consume_upstream/upstream_table_trait.rs
- src/stream/src/executor/backfill/snapshot_backfill/executor.rs
- src/stream/src/executor/backfill/snapshot_backfill/utils.rs
- src/stream/src/executor/backfill/snapshot_backfill/vnode_stream.rs
This PR is for supporting the cross db streaming query described in https://github.com/risingwavelabs/risingwave/issues/19631.
In this PR, we implement a `ConsumeUpstreamStream` to consume the upstream table epoch by epoch and yield `StreamChunk`. Inside `ConsumeUpstreamStream`, we use `VnodeStream` implemented in https://github.com/risingwavelabs/risingwave/pull/19936 to consume each vnode, and with it we are able to get the latest progress of each vnode at anytime. After it finishes one epoch, it will call `next_epoch` the next epoch and create a new …
> feat(snapshot-backfill): implement executor to consume upstream table

- scripts/install/install-risingwave.sh
We currently use `curl -s https://api.github.com/repos/risingwavelabs/risingwave/releases/latest` to get the latest released risingwave version. However, this method is very likely subject to the API rate limit restriction especially in work places sharing one single public IP. In such case, the script will not work:
```sh
$ curl -s https://api.github.com/repos/risingwavelabs/risingwave/releases/latest
{"message":"API rate limit exceeded for 101.127.221.250. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation …
```
> chore(install script): use release page redirection instead of github api to get latest version

- src/utils/pgwire/src/pg_extended.rs
- src/utils/pgwire/src/pg_protocol.rs
Refactor pgwire to allow `PgStream` to be cloned and used concurrently, so that we can use it to write messages asynchronously, typically for `Notice`s.
<details>
</details>
> refactor(pgwire): allow sharing of pg stream

- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzCdcEngineRunner.java
- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/JniDbzSourceHandler.java
- java/java-binding/src/main/java/com/risingwave/java/binding/Binding.java
- java/java-binding/src/main/java/com/risingwave/java/binding/CdcSourceChannel.java
- src/connector/src/source/cdc/source/reader.rs
- src/jni_core/src/lib.rs
- src/jni_core/src/macros.rs
Pass the ownership of Debezium CDC source message sender to the Java thread by creating a wrapper of it. Use `Cleaner` in the Java code to release memory when it's no longer needed.
Previously there was memory unsafety: https://github.com/risingwavelabs/risingwave/issues/19783.
<details>
</details>
> fix(cdc): pass ownership of source message sender to java thread

- src/connector/src/sink/file_sink/opendal_sink.rs
As titled.
Example:
```
CREATE sink test_sink as select id, name from test WITH (
connector = 's3',
) FORMAT PLAIN ENCODE JSON(
force_append_only='true', 
jsonb.handling.mode = 'dynamic'
);
```
With `dynamic`, `jsonb` column will be expressed as json object instead string in the files on s3.
<details>
</details>
> feat(dal-sink): support dynamic json handle mode

- e2e_test/source_inline/connection/ddl.slt
- e2e_test/source_inline/kafka/avro/alter_table.slt
- e2e_test/source_inline/kafka/avro/partial_schema.slt
- src/frontend/src/handler/alter_table_column.rs
- src/frontend/src/handler/create_sink.rs
- src/frontend/src/handler/create_source.rs
- src/frontend/src/handler/create_table.rs
- src/frontend/src/rpc/mod.rs
This is a follow-up of #20131:
> we can now modify this behavior simply by passing a different `SqlColumnStrategy`, which will accomplish the objective in https://github.com/risingwavelabs/risingwave/issues/12199.
This PR removes the `Reject` strategy and adds a `FollowChecked` instead, which means that we will follow the columns specified in SQL with schema check against the external system.
As a result, users can now specify the (maybe partial) schema when creating a table with a derived schema (i.e., using a schema registry). Consequently, `REFRESH SCHEMA` …
> feat(frontend): allow specifying (partial) schema when creating table with derived schema

- ci/scripts/run-e2e-test.sh
- e2e_test/commands/internal_table.mjs
- e2e_test/queryable_internal_state/group_agg.slt
- src/stream/src/common/table/state_table.rs
- src/stream/src/executor/aggregation/agg_group.rs
- src/stream/src/executor/hash_agg.rs
- src/stream/src/executor/simple_agg.rs
- src/stream/src/executor/sort_buffer.rs
- src/stream/src/from_proto/hash_agg.rs
- src/stream/src/from_proto/simple_agg.rs
cherry pick https://github.com/risingwavelabs/risingwave/pull/20435 to release-2.0
fix #20449
> cherry-pick fix(hash agg): split `AggGroup` inter states and outputs change build… to 2.0

- ci/scripts/e2e-source-test.sh
We witnessed frequent e2e source test failure. 
I’m thinking would it be caused by too high parallelism of the tests.
Since for each Kafka source, we will spawn multiple threads. Too many threads causing it failed to pull messages in time.
So decrease parallelism to see if it works.
<details>
</details>
> ci: decrease parallelism for e2e source test

- dashboard/pages/fragment_graph.tsx
- proto/meta.proto
- proto/stream_plan.proto
- proto/stream_service.proto
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_actor_infos.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_fragments.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_sinks.rs
- src/meta/service/src/stream_service.rs
- src/meta/src/barrier/checkpoint/control.rs
- src/meta/src/barrier/checkpoint/creating_job/status.rs
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/info.rs
- src/meta/src/barrier/rpc.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/controller/utils.rs
- src/meta/src/model/stream.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/scale.rs
- src/meta/src/stream/stream_graph/actor.rs
- src/meta/src/stream/stream_graph/fragment.rs
- src/meta/src/stream/test_fragmenter.rs
- src/stream/src/task/barrier_manager/managed_state.rs
- src/stream/src/task/stream_manager.rs
- src/tests/simulation/src/ctl_ext.rs
- src/tests/simulation/tests/integration_tests/scale/shared_source.rs
After https://github.com/risingwavelabs/risingwave/pull/20222, the `nodes` of each `StreamActor` in a single fragment becomes the same. Therefore, in this PR, we will deprecate the field `nodes` in `StreamActor`, and instead move the field to `Fragment` to explicitly enforce that all `StreamActor`s in the `Fragment` has the same `nodes`.
In global barrier worker, the `nodes` is stored in each `InflightFragmentInfo`, and we will use the `nodes` to create new actors when handling fragment reschedule. Note that, the `nodes` will be changed during `ReplaceTable`. …
> feat(meta): let stream actors in fragment share same stream node

- src/connector/src/sink/log_store.rs
- src/stream/src/common/log_store_impl/in_mem.rs
- src/stream/src/common/log_store_impl/kv_log_store/mod.rs
- src/stream/src/common/log_store_impl/kv_log_store/state.rs
- src/stream/src/common/log_store_impl/kv_log_store/test_utils.rs
- src/stream/src/common/log_store_impl/kv_log_store/writer.rs
- src/stream/src/executor/sink.rs
- src/stream/src/executor/sync_kv_log_store.rs
Similar to what we do in https://github.com/risingwavelabs/risingwave/pull/20218
<details>
</details>
> refactor(log-store): update log store state vnode bitmap after yield barrier

- e2e_test/iceberg/benches/predicate_pushdown.slt
- src/connector/src/sink/iceberg/mod.rs
In this pr https://github.com/risingwavelabs/risingwave/pull/20340
we support partition_by  for iceberg, But it will panic, when `partition_by` is the column name
this pr fix panic. 
But iceberg-rust doesn't support func now, so this option is currently only supported by column name
https://github.com/apache/iceberg-rust/blob/75c7e8d67942fc6e29413d8011c508bdba95abe9/crates/iceberg/src/spec/partition.rs#L537
iceberg sink
with option: partition_by  Optional. A partition operation is performed based on the value of this column.  When the user sets partition_by …
> fix(sink): fix iceberg sink partition_by panic 

- e2e_test/webhook/check_1.slt.part
- e2e_test/webhook/check_2.slt.part
- e2e_test/webhook/check_3.slt.part
- e2e_test/webhook/create_table.slt.part
- e2e_test/webhook/drop_table.slt.part
- e2e_test/webhook/sender.py
- src/frontend/src/binder/expr/mod.rs
- src/frontend/src/binder/mod.rs
- src/frontend/src/handler/create_table.rs
- src/frontend/src/webhook/mod.rs
- src/sqlparser/src/ast/ddl.rs
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/src/parser.rs
Currently, webhook strictly depends on the `secret management` feature, which is a premium feature now. However, as it's actually a common and lightweight feature, it's unreasonable to make webhook a premium feature as well. This PR allow user to use raw string as secret to do webhook verification. Example:
```
create table validate_raw_string (
data JSONB
) WITH (
connector = 'webhook',
) VALIDATE AS secure_compare(
headers->>'x-hub-signature',
'sha1=' || encode(hmac('TEST_WEBHOOK', data, 'sha1'), 'hex')
);
```
<details> …
> feat(webhook): allow webhook without secret

- src/frontend/src/handler/create_source/validate.rs
This change simply permits Kinesis sources to be created with CSV format e.g.:
```sql
FORMAT PLAIN ENCODE CSV (
without_header = 'true',
delimiter = '\t'
);
```
We've been running this patch for a while and the functionality seems to otherwise be fully implemented in RisingWave - it is just currently being gatekept by `CONNECTORS_COMPATIBLE_FORMATS`. 
Fixes #20508.
The [documentation page for Kinesis source](https://docs.risingwave.com/integrations/sources/kinesis) already suggests that CSV support is available, but it is inaccurate:
>  Protocol error: …
> feat(source): enable csv for kinesis connector

- e2e_test/batch/catalog/pg_settings.slt.part
- e2e_test/streaming/unaligned-join.slt
- src/common/src/session_config/mod.rs
- src/common/src/util/stream_graph_visitor.rs
- src/frontend/planner_test/tests/testdata/input/delta_join.yaml
- src/frontend/planner_test/tests/testdata/input/join.yaml
- src/frontend/planner_test/tests/testdata/output/delta_join.yaml
- src/frontend/planner_test/tests/testdata/output/join.yaml
- src/frontend/src/optimizer/mod.rs
- src/frontend/src/optimizer/rule/add_logstore_rule.rs
- src/frontend/src/optimizer/rule/mod.rs
Add log store rule which will add log store if `unaligned join` session variable is set. This provides a convenient way to test unaligned join. Subsequent PRs will also deal with re-aligning unaligned joins.
Unaligned Join with log store on output works best when downstream is the majority bottleneck. An example would be several cascading joins.
Instead of having to process the entire chunk, downstream can process it in smaller batches, while barriers can continue to bypass.
<details>
</details>
> feat(frontend): add AddLogStore rule

- e2e_test/source_legacy/cdc/cdc.share_stream.slt
- e2e_test/source_legacy/cdc/cdc.validate.postgres.slt
- src/frontend/src/handler/create_table.rs
- src/meta/src/rpc/ddl_controller.rs
Resolve https://github.com/risingwavelabs/risingwave/pull/19112#issuecomment-2613712659, with a bug/limitation https://github.com/risingwavelabs/risingwave/issues/20356 left.
<details>
</details>
> feat(cdc): fix generated column for table on cdc source

- e2e_test/batch/basic/dml_update.slt.part
- e2e_test/batch/types/map.slt.part
- e2e_test/batch/types/struct/struct.slt.part
- src/common/src/types/mod.rs
- src/common/src/types/struct_type.rs
- src/connector/codec/src/decoder/avro/mod.rs
- src/connector/src/parser/unified/json.rs
- src/connector/src/sink/deltalake.rs
- src/expr/impl/src/scalar/to_jsonb.rs
- src/frontend/planner_test/tests/testdata/output/array.yaml
- src/frontend/planner_test/tests/testdata/output/expr.yaml
- src/frontend/planner_test/tests/testdata/output/row_filter.yaml
- src/frontend/planner_test/tests/testdata/output/struct_query.yaml
- src/frontend/planner_test/tests/testdata/output/update.yaml
- src/frontend/src/expr/type_inference/cast.rs
- src/frontend/src/optimizer/rule/table_function_to_file_scan_rule.rs
- src/frontend/src/optimizer/rule/table_function_to_mysql_query_rule.rs
- src/frontend/src/optimizer/rule/table_function_to_postgres_query_rule.rs
- src/frontend/src/utils/data_type.rs
In Postgres, `record` type (typically created by `ROW` expression) have fields implicitly named `f1` `f2` etc. This PR makes our implementation more consistent with theirs.
<details>
</details>
> refactor(types): assign name `f{}` to unnamed fields of struct (`record`)

- src/stream/src/common/table/state_table.rs
- src/stream/src/executor/source/fs_fetch_executor.rs
- src/stream/src/executor/source/legacy_fs_source_executor.rs
- src/stream/src/executor/source/mod.rs
- src/stream/src/executor/source/source_backfill_executor.rs
- src/stream/src/executor/source/source_backfill_state_table.rs
- src/stream/src/executor/source/source_executor.rs
- src/stream/src/executor/source/state_table_handler.rs
Previously on source split change (either on explicit split change, or on split migration during scale), we write the state of target splits (splits to read after barrier) before yielding the barrier, so as to include the state of target splits in the checkpoint of the barrier. However, before the barrier, some of the target splits may be owned by other source parallelisms, and the state of the splits may be written by these other source parallelisms, and if we also write the state in the current parallelism, the splits may be written in multiple parallelisms …
> feat(source): update split state after yield barrier on split change for source executor

- e2e_test/ddl/show.slt
- e2e_test/source_legacy/basic/nosim_kafka.slt
- proto/plan_common.proto
- src/common/src/catalog/column.rs
- src/common/src/catalog/test_utils.rs
- src/connector/codec/src/decoder/avro/schema.rs
- src/connector/codec/src/decoder/protobuf/parser.rs
- src/connector/codec/tests/integration_tests/protobuf.rs
- src/connector/codec/tests/integration_tests/utils.rs
- src/connector/src/parser/debezium/simd_json_parser.rs
- src/connector/src/parser/json_parser.rs
- src/connector/src/parser/plain_parser.rs
- src/connector/src/source/manager.rs
- src/frontend/src/binder/expr/mod.rs
- src/frontend/src/binder/mod.rs
- src/frontend/src/catalog/table_catalog.rs
- src/frontend/src/handler/create_table.rs
- src/frontend/src/handler/show.rs
- src/prost/src/lib.rs
- src/storage/src/row_serde/mod.rs
The follow-up to #20496. `ColumnDesc` is simply `Field` with some extra information.
`field_descs` will be generated on the fly based on the `StructType` when it's used in `DESCRIBE`. Resolve https://github.com/risingwavelabs/risingwave/issues/17128.
<details>
</details>
> refactor(types): remove `type_name` and `field_descs` from `ColumnDesc`

- src/connector/src/sink/iceberg/mod.rs
* modified `try_matches_arrow_schema` to traverse embedded structs for validation
<details>
</details>
> feat(iceberg): add support for validating nested iceberg schemas

- e2e_test/iceberg/test_case/iceberg_engine.slt
- src/frontend/src/optimizer/rule/batch/batch_iceberg_predicate_pushdown.rs
- Only push down predicates to iceberg scan if the arguments of binary expression has the same type, because iceberg-rs doesn't full type conversion between different type of the predicate, so it would cause query failure.
- resolve https://github.com/risingwavelabs/risingwave/issues/20462 
<details>
</details>
> fix(iceberg): fix iceberg predicate pushdown

- e2e_test/source_inline/kafka/avro/ref.slt
- src/connector/src/sink/encoder/avro.rs
- src/connector/src/sink/mod.rs
This is the sink analogy for #19601 and #19746. Comparing the source and sink support:
* The sink did not support any form of `Ref` previously, while the source supported a subset (single-layer) via a hack.
* The sink unifies schema and datum handling via `MaybeData`, while the source took 2 PRs to fix separately.
* The sink uses an owned newtype `NamesRef(HashMap<Name, AvroSchema>)` while the source uses `apache_avro::schema::NamesRef<'s> = HashMap<Name, &'s AvroSchema>`. The former requires more memory while the latter requires more time to resolve every …
> feat(sink): resolve avro `Ref` to corresponding `Record` definition

- src/connector/codec/src/decoder/avro/schema.rs
- src/connector/codec/tests/integration_tests/avro.rs
- src/connector/codec/tests/integration_tests/json.rs
- src/connector/src/parser/debezium/avro_parser.rs
It used to give `record` (but not `record` inside `array`/`map`) special treatment and traverse a tree-of-tree (#19538). These are no longer needed thanks to #20497.
It also supports a top-level Avro `union` (in addition to `record`) which also maps to SQL `struct`. However the [practical e2e usage](https://www.confluent.io/blog/multiple-event-types-in-the-same-kafka-topic/#avro-unions-with-schema-references) is still blocked by avro lib bug #17632.
The ColumnIds are initialized with placeholder, as the actual assignment happens in frontend `create table` / …
> refactor(source): simplify Avro field to SQL column mapping

- src/storage/hummock_test/src/hummock_storage_tests.rs
- src/storage/src/hummock/store/local_hummock_storage.rs
- src/storage/src/memory.rs
- src/storage/src/monitor/monitored_store.rs
- src/storage/src/monitor/traced_store.rs
- src/storage/src/panic_store.rs
- src/storage/src/store.rs
- src/storage/src/store_impl.rs
- src/stream/src/common/log_store_impl/kv_log_store/state.rs
- src/stream/src/common/log_store_impl/kv_log_store/writer.rs
- src/stream/src/common/table/state_table.rs
- src/stream/src/executor/hash_join.rs
- src/stream/src/executor/now.rs
- src/stream/src/executor/sort.rs
- src/stream/src/executor/sync_kv_log_store.rs
- src/stream/src/executor/top_n/top_n_plain.rs
- src/stream/src/executor/watermark_filter.rs
- src/stream/tests/integration_tests/eowc_over_window.rs
- src/stream/tests/integration_tests/over_window.rs
Part of https://github.com/risingwavelabs/risingwave/issues/18312
In this PR, on `update_vnode_bitmap` of `LocalStateStore`, we will explicitly wait for the previous epoch to be committed, so that after `update_vnode_bitmap` returns, the local state store is ready to be read, and doesn't depend on correctly calling `try_wait_epoch` outside of it.
<details>
</details>
> feat(storage): wait committed epoch when update vnode bitmap

- java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java
- java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSinkConfig.java
- java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JdbcUtils.java
- RisingWave uses transactions (i.e. autoCommit = false) for jdbc sink, however, we haven't rollbacked the transaction before closing connection. 
- In this PR, we also provide a sink parameter `jdbc.auto.commit` to allow users to control whether to use transaction for jdbc sink.
```
CREATE SINK s_pg FROM t WITH (
connector = 'jdbc', 
jdbc.url = 'jdbc:postgresql://127.0.0.1:5432/dev?user=xxxx&password=xxxx',
table.name = 't', 
type = 'upsert', 
primary_key = 'id', 
jdbc.query.timeout = 60, 
jdbc.auto.commit=true
);
```
<details> …
> fix(connector): rollback transaction before closing connection for jdbc sink

- src/connector/src/sink/deltalake.rs
- src/connector/src/sink/elasticsearch_opensearch/opensearch.rs
- src/connector/src/sink/iceberg/mod.rs
- src/connector/src/sink/mod.rs
- src/connector/src/sink/remote.rs
- src/connector/src/sink/starrocks.rs
- src/stream/src/common/log_store_impl/kv_log_store/buffer.rs
- src/stream/src/common/log_store_impl/kv_log_store/mod.rs
- src/stream/src/common/log_store_impl/kv_log_store/reader.rs
- src/stream/src/common/log_store_impl/kv_log_store/state.rs
- src/stream/src/common/log_store_impl/kv_log_store/writer.rs
- src/stream/src/executor/sink.rs
- src/stream/src/executor/sync_kv_log_store.rs
- src/stream/src/from_proto/sink.rs
Resolve https://github.com/risingwavelabs/risingwave/issues/19337
In coordinated sinks, different parallelisms coordinate with each other by their epoch progress. More specifically, they should write the data of the same epoch simultaneously, and then commit together on the epoch, and then write the same epoch truncate offset to storage. Since different parallelisms should work on the same epoch, we need to ensure that after recovery they are initialized from the same epoch. However, in sink log store, since we only need to ensure at-least-once delivery, the …
> fix(sink): align init epoch for coordinated sinks

- src/bench/sink_bench/main.rs
- src/connector/src/sink/log_store.rs
- src/stream/src/common/log_store_impl/in_mem.rs
- src/stream/src/common/log_store_impl/kv_log_store/buffer.rs
- src/stream/src/common/log_store_impl/kv_log_store/mod.rs
- src/stream/src/common/log_store_impl/kv_log_store/reader.rs
- src/stream/src/common/log_store_impl/kv_log_store/state.rs
- src/stream/src/common/log_store_impl/kv_log_store/writer.rs
- src/stream/src/executor/sink.rs
- src/stream/src/executor/sync_kv_log_store.rs
Currently in decoupled sinks, which use KvLogStore, we handle scale in a similar mechanism to online scale in normal streaming jobs. When scale happen, the barrier with scale mutation will arrive at log writer first, and then instead of applying the scale mutation to log reader immediately, the scale mutation will be added to the buffer queue as a special item, and the reader will not apply this item until all previous items before it has been consumed.
However, this works when no sink parallelism exists in the scale. For a sink parallelism that will exit …
> fix(log-store): rebuild decoupled sink on scale to fix data loss

- src/connector/src/connector_common/common.rs
- src/connector/src/source/filesystem/s3/mod.rs
- src/connector/src/source/kafka/client_context.rs
- src/connector/with_options_sink.yaml
- src/connector/with_options_source.yaml
Previously the value was hardcoded to 10s. We make it configurable to accommodate some low provide credential case.
add with property `aws.msk.signer_timeout_sec` for AWS MSK source. This controls the timeout limit for loading AWS credentials for AWS MSK.
<details>
</details>
> feat: add aws.msk.signer_timeout_sec to config the timeout of signer

- src/stream/src/task/barrier_manager/managed_state.rs
In the event loop of local barrier manager, we need to ensure that events do not break the causal order. For example, let's say, an actor has two event, `collect barrier1` and then `collect barrier2`, each causing event of `barrier1 all collected` and `barrier2 all collected`, and then we should ensure that the local barrier manager must handle `barrier1 all collected` before `barrier2 all collected`.
In current implementation, when we poll the next barrier manager event, we will poll all ready actor events first, and apply them to the graph state, and in the …
> fix(barrier): ensure causal order in local barrier manager event

- e2e_test/streaming/asof_join.slt
- src/stream/src/executor/asof_join.rs
asof join can panic or cause downstream panic in some cases might panic when there are more than 1 identical inequality key.
IMPACT: after this PR, existing asof join can cause downstream panic or inconsistent result. But only in rare cases this can happen.
<details>
</details>
> fix(streaming): asof join can panic in some cases

- src/meta/model/src/actor.rs
- src/meta/model/src/actor_dispatcher.rs
- src/meta/model/src/fragment.rs
- src/meta/model/src/prelude.rs
- src/meta/src/backup_restore/restore_impl/v2.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/controller/scale.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/controller/utils.rs
- src/meta/src/manager/metadata.rs
- src/meta/src/stream/scale.rs
- src/meta/src/stream/source_manager.rs
- src/meta/src/stream/source_manager/split_assignment.rs
- src/meta/src/stream/stream_manager.rs
- src/storage/backup/src/meta_snapshot_v2.rs
With `FragmentRelation` table introduced, we don't have to persist the dispatcher information. Therefore, in this PR, we will deprecate the `dispatcher` table. In all places that used the `dispatcher` table, we will change to use the `FragmentRelation` table.
Previously, the `dispatcher` is used in either resolving the logical connection between fragments, or loading the existing physical dispatchers. For resolving the logical connection between fragments, we can use the `FragmentRelation` directly. For loading existing physical dispatchers, we can actually …
> refactor(meta): deprecate dispatcher table and compose dispatcher by fragment relation

- src/stream/src/executor/source/fs_fetch_executor.rs
Close https://github.com/risingwavelabs/risingwave/issues/20593
How to reproduce
```
CREATE source s1(
id int,
) WITH (
connector = 's3',
match_pattern = '*.parquet',
s3.region_name = 'custom',
s3.bucket_name = 'hummock001',
s3.credentials.access = 'hummockadmin',
s3.credentials.secret = 'hummockadmin',
s3.endpoint_url = 'http://hummock001.127.0.0.1:9301',
refresh.interval.sec = 1,
) FORMAT PLAIN ENCODE PARQUET;
create table d(id int);
create sink sink1 into d as select id from s1 with (
type = 'append-only',
force_append_only = 'true',
);
alter sink sink1 …
```
> fix(file source): clear counter `splits_on_fetch` when updating rate limit

- src/meta/src/hummock/manager/time_travel.rs
Previously the timetravel sst metadata is deleted in one query, i.e. `delete from xx where sst_id is in (...)`. However, in extremly heavy write workload, the `is in` condition can exceed the threshold 65536 and result in error: `failed to access meta store: Execution Error: encountered unexpected or invalid data: PgConnection::run(): too many arguments for query: 118133 (sqlx_postgres::connection::executor:213)`.
This PR addresses the bug by splitting the deletion into smaller batches.
<details>
</details>
> fix(meta): delete large time travel metadata in smaller batch

- proto/expr.proto
- src/expr/impl/src/scalar/test_license.rs
- src/frontend/src/binder/expr/function/builtin_scalar.rs
- src/frontend/src/expr/pure.rs
- src/frontend/src/optimizer/plan_expr_visitor/strong.rs
- src/license/src/manager.rs
Add a function `rw_license()` (returning a jsonb) to dump the license information.
If the current license is valid, the output will be like this:
```
dev=> select rw_license();
rw_license
-------------------------------------------------------------------------------------------------------------
{"cpu_core_limit": null, "exp": 9999999999, "iss": "test.risingwave.com", "sub": "rw-test", "tier": "paid"}
(1 row)
```
Otherwise, it will yield an error indicating what's going wrong (like invalid token, expired license).
~~Note that a valid license does not mean …
> feat(expr): add expression to reveal license status & content

- src/stream/src/executor/sync_kv_log_store.rs
> feat(logstore): handle paused stream

- src/stream/src/executor/sync_kv_log_store.rs
No need to iterate through the rest of the buffer after hitting a flushed item / chunk. Because the rest of the chunks should already be flushed
<details>
</details>
> refactor(stream): shortcircuit flushing chunks on barrier

- java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSinkConfig.java
- Currently, JDBC sink query timeout is 600s while socket timeout is 300s. It would cause an issue if transactions are waiting for a lock, because socket timeout just close the connect from RisingWave side, but the target database connection waiting for a lock doesn't  know it and we have no way to kill the query anymore.
- So in this PR, we reduce the query  timeout from 600s to 60s to make sure it is smaller than 300s (the socket timeout value).
- Related issue https://github.com/risingwavelabs/risingwave/issues/18372
<details> …
> fix(sink): reduce jdbc query timeout to 60s

- src/frontend/src/handler/alter_table_column.rs
- src/frontend/src/handler/mod.rs
Support handling `ALTER TABLE .. ALTER COLUMN .. <new-type>` in the frontend, as a step towards #19755.
The implementation is as simple as modifying the table definition, replanning, and replacing the table plan. However, since we verify that the data type matches the original definition (since #19828), altering the column type cannot succeed solely with the changes in this PR.
As a result, this is currently mainly for debugging purposes, i.e., there will be no need to rely on an external schema registry to test the behavior of column type change (which will …
> feat(frontend): alter column type for debugging purposes

- proto/meta.proto
- src/common/src/hash/consistent_hash/vnode_count.rs
- src/meta/model/src/fragment.rs
- src/meta/service/src/scale_service.rs
- src/meta/service/src/stream_service.rs
- src/meta/src/barrier/checkpoint/control.rs
- src/meta/src/barrier/command.rs
- src/meta/src/controller/catalog/util.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/controller/utils.rs
- src/meta/src/dashboard/mod.rs
- src/meta/src/hummock/manager/compaction/compaction_group_manager.rs
- src/meta/src/manager/metadata.rs
- src/meta/src/model/stream.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/scale.rs
- src/meta/src/stream/source_manager.rs
- src/meta/src/stream/stream_graph/actor.rs
- src/meta/src/stream/stream_graph/fragment.rs
- src/meta/src/stream/stream_graph/schedule.rs
- src/meta/src/stream/test_fragmenter.rs
- src/prost/src/lib.rs
- src/tests/simulation/src/ctl_ext.rs
- src/tests/simulation/tests/integration_tests/scale/dynamic_filter.rs
- src/tests/simulation/tests/integration_tests/scale/nexmark_q4.rs
With `fragment_relation` table introduced, the `upstream_fragment_id` in `fragment` table becomes redundant. In this PR, we will deprecate the usage on this column.
<details>
</details>
> refactor(meta): deprecate persisted fragment upstream ids

- e2e_test/source_legacy/cdc/cdc.share_stream.slt
- e2e_test/source_legacy/cdc/mysql_create.sql
- e2e_test/source_legacy/cdc/postgres_cdc.sql
- e2e_test/source_legacy/cdc_inline/sql_server_cdc/sql_server_cdc.slt
- src/frontend/src/handler/create_table.rs
From @BugenZhao:
This feature doesn’t make much sense because…
- all upstream data are already filled default value by CDC driver (if applicable)
- it’s only applicable for performing DML in our side, which might be rare in CDC table’s case
- only the most trivial expressions (that can be parsed by us) are supported, which is quite limited
Another motivation is #20625
apply #20626 in main
<details>
</details>
> feat: remove support for default column from CDC

- Cargo.lock
- Cargo.toml
- proto/catalog.proto
- proto/expr.proto
- src/expr/core/src/aggregate/user_defined.rs
- src/expr/core/src/expr/expr_udf.rs
- src/expr/core/src/sig/udf.rs
- src/expr/core/src/table_function/user_defined.rs
- src/expr/impl/src/udf/external.rs
- src/expr/impl/src/udf/mod.rs
- src/expr/impl/src/udf/python.rs
- src/expr/impl/src/udf/quickjs.rs
- src/expr/impl/src/udf/wasm.rs
- src/frontend/src/catalog/function_catalog.rs
- src/frontend/src/expr/user_defined_function.rs
- src/frontend/src/handler/create_aggregate.rs
- src/frontend/src/handler/create_function.rs
- src/frontend/src/handler/create_sql_function.rs
- src/meta/model/migration/src/lib.rs
- src/meta/model/migration/src/m20250121_085800_change_wasm_udf_identifier.rs
- src/meta/model/src/function.rs
- src/meta/src/controller/mod.rs
- src/prost/build.rs
- src/prost/src/lib.rs
This PR:
- Rename `identifier` in UDF-related structures to `name_in_runtime` to better distinguish between the name of UDF registered in RW and the name of the function to call in language runtime or remote server.
- Rename `CreateFunctionOptions` to `CreateOptions` and `UdfOptions` to `BuildOptions` to clarify the usage of them.
- Move the awareness of WASM function signature from RW to `arrow-udf-wasm`. Use the new `arrow_udf_wasm::Runtime::find_function` API in RW. https://github.com/arrow-udf/arrow-udf/pull/99
This is a preparation for WASM UDAF. …
> refactor(udf): simplify WASM UDF implementation by moving some logic to `arrow-udf-wasm`

- Cargo.lock
- src/common/Cargo.toml
- src/common/src/util/value_encoding/column_aware_row_encoding.rs
- src/common/src/util/value_encoding/error.rs
- src/storage/src/row_serde/value_serde.rs
Reimplement column-aware row encoding to make the code more clear, concise and less error-prone. See review comments for explanation of changes.
<details>
</details>
> refactor: streamline column-aware row encoding impl

- e2e_test/batch/functions/trigonometric_funcs.slt.part
- proto/expr.proto
- src/expr/impl/src/scalar/trigonometric.rs
- src/frontend/src/binder/expr/function/builtin_scalar.rs
- src/frontend/src/expr/pure.rs
- src/frontend/src/optimizer/plan_expr_visitor/strong.rs
- src/tests/regress/data/sql/float8.sql
- Support `atand` function. This implement is samilar with the PG implementation.
- Part of #8806 and #9678.
<details>
- Support `atand` and `atan2d` mathematical function.
</details>
> feat(expr): support `atand` function

- src/batch/executors/src/executor/insert.rs
- src/batch/src/executor/fast_insert.rs
- src/ctl/src/cmd_impl/hummock/list_kv.rs
- src/storage/hummock_test/benches/bench_hummock_iter.rs
- src/storage/hummock_test/src/bin/replay/replay_impl.rs
- src/storage/hummock_test/src/compactor_tests.rs
- src/storage/hummock_test/src/failpoint_tests.rs
- src/storage/hummock_test/src/hummock_read_version_tests.rs
- src/storage/hummock_test/src/hummock_storage_tests.rs
- src/storage/hummock_test/src/snapshot_tests.rs
- src/storage/hummock_test/src/state_store_tests.rs
- src/storage/hummock_test/src/sync_point_tests.rs
- src/storage/hummock_test/src/test_utils.rs
- src/storage/src/hummock/store/hummock_storage.rs
- src/storage/src/hummock/store/local_hummock_storage.rs
- src/storage/src/hummock/test_utils.rs
- src/storage/src/hummock/utils.rs
- src/storage/src/memory.rs
- src/storage/src/monitor/mod.rs
- src/storage/src/monitor/monitored_store.rs
- src/storage/src/monitor/traced_store.rs
- src/storage/src/panic_store.rs
- src/storage/src/store.rs
- src/storage/src/store_impl.rs
- src/storage/src/table/batch_table/mod.rs
- src/stream/src/common/log_store_impl/kv_log_store/reader.rs
- src/tests/compaction_test/src/compaction_test_runner.rs
Previously we have two traits to read in storage, `LocalStateStore` and `StateStoreRead`. One difference in the two traits is that, for `StateStoreRead`, we have to specify the epoch to read on, while for `LocalStateStore`, since its read methods always read from the latest snapshot, we don't need to specify the epoch.
In https://github.com/risingwavelabs/risingwave/pull/20153, we introduce a new associated type `FlushedSnapshotReader`, which also reads data from the latest snapshot. However, since it implements the `StateStoreRead` trait, when we call its …
> refactor(storage): create new read snapshot to read for StateStore trait

- e2e_test/batch/catalog/pg_settings.slt.part
- proto/stream_plan.proto
- src/common/src/session_config/mod.rs
- src/frontend/planner_test/tests/testdata/output/delta_join.yaml
- src/frontend/planner_test/tests/testdata/output/join.yaml
- src/frontend/src/optimizer/plan_node/stream_sync_log_store.rs
- src/stream/src/executor/sync_kv_log_store.rs
- src/stream/src/from_proto/sync_log_store.rs
At writer future we will sleep briefly when transitioning from clean state to flushed state. This allows us to avoid flushing, if the read side can catch up.
Clean state is when writer has no flushed items, not reading from state store.
<details>
</details>
> feat(logstore): provide more opportunities to read

- src/storage/src/hummock/utils.rs
The previous logging is really hard to read:
```
2025-03-10T09:11:13.610591123Z  WARN risingwave_storage::hummock::utils: timeout when waiting for version update info="wait_for_epoch: epoch: 8150230122037248, table_id: 78" elapsed=31.224454231s backtrace="Backtrace [{ fn: \"{async_fn#0}<risingwave_storage::hummock::utils::wait_for_epoch::{async_fn#0}::{closure_env#0}, risingwave_storage::hummock::utils::wait_for_epoch::{async_fn#0}::{closure_env#1}>\", file: \"./src/storage/src/hummock/utils.rs\", line: 639 }, { fn: \"{async_fn#0}\", file: …
```
> refactor(storage): better backtrace display in warn log for `wait_for_update`

- proto/stream_service.proto
- src/meta/src/barrier/checkpoint/control.rs
- src/meta/src/barrier/checkpoint/creating_job/mod.rs
- src/meta/src/barrier/checkpoint/creating_job/status.rs
- src/meta/src/barrier/complete_task.rs
- src/meta/src/barrier/worker.rs
- src/stream/src/executor/backfill/snapshot_backfill/executor.rs
- src/stream/src/task/barrier_manager/progress.rs
Previously in snapshot backfill, we impose back-pressure to upstream by limiting the number of pending upstream barriers. However, when we support recoverable snapshot backfill, we won't restore all previously pending upstream barriers, and then we won't be able to get the exact number of pending upstream epochs. Therefore, in this PR, we will change to limit the lag between the latest upstream epoch and the consuming epoch. When the lag exceeds a monotonically decreasing lag upper bound, we won't poll upstream to impose back-pressure to upstream.
<details> …
> feat(snapshot-backfill): impose back-pressure to upstream by epoch lag size

- proto/monitor_service.proto
- src/common/src/config.rs
- src/common/src/lib.rs
- src/common/src/operator.rs
- src/compute/src/rpc/service/monitor_service.rs
- src/config/example.toml
- src/frontend/src/handler/explain.rs
- src/frontend/src/handler/explain_analyze_stream_job.rs
- src/frontend/src/handler/mod.rs
- src/sqlparser/src/ast/analyze.rs
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/src/lib.rs
- src/sqlparser/src/parser.rs
- src/storage/compactor/src/rpc.rs
- src/stream/src/executor/monitor/in_mem_stats.rs
- src/stream/src/executor/monitor/streaming_stats.rs
- src/stream/src/executor/wrapper.rs
- src/stream/src/executor/wrapper/stream_node_metrics.rs
- src/stream/src/task/mod.rs
- src/stream/src/task/stream_manager.rs
Closes #20721 
Support explain analyze stream job. See release notes for an example.
<details>
<summary><b>DEMO</b></summary>
https://github.com/user-attachments/assets/90bde9ff-c0d3-40dd-b33f-3aab45291c67
</details>
In this PR every executor will collect profiling metrics, but only 1 set of metrics is allocated per **operator**. For instance, for hash aggregation, we could have 8 parallelism, and hence 8 executors running. But all 8 executors will share a single set of metrics, to avoid high memory consumption when actor counts are high.
When some executor …
> feat(frontend,meta,stream): explain analyze stream job

- ci/workflows/main-cron.yml
- src/meta/src/barrier/checkpoint/control.rs
- src/meta/src/barrier/checkpoint/creating_job/barrier_control.rs
- src/meta/src/barrier/checkpoint/creating_job/mod.rs
- src/meta/src/barrier/checkpoint/recovery.rs
- src/meta/src/barrier/manager.rs
- src/meta/src/barrier/rpc.rs
- src/meta/src/barrier/utils.rs
- src/meta/src/barrier/worker.rs
- src/tests/simulation/tests/integration_tests/recovery/background_ddl.rs
Previously, we only support the logical error between databases. The logical error is sent back to meta node as a separate control stream response variant. However, for worker node failure, we haven't handled the database isolation properly yet. On worker node failure, we will either ignore the failure, when no database is waiting on a response from the failed worker node, or else trigger global recovery. Moreover, to simplify the handling logic, currently when handling inject barrier request, we will send the request to all existing worker nodes, even there …
> feat(meta): isolate database worker node failure

- src/sqlparser/src/ast/legacy_source.rs
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/tests/testdata/create.yaml
- src/utils/pgwire/src/pg_protocol.rs
See #20713 for how many times we were incautious on this. This PR adds an additional check for `create table | source` before the invalid SQL is persisted in meta catalog (and fixes spotted existing issues).
If the invalid SQL was persisted in meta catalog, the corresponding `table | source` would not be able to `alter`:
```
1: unable to parse definition sql
2: sql parser error: syntax error (...details...)
```
With this check, developers working on new syntax extension would …
> fix(sqlparser): enforce `Display` of `create table | source` to be valid SQL

- src/frontend/src/handler/alter_table_column.rs
When generating `ColIndexMapping` (which is used to map the output of the new table job to make the schema compatible with existing downstream jobs), also check whether the data type matches. If not, treat it as a new column to avoid runtime schema mismatch.
Note that we don't currently have this issue because the `ColumnIdGenerator` has already checked the data type (https://github.com/risingwavelabs/risingwave/pull/19828) when matching the column IDs for the altered table.
However, in following PRs (like …
> refactor(frontend):  also check column data type when generating column index mapping for replacing table

- e2e_test/ddl/not_null.slt
- e2e_test/source_legacy/cdc/cdc.share_stream.slt
- e2e_test/source_legacy/cdc/cdc.validate.postgres.slt
- src/common/src/catalog/column.rs
- src/frontend/src/catalog/system_catalog/information_schema/columns.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_columns.rs
- src/frontend/src/handler/create_table.rs
- src/frontend/src/optimizer/mod.rs
- src/frontend/src/optimizer/plan_node/stream_filter.rs
Followup of https://github.com/risingwavelabs/risingwave/pull/20611. For streaming input, for example, kafka input, or Sink into input, we drop the row violating NOT NULL constraint. And we ban NOT NULL in cdc tables.
<details>
Support NOT NULL in table schema.
For BatchInsert/Update, RW will throw an error for rows with NULL.
For Streaming, RW will ignore the rows with NULL silently.
> feat(stream): support not null in stream

- Cargo.lock
- src/compute/Cargo.toml
- src/compute/src/rpc/service/monitor_service.rs
- src/stream/src/executor/sink.rs
- src/utils/workspace-config/Cargo.toml
Seems that we will still enable verbose instrument await in release mode, so using verbose_instrument_await does not help. Changed to use `regex` to remove the false positive `!!!`.
Previously was 
```
[Actor 9]
Actor 9: `CREATE SINK s FROM t WITH (connector = 'blackhole')` [10.429s]
Epoch 8172558712635392 [422.406ms]
Sink 900000001 [423.052ms]
consume_log (sink_id 7) [!!! 10.426s]
log_reader_next_item [423.059ms]
StreamScan 90000272A [423.059ms]
Merge 900000000 [422.591ms]
```
now is
```
[Actor 10]
Actor 10: `CREATE SINK s FROM t WITH (connector = …
```
> chore: remove false positive blocking consume_log from await-tree output

- src/meta/src/barrier/checkpoint/control.rs
- src/meta/src/barrier/checkpoint/recovery.rs
- src/meta/src/barrier/rpc.rs
- src/meta/src/barrier/worker.rs
In https://github.com/risingwavelabs/risingwave/pull/20862, in global recovery, we have a special logic to early suspend the databases that have actors to be run on failed worker node. However, if some databases failed to collect the first barrier, we will still fail the global recovery and retry everything, and then some problematic databases may block the global recovery.
In this PR, we will remove the special early suspend logic, and then handle any failure happened when collecting the initial barrier in a general manner, and suspend any failed databases. …
> fix(meta): isolate database logical error in global recovery

- e2e_test/source_inline/kafka/avro/alter_table.slt
- proto/plan_common.proto
- src/common/src/lib.rs
- src/common/src/types/mod.rs
- src/frontend/src/handler/create_mv.rs
- src/frontend/src/handler/create_source.rs
- src/frontend/src/handler/create_source/external_schema/nexmark.rs
- src/frontend/src/handler/create_table.rs
- src/frontend/src/handler/create_table/col_id_gen.rs
- src/frontend/src/handler/create_table_as.rs
Update `ColumnIdGenerator` to also generate id for nested fields (#20620) by traversing the data type of the columns.
When creating a new `ColumnIdGenerator` from an existing table, we traverse the fields of each column recursively and collect them into a map indexed by their access **path**s. When generating ids, we check against the map to decide whether a change is considered compatible and whether there's an ID to reuse.
To reviewers: don't be scared as half of lines are unit tests. 😄
<details>
</details>
> feat(frontend): generate column id to struct fields

- src/common/benches/bench_column_aware_row_encoding.rs
- src/common/src/util/value_encoding/column_aware_row_encoding.rs
- src/storage/src/row_serde/value_serde.rs
Follow-up of #20563.
If the `ids` field of a struct type is set, we dispatch to a new encoding that recursively uses column-aware encoding for struct types. In this way, the IDs of nested fields are encoded, enabling compatibility during schema change.
Several TODOs related to performance remain in the code, which will be addressed with some refactoring in future PRs. See micro-benchmark results in https://github.com/risingwavelabs/risingwave/pull/20604#issuecomment-2731805679.
<details>
</details>
> feat: recursively use col-aware encoding for structs

- ci/scripts/run-backfill-tests.sh
- e2e_test/backfill/cross_db/cross_db_mv.slt
- src/frontend/src/optimizer/plan_node/utils.rs
- src/meta/src/barrier/worker.rs
- src/prost/src/lib.rs
- src/stream/src/executor/backfill/snapshot_backfill/executor.rs
- src/stream/src/executor/backfill/snapshot_backfill/state.rs
Hits the following panic for cross db snapshot backfill after recovery.
```
thread 'rw-streaming' panicked at /Users/william/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/itertools-0.14.0/src/zip_eq_impl.rs:50:17:
itertools: .zip_eq() reached end of one iterator before the other
```
We used the wrong column size to resolve the consume progress from the progress rows loaded from progress state table. The bug will be reproduced when backfill recover from half of an epoch.
Add an e2e test to cover the case. Before this PR the e2e will failed with the …
> fix(snapshot-backfill): fix panic in cross db snapshot backfill recovery

- src/frontend/src/handler/create_source.rs
- src/frontend/src/handler/create_source/external_schema.rs
- src/frontend/src/handler/create_source/external_schema/protobuf.rs
- src/sqlparser/src/ast/mod.rs
|`legacy_source::ProtobufSchema`|`StreamSourceInfo`|
|-|-|
|message_name|proto_message_name|
|row_schema_location|row_schema_location|
|use_schema_registry|use_schema_registry|
||name_strategy|
||key_message_name|
||format|
||...|
As a result, `name_strategy` was not passed down compared to `extract_avro_table_schema`, and `format` was hard-coded to `Plain` despite it does not affect schema derivation.
Note:
* Name strategy is still considered unsupported.
* It is mainly used together with multiple event types within a single topic, which is not well …
> fix(frontend): `encode protobuf` shall pass options without `legacy_source::ProtobufSchema`

- src/frontend/src/handler/create_source.rs
- src/frontend/src/handler/create_source/external_schema.rs
- src/frontend/src/handler/create_source/external_schema/protobuf.rs
- src/sqlparser/src/ast/mod.rs
Cherry picking \#20949 onto branch release-2.2,
This PR/issue was created to resolve #20979 by cherry-pick action from commit 3ce8ec6624d084ce85d7c49aa42011af32d13917.,
> fix(frontend): `encode protobuf` shall pass options without `legacy_source::ProtobufSchema` (#20949)

- ci/workflows/main-cron.yml
It appears that recent `main-cron` runs failed only because of timeout or spot instance preemptions. Let's apply the same tech as #20727 to `main-cron` to reduce the overall run time, so that it can succeed in a higher chance.
----
Looks great! Runtime has been significantly reduced in https://buildkite.com/risingwavelabs/main-cron/builds/4601:
All failures are because of absence of #21025.
<details>
</details>
> ci: also use buildkite job parallelism in main-cron

- ci/docker-compose.yml
- e2e_test/source_inline/kafka/alter/add_column_shared.slt
- e2e_test/source_legacy/cdc/cdc.check.slt
- e2e_test/source_legacy/cdc/cdc.check_new_rows.slt
- e2e_test/source_legacy/cdc/cdc.load.slt
- e2e_test/source_legacy/cdc/cdc.share_stream.slt
- e2e_test/source_legacy/cdc/postgres_cdc.sql
- e2e_test/source_legacy/cdc/postgres_cdc_insert.sql
- src/common/src/types/from_sql.rs
- src/common/src/types/jsonb.rs
- src/connector/src/connector_common/postgres.rs
- src/connector/src/sink/postgres.rs
- src/connector/src/source/cdc/external/sql_server.rs
As titled
<details>
</details>
> feat(cdc): support mapping json of pg to jsonb in rw in pg-cdc

- .github/workflows/update-pr-template-by-version.yml
It seems we were not using peter-evans/create-pull-request@v7 correctly.
https://github.com/peter-evans/create-pull-request/blob/v7/README.md
> How the action behaves:
> * If there are changes (i.e. a diff exists with the checked-out base branch), the changes will be pushed to a new branch and a pull request created.
That is, when the action executes, `main` (the `base`) shall be checked out and the action will create/update `update-pr-template-${{ env.version }}` (the `branch`). If we already pushed the `branch` to remote, it will be recognized by the action …
> fix(action): update-pr-template-by-version auto branch management

- src/meta/src/barrier/checkpoint/control.rs
- src/meta/src/barrier/checkpoint/creating_job/barrier_control.rs
- src/meta/src/barrier/checkpoint/creating_job/mod.rs
- src/meta/src/barrier/checkpoint/creating_job/status.rs
- src/meta/src/barrier/checkpoint/recovery.rs
- src/meta/src/barrier/checkpoint/state.rs
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/info.rs
- src/meta/src/barrier/progress.rs
- src/meta/src/barrier/rpc.rs
- src/meta/src/barrier/worker.rs
- src/stream/src/executor/backfill/snapshot_backfill/executor.rs
- src/stream/src/task/barrier_manager/progress.rs
Before the [PR](https://github.com/risingwavelabs/risingwave/pull/20848) to support recoverable snapshot backfill, we will refine the current logic of tracking snapshot backfill in global barrier manager, so that we can simplify the implementation in the subsequent PR.
We will make the following changes:
- Previously, we store initial mutation and new actors to create in the tracker of snapshot backfill(`CreatingStreamingJobControl`), and take them out to include it when later injecting the first barrier. In this PR we will change to injecting the first …
> refactor(snapshot-backfill): refine snapshot backfill tracking logic in meta

- src/connector/src/sink/big_query.rs
- src/connector/src/sink/boxed.rs
- src/connector/src/sink/decouple_checkpoint_log_sink.rs
- src/connector/src/sink/file_sink/batching_log_sink.rs
- src/connector/src/sink/mod.rs
- src/connector/src/sink/postgres.rs
- src/connector/src/sink/remote.rs
- src/connector/src/sink/test_sink.rs
- src/connector/src/sink/trivial.rs
- src/connector/src/sink/writer.rs
- src/tests/simulation/tests/integration_tests/sink/utils.rs
Previously in deterministic sink test, we allow registering the customized logic of `SinkWriter`. However, currently have a more general `LogSinker` trait. In this PR, we will support registering the customized logic of this more general `LogSinker`.
Definition of the `consume_log_and_sink` of `LogSinker` is slightly changed to simplify the support for type erasion in the dynamic dispatch. Previously we impl `SinkLogReader` for `LogReader`, and pass `&mut impl SinkLogReader` to `consume_log_and_sink`. In this PR, will change to impl `SinkLogReader` for `&mut …
> feat(sink): support registering the more general dyn LogSinker in test

- src/meta/src/barrier/checkpoint/control.rs
- src/meta/src/barrier/checkpoint/creating_job/mod.rs
- src/meta/src/barrier/checkpoint/recovery.rs
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/context/context_impl.rs
- src/meta/src/barrier/context/recovery.rs
- src/meta/src/barrier/edge_builder.rs
- src/meta/src/barrier/info.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/rpc.rs
- src/meta/src/barrier/worker.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/controller/utils.rs
- src/meta/src/model/stream.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/source_manager.rs
- src/meta/src/stream/source_manager/split_assignment.rs
- src/meta/src/stream/stream_graph/actor.rs
- src/meta/src/stream/stream_graph/id.rs
- src/meta/src/stream/stream_manager.rs
- src/meta/src/stream/test_fragmenter.rs
After we deprecated the dispatcher table in https://github.com/risingwavelabs/risingwave/pull/20541, we will not persist the dispatcher info, and instead, we recompose the dispatcher and upstreams actor information of each actor by the newly introduced `FragmentRelation`. By now, we have two implementations of building the edges between actors, one in the original `FragmentActorBuilder`, and the other in global barrier worker for recovery. 
Having two implementations is redundant, and the implementation in global barrier worker during recovery is inevitable. …
> feat(meta): compose fragment dispatcher in barrier workers

- src/meta/src/hummock/manager/checkpoint.rs
- src/meta/src/hummock/manager/time_travel.rs
- src/meta/src/hummock/manager/versioning.rs
- src/storage/backup/src/lib.rs
- src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
- src/storage/hummock_sdk/src/time_travel.rs
- src/storage/hummock_sdk/src/version.rs
(cherry picked from commit 1acd08c0928f3d35b0f94cada03ba5bd66b825bd)
cherry pick
close #21104
<details>
</details>
> refactor(meta): exclude table change log from time travel metadata (#20948)

- Cargo.lock
- Cargo.toml
foyer side changes:
- Fix blob/region split condition calculation error.
- Add ut for the corner case.
- Refine splitter code.
- Fix direct fs error log.
https://github.com/foyer-rs/foyer/pull/912
https://github.com/foyer-rs/foyer/issues/905
https://github.com/risingwavelabs/risingwave/pull/21116
close https://github.com/risingwavelabs/risingwave/issues/21157
<details>
</details>
> fix(foyer): fix foyer split condition calculation error

- Cargo.lock
- src/connector/Cargo.toml
- src/connector/src/sink/mongodb.rs
Addresses the following:
* #19326
* #19725
Dependabot fails to create the PR because `tokio-runtime` feature is not present in `mongodb >= 3`.
As shown by the `Cargo.lock` diff, this also helps us to drop a lot of old indirect dependencies in addition to `derivative` and `idna`.
Noticeable items in release notes from 2.8.2 to 3.2.3:
* v3.1.0: Added support for MongoDB 8.0 (released Oct 2024)
* v3.2.0: Upcoming v3.3.0 will drop support for MongoDB 4.0 (released Jun 2018 and reached EOL Apr 2022)
<details> …
> chore(deps): Bump mongodb from 2 to 3

- e2e_test/streaming/unaligned-join.slt
- src/common/src/session_config/mod.rs
- src/frontend/planner_test/tests/testdata/output/delta_join.yaml
- src/frontend/planner_test/tests/testdata/output/join.yaml
- src/stream/src/common/log_store_impl/kv_log_store/reader.rs
- src/stream/src/common/log_store_impl/kv_log_store/state.rs
- src/stream/src/common/log_store_impl/kv_log_store/test_utils.rs
- src/stream/src/executor/sync_kv_log_store.rs
- src/stream/src/from_proto/sync_log_store.rs
If read size is unbounded, we can end up reading a really large chunk, and lead to barrier latency spike, if it cannot be processed next barrier.
We also only pause on ckpt barrier, because if we pause on chunk buffer full, the state will transition to the read state immediately, and after polling, the chunk buffer will have free space again, and we resume immediately. After that, the state transitions back to the write state, and the whole cycle repeats. In normal circumstances this is fine. But if there's high write pressure, it will backpressure the write …
> feat(stream): limit sync log store flushed item read size + only pause on checkpoint barrier

- proto/monitor_service.proto
- src/common/metrics/src/monitor/in_mem.rs
- src/common/src/operator.rs
- src/compute/src/rpc/service/monitor_service.rs
- src/frontend/src/handler/explain_analyze_stream_job.rs
- src/stream/src/executor/monitor/profiling_stats.rs
- src/stream/src/executor/monitor/streaming_stats.rs
- src/stream/src/executor/wrapper.rs
- src/stream/src/executor/wrapper/stream_node_metrics.rs
- src/stream/src/task/stream_manager.rs
This is done to avoid GC and it avoids synchronization between actors due to them updating the same metric.
It allows us to track metrics at a more granular level as well: We can look at min, max, avg for each metric, and identify the slowest executor for a given operator.
The trade-off is that more memory is utilized per executor. But the memory used per executor is very little. Each metric occupies 8 bytes of memory, with the `Arc` pointer, that's another 8 bytes. Considering the entry in the hash map and the value stored, we …
> refactor(frontend,stream): store metrics at an executor level rather than operator level

- .github/workflows/cherry-pick-to-release-branch.yml
Instruct developers to use `need-cherry-pick-since-release-xx`.
<details>
</details>
> chore(ci): deprecate `cherry-pick-to-release` in favor of `since`

- src/compute/src/rpc/service/exchange_service.rs
- src/stream/src/executor/dispatch.rs
- src/stream/src/executor/exchange/output.rs
- src/stream/src/executor/integration_tests.rs
Currently, the logic of `RemoteOutput` and `LocalOutput` is basically the same, except that
- the instrument await tree message is different
- remote output calls `chunk.compact()` for `StreamChunk` before adding to `Sender`.
In this PR, we will unify the two `Output`s. The difference in instrument await can be unified without much concern. For calling `chunk.compact()`, we delay calling it in the handler of exchange service.
<details>
</details>
> refactor(stream): unify remote and local output

- src/stream/src/executor/chain.rs
- src/stream/src/executor/dispatch.rs
- src/stream/src/executor/exchange/input.rs
- src/stream/src/executor/integration_tests.rs
- src/stream/src/executor/merge.rs
- src/stream/src/executor/receiver.rs
- src/stream/src/executor/values.rs
- src/stream/src/from_proto/merge.rs
- src/stream/src/task/barrier_manager.rs
- src/stream/src/task/barrier_manager/managed_state.rs
- src/stream/src/task/stream_manager.rs
Currently when we spawn an actor, we pass two shared structs actor, `SharedContext` and `LocalBarrierManager`. The lifecycle of the two structs is basically the same: they are bind to a database, and get created along with having a new running database, and get cleared when the database is reset or global recovery is triggered. 
Previously we store the `SharedContext` separately to `DatabaseManagedBarrierState`, while the `LocalBarrierManager` is stored in `DatabaseManagedBarrierState`. This is because, `SharedContext` is used to …
> refactor(stream): store shared context in local barrier manager

- src/storage/hummock_test/src/bin/replay/replay_impl.rs
- src/storage/hummock_test/src/hummock_storage_tests.rs
- src/storage/src/hummock/mod.rs
- src/storage/src/hummock/shared_buffer/shared_buffer_batch.rs
- src/storage/src/hummock/store/hummock_storage.rs
- src/storage/src/hummock/store/local_hummock_storage.rs
- src/storage/src/hummock/store/version.rs
- src/storage/src/hummock/test_utils.rs
- src/storage/src/hummock/utils.rs
- src/storage/src/memory.rs
- src/storage/src/monitor/monitored_store.rs
- src/storage/src/monitor/traced_store.rs
- src/storage/src/panic_store.rs
- src/storage/src/store.rs
- src/storage/src/store_impl.rs
- src/storage/src/table/batch_table/mod.rs
- src/stream/src/common/table/state_table.rs
Currently we have `get` method in `LocalStateStore`, and `get` and `get_keyed_row` in `StateStoreRead`, which is somehow verbose and duplicated. Besides, for these methods, in most usages, we won't use the returned `Bytes` value directly, and instead deserialize the `&[u8]` of it, which makes the memory allocation and clone to construct the `Bytes` unnecessary.
For these reasons, in this PR, we will extract the common `StateStoreGet` trait, so that we won't have two traits for get related methods. Besides, instead of having `get` or `get_keyed_row` method to …
> refactor(storage): unify state store trait get method

- e2e_test/batch/catalog/pg_settings.slt.part
- src/common/src/session_config/mod.rs
- src/frontend/planner_test/tests/testdata/input/join.yaml
- src/frontend/planner_test/tests/testdata/output/join.yaml
- src/frontend/src/optimizer/plan_node/logical_join.rs
We have a known issue #20028  that building rows into arrays, especially certain data types, this building process takes quite some time. Filtering unnecessary rows earlier in the join can reduce the cost.
Apart from building rows into arrays, materializing possibly many rows only to get them filtered in the next executor is just wasteful.
However, it could be generally hard to decide which one is better, as the existing comment suggest that
```
// We do so as the filter operator can apply the non-equal condition batch-wise (vectorized)
// as opposed to the …
```
> feat: allow user to force filter pushed into join in streaming query

- .github/workflows/run-main-cron.yml
Label `ci/main-cron/run-all` to run main-cron test for cherry-pick PRs
<details>
</details>
> ci: label ci/main-cron/run-all for cherry-pick PRs

- Cargo.lock
- src/ctl/Cargo.toml
- src/ctl/src/cmd_impl/await_tree.rs
See https://github.com/risingwavelabs/rw-diagnose-tools/compare/main%40%7B1day%7D...main for more impl information.
This PR makes some changes:
1. Add another rule to detect actors blocked by IO operations, such as `store_flush` and `store_get`
2. Refactor the code, place output part (`println`) in riseclt instead of `rw-diagnose-tools`.
3. Support analyze await tree dump file from meta dashboard, the format of which is slightly different from the format of dump file by risectl.
<details>
</details>
> feat(ctl): add an IO-bound rule for await tree analyze

- proto/stream_plan.proto
- proto/stream_service.proto
- src/meta/src/barrier/checkpoint/control.rs
- src/meta/src/barrier/checkpoint/creating_job/mod.rs
- src/meta/src/barrier/checkpoint/recovery.rs
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/edge_builder.rs
- src/meta/src/barrier/info.rs
- src/meta/src/barrier/rpc.rs
- src/meta/src/barrier/worker.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/model/stream.rs
- src/stream/src/executor/dispatch.rs
- src/stream/src/executor/exchange/input.rs
- src/stream/src/executor/merge.rs
- src/stream/src/executor/receiver.rs
- src/stream/src/from_proto/merge.rs
- src/stream/src/task/barrier_manager.rs
- src/stream/src/task/barrier_manager/managed_state.rs
- src/stream/src/task/mod.rs
Previously we broadcast the `ActorInfo` of globally all running actors to the `SharedContext` of each CN, so that the `DispatchExecutor` and `MergeExecutor` can get the host of downstream or upstream actors to establish the exchange connection. 
In https://github.com/risingwavelabs/risingwave/pull/21256, we already unified remote and local output so that the `DispatchExecutor` won't need the `ActorInfo` of downstream actor. In this PR, instead of only providing with upstream actor_ids, we will change to provide the upstream …
> refactor(stream): do not broadcast actor info in shared context

- ci/workflows/main-cron.yml
The test framework for arrangement backfill background_ddl has a number of bugs, and should be overhauled. Ban it for now in v2.2 to avoid blocking release
https://github.com/risingwavelabs/risingwave/issues/21325
<details>
</details>
> chore(ci): disable arrangement backfill background_ddl test

- proto/connector_service.proto
- src/connector/src/sink/coordinate.rs
- src/meta/src/manager/sink_coordination/coordinator_worker.rs
- src/meta/src/manager/sink_coordination/handle.rs
- src/meta/src/manager/sink_coordination/manager.rs
- src/rpc_client/src/sink_coordinate_client.rs
- src/stream/src/common/log_store_impl/kv_log_store/mod.rs
- src/stream/src/common/log_store_impl/kv_log_store/reader.rs
- src/stream/src/common/log_store_impl/kv_log_store/state.rs
- src/stream/src/common/log_store_impl/kv_log_store/writer.rs
- src/stream/src/from_proto/sink.rs
resolve https://github.com/risingwavelabs/risingwave/issues/21094
For coordinated log sinker, if the `start_epoch` in `StartResponse` is `None`, it will call `log_reader.start_from(None)`, and then peek the first item to get the first epoch. It will send an `AlignInitialEpochRequest` with this `first_epoch` and wait for the `AlignInitialEpochResponse` to get the `aligned_initial_epoch`. If the `aligned_initial_epoch` is later than the `first_epoch`, it will keep calling `next_item`, until the epoch reaches `aligned_initial_epoch`, …
> feat(sink): skip some epoch items to align initial coordinate epoch

- proto/connector_service.proto
- src/connector/src/sink/coordinate.rs
- src/connector/src/sink/test_sink.rs
- src/connector/src/source/test_source.rs
- src/meta/src/manager/sink_coordination/coordinator_worker.rs
- src/meta/src/manager/sink_coordination/handle.rs
- src/meta/src/manager/sink_coordination/manager.rs
- src/rpc_client/src/sink_coordinate_client.rs
- src/stream/src/common/log_store_impl/kv_log_store/mod.rs
- src/stream/src/common/log_store_impl/kv_log_store/reader.rs
- src/stream/src/common/log_store_impl/kv_log_store/state.rs
- src/stream/src/common/log_store_impl/kv_log_store/writer.rs
- src/stream/src/from_proto/sink.rs
- src/tests/simulation/tests/integration_tests/sink/basic.rs
- src/tests/simulation/tests/integration_tests/sink/err_isolation.rs
- src/tests/simulation/tests/integration_tests/sink/rate_limit.rs
- src/tests/simulation/tests/integration_tests/sink/recovery.rs
- src/tests/simulation/tests/integration_tests/sink/scale.rs
- src/tests/simulation/tests/integration_tests/sink/utils.rs
Add madsim test for coordinated sink. Existing tests is fully reused. 
For coordinated sink, the sink writers write data to a staging store with a handle id, and include the handle id as the sink metadata. When coordinator commits, it resolves the handle ids from sink metadata, retrieves staging data from staging store, and then add the staging data to the global store.
<details>
</details>
> feat(sink): add madsim tests for coordinated sink

- .github/workflows/run-main-cron.yml
cherry-pick https://github.com/risingwavelabs/risingwave/pull/21306
<details>
</details>
> cherry-pick ci: label ci/main-cron/run-all for cherry-pick PRs (#21306)

- ci/scripts/e2e-test-serial.sh
- e2e_test/release_mode_only/stack_overflow_17342.slt
See https://github.com/risingwavelabs/risingwave/issues/21355#issuecomment-2806876248
future work: #21427
<details>
</details>
> test: run fe stack overflow test only in release mode

- src/stream/src/executor/source/fs_fetch_executor.rs
cherry pick https://github.com/risingwavelabs/risingwave/pull/21416/files into release-2.3
<details>
</details>
> fix(source): handling the case of reading empty files 

- src/frontend/src/optimizer/plan_node/logical_join.rs
related: https://github.com/risingwavelabs/risingwave/issues/21355#issuecomment-2808083547
by returning PlanRef in function calls directly. Otherwise, `LogicalJoin::to_stream` needs to allocate stack memory for these temporary variables.
`LogicalJoin::to_stream` is somehow an important path (especially in deep plan), so it may worth the micro optimization
<details>
</details>
> refactor(frontend): reduce memory usage of `LogicalJoin::to_stream`

- risedev
By ignoring `SIGINT` in the `risedev` wrapper, `cargo-make` will also inherit to ignore it, preventing it from being killed when users send <kbd>Ctrl-C</kbd> to the `psql` shell.
Full explanation: https://www.notion.so/risingwave-labs/Story-on-CI-Graceful-Cancellation-1d7f0d69cb76803d900bd1512bf8b479?pvs=4#1d7f0d69cb7680fd8e62dacb796ff9c5
<details>
</details>
> fix(risedev): workaround ctrl-c handling for `risedev psql`

- ci/scripts/e2e-test-serial.sh
- e2e_test/streaming/bug_fixes/stack_overflow_17342.slt
Reverts risingwavelabs/risingwave#21424
https://github.com/risingwavelabs/risingwave/pull/21424#issuecomment-2812700084
Although I think if the test fail in dev mode, it's a not big deal. But this might be a good way to track increased memory usage in frontend. (until we cannot manage it...)
related #21355
> revert: "test: run fe stack overflow test only in release mode"

- ci/scripts/gen-integration-test-yaml.py
- ci/workflows/docker-arm-fast.yml
- ci/workflows/docker.yml
- ci/workflows/integration-tests.yml
- ci/workflows/main-cron-bisect.yml
- ci/workflows/main-cron.yml
- ci/workflows/pull-request.yml
It's observed that `agent_lost` is not retried in recent main-cron runs (https://buildkite.com/risingwavelabs/main-cron/builds/4973#019653ee-6c34-45fc-8f1b-41218534b599).
According to the doc (https://buildkite.com/resources/changelog/193-signal-and-signal-reason-in-automatic-retry-rules/), we may also include `exit_status: -1` as a retry condition.
<details>
</details>
> chore(ci): add `exit_status: -1` as buildkite auto-retry condition

- src/meta/src/barrier/command.rs
- src/stream/src/executor/dispatch.rs
- src/stream/src/executor/exchange/input.rs
- src/stream/src/executor/exchange/output.rs
- src/stream/src/executor/exchange/permit.rs
- src/stream/src/executor/integration_tests.rs
- src/stream/src/executor/merge.rs
- src/stream/src/executor/receiver.rs
- src/stream/src/from_proto/merge.rs
- src/stream/src/task/barrier_manager.rs
- src/stream/src/task/barrier_manager/managed_state.rs
- src/stream/src/task/mod.rs
- src/stream/src/task/stream_manager.rs
Previously, upstream and downstream actors create exchange channel via `SharedContext`, which is shared via `Arc<Mutex<..>>` and served as a buffer to hold the pending channel tx or rx. It works well in the current scenario, where the upstream and downstream actors are included in a same checkpoint and requires no failure isolation. However, to support partial checkpoint on jobs with streaming dependencies, we will have to isolate the failure between upstream and downstream actors if they are from different streaming jobs, and the current mechanism using …
> feat(stream): actor create exchange via channel

- src/expr/impl/src/aggregate/approx_count_distinct/append_only.rs
- src/expr/impl/src/aggregate/approx_count_distinct/mod.rs
- src/expr/impl/src/aggregate/approx_count_distinct/updatable.rs
The PR replaces the base-2 logarithm used in the linear-counting branch with the natural logarithm. In the original HyperLogLog paper the bias-correction for small cardinalities is `E = m × ln(m / V)` where V is the number of zero registers. Using log₂ instead of ln multiplies the estimate by 1/ln 2 ≈ 1.44. Consequently every time the algorithm fell into the “small-range” path (roughly n ≲ 2.5 m, i.e. < 163 840 for m = 65 536) it over-estimated the true cardinality by about 44 %. That matches the 40 %-plus inflation we observed around 20 000 distinct values. …
> fix(agg): fix the error of append-only approx_count_distinct

- src/meta/src/barrier/worker.rs
Currently, when global recovery is not triggered, we won't retry creating control stream to failed CN worker in most scenarios. We only try recreating the stream on per-database failure recovery. However, we don't retry on all failed CN, but only for CN on which there are some existing jobs of the recovering database running.
As a result, when a worker without any job running gets disconnected on its control stream, any per-database failure recovery won't retry creating control stream to the worker, until a global recovery is triggered. When this happens, any …
> fix(meta): try reconnect to worker node on create new streaming job

- ci/scripts/e2e-sink-test.sh
- e2e_test/sink/postgres_sink.slt
- e2e_test/sink/remote/jdbc.check.pg.slt
- src/config/ci-jdbc-to-native.toml
- src/connector/src/sink/postgres.rs
- src/risedevtool/src/task/postgres_service.rs
- src/stream/src/from_proto/sink.rs
It didn't switch the connector type previously. Closes https://github.com/risingwavelabs/risingwave/issues/21525.
We also fix the duplicate entry error for `on conflict do update`, by just batching at most one row at a time.
<details>
</details>
> fix(stream): switch `jdbc_pg_to_native` sink

- src/stream/src/executor/source/fs_fetch_executor.rs
Previously in https://github.com/risingwavelabs/risingwave/pull/21434 we handled the empty file case. In order to clean up empty files in the state table, the reading file will be set when listing. However, we should only get the file name from the hidden column of the chunk and assign it to the reading file when reading the file.
This pr is changed to not store the empty file information in the fetch exectuor's state table.
<details>
</details>
> fix(file source): do not persist empty file info in state table

- .github/workflows/cherry-pick-since-release-branch.yml
With `always()`, it will skip the status check for jobs in `needs`, which is not expected.
According to [GitHub docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions):
> A default status check of `success()` is applied unless you include one of these (status check) functions.
So prior to this PR, it was
```
always() && needs.get-target-release-branches.outputs.branches != '[]'
```
now it becomes...
```
success() && needs.get-target-release-branches.outputs.branches != '[]'
``` …
> fix(ci): only run `report_status` if there's a cherry-pick tag

- dashboard/lib/api/streaming.ts
- dashboard/pages/indexes.tsx
- src/meta/src/controller/catalog/list_op.rs
- src/meta/src/dashboard/mod.rs
Previously we only displayed the metadata for the state table of the index, which lacked information about the index itself, espeically the `index_items`, i.e., expression of each index column.
<details>
</details>
> feat(dashboard): display metadata for index itself besides index table

- src/meta/src/barrier/checkpoint/creating_job/mod.rs
- src/meta/src/barrier/context/recovery.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/rpc.rs
- src/storage/hummock_sdk/src/change_log.rs
- src/storage/hummock_sdk/src/frontend_version.rs
- src/storage/hummock_sdk/src/version.rs
- src/storage/src/hummock/store/version.rs
Previously in L0 log store, we use a simple `Vec<u64>` to represent a group of epochs, where the last epoch is the checkpoint epoch, and the epochs at the front are non-checkpoint epochs in between. As suggested by @kwannoel , related code has poor readability. In this PR, we will explicitly break down the `Vec<u64>` into `(Vec<u64>, u64)`, which represents `(non-checkpoint epochs, checkpoint epoch)` to improve readability.
<details>
</details>
> refactor(storage): break down log epoch list into non-checkpoint and checkpoint

- proto/expr.proto
- src/common/src/types/mod.rs
- src/expr/impl/src/scalar/array_flatten.rs
- src/expr/impl/src/scalar/mod.rs
- src/frontend/src/binder/expr/function/builtin_scalar.rs
- src/frontend/src/expr/pure.rs
- src/frontend/src/optimizer/plan_expr_visitor/strong.rs
Many query engines/databases have builtin function `array_flatten` or `flatten` to flatten an array of arrays. And it is also requested by our user. This PR adds it for RisingWave.
For the sake of simplicity and clarity, we implement this function following [Snowflake](https://docs.snowflake.com/en/sql-reference/functions/array_flatten?utm_source=chatgpt.com), [Trino](https://trino.io/docs/current/functions/array.html#flatten), [DuckDB](https://database.guide/flattening-nested-lists-with-duckdbs-flatten-function/?utm_source=chatgpt.com), which means, this function works in a non-recursive way, only flattening one level of nesting.
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593 …
> feat(expr): implement `array_flatten`

- .github/workflows/build-docker-image.yml
- ci/workflows/docker.yml
Closes https://github.com/risingwavelabs/risingwave/issues/21601.
This PR reduces margin for human error due to manual tagging of images. It also makes tagging entirely optional. We can automatically generate semantically correct tagging after this PR:
```
v<X.Y.Z[-alpha]>--<label>--<commit_sha>--<git-branch>
```
We use `--`, to clearly delimit different sections. Since hyphens `-` can be used within each segment as well. It will only be a problem if developer uses `-` as a prefix or suffix. I think that's unlikely.
Test workflow dispatch via cli (actual use …
> feat(ci): support workflow for docker image building

- .github/workflows/build-docker-image.yml
- src/tests/sqlsmith/src/sql_gen/table_functions.rs
Add support for generating jsonb_* table functions in Sqlsmith, including `jsonb_array_elements`, `jsonb_array_elements_text`, `jsonb_each`, `jsonb_each_text` and `jsonb_objective_keys`. 
Since some functions (e.g., jsonb_array_elements, jsonb_each) require a specific top-level Jsonb structure—such as an array or object, we first determine the expected top-level type. Then, we recursively generate the Jsonb value under depth control. 
Fixes part of #4540 
<details>
</details>
> feat(sqlsmith): support generation of jsonb_* table function

- Makefile.toml
- src/sqlparser/src/ast/ddl.rs
- src/sqlparser/tests/testdata/alter.yaml
…eses for changed properties
as title 
introduced in https://github.com/risingwavelabs/risingwave/pull/20691
<details>
</details>
> fix: print `AlterSinkOperation::SetSinkProps` correctly

- e2e_test/sink/sink_into_table/decoupled.slt
- src/connector/src/sink/trivial.rs
- src/frontend/planner_test/tests/testdata/input/sink_into_table.yaml
- src/frontend/planner_test/tests/testdata/output/sink_into_table.yaml
- src/frontend/src/optimizer/plan_node/stream_sink.rs
https://github.com/risingwavelabs/risingwave/issues/19285
Use it when sink_decouple is set to true for sink into table. This is supported by placing a logstore before the sink.
```
upstream -> logstore -> sink -> rw table
```
We don't enable `sink_decouple` by default for `sink into table`. But it's available if the user specifies `sink_decouple=true`.
<details>
</details>
> feat(frontend): support sink_decouple for sink into table

- README.md
- ci/scripts/e2e-doris-sink-test.sh
In #21730, we removed the unnecessary `apt install` line before issuing DDL to the Doris server. Then, we started to encounter #21806. I believe this is because we need to allow the server some time to be ready for connection.
A better approach might be to wait for the service to be ready before executing the CI script, by requiring `service_healthy` condition in `depends_on` list in `docker-compose.yml`. However, this may increase the startup time of other CI steps.
https://docs.docker.com/compose/how-tos/startup-order/
Close #21806
<details> …
> fix(ci): increase wait time for doris to be ready in `e2e-doris-sink` test

- e2e_test/ddl/alter_table_column_type.slt
- e2e_test/source_legacy/cdc_inline/alter/cdc_table_alter.slt
- src/common/src/util/column_index_mapping.rs
- src/frontend/src/handler/alter_table_column.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/manager/metadata.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/stream_graph/fragment.rs
- src/prost/src/lib.rs
Previously, when performing schema change, the frontend will generate a `ColumnIndexMapping` between the old and the new schema. It will be used by the meta node to rewrite the `output_indices` field of the dispatchers, to maintain the same schema from the view of existing downstream jobs.
Things start to get complicated since we support altering the column type (https://github.com/risingwavelabs/risingwave/issues/19755): instead of using a simple `output_indices` to transform the data chunks in the dispatcher, we need to introduce some sort of expression …
> refactor(meta): avoid using frontend generated `ColumnIndexMapping` when constructing new dispatcher for replacement

- src/ctl/src/cmd_impl/hummock/sst_dump.rs
- src/meta/src/hummock/compaction/overlap_strategy.rs
- src/meta/src/hummock/compaction/picker/intra_compaction_picker.rs
- src/meta/src/hummock/compaction/picker/manual_compaction_picker.rs
- src/meta/src/hummock/compaction/picker/min_overlap_compaction_picker.rs
- src/meta/src/hummock/compaction/picker/trivial_move_compaction_picker.rs
- src/storage/hummock_sdk/src/sstable_info.rs
- src/storage/hummock_sdk/src/version.rs
Fields in `SstableInfo` is important for data correctness, and we should fill them carefully. Having `Default` impl for `SstableInfo` can easily implicitly fill in unexpected default value.
In this PR, we will remove the `derive(Default)` for `SstableInfo` when we are not in test build. Current usages of the default implementation are removed and changed accordingly. When dealing with `OverlapStrategy`, we used to pass the whole `SstableInfo`, but actually only its `key_range` is used. We will change to only pass the `KeyRange`.
<details> …
> refactor(storage): no default sstable info

- src/frontend/src/binder/mod.rs
- src/frontend/src/handler/create_mv.rs
- src/frontend/src/handler/query.rs
- src/frontend/src/optimizer/backfill_order_strategy.rs
- src/frontend/src/optimizer/mod.rs
This PR is in preparation for https://github.com/risingwavelabs/risingwave/pull/21814. To auto-derive backfill order, we need the stream plan, which is produced only after the planning phase.
So we do two things here:
1. Refactor the planning for backfill order strategy after binding.
2. Move the module for backfill order strategy planning into the **optimizer**. This makes more sense, since this is no longer purely binding user input. Rather we are optimizing the backfill order.
We intentionally keep this PR separate from #21814, since we refactor file …
> feat(frontend): plan backfill order strategy after the planner phase, instead of binding phase

- src/frontend/src/handler/create_mv.rs
- src/frontend/src/optimizer/backfill_order_strategy.rs
This PR adds the `backfill_order = auto` option when creating materialized views. It focuses on filling right-side tables first (usually smaller lookup tables) and constructs a partial order, which allows for concurrent backfill on incomparable elements (elements which have no dependencies on each other).
We handle the common cases of:
- stream scan
- join
- union
And leave the rest for further improvement.
For tests, please checkout the downstream PR: https://github.com/risingwavelabs/risingwave/pull/21838
<details> …
> feat(frontend): auto derive backfill order

- proto/stream_plan.proto
- src/frontend/src/handler/create_mv.rs
- src/frontend/src/optimizer/backfill_order_strategy.rs
- src/frontend/src/stream_fragmenter/graph/fragment_graph.rs
- src/frontend/src/stream_fragmenter/mod.rs
- src/meta/src/barrier/backfill_order_control.rs
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/progress.rs
- src/meta/src/stream/stream_graph/fragment.rs
- src/meta/src/stream/stream_manager.rs
- src/meta/src/stream/test_fragmenter.rs
This PR is intentionally separated from the previous one, since it involves refactoring and adds noise.
From the previous PR, I realize we only need to pass a backfill order to the meta node, rather than different backfill order strategies.
That's because for `auto` (the variant we are removing), we will directly derive a fixed order for it in the frontend, and send it to the meta node.
Therefore we can simplify the proto definition. There's no risk of breaking backwards compatbility, since this is not persisted, and hasn't made it into any release branch …
> refactor(frontend,proto): remove unused `auto` variant for backfill order strategy

- grafana/dashboard/common.py
- grafana/risingwave-dev-dashboard.dashboard.py
- grafana/risingwave-user-dashboard.dashboard.py
Add a hidden variable `cluster` to the Grafana dashboards when the namespace filter is enabled . Values of the variable will be popped up with the query `label_values(up{risingwave_name=~".+", namespace=$namespace})`. Generally, there will be two cases:
- On premise: there's no such label `cluster` so that all queries will have an ineffective label filter `cluster=""`.
- Cloud: there's such label `cluster` and it's unique to a `namespace`. The only value option will be used in all queries.
The `cluster` variable and label filter is used to streamline query …
> feat(dashboard): add hidden cluster variable to hint query over promxy

- Cargo.lock
- Cargo.toml
- clippy.toml
- src/batch/clippy.toml
- src/batch/src/error.rs
- src/common/src/error.rs
- src/connector/src/connector_common/iceberg/jni_catalog.rs
- src/connector/src/connector_common/iceberg/storage_catalog.rs
- src/connector/src/error.rs
- src/connector/src/source/iceberg/parquet_file_handler.rs
- src/error/Cargo.toml
- src/error/src/lib.rs
- src/error/src/wrappers.rs
- src/stream/clippy.toml
> feat: show backtrace from iceberg::Error by introducing a newtype

- src/batch/src/worker_manager/worker_node_manager.rs
- src/meta/node/src/server.rs
- src/meta/src/controller/session_params.rs
- src/meta/src/manager/notification.rs
- src/meta/src/serving/mod.rs
- src/meta/src/stream/scale.rs
Previously, the runtime parameter `batch_parallelism` [doesn't apply to the batch scan](https://github.com/risingwavelabs/risingwave/blob/b34ead99cea83cf861952bba326ca2c1bff2efe0/src/frontend/src/scheduler/plan_fragmenter.rs#L1008). Therefore the batch scan will use all available serving parallleism up to 256. The might cause problem when high QPS introduces too many batch tasks in serving nodes.
This PR makes batch scan adhere to `batch_parallelism`, in order to limit batch scan task parallelism to lower number when necessary. The implementation idea is to …
> fix: make batch scan adhere to runtime param batch_parallelism

- proto/hummock.proto
- src/compute/src/server.rs
- src/meta/service/src/hummock_service.rs
- src/meta/src/hummock/manager/sequence.rs
- src/meta/src/hummock/manager/utils.rs
- src/meta/src/hummock/mock_hummock_meta_client.rs
- src/meta/src/hummock/test_utils.rs
- src/rpc_client/src/compactor_client.rs
- src/rpc_client/src/hummock_meta_client.rs
- src/rpc_client/src/meta_client.rs
- src/storage/compactor/src/server.rs
- src/storage/hummock_sdk/src/lib.rs
- src/storage/hummock_test/src/compactor_tests.rs
- src/storage/hummock_test/src/sync_point_tests.rs
- src/storage/src/hummock/compactor/compaction_utils.rs
- src/storage/src/hummock/compactor/compactor_runner.rs
- src/storage/src/hummock/compactor/fast_compactor_runner.rs
- src/storage/src/hummock/compactor/mod.rs
- src/storage/src/hummock/compactor/shared_buffer_compact.rs
- src/storage/src/hummock/event_handler/hummock_event_handler.rs
- src/storage/src/hummock/hummock_meta_client.rs
- src/storage/src/hummock/mod.rs
- src/storage/src/hummock/object_id_manager.rs
- src/storage/src/hummock/sstable/mod.rs
- src/storage/src/hummock/store/hummock_storage.rs
- src/storage/src/monitor/monitored_store.rs
- src/storage/src/monitor/traced_store.rs
- src/tests/compaction_test/src/compaction_test_runner.rs
Currently in hummock, we only have the sst object file, and the structs and rpc related to generating unique object id are all for sstable object id. As we will support more object types for vector index, in this PR, we will generalize them to support generating the unique general object id type.
<details>
</details>
> refactor(meta): generate general hummock object id on meta

- src/common/src/config.rs
- src/config/example.toml
- src/meta/node/src/lib.rs
- src/meta/src/hummock/manager/checkpoint.rs
- src/meta/src/hummock/manager/gc.rs
- src/meta/src/hummock/manager/time_travel.rs
- src/meta/src/manager/env.rs
- src/storage/hummock_sdk/src/version.rs
When doing GC, we will filter out the objects pinned by time travel. Previously we do the filtering by reading the `hummock_sstable_info` meta store table. This works for the current code that only has sst object to track. However, we will have vector index file in the future, and therefore reading `hummock_sstable_info` is not enough.
In this PR, we will change to list the whole `hummock_time_travel_version`  and `hummock_time_travel_version_delta` table to figure out the object id pinned by time travel version, so that in the future we can support GC of …
> feat(storage): filter out GC objects by listing time travel versions and deltas

- src/connector/src/connector_common/connection.rs
- src/connector/src/connector_common/mod.rs
- src/connector/src/sink/kafka.rs
- src/connector/src/source/kafka/enumerator.rs
- src/connector/src/source/kafka/source/reader.rs
- Introduced a new function `read_kafka_log_level` to read the log level from the environment variable `RISINGWAVE_KAFKA_LOG_LEVEL`.
- Updated `KafkaConnection`, `KafkaSinkWriter`, and `KafkaSplitReader` to utilize the dynamic log level configuration.
- Ensured that an invalid log level falls back to the default level of INFO with a warning log.
proposed by @arkbriar 
introduce `RISINGWAVE_KAFKA_LOG_LEVEL` to control the log level of kafka sdk
accept
```
DEBUG
INFO
WARN
ERROR
CRITICAL
EMERG
ALERT
NOTICE
```
<details> …
> feat: add ENV to control Kafka sdk log level

- ci/scripts/connector-node-integration-test.sh
- integration_tests/iceberg-cdc/docker-compose.yml
`mc config` is not available anymore. Refer to https://github.com/minio/mc/pull/5201
<details>
</details>
> chore(ci): replace mc config host add with mc alias set

- src/connector/src/connector_common/connection.rs
> fix: respect RUST_LOG when RISINGWAVE_KAFKA_LOG_LEVEL is not set

- src/tests/sqlsmith/config.yml
- src/tests/sqlsmith/src/config.rs
- src/tests/sqlsmith/src/sql_gen/relation.rs
This PR extends the SQLSmith generator with support for generating NATURAL JOIN and JOIN ... USING (...) clauses. 
<details>
</details>
> feat(sqlsmith): support natural and using join

- src/sqlparser/src/ast/mod.rs
- src/utils/pgwire/src/pg_protocol.rs
The new check added in #20860 (since v2.4.0) contains an improper fix for redacted sql:
* Previously we had `foo = [REDACTED]`. This is not a valid SQL and fails the new check.
* That PR updated it to `foo = '[REDACTED]'`. It is valid in most cases (eg credentials) but not valid in `connection = '[REDACTED]'`. It is expected to be an `ObjectName` rather than a string.
* This PR reverts the improper fix and make it `foo = [REDACTED]` again. This is again not a valid SQL but we exclude redacted sqls from the validity check.
The actual panic is fixed (with repro …
> fix(sqlparser): bypass parsability check for redacted sql

- src/common/src/types/map_type.rs
- src/common/src/types/mod.rs
- src/common/src/types/struct_type.rs
- src/expr/core/src/sig/mod.rs
- src/frontend/planner_test/tests/testdata/output/backfill.yaml
- src/frontend/planner_test/tests/testdata/output/temporal_filter.yaml
- src/frontend/planner_test/tests/testdata/output/union.yaml
- src/frontend/src/optimizer/plan_node/logical_union.rs
To prevent misuse. See #22054 for the motivation to fix it now.
<details>
</details>
> refactor(common): remove `PartialOrd` for `DataType` (retained for `DataTypeName`)

- .github/workflows/cherry-pick-since-release-branch.yml
As title. To address https://github.com/risingwavelabs/risingwave/pull/21306#issuecomment-2947908950
<details>
</details>
> chore(ci): use PAT for cherry-pick workflow

- ci/workflows/pull-request.yml
https://github.com/risingwavelabs/risingwave/pull/22075#issuecomment-2952058347
<details>
</details>
> feat: increase timeout for slow e2e test

- ci/docker-compose.yml
- ci/scripts/e2e-sink-test.sh
- ci/scripts/e2e-source-test.sh
- ci/scripts/regress-test.sh
- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/DbzConnectorConfig.java
- risedev.yml
- src/batch/executors/src/executor/postgres_query.rs
- src/frontend/src/expr/table_function.rs
Fixes #21932 by parsing the properties file first and do substitution in-memory. This avoid the substituted text from being handled by the properties-parser.
Also fixes a similar issue in `postgres_query` (batch PostgreSQL source). We shall pass parameters structurally rather than via a interpolated connection string, which would also require complicated escaping to be parsed back losslessly.
Also identified issues in our dev/test tools:
* `risedev` (using `cargo-make`/`envmnt`) environment variable passing …
> fix(cdc/batch): special char during debezium props substitution and `postgres_query`

- e2e_test/source_inline/cdc/sql_server/sql_server_cdc.slt.serial
- e2e_test/source_inline/cdc/sql_server/sql_server_cdc_insert.sql
- e2e_test/source_inline/cdc/sql_server/sql_server_cdc_prepare.sql
- src/connector/src/parser/sql_server.rs
- When upstream pk is `varchar` or `uuid`(both will convert to `utf-8`), we should not panic.
- add test
<details>
</details>
> fix(mssql-cdc): support `uuid` and `varchar` as primary key data type

- ci/scripts/e2e-test-serial.sh
- e2e_test/backfill/backfill_progress.slt
- src/frontend/src/catalog/system_catalog/rw_catalog/mod.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_fragment_backfill_progress.rs
In this PR, we introduced the fragment backfill progress view. This view will display the backfill progress per fragment, in a similar format to `show jobs`.
After backfill order is introduced, we need to also provide a way for users to observe the backfill progress per backfill node. Currently users can only view this progress at a job level, and not at a fragment level via show jobs.
The user flow will be something like:
1. `DESCRIBE FRAGMENTS creating_job_name` or `explain <query>`
2. After seeing the fragment_ids of their stream job / backfill table …
> feat(catalog): add fragment backfill progress view

- src/connector/src/connector_common/mod.rs
- src/connector/src/sink/file_sink/s3.rs
- src/connector/src/source/filesystem/opendal_source/mod.rs
- src/connector/src/source/filesystem/opendal_source/s3_source.rs
- src/connector/src/source/filesystem/s3/mod.rs
- src/connector/src/source/reader/reader.rs
- src/connector/with_options_sink.yaml
- src/connector/with_options_source.yaml
- src/frontend/src/scheduler/plan_fragmenter.rs
Previously users are required to configure an access key and access ID to access, which is intended to isolate Hummock's S3. However, for on-prem users, it is more reasonable to expose this configuration to them. Users can set `disable_config_load` to allow the S3 source and sink to directly obtain authentication information from the pod's environment. 
This PR places `disable_config_load` within the with option, and the default behavior is set to true.
<details>
</details>
> refactor(s3 connector): expose `enable_config_load` to user for s3 source and sink

- ci/scripts/e2e-test-serial.sh
- e2e_test/backfill/backfill_progress/create_materialized_view.slt
- e2e_test/backfill/backfill_progress/create_materialized_view_snapshot.slt
- e2e_test/backfill/backfill_progress/test.slt
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_fragment_backfill_progress.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_table_scan.rs
- src/frontend/src/expr/table_function.rs
- src/frontend/src/optimizer/logical_optimization.rs
- src/frontend/src/optimizer/rule/table_function_to_file_scan_rule.rs
- src/frontend/src/optimizer/rule/table_function_to_internal_backfill_progress.rs
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593ebdbfa826691daf75bdaf7d14fa0/.github/contributor-license-agreement.txt).
This PR improves the backfill progress tracking for snapshot backfill by:
1. Restructuring the backfill progress test files for better organization
2. Adding support for tracking progress in snapshot backfill mode by:
- Tracking the minimum epoch in backfill progress
- Enhancing the `rw_fragment_backfill_progress` view to show 100% completion when the minimum epoch exceeds the backfill epoch
- Adding `is_snapshot_backfill` and `backfill_epoch` fields to the table scan information
3. Extending the test cases to verify both regular and snapshot backfill …
> feat(frontend): support fragment level progress for snapshot backfill

- ci/scripts/e2e-test-serial.sh
- e2e_test/streaming/unaligned-join.slt
I think it can potentially cause parallel mode tests to be slow. Only apply the join amplification workload for serial mode test.
<details>
</details>
> chore(ci): only run unaligned-join test in serial mode

- src/tests/sqlsmith/src/lib.rs
- src/tests/sqlsmith/src/sql_gen/dml.rs
- src/tests/sqlsmith/src/sql_gen/expr.rs
- src/tests/sqlsmith/src/sql_gen/mod.rs
- src/tests/sqlsmith/src/sql_gen/query.rs
- src/tests/sqlsmith/src/sql_gen/relation.rs
- src/tests/sqlsmith/src/sql_gen/time_window.rs
#22085 is a fix to convert `real_value: String` back to `ast::Ident` properly, by quoting the value with `"` if there's any upper case or special character.
However, in sqlsmith, we previously relied on the incorrect behavior by directly interpolating a `.` into the name of `Column` to represent the qualified name. As a result, the fix failed the fuzzing test in main-cron.
This PR fixed the handling of column name in sqlsmith, by storing an `ObjectName` instead.
```
[2m2025-06-12T16:36:47.783799Z[0m [32m INFO[0m …
```
> fix(sqlsmith): use `ObjectName` for column name to correctly distinguish qualified name

- src/frontend/src/handler/mod.rs
- src/sqlparser/src/ast/ddl.rs
- src/sqlparser/src/parser.rs
…erations
Updated the ALTER SINK operation to use AlterConnectorProps instead of SetSinkProps, reflecting a more accurate representation of the operation's purpose. Adjusted related parsing and handling logic accordingly.
<details>
</details>
> refactor: unify alter connector op name in `AlterSinkOperation`

- ci/scripts/e2e-test-serial.sh
- e2e_test/batch/explain_analyze.slt
- src/frontend/src/handler/explain_analyze_stream_job.rs
- src/prost/build.rs
The main goal of this PR is to tolerate project and merge nodes injected by sink into table. See https://github.com/risingwavelabs/risingwave/pull/22230. We ensure metrics collection and graph generation can tolerate this case for backwards compatibility. We also add more test coverage, just to validate that explain analyze shouldn't crash.
This PR improves the `EXPLAIN ANALYZE` functionality for stream jobs with the following changes:
1. Added a new e2e test for `EXPLAIN ANALYZE` that tests the command on tables, materialized views, and sinks with different …
> fix(frontend): tolerate duplicate operator ids and missing metrics

- src/common/src/util/stream_graph_visitor.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/model/stream.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/stream_graph/fragment.rs
- src/tests/simulation/tests/integration_tests/scale/dynamic_filter.rs
…r ids
A unique operator id is required for us to accurately track the profiling metrics for newly injected project and merge nodes inside explain analyze.
1. Traverse the union fragment to find the max operator id. Use that +1, +2 to assign operator ids to the injected project and merge nodes.
2. Refactor function name `visit_stream_node` -> `visit_stream_node_body` to reflect the actual usage.
The operator id just needs to be locally unique to the fragment, since it's globally namespaced by the fragment id.
<details> …
> fix(meta): injected project and merge nodes should have unique operator ids by sink into table

- ci/scripts/deterministic-it-test.sh
- ci/workflows/pull-request.yml
https://github.com/risingwavelabs/risingwave/pull/21781#issuecomment-2979415694
<details>
</details>
> chore(ci):  isolate logstore tests from pull request workflow

- e2e_test/source_inline/kafka/shared_source.slt.serial
- src/frontend/src/stream_fragmenter/mod.rs
- src/frontend/src/stream_fragmenter/rewrite/delta_join.rs
close https://github.com/risingwavelabs/risingwave/issues/22223
For job with snapshot backfill, since its checkpoint is independent to upstream, it should not have any streaming exchange with upstream. However, for delta join and shared source backfill, they must receive upstream messages from exchange channel with upstream. As a result, snapshot backfill join with delta join and shared source backfill will have the panic described in https://github.com/risingwavelabs/risingwave/issues/22223.
In this PR, we will explicitly ban snapshot backfill with delta …
> fix(frontend): ban snapshot backfill with shared source backfill and delta join

- src/stream/src/common/log_store_impl/kv_log_store/buffer.rs
- src/stream/src/common/log_store_impl/kv_log_store/mod.rs
- src/stream/src/common/log_store_impl/kv_log_store/reader.rs
- src/stream/src/common/log_store_impl/kv_log_store/state.rs
- src/stream/src/executor/sync_kv_log_store.rs
- src/stream/src/from_proto/sink.rs
- src/stream/src/from_proto/sync_log_store.rs
resolve https://github.com/risingwavelabs/risingwave/issues/22282
In log store, we have logic to merge any contiguous `Flushed` stream chunks into one, so that later we can read all rows of them together in once. However, previously we don't have a limit on the size of merged chunk yet, and they are possible to be merged into a very large chunk when there are too many data in a barrier, and we may exceed the upper bound of valid buffer size of chunk builder and panic like https://github.com/risingwavelabs/risingwave/issues/22282.
In this PR, we will use the …
> feat(log-store): limit the max size of merged flushed chunk

- src/frontend/src/stream_fragmenter/mod.rs
Added a check to prevent using backfill order control with cross-database snapshot backfill operations. This change:
1. Adds a new `has_cross_db_snapshot_backfill` flag to the `BuildFragmentGraphState` struct to track when cross-database snapshot backfill is used
2. Sets this flag when a cross-database snapshot backfill stream scan is encountered
3. Adds validation logic to return a clear error message when users attempt to combine backfill order control with cross-database snapshot backfill
This prevents users from attempting unsupported combinations of …
> feat(frontend): disallow backfill order with cross-db snapshot backfill

- java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java
`SUCCESS_NO_INFO` is a returned status from calling `executeBatch`, it's not a configuration parameter.
On the other hand, `NO_GENERATED_KEYS` is the correct configuration parameter:
[docs](https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/java/sql/Connection.html#prepareStatement(java.lang.String,int))
<details>
</details>
> fix(connector): jdbc pg should use `NO_GENERATED_KEYS` instead of `SUCCESS_NO_INFO`

- ci/scripts/build.sh
In the [latest `main-cron` run,](https://buildkite.com/risingwavelabs/main-cron/builds/5725#019788eb-8b2e-46a4-9d29-ca57e78e388e) it appears that test cases related to backfilling are much slower. This could be because it's more resource-intensive, thus significantly affected by the code coverage introduced in #22201.
Given that the results may not be accurate after code optimization, let's disable coverage instrument on `main-cron` first. Later we may investigate if it's meaningful & feasible to re-enable it.
<details> …
> chore(ci):  disable coverage instrument on `main-cron`

- src/storage/hummock_test/src/hummock_read_version_tests.rs
- src/storage/hummock_test/src/hummock_storage_tests.rs
- src/storage/hummock_test/src/state_store_tests.rs
- src/storage/hummock_trace/src/opts.rs
- src/storage/src/hummock/event_handler/hummock_event_handler.rs
- src/storage/src/hummock/event_handler/mod.rs
- src/storage/src/hummock/event_handler/uploader/mod.rs
- src/storage/src/hummock/iterator/change_log.rs
- src/storage/src/hummock/store/local_hummock_storage.rs
- src/storage/src/hummock/store/version.rs
- src/storage/src/memory.rs
- src/storage/src/store.rs
- src/stream/src/common/log_store_impl/kv_log_store/mod.rs
- src/stream/src/common/log_store_impl/kv_log_store/state.rs
- src/stream/src/common/table/state_table.rs
- src/stream/src/executor/sync_kv_log_store.rs
Previously in `LocalHummockStorage`, we add the newly generated imm to uploader whenever on `flush`. This works for normal state table, where we only flush once in each epoch. However, for state of kv log store, we may flush multiple times on multiple chunks, which generates a large number of imm and meanwhile many `HummockEvent::ImmToUploader`, and causes too much pending events and unable to handle hummock event timely.
In this PR, we add a new option `upload_on_flush` in `NewLocalOptions`. When it's false, we won't always add the imm generated in `flush` …
> feat(storage): batch add flushed imm to uploader

- e2e_test/source_inline/nats/test.slt.serial
- integration_tests/nats/README.md
- integration_tests/nats/create_sink.sql
- integration_tests/nats/create_source.sql
- integration_tests/nats/pb/create_source.sql
- src/connector/src/connector_common/common.rs
- src/connector/src/source/nats/enumerator/mod.rs
- src/connector/with_options_sink.yaml
- src/connector/with_options_source.yaml
resolve https://github.com/risingwavelabs/risingwave/issues/21797
per request by poc user
The NATS connector currently creates streams automatically when they don't exist, which can lead to unintended stream creation in production environments. This poses security and operational risks:
Streams may be created with default configurations that don't match production requirements
Typos in stream names could result in unwanted streams being created
No explicit control over when RisingWave should have stream creation permissions
This PR introduces a new boolean …
> feat: add `allow_create_stream` to avoid create nats stream by mistake

- ci/workflows/main-cron.yml
It's blocking other patches from making it into release-2.5. Unblock main-cron first, until I fix it. It will be fixed before 2.5 released.
<details>
</details>
> chore(ci): temporarily disable logstore test for release-2.5

- e2e_test/batch/types/vector.slt.part
- proto/expr.proto
- src/expr/impl/src/scalar/mod.rs
- src/expr/impl/src/scalar/vector_dist.rs
- src/frontend/src/binder/expr/binary_op.rs
- src/frontend/src/binder/expr/function/builtin_scalar.rs
- src/frontend/src/expr/pure.rs
- src/frontend/src/expr/type_inference/func.rs
- src/frontend/src/optimizer/plan_expr_visitor/strong.rs
Adding an expression for the vector index poc. The implementation may be optimized further.
<details>
</details>
> feat(expr): `l2_distance` between 2 `vector`s

- src/connector/src/sink/postgres.rs
[
We add pipelining in this PR](https://www.postgresql.org/docs/current/libpq-pipeline-mode.html), which can be simply done by concurrently executing a series of futures.
This also removes complicated logic around parameter batching, just do query pipelining.
These fixes are done for PG rust sink.
> perf(connector): optimize pg native sink writer with pipelining

- src/sqlparser/src/parser.rs
- src/sqlparser/tests/testdata/array.yaml
- src/sqlparser/tests/testdata/select.yaml
Cherry picking #22394 onto branch release-2.3,
This PR/issue was created to resolve #22407
> fix(sqlparser): `arr[lo:hi]` and `map{k: v}` broken by `aggregate:` (#22394)

- proto/stream_plan.proto
- src/common/src/catalog/column.rs
- src/common/src/catalog/mod.rs
- src/ctl/src/cmd_impl/meta/cluster_info.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_backfill_info.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_fragments.rs
- src/frontend/src/catalog/system_catalog/rw_catalog/rw_rate_limit.rs
- src/frontend/src/stream_fragmenter/graph/fragment_graph.rs
- src/frontend/src/stream_fragmenter/mod.rs
- src/meta/src/barrier/backfill_order_control.rs
- src/meta/src/barrier/context/context_impl.rs
- src/meta/src/barrier/rpc.rs
- src/meta/src/controller/catalog/mod.rs
- src/meta/src/controller/fragment.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/controller/utils.rs
- src/meta/src/dashboard/mod.rs
- src/meta/src/model/stream.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/scale.rs
- src/meta/src/stream/stream_graph/fragment.rs
- src/meta/src/stream/test_fragmenter.rs
- src/prost/src/lib.rs
Previously when declaring the `FragmentTypeFlag`, we need to carefully set the raw int value of the enum variant to be a well-formed power of 2 value. In this PR, we will change to use a macro to generate the enum, so that we only need to declare a list of flags, and then the value can be correctly generated.
Besides, previously we operate with `fragment_type_mask` as raw int value, where we have to do raw bit operation on int value, which is unreadable, and can easily make mistake. In this PR, we will wrap the raw int value with a struct `FragmentTypeMask`, …
> refactor(meta): wrap fragment type mask with struct

- e2e_test/streaming/alter_mv/alter_mv_simple.slt
- proto/ddl_service.proto
- src/frontend/src/catalog/catalog_service.rs
- src/meta/service/src/ddl_service.rs
- src/meta/src/controller/streaming_job.rs
- src/meta/src/manager/streaming_job.rs
- src/meta/src/rpc/ddl_controller.rs
- src/meta/src/stream/stream_graph/fragment.rs
> [!WARNING]
> This feature is highly experimental and may be subject to change. It won't be published in the documentation in the near future.
This PR adds minimal support for `ALTER MATERIALIZED VIEW <name> AS <query>` to the meta service. The logic is kept as simple (trivial) as possible.
Thanks to the great extendibility of the design of the graph builder, almost no extra logic is required to support basic replacement of materialized view but adding some `match` arms!
Note that we inherit the very basic algorithm for matching internal tables that's used …
> feat(meta): minimal support for `ALTER MATERIALIZED VIEW AS`

- src/connector/src/allow_alter_on_fly_fields.rs
- src/connector/src/source/kafka/mod.rs
- src/connector/with_options_source.yaml
… related configurations
per requested by @xxchan 
thread https://github.com/risingwavelabs/risingwave/pull/22466#pullrequestreview-2977510415
<details>
make `group.id.prefix` valid in alter table/source connector, not valid for sink
</details>
> feat: make kafka source `group.id.prefix` alter-able

- ci/scripts/e2e-test-serial.sh
- src/frontend/src/session.rs
- src/utils/pgwire/src/pg_message.rs
- src/utils/pgwire/src/pg_protocol.rs
- src/utils/pgwire/src/pg_server.rs
Cherry picking #22504 onto branch release-2.3,
This PR/issue was created to resolve #22518.
> fix(pgwire): send ParameterStatus(TimeZone) on startup to avoid psycopg[binary] segfault (#22504)

- src/meta/src/controller/catalog/drop_op.rs
- src/meta/src/rpc/ddl_controller.rs
Related recovery test (madsim) fails:
https://buildkite.com/risingwavelabs/main-cron/builds/6162#0197f511-7ef0-46ea-ba7d-7a3b45607c07
The clean logic is necessary, but in this case, the second DDL should theoretically have been rejected earlier by recovery status check. 🤔 
<details>
</details>
> fix: clean dirty creating subscription after command failure

- e2e_test/sink/mqtt_sink.slt
- src/connector/src/source/mqtt/enumerator/mod.rs
- src/connector/src/source/mqtt/source/reader.rs
- src/connector/src/source/mqtt/split.rs
This PR does 2 things, separated in commits (it can be helpful to review them separatedly).
1. It fixes the MQTT data loss (https://github.com/risingwavelabs/risingwave/issues/19707) by moving the processing to a single split (and client)
2. It allows multiple MQTT topics to be specified by separating with `,`s
I intentionally chose to keep 1 split, even when using multiple MQTT topics to prevent message duplication in the case of overlapping topics. e.g. subscribing to `/a/#` and `/a/b/#` should only result in 1 message on topic `a/b/c`. Splitting multiple …
> feat(mqtt): fix MQTT data loss

- src/meta/src/rpc/ddl_controller.rs
- src/stream/src/executor/integration_tests.rs
- src/stream/src/executor/merge.rs
- src/stream/src/executor/mod.rs
- src/stream/src/executor/project/mod.rs
- src/stream/src/executor/project/project_scalar.rs
- src/stream/src/executor/upstream_sink_union.rs
- src/stream/src/task/actor_manager.rs
Currently, we have only implemented the `UpstreamSinkUnion` operator. In `create_nodes_inner` function, we replaced the previous `Merge` + `Project` operator in a way that is not completely reliable. Soon, once the meta's modification is completed, the hack here will no longer be needed.
In addition, the operator does not currently support dynamic increase and decrease of upstream, but will support it in the future.
<details>
</details>
> feat(compute): Implement UnionUpstreamSink operator

- src/frontend/src/handler/create_mv.rs
- src/frontend/src/handler/create_sink.rs
- src/frontend/src/handler/query.rs
- src/frontend/src/optimizer/logical_optimization.rs
- src/frontend/src/optimizer/mod.rs
- src/frontend/src/optimizer/plan_node/logical_multi_join.rs
- src/frontend/src/optimizer/plan_node/mod.rs
- src/frontend/src/optimizer/plan_rewriter/share_source_rewriter.rs
- src/frontend/src/optimizer/plan_visitor/apply_visitor.rs
- src/frontend/src/optimizer/plan_visitor/cardinality_visitor.rs
- src/frontend/src/optimizer/plan_visitor/distributed_dml_visitor.rs
- src/frontend/src/optimizer/plan_visitor/execution_mode_decider.rs
- src/frontend/src/optimizer/plan_visitor/input_ref_validator.rs
- src/frontend/src/optimizer/plan_visitor/jsonb_stream_key_checker.rs
- src/frontend/src/optimizer/plan_visitor/mod.rs
- src/frontend/src/optimizer/plan_visitor/plan_correlated_id_finder.rs
- src/frontend/src/optimizer/plan_visitor/read_storage_table_visitor.rs
- src/frontend/src/optimizer/plan_visitor/relation_collector_visitor.rs
- src/frontend/src/optimizer/plan_visitor/rw_timestamp_validator.rs
- src/frontend/src/optimizer/plan_visitor/share_parent_counter.rs
- src/frontend/src/optimizer/plan_visitor/side_effect_visitor.rs
- src/frontend/src/optimizer/plan_visitor/sys_table_visitor.rs
- src/frontend/src/optimizer/plan_visitor/temporal_join_validator.rs
Previously, in `PlanVisitor` trait, we include the `visit_$convention_$variant_name` method of all conventions in the trait. However, every time we visit a plan, its convention is fixed. In this PR, we will divide the trait into 3 `$ConventionPlanVisitor` traits, with each trait only has the `visit_$convention_$variant_name` of its own plan nodes, so that we can avoid calling the `visit_xxx` method with the wrong convention. We will also have a `PlanVisitor<C: ConventionMarker>` trait, with a method `fn visit(&mut self, plan: PlanRef) -> Self::Result;`. …
> refactor(frontend): separate PlanVisitor of different conventions

- proto/expr.proto
- src/common/src/types/mod.rs
- src/expr/impl/src/scalar/vector.rs
- src/frontend/src/binder/expr/binary_op.rs
- src/frontend/src/binder/expr/mod.rs
- src/frontend/src/expr/pure.rs
- src/frontend/src/expr/type_inference/func.rs
- src/frontend/src/optimizer/plan_expr_visitor/strong.rs
- src/sqlparser/src/parser_v2/data_type.rs
Support vector concatenation: `vector || vector -> vector`
Caveat:
Since we require vector types to have a statically defined size, we cannot infer it for `null` or extended mode parameters `$1`.
<details>
</details>
> feat(expr): `vector || vector` concatenation

- src/stream/src/executor/sink.rs
close https://github.com/risingwavelabs/risingwave/issues/22717
advance delete will hold a chunk wait for barrier to handle if the sink's primary key does not match upstream, this does not make sense for force_append_only. As we already skip the logic for AppendOnly sink
<details>
</details>
> fix(sink): avoid advance delete for force_append_only sink

- src/connector/src/macros.rs
- src/connector/src/source/batch.rs
- src/connector/src/source/filesystem/opendal_source/batch_posix_fs_source.rs
- src/connector/src/source/filesystem/opendal_source/mod.rs
- src/connector/src/source/mod.rs
- src/connector/with_options_source.yaml
- src/frontend/src/scheduler/plan_fragmenter.rs
- src/stream/src/executor/source/executor_core.rs
- src/stream/src/executor/source/source_executor.rs
> feat: batch posix fs connector (__for_testing_only_batch_posix_fs)

- src/connector/src/connector_common/postgres.rs
If a user has already created a publication, we do not need to perform operations such as `creating publication` or `alter publication add tables`, and table owner permissions are not required. 
In the previous implementation, the primary key was retrieved using SeaORM, which required querying the `information_schema.table_constraints` table, but this table requires higher permissions. This PR changes the primary key retrieval step to query other system tables to avoid this issue.
<details>
</details>
> refactor(pg-cdc): do not require table owner permission for pk access

- ci/scripts/e2e-test-serial.sh
- dashboard/README.md
- e2e_test/dashboard/create_graph.slt.part
- e2e_test/dashboard/drop_graph.slt.part
- e2e_test/dashboard/graph.slt
Added dedicated test data for the dashboard's rendering capabilities. Previously we have some adhoc sql, that's not tested in CI. This PR unifies those SQL into a single slt script, and tests the queries to make sure they can run in CI.
We don't use `nexmark` or `tpch`, since these query sets are 1-deep, (i.e. base tables and MVs only on base tables, no mv-on-mv). So we cannot evaluate the graph rendering for deep graphs. Further, these queries also do not have high backpressure, and we can't really see how high backpressure is visualized for these.
This PR: …
> feat(dashboard): add test data for dashboard rendering

- dashboard/components/utils/backPressure.tsx
There's no need to further normalize the backpressure by dividing by 100. The values received here are not percentages but a float with the rate: `[0.0, 1.0]`.
Before the change, even though backpressure is at 98%, there's no colour transition for that edge or width transition:
After the change, you can see there's colour transition and width transition at 115% backpressure:
<details>
</details>
> fix(dashboard): normalize backpressure values to 0-1 range

- src/storage/src/vector/distance.rs
issue: resolve #22872 
Tests under src/storage/src/vector/distance.rs used a signed difference to compare floating-point values:
`($first - $second) < FLOAT_ALLOWED_BIAS`
This is asymmetric and can let large negative differences pass. After upgrading CMake I also observed a drift (~1.2e-5) that slightly exceeds the current 1e-5 epsilon causing the test to fail locally.
Observed failure: `Expected: 31.531513, Actual: 31.531525  (|Δ| ≈ 1.2e-5)`
**This PR:**
- Fixes the logic to compare absolute difference.
- Uses a combined absolute + relative tolerance to …
> fix: float comparison in vector::distance tests

- Cargo.lock
- src/storage/Cargo.toml
cherry-pick 
see https://github.com/nimtable/iceberg-compaction/pull/79
<details>
</details>
> fix: cherry-pick fix datafusion sql format 

- src/common/src/types/timestamptz.rs
- src/expr/impl/src/scalar/timestamptz.rs
It was disallowed to prevent a panic in the `speedate` library, and the issue has been fixed since 0.15. Resolves #22789
<details>
</details>
> feat(expr): allow parsing timestamptz before year 1600

- src/frontend/src/optimizer/plan_node/generic/join.rs
- src/frontend/src/optimizer/plan_node/generic/source.rs
- src/frontend/src/optimizer/plan_node/logical_agg.rs
- src/frontend/src/optimizer/plan_node/logical_dedup.rs
- src/frontend/src/optimizer/plan_node/logical_join.rs
- src/frontend/src/optimizer/plan_node/logical_over_window.rs
- src/frontend/src/optimizer/plan_node/logical_project.rs
- src/frontend/src/optimizer/plan_node/logical_topn.rs
- src/frontend/src/optimizer/plan_node/stream.rs
- src/frontend/src/optimizer/plan_node/stream_asof_join.rs
- src/frontend/src/optimizer/plan_node/stream_cdc_table_scan.rs
- src/frontend/src/optimizer/plan_node/stream_delta_join.rs
- src/frontend/src/optimizer/plan_node/stream_dml.rs
- src/frontend/src/optimizer/plan_node/stream_dynamic_filter.rs
- src/frontend/src/optimizer/plan_node/stream_group_topn.rs
- src/frontend/src/optimizer/plan_node/stream_hash_agg.rs
- src/frontend/src/optimizer/plan_node/stream_hash_join.rs
- src/frontend/src/optimizer/plan_node/stream_local_approx_percentile.rs
- src/frontend/src/optimizer/plan_node/stream_materialize.rs
- src/frontend/src/optimizer/plan_node/stream_materialized_exprs.rs
- src/frontend/src/optimizer/plan_node/stream_over_window.rs
- src/frontend/src/optimizer/plan_node/stream_row_merge.rs
- src/frontend/src/optimizer/plan_node/stream_simple_agg.rs
- src/frontend/src/optimizer/plan_node/stream_sink.rs
- src/frontend/src/optimizer/plan_node/stream_stateless_simple_agg.rs
- src/frontend/src/optimizer/plan_node/stream_temporal_join.rs
- src/frontend/src/optimizer/plan_node/stream_topn.rs
- src/frontend/src/optimizer/plan_node/stream_union.rs
- src/frontend/src/optimizer/property/stream_kind.rs
- src/frontend/src/optimizer/rule/stream/separate_consecutive_join_rule.rs
Motivation: #22799.
Following #22798, this PR introduces `Upsert` stream kind and reject it in many cases when an operator does not support processing `Upsert` stream as input.
For now, the only source of `Upsert` stream is the `Source` operator for sources that are not append-only. However, since users are not allowed to create bare upsert `SOURCE` currently, but always materializing them with a `TABLE`, there's still no hit for the rejection path.
<details>
</details>
> refactor(optimizer): introduce `Upsert` stream kind & reject it in many cases

- src/connector/src/sink/snowflake_redshift/redshift.rs
- updates Redshift sink to use `VARCHAR(MAX)` instead of `VARCHAR` for the following data types: `Varchar`, `Jsonb`, Internal columns like `__ROW_ID`
<details>
</details>
> fix(redshift): update VARCHAR to VARCHAR(MAX) for compatibility

- dashboard/components/TimeControls.tsx
- dashboard/lib/api/streamingStats.ts
- dashboard/lib/utils/timeUtils.ts
- dashboard/pages/fragment_graph.tsx
- dashboard/pages/relation_graph.tsx
- src/meta/src/dashboard/mod.rs
90% written by LLM.
Added time-based controls to the dashboard for viewing historical metrics data. This feature allows users to:
1. Specify a timestamp to view metrics at a specific point in time
2. Set a time offset for rate calculations (throughput, backpressure)
The implementation includes:
- A new `TimeControls` component with timestamp and offset inputs
- Time utility functions for parsing and formatting timestamps
- Backend support for time-based parameters in Prometheus queries
- Integration with fragment and relation graph pages
This enhancement …
> feat(dashboard): support querying historical backpressure

- src/stream/src/executor/mview/materialize.rs
The materialize executor had redundant deserialization issues:
In `ConflictBehavior::Overwrite` and `DoUpdateIfNotNull:` Rows were deserialized for conflict resolution, then serialized to Bytes for `ChangeBuffer` storage, and need to be deserialized again during generate_output
This caused unnecessary performance overhead due to repeated serialization/deserialization cycles
This pr modified `ChangeBuffer` to  store `OwnedRow` instead of `Bytes` to eliminate redundant deserialization.
Although doing so may take up a little more memory, it is worth it here, and …
> refactor(on conflict): optimize materialize executor by storing `OwnedRow` in `ChangeBuffer`

- src/common/src/config/mod.rs
- src/common/src/config/streaming.rs
- src/stream/src/executor/now.rs
- src/stream/src/from_proto/now.rs
add a `stream_now_progress_ratio` to decouple now timestamp from the epoch timestamp to avoid introducing excessive changes within one epoch from dynamic filter
``` rust
// stream_now_progress_ratio must be set > 1.0, otherwise it will be ignore
let adjusted_timestamp = prev_now_timestamp + barrier_interval_ms * stream_now_progress_ratio;
let now_timestamp = min(adjusted_timestamp, epoch_timestamp);
```
This pull request introduces enhancements to the `NowExecutor` by adding support for a configurable `progress_ratio` to adjust timestamp progression …
> feat: decouple streaming now timestamp and epoch

- src/frontend/src/binder/expr/function/builtin_scalar.rs
Previously when we declare builtin scalar function, we use `guard_by_len` to pre-check the number of parameters. We pass the number of a parameter, and when later access the parameters, we get each parameter via a vec of parameters.
In this PR, we will change to specify the expected number of parameter by a static const. We can declare the builtin function as `guard_by_len(|binder, [arg0, arg1]| {...}`, where the parameters are in a fixed size array, and the length is specified inherently, and we can access each parameter directly by doing pattern match. …
> refactor(frontend): use const size array guard_by_len in builtin scalar function

- .github/workflows/copilot-setup-steps.yml
Created a new runner with 16 core, 64 gb memory, and 600 gb SSD for Copilot agent:
https://github.com/organizations/risingwavelabs/settings/actions/github-hosted-runners/1
to avoid
(#23014)
<details>
</details>
> chore:  use a larger runner for copilot agent

- dashboard/pages/relation_graph.tsx
- e2e_test/dashboard/create_graph.slt.part
- e2e_test/dashboard/drop_graph.slt.part
- proto/meta.proto
- src/meta/src/dashboard/mod.rs
Previously we only mapped fragment backpressure edges if they are between stream scan (input) and mv/table/index (output).
However, this fails to consider `sink into table`. This is because the input for sink into table to the destination table is not `stream scan`, it's currently a merge and project.
In this PR we directly do a `fragment -> relation` mapping, rather than maintain two separate maps for input and output.
On the frontend, we can simply filter out intra-node mappings, by checking whether after performing the `fragment->relation` mapping, the …
> fix(dashboard): fix fragment to relation backpressure edge mapping

- src/compute/tests/cdc_tests.rs
- src/meta/src/barrier/cdc_progress.rs
- src/stream/src/executor/backfill/cdc/cdc_backill_v2.rs
This PR fixes 2 issues introduced by #22943:
1. Two unit tests fail because #22943 introduces a new filtering logic by CDC offset, but 
- The existing `MockExternalTableReader` and `MockOffsetGenExecutor` doesn't fit these 2 tests out-of-box. 
- More importantly, the filtering logic may be [incorrect](https://github.com/risingwavelabs/risingwave/pull/22503#discussion_r2315818706).
- So This PR **disables the new filtering logic for now**.
2. The meta node with MySQL meta store fails to start due to a SUM returning decimal and being unable to cast to i64. …
> fix(meta): fix meta store compatibility issue

- e2e_test/streaming/now_semi_join.slt
- src/frontend/planner_test/tests/testdata/output/expr.yaml
- src/frontend/planner_test/tests/testdata/output/generate_series_with_now.yaml
- src/frontend/planner_test/tests/testdata/output/nexmark_temporal_filter.yaml
- src/frontend/planner_test/tests/testdata/output/predicate_pushdown.yaml
- src/frontend/planner_test/tests/testdata/output/share.yaml
- src/frontend/planner_test/tests/testdata/output/temporal_filter.yaml
- src/frontend/src/optimizer/plan_node/generic/project.rs
- src/frontend/src/optimizer/plan_node/logical_agg.rs
The function `NOW()` is often used in combination with `extract` or `date_trunc`. Although the output of `NOW()` changes every barrier, the final output may rarely change. We should eliminate no-op updates for it to avoid triggering recalculation for downstream as much as possible.
For simplicity, this PR sets the hint flag for all `Project` whose input is `Now`. There could be some false positives, like `Add` or `Subtract` on the `NOW()` timestamp, but it doesn't seem to be harmful.
A similar issue was initially raised in …
> feat(optimizer): set `noop_update_hint` for `Project` after `Now`

- e2e_test/ddl/alter_table_column_type/empty_struct.slt
- src/common/src/array/struct_array.rs
- src/common/src/types/mod.rs
- src/common/src/types/struct_type.rs
- src/common/src/util/value_encoding/column_aware_row_encoding.rs
When introducing support for `ALTER TYPE` for columns with composite (`struct`) types, we introduced a new field `field_ids` for `struct` data type (https://github.com/risingwavelabs/risingwave/pull/20620), to differentiate between the old and new encoding.
However, by using `repeated` field in protobuf, we cannot distinguish between "unset" (`None`) and "set with empty list" (`Some([])`), which leads to some confusion when handling empty struct. We didn't treat this a problem, as we don't provide official support for empty struct since our parser doesn't …
> feat: treat empty(zero-field) struct as alterable

- src/compute/src/lib.rs
- src/compute/src/server.rs
Issue: #21635
The `compute_node_serve` future in the compute crate was previously exceeding Clippy’s `large_futures` threshold (16 KB).
This was primarily due to:
- Large configuration and options structs (`ComputeNodeOpts`, `Config`) being captured across multiple .awaits.
- `StateStoreImpl::new` producing a very large intermediate future that was stored inline in the outer state machine.
**Changes**
- Wrapped the `compute_node_serve` opts argument in Arc to prevent a ~384 B struct from being embedded in every suspend variant.
- Wrapped the loaded …
> fix(compute): reduced compute_node_serve future size

- e2e_test/sink/sink_into_table/alter_column.slt
- src/frontend/src/handler/alter_table_column.rs
Allows alter operations on tables that have incoming sinks and generated_columns.
<details>
</details>
> fix(sink): Relax some alter table column conditions

- src/stream/src/executor/filter.rs
- src/stream/src/executor/mod.rs
- src/stream/src/executor/watermark_filter.rs
- src/stream/src/from_proto/filter.rs
Background:
- #22799 
- #22902 
As discussed in #22856, it appears that the behavior of `Filter` executor when handling upsert stream should differ from when handling retractable stream. Specifically, we should
- always yield `Delete` records on `Delete` (or `UpdateDelete`) input, regardless of the filter result, to ensure the existing record (if any) can be cleaned up
- always yield `Delete` records on `Insert` (or `UpdateInsert`) input when the filter result is `false`, to ensure the existing record (if any) can be cleaned up
See more details in code and …
> feat(streaming): introduce upsert behavior for filter executor

- Cargo.lock
- src/connector/Cargo.toml
Tested on AWS ElasticCache (Redis OSS). Now we can use both `redis` and `rediss` protocl to connect to redis.
<details>
Support redis tls via `rediss` protocol
</details>
> feat(sink): support redis sink tls

- src/stream/src/executor/top_n/group_top_n_appendonly.rs
- src/stream/src/executor/top_n/top_n_state.rs
See https://github.com/risingwavelabs/risingwave/issues/23263#issuecomment-3311630206 for details.
The high part of the append only group top N cache should always be empty so calling storage iter next is wasteful.
<details>
</details>
> feat: avoid populating the high part of append-only group topn cache

- src/connector/src/sink/sqlserver.rs
Sql Server Sink uses MERGE keyword to implement UPSERT. Since the non-atomic nature of the MERGE, a MERGE designed to upsert a single row can cause a deadlock.
This PR fixes the bug by adding the HOLDLOCK hint, telling SQL Server to take and hold a stronger lock during the initial read phase and not release it until the entire transaction is complete.
<details>
</details>
> fix(connector): fix sql server sink deadlock

- e2e_test/batch/functions/trim.slt.part
- src/expr/impl/src/scalar/trim.rs
- src/tests/regress/data/sql/strings.sql
- Support `trim`, `ltrim`, `rtrim` function on bytea type
- Part of #8831.
Support `trim` syntax: 
- trim ( [ LEADING | TRAILING | BOTH ] bytesremoved bytea FROM bytes bytea ) → bytea
- trim ( [ LEADING | TRAILING | BOTH ] [ FROM ] bytes bytea, bytesremoved bytea ) → bytea
- btrim ( bytes bytea, bytesremoved bytea ) → bytea
- ltrim ( bytes bytea, bytesremoved bytea ) → bytea
- rtrim ( bytes bytea, bytesremoved bytea ) → bytea
<details>
Support `trim`, `ltrim`, `btrim` and `rtrim` function on bytea type
</details>
> feat(frontend): support `trim`, `ltrim`, `rtrim` function on bytea type
