src/meta/src/stream/stream_manager.rs
As title, this happens because of stopping the mock compute service during checkpoint. The barrier manager will enter recovery mode. This PR is a quick fix on this test, and `test_create_materialized_view` is outdated which need refactor.
Resolve https://github.com/singularity-data/risingwave/issues/1722
=> fix: quick fix for create mv ut timeout

.github/workflow-template/jobs/e2e-source.yml, .github/workflows/main.yml, .github/workflows/pull-request.yml
As title, to solve frequent timeout.
=> chore(ci): remove setup kafka step

e2e_test/v2/batch_distributed/tpch.slt
=> test: Add tpch q7 for batch distributed query

.github/workflow-template/jobs/e2e-risedev.yml, .github/workflow-template/jobs/e2e-source.yml, .github/workflows/main.yml, .github/workflows/pull-request.yml, CONTRIBUTING.md, e2e_test/v2/batch/aggregate/avg.slt, e2e_test/v2/batch/aggregate/count.slt, e2e_test/v2/batch/explain.slt, e2e_test/v2/batch/float_ord.slt, e2e_test/v2/batch/insert_expr.slt, e2e_test/v2/batch/join.slt, e2e_test/v2/batch/modify.slt, e2e_test/v2/batch/query.slt, e2e_test/v2/batch/tpch.slt, e2e_test/v2/batch/types/decimal.slt, e2e_test/v2/batch_distributed/aggregate/avg.slt, e2e_test/v2/batch_distributed/aggregate/count.slt, e2e_test/v2/batch_distributed/float_ord.slt, e2e_test/v2/batch_distributed/insert_expr.slt, e2e_test/v2/batch_distributed/modify.slt, e2e_test/v2/batch_distributed/tpch.slt, e2e_test/v2/batch_distributed/types/decimal.slt, src/frontend/src/handler/mod.rs, src/frontend/src/handler/query.rs, src/frontend/src/handler/query_single.rs, src/frontend/src/handler/set.rs, src/frontend/src/session.rs
Note this is just a simple beginning of [support set comand](https://github.com/singularity-data/risingwave/issues/1219). There are still a lot of todos: better config init policy, how to handle system level config/consistency of change config, how to persist config, better API design (Builder code patterns or possible generic to make the code pretty). I'd like to distribute the tasks to anyone who are interested in the project. Java's design looks good:
https://github.com/singularity-data/risingwave/blob/8a7c9718dc97eaaede84c1be5a107944a69835e1/legacy/common/src/main/java/com/risingwave/common/config/ConfigEntry.java#L11-L27
But I do not found properly crates to help me and a little overdesign (This part of java code is hard to translate to Rust), so I leave it simple.
The main goal is …
=> feat(session-config): introduce entry-level pure in-memory set configuration

src/utils/pgwire/src/pg_server.rs
1. Do not print unexpected eof as error to log.
Now when start fe, it will show (the wait TCP connection will always be the first open-and-closed connection):
```
2022-04-11T08:02:56.081101Z  INFO pgwire::pg_server: Server Listening at 127.0.0.1:4566
2022-04-11T08:02:56.107196Z  INFO pgwire::pg_server: New connection: 127.0.0.1:65275
2022-04-11T08:02:56.107395Z  INFO pgwire::pg_server: Connection 127.0.0.1:65275 closed
```
=> fix(fe-server): do not print unexpected eof as error to log

src/meta/src/barrier/mod.rs, src/meta/src/barrier/recovery.rs
As title, using retry category for operation in recovery rather than simple loop and add retry interval for `reset_compute_nodes`.
=> feat: apply retry category when recovery

src/meta/src/barrier/recovery.rs
As title, missing naming fix of https://github.com/singularity-data/risingwave/pull/1768.
=> chore(meta): fix retry strategy naming

e2e_test/streaming/extreme_null.slt
We have no assumption about the order of inserted rows.
- https://github.com/singularity-data/risingwave/runs/5970211767?check_suite_focus=true
=> test(streaming): fix order assumption in `extreme_null`

src/common/src/alloc.rs, src/common/src/buffer/bitmap.rs, src/common/src/buffer/buffer_.rs, src/common/src/buffer/mod.rs, src/frontend/src/binder/expr/subquery.rs, src/frontend/src/binder/window_table_function.rs, src/frontend/src/handler/set.rs, src/frontend/src/meta_client.rs, src/frontend/src/scheduler/execution/mod.rs, src/frontend/src/scheduler/execution/query.rs, src/frontend/src/scheduler/execution/stage.rs, src/frontend/src/scheduler/query_manager.rs, src/source/src/connector_source.rs, src/storage/benches/bench_block_iter.rs, src/stream/src/executor_v2/batch_query.rs, src/stream/src/executor_v2/hop_window.rs, src/stream/src/executor_v2/receiver.rs, src/stream/src/executor_v2/top_n.rs, src/stream/src/executor_v2/top_n_appendonly.rs, src/stream/src/executor_v2/top_n_executor.rs, src/utils/pgwire/src/error.rs
Add missing headers.
Will fix the checker action in the next PR.
=> chore: add missing license headers

src/frontend/src/scheduler/execution/query.rs, src/frontend/src/scheduler/execution/stage.rs
Fix a bug which may lead to schedule failure.
Closes #1723
=> fix: Fix distributed query manager bug

.github/workflow-template/pr-override.yml, .github/workflows/pull-request.yml, CONTRIBUTING.md, bors.toml
TL;DR: use `bors try` on contributors' PR to run tests.
close https://github.com/singularity-data/risingwave/issues/1727
=> chore(ci): use bors try for contributors

src/stream/src/executor_v2/agg.rs, src/stream/src/executor_v2/global_simple_agg.rs, src/stream/src/executor_v2/hash_agg.rs, src/stream/src/executor_v2/local_simple_agg.rs
The relation between `Executor` and `AggExecutor` are combinations, not inheritance, so no structure should implement them both.
=> refactor(stream): refine AggExecutor and Executor

.github/workflows/license_check.yml
As title
fix https://github.com/singularity-data/risingwave/issues/1797
=> fix(ci): checkout code before license check

src/meta/Cargo.toml, src/meta/src/model/mod.rs, src/meta/src/rpc/service/ddl_service.rs, src/meta/src/rpc/service/stream_service.rs, src/meta/src/stream/fragmenter.rs, src/meta/src/stream/graph/fragment_graph.rs, src/meta/src/stream/graph/stream_graph.rs, src/meta/src/stream/test_fragmenter.rs
Previously, we only supports a tree-like fragment graph. Now we refactor it to support any DAG.
* Use topology sort to construct actors from fragments.
* Fully support multi-dispatcher per fragment / per actor.
* Differentiate local actor id and global actor id, generate all ids in batch.
close https://github.com/singularity-data/risingwave/issues/1751
=> refactor(meta): support DAG fragment graph

risedev.yml, scripts/source/docker-compose.yml, src/meta/src/rpc/service/ddl_service.rs
- Fix #1805 
- Fix scripts/source/docker-compose.yml
close #1805
=> fix: fill source id before creating source in compute node

src/stream/src/executor/debug/mod.rs, src/stream/src/executor/debug/update_check.rs, src/stream/src/executor/hash_join.rs, src/stream/src/task/stream_manager.rs
When there're multiple rows matched with a single `UpdateDelete`, the hash join executor will yield multiple continuous `UpdateDelete`s, which violates the assumption of U+ after U- used by `Merge`, `Filter` and so on. One can simply reproduce this in tpch q17, q18 with rearranged chain in #1556 since it introduces more barriers than before.
- Close #1801
=> fix(streaming): avoid violating the assumption of U+ after U- in hash join & add checker

src/common/src/array/stream_chunk.rs, src/common/src/array/stream_chunk_iter.rs, src/stream/src/executor/debug/update_check.rs, src/stream/src/executor_v2/hop_window.rs, src/stream/src/lib.rs
=> refactor(stream): switch to RowRefV2

src/stream/src/executor/managed_state/top_n/top_n_state.rs, src/stream/src/executor_v2/agg.rs, src/stream/src/executor_v2/global_simple_agg.rs, src/stream/src/executor_v2/hash_agg.rs, src/stream/src/executor_v2/lookup.rs, src/stream/src/executor_v2/mod.rs, src/stream/src/executor_v2/top_n.rs, src/stream/src/executor_v2/top_n_appendonly.rs
It's impossible to implement `clear_cache` in `ExecutorV2`, we may investigate another way.
=> refactor(stream): remove Executor::clear_cache

src/batch/src/executor/stream_scan.rs, src/common/src/catalog/column.rs, src/common/src/catalog/schema.rs, src/frontend/Cargo.toml, src/frontend/src/binder/relation.rs, src/frontend/src/catalog/column_catalog.rs, src/frontend/src/catalog/source_catalog.rs, src/frontend/src/handler/create_mv.rs, src/frontend/src/handler/create_source.rs, src/frontend/src/handler/describe.rs, src/frontend/src/optimizer/plan_node/logical_agg.rs, src/frontend/src/optimizer/plan_node/logical_filter.rs, src/frontend/src/optimizer/plan_node/logical_join.rs, src/frontend/src/optimizer/plan_node/logical_project.rs, src/frontend/src/optimizer/plan_node/stream_materialize.rs, src/frontend/src/test_utils.rs
Since we cannot make query on source and need to create mv from source first, this pr support to create mv conclude struct column.
```
create materialized view mv1 as select t1.country as c from t1
```
Two main changes:
1. bind field_descs in ColumnDesc from SourceCatalog.
2. add sub_fields and type_name in Field used to into field_descs and type_name in ColumnDesc.
=> feat: add sub_fields in field to support create mv conclude struct column

src/stream/src/executor_v2/top_n.rs, src/stream/src/executor_v2/top_n_appendonly.rs, src/stream/src/executor_v2/top_n_executor.rs
=> refactor(stream): refine TopNExecutorBase

Makefile, docker/docker-compose.yml
Add docker-compose.yml.
This version is keep simple for verifying availability. It only setup necessary components such as `minio`, `metanode`, `computenode` and `frontend`.
Plan to add `Redpanda` later. Maybe refactor network configuration.
#1606
=> feat(docker): add docker-compose.yml

proto/stream_plan.proto, src/compute/tests/table_v2_materialize.rs, src/meta/src/stream/fragmenter.rs, src/stream/src/executor/hash_join.rs, src/stream/src/executor/mod.rs, src/stream/src/executor/mview/materialize.rs, src/stream/src/executor_v2/lookup.rs, src/stream/src/executor_v2/lookup/tests.rs, src/stream/src/executor_v2/mod.rs, src/stream/src/executor_v2/mview/materialize.rs, src/stream/src/executor_v2/v1_compat.rs, src/stream/src/task/stream_manager.rs
As title. The pseudo ArrangeNode is used to construct MaterializeExecutor (but without table id).
ref https://github.com/singularity-data/risingwave/issues/719
=> feat(streaming): add proto for lookup executor

src/frontend/src/scheduler/execution/stage.rs, src/frontend/src/scheduler/query_manager.rs, src/frontend/src/scheduler/worker_node_manager.rs
=> fix(frontend): avoid panic when no worker

src/batch/src/executor/create_source.rs
No CI workflow is relying on CreateSourceExecutor now, so I completely mark the methods as unreachable.
=> refactor: disable CreateSourceExecutor in batch mode

src/bench/ss_bench/main.rs, src/bench/ss_bench/operations/mod.rs, src/bench/ss_bench/operations/write_batch.rs, src/compute/src/server.rs, src/storage/src/hummock/compactor.rs, src/storage/src/hummock/compactor_tests.rs, src/storage/src/hummock/local_version_manager.rs, src/storage/src/hummock/mod.rs, src/storage/src/hummock/shared_buffer/shared_buffer_manager.rs, src/storage/src/hummock/shared_buffer/shared_buffer_uploader.rs, src/storage/src/hummock/snapshot_tests.rs, src/storage/src/hummock/sstable_store.rs, src/storage/src/hummock/state_store_tests.rs, src/storage/src/hummock/test_utils.rs, src/storage/src/storage_failpoints/test_hummock.rs, src/storage/src/store_impl.rs
Lift `LocalVersionManager::pick_few_tables` to `SstableStore::sstables`, then in turn removing some unnecessary references in `LocalVersionManager`, `CompactorContext` and `SharedBufferUploader`.
=> refactor(storage): remove unnecessary ref to local_version_manager

.github/workflow-template/jobs/e2e-risedev.yml, .github/workflows/main.yml, .github/workflows/pull-request.yml, src/stream/src/executor_v2/mod.rs
As title. After #1556 and #1811 is merged, let's see whether we can successfully switch to `RearrangedChain`. 😢
This PR also removes no-cache e2e tests since all of the executor v2s are not able to clear cache now. Besides, the clear-cache of v1 `HashJoin` has also been disabled due to known issues in #1540.
=> chore(streaming): switch to rearranged chain & remove no-cache e2e

proto/stream_plan.proto, src/meta/src/model/stream.rs, src/meta/src/stream/fragmenter.rs, src/meta/src/stream/graph/fragment_graph.rs, src/meta/src/stream/graph/stream_graph.rs, src/meta/src/stream/rewrite/delta_join.rs, src/meta/src/stream/rewrite/mod.rs, src/meta/src/stream/scheduler.rs, src/meta/src/stream/stream_manager.rs
* Remove `ExchangeNode` before fragment -> actor stage. As now fragments might have multiple dispatchers, information of exchange node is not useful anymore. Dispatch strategy is now recorded in FragmentEdge.
* Prepare for actor placement rule implementation. We need to ensure some actors stay on the same worker node. Now we add this field, set this field according to FragmentEdge. Will later add logic to enforce such rule.
ref https://github.com/singularity-data/risingwave/issues/719
=> feat(meta): actor placement rule and dispatcher refactor

src/stream/src/executor/managed_state/top_n/top_n_state.rs
`ManagedTopNState` currently only guarantees that a single write batch does not include two same keys, however, it is required that all the write batches of a single epoch must not include two writes with the same keys.
This PR buffers the rows inserted(one particular branch) into the flush buffer instead of writing them down into the storage directly.
closes #1841
=> fix(streaming): do not write batch for a single insert in ManagedTopNState

src/common/src/array/stream_chunk_iter.rs, src/stream/src/executor_v2/hop_window.rs, src/stream/src/executor_v2/top_n.rs, src/stream/src/executor_v2/top_n_appendonly.rs
As title. So that there's no need to compact the stream chunk.
- #1839
=> refactor(streaming): use row iterator of `StreamChunk` in top-n

src/frontend/src/expr/mod.rs, src/frontend/src/expr/utils.rs, src/frontend/src/optimizer/plan_node/batch_filter.rs, src/frontend/src/optimizer/plan_node/logical_join.rs, src/frontend/src/optimizer/plan_node/stream_filter.rs, src/frontend/src/utils/condition.rs
As title. Follow up to #1816 
I think `impl From<&T>` is not very common, especially when there's `impl FROM<T>`. Replace it's usage with a `clone`
=> refactor(frontend/expr): remove impl From<&Condition> for ExprImpl

src/batch/src/task/hash_shuffle_channel.rs, src/common/src/array/data_chunk.rs, src/common/src/hash/key.rs, src/common/src/util/ordered/serde.rs, src/storage/src/storage_value.rs, src/storage/src/write_batch.rs, src/stream/src/executor/managed_state/aggregation/extreme.rs, src/stream/src/executor/managed_state/aggregation/mod.rs, src/stream/src/executor_v2/agg.rs, src/stream/src/executor_v2/global_simple_agg.rs, src/stream/src/executor_v2/hash_agg.rs
- Summarize your change 
- Support value meta in hash agg executor v2.
- Introduce `HashCode` struct to bypass async closure problem.
=> feat(streaming): support value meta in hash agg

proto/meta.proto, proto/stream_plan.proto, src/common/src/hash/dispatcher.rs, src/meta/src/manager/hash_dispatch.rs, src/meta/src/model/hash_mapping.rs, src/storage/src/hummock/value.rs, src/storage/src/storage_value.rs, src/stream/src/executor/dispatch.rs, src/stream/src/executor/managed_state/aggregation/extreme.rs
- Summarize your change 
- Rename `consistent_hash_value` to `vnode`
- Rename `VirtualKey` to `VirtualNode`
- Set the number of total virtual node as 65536 (previously 2048)
=> chore(streaming): rename consistent hash related value to vnode

src/common/src/hash/dispatcher.rs, src/storage/src/hummock/value.rs, src/stream/src/executor/dispatch.rs
- Change virtual node number from 65536 back to 2048.
- Format code in `value.rs`.
The change of virtual node number is just a workaround, since 65536 is too large for a gRPC message. We could use some other strategies later to encode long array and then enable 65536.
=> chore: change vnode number and fix code format

src/stream/src/executor_v2/global_simple_agg.rs
Signed-off-by: Zulai Wang <zl31wang@gmail.com>
As title.
#1886
=> refactor(streaming): implement GlobalSimpleAgg without AggExecutor

src/source/src/connector_source.rs, src/source/src/high_level_kafka.rs, src/source/src/manager.rs, src/source/src/parser/mod.rs
=> refactor: use enum to dispatch SourceParser types

src/stream/src/executor/dispatch.rs, src/stream/src/executor/integration_tests.rs, src/stream/src/task/stream_manager.rs
As title
close https://github.com/singularity-data/risingwave/issues/865
ref https://github.com/singularity-data/risingwave/issues/719
=> feat(streaming): support multiple dispatchers on compute node

src/frontend/src/optimizer/plan_node/logical_agg.rs, src/frontend/test_runner/tests/testdata/basic_query_2.yaml
Previously, only `InputRef`s are allowed in the `group by` expression. This pr adds support for complex expressions in the `group by`. 
Note that it seems that the current code already supports complex expressions in `group by`, so I only change the error code and the condition. Other chores like comment improvement and typo fix are also included in this pr.
This pr resolves #1637.
=> feat(frontend): support complex expr in group by

src/frontend/test_runner/tests/testdata/tpch.yaml
* If batch / stream plan is already available, remove logical_plan.
* For logical_plan w/o correlated subquery, prefer optimized_logical_plan.
=> chore(frontend): prefer optimized_logical_plan in planner test

proto/stream_plan.proto, src/meta/src/stream/fragmenter.rs, src/meta/src/stream/graph/fragment_graph.rs, src/meta/src/stream/rewrite/delta_join.rs, src/stream/src/executor/mview/materialize.rs, src/stream/src/executor_v2/lookup.rs, src/stream/src/executor_v2/lookup/sides.rs, src/stream/src/task/mod.rs, src/stream/src/task/stream_manager.rs
Refactor meta to allow lookup executor to scan from arrangements. We store a fragment_id in lookup stream node.
close https://github.com/singularity-data/risingwave/issues/719
=> feat(streaming): enable lookup to scan from arrange keyspace

src/batch/src/executor/join/nested_loop_join.rs, src/batch/src/executor/join/sort_merge_join.rs, src/common/src/array/data_chunk.rs, src/common/src/array/data_chunk_iter.rs, src/common/src/array/list_array.rs, src/common/src/array/struct_array.rs, src/common/src/types/mod.rs, src/common/src/util/chunk_coalesce.rs, src/common/src/util/ordered/mod.rs, src/common/src/util/ordered/serde.rs, src/frontend/src/handler/util.rs, src/stream/src/common/builder.rs, src/stream/src/executor/hash_join.rs, src/stream/src/executor_v2/lookup/impl_.rs, src/stream/src/executor_v2/top_n_executor.rs
This PR introduces a zero-cost row-iterator for `DataChunk`, like what we did in #1818.
https://github.com/singularity-data/risingwave/blob/62fb15b87f1ccbf97fb8f61554862a3eb7b722c7/src/common/src/array/data_chunk_iter.rs#L28-L41
There're lots of usages that rely on "the `RowRef` is a vector of datum refs". In fact, this assumption is unnecessary and in most of the cases, they are just requiring an iterator of `DatumRef`s. This PR also refactors them and avoids the allocation as much as possible.
- Close #1840.
=> feat(array): introduce zero-cost data chunk row-iterator

grafana/risingwave-dashboard.json, src/storage/src/hummock/value.rs
- put all compaction metrics into a grafana graph
=> chore(compaction): put all compaction metrics into a grafana graph

.github/workflow-template/jobs/e2e-risedev.yml, .github/workflow-template/jobs/e2e-source.yml, .github/workflows/main.yml, .github/workflows/pull-request.yml
Due to Rust toolchain not present, cargo make will stuck on setup env for a minute. This PR fixes the issue.
=> chore(ci): fix slow playground prepare

Cargo.lock, src/batch/Cargo.toml, src/batch/src/executor/executor2_wrapper.rs, src/batch/src/executor/mod.rs, src/batch/src/executor/test_utils.rs, src/batch/src/executor2/executor_wrapper.rs, src/batch/src/executor2/filter.rs, src/batch/src/executor2/mod.rs, src/batch/src/executor2/trace.rs, src/batch/src/lib.rs
1. Implement `Executor2` using `Stream`.
2. Implement `Filter` using `Executor2` trait.
3. Some infra for refactoring.
Closes #1190
=> refactor(batch): Use `futures-async-stream` to implement batch executor.

src/frontend/src/expr/type_inference.rs
* Organize exprs into groups: logical, comparison, arithmetic, temporal, string.
* According to pg, the order of `num_types` should be `int2->int4->int8->numeric->float4->float8`.
* Remove unnecessary helper functions. It is actually shorter and more readable without them. For example `build_binary_funcs` produces all combinations of `exprs * arg1 * arg2` and requires the return types to be the same, which is only useful for `cmp`.
* Implicit cast on operands are still not supported yet.
=> refactor(frontend): cleanup infer_type and align with pg

CONTRIBUTING.md
=> docs: add instructions of starting playground with `cargo run`

src/storage/benches/bench_merge_iter.rs, src/storage/src/hummock/compactor.rs, src/storage/src/hummock/iterator/merge.rs, src/storage/src/hummock/iterator/merge_inner.rs, src/storage/src/hummock/iterator/mod.rs, src/storage/src/hummock/iterator/reverse_merge.rs, src/storage/src/hummock/iterator/reverse_user.rs, src/storage/src/hummock/iterator/test_utils.rs, src/storage/src/hummock/iterator/user.rs, src/storage/src/hummock/state_store.rs, src/storage/src/hummock/test_utils.rs
Remove all the lifetime associated with iterators defined in Hummock.
This PR conflicts with PR #1928 on `use XXX` statements only at one location. It seems #1928 is ready and this PR will wait for it to be merged first.
After this refactoring, we can bound the trait `StateStoreIter` by `'static`. This will bypass the compiler limitation described in #1930 when `Send` is used to bound `NextFuture` in `StateStoreIter`.
#1930
=> refactor(storage): remove lifetime on iterators

src/storage/src/table/mem_table.rs, src/storage/src/table/mod.rs, src/storage/src/table/state_table.rs
As described in doc [Relational State Store Layer](https://singularity-data.quip.com/J4JuAK9aSaYQ/RFC-Relational-State-Store-Layer-for-Stream-ExecutorWIP), this PR defines IO interfaces of `StateTable` and `MemTable`.
=> chore(relational_state_store): define interfaces of relational layer

src/storage/src/hummock/state_store.rs, src/storage/src/memory.rs, src/storage/src/monitor/monitored_store.rs, src/storage/src/panic_store.rs, src/storage/src/rocksdb_local.rs, src/storage/src/rocksdb_local_mock.rs, src/storage/src/store.rs, src/storage/src/tikv.rs, src/storage/src/tikv_mock.rs
As title.
Related details can be found in the issue #1930 and PR #1956. 
In essence, we need this `Send` bound to use iter in some async functions.
closes #1930
=> refactor(storage): add Send bound to NextFuture in StateStoreIter

src/stream/src/executor/actor.rs, src/stream/src/executor/dispatch.rs, src/stream/src/executor/integration_tests.rs, src/stream/src/executor/mod.rs, src/stream/src/executor_v2/mod.rs, src/stream/src/task/stream_manager.rs
=> refactor(streaming): use async stream for dispatcher

.github/workflow-template/jobs/e2e-risedev.yml, .github/workflows/main.yml, .github/workflows/pull-request.yml, src/batch/src/executor/delete.rs, src/batch/src/executor/insert.rs, src/compute/tests/table_v2_materialize.rs, src/connector/src/base.rs, src/connector/src/filesystem/s3/s3_dir.rs, src/connector/src/filesystem/s3/source/s3_file_reader.rs, src/connector/src/kafka/source/reader.rs, src/connector/src/kinesis/source/reader.rs, src/connector/src/pulsar/source/reader.rs, src/connector/src/utils.rs, src/source/src/connector_source.rs, src/source/src/lib.rs, src/source/src/manager.rs, src/source/src/table_v2.rs, src/stream/Cargo.toml, src/stream/src/executor/source.rs
This PR fixes the `create materialized view from source` feature
It is now possible to `create materialized views` from the rust frontend 
However, the state storage of the source executor is not currently handled and requires a PR from @tabVersion  to complete
Since we need to start the whole MV with the first barrier, we modified `/src/compute/tests/table_v2_materialize.rs` to inject the first barrier
=> feat: make `create materialized view from source` available

scripts/source/docker-compose.yml
we do not rely on `confluentinc/cp-kafkacat`, roll back to `edenhill/kafkacat:1.6.0`
=> chore: fix docker compose dependencies

src/stream/src/executor/source.rs
=> fix: use random instead of sleep

src/meta/src/rpc/service/ddl_service.rs, src/meta/src/rpc/service/stream_service.rs, src/meta/src/stream/fragmenter.rs, src/meta/src/stream/graph/stream_graph.rs, src/meta/src/stream/stream_manager.rs, src/meta/src/stream/test_fragmenter.rs
In the current implementation, fragmenter will create a one-on-one mapping of parallel unit with downstream actor id, which may be inconsistent with the actual scheduled location of downstream actor. This PR removed hash mapping related logic in fragmenter and assign hash mapping after fragments scheduled.
used by #1875
=> refactor(meta): use scheduled parallel unit in dispatcher's hash mapping

src/storage/src/cell_based_row_deserializer.rs, src/storage/src/keyspace.rs, src/stream/src/executor/managed_state/flush_status.rs, src/stream/src/executor/managed_state/top_n/mod.rs, src/stream/src/executor/managed_state/top_n/top_n_bottom_n_state.rs, src/stream/src/executor/managed_state/top_n/top_n_state.rs
Use `iter` instead of `scan` in TopNExecutor as we don't know exactly how many kv pairs we need to scan from Hummock.
Add a `StripPrefixIterator` to get rid of the prefix in the keyspace.
Add a `reset` method to `CellBasedRowDeserializer` to clear `pk_bytes` when we need to use it repetitively across different inputs.
=> refactor(stream, storage): use iter in TopNExecutor

src/expr/src/expr/expr_binary_nonnull.rs
The macro `gen_binary_expr_atm` currently list certain combinations of temporal types, e.g. `timestamp_timestamp_f`, `timestamp_interval_f`. This makes it harder to add more temporal operators as their signatures are not that regular compared to numbers. It makes less sense to reuse them across `add`/`sub`/`mul`/`div`. For details, check the pg operator table below.
This PR allows `gen_binary_expr_atm` to pass thru a list to `gen_atm_impl` directly, so that different operators (`add`/`sub`/`mul`/`div`) can add their own implementations without touching the definition of `gen_binary_expr_atm` any more.
```
lhs     | oprname |     rhs     | ?column? |     ret     |         oprcode         
-------------+---------+-------------+----------+-------------+-------------------------
float8      | …
```
=> refactor(expr): decouple macro gen_binary_expr_atm from temporal operator signatures

src/meta/src/barrier/info.rs, src/meta/src/barrier/mod.rs
After investigation the bug mentioned in #1995 and reported in slack group, this bug is caused by injecting a barrier immediately after a quick checkpoint when there's no actors exist in the cluster. This means two equal epoch might generated and fail the epoch check in this situation.
After this PR merged, we should introduce or develop a monotonic clock lib for epoch generation.
Resolve https://github.com/singularity-data/risingwave/issues/1995
=> fix: fix epoch check panic when checkpoint

e2e_test/v2/streaming/index.slt, src/frontend/src/handler/create_index.rs, src/frontend/src/handler/create_table.rs, src/frontend/src/handler/mod.rs, src/frontend/src/optimizer/mod.rs
```
create index index_1 on t(v1);
```
... has the same effect as:
```
create materialized view index_1 as select * from t order by v1;
```
close https://github.com/singularity-data/risingwave/issues/1909
=> feat(frontend): support create index

src/frontend/src/binder/expr/binary_op.rs, src/frontend/src/binder/expr/function.rs, src/frontend/src/binder/expr/mod.rs, src/frontend/src/expr/expr_rewriter.rs, src/frontend/src/expr/function_call.rs, src/frontend/src/expr/type_inference.rs, src/frontend/src/expr/utils.rs, src/frontend/src/optimizer/plan_node/logical_agg.rs, src/frontend/src/planner/relation.rs, src/frontend/test_runner/tests/testdata/expr.yaml
- `infer_type` returns `Err` rather than `None` so that callers do not need to construct errors with repeatedly.
- `FunctionCall` now has 3 constructors:
- `new` should be used in most cases. Return type is inferred.
- `new_cast` dedicates to create cast expression, which needs the "return_type" as input argument.
- `new_unchecked` constructs the struct directly bypassing type inference. Mainly for internal expr rewriting where inferring again is less desirable.
To handle in later PR: `CASE` and `IN` should be handled by `FunctionCall::new` rather than `new_unchecked`.
~~- [ ] I have added necessary unit tests and integration tests~~ (Refactor does not break existing tests.)
=> refactor(frontend): remove `FunctionCall::new_with_return_type` that bypass infer_type

src/stream/src/executor/hash_join.rs, src/stream/src/executor_v2/lookup.rs, src/stream/src/executor_v2/lookup/cache.rs, src/stream/src/executor_v2/lookup/impl_.rs, src/stream/src/executor_v2/lookup/sides.rs
e2e should be a lot faster. When we have multi-way join, we can move the cache to `ArrangeExecutor` and reimplement this in MVCC way.
close https://github.com/singularity-data/risingwave/issues/2045
=> feat(streaming): add cache for lookup

src/frontend/src/expr/agg_call.rs, src/frontend/src/expr/correlated_input_ref.rs, src/frontend/src/expr/function_call.rs, src/frontend/src/expr/input_ref.rs, src/frontend/src/expr/literal.rs, src/frontend/src/expr/mod.rs, src/frontend/src/expr/subquery.rs, src/frontend/src/optimizer/plan_node/batch_filter.rs, src/frontend/src/optimizer/plan_node/batch_project.rs, src/frontend/src/optimizer/plan_node/batch_values.rs, src/frontend/src/optimizer/plan_node/stream_filter.rs, src/frontend/src/optimizer/plan_node/stream_hash_join.rs, src/frontend/src/optimizer/plan_node/stream_hop_window.rs, src/frontend/src/optimizer/plan_node/stream_project.rs
Sometimes we need some raw proto message, e.g. `InputRefExpr`, it's better for each type to implement their own `to_proto`, and implement `to_expr_proto` to wrap them.
=> refactor(frontend): rename Expr::to_protobuf to Expr::to_expr_proto

src/meta/src/cluster/mod.rs, src/meta/src/hummock/hummock_manager.rs, src/meta/src/manager/catalog.rs, src/meta/src/manager/catalog_v2.rs, src/meta/src/manager/notification.rs
Add support for sending notifications asynchronously.
It is used where it is only necessary to ensure that the message will be sent, but not that the message must be sent successfully at the end of the method.
=> feat(meta): add support for sending notifications asynchronously

src/batch/src/executor/mod.rs, src/batch/src/executor2/limit.rs, src/batch/src/executor2/mod.rs
Signed-off-by: Fedomn <fedomn.ma@gmail.com>
Use futures-async-stream to refactor LimitExecutor
close https://github.com/singularity-data/risingwave/issues/1938
=> refactor(batch): Use futures-async-stream to implement limit executor

e2e_test/v2/streaming/index.slt, proto/stream_plan.proto, src/frontend/src/handler/create_index.rs, src/frontend/src/optimizer/mod.rs, src/frontend/src/optimizer/plan_node/stream_materialize.rs
As title
close https://github.com/singularity-data/risingwave/issues/2017
=> chore(frontend): distribute index by arrange key

src/storage/src/hummock/cache.rs
In this PR, we mainly finished two works
* Add some comments and do some simple refactor in the lru cache code to improve code readability.
* Add some `debug_assert` to ensure the correct usage on some unsafe methods.
* Fix the following bug.
In current code, in the `insert` of `LruCacheShard`
https://github.com/singularity-data/risingwave/blob/2027b1f1686eee2da853af2ba1edc2edcf3f1d3b/src/storage/src/hummock/cache.rs#L328-L336
we use `unwrap` after `self.remove_cache_handle(old)`. 
However, `remove_cache_handle` will return `None` when the handle is still referenced externally. 
https://github.com/singularity-data/risingwave/blob/2027b1f1686eee2da853af2ba1edc2edcf3f1d3b/src/storage/src/hummock/cache.rs#L385-L397
And therefore, if we first lookup a specific key and hold the handle, and …
=> refactor(lru cache): do some simple refactor and add some comments to improve code readability

.github/workflow-template/pr-override.yml, .github/workflows/pull-request.yml, CONTRIBUTING.md, bors.toml
This reverts commit 0055db322d529a97c7c99ac1c124a975c7ab1655.
bors doesn't work well, consider to trigger the CI manually as a workaround.
=> Revert "chore(ci): use bors try for contributors (#1784)"

Makefile.toml, proto/catalog.proto, src/frontend/src/catalog/table_catalog.rs, src/frontend/src/optimizer/plan_node/stream_materialize.rs
If `is_index` is true, then this table is actually an index.
I'm thinking of whether we need a separate `IndexCatalog` in the future. But for now, let's keep everything simple and just make it a special table.
close https://github.com/singularity-data/risingwave/issues/2015
close https://github.com/singularity-data/risingwave/issues/1908
=> feat(frontend): record index in catalog

src/meta/src/hummock/compaction.rs, src/meta/src/hummock/hummock_manager.rs, src/meta/src/hummock/hummock_manager_tests.rs, src/meta/src/hummock/metrics_utils.rs, src/storage/hummock_sdk/src/compact.rs, src/storage/src/hummock/compactor.rs
Fix incorrect compaction metrics due to changes in https://github.com/singularity-data/risingwave/pull/2062.
- `trigger_sst_stat` should read number of SSTs should from `HummockVersion` now.
=> fix(metrics): correct compaction metrics

Cargo.lock, src/meta/Cargo.toml, src/meta/src/stream/fragmenter/graph/fragment_graph.rs, src/meta/src/stream/fragmenter/graph/stream_graph.rs, src/meta/src/stream/fragmenter/mod.rs, src/meta/src/stream/fragmenter/rewrite/delta_join.rs
- Mutable states are split into `BuildFragmentGraphState` and `BuildActorGraphState`
The two stage of fragmenter is orthogonal, after splitting the mutable states into two places, what variables are mutated/referenced become more clear, and only `&self` is used for `StreamFragmenter`
- For the remaining fields, `XxManagerRef` can be used directly thus removed. `parallel_degree` and `is_legacy_frontend` are kept for simplicity
=> refactor(fragmenter): split fileds into different structs -- lose weight!

src/meta/src/stream/fragmenter/mod.rs
as title. The code are self-explanatory now, so they are not needed
=> chore(fragmenter): clean up some outdated/verbose comments

e2e_test/v2/streaming/time_window.slt
=> test(stream): add tumble window e2e test

proto/catalog.proto, src/frontend/src/binder/relation/table_or_source.rs, src/frontend/src/catalog/table_catalog.rs, src/frontend/src/handler/create_index.rs, src/frontend/src/optimizer/mod.rs, src/frontend/src/optimizer/plan_node/logical_scan.rs, src/frontend/src/optimizer/plan_node/mod.rs, src/frontend/src/optimizer/plan_node/stream_delta_join.rs, src/frontend/src/optimizer/plan_node/stream_materialize.rs, src/frontend/src/optimizer/plan_node/stream_table_scan.rs, src/frontend/src/optimizer/rule/index_delta_join.rs, src/frontend/src/optimizer/rule/mod.rs, src/frontend/src/planner/relation.rs, src/frontend/src/scheduler/plan_fragmenter.rs, src/frontend/test_runner/src/lib.rs, src/frontend/test_runner/tests/testdata/index.yaml
In this PR, we added a rule. If both children of stream hash join are indexed by join key (join key is the prefix of mv order key), then we use `StreamDeltaJoin` for this plan.
Table indexes are added to `BoundTable` when binding. In the future, we should optimize this.
The PR only implements the rule. What's going on underlying is still creating "delta join + arrange" nodes, instead of re-using the index. The re-using index part will be introduce later after next week's meeting.
close https://github.com/singularity-data/risingwave/issues/885
=> feat(frontend): generate delta join plan when index matches

src/meta/src/stream/stream_manager.rs
because ctx is consumed (thus splitted) here. (And in my opinion the large struct should not be passed later) 
In this way we can see clearer what is used/mutated 
=> refactor(meta): destruct create mv ctx in parameter site

.github/workflow-template/main-cron.yml, .github/workflow-template/main-override.yml, .github/workflow-template/template.yml, .github/workflows/main-cron.yml, .github/workflows/main.yml, .github/workflows/pull-request.yml, CONTRIBUTING.md
After this PR, EC2 for CI workflow will be created in the following way, which is [recommended by AWS officially](https://github.com/aws-actions/configure-aws-credentials#assuming-a-role).
1. GitHub Action servers use OIDC (OpenID Connect) to connect to AWS
2. AWS checks the request must be from this organization and this repo
3. AWS allocates a new short-term IAM account for this CI run only. It only lives for 1 hour.
4. The GitHub Action continues to execute other steps with this IAM account
After that, the community developer should be able to run CI easily. I'll test this later.
References:
1. https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
2. …
=> chore(ci): aws runner: switch to OIDC-based assuming role

src/frontend/src/handler/explain.rs
=> fix(frontend): explain should return distributed query plan

src/meta/src/hummock/compaction.rs
compact old ssts first in L0
about `must_l0_to_l0`: 
- when all levels are busy, we can only do L0 to L0 compaction, so `must_l0_to_l0` is set
- otherwise, we choose a level with highest priority to compact. If we chose L0, then we can decide whether to do a L0 to Ln (typically L1) or a L0 to L0 compaction, without force by `must_l0_to_l0`
=> feat(compaction): compact old ssts first in L0

src/risedevtool/src/task/etcd_service.rs
As title
workaround for https://github.com/singularity-data/risingwave/issues/2094
=> chore(risedev): set txn ops to unlimited

src/meta/src/stream/fragmenter/graph/stream_graph.rs, src/meta/src/stream/fragmenter/mod.rs, src/meta/src/stream/stream_manager.rs
Should resolve #2028  and #2032 . After this PR, different actors of same fragment should fix back to use same table id. And it do not introduce new round of StreamNode traverse.
<strike>
* Add a HashMap `table_ids_map` in fragmenter. (operator_id -> local table ids). It records the local table ids of each stateful operator. For cases that generate new operator
*  Exchange -> Dispatcher/Merge. They do not need table ids so it's safe.
* Delta Join rewrite. Might generate Arrange Executors, so if Delta Join needs table states it should update this map.
* When serialize StreamNode, get local table id from `table_ids_map` via operator id. Add the `start_table_id` and we get global table id.
</strike>
There will be a two-phase rewrite. First rewrite only write local table id into `StreamNode` …
=> refactor(state-store): Different actors should use the same table id

src/common/src/array/stream_chunk.rs
The doctests of `cargo test` fail to compile because the rename did not update comments.
#2089
=> fix(test): `StreamChunk::from_str` -> `from_pretty`

proto/stream_plan.proto, src/meta/src/stream/fragmenter/graph/stream_graph.rs, src/meta/src/stream/fragmenter/mod.rs, src/stream/src/executor/hash_join.rs
Previously I use TableRefId (wants to keep consistent with Materialize Executor), but it's too inconvenient to write code. 
Given that we wil remove `TableRefId` after Java frontend removed, replace it now.
=> refactor(proto): replace TableRefId to uint32 for HashJoin

src/config/risingwave.toml
Fix a mismatched configuration entry which is originated from https://github.com/singularity-data/risingwave/pull/1928
in risingwave.toml, it's 
```toml
shared_buffer_threshold_size = 268435456
```
, while in config.rs it's 
```rust
/// Size threshold to trigger shared buffer flush.
#[serde(default = "default::shared_buffer_threshold")]
pub shared_buffer_threshold: u32,
```
https://github.com/singularity-data/risingwave/pull/1928
=> fix: fix mismatched configuration entry

src/frontend/src/optimizer/plan_node/logical_agg.rs, src/frontend/src/optimizer/rule/unnest_agg_for_loj.rs, src/frontend/src/planner/select.rs
This `aliases` field in `LogicalAgg` has always been `None` (except in unit tests) and will not be used in the future (#1433).
To reiterate: `aliases` will be user-facing and handled at bound sql level but not in plan nodes, while `field` names are for internal debugging only and can follow whatever rules, possibly not matching aliases.
~~- [ ] I have added necessary unit tests and integration tests~~ (Refactor does not break existing tests.)
=> refactor(frontend): remove unused agg aliases

src/meta/src/hummock/compaction.rs
Fix bug caused by https://github.com/singularity-data/risingwave/pull/1994. It sets level type of target level by select level
=> Fix level type error

src/batch/src/executor2/project.rs, src/common/src/array/data_chunk.rs, src/common/src/array/mod.rs, src/common/src/array/stream_chunk.rs, src/common/src/lib.rs
Similar to #2111 
Although it may not be the best solution, it's must friendly then before.
If we find a better solution such as `pretty_chunk!` macro, it's possible to write a simple script to migrate them all.
=> test(batch): introduce DataChunk::from_pretty

src/frontend/src/scheduler/worker_node_manager.rs, src/frontend/src/session.rs, src/meta/src/barrier/mod.rs, src/meta/src/cluster/mod.rs, src/meta/src/rpc/service/ddl_service.rs, src/meta/src/rpc/service/notification_service.rs
- Removed `deactivate_worker_node` in  ClusterManager.
=> refactor: remove unused api in cluster manager

.github/workflow-template/jobs/compute-node-test.yml, .github/workflows/main-cron.yml, .github/workflows/main.yml, .github/workflows/pull-request.yml, e2e_test/v2/streaming/index.slt, src/frontend/src/optimizer/plan_node/stream_index_scan.rs, src/frontend/src/optimizer/plan_node/stream_table_scan.rs, src/frontend/test_runner/tests/testdata/stream_proto.yaml, src/meta/src/stream/fragmenter/mod.rs, src/meta/src/stream/fragmenter/rewrite/delta_join.rs
This PR adds support for rewriting `DeltaIndexJoin` to lookups on meta node. If we have created index beforehand, we will create `DeltaIndexJoin` plan, and we will join using index directly.
The MV can be created, but the result will be empty if we remove the force exchange check. Things will only work when we have added distribution key and pk of MV to catalog, so that the exchange can be eliminated.
ref https://github.com/singularity-data/risingwave/issues/2076
=> feat(meta): support rewrite join on index

src/batch/src/executor/merge_sort_exchange.rs, src/batch/src/executor/order_by.rs, src/batch/src/executor/test_utils.rs, src/batch/src/executor2/limit.rs, src/batch/src/executor2/top_n.rs, src/common/src/array/data_chunk.rs, src/common/src/array/mod.rs, src/common/src/util/sort_util.rs
Columns inside DataChunk are already wrapped with Arc, so it's useless to use Arc<DataChunk>.
=> refactor(batch): remove DataChunkRef

src/frontend/src/binder/expr/subquery.rs, src/frontend/test_runner/tests/testdata/subquery_expr.yaml
The binder was reporting "correlated subquery unsupported" on any error from subquery. As of now, presence of correlated subquery expr will not raise an error, and we should bubble the original error up.
=> fix(binder): remove stale error about correlated subquery

src/meta/src/lib.rs, src/meta/src/stream/fragmenter/graph/stream_graph.rs, src/meta/src/stream/stream_manager.rs
as title
- ~~I have written necessary docs and comments~~
- ~~I have added necessary unit tests and integration tests~~
=> refactor: use `let else` to simplify huge `if let` block

Cargo.lock, src/frontend/Cargo.toml, src/frontend/src/optimizer/join_solver.rs, src/frontend/src/optimizer/mod.rs, src/storage/compactor/Cargo.toml
The solver generates the lookup plans by controlling two parameters `StreamStrategy::LeftThisEpoch` or `ArrangeStrategy::LeftFirst` and based on join order generated by optimizer.
ref https://github.com/singularity-data/risingwave/issues/1962
close https://github.com/singularity-data/risingwave/issues/2147
=> feat(frontend): add delta join solver

src/common/src/array/data_chunk.rs
`cargo test` will fail due to this error. Not sure why this pass CI 
```
---- src/array/data_chunk.rs - array::data_chunk::DataChunk::from_pretty (line 470) stdout ----
error[E0432]: unresolved import `risingwave_common::array::stream_chunk::DataChunkTestExt`
--> src/array/data_chunk.rs:471:5
|
4 | use risingwave_common::array::stream_chunk::DataChunkTestExt as _;
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^----------------^^^^^
|     |                                       |
|     |                                       help: a similar name exists in the module: `StreamChunkTestExt`
|     no `DataChunkTestExt` in `array::stream_chunk`
error[E0599]: no function or associated item named `from_pretty` found for struct `DataChunk` in the current scope
--> src/array/data_chunk.rs:473:24
|
6 …
```
=> fix(doc): fix doc cargo test fail

Cargo.lock, src/compute/tests/table_v2_materialize.rs, src/source/Cargo.toml, src/stream/src/executor/mod.rs, src/stream/src/executor_v2/error.rs, src/stream/src/executor_v2/mod.rs, src/stream/src/executor_v2/source.rs, src/stream/src/task/barrier_manager.rs, src/stream/src/task/barrier_manager/tests.rs
As title. This PR also changes the channel element type in `BarrierManager` from `Message` to `Barrier`.
resolve #1476
=> refactor(stream): migrate SourceExecutor to ExecutorV2

src/stream/src/executor_v2/mview/materialize.rs
This PR uses relational interfaces for materialize executor.
close https://github.com/singularity-data/risingwave/issues/1201
=> feat(relational_layer): use relational layer for materialize executor

src/storage/hummock_sdk/src/key.rs
extract table id from full key
=> feat(storage): extract table id from full key

src/meta/src/cluster/mod.rs, src/meta/src/manager/notification.rs
As title, the deadlock occurs when frontend reboot while the notification manager is sending notifications asynchronously. The lock will always be hold since the notification manager is keep retrying on a broken connection to the reboot frontend. The frontend will never acquire the lock to finish subscribe. It also holds catalog/cluster lock at this time, which will cause other components heartbeat timeout and fail.
In this PR, we remove retry logic for notify and change drop sender to a more direct approach:
- Handling drop sender in `stop_retry_rx` is not correct, consider this scenario: there's no task under scheduled, one worker get deleted and a msg sent to `stop_retry_rx`. Then add this worker back, the sender will be dropped incorrectly when there's a task scheduled. Cc @HuaHuaY 
- …
=> fix(meta): fix dead lock when frontend reboot during handing task in notification manager

proto/stream_plan.proto, src/frontend/src/optimizer/plan_node/stream_hash_agg.rs, src/meta/src/stream/fragmenter/graph/stream_graph.rs, src/meta/src/stream/fragmenter/mod.rs, src/stream/src/executor/hash_agg.rs, src/stream/src/executor_v2/aggregation/mod.rs, src/stream/src/executor_v2/hash_agg.rs, src/stream/src/executor_v2/v1_compat.rs
For HashAgg, previous the keyspace encoding is `operator_id/agg_idx/group_key ....`, now change to `table_id/group_key...`. Each agg call in hash agg corresponds to a table states. 
After some offline discusssion, the simple agg will also do similar refactoring. It might be helpful for relation table interface. In future, all internal states may be prefixed by table_id instead of operator_id.
Code
* Add table ids in proto `HashAgg` node.
* Count and assign table id in meta fragmenter.
* Tweak the hash agg in stream executor to use vector of keyspace. I add a new method `generate_hash_agg_states` (fork of `generate_agg_states`). It will only be used by hash agg for now and if we merge hash agg and simple agg, we can merge them into one.
* Tweak some unit tests.
=> feat(relational-states): use table id for hash agg states

src/risedevtool/src/task/meta_node_service.rs
If you start risingwave playground via `cargo run --bin risingwave -- playground` with `enable-dashboard-v2: true`, it will panic and complain "environment variable not found". This PR fixes this.
N/A
None
=> fix: panic when starting with dashboard v2

src/common/src/array/bool_array.rs, src/common/src/array/chrono_array.rs, src/common/src/array/data_chunk_iter.rs, src/common/src/array/decimal_array.rs, src/common/src/array/interval_array.rs, src/common/src/array/list_array.rs, src/common/src/array/mod.rs, src/common/src/array/primitive_array.rs, src/common/src/array/struct_array.rs, src/common/src/array/utf8_array.rs, src/expr/src/vector_op/substr.rs
An unchecked version of `value_at` is added to the `Array` trait, and corresponding implementations are also added.
close #1814
=> feat(array): add `value_at_unchecked` for Array

src/compute/tests/row_seq_scan.rs, src/storage/src/table/state_table.rs, src/stream/src/executor_v2/mview/materialize.rs, src/stream/src/executor_v2/mview/table_state_tests.rs, src/stream/src/executor_v2/mview/test_utils.rs
As some relational interfaces has been implemented, `ManageMViewState` can be replaced by `StateTable`. This PR replaced `ManageMViewState` with `StateTable` in some unit tests.
=> refactor(test): refactor some unit tests by relational interfaces

src/storage/src/table/cell_based_table.rs, src/storage/src/table/state_table.rs, src/stream/src/executor_v2/mview/materialize.rs
As title, relational layer provides hash and non-hash write interfaces.
=> chore(relational_layer): add value_meta in relational write interfaces

risedev.yml
Seems no one is using java frontend to debug. So add a `legcay` suffix to the command and make rust frontend a frist class citizen in risedev debug mode. 
Otherwise we have to change the yml every time to debug compute node with new fe.
=> chore(risedev): rust frontend debug is first citizen

e2e_test/source/basic_test.slt
as title, use select * from s twice:
1. trigger connector reader to fetch from kafka
2. query from materialized source
- the test may last for 30s (on my local machine)
- sleep 1s may not long enough for all reader to fetch data and it may cause unexpected failure
=> ci: reopen kafka basic tests

src/stream/src/executor/managed_state/top_n/mod.rs, src/stream/src/executor/managed_state/top_n/top_n_bottom_n_state.rs, src/stream/src/executor/managed_state/top_n/top_n_state.rs
In #1969, we replace `scan` in `TopNExecutor` with `iter`. However, we still first materialize all the kv pairs from `iter`.
This PR adds a `PkAndRowIterator` so that two TopN's states only need to deal with `OrderedRow` and `Row` instead of raw `Bytes`.
Also eliminate an extra comparison between `key_from_storage` and `key_from_buffer` due to `encounter_same_key` check.
=> refactor(streaming): use iterator directly instead of materializing all kv pairs from iterator

src/storage/src/hummock/state_store.rs, src/storage/src/keyspace.rs, src/storage/src/memory.rs, src/storage/src/monitor/monitored_store.rs, src/storage/src/panic_store.rs, src/storage/src/rocksdb_local.rs, src/storage/src/rocksdb_local_mock.rs, src/storage/src/store.rs, src/storage/src/tikv.rs, src/storage/src/tikv_mock.rs
This is useless as we have removed all the lifetime on user iterators.
This is the first step for #2221 to replace `scan` with `iter`.
=> refactor(storage): remove lifetime on Iter in StateStore

e2e_test/v2/streaming/index.slt, e2e_test/v2/streaming_delta_join/join-3way.slt, e2e_test/v2/streaming_delta_join/tpch_snapshot.slt, src/stream/src/executor/actor.rs, src/stream/src/executor/dispatch.rs, src/stream/src/executor_v2/lookup/impl_.rs, src/stream/src/executor_v2/lookup/sides.rs
Lookup should forward barrier only when two sides are both ready.
close https://github.com/singularity-data/risingwave/issues/2243
=> fix(streaming): lookup barrier is not aligned

src/meta/src/hummock/compaction/tier_compaction_picker.rs
CompactTask::splits shouldn't be empty. Otherwise `parallelism` == 0 and compactor is stuck. See `Compactor::compact` `let parallelism = compact_task.splits.len();` (found in e2e when intra L0 compaction happens)
Also `TierCompactionPicker::pick_compaction` uses `splits.push(KeyRange::new(Bytes::new(), Bytes::new()));`. Should it use `KeyRange::inf()` is `splits.len() == 1` ?
=> fix: compaction picker intra L0

Cargo.lock, src/storage/hummock_sdk/Cargo.toml, src/storage/hummock_sdk/src/compact.rs
=> chore: pretty print key range in compaction task

docker/docker-compose.yml
Replace host network mode to docker network.
Notice that kafka-addr is set to port 29092 in docer network, and map 9092 to host.
=> chore(docker): replace host network mode to docker network

legacy/planner/src/main/java/com/risingwave/planner/rel/streaming/PrimaryKeyDerivationVisitor.java, legacy/planner/src/main/java/com/risingwave/planner/rel/streaming/RwStreamSort.java, legacy/planner/src/test/resources/com/risingwave/planner/planner/streaming/PrimaryKeyDerivationTest.xml, legacy/planner/src/test/resources/com/risingwave/planner/planner/streaming/StreamSortTest.xml, proto/stream_plan.proto, src/frontend/src/optimizer/plan_node/stream_topn.rs, src/frontend/test_runner/tests/testdata/order_by.yaml, src/frontend/test_runner/tests/testdata/tpch.yaml, src/stream/src/executor/top_n.rs, src/stream/src/executor/top_n_appendonly.rs, src/stream/src/executor_v2/hash_join.rs, src/stream/src/executor_v2/top_n.rs, src/stream/src/executor_v2/top_n_appendonly.rs
As #2130 suggests, the internal key used in `TopNExecutor` is different from the output primary key of `TopNExecutor`. 
This PR separates these two concepts.
Notice that as previously, the column used in both `order by` and primary keys will be deduplicated when used as the internal key. Only the backend, not the frontend, is now aware of this optimization.
closes #2130 
closes #2022
=> refactor(frontend,streaming): separate output pk and internal key in topNExecutor

src/frontend/src/expr/mod.rs, src/frontend/test_runner/tests/testdata/subquery_expr_correlated.yaml, src/frontend/test_runner/tests/testdata/tpch.yaml
For multi-nested queries, if a subquery as a whole doesn't reference any columns out of it, then it should not be consisdered correlated. Assume we have a two-level nested query(use outer subquery and inner subquery to differeniate them), if the inner subquery only references columns in outer subquery and outer subquery doesn't reference any columns out of it, then outer subquery should not be considered correlated.
=> fix(frontend): fix a bug of is_correlated(has_correlated_input_ref)

risedev.yml, src/cmd_all/src/playground.rs
Compactor should not be part of the playground.
close https://github.com/singularity-data/risingwave/issues/2249
=> fix(cmd_all): playground cannot start without risedev.yml

proto/stream_plan.proto, src/frontend/src/optimizer/plan_node/stream_simple_agg.rs, src/meta/src/stream/fragmenter/graph/stream_graph.rs, src/meta/src/stream/fragmenter/mod.rs, src/meta/src/stream/test_fragmenter.rs, src/stream/src/executor/global_simple_agg.rs, src/stream/src/executor_v2/aggregation/mod.rs, src/stream/src/executor_v2/global_simple_agg.rs, src/stream/src/executor_v2/hash_agg.rs, src/stream/src/executor_v2/integration_tests.rs, src/stream/src/executor_v2/test_utils.rs
Prevoius the keyspace encoding is `executor_id/agg_call_idx` (9 + 4), now `table_id` (5). 
Code:
* Count and assign table id in meta fragmenter. 
* use table id to create agg states
=> feat(simple-agg): use table ids for simple agg

src/frontend/src/binder/select.rs, src/frontend/src/optimizer/plan_node/logical_agg.rs, src/frontend/src/planner/select.rs
Post-agg Project from `select_items` (and post-agg Filter from `having`) will not be planned inside `LogicalAgg::create`. This allows reusing the subquery expr handling logic in `plan_select`. It will only create `LogicalAgg` with `agg_calls` extract from `select_items` (and `having`) and return the rewritten `select_items` (and `having`).
Also reverts the unnecessary separation of `bind_select` and `BoundSelect::create` in https://github.com/singularity-data/risingwave/pull/2220#discussion_r861436057
~~- [ ] I have added necessary unit tests and integration tests~~ (Refactor does not break existing tests.)
=> refactor(frontend): separate post-agg Project from LogicalAgg::create

src/frontend/src/binder/expr/function.rs, src/frontend/src/expr/utils.rs, src/frontend/test_runner/tests/testdata/basic_query.yaml
Add constant folding for `IsTrue`, `IsFalse`, `IsNull`, `IsNotTrue`, `IsNotFalse`, `IsNotNull`. `NULL` is taken into account as well. For example, `NULL IS NOT TRUE` will become `True`.
=> feat(frontend/expr): boolean constant folding for (Is, IsNot) x (True, False, Null)

src/frontend/src/binder/select.rs, src/frontend/src/optimizer/plan_node/logical_agg.rs, src/frontend/src/planner/select.rs, src/frontend/test_runner/tests/testdata/agg.yaml, src/frontend/test_runner/tests/testdata/tpch.yaml
Bind and plan `having`. Mostly reusing logic handling `where` for filtering and logical handling `select_items` for post-agg rewriting.
Limitations:
- Q11 still requires nested loop join for `having sum(...) > uncorrelated-subquery` as there are no equality conditions.
- Post-agg correlated subqueries are not handled by the rewriter yet. For example:
```
create table t (v1 int, v2 int);
select min(v1), (select max(v2)) from t;
select min(v1), (select v2) from t group by v2;
select min(v1), (select v2) from t;  -- expected error: subquery uses ungrouped column "t.v2" from outer query
select 1 from t having min(v1) > (select max(v2));
select 1 from t group by v2 having min(v1) > (select v2);
select 1 from t having min(v1) > (select v2);  -- expected error: subquery uses ungrouped column …
```
=> feat(frontend): bind & plan having

src/frontend/src/optimizer/plan_node/logical_agg.rs, src/frontend/test_runner/tests/testdata/subquery_expr_correlated.yaml
See #2275. Without the check in `rewrite_subquery`, the first test case (`select min(v1), (select max(v2)) from t`) would output the following plan (before decorrelation):
```
LogicalProject { exprs: [$0, $1], expr_alias: [ ,  ] }
LogicalApply { type: LeftOuter, on: always }
LogicalAgg { group_keys: [], agg_calls: [min($0)] }
LogicalProject { exprs: [$1], expr_alias: [ ] }
LogicalScan { table: t, columns: [_row_id#0, v1, v2] }
LogicalProject { exprs: [$0], expr_alias: [ ] }
LogicalAgg { group_keys: [], agg_calls: [max($0)] }
LogicalProject { exprs: [CorrelatedInputRef { index: 2, depth: 1 }], expr_alias: [ ] }
LogicalValues { rows: [[]], schema: Schema { fields: [] } }
```
Note that 1st child of `LogicalApply` outputs 1 column but the 2nd child contains `CorrelatedInputRef { index: 2, …
=> fix(planner): report unsupported post-agg correlated subquery

e2e_test/batch/tpch/q2.join_reorder.workaround.slt.part, e2e_test/batch/tpch/q8.join_reorder.workaround.slt.part, e2e_test/batch/tpch/q9.join_reorder.workaround.slt.part, e2e_test/streaming/tpch/views/q2.join_reorder.workaround.slt.part, e2e_test/streaming/tpch/views/q8.join_reorder.workaround.slt.part, e2e_test/streaming/tpch/views/q8.slt.part, e2e_test/streaming/tpch/views/q9.join_reorder.workaround.slt.part, e2e_test/streaming/tpch/views/q9.slt.part, e2e_test/v2/batch/tpch.slt, e2e_test/v2/streaming/tpch_snapshot.slt, e2e_test/v2/streaming/tpch_upstream.slt, e2e_test/v2/streaming_delta_join/tpch_snapshot.slt, src/frontend/test_runner/tests/testdata/tpch.yaml
- join reorder by changing query in manual, and open q2 q8 q9 streaming and batch e2e test
- open tpch q12 batch e2e test
- open q18 and q20 streaming and batch planner test 
- add q21 and q22 planner test
=> e2e(tpch): open some tpch with changing query workaround

src/common/src/util/ordered/serde.rs, src/stream/src/executor/lookup/tests.rs
Store zero bytes for sentinel cell value.
=> chore(relational-table): store zero bytes for sentinel columns

src/storage/src/memory.rs
ref #2197 . e2e test will dead lock if runs in memory state backend.
parking_lot::Mutex can also solve it. 
Can not find the root cause. I guess different actors in different spawned tasks doing operations concurrently so we get a deadlock. 
=> fix(state-store): fix a dead lock in memory state store

docker/README.md, docker/docker-compose.yml, src/risedevtool/src/compose.rs
Due to image build issue, compactor is not added in prior PRs. This PR adds compactor in docker-compose. Need test before merging.
To avoid users are using different version of the images, we now use `risingwave` single binary image to start all components. When https://github.com/singularity-data/risingwave/issues/2300 has been done, we can change back to use separate images.
=> feat(docker): add compactor in compose file

e2e_test/v2/streaming/index.slt, src/frontend/test_runner/tests/testdata/index.yaml
As title. Anyway, if there's projection between HashJoin and IndexScan, then the plan cannot be converted to delta join (for now). This PR adds test for projection outside join.
=> chore(frontend): add test for delta join with projection

src/batch/src/executor2/merge_sort_exchange.rs
visibility has been handled at https://github.com/singularity-data/risingwave/blob/lz/todo/src/batch/src/executor2/merge_sort_exchange.rs#L128.
Remove outdated TODO comments.
=> chore(batch): remove outdated TODO in MergeSortExchangeExecutor

src/common/src/array/iterator.rs, src/common/src/lib.rs
implement TrustedLen, added exact `size_hint` function for `ArrayIterator` and `ArrayImplIterator`.
close #1819
=> feat(array): implement `TrustedLen` for `ArrayIterator` and `ArrayImplIterator`

src/frontend/test_runner/tests/testdata/nexmark.yaml
* Only a few queries can be planned.
* Some of them failed because of parser error. Flink SQL's syntax is somehow different from Postgres.
* Window functions are expressed differently in RisingWave. Need rewrite some queries.
=> feat(frontend): add nexmark planner test

src/frontend/src/optimizer/plan_node/logical_hop_window.rs
When performing column pruning for `LogicalHopWindow`, `time_col` should be kept.
fix #2320
=> fix(frontend): fix panic on `LogicalHopWindow::prune_col`

src/storage/src/hummock/compactor.rs, src/storage/src/hummock/shared_buffer/shared_buffer_uploader.rs
avoid virtualnode bitmap clone
=> perf(bitmap): avoid virtualnode bitmap clone

src/batch/src/executor2/delete.rs, src/batch/src/executor2/insert.rs, src/connector/src/base.rs, src/connector/src/dummy_connector.rs, src/connector/src/lib.rs, src/connector/src/state.rs, src/source/src/connector_source.rs, src/source/src/lib.rs, src/source/src/table_v2.rs, src/stream/src/executor_v2/source.rs
introduce SourceStateHandler for source executor. 
* introduce `DummyConnector`, it will serve as an idle connector for the executor which is assigned no split.  
* in the current design, one connector source should handle multiple splits but it is not implemented yet. It will check `SourceExecutor.stream_source_splits` can have at most 1 element. 
---
this pr is based on #2257  so merge this before that.
=> feat(source): support recover state from SourceStateHandler

src/meta/src/hummock/hummock_manager.rs, src/meta/src/hummock/vacuum.rs
One of the issues in #2238: right now we vacuum stale ssts files only when we delete a version. And we can only delete the currently smallest version that has not been deleted.
So whenever we have a version that is being pinned, all the newer versions after it cannot be deleted, and thus their stale ssts files don't have a chance to be vacuumed.
However:
1. it is possible that those newer versions' stale ssts are not being used in any older version.
2. these stale ssts will not be used by any version that is even newer.
So we can actually vacuum a larger set of ssts than we currently do.
Haven't added the test yet, will add it later.
#2238
=> feat(storage): vacuum a larger set of ssts

e2e_test/v2/batch/order_by.slt, src/frontend/src/binder/insert.rs, src/frontend/src/binder/query.rs, src/frontend/src/lib.rs, src/frontend/src/optimizer/mod.rs, src/frontend/src/planner/query.rs, src/frontend/src/planner/select.rs, src/frontend/src/planner/set_expr.rs, src/frontend/test_runner/tests/testdata/nexmark.yaml, src/frontend/test_runner/tests/testdata/order_by.yaml
This pr solve #2124, so we can order by number of output column, column label and any expression that is valid in select list now. It uses BatchProject for Batch and out_fields for stream to do the projection. Some part of the pr may not be good enough, and I'm open for any advice. Thx!
close #2124 #1635
=> feat(frontend): order by arbitrary expr

src/frontend/src/optimizer/rule/filter_join.rs, src/frontend/test_runner/tests/testdata/nexmark.yaml, src/frontend/test_runner/tests/testdata/tpch.yaml
add outer join simplify in the filter-join rule. now it is just a naive implementation for comparison expression, we can give a more general implementation with constant folding in future
=> feat(optimizer): outer join simplify

src/common/src/array/data_chunk.rs, src/stream/src/executor/source.rs
Signed-off-by: Zulai Wang <zl31wang@gmail.com>
As title. We cannot reuse the capacity-limiting `StreamChunkBuilder` or `IterChunks` here to split the chunks, as we are splitting an existing `StreamChunk` in source executor instead of generating from scratch. So, I use the `rechunk` method to split the chunks.
#1891
=> feat(streaming): split chunks in source executor

dashboard/components/StreamingView.js, dashboard/lib/graaphEngine/canvasEngine.js, dashboard/lib/streamPlan/parser.js, dashboard/lib/streamPlan/streamChartHelper.js
Fixed parser for two changes in the meta-node API: 1) operatorId is not unique now 2) some properties in operators are renamed (#2255)
This PR just roughly fixed #2359. I will figure out a better solution. (For example, use data definitions in `proto`)
=> fix(dashboard-v2): failed to render because API is changed

src/storage/src/hummock/sstable/builder.rs, src/storage/src/hummock/sstable/mod.rs
since we have bitmap in object store now, we need to remove old bitmap in sstablemeta
=> feat(bitmap): remove old bitmap in sstablemeta

.github/workflow-template/jobs/e2e-risedev.yml, .github/workflows/main-cron.yml, .github/workflows/main.yml, .github/workflows/pull-request.yml
As we've refactored hummock compaction in https://github.com/singularity-data/risingwave/pull/2242, we observed `ci-3cn-1fe, streaming` is slower up to ~20 seconds. **We will fine tune the compaction picker**. Before that, this PR temporarily increases e2e timeout by 1 minute.
=> chore: increase e2e timeout before fine tune hummock compaction

src/stream/src/executor/managed_state/join/mod.rs
- The previous serialization does not match the deserialization, causing bugs.
=> fix(streaming): inappropriate serialization for `JoinRow`

src/storage/src/hummock/sstable/builder.rs
remove limit of bitmaps in SST, since we no longer have 65536 vnodes
=> refactor(bitmap): remove limit of bitmaps in SST

.github/workflow-template/jobs/compute-node-test.yml, .github/workflows/main-cron.yml, .github/workflows/main.yml, .github/workflows/pull-request.yml, src/storage/src/hummock/block_cache.rs, src/storage/src/hummock/cache.rs, src/storage/src/hummock/sstable_store.rs, src/storage/src/storage_failpoints/test_hummock.rs, src/storage/src/storage_failpoints/test_iterator.rs, src/storage/src/storage_failpoints/test_sstable.rs
This PR fixes the failure injection tests introduced in #1564 and modifies the CI workflow to run failiure injection tests.
#1221
=> fix: fix failpoint tests and add to CI

src/storage/src/hummock/iterator/test_utils.rs, src/storage/src/hummock/sstable/mod.rs, src/storage/src/hummock/sstable_store.rs, src/storage/src/storage_failpoints/test_iterator.rs
In this PR, we enable disabling bloom filter and block cache in failpoints test, so that we can have finer grained control over the read path when we explicitly want to read from object store directly.
=> refactor(failpoints): enable disabling bloom filter and block cache in failpoints test

src/meta/src/barrier/mod.rs, src/meta/src/barrier/recovery.rs, src/meta/src/stream/meta.rs, src/meta/src/stream/stream_manager.rs
As title, all aborted creating mv should be cleaned, not only the mv in prev command.
=> fix(meta): clean up all aborted creating mv when recovery

docker/README.md, risedev.yml, src/risedevtool/src/bin/risedev-compose.rs, src/risedevtool/src/compose.rs, src/risedevtool/src/service_config.rs
I tried a little bit to deploy services across 5 EC2, and succeeded. Basically, I'm using Terraform to start all servers, install docker, and then start components with docker-compose generated by risedev. This PR enables risedev to generate docker-compose files with host network mode, and those files can be deployed to different servers.
For the Terraform config and other deploy scripts, maybe I'll have another repo to store it.
=> feat(risedev): support host network mode

src/meta/src/hummock/compactor_manager.rs, src/meta/src/hummock/hummock_manager.rs, src/meta/src/hummock/hummock_manager_tests.rs, src/meta/src/hummock/vacuum.rs
Handle multiple version metadata deletions in one go, to reduce meta store transactions.
=> refactor(storage): batch version deletion in vacuum

src/meta/src/dashboard/index.html, src/meta/src/stream/fragmenter/graph/stream_graph.rs, src/meta/src/stream/fragmenter/mod.rs
* Dashboard can now correctly show texts.
* If there are projection between two stateful executors, now they will be split into two actors.
Note that the distribution issue is still not fixed in https://github.com/singularity-data/risingwave/issues/2442
fix https://github.com/singularity-data/risingwave/issues/2446
fix https://github.com/singularity-data/risingwave/issues/2448
=> fix(meta): dashboard node type and stateful fragment rule

Cargo.lock, src/common/Cargo.toml, src/common/src/util/epoch.rs, src/meta/src/barrier/mod.rs, src/meta/src/barrier/recovery.rs
As title, the epoch will never goes backwards during Meta serving. Since committed epoch in cluster is persistent in MetaStore, it also works after reboot and recovery. Besides add some warning when two epoch generated are too close and clock goes backwards.
Close https://github.com/singularity-data/risingwave/issues/2011
=> feat(meta): add logical part for epoch to avoid backwards

src/common/src/error.rs, src/meta/src/cluster/mod.rs, src/rpc_client/src/meta_client.rs
A temporary fix to reduce confusion like https://github.com/singularity-data/risingwave/issues/2367
Not done: set a larger heartbeat interval for `dev-compute-node`, so that users can be happier debugging.
=> fix: panic worker node when it's removed by meta node

src/frontend/src/optimizer/mod.rs, src/frontend/src/optimizer/plan_node/logical_agg.rs, src/frontend/src/optimizer/plan_node/logical_project.rs, src/frontend/src/optimizer/rule/project_merge.rs, src/frontend/src/optimizer/rule/pull_up_correlated_predicate.rs, src/frontend/src/optimizer/rule/unnest_agg_for_loj.rs, src/frontend/src/planner/insert.rs, src/frontend/src/planner/relation.rs, src/frontend/src/planner/select.rs, src/frontend/test_runner/tests/testdata/agg.yaml, src/frontend/test_runner/tests/testdata/basic_query.yaml, src/frontend/test_runner/tests/testdata/column_pruning.yaml, src/frontend/test_runner/tests/testdata/distribution_derive.yaml, src/frontend/test_runner/tests/testdata/expr.yaml, src/frontend/test_runner/tests/testdata/index.yaml, src/frontend/test_runner/tests/testdata/insert.yaml, src/frontend/test_runner/tests/testdata/join.yaml, src/frontend/test_runner/tests/testdata/limit.yaml, src/frontend/test_runner/tests/testdata/mv_on_mv.yaml, src/frontend/test_runner/tests/testdata/nexmark.yaml, src/frontend/test_runner/tests/testdata/order_by.yaml, src/frontend/test_runner/tests/testdata/predicate_pushdown.yaml, src/frontend/test_runner/tests/testdata/stream_proto.yaml, src/frontend/test_runner/tests/testdata/struct_query.yaml, src/frontend/test_runner/tests/testdata/subquery.yaml, src/frontend/test_runner/tests/testdata/subquery_expr.yaml, src/frontend/test_runner/tests/testdata/subquery_expr_correlated.yaml, src/frontend/test_runner/tests/testdata/time_window.yaml, src/frontend/test_runner/tests/testdata/tpch.yaml
2nd part of #1433. Thanks to the refactor of #2465, we can simply remove all references to `aliases` of `LogicalProject` without breaking anything. As a result, projects that are purely for renaming are eliminated from the plans.
=> refactor(optimizer): remove aliases from LogicalProject

src/storage/hummock_sdk/src/lib.rs
=> minor: use 0 as the higher bit to represent remote sst id for better logging

src/frontend/src/optimizer/plan_node/stream_materialize.rs
> Checks against `UNNAMED_COLUMN` would be unnecessary after #2436
_Originally posted by @xiangjinwu in https://github.com/singularity-data/risingwave/pull/2465#discussion_r871164005_
=> refactor(optimizer): cleanup unnecessary check on mview aliases

src/frontend/src/utils/column_index_mapping.rs
Otherwise cargo test will fail
=> fix(cargo-doc): fix wrong usage in rust doc string.

src/risedevtool/src/task/etcd_service.rs
Fix #2491 by enabling auto compaction by revision in etcd. The compaction will be triggered every 5mins acoording to https://etcd.io/docs/v3.3/op-guide/maintenance/#auto-compaction.
=> fix: enable etcd auto compaction by revision

src/storage/src/hummock/local_version_manager.rs
Avoid burst later tick when previous ones are delayed.
=> fix: avoid burst tick

e2e_test/v2/streaming/tpch_snapshot.slt, e2e_test/v2/streaming/tpch_upstream.slt
Reverts singularity-data/risingwave#2518
The test works in local and PR CI, but fails in main CI. The stuck problem still exists...
failing main CI:
https://github.com/singularity-data/risingwave/runs/6433891863?check_suite_focus=true
passing PR CI:
https://github.com/singularity-data/risingwave/runs/6433748795?check_suite_focus=true
related PRs:
#2430 #2518
=> Revert "test(streaming): enable tpch q4, q18, q20"

src/common/src/types/mod.rs, src/common/src/types/scalar_impl.rs, src/frontend/src/binder/values.rs
Delete scalarImpl to datatype function since we can get the data type from literal.
=> refactor: binding struct values when they are parsed as row

e2e_test/v2/batch/types/arithmetic.slt, src/expr/src/vector_op/cast.rs
As title, support incomplete timestamp literal to compatible with PG
```
select timestamp '1996-08-26';
```
#2460
=> fix(batch): support incomplete timestamp literal

src/common/src/array/data_chunk_iter.rs
Refactor the `next` method of `DataChunkIter`. 
`next_visible_row_idx` can be reused to implement it.
=> refactor(common): use next_visible_row_idx for data chunk iter

proto/expr.proto, src/expr/src/expr/expr_binary_nullable.rs, src/expr/src/expr/mod.rs, src/meta/src/stream/test_fragmenter.rs
Remove unused internal function `STREAM_NULL_BY_ROW_COUNT`.
Fix #794
=> refactor(stream): remove STREAM_NULL_BY_ROW_COUNT

src/compute/src/rpc/service/stream_service.rs, src/meta/src/barrier/mod.rs, src/stream/src/task/stream_manager.rs
As title, there's no need to sync states when forcing stop actors in recovery. As described in #2491 , when commit_epoch fails in barrier manager, the prev epoch is already used in this barrier lifecycle. To satisfy hummock epoch write check:
1. always use a new epoch as prev epoch in recovery.
2. avoid sync states when forcing stop actors.
Note that, In some scenarios such as network isolation appeared between some CNs and Meta, whether prev epoch is used or not is unknown. This might break some prev_epoch check in some executors. Need more test on this and further fix.
Resolve https://github.com/singularity-data/risingwave/issues/2492
=> fix(streaming): avoid sync states when forcing stop actors in recovery

src/meta/src/hummock/compaction/compaction_picker.rs, src/meta/src/hummock/compaction/level_selector.rs, src/meta/src/hummock/compaction/mod.rs, src/meta/src/hummock/compaction/overlap_strategy.rs, src/meta/src/hummock/compaction/tier_compaction_picker.rs, src/storage/src/hummock/compactor.rs, src/storage/src/hummock/sstable/group_builder.rs, src/storage/src/hummock/state_store.rs, src/storage/src/hummock/utils.rs
make compaction output be partitioned by parallel unit
=> feat(compaction): make compaction output be partitioned by parallel unit

src/batch/src/task/hash_shuffle_channel.rs, src/common/src/buffer/bitmap.rs
=> chore(batch): remove unnecessary compact

proto/expr.proto, src/expr/src/expr/expr_concat_ws.rs, src/expr/src/expr/mod.rs
As per title. Changes for frontend will be implemented separately.
Part of #2405. Migrated over from #2427 for CI to run correctly. cc @skyzh .
=> feat(expr): Implement evaluation for CONCAT_WS expression

proto/data.proto, src/common/src/types/mod.rs, src/expr/src/expr/build_expr_from_prost.rs, src/expr/src/expr/expr_literal.rs, src/expr/src/expr/expr_unary.rs
=> refactor(proto): remove TypeName::Symbol and Char

risedev.yml, src/connector/src/state.rs, src/stream/src/executor/source.rs
Fix #2546 
- Use state_identifier directly for source state key without encoding epoch in it.
- Add `idle_between_barriers` in source executor to track whether there is any data ingesting from source between barriers. Do not update source state to storage if the source state does not change.
With this PR, I confirmed (via grafana and manual checking on minio) that the number of newly added SSTs and number of kvs written to storage drop to zero after I stop producing data into the kafka source.
=> fix(source): remove epoch in state user key and no flush on idle

src/prost/build.rs, src/prost/src/lib.rs
revert some of https://github.com/singularity-data/risingwave/pull/2477
Because CLion can not parse code generated in `OUT_DIR`.
=> refactor(prost): use src as default build path for prost

src/frontend/src/optimizer/plan_node/logical_multi_join.rs, src/frontend/src/optimizer/plan_node/mod.rs, src/frontend/src/optimizer/rule/mod.rs, src/frontend/src/optimizer/rule/multijoin_join.rs
Adds `LogicalMultiJoin` PlanTreeNode. 
In a follow up PR (in progress; passes e2e tests reliably but missing unit tests) we will add optimizer rules for converting a `LogicalMultiJoin` into a left-deep join tree with heuristic reordering to avoid cross joins (and prioritize e.g. joins with primary keys in join columns).
https://github.com/singularity-data/risingwave/issues/2425
https://github.com/singularity-data/risingwave/issues/1866
=> feat(frontend): add `LogicalMultijoin`

src/common/src/array/bool_array.rs, src/common/src/array/column_proto_readers.rs, src/common/src/buffer/bitmap.rs
Previously, we encoded the bitmap and bool array to protobuf with 1 byte per item, which is inefficient. This PR makes it directly use the memory representation to encode bits, prepending a byte telling the number of trailing bits in the last byte.
- Close #2569
=> feat(array): use compact encoding for bitmap and bool array

e2e_test/v2/batch/func.slt, src/expr/src/expr/build_expr_from_prost.rs, src/expr/src/expr/expr_in.rs, src/frontend/src/binder/expr/mod.rs, src/frontend/src/expr/mod.rs, src/frontend/test_runner/tests/testdata/expr.yaml
The backend impl used to restrict the left side to be `InputRef` and right side to be `[Literal]`.
It can actually be extended naturally without any change:
* left: `InputRef` -> any expr
* right: `Literal` -> any const expr that evaluates without `InputRef` into input data chunk
On the frontend, we split the list in const ones and non-const ones, and rewrite the non-const ones as or-equal.
Limitations:
* A long list of `or-equal` is not performant. But most use cases should be constants.
* Constant folding is done at backend expr building time, and frontend only checks it is foldable.
Fixes #2456
=> feat(expr): IN-list support non-literals

src/connector/src/base.rs
clippy warns `large size difference between variants`
more details [here](https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant)
merge this before #2432
=> fix(connector): make too big struct a Box

e2e_test/v2/batch/func.slt, src/frontend/src/binder/expr/function.rs, src/frontend/src/expr/function_call.rs, src/frontend/test_runner/tests/testdata/expr.yaml
Implement support for `concat_ws` on frontend.
Bind `concat_ws` on frontend. Call cast over function arguments to ensure they are `varchar`.
Part of #2405
=> feat(frontend): Bind concat_ws expression

src/stream/src/executor/debug.rs, src/stream/src/executor/debug/trace.rs
Enable metrics in release mode, so that we can know what's going wrong.
=> chore(streaming): enable actor metrics in release mode

Cargo.lock, src/source/Cargo.toml
Apache avro have docsy, bootstrap, etc. as submodule, which will make `cargo build` extremely slow. We switched to our own fork and remove the submodules.
=> chore: switch avro to fork

src/frontend/src/binder/relation/mod.rs, src/frontend/src/binder/relation/window_table_function.rs, src/frontend/test_runner/tests/testdata/time_window.yaml
=> feat(frontend): support alias for window table function

Cargo.lock, src/ctl/Cargo.toml, src/ctl/src/cmd_impl/hummock/list_kv.rs, src/ctl/src/common/hummock_service.rs, src/ctl/src/lib.rs
1. Add args ( epoch , table ) in `ctl/list-kv`, we can use it to query the "kv" in hummock store.  
`cargo run --bin risectl -- hummock list-kv --epoch<epoch> --table-id<tableid>`
We will query the "kv" in all tables , if `--table-id` is null or `u32::MAX.` And we will query the "kv" with `u64::MAX`( epoch ) , if `--epoch` is null
2. We will see table_id, executor_id in results. 
usage:
` cargo run --bin risectl -- hummock list-kv --epoch=1 --table-id=180`
result with epoch = 1 and table_id = 180;
` cargo run --bin risectl -- hummock list-kv `
result with epoch = `u64::MAX` and all_table;
output:
`table_id:180
key : b"........." ====> value : b"..........."`
=> feat(ctl) add args ( epoch , table ) in list-kv

risedev.yml, src/frontend/src/session.rs, src/utils/logging/src/lib.rs, src/utils/pgwire/src/error.rs, src/utils/pgwire/src/pg_message.rs, src/utils/pgwire/src/pg_protocol.rs, src/utils/pgwire/src/pg_server.rs
This PR adds some loggings on pgwire and frontend so that it can help us identify the root cause of message flow failures.
=> chore: add some logging on pgwire and frontend

src/frontend/src/optimizer/plan_node/batch_update.rs, src/frontend/src/optimizer/plan_node/logical_update.rs, src/frontend/src/optimizer/plan_node/mod.rs, src/frontend/src/planner/update.rs, src/frontend/test_runner/src/lib.rs, src/frontend/test_runner/tests/testdata/update.yaml
The plan for `UPDATE` is similar to Project. It projects the original filtered input to an updated row, then the executor will combine the two rows into a pair of `U-` and `U+`.
- Close #2619
=> feat(frontend): plan `UPDATE`

e2e_test/v2/batch/const.slt, src/batch/src/executor2/sort_agg.rs, src/common/src/util/chunk_coalesce.rs, src/frontend/src/optimizer/rule/filter_agg.rs, src/frontend/test_runner/tests/testdata/predicate_pushdown.yaml
Bug reported from #2611 for the following queries:
```
select 42 where true;
select 42 where false;
select 42 where 2 > 1;
select 42 where 2 < 1;
select 42 having true;
select 42 having false;
select 42 having 2 > 1;
select 42 having 2 < 1;
```
* Both batch filter & sort agg executor build chunks from columns. When there are no columns, they default to zero cardinality mistakenly.
* Pushing predicates thru SimpleAgg is wrong and should be skipped.
Limitations:
* There may be other API usages that default to 0-cardinality chunk. It should actually report an error when cardinality cannot be guessed from columns or visibility map.
FIxes #2611
=> fix(batch & optimizer): 0-column chunk handling in filter & agg

Makefile.toml
Getting env info is slow. What's more, getting crate info requires downloading the whole crates.io index. So we disable it.
close https://github.com/singularity-data/risingwave/issues/2615
=> chore(risedev): disable env info

src/compute/src/rpc/service/stream_service.rs, src/source/src/manager.rs, src/source/src/parser/avro_parser.rs, src/source/src/parser/mod.rs
Integrate Avro Parser to SourceParserImpl. As Avro Schema file needs to be read from S3 and S3 SDK is async, so change the following function to async.
` StreamServiceImpl.create_source_inner`
` SourceManager.create_source`
` SourceParserImpl.create`
=> feat(connector): Integrate avro format parser to SourceParserImpl

src/compute/src/server.rs, src/compute/tests/table_v2_materialize.rs, src/config/risingwave.toml, src/source/src/manager.rs, src/stream/src/executor/source.rs, src/stream/src/from_proto/source.rs, src/stream/src/task/mod.rs, src/stream/src/task/stream_manager.rs
As title. We hard-code 100ms for now, until we can specify checkpoint interval in risingwave.toml. I'll test and bench later to see if this really works.
close https://github.com/singularity-data/risingwave/issues/2625
fix partially https://github.com/singularity-data/risingwave/issues/2626
fix https://github.com/singularity-data/risingwave/issues/2578
=> feat(streaming): limit source ingestion rate based on barrier

risedev.yml, src/bench/ss_bench/main.rs, src/common/src/config.rs, src/compute/src/server.rs, src/config/risingwave.toml, src/frontend/src/session.rs, src/meta/src/lib.rs, src/risedevtool/src/service_config.rs, src/risedevtool/src/task/meta_node_service.rs, src/storage/compactor/src/server.rs, src/storage/src/hummock/block_cache.rs, src/storage/src/hummock/compactor_tests.rs, src/storage/src/hummock/local_version_manager.rs, src/storage/src/hummock/sstable/builder.rs, src/storage/src/hummock/state_store_tests.rs, src/storage/src/hummock/test_utils.rs, src/storage/src/store_impl.rs, src/stream/src/from_proto/source.rs, src/stream/src/task/stream_manager.rs
Use `item_<mb|kb>` for config items, so that they are easier to read and config.
double checked with @Little-Wallace , the block cache capacity is indeed memory consumption instead of entry number 🤣 @zwang28 
close https://github.com/singularity-data/risingwave/issues/2657
=> feat(config): human-readable config

.github/pr-title-checker-config.json, .github/workflows/pr-title-checker.yml
~Try to add a pr title checker.
Testing its effect.~
If it blocks the merging somehow like the already removed `semantic check`, we may tag an `ignore-title` to bypass the check.
=> feat(ci): pr title checker

src/stream/src/executor/managed_state/join/mod.rs
Sometimes the compiler will complain about the lifetime for these functions while sometimes it will accept. 🤣 Just add a more explicit lifetime annotation for them.
=> fix(streaming): unstable lifetime compiling bug in join state

src/batch/src/execution/local_exchange.rs, src/batch/src/executor/mod.rs, src/batch/src/executor2/delete.rs, src/batch/src/executor2/filter.rs, src/batch/src/executor2/generate_series.rs, src/batch/src/executor2/generic_exchange.rs, src/batch/src/executor2/hash_agg.rs, src/batch/src/executor2/hop_window.rs, src/batch/src/executor2/insert.rs, src/batch/src/executor2/join/hash_join.rs, src/batch/src/executor2/join/nested_loop_join.rs, src/batch/src/executor2/join/sort_merge_join.rs, src/batch/src/executor2/limit.rs, src/batch/src/executor2/merge_sort_exchange.rs, src/batch/src/executor2/mod.rs, src/batch/src/executor2/order_by.rs, src/batch/src/executor2/project.rs, src/batch/src/executor2/row_seq_scan.rs, src/batch/src/executor2/sort_agg.rs, src/batch/src/executor2/top_n.rs, src/batch/src/executor2/update.rs, src/batch/src/executor2/values.rs, src/batch/src/rpc/service/task_service.rs, src/batch/src/task/context.rs, src/batch/src/task/mod.rs, src/batch/src/task/task_.rs, src/batch/src/task/task_manager.rs
In this PR we add a trait `BatchTaskContext` so that we can provide different executor execution/task context. Since we need to add support for local executor mode, which will construct executors in frontend (currently we only construct it in compute node), so we need to abstract out the execution context for different execution environments.
=> refactor(batch): Refactor batch task context for execution.

src/storage/src/keyspace.rs, src/storage/src/table/cell_based_table.rs, src/storage/src/table/state_table.rs, src/stream/src/executor/mview/table_state_tests.rs
This PR implements the StateTableIter, which is a merge iterator for CellBasedRowIter and MemTableIter.
=> feat(relational_table_iter): implement relational iter

src/stream/src/executor/mview/table_state_tests.rs
When #2744 is merged to main, there exists some actual conflicts (or code inconsistency) which GIT is unable to detect, and thus cause the failure of main CI. This PR is to fix these problems.
=> fix(test): fix state table tests

src/batch/src/executor2/join/hash_join.rs, src/batch/src/executor2/join/hash_join_state.rs
- do not join remaining when build table is empty.
#2749
=> fix(batch): join remaining panic when build table is empty

proto/hummock.proto, proto/stream_service.proto, src/bench/ss_bench/operations/write_batch.rs, src/compute/src/rpc/service/stream_service.rs, src/meta/src/barrier/mod.rs, src/meta/src/hummock/compactor_manager.rs, src/meta/src/hummock/hummock_manager.rs, src/meta/src/hummock/hummock_manager_tests.rs, src/meta/src/hummock/metrics_utils.rs, src/meta/src/hummock/mock_hummock_meta_client.rs, src/meta/src/hummock/test_utils.rs, src/meta/src/hummock/vacuum.rs, src/meta/src/rpc/service/hummock_service.rs, src/rpc_client/src/hummock_meta_client.rs, src/rpc_client/src/meta_client.rs, src/storage/src/hummock/compactor_tests.rs, src/storage/src/hummock/hummock_meta_client.rs, src/storage/src/hummock/local_version.rs, src/storage/src/hummock/local_version_manager.rs, src/storage/src/hummock/shared_buffer/shared_buffer_uploader.rs, src/storage/src/hummock/snapshot_tests.rs, src/storage/src/hummock/state_store.rs, src/storage/src/hummock/state_store_tests.rs, src/storage/src/monitor/monitored_store.rs, src/storage/src/storage_failpoints/test_hummock.rs, src/storage/src/store.rs, src/stream/src/task/barrier_manager.rs, src/stream/src/task/barrier_manager/managed_state.rs, src/stream/src/task/stream_manager.rs
This PR removes the `add_(ss)tables` RPC. Shared buffer no longer calls `add_tables` to track uncommitted SSTs in meta. Instead it commits these SSTS directly via `commit_epoch`. 
It reduces ~N RPCs per checkpoint, where N=number of CNs.
Major changes:
- Remove `add_tables`.
- Remove `abort_epoch`. We no longer need `abort_epoch` unless we want to vacuum orhpan SSTs sooner. Anyway they will be vacuumed after `orphan_sst_retention_interval`.
- CNs will inform meta SSTs that has been synced to s3, when replying checkpoint barrier.
https://github.com/singularity-data/risingwave/issues/2414
=> refactor(storage): remove add_sstables RPC.

src/batch/Cargo.toml, src/common/Cargo.toml, src/compute/Cargo.toml, src/connector/Cargo.toml, src/expr/Cargo.toml, src/frontend/Cargo.toml, src/meta/Cargo.toml, src/prost/Cargo.toml, src/rpc_client/Cargo.toml, src/source/Cargo.toml, src/storage/Cargo.toml, src/storage/compactor/Cargo.toml, src/stream/Cargo.toml
Lock madsim version to `0.2.0-alpha.1` to fix the build.
fix #2782
=> fix(build): lock madsim version

src/storage/src/hummock/iterator/backward_user.rs, src/storage/src/hummock/iterator/forward_user.rs, src/storage/src/hummock/iterator/mod.rs, src/storage/src/hummock/shared_buffer/shared_buffer_batch.rs, src/storage/src/hummock/sstable/forward_sstable_iterator.rs, src/storage/src/hummock/state_store.rs
Currently in the `iter_inner` of `HummockStorage` method, we have to pass a `backward` flag, and in the method body, we have to write some very similar code for twice for both backward and forward. In this PR, we refactor the `iter_inner method`  and specify the direction in the generic parameter of `iter_inner` so that we can remove some duplicated code.
=> refactor(storage): avoid passing backward flag in iter_inner of hummock storage

docker/Dockerfile
Previous, we only selectively added some components into docker build image, which will absolutely cause problems like https://github.com/singularity-data/risingwave/issues/2782. In this PR, we copy everything into the image.
=> chore(build): add Cargo.lock into docker image

grafana/risingwave-dashboard.json, proto/hummock.proto, src/compute/src/server.rs, src/meta/src/hummock/compaction/mod.rs, src/meta/src/hummock/metrics_utils.rs, src/meta/src/rpc/metrics.rs, src/storage/compactor/src/server.rs, src/storage/hummock_sdk/src/compact.rs, src/storage/src/hummock/block_cache.rs, src/storage/src/hummock/compactor.rs, src/storage/src/hummock/sstable/forward_sstable_iterator.rs, src/storage/src/hummock/sstable_store.rs, src/storage/src/monitor/local_metrics.rs, src/storage/src/monitor/mod.rs, src/storage/src/monitor/state_store_metrics.rs
I add more metrics to measure the compaction write-amplification. And I'm trying to find out the time cost component of compaction so that we can make a optimization goal in the future.  And the following is what this PR adds:
1. add flush flow and we can see that the write-amplification is about 4 times or 5times.  <img width="718" alt="image" src="https://user-images.githubusercontent.com/16376959/169969642-68b0876d-6450-4392-bc48-9a3f2790c8ff.png">
2. collect remote io cost and get-table-id rpc cost so that we can know that IO and rpc to meta-service cost most of time in compaction. <img width="727" alt="image" src="https://user-images.githubusercontent.com/16376959/169969997-8dc15ab0-d4e3-4876-a6c9-d7c1fecf7a43.png">
3. report IO size of every compaction task so that we can found that …
=> feat(metrics): add metric for compaction to measure compaction time cost and write-amplification

proto/task_service.proto, src/batch/src/rpc/service/task_service.rs, src/batch/src/task/task_.rs, src/batch/src/task/task_manager.rs, src/expr/src/expr/expr_field.rs, src/expr/src/expr/mod.rs, src/expr/src/expr/test_utils.rs, src/stream/src/executor/managed_state/join/mod.rs
Abort batch tasks on CN. The RPC just sends the message to notify the task that it should abort, but it does not wait for the task to abort successfully.
Part of handling task execution failure, i.e. when one task fails, the scheduler should be able to notify other batch tasks of the same query to abort and thus release the resources.
Introduce a new channel in the `TaskExeuction` to notify the spawned execution that its task needs to be aborted.
The spawned execution `select` on both the stream of a data chunk and the stream of this new channel's receiver, so that whenever the abort message is sent, the task will immediately be aborted.
Turn `try_execute` into a member function by making `self` a `Arc<Self>` so that the task's `state` can be set more easily.
#1977
=> feat(batch): abort task

src/batch/src/execution/local_exchange.rs, src/compute/src/server.rs, src/frontend/src/session.rs, src/meta/src/barrier/mod.rs, src/meta/src/cluster/mod.rs, src/meta/src/hummock/compaction_scheduler.rs, src/meta/src/hummock/mod.rs, src/meta/src/rpc/server.rs, src/meta/src/stream/stream_manager.rs, src/meta/src/test_utils.rs, src/rpc_client/src/meta_client.rs, src/storage/compactor/src/server.rs, src/storage/src/hummock/compactor.rs, src/stream/src/executor/merge.rs
As said in https://github.com/crossbeam-rs/crossbeam-channel/issues/25, a one-shot channel helps exposing bugs earlier and debugging. And it is optimized for sending a single value.
=> refactor: use oneshot channel for shutdown

src/stream/src/task/mod.rs
Per discussion at #wg-perf, local channel size has some effects on throughput but little effect on barrier latency. So we make it larger to improve throughput.
=> chore(stream): change default local channel size to 16

docker/Dockerfile
Fix the following error in meta-node docker image
```bash
error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```
=> fix: docker builder and wrapper should be the same version

src/storage/src/hummock/shared_buffer/mod.rs, src/storage/src/hummock/state_store.rs, src/storage/src/hummock/utils.rs
Currently in our code, we should pass a `backward` and `backward_range` flag everywhere only to indicate whether the range passed in is a backward or forward range. When we check such flag, what we do is only swap the start and end bound of the range when the backward flag is true. In this PR, we remove all the backward flag, and only reverse the range at the high level `backward_iter`.
=> refactor(storage): remove backward_range flag and reverse the range order only at the topest level

src/frontend/src/handler/query.rs, src/frontend/src/scheduler/distributed/query.rs, src/frontend/src/scheduler/hummock_snapshot_manager.rs, src/frontend/src/scheduler/local.rs, src/frontend/src/scheduler/plan_fragmenter.rs, src/frontend/src/scheduler/query_manager.rs, src/frontend/src/session.rs
Currently, the batch query manager unpins a query only after that query has been executed successfully. There is no handling for errors.
After this PR, we unpin the epoch/snapshot when:
1. all the leaf stages are scheduled.
2. when the scheduling fails.
Then:
1. we don't need to unpin the epoch after the job fails in any way after (1).
2. As long as the iterator is created during scheduling, i.e. they should be initialized when the backend builds the executors according to the plan, we do not need to take care of their failure or success in a unique way. It's the same as scheduling success(1) or failure(2).
Other changes:
1. Put the request to meta for unpinning the epoch into another task. So all the resources related to a query can be reclaimed without being blocked.
2. Since (1) can …
=> refactor(frontend): unpin epoch when all leaf stages are scheduled

Cargo.lock, src/utils/pgwire/Cargo.toml, src/utils/pgwire/src/pg_message.rs, src/utils/pgwire/src/pg_protocol.rs, src/utils/pgwire/src/pg_server.rs, src/workspace-hack/Cargo.toml
ref: #2621. 
This is PR init the extended query mode. The feature is very limited. We do not support prepared statement or portal. Just hard code the return type of DataRow and returned result sets.
=> feat(pgwire): introduce extended query mode init

e2e_test/batch/order_by.slt, src/common/src/util/sort_util.rs
It should handle null values properly rather than unwrap and panic.
Fixes #2826
=> fix: batch TopN sort_util handles null

src/batch/src/task/task_manager.rs, src/compute/src/rpc/service/exchange_service.rs
As we support local mode execution in #2809, both `TaskService` and `ExchangeSerivce` need to get data from the output of tasks.
Therefore, we move the concrete implementation of `get_data` from `ExchangeService` to `BatchManager` so that both endpoints can share the same code.
#2809
=> refactor(batch,rpc): move get_data's concrete implementation to BatchManager

src/storage/src/hummock/compaction_executor.rs
The bug makes compaction executor single tasked. Fixed.
=> fix(storage): multitasked compaction executor

src/storage/src/hummock/sstable/builder.rs
make vnode bits same as upstream
=> fix(bitmap): make vnode bits same as upstream

ci/Dockerfile, ci/docker-compose.yml, ci/scripts/compute-node-build.sh, ci/scripts/compute-node-test.sh, ci/scripts/e2e-risedev.sh, ci/scripts/e2e-source.sh, ci/scripts/misc-check.sh, ci/workflows/main-cron.yml, ci/workflows/main.yml, ci/workflows/pull-request.yml, src/risedevtool/etcd.toml, src/risedevtool/src/bin/risedev-playground.rs
The ci service is migrated from github to buildkite.
The migration workflows include:
1. main.yml
2. main-cron.yml
3. pull-request.yml
- ci folder is for migration to buildkite.
- src/risedevtool/etcd.toml: because the tar command here may report an error when executed in a container, I add the --no-same-owner parameter to avoid this problem.
issue: https://github.com/singularity-data/risingwave/issues/2100
=> feat(ci): migrating ci services to buildkite.

e2e_test/batch/aggregate/single_value.slt, src/expr/src/vector_op/agg/aggregator.rs, src/frontend/src/binder/expr/function.rs, src/frontend/src/expr/agg_call.rs
Add the support for `single_value(c)` back.
You can find the example in the e2e doc.
=> feat(frontend): support single_value(c)

src/batch/src/execution/local_exchange.rs, src/batch/src/task/context.rs, src/batch/src/task/task_.rs, src/batch/src/task/task_manager.rs, src/frontend/src/scheduler/task_context.rs
The first step in simplifying task context trait: remoing `get_task_error`.
=> refactor(batch): Simplify task context by removing `get_task_error`.

src/batch/src/executor/delete.rs, src/batch/src/executor/filter.rs, src/batch/src/executor/generate_series.rs, src/batch/src/executor/generic_exchange.rs, src/batch/src/executor/hash_agg.rs, src/batch/src/executor/hop_window.rs, src/batch/src/executor/insert.rs, src/batch/src/executor/join/hash_join.rs, src/batch/src/executor/join/nested_loop_join.rs, src/batch/src/executor/join/sort_merge_join.rs, src/batch/src/executor/limit.rs, src/batch/src/executor/merge_sort_exchange.rs, src/batch/src/executor/mod.rs, src/batch/src/executor/order_by.rs, src/batch/src/executor/project.rs, src/batch/src/executor/row_seq_scan.rs, src/batch/src/executor/sort_agg.rs, src/batch/src/executor/top_n.rs, src/batch/src/executor/update.rs, src/batch/src/executor/values.rs, src/batch/src/rpc/service/task_service.rs, src/batch/src/task/task_.rs, src/batch/src/task/task_manager.rs, src/compute/tests/row_seq_scan.rs, src/compute/tests/table_v2_materialize.rs, src/frontend/src/scheduler/local.rs, src/storage/src/memory.rs, src/storage/src/table/cell_based_table.rs, src/storage/src/table/test_relational_table.rs, src/stream/src/executor/batch_query.rs
We replace `scan` with `iter` after we can finally unpin the epoch earlier, i.e. after the iterator is successfully or unsuccessfully created.
This is possible as we now #2825  unpin the epoch of a batch query after it `successfully` schedules all the tasks of leaf stages. The implicit assumption here is that the `CellBasedRowIterator` for batch query will only be used in leaf stages.
The ugly part is that I have to create the iterator during building (a non-sync func) the executors instead of during executing. Since `building` is part of scheduling while `executing` is an independent process, creating iterators during build can be effectively considered part of scheduling. 
Otherwise, we need to introduce another communication path for CN to notify the batch query manager in the frontend …
=> refactor(batch): use iter instead of scan in CellBasedTableRowIter

src/stream/src/executor/aggregation/mod.rs, src/stream/src/executor/global_simple_agg.rs, src/stream/src/executor/hash_agg.rs, src/stream/src/executor/managed_state/aggregation/mod.rs, src/stream/src/executor/managed_state/aggregation/value.rs
Use relational state for hash agg/simple agg that use `ManagedValueState`. 
For each AggCall, there is a relational table state correspond. For simple agg, the primary key in table state is empty `vec![]` (Down to the keyspace encoding it is just `table_id/`). For hash agg, the primary key in table state is `group_key` (Keyspace encoding `table_id/group_key`). 
For code, my design principle is to only let `AggState` to aware of `StateTable` or `Keyspace` or `WriteBatch`. In the future, if we apply relational states to all, then all executors do not need to start write batch/use keyspace to scan, it only need to access the `ManagedState`.
~~* Because different `AggState` may share one `StateTable`, so I wrap a `Arc<Mutex<>>`. The Mutex seems can only be tokio::sync::Mutex, though I'm a …
=> feat(relational-state): use relational state for value state

src/batch/src/executor/delete.rs, src/batch/src/executor/filter.rs, src/batch/src/executor/hash_agg.rs, src/batch/src/executor/merge_sort_exchange.rs, src/batch/src/executor/order_by.rs, src/batch/src/executor/sort_agg.rs, src/batch/src/executor/top_n.rs, src/batch/src/executor/update.rs, src/common/src/array/data_chunk.rs, src/common/src/hash/key.rs, src/compute/tests/table_v2_materialize.rs, src/expr/src/expr/expr_case.rs, src/expr/src/expr/expr_coalesce.rs, src/expr/src/expr/expr_in.rs, src/stream/src/executor/managed_state/join/join_entry_state.rs
To reduce the PR size of `DataChunk` refactor (#2663), we remove usage of `DataChunkBuilder` for literals in unit tests.
#2663
=> refactor(test): use `DataChunk::from_pretty` for literals in unit tests rather than DataChunkBuilder

src/batch/src/executor/join/hash_join.rs, src/batch/src/executor/join/nested_loop_join.rs, src/batch/src/executor/join/sort_merge_join.rs, src/common/src/util/chunk_coalesce.rs, src/frontend/src/handler/util.rs
To reduce the PR size of `DataChunk` refactor (#2663), we remove usage of `DataChunk::try_from` and `DataChunk::new` for literals in unit tests.
Also noticed that test fixtures for hash join, nested loop join, sort merge join are duplicated. It is not a concern of this PR to DRY them.
1st part: #2874 removal of `DataChunkBuilder` for test literals
=> refactor(test): use `DataChunk::from_pretty` for literals in unit tests rather than try_from or new

src/frontend/src/scheduler/distributed/query.rs, src/frontend/src/scheduler/plan_fragmenter.rs
In #2835, thought `leaf stages` represent those stages that need to read data from tables, but actually wrong
#2835
=> fix(batch): find out stages that have table scan instead of using leaf stages

Makefile.toml, ci/scripts/deterministic-simulation-test.sh, ci/workflows/main-cron.yml, ci/workflows/main.yml, ci/workflows/pull-request.yml, src/meta/Cargo.toml, src/meta/src/stream/test_fragmenter.rs, src/source/src/connector_source.rs, src/source/src/lib.rs, src/stream/src/executor/barrier_align.rs
This PR fixes build with madsim and adds the command to risedev and CI scripts.
Now we can run simulation unit tests with a shorter command:
```sh
./risedev stest
```
Note that some tests still fail at this moment, so I mark the step as `soft_fail` to allow failures.
The following results from CI are as expected:
```
Summary [   5.929s] 557 tests run: 544 passed, 13 failed, 13 skipped
error: test run failed
```
=> ci: add deterministic simulation test

proto/task_service.proto
As title. Has been definied in batch_plan.proto.
=> chore(batch): remove repetitive definition of TaskOutputId

ci/workflows/main-cron.yml, ci/workflows/main.yml, ci/workflows/pull-request.yml
After Java frontend gets retired, "compute-node test" is an outdated name -- now we test and build the whole RisingWave system inside those CI steps.
=> chore(ci): rename CI name

src/meta/src/hummock/compaction/mod.rs, src/meta/src/hummock/compaction/tier_compaction_picker.rs, src/storage/src/hummock/compactor.rs
Compaction task should not contain empty splits. Same as https://github.com/singularity-data/risingwave/pull/2251
=> fix(storage): ensure at least one split in compaction task

src/frontend/test_runner/README.md
The function `run_all_test_files` has been removed since commit [68d0aef](https://github.com/singularity-data/risingwave/commit/68d0aef555cc4c198d8f25fab25bc7f6edddb696).
#915
#1091
=> fix(docs/frontend): remove some out-of-date docs

proto/task_service.proto, src/batch/src/rpc/service/exchange.rs, src/batch/src/rpc/service/task_service.rs, src/batch/src/task/task_.rs
As title.
~Reuse the `GetDataResponse` as the return value of `rpc execute(ExecuteRequest)`.~ Actually forbidden by `buf lint`...
#2809
=> feat(batch): add rpc for local execution mode

src/storage/src/table/cell_based_table.rs, src/storage/src/table/state_table.rs, src/storage/src/table/test_relational_table.rs
This PR refactors the state table iterator in a zero-copy manner.
- Use `Cow` as the item type of this iterator.
- Avoid cloning from the peek result.
- #2885 
- Close #2893
=> feat(storage): zero-copy state table iterator

proto/buf.yaml, proto/task_service.proto, src/batch/src/rpc/service/exchange.rs, src/batch/src/rpc/service/task_service.rs, src/batch/src/task/task_.rs
Remove `ExecuteResponse` as it is the same as `GetDataResponse`.
We add two configurations into `buf.yaml` to enable so.
=> chore(proto): allow same type for rpc response

src/batch/src/executor/join/nested_loop_join.rs, src/common/src/array/data_chunk.rs, src/common/src/array/stream_chunk.rs, src/expr/src/expr/expr_array.rs
As of now, `DataChunk` stores an optional visibility bitmap and a cardinality at the same time. However, when a visibility bitmap does exist, the cardinality is redundant and need to be kept consistent with visibility (e.g. `DataChunk::set_visibility`). It is even harder after `into_parts` and `new` are refactored to include cardinality (#2907).
All public interfaces are still using `Option<Bitmap>`; only the internal implementation is updated. This allows a smoother migration and smaller PR. As mentioned above, `into_parts` and `new` will use this new `Vis` as public interface in the next PR. All remaining methods can decide whether or not to change individually.
Also removed unused `DataChunk::default()`, and added warning comments of `StreamChunk::default()`, which is only used in some …
=> refactor(DataChunk): consolidate visibility bitmap and cardinality

src/batch/src/executor/join/hash_join_state.rs
Signed-off-by: Ryan Russell <git@ryanrussell.org>
- Fix readability issues in `src/batch/src/executor/join/hash_join_state.rs`
- bacause -> because
- `do_left_anti_join_with_non_equi_conditon()` -> `do_left_anti_join_with_non_equi_condition()`
=> refactor(hash_join_state): Improve Code Readability

src/batch/src/executor/delete.rs, src/batch/src/executor/generic_exchange.rs, src/batch/src/executor/insert.rs, src/batch/src/executor/join/nested_loop_join.rs, src/batch/src/executor/limit.rs, src/batch/src/executor/order_by.rs, src/batch/src/executor/project.rs, src/batch/src/executor/update.rs, src/batch/src/executor/values.rs, src/common/src/array/data_chunk.rs, src/common/src/hash/key.rs, src/common/src/util/chunk_coalesce.rs, src/compute/tests/table_v2_materialize.rs, src/expr/src/expr/expr_binary_nonnull.rs, src/expr/src/expr/expr_field.rs, src/expr/src/expr/expr_is_null.rs, src/expr/src/expr/expr_unary.rs, src/expr/src/vector_op/agg/general_agg.rs, src/expr/src/vector_op/agg/general_distinct_agg.rs, src/expr/src/vector_op/agg/general_sorted_grouper.rs, src/source/src/common.rs, src/storage/src/table/cell_based_table.rs, src/stream/src/executor/filter.rs, src/stream/src/executor/hash_join.rs, src/stream/src/executor/project.rs
Part 2/3 of actual refactor #2663
With the introduction of a safer `DataChunk::new` in #2934, this PR migrate some callers of `DataChunkBuilder` or `TryFrom<Vec<Column>>` to `new`. **We need to find the proper `cardinality` as extra argument to pass into `new`.**
The original plan in #2934 was to migrate `TryFrom<Vec<Column>>` as part 2 and `DataChunkBuilder` as part 3. But here I am making simple callers as part 2 and complicated callers as part3.
Simple callers include:
* The ones in unit tests (`@@ mod tests`). `cardinality` for test cases are usually static and easy to find.
* The return of DML. Before #2678 is fixed, we are returning number of affected rows, which is always a 1-row-1-col int64 chunk.
* Other callers where `cardinality` is already available in a local variable.
* …
=> refactor(DataChunk): use `new` rather than `DataChunkBuilder` or `try_from` in simple cases

proto/hummock.proto, src/meta/src/hummock/compaction/level_selector.rs, src/meta/src/hummock/compaction/mod.rs, src/meta/src/hummock/hummock_manager.rs, src/meta/src/hummock/hummock_manager_tests.rs, src/meta/src/manager/id.rs, src/storage/hummock_sdk/src/lib.rs
Use `IdGenerator` for compaction task id, in order to make later compaction group easier (each compaction group owns a `CompactStatus` and share the same compaction task id). 
This also fixes a bug that originally `next_compact_task_id` was not correctly stored to meta store.
=> refactor(meta): use IdGenerator for compaction task id

Cargo.lock, src/batch/Cargo.toml, src/batch/src/executor/delete.rs, src/batch/src/executor/filter.rs, src/batch/src/executor/generate_series.rs, src/batch/src/executor/generic_exchange.rs, src/batch/src/executor/hash_agg.rs, src/batch/src/executor/hop_window.rs, src/batch/src/executor/insert.rs, src/batch/src/executor/join/hash_join.rs, src/batch/src/executor/join/nested_loop_join.rs, src/batch/src/executor/join/sort_merge_join.rs, src/batch/src/executor/limit.rs, src/batch/src/executor/merge_sort_exchange.rs, src/batch/src/executor/mod.rs, src/batch/src/executor/order_by.rs, src/batch/src/executor/project.rs, src/batch/src/executor/row_seq_scan.rs, src/batch/src/executor/sort_agg.rs, src/batch/src/executor/top_n.rs, src/batch/src/executor/update.rs, src/batch/src/executor/values.rs
RT.
Prepare for further refactor of `BatchTaskContext`.
=> refactor(batch): Executor builder should not create their children

proto/stream_plan.proto, src/frontend/src/optimizer/plan_node/stream_topn.rs, src/frontend/src/stream_fragmenter/mod.rs, src/meta/src/stream/stream_graph.rs, src/stream/src/from_proto/top_n.rs
Replace operator_id to table_id for `TopN`.
- Add a fields table_id in `TopNode` proto. This is designed to use indenpendent table_id to replace operator_id
- `gen_table_id` when build the `stream_fragemnet` and recaluc truely table_id when `generate_steam_graph` 
- use `keyspace::table_root` to replace `keyspace::executor_root` for table_id prefix
- refactor some code logic for pattern match
- close https://github.com/singularity-data/risingwave/issues/2925
- https://github.com/singularity-data/risingwave/pull/1987
=> feat(steaming): use table_id as topN prefix for keyspace

src/frontend/src/stream_fragmenter/mod.rs
refactor assign table_id logic
- use indenpendent method to unify the pattern match logic for table_id assign
- simply the build_fragment by assign_table_id_to_stream_node method
- TODO: we need to handle the specialy logic for join(e.g. HashJoin, DeltaIndexJoin) in the furtue
- https://github.com/singularity-data/risingwave/pull/2942
=> refactor(streaming): refactor assign table_id logic

src/utils/memcomparable/src/ser.rs
Signed-off-by: Ryan Russell <git@ryanrussell.org>
Fix `test_decimal_e_m()`; `exponets` -> `exponents`
=> refactor(test_decimal_e_m): Fix `exponents`

src/frontend/src/lib.rs, src/frontend/src/scheduler/distributed/query.rs, src/frontend/src/scheduler/distributed/stage.rs, src/frontend/src/scheduler/local.rs, src/frontend/src/scheduler/plan_fragmenter.rs, src/frontend/src/scheduler/query_manager.rs, src/frontend/src/scheduler/task_context.rs, src/storage/src/hummock/iterator/backward_user.rs
which is lint group for: unused-imports, unused-variables, unused-assignments, dead-code, unused-mut, unreachable-code, unreachable-patterns, unused-must-use, unused-unsafe, path-statements, unused-attributes, unused-macros, unused-allocation, unused-doc-comments, unused-extern-crates, unused-features, unused-labels, unused-parens, unused-braces, redundant-semicolons 🙀 
=> chore: do not #[allow(unused)]

proto/hummock.proto, src/meta/src/hummock/hummock_manager.rs, src/meta/src/hummock/hummock_manager_tests.rs, src/meta/src/hummock/model/compact_task_assignment.rs, src/meta/src/hummock/model/current_version_id.rs, src/meta/src/hummock/model/pinned_snapshot.rs, src/meta/src/hummock/model/pinned_version.rs, src/meta/src/hummock/model/sstable_id_info.rs, src/meta/src/hummock/model/stale_sstables.rs, src/meta/src/hummock/model/version.rs
We defined several wrapper type (*RefId) in hummock.proto, in order to use them as Key when writing to meta store.
It turns out we can use primitive type directly. So this PR removes these unnecessary types.
=> refactor(meta): remove RefId proto in hummock

src/meta/src/rpc/server.rs, src/meta/src/stream/source_manager.rs, src/meta/src/stream/stream_manager.rs
This PR provides the ability to discover Split.
When a Materialized View is created on a meta node, the stream_manager registers the source fragment with the source_manager, and then the source_manager spawns a loop to call the Split Enumerator to discover new split and push down the newly found Split
=> feat: new split discovery in meta node

Cargo.lock, src/storage/Cargo.toml, src/storage/src/hummock/sstable/block.rs, src/storage/src/hummock/sstable/utils.rs
Signed-off-by: Shmiwy <wyf000219@gmail.com>
In this PR, I support zstd compression for blocks.
I just append a possible kinds of compression algorithm  called `Zstd` to `CompressionAlgorithm` enumeration.  I also append the corresponding match arm, which encodes and decodes data using the interface provided by 'zstd' crate
#2800
=> refactor(storage): support zstd compression in block

src/config/risingwave.toml
During benchmarks, 256MB of meta cache will cause very high object storage throughput. 1GB seems like a reasonable value.
Also, we'd better find a way to determine the right size of meta cache. e.g. if meta cache misses frequently on one file, we should dynamically increase the meta cache size.
=> chore(config): set meta cache to 1gb

src/common/src/array/list_array.rs, src/common/src/array/mod.rs, src/common/src/array/struct_array.rs, src/common/src/types/mod.rs
The PR fixes two things:
1. Use boxed slice in `StructValue` and `ListValue`, which use 16 bytes (`Vec` uses 24).
2. Fix the incorrect calculation of Decimal size, which is 20 now instead of 16, need to be optimized later.
We store Vec<Datum> in our state store, so the memory usage of Datum is critical.
=> fix(types): reduce [Struct/List]Value memory usage and fix Decimal data_size

src/expr/src/vector_op/arithmetic_op.rs
In addition to the previous PR, I consistent the writing style for the returning of general_[operation].
for example, `general_atm(l, r, |a, b| {
a.checked_add(&b)
.ok_or_else(|| RwError::from(NumericValueOutOfRange))
})`
=> feat(expr): Implementation for bitwise operation (Continue PR #2884)

ci/scripts/unit-test.sh
Run fail point tests along with llvm coverage test.
=> chore(ci): speedup unit test

src/risedevtool/src/bin/risedev-compose.rs
Store Kafka and frontend info to risingwave deployment directory, so that we don't need to manually copy them to the script.
=> chore(risedev): store kafka and frontend config when compose deploy

proto/buf.yaml, proto/hummock.proto, src/frontend/src/meta_client.rs, src/frontend/src/test_utils.rs, src/meta/src/hummock/hummock_manager.rs, src/meta/src/hummock/hummock_manager_tests.rs, src/meta/src/hummock/mock_hummock_meta_client.rs, src/meta/src/rpc/service/hummock_service.rs, src/rpc_client/src/hummock_meta_client.rs, src/rpc_client/src/meta_client.rs, src/storage/src/hummock/hummock_meta_client.rs
I actually already finished some development of using this RPC in frontend manager. But I'd like to make the PR small.
The main idea is `unpin_snapshot_before(min_epoch)`. This is to allow the meta to **unpin all epoch < min_epoch**. The implementation is learned from the retryable pin snapshot. Calcualting all pinned snapshot that is smaller than specified epoch and unpin them all.
Part of #2364
=> feat: add hummock rpc `unpin_snapshot_before`

src/frontend/src/stream_fragmenter/mod.rs, src/meta/src/stream/stream_graph.rs, src/stream/src/from_proto/top_n_appendonly.rs
use table_id as AppendOnlytopN prefix for keyspace
- refactor the logic with pattern match
- support AppendOnlyTopN Executor use table_id as KeySpace Preifx
- some test for assign_table_id
- https://github.com/singularity-data/risingwave/pull/2942
=> feat(streaming): use table_id as AppendOnlytopN prefix for keyspace

src/frontend/src/handler/create_index.rs, src/frontend/src/optimizer/plan_node/logical_project.rs, src/frontend/src/optimizer/plan_node/logical_scan.rs, src/frontend/src/planner/relation.rs, src/frontend/src/scheduler/distributed/query.rs, src/frontend/src/scheduler/plan_fragmenter.rs, src/frontend/src/utils/mod.rs, src/frontend/test_runner/tests/testdata/column_pruning.yaml, src/frontend/test_runner/tests/testdata/join.yaml, src/frontend/test_runner/tests/testdata/nexmark.yaml, src/frontend/test_runner/tests/testdata/predicate_pushdown.yaml, src/frontend/test_runner/tests/testdata/subquery_expr_correlated.yaml, src/frontend/test_runner/tests/testdata/tpch.yaml
as title 
batch/stream plan (almost) not changed
close #2343
=> feat(optimizer): pushdown predicate to LogicalScan

src/common/src/cache.rs
`LruCacheShard` only need to be `Send` for the async environment. It's not thread-safe and is protected by `Mutex` in `LruCache`.
=> fix: remove unsafe impl Sync trait for LruCacheShard

.git-blame-ignore-revs
as title
https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view
before 
after
```bash
git config blame.ignoreRevsFile .git-blame-ignore-revs
```
- ~~[ ] All checks passed in `./risedev check` (or alias, `./risedev c`)~~
=> chore: Ignore commits in the blame view

src/risedevtool/src/task/minio_service.rs
https://docs.min.io/minio/baremetal/installation/deploy-minio-single-node-single-drive.html#id3
MinIO [RELEASE.2022-06-02T02-11-04Z](https://github.com/minio/minio/releases/tag/RELEASE.2022-06-02T02-11-04Z) doesn't allow using MinIO on root disk. We bypass this restriction.
=> chore(risedev): allow minio to be used on non-root disk

src/stream/src/from_proto/source.rs
source executor use table_id for keyspace prefix
- use keyspace::table_root to replace keyspace::executor_root same as materialized_executor
- https://github.com/singularity-data/risingwave/pull/2992/files
=> feat(streaming): source executor use table_id for keyspace prefix

Cargo.lock, risedev.yml, src/common/Cargo.toml, src/common/src/error.rs, src/common/src/util/addr.rs, src/risedevtool/src/bin/risedev-playground.rs, src/risedevtool/src/task/task_configure_grpc_node.rs
The original HostAddr parsing doesn't work on IPv6 address. This PR fixes this, while supporting IPv6 across all worker nodes.
close https://github.com/singularity-data/risingwave/issues/3005
=> feat(risedev): support ipv6 in config

e2e_test/batch/join.slt, src/batch/src/executor/generate_series.rs, src/batch/src/executor/hash_agg.rs, src/batch/src/executor/join/hash_join.rs, src/batch/src/executor/join/hash_join_state.rs, src/batch/src/executor/join/nested_loop_join.rs, src/batch/src/executor/merge_sort_exchange.rs, src/batch/src/executor/sort_agg.rs, src/batch/src/executor/values.rs, src/common/src/array/data_chunk.rs, src/common/src/util/chunk_coalesce.rs
Part 3/3 of actual refactor #2663 (Earlier parts: #2934 #2936)
This PR removes `DataChunkBuilder` and `TryFrom<Vec<Column>>`. All callers have been migrated to `new` with an extra cardinality parameter.
=> refactor(DataChunk): use `new` rather than `DataChunkBuilder` or `try_from`

src/frontend/src/scheduler/distributed/query_manager.rs, src/frontend/src/scheduler/hummock_snapshot_manager.rs
…ompaction process
Previously we do not unpin the dml query (It is in single schedule and only unpin if err). 
Usually the dml is happen before query, so this makes the unpin never really happen (cuz there is always a older epoch being pinnned by the dml). 
Add two logs for testing locally. Glad to collect more opinions on where and how to write these logs.
=> fix: should always unpin epoch for dml query

e2e_test/batch/local_mode.slt, src/frontend/src/session.rs
=> fix(config): parameters are case insensitive in set command

src/common/src/buffer/bitmap.rs, src/common/src/consistent_hash/mod.rs, src/common/src/consistent_hash/vnode.rs, src/common/src/lib.rs, src/storage/src/hummock/shared_buffer/mod.rs, src/storage/src/hummock/state_store.rs, src/storage/src/hummock/state_store_tests.rs, src/storage/src/hummock/utils.rs
Introduce non-proto type for vnode bitmap.
#2882 should depend on this PR. More specifically, the non-proto type introduced by this PR will be used in keyspace and interfaces of state store (get, scan, etc.).
=> feat(storage): introduce non-proto type for vnode bitmap

Cargo.lock, src/utils/pgwire/Cargo.toml, src/utils/pgwire/src/lib.rs, src/utils/pgwire/src/pg_extended.rs, src/utils/pgwire/src/pg_field_descriptor.rs, src/utils/pgwire/src/pg_message.rs, src/utils/pgwire/src/pg_protocol.rs, src/utils/pgwire/src/pg_server.rs
- This is PR about the simple extended query mode. 
- The detail of this design and its restriction is in the #2924.
- It supports the concept of "prepared statement" and "portal" in the pgwire semantically. To support generic parameters, its implementation is based on the regular expression replace. It didn't use any parse or infer technology and that's why this feature is limited. 
ref: #2924.
=> feat(pgwire): introduce simple extended query mode

src/frontend/src/lib.rs, src/frontend/src/scheduler/hummock_snapshot_manager.rs
Use the RPC `unpin_snapshot_before` introduced in #2964 in FE hummock manager. 
Different from previous, when unpin a epoch, we decrease the ref count in the maps then calculate the min epoch without query running on it (Note this epoch must <= max_committed_epoch) and tell meta to unpin all epochs before it. 
* Replace previous HashMap to BTreeMap (we can more easily find the lowest epoch)
Fact: unpin epoch b > epoch a do not will not make compaction/GC better cuz the storage only concerned about the min epoch level.
Tested locally and ensure that unpin is happening (log). Need to explore better visualization/test of pin/unpin
Part of #2364
=> feat: use unpin_snapshot_before in FE

src/storage/src/keyspace.rs
=> chore: remove scan_with_start_key

README.md
=> chore(docs): bump to 0.1.8 and update CI badge

src/storage/src/hummock/compactor.rs, src/storage/src/hummock/sstable/group_builder.rs, src/storage/src/hummock/sstable/multi_builder.rs
Currently when we do compaction, we first build all the ssts, and then upload the ssts in parallel. Uploading is IO intensive, while building ssts is CPU intensive. Therefore, the time for IO is wasted while we are building ssts. In this PR, instead of waiting for all ssts to be generated, we will issue an upload tokio task whenever we generate a new sst, and we join all the upload tasks at the end of compaction. In this way, generating ssts and uploading can be done in parallel.
=> feat(storage): support concurrent upload in capacity split sst builder

src/common/src/error.rs, src/common/src/lib.rs, src/common/src/session_config.rs, src/frontend/src/config.rs, src/frontend/src/handler/dml.rs, src/frontend/src/handler/query.rs, src/frontend/src/handler/set.rs, src/frontend/src/optimizer/plan_node/stream_hash_join.rs, src/frontend/src/session.rs, src/frontend/test_runner/src/lib.rs
#3036 , make sure every session config parameter has a default value.
Error when setting a unsupported configuration parameter.
closes #3036
=> refactor(session): error when setting unrecognized configuration parameter

src/storage/src/table/state_table.rs
When we use `state_table.iter()` in a async trait function, it shows a confusing compiler error about signature mismatch. I think it's compiler's problem but I do not get too many evidence. I just removed the unnecessary closure mentioned in the error and it seems work.
@wcy-fdu can you please check that it fixs your problem? I have tested it on my version.
The compiler error looks like:
Because the `.map` looks unnecessary, so I just removed it.
=> fix: the signature unmatch in async trait function

src/connector/src/datagen/split.rs
=> fix(connector): remove redundant warning

e2e_test/streaming/extreme_null.slt
=> fix(e2e): cleanup after extreme null test

src/stream/src/executor/debug.rs, src/stream/src/executor/debug/trace.rs
Fix executor metrics in release mode
=> fix(ci): fix executor metrics in release mode

proto/hummock.proto, src/meta/src/hummock/compaction/mod.rs, src/meta/src/hummock/compactor_manager.rs, src/meta/src/hummock/hummock_manager.rs, src/meta/src/hummock/test_utils.rs, src/meta/src/rpc/server.rs, src/meta/src/stream/meta.rs, src/meta/src/stream/stream_manager.rs, src/storage/src/hummock/compactor.rs, src/storage/src/hummock/compactor_tests.rs
To support clean expired key when compaction
- to get the all TableFragments exist_table_ids by fragment_manager
- compact_task collect the exist_table_id via SSTableInfo
- compactor reclaim the expired_key by compare the table_id ( which decode from key_prefix) with exist_table_id
- https://github.com/singularity-data/risingwave/issues/2908
=> feat(storage): use exist_table_id to filter exist key when compaction

src/common/src/util/ordered/serde.rs, src/storage/src/table/cell_based_table.rs, src/storage/src/table/state_table.rs, src/storage/src/table/test_relational_table.rs
=> chore(storage): remove redundant Result on `serialize_pk`

e2e_test/batch/types/interval.slt, src/frontend/src/binder/expr/value.rs, src/risedevtool/src/bin/risedev-playground.rs, src/sqlparser/src/ast/value.rs
Add a func to parse the argument of interval with specific syntax. Like @xiangjinwu point out in issue.
But now only support like `select interval '5 days'; `
close #3003
=> binder: support string interval

e2e_test/batch/func.slt, src/frontend/src/binder/expr/mod.rs
=> feat: alias data type `STRING` to `VARCHAR`

proto/plan_common.proto, proto/stream_plan.proto, src/batch/src/executor/row_seq_scan.rs, src/compute/tests/integration_tests.rs, src/frontend/src/optimizer/plan_node/batch_seq_scan.rs, src/frontend/src/optimizer/plan_node/stream_index_scan.rs, src/frontend/src/optimizer/plan_node/stream_table_scan.rs, src/frontend/test_runner/tests/testdata/stream_proto.yaml, src/storage/src/table/cell_based_table.rs, src/storage/src/table/test_relational_table.rs, src/stream/src/executor/batch_query.rs, src/stream/src/from_proto/batch_query.rs
- Continued from https://github.com/singularity-data/risingwave/pull/2957.
- Adds dedup pk decoding to `BatchQueryExecutor`.
- Changes `pk_descs` to pass by reference to `DedupPkCellBasedTableIter`. This avoids a `clone` of `pk_descs` each time we call the `execute_inner` method of `BatchQueryExecutor`.
related #588
=> perf(executor): implement dedup pk decoding for BatchQueryExecutor

src/connector/src/pulsar/enumerator/client.rs, src/connector/src/pulsar/source/reader.rs
=> refactor(connector): simplify pulsar reader

ci/plugins/upload-failure-logs/hooks/post-command, ci/workflows/main-cron.yml, ci/workflows/main.yml, ci/workflows/pull-request.yml
upload error logs after Buildkite CI command failed.
issue: https://github.com/singularity-data/risingwave/issues/2898
=> chore(ci): ci upload failure logs

src/batch/src/executor/table_function.rs, src/common/src/types/chrono_wrapper.rs, src/common/src/types/ops.rs, src/expr/src/vector_op/arithmetic_op.rs
`num_traits::CheckedAdd` requires the rhs and output to be the same as self. `std::ops::Add` allows them to be different but does not return err. We define our own trait to get the best of both worlds.
=> refactor(common): extend `CheckedAdd` with `Rhs` and `Output`

src/stream/src/executor/aggregation/mod.rs, src/stream/src/executor/global_simple_agg.rs, src/stream/src/executor/hash_agg.rs, src/stream/src/executor/managed_state/aggregation/value.rs
Previously I misunderstand state table. The insert was done like `insert(pk: group_key, value: agg_value)`.
But in fact, it should be done like `insert(pk: group_key, value: [group_key, agg_value])`. Otherwise the pk_indices in future refactor won't work.
=> fix: fix the table descs of value state

src/meta/src/hummock/compaction_group/manager.rs, src/meta/src/hummock/hummock_manager.rs, src/meta/src/hummock/test_utils.rs, src/meta/src/rpc/server.rs, src/meta/src/stream/meta.rs, src/meta/src/stream/stream_manager.rs
optimize get existing table ids when compact
- remove the dependent of fragment when HummockManager construct
- optimize get existing_table_ids range which limit to compaction_group 
- https://github.com/singularity-data/risingwave/pull/3038
- https://github.com/singularity-data/risingwave/pull/3044
=> feat(storage): optimize get existing table ids when compact

src/meta/src/hummock/compaction/tier_compaction_picker.rs
close https://github.com/singularity-data/risingwave/issues/3066
=> fix(compaction): fix compaction task do not schedule even if the number of L0 files is very large

src/utils/pgwire/src/pg_extended.rs, src/utils/pgwire/src/pg_protocol.rs, src/utils/pgwire/src/pg_server.rs
fix the simple extended query mode 
- **add parse_params() to parse different param according to the type** 
For the simple extended query mode, it just simply replaces the params. This causes problems when I test in local e2e mode. 
For example:
SELECT $1 => SELECT Hello,World ❌ （Expect: SELECT 'Hello,World' ✔）
Then I realized that we couldn't simply replace params, different params need different parse. Such as VARCHAR params need to add (**\'**) on both sides of it. So I add the parse_params() to parse the params and now it only supports the VARCHAR type. We can expand another kind in future.
#2924
=> fix(pg-wire): fix the simple extended query mode

src/connector/src/datagen/mod.rs, src/connector/src/datagen/source/reader.rs
allow datagen to generate random value with specific seed
this pr only works with random int and float. do not support generating deterministic timestamp and varchar. 
part of #3095
=> feat(connector): add random seed for datagen 

src/risedevtool/src/task/etcd_service.rs
Fix https://github.com/singularity-data/risingwave/issues/3054.
Benchmark result of ./risedev d full in single machine:
- Etcd space quota is below 1.2GB.
- Etcd memory usage is below 10GB.
Close https://github.com/singularity-data/risingwave/issues/3054
=> chore(risedev): tune etcd configuration.

src/storage/src/table/state_table.rs, src/storage/src/table/test_relational_table.rs
=> fix: iter only need the pk prefix reference instead of ownership

src/meta/src/hummock/compaction_group/manager.rs, src/storage/src/hummock/compactor.rs, src/storage/src/hummock/compactor_tests.rs
Fix incorrect usage of CompactionConfig::default.
Should use CompactionConfigBuilder.
Temporarily disable StateCleanUpCompactionFilter, because compaction group manager is not providing the correct `existing_table_ids` in 9a34de40.
=> fix(meta): use CompactionConfigBuilder

src/common/src/catalog/schema.rs, src/common/src/error.rs, src/stream/src/executor/aggregation/agg_state.rs, src/stream/src/executor/aggregation/foldable.rs, src/stream/src/executor/aggregation/mod.rs, src/stream/src/executor/aggregation/row_count.rs, src/stream/src/executor/aggregation/single_value.rs, src/stream/src/executor/batch_query.rs, src/stream/src/executor/error.rs, src/stream/src/executor/filter.rs, src/stream/src/executor/global_simple_agg.rs, src/stream/src/executor/hash_agg.rs, src/stream/src/executor/hop_window.rs, src/stream/src/executor/local_simple_agg.rs, src/stream/src/executor/lookup/impl_.rs, src/stream/src/executor/managed_state/aggregation/extreme.rs, src/stream/src/executor/managed_state/aggregation/extreme_serializer.rs, src/stream/src/executor/managed_state/aggregation/mod.rs, src/stream/src/executor/managed_state/aggregation/string_agg.rs, src/stream/src/executor/managed_state/aggregation/value.rs, src/stream/src/executor/mview/materialize.rs, src/stream/src/executor/project.rs, src/stream/src/executor/top_n_executor.rs
=> refactor(streaming): remove `AggStateError` variant and more

src/stream/src/executor/error.rs, src/stream/src/executor/managed_state/top_n/mod.rs, src/stream/src/executor/managed_state/top_n/top_n_bottom_n_state.rs, src/stream/src/executor/managed_state/top_n/top_n_state.rs, src/stream/src/executor/top_n.rs, src/stream/src/executor/top_n_appendonly.rs
Similar to #3140.
closes #3134
=> refactor(stream): remove TopNStateError

e2e_test/batch/func.slt, proto/expr.proto, src/expr/src/expr/build_expr_from_prost.rs, src/expr/src/expr/expr_binary_bytes.rs, src/expr/src/expr/mod.rs, src/expr/src/vector_op/mod.rs, src/expr/src/vector_op/repeat.rs, src/frontend/src/binder/expr/function.rs, src/frontend/src/expr/type_inference.rs
Add support for `repeat` function
#112
=> feat(expr): support `repeat` function

src/frontend/src/scheduler/hummock_snapshot_manager.rs, src/meta/src/hummock/hummock_manager.rs
We should consider visualize the info in Grafana/Dashboard to help debug instead of directly tracing it. 
Otherwise the log size may be huge.
=> chore: remove all tracing logs relates to pin/unpin

risedev.yml, src/risedevtool/src/service_config.rs, src/risedevtool/src/task/compactor_service.rs, src/risedevtool/src/task/compute_node_service.rs, src/risedevtool/src/task/utils.rs, src/storage/src/store_impl.rs
=> chore(storage): deprecate in-memory state store in e2e scenarios

proto/hummock.proto, src/meta/src/hummock/compaction/tier_compaction_picker.rs, src/meta/src/hummock/test_utils.rs, src/storage/src/hummock/compactor.rs, src/storage/src/hummock/shared_buffer/shared_buffer_uploader.rs, src/storage/src/hummock/sstable/builder.rs, src/storage/src/hummock/sstable/group_builder.rs, src/storage/src/hummock/sstable/mod.rs, src/storage/src/hummock/sstable/multi_builder.rs, src/storage/src/hummock/test_utils.rs
- remove `CombinedGrouping`. I have talked with @zwang28. We will split all get/write/flush operations for different group. Of course, the sst files of different group will be also splitted.
- add unit id for sstableinfo for unit aware compaction. See more details in https://github.com/singularity-data/risingwave/pull/3111
=> feat(hummock): remove combine group for compaction

src/stream/src/executor/aggregation/approx_count_distinct.rs
=> fix(streaming): compile error in count distinct

Cargo.lock
Expect to fix the dependency security warning of Github.
None
=> chore: cargo update for frontend/test_runner

src/frontend/src/optimizer/plan_node/logical_project.rs, src/frontend/src/optimizer/plan_node/logical_scan.rs, src/frontend/src/optimizer/property/distribution.rs, src/frontend/test_runner/tests/testdata/pk_derive.yaml
revert #3119 
fix #3086,  #3118
=> fix(optimizer): fix logical scan pk derive

e2e_test/batch/cte.slt, src/frontend/src/binder/relation/mod.rs
See the related issue
Fixes #3155
=> fix(binder): bind CTE only when schema_name is empty

Makefile.toml, src/meta/src/hummock/compaction_group/manager.rs, src/storage/src/hummock/compactor.rs, src/storage/src/hummock/compactor_tests.rs
Workaround compaction filter failure due to unfinished compaction group feature.
Re-enable compaction filter.
=> fix(storage): re-enable compaction filter

docs/README.md
=> fix(doc): Add link for batch local execution mode

ci/plugins/swapfile/hooks/pre-command, ci/workflows/main-cron.yml, ci/workflows/main.yml, ci/workflows/pull-request.yml
Add swap file for ec2 instances to fix the issue of OOM.
issue: https://github.com/singularity-data/risingwave/issues/2898
=> chore(ci): ci add swap file for ec2 instance

src/common/src/error.rs, src/frontend/src/scheduler/distributed/query.rs, src/frontend/src/scheduler/distributed/query_manager.rs, src/frontend/src/scheduler/distributed/stage.rs, src/frontend/src/scheduler/error.rs, src/frontend/src/scheduler/hummock_snapshot_manager.rs, src/frontend/src/scheduler/local.rs, src/frontend/src/scheduler/mod.rs, src/frontend/src/scheduler/plan_fragmenter.rs, src/frontend/src/scheduler/worker_node_manager.rs
=> feat(frontend): introduce scheduler error

src/stream/src/from_proto/batch_query.rs
=> chore: clean up code for legacy frontend

src/frontend/src/scheduler/distributed/query.rs, src/frontend/src/scheduler/plan_fragmenter.rs
Found this issue in #3172, where stage 4 and 7 were marked as `has_table_scan = false` with Fragment:
```
BatchProject { exprs: [$0, ($1 * (1:Int32 - $2))] }
BatchFilter { predicate: ($3 >= '1993-01-01':Varchar::Date) AND ($3 < ('1993-01-01':Varchar::Date + '3 mons 00:00:00':Interval)) }
BatchScan { table: lineitem, columns: [l_suppkey, l_extendedprice, l_discount, l_shipdate] }
```
Hard to test its e2e impact.
=> fix(batch scheduler): has_table_scan had false negative

src/frontend/src/binder/relation/mod.rs, src/frontend/src/binder/relation/window_table_function.rs, src/frontend/src/optimizer/plan_node/logical_hop_window.rs, src/frontend/test_runner/tests/testdata/column_pruning.yaml, src/frontend/test_runner/tests/testdata/nexmark.yaml, src/frontend/test_runner/tests/testdata/time_window.yaml
It's a little hard in parser to support a subquery as the table function's input, but we can achieve the same ability by accepting CTE here.
Close #2733
=> feat(binder): allow CTE as time window table function's input

src/storage/src/monitor/local_metrics.rs
As titled. Previously, we report data_block_miss as meta_miss.
=> fix(metric): fix SST meta miss metric

src/stream/src/executor/global_simple_agg.rs, src/stream/src/executor/hash_agg.rs
The source has pk vec![2]. So the agg should accept pk_indices as vec![2].
The unitest is wrong-written.
=> fix: fix in-correct unittest (pk infer)

src/frontend/src/optimizer/plan_node/logical_agg.rs, src/frontend/test_runner/tests/testdata/agg.yaml, src/frontend/test_runner/tests/testdata/stream_proto.yaml, src/frontend/test_runner/tests/testdata/tpch.yaml
Surprised that nothing breaks down in the backend... :astonished:
closes #3120
=> refactor(front): use no column for pk of simple agg

src/stream/src/executor/aggregation/mod.rs, src/stream/src/executor/global_simple_agg.rs, src/stream/src/executor/hash_agg.rs
It was bug introduced by incorrect arguments (My bad)...
=> refactor: refactor create state table code + fix incorrect arguments

src/storage/src/hummock/local_version_manager.rs
Currently, in `write_shared_buffer`, we will wait in a while loop until the total memory usage of shared buffer batch reduce to below a threshold. However, while we wait in the while loop, there is no await point that takes effect and yields the execution to tokio runtime, and therefore the tokio worker thread will keep being occupied until the memory usage goes below the threshold.
With the behavior of shared buffer described above, the system might get dead locked under the following case. Assume our tokio runtime has only one worker thread and the current memory usage is beyond the threshold. Executor1 write shared buffer, and trigger a flush task. Executor2 write shared buffer, and there is no flush task to issue, and it keep waiting in a while loop and occupy the worker thread. Since …
=> fix(storage): avoid endless loop when flush share buffer

proto/stream_plan.proto, src/frontend/src/optimizer/plan_node/stream_index_scan.rs, src/frontend/src/optimizer/plan_node/stream_table_scan.rs, src/meta/src/stream/stream_manager.rs, src/stream/src/from_proto/batch_query.rs
Use `ExecutorParams.vnode_bitmap` instead
=> refactor(streaming): remove redundant hash_mapping in batch node

src/stream/src/executor/managed_state/aggregation/value.rs
value (agg call value) should always be the last part of a row.
=> fix: the agg value should be put behind pk

src/common/src/util/ordered/serde.rs, src/storage/src/cell_based_row_deserializer.rs, src/storage/src/table/cell_based_table.rs, src/storage/src/table/mod.rs, src/storage/src/table/state_table.rs, src/stream/src/executor/lookup/impl_.rs, src/stream/src/executor/lookup/sides.rs, src/stream/src/executor/managed_state/join/mod.rs, src/stream/src/executor/managed_state/top_n/mod.rs, src/stream/src/executor/managed_state/top_n/top_n_bottom_n_state.rs, src/stream/src/executor/managed_state/top_n/top_n_state.rs, src/stream/src/executor/top_n.rs, src/stream/src/executor/top_n_appendonly.rs
=> refactor(state_table): pre-compute column id mapping

src/connector/src/datagen/source/field_generator/mod.rs, src/connector/src/datagen/source/field_generator/numeric.rs, src/connector/src/datagen/source/generator.rs, src/connector/src/datagen/source/reader.rs
int and float generation supports deterministic results with given seed and offset (we xor seed and offset as new seed). 
the prev impl gen a certain sequence with the given seed, but if we rebuild the source, datagen will output the sequence from the beginning rather than at the specific offset. 
- varchar and timestamp datagen does not support deterministic gen
- …
=> fix(connector): support deterministic datagen for random int/float

src/frontend/src/optimizer/plan_node/logical_agg.rs, src/frontend/test_runner/tests/testdata/tpch.yaml
=> fix(frontend): show distinct in agg

src/batch/src/executor/row_seq_scan.rs, src/compute/tests/integration_tests.rs, src/storage/src/table/cell_based_table.rs, src/storage/src/table/test_relational_table.rs, src/stream/src/executor/batch_query.rs
See: https://github.com/singularity-data/risingwave/issues/3203#issuecomment-1154806210
related #3203
=> refactor(cell_based_table): rename iter_with_pk to dedup_pk_iter

src/expr/src/expr/expr_unary.rs, src/expr/src/vector_op/cast.rs, src/frontend/src/expr/type_inference.rs
The frontend binder is already removing unnecessary cast between same type.
=> refactor: cleanup dead code that casts between same type

Cargo.lock, src/batch/src/execution/grpc_exchange.rs, src/common/src/error.rs, src/frontend/src/handler/dml.rs, src/frontend/src/meta_client.rs, src/frontend/src/scheduler/distributed/query_manager.rs, src/frontend/src/test_utils.rs, src/meta/src/barrier/command.rs, src/meta/src/barrier/mod.rs, src/meta/src/barrier/recovery.rs, src/meta/src/hummock/mock_hummock_meta_client.rs, src/meta/src/stream/source_manager.rs, src/meta/src/stream/stream_manager.rs, src/rpc_client/Cargo.toml, src/rpc_client/src/compute_client.rs, src/rpc_client/src/compute_client_pool.rs, src/rpc_client/src/error.rs, src/rpc_client/src/hummock_meta_client.rs, src/rpc_client/src/lib.rs, src/rpc_client/src/meta_client.rs, src/rpc_client/src/stream_client_pool.rs, src/storage/src/hummock/hummock_meta_client.rs
As title.
We should always use the wrapper functions in `rpc_client` crate in the future. We may store some info about the worker nodes there and refine the error messages.
- #3156
=> chore: introduce rpc error

src/frontend/src/session.rs, src/utils/pgwire/src/pg_extended.rs, src/utils/pgwire/src/pg_protocol.rs, src/utils/pgwire/src/pg_server.rs
- Add the infer_return_type interface in the session trait.
- Use the infer_return_type interface in pgwire to get the row_description.
- To test the modification of pgwire, add the implementation of infer_return_type  in mock_session and pass the original unit test.
- add simple infer_return_type implementation in frontend session to support no param SQL.
#3131
=> feat(pgwire): add infer_return_type interface in session trait

src/common/src/array/column_proto_readers.rs, src/common/src/types/chrono_wrapper.rs, src/frontend/src/stream_fragmenter/mod.rs, src/utils/pgwire/src/pg_field_descriptor.rs, src/utils/pgwire/src/pg_response.rs
as title. Found by searching `Java` 🥸
=> refactor: remove some workarounds about Java frontend

proto/hummock.proto, src/ctl/src/cmd_impl/hummock/trigger_manual_compaction.rs, src/ctl/src/lib.rs, src/meta/src/hummock/compaction/level_selector.rs, src/meta/src/hummock/compaction/tier_compaction_picker.rs, src/meta/src/hummock/compactor_manager.rs, src/meta/src/hummock/hummock_manager.rs, src/meta/src/hummock/hummock_manager_tests.rs, src/meta/src/hummock/level_handler.rs, src/meta/src/hummock/mock_hummock_meta_client.rs, src/meta/src/hummock/test_utils.rs, src/meta/src/rpc/server.rs, src/meta/src/rpc/service/hummock_service.rs, src/meta/src/stream/stream_manager.rs, src/rpc_client/src/hummock_meta_client.rs, src/rpc_client/src/meta_client.rs, src/storage/src/hummock/hummock_meta_client.rs
simply support trigger manual compaction
- simply support trigger manual compaction in hummock_manager
- add trigger manual compaction rpc
- support  trigger manual compaction for risectl
- https://github.com/singularity-data/risingwave/issues/3097
=> feat(storage): simply support trigger manual compaction and risectl

src/storage/src/hummock/compactor.rs, src/storage/src/hummock/compactor_tests.rs
This PR temporarily disables compaction filter.
Compaction filter relies on compaction group manager to provide `existing_table_ids`. Current source is not in `existing_table_ids`, so its state can be incorrectly removed by compaction filter.
=> fix(storage): disable compaction filter temporarily.

src/compute/tests/integration_tests.rs, src/storage/src/table/cell_based_table.rs, src/stream/src/from_proto/batch_query.rs
It is not ad-hoc anymore. Was a workaround
=> refactor(storage): remove new_adhoc from CellBasedTable

src/batch/src/executor/row_seq_scan.rs, src/common/src/util/ordered/serde.rs, src/compute/tests/integration_tests.rs, src/storage/src/table/cell_based_table.rs, src/storage/src/table/state_table.rs, src/storage/src/table/test_relational_table.rs, src/stream/src/executor/managed_state/aggregation/value.rs, src/stream/src/executor/managed_state/top_n/top_n_bottom_n_state.rs, src/stream/src/executor/managed_state/top_n/top_n_state.rs, src/stream/src/executor/mview/materialize.rs, src/stream/src/executor/mview/test_utils.rs, src/stream/src/from_proto/batch_query.rs
As title
close https://github.com/singularity-data/risingwave/issues/3232
=> refactor(state_table): simplify interface of insert / delete

proto/stream_plan.proto, src/frontend/src/optimizer/plan_node/stream_exchange.rs, src/frontend/src/optimizer/plan_node/stream_hash_agg.rs, src/frontend/src/optimizer/plan_node/stream_hash_join.rs, src/frontend/src/optimizer/plan_node/stream_materialize.rs, src/frontend/src/optimizer/plan_node/stream_project.rs, src/frontend/src/optimizer/plan_node/stream_simple_agg.rs, src/frontend/src/optimizer/plan_node/stream_source.rs, src/frontend/src/optimizer/plan_node/stream_table_scan.rs, src/frontend/src/optimizer/plan_node/stream_topn.rs, src/frontend/test_runner/tests/testdata/append_only.yaml, src/meta/src/stream/test_fragmenter.rs, src/stream/src/executor/hash_join.rs, src/stream/src/from_proto/global_simple_agg.rs, src/stream/src/from_proto/hash_agg.rs, src/stream/src/from_proto/hash_join.rs, src/stream/src/from_proto/local_simple_agg.rs
Integrate append-only version executors (TopN, HashAgg, HashJoin, SimpleAgg) to the stream graph.
close #2407
close #1550
=> feat(streaming): integrate append-only executors to stream graph

e2e_test/batch/func.slt, e2e_test/batch/functions/concat.slt, proto/expr.proto, src/expr/src/expr/expr_unary.rs, src/expr/src/expr/mod.rs, src/expr/src/vector_op/cast.rs, src/frontend/src/expr/function_call.rs, src/frontend/src/expr/mod.rs, src/frontend/src/expr/type_inference.rs, src/frontend/test_runner/tests/testdata/expr.yaml
Fixes #3146 by introducing a dedicated `BoolOut` expr. All other types can share the same expr/func for **I/O** and **from/to-string cast**.
Check doc comment of `cast_output` for details. The 2 different implementations in PostgreSQL are called `boolout` and `booltext`.
In PostgreSQL, only 4 types have cast-to-string different from output format: `bool`, `cidr`, `inet`, `xml`, and only 1 type has cast-from-string different from input format: `xml`.
=> fix(expr): bool has different output format and cast-string format

src/batch/src/executor/generic_exchange.rs, src/batch/src/executor/merge_sort_exchange.rs, src/batch/src/executor/test_utils.rs
Use a concrete struct to create a source instead of merely generics.
For each concrete source, we have a dedicated concrete source creator struct to initialize. This is helpful when we want to ingest different data into different sources during tests.
closes #1645
=> refactor(batch): easier for writing tests with customized exchange source

src/storage/src/table/state_table.rs, src/stream/src/executor/managed_state/top_n/top_n_state.rs
=> chore: fix typo in state table

proto/data.proto, src/meta/src/barrier/command.rs, src/meta/src/barrier/mod.rs, src/meta/src/stream/source_manager.rs, src/stream/src/executor/mod.rs
=> style(meta): remove NothingMutation

src/batch/src/executor/generic_exchange.rs, src/batch/src/executor/merge_sort_exchange.rs
>source_idx: usize,
>current_source: Option<Box<dyn ExchangeSource>>,
unused.
>first_execution
Not needed anymore as `async fn do_execute(mut self: Box<Self>) {` is implemented by async_stream
=> refactor(batch): clean up unused fields

src/meta/src/manager/hash_mapping.rs
Alter strategy of assigning vnodes to parallel unit when generating vnode mappings, so that initial vnode mapping will look like:
```
[1,1,1,1,2,2,2,2,3,3,3,3,4,4,4]
```
instead of 
```
[1,1,1,2,2,2,3,3,3,4,4,4,1,2,3]
```
In this way:
- The compression could achieve better effects. 
- It looks prettier.
=> chore(meta): make vnodes sequential in initial hash mapping

src/object_store/src/object/error.rs, src/storage/src/error.rs
>The #[from] attribute always implies that the same field is #[source], so you don't ever need to specify both attributes.
=> refactor(storage): remove source when there is a from attribute

proto/meta.proto, src/connector/src/base.rs, src/connector/src/datagen/source/reader.rs, src/connector/src/lib.rs, src/connector/src/macros.rs, src/connector/src/nexmark/source/reader.rs, src/connector/src/state.rs, src/meta/src/barrier/command.rs, src/meta/src/stream/source_manager.rs, src/source/src/connector_source.rs, src/stream/src/executor/mod.rs, src/stream/src/executor/source.rs
=> chore: introduce ConnectorSplit protobuf message

src/batch/src/task/broadcast_channel.rs, src/batch/src/task/fifo_channel.rs, src/batch/src/task/hash_shuffle_channel.rs, src/batch/src/task/mod.rs
ref: #3024 
For 3 channels:
FIFO, HASH, BROADCAST
=> refactor: use bounded channel for 3 channels

src/utils/pgwire/src/pg_field_descriptor.rs
- fix the wrong typeOID of Decimal type.
- Add the comment to avoid bug like this in the future.
#3015
=> fix(pgwire): fix the wrong typeOID of Decimal type

src/stream/src/executor/top_n_appendonly.rs
As title.
close https://github.com/singularity-data/risingwave/issues/3286
=> fix(stream): fix append_only top_n

src/frontend/src/session.rs
The original implementation of infer_return_type interface in frontend is copied from run_statement. It will actually execute the statement and get the result description from the result of execution. This implementation is primarily for testing purposes but it's inefficient. Infer_return_type API is to get the result description but needn't execute.
Hence we give a new implementation for infer_return_type. It calls a new function "infer", "infer" will get the result description 
of the query statement but not execute. 
#3131
=> feat: implement infer_return_type in frontend

Cargo.lock, Makefile.toml, src/cmd/Cargo.toml, src/cmd/src/bin/ctl.rs, src/cmd_all/src/bin/risingwave.rs, src/ctl/src/common/hummock_service.rs, src/ctl/src/common/meta_service.rs, src/ctl/src/lib.rs, src/risedevtool/src/bin/risedev-playground.rs, src/risedevtool/src/lib.rs, src/risedevtool/src/risectl_env.rs
As title. Now developers should use `./risedev d && ./risedev ctl` to start risectl. An environment file will be generated, like:
```
export RW_HUMMOCK_URL="hummock+minio://hummockadmin:hummockadmin@127.0.0.1:9301/hummock001"
export RW_META_ADDR="http://127.0.0.1:5690"
```
=> feat(risedev): generate risectl config

src/frontend/src/handler/mod.rs, src/frontend/src/session.rs, src/frontend/src/test_utils.rs, src/frontend/test_runner/src/lib.rs
Add `Arc<str>` into `OptimizerContext` to store `raw_sql` strings for debugging.
- Add `Arc<str>` into `OptimizerContext`
- Refactor to create `Arc<str>` at entry points
Closes #2777
=> feat(frontend): Add sql string into context for debugging

docs/developer-guide.md
We can now directly `approve and run` instead.
=> doc: no need to manually check in PR from forks

proto/common.proto, proto/data.proto, proto/stream_plan.proto, src/common/src/array/decimal_array.rs, src/common/src/array/primitive_array.rs, src/common/src/array/utf8_array.rs, src/common/src/buffer/bitmap.rs, src/common/src/types/mod.rs, src/meta/src/hummock/compaction/overlap_strategy.rs, src/meta/src/hummock/test_utils.rs, src/meta/src/manager/hash_mapping.rs, src/meta/src/stream/scheduler.rs, src/meta/src/stream/stream_graph.rs, src/meta/src/stream/stream_manager.rs, src/storage/src/hummock/sstable/builder.rs, src/stream/src/from_proto/batch_query.rs, src/stream/src/task/stream_manager.rs
As title.
- `Bitmap` is easier to set and get the value for some index.
- `Bitmap` is implemented with `Bytes` (#2831) which is born to clone cheaply.
=> refactor: use packed bitmap struct for vnode bitmap

src/storage/src/table/state_table.rs, src/stream/src/executor/aggregation/agg_state.rs, src/stream/src/executor/aggregation/mod.rs, src/stream/src/executor/global_simple_agg.rs, src/stream/src/executor/hash_agg.rs, src/stream/src/executor/managed_state/aggregation/extreme.rs, src/stream/src/executor/managed_state/aggregation/extreme_serializer.rs, src/stream/src/executor/managed_state/aggregation/mod.rs, src/stream/src/executor/managed_state/aggregation/string_agg.rs, src/stream/src/executor/managed_state/aggregation/value.rs
Sorry for the huge PR, but this should be the min efforts to introduce the relational refactor. Mainly change is the AggState interface (mostly`get_output`), now we pass StateTable as & or &mut. 
After this PR, besides StringAgg (we currently do not have e2e test in it so i prefer not include here), all other agg call should use the relational table. 
* Change the function signature. Add &StateTable or &mut StateTable
* `get_output(epoch)` -> `get_output(epoch, &StateTable<S>)`. The states may need to fetch data from remote store.
* Same for `row_count`, `mark_as_dirty`.
* For HashAgg, I wrap a `Arc<Mutex<>>` for all State Tables cuz I do not want to solve too difficult Multi-thread problems in this PR. Discussed and we thought `apply_batch` (Mostly mem_table write) should not be …
=> feat: apply relational refactor for hash agg (max, min)

src/batch/src/executor/row_seq_scan.rs, src/common/src/util/ordered/serde.rs, src/compute/tests/integration_tests.rs, src/storage/src/lib.rs, src/storage/src/table/cell_based_table.rs, src/storage/src/table/state_table.rs, src/stream/src/from_proto/batch_query.rs
As title. This PR also refactors some unused logic.
- #3316
=> refactor(storage): remove `Option` on pk serializer of cell-based table

proto/hummock.proto, src/ctl/src/cmd_impl/hummock/trigger_manual_compaction.rs, src/ctl/src/lib.rs, src/meta/src/hummock/compaction/compaction_picker.rs, src/meta/src/hummock/compaction/level_selector.rs, src/meta/src/hummock/compaction/manual_compaction_picker.rs, src/meta/src/hummock/compaction/min_overlap_compaction_picker.rs, src/meta/src/hummock/compaction/mod.rs, src/meta/src/hummock/compaction/tier_compaction_picker.rs, src/meta/src/hummock/hummock_manager.rs, src/meta/src/hummock/hummock_manager_tests.rs, src/meta/src/hummock/mock_hummock_meta_client.rs, src/meta/src/rpc/server.rs, src/meta/src/rpc/service/hummock_service.rs, src/rpc_client/src/hummock_meta_client.rs, src/rpc_client/src/meta_client.rs, src/storage/src/hummock/hummock_meta_client.rs
add manual compaction picker  and support more optional parameters for  targeted compaction
- a new indenpendent compaction_picker for manual_compaction
- support more optional parameters for manual_compaction and distinguish get_compaction_task for manual
- risectl support  parameters above
- https://github.com/singularity-data/risingwave/issues/3097
=> feat(storage): add manual compaction picker for targeted compaction

proto/hummock.proto, src/meta/src/hummock/compaction/overlap_strategy.rs, src/meta/src/hummock/compaction/tier_compaction_picker.rs, src/meta/src/hummock/hummock_manager.rs, src/meta/src/hummock/test_utils.rs, src/storage/src/hummock/compactor.rs, src/storage/src/hummock/shared_buffer/shared_buffer_uploader.rs, src/storage/src/hummock/sstable/builder.rs, src/storage/src/hummock/sstable/mod.rs, src/storage/src/hummock/sstable/multi_builder.rs, src/storage/src/hummock/test_utils.rs
remove vnode bitmap in sst info, because we no longer need that
=> refactor(vnode bitmap): remove vnode bitmap in sst info

src/frontend/src/catalog/source_catalog.rs
As title.
Dashboard executor info of tpch Q12
```
{
"operatorId": "89",
"pkIndices": [
2,
5
],
"appendOnly": true,
"identity": "StreamAppendOnlyHashJoin { type: Inner, predicate: $0 = $3 }",
"fields": [
...
],
"hashJoin": {
"leftKey": [
0
],
"rightKey": [
0
],
"leftTableId": 20,
"rightTableId": 21,
"distKeyL": [
0
],
"distKeyR": [
0
],
"isAppendOnly": true
}
}
```
=> feat(stream): enable append-only mv plan for kafka source

Cargo.lock, src/cmd/src/bin/ctl.rs, src/ctl/Cargo.toml, src/ctl/src/cmd_impl/bench.rs, src/ctl/src/cmd_impl/table/scan.rs, src/ctl/src/common/hummock_service.rs, src/ctl/src/lib.rs
This bench command is very simple now. We can use risectl to connect to an existing cluster and bench on an existing table. In the future, we can mock some workloads like join, agg, etc. to know more about the system performance.
Generally, this should be used like:
* Start a cluster and create materialized view, use data source to ingest real data.
* Run risectl on existing data to do benchmarks.
=> feat(ctl): add bench command

src/frontend/src/binder/query.rs, src/frontend/test_runner/tests/testdata/subquery.yaml
as title
close https://github.com/singularity-data/risingwave/issues/3345
=> fix(binder): do not allow correlated input ref in order by

src/frontend/src/binder/query.rs, src/frontend/src/binder/relation/join.rs, src/frontend/test_runner/tests/testdata/subquery.yaml
After reconsidering https://github.com/singularity-data/risingwave/pull/3346/, I think the actual problem is correlated input ref should not occur in join tables, not only order exprs.
=> fix(binder): do not allow correlated subquery in join tables

.github/ISSUE_TEMPLATE/feature_request.md
As the description, `type/enhancement` is used for enhancement **based on current implementation**, so I'm really curious that why it's used for `feature-request` template.
=> chore(github): feature-request template should use the feature label

src/frontend/src/scheduler/worker_node_manager.rs, src/frontend/src/session.rs, src/rpc_client/src/meta_client.rs
Since we have notification service now, frontend need not query meta by itself on initialization.
=> fix(frontend): remove redundant request to meta in frontend

src/batch/src/task/broadcast_channel.rs, src/batch/src/task/channel.rs, src/batch/src/task/data_chunk_in_channel.rs, src/batch/src/task/fifo_channel.rs, src/batch/src/task/hash_shuffle_channel.rs, src/batch/src/task/mod.rs, src/batch/src/task/task_execution.rs
Chunk being broadcasted should only be serialized once at most. If it is always being sent via local channels, then it should never be serialized.
For FIFO/hash channels, they should not pay an extra cost, i.e. stay the same.
closes #3282
=> feat(batch): serialize chunk broadcasted only once

src/frontend/src/expr/function_call.rs, src/frontend/src/expr/type_inference/cast.rs, src/frontend/src/expr/type_inference/func.rs, src/frontend/src/expr/type_inference/mod.rs
This PR contains 4 refactors that prepares for implicit cast (preview in #3296).
* `FuncSigMap` hides the implementation of `HashMap<FuncSign, DataTypeName>`. It will be updated to another lookup structure. With this refactoring, the `build_type_derive_map` with `insert` calls can be reused.
* `infer_type` interface takes input exprs and potentially returns them casted to the matching function's parameters.
* `DataTypeName` to `DataType` mapping extracted
* `cast_ok_base` works on `DataTypeName` rather than `DataType`.
=> refactor(binder): prepare for implicit cast support

src/stream/src/executor/hash_agg.rs
* Remove Arc Mutex on StateTable Vector
* Deparallel states apply_batch. It is by design single-thread as we only have one mem_table for write and it is not thread safe. The mem write should be fast so not bothered to be multithread. Now we only paralllelize the async remove fetch.
=> refactor: deparallel hash agg apply batch + remove Arc Mutex

proto/catalog.proto, src/frontend/src/catalog/table_catalog.rs, src/frontend/src/handler/create_mv.rs, src/frontend/src/handler/create_source.rs, src/frontend/src/handler/create_table.rs, src/frontend/src/handler/explain.rs, src/frontend/src/handler/mod.rs, src/frontend/src/handler/util.rs, src/frontend/src/optimizer/plan_node/logical_agg.rs, src/frontend/src/optimizer/plan_node/stream_hash_join.rs, src/frontend/src/optimizer/plan_node/stream_materialize.rs, src/frontend/test_runner/src/lib.rs, src/sqlparser/src/ast/statement.rs
catalog add properties for
- add properties in catalog.proto for persisting
- handler fit properties
- fix some test with properties
- https://github.com/singularity-data/risingwave/issues/3379
- https://github.com/singularity-data/risingwave/issues/3298
=> feat(frontend): catalog add properties for ttl

e2e_test/batch/distribution_mode.slt, e2e_test/batch/functions/trim.slt.part, e2e_test/batch/local_mode.slt, src/expr/src/expr/build_expr_from_prost.rs, src/expr/src/expr/expr_binary_bytes.rs, src/expr/src/vector_op/mod.rs, src/expr/src/vector_op/trim.rs, src/expr/src/vector_op/trim_characters.rs
Previously, `trim/ltrim/rtrim` does not support trimming user-defined characters other than spaces.
closes #3356
=> fix(expr): trim

src/utils/pgwire/src/pg_extended.rs, src/utils/pgwire/src/pg_message.rs, src/utils/pgwire/src/pg_protocol.rs
Support portal type in describe message. It is required when using JDBC.
#3392
=> feat(pgwire):support portal description 

Makefile.toml
About 4 hours ago, `cargo_metadata` released 0.14.3 which broke semantic versioning and caused `./risedev install-tools` to fail. 🤪
```
error[E0277]: the trait bound `Box<str>: From<Edition>` is not satisfied
--> /Users/wangrunji/.cargo/registry/src/github.com-1ecc6299db9ec823/guppy-0.14.2/src/graph/build.rs:328:42
|
328 |                 edition: package.edition.into(),
|                                          ^^^^ the trait `From<Edition>` is not implemented for `Box<str>`
|
= help: the following other types implement trait `From<T>`:
<Box<(dyn StdError + 'a)> as From<E>>
<Box<(dyn StdError + 'static)> as From<&str>> …
```
=> fix(risedev): fix install-tools

docker/Dockerfile
=> feat(build): compress debug info in docker builds

proto/catalog.proto, proto/meta.proto, src/meta/src/rpc/service/notification_service.rs
=> chore(meta): deprecate VirtualTable in catalog.proto

src/stream/src/executor/source.rs
Should be merged after concurrent checkpoint. Remove source limit.
close https://github.com/singularity-data/risingwave/issues/3403
=> feat(streaming): remove source limit for concurrent ckpt

.config/nextest.toml, ci/docker-compose.yml, ci/scripts/unit-test.sh, ci/workflows/main.yml, ci/workflows/pull-request.yml
Tweak nextest config, so that it can be more useful. Also produce junit file so that it can integrate with Buildkite's test analytics better.
=> chore(ci): better nextest config

risedev.yml
Signed-off-by: Wish <breezewish@outlook.com>
Utilize https://github.com/singularity-data/risingwave/pull/3444 for the online playground docker image.
https://github.com/singularity-data/risingwave/pull/3444
=> chore(risedev): Add a profile for the online playground

proto/hummock.proto, src/meta/src/hummock/compaction_group/manager.rs, src/meta/src/hummock/compaction_group/mod.rs, src/meta/src/rpc/service/ddl_service.rs, src/meta/src/stream/meta.rs, src/meta/src/stream/source_manager.rs, src/meta/src/stream/stream_manager.rs
compaction group support table_option of internal_table
- TableOption proto 
- register table_option to compaction_group
- interface for table_option read
- https://github.com/singularity-data/risingwave/issues/3298
=> feat(storage): compaction group support table_option of internal_table

dashboard/components/Layout.js, dashboard/pages/_app.js
- Fix page flashing caused by loading wrapper.
- Add layout title and fix nav item animation
From: 
To:
=> refine(dashboard): layout and loading indicator

src/common/src/array/data_chunk_iter.rs, src/common/src/array/mod.rs, src/common/src/types/mod.rs, src/storage/src/table/cell_based_table.rs
As title. This is a fix for common types except for array and struct. Check #3457 for more details.
- #3457
=> fix(array): inconsistent hash behavior of `Datum` and `Array::Item`

src/connector/src/datagen/mod.rs, src/connector/src/datagen/source/generator.rs, src/connector/src/datagen/source/mod.rs
Signed-off-by: Ryan Russell <git@ryanrussell.org>
Improve the datagen connector readability.
=> refactor(datagen): improve datagen connector readability

src/utils/logging/Cargo.toml, src/utils/memcomparable/src/de.rs, src/utils/pgwire/src/pg_protocol.rs, src/utils/pgwire/src/pg_server.rs
Signed-off-by: Ryan Russell <git@ryanrussell.org>
More code readability improvements focused in the `/src/utils` path
=> chore(utils): improve readability

Cargo.lock, proto/hummock.proto, src/common/Cargo.toml, src/common/src/config.rs, src/meta/src/hummock/compaction/compaction_config.rs, src/meta/src/hummock/compaction/level_selector.rs, src/meta/src/hummock/compaction/mod.rs, src/meta/src/hummock/compaction_group/manager.rs, src/meta/src/hummock/compaction_group/mod.rs, src/meta/src/hummock/compactor_manager.rs, src/meta/src/hummock/hummock_manager.rs, src/storage/Cargo.toml, src/storage/hummock_sdk/src/key.rs, src/storage/src/hummock/compactor.rs, src/storage/src/hummock/compactor_tests.rs
hummock support ttl ability with compaction_filter
- bitflags to control compaction_filter 
- multi_compaction_filter (state_clean_up and ttl)
- transfer table_opiton and mask to compactor for compaction_filter
- unit-test for ttl_compaction_filter
- https://github.com/singularity-data/risingwave/issues/3298
=> feat(storage): hummock support ttl ability with compaction_filter

src/meta/src/rpc/service/ddl_service.rs, src/meta/src/stream/source_manager.rs
=> fix(source): fix warning from source manager when drop materialized source

src/batch/src/executor/row_seq_scan.rs
Simplify the auxiliary function introduced in #3470.
The Preferred solution is to do this type alignment in frontend: #3479 #3478
=> refactor(batch): simplify scan_range literal casting

src/common/src/config.rs, src/meta/src/hummock/compaction/compaction_config.rs, src/meta/src/hummock/compaction/level_selector.rs, src/meta/src/hummock/compaction_group/manager.rs, src/meta/src/hummock/compaction_group/mod.rs, src/storage/src/hummock/compactor.rs, src/storage/src/hummock/compactor_tests.rs
as title
- ~[ ] I have written necessary docs and comments~
- https://github.com/singularity-data/risingwave/pull/3438
=> feat(storage): use STATE_CLEAN and TTL as default compaction_filter_mask

src/common/src/catalog/column.rs, src/frontend/src/optimizer/plan_node/logical_agg.rs, src/stream/src/executor/aggregation/mod.rs, src/stream/src/executor/hash_agg.rs, src/stream/src/from_proto/hash_agg.rs
* Fix the wrong infer in `infer_internal_table_catalog`. Done some Simple DRY. Previous code is hard to maintain and read... May need more work in future.
* CN parse the table catalog and init the state table.
* Tweak some unit test, infer table catalog manually. 
Part of #3475
=> refactor(relational_states): use fe table catalog for hash agg

proto/stream_plan.proto, src/frontend/src/optimizer/plan_node/stream_hash_agg.rs, src/frontend/test_runner/tests/testdata/stream_proto.yaml, src/stream/src/from_proto/hash_agg.rs
As you can see in the code, when serialize "distribution_keys" in FE, it's `logical.group_keys()`. However in some cases, the dist key might be different from group keys (See the pic above, the hash agg and hash join are in same fragment). So it's better to distinguish dist keys and group keys. 
In future, after we done the refactor of state table, might no need to pass dist keys in each StreamNode. Ideally, we can get dist keys from state table and encode it as vnode.
ref: #3456.
=> refactor(hash-agg): rename distribution keys to group keys

src/batch/src/executor/row_seq_scan.rs
=> chore: remove a warn! introduced by mistake when debugging

proto/hummock.proto, src/meta/src/hummock/hummock_manager.rs, src/meta/src/hummock/model/mod.rs, src/meta/src/hummock/model/version_delta.rs
store incremental hummock version in meta
it will replace hummock version
=> perf(hummock manager): store incremental hummock version in meta

src/stream/src/executor/aggregation/mod.rs, src/stream/src/executor/global_simple_agg.rs, src/stream/src/executor/hash_agg.rs, src/stream/src/executor/integration_tests.rs, src/stream/src/executor/test_utils.rs, src/stream/src/from_proto/global_simple_agg.rs, src/stream/src/from_proto/hash_agg.rs
…nd some simple refactor
* Add a method in mod.rs `generate_state_table_from_proto`. Currently reused by global agg and simple agg. 
* Add a method in test_util.rs `new_boxed_simple_agg_executor`. Currently used by tests in simple agg.
=> refactor(simple-agg): use fe generated table catalog for simple agg + some code-reuse refactor

docs/state-store-overview.md
Fix a little little typo in the document.
=> doc(state-store): fix a typo

src/batch/src/executor/insert.rs, src/bench/ss_bench/operations/get.rs, src/bench/ss_bench/operations/prefix_scan_random.rs, src/common/src/catalog/mod.rs, src/common/src/util/epoch.rs, src/ctl/src/cmd_impl/hummock/list_kv.rs, src/meta/src/hummock/compaction_group/manager.rs, src/meta/src/hummock/compaction_group/mod.rs, src/storage/src/hummock/compactor.rs, src/storage/src/hummock/compactor_tests.rs, src/storage/src/hummock/iterator/backward_user.rs, src/storage/src/hummock/iterator/forward_user.rs, src/storage/src/hummock/iterator/test_utils.rs, src/storage/src/hummock/snapshot_tests.rs, src/storage/src/hummock/state_store.rs, src/storage/src/hummock/state_store_tests.rs, src/storage/src/keyspace.rs, src/storage/src/memory.rs, src/storage/src/storage_failpoints/test_hummock.rs, src/storage/src/store.rs, src/stream/src/executor/lookup/tests.rs
Some change about TTL as title
- ~`keyspace` adapt table properties with `CatalogTable`~
-  `UserIterator` add check through min_epoch
- `ReadOptions` add Option<ttl> and support to calculate min_epoch for iterator
- https://github.com/singularity-data/risingwave/issues/3298
=> feat(storage):   iterator support min_epoch check

src/compute/src/rpc/service/stream_service.rs, src/storage/src/hummock/local_version.rs, src/storage/src/hummock/local_version_manager.rs, src/storage/src/hummock/shared_buffer/mod.rs, src/storage/src/hummock/state_store.rs, src/storage/src/memory.rs, src/storage/src/monitor/monitored_store.rs, src/storage/src/panic_store.rs, src/storage/src/store.rs, src/stream/src/task/barrier_manager.rs, src/stream/src/task/barrier_manager/managed_state.rs, src/stream/src/task/stream_manager.rs
During the recovery process, we stop all actors in the compute node but we miss to clear buffers in storage, which keeps the memory unreleased. This PR fixes the problem by adding a method to clear shared buffer and calling it on stop_all_actors.
=> fix: clear shared buffer on stop_all_actors

src/frontend/src/optimizer/plan_node/batch_simple_agg.rs, src/frontend/src/optimizer/plan_node/batch_topn.rs
picked from #https://github.com/singularity-data/risingwave/pull/3251
=> fix(optimizer): batch distinct agg & local topn distribution

src/frontend/src/binder/expr/binary_op.rs, src/frontend/src/binder/expr/value.rs, src/frontend/src/binder/set_expr.rs
as title
old error for create mv with parentheses is confusing
new
=> chore(binder): add descriptions to some NotImplemented error

src/utils/pgwire/src/error.rs, src/utils/pgwire/src/pg_protocol.rs
=> chore(pgwire): add simple 'unrecognized_param' error handle

ci/build-ci-image.sh, ci/docker-compose.yml, ci/scripts/e2e-test-parallel.sh, ci/scripts/e2e-test.sh, ci/workflows/main.yml, ci/workflows/pull-request.yml
- Produce junit file with sqllogictest and upload it to Buildkite test analytics
- Allow parallel e2e test to fail
close https://github.com/singularity-data/risingwave/issues/3439
=> feat(ci): integrate sqllogictest with test analysis

src/stream/src/executor/lookup/impl_.rs, src/stream/src/executor/lookup/sides.rs, src/stream/src/from_proto/lookup.rs
=> refactor(lookup): use state table for lookup

proto/plan_common.proto, proto/stream_plan.proto, src/common/src/catalog/physical_table.rs, src/common/src/util/sort_util.rs, src/frontend/src/optimizer/plan_node/stream_materialize.rs, src/frontend/src/optimizer/plan_node/stream_topn.rs, src/frontend/src/optimizer/property/order.rs, src/frontend/src/stream_fragmenter/rewrite/delta_join.rs, src/frontend/test_runner/tests/testdata/stream_proto.yaml, src/meta/src/stream/test_fragmenter.rs
Trying to dedup `OrderedColumnDesc`, and use `FieldOrder` instead (https://github.com/singularity-data/risingwave/issues/3638). But found it difficult. Simplify `ColumnOrder` proto first
=> refactor(proto): simplify ColumnOrder

e2e_test/batch/types/arithmetic.slt.part, src/common/src/types/interval.rs, src/expr/src/expr/expr_binary_nonnull.rs, src/expr/src/vector_op/arithmetic_op.rs
Signed-off-by: Shmiwy <wyf000219@126.com>
support these expr
+ float * interval
+ interval * float
#924 #3341
=> feat(expr): support float mul interval

.github/pull_request_template.md
Added documentation-specific instructions so that developers can specify whether their PR contains user-facing changes, categorize the changes if so, and create a release note draft. The purpose of this template change is to make it easier for all to locate user-facing changes, and easier for tech writers to create official release notes. 
- Describe clearly one logical change …
=> chore(doc): add documentation-specific instructions

e2e_test/batch/basic/func.slt.part, src/frontend/src/binder/expr/function.rs
=> feat: add current_database()

src/storage/src/hummock/local_version_manager.rs
close https://github.com/singularity-data/risingwave/issues/3639
This bug may cause write lose because the shared buffer was created in BTreeMap of before version but the other thread will replace the whole `LocalVersion`, include BTreeMap of shared-buffer and `HummockVersion`.
* …
=> fix(storage): fix race condition between pin version and new shared-buffer

ci/workflows/docker.yml, ci/workflows/main.yml
=> fix(ci): fix env variables in docker push step

src/frontend/test_runner/tests/testdata/nexmark.yaml
* date_format -> to_char
* split_index -> split_part
* hour -> extract
#132
=> test(nexmark): rewrite flinksql function to the corresponding pg one

src/batch/Cargo.toml, src/batch/benches/filter.rs, src/batch/benches/nested_loop_join.rs, src/batch/src/executor/join/mod.rs, src/batch/src/executor/join/nested_loop_join.rs, src/batch/src/executor/join/row_level_iter.rs, src/batch/src/executor/test_utils.rs
Add micro benchmark for NestedLoopJoinExecutor and some minor changes.
Part of the benchmark results on ec2 c4.4xlarge instance:
```bash
NestedLoopJoinExecutor/32(Inner)                                                                            
time:   [449.19 ms 449.29 ms 449.39 ms]
NestedLoopJoinExecutor/128(Inner)                                                                            
time:   [355.96 ms 355.98 ms 356.00 ms]
NestedLoopJoinExecutor/512(Inner)                                                                            
time:   [333.32 ms 333.33 ms 333.35 ms]
NestedLoopJoinExecutor/1024(Inner) …
```
=> test(batch): add micro benchmark for NestedLoopJoinExecutor

src/meta/src/hummock/hummock_manager.rs, src/meta/src/hummock/hummock_manager_tests.rs, src/meta/src/hummock/model/version.rs, src/meta/src/hummock/vacuum.rs
apply version delta from version checkpoint
this PR is successor of https://github.com/singularity-data/risingwave/pull/3503 and #3529
=> perf(hummock manager): apply version delta from version checkpoint

Cargo.lock, e2e_test/batch/basic/func.slt.part, proto/expr.proto, src/expr/Cargo.toml, src/expr/src/error.rs, src/expr/src/expr/expr_regexp.rs, src/expr/src/expr/mod.rs, src/frontend/src/binder/expr/function.rs, src/frontend/src/expr/function_call.rs
Add support for the regexp_match function.
Add the [regexp_match](https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP) function. Please note that the optional argument flag is not supported now.
#3605
=> feat(expr): support regexp_match

src/frontend/src/optimizer/plan_node/logical_agg.rs, src/frontend/src/utils/column_index_mapping.rs, src/frontend/test_runner/tests/testdata/agg.yaml
Removes unnecessary helpers (`inverse_with_required`, `i2o_col_mapping_with_required_out`) after the fix #3632
Also extracts the common part of `rewrite_with_input` and `prune_col` into `rewrite_with_input_agg`, which also fixes the following bug introduced by #3626:
```
dev=> create table t(v1 int, v2 int);
CREATE_TABLE
dev=> explain with sub(a, b) as (select min(v1), sum(v2) filter (where v2 < 5) from t) select b from sub;
QUERY PLAN                           
---------------------------------------------------------------
BatchSimpleAgg { aggs: [sum($0)] }
BatchExchange { order: [], dist: Single }
BatchSimpleAgg { aggs: …
```
=> refactor(optimizer): cleanup LogicalAgg::prune_col

src/frontend/test_runner/tests/testdata/nexmark.yaml
=> test(nexmark): explain q16 q17

proto/meta.proto, src/rpc_client/src/meta_client.rs
As title, the worker type field in `HeartbeatRequest` is not necessary and should not always be CN in `MetaClient` impl.
If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. …
=> fix: fix heartbeat req field and meta client impl

Cargo.lock, e2e_test/batch/types/interval.slt.part, e2e_test/batch/types/time.slt.part, src/expr/src/expr/template.rs, src/frontend/src/expr/type_inference/func.rs, src/frontend/src/handler/query.rs, src/frontend/src/scheduler/distributed/query.rs, src/frontend/src/scheduler/distributed/stage.rs, src/tests/sqlsmith/Cargo.toml, src/tests/sqlsmith/README.md, src/tests/sqlsmith/src/bin/main.rs, src/tests/sqlsmith/src/expr.rs, src/tests/sqlsmith/src/lib.rs
Now we can run sqlsmith e2e against RisingWave without failures. Sqlsmith still lacks many features and the testing is not always stable. So I will include it in our CI process when I think it's stable enough.
https://github.com/singularity-data/risingwave/issues/2571
Fixed https://github.com/singularity-data/risingwave/issues/3341
=> fix(sqlsmith): completely cover all exprs

Cargo.lock, Makefile.toml, src/test_runner/Cargo.toml, src/workspace-hack/Cargo.toml
We should not override RUSTFLAGS, so that cargo can pick up flags in `config.toml`.
Please …
=> fix(risedev): unexpected rebuilds on Linux

src/common/src/buffer/bitmap.rs
Add is_set to BitmapBuilder so that we can check if a specific bit is set when building the bitmap.
This is used to implement first-match optimization for NestedLoopJoinExecutor.
=> feat(common): add is_set to BitmapBuilder

src/batch/src/executor/join/nested_loop_join.rs
In https://github.com/singularity-data/risingwave/pull/3724, when doing left semi join, we iterate all left rows for each right chunk no matter if the left row has been matched in previous outer loops. This is a compromise due to the lack of interface to check if a specific bit is set when building a bitmap.
Now that `is_set` is added in https://github.com/singularity-data/risingwave/pull/3768, we can implement first-match optimization for left semi join, i.e., skipping the left rows matched in previous loops.
This change can greatly reduce the execution time for left semi join in some workloads. Take the randomly generated …
=> fix(batch): add first-match optimization for left semi join

e2e_test/streaming/struct_table.slt, src/batch/src/executor/order_by.rs
Fix panic on batch query when doing order_by with struct table
close #3780
=> fix(batch): fix order_by with struct table

src/expr/src/expr/agg.rs, src/frontend/src/expr/agg_call.rs, src/frontend/src/optimizer/plan_node/logical_agg.rs, src/stream/src/executor/aggregation/agg_call.rs, src/stream/src/executor/aggregation/mod.rs, src/stream/src/executor/global_simple_agg.rs, src/stream/src/executor/hash_agg.rs, src/stream/src/executor/integration_tests.rs, src/stream/src/executor/local_simple_agg.rs, src/stream/src/executor/managed_state/aggregation/mod.rs
`AggKind::RowCount` was used to present `count(*)` but later we converged to just use `AggKind::Count` with 0 arguments. The current rust frontend never generates a `AggKind` in the binder/planner, and the match arms in `stream` crate are dead and identical to `Count`.
=> refactor: remove stale AggKind::RowCount

Cargo.lock, src/connector/Cargo.toml, src/connector/src/base.rs, src/connector/src/datagen/mod.rs, src/connector/src/macros.rs, src/connector/src/nexmark/enumerator/mod.rs, src/connector/src/nexmark/mod.rs, src/connector/src/nexmark/source/generator.rs, src/connector/src/nexmark/source/reader.rs
1. ~I removed the special `Box` for `NexmarkProperty`, although it's large, it's really a non-critical path so I think we can just keep it simple.~
2. Introduced `serde_with` crate then parse the integer correctly.
Now we can create source with integer properties, e.g.:
```sql
create source auction (a_id INTEGER, item_name VARCHAR(24), description VARCHAR(104), initial_bid INTEGER, reserve INTEGER, a_date_time TIMESTAMP, expires TIMESTAMP, seller INTEGER, category INTEGER) with ( 'connector' = 'nexmark', 'nexmark.table.type' = 'Auction', 'nexmark.split.num' = '1' ) row format …
```
=> fix(connector): support parsing non-string nexmark properties

Cargo.lock, src/connector/Cargo.toml
Our PR has been merged, and the upstream repo is actively maintained now, just remove the fork.
https://github.com/streamnative/pulsar-rs/pull/196
=> build(deps): use official pulsar-rs instead of fork

Cargo.lock, proto/stream_plan.proto, src/common/src/error.rs, src/connector/Cargo.toml, src/connector/src/lib.rs, src/connector/src/sink/kafka.rs, src/connector/src/sink/mod.rs, src/connector/src/sink/mysql.rs, src/connector/src/sink/redis.rs, src/stream/src/executor/error.rs, src/stream/src/executor/mod.rs, src/stream/src/executor/sink.rs, src/stream/src/from_proto/mod.rs, src/stream/src/from_proto/sink.rs
working on kafka sink: parse stream chunk to json and sink to kafka
we can achieve exactly once  semantic by: 
* begin a kafka transaction when a barrier comes
* kafka sink records the last success epoch num and send record requests in any epoch that is smaller or equal to the saved one will be discarded
* abort the transaction whenever a request fails then roll the system back to prev epoch
* commit to kafka if there is no failure in this epoch (the …
=> feat: kafka json append only sink

e2e_test/streaming/basic.slt, src/common/src/types/decimal.rs
as title
- fix decimal from_str pattern match
- add e2e test for decimal
- https://github.com/singularity-data/risingwave/issues/3817
=> fix(type): fix decimal from_str and add e2e test

src/batch/src/executor/hash_agg.rs, src/batch/src/executor/sort_agg.rs, src/common/src/array/iterator.rs, src/expr/src/vector_op/agg/aggregator.rs, src/expr/src/vector_op/agg/approx_count_distinct.rs, src/expr/src/vector_op/agg/count_star.rs, src/expr/src/vector_op/agg/general_agg.rs, src/expr/src/vector_op/agg/general_distinct_agg.rs, src/expr/src/vector_op/agg/general_sorted_grouper.rs
Before this PR,
- `HashAggExecutor` used `Aggregator::update_with_row` to feed the aggregator one row at a time and used `Aggregator::output` to generate the aggregation result
- `SortAggExecutor` used `Aggregator::update_and_output_with_sorted_groups` to feed the aggregator with multiple rows together with `EqGroups`, and used `Aggregator::output` to generate the aggregation result
Several problems existed:
- `Aggregator::update(input: &DataChunk)` was not used
- `Aggregator::update_and_output_with_sorted_groups` impls needed to know about `EqGroups`, and control the timing of output and reset of internal state, making the …
=> refactor(batch,agg): merge `Aggregator::update*` and refactor `SortAggExecutor`

src/common/src/types/mod.rs, src/common/src/util/ordered/serde.rs, src/utils/memcomparable/src/de.rs
as title
- support get encoding_data_size by DataType without mem copy
- deserialize_prefix_len_with_column_indices for prefix_bloom_filter
- some unit-test
=> feat(storage): support deserialize_prefix_len for prefix_bloom_filter

src/tests/regress/README.md, src/tests/regress/src/opts.rs, src/tests/regress/src/schedule.rs
Pass user name for regress tests.
Mute the output of failed tests via stdin.
Will do in future PRs:
1. We only want to show the test cases that have different outputs as expected instead of the entire tests, similar to `sqllogictest`.
2. We will need to deal with the error message in special ways, check out #3853.
#3853
=> fix(test): pass user name for regress tests

src/tests/sqlsmith/src/lib.rs
This temporarily PR refer to https://github.com/singularity-data/risingwave/issues/3367.
Implement Having but not yet complete because agg haven,t implement finish. (After finish agg will close this issue)
Some change is the order of Group by, this suggest that it should be after where because the restricted bounded column affects Having and Select only.
- Describe clearly one logical change and avoid lazy messages …
=> feat(sqlsmith): Implement Having without agg

src/stream/src/executor/dispatch.rs
As title, as we're not sure whether this would cause problems... …
=> fix(streaming): forbid update being shuffled

proto/meta.proto, proto/stream_plan.proto, src/meta/src/barrier/command.rs, src/meta/src/rpc/server.rs, src/meta/src/rpc/service/ddl_service.rs, src/meta/src/rpc/service/mod.rs, src/meta/src/rpc/service/scale_service.rs, src/stream/src/executor/mod.rs, src/stream/src/executor/source/source_executor.rs
Add pause barrier and resume barrier.
Once received pause barrier, the source executor will stop to read from source and only receive new barriers.
Scale service in Meta and two interfaces are added to do testing and controling.
https://github.com/singularity-data/risingwave/issues/3292
=> feat: add pause barrier and resume barrier

src/batch/benches/nested_loop_join.rs, src/batch/src/executor/join/nested_loop_join.rs
Implement full outer join (by copy & paste from left/right outer join).
The code logic of left/right/full outer join may be further simplified in later PRs.
https://github.com/singularity-data/risingwave/issues/3767
=> feat(batch): Implement full outer join for nested loop join

src/common/src/cache.rs, src/object_store/src/object/disk.rs, src/storage/hummock_test/src/state_store_tests.rs, src/storage/src/hummock/block_cache.rs, src/storage/src/hummock/iterator/forward_merge.rs, src/storage/src/hummock/iterator/test_utils.rs, src/storage/src/hummock/sstable/forward_sstable_iterator.rs, src/storage/src/hummock/sstable_store.rs, src/storage/src/storage_failpoints/test_iterator.rs, src/storage/src/storage_failpoints/test_sstable.rs
As title. `lookup_dedup` will now spawn a task in the background, so that it won't deadlock.
Example: We have two futures running.
```
let future_1 = async move {
lru.lookup("a", fetch_from_storage).await
}
let future_2 = async move {
lru.lookup("a", fetch_from_storage).await
}
```
If we run them in the following way:
```
future_1.poll_next(); // so that we will cache miss, and LRU will call `fetch_from_storage` to get data.
future_2.poll_next(); // as request to "a" is in-flight, LRU will wait until future_1 completes the request.
drop(future_1);
loop { …
```
=> fix(lru): correctly handle future cancellation

src/ctl/src/cmd_impl/hummock/sst_dump.rs
Extended the functionality of sst-dump to iterate over and print stored KV-pairs. The data of pairs is printed as well as interpretation of the data.
```sql
Create Table t1 (k int, v1 int, v2 int);
Insert Into t1 Values (1, null, 2);
```
Results in the following:
```
Block 0
-----------
Offset: 0, Size: 126, Checksum: 13688900580554635392, Compression Algorithm: None
KV-Pairs:
full key: [74, 00, 00, 03, ea, 1a, 01, 82, 5d, 71, 94, 24, 80, 10, 00, 7f, ff, ff, ff, ff, f6, 8a, 39, af, 86, ff, ff]
full value: [00]
user key: [74, 00, 00, 03, ea, 1a, 01, 82, 5d, 71, 94, 24, 80, 10, 00, 7f, ff, ff, ff]
user value: []
epoch: …
```
=> feat(ctl): For sst-dump, iterate over KV-pairs, print pairs in human readble format, and interprete them based on table schema

src/frontend/src/scheduler/distributed/query_manager.rs, src/frontend/src/scheduler/distributed/stage.rs, src/rpc_client/src/compute_client.rs
=> refactor(batch-task-service): only one `create_task` API is needed

e2e_test/ddl/schema.slt, e2e_test/ddl/table.slt, src/frontend/src/binder/bind_context.rs, src/frontend/src/binder/expr/column.rs, src/frontend/src/binder/expr/mod.rs, src/frontend/src/binder/query.rs, src/frontend/src/binder/relation/mod.rs, src/frontend/src/binder/select.rs, src/frontend/src/binder/struct_field.rs, src/frontend/src/handler/create_table.rs, src/frontend/src/handler/handle_privilege.rs, src/frontend/src/handler/show.rs, src/frontend/src/handler/variable.rs, src/frontend/test_runner/tests/testdata/nexmark.yaml, src/sqlparser/src/ast/mod.rs
Fix #3888, this PR makes the decision of case sensitivity during parsing.
There are three cases:
1. always case-insensitive even with double quotes, such as session variables
2. case-sensitive by double quotes
3. case-insensitive with no quotes
Names are case-insensitive by default, e.g. column name, table name, etc, unless the name is double-quoted. In this case, they are case-sensitive.
Please keep the types that apply to your changes, and remove those …
=> fix(parser): case insensitive except double quotes

src/config/risingwave.toml
As title. 
I tried to fix it along with #3910 but CI timed out... Let's try it separately.
Please create a release note for your changes. In the release note, focus on the impact …
=> fix: remove `unsafe_worker_node_parallel_degree` in risingwave.toml

src/config/risingwave.toml, src/frontend/src/scheduler/distributed/query.rs, src/frontend/src/scheduler/plan_fragmenter.rs, src/meta/src/cluster/mod.rs, src/meta/src/manager/env.rs, src/meta/src/stream/scheduler.rs
As title.
For example, given `unsafe_worker_node_parallel_degree = 4`, there will be 4 hash parallel units and 1 single parallel units. …
=> fix: parallelism should not be subtracted 1

Cargo.lock, src/tests/sqlsmith/Cargo.toml, src/tests/sqlsmith/src/bin/main.rs
Permit overflow errors. Workaround by just checking error code and expected error message.
- This is a workaround, not a permanent solution.
- Currently for overflows RisingWave just return an internal error code, and NumericOutOfRangeError as part of the error message. Need to design a better way to handle it.
- We can also remove operators which potentially overflow from SqlSmith, but I think this would significantly reduce our coverage (most of arithmetic operators won't be included in SqlSmith tests).
If your pull request …
=> fix(sqlsmith): Ignore NumericOutOfRangeError

src/connector/src/sink/kafka.rs, src/stream/src/executor/sink.rs
as title, the pr include sink executor internals, without failover part
you can now run 
```sql
create materialized source s (v1 int ) with ('connector' = 'datagen') row format json ;
create materialized view v as select * from s where v1 > 0;
create sink si from v with ('kafka.brokers' = '127.0.0.1:29092', 'kafka.topic' = 'test_topic', 'sink.type' = 'append_only', 'sink_type' = 'kafka');
```
to try a kafka sink! 
- How does this PR work? Need a brief …
=> feat: make sink e2e work

src/frontend/src/binder/select.rs, src/frontend/test_runner/tests/testdata/nexmark.yaml, src/tests/regress/data/expected/boolean.out, src/tests/regress/data/sql/boolean.sql, src/tests/regress/src/file.rs, src/tests/regress/src/schedule.rs
This PR tries to reboot our regress test, only boolean.sql included for now.
Was blocked by:
1. error message incompatible with PG (commented out)
2. `text` type unsupported (commented out)
3. previously, some output is changed for RisingWave passing the tests, so correct them to be the same as PG.
This PR:
1. makes the regress test ignore all the comments. Previously comments are still compared and thus lead to unnecessary regress test errors.
2. output the diff to another separate file instead of stdout.
3. comment out error cases and …
=> fix(regress test): ignore comment diff and support boolean test

src/storage/src/encoding/cell_based_row_deserializer.rs, src/storage/src/encoding/cell_based_row_serializer.rs, src/storage/src/encoding/dedup_pk_cell_based_row_serializer.rs, src/storage/src/encoding/mod.rs, src/storage/src/table/mod.rs, src/storage/src/table/state_table.rs, src/storage/src/table/storage_table.rs, src/storage/src/table/storage_table/iter_utils.rs
We have triat `Encoding` to serialize row into KV entry, and `Decoding` to deserialize KV entries into row, however, current implementation is a little confusing because `StateTableBase` bound to `Encoding` and `StorageTableIter` bound to `Decoding`. 
This PR merges `Encoding` and `Decoding` into one new trait `RowSerde` (maybe we can call it something else like `RowExchanger`...), which is responsible for the conversion between row and KV. Thus, all struct in relational table layer only need to bound with this trait. This further decouples the Encoding and Relational layers, and remove the cell-based attributes of the …
=> feat(encoding): merge encoding and decoding into one trait RowSerde

Cargo.lock, src/tests/regress/Cargo.toml, src/tests/regress/README.md, src/tests/regress/data/expected/boolean.out, src/tests/regress/data/sql/boolean.sql, src/tests/regress/src/opts.rs, src/tests/regress/src/schedule.rs
RW requires session variable assignment `SET RW_IMPLICIT_FLUSH TO true;` while PG cannot recognize it.
So we require users to input the database they are testing against,
and add this session variable assignment for each test case when running against RW only.
Will enable regress tests in CI for both RW and PG in future pr.
~- [] I have added necessary unit tests and integration tests~
=> fix(regress test): enable regress tests for both RW and PG

src/connector/src/source/pulsar/admin/client.rs, src/connector/src/source/pulsar/enumerator/client.rs, src/connector/src/source/pulsar/mod.rs
This PR fixes an issue with Pulsar split enumerator regarding non-partitioned-topic
The previous method to determine if a topic is partitioned was based on the `-partition-` suffix, which was wrong, now the `partitions` field in the metadata is used to determine.
* SQL …
=> chore: refine split enumerator for pulsar connector

Cargo.lock, src/common/src/util/ordered/serde.rs, src/storage/hummock_sdk/Cargo.toml, src/storage/hummock_sdk/src/key.rs, src/storage/hummock_sdk/src/lib.rs, src/storage/hummock_sdk/src/slice_transform.rs, src/storage/src/keyspace.rs
support slice transform
- add SchemaSliceTransform
- some unit-test
- https://github.com/singularity-data/risingwave/issues/3927
=> feat(storage): SliceTransform for prefix bloom filter

src/tests/sqlsmith/src/lib.rs, src/tests/sqlsmith/src/relation.rs, src/tests/sqlsmith/src/time_window.rs, src/tests/sqlsmith/src/utils.rs
Ran sqlsmith e2e locally.
Implement `gen_with`.
- Control complexity of `gen_query` by providing terminating branch. This is required because it is mutually recursive with `gen_with`.
- Provide local context for selected query in generated with clause.
- Pass `with_tables` to `gen_from`. Once we generate `with` clauses, we expect they are used in the `FROM` clause.
- Only generate simple with query, we only generate a single `CTE`. In the future …
=> feat(sqlsmith): generate `with`

e2e_test/nexmark/create_tables.slt.part, e2e_test/nexmark/insert_auction.slt.part, e2e_test/nexmark/insert_bid.slt.part, e2e_test/nexmark/insert_person.slt.part, e2e_test/streaming/nexmark/views/q0.slt.part, e2e_test/streaming/nexmark/views/q1.slt.part, e2e_test/streaming/nexmark/views/q10.slt.part, e2e_test/streaming/nexmark/views/q14.slt.part, e2e_test/streaming/nexmark/views/q4.slt.part, e2e_test/streaming/nexmark/views/q5.slt.part, e2e_test/streaming/nexmark/views/q7.slt.part, e2e_test/streaming/nexmark/views/q8.slt.part, risedev.yml, src/connector/src/source/nexmark/source/event.rs, src/frontend/test_runner/tests/testdata/nexmark.yaml, src/tests/sqlsmith/tests/testdata/nexmark.sql
It looks a little weired because I just renamed them to camelStyle in a near PR #3917 , but there are several reasons to do this revert:
1. Previously I followed the [nexmark-flink](https://github.com/nexmark/nexmark/tree/master/nexmark-flink/src/main/resources/queries) style, but I found that in the original paper, the style is strange (e.g. `emailaddress` and `credit_card` in the same table) and no one followed it. FlinkSQL just use their own style and we can also have our one.
2. Lowercase is more welcome in pg SQL. We have to use double-quoted field if we really want to use …
=> fix(nexmark): rename the field names to lower style

.gitignore, ci/plugins/upload-failure-logs/hooks/post-command, ci/scripts/regress-test.sh, ci/workflows/main.yml, ci/workflows/pull-request.yml, src/tests/regress/src/file.rs, src/tests/regress/src/schedule.rs
Enable regress test for RisingWave in CI.
Add `regress-test.sh` script and invoke it in both main.yml and pull-request.yml
Use `Stdio::piped()` instead of an input file for the command `psql`.
In the future, we want to let PostgreSQL also run the regress test to validate our test cases are correct.
Also, we want to collect the failure logs into a `.zip`.
=> ci(regress test): enable regress test for RisingWave

src/frontend/src/optimizer/plan_node/logical_join.rs, src/frontend/src/optimizer/plan_node/logical_topn.rs, src/frontend/test_runner/tests/testdata/column_pruning.yaml
`required_cols` refers to indices in the original TopN, while `output_required_cols` refers to indices in the new TopN.
This fix is actually borrowed from LogicalFilter, another node that always has same output schema as its input:
https://github.com/singularity-data/risingwave/blob/661dead78c42f04fba0521a719b87e9c3cd69d23/src/frontend/src/optimizer/plan_node/logical_filter.rs#L145-L161
Seems we need to refactor `prune_col` of each node to reduce the chance of making such errors. But fixing this one first.
Fixes #4025
=> fix(optimizer): index out of bounds in `LogicalTopN::prune_col`

src/storage/src/hummock/shared_buffer/shared_buffer_uploader.rs
Currently we re-initialize a compact context for every local compaction task. However, most of field in the context is the same in different compact task. Therefore, we can only initialize the compactor context during initialization.
=> refactor(storage): avoid initialize compactor context in every local compact

src/tests/sqlsmith/src/lib.rs, src/tests/sqlsmith/src/relation.rs, src/tests/sqlsmith/src/time_window.rs, src/tests/sqlsmith/src/utils.rs
Waiting for sqlsmith e2e to pass locally.
- Use `relation_id` to generate table ids instead. Current implementation uses `self.bound_relations.len()`. This can result in duplicate table ids generated.
Queries with same number of bound_relations in local context will generate duplicate table ids.
- Use local context when generating left and right factor of eqjoin.
If your …
=> feat(sqlsmith): enable eqjoin

src/tests/sqlsmith/src/lib.rs
Enable generation of `CTE`s from `WITH` clause in implicit `CROSS JOIN`:
```sql
FROM with_table, t0, t1, ...
```
Able to remove this workaround as #4025 has been resolved.
Please …
=> feat(sqlsmith): Remove `CROSS JOIN` workaround for `with_tables`

ci/workflows/main.yml
Only made changes to pull-request.yml in #4064, which leads to CI failure on main branch.
This pr enables regress test env on branch main.
closes #3853
=> fix(ci): enable regress test env on branch main also

src/ctl/src/cmd_impl/hummock/sst_dump.rs
`./risedev ctl hummock sst-dump` allows to display the content of SSTs and show the stored KV-pairs including interpretation of them. The previous implementation (see PR #3916) assumes that each stored table-ID is known. However, that is not always the case and can cause the code to panic (see Issue #4043).
The current PR fixes that problem. In short, each `Option<T>::unwrap()` added in PR #3916 is replaced with an according logic to handle the case that a table- or column-ID is not know. Errors are still propagated.
Issue #4043 (risectl: support key doesn't belong to any table)
PR #3916
=> fix(risectl): support key doesn't belong to any table

src/batch/src/executor/hop_window.rs, src/common/src/array/data_chunk_iter.rs, src/common/src/hash/key.rs, src/stream/src/executor/aggregation/foldable.rs, src/stream/src/executor/dynamic_filter.rs, src/stream/src/executor/error.rs, src/stream/src/executor/hash_agg.rs, src/stream/src/executor/hop_window.rs, src/stream/src/executor/local_simple_agg.rs, src/stream/src/executor/lookup/impl_.rs, src/stream/src/executor/managed_state/join/mod.rs, src/stream/src/executor/mod.rs, src/stream/src/executor/sink.rs, src/stream/src/executor/source/source_executor.rs, src/stream/src/executor/source/state.rs
As title. After connector introduces its per-crate error, we're able to remove the `SourceError` and `SinkError`.
- #3116
=> refactor(streaming): cleanup more stream executor error

proto/meta.proto, src/meta/src/rpc/server.rs, src/meta/src/rpc/service/scale_service.rs
Add an interface to get cluster info.
Although we already have a similar function for Dashboard, we tend to add a new independent interface for orchestrator. We may require more info through this interface. A new independent interface is more flexible.
Add an interface for the orchestrator to get cluster info.
=> feat(meta): add get_cluster_info interfaces

src/stream/src/executor/monitor/streaming_stats.rs
1. It's inconsistent.
2. It's correct in grafana so the graph can't display it.
=> fix(stream): stream_join_total_lookup_count -> stream_join_lookup_total_count

src/utils/pgwire/src/pg_protocol.rs, src/utils/pgwire/src/pg_server.rs
Inside the `PgProtocol` struct, we move `stream` and `buf_out` to a new `PgStream` struct.
So that states such as `unnamed_statement` can be moved from argument into struct, without causing errors in borrow checker.
=> refactor(pgwire): move argument states into the struct

src/storage/src/hummock/compactor.rs, src/storage/src/hummock/iterator/backward_concat.rs, src/storage/src/hummock/iterator/concat_inner.rs, src/storage/src/hummock/iterator/forward_concat.rs, src/storage/src/hummock/iterator/forward_merge.rs, src/storage/src/hummock/iterator/forward_user.rs, src/storage/src/hummock/iterator/mod.rs, src/storage/src/hummock/iterator/test_utils.rs, src/storage/src/hummock/mod.rs, src/storage/src/hummock/shared_buffer/mod.rs, src/storage/src/hummock/sstable/backward_sstable_iterator.rs, src/storage/src/hummock/sstable/forward_sstable_iterator.rs, src/storage/src/hummock/sstable/mod.rs, src/storage/src/hummock/sstable_store.rs, src/storage/src/hummock/state_store.rs, src/storage/src/storage_failpoints/test_iterator.rs, src/storage/src/storage_failpoints/test_sstable.rs
- fix get_from_table to use store_read_options instead of sstable_read_options (the reason is that currently we do not use sstable_read_options for point_get via sstable_iterator, but we need to use store_read_options to judge whether we need to check bloom_filter)
- distinguish ReadOptions between store and sstable_iter for making the code more readable and reduce errors using read_options
- thanks for @hzxa21 suggesstion
=> chore(storage):  distinguish ReadOptions between store and sstable_iter for readable

src/compute/src/compute_observer/observer_manager.rs, src/meta/src/manager/catalog.rs, src/storage/compactor/src/compactor_observer/observer_manager.rs
as title
- broadcast source to cn and compactor
- fix observer handle logic for source
- use FullKeySliceTransform as default
- https://github.com/singularity-data/risingwave/issues/4027
=> fix(meta): fix broadcast source for observer

src/storage/benches/bench_merge_iter.rs, src/storage/hummock_sdk/src/key.rs, src/storage/hummock_test/src/local_version_manager_tests.rs, src/storage/src/hummock/compactor.rs, src/storage/src/hummock/local_version_manager.rs, src/storage/src/hummock/shared_buffer/mod.rs, src/storage/src/hummock/shared_buffer/shared_buffer_batch.rs, src/storage/src/hummock/state_store.rs, src/storage/src/keyspace.rs
shared_buffer writebatch add table_id to support schema-ful
- SharedBufferBatch add table_id 
- compactor filter uncommitted data and build the exisiting_table_ids
- https://github.com/singularity-data/risingwave/issues/3871
=> feat(storage):  add table_id for shared_buffer writebatch

src/frontend/src/optimizer/heuristic.rs, src/frontend/src/optimizer/mod.rs, src/frontend/test_runner/tests/testdata/subquery_expr_correlated.yaml
This PR is separated from #4085 for better code review.
Support push down apply until reaching a fix-point.
For some plans contain multi `Apply`, one round of heuristic optimizer is not enough. We need to reach a fix-point which means all apply need to be pushed down and eliminated.
Here is the example needed multiple round of applying transformation rules:
```sql
explain verbose trace select * from t1 where exists(select x from t2 where t1.x = t2.x and t2.y in (select t3.y + t2.y from t3 where t1.x = t3.x));
General Unnesting(Translate Apply):
apply TranslateApplyRule 2 time(s)
LogicalProject { exprs: [t1.x, t1.y] } …
```
=> feat(optimizer): support push down apply until reaching a fix-point

src/storage/hummock_test/src/compactor_tests.rs, src/storage/src/keyspace.rs, src/storage/src/table/storage_table.rs, src/stream/src/executor/source/source_executor.rs, src/stream/src/executor/source/state.rs
as tilte
- keyspace read_path use `ReadOptions`
- keyspace remove dependence of table_id
- https://github.com/singularity-data/risingwave/issues/3871
=> refactor(storage): refact keyspace read path with read_options

proto/hummock.proto, src/meta/src/hummock/hummock_manager.rs
Fix the bug introduced by https://github.com/singularity-data/risingwave/pull/4081, which deletes SSTs generated by trivial move incorrectly.
extend_ssts_to_delete_from_deltas should ignore delta from trivial move.
* Other …
=> fix(storage): handle trivial move correctly when deleting SST

ci/workflows/main.yml
Should use same unit test script as PR. `main` workflow should not run sqlsmith tests too, see https://github.com/singularity-data/risingwave/issues/4139, https://github.com/singularity-data/risingwave/pull/4134.
* RisingWave …
=> fix(ci): main workflow use latest unit test script

ci/scripts/pr.env.sh, ci/scripts/run-unit-test.sh
- Exclude sqlsmith tests from coverage by:
- Running usual test workflow with coverage (no sqlsmith included)
- Running sqlsmith tests without coverage
Currently for code coverage check:
- PRs which do not modify sqlsmith src files will decrease coverage, since sqlsmith tests do not run.
- See https://github.com/singularity-data/risingwave/pull/4236#issuecomment-1196649361, as well as [88351f0](https://github.com/singularity-data/risingwave/pull/4231/commits/88351f05bdafb53535f1eb2e32bfc2f670d25362) from this PR.
- PRs which modify sqlsmith src files may continue increasing coverage.
- Better to just remove sqlsmith tests …
=> fix(ci): exclude sqlsmith tests from coverage

src/bench/Cargo.toml
=> chore: disable compile ss_bench by default

e2e_test/batch/issue_4213.slt, src/frontend/src/scheduler/distributed/query.rs, src/frontend/src/scheduler/plan_fragmenter.rs
close https://github.com/singularity-data/risingwave/issues/4213
This happends because:
1. When building the stage containing the HashJoin, the parallism is initially 1.
2. When visiting the Exchange node connecting the stage of Scan(t1), we have 
```rust 
let child_exchange_info = node.distribution().to_prost(builder.parallelism);
```
So the tasks will have 1 outputs.
3. When visiting the other side containing the other scan node, we updated `builder.table_scan_info`
4. When finish building, **we modified the parallelism of the stage**
```rust
parallelism: match &self.table_scan_info {
None => self.parallelism,
Some(info) …
```
=> fix(batch fragmenter): fix wrong exchange output cnt

e2e_test/streaming/string_agg.slt, src/stream/src/executor/managed_state/aggregation/string_agg.rs, src/stream/src/from_proto/agg_call.rs
Support delimiter argument in streaming `string_agg` function.
* Support `delimiter` argument in streaming `string_agg` 
#2868
=> feat(stream): support `delim` argument in streaming `string_agg`

e2e_test/batch/functions/internal.slt.part, src/frontend/src/binder/expr/function.rs
Expose `Vnode` function as `__rw_vnode` for debug purpose.
https://github.com/singularity-data/risingwave/pull/4262#pullrequestreview-1053889717
=> feat(frontend): expose `Vnode` function as `__rw_vnode` for easy debugging

src/frontend/src/binder/insert.rs, src/frontend/src/binder/update.rs, src/frontend/src/handler/dml.rs, src/frontend/src/scheduler/distributed/query_manager.rs, src/frontend/src/scheduler/worker_node_manager.rs
As title, we should only schedule dml to CNs which contains table source writer. When new CN joined, schedule dml to new node will failed due to no writer and downstream mview exist.
Note that, I will move `vnode_mapping` out of `TableCatalog` described in #3449 in next PR and modify schedule single/multi policy together.
* Connector …
=> fix(frontend): only schedule dml to cn which contain table source writer

Cargo.lock, risedev.yml, src/cmd_all/src/bin/risingwave.rs, src/object_store/Cargo.toml, src/object_store/src/object/mem.rs, src/object_store/src/object/mod.rs, src/risedevtool/src/risectl_env.rs, src/risedevtool/src/task/compactor_service.rs, src/risedevtool/src/task/compute_node_service.rs, src/risedevtool/src/task/utils.rs
As title. Used `lazy_static` for shared in-memory object store.
To start this:
```
PLAYGROUND_PROFILE=playground-3cn ./risedev p
```
Close #4195.
=> feat(risedev): support 3 compute nodes in playground

src/cmd_all/src/playground.rs, src/compute/src/server.rs, src/risedevtool/src/compose.rs, src/risedevtool/src/task/compute_node_service.rs
As title.
- Close #4351 
- Resolve the comments about compactor in #4332
=> fix(risedev): cannot `d` after adding shared in-memory hummock support 

proto/batch_plan.proto, proto/stream_plan.proto, src/batch/src/executor/join/lookup_join.rs, src/frontend/src/optimizer/plan_node/batch_lookup_join.rs, src/frontend/src/optimizer/plan_node/logical_join.rs, src/frontend/src/optimizer/plan_node/logical_scan.rs, src/frontend/src/optimizer/plan_node/stream_index_scan.rs, src/frontend/src/optimizer/plan_node/stream_materialize.rs, src/frontend/src/optimizer/plan_node/stream_table_scan.rs, src/frontend/test_runner/tests/testdata/stream_proto.yaml, src/stream/src/from_proto/chain.rs
- Previously we used column ids as indices in the chain executor to remap the columns from the upstream with the Java frontend. This PR fixes this with upstream column indices.
- Batch lookup join directly casts column id to index, which should be avoided.
- This PR makes it allocate column id from `1000`, which helps us to debug these misusing.
=> fix: use correct column indices for chain & batch lookup join

src/tests/sqlsmith/src/bin/main.rs, src/tests/sqlsmith/tests/frontend/mod.rs
Add stream queries to workflow.
- Previously #4228 disabled stream generators for frontend.
- e2e tests did not have stream queries tested.
This PR enables both.
Please create a …
=> feat(sqlsmith): test stream queries

src/frontend/test_runner/src/lib.rs, src/frontend/test_runner/tests/testdata/agg.yaml, src/frontend/test_runner/tests/testdata/append_only.yaml, src/frontend/test_runner/tests/testdata/array.yaml, src/frontend/test_runner/tests/testdata/basic_query.yaml, src/frontend/test_runner/tests/testdata/column_pruning.yaml, src/frontend/test_runner/tests/testdata/common_table_expressions.yaml, src/frontend/test_runner/tests/testdata/distribution_derive.yaml, src/frontend/test_runner/tests/testdata/expr.yaml, src/frontend/test_runner/tests/testdata/index.yaml, src/frontend/test_runner/tests/testdata/insert.yaml, src/frontend/test_runner/tests/testdata/join.yaml, src/frontend/test_runner/tests/testdata/limit.yaml, src/frontend/test_runner/tests/testdata/mv_on_mv.yaml, src/frontend/test_runner/tests/testdata/nexmark.yaml, src/frontend/test_runner/tests/testdata/order_by.yaml, src/frontend/test_runner/tests/testdata/pg_catalog.yaml, src/frontend/test_runner/tests/testdata/pk_derive.yaml, src/frontend/test_runner/tests/testdata/predicate_pushdown.yaml, src/frontend/test_runner/tests/testdata/project_set.yaml, src/frontend/test_runner/tests/testdata/range_scan.yaml, src/frontend/test_runner/tests/testdata/struct_query.yaml, src/frontend/test_runner/tests/testdata/subquery.yaml, src/frontend/test_runner/tests/testdata/subquery_expr.yaml, src/frontend/test_runner/tests/testdata/subquery_expr_correlated.yaml, src/frontend/test_runner/tests/testdata/time_window.yaml, src/frontend/test_runner/tests/testdata/tpch.yaml, src/frontend/test_runner/tests/testdata/update.yaml
The current behaviour is not to explain verbose in planner tests, we thereby do not capture: node distributions, fully qualified column names, and output indices in joins.
This PR will use explain verbose in all planner tests.
=> feat(planner): Use explain verbose for all planner tests

src/batch/src/task/broadcast_channel.rs, src/batch/src/task/channel.rs, src/batch/src/task/fifo_channel.rs, src/batch/src/task/hash_shuffle_channel.rs, src/batch/src/task/task_execution.rs
Task execution should stop polling data stream after returning `None`.
Closes #4132
=> fix(batch): Stop polling after data stream returns `None`

src/batch/src/executor/row_seq_scan.rs, src/compute/tests/integration_tests.rs
As there is no difference in TableScan and RangeScan, it's no need to differentiate them.
Please create a release note for your changes. In the release note, focus on the impact …
=> refactor(batch): unify scan type in batch scan

src/common/src/field_generator/numeric.rs, src/common/src/types/ordered_float.rs
Now the default range of all field generators is set to [0, i16::MAX] to avoid range overflow.
When creating a field generator without specific lowerbound and upperbound, the generator will generate data in range [0, i16::MAX] by default, rather than [0, T::MAX].
close #4363
=> fix(common): use smaller upperbound for generators to avoid range overflow

proto/hummock.proto, src/meta/src/hummock/compaction/manual_compaction_picker.rs, src/meta/src/hummock/compaction/mod.rs, src/meta/src/rpc/service/hummock_service.rs
support manual compaction for specific sst ids from CN, so as that CNs can trigger L0 intra compaction which exactly contains SSTs that generated by itself. see also #4072  …
=> feat(meta): support manual compaction for specific sst ids from CN

src/frontend/src/expr/mod.rs, src/frontend/src/utils/condition.rs
using [`Itertools::format_with`](https://docs.rs/itertools/0.8.0/itertools/trait.Itertools.html#method.format_with), which allows specifying a separator
=> refactor(frontend): simplify ConditionDisplay

src/batch/src/executor/join/hash_join.rs, src/batch/src/executor/join/nested_loop_join.rs
I defined `append_chunk` in nested loop join and hash join to append data chunks to the data chunk builder. However, in `DataChunkBuilder` there is an equivalent method `trunc_data_chunk`. To reduce code redundancy, all `append_chunk` should be replaced by `trunc_data_chunk`.
=> refactor(batch): remove `append_chunk` in nested loop join and hash join

src/frontend/src/expr/mod.rs, src/frontend/src/expr/type_inference/cast.rs, src/frontend/src/expr/type_inference/mod.rs, src/tests/sqlsmith/README.md, src/tests/sqlsmith/src/expr.rs, src/tests/sqlsmith/src/utils.rs
- Gen casts.
- See [cast signatures](https://gist.github.com/kwannoel/5967f133ca79b37a17159497d84befd5)
- Provide cast sig map.
- Filter out casts that often fail / can't easily generate cast expressions for.
- Avoids testing varchar casting, arbitrary string of characters may not be able to cast to datatypes.
- To test implicit cast most straightforward way is probably INSERTs?
- For assign cast it can be done under CONCAT perhaps.
- TODO: …
=> feat(sqlsmith): generate explicit type castings

src/tests/sqlsmith/src/expr.rs
Enable gen_agg however disallow distinct agg first until the issue  https://github.com/singularity-data/risingwave/issues/4220 is resolved.
=> feat(sqlsmith): Enable gen_agg but workaround distinct agg

src/frontend/src/expr/subquery.rs, src/frontend/test_runner/tests/testdata/common_table_expressions.yaml
`Clone` of `expr::Subquery` was purposed banned as `BoundQuery` was not `Clone` at that time and `ExprImpl`s are only cloned after decorrelation. However, since support of CTE in #2741, we do need to clone `BoundQuery` (including `expr::Subquery`) before decorrelation.
Fixes #4404
=> fix(binder): allow `Clone` for `expr::Subquery` as part of CTE

src/sqlparser/src/ast/statement.rs
As title. Pointed out by @CharlieSYH , we should keep compatibility with PostgreSQL.
> 
> I tested this statement and it retuned an error "ERROR:  sql parser error: Expected end of statement, found: PASSWORD":
> `CREATE USER u1 PASSWORD 's1234';`
> But this works: `CREATE USER u1 WITH PASSWORD 's1234';`
>
> Seems that 'with' is not optional. Can you confirm on that?
>
> _Originally posted by @CharlieSYH in https://github.com/singularity-data/risingwave/issues/3074#issuecomment-1203882709_
Please …
=> fix(frontend): make WITH optional for user create and alter

e2e_test/batch/basic/join.slt.part, src/frontend/src/optimizer/plan_node/batch_hash_join.rs, src/frontend/src/optimizer/plan_node/batch_seq_scan.rs, src/frontend/src/optimizer/plan_node/logical_scan.rs, src/frontend/test_runner/tests/testdata/basic_query.yaml, src/frontend/test_runner/tests/testdata/join.yaml, src/frontend/test_runner/tests/testdata/mv_on_mv.yaml, src/frontend/test_runner/tests/testdata/project_set.yaml, src/frontend/test_runner/tests/testdata/range_scan.yaml, src/frontend/test_runner/tests/testdata/update.yaml
For other batch operators, `HashShard` is a simple hashing, i.e.,
`target_shard = hash(dist_key) % shard_num`
But MV is actually sharded by consistent hashing, i.e.,
`target_shard = vnode_mapping.map(hash(dist_key) % vnode_num)`
They are incompatible, so we just specify its distribution as `SomeShard` to force an exchange is inserted.
To reproduce the current wrong behavior:
```sql
create table t(x int);
create index i on t(x);
insert into t values (1),(2),(3),(4),(5);
explain select * from t join i using(x);
QUERY PLAN
-------------------------------------------------------
BatchExchange { order: [], dist: Single } …
```
=> fix: use SomeShard as the distribution of batch scan

e2e_test/batch/explain.slt, e2e_test/ddl/table.slt, src/frontend/src/handler/create_sink.rs, src/frontend/src/handler/explain.rs
as title, support stream sink in explain
None
=> feat: support explain sink

Makefile.toml, src/tests/sqlsmith/tests/frontend/mod.rs
as title, Occasionally, we use `risedev c` locally to check before we push new code to pull request , but it fail in CI through `pre-unit-test.sh`. if we unify them , we can figure out some problem locally ASAP, avoid to waste the cost of CI
- Makefile.toml for risedev c
- sqlsmith clippy
=> chore(risedev): unify clippy between risedev c and pre-unit-test.sh

e2e_test/batch/basic/local/lookup_join.slt.part, src/frontend/src/optimizer/plan_node/eq_join_predicate.rs, src/frontend/src/optimizer/plan_node/logical_join.rs, src/frontend/src/optimizer/plan_node/logical_scan.rs, src/frontend/test_runner/tests/testdata/join.yaml
Pullup predicates in `LogicalScan` into `BatchLookupJoin` 
Fixes: https://github.com/singularity-data/risingwave/issues/4042
=> fix(planner): Pullup predicates in `LogicalScan` into `BatchLookupJoin` 

src/frontend/src/optimizer/plan_node/logical_join.rs, src/frontend/test_runner/tests/testdata/tpch.yaml
DynamicFilter's LHS should follow upstream distribution
Fixes: https://github.com/singularity-data/risingwave/issues/4125
=> fix(planner): DynamicFilter's LHS should follow upstream distribution

e2e_test/batch/explain.slt, e2e_test/ddl/table.slt, e2e_test/source/basic_test.slt, src/connector/src/sink/kafka.rs, src/connector/src/sink/mod.rs, src/frontend/src/handler/create_sink.rs, src/frontend/src/handler/drop_sink.rs, src/sqlparser/tests/testdata/create.yaml
as title, this pr rename sink usage in SQL. More info in release part 
If your pull request contains user-facing changes, please specify the types of …
=> refactor(sink): rename sink properties

src/frontend/src/scheduler/error.rs, src/frontend/src/scheduler/worker_node_manager.rs
…orkers found
I think we should return errors if 0 parallel units provides, cuz it will result in 0 worker nodes.
0 worker nodes means we do not schedule **any** task. 
If we do not do this, we need to add logic in caller side. But this is not necessary and duplicate and complex.
* SQL commands, functions, and …
=> fix(worker-node-mgr): worker node manager should return error if no workers found

Cargo.lock, e2e_test/batch/aggregate/timestamp.slt.part, src/batch/src/execution/local_exchange.rs, src/common/Cargo.toml, src/common/src/cache.rs, src/common/src/config.rs, src/connector/src/source/filesystem/file_common.rs, src/connector/src/source/filesystem/s3/s3_dir.rs, src/connector/src/source/pulsar/admin/client.rs, src/connector/src/source/pulsar/enumerator/client.rs, src/meta/src/hummock/metrics_utils.rs, src/meta/src/rpc/metrics.rs, src/meta/src/rpc/server.rs, src/meta/src/stream/stream_manager.rs, src/meta/src/stream/test_fragmenter.rs, src/object_store/src/object/disk.rs, src/source/src/table_v2.rs, src/storage/hummock_sdk/src/filter_key_extractor.rs, src/stream/src/executor/merge.rs, src/stream/src/executor/source/source_executor.rs, src/tests/sqlsmith/Cargo.toml, src/utils/pgwire/Cargo.toml, src/utils/pgwire/src/pg_server.rs, src/workspace-hack/Cargo.toml
This PR fixes several unit tests in simulation:
- switch all multi-thread tokio runtime to default current-thread runtime
- `risingwave_common cache::tests::test_future_cancel`: yield instead of spin loop. @Little-Wallace 
- `risingwave_connector`: ignore all tests using MockServer since it's not supported on madsim. @shanicky 
- `risingwave_object_store`: ignore all tests in disk object store since madsim does not support fs yet. @wenym1 
- `risingwave_stream executor::source::source_executor::tests::test_table_dropped`: write chunk on current task instead of spawn a new one to avoid panic after table dropped @BugenZhao 
- …
=> fix(test): fix or ignore several unit tests on madsim

Makefile.toml, ci/scripts/build.sh, ci/scripts/e2e-source-test.sh, ci/scripts/e2e-test-parallel.sh, ci/scripts/e2e-test.sh, ci/scripts/regress-test.sh, src/cmd_all/src/playground.rs, src/risedevtool/README.md, src/risedevtool/src/bin/risedev-compose.rs, src/risedevtool/src/bin/risedev-dev.rs, src/risedevtool/src/config.rs, src/risedevtool/src/service_config.rs
As title. This PR also fixes that the `risedev playground` ignores the config file.
=> chore(risedev): avoid using ambiguous "playground" term with `risedev d`

Makefile.toml
All commands running locally should update Cargo.lock, so we removed --locked here. Also removed -D warning to avoid possible recompile. …
=> fix(risedev): check clippy should report warning

src/frontend/src/optimizer/plan_node/logical_apply.rs, src/frontend/src/optimizer/rule/apply_agg.rs, src/frontend/src/optimizer/rule/apply_proj.rs, src/frontend/src/optimizer/rule/translate_apply.rs, src/frontend/test_runner/tests/testdata/subquery_expr_correlated.yaml, src/frontend/test_runner/tests/testdata/tpch.yaml
We used to treat scalar agg and group agg the same when push Apply down. However this isn't true when it comes to count(*).
This pr fix this bug.
If we run TranslateApply multiple times, then Apply's left will be rewritten multiple times, but the logic of rewriting Apply's left can only be applied once. We currently rely `rewrite()` on returning None to remind us that left doesn't need to be rewritten, …
=> fix(optimizer): push Apply down scalar agg.

src/frontend/src/handler/create_source.rs, src/sqlparser/src/ast/statement.rs, src/sqlparser/src/keywords.rs
=> fix: allow create source with row format debezium_json

src/frontend/src/stream_fragmenter/mod.rs, src/frontend/src/stream_fragmenter/rewrite/delta_join.rs
There is an empty struct called `StreamFragmenter` with many instance methods. I have made them static methods.
This is a follow up after #4519
=> refactor(fragmenter): delete unneeded `self.` in fragmenter

src/storage/src/hummock/compaction_group_client.rs, src/storage/src/hummock/error.rs, src/storage/src/hummock/mod.rs
As titled. See https://github.com/singularity-data/risingwave/issues/4427 for detail.
Please create a release note for your changes. In the release note, focus on the impact on …
=> fix(storage): remove timeout when get compaction group id

e2e_test/batch/types/cast.slt.part, src/common/src/types/ordered_float.rs, src/expr/src/expr/expr_unary.rs, src/expr/src/vector_op/cast.rs, src/frontend/src/handler/util.rs
* Fixes float to string casting of `Infinity`. (It used to be `inf`)
* Support casting to string from `time`/`interval`/`date`/`timestamp`.
* Placeholder implementation for casting `timestamp with time zone` to string. Its final implementation depends on `TimeZone` from session (#3552).
#1632
=> feat(expr): support casting temporal types to string

proto/task_service.proto, src/batch/src/rpc/service/task_service.rs, src/batch/src/task/task_execution.rs, src/batch/src/task/task_manager.rs
Working on a draft PR of cancel task and I found that an important problem is how we define `abort_task()` API semantics. 
Now, `abort_task()` will succeed only if the task is cancelled by exact that request. Means if a task A has already stopped execution (may be because self-failure or complete) before that request, in this case abort_task still fail cuz it is not abort by exact that request.
I want to change that semantics of API to "**As long as the task is die, no matter in what ways, return success**".  This may means even if the task is died because of task execution failure, previous aborted, task_id not found …
=> refactor: propose the API semantics of abort_task

.cargo/config.toml
Previously the stack cannot be shown correctly when profiling. This is caused by [a bug in `lld `](https://bugs.chromium.org/p/chromium/issues/detail?id=919499#c16) which we used to link on Linux platform. The stack unwind is broken so flamegraph looks weird.
After adding flag `-Wl,--no-rosegment` to `lld`, everything works.
By the way, the [cargo-flamegraph](https://github.com/flamegraph-rs/flamegraph) project works well for me. It helps you to run `perf` and then generate flame graph in one command.
N/A
N/A
None
=> fix: stack unwind when profiling

src/storage/src/table/state_table.rs, src/stream/src/executor/managed_state/aggregation/extreme.rs, src/stream/src/executor/managed_state/aggregation/string_agg.rs, src/stream/src/executor/managed_state/mod.rs, src/stream/src/executor/managed_state/top_n/top_n_state_new.rs
This PR extracts the creation of iterator on state table with/without pk prefix as a function, to improve code reuse.
This is part of the refactoring of managed agg state.
=> refactor(stream): extract `iter_state_table` function

src/stream/src/common/column_mapping.rs, src/stream/src/common/mod.rs, src/stream/src/executor/aggregation/mod.rs, src/stream/src/executor/global_simple_agg.rs, src/stream/src/executor/hash_agg.rs, src/stream/src/executor/managed_state/aggregation/mod.rs, src/stream/src/executor/managed_state/aggregation/string_agg.rs
This PR adds a new `StateTableColumnMapping` to convert column indices between state table and input chunk. It's intended to be used in managed agg states to find columns they're interested in from state table and construct state table rows from input chunks.
This is part of the refactoring of managed agg states.
#4185
=> refactor(stream,agg): add `StateTableColumnMapping` to convert column indices

e2e_test/batch/basic/index.slt.part, src/frontend/src/handler/mod.rs, src/frontend/src/handler/variable.rs, src/frontend/src/optimizer/rule/index_selection.rs, src/frontend/test_runner/src/lib.rs, src/frontend/test_runner/tests/testdata/index_selection.yaml
- support non-covering index selection
- index lookup is logically equivalent to a logical join with an index scan as its left input and a primary table scan as its right input.
- index lookup cost is equal to the index cost of the index scan multiplying a constant value which simply is 3 currently.
#4339
=> feat(optimizer): support non-covering index selection

src/frontend/src/scheduler/distributed/query.rs, src/frontend/src/scheduler/distributed/stage.rs, src/frontend/src/scheduler/error.rs, src/rpc_client/src/compute_client.rs
* Add a shutdown channel to control task abort
* The test in basic.slt.part `values(CAST('abc' AS BOOLEAN))` is a test case we can observe. It shows that it is indeed being called `abort_task` …
=> feat(batch): abort task when failed

src/stream/src/common/column_mapping.rs
This PR removes the unused `state_table_to_upstream` in `StateTableColumnMapping`. It's a small amendment for #4584.
#4584
=> refactor(stream): remove useless `state_table_to_upstream` method

Cargo.lock, src/batch/Cargo.toml, src/batch/src/executor/trace.rs, src/batch/src/task/task_execution.rs, src/stream/Cargo.toml, src/stream/src/executor/actor.rs, src/stream/src/executor/debug/trace.rs, src/stream/src/executor/mod.rs, src/stream/src/task/stream_manager.rs
This is the first PR in series to enable minitrace and find slow requests using minitrace. We replace all tokio tracing spans with minitrace. As currently we don't specify a root span, all those spans are no-op and won't do any actual work.
* SQL commands, functions, …
=> feat(runtime): replace tokio-tracing with minitrace

Cargo.lock, e2e_test/batch/types/interval.slt.part, src/common/src/types/interval.rs, src/expr/src/expr/expr_unary.rs, src/frontend/src/binder/expr/value.rs, src/sqlparser/Cargo.toml, src/sqlparser/src/ast/value.rs
We used to parse interval in binder, and only support the first 2 queries but not the last one:
```
select interval '3' day;
select interval '3 day';
select '3 day'::interval;
```
This PR extracts the parsing logic (#3037) from `bind_interval` to `common::types::IntervalUnit`, and reuses it for casting expr.
Note that the parsing logic is moved unchanged. Its enhancement deserves a standalone PR.
This also decouples the crates `sqlparser` and `common`. Neither is dependent on the other.
#1632
=> refactor(expr): support string-to-interval casting

e2e_test/streaming/struct_table.slt, src/sqlparser/src/parser.rs
fix https://github.com/singularity-data/risingwave/issues/4611
The problem is that when `parse_struct_data_type` handles `struct<v2 struct<v1 int, v2 int>>,` the comma is wrongly consumed by the outer call. It should return in the `self.angle_brackets_num == 0` branch without consuming the comma.
=> fix(parser): fix parsing right angle brackets

proto/task_service.proto, risedev.yml, src/batch/src/task/task_execution.rs, src/frontend/src/scheduler/distributed/query.rs, src/frontend/src/scheduler/distributed/stage.rs
* Cut down some unused status in task_service.proto.
* Simplify `StateState` and `QueryState`, tries to move join_handle, sender etc out from it. 
* 
Please create a release note …
=> refactor: simplify the task status and stage state

e2e_test/ddl/user.slt, src/frontend/src/handler/drop_user.rs
`ObjectName::to_string` is not meant to extract the user name. `create user` actually uses `Binder::resolve_user_name` to convert from `ObjectName` to `String`.
Fixes #4623
=> fix(handler): handle quoted names in `drop user`

src/frontend/src/optimizer/plan_node/logical_scan.rs
- fix logical scan distribution_key using `output_col_idx` instead of `required_col_idx`.
=> fix(optimizer): fix logical scan distribution key

src/frontend/src/expr/agg_call.rs, src/frontend/test_runner/tests/testdata/batch_dist_agg.yaml, src/frontend/test_runner/tests/testdata/stream_dist_agg.yaml, src/frontend/test_runner/tests/testdata/subquery_expr_correlated.yaml
Previously `string_agg` calls with invalid arguments is allowed by frontend, and the error is threw until it arrive backend.
=> fix(frontend): reject invalid `string_agg` calls in frontend

src/frontend/src/expr/agg_call.rs, src/frontend/src/expr/type_inference/agg.rs, src/tests/sqlsmith/src/expr.rs
Add support to generate `string_agg` calls in `SqlGenerator::gen_agg`, since `string_agg` is already fully supported in RW.
=> feat(sqlsmith): support generating `string_agg` calls

src/meta/src/rpc/service/hummock_service.rs
as title
- prevent use incorrect table_id to filter sst
- add assert
=> fix(meta): fix trigger_manual_compaction incorrect table_id

src/source/src/row_id.rs, src/stream/src/executor/source/source_executor.rs
=> feat: update row-id generator when vnode mapping changed

src/storage/benches/bench_compactor.rs, src/storage/benches/bench_merge_iter.rs, src/storage/src/hummock/compactor/compactor_runner.rs, src/storage/src/hummock/iterator/backward_merge.rs, src/storage/src/hummock/iterator/backward_user.rs, src/storage/src/hummock/iterator/concat_inner.rs, src/storage/src/hummock/iterator/forward_merge.rs, src/storage/src/hummock/iterator/forward_user.rs, src/storage/src/hummock/iterator/merge_inner.rs, src/storage/src/hummock/iterator/mod.rs, src/storage/src/hummock/shared_buffer/mod.rs, src/storage/src/hummock/shared_buffer/shared_buffer_batch.rs, src/storage/src/hummock/state_store.rs, src/storage/src/storage_failpoints/test_iterator.rs
In #2709 we introduced local metrics for iterators and block cache, which, however, needs to be carefully reported by caller. Besides, it didn't check if the its data is reported or reported multiple times. And that leads to abnormal metrics:
e.g. 70k+ meta cache access but 0 data cache accesss
After investigation, both metrics lost and metrics reported multiple times problems exist by:
```rust
#[derive(Default)]
pub struct StoreLocalStatistic {
// ... ...
reported: AtomicBool,
added: AtomicBool,
}
impl StoreLocalStatistic {
pub fn add(&mut self, other: &StoreLocalStatistic) {
// ... ...
if other.added.fetch_or(true, …
```
=> fix(metrics): fix iterator metrics data report duplication and lost

Cargo.lock, src/bench/Cargo.toml, src/common/src/test_utils/rand_array.rs, src/frontend/Cargo.toml, src/meta/Cargo.toml, src/prost/Cargo.toml, src/storage/hummock_test/Cargo.toml, src/tests/simulation/Cargo.toml, src/utils/async_stack_trace/Cargo.toml, src/workspace-hack/Cargo.toml
This PR unifies the dependencies to have one version.
* remove futures-executor when possible
* retain only one version of aws-sdk
* try retaining only one prost
pulsar-rs is still using prost v0.10 and needs upstream update. will be fixed after upstream updates the dependency.
=> chore(deps): bump dependencies

e2e_test/batch/basic/func.slt.part, src/sqlparser/src/parser.rs
As per title. See discussion https://github.com/singularity-data/risingwave/pull/4729#discussion_r949988804.
#4344
=> chore(parser): remove todo for parsing nested negative expressions

e2e_test/batch/aggregate/aggregate2/test.slt.part, e2e_test/batch/basic/array_access.slt.part, src/frontend/src/binder/expr/value.rs
Replace panic with BindError.
Previously `select * from t where v1[1]=1;` resulted in a panic, now in a BindError.
closes #4755
=> fix(binder): fix panic when index on non composite type

src/common/src/session_config/query_mode.rs
Make local execution mode default.
Default batch execution mode changed from distributed to local.
#4654
=> refactor(batch): Make local mode default

src/risedevtool/src/task/compute_node_service.rs
After this PR, 
```sh
RW_NODE=playground cargo run --bin risingwave -- playground
```
can work.
N/A
N/A
None
=> fix: cargo run playground

src/frontend/src/optimizer/plan_node/logical_scan.rs
- LogicalScan clone should use `output_col_idx` instead of `required_col_idx` to preserve its output schema.
=> fix(optimizer): fix logical scan clone with predicate

ci/build-ci-image.sh, ci/docker-compose.yml, ci/scripts/e2e-test-parallel.sh, risedev.yml, src/risedevtool/README.md
This PR adds a new profile of `ci-3cn-3fe` which starts 3 frontend nodes, and applies parallel e2e with it.
- https://github.com/risinglightdb/sqllogictest-rs/pull/76
=> feat(ci): randomly pick from multiple frontends in parallel e2e

src/meta/src/manager/catalog/mod.rs, src/meta/src/stream/stream_manager.rs
Due to the misunderstanding of the process at the beginning , the previous PR introduced `broadcast_info_op`. It will notify all nodes (`frontend`, `compute`, `compactor`) after creating and destorying the mview. 
For creating and destorying, `compactor` and `compute` must maintain the `Catalog` for compaction that it can build the `prefix_bloom_filter` by `Catalog` until last `barrier`  through the whole graph. 
In short, we need to ensure that before the `Barrier Command`, `compactor` and `compute` must maintain the `Catalog` , otherwise it will stuck.
Why did we remove broadcast in `catalog.rs` ?
It is no longer needed …
=> fix(compactor): fix drop mv stuck

src/expr/src/expr/agg.rs, src/tests/sqlsmith/src/expr.rs
- Disable single value in sqlsmith. I think this approach is better, since single value is meant for internal use.
- Added some comments providing more clarity on single-value.
- [See previous discussion on single value ](https://risingwave-labs.slack.com/archives/C03G9HMLEBC/p1653378232953079).
- I don't think we necessarily want / need to support `single_value(timestamp)` as a feature. 
It is unused, hence disabling it on sqlsmith should close #4864 .
Related to: #1335, #4866, #4864
=> fix(sqlsmith): disable single value

src/meta/src/hummock/manager/mod.rs
need to regain the newest version ynder the protection of a write lock, otherwise the old version may be used to overwrite the new one
- fix current_version
=> fix(compactor): fix version get for trivial_move

Cargo.lock, src/tests/simulation/Cargo.toml
Thanks to @wangrunji0408's hard work, the madsim v0.2.4 supports simulating coarse clock, which is necessary for those systems without `tsc` support (mainly seen on virtual machines).
```
❯ cat /sys/devices/system/clocksource/clocksource0/available_clocksource
kvm-clock hpet acpi_pm 
```
=> chore: bump madsim to support coarse clock

src/meta/src/barrier/command.rs
There are many cascading updates in the scaling scenario
When the upstream changes, the downstream actor will update its upstream by `merges` in `UpdateMutation` and wait for the new upstream barrier, but when the downstream actor is about to be deleted, the upstream actor does not forward the `Barrier` to it, so it will cause infinite waiting.
This PR skips the Merge Update of the deleted downstream actors
As an example, the dashed node downstream in the diagram should not expect the upstream Barrier to forward through the red line
~- [ ] I have written necessary rustdoc …
=> feat: do not update downstream removed actors' merge node in case of cascading migration

src/frontend/src/optimizer/plan_node/logical_scan.rs
- Fix index scan output schema by using `output_col_idx` instead of `required_col_idx`.
#4921
=> fix(optimizer): fix index scan output schema

src/meta/src/hummock/compaction/mod.rs, src/meta/src/hummock/manager/mod.rs
use apply_version_delta to replace apply_compact_result in order to avoid using `compact_task` to apply vesrion again after generating `version_delta` with `compact_task`
- use `apply_version_delta` for `current_version`
- remove the calculation of `new_version_id`, `new_version_id` is only calculated in `apply_version_delta`
- remove unused function
- https://github.com/singularity-data/risingwave/pull/4890
=> refactor(meta): use apply_version_delta to replace apply_compact_result

src/frontend/src/optimizer/plan_node/batch_hop_window.rs, src/frontend/src/optimizer/plan_node/batch_project.rs, src/frontend/src/optimizer/plan_node/batch_project_set.rs, src/frontend/src/optimizer/plan_node/logical_hop_window.rs, src/frontend/src/optimizer/plan_node/logical_project.rs, src/frontend/src/optimizer/plan_node/logical_project_set.rs
This PR introduces deriving the order property for query optimization from the respective input, if the order does not change due to the operator.
- [ x] I have written necessary rustdoc comments
- [ x] I have added necessary unit tests and integration tests
- [ x] All checks passed in `./risedev check` (or alias, `./risedev c`)
=> feat(frontend): Derive order property from input 

src/frontend/src/optimizer/rule/apply_scan.rs, src/frontend/test_runner/tests/testdata/subquery.yaml, src/frontend/test_runner/tests/testdata/subquery_expr_correlated.yaml, src/frontend/test_runner/tests/testdata/tpch.yaml
- `ApplyScanRule` contains the remove DAG logic which relies on equivalent detection. The equivalent here is null reject semantics, so all the related column need to be filtered by `is not null`.
=> fix(optimizer): fix apply scan rule with null reject

src/storage/src/hummock/mod.rs, src/storage/src/hummock/shared_buffer/shared_buffer_batch.rs, src/storage/src/hummock/state_store.rs, src/storage/src/hummock/validator.rs, src/storage/src/hummock/value.rs
refactor get_from_table
- extract `user_key` in `get_from_table`
- remove duplicated parameter `key` 
=> refactor(storage): refactor get_from_table

e2e_test/batch/basic/range_scan.slt.part, src/batch/src/executor/join/lookup_join.rs, src/batch/src/executor/row_seq_scan.rs, src/common/src/util/scan_range.rs, src/frontend/src/expr/mod.rs, src/frontend/src/optimizer/plan_node/batch_seq_scan.rs, src/frontend/src/utils/condition.rs, src/frontend/test_runner/tests/testdata/range_scan.yaml
- Support `is null` for scan range which is also a preparation for null-safe lookup join.
#4958
=> feat(batch): support is null for scan range

src/frontend/src/expr/expr_visitor.rs, src/frontend/src/expr/mod.rs, src/frontend/src/expr/utils.rs, src/frontend/src/optimizer/mod.rs, src/frontend/src/optimizer/plan_correlated_id_finder.rs, src/frontend/src/optimizer/plan_visitor.rs, src/frontend/src/optimizer/rule/index_selection.rs
- `ExprVisitor` and `PlanVisitor` provide a default return value `R` but with an easy misuse default merge function which returns the first visit value of its inputs.
- This PR enforces users to implement their `merge` function to merge the return value.
- The most mistaken use case of this kind of visitor is to implement the `Has` visitors. `Has` visitors should provide a merge function like `|a, b| -> a | b`
=> refactor(frontend): refactor expr visitor and plan visitor

src/frontend/src/expr/function_call.rs, src/frontend/src/expr/type_inference/func.rs, src/frontend/test_runner/tests/testdata/expr.yaml
They should also be part of `infer_type`.
=> refactor(binder): extract special type infer rules from `FunctionCall:new`

risedev.yml
Since #5009 and #5035 are fixed, we can restore tiered cache on CI and 3 node benchmark compose.
#5009 #5035 #5036 #5039
=> chore: enable tiered cache on CI and 3 node compose

src/frontend/src/optimizer/plan_node/mod.rs, src/frontend/src/stream_fragmenter/mod.rs, src/frontend/src/stream_fragmenter/rewrite/delta_join.rs, src/frontend/src/stream_fragmenter/rewrite/mod.rs
+ Removed struct `StreamFragmenter`
+ Publicize `BuildFragmentGraphState` at crate level for future refactoring
Not really needed -- the change list is pretty much the documentation (and it's just three lines!)
#3684
=> refactor(fragmenter): remove unneeded struct, prepare for rewrite

README.md
I'm trying out the first query from README.md but it failed. It turns out NOT NULL constraint is deleted (https://github.com/RisingWaveLabs/risingwave/issues/4513). So I delete NOT NULL constraint too in README.md.
* Other …
=> fix: delete not null of first query demo in README.md

src/stream/src/executor/dispatch.rs
When testing migration in #4956, we find that simple dispatcher does not support updating now. According to our design, the `Update` barrier should be forwarded to all outputs, including the to-be-removed ones and to-be-added ones. Therefore, the simple dispatcher need to hold 2 outputs temporarily. The old one will be dropped before we finish processing the `Update` mutation, so we assert the data chunk should always be dispatched to exactly one actor.
Note: `Update` on the receiver executor (a special version of merge executor with only 1 receiver) is still not implemented yet. …
=> feat(streaming): support configuration change on simple dispatcher

src/frontend/src/binder/query.rs, src/frontend/test_runner/tests/testdata/limit.yaml, src/sqlparser/src/ast/mod.rs, src/sqlparser/src/ast/query.rs, src/sqlparser/src/parser.rs, src/sqlparser/src/test_utils.rs, src/sqlparser/tests/sqlparser_common.rs, src/sqlparser/tests/testdata/select.yaml, src/tests/sqlsmith/src/lib.rs
When I try `WITH TIES` I found `FETCH` is ignored, which is bad 😕
This PR: 
- Rejects `WITH TIES` and bind `FETCH` to limit. 
- Also did some refactor on sqlparser: simply let `limit/offset/fetch` be `String`, instead of `Expr`, so that unnecessary pattern matching can be avoided.
(Note: I also found that PG supports `OFFSET` after `FETCH`. Not implemented here.
> According to the standard, the OFFSET clause must come before the FETCH clause if both are present; but PostgreSQL is laxer and allows either order.
=> feat(binder): bind FETCH

src/frontend/src/handler/explain.rs
Support explain distsql in the handler to output JSON-formatted distributed plan information. Eg. 
```
create table t1(v1 int);
explain (type distsql) select * from t1;
QUERY PLAN                 
--------------------------------------------
{
"root_stage_id": 0,
"stages": {
"1": {
"root": {
"plan_node_id": 17,
"plan_node_type": "BatchSeqScan",
"schema": [
{
"dataType": {
"typeName": "INT32",
"isNullable": true
},
"name": "t1.v1"
}
],
"children": [],
"source_stage_id": null
},
"parallelism": 4,
"exchange_info": {
"mode": "SINGLE"
}
},
"0": {
"root": {
"plan_node_id": 18,
"plan_node_type": "BatchExchange",
"schema": [
{ …
```
=> feat(frontend): support explain distsql

src/frontend/src/handler/dml.rs, src/frontend/src/optimizer/mod.rs, src/frontend/test_runner/tests/testdata/basic_query.yaml, src/frontend/test_runner/tests/testdata/index_selection.yaml, src/frontend/test_runner/tests/testdata/insert.yaml, src/frontend/test_runner/tests/testdata/update.yaml
Currently only a demo and I'm not sure whether which way we should do. 
Please create a release note for your changes. In the release note, focus on the impact on users, and …
=> refactor: always insert a exchange singleton on top dml

src/frontend/src/handler/query.rs, src/frontend/src/scheduler/distributed/mod.rs, src/frontend/src/scheduler/distributed/query.rs, src/frontend/src/scheduler/distributed/query_manager.rs, src/frontend/src/scheduler/error.rs, src/frontend/src/scheduler/mod.rs, src/frontend/src/session.rs, src/frontend/src/test_utils.rs, src/utils/pgwire/src/error.rs, src/utils/pgwire/src/pg_message.rs, src/utils/pgwire/src/pg_protocol.rs, src/utils/pgwire/src/pg_server.rs, src/utils/runtime/src/lib.rs
Abort task when receive ctrl-c signal. Note: this do not mean the query will return immediately.
Code change:
* Add psql protocol related Message: `BackendKeyData`, `CancelRequest`. Used to process cancel request from user.
* Add a shutdown channel for each query and use tokio::select in `QueryRunner`: once received a `()`, shutdown all stages. Should differentiate with #5022: One shutdown message is sent from QueryRunner, one is sent from user. 
* Records the channel for each query in `SessionImpl`: When user cancel a query, first fetch correspoding session using SessionId, then fetch all running queries channel and send …
=> refactor: cancel running batch query of ctrl-c

Cargo.lock, src/ctl/Cargo.toml, src/ctl/src/cmd_impl/meta.rs, src/ctl/src/cmd_impl/meta/reschedule.rs, src/ctl/src/lib.rs, src/meta/src/stream/scale.rs, src/rpc_client/src/meta_client.rs
This PR provides the `risedev ctl meta reschedule` interface, which allows you to call the reschedule api of meta directly from the command line.
Use the `--plan` parameter to provide a reschedule plan, which can provide multiple fragment at the same time  separated by `;`, and the `-dry-run` parameter will only show the parsed results without operation
```
100-[1,2,3]+[4,5];101-[1];102+[3]
```
For fragment 100,  parallel units 1,2,3 will be removed, while parallel units 4,5 will be added. 
You can also provide only the removed parallel unit ids (like fragment 101) or only the added pu ids (like fragment 102), but in the …
=> feat: reschedule interface in risedev 

src/meta/src/barrier/mod.rs, src/meta/src/barrier/recovery.rs, src/meta/src/rpc/server.rs, src/meta/src/stream/source_manager.rs, src/meta/src/stream/stream_manager.rs, src/stream/src/executor/source/source_executor.rs
as title, push the assignment to source executor can help restore state. 
fix #4918
=> fix: meta push split assignments down when recovery

src/compute/src/server.rs, src/rpc_client/src/compute_client.rs, src/utils/pgwire/src/pg_server.rs
Set tcp no_delay option to reduce latency.
=> feat: Set tcp no delay for compute nodes

src/ctl/src/cmd_impl/hummock/list_kv.rs
As titled.
Please create a release note for your changes. In …
=> fix(ctl): use given epoch when list_kv

src/frontend/src/handler/query.rs, src/frontend/src/scheduler/distributed/query_manager.rs, src/frontend/src/scheduler/error.rs, src/frontend/src/scheduler/local.rs
This makes the code more easy to write for #5027 
Add `collect_rows()` convert Stream<DataChunk> -> Vec<Rows>. Handler do not need to know the detail of data fetch.
Do not consume data chunk in a stream in handler, hide the detail inside ResultFetcher.
* RisingWave …
=> refactor(batch): do not consume data chunk in handler

src/meta/src/manager/cluster.rs, src/meta/src/manager/notification.rs
- As title.
- Use any command by risedev ctl. After 60s without any heartbeat, meta will panic.
Log:
```
thread 'risingwave-main' panicked at 'internal error: entered unreachable code', src/meta/src/manager/notification.rs:155:18
```
close #5194
=> fix(meta): expired RiseCtl worker causes meta panics

src/meta/src/manager/notification.rs, src/tests/sync_point/src/test_utils.rs
remove unused notify_all
- remove unused notify_all
- remove WorkerType::Generic
- https://github.com/risingwavelabs/risingwave/issues/5238
=> chore(meta): remove unused notify_all

e2e_test/batch/aggregate/sort_agg.slt.part, src/frontend/planner_test/tests/testdata/agg.yaml, src/frontend/planner_test/tests/testdata/order_by.yaml, src/frontend/planner_test/tests/testdata/tpch.yaml, src/frontend/src/optimizer/plan_node/batch_sort_agg.rs, src/frontend/src/optimizer/plan_node/logical_agg.rs, src/frontend/src/optimizer/plan_node/logical_project.rs
This PR makes use of Sort Aggregation, when a sort order is required by the output
- [ x] I have written necessary rustdoc comments
- [x ] I have added necessary unit tests and integration tests
- [x ] All checks passed in `./risedev check` (or alias, `./risedev c`)
=> feat(frontend): Use SortAgg when output requires sort 

e2e_test/streaming/nexmark_snapshot.slt, e2e_test/streaming/nexmark_upstream.slt, e2e_test/streaming/tpch_snapshot.slt, e2e_test/streaming/tpch_upstream.slt
As title. Previously the `tpch_upstream.slt` is the same as `tpch_snapshot.slt`. 😄
=> fix(test): data should be from upstream in `tpch_upstream.slt`

src/storage/src/table/streaming_table/mem_table.rs, src/storage/src/table/streaming_table/state_table.rs, src/storage/src/table/streaming_table/test_streaming_table.rs
Make the panic message easier to read when conflicts detected by memtable.
Before:
> thread 'risingwave-streaming-actor' panicked at 'invalid flush status: double insert [75, 0, 128, 0, 0, 4, 0, 128, 0, 0, 4] -> [1, 4, 0, 0, 0, 1, 18, 0, 0, 0, 83, 117, 112, 112, 108, 105, 101, 114, 35, 48, 48, 48, 48, 48, 48, 48, 48, 52, 1, 25, 0, 0, 0, 66, 107, 55, 97, 104, 52, 67, 75, 56, 83, 89, 81, 84, 101, 112, 69, 109, 118, 77, 107, 107, 103, 77, 119, 103, 1, 15, 0, 0, 0, 50, 53, 45, 56, 52, 51, 45, 55, 56, 55, 45, 55, 52, 55, 57, 1, 0, 0, 4, 0, 98, 25, 56, 25, 2, 0, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0]'
After:
> thread …
=> feat: improve memtable conflicts error message

src/frontend/src/handler/mod.rs, src/sqlparser/src/ast/mod.rs, src/sqlparser/src/parser.rs, src/sqlparser/tests/sqlparser_common.rs, src/utils/pgwire/src/pg_protocol.rs, src/utils/pgwire/src/pg_response.rs
separate BEGIN and START_TRANSACTION.
#5262
=> fix(frontend): mix START_TRANSACTION and BEGIN

src/frontend/planner_test/tests/testdata/index_selection.yaml, src/frontend/src/optimizer/plan_node/logical_scan.rs
Instead of checking if the cost of using an index scan is cheaper than just ripping through all values, the fact that the output requires a specific order is taken into account when choosing scan types.
This PR introduces the usage of covered index, when the output requires an order that is matched by the index.
=> feat(frontend): Use index scan if it satisfies required order

e2e_test/streaming/bug_fixes/issue_5285.slt, src/stream/src/executor/group_top_n.rs, src/stream/src/executor/top_n.rs, src/stream/src/executor/top_n_appendonly.rs, src/stream/src/executor/top_n_executor.rs
fix https://github.com/risingwavelabs/risingwave/issues/5285
=> fix(stream): fix wrong usage of chunk builder in topn

src/common/src/array/data_chunk_iter.rs, src/compute/tests/integration_tests.rs, src/storage/src/table/batch_table/test_batch_table.rs, src/storage/src/table/streaming_table/state_table.rs, src/storage/src/table/streaming_table/test_streaming_table.rs, src/stream/src/executor/dynamic_filter.rs, src/stream/src/executor/group_top_n.rs, src/stream/src/executor/hash_join.rs, src/stream/src/executor/managed_state/aggregation/array_agg.rs, src/stream/src/executor/managed_state/aggregation/extreme.rs, src/stream/src/executor/managed_state/aggregation/string_agg.rs, src/stream/src/executor/managed_state/aggregation/value.rs, src/stream/src/executor/managed_state/dynamic_filter.rs, src/stream/src/executor/managed_state/join/join_entry_state.rs, src/stream/src/executor/managed_state/join/mod.rs, src/stream/src/executor/managed_state/top_n/top_n_state.rs, src/stream/src/executor/mview/test_utils.rs, src/stream/src/executor/top_n.rs, src/stream/src/executor/top_n_appendonly.rs
As title:
```diff
-    pub fn serialize(&self) -> value_encoding::Result<Vec<u8>> {
+    pub fn serialize(&self) -> Vec<u8> {
```
Other changes are consequent. 😇
None
None
=> refactor: `Row::serialize()` does not need to return `Result`

proto/hummock.proto, src/ctl/src/cmd_impl/hummock/list_version_deltas.rs, src/ctl/src/lib.rs, src/meta/src/hummock/manager/mod.rs, src/meta/src/hummock/mock_hummock_meta_client.rs, src/meta/src/rpc/service/hummock_service.rs, src/rpc_client/src/hummock_meta_client.rs, src/rpc_client/src/meta_client.rs, src/storage/src/hummock/hummock_meta_client.rs
Add a list-version-deltas command to **risectl** to print the version delta logs.
Users can specify the first version delta via `start_id` and the number of epochs to print via `num_epochs`.
```
$ ./risedev ctl hummock list-version-deltas -h
USAGE:
risectl hummock list-version-deltas [OPTIONS]
OPTIONS:
-h, --help                                 Print help information
-n, --num-epochs <NUM_EPOCHS>              [default: 100]
-s, --start-version-delta-id <START_ID>    [default: 0]
-V, --version                              Print version information
```
~- [ ] I have added …
=> feat(risectl): risectl hummock: add list-version-deltas

src/utils/pgwire/src/pg_extended.rs, src/utils/pgwire/src/pg_protocol.rs
We missing a behavior in describe phase : [https://www.postgresql.org/docs/current/protocol-flow.html#:~:text=The%20response%20is%20a%20RowDescri[…]0a%20query%20that%20will%20return%20rows%3B](https://www.postgresql.org/docs/current/protocol-flow.html#:~:text=The%20response%20is%20a%20RowDescription%20message%20describing%20the%20rows%20that%20will%20be%20returned%20by%20executing%20the%20portal%3B%20or%20a%20NoData%20message%20if%20the%20portal%20does%20not%20contain%20a%20query%20that%20will%20return%20rows%3B)
#3675
=> fix(pgwire): return no_data in describe message when encounter non-query statement 

src/batch/src/rpc/service/task_service.rs, src/batch/src/task/context.rs
disable collecting executor metrics in local execution mode 
this pr can fix #5320 . After disable collecting executor metrics, the zero QPS didn't occur. So I guess that prometheus will not be OOM.
#5013
=> fix:disable collecting executor metrics in local execution mode 

risedev.yml, src/batch/src/task/hash_shuffle_channel.rs, src/common/src/array/data_chunk.rs, src/common/src/array/data_chunk_iter.rs, src/common/src/hash/key.rs, src/common/src/util/hash_util.rs, src/common/src/util/scan_range.rs, src/expr/src/expr/expr_vnode.rs, src/storage/src/table/mod.rs, src/storage/src/table/streaming_table/state_table.rs, src/stream/src/executor/dispatch.rs, src/stream/src/executor/hash_agg.rs
This PR adds the vnode checking for the `write_chunk` interface of the state table. So that we can check whether the distribution of records written with `write_chunk` is correct.
- #5151 
- #5344 
- #5322
=> fix(streaming): add vnode check for state table `write_chunk`

src/common/src/config.rs, src/compute/src/server.rs, src/config/risingwave.toml, src/source/src/connector_source.rs, src/source/src/manager.rs
As per the title, reduce it from 512 to 16.
Also in #5249.
Also suspect that with a faster in-memory data generation source, this unnecessarily large size channel is the cause of OOM.
I mean, without memory management, OOM is expected. But it seems that OOM didn't occur this often before. …
=> refactor(config): reduce connector_message_buffer_size and make it configurable

risedev.yml, src/meta/src/lib.rs, src/meta/src/manager/env.rs, src/risedevtool/src/service_config.rs, src/risedevtool/src/task/meta_node_service.rs
Use 5 sec for `no_available_compactor_stall_sec` by default, which is the same as `compactor_selection_retry_interval_sec` removed by https://github.com/risingwavelabs/risingwave/pull/5240, in order to keep compaction behavior close to it.
* SQL …
=> chore: modify default value for no_available_compactor_stall_sec

src/frontend/planner_test/src/lib.rs, src/frontend/src/handler/create_mv.rs, src/frontend/src/handler/explain.rs, src/meta/src/hummock/compaction_group/manager.rs
lifecycle of new created compaction groups: when mv is created, dropped or compaction groups are purged
this PR is successor of #5265 
background:
Discussions on compaction group:
* Plan to introduce more compaction groups into our system. Experiments WIP.
* Prefer using separate HummockVersion for different compaction groups even when we have more compaction groups after considering using shared L0, which introduces excessive complexity in compaction and is error-prone.
* Discuss about optimizations to handle increasing IOPS and small objects issue.
If your pull request contains user-facing changes, please specify the …
=> feat(compaction group): lifecycle of new created compaction groups

src/common/src/config.rs, src/config/risingwave.toml, src/stream/src/executor/aggregation/mod.rs, src/stream/src/executor/global_simple_agg.rs, src/stream/src/executor/hash_agg.rs, src/stream/src/executor/hash_join.rs, src/stream/src/executor/lookup/cache.rs, src/stream/src/executor/lookup/impl_.rs, src/stream/src/executor/lookup/tests.rs, src/stream/src/executor/managed_state/aggregation/mod.rs, src/stream/src/executor/test_utils.rs, src/stream/src/from_proto/global_simple_agg.rs, src/stream/src/from_proto/hash_agg.rs, src/stream/src/from_proto/hash_join.rs, src/stream/src/from_proto/lookup.rs
#5249 wants to eliminate hardcoded values.
This PR moves
`HASH_AGG_CACHE_SIZE`,
`JOIN_CACHE_CAP`,
`EXTREME_CACHE_SIZE`,
to the configuration file.
Makes #5080  easier to enable the no-cache test. …
=> refactor(config): eliminate hardcoded cache size

src/frontend/src/optimizer/plan_node/logical_topn.rs, src/frontend/src/optimizer/plan_node/stream_group_topn.rs, src/frontend/src/optimizer/plan_node/stream_topn.rs
- remove useless parameter `group key` in `infer_catalog`
- more wrapper function instead of `self.logical.xxx()`
=> refactor(optimizer): some refactor on stream topn

src/common/src/util/epoch.rs, src/compute/src/rpc/service/stream_service.rs, src/stream/src/executor/actor.rs, src/stream/src/executor/hash_join.rs, src/stream/src/executor/lookup/impl_.rs, src/stream/src/executor/managed_state/dynamic_filter.rs, src/stream/src/executor/managed_state/join/mod.rs, src/stream/src/executor/mod.rs, src/stream/src/executor/source/reader.rs, src/stream/src/executor/source/source_executor.rs, src/stream/src/executor/top_n_appendonly.rs
- rename `pub struct Epoch {    pub curr: u64,    pub prev: u64}` to EpochPair
- move EpochPair into common crate
=> refactor(EpochPair):some refactor epoch pair

src/batch/src/executor/join/chunked_data.rs, src/batch/src/executor/join/hash_join.rs, src/batch/src/task/task_execution.rs, src/batch/src/task/task_manager.rs, src/common/src/error.rs
Reviewed the codes and found that we don't really need the `RwError` to implement `Clone`, remove it temporally.
And since we don't need `Clone`, we can also avoid the `Arc`.
=> chore(error): remove unnecessary Clone and use Box in RwError

src/common/src/field_generator/timestamp.rs, src/expr/src/vector_op/cast.rs
closes https://github.com/risingwavelabs/risingwave/issues/5481
=> feat(expr): limit timestamp datagen to microseconds, improve timestamp cast error msg

proto/meta.proto, src/meta/src/hummock/compaction_scheduler.rs, src/meta/src/manager/catalog/fragment.rs, src/meta/src/stream/scheduler.rs, src/meta/src/stream/stream_graph.rs, src/meta/src/stream/stream_manager.rs, src/meta/src/stream/test_fragmenter.rs
This PR introduces `upstream_fragment_ids` to `Fragment` to reduce the cost of maintaining the index when scaling, as there are many places to use, this field is currently modified in these two places
1. Creating Fragment
2. Creating mv on mv for chain node modification
* …
=> feat: add upstream_fragment_ids to Fragment

src/frontend/src/handler/query.rs, src/frontend/src/scheduler/distributed/query.rs, src/frontend/src/scheduler/distributed/query_manager.rs, src/frontend/src/scheduler/hummock_snapshot_manager.rs, src/frontend/src/scheduler/local.rs
Prior to this PR, we will never release the hummock snapshot assigned to batch queries in local execution mode. This PR fixes the issue and does some minor refactoring.
This is yet another bug that causes #5418.
* RisingWave …
=> fix(frontend): release hummock snapshot in local execution mode

src/stream/src/executor/global_simple_agg.rs, src/stream/src/executor/hash_agg.rs
After fixing the epoch watermark for compaction in #5522, `validate_epoch` can fail due to `safe_epoch > read_epoch`. This is caused by forgetting to update the epoch used for reads in state table when there is nothing to flush in agg executor.
This PR introduces a quick fix by calling `commit_no_data_expected` when there is nothing to flush on seeing a barrier in agg executor. I also checked other stateful executors' implementation and confirmed that the agg executor is the only victim. No changes need to be made to other executors.
If your pull request contains user-facing changes, please specify the types of the changes, …
=> fix(state_table): call commit_no_data_expected on state table even with nothing to flush

src/frontend/src/scheduler/hummock_snapshot_manager.rs
Prior to this PR, frontend will never unpin snapshot after `notify_epoch_assigned_for_queries` is called on empty batches, which causes compaction to fail to delete any stale key-value entries.
This PR fixes #5418.
* Other …
=> fix(frontend): fix unpin_snapshot_before in HummockSnapshotManager

proto/hummock.proto, src/ctl/src/cmd_impl/hummock/list_kv.rs, src/ctl/src/cmd_impl/hummock/list_version.rs, src/ctl/src/cmd_impl/hummock/sst_dump.rs, src/ctl/src/lib.rs, src/meta/src/hummock/manager/versioning.rs, src/meta/src/rpc/service/hummock_service.rs, src/rpc_client/src/meta_client.rs
Add list_pinned_versions and list_pinned_snapshots command for risectl.
Sample output
./risedev ctl hummock list-pinned-versions 
```
Worker 1 type 2 min_pinned_version_id 208
Worker 2 type 2 min_pinned_version_id 208
Worker 3 type 2 min_pinned_version_id 208
```
./risedev ctl hummock list-pinned-snapshots
```
Worker 4 type 1 min_pinned_snapshot 3060628331102208
```
Please keep the types …
=> feat(ctl): list pinned hummock versions and snapshots

src/storage/src/hummock/store/event_handler.rs, src/storage/src/hummock/store/state_store.rs, src/storage/src/hummock/store/version.rs
remove order_index of staging
-  remove order_index of staging
-  maintain the Mutex of ReadVersion instead of StorageCore
=> refactor(storage): remove order_index of staging

src/storage/src/table/streaming_table/mem_table.rs, src/storage/src/table/streaming_table/state_table.rs, src/stream/src/executor/managed_state/aggregation/value.rs
Previously I attempted to add `upsert` in #5191 to get rid of `flush` and `is_dirty` of managed agg states, but the benchmark result showed a degradation. According discussions in #3885 and #3893, I think it's still worth adding this method to make the semantics clean, also to allow enabling sanity check in simple/hash agg.
=> feat(state_table): add `upsert` method for `StateTable` to make the semantics clean

.cargo/config.toml, src/frontend/src/optimizer/heuristic.rs, src/frontend/src/optimizer/plan_node/logical_multi_join.rs, src/storage/src/hummock/store/event_handler.rs, src/storage/src/hummock/store/memtable.rs, src/storage/src/hummock/store/mod.rs, src/storage/src/hummock/store/state_store.rs, src/storage/src/hummock/store/version.rs, src/storage/src/store_impl.rs, src/stream/src/executor/managed_state/dynamic_filter.rs, src/tests/regress/src/lib.rs, src/utils/pgwire/src/pg_protocol.rs
[`forbit`](https://doc.rust-lang.org/rustc/lints/levels.html#forbid) level means `deny`+ *can not be overridden*,
which will forbid `#[allow(unused)]` 😄
=> chore: set unused_must_use's lint level to Forbid

src/stream/src/executor/source/reader.rs
Pausing the source stream can be achieved by only polling the other future.
=> refactor(stream): simplify pause stream

src/connector/src/source/filesystem/s3/source/s3_file_reader.rs
remove some redundant clone in `src/connector/src/source/filesystem/s3/source/s3_file_reader.rs`.
=> refactor(connector): remove redundant clone

.gitattributes
As title. The semantics of `vendored` and `generated` are explained [here](https://github.com/github/linguist/blob/f3f5de6288cd7b09eabc5a3b26df9c13add5a2bc/docs/overrides.md).
- #5155
=> chore: exclude generated & vendored files in linguist

src/batch/src/executor/hash_agg.rs, src/batch/src/executor/join/hash_join.rs, src/batch/src/executor/join/lookup_join.rs, src/common/src/hash/dispatcher.rs, src/common/src/hash/key.rs, src/stream/src/from_proto/hash_agg.rs, src/stream/src/from_proto/hash_join.rs
1. replace `Input` with `Self`
2. Hide `calc_hash_key_kind`
=> refactor: simplify HashKeyDispatcher

src/ctl/src/cmd_impl/hummock/list_kv.rs, src/ctl/src/lib.rs, src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs, src/storage/hummock_test/src/compactor_tests.rs, src/storage/hummock_test/src/state_store_tests.rs, src/storage/src/hummock/local_version/pinned_version.rs, src/storage/src/hummock/state_store.rs, src/storage/src/store.rs, src/storage/src/table/batch_table/storage_table.rs, src/storage/src/table/streaming_table/state_table.rs
as title
- remove`Option` of `CompactionGroupId` in function levels
- remove risectl list-kv with None table_id
- fix unit-test
- https://github.com/risingwavelabs/risingwave/pull/5620
=> refactor(storage): remove the Option of CompactionGroupId in function levels

proto/catalog.proto, src/frontend/src/catalog/pg_catalog/mod.rs, src/frontend/src/catalog/pg_catalog/pg_matviews_info.rs, src/frontend/src/catalog/table_catalog.rs, src/frontend/src/handler/create_mv.rs, src/frontend/src/handler/create_table.rs, src/frontend/src/optimizer/mod.rs, src/frontend/src/optimizer/plan_node/stream_materialize.rs, src/frontend/src/optimizer/plan_node/utils.rs, src/storage/hummock_sdk/src/filter_key_extractor.rs
as title.
```
dev=> select matviewname, definition from pg_catalog.pg_matviews_info;
-[ RECORD 1 ]-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
matviewname | nexmark_q7
definition  | SELECT B.auction, B.price, B.bidder, B.date_time FROM bid AS B JOIN (SELECT MAX(price) AS maxprice, window_end AS date_time FROM TUMBLE(bid, date_time, INTERVAL '10' SECOND) GROUP BY …
```
=> feat: add definition column for pg_matviews_info

src/source/src/parser/avro_parser.rs, src/source/src/test_data/complex-schema.avsc
- fix bug in parsing avro datetime which will cause panic when convert to nano_secs also 
- fix the complex-schema example.
=> fix(source): fix parse avro datetime

src/compute/src/server.rs, src/meta/src/hummock/compactor_manager.rs, src/storage/compactor/src/server.rs, src/storage/hummock_test/src/compactor_tests.rs, src/storage/src/hummock/compactor/compactor_runner.rs, src/storage/src/hummock/compactor/context.rs, src/storage/src/hummock/compactor/mod.rs, src/storage/src/hummock/compactor/task_progress.rs, src/storage/src/hummock/shared_buffer/shared_buffer_uploader.rs, src/storage/src/hummock/sstable/multi_builder.rs
The changes are as follows:
- Move task progress related structs to another file
- Use atomic variables for `num_ssts_sealed/uploaded`. The map has to be modified in `compaction_executor`'s tasks, so the `Mutex` cannot be removed.
- Use a guard to make sure the `TaskProgress` is removed from the `HashMap` in a case where a task finishes with an error and `on_task_complete` is not called.
- Change when to create/remove `TaskProgress`: 
- create: Originally it is created when the first sst is sealed. However, it is not semantically right - the progress should start from zero.
- remove: Originally it is removed when a split …
=> refactor(compaction): reduce the usage of mutex in task progress tracking

.cargo/config.toml, dashboard/lib/streamPlan/parser.js, src/meta/src/dashboard/index.html, src/storage/src/hummock/file_cache/store.rs
closes #5652
The format was already corrected by #5651
By the way, fixed a display error in dashboard
None
#5652
=> fix: fix clippy options (rustflags)

src/batch/src/executor/hop_window.rs, src/batch/src/executor/join/hash_join.rs, src/batch/src/executor/join/lookup_join.rs, src/batch/src/executor/join/nested_loop_join.rs, src/expr/src/expr/build_expr_from_prost.rs, src/expr/src/expr/expr_binary_nonnull.rs, src/expr/src/expr/expr_binary_nullable.rs, src/expr/src/expr/expr_case.rs, src/expr/src/vector_op/agg/filter.rs, src/stream/src/executor/dynamic_filter.rs, src/stream/src/executor/filter.rs, src/stream/src/executor/hash_join.rs, src/stream/src/executor/hop_window.rs, src/stream/src/executor/project.rs, src/stream/src/executor/project_set.rs
As title. `expr_unary` is already doing this. In most cases frontend should capture such invalid exprs that fail to build. But in case there is a discrepancy, or when the frontend code of a new expr is merged before backend impl, this can reduce the chance of a panic.
=> fix(expr): replace `unimplemented` panic with Err

risedev.yml
File cache doesn't cleanup disk on restart which is fine. But when we use in-mem meta store in risedev-bench, each restart results a new DB instance, but CN still uses old file cache, which causes #5587, #5609 and #5614. 
Details in https://github.com/risingwavelabs/risingwave/issues/5587#issuecomment-1263486972
Let's disable it for now, or shall we 
- clean up file cache during risedev-bench deployment flow, e.g. --force-recreate?
- clean up file cache during rw process start?
~~- [ ] All checks passed in …
=> chore(risedev): disable tier-cached

src/storage/src/hummock/store/state_store.rs
- remove unused imports while test feature is not enabled 
I am confused that why clippy doesn't complain about these.
=> style: remove unused imports while test feature is not enabled

src/common/src/array/data_chunk_iter.rs, src/storage/src/row_serde/row_serde_util.rs, src/storage/src/table/mod.rs, src/storage/src/table/streaming_table/mem_table.rs, src/storage/src/table/streaming_table/state_table.rs
1. Improved error messages of sanity check in StateTable #5524
2. By the way, refactored the StateTable to replace `streaming_deserialize()` to `RowDeserializer`
None
Closes #5524
=> refactor: improve sanity check error message

src/storage/src/row_serde/mod.rs, src/storage/src/row_serde/row_serde_util.rs, src/storage/src/table/batch_table/storage_table.rs
- Move the logic of mapping columns to struct `ColumnMapping`
- Simplify `ColumnMapping` and move these `ColumnDesc` stuff to the outside.
None
None
=> refactor: remove `batch_deserialize` in stata table

proto/stream_plan.proto, proto/stream_service.proto, src/batch/src/executor/delete.rs, src/batch/src/executor/insert.rs, src/batch/src/executor/update.rs, src/common/src/util/prost.rs, src/compute/src/rpc/service/stream_service.rs, src/compute/tests/integration_tests.rs, src/frontend/src/catalog/root_catalog.rs, src/frontend/src/catalog/schema_catalog.rs, src/frontend/src/catalog/source_catalog.rs, src/frontend/src/handler/drop_source.rs, src/frontend/src/handler/drop_table.rs, src/frontend/src/optimizer/plan_node/stream_source.rs, src/meta/src/barrier/recovery.rs, src/meta/src/stream/scale.rs, src/meta/src/stream/source_manager.rs, src/meta/src/stream/stream_manager.rs, src/meta/src/stream/test_fragmenter.rs, src/rpc_client/src/stream_client.rs, src/source/src/lib.rs, src/source/src/manager.rs, src/source/src/table.rs, src/stream/src/executor/source/source_executor.rs, src/stream/src/from_proto/source.rs
we wrap source info into SourceNode, so that SourceExecutorBuilder can build stream source without local source manager. By this way, we can avoid calling create_souce rpc of CNs when creating a new stream source. 
- Add SourceDescBuilder to avoid using local source manager in SouceExecutor and SourceExecutorBuilder
- compute: remove create_source/sync_source rpc
- meta: avoid sending create_source request to CN when doing create_source
- meta: avoid sending sync_sources request to CN when doing recovery
- source: remove create_source/create_table_source in SourceManager
- fix unit-tests
Please explain **IN DETAIL** what …
=> refactor: remove create_source/sync_source rpc in CN(#5269)

Cargo.lock, src/bench/Cargo.toml, src/tests/regress/Cargo.toml, src/tests/sqlsmith/Cargo.toml, src/utils/runtime/Cargo.toml, src/workspace-hack/Cargo.toml
`ansi_term` is unmaintained
Fixes #5421
=> chore(deps): bump tracing-subscriber and use nu-ansi-term

src/meta/src/rpc/server.rs, src/meta/src/rpc/service/ddl_service.rs, src/meta/src/rpc/service/scale_service.rs
This PR removes the DDL lock from meta. This is introduced to avoid corrupting the running state when manually pausing or resuming the sources. As we support scaling now, the `pause` and `resume` will rarely be called by ourselves, so there's no need to have this. Besides, the naming of "ddl lock" gives a misconception of the DDL service body executing sequentially.
- #3471
=> refactor(meta): remove ddl lock for scaling
