risingwavelabs/risingwave

- Makefile.toml
- risedev.yml
- src/risedevtool/src/bin/risedev-config.rs
Received several inquiries about "why I enabled the component in configure but it is not started???" recently, so I added a line of text to ask users to modify cluster config.
> chore(risedev): ask users to modify cluster config

- .github/ISSUE_TEMPLATE/config.yml
As title. We prefer to use issue to track bugs and features.
> community: add discussions and community chat in issue template

- e2e_test/v2/batch_distributed/tpch.slt
> test: Add tpch q6 for batch distributed query

- src/source/src/manager.rs
I've missed some comments in #1660, fix in this pr 
#1660
> fix(source): fix previously omitted review

- docs/data-model-and-encoding.md
- docs/meta-service.md
- docs/mv-on-mv.md
- docs/state-store-overview.md
- docs/streaming-overview.md
Do proofreading and tweak some details of dev docs.
> chore(docs): Tweak some details of dev docs

- src/risedevtool/src/config/service_config.rs
> fix(risedev): forbid unused parameters in config

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/development-task.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/labeler.yml
> chore: Add grouping to issue labels.

- src/common/src/array/column.rs
- src/common/src/array/macros.rs
- src/common/src/array/stream_chunk.rs
- src/common/src/array/stream_chunk_iter.rs
- src/common/src/test_utils/mod.rs
- src/common/src/test_utils/test_stream_chunk.rs
- src/stream/src/executor_v2/hop_window.rs
Not sure whether it will be better :(
> feat(stream): Introduce RowsIterV2

- .github/workflow-template/jobs/e2e-risedev.yml
- .github/workflows/main.yml
- .github/workflows/pull-request.yml
> test: Remove single batch test

- .github/workflow-template/jobs/e2e-risedev.yml
- .github/workflows/main.yml
- .github/workflows/pull-request.yml
- src/frontend/src/handler/dml.rs
- src/frontend/src/handler/mod.rs
- src/frontend/src/scheduler/query_manager.rs
- src/frontend/src/session.rs
> refactor: Remove single mode

- e2e_test/streaming/tpch/views/q9.slt.part
- e2e_test/v2/streaming/tpch_snapshot.slt
> feat(tpch): add streaming tpch-q9 e2e test tweak version

- src/connector/src/base.rs
- src/connector/src/filesystem/s3/source/s3_file_reader.rs
- src/connector/src/kafka/enumerator/client.rs
- src/connector/src/kafka/mod.rs
- src/connector/src/kafka/source/reader.rs
- src/connector/src/kinesis/config.rs
- src/connector/src/kinesis/source/reader.rs
- src/connector/src/pulsar/source/reader.rs
- src/connector/src/utils.rs
- src/source/src/manager.rs
Follow up of https://github.com/singularity-data/risingwave/pull/1833
> refactor(source): use Properties to simplify getting property

- src/common/src/hash/key.rs
- src/stream/src/executor_v2/batch_query.rs
> fix: compile error on main branch

- e2e_test/streaming/tpch/views/q8.slt.part
- e2e_test/v2/streaming/tpch_snapshot.slt
> feat(tpch): add streaming tpch-q8 e2e test tweak version

- src/frontend/src/binder/expr/mod.rs
- src/frontend/src/expr/function_call.rs
- src/frontend/src/expr/type_inference.rs
- src/frontend/test_runner/tests/testdata/tpch.yaml
support bind in expression. Successful plan tpch q12.
> feat(binder): bind `IN` expression.

- e2e_test/v2/streaming/tpch_snapshot.slt
> feat(e2e): add streaming tpch e2e test q12

- src/stream/src/executor_v2/hash_agg.rs
> refactor(streaming): implement HashAgg without AggExecutor

- Cargo.lock
- src/connector/Cargo.toml
- src/storage/Cargo.toml
> chore: bump dependencies

- src/batch/src/executor/create_table.rs
- src/batch/src/executor/delete.rs
- src/batch/src/executor/insert.rs
- src/compute/src/rpc/service/stream_service.rs
- src/connector/src/base.rs
- src/source/src/connector_source.rs
- src/source/src/lib.rs
- src/source/src/manager.rs
- src/stream/src/executor/source.rs
> refactor: remove old version create_source

- e2e_test/v2/batch/tpch.slt
- src/frontend/test_runner/tests/testdata/tpch.yaml
As title
ref https://github.com/singularity-data/risingwave/issues/1852
> feat: support TPC-H Q4 for batch

- src/frontend/src/optimizer/mod.rs
- src/frontend/src/optimizer/plan_node/stream_materialize.rs
- src/frontend/src/optimizer/plan_node/stream_table_scan.rs
- src/frontend/src/optimizer/property/distribution.rs
- src/frontend/test_runner/tests/testdata/basic_query_1.yaml
- src/frontend/test_runner/tests/testdata/basic_query_2.yaml
- src/frontend/test_runner/tests/testdata/join.yaml
- src/frontend/test_runner/tests/testdata/mv_on_mv.yaml
- src/frontend/test_runner/tests/testdata/stream_proto.yaml
- src/frontend/test_runner/tests/testdata/struct_query.yaml
materialize's dist should satisfies pk
or there might be multi executor write same pk
revert https://github.com/singularity-data/risingwave/pull/1653
> fix(optimizer): materialize's dist should satisfies pk

- src/batch/src/executor/executor2_wrapper.rs
> refactor(batch): Fix comments in last refactor.

- .github/workflow-template/jobs/e2e-risedev.yml
- .github/workflows/main.yml
- .github/workflows/pull-request.yml
> fix: revert ci timeout to previous value

- Cargo.lock
- src/risedevtool/Cargo.toml
- src/risedevtool/src/bin/risedev-playground.rs
- src/risedevtool/src/lib.rs
- src/risedevtool/src/task.rs
- src/risedevtool/src/task/kafka_service.rs
- src/risedevtool/src/task/task_kafka_ready_check.rs
- src/risedevtool/src/task/zookeeper_service.rs
- src/risedevtool/src/wait.rs
Ensure Kafka is ready using Kafka's API instead of wait for TCP.
close https://github.com/singularity-data/risingwave/issues/1996
> feat(risedev): ensure kafka is ready using API

- .github/workflow-template/jobs/compute-node-build.yml
- .github/workflows/main.yml
- .github/workflows/pull-request.yml
- CONTRIBUTING.md
- Cargo.lock
- Cargo.toml
- Makefile.toml
- src/README.md
- src/cmd/src/bin/compute_node.rs
- src/cmd/src/bin/ctl.rs
- src/cmd/src/bin/frontend_node.rs
- src/cmd/src/bin/meta_node.rs
- src/cmd_all/Cargo.toml
- src/cmd_all/src/bin/risingwave.rs
As title. Also split all-in-one and ordinary binaries into two crates, so that switching between modes won't cause rebuild.
> chore(ci): only build necessary components

- src/frontend/src/optimizer/rule/filter_join.rs
- src/frontend/test_runner/tests/testdata/tpch.yaml
As what #1951 said, some predicates lost during the optimization. I found this bug is due to wrongly concatenating two`Option<Condition>`. This pr fix this problem.
close #1951
> fix(frontend): fix a bug that could lead to predicates loss.

- src/batch/src/executor/delete.rs
- src/batch/src/executor/insert.rs
- src/source/src/connector_source.rs
- src/source/src/lib.rs
- src/source/src/table_v2.rs
> refactor: remove open from StreamSourceReader

- e2e_test/v2/streaming/tpch_snapshot.slt
- e2e_test/v2/streaming/tpch_upstream.slt
> feat(tpch): add streaming e2e tpchq14 test

- .github/workflows/main-cron.yml
fix misc check
introduced in #2003
> fix(CI): fix misc check

- proto/stream_plan.proto
- src/frontend/src/optimizer/plan_node/stream_table_scan.rs
- src/stream/src/executor/chain.rs
- src/stream/src/executor_v2/mod.rs
- src/stream/src/executor_v2/v1_compat.rs
> chore(streaming): enable original chain executor

- docker/README.md
- docker/docker-compose.yml
Fix command of start compute node.
Add redpanda service.
#1606
> chore(docker): add redpanda for docker compose

- src/batch/src/executor/join/nested_loop_join.rs
- src/batch/src/executor/join/sort_merge_join.rs
- src/batch/src/executor/mod.rs
- src/batch/src/executor/test_utils.rs
- src/batch/src/executor2/hash_agg.rs
- src/batch/src/executor2/mod.rs
- src/batch/src/lib.rs
- use futures-async-stream to implement batch hash agg
- update unit tests
close #1936
> refactor(batch): use futures-async-stream to implement hash agg

- src/meta/src/stream/stream_manager.rs
to eliminate the too many args
follow up to https://github.com/singularity-data/risingwave/pull/2080
> refactor: make resolve_chain_node_inner nested

- .github/workflow-template/jobs/misc-check.yml
- .github/workflows/main-cron.yml
- .github/workflows/main.yml
- .github/workflows/pull-request.yml
- CONTRIBUTING.md
- proto/batch_plan.proto
- proto/catalog.proto
- proto/data.proto
- proto/ddl_service.proto
- proto/expr.proto
- proto/hummock.proto
- proto/meta.proto
- proto/plan_common.proto
- proto/stream_plan.proto
- proto/stream_service.proto
- proto/task_service.proto
prototool is not maintained, switch to buf.
Close #2008
> chore: fully retire prototool

- src/stream/src/executor/hash_agg.rs
> fix(hash-agg): make hash agg shared states (executor id -> operator id)

- src/batch/src/executor/merge_sort_exchange.rs
- src/batch/src/executor/mod.rs
- src/batch/src/executor2/generic_exchange.rs
- src/batch/src/executor2/mod.rs
Implement GenericExchange using the Executor2 trait.
close https://github.com/singularity-data/risingwave/issues/1935
> refactor(batch): Use futures-async-stream to implement GenericExchange executor

- e2e_test/v2/batch/tpch.slt
- e2e_test/v2/streaming/tpch_snapshot.slt
- e2e_test/v2/streaming/tpch_upstream.slt
> test: enable q3 and q10 e2e tests

- src/common/src/config.rs
As title
close https://github.com/singularity-data/risingwave/issues/2112
> chore(cmd): ban undefined options

- e2e_test/batch/tpch/q11.slt.part
- e2e_test/v2/batch/order_by.slt
- e2e_test/v2/streaming/order_by.slt
- proto/batch_plan.proto
- src/batch/src/executor2/top_n.rs
- src/common/src/array/data_chunk.rs
- src/common/src/util/sort_util.rs
- src/frontend/src/optimizer/plan_node/batch_topn.rs
> feat(batch): support `offset` in batch TopN executor

- risedev.yml
- src/meta/src/barrier/mod.rs
- src/meta/src/lib.rs
- src/meta/src/manager/env.rs
- src/meta/src/stream/stream_manager.rs
- src/risedevtool/src/service_config.rs
- src/risedevtool/src/task/meta_node_service.rs
> feat(meta): make checkpoint interval configurable

- src/storage/src/hummock/sstable/builder.rs
- src/storage/src/hummock/sstable/mod.rs
- src/storage/src/hummock/value.rs
add value meta bitmap into sst meta
> feat(storage): add value meta bitmap into sst meta

- src/frontend/src/scheduler/execution/query.rs
- src/frontend/src/scheduler/execution/stage.rs
- src/frontend/src/scheduler/plan_fragmenter.rs
Fix the problem of stage scheduling failed and frontend hangs problem.
Closes #2179 .
> fix(batch): Fix stage schedule failed hang problem

- e2e_test/v2/streaming/index.slt
- proto/catalog.proto
- src/common/src/catalog/physical_table.rs
- src/frontend/src/catalog/table_catalog.rs
- src/frontend/src/optimizer/plan_node/logical_scan.rs
- src/frontend/src/optimizer/plan_node/stream_materialize.rs
- src/frontend/src/optimizer/plan_node/stream_table_scan.rs
- src/frontend/src/optimizer/rule/index_delta_join.rs
- src/frontend/src/scheduler/execution/query.rs
- src/frontend/src/scheduler/plan_fragmenter.rs
- src/frontend/test_runner/tests/testdata/index.yaml
- src/frontend/test_runner/tests/testdata/order_by.yaml
- src/frontend/test_runner/tests/testdata/stream_proto.yaml
- src/frontend/test_runner/tests/testdata/tpch.yaml
The distribution should now be correct, though the select statement doesn't produce result. Will fix bugs later.
close https://github.com/singularity-data/risingwave/issues/2099
> feat(frontend): do not include order keys in materialize pk

- Cargo.lock
> fix(test): Update cargo.lock to resolve security problem

- src/batch/src/executor2/join/mod.rs
> fix: Missing license header

- src/meta/src/dashboard/mod.rs
- src/meta/src/rpc/server.rs
> chore(dashboard): remove test data for frontend

- src/storage/src/hummock/state_store.rs
> fix(state-store): use user key to compare in binary table search.

- .github/workflow-template/jobs/release.yml
- .github/workflows/main.yml
- Cargo.lock
- README.md
- src/batch/Cargo.toml
- src/cmd/Cargo.toml
- src/cmd_all/Cargo.toml
- src/common/Cargo.toml
- src/compute/Cargo.toml
- src/connector/Cargo.toml
- src/ctl/Cargo.toml
- src/expr/Cargo.toml
- src/frontend/Cargo.toml
- src/meta/Cargo.toml
- src/risedevtool/Cargo.toml
- src/rpc_client/Cargo.toml
- src/source/Cargo.toml
- src/sqlparser/Cargo.toml
- src/storage/Cargo.toml
- src/stream/Cargo.toml
> release: v0.1.6

- README.md
Happy holiday!
due to https://github.com/singularity-data/risingwave/issues/2249
> docs: revert v0.1.6 release

- README.md
As title. I've tagged v0.1.6 release again. Bugs of playground should be fixed.
> docs: re-release v0.1.6

- src/common/src/util/ordered/serde.rs
- src/storage/src/cell_based_row_serializer.rs
- src/storage/src/table/cell_based_table.rs
Next Plan: Need to think about how to re-use and simplify relational-table related API
> refactor(relational-table): support serialize pk only

- e2e_test/v2/batch/aggregate/distinct.slt
- src/frontend/src/planner/select.rs
- src/frontend/test_runner/tests/testdata/agg.yaml
> feat(planner): support SELECT DISTINCT

- src/frontend/test_runner/README.md
- src/frontend/test_runner/planner_test.toml
```
./risedev run-planner-test <yaml file name>
./risedev run-planner-test tpch # Run tpch.yaml
./risedev run-planner-test # Run all tests
```
> chore(frontend): add run-planner-test for risedev

- e2e_test/v2/batch/aggregate/count.slt
- src/frontend/src/binder/expr/function.rs
- src/frontend/src/expr/agg_call.rs
- src/frontend/src/expr/expr_rewriter.rs
- src/frontend/src/expr/mod.rs
- src/frontend/src/optimizer/plan_node/logical_agg.rs
As title. We just need to pass the boolean from parser all the way down to protobuf.
> feat(frontend): support distinct within agg call

- src/storage/src/hummock/state_store.rs
- src/storage/src/hummock/utils.rs
Signed-off-by: Zulai Wang <zl31wang@gmail.com>
As title.
Close #2123
> feat(storage): use binary search to locate SST iterators

- docker/Dockerfile
> feat(docker): add compactor and single binary into dockerfile

- src/connector/Cargo.toml
- src/connector/src/base.rs
- src/connector/src/lib.rs
- src/connector/src/nexmark/config.rs
- src/connector/src/nexmark/enumerator/mod.rs
- src/connector/src/nexmark/mod.rs
- src/connector/src/nexmark/source/event.rs
- src/connector/src/nexmark/source/generator.rs
- src/connector/src/nexmark/source/message.rs
- src/connector/src/nexmark/source/mod.rs
- src/connector/src/nexmark/source/reader.rs
- src/connector/src/nexmark/split.rs
- src/connector/src/utils.rs
- src/expr/src/vector_op/cast.rs
- src/source/src/lib.rs
- src/source/src/manager.rs
- src/source/src/parser/common.rs
- src/source/src/parser/json_parser.rs
- src/source/src/parser/protobuf_parser.rs
Add the nexmark generator as source
#2291
> feat(source): Add nexmark as source connector

- e2e_test/v2/streaming/time_window.slt
Hop will be added later, blocked on #2320
> test: add aggregation tests for tumble window

- src/batch/src/executor2/sort_agg.rs
- src/expr/src/vector_op/agg/aggregator.rs
- src/expr/src/vector_op/agg/count_star.rs
- src/expr/src/vector_op/agg/general_agg.rs
- src/expr/src/vector_op/agg/general_distinct_agg.rs
- src/expr/src/vector_op/agg/general_sorted_grouper.rs
Remove the next chunk offset returned by aggregator for sort agg
previous PR #2084
> refactor(batch): refine sort agg

- proto/hummock.proto
- src/meta/src/hummock/compaction/tier_compaction_picker.rs
- src/meta/src/hummock/level_handler.rs
- src/meta/src/hummock/test_utils.rs
- src/storage/src/hummock/compactor.rs
- src/storage/src/hummock/local_version_manager.rs
- src/storage/src/hummock/shared_buffer/shared_buffer_uploader.rs
- src/storage/src/hummock/sstable/builder.rs
- src/storage/src/hummock/sstable/mod.rs
- src/storage/src/hummock/sstable/multi_builder.rs
- src/storage/src/hummock/test_utils.rs
> feat(bitmap): store bitmap in meta store

- src/common/src/util/ordered/serde.rs
- src/storage/src/cell_based_row_deserializer.rs
- src/storage/src/cell_based_row_serializer.rs
- src/storage/src/table/cell_based_table.rs
- src/stream/src/executor/managed_state/top_n/top_n_bottom_n_state.rs
- src/stream/src/executor/managed_state/top_n/top_n_state.rs
- src/stream/src/executor/mview/state.rs
Large refactor. The code is easier to read. Two batch writes are merged into one. No need to merge insert/delete.
close https://github.com/singularity-data/risingwave/issues/2336
> refactor(storage): better cell based table serialization

- e2e_test/v2/batch/tpch.slt
> e2e(batch): open more tpch batch e2e test

- e2e_test/v2/streaming/time_window.slt
> test: add aggregation tests for hop window

- src/frontend/src/optimizer/plan_node/batch_delete.rs
- src/frontend/src/optimizer/plan_node/batch_exchange.rs
- src/frontend/src/optimizer/plan_node/batch_filter.rs
- src/frontend/src/optimizer/plan_node/batch_hash_agg.rs
- src/frontend/src/optimizer/plan_node/batch_hash_join.rs
- src/frontend/src/optimizer/plan_node/batch_hop_window.rs
- src/frontend/src/optimizer/plan_node/batch_insert.rs
- src/frontend/src/optimizer/plan_node/batch_limit.rs
- src/frontend/src/optimizer/plan_node/batch_project.rs
- src/frontend/src/optimizer/plan_node/batch_seq_scan.rs
- src/frontend/src/optimizer/plan_node/batch_simple_agg.rs
- src/frontend/src/optimizer/plan_node/batch_sort.rs
- src/frontend/src/optimizer/plan_node/batch_topn.rs
- src/frontend/src/optimizer/plan_node/batch_values.rs
- src/frontend/src/optimizer/plan_node/convert.rs
- src/frontend/src/optimizer/plan_node/mod.rs
> feat: Add `to_local` method to generate local execution lan

- src/storage/hummock_sdk/src/key.rs
- src/storage/src/hummock/sstable/builder.rs
- src/storage/src/hummock/state_store.rs
- src/storage/src/hummock/state_store_tests.rs
- src/storage/src/hummock/utils.rs
make get_key use vnode bitmap filter
> perf(storage): make get_key use vnode bitmap filter

- src/storage/src/hummock/sstable/group_builder.rs
fix main
make caller(builder) call get_table_id with new interface
> fix(builder): make caller(builder) call get_table_id with new interface

- .github/workflows/license_check.yml
> chore(ci): enable license checker for forks

- src/storage/src/hummock/cache.rs
In this PR, we fix a bug when release the handle of a stale value. 
Currently when we release a handle, we remove it from the hash table without checking whether it is still the latest value of the key. Under current code, if we follow operation below, something unexpected will happen.
```
set k, v1
handle_v1 = get k
set k, v2
release handle_v1
get k == null // Unexpected, we should be able to get v2
```
The newly added unit test `test_release_stale_value` has covered such case. The case will fail in the original code.
> fix(lru cache): fix a bug when releasing the handle of a stale value

- src/meta/src/hummock/compaction/mod.rs
- src/meta/src/hummock/compaction/tier_compaction_picker.rs
- src/meta/src/hummock/mod.rs
https://github.com/singularity-data/risingwave/pull/2242 has left some problem and may cause CI fail. This PR optimizes the performance of get_compact_task and report_compact_task
> feat(compaction) optimize performance when trigger and apply compaction

- src/storage/src/hummock/sstable/group_builder.rs
> test(compaction): re-enable ignored test

- src/connector/src/base.rs
> fix(connector): kinesis impl is mismatched to pulsar

- Makefile.toml
> chore: commands to clear/start dev cluster with kafka

- .github/workflow-template/jobs/e2e-risedev.yml
- .github/workflows/main-cron.yml
- .github/workflows/main.yml
- .github/workflows/pull-request.yml
- e2e_test/v2/streaming/tpch_snapshot.slt
- e2e_test/v2/streaming/tpch_upstream.slt
Main CI failing on this. Fix the bug later.
> test(streaming): disable tpch q20 and increase timeout limit

- e2e_test/v2/streaming/tpch_snapshot.slt
- e2e_test/v2/streaming/tpch_upstream.slt
Remove left semi join related tpch since they might stuck.
> test(streaming): disable tpch q4 q18

- e2e_test/v2/batch/tpch.slt
- src/frontend/src/optimizer/plan_node/batch_nested_loop_join.rs
- src/frontend/src/optimizer/plan_node/logical_join.rs
- src/frontend/src/optimizer/plan_node/mod.rs
- src/frontend/src/utils/condition.rs
- src/frontend/test_runner/tests/testdata/join.yaml
- src/frontend/test_runner/tests/testdata/tpch.yaml
- Support batch nested-loop join
- Enable TPC-H Q11 in E2E and UT
closes #1862
> feat(frontend): support batch nested-loop join and enable TPCH Q11

- src/frontend/src/utils/condition.rs
- src/frontend/test_runner/tests/testdata/join.yaml
- src/frontend/test_runner/tests/testdata/subquery.yaml
- src/frontend/test_runner/tests/testdata/subquery_expr.yaml
- src/frontend/test_runner/tests/testdata/subquery_expr_correlated.yaml
- src/frontend/test_runner/tests/testdata/tpch.yaml
as title.
Conjunction of 0 predicates should be `true`, instead of `always`.
None
> fix: explain result: replace `always` to `true`

- src/frontend/src/optimizer/plan_node/logical_join.rs
> fix: don't panic if stream nested-loop join is inevitable

- src/frontend/src/optimizer/plan_node/batch_hash_join.rs
- add non-equi condition in batch join ToBatchProst
Close #2468
Close #2462
> fix(frontend): add non-equi condition in batch join ToBatchProst

- src/frontend/src/optimizer/plan_node/eq_join_predicate.rs
- src/frontend/test_runner/tests/testdata/struct_query.yaml
- src/frontend/test_runner/tests/testdata/tpch.yaml
> fix(frontend): missing space before AND in explain

- e2e_test/v2/batch/types/decimal.slt
- src/frontend/src/binder/expr/function.rs
- src/frontend/test_runner/tests/testdata/expr.yaml
> fix(frontend): add implicit cast for round

- e2e_test/v2/batch/subquery.slt
- e2e_test/v2/batch/tpch.slt
- src/frontend/src/optimizer/rule/pull_up_correlated_predicate.rs
- src/frontend/test_runner/tests/testdata/tpch.yaml
> feat(frontend): remove the limitation of unnesting AntiApply.

- e2e_test/batch/aggregate/count.slt
- src/expr/src/vector_op/agg/aggregator.rs
- src/expr/src/vector_op/agg/general_agg.rs
- src/expr/src/vector_op/agg/general_sorted_grouper.rs
previously it's null
fix #2475
> fix: set initial result to 0 for count

- src/expr/src/expr/mod.rs
Signed-off-by: xyz <a997647204@gmail.com>
For binary expr, match arm is splited into three, we can merge them into one
> refactor(expr): merge build binary expr match arm

- src/frontend/src/binder/expr/mod.rs
- src/frontend/test_runner/tests/testdata/tpch.yaml
> feat(binder): support `substring(s [FROM start] [FOR count])`

- e2e_test/v2/streaming/tpch_snapshot.slt
- e2e_test/v2/streaming/tpch_upstream.slt
- enable tpch q4, q18, q20
Those are tested locally multiple times.
#2495 
Stuck problem likely fixed by #2447
> test(streaming): enable tpch q4, q18, q20

- Cargo.lock
- src/batch/Cargo.toml
- src/cmd/Cargo.toml
- src/cmd_all/Cargo.toml
- src/common/Cargo.toml
- src/compute/Cargo.toml
- src/connector/Cargo.toml
- src/ctl/Cargo.toml
- src/expr/Cargo.toml
- src/frontend/Cargo.toml
- src/meta/Cargo.toml
- src/risedevtool/Cargo.toml
- src/rpc_client/Cargo.toml
- src/source/Cargo.toml
- src/sqlparser/Cargo.toml
- src/storage/Cargo.toml
- src/stream/Cargo.toml
The last version that legacy frontend works.
> release: v0.1.7

- src/frontend/src/binder/expr/binary_op.rs
- src/frontend/src/binder/expr/mod.rs
... to improve readability.
~~- [ ] I have added necessary unit tests and integration tests~~ (Refactor does not break existing tests.)
> refactor(binder): organize bind_expr arms into groups

- .github/workflow-template/jobs/compute-node-test.yml
- .github/workflows/main-cron.yml
- .github/workflows/main.yml
- .github/workflows/pull-request.yml
cargo doc only builds the doc. Not test it.
ref #2504
> fix(ci): fix doc check

- src/common/src/error.rs
- src/frontend/src/config.rs
- src/frontend/src/handler/query.rs
- src/frontend/src/lib.rs
> feat: Add query_mode session config

- README.md
> docs: update for 0.1.7 release

- docs/state-store-overview.md
> docs: clearify HummockClient's location

- proto/meta.proto
- src/meta/src/barrier/recovery.rs
- src/meta/src/cluster/mod.rs
- src/meta/src/rpc/server.rs
- src/meta/src/rpc/service/stream_service.rs
As title.
Part of https://github.com/singularity-data/risingwave/issues/2539
> refactor(meta): remove some legacy frontend support in meta, including StreamServiceImpl

- e2e_test/v2/batch/tpch.slt
- src/batch/src/executor2/project.rs
- src/batch/src/task/hash_shuffle_channel.rs
We'd better compact DataChunk first if we want to manipulate something in it. 
Project should consider the case that zero columns with non-zero cardinality.
close #2486
> fix(batch): fix a bug of exchange and project.

- src/frontend/src/optimizer/rule/filter_join.rs
- src/frontend/test_runner/tests/testdata/join.yaml
- src/frontend/test_runner/tests/testdata/subquery_expr_correlated.yaml
- src/frontend/test_runner/tests/testdata/tpch.yaml
> fix(optimizer): predicate pushdown when there's no filter above join

- src/frontend/src/expr/agg_call.rs
- src/frontend/test_runner/tests/testdata/struct_query.yaml
This PR distinguishes unsupported agg-calls from invalid ones and makes it not panic on invalid arguments.
- Close #2464
> fix(frontend): check arguments for agg call

- src/connector/src/kafka/enumerator/client.rs
> fix: error returned when creating a source from a non-existent topic

- src/frontend/src/lib.rs
- src/frontend/src/scheduler/execution/query.rs
- src/frontend/src/scheduler/execution/stage.rs
- src/frontend/src/scheduler/mod.rs
- src/frontend/src/scheduler/plan_fragmenter.rs
> refactor(batch): Remove some dead code in scheduler.

- src/connector/src/base.rs
- src/source/src/connector_source.rs
> chore: add Column for connectors

- .github/ISSUE_TEMPLATE/design-rfc.md
> chore: add RFC template to issue templates

- .github/ISSUE_TEMPLATE/design-rfc.md
As title. The cuurent `design-rfc.md` doesn't work without the header... 
N/A
None
> chore: update design-rfc

- .gitignore
... so that they are not accidentally checked in.
> chore: ignore generated prost/sim files

- src/frontend/test_runner/tests/testdata/tpch.yaml
Test against `batch_plan` and `stream_plan` rather than `logical_plan`.
> test(frontend): update TPC-H Q16 planner test

- src/connector/src/base.rs
- src/connector/src/dummy_connector.rs
- src/connector/src/filesystem/s3/source/s3_file_reader.rs
- src/connector/src/kafka/enumerator/client.rs
- src/connector/src/kafka/source/reader.rs
- src/connector/src/kafka/split.rs
- src/connector/src/kinesis/enumerator/client.rs
- src/connector/src/kinesis/source/reader.rs
- src/connector/src/kinesis/split.rs
- src/connector/src/nexmark/enumerator/mod.rs
- src/connector/src/nexmark/source/reader.rs
- src/connector/src/nexmark/split.rs
- src/connector/src/properties.rs
- src/connector/src/pulsar/enumerator/client.rs
- src/connector/src/pulsar/source/reader.rs
- src/connector/src/pulsar/split.rs
- src/connector/src/state.rs
> chore(connector): Simplifying connector/base.rs with macro

- .github/pull_request_template.md
Add a reminder in the PR template about using the 'user-facing changes' label to indicate a PR contains user-facing changes.
- 
- [] I have written necessary docs and comments
- [] I have added necessary unit tests and integration tests
> chore: add a reminder about a new label

- e2e_test/batch/modify.slt
- proto/batch_plan.proto
- src/batch/src/executor/mod.rs
- src/batch/src/executor2/delete.rs
- src/batch/src/executor2/insert.rs
- src/batch/src/executor2/mod.rs
- src/batch/src/executor2/update.rs
- src/common/src/array/column.rs
- src/common/src/array/stream_chunk.rs
- src/frontend/src/optimizer/plan_node/batch_update.rs
- src/frontend/src/optimizer/plan_node/logical_update.rs
This PR implements update executor in compute node, so that we can execute `UPDATE` statements.
- Close #784
- Unresolved: #2672
> feat(batch): update executor

- src/connector/src/base.rs
- src/connector/src/dummy_connector.rs
- src/connector/src/filesystem/s3/source/s3_file_reader.rs
- src/connector/src/kafka/source/reader.rs
- src/connector/src/kinesis/source/reader.rs
- src/connector/src/nexmark/source/reader.rs
- src/connector/src/pulsar/source/reader.rs
> chore(connector): add columns for trait when creating split reader

- e2e_test/batch/types/array.slt
- proto/expr.proto
- src/common/src/array/list_array.rs
- src/common/src/array/mod.rs
- src/common/src/array/struct_array.rs
- src/common/src/types/mod.rs
- src/expr/src/expr/expr_array.rs
- src/expr/src/expr/expr_field.rs
- src/expr/src/expr/mod.rs
- src/frontend/src/binder/expr/mod.rs
- src/frontend/src/binder/expr/value.rs
- src/frontend/src/expr/mod.rs
- src/frontend/src/expr/type_inference.rs
- src/frontend/test_runner/tests/testdata/array.yaml
- src/sqlparser/src/ast/mod.rs
This PR implements the expression (function call) constructing an ARRAY.
> feat: support array expression

- src/frontend/src/session.rs
- src/frontend/src/test_utils.rs
- src/utils/pgwire/src/pg_message.rs
- src/utils/pgwire/src/pg_protocol.rs
- src/utils/pgwire/src/pg_server.rs
> refactor(pgwire): use generic for session manager

- .gitignore
Signed-off-by: d2lark <lichengamoy@gmail.com>
just ignore .gitpod.yml
- Add the 'user-facing changes' label if your PR contains changes that are visibile to users (optional)
> chore: ignore .gitpod.yml

- src/frontend/src/optimizer/mod.rs
- src/frontend/src/optimizer/plan_node/batch_delete.rs
- src/frontend/src/optimizer/plan_node/batch_filter.rs
- src/frontend/src/optimizer/plan_node/batch_hash_agg.rs
- src/frontend/src/optimizer/plan_node/batch_hash_join.rs
- src/frontend/src/optimizer/plan_node/batch_insert.rs
- src/frontend/src/optimizer/plan_node/batch_nested_loop_join.rs
- src/frontend/src/optimizer/plan_node/batch_project.rs
- src/frontend/src/optimizer/plan_node/batch_seq_scan.rs
- src/frontend/src/optimizer/plan_node/batch_simple_agg.rs
- src/frontend/src/optimizer/plan_node/batch_update.rs
- src/frontend/test_runner/src/lib.rs
- src/frontend/test_runner/tests/testdata/agg.yaml
- src/frontend/test_runner/tests/testdata/join.yaml
Add correct singleton distribution requirement in `to_local`.
> feat(batch): Add correct single distribution in `to_local`.

- .cargo/config.toml
- .github/workflow-template/jobs/compute-node-build.yml
- .github/workflows/main-cron.yml
- .github/workflows/main.yml
- .github/workflows/pull-request.yml
- docker/Dockerfile
As title, which might accelerate build.
> chore(build): use lld for linux

- .github/pull_request_template.md
- Add the 'user-facing changes' label if your PR contains changes that are visibile to users (optional)
> doc: fix a typo

- e2e_test/streaming/nexmark/create_views.slt.part
- e2e_test/streaming/nexmark/drop_views.slt.part
- e2e_test/streaming/nexmark/q4.slt.part
- e2e_test/streaming/nexmark/q5.slt.part
- e2e_test/streaming/nexmark/views/q4.slt.part
- e2e_test/streaming/nexmark/views/q5.slt.part
- e2e_test/streaming/nexmark_snapshot.slt
- e2e_test/streaming/nexmark_upstream.slt
- src/frontend/test_runner/tests/testdata/nexmark.yaml
Add nexmark q4 and q5 in e2e_test
> test: support nexmark q4 and q5

- docs/developer-guide.md
> doc: remove extra parentheses

- Makefile.toml
- src/risedevtool/src/bin/risedev-compose.rs
- src/risedevtool/src/compose_deploy.rs
When running apply-compose-deploy, the following message will be shown in console:
> feat(risedev): more message when deploy

- e2e_test/batch/cte.slt
add e2e tests for common table expressions.
> test(frontend): add e2e tests for common table expressions

- src/stream/src/executor/barrier_align.rs
- src/stream/src/executor/merge.rs
As title
close https://github.com/singularity-data/risingwave/issues/2841
> fix(streaming): fix biased aligner

- grafana/risingwave-dashboard.json
- src/risedevtool/src/bin/risedev-compose.rs
- src/stream/src/executor/actor.rs
- src/stream/src/executor/dispatch.rs
- src/stream/src/executor/integration_tests.rs
- src/stream/src/executor/managed_state/join/mod.rs
- src/stream/src/executor/merge.rs
- src/stream/src/executor/mod.rs
- src/stream/src/executor/monitor/streaming_stats.rs
- src/stream/src/executor/receiver.rs
- src/stream/src/from_proto/merge.rs
- src/stream/src/task/stream_manager.rs
* stream_actor_barrier_time: how long does it take for a barrier to flow from the receiver / merge node to the dispatcher node.
* stream_actor_process_time: how long does it take from the actor to receive the first chunk until the actor processes a barrier.
```
| process chunk | process chunk |   process barrier     |
<------      stream_actor_process_time            ------>
<---- barrier time ---->
```
> feat(metrics): add actor processing latency

- src/stream/src/executor/managed_state/top_n/top_n_state.rs
Sorry for merging the debug message by mistake.
> chore: remove redundant output

- docker/Dockerfile
- docker/aws/Dockerfile
Otherwise compute nodes won't be able to access S3.
> chore(build): bundle ca-certificates

- src/frontend/test_runner/README.md
- src/frontend/test_runner/planner_test.toml
- src/frontend/test_runner/tests/testdata/agg.yaml
- src/frontend/test_runner/tests/testdata/array.yaml
- src/frontend/test_runner/tests/testdata/basic_query.yaml
- src/frontend/test_runner/tests/testdata/column_pruning.yaml
- src/frontend/test_runner/tests/testdata/common_table_expressions.yaml
- src/frontend/test_runner/tests/testdata/distribution_derive.yaml
- src/frontend/test_runner/tests/testdata/expr.yaml
- src/frontend/test_runner/tests/testdata/index.yaml
- src/frontend/test_runner/tests/testdata/insert.yaml
- src/frontend/test_runner/tests/testdata/join.yaml
- src/frontend/test_runner/tests/testdata/limit.yaml
- src/frontend/test_runner/tests/testdata/mv_on_mv.yaml
- src/frontend/test_runner/tests/testdata/nexmark.yaml
- src/frontend/test_runner/tests/testdata/order_by.yaml
- src/frontend/test_runner/tests/testdata/pk_derive.yaml
- src/frontend/test_runner/tests/testdata/predicate_pushdown.yaml
- src/frontend/test_runner/tests/testdata/stream_proto.yaml
- src/frontend/test_runner/tests/testdata/struct_query.yaml
- src/frontend/test_runner/tests/testdata/subquery.yaml
- src/frontend/test_runner/tests/testdata/subquery_expr.yaml
- src/frontend/test_runner/tests/testdata/subquery_expr_correlated.yaml
- src/frontend/test_runner/tests/testdata/time_window.yaml
- src/frontend/test_runner/tests/testdata/tpch.yaml
- src/frontend/test_runner/tests/testdata/types.yaml
- src/frontend/test_runner/tests/testdata/update.yaml
add comments for running task `do-apply-planner-test` updated files for it is friendly for newcomers
> chore(frontend): comment for `do-apply-planner-test` updated files

- src/stream/src/executor/chain.rs
- src/stream/src/executor/global_simple_agg.rs
- src/stream/src/executor/hash_agg.rs
- src/stream/src/executor/mod.rs
- src/stream/src/executor/rearranged_chain.rs
- src/stream/src/executor/top_n_executor.rs
> refactor(streaming): extract the first barrier

- .github/workflows/docker_main.yml
- .github/workflows/docker_pr.yml
> chore(ci): tag docker image with nightly tags

- src/frontend/src/optimizer/plan_node/logical_hop_window.rs
- src/frontend/test_runner/tests/testdata/time_window.yaml
> fix(optimizer): fix col prune for logical hop

- README.md
- docker/README.md
- docker/aws/aws-build.sh
> chore(build): add --pull=always, more hint for AWS builds

- grafana/risingwave-dashboard.json
Otherwise Grafana will take a lot network traffic, and dashboard refresh would be slow :)
> chore(grafana): collapse actor metrics by default

- src/batch/src/executor/delete.rs
- src/batch/src/executor/generic_exchange.rs
- src/batch/src/executor/insert.rs
- src/batch/src/executor/merge_sort_exchange.rs
- src/batch/src/executor/mod.rs
- src/batch/src/executor/row_seq_scan.rs
- src/batch/src/executor/update.rs
Little refactor for executor builder.
> refactor(batch): Little refactor for executor builder

- e2e_test/source/basic_test.slt
> chore: try add source e2e test mv part back

- Cargo.lock
- e2e_test/batch/func.slt
- proto/expr.proto
- src/expr/Cargo.toml
- src/expr/src/expr/expr_unary.rs
- src/expr/src/expr/mod.rs
- src/expr/src/vector_op/md5.rs
- src/expr/src/vector_op/mod.rs
- src/frontend/src/binder/expr/function.rs
- src/frontend/src/expr/type_inference.rs
> feat(expr): add md5 expr

- .github/workflow-template/template.yml
- .github/workflows/main-cron.yml
- .github/workflows/main.yml
- .github/workflows/pull-request.yml
- Cargo.lock
- src/batch/Cargo.toml
- src/cmd/Cargo.toml
- src/cmd_all/Cargo.toml
- src/common/Cargo.toml
- src/compute/Cargo.toml
- src/connector/Cargo.toml
- src/expr/Cargo.toml
- src/frontend/Cargo.toml
- src/meta/Cargo.toml
- src/risedevtool/Cargo.toml
- src/risedevtool/src/bin/risedev-config.rs
- src/source/Cargo.toml
- src/storage/Cargo.toml
- src/stream/Cargo.toml
- src/workspace-hack/Cargo.toml
As title
Note: Failed to upgrade "protobuf = 3" due to serde_protobuf's dep.
> chore: dump all deps

- docs/data-source.md
> doc(source): update doc to catch up new design

- README.md
- docker/Dockerfile
- docker/README.md
- risedev.yml
- src/cmd_all/src/playground.rs
The `docker run playground` command now won't require host network mode.
> chore(cmd): allow listen 0.0.0.0 for playground

- src/batch/src/rpc/service/task_service.rs
- src/batch/src/task/task_manager.rs
- src/common/src/error.rs
- src/compute/src/rpc/service/exchange_service.rs
- src/compute/src/rpc/service/stream_service.rs
- src/meta/src/rpc/service/cluster_service.rs
- src/meta/src/rpc/service/ddl_service.rs
- src/meta/src/rpc/service/heartbeat_service.rs
- src/meta/src/rpc/service/notification_service.rs
- src/meta/src/rpc/service/stream_service.rs
Can just `?` instead of `map_err()`.
> refactor(error): impl From<RwError> to tonic::Status

- src/meta/src/stream/stream_graph.rs
> refactor: use `DispatchStrategy` in `StreamActorDownstream`

- src/meta/src/hummock/compaction/mod.rs
- src/meta/src/hummock/compaction/overlap_strategy.rs
- src/meta/src/hummock/compaction/tier_compaction_picker.rs
implement vnode-aware overlap in compaction excluding recursion
reference: https://singularity-data.quip.com/WpJXA1O4B82s#WeQABA76Lcn
> feat(vnode bitmap): implement vnode-aware overlap in compaction

- ci/scripts/docker.sh
- ci/workflows/docker.yml
migrate docker build pipeline from Github Action to Buildkite.
issue: https://github.com/singularity-data/risingwave/issues/2898
> chore(ci): migrate docker build pipeline

- src/compute/tests/integration_tests.rs
- src/connector/src/state.rs
- src/storage/src/keyspace.rs
- src/storage/src/table/test_relational_table.rs
- src/storage/src/write_batch.rs
- src/stream/src/executor/managed_state/aggregation/extreme.rs
- src/stream/src/executor/managed_state/join/join_entry_state.rs
- src/stream/src/executor/managed_state/top_n/top_n_bottom_n_state.rs
- src/stream/src/executor/managed_state/top_n/top_n_state.rs
- src/stream/src/executor/mview/test_utils.rs
- src/stream/src/executor/source.rs
- src/stream/src/executor/test_utils.rs
remove some unused code and fix test
- remove executor_root and shared_executor_root from keyspace.rs
- fix test about keyspace with keyspace::table_root
> fix(streaming): fix some test with keyspace::table_root

- Cargo.lock
- src/common/Cargo.toml
- src/connector/Cargo.toml
> chore(build): bump deps

- src/source/src/connector_source.rs
> fix(connector): use bound channel for source

- src/meta/src/manager/hash_mapping.rs
- src/meta/src/stream/scheduler.rs
notify meta when hash mapping changes
> feat(compaction): notify meta when hash mapping changes

- src/risedevtool/src/bin/risedev-playground.rs
> fix(risedev): specify username in playground hints

- ci/scripts/e2e-source-test.sh
- ci/scripts/e2e-test-parallel.sh
- ci/scripts/e2e-test.sh
- dashboard/README.md
- docs/developer-guide.md
- src/common/src/catalog/mod.rs
- src/meta/src/manager/user.rs
As title, this is for compatibility with customized utils for PostgreSQL. And for security reasons, we should support changing user passwords before production.
> feat: add default super user postgres

- e2e_test/database/test.slt
- e2e_test/ddl/database.slt
- e2e_test/ddl/privilege.slt
- e2e_test/ddl/schema.slt
- e2e_test/ddl/show.slt
- src/common/src/catalog/mod.rs
- src/frontend/src/handler/create_database.rs
- src/frontend/src/handler/drop_database.rs
As the title, achieve better compatibility with PostgreSQL.
> feat(frontend): change the default schema name to public

- e2e_test/batch/explain.slt
- src/frontend/src/handler/explain.rs
> feat(frontend): support explain create index

- src/meta/src/barrier/mod.rs
Introduced by #3129 and #3211. This leads to building failure on the main branch.
> fix(meta): compile error with rpc error

- src/batch/src/lib.rs
- src/common/src/lib.rs
- src/compute/src/lib.rs
- src/connector/src/lib.rs
- src/expr/src/lib.rs
- src/frontend/src/handler/describe.rs
- src/frontend/src/handler/mod.rs
- src/frontend/src/handler/query.rs
- src/frontend/src/handler/show.rs
- src/frontend/src/lib.rs
- src/meta/src/lib.rs
- src/rpc_client/src/lib.rs
- src/source/src/lib.rs
- src/source/src/parser/avro_parser.rs
- src/storage/compactor/src/lib.rs
- src/storage/src/hummock/shared_buffer/mod.rs
- src/storage/src/lib.rs
- src/stream/src/executor/lookup/tests.rs
- src/stream/src/lib.rs
- src/tests/regress/src/lib.rs
> chore: enable unused_async clippy lint

- ci/docker-compose.yml
> feat(ci): bump sqllogictest to v0.5.1

- src/stream/src/executor/hop_window.rs
No idea why it caused the issue, anyway, don't hack the compiler 😇🥵
possibly fix https://github.com/singularity-data/risingwave/issues/3266, but still unknown of root cause.
> fix(streaming): fix possible ub in hop executor

- e2e_test/streaming/append_only.slt
> test(streaming): add basic e2e test for append-only executors

- ci/Dockerfile
- ci/build-ci-image.sh
- ci/docker-compose.yml
- ci/scripts/common.env.sh
- ci/workflows/main-cron.yml
- ci/workflows/main.yml
- ci/workflows/pull-request.yml
> chore(ci): add cargo cache for CI

- proto/data.proto
- proto/meta.proto
- proto/source.proto
- src/connector/src/base.rs
- src/connector/src/macros.rs
- src/meta/src/barrier/command.rs
- src/meta/src/stream/source_manager.rs
- src/prost/build.rs
- src/prost/src/lib.rs
- src/stream/src/executor/mod.rs
> chore(connector): refactor source protobuf

- src/meta/src/hummock/hummock_manager.rs
- src/meta/src/hummock/hummock_manager_tests.rs
let compactor be unaware of vnode mapping
> feat(compaction): let compactor be unaware of vnode mapping

- Makefile.toml
- src/batch/src/rpc/service/task_service.rs
- src/batch/src/task/task_execution.rs
> fix(ci): Reduce log

- src/meta/src/hummock/compaction/manual_compaction_picker.rs
fetch info from table_id field in sstableinfo
fix main
> fix(picker): fetch info from table_id field in sstableinfo

- src/meta/src/hummock/compaction/compaction_config.rs
deprecate the HashStrategy for OverlapStrategy
> refactor(compaction): deprecate the HashStrategy for OverlapStrategy

- src/tests/sqlsmith/tests/test_runner.rs
> fix: build failure caused by OptimzierContext::new

- src/frontend/src/handler/create_table.rs
- src/frontend/src/optimizer/mod.rs
- src/frontend/src/optimizer/plan_node/batch_delete.rs
- src/frontend/src/optimizer/plan_node/batch_hash_agg.rs
- src/frontend/src/optimizer/plan_node/batch_hash_join.rs
- src/frontend/src/optimizer/plan_node/batch_hop_window.rs
- src/frontend/src/optimizer/plan_node/batch_insert.rs
- src/frontend/src/optimizer/plan_node/batch_nested_loop_join.rs
- src/frontend/src/optimizer/plan_node/batch_project.rs
- src/frontend/src/optimizer/plan_node/batch_seq_scan.rs
- src/frontend/src/optimizer/plan_node/batch_simple_agg.rs
- src/frontend/src/optimizer/plan_node/batch_table_function.rs
- src/frontend/src/optimizer/plan_node/batch_topn.rs
- src/frontend/src/optimizer/plan_node/batch_update.rs
- src/frontend/src/optimizer/plan_node/batch_values.rs
- src/frontend/src/optimizer/plan_node/convert.rs
- src/frontend/src/optimizer/plan_node/logical_project.rs
- src/frontend/src/optimizer/plan_node/logical_topn.rs
- src/frontend/src/optimizer/plan_node/plan_base.rs
- src/frontend/src/optimizer/plan_node/stream_materialize.rs
- src/frontend/src/optimizer/property/order.rs
- src/frontend/src/planner/delete.rs
- src/frontend/src/planner/insert.rs
- src/frontend/src/planner/update.rs
- src/storage/benches/bench_lru_cache.rs
Remove some unnecessary lazy_static
> refactor: remove unnecessary lazy_static

- src/storage/src/hummock/compactor_tests.rs
as title
fix https://github.com/singularity-data/risingwave/issues/3348
> fix(storage): fix slow unit-test in compactor_test

- src/utils/pgwire/src/pg_extended.rs
- src/utils/pgwire/src/pg_protocol.rs
Just some simple change while skim the code
> style: add more comments & refactor on pg-wire 

- Cargo.lock
- src/tests/sqlsmith/Cargo.toml
- src/tests/sqlsmith/src/expr.rs
- src/tests/sqlsmith/src/lib.rs
- src/tests/sqlsmith/src/relation.rs
- src/tests/sqlsmith/src/scalar.rs
- src/tests/sqlsmith/tests/test_runner.rs
As title
close https://github.com/singularity-data/risingwave/issues/3349
> feat(test): parallelize sqlsmith test

- ci/build-ci-image.sh
- ci/workflows/pull-request.yml
> chore(ci): auto build ci image

- src/frontend/src/handler/describe.rs
- src/frontend/src/handler/dml.rs
- src/frontend/src/handler/explain.rs
- src/frontend/src/handler/query.rs
- src/frontend/src/handler/show.rs
- src/utils/pgwire/src/pg_extended.rs
- src/utils/pgwire/src/pg_message.rs
- src/utils/pgwire/src/pg_protocol.rs
- src/utils/pgwire/src/pg_response.rs
- src/utils/pgwire/src/pg_server.rs
- src/utils/pgwire/src/types.rs
> feat(pgwire): support row limit in extended query mode

- src/frontend/src/handler/explain.rs
as title
- https://github.com/singularity-data/risingwave/pull/3382
> chore(frontend): fix handle_with_properties ctx of explain

- src/storage/src/table/cell_based_table.rs
> fix: build failure of cell based table with release profile

- src/stream/src/executor/debug/trace.rs
- src/stream/src/executor/dispatch.rs
- src/stream/src/executor/merge.rs
- src/stream/src/executor/receiver.rs
- src/utils/pgwire/src/pg_extended.rs
follow up of https://github.com/singularity-data/risingwave/pull/3391, see comments in previous PR. Ended up resolving my own comments. 😇
fixing my own comments in https://github.com/singularity-data/risingwave/pull/3391
> fix(streaming): readability improvements

- src/batch/src/executor/filter.rs
- src/batch/src/executor/join/hash_join_state.rs
- src/batch/src/executor/join/nested_loop_join.rs
- src/batch/src/executor/limit.rs
- src/batch/src/task/hash_shuffle_channel.rs
- src/common/src/array/data_chunk.rs
- src/common/src/array/list_array.rs
- src/common/src/array/stream_chunk.rs
- src/common/src/array/struct_array.rs
- src/common/src/buffer/bitmap.rs
- src/common/src/test_utils/test_stream_chunk.rs
- src/expr/src/expr/expr_is_null.rs
- src/stream/src/executor/aggregation/approx_count_distinct.rs
- src/stream/src/executor/aggregation/foldable.rs
- src/stream/src/executor/aggregation/row_count.rs
- src/stream/src/executor/dispatch.rs
- src/stream/src/executor/hash_agg.rs
[src/common/src/buffer/bitmap.rs](https://github.com/singularity-data/risingwave/pull/3560/files#diff-e5410c4a48b3813193cb4731ffe5a39a4b05e4bdf627c3fd2d8e640ed1ad3d8d)
- remove some useless methods
- remove useless Result
> refactor: improve the interface of bitmap

- src/common/src/session_config.rs
- src/frontend/src/session.rs
Accept datestyle parameter and do nothing.
fixes #3253
> feat(config): accept datestyle parameter

- src/storage/src/hummock/compactor_tests.rs
as title
- ~[ ] I have written necessary docs and comments~
- ~[ ] All checks passed in `./risedev check` (or alias, `./risedev c`)~
> fix(storage): fix unstable_test for compactor and add tracing

- src/compute/tests/integration_tests.rs
- src/storage/src/table/state_table.rs
- src/storage/src/table/test_relational_table.rs
- src/stream/src/executor/mview/test_utils.rs
> chore: rename cell_based table to storage table

- src/stream/src/executor/lookup/impl_.rs
- src/stream/src/from_proto/lookup.rs
Detail please see #3656 
Close #3656
> fix(lookup): fix the semantics of arrange_order_rules

- Cargo.lock
- README.md
- src/test_runner/Cargo.toml
> chore(docs): update the binary version to v0.1.10

- e2e_test/batch/basic/basic.slt.part
- src/common/src/session_config/mod.rs
- src/frontend/src/handler/variable.rs
> feat(frontend): support show all (#3665)

- proto/catalog.proto
- proto/user.proto
`///` in proto will become `////` 🥸
> chore: fix rustdoc for prost

- src/meta/src/hummock/hummock_manager.rs
Fix flawed `check_state_consistency`. 
It is revealed by an unstable test, which reports failed assertion on check_state_consistency:
```
#!/bin/bash
set -e
for (( i=0; i<=10000; i++ ))
do
cargo test --color=always --lib stream::stream_manager::tests::test_create_materialized_view --no-fail-fast --manifest-path risingwave/src/meta/Cargo.toml -- --format=json --exact -Z unstable-options --show-output
done
```
With this fix, the unstable test is fixed as well.
> fix: correctly implement check_state_consistency

- docs/consistent-hash.md
- docs/relational_table/relational-table-schema.md
- docs/relational_table/storing-state-using-relational-table.md
As title. Preview: https://github.com/singularity-data/risingwave/blob/e3d0516a4b6452024eae616567968f152d8845c0/docs/relational_table/relational-table-schema.md
* Create a folder "relational_table" and move 2 relate files into it.
* Write a doc on detail Relational Table Schema. 
* Connector (sources …
> doc: add relational table schema doc + move files

- .github/workflows/license_check.yml
- e2e_test/streaming/tpch_snapshot.slt
- e2e_test/streaming/tpch_upstream.slt
Possibly fix recent CI fails.
Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where …
> fix(ci): use header fix action for license check

- src/bench/ss_bench/operations/write_batch.rs
- src/storage/src/hummock/conflict_detector.rs
- src/storage/src/hummock/iterator/backward_user.rs
- src/storage/src/hummock/iterator/forward_user.rs
- src/storage/src/hummock/shared_buffer/shared_buffer_batch.rs
- src/storage/src/hummock/state_store_tests.rs
- src/storage/src/hummock/test_utils.rs
- src/storage/src/hummock/value.rs
- src/storage/src/storage_value.rs
- src/storage/src/table/test_relational_table.rs
- src/storage/src/write_batch.rs
as title
- remove unused code value_meta
- fix some unit-test
- https://github.com/singularity-data/risingwave/pull/3764
> chore(storage): remove value meta

- src/meta/src/dashboard/index.html
As title. Add more hacks to make things work.
RisingWave dashboard adds dynamic filter node support.
close https://github.com/singularity-data/risingwave/issues/3791
> fix(dashboardv1): adapt new dispatcher design and add dynamic filter node

- src/common/src/util/ordered/serde.rs
- src/utils/memcomparable/src/de.rs
fix decimal flag bound and some test
- ~[ ] I have added necessary unit tests and integration tests`
> fix(utils): fix decimal flag bound

- Cargo.lock
- src/cmd/src/bin/compactor.rs
- src/cmd/src/bin/compute_node.rs
- src/cmd/src/bin/ctl.rs
- src/cmd/src/bin/frontend_node.rs
- src/cmd/src/bin/meta_node.rs
- src/cmd_all/src/bin/risingwave.rs
- src/cmd_all/src/playground.rs
- src/utils/runtime/Cargo.toml
- src/utils/runtime/src/lib.rs
- src/workspace-hack/Cargo.toml
Now we can use environment variable to control tokio, deadlock detection, and profile flame graph behavior. See docs for more information. …
> feat(cli): add prof and tokio env config

- src/stream/src/executor/debug/epoch_check.rs
As title, so as to avoid potential correctness issues and stuck. …
> chore(streaming): check epoch continuous

- src/common/src/hash/dispatcher.rs
- src/common/src/hash/key.rs
- src/common/src/types/mod.rs
> fix(hash): fix hash_key_data_size

- src/stream/src/from_proto/mod.rs
> style(stream): exhaustive patterm for build_executor

- proto/batch_plan.proto
> chore(proto): remove unused FilterScanNode

- proto/catalog.proto
- src/frontend/src/catalog/table_catalog.rs
- src/frontend/src/optimizer/plan_node/stream_materialize.rs
- src/frontend/src/optimizer/plan_node/utils.rs
…ize prefix_slice
as title
- https://github.com/singularity-data/risingwave/issues/3874
> feat(meta): table catalog add read_pattern_prefix_column

- src/common/src/types/chrono_wrapper.rs
- src/common/src/types/mod.rs
> feat: impl chrono types from protobuf

- proto/stream_plan.proto
- src/frontend/src/optimizer/plan_node/mod.rs
- src/frontend/src/stream_fragmenter/rewrite/delta_join.rs
- src/meta/src/stream/stream_graph.rs
- src/stream/src/executor/lookup/impl_.rs
- src/stream/src/executor/lookup/tests.rs
- src/stream/src/from_proto/lookup.rs
> refactor: use state table catalog for lookup

- proto/hummock.proto
- src/ctl/src/cmd_impl/hummock/list_version.rs
- src/ctl/src/cmd_impl/hummock/sst_dump.rs
- src/meta/src/hummock/hummock_manager.rs
- src/meta/src/hummock/hummock_manager_tests.rs
- src/meta/src/hummock/mock_hummock_meta_client.rs
- src/meta/src/hummock/model/pinned_version.rs
- src/meta/src/hummock/vacuum.rs
- src/meta/src/model/mod.rs
- src/meta/src/rpc/service/hummock_service.rs
- src/rpc_client/src/hummock_meta_client.rs
- src/rpc_client/src/meta_client.rs
- src/storage/src/hummock/hummock_meta_client.rs
- src/storage/src/hummock/local_version.rs
- src/storage/src/hummock/local_version_manager.rs
- src/storage/src/monitor/hummock_metrics.rs
let `pin_version` use push scheme
Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions …
> feat(meta): let `pin_version` use push scheme

- src/frontend/src/optimizer/property/distribution.rs
As title
Previous:
```
BatchExchange { order: [], dist: [t.v1flag] }
```
This PR:
```
BatchExchange { order: [], dist: [t.v1, flag] }
```
#3798
> fix(frontend): dist keys in explain verbose mode should be comma seperated

- src/connector/src/source/nexmark/enumerator/mod.rs
- src/connector/src/source/nexmark/source/event.rs
- src/frontend/test_runner/tests/testdata/nexmark.yaml
Use the same schema between all nexmark testings.
#132
> fix(nexmark): make the table schema consistency

- src/common/src/monitor/rwlock.rs
- src/connector/src/sink/mysql.rs
- src/frontend/src/catalog/pg_catalog/mod.rs
- src/meta/src/stream/source_manager.rs
- src/meta/src/stream/stream_graph.rs
- src/storage/src/table/storage_table.rs
- src/stream/src/executor/hash_join.rs
- src/stream/src/executor/lookup/sides.rs
- src/stream/src/executor/managed_state/aggregation/mod.rs
- src/stream/src/executor/managed_state/aggregation/string_agg.rs
- src/stream/src/executor/managed_state/flush_status.rs
- src/stream/src/executor/managed_state/join/join_entry_state.rs
- src/stream/src/executor/managed_state/join/mod.rs
- src/stream/src/executor/managed_state/top_n/top_n_state_new.rs
- src/stream/src/executor/source/reader.rs
- src/stream/src/executor/top_n.rs
- src/stream/src/executor/top_n_appendonly.rs
- src/stream/src/executor/top_n_new.rs
- src/stream/src/task/barrier_manager.rs
As title, and mark some code as cleanable after some refactors. …
> chore: expect dead code instead of allow dead code

- src/tests/sqlsmith/src/bin/main.rs
Currently `CREATE MATEIRLIAZED VIEW` only enabled for frontend fuzzing. This PR enables for e2e fuzzing as well.
Have ran it a few times e2e locally, and passed the tests.
Please …
> feat(sqlsmith): Generate MATERIALIZED VIEW for e2e fuzzing

- src/meta/src/stream/source_manager.rs
> fix: fix source manager crash with empty splits

- src/tests/sqlsmith/src/lib.rs
- src/tests/sqlsmith/src/time_window.rs
> feat(sqlsmith): Generate `HOP`

- src/batch/src/executor/hop_window.rs
fix https://github.com/singularity-data/risingwave/issues/3967
> fix: remove the check of no output of hop in compute node

- risedev.yml
- src/ctl/src/common/hummock_service.rs
- src/ctl/src/common/meta_service.rs
As title.
Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment …
> chore(ctl): better error message for using risectl

- src/ctl/src/cmd_impl/meta.rs
- src/ctl/src/cmd_impl/meta/pause_resume.rs
- src/ctl/src/lib.rs
- src/rpc_client/src/meta_client.rs
A useful feature for debugging.
#3697 
#3471 
Close #4003
> feat(risectl): add meta pause/resume

- Cargo.lock
- proto/stream_plan.proto
- src/meta/Cargo.toml
- src/meta/src/manager/catalog.rs
- src/meta/src/stream/test_fragmenter.rs
As title.
Please keep the types that apply to your changes, and remove those …
> chore: resolve frontend dependency in meta and some code clean

- e2e_test/streaming/index.slt
Enable part of the index test, so that we can discover issue earlier.
Please create a release note for your changes. In the release …
> chore(test): enable part of the index test

- src/frontend/src/handler/query.rs
As title, follow up for #4041. …
> feat: force enable local query mode for system table

- ci/Dockerfile
- ci/build-ci-image.sh
- ci/docker-compose.yml
- ci/scripts/regress-test.sh
As title, so as to avoid installing tools every time we run test. …
> chore(ci): move psql install into docker image build

- proto/hummock.proto
- src/meta/src/hummock/compaction/tier_compaction_picker.rs
- src/meta/src/hummock/test_utils.rs
- src/storage/src/hummock/compactor.rs
- src/storage/src/hummock/shared_buffer/shared_buffer_uploader.rs
- src/storage/src/hummock/sstable/mod.rs
- src/storage/src/hummock/sstable/multi_builder.rs
- src/storage/src/hummock/state_store.rs
- src/storage/src/hummock/test_utils.rs
- src/storage/src/hummock/utils.rs
part of https://github.com/singularity-data/risingwave/pull/3111 …
> feat(hummock): remove useless unit in proto

- src/tests/sqlsmith/src/bin/main.rs
- src/tests/sqlsmith/src/lib.rs
- src/tests/sqlsmith/tests/test_runner.rs
- Unifying table setup functionality between sqlsmith frontend and e2e testsuite.
- Should make sure both e2e and frontend have same setup behaviour. Avoid inconsistent behaviour from sqlsmith.
- It will be easier to cleanup error handling code as well, since they are refactored into common functions.
- e.g. `parse_sql`, `create_table_statement_to_table`.
- Describe clearly one …
> refactor(sqlsmith): unify setup functionality

- src/compute/src/compute_observer/observer_manager.rs
- src/storage/compactor/src/compactor_observer/observer_manager.rs
- src/storage/hummock_sdk/src/slice_transform.rs
- src/storage/src/hummock/compactor.rs
- src/storage/src/hummock/local_version_manager.rs
- src/storage/src/hummock/mod.rs
- src/storage/src/hummock/shared_buffer/shared_buffer_uploader.rs
- src/storage/src/store_impl.rs
as title
- https://github.com/singularity-data/risingwave/issues/3927
- https://github.com/singularity-data/risingwave/pull/3928
> refactor(storage): refactor slice_transform with enum

- src/stream/src/executor/aggregation/agg_state.rs
- src/stream/src/executor/aggregation/mod.rs
- src/stream/src/executor/global_simple_agg.rs
- src/stream/src/executor/hash_agg.rs
- src/stream/src/executor/managed_state/aggregation/extreme.rs
- src/stream/src/executor/managed_state/aggregation/mod.rs
- src/stream/src/executor/managed_state/aggregation/string_agg.rs
- src/stream/src/executor/managed_state/aggregation/value.rs
- src/stream/src/executor/test_utils.rs
- src/stream/src/from_proto/hash_agg.rs
> feat(streaming): use row-based encoding for agg

- src/utils/pgwire/src/pg_extended.rs
- src/utils/pgwire/src/pg_message.rs
- src/utils/pgwire/src/pg_protocol.rs
- src/utils/pgwire/src/pg_response.rs
- src/utils/pgwire/src/pg_server.rs
as title and related issue
#4049
> feat(pgwire): introdue binary for extended query mode

- src/meta/src/barrier/recovery.rs
- src/meta/src/cluster/mod.rs
- src/meta/src/stream/meta.rs
As title.
Please keep the types that apply to your changes, and remove those …
> chore: fix migrate plan return type

- e2e_test/batch/tpch.slt
> fix(batch): Enable tpch q16

- src/frontend/src/handler/describe.rs
- src/frontend/src/handler/dml.rs
- src/frontend/src/handler/explain.rs
- src/frontend/src/handler/mod.rs
- src/frontend/src/handler/query.rs
- src/frontend/src/handler/show.rs
- src/frontend/src/handler/util.rs
- src/frontend/src/handler/variable.rs
- src/frontend/src/session.rs
- src/frontend/src/test_utils.rs
- src/tests/sqlsmith/tests/test_runner.rs
- src/utils/pgwire/src/pg_extended.rs
- src/utils/pgwire/src/pg_message.rs
- src/utils/pgwire/src/pg_protocol.rs
- src/utils/pgwire/src/pg_server.rs
- src/utils/pgwire/src/types.rs
> refactor:move binary format support to frontend

- e2e_test/streaming/tpch/create_views.slt.part
- e2e_test/streaming/tpch_snapshot.slt
- e2e_test/streaming/tpch_upstream.slt
> chore: use create_views.slt.part in streaming e2e

- src/frontend/src/handler/explain.rs
- src/frontend/src/handler/query.rs
As title. Related issue #4172
As title. Related issue #4172
> fix(frontend): explain local plan in local mode

- src/storage/src/hummock/shared_buffer/shared_buffer_batch.rs
> fix(storage): fix compile error for release mode

- ci/README.md
- ci/scripts/pr.env.sh
If there's no change in script, `grep` will return exit code of non-zero. As we've set `-e`, bash will immediately exit.
We can temporarily disable `-e` upon running the command. …
> fix(ci): fix unit test failure

- src/common/src/cache.rs
- src/common/src/config.rs
- src/common/src/lib.rs
- src/common/src/types/mod.rs
- src/common/src/util/chunk_coalesce.rs
> chore: remove #![expect(dead_code)] for common

- src/stream/src/executor/group_top_n.rs
Signed-off-by: Shmiwy <wyf000219@126.com>
support multi group keys in group topN. …
> feat(stream): support multi group keys in group topN

- Cargo.lock
- proto/common.proto
- src/frontend/Cargo.toml
- src/frontend/src/catalog/mod.rs
- src/frontend/src/catalog/root_catalog.rs
- src/frontend/src/catalog/schema_catalog.rs
- src/frontend/src/catalog/sink_catalog.rs
- src/frontend/src/catalog/source_catalog.rs
- src/frontend/src/handler/create_sink.rs
- src/frontend/src/handler/drop_sink.rs
- src/meta/src/cluster/mod.rs
As title, together with some code clean. …
> fix: check sink owner when drop

- ci/workflows/main.yml
> fix(ci): add mult arch image build when tag

- README.md
> chore(docs): update the binary version with new tag

- src/meta/src/hummock/hummock_manager.rs
For trivial_move compaction task, there is no need to check the task assignment because we won't populate compact_task_assignment for it. Prior to this PR, trivial move compaction will cause meta node to panic.
> fix(compaction): Skip compaction task assignment check for trivial move tasks

- src/stream/src/executor/managed_state/top_n/top_n_bottom_n_state.rs
- src/stream/src/executor/managed_state/top_n/top_n_state.rs
> refactor(streaming): apply row-based encoding for append_only top_n

- docs/developer-guide.md
As per title. Encounter this fairly often on machine with 16GB RAM, 8 cores.
* …
> chore(developer-docs): add note on compilation bottlenecks

- src/frontend/src/handler/create_mv.rs
- src/frontend/src/handler/create_source.rs
- src/frontend/src/handler/create_table.rs
- src/frontend/src/handler/explain.rs
- src/frontend/src/handler/mod.rs
- src/frontend/src/optimizer/plan_node/logical_agg.rs
- src/frontend/src/optimizer/plan_node/stream_dynamic_filter.rs
- src/frontend/src/optimizer/plan_node/stream_hash_join.rs
- src/frontend/src/optimizer/plan_node/stream_materialize.rs
- src/frontend/src/optimizer/plan_node/utils.rs
- src/frontend/src/session.rs
- src/frontend/test_runner/src/lib.rs
as title
- save properties in ctx
- fix table option for internal table
- https://github.com/singularity-data/risingwave/issues/4425
> fix(frontend): fix table option for internal table

- ci/workflows/main.yml
> chore(ci): remove repeated ci steps

- src/compute/src/compute_observer/observer_manager.rs
- src/storage/compactor/src/compactor_observer/observer_manager.rs
- src/storage/hummock_sdk/src/filter_key_extractor.rs
- src/tests/sqlsmith/tests/frontend/mod.rs
> fix: fix observer version check and add sync in compute/compactor node

- proto/meta.proto
- src/meta/src/rpc/server.rs
- src/meta/src/rpc/service/notification_service.rs
feat(meta): meta push initial hummock version into CN …
> feat(meta): meta push initial hummock version into CN

- ci/scripts/e2e-test.sh
- e2e_test/extended_query/basic.slt
add basic.slt in extended_query, this file test:
basic statement:
- SET 
- EXPLAIN
- CREATE
- DROP
- INSERT 
- SELECT
- VALUES
- SHOW
- DESCRIBE
basic type:
- int2 int4 int8
- float4 float8 numeric
- data time timestamp
#4483
> feat(CI):add extended_query e2e test in CI

- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/recovery.rs
- src/meta/src/lib.rs
- src/meta/src/manager/catalog/mod.rs
- src/meta/src/manager/env.rs
- src/meta/src/stream/stream_manager.rs
> feat(meta): migration by default when recovery enabled in meta

- src/common/src/util/sort_util.rs
This PR adds support for `NaiveDateTime`, `NaiveTime`, `Struct` and `List` in the sorting utility module.
This is part of the refactoring of managed agg states.
> feat(common): support all data types in `sort_util`

- e2e_test/sink/t2.slt
- e2e_test/sink/t3.slt
Tiny fix in two sink e2e tests.
> fix(test): change name in Sink with properties

- src/frontend/src/binder/relation/mod.rs
- src/frontend/test_runner/tests/testdata/distribution_derive.yaml
> fix(binder): cte name assert use the real name

- dashboard/pages/api/cluster.js
- src/meta/src/dashboard/index.html
As title, cause by proto change:
```proto
enum WorkerType {
UNSPECIFIED = 0;
FRONTEND = 1;
COMPUTE_NODE = 2;
RISE_CTL = 3;
COMPACTOR = 4;
GENERIC = 100;
}
```
If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, …
> chore: fix dashboard worker node info

- src/ctl/src/cmd_impl/profile.rs
> chore(risedev): add a message for saved profiling result

- src/compute/tests/integration_tests.rs
- src/stream/src/executor/actor.rs
- src/stream/src/executor/aggregation/mod.rs
- src/stream/src/executor/dispatch.rs
- src/stream/src/executor/dynamic_filter.rs
- src/stream/src/executor/filter.rs
- src/stream/src/executor/global_simple_agg.rs
- src/stream/src/executor/hash_agg.rs
- src/stream/src/executor/hash_join.rs
- src/stream/src/executor/hop_window.rs
- src/stream/src/executor/integration_tests.rs
- src/stream/src/executor/local_simple_agg.rs
- src/stream/src/executor/merge.rs
- src/stream/src/executor/mod.rs
- src/stream/src/executor/monitor/streaming_stats.rs
- src/stream/src/executor/project.rs
- src/stream/src/executor/receiver.rs
- src/stream/src/executor/source/source_executor.rs
- src/stream/src/from_proto/chain.rs
- src/stream/src/from_proto/dynamic_filter.rs
- src/stream/src/from_proto/hash_agg.rs
- src/stream/src/from_proto/hash_join.rs
- src/stream/src/from_proto/merge.rs
- src/stream/src/from_proto/source.rs
- src/stream/src/task/stream_manager.rs
Also use fine-grained lock
Also remove OperatorInfoStatus and related metrics ( close https://github.com/singularity-data/risingwave/issues/4663)
> refactor(stream): move actor_id into ctx

- src/meta/src/hummock/compaction_scheduler.rs
- src/meta/src/hummock/error.rs
- src/meta/src/hummock/manager/gc.rs
- src/meta/src/hummock/manager/mod.rs
- src/meta/src/hummock/manager/tests.rs
- src/meta/src/hummock/mock_hummock_meta_client.rs
- src/meta/src/hummock/mod.rs
- src/meta/src/hummock/vacuum.rs
- src/meta/src/lib.rs
- src/meta/src/manager/env.rs
- src/meta/src/model/cluster.rs
- src/meta/src/rpc/server.rs
- src/meta/src/rpc/service/hummock_service.rs
This PR guarantees the correctness of GC, by filtering out candidate SSTs by watermark. 
- It adds a method `collect_global_gc_watermark` to collect global watermark.
- It's the last PR of https://github.com/singularity-data/risingwave/issues/4037.
- It doesn't enable auto full GC, as we've provided manual full GC in risectl.
[Integration tests](https://github.com/singularity-data/risingwave/commit/5c230e1285b1983defe018ac0bbcc08755686223#diff-27053b50dcd154f53589d0da17ac06cee7fafadddc47e3f42aaaf8ef98393749) are placed in [this branch ](https://github.com/singularity-data/risingwave/tree/wangzheng/integrate_gc_test ). We …
> feat(storage): filter out SST by watermark in GC.

- Makefile.toml
- src/risedevtool/common.toml
> fix(risedev): replace shell with bash

- dashboard/lib/streamPlan/parser.js
- src/meta/src/dashboard/index.html
> fix(dashboard): add expand for visualization

- ci/scripts/deterministic-e2e-test.sh
- e2e_test/streaming/nexmark/create_views.slt.part
- e2e_test/streaming/nexmark/drop_views.slt.part
- e2e_test/streaming/nexmark/q15.slt.part
- e2e_test/streaming/nexmark/views/q15.slt.part
- e2e_test/streaming/nexmark_snapshot.slt
- e2e_test/streaming/nexmark_upstream.slt
> test: add nexmark q15 into e2e tests

- src/frontend/test_runner/src/bin/apply.rs
> feat(planner_test): print better debugging message for panics

- src/frontend/src/session.rs
- src/risedevtool/src/task/compactor_service.rs
- src/risedevtool/src/task/frontend_service.rs
Fix https://github.com/singularity-data/risingwave/issues/4869. …
> fix(risedev): provide client-address for compactor

- ci/build-ci-image.sh
- ci/docker-compose.yml
- ci/scripts/e2e-test-parallel.sh
- ci/scripts/run-e2e-test.sh
To reflect the change of https://github.com/risinglightdb/sqllogictest-rs/pull/86
> chore(ci): use one session for each file in serial mode e2e tests

- src/frontend/src/utils/column_index_mapping.rs
`rewrite_provided_distribution` do not handle `UpstreamHashShard`
> fix(opt): fix rewrite_provided_distribution

- e2e_test/batch/tpch.slt
Fix https://github.com/singularity-data/risingwave/pull/4902#issuecomment-1227945405
> feat: Make tpch distributed explicitly

- e2e_test/streaming/project_set.slt
- src/stream/src/executor/project_set.rs
close https://github.com/singularity-data/risingwave/issues/4894
> fix(streaming): rewrite update op to insert/delete for ProjectSet

- src/frontend/src/handler/create_index.rs
- src/frontend/src/handler/create_mv.rs
- src/frontend/src/handler/create_sink.rs
- src/frontend/src/handler/create_source.rs
- src/frontend/src/handler/create_table.rs
- src/frontend/src/stream_fragmenter/mod.rs
I was trying to understand the underlying logic of the fragmentor. While I read the code, I found some suboptimal code that can be improved. This PR includes these improvements.
I was assigned to rewrite this code, and I think trivial simplifications are good starters.
These are all internal changes :-)
> refactor(fragmentor): some refactoring done when I tried to understand the code

- src/common/src/error.rs
- src/frontend/test_runner/tests/testdata/basic_query.yaml
- src/frontend/test_runner/tests/testdata/types.yaml
> chore: fix feature request link

- ci/scripts/benchmark.sh
> fix(ci): change the auto benchmark region config

- src/storage/src/row_serde/mod.rs
> chore: remove cell-based field in column mapping

- e2e_test/batch/join/inner/test_null_safe_equal_join.slt.part
- src/batch/src/executor/join/hash_join.rs
> test: add test for batch null safe hash join

- .github/workflows/assign-issue-milestone.yml
> chore: add issues to GitHub Project automatically

- src/frontend/src/optimizer/plan_node/logical_topn.rs
- src/frontend/src/optimizer/plan_node/stream_group_topn.rs
- src/frontend/src/optimizer/plan_node/stream_topn.rs
- src/stream/src/executor/group_top_n.rs
- src/stream/src/executor/top_n.rs
- src/stream/src/executor/top_n_appendonly.rs
- src/stream/src/from_proto/group_top_n.rs
- src/stream/src/from_proto/top_n.rs
Signed-off-by: Shmiwy <wyf000219@126.com>
refactor 2-phase topN to reduce the code duplication
Please create a release note for your changes. In the release note, focus on the …
> refactor(stream): refactor 2-phase topN to reduce the code duplication

- src/storage/src/table/streaming_table/mem_table.rs
- src/stream/src/executor/hash_join.rs
Check the code for details.
The sanity check for HashJoin is also enabled correctly.
- #4997
- #3085
- #4588
- Close #3887
> fix(storage): incorrect row op of "insert then update"

- .github/workflows/assign-issue-milestone.yml
> chore: fix workflow of adding issues to project

- docker/docker-compose.yml
- src/risedevtool/src/compose.rs
- src/risedevtool/src/task/frontend_service.rs
As titled.
Please create a release note for your changes. In …
> fix(risedev): specify config-path for frontend in compose

- src/common/src/error.rs
> chore: remove unused ErrorCode variants

- proto/user.proto
- src/frontend/src/catalog/pg_catalog/mod.rs
- src/frontend/src/handler/alter_user.rs
- src/frontend/src/handler/create_database.rs
- src/frontend/src/handler/create_index.rs
- src/frontend/src/handler/create_mv.rs
- src/frontend/src/handler/create_sink.rs
- src/frontend/src/handler/create_source.rs
- src/frontend/src/handler/create_user.rs
- src/frontend/src/handler/privilege.rs
- src/frontend/src/handler/query.rs
- src/frontend/src/session.rs
- src/frontend/src/test_utils.rs
- src/meta/src/manager/catalog/mod.rs
- src/meta/src/manager/catalog/user.rs
1. add database's CONNECT privilege check.
2. allow who connects to a database to create object in the public schema of the database.
3. add query's SELECT privilege check.
> fix: fix privileges check

- src/meta/src/barrier/recovery.rs
- src/meta/src/manager/catalog/fragment.rs
- src/meta/src/rpc/service/ddl_service.rs
- src/meta/src/stream/stream_manager.rs
> refactor: maintenaning vnode mapping notify in fragment manager

- e2e_test/nexmark/create_sources.slt.part
- src/frontend/test_runner/tests/testdata/nexmark.yaml
> chore(test): add primary key constraints for nexmark sources & planner tests

- proto/hummock.proto
- src/meta/src/hummock/compaction/mod.rs
- src/meta/src/hummock/compaction/overlap_strategy.rs
Remove unused and untested hash overlap strategy in compaction. …
> chore(compaction): remove consistent hash overlap strategy.

- src/frontend/src/scheduler/distributed/query.rs
- src/frontend/src/scheduler/distributed/stage.rs
> fix: incorrect naming of tx and rx

- e2e_test/streaming/group_top_n.slt
- src/frontend/planner_test/tests/testdata/nexmark.yaml
- src/frontend/planner_test/tests/testdata/over_window_function.yaml
- src/frontend/src/optimizer/mod.rs
- src/frontend/src/optimizer/plan_node/logical_join.rs
- src/frontend/src/optimizer/rule/over_agg_to_topn.rs
> test: add a test case for window group top n

- docs/developer-guide.md
Adds the missing documentation for deterministic test. 😇
> doc(test): add developer guide for deterministic test

- src/meta/src/hummock/compaction_scheduler.rs
- src/meta/src/hummock/compactor_manager.rs
- src/meta/src/hummock/manager/mod.rs
- src/meta/src/manager/notification.rs
- src/storage/hummock_sdk/src/key_range.rs
> refactor(test): test CompactorManager

- docs/developer-guide.md
> doc: fix broken link

- src/frontend/src/handler/mod.rs
- src/utils/pgwire/src/pg_response.rs
ignore COMMIT and ROLLBACK statement 
#2595
#3675
> feat(frontend):ignore COMMIT and ROLLBACK

- src/frontend/src/handler/drop_mv.rs
> fix(frontend): refine error msg for drop internal table

- dashboard/proto/gen/batch_plan.ts
- dashboard/proto/gen/catalog.ts
- dashboard/proto/gen/common.ts
- dashboard/proto/gen/expr.ts
- dashboard/proto/gen/hummock.ts
- dashboard/proto/gen/meta.ts
- dashboard/proto/gen/stream_plan.ts
- dashboard/proto/gen/stream_service.ts
- proto/common.proto
as title
- update dashboard proto ts
- remove generaic type of WorkerType
- https://github.com/risingwavelabs/risingwave/issues/5238
> chore(proto): remove generic type

- proto/buf.yaml
- proto/health.proto
- proto/hummock.proto
- proto/user.proto
- src/meta/src/manager/catalog/user.rs
The lint for https://github.com/risingwavelabs/risingwave/issues/4119
> chore(proto): enable ENUM_ZERO_VALUE_SUFFIX lint

- src/prost/helpers/README.md
- src/prost/helpers/src/generate.rs
- src/prost/helpers/src/lib.rs
> doc(prost): update doc for prost-helper

- src/frontend/planner_test/tests/testdata/distribution_derive.yaml
- src/frontend/planner_test/tests/testdata/nexmark.yaml
- src/frontend/planner_test/tests/testdata/stream_dist_agg.yaml
- src/frontend/planner_test/tests/testdata/tpch.yaml
- src/frontend/src/utils/stream_graph_formatter.rs
forget adding it in #5454 :crying_cat_face:
> feat(explain): add explain distribution key in state table

- src/utils/pgwire/src/pg_extended.rs
support all param in text format.
#3676
> feat(pgwire):support all text format param

- src/frontend/src/expr/mod.rs
Some changes made during a meeting. Made a macro to generate some manually-written code.
N/A
N/A
> refactor(expr): use macro

- e2e_test/batch/aggregate/sum.slt.part
- src/expr/src/vector_op/agg/aggregator.rs
Address the e2e tests
Fixes #4508
> fix(batch): support sum(interval)

- src/object_store/src/object/s3.rs
In #5546, we introduced S3 bucket lifecycle rule configuration to purge stale multipart uploads. However, if no lifecycle configuration is set, `get_bucket_lifecycle_rules` will return an error, causing unwrap to panic. This PR fixes it.
* RisingWave cluster configuration …
> fix(object store): correctly handle get lifecycle response

- src/batch/benches/README.md
> doc: add docs for batch micro benchmarks

- clippy.toml
- src/common/src/types/decimal.rs
- src/common/src/types/mod.rs
- src/common/src/util/ordered/serde.rs
- src/connector/src/sink/mod.rs
- src/connector/src/source/pulsar/admin/client.rs
- src/expr/src/vector_op/agg/functions.rs
- src/frontend/src/session.rs
- src/risedevtool/src/bin/risedev-config.rs
- src/storage/src/store.rs
- src/stream/clippy.toml
- src/tests/regress/src/opts.rs
- src/tests/regress/src/schedule.rs
- src/utils/pgwire/src/pg_message.rs
- src/utils/pgwire/src/pg_protocol.rs
- src/utils/pgwire/src/pg_server.rs
> style: enable clippy upper-case-acronyms-aggressive

- src/frontend/src/optimizer/plan_node/generic.rs
- src/frontend/src/optimizer/plan_node/logical_expand.rs
- src/frontend/src/optimizer/plan_node/logical_filter.rs
Essentially continuing #5630.
#5630
> refactor(plan_node): continue the extraction in #5630

- src/frontend/src/optimizer/plan_node/generic.rs
- src/frontend/src/optimizer/plan_node/logical_join.rs
Essentially continuing #5630, #5699. Next step: rewrite stream nodes.
#5630
#5699
> refactor(plan_node): Last part on rewriting logical nodes

- src/frontend/src/handler/create_mv.rs
As titled.
Please keep the types that apply to your changes, and remove those that do …
> chore: remove temporary compaction group switch

- proto/meta.proto
- proto/stream_plan.proto
- src/connector/src/source/kafka/enumerator/client.rs
- src/connector/src/source/kafka/source/reader.rs
- src/meta/src/barrier/command.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/recovery.rs
- src/meta/src/manager/catalog/fragment.rs
- src/meta/src/stream/scale.rs
- src/meta/src/stream/source_manager.rs
- src/meta/src/stream/stream_manager.rs
- src/stream/src/executor/dispatch.rs
- src/stream/src/executor/merge.rs
- src/stream/src/executor/mod.rs
- src/stream/src/executor/receiver.rs
- src/stream/src/executor/source/reader.rs
- src/stream/src/executor/source/source_executor.rs
> feat: introduce source actor scaling

- src/meta/src/hummock/compaction_group/manager.rs
refactor(compaction group): change use case because vartrx fixed …
> refactor(compaction group): change use case because vartrx fixed

- .github/workflows/doc.yml
> fix(build): fix CI doc test by adding dependency

- e2e_test/batch/types/interval.slt.part
- src/common/src/types/interval.rs
> feat: support more postgres syntax of interval

- src/meta/src/hummock/manager/mod.rs
Set task status when cancelling a manual compaction task. Otherwise we fail this assertion https://github.com/risingwavelabs/risingwave/blob/ff7e7d9ef89961960aad88cf719058c5c82e9f55/src/meta/src/hummock/manager/mod.rs#L987
* …
> fix(compaction): set task status on cancellation

- src/meta/src/stream/source_manager.rs
> chore: re-add force tick 

- src/storage/hummock_test/src/hummock_read_version_tests.rs
- src/storage/hummock_test/src/hummock_storage_tests.rs
- src/storage/hummock_test/src/local_version_manager_tests.rs
- src/storage/hummock_test/src/state_store_tests.rs
- src/storage/hummock_test/src/test_utils.rs
- src/storage/src/hummock/event_handler/hummock_event_handler.rs
- src/storage/src/hummock/event_handler/mod.rs
- src/storage/src/hummock/local_version/local_version_manager.rs
- src/storage/src/hummock/store/state_store.rs
- src/storage/src/hummock/store/version.rs
as title
- https://github.com/risingwavelabs/risingwave/issues/5665
> feat(storage): support update committed_version of HummockReadVersion

- README.md
- ci/scripts/release.sh
> chore: update readme and release script

- docs/architecture-design.md
- docs/state-store-overview.md
- docs/streaming-overview.md
As title, just rephrasing of some sentences in the docs and/or fixing some grammar issues.
> chore(docs): rephrasing some sentences in docs 

- src/meta/src/barrier/command.rs
- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/recovery.rs
- src/meta/src/manager/background_deleter.rs
- src/meta/src/manager/catalog/fragment.rs
- src/meta/src/manager/catalog/mod.rs
- src/meta/src/rpc/service/ddl_service.rs
- src/meta/src/stream/source_manager.rs
- src/meta/src/stream/stream_manager.rs
> feat(meta): drop actor and source in batch interface

- ci/Dockerfile
- ci/build-ci-image.sh
- ci/docker-compose.yml
- ci/scripts/e2e-source-test.sh
> chore: move kafkacat dep to docker

- README.md
highlight production-ready in README.
> chore: highlight production-ready

- e2e_test/streaming/demo/ad_ctr.slt
- src/stream/src/executor/hash_agg.rs
> fix(stream): fix stream hash agg when n_appended_ops equals 0

- proto/data.proto
- proto/expr.proto
- src/batch/benches/filter.rs
- src/batch/benches/hash_join.rs
- src/batch/benches/nested_loop_join.rs
- src/batch/src/executor/filter.rs
- src/expr/src/expr/build_expr_from_prost.rs
- src/expr/src/expr/expr_array_concat.rs
- src/expr/src/expr/expr_in.rs
- src/expr/src/expr/expr_literal.rs
- src/expr/src/expr/test_utils.rs
- src/frontend/src/expr/literal.rs
- src/source/src/test_data/complex-schema.proto
- src/source/src/test_data/simple-schema.proto
> refactor(proto): add datum in proto

- src/frontend/src/optimizer/plan_node/generic.rs
- src/frontend/src/optimizer/plan_node/logical_source.rs
- src/frontend/src/optimizer/plan_node/mod.rs
- src/frontend/src/optimizer/plan_node/plan_base.rs
- src/frontend/src/optimizer/plan_node/stream.rs
- src/frontend/src/optimizer/plan_node/stream_hash_join.rs
- src/frontend/src/optimizer/plan_node/stream_local_simple_agg.rs
+ Continue the development in #6024
+ Since there are some changes that touches some existing code (well, in trivial ways), I would like to pull it to main to prevent potential merge conflicts
#5843, #6024
> refactor(plan): further preparation for `to_prost` of new stream nodes

- .github/workflows/doc.yml
> fix(ci): fix doc deployment by updating apt

- .github/workflows/dashboard_pr.yml
- dashboard/scripts/generate_proto.sh
- proto/data.proto
close https://github.com/risingwavelabs/risingwave/issues/6107
> ci: check dashboard is not broken when protobuf updates

- src/frontend/src/optimizer/plan_node/generic.rs
- src/frontend/src/optimizer/plan_node/logical_scan.rs
- src/frontend/src/optimizer/plan_node/stream.rs
- src/frontend/src/optimizer/plan_node/stream_dynamic_filter.rs
Continue the development in #6083 #6105 #6121
#6083 #6105 #6121
> refactor(plan): missing dynamic filter

- ci/scripts/docker.sh
- ci/scripts/multi-arch-docker.sh
- ci/workflows/docker.yml
- ci/workflows/main.yml
> chore(ci): upload images to dockerhub

- e2e_test/batch/duckdb/all.slt.part
- e2e_test/batch/duckdb/conjunction/or_between.slt.part
- e2e_test/batch/duckdb/conjunction/or_comparison.slt.part
> fix: add conjunction test in DuckDB

- src/common/src/buffer/bitmap.rs
There may be some dirty bits in the bytes, e.g. when implementing the bitwise not.
> fix(bitmap): Bitmap::from_bytes_with_num_bits handle the last byte wrongly

- ci/build-ci-image.sh
- ci/docker-compose.yml
- src/frontend/src/expr/mod.rs
https://github.com/nextest-rs/nextest/pull/623
> ci: fix nextest ci profile (should not retry)

- src/frontend/src/handler/mod.rs
> chore: track create as statement in github issue

- e2e_test/batch/basic/array.slt.part
- src/frontend/planner_test/tests/testdata/array.yaml
- src/frontend/src/binder/expr/mod.rs
- src/frontend/src/binder/expr/value.rs
> fix: support propagating explicit cast of array

- src/frontend/src/handler/explain.rs
> fix(frontend): disable explain create source and return a more friendly error message

- e2e_test/batch/duckdb/all.slt.part
- e2e_test/batch/duckdb/limit/test_parallel_limit.slt.part
- e2e_test/batch/duckdb/limit/test_parallel_limit_nulls.slt.part
- e2e_test/batch/duckdb/limit/test_parallel_limit_strings.slt.part
- e2e_test/batch/duckdb/limit/test_preserve_insertion_order.slt.part
> test(limit): enable duckdb limit test

- src/utils/pgwire/src/pg_protocol.rs
- src/utils/pgwire/src/pg_server.rs
Part of refactor. Want to make pgwire more stateless and more stm style.
Please create a release note for your changes. In the release note, focus on the impact on users, and …
> refactor: refactor pgwire towards stm (1)

- codecov.yml
See this solution from the [discussion](https://community.codecov.com/t/unable-to-determine-a-parent-commit-to-compare-against-in-base-branch-after-squash-and-merge/2480/15), but I didn't fully understant it yet and I'm not sure if it works. We can have a try. If it doesn't work we can try the workaround: upload cov artifact on PR and then upload on main 🤪
Doc for the config: https://docs.codecov.com/docs/comparing-commits#pseudo-comparison-example:~:text=in%20the%20UI.-,Coverage%20Offsets,-Sometimes%20the%20pseudo
> ci: try to fix codecov for main

- src/meta/src/stream/stream_graph.rs
> fix(streaming): fix merge node stream key

- src/meta/src/stream/scale.rs
- src/meta/src/stream/stream_manager.rs
> fix: add some missing fields in Chain actor

- src/rpc_client/src/meta_client.rs
As title, ignore the first tick of timeout ticker.
Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment …
> feat: fix randomly exit of meta client when start

- ci/workflows/main-cron.yml
- src/tests/compaction_test/src/runner.rs
Wait until compaction start and subscribe to the new meta node …
> chore(ci): fix catalog notification to compactor in compaction-test

- .cargo/config.toml
- docs/developer-guide.md
Signed-off-by: Bugen Zhao 2 <i@bugenzhao.com>
Close https://github.com/risingwavelabs/risingwave/issues/6205
Developers now need to install llvm from homebrew.
Please create a …
> feat(build): use llvm 15's ld on Apple Silicon

- e2e_test/batch/basic/func.slt.part
- src/common/src/buffer/bitmap.rs
- src/expr/src/expr/expr_binary_nullable.rs
> feat(expr): short-circuit optimization for or

- src/frontend/src/optimizer/plan_node/stream.rs
- src/frontend/src/optimizer/property/distribution.rs
Modified some code inspired from #6145
#6145
> refactor(st1page): improve some code and cherry-pick

- src/source/src/lib.rs
- src/source/src/parser/avro_parser/parser.rs
- src/source/src/parser/debezium/json_parser.rs
- src/source/src/parser/debezium/simd_json_parser.rs
- src/source/src/parser/json_parser.rs
- src/source/src/parser/maxwell/json_parser.rs
- src/source/src/parser/maxwell/simd_json_parser.rs
- src/source/src/parser/mod.rs
- src/source/src/parser/pb_parser/parser.rs
- use GAT and TAIT to impl zero cost async `SourceParser` trait
~- [] I have written necessary rustdoc comments~
~- [] I have added necessary unit tests and integration tests~
> perf(source): use GAT and TAIT to impl zero cost async `SourceParser` trait

- src/source/src/parser/avro_parser/schema_resolver.rs
- src/source/src/parser/pb_parser/schema_resolver.rs
- src/source/src/parser/util.rs
- extract some duplicate code as a function 
> refactor(source): extract some duplicate code as a function

- src/ctl/src/common/meta_service.rs
Help first time users of `risedev` and make the error message more helpful.
> feat: Make error message more helpful

- Makefile.toml
Create a `risedev follow` command. This is similar to `kubectl logs <pod> --follow` …
> feat: risedev follow

- .github/workflows/dashboard_pr.yml
The action runs on a merge commit. When there are changes both on main and pr, prompts to update branch first
Tested here https://github.com/xxchan/risingwave/pull/1
> ci: improve dashboard ci

- e2e_test/streaming/union.slt
- src/frontend/planner_test/tests/testdata/union.yaml
- src/frontend/src/optimizer/plan_node/logical_union.rs
- src/frontend/src/optimizer/plan_node/stream_union.rs
- Union use `HashExchange` instead of `SingleExchange`.
- Add union test case, since we already support `UnionToDistinctRule`.
* RisingWave …
> feat(streaming): union use hash shuffle

- ci/workflows/main-cron.yml
- ci/workflows/main.yml
- ci/workflows/pull-request.yml
Fix the e2e-source-test in the `main` pipeline.
Test run: https://buildkite.com/risingwavelabs/main/builds/2289
* …
> fix(ci): fix main pipeline

- src/tests/regress/data/schedule
enable the `comments.sql` PG test
close #6519
> test: enable `PG` regress test `comments.sql`

- src/batch/src/error.rs
- src/expr/src/error.rs
- src/frontend/planner_test/tests/testdata/range_scan.yaml
The original error message "Out of range" may be confusing at the first glance.
None
None
> fix: improve error message "Out of range"

- src/meta/src/hummock/compaction_scheduler.rs
As titled. Previously I used a u64::MAX as interval which results in 'overflow when adding duration to instant'. …
> fix(test): disable periodic trigger for compaction test

- src/compute/src/lib.rs
- src/stream/src/task/stream_manager.rs
- src/utils/async_stack_trace/src/lib.rs
* fix config
* turn on trace by default
* try use default verbose in CI
* cleanup comments
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
> chore: merge #6539 into v0.1.14-rc

- e2e_test/batch/basic/func.slt.part
- src/expr/src/expr/expr_case.rs
short-circuit optimization for case when …
> feat(case when): short-circuit optimization for case when

- .github/workflows/dashboard_pr.yml
- proto/common.proto
Failure example: https://github.com/risingwavelabs/risingwave/actions/runs/3554142408
> ci: fix dashboard ci for forked repo

- .github/workflows/dashboard_pr.yml
- dashboard/proto/gen/connector_service.ts
`git diff` doesn't check untracked files. If someone adds a new `.proto` file and forgets to `gen-proto`, CI will not fail.
> fix: generate ts file for newly added proto & fix ci

- src/common/src/cache.rs
- src/object_store/src/object/disk.rs
- src/storage/benches/bench_lru_cache.rs
- src/storage/src/hummock/block_cache.rs
- src/storage/src/hummock/sstable_store.rs
cherry-pick https://github.com/risingwavelabs/risingwave/pull/6634 …
> fix(cache): fix entry drop in channel

- e2e_test/batch/basic/insert_expr.slt.part
- src/batch/src/executor/insert.rs
cherry-pick https://github.com/risingwavelabs/risingwave/pull/6590 …
> fix: Data insert not aligned with col names (#6590)

- risedev.yml
- src/risedevtool/README.md
- src/risedevtool/risedev-schema.json
> chore: add JSON schema for risedev.yml

- ci/scripts/multi-arch-docker.sh
> fix(ci): fix docker build tag (#6486)

- src/common/src/types/chrono_wrapper.rs
- src/common/src/types/decimal.rs
- src/common/src/types/interval.rs
- src/common/src/types/mod.rs
- src/common/src/types/to_binary.rs
- src/frontend/src/handler/util.rs
I prepare to support the binary format of array later. And there are some syntaxes we can't support, it needs to return an Error in this case. …
> feat:return result in to_binary

- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/recovery.rs
- src/meta/src/error.rs
- src/meta/src/rpc/server.rs
- src/meta/src/rpc/service/ddl_service.rs
feat: reject ddl with streamng jobs when recovering
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
Merge #6651 into v0.1.14-rc 
https://github.com/risingwavelabs/risingwave/issues/6512#issuecomment-1331886211
> feat(meta): reject ddl with streaming jobs when recovering (#6651)

- ci/scripts/release.sh
- ci/workflows/main.yml
> fix: main release docker timeout

- dashboard/pages/streaming_graph.tsx
> fix(dashboard): fix stream graph of MoS

- src/frontend/planner_test/tests/testdata/agg.yaml
- src/frontend/planner_test/tests/testdata/distribution_derive.yaml
- src/frontend/planner_test/tests/testdata/nexmark.yaml
- src/frontend/planner_test/tests/testdata/time_window.yaml
- src/frontend/planner_test/tests/testdata/tpch.yaml
- src/frontend/src/optimizer/mod.rs
- src/frontend/src/optimizer/plan_node/generic/agg.rs
- src/frontend/src/optimizer/plan_node/generic/project.rs
- src/frontend/src/optimizer/plan_node/logical_project.rs
- src/frontend/src/optimizer/rule/agg_project_merge.rs
- src/frontend/src/optimizer/rule/mod.rs
- src/frontend/src/utils/mod.rs
- src/frontend/src/utils/rewrite_index.rs
as title and related issue.
#6544
> feat(optimizer):add ProjectAggMerge rule

- src/stream/src/executor/sort.rs
Reduce an indent and an unnecessary clone.
> style: minor style improvement to stream SortExecutor

- src/meta/src/storage/etcd_meta_store.rs
Fix bug introduced by https://github.com/risingwavelabs/risingwave/pull/6632, which didn't strip CF from key returned.
Because meta store snapshot list interface is not being used anywhere, it hasn't caused correctness issue yet.
* Installation and …
> fix(meta_store): strip cf from keys in snapshot list response

- src/stream/src/executor/dynamic_filter.rs
- src/stream/src/executor/hash_join.rs
- src/stream/src/executor/sort.rs
> refactor(row2): remove some unnecessary clones for Row2

- ci/scripts/build-other.sh
> fix(ci): fix PR ci pipeline

- src/meta/src/barrier/recovery.rs
> fix: fix determination of new nodes in migration

- e2e_test/batch/duckdb/join/iejoin/test_iejoin.test.slt.part
> test: Add duckdb iejoin test

- src/common/src/array/bytes_array.rs
- src/common/src/array/mod.rs
- src/common/src/array/utf8_array.rs
This is to reduce duplicated codes.
Also add the `BytesWritter`.
- #6426
> refactor(array): implement utf8 with bytes

- src/tests/simulation/src/slt.rs
As introduced more chaos when killing nodes in recovery, the cluster could be possible still under recovering when the write(insert/delete/update) request comes. Add retry logic in this PR.
We need to refine the error message in frontend and retry logic in simulation in the future.
* SQL commands, functions, and …
> fix: retry write when cluster is under recovering

- ci/workflows/main.yml
- ci/workflows/pull-request.yml
> chore(ci): increase timeout of build dev

- dashboard/proto/gen/connector_service.ts
- dashboard/proto/gen/hummock.ts
- dashboard/proto/gen/stream_plan.ts
- proto/stream_plan.proto
- src/frontend/src/stream_fragmenter/mod.rs
- src/meta/src/model/stream.rs
add fragment type chain
Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the …
> refactor(fragment): add fragment type chain

- README.md
- e2e_test/streaming/demo/ad_ctr.slt
- src/frontend/src/handler/create_source.rs
Please keep the types that apply …
> fix: broken docs website links

- ci/workflows/docker.yml
- ci/workflows/main-cron.yml
- ci/workflows/main.yml
- ci/workflows/pull-request.yml
Try to fix the port already allocated issue. https://github.com/risingwavelabs/risingwave/issues/6953
> ci: bump docker-compose-buildkite-plugin

- ci/docker-compose.yml
Try to fix the port already allocated issue. https://github.com/risingwavelabs/risingwave/issues/6953
> fix(ci): fix docker compose port allocated

- README.md
> fix(docs): update versions in README.md and fix CI badge

- e2e_test/batch/basic/func.slt.part
- src/frontend/src/binder/expr/function.rs
Implement `mod` function using implemented `modulus`.
Add corresponding e2e tests.
Match function name "mod" to expr type "modulus".
- Close [#6843](https://github.com/risingwavelabs/risingwave/issues/6843)
> feat(expr): Implement mod function

- src/connector/src/sink/kafka.rs
`info -> debug` otherwise print every record.
> chore(connector): fix log level

- ci/scripts/check.sh
- ci/scripts/cron-e2e-test.sh
- ci/scripts/cron-fuzz-test.sh
- ci/scripts/deterministic-recovery-test.sh
- ci/scripts/pr.env.sh
- ci/scripts/run-e2e-test.sh
- ci/scripts/run-fuzz-test.sh
- ci/scripts/run-unit-test.sh
> fix(ci): ci doesn't fail when ut fails 😲

- e2e_test/batch/duckdb/join/empty_joins.slt.part
> test: Add empty join

- src/frontend/src/optimizer/plan_node/logical_hop_window.rs
- Fix hop window column pruning.
Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where …
> fix(optimizer): fix hop window column pruning

- e2e_test/source/basic/datagen.slt
- src/common/src/field_generator/mod.rs
- src/connector/src/source/datagen/source/reader.rs
Will add tests.
(Seems `datagen` is not intended to be documented. So just leave a message/label here in case it is documented in the future)
> feat(connector): add datagen for array/list

- e2e_test/nexmark/create_sources.slt.part
- e2e_test/nexmark/drop_sources.slt.part
- e2e_test/source/nexmark_endless/nexmark_endless_part1.slt
- e2e_test/source/nexmark_endless/nexmark_endless_part2.slt
- e2e_test/source/nexmark_endless/nexmark_endless_part4.slt
> refactor(test): use unified nexmark source instead of three separated sources

- e2e_test/batch/types/interval.slt.part
- src/common/src/types/interval.rs
> fix(type): precision not enough should not throw Error (#7096) 

- src/utils/pgwire/src/pg_protocol.rs
Should close #7137
Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact …
> fix: flush error for Startup/Password/SslError

- src/frontend/src/optimizer/mod.rs
- src/frontend/src/optimizer/plan_node/batch_sort_agg.rs
- src/frontend/src/optimizer/plan_node/logical_agg.rs
- src/frontend/src/optimizer/rule/apply_join_transpose_rule.rs
- src/frontend/src/optimizer/share_source_rewriter.rs
- src/frontend/src/scheduler/distributed/stage.rs
- src/frontend/src/scheduler/plan_fragmenter.rs
- src/frontend/src/utils/column_index_mapping.rs
- src/sqlparser/src/tokenizer.rs
> style: fix clippy warnings 20221229

- src/tests/sqlsmith/src/lib.rs
- src/tests/sqlsmith/tests/frontend/mod.rs
- Does not seem to catch any errors yet, perhaps when:
- multi statement is supported: https://github.com/risingwavelabs/risingwave/pull/6849
- https://github.com/risingwavelabs/risingwave/issues/7132 is implemented
- we will start to see more errors caught.
* RisingWave …
> feat(sqlsmith): add round trip property test for parsing

- .github/workflows/dashboard_pr.yml
- proto/user.proto
Error message for dashboard ci is missing because `git merge-base` failed due to missing commit histories after #6629
fix https://github.com/risingwavelabs/risingwave/issues/7157
Also add a hint for `npm i` and use grouping to make the logs cleaner
> fix(ci): fix error message for dashboard ci

- ci/workflows/main.yml
As per the title
https://buildkite.com/risingwavelabs/main/builds/2676
> chore(ci): increase timeout for deterministic scaling test

- src/utils/runtime/src/lib.rs
As titled. Otherwise they are disabled by default in release mode, thus I cannot conveniently review the opts and configs.
* RisingWave cluster …
> chore(log): enable log for compute node and compactor node

- src/storage/src/hummock/sstable_store.rs
- src/storage/src/hummock/store/version.rs
- src/storage/src/monitor/local_metrics.rs
- src/storage/src/monitor/state_store_metrics.rs
Parallel Read for SST Meta
ref: 3. in https://www.notion.so/risingwave-labs/Ideas-on-Improving-Storage-Read-Performance-d397adbb6c384f32a0eae271b47ab2d8
Please create a release …
> perf(storage): Parallel Read for SST Meta

- README.md
> chore(docs): update versions in README.md

- src/stream/src/executor/hash_agg.rs
> refactor(hash_agg): rename some variables in `hash_agg` to make it clearer

- e2e_test/batch/basic/cte.slt.part
- src/frontend/src/binder/bind_context.rs
- src/frontend/src/binder/mod.rs
- src/frontend/src/binder/query.rs
- src/frontend/src/binder/relation/mod.rs
- src/frontend/src/binder/set_expr.rs
- support hierarchical context for CTE.
- Assign CteId for each CTE. …
> feat(binder): support hierarchical context for cte

- docs/cpu-profiling.md
- docs/developer-guide.md
- docs/memory-profiling.md
Migrate CPU & memory profiling guides from Quip. 
Not user-facing. It's a developer doc.
None
> doc: profiling guides

- e2e_test/batch/duckdb/join/test_complex_range_join.slt.part
> test: Add duckdb range join tests

- src/frontend/src/utils/stream_graph_formatter.rs
- src/meta/src/stream/stream_graph.rs
- src/stream/src/executor/now.rs
- src/stream/src/task/stream_manager.rs
hot fix by ban emitting watermark temporarily
#7226 
#7226
> feat(watermark): hot fix by ban emitting watermark temporarily

- e2e_test/batch/tpch/q15.slt.part
- e2e_test/streaming/tpch/views/q15.slt.part
- Since we have already supported share cte, let rewrite tpch q15 with cte for e2e test cases.
Please create a release note for your changes. In the release note, focus on the …
> chore(test): rewrite tpch q15 with cte for e2e test

- risedev.yml
As title. Caused by #7225
None
#7225
> fix: revert the changes to risedev.yml

- e2e_test/ddl/show.slt
- src/frontend/src/handler/show.rs
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/src/parser.rs
- src/sqlparser/tests/testdata/show.yaml
Implement show views
fix: https://github.com/risingwavelabs/risingwave/issues/7297
> feat(frontend): show views

- Cargo.lock
- src/tests/simulation/Cargo.toml
- src/tests/simulation/src/cluster.rs
- src/tests/simulation/src/kafka.rs
- src/tests/simulation/src/lib.rs
- src/tests/simulation/tests/sink.rs
fix #5856
Added simple tests for append_only and debezium sink …
> feat: add deterministic tests for scaling of sink

- .cargo/config.toml
- refine some comments for build 
#7429
#7375
> chore: refine build comments

- src/batch/src/task/broadcast_channel.rs
- src/batch/src/task/channel.rs
- src/batch/src/task/consistent_hash_shuffle_channel.rs
- src/batch/src/task/fifo_channel.rs
- src/batch/src/task/hash_shuffle_channel.rs
- src/batch/src/task/task_execution.rs
- src/tests/regress/src/schedule.rs
This reverts commit 5da5ad6dc5119229d0e2968b8f258b81bf422bad.
Revert previous commit, as it may brought some new bugs …
> fix: Revert "fix: broken channel reciever (#7367)"

- src/frontend/planner_test/tests/testdata/distribution_derive.yaml
- src/frontend/planner_test/tests/testdata/nexmark.yaml
- src/frontend/planner_test/tests/testdata/stream_dist_agg.yaml
- src/frontend/planner_test/tests/testdata/tpch.yaml
- src/frontend/planner_test/tests/testdata/union.yaml
- src/frontend/src/optimizer/plan_node/utils.rs
- Replace dot of the internal table column name with underline. …
> feat(frontend): better column name for internal table

- Cargo.lock
> chore(deps): fix lock conflicts

- Cargo.lock
- src/workspace-hack/Cargo.toml
> chore(deps): fix hakari generated toml

- ci/Dockerfile
- ci/build-ci-image.sh
- ci/docker-compose.yml
> chore: add netcat dep in docker

- src/compute/src/memory_management/memory_manager.rs
This change is _very_ simple. It improves some changes from another PR mentioned below.
#7397
> chore(memory_management): move to local imports

- src/frontend/src/catalog/source_catalog.rs
> fix: remove outdated comment

- src/frontend/src/handler/explain.rs
> chore: remove explain create source

- .mergify.yml
> ci: remove mergify priority

- src/compute/src/server.rs
- src/storage/compactor/src/server.rs
- src/storage/hummock_sdk/src/compact.rs
- src/storage/hummock_test/src/compactor_tests.rs
- src/storage/hummock_test/src/local_version_manager_tests.rs
- src/storage/src/hummock/compactor/compaction_utils.rs
- src/storage/src/hummock/compactor/compactor_runner.rs
- src/storage/src/hummock/compactor/context.rs
- src/storage/src/hummock/compactor/mod.rs
- src/storage/src/hummock/compactor/shared_buffer_compact.rs
- src/storage/src/hummock/event_handler/hummock_event_handler.rs
- src/storage/src/hummock/local_version/local_version_manager.rs
- src/storage/src/hummock/mod.rs
- src/storage/src/hummock/shared_buffer/shared_buffer_uploader.rs
- src/tests/compaction_test/src/delete_range_runner.rs
as title
~- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, …
> refactor(storage): refactor compactor context to make code more readable

- Cargo.lock
- src/frontend/src/session.rs
- src/utils/pgwire/Cargo.toml
- src/utils/pgwire/src/lib.rs
- src/utils/pgwire/src/pg_protocol.rs
- src/utils/pgwire/src/pg_server.rs
> feat: support multiple stmts in one run (simple query)

- README.md
- ci/workflows/main.yml
- fix main pipeline release step
- update the release version in readme
> fix(release): fix main pipeline release step && update readme

- ci/scripts/release.sh
> fix: fix release scripts

- ci/scripts/deterministic-recovery-test.sh
> fix(chore): Change comments in test to ci-3cn-2fe-3meta

- src/meta/src/lib.rs
It seems to be a mistake introduced in #7658
> fix: bug of MetaNodeOpts

- risedev.yml
> fix(ci): fix main-cron by increasing total compute node memory in compaction test

- src/frontend/planner_test/tests/testdata/batch_index_join.yaml
- src/frontend/planner_test/tests/testdata/expr.yaml
- src/frontend/src/optimizer/plan_node/batch_lookup_join.rs
> fix(optimizer): fix distributed batch lookup join shuffle columns

- src/connector/src/source/datagen/source/generator.rs
- stop datagen when sequence out of range
~- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer the issue)~
#7460
> fix(source): stop datagen when sequence out of range

- dashboard/proto/gen/catalog.ts
- proto/catalog.proto
- src/common/src/catalog/physical_table.rs
- src/frontend/src/catalog/table_catalog.rs
- src/frontend/src/optimizer/plan_node/logical_scan.rs
- src/frontend/src/optimizer/plan_node/stream_index_scan.rs
- src/frontend/src/optimizer/plan_node/stream_materialize.rs
- src/frontend/src/optimizer/plan_node/stream_table_scan.rs
- src/frontend/src/optimizer/plan_node/utils.rs
- src/frontend/src/scheduler/distributed/query.rs
- src/storage/hummock_sdk/src/filter_key_extractor.rs
- src/tests/compaction_test/src/delete_range_runner.rs
close https://github.com/risingwavelabs/risingwave/issues/7660.
> feat: add watermark columns in table catalog

- src/stream/src/executor/global_simple_agg.rs
- src/stream/src/executor/local_simple_agg.rs
- src/stream/src/executor/mview/materialize.rs
- src/stream/src/executor/sink.rs
> feat(stream): handle watermark in stream executors(part 1)

- src/frontend/planner_test/tests/testdata/explain.yaml
- src/frontend/planner_test/tests/testdata/nexmark_source.yaml
- src/frontend/planner_test/tests/testdata/share.yaml
- src/frontend/src/handler/explain.rs
support explain create table with connector
solve https://github.com/risingwavelabs/risingwave/issues/7518
> feat(explain): support explain create table with connector

- src/stream/src/common/table/state_table.rs
> refactor(state table): remove duplicate function used to create state table for unit tests

- src/common/src/system_param.rs
Don't use `RwError`;
Use `ok_or_else` to avoid unnecesary error creation.
To some extent mitigate #6205...
> refactor: error handling in system param

- Cargo.lock
- src/connector/Cargo.toml
- src/connector/src/parser/avro/parser.rs
- src/connector/src/parser/avro/util.rs
- src/connector/src/parser/debezium/avro_parser.rs
- support parsing avro decimal value #7940
- do some re-org …
> feat(source): support parsing avro decimal value

- src/batch/src/rpc/service/task_service.rs
- src/batch/src/task/task_execution.rs
- src/batch/src/task/task_manager.rs
- src/frontend/src/scheduler/distributed/query.rs
- src/frontend/src/scheduler/distributed/stage.rs
- src/utils/runtime/src/lib.rs
> fix(batch): Fix batch task leak

- src/connector/src/macros.rs
- src/connector/src/source/base.rs
- src/connector/src/source/cdc/source/reader.rs
- src/connector/src/source/datagen/source/reader.rs
- src/connector/src/source/dummy_connector.rs
- src/connector/src/source/filesystem/s3/source/reader.rs
- src/connector/src/source/google_pubsub/source/reader.rs
- src/connector/src/source/kafka/source/reader.rs
- src/connector/src/source/kinesis/source/reader.rs
- src/connector/src/source/nexmark/source/reader.rs
- src/connector/src/source/pulsar/source/reader.rs
- src/source/src/connector_source.rs
- src/source/src/fs_connector_source.rs
- rename `SplitReaderV2`
- Connector …
> chore: rename SplitReaderV2

- src/frontend/planner_test/tests/testdata/basic_query.yaml
- src/frontend/src/optimizer/plan_node/stream_table_scan.rs
- Not every stream scan contains distribution key.
</details>
#7959
> fix(streaming): fix stream scan distribution key

- e2e_test/batch/catalog/pg_conversion.slt.part
- src/frontend/src/catalog/system_catalog/mod.rs
- src/frontend/src/catalog/system_catalog/pg_catalog/mod.rs
- src/frontend/src/catalog/system_catalog/pg_catalog/pg_conversion.rs
Add pg_conversion to system catalog.
Add pg_conversion to system catalog.
</details>
Resolve #7958
> feat(frontend): add pg_conversion to system catalog

- src/cmd_all/src/playground.rs
- src/risedevtool/src/task/frontend_service.rs
- src/risedevtool/src/task/meta_node_service.rs
playground: don't panic when PREFIX_BIN is not set.
risedev: add command hint for user-managed fe/meta
> chore: some minor DX improvements

- src/cmd/src/bin/compactor.rs
- src/cmd/src/bin/compute_node.rs
- src/cmd/src/bin/ctl.rs
- src/cmd/src/bin/frontend_node.rs
- src/cmd/src/bin/meta_node.rs
- src/cmd_all/src/bin/risingwave.rs
- src/storage/backup/cmd/src/bin/backup_restore.rs
- src/tests/compaction_test/src/bin/compaction.rs
- src/tests/compaction_test/src/bin/delete_range.rs
- src/utils/runtime/src/lib.rs
Because it's too verbose for playground.
Also change the way to enable tokio console.
> chore: change storage log level to INFO for playground

- src/sqlparser/src/ast/statement.rs
> fix: fix typo of debezium avro source format

- .github/pull_request_template.md
A gentle reminder.
- Connector (sources & …
> chore: remind reviewers of requesting benchmark results

- Cargo.lock
- ci/scripts/e2e-iceberg-sink-test.sh
- src/storage/Cargo.toml
- src/storage/benches/bench_multi_builder.rs
- src/storage/src/hummock/compactor/mod.rs
- src/storage/src/hummock/mod.rs
- src/storage/src/hummock/sstable/bloom.rs
- src/storage/src/hummock/sstable/builder.rs
- src/storage/src/hummock/sstable/mod.rs
- src/storage/src/hummock/sstable/multi_builder.rs
- src/storage/src/hummock/sstable/writer.rs
- src/storage/src/hummock/sstable/xor_filter.rs
- src/storage/src/hummock/sstable_store.rs
> perf(bloom filter): replace bloom filter with xor filter

- src/meta/src/backup_restore/backup_manager.rs
- src/meta/src/backup_restore/meta_snapshot_builder.rs
- src/meta/src/backup_restore/restore.rs
- src/meta/src/manager/system_param/mod.rs
- src/meta/src/manager/system_param/model.rs
- src/storage/backup/src/meta_snapshot.rs
Same as #8077. Fix for release 0.1.17.
</details>
> fix(meta backup): add missing meta model in meta snapshot

- grafana/risingwave-dashboard.dashboard.py
This looks more informative to me.
</details>
> feat(metrics): lru manager: show the diff between watermark and now

- src/storage/src/hummock/sstable/mod.rs
- src/storage/src/hummock/sstable/xor_filter.rs
- src/storage/src/hummock/sstable_store.rs
cherry-pick https://github.com/risingwavelabs/risingwave/pull/8126
</details>
> fix(storage): fix calculate incorrect memory usage of sstable meta

- .github/workflows/license_check.yml
Seems the recent changes in skywalking-eyes have broken the GitHub Actions workflow (https://github.com/apache/skywalking-eyes/pull/150). Anyway it's [not a good practice](https://github.com/marketplace/actions/license-eye-header#check-license-headers) to use the `main` branch, let's use a fixed revision for it.
~~- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.
~~
- Connector (sources & …
> fix(ci): use a fixed revision for skywalking eyes

- e2e_test/batch/types/array_ty.slt.part
- risedev.yml
- src/common/src/array/column_proto_readers.rs
- src/common/src/array/decimal_array.rs
- src/common/src/array/list_array.rs
- src/frontend/planner_test/tests/testdata/nexmark_source.yaml
- src/frontend/planner_test/tests/testdata/predicate_pushdown.yaml
- src/frontend/planner_test/tests/testdata/share.yaml
- src/frontend/planner_test/tests/testdata/subquery.yaml
- src/frontend/planner_test/tests/testdata/time_window.yaml
- src/meta/src/lib.rs
- src/meta/src/rpc/election_client.rs
- src/storage/hummock_sdk/src/key.rs
- src/storage/src/hummock/compactor/iterator.rs
- src/storage/src/hummock/sstable/block.rs
- src/storage/src/hummock/sstable/builder.rs
- src/storage/src/hummock/sstable/utils.rs
- src/stream/src/executor/backfill.rs
> chore: merge fixes into v0.1.17-rc

- .typos.toml
- src/stream/src/executor/source/fs_source_executor.rs
> chore: fix typo: steam

- README.md
Update the production readiness description, and some other descriptions to be consistent with the product intro in the user documentation.
- [x ] My PR **DOES NOT** contain user-facing changes.
</details>
> chore: update production description in readme

- src/meta/src/barrier/progress.rs
- src/stream/src/executor/backfill.rs
- I used a `nexmark_20` as upstream mview and create a simple count mview on it to evaluate the current accuracy of the DDL progress. It is found that the progress should be able to decrease, because the downstream consumption rate might be slower than the upstream production rate. Another observation is that a calculated progress of 100% or 99% is of little value, thus establishing a lower bound value is more crucial than setting an upper bound value.
- …
> fix(meta): refine ddl progress

- src/frontend/planner_test/src/lib.rs
- src/frontend/planner_test/tests/testdata/agg.yaml
- src/frontend/planner_test/tests/testdata/column_pruning.yaml
- src/frontend/planner_test/tests/testdata/distribution_derive.yaml
- src/frontend/planner_test/tests/testdata/dynamic_filter.yaml
- src/frontend/planner_test/tests/testdata/join.yaml
- src/frontend/planner_test/tests/testdata/limit.yaml
- src/frontend/planner_test/tests/testdata/nexmark.yaml
- src/frontend/planner_test/tests/testdata/nexmark_source.yaml
- src/frontend/planner_test/tests/testdata/order_by.yaml
- src/frontend/planner_test/tests/testdata/over_window_function.yaml
- src/frontend/planner_test/tests/testdata/pk_derive.yaml
- src/frontend/planner_test/tests/testdata/predicate_pushdown.yaml
- src/frontend/planner_test/tests/testdata/subquery.yaml
- src/frontend/planner_test/tests/testdata/subquery_expr.yaml
- src/frontend/planner_test/tests/testdata/subquery_expr_correlated.yaml
- src/frontend/planner_test/tests/testdata/tpch.yaml
- src/frontend/planner_test/tests/testdata/union.yaml
> chore(test): separate optimized logical plan for planner test

- Cargo.lock
- src/cmd_all/Cargo.toml
- fix security issue
</details>
> chore(deps): bump tempfile to fix security issue

- src/stream/src/executor/aggregation/agg_group.rs
- src/stream/src/executor/global_simple_agg.rs
- src/stream/src/executor/hash_agg.rs
Split changes building logic for global simple agg and hash agg to make it clear.
</details>
> refactor(stream,agg): clean the messy `build_changes` method

- e2e_test/streaming/nexmark/create_views.slt.part
- e2e_test/streaming/nexmark/drop_views.slt.part
- e2e_test/streaming/nexmark/q106.slt.part
- e2e_test/streaming/nexmark/test_mv_result.slt.part
- e2e_test/streaming/nexmark/views/q106.slt.part
Found #8261 . Verify the results with PG.
</details>
> test: add nexmark_q106 into e2e tests

- .github/workflows/connector-node-integration.yml
> chore: bypass connector node ci when unnecessary

- src/meta/src/rpc/election_client.rs
- src/meta/src/rpc/server.rs
- src/meta/src/storage/wrapped_etcd_client.rs
- src/risedevtool/src/task/meta_node_service.rs
Signed-off-by: Shanicky Chen <peng@risingwave-labs.com>I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).
This PR modifies the etcd election client for the meta node, replacing the client with the EtcdRefreshClient and using long-lived connections. …
> fix: using multiple etcd nodes for meta-node

- ci/scripts/run-e2e-test.sh
- ci/workflows/main-cron.yml
- ci/workflows/pull-request.yml
[Previously increased `TEST_NUm=64` -> `TEST_NUM=100`](https://github.com/risingwavelabs/risingwave/pull/8259/files#diff-ea955d23713140916272f1d0af5b0613b2f199639d1a9293daad9b4cef2c14a9R145). 
Rolling it back due to timeout.
Also update cli options to be compatible with clap v4.
</details>
> fix(ci): avoid `end-to-end test (deterministic simulation)` timeout on `main-cron`

- dashboard/proto/gen/java_binding.ts
- proto/java_binding.proto
- src/java_binding/java/com_risingwave_java_binding_Binding.h
- src/java_binding/java/java-binding/src/main/java/com/risingwave/java/Demo.java
- src/java_binding/java/java-binding/src/main/java/com/risingwave/java/binding/Binding.java
- src/java_binding/src/iterator.rs
- src/java_binding/src/lib.rs
> feat(java-binding): support setting vnodes to read in java-binding read plan

- src/compute/src/server.rs
> fix(cherry-pick): avoid panicking when there's no enough memory for computing tasks

- src/frontend/planner_test/tests/testdata/append_only.yaml
- src/frontend/planner_test/tests/testdata/common_table_expressions.yaml
- src/frontend/planner_test/tests/testdata/delta_join.yaml
- src/frontend/planner_test/tests/testdata/distribution_derive.yaml
- src/frontend/planner_test/tests/testdata/dynamic_filter.yaml
- src/frontend/planner_test/tests/testdata/join.yaml
- src/frontend/planner_test/tests/testdata/mv_on_mv.yaml
- src/frontend/planner_test/tests/testdata/nexmark.yaml
- src/frontend/planner_test/tests/testdata/nexmark_source.yaml
- src/frontend/planner_test/tests/testdata/predicate_pushdown.yaml
- src/frontend/planner_test/tests/testdata/project_set.yaml
- src/frontend/planner_test/tests/testdata/share.yaml
- src/frontend/planner_test/tests/testdata/shared_views.yaml
- src/frontend/planner_test/tests/testdata/tpch.yaml
- src/frontend/src/optimizer/plan_node/generic/join.rs
- src/frontend/src/optimizer/plan_node/logical_join.rs
- To resolve #8322.
- The current implementation of streaming join's logical primary key includes the join keys from both sides, but in most cases, only one side is necessary. For instance, a left join requires only the left join key, while an inner join also needs the left join key, as it serves as the distribution key. Similarly, a right join necessitates only the right key. By including only the necessary key, we can improve the performance of streaming join operations.
- Installation and …
> feat(stream):  reduce unnecessary join keys as the logical pk of the join

- e2e_test/source/basic/datagen.slt
- src/common/src/field_generator/timestamp.rs
- src/meta/src/manager/catalog/mod.rs
- src/meta/src/rpc/ddl_controller.rs
My PR **DOES NOT** contain user-facing changes
closes #8335
> fix(meta): allow multiple internal tables while dropping table

- dashboard/components/Layout.tsx
- dashboard/components/SpinnerOverlay.tsx
- dashboard/mock-server.js
- dashboard/mock/fetch.sh
- dashboard/package-lock.json
- dashboard/package.json
- dashboard/pages/_app.tsx
- dashboard/pages/api/cluster.ts
- dashboard/pages/api/fetch.ts
- dashboard/pages/await_tree.tsx
- dashboard/pages/streaming_plan.tsx
- src/meta/src/dashboard/mod.rs
- src/meta/src/rpc/server.rs
- Add a page for dumping await-trees and display them in Monaco editor.
- Refactor some layout code to make it more responsive.
</details>
> feat(dashboard): dump await-tree of compute nodes

- e2e_test/extended_query/basic.slt
- src/frontend/src/handler/describe.rs
- src/frontend/src/handler/query.rs
- src/frontend/src/handler/variable.rs
- src/utils/pgwire/src/pg_protocol.rs
- src/utils/pgwire/src/pg_response.rs
as title.
fix #8089
</details>
> fix(pgwire): infer query type using parser rather than  naive string comparison 

- src/frontend/src/optimizer/plan_node/stream_watermark_filter.rs
> feat(watermark): add watermark derivation for watermark filter

- java/common-utils/src/main/java/com/risingwave/java/utils/MetaClient.java
- java/common-utils/src/main/java/com/risingwave/java/utils/VnodeHelper.java
- java/common-utils/src/test/java/com/risingwave/connector/utils/VnodeHelperTest.java
- java/java-binding-integration-test/src/main/java/com/risingwave/java/binding/Demo.java
- src/java_binding/gen-demo-insert-data.py
- src/java_binding/run_demo.sh
Currently we only two rows in our demo. In this PR, we generate demo data with a python script. 
Besides, we added unpinVersion method in our meta client.
</details>
> feat(java-binding): generate java binding demo data by a script

- docker/docker-compose.yml
- src/risedevtool/src/task/compactor_service.rs
- src/risedevtool/src/task/compute_node_service.rs
Exposing 5690/5691 ports on Meta service to localhost.
BTW, adjust the memory profiling args.
</details>
> fix: docker-compose.yml: expose ports

- src/batch/src/lib.rs
- src/batch/src/task/broadcast_channel.rs
- src/batch/src/task/channel.rs
- src/batch/src/task/consistent_hash_shuffle_channel.rs
- src/batch/src/task/fifo_channel.rs
- src/batch/src/task/hash_shuffle_channel.rs
> refactor: Use async function in trait rather GAT to simplify code

- src/stream/src/executor/now.rs
Let now executor send watermark after each chunk it sends.
</details>
> feat(now executor): now executor will send watermark

- ci/Dockerfile
- ci/build-ci-image.sh
- ci/docker-compose.yml
- ci/scripts/deterministic-scale-test.sh
> ci: reuse nextest archive for scale test

- e2e_test/batch/basic/query.slt.part
- src/batch/src/error.rs
- src/batch/src/task/broadcast_channel.rs
- src/batch/src/task/channel.rs
- src/batch/src/task/consistent_hash_shuffle_channel.rs
- src/batch/src/task/fifo_channel.rs
- src/batch/src/task/hash_shuffle_channel.rs
- src/batch/src/task/task_execution.rs
> fix(batch): Report data error in distributed mode correctly.

- src/stream/src/executor/watermark_filter.rs
> fix(stream): WatermarkFilter shouldn't asumed all vnodes have records

- e2e_test/batch/issue_7324.slt
> fix: Remove temporary workaround.

- src/frontend/src/optimizer/plan_node/generic/hop_window.rs
- src/frontend/src/optimizer/plan_node/generic/join.rs
- src/frontend/src/optimizer/plan_node/logical_apply.rs
- src/frontend/src/optimizer/plan_node/logical_hop_window.rs
- src/frontend/src/optimizer/plan_node/logical_join.rs
- src/frontend/src/optimizer/plan_node/stream_hop_window.rs
- move some methods into core struct
- refactor the join's predicate push down
- 
</details>
> refactor(optimizer): move some methods into core struct && refactor the join's predicate push down

- Cargo.lock
- src/object_store/Cargo.toml
- src/object_store/src/object/opendal_engine/gcs.rs
- src/object_store/src/object/opendal_engine/opendal_object_store.rs
- src/object_store/src/object/opendal_engine/oss.rs
- src/object_store/src/object/opendal_engine/webhdfs.rs
This PR will bump OpenDAL to latest version for new features and bug fixes.
Releast notes: https://docs.rs/opendal/0.30.1/opendal/docs/changelog/index.html
> chore: Bump OpenDAL to latest version

- src/stream/src/executor/hop_window.rs
> fix(streaming): hop executor handle watermark

- src/batch/src/error.rs
- src/batch/src/rpc/service/exchange.rs
- src/batch/src/task/task_execution.rs
> refactor: ExchangeWriter should report error throught status

- .typos.toml
> fix(ci): exclude `go.mod` and `go.sum` files for typos

- src/frontend/src/optimizer/plan_node/logical_join.rs
- src/frontend/src/optimizer/plan_node/logical_scan.rs
- src/frontend/src/optimizer/rule/index_selection_rule.rs
> chore(batch): reuse common logical for index selection

- src/storage/src/hummock/compactor/iterator.rs
remove useless code
</details>
> refactor(compactor): remove useless code

- src/frontend/src/binder/bind_param.rs
- src/frontend/src/binder/delete.rs
- src/frontend/src/binder/insert.rs
- src/frontend/src/binder/mod.rs
- src/frontend/src/binder/query.rs
- src/frontend/src/binder/relation/join.rs
- src/frontend/src/binder/relation/mod.rs
- src/frontend/src/binder/relation/share.rs
- src/frontend/src/binder/relation/subquery.rs
- src/frontend/src/binder/relation/watermark.rs
- src/frontend/src/binder/relation/window_table_function.rs
- src/frontend/src/binder/select.rs
- src/frontend/src/binder/set_expr.rs
- src/frontend/src/binder/statement.rs
- src/frontend/src/binder/update.rs
- src/frontend/src/binder/values.rs
To complete #8112
- support bind parameter 
- add related unit test.
</details>
> feat(frontend): support bind paramater 

- src/stream/src/executor/managed_state/join/mod.rs
enable prefetch for hash join with degree table
</details>
> perf(prefetch): enable prefetch for hash join with degree table

- .github/labeler.yml
- .github/pr-title-checker-config.json
- src/meta/src/lib.rs
> deprecate: remove host cmd line argument when starting meta node

- src/compute/src/lib.rs
- src/frontend/src/lib.rs
- src/storage/compactor/src/lib.rs
Merge #8574 first,
and closes #7678
- …
> deprecate: remove --host and --client-address args

- src/cmd_all/src/playground.rs
Due to https://github.com/risingwavelabs/risingwave/pull/8574, we will no longer use `host` for meta starting from v0.18, and must provide `--advertise-addr`.
~- [ ] I have requested …
> fix: add --advertise-addr to playground meta's opts

- e2e_test/batch/basic/join.slt.part
- src/common/src/session_config/mod.rs
- src/frontend/src/handler/explain.rs
- src/frontend/src/handler/query.rs
- src/frontend/src/scheduler/distributed/query.rs
- src/frontend/src/scheduler/plan_fragmenter.rs
- src/frontend/src/scheduler/worker_node_manager.rs
complete #7558 
- SQL commands
User can use `set batch_parallelism = <var>` to set parallelism to improve the parallelism of distributed query.
</details>
> feat(frontend): support BATCH_PARALLELISM

- dashboard/proto/gen/stream_plan.ts
- proto/stream_plan.proto
- src/common/src/catalog/schema.rs
- src/frontend/src/stream_fragmenter/mod.rs
- src/meta/src/model/stream.rs
- src/stream/src/executor/barrier_recv.rs
- src/stream/src/executor/mod.rs
- src/stream/src/from_proto/barrier_recv.rs
- src/stream/src/from_proto/mod.rs
We're going to extract the barrier receiver into a separate executor, to avoid code duplication in `Source`, `Now`, and `Values` in the future. This PR is the first step and introduces the executor in the compute node.
</details>
> feat(streaming): separate `BarrierRecv` executor

- src/frontend/planner_test/tests/testdata/nexmark_source.yaml
- src/stream/src/executor/sink.rs
- src/tests/simulation/src/nexmark/create_source.sql
Since we're directly passing chunks for datagen sources after #7612, we should ensure the types can be exactly matched.
</details>
> fix(test): use correct type for nexmark source planner test

- ci/workflows/main.yml
as title, main ci often timeout and get killed
Please …
> chore: add timeout to fix main ci

- src/risedevtool/src/task/connector_service.rs
> fix: fix connector start in risedev

- docs/developer-guide.md
According to the issue https://github.com/risingwavelabs/risingwave/issues/8608 
</details>
> doc: add notes for `.cargo/config.toml`

- .dockerignore
- .gitignore
- dashboard/.gitignore
> chore: remove accidentally pushed files

- ci/scripts/e2e-iceberg-sink-test.sh
- e2e_test/sink/iceberg_sink.slt
- src/stream/src/from_proto/sink.rs
> fix(sink): pass downstream pk when starting a sink

- .github/workflows/intergration_tests.yml
- integration_tests/postgres-sink/postgres_prepare.sql
> chore: fix docker compose test

- src/common/src/array/iterator.rs
It's on the critical path, and the safety is obvious.
</details>
> perf(array): avoid double bounds check in ArrayIterator

- src/tests/simulation/src/cluster.rs
- src/tests/simulation/tests/it/cascade_materialized_view.rs
- src/tests/simulation/tests/it/dynamic_filter.rs
- src/tests/simulation/tests/it/nexmark_chaos.rs
- src/tests/simulation/tests/it/singleton_migration.rs
- src/tests/simulation/tests/it/streaming_parallelism.rs
Introduce a `Session` struct and allow developers to run multiple statements in the same session with ease. 
For example, 
- one can set session variables in a separate statement before sending subsequent statements
- one should send `INSERT` and `FLUSH` in the same session to ensure the order …
> refactor(simulation): interface of running multiple queries in the same session

- Cargo.lock
- src/ctl/src/cmd_impl/bench.rs
- src/ctl/src/cmd_impl/hummock/list_kv.rs
- src/ctl/src/cmd_impl/hummock/sst_dump.rs
- src/ctl/src/cmd_impl/table/scan.rs
- src/ctl/src/common.rs
- src/ctl/src/common/context.rs
- src/ctl/src/common/hummock_service.rs
- src/ctl/src/lib.rs
- src/storage/Cargo.toml
- src/storage/hummock_sdk/src/key.rs
- src/storage/src/hummock/sstable/mod.rs
- src/storage/src/hummock/value.rs
- Dump without depending on meta service
- Print table value via new column aware encoding
- Print SST table_ids, sst_id, object path
- Print range tombstones
- New option to specify data_directory
- Pretty print key and value
Please keep the types …
> feat(sst-dump): support more features

- .github/workflows/connector-node-integration.yml
- .github/workflows/intergration_tests.yml
Fix: https://github.com/risingwavelabs/risingwave/actions/runs/4479382409/workflow
NA
NA
My PR **DOES NOT** contain user-facing changes.
> fix(ci): fix github workflow syntax error

- .github/workflows/dashboard_main.yml
> fix: Dashboard main should also setup protoc

- src/stream/src/executor/wrapper.rs
- src/stream/src/executor/wrapper/schema_check.rs
... to expose issues like #8354 and #8136 earlier. After #8479 there should be nearly zero cost for doing this check.
</details>
> fix(streaming): also enable schema check in release profile

- Cargo.lock
- Cargo.toml
- ci/scripts/build.sh
- ci/scripts/run-e2e-test.sh
- e2e_test/extended_mode/basic.slt
- e2e_test/extended_mode/type.slt
- src/tests/e2e_extended_mode/Cargo.toml
- src/tests/e2e_extended_mode/README.md
- src/tests/e2e_extended_mode/src/main.rs
- src/tests/e2e_extended_mode/src/opts.rs
- src/tests/e2e_extended_mode/src/test.rs
- src/workspace-hack/Cargo.toml
1. Add extended mode test.
2. Refine original extended mode test in e2e test.
related issue: #8560 #8112
</details>
> test: add e2e extended mode test

- src/risedevtool/src/task/meta_node_service.rs
- src/risedevtool/src/task/utils.rs
As title. Closes #8714 
</details>
> fix(risedev): disallow in memory state store when there is a compactor

- Makefile.toml
- e2e_test/streaming/bug_fixes/issue_8570.slt
- src/common/src/row/mod.rs
- src/stream/src/executor/managed_state/top_n/top_n_state.rs
- src/stream/src/executor/top_n/group_top_n.rs
- src/stream/src/executor/top_n/group_top_n_appendonly.rs
- src/stream/src/executor/top_n/top_n_appendonly.rs
- src/stream/src/executor/top_n/top_n_cache.rs
- src/stream/src/executor/top_n/top_n_plain.rs
- src/stream/src/from_proto/mod.rs
- src/stream/src/from_proto/top_n.rs
> fix(stream): fix TopN cache by only inserting into high if the row is top

- proto/hummock.proto
- src/meta/src/hummock/manager/compaction_group_manager.rs
- src/meta/src/hummock/manager/mod.rs
- src/meta/src/hummock/manager/tests.rs
- src/meta/src/hummock/manager/versioning.rs
- src/meta/src/hummock/test_utils.rs
- src/storage/benches/bench_compactor.rs
- src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
- src/storage/hummock_sdk/src/lib.rs
- src/storage/hummock_test/src/compactor_tests.rs
- src/storage/src/hummock/compactor/compactor_runner.rs
- src/storage/src/hummock/compactor/iterator.rs
> fix: V0.18.0 rc

- src/tests/simulation/src/slt.rs
> fix: Use debug log to record simulation time

- src/stream/src/executor/hash_agg.rs
Reduce a level of dereference.
</details>
> refactor(hash agg): directly use `AggGroup` instead of `Box<AggGroup>`

- src/tests/regress/data/schedule
- src/tests/regress/data/sql/arrays.sql
Enable selected passing test cases for array type. This can be a starting point and failed / unsupported queries can be handled individually.
> test(regress): enable some tests for array

- src/stream/src/executor/agg_common.rs
- src/stream/src/executor/global_simple_agg.rs
- src/stream/src/executor/hash_agg.rs
- src/stream/src/executor/test_utils.rs
- src/stream/src/from_proto/global_simple_agg.rs
- src/stream/src/from_proto/hash_agg.rs
Just a minor refactoring to `AggExecutorArgs`.
</details>
> refactor(stream agg): use generic in `AggExecutorArgs`

- src/meta/src/barrier/mod.rs
- src/meta/src/manager/cluster.rs
> fix: fix incorrect notify and barrier control flow

- src/meta/src/barrier/mod.rs
- src/meta/src/barrier/recovery.rs
- src/meta/src/barrier/schedule.rs
- src/meta/src/rpc/server.rs
- src/meta/src/stream/stream_manager.rs
- Make `BarrierManager::run` event-loop style, to avoid #8823 from happening.
- Reset the min-interval interval tick if there's a manually scheduled barrier.
- Make `send_latency_timer` more meaningful by recording the duration from its being scheduled to its being sent to compute nodes.
</details>
> refactor(meta): improve readability of barrier manager

- ci/scripts/run-fuzz-test.sh
- ci/workflows/main-cron.yml
- ci/workflows/pull-request.yml
> chore(ci): re-enable fuzz test on main-cron, but soft-fail

- src/common/src/util/column_index_mapping.rs
- src/frontend/planner_test/tests/testdata/distribution_derive.yaml
- src/frontend/planner_test/tests/testdata/dynamic_filter.yaml
- src/frontend/planner_test/tests/testdata/expr.yaml
- src/frontend/planner_test/tests/testdata/index_selection.yaml
- src/frontend/planner_test/tests/testdata/nexmark.yaml
- src/frontend/planner_test/tests/testdata/nexmark_source.yaml
- src/frontend/planner_test/tests/testdata/pk_derive.yaml
- src/frontend/planner_test/tests/testdata/project_set.yaml
- src/frontend/planner_test/tests/testdata/share.yaml
- src/frontend/planner_test/tests/testdata/subquery.yaml
- src/frontend/planner_test/tests/testdata/subquery_expr_correlated.yaml
- src/frontend/src/optimizer/logical_optimization.rs
- src/frontend/src/optimizer/plan_node/generic/join.rs
- src/frontend/src/optimizer/plan_node/logical_join.rs
- src/frontend/src/optimizer/rule/join_project_transpose_rule.rs
- src/frontend/src/optimizer/rule/mod.rs
- src/frontend/src/utils/condition.rs
> feat(frontend):add JoinProjectTranspose rule

- ci/workflows/main-cron.yml
Similar to https://github.com/risingwavelabs/risingwave/pull/8852
</details>
> chore(ci): do not retry fuzz test if fail

- src/stream/src/executor/mview/materialize.rs
close https://github.com/risingwavelabs/risingwave/issues/8739
</details>
> refactor(streaming): materialize executor only cache key when ignoring conflict

- ci/workflows/pull-request.yml
Statistics about it:
</details>
> ci: increase timeout for e2e java-binding test

- e2e_test/source/basic/ddl.slt
- proto/catalog.proto
- src/frontend/src/catalog/source_catalog.rs
- src/frontend/src/handler/create_source.rs
- src/frontend/src/handler/create_table.rs
- src/frontend/src/handler/show.rs
- src/meta/src/rpc/service/ddl_service.rs
- Resolve https://github.com/risingwavelabs/risingwave/issues/8879
- `Show sources` only displays sources without associated tables.
</details>
> fix(frontend,meta): fix show sources

- ci/scripts/release.sh
add java and maven in release script
> fix(ci): add java and maven in release script

- integration_tests/kafka-cdc-sink/Makefile.toml
> refactor: Simplify some commands in kafka cdc example.

- docker/docker-compose.yml
> fix: Disable generated warning in docker compose

- src/storage/src/hummock/store/version.rs
`iter_fetch_meta_duration` metrics is high in longevity test
</details>
> feat(sst meta): rollback fetch meta strategy

- integration_tests/kafka-cdc-sink/Makefile.toml
- integration_tests/kafka-cdc-sink/consume.sh
- integration_tests/kafka-cdc-sink/create_topic.sh
> refactor: Remove unnecessary bash scripts

- src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
apply `GroupTableChange` into version correctly
</details>
> fix(move table): apply version correctly (close #8764)

- src/frontend/src/optimizer/plan_node/batch_simple_agg.rs
- src/frontend/src/optimizer/plan_node/generic/agg.rs
- src/frontend/src/optimizer/plan_node/logical_agg.rs
- src/frontend/src/optimizer/plan_node/stream_global_simple_agg.rs
- src/frontend/src/optimizer/plan_node/stream_hash_agg.rs
Follow up of #8898, #8870, #8905
- I know what I'm doing :)
> refactor(plan_node): simplify agg-related nodes

- src/tests/regress/data/expected/case.out
- src/tests/regress/data/schedule
- src/tests/regress/data/sql/case.sql
> test(regress): enable `case` (also covers `coalesce` `nullif`)

- src/storage/src/hummock/event_handler/uploader.rs
fix shared buffer consistency issue
</details>
> fix(shared buffer): shared buffer consistency issue (close #8944)

- src/storage/src/hummock/iterator/delete_range_iterator.rs
> fix(delete range): maintain unused iters in `seek` (close #8928)

- src/stream/src/executor/source/source_executor.rs
> fix: unstable test by checking cardinality instead of actual values

- Makefile.toml
- src/risedevtool/Cargo.toml
> refactor: Add backtrace for risedev

- Cargo.lock
- src/rpc_client/Cargo.toml
- src/rpc_client/src/meta_client.rs
- src/tests/simulation/Cargo.toml
> fix: use original lru crate in meta client and simulation

- src/frontend/src/lib.rs
- src/frontend/src/scheduler/distributed/query.rs
- src/frontend/src/scheduler/distributed/query_manager.rs
- src/frontend/src/scheduler/distributed/stage.rs
- src/frontend/src/scheduler/hummock_snapshot_manager.rs
- src/frontend/src/scheduler/plan_fragmenter.rs
- src/frontend/src/session.rs
> refactor: Remove unused code

- ci/scripts/release.sh
> fix(ci): fix docker release scripts

- .cargo/audit.toml
- Cargo.lock
- Cargo.toml
- ci/Dockerfile
- ci/build-ci-image.sh
- ci/docker-compose.yml
- ci/scripts/check.sh
- ci/workflows/pull-request.yml
- src/common/Cargo.toml
- src/common/src/monitor/process_linux.rs
- src/connector/Cargo.toml
- src/rpc_client/Cargo.toml
- src/storage/Cargo.toml
close #8953
- ignore RUSTSEC-2020-0071
- replace mach (unmaintained) with mach2 (direct fork)
- bump spin from 0.9.6 (yanked) to 0.9.8
</details>
> fix: fix cargo audit issues and add audit to ci

- proto/meta.proto
- src/common/common_service/src/observer_manager.rs
- src/frontend/src/observer/observer_manager.rs
- src/meta/src/manager/catalog/mod.rs
> chore: notify function separately rather than inside the relation group

- ci/workflows/pull-request.yml
- src/java_binding/make-java-binding.toml
1.6MB -> 718KB -> 296KB
</details>
> ci: reduce java-binding log

- src/connector/src/macros.rs
- src/connector/src/source/datagen/source/reader.rs
- src/connector/src/source/nexmark/source/reader.rs
resolve #8760 
- Other (please …
> chore: add metrics for native chunk

- src/frontend/src/handler/extended_handle.rs
- src/tests/e2e_extended_mode/src/test.rs
> refactor(frontend): refine extended handle

- src/frontend/planner_test/tests/testdata/subquery.yaml
- src/frontend/planner_test/tests/testdata/time_window.yaml
- src/frontend/src/expr/input_ref.rs
- src/frontend/src/optimizer/logical_optimization.rs
- src/frontend/src/optimizer/plan_node/logical_hop_window.rs
- src/frontend/src/optimizer/plan_node/logical_join.rs
- src/frontend/src/optimizer/rule/join_project_transpose_rule.rs
- src/frontend/src/optimizer/rule/mod.rs
- src/frontend/src/optimizer/rule/pull_up_hop_rule.rs
related issue: #8121
</details>
> feat(frontend):support pull_up_hop rule

- src/common/benches/bench_hash_key_encoding.rs
> bench(common): add more benchmark cases for unaligned number of keys

- src/frontend/src/optimizer/plan_node/batch_group_topn.rs
- src/frontend/src/optimizer/plan_node/batch_topn.rs
- src/frontend/src/optimizer/plan_node/generic/top_n.rs
- src/frontend/src/optimizer/plan_node/logical_topn.rs
- src/frontend/src/optimizer/plan_node/stream_group_topn.rs
- src/frontend/src/optimizer/plan_node/stream_topn.rs
Follow-up of #8898, #8870, #8905, #8930, #8932.
- Yes
> refactor(plan_node): `TopN` simplification

- src/common/Cargo.toml
- src/common/benches/bench_data_chunk_encoding.rs
- src/common/benches/bench_hash_key_encoding.rs
- src/common/src/test_utils/mod.rs
- src/common/src/test_utils/rand_chunk.rs
> perf(encoding): add benchmark for data chunk encoding

- src/frontend/planner_test/src/lib.rs
- src/frontend/src/binder/mod.rs
- src/frontend/src/handler/create_sink.rs
- src/frontend/src/handler/create_source.rs
- src/frontend/src/handler/create_table_as.rs
- src/frontend/src/handler/create_view.rs
- src/frontend/src/handler/describe.rs
- src/frontend/src/handler/explain.rs
- src/frontend/src/handler/extended_handle.rs
- src/frontend/src/handler/query.rs
- src/frontend/src/handler/show.rs
- src/frontend/src/session.rs
- src/tests/sqlsmith/tests/frontend/mod.rs
Separate the query into more fine-grain phase so that handle in extended mode can reused  them.
related issue: #8112
</details>
> refactor(frontend): refactor query to reduce redundent code in extended mode

- src/common/src/array/column.rs
- src/common/src/array/data_chunk.rs
- src/common/src/array/stream_chunk.rs
- src/common/src/array/vis.rs
> feat: Estimate size for data chunk

- src/meta/src/stream/stream_graph/schedule.rs
Fix panic in creating streaming jobs when no compute nodes are alive.
</details>
> fix: reject ddl rather than panic when no available parallel units to schedule

- src/frontend/planner_test/tests/testdata/watermark.yaml
- src/frontend/src/optimizer/plan_node/stream_hash_join.rs
- If the first equal join key of stream hash join contains watermark columns of both sides, we call it `StreamWindowJoin`.
</details>
> feat(stream): stream window join naming

- src/connector/src/sink/mod.rs
> chore: improve error msg

- Cargo.lock
- e2e_test/source/basic/kafka.slt
- scripts/source/test_data/json_c.1
- src/connector/Cargo.toml
- src/connector/src/parser/canal/simd_json_parser.rs
- src/connector/src/parser/common.rs
- src/connector/src/parser/debezium/simd_json_parser.rs
- src/connector/src/parser/json_parser.rs
I have removed case-converting in simd-json.
</details>
> fix(parser): fetch json keys regardless of cases

- src/common/src/array/data_chunk.rs
> feat: Add tests for estimated_heap_size of data chunk

- src/frontend/src/optimizer/plan_node/batch_delete.rs
- src/frontend/src/optimizer/plan_node/batch_insert.rs
- src/frontend/src/optimizer/plan_node/batch_update.rs
- src/frontend/src/scheduler/distributed/stage.rs
- src/frontend/src/scheduler/local.rs
- src/frontend/src/scheduler/plan_fragmenter.rs
> fix(batch): correctly schedule stage containing dml

- src/storage/src/hummock/event_handler/uploader.rs
fix merged imms
View comments in #7368 for details.
</details>
> fix(storage): fix issues in the merged imms

- src/compute/src/memory_management/mod.rs
Recently longevity failed for OOM frequently. Currently, our memory management policy is not good enough, so let's increase reserved memory and have a try.
</details>
> fix: Increase reserved memory temporarily

- src/stream/benches/hash_agg.rs
- src/stream/src/executor/test_utils.rs
Mirror q17 executor agg calls.
https://github.com/risingwavelabs/risingwave/issues/9101 is still required to micro bench value state.
</details>
> bench(hash_agg): setup benchmark to mirror q17

- src/storage/src/hummock/compactor/compaction_utils.rs
- src/storage/src/hummock/compactor/mod.rs
> fix(compaction): handle generate_splits error instead of panic

- src/meta/src/manager/catalog/database.rs
- src/meta/src/manager/catalog/mod.rs
> fix: check function duplicated in meta

- src/connector/src/parser/json_parser.rs
- src/connector/src/parser/maxwell/simd_json_parser.rs
- src/connector/src/source/manager.rs
We want to be case-sensitive.
follow up of #9086 
- Installation …
> refactor(parser): remove unused name_in_lower_case

- src/utils/runtime/src/lib.rs
print trace logs in `risingwave_hummock_sdk` module
</details>
> feat(hummock sdk): print trace logs (close #9193)

- src/common/src/hash/key.rs
Make it more explicit in the hashkey structs what's the actual trait that bitmap should implement. May help the compiler too.
</details>
> chore(common): constrain the trait of bitmap in hashkeys

- e2e_test/batch/types/int256.slt.part
- e2e_test/batch/types/number_arithmetic.slt.part
- src/batch/src/executor/join/local_lookup_join.rs
- src/expr/macro/src/types.rs
- src/expr/src/expr/expr_case.rs
- src/expr/src/vector_op/arithmetic_op.rs
- src/expr/src/vector_op/cast.rs
- src/expr/src/vector_op/cmp.rs
- src/frontend/planner_test/tests/testdata/agg.yaml
- src/frontend/planner_test/tests/testdata/bushy_join.yaml
- src/frontend/planner_test/tests/testdata/column_pruning.yaml
- src/frontend/planner_test/tests/testdata/expr.yaml
- src/frontend/planner_test/tests/testdata/index_selection.yaml
- src/frontend/planner_test/tests/testdata/nexmark.yaml
- src/frontend/planner_test/tests/testdata/nexmark_source.yaml
- src/frontend/planner_test/tests/testdata/range_scan.yaml
- src/frontend/planner_test/tests/testdata/subquery.yaml
- src/frontend/planner_test/tests/testdata/subquery_expr_correlated.yaml
- src/frontend/planner_test/tests/testdata/time_window.yaml
- src/frontend/planner_test/tests/testdata/tpch.yaml
This PR attempts to remove `*number` in [file](https://github.com/risingwavelabs/risingwave/blob/d78530084e9e8e1e15025cef91eea4bee2152326/src/expr/macro/src/types.rs) and instead use `*int`, `*numeric`, and `*float` for more precise cast control. …
> refactor(common): replace `*number` in with `*int` `*numeric` and `*float`

- src/frontend/planner_test/tests/testdata/delete.yaml
- src/frontend/planner_test/tests/testdata/insert.yaml
- src/frontend/planner_test/tests/testdata/update.yaml
- src/frontend/src/optimizer/plan_visitor/mod.rs
- src/frontend/src/optimizer/plan_visitor/side_effect_visitor.rs
- src/frontend/src/optimizer/rule/trivial_project_to_values_rule.rs
As explained in https://github.com/risingwavelabs/risingwave/issues/9188#issuecomment-1510704905. Not sure whether this fix is a best practice.
Close #9188. 
</details>
> fix(optimizer): do not rewrite `Project` to `Values` for DML with `RETURNING`

- src/frontend/src/optimizer/plan_node/logical_agg.rs
- src/frontend/src/optimizer/rule/agg_dedup_group_key_rule.rs
- src/frontend/src/optimizer/rule/agg_project_merge_rule.rs
- src/frontend/src/optimizer/rule/apply_agg_transpose_rule.rs
- src/frontend/src/optimizer/rule/distinct_agg_rule.rs
- src/frontend/src/optimizer/rule/min_max_on_index_rule.rs
- src/frontend/src/optimizer/rule/translate_apply_rule.rs
- src/frontend/src/optimizer/rule/union_to_distinct_rule.rs
- src/frontend/src/planner/select.rs
I deleted `LogicalAgg::new` with sensible alternatives.
- Yes
> refactor(plan_node): Reorganize the construction of `LogicalAgg`

- src/stream/src/executor/hash_join.rs
streaming: hash join state table should not store rows which have null columns in inequality because they will never be matched.
</details>
> perf(hash join): state table do not store inequality null (close #9014)

- src/storage/src/hummock/compactor/shared_buffer_compact.rs
- src/storage/src/hummock/shared_buffer/shared_buffer_batch.rs
- src/storage/src/hummock/sstable/delete_range_aggregator.rs
fix some delete range related issues in merged imms
View comments in https://github.com/risingwavelabs/risingwave/pull/7368 for details.
</details>
> fix(storage): fix some delete range related issues in merged imm

- src/expr/src/vector_op/int256.rs
```
dev=> select hex_to_int256('0xffffffffffffffffffffffffffffffffffffffbea12ec055f5cxxxecxxxxxxxead');
ERROR:  QueryError: Expr error: Parse error: failed to parse hex '0xffffffffffffffffffffffffffffffffffffffbea12ec055f5cxxxecxxxxxxxe...'(truncated, total 68 bytes), invalid digit found in string
```
- SQL …
> chore: better error message for `hex_to_int256`

- src/config/ci-recovery.toml
- src/config/ci.toml
Checkpoint frequency is set to 5 in CI. So decrease the imm merge threshold to enable more merging tasks.
</details>
> chore(ci): enable more imm merge tasks in ci

- proto/catalog.proto
- proto/ddl_service.proto
- src/frontend/src/catalog/catalog_service.rs
- src/frontend/src/catalog/connection_catalog.rs
- src/frontend/src/catalog/function_catalog.rs
- src/frontend/src/catalog/index_catalog.rs
- src/frontend/src/catalog/mod.rs
- src/frontend/src/catalog/source_catalog.rs
- src/frontend/src/catalog/table_catalog.rs
- src/frontend/src/catalog/view_catalog.rs
- src/frontend/src/handler/create_connection.rs
- src/frontend/src/handler/drop_connection.rs
- src/frontend/src/handler/drop_function.rs
- src/frontend/src/handler/privilege.rs
- src/frontend/src/test_utils.rs
- src/meta/src/manager/catalog/database.rs
- src/meta/src/manager/catalog/mod.rs
- src/meta/src/rpc/service/ddl_service.rs
- src/rpc_client/src/meta_client.rs
Add owner field for connection and some privilege check to make all objects behave consistently. This is a pre-work for refactoring on catalog management.
</details>
> feat: add owner for connection and some check logic

- proto/expr.proto
- src/expr/src/expr/expr_trim_array.rs
- src/expr/src/expr/mod.rs
- src/frontend/src/binder/expr/function.rs
- src/frontend/src/expr/pure.rs
- src/frontend/src/expr/type_inference/func.rs
- src/tests/regress/data/sql/arrays.sql
trim_array ( array anyarray, n integer ) → anyarray
Trims an array by removing the last n elements. If the array is multidimensional, only the first dimension is trimmed.
close #9264
https://www.postgresql.org/docs/current/functions-array.html
</details>
> feat(expr): support trim_array

- src/common/src/test_utils/rand_stream_chunk.rs
- src/stream/src/executor/aggregation/agg_impl/foldable.rs
> feat(test_utils): use seed in rand_stream_chunk

- Cargo.lock
- src/connector/Cargo.toml
As requested in #9292.
- Support `zstd` compression type for Kafka connector.
</details>
> feat(connector): enable zstd compression for rdkafka

- src/meta/src/manager/cluster.rs
As title, I'm not sure if all failures in scaling test are caused by this bug described in #9256.
</details>
> fix: update worker ttl when register to meta

- README.md
Updated the readme with the information about RisingWave Cloud and telemetry.
</details>
> chore: Update README.md with RW cloud and telemetry info

- src/stream/src/executor/hash_agg.rs
abstraction not very useful
</details>
> refactor(stream-agg): remove Emitter

- src/meta/src/hummock/compaction/picker/ttl_reclaim_compaction_picker.rs
- src/storage/src/hummock/compactor/compaction_filter.rs
- src/storage/src/store.rs
ttl ms may exceed u32
</details>
> fix(ttl): ttl ms may exceed u32 (close #9302)

- src/common/src/util/mod.rs
- src/common/src/util/stream_graph_visitor.rs
- src/meta/src/manager/catalog/fragment.rs
- src/meta/src/rpc/metrics.rs
- src/meta/src/rpc/service/ddl_service.rs
- src/meta/src/stream/stream_graph.rs
- src/meta/src/stream/stream_graph/fragment.rs
> refactor: move stream graph visitor to common crate

- src/cmd/src/bin/compute_node.rs
- src/cmd_all/src/bin/risingwave.rs
Fix: jemalloc doesn't work after #9241
https://github.com/risingwavelabs/risingwave/blob/ad8c1958713513f8f10ca526f3743dadf8df8244/src/cmd/src/bin/compute_node.rs#L20-L21
which disabled task local allocator but also make the `GLOBAL` allocator to be the original one (instead of jemalloc)
</details>
> fix: jemalloc doesn't work after #9241

- src/meta/src/hummock/compaction/picker/ttl_reclaim_compaction_picker.rs
as title 
close https://github.com/risingwavelabs/risingwave/issues/9315
Please keep the types that apply to your changes, and remove the …
> fix(storage): fix ttl_compaction_picker with epoch physical_time

- src/meta/src/model/stream.rs
- src/meta/src/stream/scale.rs
- src/tests/simulation/tests/it/main.rs
- src/tests/simulation/tests/it/table.rs
Currently, we'll panic if we migrate or scale the `Source` fragment for tables. The key is not to `unwrap` the `find_stream_source`.
</details>
> fix(meta): correctly resolve source info for scaling

- src/connector/src/parser/canal/simd_json_parser.rs
as title, resolve #9340 
- Other …
> fix: canal json parser cast from date to time by mistake

- src/compute/src/memory_management/memory_manager.rs
Revert #8982
Perhaps caused by #8982. 
I will run test in this branch before merging.
</details>
> fix(memory-management): revert back to barrier_interval

- Cargo.lock
- src/common/Cargo.toml
- src/common/src/estimate_size/collections/lru.rs
- src/stream/Cargo.toml
- src/stream/src/cache/managed_lru.rs
- src/tests/simulation/Cargo.toml
a part of https://github.com/risingwavelabs/risingwave/issues/9341
</details>
> feat(stream): add `evict_except_cur_epoch` for managedLRUCache

- src/meta/src/rpc/server.rs
- src/meta/src/rpc/service/telemetry_service.rs
We start tracking clusters using memory mode. A `meta_backend` is added to telemetry report in #9111 
</details>
> feat(meta): remove etcd constrains

- src/storage/src/hummock/event_handler/uploader.rs
> fix(imm): return back imm when fail to start merge

- src/storage/src/hummock/compactor/compactor_runner.rs
- src/storage/src/hummock/compactor/mod.rs
- src/storage/src/hummock/compactor/shared_buffer_compact.rs
- src/storage/src/hummock/iterator/delete_range_iterator.rs
- src/storage/src/hummock/iterator/forward_user.rs
- src/storage/src/hummock/mod.rs
- src/storage/src/hummock/shared_buffer/shared_buffer_batch.rs
- src/storage/src/hummock/sstable/delete_range_aggregator.rs
- src/storage/src/hummock/sstable/mod.rs
- src/storage/src/hummock/sstable/multi_builder.rs
> fix(merged imm): fix panic when merging imms (close #9353)

- src/meta/src/hummock/manager/mod.rs
- src/storage/src/hummock/compactor/mod.rs
This check may cause compact task failed when user create mv. We have check whether the state table of this sst file has changed in is_compact_task_expired so it is not necessary
</details>
> fix(meta): remove group member table ids check

- ci/workflows/pull-request.yml
- src/tests/simulation/src/cluster.rs
- src/tests/simulation/src/main.rs
- src/tests/simulation/src/risingwave-scale.toml
as title
Added **restart_delay_secs** parameter with default value of 20  and set **max_heartbeat_interval_secs** in scaling tests to 15. Related: #9256 .
~- [ ] All checks passed in `./risedev …
> fix: attempt to fix the failure in scaling tests in CI temporarily.

- e2e_test/batch/types/array_ty.slt.part
- proto/expr.proto
- src/expr/src/expr/build.rs
- src/expr/src/vector_op/array_range_access.rs
- src/expr/src/vector_op/mod.rs
- src/frontend/src/binder/expr/mod.rs
- src/frontend/src/binder/expr/value.rs
- src/frontend/src/expr/pure.rs
- src/meta/src/manager/catalog/utils.rs
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/src/parser.rs
close #9357 
There are two corner cases that our behavior is different from PG though.
Enable access a slice of array by using array[1,3,5,7,10,999][N:M] syntax. Either `N` or `M` or both can be omitted.
</details>
> feat(array): support array range access

- ci/workflows/main.yml
- ci/workflows/pull-request.yml
- src/meta/src/lib.rs
- src/meta/src/rpc/election_client.rs
~- [ ] My PR **DOES NOT** contain user-facing changes.~
Please keep …
> fix: add timeout to keep-alive response to prevent potential split-brain.

- ci/scripts/run-e2e-test.sh
- src/risedevtool/src/task/compactor_service.rs
- src/risedevtool/src/task/compute_node_service.rs
- src/risedevtool/src/task/frontend_service.rs
- src/risedevtool/src/task/meta_node_service.rs
- src/risedevtool/src/task/utils.rs
- src/utils/runtime/src/lib.rs
close #9161
enable https://github.com/risingwavelabs/kube-bench/pull/126 …
> chore(log): create directories for query log

- src/frontend/src/optimizer/heuristic_optimizer.rs
- src/frontend/src/optimizer/rule/pull_up_correlated_predicate_rule.rs
- Check equivalent plans after applying an optimizer rule.
</details>
> chore(optimizer): check equivalent plans

- src/frontend/src/optimizer/plan_node/logical_multi_join.rs
Signed-off-by: Kevin Axel <kevinaxel@163.com>I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).
</details>
> fix(optimizer): isolated nodes with a tree structure

- Cargo.lock
- src/connector/Cargo.toml
fix https://github.com/risingwavelabs/risingwave/issues/9407
</details>
> fix: fix simd_json misaligned pointer dereference

- src/common/src/array/data_chunk.rs
- Refactor partitioning of datum sizes into its own function.
- Refactor initialization of buffer into its own function.
- Will reuse this functionality for https://github.com/risingwavelabs/risingwave/issues/9305.
</details>
> refactor(common): extract buffer initialization functionality

- src/utils/workspace-config/Cargo.toml
#9401, as mentioned in the thread, we want to enable debug log for chaos mesh tests. 
Chaos mesh tests are expected to fail much more than other tests, and we may need to debug it frequently.
But if there are better way to enable this usage, we can use that approach.
~- [ ] I have added fuzzing tests or opened an issue to track them.~ (Optional, recommended for new SQL features #7934).
~- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track …
> chore(log): enable debug log in release build

- Cargo.lock
- src/common/Cargo.toml
- src/common/proc_macro/src/config.rs
- src/common/proc_macro/src/estimate_size.rs
- src/common/proc_macro/src/lib.rs
- src/common/src/array/jsonb_array.rs
- src/common/src/array/list_array.rs
- src/common/src/array/serial_array.rs
- src/common/src/array/struct_array.rs
- src/common/src/estimate_size/mod.rs
- src/common/src/types/chrono_wrapper.rs
- src/common/src/types/decimal.rs
- src/common/src/types/interval.rs
- src/common/src/types/mod.rs
- src/common/src/types/num256.rs
- src/common/src/types/ordered_float.rs
- add proc macro to derive `EstimateSize`
- add `EstimateSize` for scalars.
close #9371
</details>
> feat(estimate_size): `EstimateSize` for scalars

- src/frontend/planner_test/tests/testdata/column_pruning.yaml
- src/frontend/planner_test/tests/testdata/predicate_pushdown.yaml
- src/frontend/src/optimizer/plan_node/logical_project_set.rs
> feat(optimizer): impl LogicalProjectSet::predicate_pushdown()

- src/meta/src/hummock/compaction/picker/tier_compaction_picker.rs
In tests, we found that the overlapping layer of l0 has many sst files and no longer triggers compaction.
According to the existing implementation, one of the reasons is that when the compaction file count exceeds the limit, we forget to set the waiting_enough_files flag, which may cause us to not select the files.
- bug fix
- unit test
- Other …
> fix(storage): fix TierCompactionPicker bug due to file_count_limit

- Cargo.lock
- src/connector/Cargo.toml
> fix: cherry-pick #9412 to v0.19.0-rc

- src/meta/src/hummock/compaction/picker/tier_compaction_picker.rs
Merge into release candidate branch 0.19.0-rc
> fix(storage): fix TierCompactionPicker bug due to file_count_limit (#9433)

- e2e_test/batch/types/interoperate_decimal_float.slt.part
- src/common/src/types/decimal.rs
- src/common/src/types/ordered_float.rs
- src/expr/src/vector_op/arithmetic_op.rs
- src/expr/src/vector_op/cast.rs
- src/expr/src/vector_op/cmp.rs
Merge into release candidate branch 0.19.0-rc
> fix(common): panic during large f64 to decimal conversion (#9396)

- .github/workflows/license_check.yml
> chore(license): also check on release candidate branches

- java/connector-node/risingwave-sink-iceberg/src/main/java/com/risingwave/connector/IcebergSink.java
- java/connector-node/risingwave-sink-iceberg/src/main/java/com/risingwave/connector/UpsertIcebergSink.java
Before this PR, we have a long standing transaction stored as a field of iceberg sink. As more operations are committed, the transaction will pile up, and all previous operations since the transaction was created will be included in a transaction commit, causing the commit time getting slower and slower. 
In this PR, we remove such transaction field in the PR, and instead start a new transaction in every `sync`. With this change, the commit time gets stable.
- …
> feat(sink): start a new transaction in every iceberg commit

- ci/workflows/pull-request.yml
- proto/task_service.proto
- src/common/src/config.rs
- src/compute/src/rpc/service/exchange_service.rs
- src/config/ci.toml
- src/config/example.toml
- src/rpc_client/src/compute_client.rs
- src/stream/src/executor/exchange/input.rs
- src/stream/src/executor/exchange/permit.rs
- src/stream/src/executor/merge.rs
- src/stream/src/task/mod.rs
Merge it to release candidate branch v0.19.0-rc.
</details>
> feat(streaming): limit concurrent barriers in exchange based on permits(#9427)

- src/stream/src/executor/dedup/append_only_dedup.rs
- src/stream/src/executor/dedup/cache.rs
- src/stream/src/executor/mview/materialize.rs
- src/stream/src/executor/top_n/group_top_n.rs
- src/stream/src/executor/top_n/group_top_n_appendonly.rs
- src/stream/src/executor/top_n/utils.rs
https://github.com/risingwavelabs/risingwave/pull/9459
</details>
> fix(stream): for release branch, add forgotten executor's caches epoch-updating for LRU

- src/batch/benches/hash_join.rs
- src/batch/src/executor/join/hash_join.rs
> feat: Early stop for hash join executor

- src/batch/benches/nested_loop_join.rs
- src/batch/src/executor/join/distributed_lookup_join.rs
- src/batch/src/executor/join/local_lookup_join.rs
- src/batch/src/executor/join/lookup_join_base.rs
- src/batch/src/executor/join/nested_loop_join.rs
> feat: Early stop for nest join and lookup join

- src/compute/src/memory_management/mod.rs
> revert: "fix: Increase reserved memory temporarily" (#9499)

- src/connector/src/source/kafka/private_link.rs
As title.
Please keep the types that apply to your changes, and …
> chore(log): print PrivateLink rewrite mappings for Kafka (cherry-pick)

- e2e_test/ddl/index.slt
- src/frontend/planner_test/tests/testdata/index_selection.yaml
- src/frontend/src/handler/create_index.rs
- src/sqlparser/src/ast/mod.rs
- src/sqlparser/src/parser.rs
- src/sqlparser/tests/sqlparser_common.rs
- Support specifying distributed columns for functional indexes. https://github.com/risingwavelabs/risingwave/issues/8975
- Support specifying distributed columns for functional indexes.
</details>
> feat(frontend): support distributed by columns for functional indexes

- src/stream/src/executor/top_n/top_n_cache.rs
- src/stream/src/executor/top_n/top_n_state.rs
> fix(top n cache): avoid panic when `limit==1` (close #9500)

- src/stream/src/executor/top_n/top_n_cache.rs
- src/stream/src/executor/top_n/top_n_state.rs
This PR is the same as #9501 
</details>
> fix(top n cache): avoid panic when limit==1

- src/storage/src/hummock/error.rs
- src/storage/src/hummock/state_store.rs
> refactor: improve error message when read barrier fails (#9529)

- src/compute/src/memory_management/policy.rs
> feat(memory-manager): improve memory policy (#9516)

- ci/workflows/main-cron.yml
Compilation time variance. Previous:
Now (today https://buildkite.com/risingwavelabs/main-cron/builds/462#0187c978-4503-4f07-a10f-c03c46c5c109):
</details>
> chore(ci): increase micro-bench timeout.

- .github/pr-title-checker-config.json
- CONTRIBUTING.md
> ci: error message for pr title checker

- README.md
To highlight *set up the development environment*.
</details>
> doc: tweak instruction for compile from source

- src/common/Cargo.toml
- src/common/benches/bench_array.rs
Add benchmark for `bigint`. Shorten feedback loop for #9527. The rest can come later.
</details>
> bench(common): add array bench for bigint

- ci/scripts/gen-flamegraph.sh
- ci/workflows/pull-request.yml
Increase workload, currently it is just 100,000,000 events. Change to 400,000,000 events.
Bottleneck is likely storage space on the machine. So don't increase to 1000,000,000 first.
</details>
> chore(ci): increase nexmark events for flamegraph generation

- Cargo.lock
- scripts/source/prepare_ci_pubsub/Cargo.toml
- scripts/source/prepare_ci_pubsub/src/main.rs
- src/connector/Cargo.toml
- src/connector/src/source/google_pubsub/enumerator/client.rs
- src/connector/src/source/google_pubsub/source/reader.rs
- src/risedevtool/Cargo.toml
- src/risedevtool/src/task/task_pubsub_emu_ready_check.rs
- src/workspace-hack/Cargo.toml
- remove unused `wiremock` -> Only one `rand` now!
- bump `google-cloud-pubsub` (breaking change: `cancel` parameter removed) -> Only one `prost` now!
</details>
> build: optimize dependencies

- src/common/src/hash/key.rs
As per title. Just decouple Serialized and FixedKey's build from hash_code function. Large improvement for some cases (`Key64`).
</details>
> perf(common): don't estimate for fixed size key

- Cargo.lock
- src/risedevtool/Cargo.toml
- src/risedevtool/src/task/task_kafka_ready_check.rs
- src/workspace-hack/Cargo.toml
reduce dependencies.
</details>
> build: use rdkafka instead of kafka in risedev

- Cargo.lock
- src/expr/Cargo.toml
- src/expr/src/vector_op/string_to_array.rs
Better implementation of `string_to_array`, thanks to comments from @xiangjinwu 
</details>
> refactor(expr): better implementation of `string_to_array`

- src/batch/src/executor/table_function.rs
- src/common/src/array/data_chunk.rs
Currently, the table function executor will accumulate all data chunks before sending out, this may consume a lot of memory if user inputs a large input, for example `range(0, 999999999, 1)`
</details>
> fix(batch): Fix table function executor

- src/batch/src/task/task_execution.rs
> fix(batch):add shutdown rx in execution

- src/batch/src/task/task_execution.rs
Add log to help debugging.
</details>
> fix: Add log to batch task status change

- src/meta/src/barrier/recovery.rs
- src/rpc_client/src/lib.rs
> chore: change log level in recovery and log addr when failed to create stream client

- src/expr/src/vector_op/like.rs
See test case.
In this PR, we respect the default escape '\', but we don't support specify `ESCAPE` with other characters.
</details>
> fix(expr): support default escape '\' in like

- .github/workflows/connector-node-integration.yml
Because connector node ci jobs changed to required, we also need to trigger them in merge queue.
</details>
> fix(ci): trigger connector node ci jobs in merge queue

- src/meta/src/hummock/manager/mod.rs
- src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
> fix(sub level): insert sub level into correct pos in `HummockVersion`

- ci/scripts/cron-fuzz-test.sh
- ci/scripts/pr-fuzz-test.sh
- ci/scripts/run-fuzz-test.sh
- ci/workflows/main-cron.yml
- ci/workflows/pull-request.yml
- src/tests/sqlsmith/README.md
- src/tests/sqlsmith/scripts/gen_queries.sh
- src/tests/sqlsmith/src/sql_gen/types.rs
Fix it and re-enable fuzzing (just for frontend) per PR and in `main-cron`.
Frontend tests fail relatively less often. Can easily split into its own pipeline too.
Following PRs will try to fix up e2e fuzzing too, seems like that's failing as well.
</details>
> fix(sqlsmith): fix failing frontend tests

- Cargo.lock
- src/common/Cargo.toml
- src/common/src/config.rs
- src/config/example.toml
Achieve this by a unit test so no extra step is required.
Preview:
</details>
> test(config): check whether `example.toml` is up-to-date

- src/common/src/memory/alloc.rs
- src/common/src/memory/mod.rs
> feat: Introduce monitored alloc with mem context

- src/meta/src/stream/source_manager.rs
This PR attempts to introduce an experimental way of supporting shard reduction for split. Currently, we use an in-place mode to drop splits so that it does not affect other splits that have not changed.
This pull request adds a new `SplitDiffOptions` struct that allows for customizable control over splitting behavior. The `diff_splits` function has been updated to take this new struct as a parameter, and now checks if any splits were dropped during a diff, displaying a warning if scale-in is not enabled. Additionally, the `pre_allocate_splits` and `assign_fragments` functions have been updated to use the new …
> feat(source): supports in-place split dropping in source manager

- e2e_test/batch/basic/table_with_default_columns.slt.part
- src/frontend/planner_test/tests/testdata/update.yaml
- src/frontend/src/binder/update.rs
- src/frontend/src/catalog/table_catalog.rs
`update set` to `default` is supported for **SINGLE** column set. It might require significant changes for parser to support something like `set (v1, v2) = (default, 1)` and we feel like it maybe not worthy.
~~- [ ] My PR **DOES NOT** contain user-facing changes.~~
<details><summary>support update to default</summary>
</details>
support update to default
> feat(frontend): `update set` to `default`

- src/storage/backup/integration_tests/common.sh
> fix(test): use verbose list-version

- .typos.toml
- Cargo.lock
- src/object_store/Cargo.toml
- src/object_store/src/object/opendal_engine/opendal_object_store.rs
- src/workspace-hack/Cargo.toml
OpenDAL provide `scan` recently, which will list all objects instead of all dirs, we should use `scan` to be compatible with s3.
- Connector …
> refactor(storage): OpenDAL list object should be compatible with s3

- src/storage/src/hummock/compactor/compactor_runner.rs
- src/storage/src/hummock/compactor/iterator.rs
As we continue to create and delete tables, the residual data from the tables will still take up compactor resources. This pr skips non-existent data from the table and block perspective to reduce resource usage.
part of https://github.com/risingwavelabs/risingwave/issues/9706
</details>
> feat(storage): compactor skip sst and block related to non-existent able_id

- src/frontend/planner_test/tests/testdata/subquery.yaml
- src/frontend/src/optimizer/logical_optimization.rs
- src/frontend/src/optimizer/plan_visitor/plan_correlated_id_finder.rs
- src/frontend/src/optimizer/rule/apply_eliminate_rule.rs
- src/frontend/src/optimizer/rule/apply_join_transpose_rule.rs
- src/frontend/src/optimizer/rule/mod.rs
- Rename `ApplyScanRule` to `ApplyEliminateRule`.
- `ApplyEliminateRule` can eliminate apply operators if there is no correlated id on its RHS so that we would miss operators like `Source` as before. Resolve https://github.com/risingwavelabs/risingwave/issues/9690.
</details>
> fix(optimizer): fix subquery on sources

- src/frontend/src/expr/mod.rs
- src/frontend/src/expr/utils.rs
fix some timestamp issue in watermark derivation due to daylight saving time
</details>
> fix(timestamp): fix some timestamp issue in watermark derivation

- src/frontend/src/optimizer/rule/over_agg_to_topn_rule.rs
close https://github.com/risingwavelabs/risingwave/issues/9400
```SQL
dev=> create table t(x int, y int);
CREATE_TABLE
dev=> select * from
(select *, row_number() over(PARTITION BY y ORDER BY x) rank from t)
where rank<3 AND x>y order by x;
NOTICE:  fail to transform overAgg to groupTopN: the rank cannot be included in the outer select_list, see https://www.risingwave.dev/docs/current/sql-pattern-topn/ for more information
ERROR:  QueryError: Feature is not yet implemented: Batch over window is not implemented yet
Tracking issue: https://github.com/risingwavelabs/risingwave/issues/9124
```
just improve the error message …
> feat(optimizer): refactor group topn convert && improve err msg

- src/frontend/planner_test/tests/testdata/explain.yaml
- src/frontend/planner_test/tests/testdata/expr.yaml
- src/frontend/planner_test/tests/testdata/subquery_expr_correlated.yaml
- src/frontend/planner_test/tests/testdata/tpch.yaml
- src/frontend/src/optimizer/logical_optimization.rs
- src/frontend/src/optimizer/rule/over_agg_to_topn_rule.rs
fix https://github.com/risingwavelabs/risingwave/issues/9566
</details>
> fix(optimizer): fix convert over to group topn

- src/meta/src/hummock/compaction_scheduler.rs
> fix(storage): skip the first tick for compaction scheduler's interval trigger

- ci/scripts/integration-tests.sh
- ci/workflows/integration-tests.yml
- integration_tests/scripts/clean_demos.py
- integration_tests/twitter-pulsar/data_check
> fix(ci): fix integration test pipeline matrix limits

- src/expr/src/vector_op/md5.rs
- src/tests/regress/data/sql/strings.sql
As show in https://github.com/risingwavelabs/risingwave/issues/8847, md5 for bytea input is implemented in this PR
</details>
> feat(md5): support md5 for bytea

- src/connector/src/parser/avro/parser.rs
fix https://github.com/risingwavelabs/risingwave/pull/9689#discussion_r1190848037
Please keep the types that apply to your changes, …
> chore: fix misuse a private func

- docker/Dockerfile
- docs/developer-guide.md
> chore: remove unnecessary apt-install in docker/developer-guide

- src/object_store/src/object/s3.rs
Report warning when the http connection limitation is triggered, in order to let upper layer be aware of the increasing of latency.
</details>
> chore(object store): add log for s3 timeout retry

- src/frontend/planner_test/tests/testdata/over_window_function.yaml
- src/frontend/planner_test/tests/testdata/tpch.yaml
- src/frontend/src/optimizer/rule/project_merge_rule.rs
as title, fix https://github.com/risingwavelabs/risingwave/issues/9566
</details>
> fix(optimizer): project merge rule merge recursively

- ci/scripts/build-simulation.sh
- ci/scripts/build.sh
- ci/scripts/common.sh
- ci/scripts/deterministic-e2e-test.sh
- ci/scripts/deterministic-recovery-test.sh
- ci/scripts/docslt.sh
- ci/scripts/e2e-test-parallel-for-opendal.sh
- ci/scripts/e2e-test-parallel.sh
- ci/scripts/pulsar-source-test.sh
- ci/scripts/regress-test.sh
- ci/scripts/run-e2e-test.sh
- ci/scripts/run-fuzz-test.sh
build step Upload artifacts 26s->12s
</details>
> ci: compress artifacts

- src/frontend/src/optimizer/plan_node/logical_join.rs
> fix(optimizer): join simplify_outer should consider output indices

- src/common/src/types/mod.rs
To make it easier to maintain. 💦💦💦
This seems the only one we can refactor among all `match data_type`. We should really make more methods directly implement on `impl Scalar` types instead of the type-erased one (`ScalarImpl`), which can be more generic and efficient to use.
</details>
> refactor(common): use `for_all_type_pairs` for `create_array_builder`

- e2e_test/streaming/group_top_n.slt
- src/frontend/planner_test/tests/testdata/over_window_function.yaml
- src/frontend/src/optimizer/plan_node/generic/top_n.rs
- src/stream/src/executor/top_n/group_top_n.rs
- src/stream/src/executor/top_n/group_top_n_appendonly.rs
- src/stream/src/executor/top_n/top_n_appendonly.rs
- src/stream/src/executor/top_n/top_n_plain.rs
- src/stream/src/executor/top_n/top_n_state.rs
- src/stream/src/executor/top_n/utils.rs
…
fix https://github.com/risingwavelabs/risingwave/issues/7322, TODO https://github.com/risingwavelabs/risingwave/issues/9802
</details>
> fix(optimizer): do not dedup column in order key which is also in group key

- Makefile.toml
> fix(clippy): typo in `RISINGWAVE_FEATURE_FLAGS`

- e2e_test/batch/catalog/pg_database.slt.part
- src/frontend/src/catalog/system_catalog/pg_catalog/pg_database.rs
Fix #9800 
Add `dattablespace` into `pg_catalog`.
Please check …
> feat(pg_catalog): add dattablespace into pg_catalog

- src/frontend/planner_test/tests/testdata/agg.yaml
- src/frontend/planner_test/tests/testdata/order_by.yaml
- src/frontend/src/optimizer/plan_node/batch_group_topn.rs
fix https://github.com/risingwavelabs/risingwave/issues/7332
</details>
> fix(opt): batch group topn executor does not give any order guarantee 

- src/batch/src/executor/source.rs
- src/connector/src/sink/kafka.rs
Fix #9826. Also partially solve #9771. Because upsert will introduce `Op::Delete`, we can only
do the selection after creating materialized view here.
</details>
> fix(upsert): Fix Kafka upsert sink output and upsert source unreachable

- ci/scripts/e2e-test-parallel-for-opendal.sh
> fix(ci): opendal e2e test clean data after ci-kill 

- README.md
also removed the installation instrutions to point to user docs, to avoid making the same changes twice whenever we have a new version
- Updated the logo
- Added a new diagram
- Removed installation instructions
- Provided pointers to various sections of our user docs
</details>
> chore(doc): Update README.md to use the new logo and new diagram

- ci/scripts/deterministic-e2e-test.sh
- ci/scripts/run-fuzz-test.sh
- debug.sh
- debug2.sh
- debug3.sh
- src/tests/sqlsmith/scripts/gen_queries.sh
- src/tests/sqlsmith/src/runner.rs
- src/tests/sqlsmith/src/sql_gen/expr.rs
- src/tests/sqlsmith/src/validation.rs
Closes #9861 
Closes #9882 
Closes #9860 
</details>
> chore(sqlsmith): bump inserts from 10 to 50

- src/meta/src/hummock/compaction/overlap_strategy.rs
- src/meta/src/hummock/compaction/picker/base_level_compaction_picker.rs
- src/meta/src/hummock/compaction/picker/manual_compaction_picker.rs
- src/meta/src/hummock/compaction/picker/min_overlap_compaction_picker.rs
Optimize process of pick compact task.
This PR calculates overlap info more precisely to avoid corresponding check and `BTreeSet` operations later.
</details>
> perf(compaction): optimize process of pick compact task

- ci/scripts/docker-hdfs.sh
- docker/Dockerfile.hdfs
Add multi-arch docker file for HDFS feature. Because the HDFS feature currently is not open by default, I create a separate shell script and docker file. When needed, we need to open the HDFS feature manually and compile it using the script.
</details>
> feat(ci): add dockerfile and script for HDFS

- src/connector/src/source/kinesis/source/reader.rs
> fix: stop stream when kinesis resource not exist

- src/meta/src/storage/etcd_retry_client.rs
- src/object_store/src/object/s3.rs
~~- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.~~
Please …
> chore: code style optimization for timeout retry

- ci/scripts/integration-tests.sh
> fix(ci): add integration test clean up

- src/compute/src/memory_management/mod.rs
> chore(log): warn of storage memory exceeding soft limit

- .vscode/settings.json.example
- src/connector/Cargo.toml
- src/workspace-hack/Cargo.toml
As this hurts DX (can't run tests via Clion/VS Code without OpenSSL (But they can run tests if they `cargo build` first...))
related [#9852](https://github.com/risingwavelabs/risingwave/issues/9852)
</details>
> fix(build): force ssl-vendored temporarily

- Cargo.lock
- src/common/Cargo.toml
- src/common/src/monitor/process_linux.rs
- src/connector/Cargo.toml
- src/connector/src/source/filesystem/s3/enumerator.rs
- src/expr/Cargo.toml
- src/expr/src/vector_op/to_char.rs
- src/storage/Cargo.toml
- src/workspace-hack/Cargo.toml
> build: eliminate some duplicated dependencies

- java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/JsonDeserializer.java
Fix https://github.com/risingwavelabs/risingwave/issues/9968
</details>
> fix(sink): fix null pointer in jdbc sink

- docker/docker-compose.yml
Reported by community user `@Jiacheng Yang`. Thanks a lot!
> Hi, I tried to docker-compose up from the docker directory, but got this error:
> 
> ```
> $ docker-compose up
> ERROR: The Compose file './docker-compose.yml' is invalid because:
> Unsupported config option for services.etcd-0: 'commarisingwavend'
> 'name' does not match any of the regexes: '^x-'
> ```
> 
> You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service …
> fix(docker): fix docker-compose.yml

- e2e_test/udf/python.slt
- e2e_test/udf/test.py
- src/udf/python/risingwave/udf.py
> fix(udf): fix functions that return `jsonb[]` or struct

- src/storage/src/hummock/store/version.rs
> fix: report correct number for overlapping_iter_count

- src/meta/src/lib.rs
> chore: fix a typo for vpc_id

- src/frontend/src/catalog/system_catalog/pg_catalog/mod.rs
Fix #10026 
BTW, how can we add some compile-time checks in the catalog framework so that we can avoid such bugs?
</details>
> fix(catalog): missing column in pg_attributes output

- Cargo.lock
- src/expr/Cargo.toml
- src/expr/benches/expr.rs
- src/expr/src/agg/mod.rs
- src/expr/src/expr/build.rs
- src/expr/src/expr/expr_binary_nonnull.rs
- src/expr/src/expr/mod.rs
- src/expr/src/sig/agg.rs
- src/expr/src/sig/func.rs
- src/expr/src/sig/mod.rs
- src/expr/src/sig/table_function.rs
- src/expr/src/table_function/mod.rs
- src/expr/src/vector_op/cast.rs
- src/stream/src/executor/dynamic_filter.rs
- src/stream/src/executor/watermark_filter.rs
- src/stream/src/from_proto/hash_join.rs
- Extract a utility to debug printing the function signature.
- Build for special expression types first, then look up the signature map to achieve better error reporting. (#10037)
```diff
-Expr error: Unsupported function: Ok(Cast)
+Expr error: Unsupported function: cast(int64) -> boolean
``` …
> refactor(expr): unify function signature display

- ci/scripts/gen-flamegraph.sh
> chore(ci): pin addr2line toolchain and version

- src/common/src/config.rs
- src/config/example.toml
- src/meta/src/hummock/manager/mod.rs
- src/meta/src/lib.rs
- src/meta/src/manager/env.rs
- src/object_store/src/object/mod.rs
- src/object_store/src/object/s3.rs
close https://github.com/risingwavelabs/risingwave/issues/9996
- bucket lifecycle is configured by cloud
- s3 compatible storage do not config lifecycle
-~~ [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)~~
~~- [ ] I have requested …
> refactor(s3): config lifecycle on meta

- src/object_store/src/object/mod.rs
> chore(meta): don't warn in-memory Meta Backup for benchmarking

- ci/scripts/release.sh
After #10011, we also use `sccache` for the release script since we move the `export`s into `common.sh`:
https://github.com/risingwavelabs/risingwave/blob/d4606d17ebf31d9de0029f276f4b3b7faf33268f/ci/scripts/common.sh#L7-L12
I'm not sure whether this is intended, but we have to also install sacache in the release script, or compiling will fail: https://buildkite.com/risingwavelabs/main/builds/4329#0188669c-725b-4c7f-ad45-a454c9f2e6c7.
This PR should also be cherry-picked to `0.19.0-rc` branch. …
> fix(ci): release script for sccache

- Cargo.lock
- Cargo.toml
- ci/scripts/release.sh
- Cherry-pick of #10057.
- Also bump the version in `Cargo.toml`, resooolve https://github.com/risingwavelabs/risingwave/issues/9884#issuecomment-1567786179
</details>
> fix(ci): release script for sccache and bump version

- e2e_test/source/basic/nosim_kafka.slt
- src/frontend/src/handler/create_source.rs
The `row_id_index` should be cleared if the table schema is be replaced with avro schema inferring.
- Installation and …
> fix(connector): upsert avro schema inferring

- Cargo.lock
- src/cmd/src/bin/compactor.rs
- src/cmd/src/bin/compute_node.rs
- src/cmd/src/bin/ctl.rs
- src/cmd/src/bin/frontend_node.rs
- src/cmd/src/bin/meta_node.rs
- src/cmd/src/lib.rs
- src/cmd_all/Cargo.toml
- src/cmd_all/src/bin/risingwave.rs
The mystery of reproducibility in #9334 is caused by different runtime kinds from `cmd/src/bin/ctl.rs` and `cmd_all/src/bin/risingwave.rs`. 😄 Let's unify the entry points to avoid this confusion from happening as much as possible.
Follow up of #9935.
</details>
> refactor(cmd): unify entry points for `cmd_all` and `cmd`

- ci/scripts/release.sh
> fix(ci): don't use sccache for release

- .git-blame-ignore-revs
- e2e_test/streaming/project_set.slt
- src/frontend/planner_test/tests/testdata/input/project_set.yaml
- src/frontend/planner_test/tests/testdata/output/project_set.yaml
- src/frontend/src/optimizer/plan_node/logical_project_set.rs
fix #10080, fix #10040
</details>
> fix: don't prune table functions in project set

- src/common/src/cast/mod.rs
> refactor: rewrite str_to_bytea according to PostgreSQL

- .git-blame-ignore-revs
- e2e_test/streaming/project_set.slt
- src/common/src/cast/mod.rs
- src/frontend/planner_test/tests/testdata/input/project_set.yaml
- src/frontend/planner_test/tests/testdata/output/project_set.yaml
- src/frontend/src/optimizer/plan_node/logical_project_set.rs
Wait for them to be approved first.
</details>
> fix: cherry-pick #10081, #10083 to v0.19

- docker/docker-compose-s3-compatible.yml
- docker/s3-compatible.env
as title
~~- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.~~
<details><summary>Click here for …
> feat(docker): add docker compose yml for s3-compatible storage

- Cargo.lock
- ci/Dockerfile
- ci/build-ci-image.sh
- ci/docker-compose.yml
- ci/rust-toolchain
- ci/workflows/pull-request.yml
- src/connector/src/parser/debezium/avro_parser.rs
- src/connector/src/parser/mod.rs
- src/storage/src/hummock/mod.rs
- src/storage/src/lib.rs
Fix a incr-comp ICE.
https://github.com/rust-lang/rust/issues/112137
</details>
> build: bump toolchain to 2023-05-31
