java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java

close https://github.com/risingwavelabs/risingwave/issues/18179
</details>

fix(jdbc-sink): fix incorrect data type mapping of Timestamptz

---

src/meta/src/controller/catalog.rs

As title, this PR fixed a issue in simulation recovery test: https://buildkite.com/risingwavelabs/main-cron/builds/3488#01927729-79dd-40c8-a239-68a20b60e19f
</details>

fix: fix subscription clean during recovery

---

src/meta/src/controller/catalog.rs

As title, another bug found in simulation recovery tests. https://buildkite.com/risingwavelabs/pull-request/builds/59508#019274d8-9f15-4d75-aab9-d2d9c9678d06
</details>

fix: filter out creating associated source catalog in notification snapshot

---

src/connector/src/sink/iceberg/compaction.rs
src/connector/src/sink/iceberg/java/pom.xml
src/connector/src/sink/iceberg/java/src/main/java/com/risingwave/nimtable/SparkIcebergCompaction.java
src/connector/src/sink/iceberg/mod.rs

Integrate nimtable compaction to iceberg sink coordinator.
Compaction related configurations are passed via env var. Following is the required env var
| name | required|  |
|-----|---|---|
|NIMTABLE_COMPACTION_REGION | false| use ec2 instance region by default |
|NIMTABLE_COMPACTION_ACCESS_KEY | false| |
|NIMTABLE_COMPACTION_SECRET_KEY | false| |
|NIMTABLE_COMPACTION_EXECUTION_ROLE_ARN | true| |
|NIMTABLE_COMPACTION_ENTRYPOINT | true| |
|NIMTABLE_COMPACTION_APPLICATION_ID | true| |
|NIMTABLE_COMPACTION_FREQUENCY | true| the frequency to do compaction. the number of commit to iceberg between two compactions| …

feat(nimtable): integrate compaction to nimtable iceberg sink coordinator

---

src/connector/src/sink/big_query.rs
src/connector/src/sink/clickhouse.rs
src/storage/src/hummock/sstable/block.rs

fix(sink): fix bq sink

---

src/connector/src/source/common.rs

which leads to an https://github.com/risingwavelabs/risingwave-cloud/pull/8870
</details>

fix: misused source row count metric

---

src/frontend/src/handler/drop_table.rs

- fix drop table with schema
example
```
create schema xxx;
create table xxx.t_nimtable (id int primary key) engine = iceberg;
drop table xxx.t_nimtable;
```
</details>

feat(nimtable): fix drop table with schema

---

src/connector/src/connector_common/common.rs
src/connector/src/error.rs
src/connector/src/source/nats/mod.rs
src/connector/src/source/nats/source/reader.rs
src/connector/src/source/nats/split.rs
src/connector/with_options_source.yaml

part 2 of https://github.com/risingwavelabs/risingwave/issues/18876
following https://github.com/risingwavelabs/risingwave/pull/18873
</details>

refactor: migrate Nats JetStream consumer to durable one

---

src/utils/runtime/src/logger.rs

Their debug log is too verbose, and causing CI fail
```
ERROR: log size is significantly large (7.2M). Please disable unnecessary logs.
```
</details>

feat(log): change opendal and reqsign log level to INFO

---

SECURITY.md

Requested by users.
</details>

doc: Create SECURITY.md

---

src/meta/src/stream/stream_manager.rs

For jobs that have been scaled or experienced node changes, if there is incomplete broadcast actor information during the process of generating the replace table for the related jobs, it may lead to issues.
For a specific example, in this scenario, if we want to alter a column in table m, it will trigger a replace table event. During the build actor phase of the existing code, only one actor's actor info from m will be broadcasted, while the other nodes won't have this info. As a result, after the replace, the downstream mm won't be able to find the upstream actor, leading to a panic.
Since we no longer have the build …

fix: Fix the issue with ReplaceTable caused by incomplete actor broadcast

---

.github/workflows/cherry-pick-to-release-branch.yml

feat(ci): add cherry-pick job to release-2.1

---

src/connector/src/parser/additional_columns.rs
src/frontend/src/handler/create_source.rs
src/sqlparser/src/ast/mod.rs
src/sqlparser/src/parser.rs
src/sqlparser/tests/testdata/create.yaml

To follow better coding practices, and reuse existing utilities rather than creating new feature-limited implementation.
Before:
* `str` -> `Token` by tokenizer
* `Token` -> `ast::DataType` by sqlparser
* `ast::DataType` -> `str` by `handle_addition_columns` using `Debug`
* `str` -> `DataType` & `PbDataType` by `build_header_catalog` using match
After:
* `str` -> `Token` by tokenizer
* `Token` -> `ast::DataType` by sqlparser
* `ast::DataType` -> `DataType` by `handle_addition_columns` using `bind_data_type`
* `DataType` -> `PbDataType` by `build_header_catalog` using `to_protobuf`
Additional benefits:
* Less `match`es …

refactor(source): handle `INCLUDE header` data type properly

---

java/java-binding-integration-test/src/main/java/com/risingwave/java/binding/HummockReadDemo.java

Previously in the java-binding demo ci test, we use the `max_committed_epoch` in hummock version as the query epoch. However, after we deprecate the `max_committed_epoch` in hummock version, the value in the protobuf becomes 0, and with this invalid max committed epoch, we are not able to query the correct data. 
In this PR, we change to use the `committed_epoch` of the table as the query epoch. …

fix(java-binding): use table committed epoch in demo query

---

src/meta/model_v2/migration/src/lib.rs

chore: fix overwrite to append new migration when using generate cli

---

src/meta/src/hummock/manager/gc.rs

This lock ensures that during commit_epoch or report_compact_tasks, where versioning lock is held, no new objects will be marked for deletion here.
</details>

fix(meta): fix contention

---

ci/scripts/deterministic-e2e-test.sh

https://github.com/risingwavelabs/sqlsmith-query-snapshots/tree/fix_for_release-2.0
replace all "ENABLE_TWO_PHASE_AGG" to "RW_ENABLE_TWO_PHASE_AGG"
</details>

fix: use a fixed snapshot for fuzzy testing

---

e2e_test/source/cdc_inline/sql_server_cdc/sql_server_cdc.slt
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzChangeEventConsumer.java
src/frontend/src/handler/create_table.rs
src/frontend/src/optimizer/plan_node/stream_cdc_table_scan.rs

cherry pick to 2.0 .
</details>

fix(cdc): fix the filter expression of CdcFilter executor (#18868)

---

src/connector/src/error.rs
src/connector/src/source/mqtt/enumerator/mod.rs
src/connector/src/source/mqtt/mod.rs

as title, return error in this case instead of loop and waiting
</details>

fix: prevent mqtt enumerator in dead loop if disconnected

---

ci/scripts/backwards-compat-test.sh
ci/scripts/connector-node-integration-test.sh
ci/scripts/e2e-cassandra-sink-test.sh
ci/scripts/e2e-deltalake-sink-rust-test.sh
ci/scripts/e2e-iceberg-sink-test.sh
ci/scripts/e2e-mongodb-sink-test.sh
ci/scripts/e2e-source-test.sh
ci/scripts/release.sh

`wget` generates lots of useless logs in CI.
<details>
<summary>Example</summary>
```
+ wget https://dlcdn.apache.org/spark/spark-3.4.3/spark-3.4.3-bin-hadoop3.tgz
--2024-10-16 16:12:38--  https://dlcdn.apache.org/spark/spark-3.4.3/spark-3.4.3-bin-hadoop3.tgz
Resolving dlcdn.apache.org (dlcdn.apache.org)... 151.101.2.132, 2a04:4e42::644
Connecting to dlcdn.apache.org (dlcdn.apache.org)|151.101.2.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 388930980 (371M) [application/x-gzip]
Saving to: 'spark-3.4.3-bin-hadoop3.tgz'
0K .......... .......... .......... .......... ..........  0% 76.2M 5s …
```

chore(ci): eliminate the progress output of wget

---

src/config/ci-backfill.toml
src/config/ci-longer-streaming-upload-timeout.toml

Previously we have located the root cause of Backfill Test failure in main cron: detail in https://github.com/apache/opendal/issues/5101#issuecomment-2357831862. We have a pr to increase the streaming_upload_attempt_timeout_ms from 10s to 20s and it indeed alleviated the issue, reducing the probability of failure.
However recently the same issue happened again several times, since the minio problem cannot be fixed in a short time, I suggest (maybe the only way) to continue to increase this timeout.
Close https://github.com/risingwavelabs/risingwave/issues/18959 …

chore(test): longer streaming_upload_attempt_timeout_ms for backfill test only

---

.github/workflows/cherry-pick-to-release-branch.yml

After this PR, we don't need to add a job for every new release branch like before.
</details>

feat(ci): simplify the cherry-pick workflow

---

.github/workflows/cherry-pick-to-release-branch.yml

Use explicit permissions to avoid 403 issues according to the answer https://github.com/orgs/community/discussions/141776#discussioncomment-10970961
</details>

fix(ci): use explicit permissions

---

.github/workflows/cherry-pick-to-release-branch.yml

The previous resolution missed the push permission
</details>

fix(ci): add contents write permission

---

docs/dev/src/tests/intro.md

improve language and subtitles
</details>

doc(dev-guide): minor improve testing guide

---

src/storage/hummock_sdk/src/version.rs

The usage of `sst_id` was incorrectly changed to `object_id` in #15386.
</details>

fix(meta): read correct id field

---

ci/scripts/run-backfill-tests.sh
risedev.yml
src/config/ci-backfill.toml
src/config/ci-longer-streaming-upload-timeout.toml

fix(ci): change backfill test config

---

proto/meta.proto
src/connector/src/sink/mod.rs
src/frontend/src/catalog/system_catalog/rw_catalog/rw_event_logs.rs
src/meta/service/src/event_log_service.rs
src/meta/src/manager/event_log.rs
src/rpc_client/src/meta_client.rs
src/stream/src/executor/sink.rs
src/tests/simulation/tests/integration_tests/README.md
src/tests/simulation/tests/integration_tests/sink/err_isolation.rs
src/tests/simulation/tests/integration_tests/sink/utils.rs

feat: report sink failure event to event log

---

proto/hummock.proto
proto/stream_service.proto
src/ctl/src/cmd_impl/hummock/validate_version.rs
src/meta/src/barrier/creating_job/barrier_control.rs
src/meta/src/barrier/creating_job/mod.rs
src/meta/src/barrier/creating_job/status.rs
src/meta/src/barrier/mod.rs
src/meta/src/barrier/state.rs
src/meta/src/hummock/manager/checkpoint.rs
src/meta/src/hummock/manager/commit_epoch.rs
src/meta/src/hummock/manager/compaction/mod.rs
src/meta/src/hummock/manager/context.rs
src/meta/src/hummock/manager/time_travel.rs
src/meta/src/hummock/manager/transaction.rs
src/meta/src/hummock/mock_hummock_meta_client.rs
src/meta/src/lib.rs
src/meta/src/rpc/metrics.rs
src/prost/build.rs
src/storage/hummock_sdk/src/compact_task.rs
src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
src/storage/hummock_sdk/src/table_watermark.rs
src/storage/hummock_sdk/src/version.rs
src/storage/hummock_test/src/hummock_storage_tests.rs
src/storage/hummock_test/src/state_store_tests.rs
src/storage/src/hummock/validator.rs
src/stream/src/executor/backfill/snapshot_backfill.rs
src/stream/src/task/barrier_manager/progress.rs

Cherry-pick https://github.com/risingwavelabs/risingwave/pull/18798, https://github.com/risingwavelabs/risingwave/pull/18819 and https://github.com/risingwavelabs/risingwave/pull/18893
No significant conflict in cherry-pick. Conflicts are caused by method rename and crate import.
Resolve https://github.com/risingwavelabs/risingwave/issues/18998
</details>

feat: cherry pick #18798, #18819 and #18893 to release-2.1

---

ci/scripts/notify.py
ci/workflows/main-cron.yml

There's an undocumented `errored` outcome status for buildkite, which time'd out steps correspond to. Handled it in the notification script and added some logs.
https://buildkite.com/docs/agent/v3/cli-step#getting-a-step
</details>

fix(ci): ensure timeout steps also notify

---

src/common/src/array/arrow/arrow_iceberg.rs
src/common/src/array/arrow/arrow_impl.rs

Previously the conversion is wrong, which will drop the decimal part. This pr fix it and use DECIMAL_DEFAULT_SCALE=10 for 
`Decimal128`. Previous issue will affect parquet file source and sink. 
</details>

fix(common): fix conversion between Decimal to arrow Decimal128

---

ci/scripts/deterministic-e2e-test.sh
ci/scripts/deterministic-it-test.sh
ci/scripts/deterministic-recovery-test.sh
ci/scripts/run-deterministic-fuzz-test.sh
src/tests/simulation/src/cluster.rs
src/tests/simulation/src/main.rs

I previously attempted in-memory db as suggested by @BugenZhao: https://github.com/risingwavelabs/risingwave/pull/18859.
But it does not work quite well, since the sqlx driver kills the in memory sqlite whenever a connection is dropped.
So I revert to the next best solution, which is to use `Tempfile`.
In this PR we also add back `MADSIM_TEST_SEED`. …

test: use tempfile for rw metadata storage in deterministic tests

---

Cargo.lock
Cargo.toml
src/object_store/Cargo.toml
src/tests/simulation/Cargo.toml

chore(deps): unpatch madsim

---

src/stream/src/executor/aggregation/agg_group.rs
src/stream/src/executor/hash_agg.rs
src/stream/src/executor/simple_agg.rs

Don't count cache miss on agg group creation/recovery.
</details>

fix(metric): better agg state cache miss ratio metric

---

src/common/src/array/arrow/arrow_iceberg.rs

fix(common): fix conversion between Decimal to arrow Decimal128 

---

proto/stream_service.proto
src/meta/src/barrier/progress.rs
src/meta/src/barrier/recovery.rs
src/meta/src/model/stream.rs
src/stream/src/executor/source/source_backfill_executor.rs
src/stream/src/task/barrier_manager/progress.rs
src/tests/simulation/tests/integration_tests/README.md
src/tests/simulation/tests/integration_tests/backfill_tests.rs
src/tests/simulation/tests/integration_tests/recovery/background_ddl.rs

Co-authored-by: Kexiang Wang <kx.wang@hotmail.com>I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).
close #19045
</details>

cherry-pick feat: improve progress msg in SHOW JOBS for source backfill (#18925) to branch release-2.1 

---

src/frontend/planner_test/tests/testdata/input/agg.yaml
src/frontend/planner_test/tests/testdata/output/agg.yaml

Add a test case for the documented usage: https://risingwavelabs.mintlify.app/docs/current/sql-select/introduction#distinct-clause
Should be a follow-up of https://github.com/risingwavelabs/risingwave/pull/6593
</details>

test: add planner test case for distinct on

---

e2e_test/sink/sink_into_table/snapshot.slt

test: snapshot with option for sink into table

---

Cargo.lock
Cargo.toml

chore: update version to 2.0.2

---

docs/dev/README.md

doc(dev-guide): `cargo binstall` -> `cargo install` 

---

src/batch/src/executor/postgres_query.rs

Otherwise we will buffer all the data from the upstream query.
</details>

fix(batch): use streaming api for `postgres_query` when fetching rows from upstream

---

src/meta/service/src/stream_service.rs
src/meta/src/controller/catalog.rs
src/meta/src/dashboard/mod.rs

Previous:
After this PR:
</details>

fix(dashboard): show creating job edges in bp graph

---

Cargo.lock
Makefile.toml
ci/scripts/common.sh
docker/docker-compose.yml
src/common/secret/Cargo.toml
src/common/secret/src/encryption.rs
src/meta/src/manager/env.rs

previously we use `0123456789abcdef` as the RW_SECRET_STORE_PRIVATE_KEY_HEX in test. It's 128 bit in bytes representation by 64bit in hex.
Now we switch to use `0123456789abcdef0123456789abcdef` as 128 hex
</details>

test(secret): use correct RW_SECRET_STORE_PRIVATE_KEY_HEX length in test

---

risedev.yml
src/frontend/src/catalog/system_catalog/rw_catalog/iceberg_namespace_properties.rs
src/frontend/src/catalog/system_catalog/rw_catalog/iceberg_tables.rs
src/frontend/src/catalog/system_catalog/rw_catalog/mod.rs

- Support a system table `iceberg_tables` with a privilege check so that when external engines access the iceberg catalog, we can utilize pg-compatible access control to manage permissions seamlessly.
- Support an empty system table `iceberg_namespace_properties`.
</details>

feat(nimtable): support iceberg tables with privilege check

---

e2e_test/background_ddl/basic.slt
e2e_test/source_inline/kafka/background_ddl/basic.slt.serial
src/frontend/src/optimizer/plan_node/stream_materialize.rs
src/frontend/src/optimizer/plan_node/stream_sink.rs
src/frontend/src/optimizer/plan_node/utils.rs

There's no backfilling required. Further, `StreamNow` and `StreamSource` plan nodes are converted into stateful executors, so they will just resume from last ckpt.
</details>

feat(stream): enable background ddl for `StreamNow`, `StreamSource`

---

ci/scripts/docker-scout-notify.sh

fix(ci): fix docker scount notification

---

src/meta/model/migration/src/m20241025_062548_singleton_vnode_count.rs

Missed https://github.com/risingwavelabs/risingwave/pull/18753#discussion_r1797628658. Resolve #19144. Tested locally.
</details>

fix(meta): fix migration query under postgres meta store for #18753

---

src/stream/src/executor/over_window/frame_finder.rs
src/stream/src/executor/over_window/general.rs
src/stream/src/executor/over_window/over_partition.rs

Avoid recompute frame informations when handling every chunk.
</details>

perf(over window): avoid recompute information about window frames

---

ci/scripts/docker-scout-notify.sh

cherry-pick https://github.com/risingwavelabs/risingwave/pull/19143
</details>

fix(ci): fix docker scount notification (#19143)

---

dashboard/lib/layout.ts

chore(dashboard): remove unused function

---

Cargo.lock
Cargo.toml

chore: update version to v2.1.0-rc.1

---

src/stream/src/executor/sink.rs

The newly added actor id in assertion helps identify the stream job that may have incorrectly emitted a data chunk after pause.
</details>

refactor: improve assertion message

---

src/frontend/src/catalog/system_catalog/rw_catalog/rw_views.rs
src/frontend/src/catalog/view_catalog.rs
src/frontend/src/handler/show.rs

fix: include schema for view name in rw_relations show create view

---

lints/Cargo.lock
lints/Cargo.toml

chore: upgrade clippy utils to a version on the main branch

---

ci/scripts/build.sh
ci/scripts/check.sh

...so that poorly formatted code can still run steps like building and testing.
</details>

chore(ci): move fmt and sort checks from `build` step to `check` step

---

src/connector/src/parser/plain_parser.rs
src/connector/src/parser/unified/kv_event.rs
src/connector/src/parser/upsert_parser.rs

resolve https://github.com/risingwavelabs/risingwave/issues/16191
</details>

fix: unexpected warning on undefined-field-padding-null error

---

src/stream/src/executor/project.rs
src/stream/src/executor/project_set.rs
src/stream/src/executor/watermark_filter.rs
src/stream/tests/integration_tests/project_set.rs

This PR prevents three watermark sources, Project, ProjectSet, WatermarkFilter from generating new Watermarks when the stream is paused. Fixes #19117.
</details>

fix(watermark): stop generating watermark messages when stream is paused

---

src/connector/src/connector_common/iceberg/mod.rs
src/frontend/src/handler/create_table.rs

fix(nimtable): fix database path

---

src/stream/src/executor/project.rs
src/stream/src/executor/project_set.rs
src/stream/src/executor/watermark_filter.rs
src/stream/tests/integration_tests/project_set.rs

cherry pick fix(watermark): stop generating watermark messages when stream is paused (#19199) to branch release-2.0

---

java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/DbzConnectorConfig.java

fix(pg-cdc): fix ssl.mode value to debezium

---

ci/workflows/main-cron.yml
ci/workflows/pull-request.yml
src/meta/model/migration/README.md
src/meta/model/migration/src/m20230908_072257_init.rs
src/meta/model/migration/src/m20240304_074901_subscription.rs
src/meta/model/migration/src/m20240506_112555_subscription_partial_ckpt.rs
src/meta/model/migration/src/m20241025_062548_singleton_vnode_count.rs
src/meta/model/migration/src/utils.rs
src/meta/src/barrier/mod.rs
src/meta/src/hummock/manager/gc.rs
src/meta/src/hummock/manager/time_travel.rs

We didn't have coverage on using MySQL as the meta backend. This PR enables that, exposing and fixing several bugs:
- `ON CONFLICT DO NOTHING` syntax error: should directly use `.on_conflict_do_nothing()`.
- Data too long (>= 65536) for some text fields: should use `longtext` datatype instead of `text` or `varchar`.
</details>

fix(meta): address bugs for mysql backend & enable e2e tests

---

e2e_test/iceberg/start_spark_connect_server.sh

chore(test): bump spark from 3.4.3 to 3.4.4

---

src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs

fix(metric): include table_change_log when calculating object size #18452

---

e2e_test/source/cdc/cdc.share_stream.slt
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/DbzConnectorConfig.java
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/MySqlValidator.java
java/connector-node/risingwave-connector-service/src/main/resources/validate_sql.properties
src/frontend/src/handler/create_table.rs

cherry-pick: feat(mysql-cdc): support mysql source capture multiple databases #19038 to 2.0

---

e2e_test/subscription/create_table_and_subscription.slt
e2e_test/subscription/drop_table_and_subscription.slt
e2e_test/subscription/main.py
proto/batch_plan.proto
src/batch/src/executor/log_row_seq_scan.rs
src/frontend/src/handler/explain.rs
src/frontend/src/handler/util.rs
src/frontend/src/optimizer/plan_node/batch_log_seq_scan.rs
src/frontend/src/optimizer/plan_node/generic/log_scan.rs
src/frontend/src/session/cursor_manager.rs
src/storage/src/table/batch_table/storage_table.rs
src/storage/src/table/merge_sort.rs
src/storage/src/table/mod.rs
src/stream/src/executor/backfill/snapshot_backfill.rs

cherry-pick feat(subscription): support cusor order (#18801)

---

e2e_test/source_inline/fs/posix_fs.slt
src/frontend/src/optimizer/plan_node/stream_fs_fetch.rs
src/meta/src/controller/streaming_job.rs
src/meta/src/stream/stream_graph/fragment.rs
src/stream/src/executor/source/fetch_executor.rs
src/stream/src/executor/source/source_executor.rs

resolve https://github.com/risingwavelabs/risingwave/issues/19348
</details>

fix: table with fs connector cannot work with rate limit (#19338)

---

src/meta/src/barrier/progress.rs
src/meta/src/barrier/recovery.rs

Fixed bug found in https://buildkite.com/risingwavelabs/main-cron/builds/3843#01931e2c-869a-4314-aa99-849e4747f72c. Details explained in #19355 .
</details>

fix: finish background mview without backfill during recovery

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml
e2e_test/iceberg/start_spark_connect_server.sh

chore: update version to v2.0.3

---

src/meta/src/barrier/recovery.rs
src/meta/src/manager/metadata.rs
src/meta/src/model/stream.rs

fix(cherry-pick): background mview without backfilling should not tracked in barrier runtime info (#19355)

---

ci/scripts/run-e2e-test.sh

This was introduced for deno-udf tests before.
</details>

fix(ci): delete unused python install before embedded UDF tests

---

src/connector/src/connector_common/iceberg/mod.rs
src/connector/src/sink/iceberg/mod.rs
src/connector/with_options_sink.yaml
src/connector/with_options_source.yaml

- Since iceberg rest catalog doesn't need to specify warehouse by default, we can make `warehouse.path` optional for rest catalog.
</details>

feat(iceberg): make wrehouse.path optional for iceberg rest catalog

---

e2e_test/source_legacy/cdc_inline/postgres_create_drop.slt
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/MySqlValidator.java
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/PostgresValidator.java

Resolve https://github.com/risingwavelabs/risingwave/issues/19408
</details>

fix(direct-cdc): improve type match for pg-cdc

---

src/batch/src/executor/join/distributed_lookup_join.rs
src/batch/src/executor/row_seq_scan.rs
src/storage/src/table/batch_table/storage_table.rs

- Use `get_keyed_row` instead of `iter` to implement point get for queries with `_rw_timestamp` system columns.
</details>

feat(batch): use get_keyed_row to implement point get for _rw_timestamp

---

src/connector/src/source/kafka/enumerator/client.rs

according to [`fetch_metadata` doc](https://docs.rs/rdkafka/latest/rdkafka/consumer/trait.Consumer.html#tymethod.fetch_metadata)
> Returns the metadata information for the specified topic, or for all topics in the cluster if no topic is specified.
* return all metadata for all topic needs `describe cluster` ACL on Kafka
* return topic spec metadata just need `describe topic` ACL
a simple fix and does not affect logic …

fix: request for topic spec metadata to narrow privilege required

---

e2e_test/source_inline/fs/posix_fs.slt
src/meta/src/controller/streaming_job.rs

resolve https://github.com/risingwavelabs/risingwave/issues/19433
following https://github.com/risingwavelabs/risingwave/pull/19338
</details>

fix: alter FS source rate_limit is not handled correctly

---

src/storage/backup/src/lib.rs
src/storage/hummock_sdk/src/state_table_info.rs
src/storage/src/hummock/backup_reader.rs

This PR removes the custom serde for metadata backup manifest, because it doesn't maintain backward compatibility correctly. The backward compatibility issue was caused by a refactor in v2.1.
This PR has been tested to ensure proper backward compatibility.
</details>

fix(meta): remove custom serde

---

src/meta/src/rpc/election/etcd.rs

chore(cherry-pick): change log level for lease keeper fail (2ff588b)

---

src/meta/src/hummock/manager/compaction/mod.rs
src/stream/src/task/barrier_manager.rs

cherry pick #19370 and #19366
</details>

fix: approximately update table stats for vnode watermark reclaim

---

src/meta/src/rpc/election/etcd.rs

chore: change log level for lease keeper fail

---

ci/scripts/run-e2e-test.sh
e2e_test/python_client/main.py
src/common/src/types/postgres_type.rs
src/common/src/types/to_binary.rs

Closes #7949.
`sqllogictest-rs` doesn't support struct type yet, so I added a Python test in e2e-test.
References: 
- Postgres code [`src/backend/utils/adt/rowtypes.c`](https://github.com/postgres/postgres/blob/a3699daea2026de324ed7cc7115c36d3499010d3/src/backend/utils/adt/rowtypes.c#L687)
- Pseudo-type of struct & array of struct: [`src/include/catalog/pg_type.dat`](https://github.com/postgres/postgres/blob/master/src/include/catalog/pg_type.dat#L550-L561) …

feat(pgwire): support struct type in extended mode

---

Cargo.lock
Cargo.toml

- Resolve https://github.com/risingwavelabs/risingwave/issues/19489
</details>

fix(iceberg): pick 19471 to v2.1

---

src/frontend/src/catalog/system_catalog/rw_catalog/rw_relation_info.rs
src/meta/src/controller/catalog.rs

chore: don't treat subscription as streaming job in system catalog

---

e2e_test/sink/sink_into_table/parallelism.slt
src/frontend/planner_test/src/lib.rs
src/frontend/planner_test/tests/testdata/input/sink_into_table.yaml
src/frontend/planner_test/tests/testdata/output/emit_on_window_close.yaml
src/frontend/planner_test/tests/testdata/output/sink.yaml
src/frontend/planner_test/tests/testdata/output/sink_into_table.yaml
src/frontend/src/handler/create_sink.rs
src/frontend/src/optimizer/mod.rs
src/frontend/src/optimizer/plan_node/stream_sink.rs

fix: when target is table, the sink downstream pk is not set (#19515)

---

e2e_test/iceberg/pyproject.toml

Fix https://github.com/risingwavelabs/risingwave/security/dependabot/175
</details>

fix: upgrade setuptools because of vulnerablility

---

e2e_test/sink/sink_into_table/parallelism.slt
src/frontend/planner_test/src/lib.rs
src/frontend/planner_test/tests/testdata/input/sink_into_table.yaml
src/frontend/planner_test/tests/testdata/output/emit_on_window_close.yaml
src/frontend/planner_test/tests/testdata/output/sink.yaml
src/frontend/planner_test/tests/testdata/output/sink_into_table.yaml
src/frontend/src/handler/create_sink.rs
src/frontend/src/optimizer/mod.rs
src/frontend/src/optimizer/plan_node/stream_sink.rs

cherry-pick fix: when target is table, the sink downstream pk is not set (#19515) to branch release-2.0

---

e2e_test/sink/sink_into_table/parallelism.slt
src/frontend/planner_test/src/lib.rs
src/frontend/planner_test/tests/testdata/input/sink_into_table.yaml
src/frontend/planner_test/tests/testdata/output/emit_on_window_close.yaml
src/frontend/planner_test/tests/testdata/output/sink.yaml
src/frontend/planner_test/tests/testdata/output/sink_into_table.yaml
src/frontend/src/handler/create_sink.rs
src/frontend/src/optimizer/mod.rs
src/frontend/src/optimizer/plan_node/stream_sink.rs

cherry-pick fix: when target is table, the sink downstream pk is not set (#19515) to branch release-2.1

---

src/meta/src/controller/mod.rs
src/meta/src/manager/env.rs

When meta store migration fails, instruct users to check if they are running incompatible versions and clean the data directory if desired in single node deployments.
</details>

refactor(meta): provide better message for meta store migration failure

---

e2e_test/batch/basic/dml_update.slt.part
src/frontend/planner_test/tests/testdata/output/update.yaml
src/frontend/src/binder/update.rs
src/frontend/src/expr/subquery.rs
src/frontend/src/expr/type_inference/cast.rs

...by specifying field name for the struct type. See changes on e2e tests.
Based on #19402 and #19449.
</details>

refactor(frontend): better cast error message for `UPDATE` setting to subquery

---

src/tests/sqlsmith/src/validation.rs

chore(sqlsmith): ignore sqrt with negative input error

---

java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JdbcUtils.java

feat(sink): use mysql dialect for jdbc url start with mariadb

---

Cargo.lock
Cargo.toml

- Resolve https://github.com/risingwavelabs/risingwave/issues/19490
</details>

fix(iceberg): pick 19471 to v2.0

---

src/meta/src/barrier/context/context_impl.rs
src/meta/src/barrier/context/mod.rs
src/meta/src/barrier/context/recovery.rs
src/meta/src/barrier/schedule.rs
src/meta/src/barrier/worker.rs
src/meta/src/stream/stream_manager.rs

To support database failure isolation, we may temporarily block the command queue of a specific database when we are recovering the database, like what we do globally in the global recovery. Therefore, in this PR, we change to maintain per database scheduled command queue, and each queue have its own status, and we will support mark the queue as ready or blocked in either per-database manner or globally. …

feat(barrier): maintain per database scheduled command queue

---

proto/meta.proto
src/frontend/src/session.rs
src/meta/node/src/server.rs
src/meta/service/src/cluster_service.rs
src/meta/src/backup_restore/utils.rs
src/meta/src/controller/cluster.rs
src/meta/src/controller/mod.rs
src/rpc_client/src/meta_client.rs

- Related https://github.com/risingwavelabs/risingwave/issues/19418
- Add a rpc to fetch meta store endpoint info from meta for frontend.
</details>

feat(meta): add a rpc to fetch meta store endpoint

---

e2e_test/ddl/secret.slt
src/frontend/src/handler/create_secret.rs

The name of a secret in the catalog should not contains the schema name
</details>

fix(secret): the name of a secret in the catalog should not contains the schema name

---

e2e_test/ddl/show.slt
src/frontend/src/handler/comment.rs

fix #19607 
when on main
```
dev=> create schema show_another_schema;
CREATE_SCHEMA
dev=> create table show_another_schema.t_another (v1 int);
CREATE_TABLE
dev=> comment on table "show_another_schema"."t_another" IS 'test table description with schema';
1: Catalog error
2: table not found: t_another
dev=> comment on column "show_another_schema"."t_another".v1 IS 'test column description with schema';
1: Catalog error
2: table not found: t_another
dev=> …
```

fix: consider schema when commenting on a column or table

---

src/frontend/planner_test/tests/testdata/input/distinct_on.yaml
src/frontend/planner_test/tests/testdata/output/distinct_on.yaml
src/frontend/src/optimizer/plan_node/generic/dedup.rs
src/frontend/src/optimizer/plan_node/generic/top_n.rs
src/frontend/src/optimizer/plan_node/logical_dedup.rs

fix(optimizer): LogicalDedup distinct columns were not mapped when pruning columns

---

src/meta/src/barrier/mod.rs
src/meta/src/barrier/rpc.rs

Fix https://github.com/risingwavelabs/risingwave/issues/19613
</details>

fix(meta): cherry-pick avoid removing control stream node when failed to send request (#18767)

---

Cargo.lock
Cargo.toml

chore: upgrade package version to 2.0.4

---

docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

chore: update docker image to v2.1.0-rc.2

---

docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

Update docker image version to v2.0.4
</details>

chore: update docker image version to v2.0.4

---

src/meta/src/hummock/manager/gc.rs

fix(meta): limit max orm param

---

src/stream/src/executor/join/hash_join.rs

doc(streaming): Add docs for degree table in hash join

---

src/ctl/src/cmd_impl/hummock.rs
src/ctl/src/cmd_impl/hummock/migrate_legacy_object.rs
src/ctl/src/lib.rs
src/object_store/src/object/mod.rs
src/object_store/src/object/opendal_engine/opendal_object_store.rs
src/object_store/src/object/prefix.rs

This PR adds a CTL command to reorganize object store files whose `use_new_object_prefix_strategy=false`,  to become `use_new_object_prefix_strategy=true`.
Note that to complete the migration, the `use_new_object_prefix_strategy` and `data_directory` system params should be forcefully set to true as well in meta store.
</details>

feat(ctl): migrate legacy object with new prefix strategy

---

src/meta/src/barrier/context/context_impl.rs
src/meta/src/barrier/context/mod.rs
src/meta/src/barrier/context/recovery.rs
src/meta/src/barrier/info.rs
src/meta/src/barrier/mod.rs
src/meta/src/controller/catalog.rs
src/meta/src/controller/fragment.rs
src/meta/src/manager/metadata.rs

To support database failure isolation, when failure happens in a database, we will need to clean dirty state and reload the runtime information of the database before recovering the runtime of database. In this PR, we implement the method `reload_database_runtime_info` to reload the necessary runtime information of a specific database.
</details>

feat(meta): support reload runtime info of single database

---

src/bench/sink_bench/main.rs

As title, always met `queries overflow the depth limit!`.
</details>

chore: set recursion_limit for sink bench crate

---

Cargo.lock
Cargo.toml
src/storage/src/store_impl.rs

Switch foyer to v0.13.0 release version.
</details>

chore(dep): switch foyer to v0.13.0 release version

---

src/common/src/config.rs
src/config/example.toml
src/meta/node/src/lib.rs
src/meta/src/hummock/manager/time_travel.rs
src/meta/src/manager/env.rs

refactor(meta): insert time travel metadata in batch

---

src/stream/src/executor/backfill/snapshot_backfill.rs
src/stream/src/executor/merge.rs

Previously in snapshot backfill, we only do `mapping_chunk` to chunk generated from reading snapshot, and didn't do it for chunk generated from reading log store and received from upstream. In this PR, we will change to do `mapping_chunk` to all  chunk to be yielded.
</details>

fix(snapshot-backfill): do mapping_chunk with output indices to all chunks

---

src/meta/src/manager/catalog/database.rs

fix: add missing objects for schema empty check

---

src/meta/src/hummock/manager/commit_epoch.rs
src/storage/src/hummock/sstable/forward_sstable_iterator.rs

fix backward compact caused by https://github.com/risingwavelabs/risingwave/pull/19582
</details>

fix(storage): fix backward compact

---

src/stream/src/task/barrier_manager.rs

Resolve https://github.com/risingwavelabs/risingwave/issues/19693
Previously in local barrier worker, we assign a very low select priority to the channel that receives request to reset the control stream for recovery. Under this design, we may hit the case of https://github.com/risingwavelabs/risingwave/issues/19693 easily when any sync task failed.
In this PR, we will simply fix the issue by giving higher priority for this channel. …

fix: select channel for clear barrier worker with higher priority

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

chore: update version to v2.1.0

---

e2e_test/udf/drop_function.slt
src/frontend/src/binder/expr/function/mod.rs

fix: missing dependency info of sql UDFs for streaming job ddl

---

Cargo.lock

Resolves #19727 (but NOT #19726 or #19725)
Generated by `cargo update url`.
`idna` is only used by `url`, and `url` is used by many crates. It only takes a patch version update of `url` so there is no API breakage to downstream crates.
But `idna 1.0.3` by default would introduce a lot of new dependencies. In this PR we opt to disable IDNA support via `cargo update -p idna_adapter --precise 1.0.0` according to the [doc](https://docs.rs/crate/idna_adapter/latest).
For context, IDNA is short for Internationalizing Domain Names in Applications, a mechanism to allow non-ASCII in domain names. We can consider supporting it …

chore(deps): Bump url from 2.5.0 to 2.5.4 (idna from 0.5.0 to 1.0.3)

---

src/meta/node/src/server.rs
src/meta/service/src/stream_service.rs
src/meta/src/barrier/manager.rs
src/meta/src/barrier/mod.rs
src/meta/src/barrier/worker.rs
src/meta/src/manager/notification.rs

As titled, to resolve the shortcoming mentioned in https://github.com/risingwavelabs/risingwave/pull/16259.
Move the `AdhocRecovery` request from `LocalNotification` to the more explicit `BarrierManagerRequest`. An `oneshot::Sender` is attached to the request, and we will notify the sender when recovery finishes. We wait on the `oneshot::Receiver` to ensure that the recovery has finished.
If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact …

feat(meta): ensure recovery is finished after recover command returns

---

Cargo.lock
src/rpc_client/Cargo.toml

See #18039 for the backgrounds.
Now the upstream has resolved the issue, we can close #18039.
</details>

chore: bump `h2` to address hanging on long headers

---

.typos.toml
src/common/src/catalog/column.rs
src/connector/codec/src/decoder/mod.rs
src/stream/src/executor/backfill/cdc/mod.rs

chore: fix typo in comment

---

Cargo.lock
src/batch/Cargo.toml
src/batch/src/executor/mod.rs

Registration-style executor builder powered by the same technique used by expression impls (`linkme`). This is a preparation for #19742.
</details>

refactor(batch): register-style executor builder

---

.github/dependabot.yml
ci/scripts/gen-integration-test-yaml.py
ci/workflows/docker-arm-fast.yml
ci/workflows/docker.yml
ci/workflows/gen-flamegraph-cron.yml
ci/workflows/gen-flamegraph.yml
ci/workflows/main-cron.yml
ci/workflows/pull-request.yml
ci/workflows/sqlsmith-snapshots.yml

ci: add dependabot for GHA & bump buildkite plugin versions

---

src/stream/src/executor/source/source_executor.rs

Revert the retry part for source executor done in #19467 
The motivation and discussion can be founded in https://github.com/risingwavelabs/risingwave/issues/19681
</details>

fix(source): revert create source reader with retry

---

src/connector/codec/src/decoder/avro/mod.rs
src/connector/codec/src/decoder/utils.rs
src/connector/src/parser/unified/json.rs

refactor(source): DRY decimal parsing

---

e2e_test/source_inline/kafka/alter/add_column_shared.slt
e2e_test/source_inline/kafka/protobuf/alter_source_shared.slt
src/connector/src/with_options.rs
src/frontend/src/handler/alter_source_with_sr.rs
src/frontend/src/handler/create_source.rs
src/frontend/src/handler/create_table.rs

fix #19799
Note: This problem only exists for `REFRESH SCHEMA` (i.e., source with schema regitry), but not for `ADD COLUMN`, because only the former updated `source_info`
<details>
</details>

fix: alter shared source fresh schema will make it non-shared

---

e2e_test/error_ui/simple/main.slt
e2e_test/sink/kafka/protobuf.slt
e2e_test/sink/license.slt
e2e_test/source_legacy/basic/ddl.slt
e2e_test/time_travel/syntax.slt
src/error/src/tonic.rs
src/rpc_client/src/channel.rs
src/rpc_client/src/frontend_client.rs
src/rpc_client/src/lib.rs
src/rpc_client/src/meta_client.rs
src/rpc_client/src/stream_client.rs
src/rpc_client/src/tracing.rs

For better observability. Check changes on the test files for a preview.
<details>
</details>

feat(error): include gRPC call path in error report

---

src/meta/src/backup_restore/restore_impl/v2.rs

(cherry picked from commit 1e24ca482c29c08ba3aeb31ee44f672e3eaaef05)
close #19806
<details>
</details>

fix(meta): fix order when restoring metadata (#19791)

---

src/batch/src/executor/s3_file_scan.rs
src/connector/src/source/iceberg/parquet_file_handler.rs
src/frontend/src/expr/table_function.rs

As title.
<details>
</details>

cherry-pick fix(connector): file scan use correct path (#19793) to branch release-2.1 

---

ci/docker-compose.yml

It's a mis-resolution of the conflicts when merging #19595. As a result, tests running against this image will use an outdated `sqllogictest`, leading to [failure on `main-cron`](https://buildkite.com/risingwavelabs/main-cron/builds/4096#0193d55a-2fff-44a1-8f96-210f3a00433c) these days.
<details>
</details>

fix(ci): use correct image version for `ci-standard-env`

---

ci/scripts/e2e-source-test.sh
e2e_test/requirements.txt
e2e_test/source_inline/requirements.txt

Use pinned version to avoid similar issues in the future.
<details>
</details>

fix(ci): fix source test dependency issue

---

src/batch/executors/src/executor/s3_file_scan.rs
src/connector/src/source/iceberg/parquet_file_handler.rs
src/frontend/src/expr/table_function.rs

cherry-pick fix(connector): file scan use correct path (#19793) to branch release-2.2

---

ci/scripts/remove-micro-bench-results.sh
ci/scripts/upload-micro-bench-results.sh

chore(ci): migrate the qa service

---

e2e_test/error_ui/simple/main.slt
e2e_test/sink/kafka/protobuf.slt
e2e_test/sink/license.slt
e2e_test/source_legacy/basic/ddl.slt
e2e_test/time_travel/syntax.slt
src/error/src/tonic.rs
src/rpc_client/src/channel.rs
src/rpc_client/src/frontend_client.rs
src/rpc_client/src/lib.rs
src/rpc_client/src/meta_client.rs
src/rpc_client/src/stream_client.rs

cherry-pick feat(error): include gRPC call path in error report (#19809) to 2.2

---

src/connector/src/sink/big_query.rs
src/connector/with_options_sink.yaml

add bigquery sink option:
`bigquery.credentials`, `optional`,  with `bigquery.local.path`, `bigquery.s3.path` must choose between one to enter credentials.json as string

feat(sink): add bigquery sink json string credentials

---

src/meta/node/src/server.rs

Disable telemetry report with madsim. Otherwise, simulation test in local env will panic with no telemetry env set.
<details>
</details>

fix: disable telemetry report with madsim

---

docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

fix #19886
<details>
</details>

chore: update docker image to v2.1.0

---

src/common/metrics/src/gauge_ext.rs
src/common/metrics/src/guarded_metrics.rs
src/connector/src/source/kafka/enumerator/client.rs
src/connector/src/source/kafka/source/reader.rs
src/frontend/src/monitor/stats.rs
src/frontend/src/scheduler/distributed/stats.rs
src/storage/src/hummock/event_handler/hummock_event_handler.rs
src/storage/src/hummock/event_handler/uploader/mod.rs
src/storage/src/monitor/hummock_state_store_metrics.rs

Introduce `UintGuage` to keep consistency with other metric components, and clear up code. 💦
<details>
</details>

refactor(metrics): introduce UintGauge to keep consistency

---

src/storage/hummock_sdk/src/version.rs

As titled.
<details>
</details>

fix(metric): include table change log when calculating Hummock version size

---

src/common/metrics/src/guarded_metrics.rs
src/connector/src/source/kafka/stats.rs

Fix using unit gauge vec macro with imported `AtomicU64`. 💦
<details>
</details>

fix(chore): fix uint gauge vec macro

---

src/frontend/src/handler/create_table.rs
src/frontend/src/handler/create_table_as.rs
src/frontend/src/optimizer/mod.rs

Merge the steps for resolving on-conflict behavior in `CREATE TABLE` handler.
Also support passing an resolved protobuf repr for on-conflict behavior. This is a preparation for #19866.
<details>
</details>

refactor(frontend): merge steps for resolving on-conflict behavior in create table handler

---

src/connector/src/connector_common/iceberg/jni_catalog.rs
src/connector/src/connector_common/iceberg/mod.rs

- Remove icelake dependencies from iceberg jni catalog.
<details>
</details>

refactor(iceberg): refactor jni catalog

---

ci/scripts/cron-e2e-test.sh
ci/scripts/e2e-test-serial.sh
ci/scripts/run-e2e-test.sh
ci/workflows/main-cron.yml
ci/workflows/pull-request.yml

prepare for #18992
<details>
</details>

ci: rename e2e-test to e2e-test-serial

---

Cargo.lock
Cargo.toml
ci/scripts/multi-arch-docker.sh
docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

chore: update version to v2.0.5

---

ci/scripts/e2e-source-test.sh
e2e_test/requirements.txt
e2e_test/source_inline/requirements.txt

as title 
close https://github.com/risingwavelabs/risingwave/issues/19980
<details>
</details>

fix(ci):  cherry-pick fix source test dependency issue (#19840) to branch release-2.1

---

dashboard/lib/api/metric.ts
dashboard/mock-server.js
dashboard/mock/fetch.sh
dashboard/pages/fragment_graph.tsx
dashboard/pages/relation_graph.tsx

Our dashboard allows getting back-pressure data from both Prometheus and Meta node directly. However, this makes the frontend code more and more messy and hard to maintain.
This PR removes the support for Prometheus. In next PR you will see the code can be simplified a lot.
<details>
</details>

feat(dashboard): backpressure: remove the support for Promethues data 		 source

---

e2e_test/batch/types/jsonb.slt.part
e2e_test/batch/types/map.slt.part
src/common/src/types/jsonb.rs

(cherry picked from commit 302c3caa9728a348fa476b43bd9e6f226c9043b0)
cherry-pick
<details>
</details>

fix: support string to number type in JSONB_POPULATE_RECORD (#19937)

---

Cargo.lock
src/compute/Cargo.toml
src/compute/src/telemetry.rs
src/meta/src/telemetry.rs
src/storage/compactor/Cargo.toml
src/storage/compactor/src/telemetry.rs

fix(telemetry): retry telemetry ut 3 times to mitigate failures on CI

---

src/common/src/config.rs
src/meta/src/controller/mod.rs

Workaround for #18966.
<details>
</details>

fix(meta): use unlimited timeout for sqlite backend

---

ci/scripts/common.sh
src/meta/src/stream/stream_manager.rs

introduced in #17428, useless now
<details>
</details>

refactor(meta): cleanup legacy code for v1

---

src/connector/src/sink/iceberg/mod.rs

Add uuid for iceberg data file name suffix to avoid duplicate file name.
<details>
</details>

feat: add uuid for iceberg data file name suffix

---

src/common/rate_limit/src/lib.rs

Ignore leak bucket unit test.
NOTE: The elegant way is to extrace a clock trait and use fake clock when testing, like `governor`. But let's jsut ignore the test first.
<details>
</details>

test: ignore leak bucket unit test

---

ci/scripts/e2e-test-serial.sh

Fix flaky e2e single node test. i.e: https://buildkite.com/risingwavelabs/main-cron/builds/4195#0194320c-a8af-4e03-893f-0616a89417ff
<details>
</details>

chore(test): extend the waiting period for the single node test

---

src/frontend/src/handler/query.rs
src/frontend/src/optimizer/plan_node/utils.rs

Use time zone set by `SET TIME ZONE` if time zone is absent in input, during Hummock time travel query.
The task local variable TIME_ZONE is used to send the time_zone from session config to the optimizer, where timestamp is parsed.
Part of #19757
<details>
</details>

fix(frontend): use set time zone in Hummock time travel

---

ci/scripts/remove-micro-bench-results.sh
ci/scripts/upload-micro-bench-results.sh

cherry-pick https://github.com/risingwavelabs/risingwave/pull/19862
<details>
</details>

chore(ci): migrate the qa service (#19862)

---

src/frontend/planner_test/tests/testdata/input/watermark_group.yaml
src/frontend/planner_test/tests/testdata/output/emit_on_window_close.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml
src/frontend/planner_test/tests/testdata/output/watermark_group.yaml
src/frontend/src/optimizer/plan_node/generic/agg.rs
src/frontend/src/optimizer/plan_node/stream_hash_agg.rs

After #19894, we have the basis to support grouping by multiple watermark columns in EOWC query, as long as they're "related" to each other, which means, derived from the same upstream watermark column. E.g. the following query can now execute while could not before this PR:
```sql
create table t (foo int, ts timestamp as proctime()) append only;
create materialized view mv as
select
window_start, window_end,
count(foo) as count
from tumble(t, ts, interval '5 mins')
group by window_start, window_end
emit on window close;
```
<details> …

feat(eowc): allow multiple watermark columns in eowc hash agg

---

Cargo.lock
Cargo.toml
ci/scripts/e2e-kafka-sink-test.sh
docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.1.1
<details>
</details>

chore: update version to v2.1.1

---

ci/scripts/e2e-kafka-sink-test.sh

following https://github.com/risingwavelabs/risingwave/pull/19840
same change as https://github.com/risingwavelabs/risingwave/pull/20042
<details>
</details>

chore(test): pin pip package version for e2e sink

---

Makefile.toml
e2e_test/sink/pg_native_vs_jdbc.slt
src/connector/src/sink/postgres.rs

Closes https://github.com/risingwavelabs/risingwave/issues/20061
<details>
</details>

perf(stream): optimize native pg sink (#19688)

---

Cargo.lock
Cargo.toml

build(deps): unpatch prost

---

ci/workflows/main-cron.yml

As title.
<details>
</details>

fix(ci): increase timeout for e2e source test in main-cron

---

src/connector/src/source/iceberg/parquet_file_handler.rs

The bug is miss previously overlooked because builder = `builder.disable_config_load();` was not added. As a result, during local testing, **it was able to access S3 normally** since it was reading from the local AWS environment variables.
In other words, if the AWS config is correctly configured locally, it can also be read normally.
The main branch has already been fixed
<details>
</details>

fix(connector): fix file scan s3 access issue in release-2.1

---

src/frontend/src/handler/mod.rs

Just add a missing line.
<details>
</details>

fix(frontend): set `if_not_exists` to false when normalizing `CREATE VIEW`

---

src/connector/src/connector_common/iceberg/mod.rs

- Since iceberg-rust glue catalog doesn't support updating table, so we have to change to the java implementation by default.
<details>
</details>

fix: change iceberg glue catalog default implemantation to java

---

src/frontend/src/handler/explain.rs
src/frontend/src/handler/query.rs
src/frontend/src/scheduler/distributed/query.rs
src/frontend/src/scheduler/plan_fragmenter.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/20036
```
set timezone = 'asia/shanghai';
select * from t for system_time as of '2025-01-09 15:12:50.669';
```
<details>
</details>

fix(iceberg): fix iceberg time travel timezone

---

src/meta/src/hummock/manager/gc.rs

This log is helpful during troubleshooting.
<details>
</details>

refactor: log deleted objects

---

e2e_test/ddl/alter_owner.slt
e2e_test/ddl/alter_set_schema.slt
src/meta/src/controller/catalog/alter_op.rs

fix: synchronize the index on the mview when changing the owner or schema

---

src/meta/src/hummock/manager/gc.rs
src/meta/src/hummock/manager/time_travel.rs
src/meta/src/hummock/manager/versioning.rs

This PR fixes the time travel GC bug that may incorrectly delete objects still being used.
<details>
</details>

fix(meta): fix time travel GC bug

---

ci/scripts/run-e2e-test.sh
ci/scripts/run-meta-backup-test.sh

Follow https://github.com/risingwavelabs/risingwave/pull/20029/files
<details>
</details>

chore(test): extend sleep duration for starting single node

---

src/meta/src/hummock/manager/time_travel.rs

As titled.
<details>
</details>

refactor(meta): use insert_many to reduce latency

---

src/meta/src/manager/license.rs

Due to a breaking change in #19137, the license watcher now counts "access" events on files, which will be triggered spontaneously when we read the file, leading to infinite loop and may exhaust resources.
This PR fixes this issue by ignoring the "access" events for reloading.
<details>
</details>

fix(license): ignore access event when watching license key file changes

---

src/risedevtool/src/task/docker_service.rs
src/risedevtool/src/task/postgres_service.rs

For example, to enable logical replication for Postgres, we need to specify extra configuration through arguments.
<details>
</details>

feat(risedev): specify arguments to docker command & enable logical replication for postgres service

---

src/connector/src/parser/mysql.rs

fix(connector): improve mysql error message

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

chore: update version to v2.1.2

---

.github/workflows/license_check.yml
.github/workflows/typo.yml
src/common/src/config.rs
src/config/example.toml
src/meta/node/src/lib.rs
src/meta/src/hummock/manager/gc.rs
src/meta/src/hummock/manager/time_travel.rs
src/meta/src/manager/env.rs

feat(storage): replace magic number with config for gc

---

ci/workflows/main-cron.yml
ci/workflows/pull-request.yml

ci: reuse plugin with anchor to make yaml shorter

---

Cargo.lock
Cargo.toml
src/storage/Cargo.toml
src/storage/src/store_impl.rs

Changes:
- Switch to foyer 0.14.0
- Export foyer metrics via mixtrics 0.0.2
<details>
</details>

refactor(storage): switch to foyer 0.14.0 and mixtrics 0.0.2

---

docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

Since v2.1.0 is deprecated.
<details>
</details>

fix: update docker compose to use v2.1.2

---

e2e_test/source_inline/tvf/mysql_query.slt

test(connector): add source test for `Date('0000-00-00')`

---

Cargo.lock
Makefile.toml
ci/Dockerfile
ci/build-ci-image.sh
ci/docker-compose.yml
src/tests/simulation/Cargo.toml

test: bump slt 0.26.3

---

src/connector/src/source/cdc/external/mysql.rs

The PR is just for review and no need to merge
<details>
</details>

feat(mysql-cdc): add retry when connecting to mysql

---

ci/workflows/main-cron.yml

https://buildkite.com/risingwavelabs/main-cron/builds/4250#01947a26-2960-4834-b618-78d0332a39db
<details>
</details>

chore: increase e2e parallel in-memory test timeout

---

Cargo.lock

To avoid
```
The following warnings were emitted during compilation:
warning: clickhouse-rs-cityhash-sys@0.1.2: In file included from src/cc/city.cc:31:
warning: clickhouse-rs-cityhash-sys@0.1.2: src/cc/city.h:48:10: fatal error: 'utility' file not found
warning: clickhouse-rs-cityhash-sys@0.1.2:    48 | #include <utility>
warning: clickhouse-rs-cityhash-sys@0.1.2:       |          ^~~~~~~~~
warning: clickhouse-rs-cityhash-sys@0.1.2: 1 error generated.
error: failed to run custom build command for `clickhouse-rs-cityhash-sys v0.1.2`
```
Based on @lmatz's  and …

chore(deps): Bump libz-sys from 1.1.12 to 1.1.21

---

Cargo.lock

To avoid 
```
Compiling async-compression v0.4.5
error[E0425]: cannot find function, tuple struct or tuple variant `BIO_ctrl` in this scope
--> /Users/kexiang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.13.3/src/lib.rs:82:14
|
82 |     unsafe { BIO_ctrl(b, BIO_CTRL_INFO, 0, pp.cast::<c_void>()) }
|              ^^^^^^^^ not found in this scope
error[E0425]: cannot find function, tuple struct or tuple variant `CRYPTO_library_init` in this scope
--> /Users/kexiang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.13.3/src/li …
```

chore(deps): Bump aws-lc-rs from v1.6.2 to 1.12.1

---

Cargo.lock
Cargo.toml
src/storage/Cargo.toml
src/storage/src/store_impl.rs

fix #20230 #20231 
<details>
</details>

cherry-pick: fix: #20076 and #20155

---

Makefile.toml
src/jni_core/src/jvm_runtime.rs

...so that it can use connector features for local development.
Also refine the error message for failing to load connector libs.
<details>
</details>

fix(risedev): set `CONNECTOR_LIBS_PATH` for `risedev playground`

---

src/meta/src/hummock/manager/compaction/mod.rs
src/meta/src/hummock/manager/mod.rs
src/meta/src/hummock/mock_hummock_meta_client.rs

This pull request introduce a new field "table_id_to_table_options" to reduce get_table_id_tables lock calls. 
Since table_id_to_table_options are allowed to not update in real time, we don't have to refetch them from the sql backend every time we get_compact_task. Accessing the catalog_controller requires an async lock, which may cause performance degradation if accessed frequently. Introducing a temporary cache, and reducing its update frequency, is expected to alleviate these problems.
<details>
</details>

refactor(storage): Reduce get_table_id_tables lock calls.

---

src/common/src/config.rs
src/config/example.toml
src/meta/node/src/lib.rs
src/meta/src/hummock/manager/gc.rs
src/meta/src/hummock/manager/tests.rs
src/meta/src/hummock/mod.rs
src/meta/src/manager/env.rs

(cherry picked from commit d00c6e35893791067b55422c4f998c69c35e4f10)
cherry-pick.
close #20215
<details>
</details>

refactor: optimize delta log deletion (#20158)

---

Cargo.lock
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-hdfs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml
integration_tests/iceberg-sink2/docker/hive/docker-compose.yml
integration_tests/iceberg-sink2/docker/jdbc/docker-compose.yml
integration_tests/iceberg-sink2/docker/rest/docker-compose.yml
integration_tests/iceberg-sink2/docker/storage/docker-compose.yml
integration_tests/iceberg-source/docker/hive/docker-compose.yml
integration_tests/iceberg-source/docker/jdbc/docker-compose.yml
integration_tests/iceberg-source/docker/rest/docker-compose.yml
integration_tests/iceberg-source/docker/storage/docker-compose.yml
src/utils/pgwire/Cargo.toml
src/utils/pgwire/src/pg_message.rs

Otherwise we still get `UnexpectedEof` printed in the log, which is confusing.
Also simplify the code for detecting empty stream.
<details>
</details>

refactor(frontend): use empty tcp stream for frontend health check in docker-compose

---

src/expr/core/src/window_function/call.rs
src/prost/helpers/src/generate.rs

Previously, though we may have marked some fields as `deprecated`, the generated helper methods won't be marked with `deprecated`, and then we won't be aware of using a deprecated field if we use these helper methods.
In this PR, we will add a `#[deprecated]` to the helper method to deprecated field.
<details>
</details>

feat(prost): add deprecated attribute for helper methods of deprecated field

---

Cargo.lock

https://github.com/risingwavelabs/risingwave/pull/20252

cherry-pick fix(udf): bump arrow-udf-wasm to 0.4.1 to fix rust udf compile target

---

src/connector/src/source/kafka/private_link.rs

cherry-pick #20154
<details>
</details>

feat: make privatelink.endpoint accept json array (#20154)

---

src/meta/src/hummock/manager/time_travel.rs

Otherwise inserting into meta store will fail with `ON CONFLICT DO UPDATE command cannot affect row a second time`.
Reproduce:
```
CREATE TABLE t (v1 int)
WITH (
connector = 'datagen',
fields.v1.kind = 'random',
datagen.rows.per.second = '1'
)
FORMAT PLAIN
ENCODE JSON;
CREATE TABLE t2 (v1 int)
WITH (
connector = 'datagen',
fields.v1.kind = 'random',
datagen.rows.per.second = '1'
)
FORMAT PLAIN
ENCODE JSON;
CREATE SUBSCRIPTION s FROM t WITH (
retention = '7d'
);
CREATE SUBSCRIPTION s2 FROM t2 WITH (
retention = '7d'
);
```
<details> …

fix(meta): deduplicate pk when writing time travel metadata

---

src/connector/src/source/kafka/private_link.rs

resolve https://github.com/risingwavelabs/risingwave/issues/20270
<details>
</details>

feat: make privatelink.endpoint accept json array (#20233)

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.0.6
<details>
</details>

chore: update version to v2.0.6

---

e2e_test/source_inline/kafka/shared_source.slt.serial

https://github.com/risingwavelabs/risingwave/issues/20285
causing panics: https://github.com/risingwavelabs/risingwave/pull/20290#issuecomment-2611767615
<details>
</details>

fix(test): didn't drop source but deleted topic

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.2.0-rc.1
<details>
</details>

chore: update version to v2.2.0-rc.1

---

src/storage/hummock_sdk/src/lib.rs

When ckpt > 1, the same user key may exist in different ssts in the overlapping sublevel.
Therefore the epoch in the full key should be considered in the judgement of can concat.
<details>
</details>

fix(compactor): fix full key can concat

---

ci/workflows/main-cron.yml
ci/workflows/pull-request.yml
e2e_test/streaming/bug_fixes/issue_20342.slt
e2e_test/streaming/bug_fixes/issue_20342.slt.part
src/stream/src/executor/backfill/utils.rs

Closes https://github.com/risingwavelabs/risingwave/issues/20361
<details>
</details>

 feat(stream): normalize unmatched updates #20350 

---

src/connector/src/sink/mongodb.rs

Closes #20311
<details>
</details>

fix(sink): fix mongodb write error handling #19869 

---

ci/workflows/pull-request.yml
e2e_test/streaming/bug_fixes/issue_20342.slt
e2e_test/streaming/bug_fixes/issue_20342.slt.part
src/stream/src/executor/backfill/utils.rs

Closes https://github.com/risingwavelabs/risingwave/issues/20364
<details>
</details>

feat(stream): normalize unmatched updates #20350 

---

src/ctl/src/cmd_impl/hummock/sst_dump.rs
src/frontend/src/catalog/system_catalog/rw_catalog/rw_hummock_version.rs
src/meta/src/hummock/compaction/picker/manual_compaction_picker.rs
src/meta/src/hummock/compaction/picker/space_reclaim_compaction_picker.rs
src/meta/src/hummock/compaction/picker/tombstone_reclaim_compaction_picker.rs
src/meta/src/hummock/compaction/picker/trivial_move_compaction_picker.rs
src/meta/src/hummock/compaction/picker/ttl_reclaim_compaction_picker.rs
src/meta/src/hummock/compaction/picker/vnode_watermark_picker.rs
src/meta/src/hummock/compaction/selector/mod.rs
src/meta/src/hummock/manager/commit_epoch.rs
src/meta/src/hummock/manager/tests.rs
src/meta/src/hummock/manager/versioning.rs
src/meta/src/hummock/test_utils.rs
src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
src/storage/hummock_sdk/src/compaction_group/mod.rs
src/storage/hummock_sdk/src/sstable_info.rs
src/storage/hummock_test/src/hummock_read_version_tests.rs
src/storage/hummock_test/src/hummock_storage_tests.rs
src/storage/src/hummock/compactor/iterator.rs
src/storage/src/hummock/event_handler/uploader/test_utils.rs
src/storage/src/hummock/sstable/builder.rs
src/storage/src/hummock/test_utils.rs

(cherry picked from commit 4b1cb92e5ce37c72139f933b525ed9c41aec575f)
cherry pick #19535
<details>
</details>

refactor(storage): use Arc<SStableInfo> in HummockVersion (#19535)

---

java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/DbzConnectorConfig.java
java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/PostgresValidator.java
java/connector-node/risingwave-connector-service/src/main/resources/validate_sql.properties
java/connector-node/risingwave-source-cdc-test/src/test/java/com/risingwave/connector/source/PostgresSourceTest.java
java/connector-node/risingwave-source-cdc-test/src/test/java/com/risingwave/connector/source/SourceTestClient.java

As @edeesis use his own fork to submit codes and it's troublesome for me to submit my change to his branch. I move all the changes of the original [PR](https://github.com/risingwavelabs/risingwave/pull/19021/files) here. Thanks for your effort.
The changes resolve https://github.com/risingwavelabs/risingwave/issues/19020.
All the credit goes to @edeesis
<details>
</details>

fix(pg-cdc): fix role-based permission for rds

---

e2e_test/s3/fs_sink.py

As title。
<details>
</details>

chore(test): remove not cherry picked test

---

e2e_test/sink/elasticsearch/elasticsearch_sink.slt
src/connector/src/sink/elasticsearch_opensearch/elasticsearch.rs
src/connector/src/sink/elasticsearch_opensearch/elasticsearch_converter.rs
src/connector/src/sink/elasticsearch_opensearch/elasticsearch_opensearch_client.rs
src/connector/src/sink/elasticsearch_opensearch/elasticsearch_opensearch_config.rs
src/connector/src/sink/elasticsearch_opensearch/elasticsearch_opensearch_formatter.rs
src/connector/src/sink/elasticsearch_opensearch/opensearch.rs
src/connector/src/sink/remote.rs
src/connector/with_options_sink.yaml

cherry-pick feat(sink): support force_append_only for es sink (#19919) + fix(sink): fix es sink username must required (#20304)

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.1.3
<details>
</details>

chore: update version v2.1.3

---

ci/workflows/main-cron.yml

chore: increase main-cron test timeout

---

ci/workflows/main-cron.yml

chore: increase main-cron in-memory test timeout

---

src/storage/src/monitor/monitored_store.rs
src/storage/src/monitor/traced_store.rs
src/storage/src/store_impl.rs
src/stream/src/task/barrier_manager.rs

fix(storage): fix state store sync metrics

---

Cargo.lock

`arrow-udf-wasm` 0.4.1 changed the wasi target from `wasm32-wasi` to `wasm32-wasip1` following the upstream `rustc` change.
According to the notice:
```
Starting Rust 1.78 (May 2nd, 2024), users of WASI 0.1 are encouraged to begin migrating to the new wasm32-wasip1 target before the existing wasm32-wasi target is removed in Rust 1.84 (January 5th, 2025).
```
the old target name is officially deprecated in latest version.
<details>
</details>

fix(udf): bump `arrow-udf-wasm` to 0.4.1 to fix rust udf compile target

---

src/storage/src/store.rs
src/stream/src/common/log_store_impl/kv_log_store/mod.rs
src/stream/src/common/log_store_impl/kv_log_store/reader.rs
src/stream/src/common/log_store_impl/kv_log_store/state.rs
src/stream/src/common/log_store_impl/kv_log_store/writer.rs
src/stream/src/executor/sync_kv_log_store.rs

In this PR, we will introduce a `LogStoreReadState` and `LogStoreWriteState`, and they serve similar functionality to `StateTable`, which wraps `LocalStateStore` and provide some methods to do serde. Common methods are extracted to the two structs and shared by the sink log store and the newly implemented sync log store.
<details>
</details>

refactor(log-store): extract common read write methods to log store state

---

src/connector/src/sink/file_sink/opendal_sink.rs

as titled. This PR is to merge the PR to the customer's customized branch. It would also would be merged to main. https://github.com/risingwavelabs/risingwave/pull/20418
<details>
</details>

feat(dal-sink): support dynamic json handle mode

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.2.0
<details>
</details>

chore: update version to v2.2.0

---

src/stream/src/common/log_store_impl/kv_log_store/state.rs
src/stream/src/executor/sync_kv_log_store.rs

refactor(log-store): refine synced log store executor implementation

---

ci/scripts/e2e-test-serial.sh
e2e_test/commands/internal_table.mjs
e2e_test/queryable_internal_state/group_agg.slt
e2e_test/streaming/aggregate/state_management.slt
src/stream/src/common/table/state_table.rs
src/stream/src/executor/aggregation/agg_group.rs
src/stream/src/executor/hash_agg.rs
src/stream/src/executor/simple_agg.rs
src/stream/src/executor/sort_buffer.rs
src/stream/src/from_proto/hash_agg.rs
src/stream/src/from_proto/simple_agg.rs

Some days before, @BugenZhao found a bug of hash agg that, old groups are not deleted even when row count drops to 0. After some analysing, I found it introduced in https://github.com/risingwavelabs/risingwave/commit/7a02d12ef2eb771d605013b1af522998db4209b1 when we introduce `intermediate_state_table`. We thought we only need to UPDATE the inter states with the NEW value, but it turns out that we still need to maintain a `prev_inter_states` just like how we maintain the `prev_outputs`.
This PR splits the building process of inter states and outputs, for …

fix(hash agg): split `AggGroup` inter states and outputs change building, fixing old groups not deleted bug

---

src/stream/src/executor/source/fs_fetch_executor.rs

feat(stream): inform rate limit update for fsfetch executor

---

proto/stream_plan.proto
src/frontend/src/optimizer/plan_node/stream_table_scan.rs
src/frontend/src/stream_fragmenter/mod.rs
src/meta/src/barrier/checkpoint/control.rs
src/meta/src/barrier/command.rs
src/meta/src/barrier/context/context_impl.rs
src/meta/src/barrier/notifier.rs
src/meta/src/barrier/progress.rs
src/meta/src/barrier/rpc.rs
src/meta/src/controller/fragment.rs
src/meta/src/rpc/ddl_controller.rs
src/meta/src/stream/stream_graph/fragment.rs
src/meta/src/stream/stream_manager.rs
src/stream/src/executor/backfill/snapshot_backfill/consume_upstream/executor.rs
src/stream/src/executor/backfill/snapshot_backfill/state.rs
src/stream/src/from_proto/stream_scan.rs
src/stream/src/task/barrier_manager/progress.rs

After https://github.com/risingwavelabs/risingwave/pull/20167.
Added a new stream scan type for cross db stream table scan, and a new backfill executor variant for the new stream scan type.The barrier manager will handle this new stream scan type and fill in the snapshot epoch to the stream scan node.
<details>
</details>

feat(snapshot-backfill): support cross db snapshot backfill

---

e2e_test/source_inline/nats/operation.py
e2e_test/source_inline/nats/test.slt.serial
src/connector/src/source/mod.rs

resolve #20447 
`+ACK` is more precise for ack a message in NATS 
We still gets the error `EOF while parsing a value at line 1 column 0` but it does not affect the ack function. So we don't check the result.
<details>
</details>

fix: ack nats message properly

---

src/meta/src/hummock/manager/compaction/compaction_group_schedule.rs

fix(storage): fix data race

---

src/utils/pgwire/src/pg_protocol.rs

This PR refactors the TruncatedFormatter so that when a string is truncated, its original length is also displayed.
The goal is to identify any potentially very long SQL statements, such as `INSERT INTO t VALUES (..),(..)...(..)`.
Related: #20470
<details>
</details>

refactor: display original length for truncated fmt

---

ci/workflows/main-cron.yml

no abnormal log, just increase timeout to see whether it pass.
<details>
</details>

chore(main-cron): increase timeout for failed test

---

.github/labeler.yml

chore: labeler backward compat tests when migration updated

---

java/connector-node/risingwave-sink-iceberg/src/main/java/com/risingwave/connector/catalog/JniCatalogWrapper.java
src/connector/src/connector_common/iceberg/jni_catalog.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/20461
- Most JNI catalogs are closable objects, we need to explicitly close them to release the resource (e.g. JdbcCatalog holds a connection pool internally, if we don't handle it properly, it would cause connections leak).
<details>
</details>

fix(iceberg): fix jni catalog resource leak

---

Cargo.lock
src/batch/executors/Cargo.toml
src/batch/executors/src/executor/iceberg_scan.rs
src/connector/src/connector_common/iceberg/mod.rs
src/connector/src/source/iceberg/mod.rs

This method seems useless compared with directly `load_table`. 
Note that we use `load_table` to get the `table_meta` first, and then use `load_table_with_metadata`
<details>
</details>

refactor(iceberg): remove table_meta in IcebergSplit and load_table_with_metadata

---

docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

chore: update docker-compose files to use v2.2.0

---

ci/scripts/multi-arch-docker.sh
docker/README.md

Fix https://github.com/risingwavelabs/risingwave/issues/18863 and address https://risingwave-labs.slack.com/archives/C03KED89H88/p1739258501343789
* Add semver version for nightly images.
* Tag `latest` only for the latest stable version.
<details>
</details>

chore(ci): refactor image tags

---

ci/scripts/multi-arch-docker.sh

chore: fix docker script PATH

---

src/stream/src/executor/sync_kv_log_store.rs

fix(logstore): fix merging of `LogStoreBufferItem::Flushed`

---

src/frontend/src/handler/create_table.rs

- Use `create iceberg source xx (*) with`  instead of `create iceberg source xx with` to skip the warning message.
<details>
</details>

fix(iceberg): fix creating iceberg table warning 

---

src/meta/src/hummock/manager/commit_epoch.rs
src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
src/storage/hummock_sdk/src/compaction_group/mod.rs
src/storage/hummock_sdk/src/sstable_info.rs

fix(storage): fix unexpected sstable size zero

---

ci/scripts/multi-arch-docker.sh
docker/README.md

cherry-pick chore: refactor image tag

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.2.1
<details>
</details>

chore: update version to v2.2.1

---

e2e_test/sink/kafka/protobuf.slt
src/connector/src/sink/encoder/proto.rs

RisingWave does not have native enum data type. In the source part, a protobuf enum is ingested as varchar. This PR adds the ability to sink a varchar into a protobuf enum.
<details>
</details>

feat(sink): support protobuf enum from varchar

---

e2e_test/batch/catalog/information_schema.slt
e2e_test/batch/catalog/pg_class.slt.part
src/frontend/src/catalog/system_catalog/information_schema/key_column_usage.rs
src/frontend/src/catalog/system_catalog/information_schema/mod.rs
src/frontend/src/catalog/system_catalog/pg_catalog/mod.rs
src/frontend/src/catalog/system_catalog/pg_catalog/pg_stat_user_tables.rs

cherry pick to 2.2
<details>
</details>

feat: support pg_stat_user_tables and key_column_usage (#19739)

---

ci/workflows/pull-request.yml

chore: increase parallel e2e test timeout

---

ci/scripts/release.sh

For Homebrew releases. Otherwise we need to download the full `all-in-one` asset.
<details>
</details>

chore: also release connector libs separately

---

docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

chore: update docker compose images to v2.2.1

---

src/frontend/src/binder/relation/table_or_source.rs
src/frontend/src/catalog/schema_catalog.rs
src/meta/src/barrier/context/context_impl.rs
src/meta/src/controller/streaming_job.rs

Closes https://github.com/risingwavelabs/risingwave/issues/19031
We notify the MV catalog to the frontend only after the vnode bitmap field is filled up.
We also report the fragments to FE, before the stream job is finished creating, they are also required to run batch queries.
<details>
</details>

feat(meta): expose internal table catalog during backfill phase to batch engine

---

src/connector/src/sink/iceberg/mod.rs

- When using `create_table_if_not_exists` together with `partition_by`, we need to specify the partition spec id and field id to make JNI json serialize/deserialize happy.
<details>
</details>

fix(iceberg): iceberg partition by should specify field id and the partition spec id

---

e2e_test/batch/functions/cast.slt.part
src/frontend/src/binder/expr/mod.rs

- Allow to use `cast char` in SQL and redirect it to `cast varchar`, because some ecosystems like metabase will use it to query the system table. 
<details>
</details>

feat(frontend): redirect cast char to varchar

---

e2e_test/source_inline/kafka/alter_table_drop_connector.slt

fix a flaky test in https://github.com/risingwavelabs/risingwave/pull/20023
<details>
</details>

test: add retry for check on drop table connector

---

integration_tests/client-library/java/src/test/java/com/risingwave/TestCursor.java
integration_tests/client-library/java/src/test/java/com/risingwave/TestUtils.java
src/frontend/src/binder/declare_cursor.rs
src/frontend/src/binder/statement.rs
src/frontend/src/handler/declare_cursor.rs
src/frontend/src/handler/extended_handle.rs
src/frontend/src/handler/privilege.rs
src/frontend/src/handler/query.rs
src/frontend/src/planner/statement.rs

feat(frontend): support extended query mode for declare subscription cursor

---

src/common/src/util/cluster_limit.rs
src/frontend/src/session.rs

I found we are frequently asked about “Actor count per parallelism exceeds the critical limit”. It seems users don’t read the err message. And we also just reply `SET bypass_cluster_limits TO true`.
Try to refine the message to be more effective.
now:
<details>
</details>

feat: refine check_cluster_limits error message

---

e2e_test/batch/catalog/sysinfo.slt.part
src/frontend/src/expr/function_impl/cast_regclass.rs

The database name was not correctly handled in `cast_regclass`. Should use `resolve_schema_qualified_name` to resolve schema and name.
<details>
</details>

fix(expr): use resolve_schema_qualified_name in cast_regclass

---

src/common/src/catalog/column.rs
src/common/src/catalog/mod.rs
src/connector/src/parser/debezium/debezium_parser.rs
src/connector/src/parser/mod.rs
src/connector/src/parser/plain_parser.rs
src/connector/src/source/cdc/external/mysql.rs
src/connector/src/source/manager.rs
src/connector/src/source/nexmark/source/combined_event.rs
src/connector/src/source/pulsar/source/reader.rs
src/frontend/src/binder/select.rs
src/frontend/src/catalog/mod.rs
src/frontend/src/catalog/table_catalog.rs
src/frontend/src/handler/alter_table_column.rs
src/frontend/src/handler/create_mv.rs
src/frontend/src/handler/create_source.rs
src/frontend/src/handler/create_source/external_schema.rs
src/frontend/src/handler/create_source/external_schema/iceberg.rs
src/frontend/src/handler/create_table.rs
src/frontend/src/optimizer/plan_node/stream_cdc_table_scan.rs
src/frontend/src/planner/relation.rs

refactor (completely equivalent rewrite. No logic change): 
1. rename `ROWID_PREFIX` to `ROWID_COLUMN_NAME`
2. Add `CDC_` prefix to `[OFFSET/TABLE_NAME]_COLUMN_NAME` 
3. merge col definitions into `iceberg_hidden_cols`, `debezium_cdc_source_cols`
4. delete some unused methods
<details>
</details>

refactor: improve some special column handling

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.1.4
<details>
</details>

chore: update version to v2.1.4

---

src/frontend/src/catalog/system_catalog/rw_catalog/rw_secrets.rs

per requested by @neverchanje for cloud design
<details>
</details>

feat(rw_catalog): add schema id for rw_secrets

---

Cargo.lock
Cargo.toml

Fix #20527. E2e tests for this bug exists but not run, will be reorganized and run in #20531.
There's still some recent work to do in arrow-udf-python, so let's use the revision (which currently points to the latest commit on main) first. I'll update to a released version later.
<details>
</details>

fix(udf): update arrow-udf-python to fix python embedded udf panic

---

.git-blame-ignore-revs
src/common/src/array/data_chunk.rs
src/common/src/catalog/column.rs
src/frontend/src/handler/create_source.rs
src/frontend/src/handler/create_source/external_schema/iceberg.rs

refactor: remove unnessary check_iceberg_source
- Originally added in #14971 (When we can specify columns)
- After #15415, derive columns from iceberg source automatically and the check becomes useless.
<details>
</details>

refactor: remove unnessary check_iceberg_source

---

src/frontend/src/scheduler/local.rs

This line is part of #20470.
<details>
</details>

refactor(batch): release PlanNode early

---

src/connector/codec/src/decoder/protobuf/parser.rs
src/connector/codec/tests/integration_tests/protobuf.rs

Similar to #20559 (avro).
<details>
</details>

refactor(source): simplify Protobuf field to SQL column mapping

---

src/frontend/src/handler/mod.rs

match statement first, then match operation.
Previously, the outer match is too large.
<details>
</details>

refactor: make handler more organized

---

.github/labeler.yml

similar to #20574
<details>
</details>

ci: auto label for s3 source

---

src/common/src/catalog/column.rs
src/connector/benches/nexmark_integration.rs
src/connector/src/parser/json_parser.rs
src/frontend/src/catalog/system_catalog/mod.rs
src/frontend/src/scheduler/distributed/query.rs
src/storage/src/compaction_catalog_manager.rs
src/stream/src/executor/lookup/tests.rs

`new_atomic` and `new_struct` are merged into `named`, as mentioned in #20497.
<details>
</details>

refactor(common): consolidate `ColumnDesc` constructors

---

src/common/src/catalog/column.rs
src/connector/codec/src/decoder/avro/mod.rs
src/connector/codec/src/decoder/avro/schema.rs
src/connector/codec/src/decoder/json/mod.rs
src/connector/codec/src/decoder/protobuf/parser.rs
src/connector/codec/tests/integration_tests/avro.rs
src/connector/codec/tests/integration_tests/json.rs
src/connector/codec/tests/integration_tests/protobuf.rs
src/connector/codec/tests/integration_tests/utils.rs
src/connector/src/parser/avro/parser.rs
src/connector/src/parser/debezium/avro_parser.rs
src/connector/src/parser/json_parser.rs
src/connector/src/parser/protobuf/parser.rs
src/frontend/src/handler/create_source/external_schema/avro.rs
src/frontend/src/handler/create_source/external_schema/json.rs
src/frontend/src/handler/create_source/external_schema/protobuf.rs

https://github.com/risingwavelabs/risingwave/blob/4a63ece56e30568d66b8e764ccaf8e4d97933832/src/connector/codec/src/decoder/avro/schema.rs#L75-L79
Complete the TODO above. Actually this function only derives column name and data type, where `Field` fits best. The column id is actually assigned in `create` handler - this is clearer now as `ColumnId::placeholder()` is used in the `frontend` crate rather than `connector` crate.
<details>
</details>

refactor(source): column derivation shall return `Field` rather than `PbColumnDesc`

---

Cargo.lock
ci/Dockerfile
ci/scripts/build-other.sh
ci/scripts/e2e-test-parallel.sh
ci/scripts/slow-e2e-test.sh
docker/Dockerfile
docker/Dockerfile.hdfs
e2e_test/udf/embedded/wasm_udf.slt
e2e_test/udf/wasm/.cargo/config.toml
e2e_test/udf/wasm/Cargo.toml
src/expr/impl/Cargo.toml
src/expr/impl/src/udf/wasm.rs

As titled. We failed to compile with the newly release chrono version 0.4.40. Therefore, in this PR we will use a fixed version 0.4.39.
Besides, when compiling with target `wasm32-wasi`, it shows the following warning
```
warning: the `wasm32-wasi` target is being renamed to `wasm32-wasip1` and the `wasm32-wasi` target will be removed from nightly in October 2024 and removed from stable Rust in January 2025
```
Therefore, we change `wasm32-wasi` to `wasm32-wasip1` in the whole codebase.
<details>
</details>

fix(udf): fix wasm e2e test compile and update build target

---

ci/scripts/run-backfill-tests.sh
src/stream/src/executor/backfill/arrangement_backfill.rs

This code path is not well tested. We add a scale in test for background ddl here. Without the upstream commit, this test will fail.
Closes https://github.com/risingwavelabs/risingwave/issues/17015
<details>
</details>

test(backfill): add scale in test for arrangement backfill in background ddl

---

src/meta/src/barrier/worker.rs

During oncall I found a customer's cluster recovered, but didn't find any recover related log. Authough they are using an old version (2.0), it seems latest version also don't have these logs.
There's also no useful info in event log:
```
>  select timestamp, info from rw_event_logs  where event_type = 'COLLECT_BARRIER_FAIL'
│ 2025-02-26 05:20:10.745+00:00 │ {"collectBarrierFail": {"curEpoch": "8081375879954432", "error": "get error from control stream, in worker node 2: gRPC request to stream service failed: …
```

feat: add some logs for recovery

---

Cargo.lock
ci/Dockerfile
ci/scripts/build-other.sh
ci/scripts/slow-e2e-test.sh
docker/Dockerfile
docker/Dockerfile.hdfs
e2e_test/udf/wasm/.cargo/config.toml
e2e_test/udf/wasm/Cargo.toml
e2e_test/udf/wasm_udf.slt
src/expr/impl/Cargo.toml
src/expr/impl/src/udf/wasm.rs

cherry-pick fix(udf): fix wasm e2e test compile and update build target (#20623) to branch release-2.1

---

ci/scripts/e2e-test-parallel-for-opendal.sh
ci/scripts/e2e-test-parallel-in-memory.sh
ci/scripts/e2e-test-parallel.sh
ci/scripts/e2e-test-serial.sh
ci/scripts/slow-e2e-test.sh

Use `risedev slt` instead of `sqllogictest` in related places.
<details>
</details>

fix(ci): sqllogictest command not found

---

src/common/src/catalog/column.rs
src/common/src/catalog/schema.rs
src/common/src/catalog/test_utils.rs
src/connector/src/sink/big_query.rs
src/connector/src/sink/clickhouse.rs
src/frontend/src/catalog/table_catalog.rs

* `Field::sub_fields` -> `StructType::iter`
* `PbColumnDesc::new_atomic`/`PbColumnDesc::new_struct` -> `PbColumnDesc::new`
<details>
</details>

refactor(struct): cleanup remaining special treatment of `struct`

---

Cargo.lock
ci/Dockerfile
ci/scripts/build-other.sh
ci/scripts/run-e2e-test.sh
ci/scripts/slow-e2e-test.sh
docker/Dockerfile
docker/Dockerfile.hdfs
e2e_test/udf/wasm/.cargo/config.toml
e2e_test/udf/wasm/Cargo.toml
e2e_test/udf/wasm_udf.slt
src/expr/impl/Cargo.toml
src/expr/impl/src/udf/wasm.rs

cherry-pick fix(udf): fix wasm e2e test compile and update build target (#20623) to branch release-2.2

---

src/stream/src/executor/source/source_backfill_executor.rs

fix: should not use static for source backfill state table

---

src/connector/src/connector_common/connection.rs
src/connector/src/connector_common/iceberg/mod.rs
src/connector/src/sink/iceberg/mod.rs
src/connector/with_options_sink.yaml
src/connector/with_options_source.yaml

- Make `catalog.name` totally optional, since we have a default catalog name `risingwave` already.
<details>
</details>

fix(iceberg): refine iceberg catalog parameter validation

---

proto/data.proto
src/common/src/types/mod.rs
src/common/src/types/struct_type.rs
src/prost/src/lib.rs

Add `field_ids` to the fields in a struct type, if it's used in a table schema. They will be further used in column-aware encoding to support evolution for nested schema (https://github.com/risingwavelabs/risingwave/issues/19755) in future PRs.
It's made a separate field instead of inside the `fields` slice, because in most cases it will not be present. Although this may seem a bit hacky or dirty, it requires minimal code changes.
<details>
</details>

feat(types): add id to struct fields

---

src/jni_core/src/jvm_runtime.rs

- Throw a more user-friendly jni error.
- Previously once an exception is thrown by Jni. The error message could only be found in the log and users see only `Java Error` which is not user-friendly. This PR displays the JNI error message to the users.
```
1: gRPC request to meta service (call `/ddl_service.DdlService/CreateConnection`) failed: Internal error
2: Caught Java Exception: org.apache.iceberg.jdbc.UncheckedSQLException: Failed to connect: jdbc:postgresql://127.0.0.1:84321/metadatax
```
<details> …

fix(jni): more user friendly jni error

---

e2e_test/source_legacy/cdc/cdc.share_stream.slt
e2e_test/source_legacy/cdc/mysql_create.sql
e2e_test/source_legacy/cdc/postgres_cdc.sql
e2e_test/source_legacy/cdc_inline/sql_server_cdc/sql_server_cdc.slt
src/frontend/src/handler/create_table.rs

changes from ~~https://github.com/risingwavelabs/risingwave/pull/19255~~ #19354
#20625
https://buildkite.com/risingwavelabs/docker/builds/17020
credit to @BugenZhao 
<details>
</details>

fix: revert default value for CDC to workaround #20625

---

e2e_test/background_ddl/basic.slt
e2e_test/background_ddl/sim/basic.slt
src/frontend/src/catalog/root_catalog.rs
src/tests/simulation/src/slt.rs

When background_ddl is used on some MV, and we attempt to recreate the MV with `if not exists`, it errors out before this PR. We fix it by getting all names, not just created ones, to check for duplicates.
See slt test for more details.
<details>
</details>

fix(frontend): avoid error when `create materialized view if not exists` on existing background mv

---

src/connector/src/parser/access_builder.rs
src/connector/src/parser/avro/parser.rs
src/connector/src/parser/bytes_parser.rs
src/connector/src/parser/chunk_builder.rs
src/connector/src/parser/debezium/avro_parser.rs
src/connector/src/parser/debezium/debezium_parser.rs
src/connector/src/parser/debezium/mongo_json_parser.rs
src/connector/src/parser/debezium/simd_json_parser.rs
src/connector/src/parser/json_parser.rs
src/connector/src/parser/maxwell/maxwell_parser.rs
src/connector/src/parser/plain_parser.rs
src/connector/src/parser/protobuf/parser.rs
src/connector/src/parser/upsert_parser.rs
src/connector/src/source/base.rs
src/connector/src/source/pulsar/source/message.rs
src/connector/src/source/pulsar/source/mod.rs

This is a pre-requisite of Pulsar Schema support for avro. Unlike Confluent or AWS Glue schema registry, where the schema version is prepended at the beginning of message payload, Pulsar puts the version alongside the payload. So we need to pass such metadata (similar to message timestamp) into `AvroAccessBuilder`.
<details>
</details>

feat(source): pass `PulsarMeta` to `AvroAccessBuilder`

---

src/stream/src/executor/source/source_backfill_executor.rs

In #20606, we forgot to check `state_table_initialized` before calling `backfill_finished`
fix #20687
<details>
</details>

fix: fix shared source scale bug again

---

docker/Dockerfile

Getting below error if I do not install git. Is not installing git on purpose? 
```
=> ERROR [rust-builder 3/3] RUN cargo fetch &&   cargo build -p risingwave_cmd_all --profile  --features "rw-static-li  0.2s
------
> [rust-builder 3/3] RUN cargo fetch &&   cargo build -p risingwave_cmd_all --profile  --features "rw-static-link" --features all-udf &&   mkdir -p /risingwave/bin &&     mv /risingwave/target//risingwave /risingwave/bin/ &&     mv /risingwave/target//risingwave.dwp /risingwave/bin/ &&   cp ./target//build/tikv-jemalloc-sys-*/out/build/bin/jeprof …
```

fix: Dockerfile

---

Cargo.lock
Cargo.toml
ci/scripts/common.sh
e2e_test/udf/embedded/js_udf.slt
e2e_test/udf/js_async_udf.slt
proto/catalog.proto
proto/expr.proto
src/expr/core/src/aggregate/user_defined.rs
src/expr/core/src/expr/expr_udf.rs
src/expr/core/src/sig/udf.rs
src/expr/core/src/table_function/user_defined.rs
src/expr/impl/Cargo.toml
src/expr/impl/src/udf/python.rs
src/expr/impl/src/udf/quickjs.rs
src/frontend/src/catalog/function_catalog.rs
src/frontend/src/expr/user_defined_function.rs
src/frontend/src/handler/create_aggregate.rs
src/frontend/src/handler/create_function.rs
src/frontend/src/handler/create_sql_function.rs
src/meta/model/migration/src/lib.rs
src/meta/model/migration/src/m20250210_170743_function_options.rs
src/meta/model/src/function.rs
src/meta/src/controller/mod.rs
src/sqlparser/src/ast/mod.rs
src/tests/simulation/src/slt.rs

Let's release this feature in 2.3.
Links:
- https://github.com/risingwavelabs/risingwave/pull/20403
- https://github.com/risingwavelabs/risingwave-docs/issues/272

cherry-pick feat(udf): introduce async and batched JavaScript UDF (#20403) to 2.3

---

src/frontend/planner_test/planner_test.toml
src/frontend/planner_test/tests/testdata/input/struct_query.yaml
src/frontend/planner_test/tests/testdata/output/struct_query.yaml
src/frontend/src/expr/function_call.rs

Previously, the messages for "too few" and "too many" were inverted. Also enrich it to show field count and add planner tests.
<details>
</details>

fix(frontend): fix error message for casting `ROW` expression with mismatched field count

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.2.2
<details>
</details>

chore: update version to v2.2.2

---

e2e_test/background_ddl/basic.slt

As title
The specific issue still needs to be resolved
<details>
</details>

fix: Temporarily add sleep to prevent unexpected test failures

---

Cargo.lock
Cargo.toml
ci/workflows/pull-request.yml

chore: update package version to v2.4.0-alpha

---

src/frontend/planner_test/tests/testdata/input/asof_join.yaml
src/frontend/planner_test/tests/testdata/output/asof_join.yaml
src/frontend/src/optimizer/plan_node/generic/join.rs

- Push down predicates for asof join.
<details>
</details>

fix(optimizer): fix predicate pushdown for asof join

---

ci/Dockerfile
docker/Dockerfile

`1.28.0` does not install toolchain automatically. We need to install it.
[test](https://buildkite.com/risingwavelabs/docker/builds/17054)
<details>
</details>

fix(ci): fix rustup 1.28.0 breaking change

---

src/ctl/src/cmd_impl/meta/backup_meta.rs

- Adds rw version to meta backup log
<details>
</details>

feat: add rw version to meta backup log

---

e2e_test/source_inline/connection/alter_owner_to.slt
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/jdbc/PostgresDialect.java
proto/ddl_service.proto
src/frontend/src/catalog/system_catalog/pg_catalog/pg_class.rs
src/frontend/src/handler/alter_owner.rs
src/frontend/src/handler/mod.rs
src/meta/src/controller/catalog/alter_op.rs
src/meta/src/rpc/ddl_controller.rs
src/sqlparser/src/ast/ddl.rs
src/sqlparser/src/parser.rs

Add support for changing the owner of a connection object, including:
- Extending the SQL parser to recognize OWNER TO syntax
- Implementing owner change handling in the frontend
- Updating catalog and RPC controllers to support connection ownership changes
part of https://github.com/risingwavelabs/risingwave/issues/20700
<details>
</details>

feat: support ALTER CONNECTION OWNER TO 

---

.github/workflows/doc.yml
ci/scripts/release.sh
docker/Dockerfile.hdfs

Prefix the install command everywhere there's `rustup show` called
<details>
</details>

fix(ci): fix rust toolchain

---

.github/workflows/update-pr-template-by-version.yml

fix: update latest release branch in pr template

---

src/storage/compactor/src/lib.rs
src/storage/compactor/src/server.rs
src/storage/src/hummock/sstable/multi_builder.rs

fix(storage): fix compactor meta cache config

---

src/frontend/src/handler/create_table.rs
src/license/src/feature.rs

- Iceberg engine shouldn't be a paid feature
<details>
</details>

fix(iceberg): revert iceberg engine paid feature

---

.github/workflows/cherry-pick-since-release-branch.yml

`The expression is not closed. An unescaped ${{ sequence was found, but the closing }} sequence was not found.`
<details>
</details>

fix(action): correctly escape hashtag

---

src/common/src/config.rs
src/compute/src/rpc/service/exchange_service.rs
src/config/example.toml
src/frontend/src/scheduler/distributed/stage.rs

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
(cherry picked from commit 2b66fe374a7386f62443744b5e372cfb15ffd7e9)
close #20744
<details>
</details>

refactor: replace hardcoded buffer size with config (#20738)

---

.github/workflows/update-pr-template-by-version.yml

chore: add diff in update pr template github action

---

src/connector/src/connector_common/iceberg/mod.rs

- As title.
<details>
</details>

fix(iceberg): reject iceberg on gcs with catalog rather than rest and storage

---

src/frontend/src/catalog/mod.rs
src/frontend/src/catalog/root_catalog.rs
src/frontend/src/handler/create_database.rs
src/frontend/src/handler/create_schema.rs
src/frontend/src/handler/create_source.rs
src/frontend/src/handler/create_user.rs
src/frontend/src/session.rs
src/meta/src/rpc/ddl_controller.rs
src/meta/src/stream/stream_manager.rs
src/tests/simulation/src/lib.rs
src/tests/simulation/src/slt.rs

Currently in background ddl, we return without waiting for collecting and committing the first barrier. However, we will only retry the background ddl job until the first barrier is collected and committed so that the job info can be marked as creating. If we early return, users may think that the background ddl can be persisted and eventually succeed, but actually it won't.
In this PR, we will change to return until collecting the first barrier.
Besides, in frontend, when seeing a job to create exists but is creating, we will return with an extra `exists but …

fix(meta): background ddl wait collect first barrier

---

Cargo.lock

Resolves #20788
```
% cargo tree -i ring@0.16                                                  
ring v0.16.20
└── sct v0.7.0
└── rustls v0.21.11
% cargo update sct
```
<details>
</details>

chore(deps): Bump sct from 0.7.0 to 0.7.1 (ring from 0.16 to 0.17)

---

Cargo.lock

Resolves #20769
```
cargo update ring
```
<details>
</details>

chore(deps): Bump ring from 0.17.5 to 0.17.13

---

e2e_test/streaming/rate_limit/fragment.slt
proto/meta.proto
src/frontend/src/handler/alter_streaming_rate_limit.rs
src/frontend/src/handler/mod.rs
src/meta/service/src/stream_service.rs
src/meta/src/controller/catalog/get_op.rs
src/meta/src/controller/streaming_job.rs
src/meta/src/manager/metadata.rs
src/sqlparser/src/ast/ddl.rs
src/sqlparser/src/ast/mod.rs
src/sqlparser/src/parser.rs

This developer-feature is added for two reasons: first, to support altering specific backfill rate limits, currently our granularity is at the **relation level**. Sometimes we need to tune backfill rate limit for specific sources, e.g. dimension table, so this allows us to do that as a last resort option. Next, for backfill order control we will need to be able to alter fragment rate limit for specific operators. Some of the internal functionality of this PR overlaps with that. The major assumption we make is that each backfill operator **exists on its own …

feat(frontend,meta): support alter fragment rate limit

---

.github/ISSUE_TEMPLATE/flaky_test.yml

...so that we can open an issue to track them more easily.
Preview: https://github.com/risingwavelabs/risingwave/blob/bz/flaky-test-issue-template/.github/ISSUE_TEMPLATE/flaky_test.yml
<details>
</details>

chore:  add issue template for tracking flaky tests

---

Cargo.lock

Resolves #19726
<details>
</details>

chore(deps): Bump ginepro from 0.8.1 to 0.8.2 (avoid idna@0.4 and trust-dns-resolver@0.23)

---

.github/workflows/doc.yml
ci/scripts/release.sh
docker/Dockerfile.hdfs

After rustup v1.28.1, we no longer need any workaround. Fix https://github.com/risingwavelabs/risingwave/pull/20728#issuecomment-2710035659
<details>
</details>

chore(ci): revert changes specific to rustup v1.28

---

ci/docker-compose.yml
docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-hdfs.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml
risedev.yml
src/ctl/src/cmd_impl/meta/migration.rs

Related #19265 .
<details>
</details>

fix: fix fragment ids and incoming sinks in table catalog during migration

---

ci/docker-compose.yml
docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-hdfs.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml
risedev.yml
src/ctl/src/cmd_impl/meta/migration.rs

fix: fix fragment ids and incoming sinks in table catalog during migration (#20733)

---

Cargo.lock
src/risedevtool/Cargo.toml
src/risedevtool/src/bin/risedev-dev.rs
src/risedevtool/src/service_config.rs

before
thread 'main' panicked at src/risedevtool/src/bin/risedev-dev.rs:399:63:
Failed to join thread, likely panicked: Any { .. }
Error while executing command, exit code: 101
after
ERROR - Failed to start: failed to join thread, likely panicked: more than one or no pg store config found for metastore: ExactlyOneError { inner: Filter { iter: Iter([]) } }
<details>
</details>

fix(risedev): fix task panic error msg

---

Cargo.lock

Resolves #19683
<details>
</details>

chore(deps): Bump hashbrown from 0.15.0 to 0.15.1

---

Cargo.lock
src/utils/runtime/Cargo.toml

will run bench: 
align to [nightly-20250309](https://github.com/orgs/risingwavelabs/packages/container/risingwave/370466180?tag=nightly-20250309) with commit 87c7975a7f3d366eb950b220beb5fc551cefb28f
<details>
</details>

chore(deps): Bump tokio to v1.44.0

---

proto/hummock.proto
src/meta/src/hummock/manager/compaction/compaction_group_schedule.rs
src/meta/src/hummock/manager/compaction/mod.rs
src/storage/hummock_sdk/src/compact_task.rs
src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
src/storage/hummock_sdk/src/level.rs
src/storage/hummock_sdk/src/version.rs

part of #20640
This PR addresses the CPU overhead introduced by `check_sst_ids_exist`. 
`check_sst_ids_exist` was introduced to identify stale compaction tasks that originates from a compaction group that subsequently split. This PR introduces a `compaction_group_version_id` field for each compaction group, which increments with each split.  This field is then used to identify stale compaction tasks.
<details>
</details>

refactor(compaction): optimize stale compaction task validation

---

proto/stream_service.proto
proto/task_service.proto
src/compute/src/rpc/service/exchange_service.rs
src/meta/src/barrier/rpc.rs
src/meta/src/barrier/worker.rs
src/rpc_client/src/compute_client.rs
src/stream/src/executor/exchange/input.rs
src/stream/src/executor/merge.rs
src/stream/src/task/barrier_manager.rs
src/stream/src/task/barrier_manager/managed_state.rs
src/stream/src/task/mod.rs
src/stream/src/task/stream_manager.rs

Resolve https://github.com/risingwavelabs/risingwave/issues/20544
Stale exchange request sent in previous round of failed recovery may take the receivers of the current recovery, which causes the current recovery failed with new stale request and affect the next round of recovery, and then recovery may never succeed or take a long time.
In this PR, we generate a new uuid term_id in each round of recovery. When seeing exchange request with unmatched term_id, we will deny the request, so that we won't be affected by stale exchange requests.
Note that, changes …

fix(meta): avoid handling stale exchange request with term_id

---

e2e_test/source_inline/kafka/alter/alter_parallelism.slt
src/stream/src/executor/source/reader_stream.rs

fix #20849
<details>
</details>

test: add retry to a flaky source test

---

proto/stream_service.proto
proto/task_service.proto
src/compute/src/rpc/service/exchange_service.rs
src/meta/src/barrier/mod.rs
src/meta/src/barrier/recovery.rs
src/meta/src/barrier/rpc.rs
src/rpc_client/src/compute_client.rs
src/rpc_client/src/stream_client.rs
src/stream/src/executor/exchange/input.rs
src/stream/src/executor/merge.rs
src/stream/src/task/barrier_manager.rs
src/stream/src/task/mod.rs
src/stream/src/task/stream_manager.rs

Currently, after recovery, we may still receive stale exchange request sent before the recovery, and then incorrectly take the new exchange channels. In this PR, we change to include a term_id in the exchange request. Every round of recovery will have a new term_id, and when we receive exchange request from an unmatched term_id, we will reject the request.
Same as cherry-picking https://github.com/risingwavelabs/risingwave/pull/20879..
<details>
</details>

fix(meta): avoid handling stale exchange request (for release-2.1)

---

src/meta/src/backup_restore/restore.rs
src/meta/src/backup_restore/restore_impl/mod.rs
src/meta/src/backup_restore/restore_impl/v2.rs
src/storage/backup/integration_tests/common.sh
src/storage/backup/integration_tests/run_all.sh
src/storage/backup/integration_tests/test_overwrite_endpoint.sh

This PR simplifies the process of restoring to an object store that differs from the original cluster. Please refer to the comments for detailed information on the new arguments of the restore command.
[slack channel](https://risingwave-labs.slack.com/archives/C08DUHLH91A/p1739960012936649?thread_ts=1739953867.700609&cid=C08DUHLH91A)
<details>
</details>

feat(ctl): enable overwriting of system parameters during metadata restoration.

---

src/common/src/types/mod.rs

...so that we can avoid writing "accept-all" (`_`) pattern in the `match` expression and make it more robust.
<details>
</details>

refactor(types):  add convenient macros for simple & composite data types

---

docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

chore: update docker version to v2.2.3

---

.github/workflows/cherry-pick-since-release-branch.yml

fix(action): fetch all branches not only main

---

.github/workflows/update-pr-template-by-version.yml

fix(action): don't override the update branch when it exists remotely

---

proto/hummock.proto
src/meta/src/hummock/manager/compaction/compaction_group_schedule.rs
src/meta/src/hummock/manager/compaction/mod.rs
src/storage/hummock_sdk/src/compact_task.rs
src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
src/storage/hummock_sdk/src/level.rs
src/storage/hummock_sdk/src/version.rs

(cherry picked from commit 3ed4264e650fe7e92180c1fb684b105bead27c02)
cherry-pick
close #20883
<details>
</details>

refactor(compaction): optimize stale compaction task validation (#20863)

---

src/common/src/array/struct_array.rs
src/common/src/row/mod.rs

As title, in favor of future work.
<details>
</details>

feat(types): implement `Row` for `StructRef`

---

src/stream/src/common/table/state_table.rs
src/stream/src/executor/dynamic_filter.rs
src/stream/src/executor/now.rs

reuse code for dynamic filter / now, and planned to be used for iceberg list exec
<details>
</details>

refactor(state table): add an API for 1 row table

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.2.4
<details>
</details>

chore: update version v2.2.4

---

src/common/src/types/mod.rs
src/common/src/types/struct_type.rs

Add some auxiliary methods after introducing `field_ids` in #20620, which will be used in following PRs.
<details>
</details>

feat: add auxiliary methods for struct type with field ids

---

src/storage/src/hummock/compactor/shared_buffer_compact.rs

As titled
<details>
</details>

feat(storage): separate shared buffer compact SSTs of state table with and without old values

---

src/storage/src/hummock/compactor/shared_buffer_compact.rs

Resolve https://github.com/risingwavelabs/risingwave/issues/20943
<details>
</details>

feat(storage): cherry-pick to release-2.2 separate shared buffer compact SSTs of state table with and without old values (#20939)

---

e2e_test/ddl/alter_table_column_type.slt
e2e_test/source_inline/kafka/avro/alter_table.slt
e2e_test/source_legacy/cdc_inline/alter/cdc_table_alter.slt
src/meta/src/rpc/ddl_controller.rs

Since #20604, we've actually supported altering column types in a table. This PR adds some e2e tests to demonstrate this, along with the behavior limitations mentioned in #20706.
<details>
</details>

test: add e2e tests for `ALTER COLUMN TYPE`

---

src/storage/hummock_sdk/src/frontend_version.rs

We need to have values in the change log to distinguish between an empty epoch and an epoch with data.
<details>
</details>

fix(subscription):fix loss of subscription data due to reboot

---

.github/workflows/cherry-pick-since-release-branch.yml
.github/workflows/cherry-pick-to-release-branch.yml

Follow-up fix of #20557 #20745 #20842 #20912. Hope it works this time.
Refer to inline comments for fix details.
<details>
</details>

fix(action): cherry-pick-since GITHUB_OUTPUT as single line

---

src/storage/hummock_sdk/src/frontend_version.rs

fix(subscription):fix loss of subscription data due to reboot (#20959)  to 2.1

---

src/batch/src/execution/local_exchange.rs
src/common/src/config.rs
src/compute/src/server.rs
src/config/example.toml
src/ctl/src/cmd_impl/compute.rs
src/ctl/src/cmd_impl/hummock/resize_cache.rs
src/frontend/src/session.rs
src/meta/node/src/lib.rs
src/meta/node/src/server.rs
src/meta/src/manager/env.rs
src/rpc_client/src/compute_client.rs
src/rpc_client/src/frontend_client.rs
src/rpc_client/src/lib.rs
src/rpc_client/src/stream_client.rs

As titled.
Currently only `connect_timeout_secs` is included. Add more later on demand.
<details>
</details>

refactor(config): make rpc client option configurable

---

src/meta/model/migration/src/lib.rs
src/meta/model/migration/src/m20230908_072257_init.rs
src/meta/model/migration/src/m20250319_062702_mysql_utf8mb4.rs

We should use `utf8mb4` charset for storing unicode emojis. Fix the main-cron.
<details>
</details>

fix(meta): change mysql charset to utf8mb4

---

e2e_test/ddl/not_null.slt
src/frontend/src/handler/alter_table_column.rs
src/frontend/src/handler/create_sink.rs
src/frontend/src/handler/create_source.rs
src/frontend/src/handler/create_table.rs

https://github.com/risingwavelabs/risingwave/issues/19373
Notice when 
1. creating table with connector and the schema contains NOT NULL
2. create sink into a table with NOT NULL. 
Alter table add column with NOT NULL contraint must have default value.
<details>
</details>

feat(stream): notice for NOT NULL when create table with connector

---

src/batch/src/execution/local_exchange.rs
src/common/src/config.rs
src/compute/src/server.rs
src/config/example.toml
src/ctl/src/cmd_impl/compute.rs
src/frontend/src/session.rs
src/meta/node/src/lib.rs
src/meta/node/src/server.rs
src/meta/src/manager/env.rs
src/rpc_client/src/compute_client.rs
src/rpc_client/src/frontend_client.rs
src/rpc_client/src/lib.rs
src/rpc_client/src/stream_client.rs

(cherry picked from commit 42e1fd81bcb6525a53ed9a98509169b0c9cdf6cc)
cherry-pick.
close #21000
<details>
</details>

refactor(config): make rpc client option configurable (#20993)

---

proto/ddl_service.proto
src/frontend/src/catalog/system_catalog/rw_catalog/rw_ddl_progress.rs
src/frontend/src/meta_client.rs
src/frontend/src/test_utils.rs
src/meta/service/src/ddl_service.rs
src/meta/src/controller/catalog/get_op.rs
src/meta/src/manager/metadata.rs
src/rpc_client/src/meta_client.rs
src/storage/src/compaction_catalog_manager.rs

This PR addresses one corner case that may have lead to #20953.
The issue occurs when catalog client retrieves catalog from meta node, while the result doesn't include the table that is being dropped, as explained [here](https://github.com/risingwavelabs/risingwave/issues/20953#issuecomment-2736262262).
resolve #20953
<details>
</details>

fix: fix catalog inconsistency when dropping stream jobs.

---

ci/scripts/single-node-utils.sh
ci/scripts/standalone-utils.sh
e2e_test/udf/alter_function.slt
src/config/ci-single-node-standalone.toml

fix(udf, 2.2): fix udf test for single-node and standalone binary test

---

Makefile.toml

... as a workaround for recent main-cron [failures](https://buildkite.com/risingwavelabs/main-cron/builds/4584#0195af22-9aff-4394-8763-a81fea84ef26), because of #20852.
See https://github.com/risingwavelabs/risingwave/issues/20994 for further plan.
<details>
</details>

chore(ci):  relax log size check to 8MB

---

ci/scripts/single-node-utils.sh
ci/scripts/standalone-utils.sh
e2e_test/udf/alter_function.slt
src/config/ci-single-node-standalone.toml

fix(udf, 2.1): fix udf test for single-node and standalone binary test

---

java/connector-node/risingwave-sink-iceberg/src/main/java/com/risingwave/connector/catalog/JniCatalogWrapper.java
src/connector/src/connector_common/connection.rs
src/connector/src/connector_common/iceberg/mod.rs
src/connector/src/sink/iceberg/mod.rs
src/connector/with_options_sink.yaml
src/connector/with_options_source.yaml
src/frontend/src/handler/drop_table.rs

- Recently, Amazon S3 Tables offered table management APIs that are compatible with the Apache Iceberg REST Catalog standard, enabling any Iceberg-compatible application to easily create, update, list, and delete tables in an S3 table bucket.
- This PR supports AWS S3 Tables integration, so that we can use iceberg sink, source and iceberg engine with S3 Tables! Especially S3 Tables support automatic iceberg compaction. It is a good complement to our first version of iceberg engine.
- For more details on how to connect the rest catalog provided by S3 tables, …

feat(iceberg): iceberg integration with s3 tables

---

proto/stream_plan.proto
src/common/src/array/stream_chunk_iter.rs
src/prost/build.rs
src/stream/src/executor/project/materialized_exprs.rs
src/stream/src/executor/project/mod.rs
src/stream/src/executor/project/project_scalar.rs
src/stream/src/executor/project/project_set.rs
src/stream/src/from_proto/materialized_exprs.rs
src/stream/src/from_proto/mod.rs
src/stream/tests/integration_tests/main.rs
src/stream/tests/integration_tests/materialized_exprs.rs

This executor is basically the `MaterializedProject` mentioned in https://github.com/risingwavelabs/risingwave/issues/12201#issuecomment-2419013218. By materializing the evaluation results of expressions (including UDFs), we can 1) avoid non-determinism of UDF calls, 2) avoid repeat calculation for time-consuming calls.
Unlike `Project` which use `InputRef` to pass through input columns, this executor works more like `OverWindow`, which appends the result columns of `exprs` at the end of input columns. This executor is designed to only handle non-pure UDF …

feat(udf): add `MaterializedExprsExecutor` implementation

---

.github/dependabot.yml

chore(deps): update groups rand, strum and opentelemetry

---

Cargo.lock
Cargo.toml

Bump opentelemetry and related crates (pre-req of #21068):
| opentelemetry | opentelemetry-otlp | opentelemetry_sdk | tracing-opentelemetry | fastrace-opentelemetry |
|---------------|--------------------|-------------------|-----------------------|------------------------|
| v0.24.0       | v0.17.0            | v0.24.1           | v0.25.0               | v0.7.2                 |
| v0.25         | v0.25              | v0.25             | v0.26.0               | v0.7.3                 |
| v0.26         | v0.26              | v0.26             | v0.27.0 …

chore(deps): Bump opentelemetry from 0.24 to 0.26

---

ci/docker-compose.yml
ci/workflows/main-cron.yml
ci/workflows/pull-request.yml

In Pull-request pipeline, it's `sink-test-env`. Changing main-cron to be the same
<details>
</details>

ci: fix iceberg test on main-cron

---

src/connector/src/source/kafka/mod.rs
src/connector/with_options_source.yaml

as suggested by customer
<details>
The parms are directly passed to sdk
* `properties.fetch.min.bytes`
* `properties.fetch.message.max.bytes`
</details>

feat: add more librdkafka options for kafka source

---

.github/workflows/doc.yml
docs/rustdoc/index.md

(The compilation failed. https://github.com/risingwavelabs/risingwave/actions/runs/14029944464/job/39275230755
And I'm not using Dash any more so don't wanna fix 🤪
<details>
</details>

doc: remove docset support

---

src/ctl/src/cmd_impl/hummock/migrate_legacy_object.rs

As titled.
<details>
</details>

fix(ctl): object store migration tool

---

.github/dependabot.yml
Cargo.lock
src/connector/src/connector_common/mqtt_common.rs
src/connector/with_options_sink.yaml
src/connector/with_options_source.yaml

Changelog: https://github.com/serde-rs/serde/releases
error seems to be catched by https://github.com/serde-rs/serde/pull/2558
<details>
</details>

chore(deps): bump serde 1.0.208 -> 219

---

Cargo.lock
Cargo.toml
src/compute/Cargo.toml
src/compute/src/rpc/service/monitor_service.rs
src/connector/src/sink/remote.rs
src/expr/core/src/expr/expr_udf.rs
src/object_store/src/object/mod.rs
src/object_store/src/object/s3.rs
src/storage/src/hummock/block_cache.rs
src/storage/src/hummock/compactor/compactor_runner.rs
src/storage/src/hummock/compactor/fast_compactor_runner.rs
src/storage/src/hummock/compactor/iterator.rs
src/storage/src/hummock/compactor/mod.rs
src/storage/src/hummock/event_handler/hummock_event_handler.rs
src/storage/src/hummock/sstable/forward_sstable_iterator.rs
src/storage/src/hummock/sstable/multi_builder.rs
src/storage/src/hummock/sstable_store.rs
src/storage/src/hummock/store/local_hummock_storage.rs
src/storage/src/monitor/monitored_store.rs
src/storage/src/table/batch_table/mod.rs
src/stream/src/executor/actor.rs
src/stream/src/executor/exchange/input.rs
src/stream/src/executor/exchange/output.rs
src/stream/src/executor/sink.rs
src/stream/src/task/barrier_manager.rs
src/stream/src/task/stream_manager.rs
src/utils/workspace-config/Cargo.toml

- `verbose_instrument_await` is removed. Attribute span with `.verbose()` instead.
- Use `span!` to build a dynamic span instead of `format!`, for better performance (inline formatting).
- Use `.long_running()` attribute to exclude a span from being marked with `!!!`, so that we can revert hacks introduced in #20891.
Also, `Tree` now implements `Serialize`, making it possible to export trees in machine-readable formats. cc @KeXiangWang 
<details>
</details>
Signed-off-by: Bugen …

refactor: bump `await-tree` to `v0.3.0-alpha.3`

---

src/meta/src/barrier/checkpoint/creating_job/mod.rs
src/meta/src/barrier/command.rs
src/meta/src/barrier/info.rs
src/meta/src/barrier/mod.rs
src/meta/src/barrier/rpc.rs
src/meta/src/controller/fragment.rs
src/meta/src/controller/streaming_job.rs
src/meta/src/controller/utils.rs
src/meta/src/stream/scale.rs

As titled. Part of original code of https://github.com/risingwavelabs/risingwave/pull/20701
<details>
</details>

feat(meta): maintain actor vnode distribution in global barrier manager

---

e2e_test/sink/elasticsearch/elasticsearch_sink.slt
proto/catalog.proto
src/connector/src/connector_common/connection.rs
src/connector/src/connector_common/mod.rs
src/connector/src/macros.rs
src/connector/src/sink/elasticsearch_opensearch/elasticsearch_opensearch_config.rs
src/frontend/src/handler/create_connection.rs
src/frontend/src/handler/create_sink.rs
src/frontend/src/handler/create_source.rs
src/frontend/src/handler/create_source/external_schema.rs
src/frontend/src/handler/create_source/validate.rs
src/frontend/src/handler/util.rs

as title
<details>
support CONNECTION support for elastic search and open search, now for sink only
both of them only allow 3 fields: `{"username", "url", "password"}`
example 
```
create connection es_conn with (
type = 'elasticsearch',
url = 'http://elasticsearch:9200',
username = 'elastic',
password = 'risingwave',
);
```
</details>

feat: elastic-search/open-search connection support

---

src/stream/src/task/barrier_manager/managed_state.rs

Resolve https://github.com/risingwavelabs/risingwave/issues/21084
Previously we call `abort_actor` to abort the join handle of all actors immediately, even possibly before the failed actor send the error to error channel.
In this PR, we will not pre-`abort_actor` on actor failure, and instead abort the actor when receiving the reset request from global barrier manager and after collecting all actor failure.
<details>
</details>

fix(streaming): abort actors after collecting actor failure

---

Cargo.lock
src/batch/Cargo.toml
src/batch/src/task/task_execution.rs
src/expr/core/src/error.rs

Previous:
```
Caused by:
execution panic
```
Now:
```
Caused by:
execution panic: called `Result::unwrap()` on an `Err` value: Unsupported function: cast(timestamp with time zone) -> timestamp without time zone
HINT: Supported functions:
cast(character varying) -> jsonb
```
<details>
</details>

feat(batch): show panic message when "execution panic"

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.3.0-rc.1
<details>
</details>

chore: update version v2.3.0-rc.1

---

Cargo.lock
Cargo.toml

Mitigate low-priority errors. Refine foyer error handling.
Close #21116
<details>
</details>

refactor(foyer): bump foyer v0.15.2 to refine error handling

---

.github/workflows/update-pr-template-by-version.yml

https://github.com/risingwavelabs/risingwave/actions/runs/14076752557/job/39421011581
```
Pull request branch to create or update set to 'update-pr-template-2.3`'
...
/usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --force --depth=10 origin update-pr-template-2.3`:refs/remotes/origin/update-pr-template-2.3`
fatal: couldn't find remote ref update-pr-template-2.3`
Pull request branch 'update-pr-template-2.3`' does not exist yet.
```
<details>
</details>

fix(action):   branch name typo in update-pr-template-by-version

---

Cargo.lock
Cargo.toml
src/connector/src/sink/iceberg/mod.rs

- As title
<details>
</details>

feat(iceberg): bump iceberg-rs to 20250325 rebase branch

---

Makefile.toml

It's possible to encounter `dyld` path not loaded in nextest, when running via `cargo test`.
```
--- stdout:
--- stderr:
dyld[14913]: Library not loaded: @rpath/libstd-b75b50bea461c570.dylib
...
```
Bumping the dependency resolves this bug. See: https://github.com/nextest-rs/nextest/issues/267#issuecomment-2128030529
<details>
</details>

chore(deps): bump nextest min version to 0.9.72

---

Cargo.lock
Cargo.toml
src/batch/src/executor/insert.rs
src/storage/Cargo.toml
src/storage/benches/bench_block_cache.rs
src/storage/benches/bench_compactor.rs
src/storage/hummock_test/benches/bench_hummock_iter.rs
src/storage/hummock_test/src/compactor_tests.rs
src/storage/hummock_test/src/failpoint_tests.rs
src/storage/hummock_test/src/hummock_storage_tests.rs
src/storage/hummock_test/src/snapshot_tests.rs
src/storage/hummock_test/src/state_store_tests.rs
src/storage/hummock_test/src/sync_point_tests.rs
src/storage/hummock_trace/src/opts.rs
src/storage/src/hummock/compactor/shared_buffer_compact.rs
src/storage/src/hummock/sstable/backward_sstable_iterator.rs
src/storage/src/hummock/sstable/forward_sstable_iterator.rs
src/storage/src/hummock/sstable/writer.rs
src/storage/src/hummock/sstable/xor_filter.rs
src/storage/src/hummock/sstable_store.rs
src/storage/src/hummock/test_utils.rs
src/storage/src/hummock/utils.rs
src/storage/src/store_impl.rs
src/storage/src/table/batch_table/storage_table.rs
src/stream/src/common/log_store_impl/kv_log_store/reader.rs
src/stream/src/common/table/state_table.rs
src/tests/compaction_test/src/compaction_test_runner.rs

feat: bump foyer with fast recovery

---

src/frontend/src/handler/create_table.rs

As title.
<details>
</details>

feat(iceberg): enable exactly once semantics for iceberg table engine

---

ci/scripts/common.sh
ci/scripts/deterministic-it-test.sh
ci/workflows/main-cron.yml
ci/workflows/pull-request.yml
src/tests/simulation/tests/integration_tests/scale/isolation.rs

See more details in the previous PR (#20727).
This PR tried to parallelize integration test (deterministic simulation) on PR workflow, which is the new bottleneck. Unfortunately, a single case is acting as a bottleneck, preventing any improvement (see https://github.com/risingwavelabs/risingwave/pull/20802#issuecomment-2712841872).
Instead, this PR will now parallelize integration test (deterministic simulation, `scale::`). It used to take over 90 minutes to complete, making it prone to being interrupted.
<details> …

ci: parallelize integration test (deterministic simulation)

---

LICENSE

fix: copyright in license

---

LICENSE

Reverts risingwavelabs/risingwave#21158

revert: "fix: copyright in license"

---

.github/workflows/doc.yml

test in https://github.com/risingwavelabs/risingwave/actions/runs/14123984396
<details>
</details>

ci: fix doc CI

---

Cargo.lock
Cargo.toml

Pre-req of #21159. The bson crate is actually our fork so requires manual rebase.
<details>
</details>

chore(deps): Bump bson from 2.11.0 to 2.14.0

---

src/bench/sink_bench/main.rs
src/connector/src/sink/big_query.rs
src/connector/src/sink/decouple_checkpoint_log_sink.rs
src/connector/src/sink/file_sink/batching_log_sink.rs
src/connector/src/sink/log_store.rs
src/connector/src/sink/postgres.rs
src/connector/src/sink/remote.rs
src/connector/src/sink/trivial.rs
src/connector/src/sink/writer.rs
src/stream/src/common/log_store_impl/in_mem.rs
src/stream/src/common/log_store_impl/kv_log_store/mod.rs
src/stream/src/common/log_store_impl/kv_log_store/reader.rs
src/stream/src/common/log_store_impl/kv_log_store/test_utils.rs
src/stream/src/common/log_store_impl/kv_log_store/writer.rs
src/stream/src/executor/sink.rs

Previously we have separate `LogStoreReadItem` for `Barrier` and `UpdateVnodeBitmap`. However, `UpdateVnodeBitmap` always happens along with `Barrier`. Therefore, in this PR we will refactor to merge the `UpdateVnodeBitmap` into `Barrier`.
<details>
</details>

refactor(sink): merge log store barrier and update_vnode_bitmap item

---

Cargo.lock
Cargo.toml

Fix foyer panics, cherry pick #21145
<details>
</details>

fix: fix foyer panics, cherry pick #21145

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed-etcd.yml
docker/docker-compose-distributed.yml
docker/docker-compose-etcd.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.1.5
<details>
</details>

chore: update version to v2.1.5

---

ci/docker-compose.yml

avoid https://github.com/aws/aws-lc-rs/issues/755
https://buildkite.com/risingwavelabs/main-cron/builds/4718#0195eb6c-40e0-46eb-8b25-5220c908132f
<details>
</details>

chore: use cmake 3.31 to avoid aws-lc-rs compiling issue

---

src/connector/src/connector_common/common.rs
src/connector/with_options_sink.yaml
src/connector/with_options_source.yaml

as title
<details>
inherit props `socket.keepalive.enable` to `properties.socket.keepalive.enable` in risingwave
valid for both kafka source and sink, default to `true`
</details>

feat: set rdkafka `socket.keepalive.enable` default to `true`

---

src/license/src/feature.rs
src/storage/src/hummock/event_handler/refiller.rs
src/storage/src/store_impl.rs

Mark disk cache and data cache refill as premium feature, Elastic DIsk Cache, and check license.
cc @cyliu0 @BugenZhao to raise awareness about adjusting the test pipeline for license check. 
<details>
</details>

refactor(license): check license for disk cache and data refill

---

.github/labeler.yml

e.g., #21134 doesn't run tests and caused CI failure later.
<details>
</details>

ci: run iceberg tests if title contains iceberg

---

src/frontend/src/handler/create_table.rs

As title.
<details>
</details>

chore: disable exactly once for iceberg table engine

---

.github/labeler.yml

ci: fix iceberg labeller #21199

---

src/bench/sink_bench/main.rs
src/connector/src/sink/clickhouse.rs
src/connector/src/sink/coordinate.rs
src/connector/src/sink/decouple_checkpoint_log_sink.rs
src/connector/src/sink/deltalake.rs
src/connector/src/sink/doris.rs
src/connector/src/sink/iceberg/mod.rs
src/connector/src/sink/log_store.rs
src/connector/src/sink/mock_coordination_client.rs
src/connector/src/sink/remote.rs
src/connector/src/sink/sqlserver.rs
src/connector/src/sink/starrocks.rs
src/connector/src/sink/test_sink.rs
src/connector/src/sink/writer.rs
src/rpc_client/src/sink_coordinate_client.rs
src/stream/src/common/log_store_impl/in_mem.rs
src/stream/src/common/log_store_impl/kv_log_store/mod.rs
src/stream/src/common/log_store_impl/kv_log_store/reader.rs
src/stream/src/common/log_store_impl/kv_log_store/test_utils.rs
src/stream/src/common/log_store_impl/kv_log_store/writer.rs
src/stream/src/executor/sink.rs

Implement a new `LogSinker` dedicated for coordinated sinks. Remove method `update_vnode_bitmap` and `rewind_start_offset` from the `SinkWriter` trait, since they were only used by coordinated sinks.
<details>
</details>

refactor(sink): dedicated log sink for coordinator sink

---

src/meta/model_v2/migration/src/m20230908_072257_init.rs

fix: alter body column type in function table

---

ci/scripts/release.sh

Close https://github.com/risingwavelabs/risingwave/issues/21209
Additionally added `--clobber` for `gh release upload`. It will allow us to rerun the release pipeline once we hit issues like this again.
```
--clobber   Overwrite existing assets of the same name
```
<details>
</details>

chore: fix release upload connector repeatedly

---

ci/docker-compose.yml

Fix https://github.com/risingwavelabs/risingwave/issues/21221
<details>
</details>

chore: use cmake 3.31 to avoid cmake 4.0.0 compiling issue (#21180)

---

src/frontend/src/handler/explain_analyze_stream_job.rs

Minor fix for metric keys. In https://github.com/risingwavelabs/risingwave/pull/21166 we changed from operator level metrics to executor level metrics collection. We need to change corresponding parts of the code as well.
Tested locally (before this PR it shows 0 in all metrics):
```
dev=> explain analyze materialized view m1;
identity              |  actor_ids  | output_rows_per_second | downstream_backpressure_ratio
------------------------------------+-------------+------------------------+------------------------------- …
```

fix(frontend): fix metric keys for explain analyze

---

src/connector/src/with_options.rs
src/meta/src/stream/source_manager/worker.rs

feat: Add configurable sync call timeout for sources (#20828)

---

ci/docker-compose.yml
ci/scripts/release.sh

cherry-pick https://github.com/risingwavelabs/risingwave/pull/21217 and https://github.com/risingwavelabs/risingwave/pull/21222
<details>
</details>

chore: cherry-pick release fixes

---

proto/monitor_service.proto
src/common/metrics/src/lib.rs
src/compute/src/rpc/service/monitor_service.rs
src/frontend/src/handler/explain_analyze_stream_job.rs

Before this PR, there's no metrics for dispatcher. After this PR we populate the dispatcher metrics as well.
```
identity              |  actor_ids  | output_rows_per_second | downstream_backpressure_ratio
------------------------------------+-------------+------------------------+-------------------------------
StreamMaterialize                  | 20,19,18,17 | 21500                  | 0
└─ MergeExecutor                   | 20,19,18,17 | 21500                  | 0.255425
└─ Dispatcher                   |             | 21500 …
```

feat(frontend): support dispatcher metrics for explain analyze

---

src/common/src/hash/consistent_hash/vnode.rs
src/common/src/hash/table_distribution.rs
src/stream/src/common/log_store_impl/kv_log_store/buffer.rs
src/stream/src/common/log_store_impl/kv_log_store/mod.rs
src/stream/src/common/log_store_impl/kv_log_store/reader.rs
src/stream/src/common/log_store_impl/kv_log_store/serde.rs
src/stream/src/common/log_store_impl/kv_log_store/state.rs
src/stream/src/common/log_store_impl/kv_log_store/writer.rs
src/stream/src/executor/sync_kv_log_store.rs

Also do some refactoring to improve readability of the code.
This is in preparation for vnode level stream for sync log store.
<details>
</details>

refactor(stream): add seq_id to logstore stream

---

src/stream/src/common/log_store_impl/kv_log_store/reader.rs
src/stream/src/common/log_store_impl/kv_log_store/serde.rs

refactor(stream): add vnode to logstore stream

---

e2e_test/udf/tests/bug_fixes/18202_sql_udf_aggregate_prefix.slt
e2e_test/udf/tests/scalar/javascript.slt
e2e_test/udf/tests/scalar/test_explain.slt.part
src/common/src/util/stream_graph_visitor.rs
src/frontend/src/expr/mod.rs
src/frontend/src/optimizer/plan_node/logical_project.rs
src/frontend/src/optimizer/plan_node/mod.rs
src/frontend/src/optimizer/plan_node/stream_materialized_exprs.rs
src/frontend/src/utils/column_index_mapping.rs

> AI disclaimer: 90% of lines of Rust code are written by Cursor `claude-3.7-sonnet`, under the guidance and review of me.
This PR creates `StreamMaterializedExprs` for expressions containing UDF calls in `LogicalProject::to_stream`, so that results of indeterministic UDF calls can be materialized 
and retrieved later when updating or deleting the row.
Resolves #12201.
Future work:
1. UDF calls in filter conditions (`WHERE` and `ON`).
2. UDTF calls in `LogicalProjectSet`.
3. Other indeterministic functions like `rand()`.
<details> …

feat(udf): use `StreamMaterializedExprs` for scalar UDF calls

---

e2e_test/source_legacy/basic/kafka.slt

Introduced in #20100 . 
Found in main-cron: https://buildkite.com/risingwavelabs/main-cron/builds/4755#01960bd4-c4de-4831-be47-5cad8cdd3660
<details>
</details>

fix: fix slt of kafka source mongo strong schema

---

src/sqlparser/src/ast/statement.rs

fix https://github.com/risingwavelabs/risingwave/issues/21259
<details>
</details>

fix: `SHOW CREATE SINK` missing column spec

---

integration_tests/datagen/go.mod
integration_tests/datagen/go.sum

https://buildkite.com/risingwavelabs/integration-tests
Also changed the buildkite setting to let the integration tests run on label.
<details>
</details>

test: fix integration test go.mod

---

.github/workflows/cherry-pick-since-release-branch.yml

GitHub always uses the workflow specification from the triggering branch. For some old PRs, we didn't have `cherry-pick-since` support at that time.
This PR enables developers to trigger this workflow (on the main branch) manually in the `Actions` page.
<details>
</details>

ci: support workflow dispatch for cherry-pick workflow

---

e2e_test/udf/tests/language_specific/remote/test.slt.part

Fix #21282
<details>
</details>

fix(ci): backoff when connecting to remote udf

---

e2e_test/sink/kafka/create_sink.slt
src/sqlparser/src/ast/statement.rs
src/sqlparser/tests/testdata/create.yaml

fix: missing KEY ENCODE when display `FormatEncodeOptions`

---

src/object_store/src/object/opendal_engine/opendal_s3.rs

As title, snowflake sink is using file sink method now.
<details>
</details>

chore: remove dead code for origin snowflake sink

---

.github/workflows/cherry-pick-since-release-branch.yml

chore(ci): add actions write permission to cherry-pick-since-release

---

ci/scripts/release.sh

Although we disallow python udf by default in frontend, we should compile python udf support into the released binary.
<details>
</details>

fix(release): enable python udf compilation in release binary

---

.github/workflows/run-main-cron.yml

cherry-pick ci: label ci/main-cron/run-all for cherry-pick PRs (#21306)

---

src/common/src/catalog/mod.rs
src/stream/src/executor/mview/materialize.rs

`MaterializeCache::handle` is not quite clean to read before. This PR refactor it to improve readability, avoiding potential bugs.
<details>
</details>

refactor(mview): simplify `Materialize` conflict handling

---

ci/scripts/deterministic-recovery-test.sh

chore(ci): remove unused logs for ci recovery test

---

ci/workflows/main-cron.yml

chore: increase opendal test timeout

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.2.5
<details>
</details>

chore: update version to v2.2.5

---

e2e_test/ddl/alter_resource_group.slt
e2e_test/ddl/database.slt
src/frontend/src/handler/alter_resource_group.rs
src/frontend/src/handler/create_database.rs
src/frontend/src/handler/create_mv.rs
src/license/src/feature.rs

close #21321
<details>
</details>

feat: add premium license check for resource group (#21298)

---

src/license/src/feature.rs
src/storage/src/hummock/event_handler/refiller.rs
src/storage/src/store_impl.rs

cherry-pick: check license for disk cache & data refill #21176

---

src/stream/src/executor/aggregate/distinct.rs

In previous implementation, old distinct keys are not removed from dedup table when the counts drop to 0. This PR adds check after mutating the counts.
<details>
</details>

fix(distinct agg): delete row from dedup table when counts drop to 0

---

ci/scripts/release.sh

Python UDF compiling requires python3.12
<details>
</details>

chore(ci): use python3.12 in release.sh to compile python udf

---

ci/scripts/release.sh

cherry-pick https://github.com/risingwavelabs/risingwave/pull/21333
Close https://github.com/risingwavelabs/risingwave/pull/21340
<details>
</details>

cherry-pick chore(ci): use python3.12 in release.sh to compile python udf (#21333)

---

src/connector/src/source/iceberg/mod.rs
src/frontend/src/optimizer/rule/batch/batch_iceberg_count_star.rs

- Fix iceberg count star. Use plan files instead of listing the files manually.
<details>
</details>

fix(iceberg): fix iceberg count star

---

java/connector-node/risingwave-sink-iceberg/pom.xml

- As title
<details>
</details>

fix(iceberg): remove parquet avro lib

---

src/storage/hummock_test/src/bin/replay/replay_impl.rs
src/storage/hummock_trace/src/collector.rs
src/storage/hummock_trace/src/record.rs
src/storage/hummock_trace/src/replay/mod.rs
src/storage/hummock_trace/src/replay/worker.rs
src/storage/src/hummock/store/local_hummock_storage.rs
src/storage/src/memory.rs
src/storage/src/monitor/monitored_store.rs
src/storage/src/monitor/traced_store.rs
src/storage/src/panic_store.rs
src/storage/src/store.rs
src/storage/src/store_impl.rs
src/stream/src/common/log_store_impl/kv_log_store/state.rs
src/stream/src/common/log_store_impl/kv_log_store/writer.rs
src/stream/src/common/table/state_table.rs

Remove the `is_dirty` method from `LocalStateStore` trait.
Previously in the `commit_pending_watermark` of `StateTable`, we may incorrectly reset the `committed_watermark` to `None` when the `local_state_store.is_dirty()` but `pending_watermark` is None. In this PR, we will not check `local_state_store..is_dirty()` and only update the `committed_watermark` when `pending_watermark` is Some.
<details>
</details>

refactor(storage): remove is_dirty method from state store and refine state table commit_pending_watermark

---

src/stream/src/executor/project/materialized_exprs.rs
src/stream/src/from_proto/materialized_exprs.rs
src/stream/tests/integration_tests/materialized_exprs.rs

> AI disclaimer: 90% of lines of Rust code are written by Cursor claude-3.7-sonnet, under the guidance and review of me.
This PR adds LRU cache for `MaterializedExprsExecutor`.
<details>
</details>

perf(udf): add LRU cache for `MaterializedExprsExecutor`

---

Cargo.lock
Cargo.toml

release v2.3.0
<details>
</details>

chore: update version to v2.3.0

---

docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

update docker image tag v2.3.0
<details>
</details>

chore: update docker image tag v2.3.0

---

src/stream/src/common/log_store_impl/kv_log_store/mod.rs
src/stream/src/common/log_store_impl/kv_log_store/reader.rs
src/stream/src/common/log_store_impl/kv_log_store/serde.rs

refactor(stream): add logstore stream with vnode progress

---

src/license/src/feature.rs
src/meta/src/barrier/worker.rs

As titled.
<details>
</details>

feat(meta): add DatabaseFailureIsolation license feature

---

src/stream/src/executor/source/fs_fetch_executor.rs

Since v2.3, the logic of determining whether a file has been read and deleted from the state table becomes to determine whether the reader's stream has ended. If it has ended, a None will be inserted. The fetch executor will delete the corresponding file after encountering None.
However, if a file is empty, it will also be None, and its file name cannot be extracted from the chunk, so an empty string will be deleted. This pr fixes this problem by initializing the delete file name when handling list stream.
<details> …

fix(source): handling the case of reading empty files

---

src/frontend/src/binder/mod.rs
src/frontend/src/binder/relation/table_or_source.rs

Fixed #21413 .
<details>
</details>

fix: ban source access in streaming for cross-db access

---

src/compute/src/server.rs

Fix compute node ignored init system params when creating ElasticDiskCache.
#21420 for main branch.
<details>
</details>

fix: fix compute node ElasticDiskCache license check

---

src/license/src/feature.rs
src/meta/src/barrier/worker.rs

resolve https://github.com/risingwavelabs/risingwave/issues/21408
<details>
</details>

feat(meta): cherry-pick release-2.3 add DatabaseFailureIsolation license feature (#21404)

---

src/common/src/lru.rs
src/stream/src/cache/managed_lru.rs
src/stream/src/executor/dedup/cache.rs
src/stream/src/executor/lookup/cache.rs
src/stream/src/executor/top_n/group_top_n.rs
src/stream/src/executor/top_n/group_top_n_appendonly.rs

Our LRU cache doesn't have `remove` method before, and that caused some problem because developer may forget to remove entries from it when deleting a corresponding row from state table.
<details>
</details>

feat(lru): add `remove` method to LruCache and ManagedLruCache

---

src/stream/src/executor/aggregate/distinct.rs

After https://github.com/risingwavelabs/risingwave/commit/a190d37e1a017f8914268c848e5dd675764bd29c, the distinct agg deduplicator has a bug that can cause cache-table inconsistency, and the bug was triggered in backwards-compat-tests. This PR fixes it with the new `remove` method added in #21429.
Fixes #21395.
<details>
</details>

fix(distinct agg): remove from cache when removing from table

---

src/common/src/array/list_array.rs

The field is only written but never read. The method `ListArrayBuilder::len()` is backed by `self.bitmap.len()`. There is no need to maintain a separate field.
<details>
</details>

refactor(common): remove unused private field `ListArrayBuilder::len`

---

java/connector-node/risingwave-sink-iceberg/pom.xml

- Remove `iceberg-parquet` from the java dependence.
<details>
</details>

fix(iceberg): remove iceberg parquet lib

---

ci/workflows/main-cron.yml
ci/workflows/pull-request.yml

No need to have a separate label for parallel tests. 
Especially we want to achieve  #18992
<details>
</details>

ci: merge label `run-e2e-parallel-tests` into `run-e2e-tests`

---

e2e_test/iceberg/test_case/pure_slt/iceberg_engine.slt
proto/meta.proto
src/frontend/src/catalog/system_catalog/rw_catalog/iceberg_namespace_properties.rs
src/frontend/src/catalog/system_catalog/rw_catalog/iceberg_tables.rs
src/frontend/src/catalog/system_catalog/rw_catalog/mod.rs
src/frontend/src/meta_client.rs
src/frontend/src/test_utils.rs
src/meta/node/src/server.rs
src/meta/service/src/hosted_iceberg_catalog_service_impl.rs
src/meta/service/src/lib.rs
src/rpc_client/src/meta_client.rs

- https://github.com/risingwavelabs/risingwave/issues/19418
- Support `rw_catalog.iceberg_tables` and `rw_catalog.iceberg_namespace_properties` catalog views. `rw_catalog.iceberg_tables` will redirect the query to the meta store table `iceberg_tables` and it will check the user privilege to determine whether to show iceberg table records.
- Users can use other query engines they like to connect to the RisingWave SQL catalog.
<details>
- Support `iceberg_tables` and `iceberg_namespace_properties` system view. The goal is …

feat(iceberg): support iceberg jdbc catalog views

---

Makefile.toml
src/risedevtool/src/task.rs
src/risedevtool/src/task/configure_tmux_service.rs

close #21415
<details>
</details>

feat(risedev): support restart a node 

---

risedev.yml

After we updated minio, seems like there's some test regression. Loosening the minio rate limits test.
<details>
</details>

chore(ci): relax minio rate limits

---

ci/scripts/e2e-sqlserver-sink-test.sh
e2e_test/sink/sqlserver_sink.slt
src/connector/src/sink/sqlserver.rs
src/connector/with_options_sink.yaml

Previously SQL server sink doesn't support schema other than the default 'dbo'.
This PR fixes the issue.
<details>
</details>

fix(connector): support for SQL server table schema

---

src/meta/src/backup_restore/backup_manager.rs
src/meta/src/backup_restore/restore.rs
src/meta/src/hummock/manager/gc.rs
src/storage/backup/integration_tests/common.sh
src/storage/backup/integration_tests/test_basic.sh
src/storage/backup/src/lib.rs

This PR adds optional integrity validation in ctl restore command. 
It's helpful when duplicate objects between object stores, as a way to ensure all required objects have been copied. 
<details>
</details>

feat(ctl): support backup integrity validation

---

Makefile.toml
ci/Dockerfile
ci/build-ci-image.sh
ci/docker-compose.yml
risedev

`sqllogictest` will now exit gracefully upon failure, cancellation, or timeout of a CI step. This allows us to review ongoing and skipped test cases for debugging purposes.
Upstream PR: https://github.com/risinglightdb/sqllogictest-rs/pull/258
Preview (https://buildkite.com/risingwavelabs/main-cron/builds/4962):
There's a long story to correctly handle signals in CI, check it out if you are interested 😄:
https://www.notion.so/risingwave-labs/Story-on-CI-Graceful-Cancellation-1d7f0d69cb76803d900bd1512bf8b479?pvs=4 …

feat(ci): graceful exit of `sqllogictest` on failure, cancellation, or timeout

---

e2e_test/iceberg/test_case/pure_slt/iceberg_engine.slt
src/common/src/array/arrow/arrow_iceberg.rs
src/common/src/array/arrow/mod.rs
src/frontend/src/optimizer/rule/batch/batch_iceberg_predicate_pushdown.rs

- Fix https://github.com/risingwavelabs/risingwave/issues/21458
<details>
</details>

fix(iceberg): fix iceberg decimal predicate pushdown

---

risedev.yml
src/frontend/src/optimizer/plan_node/utils.rs
src/meta/src/barrier/checkpoint/control.rs
src/meta/src/barrier/checkpoint/creating_job/barrier_control.rs
src/meta/src/barrier/checkpoint/creating_job/mod.rs
src/meta/src/barrier/checkpoint/creating_job/status.rs
src/meta/src/barrier/checkpoint/mod.rs
src/meta/src/barrier/checkpoint/recovery.rs
src/meta/src/barrier/command.rs
src/meta/src/barrier/context/recovery.rs
src/meta/src/barrier/info.rs
src/meta/src/barrier/mod.rs
src/meta/src/barrier/rpc.rs
src/meta/src/barrier/worker.rs
src/meta/src/rpc/ddl_controller.rs
src/meta/src/stream/stream_graph/fragment.rs
src/prost/src/lib.rs
src/storage/hummock_sdk/src/change_log.rs
src/stream/src/executor/backfill/snapshot_backfill/state.rs

In this PR, we will support recoverable snapshot backfill in meta node. During recovery, we will recover the ongoing snapshot backfill states by resolving the lagged epochs from hummock table change log epoch.
<details>
</details>

feat(snapshot-backfill): support recoverable snapshot backfill (meta part)

---

src/common/src/hash/consistent_hash/vnode.rs
src/stream/src/common/log_store_impl/kv_log_store/mod.rs
src/stream/src/common/log_store_impl/kv_log_store/reader.rs
src/stream/src/common/log_store_impl/kv_log_store/serde.rs
src/stream/src/common/log_store_impl/kv_log_store/state.rs
src/stream/src/common/log_store_impl/kv_log_store/writer.rs
src/stream/src/executor/sync_kv_log_store.rs

feat(stream): truncate synced log store using progress map

---

src/meta/src/barrier/recovery.rs

Cherry picking https://github.com/risingwavelabs/risingwave/pull/21477 onto branch release-2.1.
<details>
</details>

fix(meta): reset connection pool in recovery

---

Cargo.lock
Cargo.toml

bump package version to 2.5.0-alpha since we have the release-2.4 branch already
<details>
</details>

chore: bump package version to 2.5.0-alpha

---

src/stream/src/executor/backfill/cdc/cdc_backfill.rs

Missing the transform_upstream will result in yielding chunk with incorrect schema and failing sanity check.
<details>
</details>

fix(cdc): transform upstream correctly

---

Cargo.lock

```
% cargo update resolv-conf hostname@0.4 iana-time-zone
Updating crates.io index
Locking 4 packages to latest compatible versions
Removing hostname v0.3.1
Removing hostname v0.4.0
Adding hostname v0.4.1
Updating iana-time-zone v0.1.57 -> v0.1.63
Removing match_cfg v0.1.0
Updating resolv-conf v0.7.0 -> v0.7.1 (available: v0.7.2)
Removing windows v0.48.0
Removing windows v0.52.0
Removing windows-core v0.52.0
Adding windows-link v0.1.1
note: pass `--verbose` to see 514 unchanged dependencies behind latest
```
<details> …

chore(deps): Bump iana-time-zone/hostname/resolv-conf patch versions to avoid too many windows src versions

---

e2e_test/iceberg/test_case/pure_slt/iceberg_engine.slt
src/frontend/src/optimizer/rule/rewrite_like_expr_rule.rs

- Fix optimizer rule for the following sql used by spark to query hosted iceberg catalog. The like function is not a binary operator which could accept 3 parameters, so we need to handle the corner case.
- `SELECT table_namespace FROM iceberg_tables WHERE catalog_name = 'dev' AND (table_namespace = 'public' OR table_namespace LIKE '*' ESCAPE '!') LIMIT 1;`
<details>
</details>

fix(optimizer): fix like rewrite rule

---

risedev.yml

https://github.com/risingwavelabs/risingwave/issues/21506
<details>
</details>

chore(ci): increase minio rate-limit-test's rate limit

---

risedev.yml

chore(ci): increase minio rate-limit-test's rate limit (#21508)

---

src/stream/src/executor/backfill/cdc/cdc_backfill.rs
src/stream/src/executor/backfill/cdc/upstream_table/external.rs

#21490 doesn't call `mapping_message` which will still lead to sanity check failure.
This PR fixes the bug.
<details>
</details>

fix(cdc): transform upstream correctly again

---

src/frontend/src/catalog/system_catalog/information_schema/key_column_usage.rs
src/frontend/src/catalog/system_catalog/pg_catalog/pg_stat_user_tables.rs

chore: fix license header

---

ci/scripts/deterministic-it-test.sh

resolve https://github.com/risingwavelabs/risingwave/issues/21505
<details>
</details>

fix(test): set max parallelism for integration test (madsim) to avoid possibly OOM

---

java/connector-node/risingwave-sink-iceberg/pom.xml

- as titled.
<details>
</details>

fix(iceberg): remove iceberg data lib

---

src/meta/src/controller/catalog/mod.rs
src/meta/src/controller/mod.rs

cherry-pick fix(meta): fix subscription notify (#21479) to 2.2

---

Makefile.toml
src/risedevtool/src/task/compactor_service.rs
src/risedevtool/src/task/compute_node_service.rs
src/risedevtool/src/task/frontend_service.rs
src/risedevtool/src/task/meta_node_service.rs
src/risedevtool/src/task/utils.rs

Developers can use `risedev-dev` to launch RisingWave component from docker image like this:
```bash
USE_SYSTEM_RISINGWAVE=docker:v2.3.0 ./risedev d xx
```
We have finally reinvented `docker-compose`! 😄
<details>
</details>

feat(risedev): support docker image for `USE_SYSTEM_RISINGWAVE`

---

src/connector/src/sink/sqlserver.rs

resolve #21550
<details>
</details>

fix(test): work around generate_with_options_yaml_inner issue

---

src/storage/hummock_test/src/failpoint_tests.rs
src/storage/hummock_test/src/snapshot_tests.rs
src/storage/hummock_test/src/sync_point_tests.rs
src/storage/src/hummock/store/local_hummock_storage.rs
src/storage/src/memory.rs
src/storage/src/monitor/monitored_store.rs
src/storage/src/monitor/traced_store.rs
src/storage/src/panic_store.rs
src/storage/src/store.rs
src/storage/src/store_impl.rs
src/stream/src/common/log_store_impl/kv_log_store/reader.rs

Extract the current `init`, `seal_current_epoch`, `try_flush` and `flush` to a common `StateStoreWriteEpochControl` trait, so that the later trait for vector writer introduced in https://github.com/risingwavelabs/risingwave/pull/21398 can reuse these common methods related epoch control of data writer.
<details>
</details>

refactor(storage): extract epoch control common methods

---

e2e_test/batch/basic/cross_db.slt.part
src/frontend/src/binder/relation/table_or_source.rs
src/frontend/src/catalog/root_catalog.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/21210?notification_referrer_id=NT_kwDOAI61WLMxNTYyMzQzMDM1NDo5MzUyNTM2&notifications_query=reason%3Aparticipating#event-17401297337
<details>
</details>

fix(binder): check database if exists for binder

---

ci/scripts/sql/nexmark/q14.sql
e2e_test/streaming/nexmark/sinks/q14.slt.part
e2e_test/streaming/nexmark/views/q14.slt.part
src/tests/simulation/Cargo.toml

So that we don't need `udf` feature to run it, getting rid of building Python/JS/Wasm runtime in normal local development.
There was a regression that by default we need to additionally build Python runtime since https://github.com/risingwavelabs/risingwave/pull/21390. This PR also fixes that by removing `udf` feature from `risingwave_simulation` crate. 
<details>
</details>

refactor: use sql udf for nexmark q14 `count_char`

---

.github/workflows/label-triggered.yml

https://github.com/risingwavelabs/risingwave/actions/workflows/label-triggered.yml
Since 4-15:
> This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
How can we improve the visibility of deprecation warning before actual removal, without causing too much noise 🤔 
<details>
</details>

fix(action): Label Commenter uses deprecated ubuntu-20.04

---

Cargo.lock
Cargo.toml

release v2.3.1
<details>
</details>

chore: update version to v2.3.1

---

src/connector/src/sink/iceberg/mod.rs

- Add a preifx `_p_` to the partition name.
- We can't use the same column as the partition by name. See https://github.com/risingwavelabs/iceberg-rust/blob/f5242cdab5d3994cf21e0aebdd43aebce327ea0b/crates/iceberg/src/spec/partition.rs#L560-L566
<details>
</details>

fix(iceberg): fix iceberg partition by name

---

docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

update docker image v2.3.1
<details>
</details>

chore: update docker image v2.3.1

---

docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

chore: update docker image v2.3.1 (#21597)

---

src/compute/src/observer/observer_manager.rs
src/compute/src/server.rs

follow up #21477
We've encountered another connectivity issue between compute nodes afer applyiing #21477.
<details>
</details>

fix: reset client pool for compute node

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.2.6
<details>
</details>

chore: update version v2.2.6

---

src/compute/src/observer/observer_manager.rs
src/compute/src/server.rs
src/meta/src/barrier/worker.rs
src/stream/src/task/stream_manager.rs

as titled.
Also notify compute node with Info::Recovery to trigger batch client invalidation.
<details>
</details>

fix(streaming): reset stream client pool in local barrier worker

---

src/connector/src/source/cdc/external/mysql.rs

Fix https://github.com/risingwavelabs/risingwave/issues/20799.
Note: we also have tried to remove the support in https://github.com/risingwavelabs/risingwave/pull/21024, but there's some problem. See discussions here: https://risingwave-labs.slack.com/archives/C064SBT0ASF/p1742465000639249?thread_ts=1741859862.262589&cid=C064SBT0ASF
<details>
</details>

fix(cdc): mysql default value conversion failure should be tolerated

---

src/tests/sqlsmith/src/sql_gen/types.rs

After #21545, we banned `approx_count_distinct` to non-append-only input, but SQLSmith cannot distinguish the append-only property for the input of agg. Let's just don't generate it.
<details>
</details>

fix(sqlsmith): ignore `ApproxCountDistinct` in sqlsmith

---

src/frontend/src/optimizer/plan_node/logical_agg.rs

1. Ban non-append-only `approx_count_distinct`.
2. Warn on the usage of append-only `approx_count_distinct`.
<details>
</details>

feat(agg): ban non-append-only `APPROX_COUNT_DISTINCT`

---

src/compute/src/observer/observer_manager.rs
src/compute/src/server.rs
src/meta/src/barrier/recovery.rs
src/stream/src/task/stream_manager.rs

resolve https://github.com/risingwavelabs/risingwave/issues/21613 and https://github.com/risingwavelabs/risingwave/issues/21604
</details>

fix: cherry-pick release-2.1: reset client pool for compute node (#21603, #21611)

---

src/compute/src/observer/observer_manager.rs
src/compute/src/server.rs
src/meta/src/barrier/worker.rs
src/stream/src/task/stream_manager.rs

resolve https://github.com/risingwavelabs/risingwave/issues/21612
<details>
</details>

fix: cherry-pick release-2.3: reset client pool for compute node (#21603, #21611)

---

src/sqlparser/src/ast/statement.rs
src/sqlparser/tests/testdata/create.yaml

in show create cdc source:
```
dev=> show create source mysql ;
Name     |                                                                       Create Sql
--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
public.mysql | CREATE SOURCE mysql WITH (connector = 'mysql-cdc', hostname = 'localhost', port = 8306, username = 'root', password = '123456', database.name = 'mydb') FORMAT PLAIN ENCODE JSON
(1 row)
```
It shows a …

fix(sqlparser): skip format_encode for CDC source

---

.github/workflows/cherry-pick-since-release-branch.yml

Sometimes there could be temporary failures:
https://github.com/risingwavelabs/risingwave/actions/runs/14727378004/job/41333223370?pr=21638
Such partial success/failure can be risky: some fixes might be silently included in an early release but omitted in a later one.
This PR adds a "report" step to notify developers if the workflow run succeeds or not.
<details>
</details>

chore(ci): report cherry-pick workflow status to PR

---

src/prost/helpers/src/lib.rs

rust-analyzer now has https://github.com/rust-lang/rust-analyzer/issues/18344. Omitting the documentation for `Pb`-prefixed type aliases makes it render the docs of the original type, which looks better.
<details>
</details>

chore(proto): do not add docs for `Pb`-prefixed type aliases

---

e2e_test/source_inline/kafka/avro/glue.slt.serial

Closes #21462. The actual cause is #20868 (even after `retry 3 backoff 5s`) but we fix the typo to avoid misleading people.
<details>
</details>

fix(test): typo in glue schema registry license test

---

ci/scripts/e2e-test-serial.sh

We've already skipped it for `single-node` mode. It seems no harm to also skip for `standalone` mode.
Actually I'm thinking of whether it's really necessary to add a step specifically for these deployment modes...
<details>
</details>

chore(ci): skip batch e2e also for standalone mode

---

e2e_test/source_inline/connection/ddl.slt
src/frontend/src/handler/create_sink.rs
src/frontend/src/handler/create_source.rs

close https://github.com/risingwavelabs/risingwave/issues/21650
The issue is spec to using with CONNECTION, as we will check the compatibility between CONNECTION type and SOURCE/SINK's connector. Not a framework level issue. 
<details>
</details>

fix: handle missing 'connector' field in WITH clause with CONNECTION

---

src/frontend/planner_test/tests/testdata/output/agg.yaml
src/frontend/planner_test/tests/testdata/output/append_only.yaml
src/frontend/planner_test/tests/testdata/output/batch_dist_agg.yaml
src/frontend/planner_test/tests/testdata/output/ch_benchmark.yaml
src/frontend/planner_test/tests/testdata/output/functional_dependency.yaml
src/frontend/planner_test/tests/testdata/output/index_selection.yaml
src/frontend/planner_test/tests/testdata/output/join.yaml
src/frontend/planner_test/tests/testdata/output/limit.yaml
src/frontend/planner_test/tests/testdata/output/nexmark.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_source.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_source_kafka.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_temporal_filter.yaml
src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml
src/frontend/planner_test/tests/testdata/output/order_by.yaml
src/frontend/planner_test/tests/testdata/output/project_set.yaml
src/frontend/planner_test/tests/testdata/output/range_scan.yaml
src/frontend/planner_test/tests/testdata/output/row_filter.yaml
src/frontend/planner_test/tests/testdata/output/singleton.yaml
src/frontend/planner_test/tests/testdata/output/stream_dist_agg.yaml
src/frontend/planner_test/tests/testdata/output/subquery.yaml
src/frontend/planner_test/tests/testdata/output/topn.yaml
src/frontend/planner_test/tests/testdata/output/tpch.yaml
src/frontend/planner_test/tests/testdata/output/tpch_kafka.yaml
src/frontend/planner_test/tests/testdata/output/tpch_variant.yaml
src/frontend/src/handler/create_mv.rs
src/frontend/src/optimizer/mod.rs
src/frontend/src/optimizer/plan_node/stream_materialize.rs
src/tests/simulation/src/nexmark.rs

This reverts commit 27efddf862d4b7969e0057301070c9d6ba3d9dad.
closes https://github.com/risingwavelabs/risingwave/issues/21668.
<details>
</details>

Revert "feat: use order key as mv's dist key (#20176)"

---

src/meta/src/barrier/context/context_impl.rs
src/tests/sqlsmith/src/sql_gen/mod.rs
src/tests/sqlsmith/src/sql_gen/relation.rs
src/tests/sqlsmith/src/sql_gen/table_functions.rs

Add support for generating `generate_series()` and `range()` table functions in Sqlsmith. 
It enables both integer and timestamp variants, where the step argument is optional for integers but required as an interval for timestamps. Timestamp expressions are constructed using a fixed base and random offsets via chrono. 
Fixes #4540 
<details>
</details>

feat(sqlsmith): support generation of generate_series and range table functions

---

ci/docker-compose.yml
e2e_test/commands/pulsar_produce.py
e2e_test/requirements.txt
e2e_test/source_inline/pulsar/basic.slt

Part of #21401. Unlike the sink counterpart #12505, this is not a new step with a new shell script, but part of the `source_inline` sets.
Next step: #21682 that substitutes URLs with risedev to provide a unified experience between CI and local dev
<details>
</details>

test(source): pulsar with docker in addition to public cloud

---

src/compute/src/observer/observer_manager.rs
src/compute/src/server.rs
src/meta/src/barrier/worker.rs
src/stream/src/task/stream_manager.rs

resolve https://github.com/risingwavelabs/risingwave/issues/21607 and https://github.com/risingwavelabs/risingwave/issues/21614
<details>
</details>

fix: cherry-pick release-2.2: reset client pool for compute node (#21603, #21611)

---

src/meta/src/barrier/worker.rs

fix(meta): cherry-pick release-2.4 try reconnect to worker node on create new streaming job (#21591)

---

e2e_test/batch/catalog/pg_settings.slt.part
e2e_test/ddl/show_purify.slt
src/common/src/session_config/mod.rs
src/frontend/src/catalog/purify.rs
src/frontend/src/session/current.rs

Cherry-pick #21656 to release-2.3. Close #21659.
<details>
</details>

feat(frontend): add a session config to allow disabling sql purification (#21656)

---

src/common/src/array/arrow/arrow_52.rs
src/common/src/array/arrow/arrow_54.rs
src/common/src/array/arrow/arrow_impl.rs
src/common/src/array/arrow/mod.rs

Introduced by #17354
<details>
</details>

refactor(arrow): cleanup stale arrow-48 compatible work

---

e2e_test/udf/tests/language_specific/javascript_async.slt

Try fix the flaky js udf call https://github.com/risingwavelabs/risingwave/issues/21719.
<details>
</details>

fix(test): add retry for js async udf call

---

ci/workflows/pull-request.yml

chore: increase check timeout

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.3.2
<details>
</details>

chore: update version to v2.3.2

---

Cargo.lock
Cargo.toml
src/common/Cargo.toml
src/common/src/array/arrow/arrow_53.rs
src/common/src/array/arrow/arrow_deltalake.rs
src/common/src/array/arrow/mod.rs

Notably:
* deltalake: 0.20.1 -> 0.24
* datafusion: 0.41 -> 0.44
* arrow: 52 -> 53
* lexical-core: 0.8.5 -> 1 [#18723](https://github.com/risingwavelabs/risingwave/issues/18723)
The deltalake/datafusion/arrow versions are still lagging behind. But bumping them requires more efforts to fix the build. So doing the simple part first.
<details>
</details>

chore(deps): Bump deltalake from 0.20.1 to 0.24 to drop some ancient transitive dependencies

---

e2e_test/batch/functions/date_bin.part
proto/expr.proto
src/expr/impl/src/scalar/date_bin.rs
src/expr/impl/src/scalar/mod.rs
src/frontend/src/binder/expr/function/builtin_scalar.rs
src/frontend/src/expr/pure.rs
src/frontend/src/optimizer/plan_expr_visitor/strong.rs

Impl https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-BIN
<details>
</details>

feat(expr): add date_bin

---

src/common/src/array/list_array.rs
src/common/src/types/mod.rs
src/common/src/util/value_encoding/column_aware_row_encoding.rs
src/expr/impl/src/scalar/array.rs
src/expr/impl/src/scalar/array_concat.rs
src/expr/impl/src/scalar/array_flatten.rs
src/expr/impl/src/scalar/cast.rs
src/expr/impl/src/scalar/jsonb_build.rs
src/expr/impl/src/scalar/to_jsonb.rs
src/expr/impl/src/table_function/pg_expandarray.rs
src/expr/macro/src/gen.rs

The inner data of the `DataType::List` variant is quite different from `MapType` in `DataType::Map` and `StructType` in `DataType::Struct`, so the name should be `as_list_element_type` instead of `as_list`. The old name is very confusing.
<details>
</details>

refactor(common): rename `DataType::as_list` to `as_list_element_type`

---

Cargo.lock
src/connector/Cargo.toml
src/risedevtool/Cargo.toml

https://github.com/yoshidan/google-cloud-rust
> Since the development of [google cloud rust by Google](https://github.com/googleapis/google-cloud-rust) seems to have resumed, We have decided to donate the `google-cloud-*` namespace to Google.
> #### Migration from `google-cloud-*` to `gcloud-*`
> Library users do not need to modify existing code. Use `package` option at [dependency] in Cargo.toml
> ```
> google-cloud-spanner = { package="gcloud-spanner", version="1.0.0" }
> ```
The official crates are not ready for use yet.
<details> …

chore(deps): Migrate from google-cloud-* to gcloud-*

---

e2e_test/README.md
e2e_test/batch/decribe_fragment.slt
proto/meta.proto
src/frontend/src/handler/describe.rs
src/frontend/src/handler/mod.rs
src/frontend/src/meta_client.rs
src/frontend/src/test_utils.rs
src/meta/service/src/stream_service.rs
src/meta/src/controller/fragment.rs
src/rpc_client/src/meta_client.rs
src/sqlparser/src/ast/mod.rs
src/sqlparser/src/parser.rs

close #21746
<details>
</details>

feat: support describe fragment <fragment-id> (#21587)

---

src/meta/src/controller/cluster.rs
src/meta/src/rpc/ddl_controller.rs

To make it less confusing in case there's misconfiguration on resource group.
<details>
</details>

refactor(meta): include resource group name in scheduling error message

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.4.0-rc.1
<details>
</details>

chore: update version to v2.4.0-rc.1

---

Cargo.lock

As titled. After this bump, the only thing still depending on arrow-53 is deltalake, which will be handled next.
<details>
</details>

chore(deps): Bump gcloud-bigquery from 1.0.0 to 1.1.0 (depending on arrow-53 -> arrow-54)

---

docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

update docker image to v2.4.0-rc.1
<details>
</details>

chore: update docker image to v2.4.0-rc.1

---

e2e_test/over_window/generated/batch/ignore_nulls/mod.slt.part
e2e_test/over_window/generated/batch/main.slt.part
e2e_test/over_window/generated/batch/odd_frames/mod.slt.part
e2e_test/over_window/generated/streaming/ignore_nulls/mod.slt.part
e2e_test/over_window/generated/streaming/main.slt.part
e2e_test/over_window/generated/streaming/odd_frames/mod.slt.part
e2e_test/over_window/templates/ignore_nulls/mod.slt.part
e2e_test/over_window/templates/main.slt.part
e2e_test/over_window/templates/odd_frames/mod.slt.part
src/expr/impl/src/window_function/buffer.rs

Fix #21705.
<details>
</details>

fix(test): include missing OverWindow slt tests

---

Makefile.toml

feat(risedev): skip build connector node for USE_SYSTEM_RISINGWAVE

---

Cargo.lock
Cargo.toml
src/expr/impl/src/udf/python.rs

In `arrow-udf-runtime` 0.8.0, python subinterpreter and the `.sandbox` method are removed, because we don't think CPython can provide proper sandboxing mechanism. After https://github.com/risingwavelabs/risingwave/pull/20893, we already disabled python embedded udf by default and don't allow user to change this config on RW Cloud, so it's safe to just remove sandboxing.
This can
- resolve #21216,
- resolve #21065,
- likely resolve #20831,
- likely resolve #21022.
<details>
</details>

chore(udf): upgrade arrow-udf-runtime to 0.8.0

---

src/frontend/src/handler/create_table.rs

- Retrieve the pk information from the table proto instead of column constraints, because column constraints could be empty when users' sql doesn't explicitly specify it.
- Related issue. https://github.com/risingwavelabs/risingwave/issues/21788
<details>
</details>

fix(iceberg): fix iceberg table engine pk retrieving

---

src/meta/node/src/server.rs
src/meta/service/src/hummock_service.rs
src/meta/src/hummock/compactor_manager.rs
src/meta/src/hummock/manager/mod.rs
src/meta/src/manager/iceberg_compaction.rs

1. refactor iceberg compaction manager 
2. introduce iceberg compactor manager 
part of https://github.com/risingwavelabs/risingwave/pull/21669
<details>
</details>

feat(compactor): introduce iceberg compactor manager

---

src/tests/sqlsmith/src/sql_gen/table_functions.rs

This PR supports generation of `regexp_match`. 
It recursively generates a regular expression pattern that matches or mis-maches the given input string. 
Ref: https://www.postgresql.org/docs/current/functions-matching.html
Fix #4540  
<details>
</details>

feat(sqlsmith): support generation of regexp_match table function

---

src/common/src/config.rs
src/storage/compactor/src/lib.rs

as title
with https://github.com/risingwavelabs/risingwave/compare/main...xxh/add-iceberg-compaction-into-compactor
<details>
</details>

feat(compactor): introduce compactor mode for iceberg

---

src/connector/src/source/cdc/external/mysql.rs

Cherry-pick #21569 to release-2.2. Conflict due to formatting. Close https://github.com/risingwavelabs/risingwave/issues/21618.
<details>
</details>

fix(cdc):  mysql default value conversion failure should be tolerated (#21569)

---

Cargo.lock
src/common/src/hash/key.rs

Motivation: separated from the upcoming chrono/arrow/datafusion/deltalake version bump, to focus on the `std::mem::size_of::<HeapNullBitmap>()` change.
Changelog:
-   0.5.7
- Optimize `Clone::clone_from` to avoid extra allocations and copies.
-   0.5.6
- Fixed FixedBitset not implementing Send/Sync due to the stack size shrink.
-   0.5.5 (yanked)
- Add functions for counting the results of a set operation (`union_count`, `intersection_count`, `difference_count`, `symmetric_difference_count`)
- **Shrink the stack size of FixedBitset. There should be zero stack …

chore(deps): Bump fixedbitset from 0.5.0 to 0.5.7

---

e2e_test/source_inline/cdc/mysql/mysql_create_drop.slt.serial
src/frontend/src/catalog/source_catalog.rs

An ad-hoc fix for https://github.com/risingwavelabs/risingwave/issues/21487.
<details>
</details>

fix(frontend): do not purify SQL definition for CDC sources

---

src/storage/src/memory.rs
src/storage/src/store.rs
src/storage/src/vector/distance.rs
src/storage/src/vector/mod.rs
src/storage/src/vector/utils.rs

feat(storage): implement in memory FLAT vector index

---

Cargo.lock
Cargo.toml
e2e_test/iceberg/test_utils/test_result.py

When `plan_task` contains delete files, there's a probability that the scan will either return `try_lock` error, or block forever
fixed by https://github.com/risingwavelabs/iceberg-rust/pull/48
- fix https://github.com/risingwavelabs/risingwave/issues/21770, https://github.com/risingwavelabs/risingwave/issues/21751
- Validated here (#21756) https://buildkite.com/risingwavelabs/main-cron/builds?branch=xxchan%2Fprominent-bovid (run main-cron test 40 times, it's green with this fix)
<details> …

fix(iceberg): fix delete file lost wake

---

ci/workflows/pull-request.yml

fix(ci): CI_STEPS regex shall not require leading space 

---

e2e_test/source_inline/kafka/datagen.slt
src/connector/src/macros.rs
src/frontend/src/scheduler/plan_fragmenter.rs

Mainly for testing purposes of batch execution.
<details>
</details>

feat(frontend): support batch scan on datagen source

---

src/frontend/planner_test/tests/testdata/input/temporal_join.yaml
src/frontend/planner_test/tests/testdata/output/temporal_join.yaml
src/frontend/src/optimizer/plan_node/logical_multi_join.rs

- Avoid reordering joins when there is a temporal join
- Resolve https://github.com/risingwavelabs/risingwave/issues/21843
<details>
</details>

fix(optimizer): fix join reorder for temporal join

---

Cargo.toml
src/common/Cargo.toml
src/common/heap_profiling/Cargo.toml
src/common/metrics/Cargo.toml
src/compute/Cargo.toml
src/connector/Cargo.toml
src/connector/codec/Cargo.toml
src/ctl/Cargo.toml
src/expr/core/Cargo.toml
src/expr/impl/Cargo.toml
src/frontend/Cargo.toml
src/jni_core/Cargo.toml
src/meta/Cargo.toml
src/meta/dashboard/Cargo.toml
src/meta/node/Cargo.toml
src/meta/service/Cargo.toml
src/object_store/Cargo.toml
src/risedevtool/Cargo.toml
src/stream/Cargo.toml
src/tests/e2e_extended_mode/Cargo.toml
src/tests/sqlsmith/Cargo.toml
src/tests/state_cleaning_test/Cargo.toml
src/utils/futures_util/Cargo.toml
src/utils/variables/Cargo.toml

https://deps.rs/repo/github/risingwavelabs/risingwave
* No actual version change in the lock file. Just updating the toml to match the lock.
* rustls will be handled separately as it takes a real version bump. (Currently we are locked to an old unaffected version.)
* Unifies `chrono`, `regex`, `smallvec` version to the workspace
<details>
</details>

chore(deps): tighten range to avoid downgrading to vulnerable versions

---

proto/stream_service.proto
src/compute/src/rpc/service/stream_service.rs
src/ctl/src/cmd_impl/hummock/migrate_legacy_object.rs
src/ctl/src/cmd_impl/hummock/sst_dump.rs
src/meta/src/backup_restore/backup_manager.rs
src/meta/src/backup_restore/restore.rs
src/meta/src/hummock/manager/checkpoint.rs
src/meta/src/hummock/manager/gc.rs
src/meta/src/hummock/manager/tests.rs
src/meta/src/hummock/manager/time_travel.rs
src/meta/src/hummock/manager/versioning.rs
src/rpc_client/src/stream_client.rs
src/storage/backup/src/lib.rs
src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
src/storage/hummock_sdk/src/lib.rs
src/storage/hummock_sdk/src/version.rs
src/storage/src/hummock/event_handler/hummock_event_handler.rs
src/storage/src/hummock/event_handler/mod.rs
src/storage/src/hummock/event_handler/uploader/mod.rs
src/storage/src/hummock/sstable_store.rs
src/storage/src/hummock/store/hummock_storage.rs

Introduce a more general enum `HummockObjectId`, to represent the general object ids tracked by hummock version. The related logic is refactored accordingly so that the GC logic becomes not special for `HummockSstableObjectId`.
<details>
</details>

refactor(storage): support GC on multiple object types and suffixs

---

ci/scripts/e2e-sink-test.sh
e2e_test/sink/postgres_sink.slt
e2e_test/sink/remote/jdbc.check.pg.slt
src/config/ci-jdbc-to-native.toml
src/connector/src/sink/postgres.rs
src/risedevtool/src/task/postgres_service.rs
src/stream/src/from_proto/sink.rs

closes https://github.com/risingwavelabs/risingwave/issues/21625.
<details>
</details>

fix(stream): switch `jdbc_pg_to_native` sink (#21543)

---

e2e_test/ddl/subscription.slt
src/frontend/src/session/cursor_manager.rs

https://github.com/risingwavelabs/risingwave/pull/21261
#21231
<details>
</details>

fix(subscription): fix cursor schema error in 2.3

---

src/frontend/src/catalog/source_catalog.rs
src/frontend/src/handler/create_source.rs
src/frontend/src/planner/relation.rs

feat: cherry-pick(2.3) add some check for iceberg source to prevent unexpected behavior (#21851)

---

e2e_test/iceberg/start_spark_connect_server.sh

In 2.4, this script is refactored. (#21690) .
So we just bump version to fix download error here
fix download error https://buildkite.com/risingwavelabs/main-cron/builds/5226
<details>
</details>

fix: bump iceberg/spark pkg version

---

e2e_test/iceberg/test_case/cdc/load.slt
src/frontend/src/handler/create_table.rs

- https://github.com/risingwavelabs/risingwave/pull/21811 stopped passing the job type to iceberg, but it should be, otherwise, we can't create an iceberg table with postgre cdc.
<details>
</details>

fix(iceberg): fix CDC table with iceberg engine

---

dashboard/package-lock.json
dashboard/package.json

I don't see it used anywhere, although it's a top-level depdendency.
It was introduced [here](https://github.com/risingwavelabs/risingwave/pull/531/files#diff-2d8d55c799cd71f1b35e831f075f8178ed1734c4820a2ad548b4dd24d6938d7cR20).
For this line: https://github.com/risingwavelabs/risingwave/pull/531/files#diff-aa4477bad62c1253d5b3c4b3259e024d7741acaca65d19301a5a7b01544cb06dR13
Removed since it triggers a dependabot alert: https://github.com/risingwavelabs/risingwave/security/dependabot/226
<details>
</details>

refactor(dashboard): remove react-syntax-highlighter

---

src/connector/src/sink/iceberg/mod.rs

- Add instruments to iceberg sink.
<details>
</details>

feat(iceberg): add await tree instrument for iceberg sink

---

Cargo.lock
src/tests/simulation/src/main.rs
src/tests/sqlsmith/Cargo.toml
src/tests/sqlsmith/config.yml
src/tests/sqlsmith/develop.md
src/tests/sqlsmith/src/bin/main.rs
src/tests/sqlsmith/src/config.rs
src/tests/sqlsmith/src/lib.rs
src/tests/sqlsmith/src/sql_gen/mod.rs
src/tests/sqlsmith/src/sql_gen/query.rs
src/tests/sqlsmith/src/sql_gen/relation.rs
src/tests/sqlsmith/src/test_runners/diff.rs
src/tests/sqlsmith/src/test_runners/fuzzing.rs
src/tests/sqlsmith/src/test_runners/utils.rs
src/tests/sqlsmith/tests/frontend/mod.rs

This PR decouples weight configuration from the generator logic in Sqlsmith, enabling more flexible and modular control over SQL generation behavior.
It introduces a YAML-based configuration mode and supports specifying a custom config file via the CLI. Each feature in the config file can be assigned two fields: weight and enabled.
For example, when adding a new feature such as `eowc`, a developer can set its weight to 100 to focus fuzzing on it. The generation logic can then be gated with a call like `self.should_generate("eowc")`, which checks the …

feat(sqlsmith): support decoupling weights from generators

---

src/frontend/src/utils/with_options.rs

Improve code reuse in WITH option resolving.
<details>
</details>

refactor(frontend): reuse `resolve_secret_refs_inner`

---

Cargo.lock
Cargo.toml

In https://github.com/risingwavelabs/risingwave/pull/21919 we changed from ddef529 to bc7dec7fea2b6d00066e7acf2f399d4a85eb0d6f
, which does not include the commit for #21848 
<details>
</details>

chore(deps): update iceberg-rust version

---

Cargo.lock
Cargo.toml
clippy.toml
src/batch/clippy.toml
src/batch/src/error.rs
src/common/src/error.rs
src/connector/src/connector_common/iceberg/jni_catalog.rs
src/connector/src/connector_common/iceberg/storage_catalog.rs
src/connector/src/error.rs
src/connector/src/source/iceberg/parquet_file_handler.rs
src/error/Cargo.toml
src/error/src/lib.rs
src/error/src/wrappers.rs
src/stream/clippy.toml

- #21919 
- #21937
<details>
</details>

chore(deps): bump iceberg-rust version to release 2.4

---

src/meta/model/src/exactly_once_iceberg_sink.rs
src/meta/src/backup_restore/restore_impl/v2.rs
src/storage/backup/src/meta_snapshot_v2.rs

This PR follows the standard steps to include a metadata model in metadata backup:
1. Derive `Serialize` and `Deserialize` for the model.
2. Add it to the `for_all_metadata_models_v2` macro.
3. Add `insert_models` for it.
<details>
</details>

fix: include exactly_once_iceberg_sink metadata in metadata backup

---

src/meta/src/backup_restore/restore.rs

Fix a risectl bug introduced in #21881
<details>
</details>

fix: fix validate_integrity bug

---

e2e_test/iceberg/pyproject.toml

- Resolve https://github.com/risingwavelabs/risingwave/security/dependabot/242
<details>
</details>

fix(iceberg): bump poetry setuptools to 78.1.1

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.4.0
<details>
</details>

chore: update version to v2.4.0

---

src/meta/src/controller/catalog/drop_op.rs

- Ban dropping database and dropping source cascade with iceberg tables.
<details>
</details>

fix(iceberg): dropping database and dropping source cascade with iceberg tables.

---

proto/frontend_service.proto
src/batch/executors/src/executor/generic_exchange.rs
src/batch/src/worker_manager/worker_node_manager.rs
src/common/src/config.rs
src/config/example.toml
src/frontend/src/handler/show.rs
src/frontend/src/rpc/mod.rs
src/frontend/src/scheduler/local.rs
src/frontend/src/session.rs
src/meta/service/src/notification_service.rs
src/meta/src/controller/cluster.rs
src/rpc_client/src/frontend_client.rs
src/tests/simulation/src/cluster.rs
src/tests/simulation/tests/integration_tests/recovery/background_ddl.rs

close #21453
follow-up: #21953
<details>
</details>

feat(frontend): SHOW PROCESSLIST of all frontends

---

docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

update docker image to v2.4.0
<details>
</details>

chore: update docker image to v2.4.0

---

e2e_test/iceberg/test_case/pure_slt/iceberg_engine.slt
src/meta/model/migration/src/lib.rs
src/meta/model/migration/src/m20250522_074525_iceberg_tables.rs
src/meta/model/migration/src/m20250522_074947_iceberg_namespace_properties.rs
src/meta/model/src/iceberg_namespace_properties.rs
src/meta/model/src/iceberg_tables.rs
src/meta/model/src/lib.rs
src/meta/src/backup_restore/restore_impl/v2.rs
src/storage/backup/src/meta_snapshot_v2.rs

- Previously, we created the hosted iceberg catalog system related tables on demand; however, our backup handling logic needs to specify models, so we need to initialize the tables at the beginning.
<details>
</details>

feat(iceberg): init and backup hosted iceberg system table

---

e2e_test/iceberg/test_case/pure_slt/iceberg_engine.slt
src/meta/model/migration/src/lib.rs
src/meta/model/migration/src/m20250522_074525_iceberg_tables.rs
src/meta/model/migration/src/m20250522_074947_iceberg_namespace_properties.rs
src/meta/model/src/iceberg_namespace_properties.rs
src/meta/model/src/iceberg_tables.rs
src/meta/model/src/lib.rs
src/meta/src/backup_restore/restore_impl/v2.rs
src/storage/backup/src/meta_snapshot_v2.rs

- resolve https://github.com/risingwavelabs/risingwave/issues/21975
<details>
</details>

feat(iceberg): cherry-pick init and backup hosted iceberg system table

---

docs/dev/src/build-and-run/intro.md
docs/dev/src/design/meta-service.md
risedev.yml

- Some outdated information I encountered while reading the documentation recently.
- Some additional notes.
<details>
</details>

chore(doc): Fixed some introduction docs

---

src/dml/src/error.rs

This PR updates the error message for `DmlError::NoReader` to enhance user understanding.
Since the `DmlManager` in compute node lacks a definitive way to determine if the cluster is in recovery, I assume that all instances of `DmlError::NoReader` are due to cluster recovery.
<details>
</details>

refactor: refine error message

---

ci/scripts/standalone-utils.sh
src/cmd_all/scripts/standalone-demo-dev.sh
src/cmd_all/scripts/standalone-demo-full.sh
src/frontend/src/lib.rs

This PR updates the default gRPC listening address for the frontend, allowing the port to be accessible from within the Kubernetes cluster network. According to the docker spec, `Any port which is listening on the default "0.0.0.0" address inside a container will be accessible from the network`
https://risingwave-labs.slack.com/archives/C03DFGV6L2W/p1748519736091219?thread_ts=1748508108.072629&cid=C03DFGV6L2W
<details>
</details>

refactor: change default gRPC addr

---

src/stream/src/executor/backfill/arrangement_backfill.rs
src/stream/src/executor/backfill/utils.rs
src/stream/src/executor/over_window/general.rs

feat(streaming): add tracing logs for arrangement backfill and improve inconsistency logs for over window

---

e2e_test/ddl/alter_table_column_type/with_index.slt
proto/expr.proto
src/common/src/types/mod.rs
src/common/src/types/struct_type.rs
src/frontend/src/catalog/index_catalog.rs
src/frontend/src/expr/pure.rs
src/frontend/src/optimizer/plan_expr_visitor/strong.rs
src/meta/src/controller/rename.rs
src/meta/src/controller/streaming_job.rs

Rewrite the persisted expression of index items after there's `ALTER COLUMN TYPE`. In short, we will wrap `InputRef` with an internal `CompositeCast` in the meta service to maintain correct return type, and further eliminate it with expression rewriter in frontend.
This allows functional index like struct field accessing still work after adding more field into the struct (regardless of the position of the new field).
<details>
</details>

feat(meta): rewrite index after `ALTER COLUMN TYPE`

---

src/common/src/util/deployment.rs
src/utils/pgwire/src/error.rs
src/utils/pgwire/src/lib.rs
src/utils/pgwire/src/pg_extended.rs
src/utils/pgwire/src/pg_protocol.rs

While troubleshooting https://github.com/risingwavelabs/risingwave/issues/21751 , the error contains limited context, making it quite hard to debug.
```
2025-05-03T16:14:54.873906933Z ERROR handle_query: pgwire::pg_protocol: error when process message error=Failed to run the query: Scheduler error: Unexpected => try_lock failed because the operation would block mode="simple query" session_id=4 sql=SELECT count(*) FROM iceberg_t1_source
```
~Previously attempted to use `?err.as_report()` but it doesn't seem to work.  https://github.com/risingwavelabs/risingwave/pull/21756. So using the most brute-force way for now.~
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License …

feat: print backtrace in pg_protocol in debug mode

---

e2e_test/source_inline/kafka/protobuf/alter_source.slt

fix #21701 
<details>
</details>

ci: add sleep to increase test stability

---

e2e_test/source_inline/connection/issue_22096.slt
src/meta/node/src/lib.rs
src/meta/node/src/server.rs
src/meta/src/manager/diagnose.rs
src/meta/src/manager/env.rs

Previously frontend node will redact SQL options according on configurable keywords, while meta node's diagnosis report will always redact all SQL options.
In this PR we make the diagnosis report redaction use the same configurable keywords as well.
<details>
</details>

fix: redact sql option in diagnosis report according to keywords

---

ci/scripts/check-dylint.sh
lints/ui/format_error.stderr

To enforce that our lints on error formatting work as expected.
<details>
</details>

chore(ci): enforce unit (UI) test of dylint

---

src/common/src/util/mod.rs
src/common/src/util/quote_ident.rs
src/expr/impl/src/scalar/string.rs
src/sqlparser/src/ast/mod.rs

...so that it can be reused in other places.
<details>
</details>

refactor: extract `QuoteIdent` wrapper for formatting quoted identifier

---

src/connector/src/connector_common/common.rs
src/connector/src/connector_common/mod.rs
src/connector/src/source/kinesis/mod.rs
src/connector/src/source/kinesis/source/reader.rs
src/connector/with_options_sink.yaml
src/connector/with_options_source.yaml

(cherry picked from commit 14d4c71e81fbaa57e48e4ce79dc1faa13c82cd95)
close #22116
<details>
</details>

fix(connector): add timeout and retry for kinesis client (#21616)

---

e2e_test/batch/types/struct/struct_field_ident.slt.part
src/common/src/types/struct_type.rs
src/common/src/util/mod.rs
src/common/src/util/quote_ident.rs
src/expr/impl/src/scalar/string.rs
src/sqlparser/src/ast/mod.rs

Fi x #22073.
<details>
</details>

fix(types): quote struct field identifiers in `Display` implementation

---

src/tests/simulation/tests/integration_tests/log_store/scale.rs

Closes https://github.com/risingwavelabs/risingwave/issues/22125
<details>
</details>

fix(ci):  increase load to increase logstore lag

---

e2e_test/backwards-compat-tests/scripts/utils.sh

fix(ci): fix backwards compat test offset version (#22133)

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.4.1
<details>
</details>

chore: update version v2.4.1

---

src/common/src/types/map_type.rs
src/common/src/types/mod.rs
src/common/src/types/struct_type.rs
src/expr/core/src/sig/mod.rs
src/frontend/planner_test/tests/testdata/output/temporal_filter.yaml
src/frontend/planner_test/tests/testdata/output/union.yaml
src/frontend/src/optimizer/plan_node/logical_union.rs

refactor(common): remove `PartialOrd` for `DataType` (retained for `DataTypeName`) (#22053)

---

src/connector/src/source/kafka/client_context.rs

fix: improve error handling for AWS MSK IAM token generation

---

ci/workflows/pull-request.yml

Sequel to #21943 and #22182 ...
We will handle the following separately:
* consider unify the settings to a single place
* adding a way to run all tests
<details>
</details>

fix(ci): update pull-request PostgreSQL meta backend password

---

proto/plan_common.proto
src/common/src/catalog/column.rs
src/common/src/catalog/test_utils.rs
src/stream/src/executor/source/state_table_handler.rs

- Fix column desc proto, previously we add an additional `nullable` column to the proto, whose default value is false. It should be optional, otherwise,e it would cause a compatibility issue.
<details>
</details>

fix(proto): fix nullable column

---

src/meta/src/barrier/command.rs
src/meta/src/barrier/complete_task.rs
src/meta/src/barrier/context/context_impl.rs
src/meta/src/barrier/progress.rs
src/meta/src/barrier/rpc.rs
src/meta/src/barrier/schedule.rs
src/meta/src/barrier/worker.rs
src/meta/src/controller/fragment.rs
src/meta/src/controller/streaming_job.rs
src/meta/src/manager/metadata.rs
src/meta/src/manager/streaming_job.rs
src/meta/src/rpc/ddl_controller.rs
src/meta/src/stream/scale.rs
src/meta/src/stream/source_manager.rs

https://github.com/risingwavelabs/risingwave/issues/14131.
This PR is a follow-up of #22141 to add await tree to meta nodes.
<details>
</details>

feat(meta): add await-tree instrument for barrier manager

---

Cargo.lock
proto/expr.proto
src/expr/impl/Cargo.toml
src/expr/impl/src/scalar/ai_model.rs
src/expr/impl/src/scalar/mod.rs
src/frontend/src/binder/expr/function/builtin_scalar.rs
src/frontend/src/expr/pure.rs
src/frontend/src/optimizer/plan_expr_visitor/strong.rs

According to comments of #21929, we decided to implement AI functions as normal expressions with `prebuilt` "context", which do simplifies the code. However, we then have two more things to do to achieve a better UX:
1. #22240
2. #22254
<details>
</details>

feat(expr): add `openai_embedding` function

---

src/frontend/src/handler/alter_user.rs
src/frontend/src/handler/create_user.rs
src/frontend/src/handler/mod.rs
src/frontend/src/handler/variable.rs
src/frontend/src/meta_client.rs
src/frontend/src/test_utils.rs
src/rpc_client/src/meta_client.rs

chore: notice about empty password when trying to create or alter user

---

src/frontend/src/binder/delete.rs
src/frontend/src/binder/expr/function/mod.rs
src/frontend/src/binder/insert.rs
src/frontend/src/binder/relation/table_or_source.rs
src/frontend/src/binder/update.rs
src/frontend/src/catalog/system_catalog/rw_catalog/rw_user_secrets.rs
src/frontend/src/handler/alter_rename.rs
src/frontend/src/handler/alter_user.rs
src/frontend/src/handler/create_database.rs
src/frontend/src/handler/create_index.rs
src/frontend/src/handler/create_schema.rs
src/frontend/src/handler/create_user.rs
src/frontend/src/handler/drop_index.rs
src/frontend/src/handler/privilege.rs
src/frontend/src/handler/use_db.rs
src/frontend/src/session.rs

Closed #21733 . After this PR, the error message will be like: 
```sql
dev=> create table t1(v1 int);
Caused by:
Permission denied: permission denied for schema "public": "CREATE"
```
This aligns with the behavior observed in pg, and acl is provided with the added benefit of providing extra information.
<details>
</details>

chore: enhance the clarity of the error message for privilege denial

---

e2e_test/streaming/materialized_project.slt
src/frontend/planner_test/tests/testdata/input/project.yaml
src/frontend/planner_test/tests/testdata/output/cse_expr.yaml
src/frontend/planner_test/tests/testdata/output/project.yaml
src/frontend/src/optimizer/plan_node/logical_project.rs

In https://github.com/risingwavelabs/risingwave/pull/20971 we started to do materialization for all UDF calls. In https://github.com/risingwavelabs/risingwave/pull/22242 we introduced `openai_embedding`, a builtin impure function which is very likely to be used in stream queries. This PR includes such functions in `MaterializedExprs` operators to avoid potential inconsistency.
Fix #22254.
<details>
</details>

feat(expr): use `MaterializedExprs` for all impure expressions

---

src/stream/src/executor/backfill/utils.rs

resolve https://github.com/risingwavelabs/risingwave/issues/22164
<details>
</details>

fix(snapshot-backfill): ensure data chunk builder size has least 2

---

src/frontend/src/handler/mod.rs
src/frontend/src/handler/prepared_statement.rs
src/sqlparser/src/ast/mod.rs
src/sqlparser/src/parser.rs
src/sqlparser/tests/sqlparser_postgres.rs
src/utils/pgwire/src/pg_response.rs

As titled.
postgre python library `psycopg` calls `DEALLOCATE` in its usual execution, which will fail on unsupported statement when querying RisingWave. Therefore, in this PR, we will add a dummy implementation to let the statement succeed.
This is part of the fix to the corrupted feature store demo in integration tests.
<details>
</details>

feat(frontend): add dummy handling of PREPARE and DEALLOCATE

---

java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java

fix(connector): avoid returning any rows for jdbc sink

---

src/connector/src/connector_common/common.rs
src/connector/src/connector_common/mod.rs
src/connector/src/source/kinesis/mod.rs
src/connector/src/source/kinesis/source/reader.rs

close https://github.com/risingwavelabs/risingwave/issues/22162
<details>
</details>

fix: remove KinesisSdkOptions for compatibility issue (#22143)

---

dashboard/components/Relations.tsx
dashboard/lib/api/streaming.ts
src/meta/node/src/server.rs
src/meta/src/dashboard/mod.rs

feat(dashboard): show table data size

---

src/frontend/src/handler/create_table.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/21815#issuecomment-2989860185
- Previously we didn't handle the empty password.
<details>
</details>

fix(iceberg): fix empty metastore password for iceberg engine.

---

Makefile.toml

fix(risedev): fix kill when no llvm code cov env set

---

src/common/src/system_param/mod.rs
src/frontend/src/handler/alter_database_param.rs
src/frontend/src/handler/alter_system.rs
src/frontend/src/handler/create_database.rs
src/meta/src/controller/catalog/alter_op.rs
src/meta/src/controller/catalog/create_op.rs

Add the same checks for database param as system param.
<details>
</details>

fix(ddl): add parameter check for database

---

src/error/src/code.rs
src/error/src/lib.rs
src/error/src/tonic/extra.rs
src/meta/src/barrier/rpc.rs
src/utils/pgwire/src/error_or_notice.rs
src/utils/pgwire/src/pg_message.rs

Towards #21924.
- Forward the `PostgresErrorCode` within errors, including gRPC boundary
- Request it at the top level (pgwire server)
- Generate the corresponding response message, instead of always using the code for "internal error"
<details>
</details>

feat(error): forward postgres error code & use it in pgwire server

---

ci/scripts/release.sh

The absolute path is incorrect.
<details>
</details>

fix:  unset `RUSTC_WORKSPACE_WRAPPER` for release script

---

proto/meta.proto
proto/stream_plan.proto
src/frontend/src/handler/alter_streaming_enable_unaligned_join.rs
src/frontend/src/handler/mod.rs
src/frontend/src/meta_client.rs
src/frontend/src/optimizer/plan_node/stream_sync_log_store.rs
src/frontend/src/test_utils.rs
src/meta/service/src/stream_service.rs
src/meta/src/controller/streaming_job.rs
src/rpc_client/src/meta_client.rs
src/sqlparser/src/ast/ddl.rs
src/sqlparser/src/parser.rs
src/stream/src/executor/sync_kv_log_store.rs
src/stream/src/from_proto/sync_log_store.rs

Only used for testing: https://github.com/risingwavelabs/risingwave/pull/22320.
I don't plan to make it user-facing (yet).
<details>
</details>

feat(meta): support offline realignment of unaligned join

---

Cargo.lock
Cargo.toml
src/ctl/src/common/hummock_service.rs
src/java_binding/src/hummock_iterator.rs
src/storage/Cargo.toml
src/storage/benches/bench_block_cache.rs
src/storage/benches/bench_compactor.rs
src/storage/benches/bench_multi_builder.rs
src/storage/hummock_test/src/bin/replay/main.rs
src/storage/src/hummock/event_handler/refiller.rs
src/storage/src/hummock/iterator/test_utils.rs
src/storage/src/hummock/sstable_store.rs
src/storage/src/hummock/test_utils.rs
src/storage/src/store_impl.rs

Signed-off-by: MrCroxx <mrcroxx@outlook.com>I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593ebdbfa826691daf75bdab7d14fa0/.github/contributor-license-agreement.txt).
The pre-PR for refiller refactor.
If @Li0k needs to bump crate `iceberg-compaction-core`, please merge this PR first.
<details>
</details>

chore: bump foyer + mixtrics

---

src/meta/src/barrier/utils.rs

fix(meta): fix incorrectly marking worker node as barrier collected

---

src/frontend/planner_test/src/lib.rs
src/frontend/src/catalog/table_catalog.rs
src/frontend/src/handler/alter_table_column.rs
src/frontend/src/handler/alter_table_drop_connector.rs
src/frontend/src/handler/alter_table_with_sr.rs
src/frontend/src/handler/create_index.rs
src/frontend/src/handler/create_mv.rs
src/frontend/src/handler/create_sink.rs
src/frontend/src/handler/create_table.rs
src/frontend/src/handler/create_table_as.rs
src/frontend/src/handler/drop_sink.rs
src/frontend/src/handler/explain.rs
src/frontend/src/rpc/mod.rs

This is because, in many cases, we want to manipulate the `Table` or `Source` catalog after they are generated with a commonly reused `plan_xxx` function. Keeping them in the frontend-version struct makes them easier to modify and avoids unnecessary backward conversion.
<details>
</details>

refactor(frontend): defer converting into `PbTable` or `PbSource` until necessary in handler

---

e2e_test/iceberg/start_spark_connect_server.sh

- Recently, the iceberg e2e-tests timeout frequently, let's add some time measurement to monitor it.
<details>
</details>

chore(iceberg): measure the iceberg spark download time for e2e test

---

java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java

fix(connector): avoid returning any rows for jdbc sink#22280

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.3.4
<details>
</details>

chore: update version to v2.3.4

---

src/tests/sqlsmith/src/sql_gen/functions.rs
src/tests/sqlsmith/src/sql_gen/types.rs

From @xiangjinwu:
> In PostgreSQL, varchar supports both strpos and position , while bytea only supports position
> In RisingWave, we dispatch strpos and position to the same implementation without checking the data type. As a result:
v2.4: varchar supports both and bytea supports neither
v2.5/main: both varchar and bytea supports both strpos and position (by [#22076](https://github.com/risingwavelabs/risingwave/pull/22076))
So for now we just ban it. Tracking its re-enabling in https://github.com/risingwavelabs/risingwave/issues/7328
<details> …

chore(sqlsmith): ban strpos/position

---

src/frontend/planner_test/src/lib.rs
src/frontend/src/handler/query.rs
src/frontend/src/optimizer/mod.rs
src/frontend/src/optimizer/plan_node/stream_materialize.rs
src/frontend/src/optimizer/plan_node/stream_sink.rs
src/frontend/src/optimizer/plan_visitor/execution_mode_decider.rs
src/frontend/src/optimizer/plan_visitor/read_storage_table_visitor.rs
src/frontend/src/optimizer/plan_visitor/sys_table_visitor.rs
src/frontend/src/planner/delete.rs
src/frontend/src/planner/insert.rs
src/frontend/src/planner/mod.rs
src/frontend/src/planner/query.rs
src/frontend/src/planner/statement.rs
src/frontend/src/planner/update.rs
src/tests/sqlsmith/tests/frontend/mod.rs

Previously in frontend optimizer, we have `PlanPhase` enum to determine the current phase of the plan. We have assertion on the phase to ensure that plan of invalid phase is not passed by mistake.
In this PR, we will change from dynamic enum type to static generic type, so that we can detect the incorrect usage at compile time.
<details>
</details>

refactor(frontend): static typed plan phase

---

e2e_test/iceberg/start_spark_connect_server.sh

- As titled.
<details>
</details>

chore(iceberg): speed up iceberg e2e test

---

e2e_test/iceberg/start_spark_connect_server.sh

- Resolve https://github.com/risingwavelabs/risingwave/issues/22478
<details>
</details>

test(iceberg): speedup iceberg test in v2.4

---

src/storage/src/store.rs
src/storage/src/vector/hnsw.rs
src/storage/src/vector/mod.rs
src/storage/src/vector/utils.rs

feat(storage): implement in memory hnsw builder

---

Cargo.lock
Cargo.toml
ci/scripts/release.sh

successful build in https://buildkite.com/risingwavelabs/docker/builds/17485
<details>
</details>

fix(release): install dependencies required by faiss in release pipeline

---

Cargo.lock
lints/src/utils/format_args_collector.rs
src/frontend/src/handler/alter_mv.rs
src/meta/Cargo.toml
src/meta/src/rpc/ddl_controller.rs
src/meta/src/stream/stream_graph.rs
src/meta/src/stream/stream_graph/fragment.rs
src/meta/src/stream/stream_graph/state.rs
src/meta/src/stream/stream_graph/state_match.rs
src/prost/build.rs

In the last PR (#22366), we've introduced minimal support for `ALTER MATERIALIZED VIEW`. However, the state table mapping algorithm is trivial and can be problematic in many cases:
> Note that we inherit the very basic algorithm for matching internal tables that's used by replacing table with connector (only source node state table). In this implementation, we simply sort the tables and match them without any additional checks. This assumes that there's neither change on the topological structure of the fragment graph, nor schema change, which is typically …

feat(meta): introduce basic state table mapping algorithm for `ALTER MV`

---

.gitignore

chore: update .gitignore to exclude rustc ice files

---

Cargo.lock
src/license/Cargo.toml
src/license/src/feature.json
src/license/src/feature.rs

Instead of defining features in the macro `def_feature!`, this PR moves the definition to a JSON schema file `feature.json`. This makes it easier for other repositories to reuse the feature definition.
<details>
</details>

refactor(license): define feature list with JSON schema

---

src/frontend/src/catalog/system_catalog/rw_catalog/rw_connections.rs
src/frontend/src/catalog/system_catalog/rw_catalog/rw_secrets.rs
src/meta/src/controller/utils.rs

Left by #20755 .
<details>
</details>

fix: construct user info after secret and conn privilege granted or revoked

---

Cargo.lock
Cargo.toml
src/ctl/src/common/hummock_service.rs
src/java_binding/src/hummock_iterator.rs
src/storage/Cargo.toml
src/storage/benches/bench_block_cache.rs
src/storage/benches/bench_compactor.rs
src/storage/benches/bench_multi_builder.rs
src/storage/hummock_test/src/bin/replay/main.rs
src/storage/src/hummock/event_handler/refiller.rs
src/storage/src/hummock/iceberg_compactor_runner.rs
src/storage/src/hummock/iterator/test_utils.rs
src/storage/src/hummock/sstable_store.rs
src/storage/src/hummock/test_utils.rs
src/storage/src/store_impl.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/22463
<details>
</details>

fix: cherry pick iceberg-compaction & foyer location generator to v2.5

---

e2e_test/ddl/alter_set_schema.slt
e2e_test/source_inline/connection/ddl.slt

as title
feature impl in https://github.com/risingwavelabs/risingwave/pull/13341 
<details>
</details>

test: cover ALTER CONNECTION SET SCHEMA

---

Cargo.toml

fix(build): disable parallel frontend to reduce ICE

---

ci/workflows/main-cron.yml

chore: update timeout in main-cron

---

dashboard/components/Relations.tsx
dashboard/lib/api/streaming.ts
proto/catalog.proto
proto/ddl_service.proto
src/connector/src/sink/catalog/mod.rs
src/frontend/src/catalog/catalog_service.rs
src/frontend/src/catalog/table_catalog.rs
src/frontend/src/handler/create_index.rs
src/frontend/src/handler/create_table.rs
src/frontend/src/handler/create_table_as.rs
src/frontend/src/handler/create_view.rs
src/frontend/src/handler/explain.rs
src/frontend/src/optimizer/plan_node/stream_materialize.rs
src/frontend/src/optimizer/plan_node/utils.rs
src/frontend/src/scheduler/distributed/query.rs
src/frontend/src/session/cursor_manager.rs
src/frontend/src/test_utils.rs
src/meta/service/src/ddl_service.rs
src/meta/src/controller/catalog/create_op.rs
src/meta/src/controller/catalog/test.rs
src/meta/src/controller/mod.rs
src/meta/src/controller/streaming_job.rs
src/meta/src/manager/streaming_job.rs
src/meta/src/rpc/ddl_controller.rs
src/rpc_client/src/meta_client.rs
src/storage/src/compaction_catalog_manager.rs

chore: fully deprecate dependent_relations to avoid misuse

---

e2e_test/source_inline/pulsar/basic.slt
src/connector/src/source/pulsar/enumerator/client.rs
src/connector/src/source/pulsar/topic.rs

close https://github.com/risingwavelabs/risingwave/issues/22528
do check for topic existence for persistent topics
```
For non-persistent topics
* Non-persistent topics are meant for transient messaging—messages are not stored on disk and can be lost if consumers are offline.
* Because of their short-lived nature, non-persistent topics do not always exist on brokers unless there's active traffic.
* So, unless there's a live producer/consumer, the broker may not be aware of the non-persistent topic.
```
<details> …

fix: check pulsar topic exist

---

e2e_test/source_legacy/cdc_inline/auto_schema_change_pg.slt
src/frontend/src/catalog/purify.rs
src/frontend/src/handler/create_table.rs
src/meta/service/src/ddl_service.rs

Close https://github.com/risingwavelabs/risingwave/issues/22489
We have a logic to determine whether the schema before and after the change are subsets or supersets of each other, to ensure that the schema change only drops columns and adds columns. However, when comparing, if the hidden column is included in the rw table, it will definitely fail. This PR fixes this problem, and add test.
<details>
</details>

fix(cdc): fix auto schema change failure when include hidden columns 

---

src/frontend/src/handler/alter_system.rs

Fixes #22540 . After this PR, only super user can alter the system parameters, i.e:
```sql
dev=> alter system set max_concurrent_creating_streaming_jobs to 1;
Caused by:
Permission denied: must be superuser to execute ALTER SYSTEM command
```
<details>
</details>

fix: only super user can alter system parameters

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.5.0-rc.1
<details>
</details>

chore: update v2.5.0-rc.1

---

src/connector/src/source/base.rs

refactor(source): remove dead code 

---

src/meta/src/controller/catalog/mod.rs

Fixed #22599 .
<details>
</details>

fix: include internal tables of the creating background job in snapshot

---

src/utils/pgwire/src/pg_protocol.rs

https://www.postgresql.org/docs/17/protocol-flow.html#PROTOCOL-FLOW-CANCELING-REQUESTS
> The server will process this request and then close the connection. For security reasons, no direct reply is made to the cancel request message.
https://github.com/postgres/postgres/blob/REL_17_5/src/interfaces/libpq/fe-cancel.c#L257-L274
```
* At this point we are waiting on the server to close the connection,
* which is its way of communicating that the cancel has been handled.
* We don't expect any data, only connection closure. So if we strangely
* do receive some …
```

fix(pgwire): CancelRequest shall not be responded

---

Cargo.lock
Cargo.toml
src/storage/Cargo.toml

- Fix iceberg plan files stuck issue. Related PR: https://github.com/risingwavelabs/iceberg-rust/pull/61
<details>
</details>

fix(iceberg): fix iceberg plan files stuck

---

e2e_test/iceberg/start_spark_connect_server.sh

test(iceberg): speedup iceberg test in v2.3

---

src/stream/src/executor/aggregate/agg_group.rs

feat: parallelize apply_chunk in agg

---

.github/workflows/copilot-setup-steps.yml
src/connector/src/sink/kafka.rs
src/connector/src/source/kafka/enumerator.rs

fix: improve error handling in reachability check for Kafka Sink

---

java/connector-node/risingwave-sink-jdbc/pom.xml
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JdbcUtils.java
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/jdbc/PostgresDialect.java
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/jdbc/RedShiftDialect.java
java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/jdbc/RedShiftDialectFactory.java

We're experiencing compatibility issues with our JDBC sink when writing data to Redshift. Here, we have introduced Redshift's JDBC package and used merge to perform upsert operations.
<details>
</details>

feat(sink): support redshifit sink with jdbc

---

src/connector/src/sink/big_query.rs
src/connector/src/sink/clickhouse.rs
src/connector/src/sink/doris.rs
src/connector/src/sink/dynamodb.rs
src/connector/src/sink/elasticsearch_opensearch/elasticsearch.rs
src/connector/src/sink/elasticsearch_opensearch/opensearch.rs
src/connector/src/sink/file_sink/opendal_sink.rs
src/connector/src/sink/google_pubsub.rs
src/connector/src/sink/kafka.rs
src/connector/src/sink/kinesis.rs
src/connector/src/sink/mod.rs
src/connector/src/sink/mongodb.rs
src/connector/src/sink/mqtt.rs
src/connector/src/sink/nats.rs
src/connector/src/sink/postgres.rs
src/connector/src/sink/pulsar.rs
src/connector/src/sink/redis.rs
src/connector/src/sink/remote.rs
src/connector/src/sink/sqlserver.rs
src/connector/src/sink/starrocks.rs
src/connector/src/sink/trivial.rs

refactor(sink): no explicit specifying dummy sink coordinator

---

Cargo.lock
Cargo.toml

Apply https://github.com/risingwavelabs/faiss-rs/pull/2.
Thanks to @xxchan .
<details>
</details>

fix(storage): bump faiss-rs to avoid unstable PATH to avoid frequent rebuild

---

src/connector/src/source/filesystem/opendal_source/opendal_enumerator.rs

As title, previously, to support the match pattern set as a single file, we changed the prefixes without a trailing slash to the list root directory, which resulted in too many files being listed. This PR addresses that issue.
<details>
</details>

fix(file source): Optimize list prefix handling to avoid root directory scans

---

ci/workflows/main-cron.yml

failed occasionally on v2.5 and nightly is also very close to timeout
<details>
</details>

chore: increase build other components timeout

---

.github/workflows/copilot-setup-steps.yml

ci: fix tool install in copilot-setup-steps

---

proto/stream_plan.proto
src/meta/src/rpc/ddl_controller.rs
src/meta/src/stream/stream_graph/actor.rs
src/meta/src/stream/stream_graph/fragment.rs

As title.
<details>
</details>

fix(proto): Deprecate unused MergeNode fields

---

src/common/src/config.rs
src/config/example.toml
src/connector/src/sink/iceberg/mod.rs

- https://github.com/risingwavelabs/risingwave/pull/22663
<details>
</details>

fix: configure iceberg sink parquet row group for release 2.5

---

Cargo.lock
Cargo.toml
src/connector/src/source/iceberg/mod.rs
src/storage/Cargo.toml
src/stream/src/executor/source/iceberg_fetch_executor.rs

- Reduce iceberg plan files consumption. Related PR: https://github.com/risingwavelabs/iceberg-rust/pull/64
<details>
</details>

feat(iceberg): reduce plan files memory consumption

---

e2e_test/sink/sink_into_table/alter_column.slt
src/frontend/src/handler/alter_table_column.rs

- Should match column id instead of data type.
- When not match, the default value of the target column should be inserted, instead of null.
<details>
</details>

fix(frontend): Fix alter table column project node under sink-into-table

---

proto/expr.proto
src/expr/impl/src/scalar/vector_dist.rs
src/frontend/src/binder/expr/binary_op.rs
src/frontend/src/binder/expr/function/builtin_scalar.rs
src/frontend/src/expr/function_call.rs
src/frontend/src/expr/pure.rs
src/frontend/src/expr/type_inference/func.rs
src/frontend/src/optimizer/plan_expr_visitor/strong.rs

In addition to `l2_distance`/`<->`, this PR adds 3 more distance functions found in pgvector:
* `cosine_distance`/`<=>`
* `l1_distance`/`<+>`
* `inner_product` (and `<#>` being negative inner product)
The docslt test cases are taken from pgvector regress tests:
https://github.com/pgvector/pgvector/blob/v0.8.0/test/expected/vector_type.out#L373-L535
<details>
</details>

feat(expr): more `vector` distance functions

---

src/meta/src/stream/stream_graph/actor.rs
src/meta/src/stream/stream_graph/fragment.rs
src/meta/src/stream/stream_graph/state_match.rs

As title. Although we've aligned the `max_parallelism` of the new job in the frontend before requesting job replacement, we may still do this verification as a double check.
<details>
</details>

feat(meta): check if derived vnode count matches existing state tables during job replacement

---

e2e_test/error_ui/simple/license.slt
proto/expr.proto
src/expr/impl/src/scalar/license.rs
src/expr/impl/src/scalar/mod.rs
src/expr/impl/src/scalar/test_license.rs
src/frontend/src/binder/expr/function/builtin_scalar.rs
src/frontend/src/catalog/system_catalog/rw_catalog/mod.rs
src/frontend/src/catalog/system_catalog/rw_catalog/rw_features.rs
src/frontend/src/expr/pure.rs
src/frontend/src/optimizer/plan_expr_visitor/strong.rs
src/license/src/cpu.rs
src/license/src/feature.json
src/license/src/feature.rs
src/license/src/lib.rs
src/license/src/manager.rs
src/risedevtool/src/task/utils.rs
src/tests/simulation/tests/integration_tests/license_cpu_limit.rs

Since there won't be the concept of "Paid" tier in kernel's source code after https://github.com/risingwavelabs/risingwave/pull/22506, this PR makes our licensing system more focus on the availability of different `Feature` instead of predefined `Tier`.
- Add a system table `rw_features` to list all features in the system and their availability.
- Add a new function `rw_test_feature(<FeatureNameInCamelCase>)` to test the availability of a specific feature. Throws if it's not.
- Rename dummy feature `TestPaid` to `TestDummy`.
- Deprecate `rw_test_paid_tier`. …

feat(license): add `rw_features` system table & `rw_test_feature` function

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

release v2.5.0
<details>
</details>

chore: update version to v2.5.0

---

e2e_test/udf/tests/language_specific/sql.slt
src/frontend/src/binder/expr/function/mod.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/12422 
- It seems we don't handle the schema of functions well at the beginning, even after we have the implementation, we still ban it. This PR just removes the restriction.
<details>
</details>

feat(binder): support schema binding of functions

---

README.md

chore: update the readme

---

src/frontend/src/session.rs

🥵 should check the `usage` privilege of secret, not `create`. We need to implement `has_secret_privilege` like `has_table_privilege` to cover this case.
<details>
</details>

fix: check usage privilege for secret

---

src/frontend/src/expr/agg_call.rs
src/frontend/src/expr/correlated_input_ref.rs
src/frontend/src/expr/function_call.rs
src/frontend/src/expr/function_call_with_lambda.rs
src/frontend/src/expr/input_ref.rs
src/frontend/src/expr/literal.rs
src/frontend/src/expr/mod.rs
src/frontend/src/expr/now.rs
src/frontend/src/expr/parameter.rs
src/frontend/src/expr/subquery.rs
src/frontend/src/expr/table_function.rs
src/frontend/src/expr/user_defined_function.rs
src/frontend/src/expr/window_function.rs

Just a minor refactoring as a preparation for #22748.
<details>
</details>

refactor(frontend): make `to_expr_proto` failable instead of directly panicking

---

src/connector/src/sink/file_sink/s3.rs
src/connector/src/sink/redshift.rs
src/connector/src/sink/snowflake.rs

feat(sink): add s3 writer snowflake sink

---

src/stream/src/executor/backfill/cdc/cdc_backfill.rs

fix(cdc): limit cdc offset fetch concurrency globally

---

Cargo.lock
Cargo.toml

chore(deps): bump madsim-rdkafka to 0.4.4 (#22343) (#22351)

---

e2e_test/udf/tests/language_specific/sql.slt
src/frontend/src/binder/expr/mod.rs
src/frontend/src/error.rs
src/frontend/src/handler/create_sql_function.rs

The previous error reporting looks so but is, in fact, fragile. Let's simplify it by directly perserving the error chain from binder.
<details>
</details>

refactor(binder): simplify error reporting for binding SQL UDF

---

src/connector/src/connector_common/postgres.rs
src/connector/src/sink/redshift.rs

refactor(pg-cdc): do not require table owner permission for pk access

---

src/frontend/src/session.rs

Resolved #22785 .
<details>
</details>

fix: check usage privilege for secret (#22784)

---

Cargo.lock
Cargo.toml
src/storage/Cargo.toml

- fix https://github.com/risingwavelabs/iceberg-rust/pull/65
- Fix iceberg-rust parquet max stats bug. It would cause a duplicate rows with the same pk after spark compaction since spark compaction would utilize the stats to prune parquet files.
<details>
</details>

fix(iceberg): fix iceberg-rust parquet max stats

---

src/connector/src/connector_common/iceberg/mod.rs
src/connector/src/connector_common/iceberg/storage_catalog.rs

- Resolve https://github.com/risingwavelabs/risingwave/issues/22847#issuecomment-3173853672
- Previously, we only handled the s3 path style access for the rest catalog, but actually all the iceberg-rust file IO need to be configured as well.
<details>
</details>

fix(iceberg): fix iceberg s3 path style access

---

java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/DbzConnectorConfig.java
src/common/src/session_config/mod.rs
src/connector/src/allow_alter_on_fly_fields.rs
src/connector/src/with_options_test.rs
src/frontend/src/handler/create_source.rs

As title.
<details>
</details>

refactor(cdc): allow alter cdc source cdc.source.wait.streaming.start.timeout

---

src/stream/src/executor/join/hash_join.rs

State reads might have transient issues, if object store connection is flaky. 
> @zwang28: Panic is bad. Previously it panic, and write core dump, and further crash the K8S node since the core dump is too large, and further crash other pods in the same nodes, and so on..
For unrecoverable errors (missing state table) I use `expect` instead, and detail why it should be present.
v.2.4.3 branch: https://github.com/risingwavelabs/risingwave/pull/22879
<details>
</details>

fix(streaming): avoid `unwrap` when reading state

---

src/connector/src/sink/snowflake_redshift/redshift.rs

Met the following error during testing
```
ERROR: Invalid credentials. Must be of the format: credentials 'aws_iam_role=...' or 'aws_access_key_id=...;aws_secret_access_key=...[
;token=...
```
This PR should fix it.
<details>
</details>

fix(redshift): sepecify aws_iam_role in redshift COPY sql

---

src/stream/src/executor/temporal_join.rs

- We should use prev_epoch instead of cur_epoch to read the temporal join right side table.
<details>
</details>

fix: fix temporal join prev epoch

---

src/meta/model/src/user_default_privilege.rs
src/meta/src/backup_restore/restore_impl/v2.rs
src/storage/backup/src/meta_snapshot_v2.rs

As titled.
<details>
</details>

fix(meta): include new model in metadata backup

---

src/connector/src/sink/snowflake_redshift/snowflake.rs

fix(sink): remove drop pipe when recovery

---

.github/workflows/run-perf-test.yml

`q6` doesn't exist + fix default name (cannot have Uppercase) + add link to dashboard
<details>
</details>

fix(ci): remove non-existent query for nexmark action

---

src/connector/src/allow_alter_on_fly_fields.rs
src/connector/src/lib.rs
src/connector/src/with_options_test.rs

chore: skip generated `allow_alter_on_fly_fields` format check

---

ci/scripts/common.sh

As title, because only if we use `buildkite-docker-compose` plugin our working directory is `/risingwave`. However, `common.sh` may also be used in other cases.
<details>
</details>

fix(ci): use dirname instead of hard-coded absolute path for env in `common.sh`

---

src/frontend/src/handler/create_sink.rs

fix: only auto fill intermediate table name for redshift/snowflake

---

src/object_store/src/object/opendal_engine/opendal_object_store.rs

Setting metakey `Metakey::LastModified` ensures the field is always queryable for any object store type.
<details>
</details>

fix(storage): set missing opendal metakey

---

src/ctl/src/lib.rs

Issue: #21635
This is part of the ongoing effort to enable Clippy lints for potential stack overflows (#21635) across the codebase. Here, the focus is on the `risingwave_ctl` crate.
This PR refactors `ctl/src/lib.rs` to address a Clippy `large_stack_frames` warning by decomposing the monolithic `start_impl` async function into several smaller, purpose-scoped async helpers.
**Key changes and rationale:**
- Smaller async helpers: Each command group is now handled by its own `#[inline(never)]` async function. This prevents a single oversized state machine from …

chore(ctl): add clippy warning on large future size and stack frame

---

src/stream/src/executor/aggregate/agg_group.rs
src/stream/src/executor/aggregate/hash_agg.rs
src/stream/src/executor/aggregate/simple_agg.rs

There could also be a call of `AggGroup::get_outputs` during `AggGroup::create`. We should also include this in our statistics.
<details>
</details>

fix(streaming): also record agg state cache stats on `AggGroup::create` for `HashAgg`

---

Cargo.lock
Cargo.toml

chore:  update package version in Cargo.toml

---

ci/scripts/multi-arch-docker.sh

Fix PUSH_DOCKERHUB env missing error
`./ci/scripts/multi-arch-docker.sh: line 124: PUSH_DOCKERHUB: unbound variable`
https://buildkite.com/risingwavelabs/docker/builds/17682#_  
This bug was introduced by https://github.com/risingwavelabs/risingwave/pull/23028. It will be triggered when `IMAGE_TAG` used without `PUSH_DOCKERHUB`.
<br class="Apple-interchange-newline">
<details>
</details>

fix(ci): add default false for PUSH_DOCKERHUB env

---

Cargo.lock
src/risedevtool/Cargo.toml

Fix #15902.
`yaml-rust` was not maintained long ago. `yaml-rust2` seems to keep a (almost-)same set of interfaces while providing better performance. See more details here: https://github.com/Ethiraric/yaml-rust2/blob/master/documents/2024-03-15-FirstRelease.md
<details>
</details>

chore(risedev): replace unmaintained `yaml-rust` with `yaml-rust2`

---

src/stream/src/common/table/state_table.rs
src/stream/src/executor/dedup/append_only_dedup.rs

Extract the logic of `StateTableRowStore` from `StateTable`, which serves a similar functionality as a `BTreeMap<TableKey<Bytes>, OwnedRow>`, and provides method to read (`get` and `iter`) over serialized key (or key range) and returns `OwnedRow`, and write (`insert`, `delete`, `update`) on `(TableKey<Bytes>, OwnedRow)`.
With this `StateTableRowStore`, in future PR we can optionally preload at initialization and store all rows in memory, and always read and write on the in memory rows to avoid latency spike caused on IO when reading from state store.
Besides, …

refactor(state-table): extract logic of row store in state table

---

.github/workflows/build-docker-image.yml

1. It's confusing for the user. I have to double check the workflow definition itself, when the commit was mismatched with the branch itself, so I don't accidentally patch the `main` branch.
2. The original usecase is during workflow development, we want to test the workflow itself. Then we want to test it against a different branch. But this doesn't make sense to me, because in most cases, we are just trying to see if the workflow works. So we can just test it within the same branch.
So if it is not needed for the original usecase, it's just maintenance …

chore(ci): remove extra branch configuration

---

src/meta/src/controller/catalog/util.rs
src/meta/src/controller/fragment.rs
src/meta/src/controller/streaming_job.rs

Instead of filtering after getting the result.
<details>
</details>

refactor(meta): Use bitwise op to filter fragment type mask

---

Cargo.lock
Cargo.toml

Bump foyer version v0.19.2 for bugfixs
<details>
</details>

fix(foyer): bump foyer version v0.19.2 for bugfixs

---

e2e_test/iceberg/test_case/pure_slt/iceberg_copy_on_write.slt
e2e_test/iceberg/test_case/pure_slt/iceberg_engine.slt

- As titled.
<details>
</details>

feat(iceberg): add e2e test for iceberg copy on write mode

---

ci/workflows/main-cron.yml

Fixes timeout of single-node test in main-cron: https://buildkite.com/risingwavelabs/main-cron/builds/6742/steps/canvas?sid=01990b28-85ae-4342-902d-7c5c554fd1d4
<details>
</details>

chore: increase single-node test timeout

---

docker/docker-compose-with-lakekeeper.yml

- Add a docker compose with the lakekeeper component. A default warehouse would be created in the lakekeeper bootstrap step with minio as the storage.
- Doc https://www.notion.so/risingwave-labs/RisingWave-with-a-hosted-rest-catalog-262f0d69cb76807bbed5ebea7b33a450?source=copy_link
<details>
- Here is the doc of how to use this docker compose. https://www.notion.so/risingwave-labs/RisingWave-with-a-hosted-rest-catalog-262f0d69cb76807bbed5ebea7b33a450?source=copy_link
</details>

feat(iceberg): add docker compose with lakekeeper

---

ci/docker-compose.yml
e2e_test/source_inline/kafka/add_partition.slt
e2e_test/source_inline/kafka/alter/alter_connector_props_non_shared_source.slt
src/meta/src/controller/streaming_job.rs

resolve https://github.com/risingwavelabs/risingwave/issues/23077
<details>
</details>

fix: ALTER SOURCE CONNECTOR should work for non-shared source (#23055)

---

e2e_test/sink/sink_into_table/alter_column.slt
src/meta/src/rpc/ddl_controller.rs

Previously, we directly used the table's `distribution_key` as `dist_key` in new dispatcher, while the sink's columns were fixed. This resulted in:
- If the table didn't have a primary key, the last column `row_id` would be used as the `dist_key`.
- Adding columns to the table would cause the `row_id` to be moved backwards.
- However, the sink's output didn't have the new `row_id` position, so it would go out of bounds when `Dispatcher` executes.
The new added e2e_test will fail in previous version.
<details>
</details>

fix(sink): Build dist_key in sink-into-table dispatcher

---

src/meta/src/barrier/context/context_impl.rs
src/meta/src/controller/streaming_job.rs
src/meta/src/stream/stream_manager.rs

Fixes #23071 .
<details>
</details>

fix: cache cancel table list for compactor notification

---

src/frontend/src/optimizer/plan_node/generic/table_scan.rs
src/frontend/src/optimizer/plan_node/logical_join.rs
src/frontend/src/optimizer/plan_node/logical_scan.rs
src/frontend/src/optimizer/plan_node/stream_table_scan.rs
src/frontend/src/optimizer/rule/index_delta_join_rule.rs

Resolved #23080 .
<details>
</details>

fix: ban cross database stream query with upstream only

---

src/meta/src/barrier/cdc_progress.rs

Use `FragmentTypeMask::intersects` to filter out fragments.
<details>
</details>

refactor(meta): match fragment type mask correctly

---

Cargo.lock
Cargo.toml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml

update version to v2.6.0-rc.1
<details>
</details>

chore: update version to v2.6.0-rc.1

---

src/common/src/config.rs
src/stream/src/executor/now.rs
src/stream/src/from_proto/now.rs

cherry-pick: feat: decouple streaming now timestamp and epoch (#22487)

---

src/connector/Cargo.toml
src/connector/benches/protobuf_bench.rs

close https://github.com/risingwavelabs/risingwave/issues/20746
<details>
</details>

perf: protobuf parser perf bench

---

e2e_test/source_legacy/cdc/cdc.share_stream.slt
src/common/src/catalog/mod.rs
src/frontend/src/stream_fragmenter/mod.rs
src/meta/src/controller/catalog/drop_op.rs
src/meta/src/controller/fragment.rs
src/meta/src/controller/utils.rs
src/meta/src/rpc/ddl_controller.rs

Part 2 in https://github.com/risingwavelabs/risingwave/pull/23017#issuecomment-3265742446
- Add `FragmentTypeFlag::UpstreamSinkUnion`.
- Forbid creating and dropping sinks into table that has not been migrated.
Test locally: Table created in release-2.6 cannot perform new sink ddl operations. But old sinks are still valid.
<details>
</details>

fix(sink): Forbid non-migrated tables from sink DDL operations

---

src/meta/src/barrier/command.rs

Introduced by #22920.
<details>
</details>

fix(meta): Fix actors-to-build in snapshot-backfill

---

e2e_test/source_inline/kafka/protobuf/oneof_empty_message.slt

Such use case is the motivation for #23047 and #23099. Since they are implemented and #17264 is addressed, we can add an e2e test for it.
<details>
</details>

test(source): add an e2e test for empty protobuf message

---

src/meta/src/manager/iceberg_compaction.rs

- As titled.
<details>
</details>

fix(iceberg): fix iceberg compact get sink error

---

src/stream/src/executor/mview/materialize.rs

as title
following https://github.com/risingwavelabs/risingwave/pull/23024
<details>
</details>

refactor: use state machine for `MaterializeExecutor` 

---

Cargo.lock
Cargo.toml

https://github.com/foyer-rs/foyer/issues/1122
https://github.com/foyer-rs/foyer/pull/1123
<details>
</details>

fix(foyer): fix OOM caused by read after refill

---

src/common/src/array/arrow/arrow_iceberg.rs
src/common/src/array/arrow/arrow_impl.rs
src/common/src/array/list_array.rs
src/common/src/array/map_array.rs
src/common/src/array/mod.rs
src/common/src/array/vector_array.rs
src/common/src/types/map_type.rs
src/common/src/types/mod.rs
src/common/src/types/to_binary.rs
src/common/src/util/value_encoding/column_aware_row_encoding.rs
src/common/src/util/value_encoding/mod.rs
src/connector/src/sink/encoder/avro.rs
src/expr/core/src/expr/expr_some_all.rs
src/expr/impl/src/scalar/array.rs
src/expr/impl/src/scalar/array_concat.rs
src/expr/impl/src/scalar/array_distinct.rs
src/expr/impl/src/scalar/array_flatten.rs
src/expr/impl/src/scalar/array_range_access.rs
src/expr/impl/src/scalar/array_remove.rs
src/expr/impl/src/scalar/array_replace.rs
src/expr/impl/src/scalar/array_sort.rs
src/expr/impl/src/scalar/cast.rs
src/expr/impl/src/scalar/jsonb_build.rs
src/expr/impl/src/scalar/to_jsonb.rs
src/expr/impl/src/scalar/trim_array.rs
src/expr/impl/src/table_function/pg_expandarray.rs
src/expr/macro/src/gen.rs
src/frontend/src/binder/expr/function/builtin_scalar.rs

Follow-up of #23237, addressing some TODOs.
- Rename `as_list_elem_type`, `into_list_elem_type` to `as_list_elem`, `into_list_elem`
- Refactor some functions to take `ListType` instead of ambiguous `DataType` (not sure it's referring to the list or the element)
- For other functions, explicitly name the parameter as `elem_type` to avoid confusion
<details>
</details>

refactor(types): follow-ups of using `ListType` for `DataType::List`

---

ci/scripts/e2e-test-serial.sh
ci/scripts/slow-e2e-test.sh
ci/workflows/main-cron.yml
ci/workflows/pull-request.yml
e2e_test/dml/rate_limit_pause_resume.slt

There are frequent timeouts in recent main-crons. Though it's not relevant to backfill, moving backfill tests from `e2e-test-serial.sh` to `slow-e2e-test.sh` helps balance the run time.
<details>
</details>

fix(ci): move backfill test from `e2e-test-serial.sh` to `slow-e2e-test.sh`

---

Cargo.lock
ci/workflows/pull-request.yml
src/connector/Cargo.toml

Resolves #23251
<details>
</details>

cherry-pick: feat(sink): support redis sink tls (#23223)

---

src/common/src/array/list_array.rs
src/common/src/array/map_array.rs
src/common/src/types/scalar_impl.rs
src/expr/impl/src/scalar/array.rs
src/expr/impl/src/scalar/cast.rs
src/stream/src/executor/dispatch/output_mapping.rs

Avoid duplicating methods with the same functionality, particularly those that are less explicit like `Into`. Also add some more docs & comments.
<details>
</details>

refactor(types): more explicit methods on `ListValue` and `ListRef`

---

src/stream/src/from_proto/sync_log_store.rs

fix(streaming): fix sync log store fragment_id used in metrics

---

src/common/src/util/row_id.rs

https://github.com/risingwavelabs/risingwave/pull/23240#issuecomment-3334907145
<details>
</details>

fix(stream): fix changlog panic 

---

src/utils/pgwire/src/pg_protocol.rs

- Add a new env `RW_SSL_ENFORCE` (default is false) to control the ssl connection handling behavior.
This pull request enhances the PostgreSQL wire protocol implementation by adding support for enforcing SSL-only connections. It introduces new configuration options to control SSL enforcement, tracks SSL usage per connection, and updates the connection handling logic to reject non-SSL clients when required.
* On startup, if SSL enforcement is enabled but the connection is not using SSL, the server now rejects the connection with an appropriate error message.
* …

feat(frontend): support enforce ssl connection

---

src/connector/codec/src/decoder/mod.rs
src/connector/src/parser/parquet_parser.rs
src/connector/src/source/iceberg/parquet_file_handler.rs
src/stream/src/executor/source/fs_fetch_executor.rs

Should update offset in state table to ensure exactly once, and add error log.
<details>
</details>

fix(file_source): update state table offset and add more error log

---

src/meta/src/controller/catalog/mod.rs
src/meta/src/manager/notification.rs

Try to resolve failure in main-cron tests. https://buildkite.com/risingwavelabs/main-cron/builds/7061/steps/canvas?sid=01998be7-d435-4120-9d1a-a0b0a24fdf66
<details>
</details>

fix: don't notify empty info during bootstrap recovery

---

Cargo.lock
Cargo.toml
ci/docker-compose.yml
docker/docker-compose-distributed.yml
docker/docker-compose-with-azblob.yml
docker/docker-compose-with-gcs.yml
docker/docker-compose-with-local-fs.yml
docker/docker-compose-with-obs.yml
docker/docker-compose-with-oss.yml
docker/docker-compose-with-s3.yml
docker/docker-compose-with-sqlite.yml
docker/docker-compose.yml
integration_tests/iceberg-sink/Dockerfile
integration_tests/kafka-cdc-sink/Makefile.toml
integration_tests/nats/docker-compose.yml

release v2.5.2
<details>
</details>

chore: update version to v2.5.2

---

Cargo.lock
Cargo.toml

chore: patch rdkafka-sys and upgrade to `v4.9.0+2.10.0`

---

Cargo.lock
Cargo.toml

chore: patch rdkafka-sys and upgrade to v4.9.0+2.10.0 (#23363)
