proto/meta.proto, src/common/common_service/src/observer_manager.rs, src/compute/src/compute_observer/observer_manager.rs, src/compute/src/server.rs, src/ctl/src/cmd_impl/hummock/observer.rs, src/ctl/src/common/hummock_service.rs, src/ctl/src/common/meta_service.rs, src/frontend/src/observer/observer_manager.rs, src/frontend/src/session.rs, src/meta/src/manager/notification.rs, src/meta/src/rpc/service/notification_service.rs, src/rpc_client/src/meta_client.rs, src/storage/compactor/src/compactor_observer/observer_manager.rs, src/storage/compactor/src/server.rs, src/storage/hummock_test/src/test_utils.rs
In this PR, we do some simple refactor on the observer manager. Major changes are as followed:
- Combine the `new` and `register` of `MetaClient` into `register_new`. Our current usage of `new` and `register` are always associated together. Therefore, we can combine them together, and the returned client is always properly initialized.
- Introduce a separated `SubscribeType` enum proto to decouple worker type and the subscribed item. Currently both `ComputeNode` and `RiseCtl` only care about the changes of hummock, and for each of them we introduce a new `ObserverNode`, which is unnecessary. In future PR, we can combine the …
=> refactor(notification): introduce subscribe type and avoid passing addr and worker type

Cargo.lock, src/meta/src/hummock/manager/mod.rs, src/storage/hummock_sdk/Cargo.toml, src/storage/hummock_sdk/src/filter_key_extractor.rs, src/storage/hummock_sdk/src/lib.rs
as title 
- use timeout for notify to replace the unbound wait for debug
- https://github.com/risingwavelabs/risingwave/issues/5437
=> feat(storage): use timeout for filter_extractor acquire

e2e_test/batch/catalog/pg_class.slt.part, src/frontend/src/catalog/pg_catalog/mod.rs, src/frontend/src/catalog/pg_catalog/pg_index.rs, src/frontend/src/catalog/schema_catalog.rs, src/stream/src/task/stream_manager.rs
As title, hidden indexes for `\d` and `\dm` and support `\di`.
```sql
dev=> create table t1 (v1 int, v2 int, v3 int);
CREATE_TABLE
dev=> create index idx2 on t1 (v1);
CREATE_INDEX
dev=> create materialized view mv1 as select * from t1;
CREATE_MATERIALIZED_VIEW
dev=> \d
List of relations
Schema | Name |       Type        | Owner
--------+------+-------------------+-------
public | mv1  | materialized view | root
public | t1   | table             | root
(2 rows)
dev=> \dm
List of relations
Schema | Name |       Type        | Owner
--------+------+-------------------+-------
public | mv1  | materialized view | root
(1 row) …
```
=> feat: add pg_catalog.pg_index and support \di

src/meta/src/hummock/manager/mod.rs
=> chore(meta): remove log caused by TrivialMove

src/frontend/planner_test/tests/testdata/agg.yaml, src/frontend/planner_test/tests/testdata/append_only.yaml, src/frontend/planner_test/tests/testdata/basic_query.yaml, src/frontend/planner_test/tests/testdata/column_pruning.yaml, src/frontend/planner_test/tests/testdata/common_table_expressions.yaml, src/frontend/planner_test/tests/testdata/distribution_derive.yaml, src/frontend/planner_test/tests/testdata/expr.yaml, src/frontend/planner_test/tests/testdata/index.yaml, src/frontend/planner_test/tests/testdata/join.yaml, src/frontend/planner_test/tests/testdata/mv_on_mv.yaml, src/frontend/planner_test/tests/testdata/nexmark.yaml, src/frontend/planner_test/tests/testdata/order_by.yaml, src/frontend/planner_test/tests/testdata/over_window_function.yaml, src/frontend/planner_test/tests/testdata/pk_derive.yaml, src/frontend/planner_test/tests/testdata/project_set.yaml, src/frontend/planner_test/tests/testdata/stream_dist_agg.yaml, src/frontend/planner_test/tests/testdata/struct_query.yaml, src/frontend/planner_test/tests/testdata/subquery_expr.yaml, src/frontend/planner_test/tests/testdata/time_window.yaml, src/frontend/planner_test/tests/testdata/tpch.yaml, src/frontend/src/handler/create_index.rs, src/frontend/src/handler/create_mv.rs, src/frontend/src/handler/create_sink.rs, src/frontend/src/optimizer/max_one_row_visitor.rs, src/frontend/src/optimizer/mod.rs, src/frontend/src/optimizer/plan_node/stream_index_scan.rs, src/frontend/src/optimizer/plan_node/stream_table_scan.rs, src/frontend/src/optimizer/rule/max_one_row_elim.rs, src/frontend/src/session.rs
As title. Something will change in this step (like stream keys), and the developer may need the output of this step to debug the final `to_stream()` step.
=> feat(planner): trace "logical rewrite for stream" when explain & minor fixes for scalar subquery

src/common/common_service/src/metrics_manager.rs, src/compute/src/server.rs, src/frontend/src/session.rs, src/meta/src/rpc/server.rs, src/storage/compactor/src/server.rs
`prometheus::Registry` is clonable, so there's no need to wrap it with an `Arc`. …
=> chore: remove Arc from Registry

ci/scripts/e2e-source-test.sh, e2e_test/source/kafka.slt, scripts/source/prepare_ci_kafka.sh, scripts/source/test_data/json_c.1, src/common/src/catalog/column.rs, src/source/src/manager.rs, src/source/src/parser/avro_parser.rs, src/source/src/parser/common.rs, src/source/src/parser/debezium/json.rs, src/source/src/parser/json_parser.rs, src/source/src/parser/protobuf_parser.rs
- Reduce overhead of conversions bewteen ColumnDescs
- Support parsing list value in json parser
- move installation of kafkacat to `ci/scripts/e2e-source-test.sh` so that developers could still use `scripts/source/prepare_ci_kafka.sh` to load data locally.
~- [] I have written necessary rustdoc comments~
Support parsing list value in json parser, user can create a materialized source as follow:
```SQL
CREATE materialized SOURCE js(
id int,
code string, 
timestamp bigint, 
xfas struct<device_model_id int, device_make_id int, ip …
```
=> feat(source): improve impl of parsing list

src/stream/src/executor/aggregation/mod.rs
With the newly implemented _result table_, `ROW_COUNT_COLUMN` is actually not required to be 0, so removing the assertion to clean the code.
=> refactor(stream,agg): remove row count column assert

src/frontend/src/optimizer/plan_node/generic.rs, src/frontend/src/optimizer/plan_node/logical_agg.rs, src/frontend/src/optimizer/plan_node/logical_expand.rs, src/frontend/src/optimizer/plan_node/logical_hop_window.rs, src/frontend/src/optimizer/plan_node/logical_multi_join.rs, src/frontend/src/optimizer/plan_node/logical_project.rs, src/frontend/src/optimizer/plan_node/mod.rs
+ Introduced a `trait` that in the future, `PlanRef` will be split down into three variants and this trait will be shared by them.
+ Use the trait to improve some of the existing code.
#5630, #5699, #5700, #5765, #5766
=> refactor(plan_node): Introduce `GenericPlanRef`

Cargo.lock, src/frontend/Cargo.toml, src/frontend/src/handler/mod.rs, src/frontend/src/handler/query.rs, src/frontend/src/handler/util.rs, src/frontend/src/scheduler/distributed/query_manager.rs, src/frontend/src/scheduler/local.rs
Our system returns `DataChunk` while pgwire expects `RowSet`. The conversion is being done by `to_pg_row`, which is currently invoked as part of `LocalQueryStream` or `DistributedQueryStream` in the scheduler mod.
This PR lifts the invocation of `to_pg_row` from these streams to an adapter stream created in the handler mod. This allows us to pass more formatting control parameters (TEXT/BINARY bool, DataType, DateStyle, TimeZone, floating number style) more easily in the future.
The immediate need is to pass `column_types` to `to_pg_rows` to enhance our support of the `timestamp with time zone` type.
Note that after this …
=> refactor(handler): extract RowSet formatting from scheduler to handler

Makefile.toml
This PR adds a `risedev` task for running scale tests locally.
```
./risedev sscale-test --cargo-profile ci-sim
```
It's normal that there's some slight error in the results and tests fail with M1 Mac, due to #5487 (discussion at https://risingwave-labs.slack.com/archives/C03A2PSS8KU/p1664523047458579).
I will refine the developer doc after the test framework is mostly finished.
- #5657
=> chore(test): add task for running scale tests in `risedev`

src/frontend/planner_test/tests/testdata/array.yaml, src/frontend/planner_test/tests/testdata/expr.yaml, src/frontend/src/expr/type_inference/func.rs
Fixes #5408, and also disallows comparison between arrays of different types.
When comparing an `unknown` literal (e.g. `null` or `'{1}'`) with an array, it should be casted to the same `DataType::List`. As our general inference rule only handles `DataTypeName`, this requires one more arm in the special handling logic.
=> fix(binder): improve array cmp type inference

src/storage/hummock_test/src/hummock_read_version_tests.rs, src/storage/hummock_test/src/hummock_storage_tests.rs, src/storage/hummock_test/src/local_version_manager_tests.rs, src/storage/hummock_test/src/test_utils.rs, src/storage/src/hummock/event_handler/hummock_event_handler.rs, src/storage/src/hummock/event_handler/mod.rs, src/storage/src/hummock/local_version/local_version_manager.rs, src/storage/src/hummock/mod.rs, src/storage/src/hummock/shared_buffer/shared_buffer_batch.rs, src/storage/src/hummock/store/memtable.rs, src/storage/src/hummock/store/state_store.rs, src/storage/src/hummock/store/version.rs
as title
- remove `Uploader` directly dependency of `StorageCore`
- shared `ReadVersion` between `StorageCore` and `EventHandler`
- https://github.com/risingwavelabs/risingwave/issues/5621
=> refactor(storage): remove uploader directly dependency of new state store

src/meta/src/stream/source_manager.rs
as title, one kafka broker down should not lead to meta recovery failure.
resolve #5809
=> fix: not force tick in meta recovery process

src/source/src/parser/debezium/json.rs
as title, suggest user alter table replica to FULL
resolve #5543
=> chore: refine error message for null before field in debezium parser

src/frontend/src/scheduler/distributed/query.rs, src/frontend/src/scheduler/distributed/stage.rs
When fixing #5724 (which is caused by #5787) , we find that a receiver in `QueryRunner` waits infinitely in a `while` loop. To be more specific, it waits for messages coming from the senders, while the senders have finished sending all messages, but fail to be dropped because of some cyclic reference issues. View #5816 for more details.
Align lifetime of the sender to that of `StageRunner` instead of `StageExecution`, so it will be dropped immediately when `StageRunner` ends its job. When all senders are dropped, the channel will be closed then, and the receiver will be dropped accordingly.
Fixes #5816
=> fix(batch): fix dangling channel and prevent receiver from infinite waiting

src/source/src/parser/pb_parser.rs
- delete a redundant log output
=> refactor(source): delete a redundant log output

src/common/src/util/value_encoding/mod.rs
- migrate from `from_proto_bytes` to `value_encoding` while encoding to/decoding from storage
- fix the bug that default values in struct and list are converted to NULLs caused by  `from_proto_bytes`
- in addition, serialization of value encoding for List and Struct are faster than key encoding now because the overhead of protobuf encoding is eliminated, but deserialization is still slower(though much faster than before).
#4521 
#4672 
#5713
=> refactor: migrate from `from_proto_bytes` to `value_encoding`

src/common/src/util/match_util.rs, src/common/src/util/mod.rs, src/stream/src/executor/aggregation/agg_group.rs, src/stream/src/executor/aggregation/agg_state.rs, src/stream/src/executor/aggregation/minput.rs, src/stream/src/executor/aggregation/mod.rs, src/stream/src/executor/global_simple_agg.rs, src/stream/src/executor/hash_agg.rs, src/stream/src/executor/test_utils.rs, src/stream/src/from_proto/agg_common.rs, src/stream/src/from_proto/global_simple_agg.rs, src/stream/src/from_proto/hash_agg.rs
- Hide `ManagedTableState` behind a new struct called `MaterializedInputState`, so that `AggState` need not to care about the detail.
- Introduce `enum AggStateStorage` to represent different storage type for agg states, replacing the old `Option<AggStateTable>`. This matches the backend implementation with what frontend infers.
#5806
=> refactor(stream,agg): introduce `enum AggStateStorage` to represent different storage type for agg states

src/meta/src/hummock/compaction_scheduler.rs, src/meta/src/hummock/manager/mod.rs, src/meta/src/hummock/manager/tests.rs, src/meta/src/hummock/test_utils.rs, src/meta/src/hummock/vacuum.rs
lazy init `HummockVersion` and `CompactStatus` in `HummockManager` …
=> refactor(hummock manager): lazy init `HummockVersion` and `CompactStatus`

Cargo.lock, src/common/src/types/interval.rs, src/common/src/types/mod.rs, src/expr/Cargo.toml, src/expr/src/vector_op/cast.rs, src/frontend/src/handler/util.rs, src/utils/pgwire/Cargo.toml, src/utils/pgwire/src/pg_extended.rs, src/utils/pgwire/src/pg_field_descriptor.rs
- support binary format param of timestamptz and interval 
- support binary format result of timestamptz 
#3676
=> feat(pgwire):support binary format param of timestampz and interval type 

Cargo.lock, src/common/src/util/value_encoding/mod.rs, src/ctl/Cargo.toml, src/ctl/src/cmd_impl/hummock/sst_dump.rs, src/storage/src/row_serde/row_serde_util.rs
Fix sst_dump. It originally uses deprecated cell_table interface and doesn't output correct info.
Example output:
```
full key: [74, 00, 00, 05, 37, 59, 00, 80, 00, 00, 00, 00, 00, 09, 03, 00, 80, 00, 00, 00, 00, 00, 09, 03, 00, 80, 00, 00, 04, ff, f4, 9a, fa, b3, 45, ff, ff]
full value: [00, 01, 03, 09, 00, 00, 00, 00, 00, 00, 01, 06, 00, 00, 00, 01, 04, 00, 00, 00]
user key: [74, 00, 00, 05, 37, 59, 00, 80, 00, 00, 00, 00, 00, 09, 03, 00, 80, 00, 00, 00, 00, 00, 09, 03, 00, 80, 00, 00, 04]
user value: [01, 03, 09, 00, 00, 00, 00, 00, 00, 01, 06, 00, 00, 00, 01, 04, 00, 00, 00]
epoch: 3207298180317184
type: Put
table: 1335 …
```
=> fix(ctl): fix sst_dump

src/sqlparser/src/ast/statement.rs, src/sqlparser/tests/testdata/create.yaml
As the title.
Error message of PostgreSQL:
```sql
postgres=# create user tmp with createrole createrole;
ERROR:  conflicting or redundant options
LINE 1: create user tmp with createrole createrole;
^
postgres=# create user tmp with createrole nocreaterole;
ERROR:  conflicting or redundant options
LINE 1: create user tmp with createrole nocreaterole;
^
```
```sql
postgres=# alter user tmp with createdb createdb;
ERROR:  conflicting or redundant options
postgres=# alter user tmp with createdb nocreatedb;
ERROR:  conflicting or redundant options
```
close #5904
=> feat(frontend): throw error when `UserOptions` has multiple conflicting or redundant options

src/batch/src/task/task_execution.rs, src/frontend/src/scheduler/distributed/stage.rs
Handle some status like Unsepcified, Aborted. …
=> refactor: tweak the task status handler, handle potential status change

src/utils/pgwire/src/error.rs, src/utils/pgwire/src/pg_extended.rs, src/utils/pgwire/src/pg_protocol.rs
Try to simplify the error handle in pgwire crate. This is just one step.
* Reduce unnecessary variant like SslError(IoError).
* Use PsqlError::Internal(anyhow) to represent some Error variant …
=> refactor: refine error handle and error msg in pgwire

src/storage/compaction_test/src/server.rs, src/storage/hummock_test/src/hummock_storage_tests.rs, src/storage/hummock_test/src/local_version_manager_tests.rs, src/storage/hummock_test/src/snapshot_tests.rs, src/storage/src/hummock/event_handler/hummock_event_handler.rs, src/storage/src/hummock/local_version/local_version_manager.rs, src/storage/src/hummock/mod.rs, src/storage/src/hummock/state_store.rs, src/storage/src/hummock/store/mod.rs, src/storage/src/hummock/store/state_store.rs, src/storage/src/hummock/test_utils.rs, src/storage/src/store.rs
SharedBuffer Redesign Stage1: introduce the new storage struct to replace the original implementation of hummock statestore.
For simplicity of implementation, stage1 is aligned with the old implementation, using only one instance to provide services for all executor, we will split the instance to reduce competition in the future.
At present, we still lack some logic related to upload, but it does not affect the correctness of reading and writing
- introcude new storage core
- replace the original implementation of hummock statestore in …
=> refactor(storage): introduce new storage core for basic interface implementation

e2e_test/batch/types/timestamptz_utc.slt.part, src/common/src/types/mod.rs
=> fix: `from_proto_bytes` support `timestamp with time zone`

src/batch/benches/filter.rs, src/batch/benches/hash_join.rs, src/batch/benches/nested_loop_join.rs, src/batch/src/executor/filter.rs, src/batch/src/executor/row_seq_scan.rs, src/common/src/array/list_array.rs, src/common/src/array/struct_array.rs, src/common/src/hash/key.rs, src/common/src/types/mod.rs, src/common/src/util/scan_range.rs, src/common/src/util/value_encoding/mod.rs, src/expr/src/expr/build_expr_from_prost.rs, src/expr/src/expr/expr_field.rs, src/expr/src/expr/expr_in.rs, src/expr/src/expr/expr_literal.rs, src/expr/src/expr/expr_regexp.rs, src/expr/src/expr/test_utils.rs, src/expr/src/table_function/regexp_matches.rs, src/frontend/src/expr/literal.rs, src/utils/memcomparable/src/de.rs
- migrate all `from_to_bytes` to `value_encoding`
#4672
=> refactor: migrate all from_to_bytes to value_encoding

src/frontend/src/handler/query.rs, src/frontend/src/scheduler/distributed/query.rs, src/frontend/src/scheduler/hummock_snapshot_manager.rs, src/frontend/src/scheduler/local.rs
Prior to this PR, batch query in local execution mode will release the hummock snapshot before query execution, which can cause the read epoch to be expired when reading from state store during query execution.
This PR fixes the issue by releasing the hummock snapshot after query execution is completed. Note the this is different from what we did for batch query in distributed execution mode, in which the hummock snapshot is released immediately after all scan executors are scheduled before the completion of query execution. I think this is acceptable since batch query in local execution mode is supposed to be fast and …
=> fix: fix hummock snapshot release in batch local execution

src/stream/src/executor/aggregation/agg_impl/approx_count_distinct.rs, src/stream/src/executor/aggregation/agg_impl/approx_distinct_append.rs, src/stream/src/executor/aggregation/agg_impl/approx_distinct_utils.rs, src/stream/src/executor/aggregation/agg_impl/mod.rs
add in-memory append-only approx_count_distinct (#5871 )
We haven't designed a state for it.
Please create a release …
=> feat(approx distinct): add in-memory append-only approx_count_distinct

e2e_test/batch/types/decimal.slt.part, e2e_test/streaming/basic.slt, src/common/src/types/decimal.rs
As title:
* input should accept `nan` / `inf` / `infinity` case-insensitively.
* output should be `Infinity` and `-Infinity`.
Fixes #3817
=> fix(expr): align input/output of decimal special value with PostgreSQL

src/meta/src/hummock/compaction_scheduler.rs, src/meta/src/hummock/manager/mod.rs, src/meta/src/hummock/manager/tests.rs
Before this PR we will observe several misleading warning in meta log. This PR removes unnecessary warning as below
- It's fine for get_compact_task_impl to return None, if its compaction group is created but not sync_group via commit_epoch, which mean no data for this group is written yet.
- It's fine for CN to use an inaccurate table_id->compaction_group mapping when commit_epoch, because commit_epoch will correct it.
If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel …
=> chore(log): remove unnecessary warning

src/storage/hummock_test/src/hummock_storage_tests.rs, src/storage/hummock_test/src/local_version_manager_tests.rs, src/storage/hummock_test/src/test_utils.rs, src/storage/src/hummock/event_handler/hummock_event_handler.rs, src/storage/src/hummock/local_version/local_version_manager.rs, src/storage/src/hummock/mod.rs, src/storage/src/hummock/state_store.rs
related to https://github.com/risingwavelabs/risingwave/pull/5902.
notify max_committed_epoch instead of verison_id to reduce read_lock acquisition in try_wait_epoch
- reduce read_lock acquisition in `try_wait_epoch` by reducing access to read_version
- ~rename `notify_version_id_to_worker_context` to `notify_max_committed_epoch`~
- add `Arc<version_update_tx>` and `Arc<seal_epoch>` to reduce dependence of `local_version_manager`, so we can move function `try_wait_epoch` from `local_version_manager` to `state_store`. And notify version …
=> feat(storage): reduce read_lock acquisition in try_wait_epoch

Cargo.lock, src/common/src/types/interval.rs
Because IntervalUnit only has the precision of milliseconds, when we encounter a value less than 0.001 milliseconds we will return an error. But I forget to treat 0 seconds in particular, so `select '04:00:00'::interval` will fail.
This PR fixes it.
=> fix: an interval bug caused by missing check 

src/stream/src/common/builder.rs, src/stream/src/executor/dynamic_filter.rs, src/stream/src/executor/hash_join.rs, src/stream/src/executor/lookup/impl_.rs
Apply `output_indices` while building `StreamChunk`, not after building it.
#3588
=> refactor(streaming): make StreamChunkBuilder output index aware

src/storage/hummock_test/src/hummock_storage_tests.rs, src/storage/hummock_test/src/local_version_manager_tests.rs, src/storage/hummock_test/src/test_utils.rs, src/storage/src/hummock/event_handler/hummock_event_handler.rs, src/storage/src/hummock/local_version/local_version_manager.rs, src/storage/src/hummock/mod.rs, src/storage/src/hummock/utils.rs
Currently, the logic of applying version delta and update the hummock version is in local version manager. However, local version manager will be deprecated soon after we support a new uploader. In this PR, we move the logic of applying version delta and update the hummock version to hummock event handler. The logic of calling conflict detector and removing sstable id manager watermark is moved by the way.
=> refactor(storage): apply version delta in event handler

src/frontend/src/optimizer/plan_node/mod.rs, src/frontend/src/optimizer/plan_node/stream.rs
This is the initial rewrite of the stream syntax tree.
#5630, #5699, #5700, #5765, #5766, #5797
=> refactor(plan_node): introduce a new stream node syntax tree

src/common/src/session_config/mod.rs, src/common/src/session_config/transaction_isolation_level.rs, src/frontend/src/handler/variable.rs
This is a pre-req of many sql driver: require the support of `show transaction isolationl level`. 
After this pr, people should be able to run the demo.py in sqlalchemy-risingwave. …
=> feat: mock show transaction isolation level

src/stream/src/executor/hash_agg.rs
commit dirty state only among `agg_group`s
in table state, commit `agg_group` whose key in `group_change_set` among `agg_group`s in `flush_data` in hash agg
* SQL commands, functions, and …
=> feat(hash agg): commit dirty state only

.licenserc.yaml, src/frontend/src/optimizer/rule/reorder_multijoin.rs
As title.
Fix https://github.com/risingwavelabs/risingwave/actions/runs/3336563819/jobs/5521867475
=> fix: license header

src/frontend/src/scheduler/plan_fragmenter.rs, src/stream/src/executor/source/reader.rs, src/stream/src/executor/source/source_executor.rs
For this case, we randomly pick a parallel unit to schedule.
- When reading with checkpoint, it's okay and necessary to have some remote accesses.
- If reading with the barrier (in the future), as the consistency is not preserved, it's okay to randomly pick one worker to schedule the scanning. 😅
```
dev=> select * from rw_table(1006);
partition_id |                                offset                                
--------------+----------------------------------------------------------------------
6-0          |                                                                     +
| …
```
=> fix(frontend): internal table scan of source operator

dashboard/proto/gen/meta.ts, proto/meta.proto, src/ctl/src/cmd_impl/meta/cluster_info.rs, src/meta/src/rpc/service/scale_service.rs
Update get_cluster_info interface, following this [PR](https://github.com/risingwavelabs/risingwave/pull/5974)
Orchestrator relies on the `properties` field in `Source` for the brokers' location.
=> chore(meta): update get_cluster_info interface

src/source/src/parser/avro_parser.rs, src/source/src/parser/pb_parser.rs
- allow importing avro schema from https
- refactor some code of avro/pb parser to remove redundant match clause
```sql
create materialized source s with (
connector = 'kafka',
topic = 'avro_c_bin',
properties.bootstrap.server = '127.0.0.1:29092',
scan.startup.mode = 'earliest')
row format avro message 'user'
row schema location 'https://xxx.com/complex-schema.avsc';
```
#6114
=> feat(source): allow importing avro schema from https & refactor code

src/frontend/src/optimizer/plan_node/generic.rs, src/frontend/src/optimizer/plan_node/logical_agg.rs, src/frontend/src/optimizer/plan_node/mod.rs, src/frontend/src/optimizer/plan_node/stream.rs
Continue the development in #6083 #6105
#6083 #6105
=> refactor(plan): move logical_agg methods to generic

src/utils/pgwire/src/pg_protocol.rs
According to the doc, this message is returned only when input stmt is empty, but not result sets empty
Please create a release note for your changes. In the release note, focus …
=> fix: remove return EmptyQueryResponse

src/meta/src/hummock/manager/mod.rs, src/meta/src/hummock/metrics_utils.rs
feat(compaction group): trigger sst stat for delted groups
background:
@zwang28 found that metric keeps after deletion …
=> feat(compaction group): trigger sst stat for delted groups

src/frontend/src/binder/relation/table_or_source.rs, src/frontend/src/catalog/mod.rs, src/frontend/src/catalog/root_catalog.rs, src/frontend/src/handler/create_index.rs, src/frontend/src/handler/drop_database.rs, src/frontend/src/handler/drop_index.rs, src/frontend/src/handler/drop_mv.rs, src/frontend/src/handler/drop_schema.rs, src/frontend/src/handler/drop_sink.rs, src/frontend/src/handler/drop_source.rs, src/frontend/src/handler/drop_table.rs, src/frontend/src/scheduler/plan_fragmenter.rs
As explained in #6157.
- #6157
- #5791
=> refactor(frontend): use `CatalogError` in catalog to avoid capturing unnecessary backtraces

src/stream/src/executor/dispatch.rs, src/stream/src/executor/exchange/input.rs, src/stream/src/executor/merge.rs, src/stream/src/executor/mod.rs, src/stream/src/executor/receiver.rs, src/stream/src/lib.rs
feat(watermark): Make Exchange be aware of the watermark (close #6050)
doc: https://www.notion.so/risingwave-labs/Watermark-Operators-Explained-a6f9645a068a435bb11074e9596abdf8
thanks to @BugenZhao  …
=> feat(watermark): Make Exchange be aware of the watermark (close #6050)

src/storage/hummock_sdk/src/compact.rs
As title. `CompactTask`'s `task_status` is originally printed as an integer, which is not readable.
Please create a release note for your changes. In the release note, focus on …
=> chore(storage): print compaction task status as string

e2e_test/batch/catalog/pg_opclass.slt.part, src/frontend/src/binder/relation/table_or_source.rs, src/frontend/src/catalog/pg_catalog/mod.rs, src/frontend/src/catalog/pg_catalog/pg_opclass.rs
stub pg_opclass to support sqlancer.
Update: More system tables needed, see: https://github.com/risingwavelabs/risingwave/issues/3364#issuecomment-1299904725. Does not work for now.
-
Note that although `pg_opclass` is user-facing. We do not want to expose it to end user. It is just introduced for sqlancer support.
-
https://github.com/risingwavelabs/risingwave/issues/3431#issuecomment-1164160988
=> feat(pg_catalog): stub pg_opclass

src/bench/file_cache_bench/bench.rs, src/bench/file_cache_bench/main.rs, src/bench/file_cache_bench/utils.rs, src/storage/src/hummock/file_cache/cache.rs, src/storage/src/hummock/file_cache/store.rs
The file cache used *fallocate(2)* with *FALLOC_FL_PUNCH_HOLE* flag which is only supported by limited file systems. 
*tmpfs* and *btrfs* support the syscall and look fine after testing with the file cache. So this PR looses the limitation.
close #5750
=> feat(filecache): support btrfs and tmpfs

src/meta/src/barrier/mod.rs, src/meta/src/barrier/notifier.rs
Currently for a idle cluster, we drop the channel sender without calling `Notifier::notify_finished`:
https://github.com/risingwavelabs/risingwave/blob/df0c3f408c7267d721b7beeb3cb0f5862c3053c3/src/meta/src/barrier/mod.rs#L562
It causes a channel closed error here:
https://github.com/risingwavelabs/risingwave/blob/df0c3f408c7267d721b7beeb3cb0f5862c3053c3/src/meta/src/barrier/schedule.rs#L181
For example, if we run `risedev ctl meta pause` for an idle cluster, it will respond with an error.
If your pull …
=> fix(meta): notify_finished when cluster is idle.

src/utils/pgwire/src/lib.rs, src/utils/pgwire/src/pg_extended.rs
as title. fix #6163 
After the fix, the performance of enabling prepare statement is close to disabling prepare statement.
```
sysbench \
--db-driver=pgsql \
--pgsql-host=localhost  \
--pgsql-port=4566  \
--pgsql-user=root \
--pgsql-db=dev \
--threads=16 \
--report-interval=1 \
--events=0 \
--time=100 \
--percentile=99 \
--auto_inc=false \
--table_size=100000 \
--skip_trx=true \
--range_size=1 \
/usr/local/share/sysbench/oltp_point_select.lua \
run
sysbench 1.1.0-81dd8df (using system LuaJIT 2.1.0-beta3)
Running the test with following options:
Number of threads: 16
Report intermediate results every 1 second(s)
Initializing …
```
=> fix(pgwire):cancel replace smallint,int,bigint param as xx::smallint,xx::int,xx::bigint 

src/storage/src/hummock/event_handler/hummock_event_handler.rs
=> fix(storage): avoid unwrap when notifying clear completion

ci/scripts/deterministic-recovery-test.sh, ci/workflows/main-cron.yml, ci/workflows/pull-request.yml, src/tests/simulation/src/main.rs
As title, in this PR I added a `kill_rate` option for deterministic recovery test. Here are some local test result (with `outer_join.slt` disabled, on branch of @jon-chuang 's fix on `DynamicFilter` in #6247 ):
streaming recovery test:
|  kill-rate   | cost  |
|  ----  | ----  |
| 0.0  | 19s |
| 0.3  | 169.80s |
| 0.5  | 333.93s |
| 1.0 | 561.58s |
batch recovery test:
|  kill-rate   | cost  |
|  ----  | ----  |
| 0.0  | 8.05s |
| 0.3  | 20.09s |
| 0.5  | 30.08s |
| 1.0 | 50.12s |
So let's config `kill-rate` to 0.5 in the deterministic recovery test and setup it's timeout to 10m.
If your pull request contains user-facing …
=> feat: add kill-rate for deterministic recovery test

ci/scripts/build.sh, ci/scripts/e2e-source-test.sh, ci/workflows/main.yml
This PR adds back the CI workflows for dev profile to the main branch, so that we're able to track the build/test performance with dev profile more easily, which matters for the developing experience.
- #6265
- #6103
=> chore(ci): add back e2e workflows for dev profile to main branch

Cargo.lock, dashboard/proto/gen/compactor.ts, dashboard/proto/gen/hummock.ts, proto/compactor.proto, proto/hummock.proto, src/compute/src/server.rs, src/meta/src/hummock/compaction_schedule_policy.rs, src/meta/src/hummock/compactor_manager.rs, src/meta/src/rpc/service/hummock_service.rs, src/prost/build.rs, src/prost/src/lib.rs, src/rpc_client/src/meta_client.rs, src/storage/compactor/Cargo.toml, src/storage/compactor/src/rpc.rs, src/storage/compactor/src/server.rs, src/storage/hummock_sdk/src/compact.rs, src/storage/hummock_test/src/compactor_tests.rs, src/storage/src/hummock/compactor/context.rs, src/storage/src/hummock/compactor/mod.rs
Before this PR, compactor reads config from CLI arguments, and syncs it to meta node when (re)establishing gRPC stream. The compactor config can only be updated by restarting compactor with new CLI arguments. 
After this PR, we can update compactor config at runtime. 
- Compactor exposes a RPC to accept new config. Compactor will apply new config both to local and to meta.
- Compactor's local (modified) config is lost after restart, as before.
- Compactor's local config remains the source of truth, as before.
- Meta node only stores compactor config in memory, as before.
~~- [ ] I have added necessary unit tests and …
=> feat(compactor): support set config at runtime

src/storage/hummock_test/src/compactor_tests.rs, src/storage/hummock_test/src/failpoint_tests.rs, src/storage/hummock_test/src/hummock_storage_tests.rs, src/storage/hummock_test/src/lib.rs, src/storage/hummock_test/src/snapshot_tests.rs, src/storage/hummock_test/src/state_store_tests.rs, src/storage/hummock_test/src/test_utils.rs, src/storage/src/hummock/mod.rs, src/storage/src/hummock/state_store.rs, src/storage/src/hummock/store/state_store.rs, src/storage/src/store.rs
In this PR, we remove `StateStoreWrite` from global `StateStore` and make it read only. 
Some unused field are removed from `HummockStorage` and `LocalHummockStorage`.
After global state store cannot be read, to minimize the change on unit test, we introduce a holder that holds both the local and global state store, and write to local state store and read from both and compare the read result.
=> refactor(storage): make global state store read only

ci/workflows/docker.yml, docker/risingwave.toml, src/common/src/config.rs, src/compute/src/server.rs, src/config/risingwave.toml, src/ctl/src/common/hummock_service.rs, src/frontend/src/session.rs, src/rpc_client/src/meta_client.rs, src/storage/compactor/src/server.rs, src/stream/src/executor/source/source_executor.rs, src/tests/compaction_test/src/runner.rs
As title. In this PR, I added source limit back, and other components will kill themselves when losing connection to Meta for too long. Currently the max allowed heartbeat interval is 10mins by default.
* Other (please specify in …
=> feat: limit source ingestion by barrier and add max allowed heartbeat interval

src/common/src/types/chrono_wrapper.rs, src/common/src/types/decimal.rs, src/common/src/types/interval.rs, src/common/src/types/mod.rs, src/common/src/types/to_binary.rs, src/utils/pgwire/src/pg_extended.rs, src/utils/pgwire/src/pg_field_descriptor.rs
1. add to_binary trait 
2. fix row_description:return the correct format code( we used to return text all the time
=> refactor:add to_binary trait and fix row_description 

src/connector/src/source/kafka/enumerator/client.rs
as title, now we have more detailed error message
```plain
dev=> create materialized source s1 (v1 int, v2 varchar) with (
dev(>   connector = 'kafka',
dev(>   topic = 'kafka_1_partition_topic',
dev(>   properties.bootstrap.server = '127.0.0.1:29092',
dev(>   scan.startup.mode = 'earliest'
dev(> ) row format json;
ERROR:  QueryError: internal error: connector error: failed to fetch metadata from kafka (127.0.0.1:29092), error: topic kafka_1_partition_topic not found
```
~~- [ ] I have written …
=> fix: refine kafka error message

src/frontend/src/catalog/system_catalog/mod.rs, src/frontend/src/catalog/system_catalog/pg_catalog/mod.rs, src/frontend/src/catalog/system_catalog/pg_catalog/pg_views.rs, src/frontend/src/lib.rs, src/meta/src/manager/catalog/database.rs, src/meta/src/manager/catalog/mod.rs
1. add `pg_catalog.pg_views`.
2. modify `pg_catalog.pg_class` to support `\dv`
3. small refactoring in struct `DatabaseManager` and macro `prepare_sys_catalog`.
Because we mark all system catalogs as `table` in RisingWave, but PostgreSQL's system catalogs are divided into tables and views, the output of `pg_views` is different from PostgreSQL's. `pg_views` doesn't contain information about system catalogs. 
Please keep the types that apply to your changes, …
=> feat(frontend): add `pg_catalog.pg_views` and support `\dv`

src/stream/src/executor/sort.rs
`enumerate()` should be before `filter()`
https://github.com/risingwavelabs/risingwave/pull/6085
=> fix(sort operator): `enumerate()` should be before `filter()`

src/tests/regress/README.md, src/tests/regress/data/schedule, src/tests/regress/data/sql/int4.sql
Enable PostgreSQL regress test for `int4`.
- add `int4` in `schedule`
- comment out all not-passed SQL statement in `int4.sql`
- fix a typo in regress README
#6190
=> test(regress): enable int4

e2e_test/batch/types/cast.slt.part, e2e_test/batch/types/interval.slt.part, e2e_test/batch/types/temporal_arithmetic.slt.part, e2e_test/streaming/bug_fixes/panic_on_interval_4575_comment.slt, src/common/src/types/interval.rs, src/frontend/planner_test/tests/testdata/time_window.yaml, src/frontend/planner_test/tests/testdata/tpch.yaml, src/frontend/src/optimizer/plan_node/logical_hop_window.rs
This PR fixes the display of interval values, removing the trailing `00:00:00` to match pg format.
```diff
select interval '1 day';
- 1 day 00:00:00
+ 1 day
```
=> fix(interval): remove trailing `00:00:00` in display

e2e_test/batch/basic/func.slt.part, src/expr/src/expr/expr_binary_nullable.rs
as title
very similar to #6261 
Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where …
=> feat(expr): short-circuit optimization for AND expression

e2e_test/source/datagen.slt
Add a test for `random` `datagen`. Also serve as an example for documentation.
=> test(source): add test for random datagen

src/storage/src/hummock/state_store_v1.rs, src/storage/src/hummock/store/version.rs
After merge https://github.com/risingwavelabs/risingwave/pull/6130, we found some wrong when using state_store_v1 backend. 
This PR fix wrong parameter of `hit_sstable_bloom_filter` and reduce `UserKey::encode` times
- fix wrong parameter of `hit_sstable_bloom_filter`
- remove `UserKey::for_test` in state_store 
- reduce `UserKey::encode` times
- https://github.com/risingwavelabs/risingwave/issues/6353
=> fix(storage): fix wrong parameter of hit_sstable_bloom_filter

src/meta/src/hummock/manager/context.rs, src/meta/src/hummock/manager/mod.rs
Extract `commit_epoch_sanity_check` to reduce length of `commit_epoch`.
* Other (please specify in the release …
=> refactor(meta): extract method for commit_epoch sanity check

src/stream/src/executor/batch_query.rs, src/stream/src/from_proto/batch_query.rs
As per the title,
as per #5249
=> chore(config): remove hard-coded batch size in BatchQuery executor

src/batch/src/task/task_execution.rs
Seems like this will display the error backtrace. Maybe a potential problem.
Please create a release note for your changes. In the release note, focus on the impact on users, and …
=> fix: remove unnecessary error backtrace

proto/hummock.proto, src/meta/src/hummock/compaction/level_selector.rs, src/meta/src/hummock/compaction/manual_compaction_picker.rs, src/meta/src/hummock/compaction/mod.rs, src/meta/src/hummock/compaction/overlap_strategy.rs, src/meta/src/hummock/test_utils.rs, src/storage/hummock_sdk/src/key_range.rs, src/storage/hummock_sdk/src/lib.rs, src/storage/hummock_sdk/src/prost_key_range.rs, src/storage/hummock_test/src/compactor_tests.rs, src/storage/hummock_test/src/hummock_read_version_tests.rs, src/storage/hummock_test/src/sync_point_tests.rs, src/storage/src/hummock/compactor/compactor_runner.rs, src/storage/src/hummock/sstable/builder.rs, src/storage/src/hummock/sstable/mod.rs, src/storage/src/hummock/state_store_v1.rs, src/storage/src/hummock/store/version.rs, src/storage/src/hummock/test_utils.rs
Because https://github.com/risingwavelabs/risingwave/pull/6198 would make the user-key of two neighboring equal, and we need to check it by a special way, or it would cause an panic. …
=> feat(hummock): check `KeyRange` for open-boundary caused by range-tombstone

src/meta/src/manager/catalog/fragment.rs, src/meta/src/stream/scale.rs, src/stream/src/executor/dynamic_filter.rs, src/stream/src/executor/managed_state/dynamic_filter.rs, src/stream/src/from_proto/dynamic_filter.rs, src/tests/simulation_scale/tests/dynamic_filter.rs
After the introduction of `DynamicFilter`, there is a type of fragment which has multiple upstream fragments, but the dispatcher types of these fragments are not the same. For example the fragment of `DynamicFilter` has both `NoShuffle` and `Broadcast` upstream fragments, the processing in the current scaling logic is wrong.
This PR avoids these problems by modifying each of the multiple upstreams, ~but adds an index `fragment_dispatcher_map`, which will be refactored in a later PR~
Also, DynamicFilter has some bugs in scaling scenario like #6414 , this PR tries to fix them
If your pull request contains user-facing changes, …
=> feat: enable scaling for downstream fragment of multi-dispacher relations

risedev.yml, src/frontend/src/health_service.rs, src/frontend/src/lib.rs, src/frontend/src/session.rs, src/risedevtool/src/service_config.rs, src/risedevtool/src/task/frontend_service.rs
Ref to this [issue](https://github.com/risingwavelabs/risingwave/issues/5072), add a health  check RPC service for frontend node at `127.0.0.1:4568`.
https://github.com/risingwavelabs/risingwave/issues/5072
@skyzh
=> feat: health check RPC for frontend node

src/expr/src/vector_op/cast.rs
The expected format mentioned in error message was wrong.
Fixes #6431
=> fix(expr): error message when parsing timestamptz

src/source/src/parser/common.rs, src/stream/src/executor/dynamic_filter.rs
let executor write correct data upon change in dynamic filter
maintain `last_comitted_row`
* Other …
=> fix(dynamic_filter): let executor write correct data upon scaling change

dashboard/proto/gen/stream_plan.ts, proto/stream_plan.proto, src/stream/src/executor/merge.rs, src/stream/src/executor/mod.rs, src/stream/src/executor/sort.rs, src/stream/src/executor/test_utils.rs, src/stream/src/executor/watermark_filter.rs
As the `Datum` in prost erases the type of the scalar, we added the `DataType` into the `Watermark` message.
- #6063
=> feat(streaming): add watermark message variant in proto

src/stream/src/task/barrier_manager.rs, src/stream/src/task/stream_manager.rs
clear all senders on recovery
During recovery, when `drop_all_actors` is called, only collect rx is cleared in `LocalBarrierManager`.
When `drop_all_actors` is called, `senders` should be cleared too.
#6505
=> fix(recovery): clear all senders on recovery

src/stream/src/executor/managed_state/dynamic_filter.rs
concurrently load from state table
parallel load by vnode to accelerate from state table in dynamic filter
a todo in current code:
https://github.com/risingwavelabs/risingwave/blob/4cfa252b5cc0e973c8fa146d66cfd3a52a0c08a0/src/stream/src/executor/managed_state/dynamic_filter.rs#L157
buffer data loaded in each vnode with a `BTreeMap`
If your pull request contains user-facing …
=> perf(dynamic filter): concurrently load from state table

src/sqlparser/src/tokenizer.rs
Make the `tokenize_multiline_comment()` able to handle nested comments, as mentioned in #6518 
Users may write nested comments in SQL, e.g., `0/*multi-line\n* \n/* comment \n /*comment*/*/ */ /comment*/1` will be tokenized to
```rust
vec![
Token::Number("0".to_string()),
Token::Whitespace(Whitespace::MultiLineComment(
"multi-line\n* \n/* comment \n /*comment*/*/ */ …
```
=> fix(parser): handle nested comments

src/frontend/src/optimizer/plan_node/generic.rs, src/frontend/src/optimizer/plan_node/logical_agg.rs, src/frontend/src/optimizer/plan_node/stream_global_simple_agg.rs
+ Moved the impl of `fmt_with_name`
+ Made several methods private
+ Deleted some methods
For #6356
=> refactor(plan, display): reorganize methods to have more private

src/frontend/src/observer/observer_manager.rs
As title, to fix the recovery stuck in https://buildkite.com/risingwavelabs/main-cron/builds/220#0184a1d9-64fe-4cfa-aef5-d9b898aa827a. 
The ddl operation will get stuck after refactoring in https://github.com/risingwavelabs/risingwave/pull/6378. This's because the observer manager in frontend notifies ddl request with an invalid version(0) after re-subscribing from meta. …
=> fix: notify ddl request with correct version to avoid stuck

src/compute/src/lib.rs, src/stream/src/task/stream_manager.rs, src/utils/async_stack_trace/src/lib.rs
Previously the async stack trace is only enabled by default only if the user launches with `risedev`. This PR also enables it by default if no arg is specified, which is for production (cloud) deployment.
I've benched the release build with async stack trace = (verbose, on, off) and hardly found any performance regression. So I guess we're okay to enable it in production.
I'd also like to cherry pick this fix to the release branch. 🤔
- #5931 
- #6512
=> fix: enable async stack trace by default

src/connector/src/source/nexmark/mod.rs, src/connector/src/source/nexmark/source/reader.rs, src/tests/simulation_scale/src/nexmark.rs, src/tests/simulation_scale/tests/nexmark_chaos.rs, src/tests/simulation_scale/tests/nexmark_source.rs, src/utils/nexmark/src/generator.rs, src/utils/nexmark/src/main.rs
As mentioned in #6450, the current partitioning strategy in nexmark makes some splits have no events and fall in a spin loop. This PR fixes it by changing the partitioning strategy. For each split, it no longer maintains the global offset of all events, but a local offset of its own type. This way, we can make sure each split is assigned to an even number of events for a certain type.
```
Global  Offset: 0 1 2 3 4 5 ... 49 50 51 52 53 54 55 ... 99
Person  Offset: 0                   1
Auction Offset:   0 1 2                3  4  5
Bid     Offset:         0 1 ... 45             46 47 ... 91
Person  Offset: 0 1 2 ... 7 8 9 10 …
```
=> fix(nexmark): change the partitioning strategy for each split and fix spin loop

src/tests/sqlsmith/src/runner.rs
As per title, division by zero error may not necessarily be wrapped by `internal error`.
Also added sqlsmith test to ensure we don't skip too many queries.
Please create a …
=> fix(sqlsmith): skip division by zero error

src/tests/sqlsmith/src/lib.rs, src/tests/sqlsmith/src/runner.rs, src/tests/sqlsmith/tests/frontend/mod.rs
Permit some errors in frontend as well, not just in e2e. …
=> fix(sqlsmith): handle expected frontend errors

src/storage/src/hummock/sstable/delete_range_aggregator.rs, src/storage/src/store_impl.rs
In https://github.com/risingwavelabs/risingwave/pull/6303, we accidentally added unused and unresolved import under release mode. In this PR we fix it.
https://github.com/risingwavelabs/risingwave/pull/6303
=> fix(ci): fix unused import in release build

src/meta/src/storage/etcd_meta_store.rs, src/meta/src/storage/mem_meta_store.rs, src/meta/src/storage/meta_store.rs
Previously meta_store snapshot list_cf only returns Vec\<Value\>. This PR makes it return Vec\<(Key, Value)\>.
The use case is I need list all KVs under DEFAULT_COLUMN_FAMILY, which are mostly simple single row data (e.g. various id generators, inflight barrier, notification version). Unlike MetadataModel that always contains Key in Value, these simple single row data doesn't impl MetadataModel, thus cannot get keys from list response.
list_cf is not in the critical path so I think performance impaction is acceptable.
~~- [] I have written necessary rustdoc comments~~
~~- [] I have added necessary unit tests and integration …
=> refactor(meta_store): include keys in snapshot list response

e2e_test/ddl/table.slt, src/frontend/planner_test/src/lib.rs, src/frontend/src/handler/create_table.rs, src/frontend/src/handler/mod.rs
As titled
Support optional `IF NOT EXISTS` for CREATE TABLE statement.
[PG Doc](https://www.postgresql.org/docs/current/sql-createtable.html):
IF NOT EXISTS: Do not throw an error if a relation with the same name already exists. A notice is issued in this case. Note that there is no guarantee that the existing relation is anything like the one that would have been created.
table_name
=> feat(frontend): support CREATE TABLE IF NOT EXISTS

src/meta/src/hummock/manager/mod.rs, src/meta/src/hummock/manager/tests.rs, src/meta/src/hummock/manager/worker.rs, src/meta/src/hummock/mod.rs, src/meta/src/hummock/test_utils.rs, src/meta/src/rpc/server.rs, src/meta/src/stream/stream_manager.rs, src/storage/hummock_test/src/sync_point_tests.rs
Add a dedicated worker for hummock manager. The use case is I need perform async hummock manager ops in drop method.
- Remove start_local_notification_receiver. It's replaced with this worker.
- Remove a non-deterministic test.
* …
=> refactor(meta): unify hummock manager worker

ci/scripts/release.sh
=> fix: gh create release notes too long

src/meta/src/storage/etcd_retry_client.rs, src/rpc_client/src/meta_client.rs
As title:
1. add retry logic for unknown error in etcd. #6683 
2. add retry logic for calling `new_register` to meta, which was found by @wangrunji0408 , when meta exits between client connection and sending request.
* Other …
=> fix: fix some panics in recovery

src/frontend/src/scheduler/distributed/stage.rs
To solve a bug listed in https://buildkite.com/risingwavelabs/main-cron/builds/229
Reason analysis:
Recovery test will kill nodes randomly, so it is possible that a CN crash before sending any status update. In this case, frontend should not panic, but report execution error to user (will abort remaining tasks). 
Verification:
Still on the way to verify it yet. Can not reproduce locally and is trying on EC2 but it's slow. Anyway this change is must better than before.
=> fix: potential scheduler bug in recovery test

src/frontend/planner_test/tests/testdata/agg.yaml, src/frontend/src/planner/query.rs, src/frontend/src/planner/select.rs, src/frontend/src/planner/set_expr.rs, src/frontend/src/planner/set_operation.rs
Plan `DISTINCT ON` as `GroupTopN`. plz read #6146 for details.
Seems that it can support streaming besides batch now :-)
Unnecessary columns in `GroupTopN` cache.
* …
=> feat(distinct on): Plan `DISTINCT ON` as `GroupTopN`

src/frontend/planner_test/tests/testdata/agg.yaml, src/frontend/src/planner/select.rs
Let `order by` check use complete order by list
Should we force `order by` to include `distinct on`?
#6597
=> fix(planner): `order by` check using partial `order by` list

src/common/src/array/list_array.rs, src/common/src/array/struct_array.rs, src/common/src/types/chrono_wrapper.rs, src/common/src/types/decimal.rs, src/common/src/types/interval.rs, src/common/src/types/mod.rs, src/common/src/types/to_binary.rs, src/common/src/types/to_text.rs, src/expr/src/vector_op/cast.rs, src/frontend/src/handler/util.rs
The semantic of to_binary or to_text is to convert a 'inner data' into text or binary format. 
For 'inner data', it should be a scalar with a data type. But for now, to_text() ignore the data type, it assume a default type for the scalar. E.g the default data type of ScalarRef::Int64 is INT8, but actually the data type of ScalarRef::Int64 can be TIMESTAMPTZ. 
This PR add the to_text_with_type() && to_binary_with_type(). to_text && to_binary reserve as a default version of to_text_with_type && to_binary_with_type().
If your pull request contains user-facing changes, please specify the types of the changes, and create a …
=> refactor(common):add to_text_with_type && to_binary_with_type

Cargo.lock, src/tests/simulation/Cargo.toml, src/tests/simulation/src/cluster.rs, src/tests/simulation/src/main.rs
This PR adds support for loading and dumping etcd data in deterministic test.
You can use this feature with the following command:
```sh
./risedev sslt -- --etcd-dump etcd.toml './e2e_test/streaming/*.slt'
./risedev sslt -- --etcd-data etcd.toml './e2e_test/streaming/*.slt'
```
The dumped data is in toml format, where keys and values are encoded in [Rust ascii escape format](https://doc.rust-lang.org/std/ascii/fn.escape_default.html#) to make it human-readable and editable:
```toml
revision = 515
[kv]
"cf/catalog_database/" = "\\x12\\x03dev\\x18\\x01"
"cf/catalog_schema/" = "\\x1a\\x06public \\x01" …
```
=> feat(test): support load/dump for etcd simulator

e2e_test/sink/blackhole_sink.slt, src/connector/src/sink/mod.rs
Blackhole sink does nothing, purely for performance test purposes. 
So that branch https://github.com/risingwavelabs/risingwave/tree/disable_mv can be deleted.
Partially(?) unlock #5678, and performance test for stateless ETL cases. …
=> feat(sink): add blackhole sink

ci/scripts/run-e2e-test.sh, src/tests/compaction_test/src/runner.rs
After recent refactor, `enable_compaction_deterministic` is no longer a cli options. 
This fix set it via config file for ci compaction test.
* RisingWave …
=> fix(ci): set config path for compaction test

src/batch/src/executor/limit.rs, src/common/src/array/bool_array.rs, src/common/src/array/chrono_array.rs, src/common/src/array/column.rs, src/common/src/array/decimal_array.rs, src/common/src/array/interval_array.rs, src/common/src/array/primitive_array.rs, src/common/src/array/utf8_array.rs, src/common/src/test_utils/test_stream_chunk.rs, src/expr/src/expr/build_expr_from_prost.rs, src/expr/src/expr/expr_binary_nonnull.rs, src/expr/src/expr/expr_unary.rs, src/expr/src/vector_op/agg/approx_count_distinct.rs, src/expr/src/vector_op/agg/general_agg.rs, src/expr/src/vector_op/agg/general_distinct_agg.rs, src/expr/src/vector_op/agg/general_sorted_grouper.rs, src/stream/src/executor/aggregation/agg_impl/foldable.rs, src/stream/src/executor/aggregation/value.rs, src/stream/src/executor/integration_tests.rs
This PR generalizes array's `from_slice` function to `FromIterator` trait, so that we can build an array from iterator.
=> feat(array): generalize `**Array::from_slice` to `from_iter`

ci/scripts/e2e-source-test.sh, risedev.yml, src/config/ci-compaction-test.toml, src/config/compaction-test.toml
Previously it relies on default values, and we encounter CI timeout due to recent default value changing.
~~- [] I have written necessary rustdoc comments~~
~~- [] I have added necessary unit tests and integration tests~~
* Other …
=> fix(ci): explicitly set barrier config for compaction test

e2e_test/batch/basic/logical_view.slt.part, src/frontend/src/binder/relation/table_or_source.rs, src/frontend/src/handler/create_view.rs
Previously we saved the unparsed SQL for creating view, which is not well-covered and may lead to some incorrect results like #6801. A quick but thorough fix is to directly store the user's original query. 😅
- Close #6801
=> fix(frontend): save original sql for view

src/stream/src/executor/barrier_align.rs, src/stream/src/executor/dynamic_filter.rs, src/stream/src/executor/hash_join.rs, src/stream/src/executor/managed_state/dynamic_filter.rs
Clean state in `DynamicFilter` by watermark **in right side**
Do range delete by cached watermark among corresponding vnodes on barrier
Buffer and state table will both be cleaned
`BarrierAlign` is modified
If comparator is `LessThan`, it will not be cleaned
#6472
=> feat(watermark): Clean state in DynamicFilter by watermark in right side

src/frontend/src/handler/create_source.rs
See below.
When the user creates a source like 
```SQL
CREATE MATERIALIZED SOURCE s (
v int
) WITH (
connector = 'kafka',
......
) 
ROW FORMAT AVRO 
MESSAGE 'main_message' 
ROW SCHEMA LOCATION 'location';
```
RisingWave will report an error `User-defined schema is not allowed with row format avro.` instead of panicking.
The same for `protobuf`.
Also, we might have to update [our document (column `Limitations` here)](https://www.risingwave.dev/docs/latest/sql-create-source/#supported-sources) for reminding.
=> fix(frontend): report error instead of panicking for invalid CREATE SOURCE

src/tests/regress/data/expected/float8.out, src/tests/regress/data/expected/int4.out, src/tests/regress/data/sql/float4.sql, src/tests/regress/data/sql/float8.sql, src/tests/regress/data/sql/int4.sql
The [TypeString](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-CONSTANTS-GENERIC) syntax (`date '2022-01-01'`) of [sqlparser-rs](https://github.com/risingwavelabs/risingwave/blob/8b9a74556e9e00a3ddd55bb65af8eb76396a666b/src/sqlparser/src/parser.rs#L369-L375) only supports standard types (`smallint`, `real`, `timestamp with time zone`) but not PostgreSQL-internal names (`int2`, `float4`, `timestamptz`). Given these are not user-facing, we update the test cases rather than enhancing the parser.
Also adds `drop table` at end of tests to make repeated run easier.
=> test(regress): enable more int4 queries blocked by TypedString parsing

src/config/ci-compaction-test.toml
Same as https://github.com/risingwavelabs/risingwave/pull/6812 (some default values have been changed by other commit)
* RisingWave cluster configuration …
=> fix(ci): explicitly set config for compaction-test 

Cargo.lock, src/tests/simulation/Cargo.toml
As title. See the change and explanations in https://github.com/madsim-rs/madsim/pull/95.
https://github.com/madsim-rs/madsim/pull/95
=> fix(test): fix running simulation test on ARM64 macOS

.mergify.yml
Update Mergify's commit message template to use the "What's changed and what's your intention?" section in the PR description as the message of the squashed commit.
This change has been made by @fuyufjh from Mergify config editor.
None
closes #6791
=> ci(mergify): update commit message template

dashboard/proto/gen/expr.ts, proto/expr.proto, src/frontend/planner_test/tests/testdata/expr.yaml, src/frontend/src/binder/expr/function.rs, src/frontend/src/expr/expr_visitor.rs, src/frontend/src/expr/mod.rs, src/frontend/src/expr/type_inference/func.rs, src/frontend/src/expr/utils.rs, src/frontend/src/optimizer/plan_node/logical_filter.rs, src/frontend/src/optimizer/plan_node/logical_join.rs, src/frontend/src/optimizer/plan_node/logical_scan.rs, src/frontend/src/optimizer/plan_node/mod.rs, src/frontend/src/optimizer/plan_node/stream_now.rs
Implement happy path of frontend part of now expression in order that optimizer can generate `NowExecutor` node.
We modify `to_stream` method of `LogicalFilter`. It will convert `NowExpr` in filter expression into `NowNode` and convert the `LogicalFIlter` into a `DynamicFilter`.
`LogicalFilter` with `now()` in filter expression will be replaced with a `DynamicFilter` with a `NowNode`.
- Describe any limitations of the current code …
=> feat(now): frontend part of now expression

src/frontend/planner_test/tests/testdata/order_by.yaml, src/frontend/src/optimizer/plan_node/batch_seq_scan.rs
Our BatchScan executor scans multiple ranges concurrently, so the order should be any now.
A flag in BatchScan will be introduced later to control if the BatchScan need to maintain the order.
=> fix(optimizer): BatchSort can not maintain order when it has multiple scan range

src/frontend/planner_test/tests/testdata/predicate_pushdown.yaml
Planner test introduced in https://github.com/risingwavelabs/risingwave/pull/6897 does not show predicate pushdown. We verify the correctness here.
Follow up: https://github.com/risingwavelabs/risingwave/pull/6897
=> fix(planner-test): Show predicate pushdown in `LogicalHop` for non-trivial output indices

src/common/src/config.rs, src/stream/src/executor/exchange/permit.rs
See #6571 for background.
After some discussion with @BugenZhao @yezizp2012 @tabVersion, we realized that it's futile to attempt to "backpressure" the streaming jobs by limiting `in_flight_barrier_nums`. On the contrary, it makes things more tricky, such as the interval between barriers becoming much larger, which in turn results in uncontrolled memory consumption.
This PR removes the limit of `in_flight_barrier_nums` in a quick & dirty way, and reduces the permits of exchange channels to mitigate the high-latency issue. 
Of course, we must remove the related code. Just do this fix for the imminent version release.
None
fix …
=> fix: quick fix for high barrier latency

src/tests/sqlsmith/src/sql_gen/expr.rs, src/tests/sqlsmith/src/sql_gen/mod.rs, src/tests/sqlsmith/tests/frontend/mod.rs
After implicit cast introduced, following bugs occurred:
- https://buildkite.com/risingwavelabs/pull-request/builds/14104#01851aae-4290-4fb1-85f1-a9214d5e1951
- https://buildkite.com/risingwavelabs/pull-request/builds/14089#01851a3d-b8eb-4822-a66a-9dacf9f05571
Per conversation below, I think I would just disable `implicit_cast` for now. Probably have to implement just for a subset of functions, which we know won't be too ambiguous in their evaluation result.
Full explanation (mouse-over and scroll through):
https://github.com/risingwavelabs/risingwave/blob/5a71857e17e1eb5c8fd04379643cd0dad99bae85/src/tests/sqlsmith/src/sql_g …
=> fix(sqlsmith): disable implicit cast

src/config/ci-recovery.toml, src/config/ci.toml
This PR set back the limit for in-flight barrier nums after #6943, so that the time cost for e2e tests in CI is normal. Guess the overhead is caused by more periodical checkpoints. Still investigating. 🤔
- #6943
=> fix(ci): limit in-flight barrier nums

src/frontend/planner_test/tests/testdata/predicate_pushdown.yaml, src/frontend/src/optimizer/plan_node/logical_filter.rs
Sorry, noticed mistakes in https://github.com/risingwavelabs/risingwave/pull/6964 but it got merged before I fixed it.
https://github.com/risingwavelabs/risingwave/pull/6964
=> fix(frontend): Bug in pushdown of `now()`

ci/scripts/cron-fuzz-test.sh, ci/workflows/main-cron.yml
=> fix(cron): make sqlsmith environment variables available

src/frontend/src/catalog/system_catalog/mod.rs, src/frontend/src/catalog/system_catalog/pg_catalog/mod.rs, src/frontend/src/catalog/system_catalog/pg_catalog/pg_class.rs, src/frontend/src/catalog/system_catalog/pg_catalog/pg_index.rs, src/frontend/src/catalog/system_catalog/pg_catalog/pg_tablespace.rs
- Add `pg_tablespace`
- Add more columns in `pg_class` and `pg_index`
This should be the last piece of work in the kernel side to support DBeaver. Tested against DBeaver.
Please …
=> feat(frontend): more pg_catalog support for DBeaver

ci/scripts/run-e2e-test.sh, src/utils/runtime/src/lib.rs
This PR supports overwriting log filters predefined in `init_risingwave_logger`, by specifying RUST_LOG environment variable.
One use case is I want to suppress certain logs in CI, to avoid large log size.
* Connector …
=> refactor(logging): be aware of RUST_LOG env

ci/scripts/run-e2e-test.sh, src/frontend/planner_test/tests/testdata/subquery.yaml
- Suppress debug logs in ci-compaction-test, to avoid too large log size.
- Also fix a failing planner test's expected result, because two new columns has been added in pg_class previously.
* SQL …
=> chore(ci): suppress debug log for compaction-test

src/sqlparser/tests/testdata/select.yaml
Fix parser test of wildcard struct field with additional parentheses: https://buildkite.com/risingwavelabs/main-cron/builds/282#01854176-ffb0-4018-aa7b-fe128a411a41
Please create …
=> fix: fix parser test of wildcard struct field with additional parentheses

Cargo.lock, src/expr/Cargo.toml, src/expr/src/expr/build_expr_from_prost.rs, src/expr/src/expr/expr_to_char_const_tmpl.rs, src/expr/src/vector_op/to_char.rs
Reduce duplicated format parsing during evaluation of `to_char`.
The perf improve by about 20% with a constant format string "YYYY/MM/DD HH24:MI:SS", but downgraded with the current benchmark framework due to #7050 .
=> perf(expr): reduce format parsing in to_char

src/connector/src/source/kafka/mod.rs, src/connector/src/source/kafka/source/reader.rs
Add a configurable parameter to limit the source throughput in terms of bytes.
This parameter may or may not(so not go into doc and release notes this time) be intended to be used by public users at the moment.
It is convenient for people to test resource utilization/performance for a fixed input throughput.(https://redpanda.com/blog/redpanda-vs-kafka-performance-benchmark#:~:text=3.2%20under%20workloads%20(-,up%20to%201GB/sec,-)%20that%20are%20common)
Otherwise, people have to always generate events by some source generators on the fly to Kafka/Redpanda at exactly the throughput you want, which may not be achievable and …
=> feat(connector): optionally limit kafka input throughput bytes

src/common/src/types/decimal.rs, src/common/src/types/ordered_float.rs, src/expr/src/expr/expr_unary.rs, src/expr/src/vector_op/cast.rs, src/expr/src/vector_op/tests.rs
Similar to #7055, this PR vectorizes infallible casts.
<details>
<summary>Click to show full results</summary>
bench | Before time(us) | After time(us) | Change(%) | Speedup
-- | -- | -- | -- | --
cast(int16->float32) | 4.434 | 0.146 | -96.7% | 29.3
cast(int16->int32) | 4.408 | 0.154 | -96.5% | 27.7
cast(float32->float64) | 4.432 | 0.187 | -95.8% | 22.7
cast(int32->int64) | 4.415 | 0.192 | -95.7% | 22.0
cast(int32->float64) | 4.422 | 0.194 | -95.6% | 21.8
cast(int16->int64) | 4.412 | 0.212 | -95.2% | 19.8
cast(timestamp->date) | 4.409 | 0.226 | -94.9% | 18.5 …
=> perf(expr): vectorize infallible casts

src/stream/src/task/barrier_manager/managed_state.rs, src/stream/src/task/stream_manager.rs
Trying to fix continuous recovery found in longevity and chaos test. I found that two problems might be the root cause of continuous recovery:
1. Fixed, unnecessary recovery triggered as described in #6989 . As I tested locally, when workload was very high, there were many ongoing barrier collect responses(up to 80+) when recovery. After recovery finished, each response would trigger a recovery process, because the whole cluster has already reset to previous committed epoch.
2. Before this PR, when force stopping actors in CN, the local manger will clean all states and then abort all actors. The problem is between cleaning …
=> fix: clean states in local barrier manager after actor dropped

src/stream/src/executor/source/fs_source_executor.rs, src/stream/src/executor/source/source_executor.rs, src/stream/src/executor/source/source_executor_v2.rs
this is a temp fix for #6931, and I believe that this can happen in rare cases. 
From the log described in the issue, there is a failover that occurred before the panic. I think some part of meta failed to recover and the barrier channel closed for some reason.
It shows a possibility that meta node could fail to recover and compute node should be robots enough rather than panicking.  
~~- [ ] I have written …
=> fix: return error if source executor failed to receive the first barrier

e2e_test/batch/types/interval.slt.part, src/common/src/types/interval.rs
Precision not enough should not throw Error. …
=> fix: precision not enough should not throw Error

.github/workflows/assign-issue-milestone.yml
As title. See details in https://github.com/fuyufjh/automatically-set-milestone-to-issue/pull/4
None
None
=> chore: don't overwrite the millestone if it has been set

src/compute/tests/integration_tests.rs, src/stream/src/executor/row_id_gen.rs, src/stream/src/from_proto/row_id_gen.rs, src/tests/simulation/tests/nexmark_source.rs
Correctly handle the scaling for RowIdGen executor. The logic used to work fine, but was lost in the refactoring in #6529.
- #6529
- #6836
- #7103
=> fix(streaming): handle scaling for row id gen executor

src/batch/src/executor/generic_exchange.rs
- Parallelize exchange source creation to speed up sql like `select * from v limit 1` if `v` has so many partitions.
Please create a release note for your changes. In the release …
=> feat(batch): parallelize exchange source creation

e2e_test/source/cdc/cdc.load.slt, e2e_test/source/cdc/cdc.validate.mysql.slt, e2e_test/source/cdc/cdc.validate.postgres.slt, src/sqlparser/src/ast/statement.rs, src/sqlparser/src/lib.rs
Remove the ROW FORMAT keyword for CREATE statement of native CDC connectors, which must be debezium json format.
```
create materialized source orders (
order_id int,
order_date timestamp,
customer_name string,
price decimal,
product_id int,
order_status smallint,
PRIMARY KEY (order_id)
) with (
connector = 'mysql-cdc',
hostname = '127.0.0.1',
...
) row format debezium_json <-- removed
```
Please keep the types that apply to your changes, and remove those …
=> feat(sql): Remove the ROW FORMAT keyword for CREATE statement of native CDC connectors

src/source/src/fs_connector_source.rs, src/source/src/parser/csv_parser.rs
- Fix the bug that the csv parser can't parse the last line when the last line is missing a line break.
#7063
=> fix(source): fix csv parser

ci/workflows/main-cron.yml
`TEST_NUM` and `MADSIM_TEST_NUM` is missed.
=> fix(ci): provide input parameters for main-cron's deterministic tests

src/frontend/planner_test/src/lib.rs, src/frontend/planner_test/tests/testdata/explain.yaml, src/frontend/src/handler/explain.rs, src/frontend/src/handler/mod.rs, src/frontend/src/optimizer/mod.rs, src/frontend/src/optimizer/optimizer_context.rs, src/frontend/src/test_utils.rs
Implement `explain logical`. 
It can be useful to some users who want to understand the logical plan of their query, but not the physical plan or look through the trace.
Usage combinations:
1. `explain (logical) [stmt]`: show the optimized logical plan
2. `explain (logical, trace) [stmt]`: only show the optimizer trace up to optimized logical plan
3. `explain (logical, verbose) [stmt]`: no change with 1
The documentation for `EXPLAIN` should be updated (we can merge it after release)
Enabled `explain (logical)` and `explain (logical, trace)`.
https://github.com/risingwavelabs/risingwave/issues/4856
=> feat(frontend): `explain (logical)`

ci/workflows/main-cron.yml
Decrease test num of recovery test in main-cron: https://buildkite.com/risingwavelabs/main-cron/builds/292#018574f6-e819-41db-ba51-80363d49c625.
* Connector …
=> fix: decrease test num of recovery test in main-cron

Cargo.lock, src/batch/Cargo.toml, src/batch/src/task/context.rs, src/batch/src/task/task_execution.rs, src/batch/src/task/task_manager.rs, src/frontend/src/scheduler/task_context.rs
Collect batch task mem usage by store the value in Task Context and sum it up in BatchManager.
Please create a release note for your changes. In the release note, focus on the …
=> feat: collect batch task mem

src/storage/src/hummock/event_handler/hummock_event_handler.rs, src/storage/src/hummock/state_store.rs
Before this PR, seal_epoch updating is handled by HummockEventHandler [asynchronously](https://github.com/risingwavelabs/risingwave/blob/12127933b945ba414e5a7329e04139c65f09f9c7/src/stream/src/task/barrier_manager/managed_state.rs#L133), which cannot ensure HummockEventHandler::seal_epoch is updated [before notifying barrier finishing ](https://github.com/risingwavelabs/risingwave/blob/12127933b945ba414e5a7329e04139c65f09f9c7/src/stream/src/task/barrier_manager/managed_state.rs#L144). It can lead to [current epoch can't read, because the epoch in storage is not updated](https://github.com/risingwavelabs/risingwave/issues/716 …
=> fix(storage): update seal_epoch synchronously

dashboard/proto/gen/expr.ts, proto/expr.proto, src/frontend/src/expr/function_call.rs, src/frontend/src/expr/mod.rs
=> chore: remove deprecated expr in proto

src/frontend/src/optimizer/plan_node/generic/dynamic_filter.rs, src/frontend/src/optimizer/plan_node/logical_filter.rs, src/frontend/src/optimizer/plan_node/logical_join.rs, src/frontend/src/optimizer/plan_node/stream.rs, src/frontend/src/optimizer/plan_node/stream_dynamic_filter.rs
Currently, the dynamic filter stores a whole `Condition` which contains many assumptions. In this PR, we just store the exprType and left key index, which is more type-safe and readable.
=> refactor: dynamic filter plannode

src/frontend/planner_test/tests/testdata/expr.yaml, src/frontend/planner_test/tests/testdata/predicate_pushdown.yaml
now planner test should also use timestamptz instead of timestamp …
=> fix(planner test): now planner test should also use timestamptz

Makefile.toml, risedev.yml, src/config/default.toml
Remove the hazardous `default.toml` with `enable_recovery = false`
None
None
=> fix: remove the hazardous default.toml

src/compute/src/lib.rs
Avoid zero parallelism in initialization of compute node.
* RisingWave cluster …
=> fix: avoid zero parallelism in initialization of compute node

Cargo.lock, e2e_test/database/timezone.slt, src/common/Cargo.toml, src/common/src/session_config/mod.rs, src/frontend/src/handler/variable.rs, src/frontend/src/session.rs
Session timezone. Defaults to `UTC`. 
I believe defaulting to UTC is better than defaulting to server local timezone as default timezone for user timestamps is more likely to be UTC than server timezone.
We will warn users via pgwire notice whenever they make use of session timezone implicitly.
enabled `set timezone = [TimeZone]` and `show timezone`;
https://github.com/risingwavelabs/risingwave/issues/7175
=> feat(frontend): session timezone

dashboard/proto/gen/hummock.ts, proto/hummock.proto, src/common/src/config.rs, src/config/ci-compaction-test-meta.toml, src/config/ci-compaction-test.toml, src/meta/src/hummock/manager/mod.rs, src/meta/src/hummock/manager/tests.rs, src/meta/src/rpc/service/hummock_service.rs, src/rpc_client/src/meta_client.rs, src/tests/compaction_test/src/compaction_test_runner.rs, src/tests/compaction_test/src/delete_range_runner.rs, src/tests/compaction_test/src/lib.rs
We sleep for 2 seconds in the `init_metadata_for_replay()`, the embedded meta node will commit an epoch during this period. So the version will be accidentally bumped.
- Prevent meta bump hummock version during version replay
- Remove unused interface from hummock manager
Fix #7251
=> fix(compaction-test): prevent meta bump hummock version during version replay

dashboard/proto/gen/catalog.ts, dashboard/proto/gen/ddl_service.ts, dashboard/proto/gen/expr.ts, dashboard/proto/gen/meta.ts, dashboard/proto/gen/user.ts, e2e_test/batch/catalog/pg_stat_activity.slt.part, src/frontend/src/binder/expr/function.rs, src/frontend/src/binder/mod.rs, src/frontend/src/catalog/system_catalog/mod.rs, src/frontend/src/catalog/system_catalog/pg_catalog/mod.rs, src/frontend/src/catalog/system_catalog/pg_catalog/pg_stat_activity.rs
To support superset, implement system table `pg_stat_activity` and a workaround of `pg_cancel_backend`/`pg_terminate_backend`.
Introduced a system catalog `pg_stat_activity`.
Introduced some functions: 
- pg_cancel_backend: Cancel a backend's current query. You can execute this against another backend that has exactly the same role …
=> feat(frontend): support pg_stat_activity and an workaround of pg_cancel_backend/pg_terminate_backend

src/frontend/src/handler/create_source.rs, src/sqlparser/src/ast/statement.rs, src/sqlparser/src/parser.rs
Before:
```SQL
dev=> create source products (
...
) with (
connector = 'mysql-cdc',
...
) row format debezium json;
ERROR:  QueryError: sql parser error: Expected end of statement, found: row
```
After:
```SQL
dev=> create source products (
...
) with (
connector = 'mysql-cdc',
...
) row format debezium json;
ERROR:  QueryError: sql parser error: Row format for cdc connectors should not be set here because it is limited to debezium json
```
Also fixed a typo in maxwell error message.
=> fix(frontend): add more details to cdc source error message

e2e_test/source/basic/kafka.slt, src/frontend/src/handler/create_source.rs, src/frontend/src/handler/create_table.rs
Fix the bug that users cannot create non-materialized kafka source with row format of protobuf and avro.
Before:
```SQL
create source s with (
connector = 'kafka', 
...
) row format protobuf message xxxxx row schema location file://yyyyy;
ERROR:  QueryError: Protocol error: User-defined schema is not allowed with row format protobuf. Please refer to https://www.risingwave.dev/docs/current/sql-create-source/#protobuf for more information.
```
After:
```SQL
create source s with (
connector = 'kafka', 
...
) row format protobuf message xxxxx row schema location file://yyyyy;
CREATE_SOURCE
```
Also add corresponding e2e tests. …
=> fix(frontend): fix source check on protobuf and avro based on `_rw_kafka_timestamp` column

docker/Dockerfile, docker/risingwave.toml
See background on #6814
By the way, remove images from Dockerfile except the "all-in-one" image, which are not used now.
None
None
=> fix: empty `docker/risingwave.toml`

e2e_test/streaming/group_top_n.slt, src/common/src/hash/dispatcher.rs, src/stream/src/from_proto/group_top_n.rs
=> fix: stream group topn used wrong types for hash key

src/common/src/row/mod.rs, src/common/src/row/owned_row.rs, src/compute/src/memory_management/memory_manager.rs, src/stream/src/executor/hash_agg.rs, src/stream/src/executor/lookup/cache.rs, src/stream/src/executor/sort.rs, src/stream/src/executor/sort_buffer.rs
`impl Ord for OwnedRow` is error-prone.
Close #7392
=> refactor(row): remove Ord for OwnedRow and introduce AscentRow

src/stream/src/executor/backfill.rs, src/stream/src/lib.rs
- Since storage `pk_serializer` will encode the primary key based on the order type, we need to handle the comparison between `current_pos` and upstream message storage order key properly.
* Installation …
=> fix(stream): fix backfill comparison with pk order

src/batch/src/task/broadcast_channel.rs, src/batch/src/task/channel.rs, src/batch/src/task/consistent_hash_shuffle_channel.rs, src/batch/src/task/fifo_channel.rs, src/batch/src/task/hash_shuffle_channel.rs, src/batch/src/task/task_execution.rs, src/tests/regress/src/schedule.rs
Basically the idea is store sender inside TaskExecution. And clone it out when we need to mut it.
Please create a release note for your changes. In the release note, focus on the …
=> fix: broken channel reciever

Cargo.lock, src/frontend/Cargo.toml, src/frontend/src/scheduler/local.rs
Currently local mode's root fragment is executed in frontend, if it maybe a blocking operation and block listener thread of frontend, so we move it to block pool.
#7285
=> fix: Fix potential block in frontent.

src/stream/src/executor/source/source_executor_v2.rs
- refine some code of source executor
~- [] I have written necessary rustdoc comments~
=> refactor(source): refine some code of source executor

Cargo.lock, src/source/src/parser/canal/simd_json_parser.rs
- fix json parser
fix #7446
caused by #7256 
update simd-json: https://github.com/tabVersion/simd-json/pull/1
=> fix(source): fix json parser

Cargo.lock, src/meta/src/hummock/test_utils.rs, src/storage/hummock_test/benches/bench_hummock_iter.rs, src/storage/hummock_test/src/compactor_tests.rs, src/storage/hummock_test/src/failpoint_tests.rs, src/storage/hummock_test/src/hummock_storage_tests.rs, src/storage/hummock_test/src/lib.rs, src/storage/hummock_test/src/mock_notification_client.rs, src/storage/hummock_test/src/snapshot_tests.rs, src/storage/hummock_test/src/state_store_tests.rs, src/storage/hummock_test/src/sync_point_tests.rs, src/storage/hummock_test/src/test_utils.rs, src/storage/src/hummock/mod.rs, src/stream/Cargo.toml, src/stream/src/common/table/mod.rs, src/stream/src/common/table/test_state_table.rs, src/stream/src/common/table/test_storage_table.rs, src/stream/src/common/table/test_utils.rs, src/tests/compaction_test/src/delete_range_runner.rs
- Introduce `HummockTestEnv` to simplify creating hummock storage for tests.
- Simplify `hummock_storage_tests.rs` with `HumockTestEnv`.
- rename `test_streaming_table` and `test_batch_table` to `test_state_table` and `test_storage_table`.
- Use `HummockTestEnv` to create a hummock storage backed by in-mem object storage instead of a BTeeMap state store for `test_state_table` and `test_storage_table`.
- Fix several bugs in `test_state_table` and …
=> refactor(test): simplify and fix state/storage table and hummock tests

Cargo.lock, src/common/Cargo.toml, src/expr/Cargo.toml, src/tests/simulation/src/main.rs, src/udf/Cargo.toml
Previously we reference arrow from a github commit for some unreleased features. This PR switches it back to crates.io version.
This PR also fixes the bug that simulation tester doesn't read `RUST_LOG` env to set log level.
=> chore(deps): switch arrow to crates.io version

.github/pull_request_template.md
We'll extract the content of the main section as the commit message, so if the PR author doesn't remove the hints, the commit message will be very verbose and confusing.
[Mergify's doc](https://docs.mergify.com/configuration/#template) said that they would strip the HTML comments in the section, so it's better to use comments here.
> By default, the HTML comments are stripped from body. To get the full body, you can use the body_raw attribute.
=> chore(pr-template): use html comments in main section

dashboard/proto/gen/catalog.ts, proto/catalog.proto, src/batch/src/executor/delete.rs, src/batch/src/executor/insert.rs, src/batch/src/executor/update.rs, src/frontend/src/binder/insert.rs, src/frontend/src/optimizer/plan_node/logical_insert.rs, src/frontend/src/optimizer/plan_node/logical_update.rs, src/source/src/dml_manager.rs, src/source/src/table.rs, src/stream/src/executor/dml.rs, src/stream/src/executor/source/reader.rs
=> chore: rename `TableSource` to `TableDmlHandle`

.github/workflows/dashboard_main.yml, .github/workflows/doc.yml, .github/workflows/license_check.yml, .github/workflows/typo.yml
upgrade actions/checkout to v3
> ANNOTATIONS
> ! Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
=> ci: upgrade actions/checkout to v3

docker/docker-compose.yml, src/meta/src/lib.rs, src/meta/src/rpc/follower_svc.rs, src/meta/src/rpc/server.rs, src/meta/src/rpc/service/leader_service.rs, src/risedevtool/src/task/meta_node_service.rs, src/tests/simulation/src/cluster.rs
Meta node should be identified by its `meta_endpoint` parameter. Previously, this defaults to the `listen_addr`. The purpose of `meta_endpoint` is to serve as a unique identifier for cluster membership and for leadership election and connecting to leader.  
Possibly breaks any usage of risingwave that does not pass `meta_endpoint` when running with etcd.
Meta node run with etcd must now specify `--meta-endpoint`
https://github.com/risingwavelabs/risingwave/issues/7526
=> fix(meta): Meta node should be identified by its `meta_endpoint` parameter for cluster membership

ci/scripts/deterministic-e2e-test.sh, ci/scripts/deterministic-recovery-test.sh
We are using 2 frontend notes by default and not 1 (see [simulation tests args](https://github.com/risingwavelabs/risingwave/blob/8d99f7aedf86d7a3a43eed075c163afee6d1298e/src/tests/simulation/src/main.rs#L43)). Updating echo to reflect that.  …
=> fix(chore): Echo correct setup during sim tests

ci/Dockerfile, ci/build-ci-image.sh, ci/docker-compose.yml, ci/scripts/e2e-sink-test.sh, ci/scripts/e2e-source-test.sh
fix main
aca70301a066b29f133a0ca205bb85e89a237a1c
the issue is introduced because of the upstream change
=> fix: move install mysql-client to ci image

src/compute/src/lib.rs, src/storage/compactor/src/lib.rs
Make it known to the users what are valid params
fixes https://github.com/risingwavelabs/risingwave/issues/7531
=> feat(service-params): add comments for `--state-store` params for `compute-node`, `compactor-node`

e2e_test/streaming/dynamic_filter.slt, e2e_test/streaming/temporal_filter.slt, src/frontend/src/stream_fragmenter/mod.rs, src/stream/src/executor/now.rs
`now` fragment was not singleton
Fixes: https://github.com/risingwavelabs/risingwave/issues/7543
Fixes adding e2e test for now/temporal filter: https://github.com/risingwavelabs/risingwave/issues/6790
=> fix(frontend): `now` fragment should be singleton

e2e_test/streaming/temporal_filter.slt
More tests
fix: https://github.com/risingwavelabs/risingwave/issues/6790
=> feat(e2e-testing): More tests for `TemporalFilter`

src/connector/src/source/filesystem/s3/enumerator.rs
The `match_pattern` is used to match object key in `s3.bucket_name`, standard Unix-style glob syntax is supported.
`happy[1-9].*` in the following statement will match all objects with key `foo` plus an Arabic number and any type …
=> feat(source): support match_pattern for s3 enumerator

src/meta/src/hummock/manager/compaction_group_manager.rs
When CREATE_COMPACTION_GROUP_FOR_MV is true:
- Before this PR, all tables of a stream job will be assigned their own new compaction groups. This is unnecessary, especially for small tables.
- With this PR, all tables of a stream job will be assigned one same new compaction group.
- SQL commands, functions, and …
=> refactor(meta): refactor CREATE_COMPACTION_GROUP_FOR_MV

src/cmd_all/src/playground.rs, src/meta/src/lib.rs
We may rename the args again, but let's stop the breakage due to missing playground arg changes due to https://github.com/risingwavelabs/risingwave/pull/7527...
=> fix(meta): Temporarily fix breakage of playground due to missing --host arg

e2e_test/batch/functions/overlay.slt.part, src/expr/src/vector_op/overlay.rs
Use `checked_sub`.
Fixes #7573
=> fix(expr): overlay panic on overflow

e2e_test/batch/types/date.slt, e2e_test/batch/types/time.slt.part, e2e_test/batch/types/timestamptz_utc.slt.part, src/common/src/types/interval.rs, src/expr/src/lib.rs, src/expr/src/vector_op/arithmetic_op.rs
Handle the potential "out of range" panics in time operations as careful as possible.
- Fix #7566
=> fix(expr): handle time operation out of range

ci/workflows/main-cron.yml, ci/workflows/pull-request.yml, src/prost/src/lib.rs, src/rpc_client/src/lib.rs, src/rpc_client/src/meta_client.rs, src/tests/simulation/src/cluster.rs, src/tests/simulation/src/main.rs
This PR is a follow-up to PR #7179 
This PR provides a meta client with an election client, and implements a sidecar rpc client update through the api of `members` and `leader` from LeaderService
But this also introduces a mutex, all meta client operations need to hold this lock
* …
=> feat: meta-client with new election mechanism

src/meta/src/rpc/election_client.rs, src/meta/src/rpc/server.rs
If the election client resumes from the leader state, it will start directly from the leader service
Please create a …
=> fix(meta): start leader service directly in meta election scenario

src/storage/src/hummock/error.rs, src/storage/src/hummock/state_store.rs
The `ReadCurrentEpoch error` only occurs when the cluster is under recovery. This PR emphasizes this fact in error message, because the error message will be read by frontend user.
When seeing `ReadCurrentEpoch error` constantly, root cause of unsuccessful recovery should be investigated, instead of `ReadCurrentEpoch error` itself.
If your pull request contains user-facing changes, please …
=> chore(log): modify read current epoch error message

.github/workflows/dashboard_pr.yml, .github/workflows/protobuf-breaking.yml, proto/buf.yaml, proto/common.proto
This PR adds the workflow of detecting breaking changes in protobuf to the CI workflow. Here is an example of error reporting:
- https://github.com/risingwavelabs/risingwave/pull/7609/commits/c1dd48e4f4291270ec515886d999dbf8b946b733
We've set the rule category to `WIRE_JSON` which is explained [here](https://docs.buf.build/breaking/rules). Actually `WIRE` is enough for our major usages, while `WIRE_JSON` ensures that the name of the fields is not modified, which brings less confusion to the codebase and also makes the JSON-based dashboard easier to maintain (e.g., avoid #7262 from happening).
We may not need to add this …
=> chore: check breaking change in protobuf

src/meta/src/lib.rs
risingwave-operator made a [temporary fix](https://github.com/risingwavelabs/risingwave-operator/commit/f011c368e0ffc72e615d4717fefbef4650851d2e) with regards to the breaking change that uses `meta-endpoint` instead of `host`, please refer to #7527.
But the cloud is unable to adopt this change right now, so we add `host` back.
By looking at the temporary fix, it used to use `IP` as `host` and now uses `IP:PORT` as `meta-endpoint`.
So this hot fix uses `IP` from `host` and  `PORT` from `listening-addr` to compose `meta-endpoint`, please correct me if I am wrong.
~- [ ] I have added necessary unit tests and integration …
=> fix(meta): add back host, a deprecated cmd line argument

src/tests/simulation/src/nexmark.rs, src/tests/simulation/src/nexmark/create_source.sql, src/tests/simulation/src/nexmark/q101.sql, src/tests/simulation/src/nexmark/q102.sql, src/tests/simulation/src/nexmark/q103.sql, src/tests/simulation/src/nexmark/q104.sql, src/tests/simulation/src/nexmark/q105.sql, src/tests/simulation/src/nexmark/q3.sql, src/tests/simulation/src/nexmark/q4.sql, src/tests/simulation/src/nexmark/q5.sql, src/tests/simulation/src/nexmark/q7.sql, src/tests/simulation/src/nexmark/q8.sql, src/tests/simulation/src/nexmark/q9.sql
This PR moves inlined nexmark queries to external file.
=> chore(test): move nexmark queries to external file

src/frontend/src/handler/query.rs
It's possible that the chunk stream do not return any data. For example, insert fail.
We should not panic here.
From #7454
Please create a release note for your changes. In …
=> fix: do not panic when there is None in dml ret stream

src/meta/src/lib.rs
See #7616, the previous pr only changes the etcd backend. It fails when running mem backend.
Now both etcd backend and mem backend run with the same `meta-endpoint` when `meta-endpoint` is not provided, 
i.e. `format!("{}:{}", meta_addr, listen_addr.port())`
=> fix(meta): backward compatible with host when running in mem meta backend

src/tests/sqlsmith/src/sql_gen/expr.rs
Workaround: https://github.com/risingwavelabs/risingwave/issues/4762
Please create a release note for your changes. In the release note, focus on the impact on users, and …
=> chore(sqlsmith): disable `FILTER` with correlated input reference

e2e_test/batch/functions/substr.slt.part, src/expr/src/vector_op/substr.rs, src/tests/sqlsmith/src/validation.rs
=> fix(expr): use checked operations for substr

src/meta/src/lib.rs
Fix `meta_endpoint` format when `host` is not provided in playground mode, the endpoint will be wrongly generated as `127.0.0.1:5690:5690`.
Please create a release note for …
=> fix(meta): fix meta_endpoint format when host not provided in playground mode

src/tests/simulation/src/main.rs, src/tests/simulation/src/slt.rs
~- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer the issue)~
If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, …
=> chore(test): minor code refactoring in simulation test

src/storage/src/hummock/iterator/merge_inner.rs
Change this warning message into a debug message, because it's the expected behavior during backfill. Otherwise it can overwhelm the log stream during a large MV creation. …
=> chore(log): suppress unnecessary warning

src/tests/sqlsmith/src/sql_gen/expr.rs, src/tests/sqlsmith/src/sql_gen/scalar.rs
=> fix(sqlsmith): generate typed null

.github/workflows/protobuf-breaking.yml
=> ci: add github_token for buf-setup-action

src/compute/src/lib.rs
The alias of `--advertise-addr` should be `--client-address` to keep compatible with previous versions.
None
Introduced in #7530
=> fix: alias of argument `advertise_addr`

e2e_test/source/basic/kafka_batch.slt
=> chore(test):add e2e test for producing timestamp in kafka source

src/meta/src/rpc/election_client.rs, src/meta/src/rpc/server.rs
This PR changes the connection in the ETCD election client to a short connection to resolve a stuck etcd master migration in case of auth enable.
Please create a release note …
=> chore: use short connection in etcd election client

src/frontend/planner_test/tests/testdata/sysinfo_funcs.yaml, src/frontend/src/binder/expr/function.rs, src/frontend/src/binder/expr/mod.rs
=>  feat(binder): support current_timestamp

src/meta/src/barrier/mod.rs, src/meta/src/barrier/snapshot.rs, src/meta/src/hummock/manager/compaction.rs, src/meta/src/hummock/manager/compaction_group_manager.rs, src/meta/src/hummock/manager/context.rs, src/meta/src/hummock/manager/mod.rs
Fix #7657.
We know MV creation failure will either trigger a recovery, or trigger a meta panic if enable_recovery is false.
- For the former case, this PR unpins all snapshot owned by meta node, before recovery starts. 
- For the latter case, hummock manager is already made to unpin all snapshot owned by meta node during initialization.
- …
=> fix(meta): unpin snapshot on MV creation failure

src/meta/src/hummock/manager/mod.rs
As we don't hold versioning lock throughout `get_compact_task_impl`, this bug can happen:
1. `get_compact_task_impl`: [get all_table_ids](https://github.com/risingwavelabs/risingwave/blob/9068a4ed612482ff3d101a5d6a97a5010113349c/src/meta/src/hummock/manager/mod.rs#L744).
2. New table is created and its SSTs are added to version by checkpoint. So `all_table_ids` got in step 1 is stale.
3. `get_compact_task_impl`: [new compaction task](https://github.com/risingwavelabs/risingwave/blob/9068a4ed612482ff3d101a5d6a97a5010113349c/src/meta/src/hummock/manager/mod.rs#L784) includes these new table's SSTs as input.
4. Compaction …
=> fix(compaction): fix corner case

Cargo.lock, src/frontend/planner_test/Cargo.toml, src/frontend/planner_test/src/bin/apply.rs
Comments: the backtrace is verbose but now contains sufficient information to debug
https://github.com/risingwavelabs/risingwave/issues/7754
=> feat(planner-test): backtrace on panic

Makefile.toml
Applies clippy fixes to all files, including staged and dirty
Usage: 
`./risedev cf frontend meta`
```
...
Applying clippy --fix for frontend meta (including dirty and staged files)
```
`./risedev cf`
```
...
Applying clippy --fix for all targets (including dirty and staged files)
```
https://github.com/risingwavelabs/risingwave/issues/7756
=> feat(risedev): add `check-fix` task

dashboard/proto/gen/expr.ts, e2e_test/batch/functions/pow.slt.part, proto/expr.proto, src/common/src/types/ordered_float.rs, src/expr/src/expr/expr_binary_nonnull.rs, src/expr/src/expr/mod.rs, src/expr/src/sig/func.rs, src/expr/src/vector_op/arithmetic_op.rs, src/frontend/src/binder/expr/function.rs, src/tests/sqlsmith/src/sql_gen/expr.rs
Right now, both x and y are casted into Float64 when pow(x, y).
By PG's standard, we also need to support Decimal but Decimal has no built-in pow and we may also change the underlying crate for Decimal. So we leave it aside for now.
Urgently requested by user.
#7725 
- SQL functions …
=> feat(expr): support pow function

src/expr/src/vector_op/round.rs
Rust decimal bug allows rounding past 28 significant digits which is its maximum.
https://github.com/risingwavelabs/risingwave/pull/7815#issuecomment-1424223070
=> fix(expr): incorrect decimal rounding due to `rust_decimal` bug

Cargo.lock, src/object_store/Cargo.toml, src/object_store/src/object/opendal_engine/hdfs.rs, src/object_store/src/object/opendal_engine/opendal_object_store.rs
Signed-off-by: Xuanwo <github@xuanwo.io>
This PR will bump opendal to v0.26.
Changelogs could be found at https://docs.rs/opendal/0.26.2/opendal/docs/changelog/index.html
No user face changes
chore(deps): Bump OpenDAL to 0.26
=> chore(deps): Bump OpenDAL to 0.26

Cargo.toml, ci/Dockerfile
significantly reduced build time
=> build: disable incremental build in CI

src/tests/sqlsmith/src/sql_gen/query.rs
=> fix(sqlsmith): limit number of cross joins

src/meta/src/hummock/compaction/mod.rs, src/meta/src/hummock/model/compact_task_assignment.rs, src/meta/src/hummock/model/compaction_group_config.rs, src/meta/src/hummock/model/compaction_status.rs, src/meta/src/hummock/model/mod.rs, src/meta/src/hummock/model/pinned_snapshot.rs, src/meta/src/hummock/model/pinned_version.rs, src/meta/src/hummock/model/version.rs, src/meta/src/hummock/model/version_delta.rs, src/meta/src/hummock/model/version_stats.rs
Before this PR we prefix hummock meta store model's key with descriptive name like "cf/hummock_version_delta".
This PR changes these prefix to shorter "cf/hummock_#" for better write performance and storage efficiency. …
=> refactor(meta): use short prefix name for hummock meta store model

dashboard/scripts/generate_proto.sh
Fix the error below when running `npm run gen-proto` for dashboard:
```
meta.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.
```
#7668
=> fix: fix dashboard proto-gen shell script

Cargo.lock, src/object_store/src/object/s3.rs, src/tests/simulation/Cargo.toml
This PR bumps madsim version to fix 2 bugs:
1. madsim `panicked at 'unsupported clockid: 7'`
2. S3: Deleted object not found should not result in errors.
Related changes: https://github.com/madsim-rs/madsim/pull/121
- ~~I have written necessary rustdoc comments~~
- ~~I have added necessary unit tests and integration tests~~
- ~~I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features).~~
- ~~I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to …
=> fix: bump madsim version to fix bugs

dashboard/proto/gen/plan_common.ts, proto/plan_common.proto, src/batch/src/executor/source.rs, src/connector/src/parser/avro/mod.rs, src/connector/src/parser/avro/parser.rs, src/connector/src/parser/avro/util.rs, src/connector/src/parser/debezium/avro_parser.rs, src/connector/src/parser/debezium/mod.rs, src/connector/src/parser/mod.rs, src/connector/src/source/base.rs, src/frontend/src/handler/create_source.rs, src/meta/src/hummock/manager/mod.rs, src/source/src/source_desc.rs, src/sqlparser/src/ast/statement.rs, src/sqlparser/src/keywords.rs
Support debezium avro format with schema registery. Example:
```
CREATE table dbz (id integer primary key) with (
connector = 'kafka',
topic = 'dbserver1.inventory.customers',
properties.bootstrap.server = '127.0.0.1:9092',
scan.startup.mode = 'earliest'
) row format debezium_avro row schema location CONFLUENT SCHEMA REGISTRY 'http://localhost:8081';
```
Known limitations of this PR:
- We must use CREATE TABLE syntax with primary key specified to create dbz avro source
- Schema resolution fails when calling the from_avro_datum even when reader_schema == writer_schame. This is a limitation in apache-avro rust lib. We can …
=> feat(source): support debezium avro format

src/meta/src/manager/catalog/database.rs
Fix refer count of sink dependent relations.
</details>
=> fix: fix refer count of sink dependent relations

src/meta/src/backup_restore/backup_manager.rs, src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs, src/storage/src/hummock/event_handler/hummock_event_handler.rs
This PR does several trivial refactor/fix:
- Refactor: simplify build_compaction_group_info, as member_table_ids is now included in hummock version.  Note that even after this PR, [this comment](https://github.com/risingwavelabs/risingwave/blob/d30a96e2150a568d906922708f8ae0e3cd376a4b/src/storage/src/hummock/compactor/shared_buffer_compact.rs#L63) stands correct because compute node's hummock version may have not been updated to contain the new table id.
- Fix: fix entry leaking of read_version_mapping_guard.
- Fix: add a notification for backup manager.
Please …
=> refactor(storage): simplify build_compaction_group_info

Cargo.lock, src/object_store/src/object/s3.rs, src/tests/simulation/Cargo.toml
This PR tries to fix the occasional timeout of recovery test. fix #7979.
The timeout was caused by a deadlock in the cascade drop when killing a node. It is a bug in madsim.
I have fixed it in https://github.com/madsim-rs/madsim/pull/125 so this PR is simply a version bump.
This PR also contains an improvement to the etcd simulator inspired by today's PoC meeting.
It will raise an `etcdserver: request is too large` error when the request is larger than 1.5MB. https://github.com/madsim-rs/madsim/pull/124
=> fix(test): fix occasional timeout of recovery test

src/meta/src/backup_restore/restore.rs, src/storage/backup/integration_tests/common.sh, src/storage/backup/integration_tests/run_all.sh, src/storage/backup/integration_tests/test_query_backup.sh
Add logs to troubleshoot flaky test in #7850
</details>
=> chore(ci): add log for flaky meta backup test

ci/workflows/main.yml
In the release CI yaml, there is no item named `build`, which is different to the PR CI. Therefore, the CI in PR works, but fails on release CI. This PR fix it.
</details>
=> fix(ci): make java-binding-e2e release test depends on build-release

Cargo.lock, dashboard/proto/gen/catalog.ts, dashboard/proto/gen/plan_common.ts, proto/catalog.proto, proto/plan_common.proto, src/connector/Cargo.toml, src/connector/src/common.rs, src/connector/src/parser/avro/parser.rs, src/connector/src/parser/avro/schema_resolver.rs, src/connector/src/parser/debezium/avro_parser.rs, src/connector/src/parser/json_parser.rs, src/connector/src/parser/mod.rs, src/connector/src/source/base.rs, src/connector/src/source/kafka/mod.rs, src/connector/src/source/kafka/source/message.rs, src/connector/src/source/kafka/source/reader.rs, src/frontend/src/handler/create_source.rs, src/source/src/source_desc.rs, src/sqlparser/src/ast/statement.rs, src/sqlparser/src/keywords.rs
To support `upsert-kafka` in a manner similar to [how Flink does](https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/connectors/table/upsert-kafka/), the key field of a Kafka message is used to indicate the values of the primary key column. If the value field of the message is not empty, the row will be inserted or updated. If the value field is empty, the row will be deleted. This behavior is not tied to any specific row format.
A Kafka connector with the `upsert` property enabled will produce `UpsertMessage`s encoded in bytes, instead of raw Kafka message values, as `SourceMessage`s.
The row formats …
=> feat: kafka-upsert with json,avro format

e2e_test/streaming/nexmark/views/q5.slt.part, src/frontend/planner_test/tests/testdata/nexmark.yaml, src/frontend/planner_test/tests/testdata/nexmark_source.yaml, src/frontend/planner_test/tests/testdata/share.yaml, src/tests/simulation/src/nexmark/q5.sql
- Reorder `GROUP BY window_start, bid.auction` into `GROUP BY bid.auction, window_start`, so that we can share a large sub-plan.
- Theoretically, the ordering in group-by clause doesn't matter, however, in our LogicalAgg implementation, we store them in a `vec` so the ordering matter in terms of common sub-plan detection.
- Other (please specify in …
=> chore(streaming): rewrite nexmark q5 to benefit from common sub-plan sharing

src/common/src/array/jsonb_array.rs, src/common/src/types/mod.rs, src/common/src/types/scalar_impl.rs
We already have macro `for_all_scalar_variants! { impl_convert }` that generates `From<Foo> for ScalarImpl`. No need to repeat it.
=> refactor(common): DRY `Scalar::to_scalar_value`

README.md
Sometimes GitHub sets it to visible, but sometimes not. 😅 It seems this happens when single theme is used.
=> doc: Let logo always visible

src/meta/src/hummock/compaction/picker/tier_compaction_picker.rs
=> fix(meta): fix pick a single level and repeated compact task (#8141)

src/frontend/planner_test/tests/testdata/agg.yaml, src/frontend/src/optimizer/plan_node/batch_hash_agg.rs, src/frontend/src/optimizer/plan_node/logical_agg.rs, src/frontend/src/optimizer/plan_node/stream_hash_agg.rs, src/frontend/src/optimizer/property/distribution.rs, src/tests/sqlsmith/src/lib.rs, src/tests/sqlsmith/src/runner.rs
- Fixes #7928 
- Use the right group key.
- Do proper checks on distribution to see if 2 phase agg is needed.
- Clean up `gen_dist_stream_agg_plan` logic.
- Re-enable fuzzing for 2 phase agg.
</details>
=> fix(streaming): two phase agg group key

src/common/src/session_config/mod.rs
=> fix(frontend): fix show all for force_two_phase_agg

src/risedevtool/connector.toml
=> chore(risedev): bump risedev connector node version

Cargo.lock, src/frontend/planner_test/tests/testdata/nexmark.yaml, src/frontend/planner_test/tests/testdata/nexmark_source.yaml, src/stream/src/common/table/state_table.rs, src/tests/simulation/Cargo.toml, src/tests/simulation/src/nexmark.rs, src/tests/simulation/src/nexmark/create_source.sql, src/tests/simulation/src/nexmark/q106.sql, src/tests/simulation/src/nexmark/q15.sql, src/tests/simulation/src/nexmark/q18.sql, src/tests/simulation/src/utils.rs, src/tests/simulation/tests/it/nexmark_chaos.rs, src/tests/simulation/tests/it/nexmark_q4.rs, src/tests/simulation/tests/it/nexmark_source.rs
This PR adds some tests to cover more operators in nexmark chaos tests.
- ~Add watermark column for nexmark-chaos and `nexmark_source.yaml`, to cover `WatermarkFilter`.~ Watermark does not survive scaling test, will investigate later.
- q15: Covers append-only hash aggregation with `distinct`.
- q18: Covers group top-n (possibly deduplication in the future).
- q106: self-made, covers two-phase stateful simple aggregation. (Close #7788)
- …
=> test(scale): cover more operators in nexmark chaos tests

src/stream/src/executor/hash_join.rs, src/stream/src/executor/watermark/mod.rs, src/tests/simulation/src/main.rs, src/tests/simulation/tests/it/nexmark_source.rs
Fix unwrap panic when scaling the `BufferedWatermark` and add a simple test for that.
- Close #8203
</details>
=> fix(watermark): fix merge watermark on scale

src/cmd_all/src/bin/risingwave.rs
clearer err msg
```
> ./target/debug/risingwave 
Error: unknown target: risingwave
Please either:
* set `RW_NODE` env variable (`RW_NODE=<component>`)
* create a symbol link to `risingwave` binary (ln -s risingwave <component>)
* start with subcommand `risingwave <component>``
with one of the following: ["compactor", "compactor-node", "compactor_node", "compute", "compute-node", "compute_node", "ctl", "frontend", "frontend-node", "frontend_node", "meta", "meta-node", "meta_node", "play", "playground", "risectl"]
```
@JuchangGit hope this is clearer for you.
Should fix: …
=> feat(cmd_all): sort component strings in err msg

src/sqlparser/src/ast/mod.rs, src/sqlparser/src/ast/value.rs, src/sqlparser/src/parser.rs, src/sqlparser/src/tokenizer.rs, src/sqlparser/tests/sqlparser_postgres.rs
This PR cherry-picks the feature of parsing dollar-quoted string from the upstream sqlparser-rs.
This syntax may be used for inline scripts in other languages, for example:
```sql
create function ... language python as $$
def int_42():
return 42
$$
```
=> feat(parser): parse dollar quoted string

docker/Dockerfile
Previously when using RisingWave via docker, dashboard artifact is proxied to GitHub, so it's not accessible without internet connection. This PR adds dashboard artifact to the docker image and use the local one.
</details>
=> feat: package dashboard artifact in docker image

src/frontend/src/optimizer/logical_optimization.rs
This PR does not change the optimizer's behavior except bring forward the `UNION_MERGE` rule. I think it is mixed into unnesting logic by mistake.
extract some common logic into functions.
- predicate pushdown
- unnesting
- col prune
The PR do not change them:
- join reorder, because we will have a different strategy for streaming soon. https://github.com/risingwavelabs/rfcs/pull/23
- optimization about OverWindow, because we might implement the execution with separate progress.
=> refactor(optimizer): refine logical optimizer

src/connector/src/source/filesystem/s3/enumerator.rs, src/connector/src/source/filesystem/s3/mod.rs, src/connector/src/source/filesystem/s3/source/reader.rs
We should allow user to use other S3-compatible server in our S3 connector.
- `s3.endpoint_url` parameter was added into s3 connector.
- Support  S3-compatible server in S3 connector.
</details>
=> feat(connector): allow custom s3 endpoint

src/connector/src/macros.rs, src/connector/src/parser/mod.rs, src/connector/src/source/filesystem/mod.rs, src/connector/src/source/filesystem/nd_streaming.rs, src/connector/src/source/filesystem/s3/source/reader.rs, src/source/src/source_desc.rs
`NdByteStreamWrapper` has been introduced to bridge any parser made for a message-based stream to a file-based (byte) stream by segmenting the stream using the newline character '\n' as the delimiter. Thus, we can unify the parsing process for row formats such as CSV and ndjson, and reuse the parsers.
----
I will create a new PR to refactor the current CSV parser to adopt this.
=> feat(connector): nd-stream wrapper

e2e_test/batch/types/jsonb.slt.part, src/expr/src/sig/func.rs, src/tests/regress/data/sql/jsonb.sql
Add the missing support to use `jsonb` as input to `IS [NOT] NULL`. Also add tests for similar functions that are supposed to work for all types: `CASE WHEN`, `COALESCE`.
Note that `bytea` will be handled separately. Functions based on comparison (e.g. `IS DISTINCT FROM`, `NULLIF`, `IN`) are left out purposely.
Support jsonb IS [NOT] NULL.
=> feat(expr): jsonb IS [NOT] NULL

dashboard/proto/gen/hummock.ts, proto/hummock.proto, src/ctl/src/cmd_impl/hummock/compaction_group.rs, src/ctl/src/lib.rs, src/meta/src/hummock/manager/compaction_group_manager.rs, src/meta/src/hummock/manager/tests.rs, src/meta/src/hummock/manager/worker.rs, src/meta/src/rpc/service/hummock_service.rs, src/rpc_client/src/meta_client.rs, src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs, src/storage/hummock_test/src/sync_point_tests.rs
This PR exposes RPC to split a compaction group into two.
Also add corresponding risectl cmd.
</details>
=> feat(compaction):  support split compaction group

src/common/src/util/column_index_mapping.rs, src/frontend/src/optimizer/mod.rs
fix #8216 
```
dev=>     create table t(x int);
CREATE_TABLE
dev=> explain create materialized view mv as     SELECT t.x x1, t.x x2 FROM t join t tt ON t.x=tt.x;
QUERY PLAN                                                                                       
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
StreamMaterialize { columns: [t.x(hidden), x1, t._row_id(hidden), t._row_id#1(hidden), t.x#1(hidden), x2], pk_columns: [t._row_id, t._row_id#1, x2, t.x#1], pk_conflict: "no check" } …
```
=> fix(optimizer): handle non-injective changes of `logical_rewrite_for_stream`

Cargo.lock, src/compute/Cargo.toml, src/compute/src/memory_management/memory_manager.rs, src/compute/src/memory_management/mod.rs, src/compute/src/memory_management/policy.rs, src/compute/src/server.rs
This PR introduces an abstraction for memory control policy: `trait MemoryControl`, and implements this trait on `FixedProportionPolicy` (the new memory control policy introduced in #7767) and `StreamingOnlyPolicy` (the policy we used before). We could implement this trait on various memory control policies in the future.
Related issue: #8228
- Other …
=> refactor: introduce memory control policy abstraction

src/tests/simulation/src/main.rs
This PR fixes the panic when running simulation multiple times:
```sh
MADSIM_TEST_NUM=2 ./risedev sslt ...
```
=> fix(test): fix the panic of repeated logger initialization

src/compute/Cargo.toml, src/compute/src/memory_management/policy.rs
Fix the compile error on macos introduced by #8253.
```
error[E0432]: unresolved import `tikv_jemalloc_ctl`
--> src/compute/src/memory_management/policy.rs:220:9
|
220 |     use tikv_jemalloc_ctl::{epoch as jemalloc_epoch, stats as jemalloc_stats};
|         ^^^^^^^^^^^^^^^^^ use of undeclared crate or module `tikv_jemalloc_ctl`
```
=> fix: fix build on macos

ci/scripts/e2e-source-test.sh, e2e_test/source/cdc/cdc.check_new_rows.slt, src/meta/src/manager/catalog/mod.rs, src/meta/src/rpc/ddl_controller.rs
fix #8290 
as title
</details>
=> fix(meta): allow `create table` have multiple state tables

src/common/benches/bench_row.rs, src/common/src/array/arrow.rs, src/common/src/types/mod.rs, src/connector/src/source/nexmark/source/combined_event.rs, src/frontend/src/catalog/system_catalog/rw_catalog/rw_meta_snapshot.rs, src/frontend/src/handler/describe.rs, src/frontend/src/handler/explain.rs, src/frontend/src/handler/show.rs, src/frontend/src/handler/util.rs, src/frontend/src/handler/variable.rs, src/frontend/src/session.rs, src/utils/pgwire/src/pg_extended.rs
These const were introduced to mimic `postgres_types::Type` (https://github.com/risingwavelabs/risingwave/pull/6335#discussion_r1041961956). However their `Type` is an opaque wrapper and `Inner` enum is not exposed. These consts were the only way to access them. In our case we use the enum directly.
=> refactor(common): cleanup DataType const

ci/workflows/pull-request.yml, docs/developer-guide.md
Add developer docs as well.
</details>
=> fix(ci): add build depends for sqlsmith

src/compute/src/server.rs
As title. When there's no enough memory for computing tasks, we use 512MB as the default total value for computing memory control.
User will get a warning in the log instead of panicking when there's no enough memory for computing tasks.
</details>
=> fix: turn panic into warning when there's no enough memory for computing tasks

src/common/src/array/mod.rs, src/common/src/array/serial_array.rs, src/common/src/types/mod.rs, src/common/src/types/scalar_impl.rs, src/common/src/types/to_binary.rs, src/common/src/util/value_encoding/mod.rs
This pull request adds a new module, `serial_array`, to the `src/common/src/array/` directory, which contains an implementation for the `Serial` type. `Serial` has been included in the list of `Scalar` variants in `src/common/src/types/mod.rs`, with corresponding implementations for `Scalar` and `ScalarRef`. The `ScalarRefImpl`'s implementation of `ToBinary` now includes `Serial` in the match statement. Additionally, `serialize_scalar()` in `src/common/src/util/value_encoding/mod.rs` has been modified to handle `Serial`.
~- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new …
=> feat(common): introduce Serial as Scalar and ScalarRef

.gitignore, Makefile.toml, connector_node/.gitignore, src/risedevtool/common.toml, src/risedevtool/connector.toml, src/risedevtool/src/bin/risedev-config.rs
add new option `Build RisingWave Connector from source` in `risedev configure` to allow building connector node from source each time. 
if you just want to use connector node, it is ok to just open `[Component] RisingWave Connector`. It will download the latest release from the Internet. 
~~- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created …
=> feat(risedev): risedev support for connector node

src/meta/src/rpc/election_client.rs, src/meta/src/rpc/server.rs, src/meta/src/storage/wrapped_etcd_client.rs
Signed-off-by: Shanicky Chen <peng@risingwave-labs.com>I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).
as title
This patch refactors the wrapped etcd client with macro. The changes consist of 93 insertions and 222 deletions across 3 files: election_client.rs, server.rs, and wrapped_etcd_client.rs.
The main modification is replacing the usage of `EtcdRefreshClient` with `WrappedEtcdClient` in `election_client.rs`. The `WrappedEtcdClient` is a client struct that can either wrap the `EtcdClient` or the `EtcdRefreshClient`. This allows the client to refresh its connection when it encounters an error.
In server.rs, `WrappedEtcdClient` is created with an additional …
=> chore: refactor wrapped etcd client with macro

src/sqlparser/src/parser.rs, src/sqlparser/tests/sqlparser_postgres.rs
disable single-quoted strings as aliases for column or table
disable single-quoted strings as aliases for column or table
</details>
=> fix(parser): disable single-quoted strings as aliases for column or table

Cargo.toml, ci/scripts/build.sh, docker/Dockerfile, docker/aws/aws-build.sh
This PR did 2 things:
1. Reduce the size of debuginfo in binary by setting `debug = 1`. Inspired by https://users.rust-lang.org/t/why-are-debug-symbols-so-huge/81117/2.
<details>
<summary>The stacktrace under `debug = 1` looks like...</summary>
```
Custom backtrace:
0: risingwave_frontend::handler::explain::handle_explain::{{closure}}
at ./src/frontend/src/handler/explain.rs:46:42
1: risingwave_frontend::handler::handle::{{closure}}
at ./src/frontend/src/handler/mod.rs:164:81
2: <core::pin::Pin<P> as core::future::future::Future>::poll
at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/future/future.rs:1 …
```
=> fix: reduce debuginfo size

proto/task_service.proto, src/batch/src/execution/local_exchange.rs, src/batch/src/rpc/service/task_service.rs, src/batch/src/task/task_execution.rs, src/batch/src/task/task_manager.rs, src/frontend/src/scheduler/distributed/stage.rs, src/frontend/src/scheduler/error.rs
Fix scheduler logic to avoid task leak when batch task failed.
=> fix: Fix task leak when task failed

src/connector/src/source/filesystem/nd_streaming.rs
This pr has changed the computation method of the offset for the SourceMessage. Fix the potential bugs issued by wrong segments number when file is large.
=> fix(ndstream): bad segments when data is large

src/batch/src/task/task_execution.rs
Fix a bug which will report task status as unspecified.
Closes #8360 
Fix #8360
=> fix(batch): Fix task report status unspecified.

e2e_test/ddl/alter_table_column.slt, src/frontend/src/handler/alter_table_column.rs, src/frontend/src/handler/mod.rs, src/meta/src/error.rs, src/meta/src/rpc/ddl_controller.rs
- Make the handler take an `Operation` to also support dropping columns.
- Tweak the error reporting for dropping a being-referenced column. This is naturally achieved by #8094 since we'll fail to map them with the index mapping so there's temporarily no need to implement some sort of column ref count unless we need a more detailed error message.
- There are some false positives here since we always reference all columns when creating a materialized view now. We should fix this in #4529.
- Add some e2e tests.
Note: this is still not user-facing like #8063.
Close #8351. …
=> feat(frontend): support `DROP COLUMN`

src/storage/src/monitor/monitored_store.rs
This PR fixes #8279. 
TL;DR, we suspect there is a compiler bug causing incorrect variable binding/moving when generator is used. More details can be found in #8279. 
We are still tracing down the root cause but this PR is proved working. …
=> fix: fix storage read iter metrics

dashboard/proto/gen/data.ts, dashboard/proto/gen/task_service.ts, proto/data.proto, src/common/src/array/arrow.rs, src/common/src/array/column_proto_readers.rs, src/common/src/array/mod.rs, src/common/src/array/primitive_array.rs, src/common/src/array/serial_array.rs, src/common/src/array/value_reader.rs, src/common/src/hash/key.rs, src/common/src/test_utils/rand_array.rs, src/common/src/types/mod.rs, src/common/src/types/native_type.rs
- Implemented `HashKeySerDe` for `Serial`
- Added support for `Serial` to various functions and modules in the codebase
- Defined `SerialArrayBuilder` and `SerialArray` types for building and representing arrays of `Serial`
- Modified tests to reflect these changes
The purpose of these changes is to add support for a new `SERIAL` type and enable its usage in various functions and modules in the codebase. This is done by defining `SerialArrayBuilder` and `SerialArray` types for building and representing arrays of `Serial`. The changes also include updating tests to reflect these new additions.
~- [ ] I have added fuzzing …
=> feat(common): introduce SerialArrayBuilder and SerialArray

e2e_test/batch/basic/lookup_join.slt.part, src/batch/src/task/task_execution.rs, src/frontend/src/scheduler/distributed/stage.rs
This's a workaround to fix query hang in frontend found in deterministic recovery test. When CN nodes are killed during query execution, the control flow is not interrupted and there is no event emitted. IIUC, it should be handled by the following code block, but unfortunately not. I'm not sure if this has anything to do with madsim, Cc @wangrunji0408 . Anyways, Let's fix it and revert it if it is a madsim issue.
```
Err(e) => {
// rpc error here, we should also notify stage failure
error!(
"Fetching task status in stage {:?} failed, reason: {:?}",
self.stage.id,
e.message()
);
```
<details><summary>Click here for …
=> fix: fix query hang when CN get killed

ci/workflows/main.yml
=> fix: Increase scale test timeout

ci/workflows/main-cron.yml
=> fix: Increase timeout of determined scaling test

src/common/src/util/value_encoding/column_aware_row_encoding.rs
Add harder tests to cover `u16` and `u32` offsets for `ColumnAwareSerde`.
Add harder tests to cover `u16` and `u32` offsets for `ColumnAwareSerde`.
- Refer to a related PR or issue link (optional)
#8394 
=> test: harder unit tests for `ColumnAwareSerde`

src/sqlparser/src/parser.rs
report error when using APPEND ONLY in debug model, previously we just fail to recognize the key words.
</details>
=> chore: report error when using APPEND ONLY with debug assertions off

src/common/src/catalog/column.rs, src/prost/helpers/src/lib.rs
...so that we don't need to manually `use Message as ProtoMessage` everywhere and the compiler will help us with auto-completion when we type `Pb`. Thanks @richardchien for the inspiration.
An example is shown in `column.rs`.
</details>
=> refactor(proto): auto derive a Pb-prefixed alias for proto message types

java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/metrics/ConnectorNodeMetrics.java
See the code changes 🤣
</details>
=> fix(connector-node): promethus listen port

src/tests/regress/data/expected/interval.out, src/tests/regress/data/sql/interval.sql
Similar to #8386 which handles `timestamp.out` and `timestamptz.out`.
Unlike the 2 files above, styles are already explicitly set and independent to environment. But when the subject being tested is not related to textual output style, we still want the default style `IntervalStyle=postgres`.
`horology.out` may need similar treatment, but deferred until more familiar with test cases inside.
=> test(regress): re-generate expected/interval.out using default IntervalStyle

src/common/src/types/chrono_wrapper.rs, src/common/src/types/decimal.rs, src/common/src/types/mod.rs
support `from_text` and `from_binary` to create ScalarImpl.
These function will be used later to convert a param to a ScalarImpl. #8112
</details>
=> feat(common): support from_binary and from_text in ScalarImpl

src/common/src/array/interval_array.rs, src/common/src/types/interval.rs, src/common/src/types/mod.rs
In preparation of #4514, we first cleanup some unused methods to make the update easier.
* `from_protobuf_bytes` and `to_protobuf_owned` no longer used. See #8452 for current implementation in use. There have been 3 versions and we are removing one here, leaving 2 to be consolidated later.
* `get_years` can be confusing and thus removed.
* `total_ms` is same as `as_ms_i64`.
* `as_ms_i64` and `from_total_ms` marked as deprecated. They completely defeat the purpose of defining `IntervalUnit` rather than using `Duration`. Actually fixes to replace them will be done after the ms -> us update.
The whole plan is:
* Cleanups …
=> refactor(common): cleanup unused methods on `IntervalUnit`

src/cmd_all/src/bin/risingwave.rs
It's still too noisy:
```
2023-03-07T19:32:08.823380Z  INFO risingwave_storage::hummock::event_handler::uploader: epoch 3996537836142592 is sealed
2023-03-07T19:32:08.823399Z  INFO risingwave_storage::hummock::event_handler::uploader: epoch 3996537836142592 to seal has no data
2023-03-07T19:32:09.822730Z  INFO risingwave_storage::hummock::event_handler::uploader: epoch 3996537901678592 is sealed
2023-03-07T19:32:09.822750Z  INFO risingwave_storage::hummock::event_handler::uploader: epoch 3996537901678592 to seal has no data
2023-03-07T19:32:10.823186Z  INFO risingwave_storage::hummock::event_handler::uploader: epoch …
```
=> chore: change storage log level to WARN for playground

src/batch/src/executor/hop_window.rs, src/common/src/array/arrow.rs, src/common/src/array/interval_array.rs, src/common/src/types/interval.rs, src/expr/benches/expr.rs, src/expr/src/expr/expr_binary_nonnull.rs, src/expr/src/expr/expr_literal.rs, src/expr/src/table_function/generate_series.rs, src/expr/src/vector_op/tests.rs, src/frontend/src/binder/expr/value.rs, src/stream/src/executor/hop_window.rs
Some of these constructors needs a signature update to be fully correct: return `Option`, `Result` or be named `_uncheck`. Based on their existing usage, this PR just makes them test-only before deciding the proper signature.
Note that `#[cfg(test)]` does not allow crate B's tests to use functions defined from crate A. So we are just hiding the methods behind a trait `IntervalUnitTestExt`. The trait is also behind a separate mod to avoid accidental `use types::*`, which we may also want to forbid later.
Besides tests, these constructors are also used in the interval parsing logic. They are replaced by an equivalent …
=> refactor(common): make certain `IntervalUnit` constructors test-only

Makefile.toml, ci/scripts/e2e-iceberg-sink-test.sh, e2e_test/sink/iceberg_sink.slt, java/connector-node/connector-api/src/main/java/com/risingwave/connector/api/TableSchema.java, java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/JsonDeserializer.java, src/risedevtool/connector.toml
As titled. Current code will return `Integer` for `INT64`, and cause iceberg sink to get error. In this PR we fix the problem and update the ci to cover the case.
Besides, we support running connector node with java 17, and the `./risedev d` can avoid rebuilding connector node from source if the project has been built previously. To force rebuild, we can set `REBUILD_CONNECTOR_NODE=1`.
- …
=> fix(sink): fix connector node sink json payload serialization

src/batch/src/rpc/service/task_service.rs, src/batch/src/task/task_execution.rs, src/batch/src/task/task_manager.rs
=> refactor: Remove state reporter for local mode

src/meta/src/barrier/command.rs, src/meta/src/barrier/recovery.rs, src/meta/src/stream/stream_manager.rs
`wait_epoch` should be called in recovery to ensure that each actor can read the latest `HummockVersion`.
View details in #8467 
link #8199 
</details>
=> fix(recovery): wait_epoch should be called in recovery (close #8467)

src/common/src/types/mod.rs, src/common/src/util/schema_check.rs
See `for_all_type_pairs`. We can use this macro to easily check whether a logical type matches a physical type.
</details>
=> refactor: use a macro for logical vs physical type matching

risedev.yml, src/compute/src/lib.rs, src/compute/src/memory_management/policy.rs, src/compute/src/server.rs, src/risedevtool/src/service_config.rs, src/risedevtool/src/task/compute_node_service.rs
As title. Make the memory control policy configurable to users. See #8439 for details.
Closes #8439
2 more options for users to specify in `risedev.yml` for compute node configuration: `memory-control-policy` and `streaming-memory-proportion`. Currently, valid values for `memory-control-policy` are "streaming-only" and "streaming-batch". `streaming-memory-proportion` only works when `memory-control-policy` is set to "streaming-batch", and must fall …
=> feat: user configurable memory control policy

src/frontend/src/optimizer/plan_node/stream_sink.rs
Currently, our iceberg sink will fail easily with multiple concurrency, because iceberg support poorly on concurrent commit on metadata. Therefore, we may temporarily enforce the parallelism of iceberg sink to 1. 
We shall have a plan to support a centralized coordinator or committer for sinks like iceberg that requires communication between different sink parallelism. …
=> feat(sink): set parallelism of iceberg sink to 1

src/common/src/util/chunk_coalesce.rs, src/stream/src/common/builder.rs
Do not panic but only warn about dropping a non-empty builder or iterator. See #8491 for more details.
- Close #8491.
</details>
=> fix(common): only warn on dropping non-empty builder

src/frontend/src/handler/mod.rs, src/utils/pgwire/src/pg_response.rs
Fix https://github.com/risingwavelabs/risingwave/issues/7976
With this PR
```
dev=> SHOW TRANSACTION ISOLATION LEVEL;
transaction isolation level 
-----------------------------
READ_COMMITTED
(1 row)
dev=> SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
NOTICE:  Ignored temporarily. See detail in issue#2541
SET_TRANSACTION
```
~- [x] My PR **DOES NOT** contain user-facing changes.~
- Support `SET SESSION CHARACTERISTICS AS …
=> feat(frontend): support SET SESSION CHARACTERISTICS AS TRANSACTION

dashboard/proto/gen/data.ts, e2e_test/batch/types/interval.slt.part, e2e_test/batch/types/temporal_arithmetic.slt.part, proto/data.proto, src/batch/src/executor/order_by.rs, src/common/src/array/arrow.rs, src/common/src/array/column_proto_readers.rs, src/common/src/hash/key.rs, src/common/src/row/owned_row.rs, src/common/src/test_utils/rand_array.rs, src/common/src/types/chrono_wrapper.rs, src/common/src/types/interval.rs, src/common/src/types/mod.rs, src/common/src/util/value_encoding/mod.rs, src/connector/src/parser/avro/parser.rs, src/connector/src/parser/avro/util.rs, src/expr/src/vector_op/arithmetic_op.rs, src/expr/src/vector_op/cast.rs, src/expr/src/vector_op/tumble.rs, src/frontend/src/optimizer/plan_node/logical_hop_window.rs, src/stream/src/executor/watermark_filter.rs
Fixes #4514
This PR mostly replaces the `ms` field with `usecs`, and the constructor `new` with `from_month_day_usec`. The bugs related to overflows or variable length month / day are not fixed yet, to keep this PR focused on the unit change.
Note the valid range reduced from `- (2 ^ 63) ms` .. `2 ^ 63 - 1 ms` to `- (2 ^ 63) us` .. `2 ^ 63 - 1 us`
**Breaking change**:
* protobuf in both `data.proto/IntervalUnit` and `data.proto/Datum`. (Why 2? See #8452)
* memcomparable encoding / HashKeySerSe
* value encoding
FYI regarding the fractional second unit of an interval:
* PostgreSQL uses `us` as `i64`
* …
=> fix(common): interval should have microsecond precision

src/stream/src/executor/backfill.rs, src/stream/src/executor/chain.rs, src/stream/src/executor/dispatch.rs, src/stream/src/executor/integration_tests.rs, src/stream/src/executor/mod.rs, src/stream/src/executor/rearranged_chain.rs
In #8094 we forgot to also map the watermark with the output indices in the dispatcher. 😰 This PR fixes this issue, and also adds the `output_indices` support for Round-robin Dispatcher.
</details>
=> fix(streaming): map watermark in dispatcher with output indices

src/common/src/system_param/mod.rs, src/compute/src/server.rs, src/meta/src/backup_restore/backup_manager.rs, src/meta/src/rpc/server.rs, src/storage/backup/integration_tests/run_all.sh, src/storage/backup/integration_tests/test_set_config.sh, src/storage/backup/src/storage.rs, src/storage/src/hummock/backup_reader.rs, src/storage/src/hummock/mod.rs, src/storage/src/store_impl.rs, src/tests/compaction_test/src/delete_range_runner.rs
This PR makes system params `backup_storage_url` and `backup_storage_directory` mutable.
These 2 params are used by both meta node and compute node. They are updated in a similar way:
- watch system params changes.
- recreate underlying storage that stores meta snapshot, if any of the 2 params has been changed.
- Other (please specify in the release …
=> feat(backup): support mutating backup config

src/frontend/planner_test/tests/testdata/subquery.yaml, src/frontend/src/optimizer/plan_visitor/max_one_row_visitor.rs
=> fix(optimizer): ban scalar subquery for project set

e2e_test/streaming/bug_fixes/issue_8084.slt, src/frontend/planner_test/tests/testdata/join.yaml, src/frontend/src/optimizer/plan_node/logical_filter.rs, src/frontend/src/optimizer/plan_node/logical_join.rs
a work around to #8084 
we need fix to ban the query when we have a better not null property analyze in optimizer,
</details>
=> fix(streaming): ignore null stream key from full outer join to workaround

src/frontend/planner_test/tests/testdata/agg.yaml, src/frontend/src/catalog/index_catalog.rs, src/frontend/src/optimizer/plan_node/logical_scan.rs, src/frontend/src/optimizer/rule/min_max_on_index_rule.rs, src/frontend/src/optimizer/rule/top_n_on_index_rule.rs
- Support index selection for sort aggregation with a descending ordering.
</details>
#8511
=> feat(batch): Support index selection for sort aggregation with a descending ordering

src/compute/src/memory_management/memory_manager.rs, src/compute/src/memory_management/mod.rs, src/compute/src/memory_management/policy.rs, src/compute/src/server.rs
Refine conditional compilation for mem control by introducing `DummyPolicy` for non-Linux OS.
</details>
=> refactor: refine conditional compilation for mem control on different OSs

ci/workflows/main.yml
As title, to resolve the recent timeouts on main branch CI.
</details>
=> fix(ci): increase scaling test timeout for nexmark recovery test

ci/scripts/deterministic-e2e-test.sh, ci/workflows/pull-request.yml, src/tests/sqlsmith/scripts/gen_queries.sh, src/tests/sqlsmith/src/sql_gen/scalar.rs
- Fuzz testing for sqlsmith is still useful, can see if we caused something severe. But don't want it to block PR.
- Use `soft_fail` instead, so we can still merge even if fuzz testing fails.
- Ensure snapshot for `main`, `pr` and `main-cron` is run entirely, to avoid discrepancies.
</details>
=> fix(ci): run entire snapshot in `main`, `pr` and `main-cron` workflows

src/utils/pgwire/src/pg_protocol.rs, src/utils/pgwire/tests/js/test/pgwire.test.ts
=> fix(pgwire): process empty query correctly

dashboard/proto/gen/stream_plan.ts, proto/stream_plan.proto, src/common/src/catalog/column.rs, src/frontend/src/optimizer/plan_node/logical_scan.rs, src/frontend/src/optimizer/plan_node/stream_index_scan.rs, src/frontend/src/optimizer/plan_node/stream_table_scan.rs, src/storage/src/table/batch_table/storage_table.rs, src/stream/src/executor/backfill.rs, src/stream/src/from_proto/chain.rs
This is a prerequisite of #4529. TL;DR:
```
CREATE TABLE t (k INT PRIMARY KEY, v1 INT, v2 INT);
CREATE MATERIALIZED VIEW mv AS SELECT v1 FROM t;
Before:
- dispatcher -> merge -> chain: [k, v1, v2]
- historical data
- (non-backfill) batch-plan -> chain: [v1]
- (backfill) table scan -> [k, v1, v2]
- chain -> ..: [v1]
After this PR:
- dispatcher -> merge -> chain: [k, v1, v2]
- historical data
- (non-backfill) batch-plan -> chain: [v1]
- (backfill) table scan -> [k, v1] (k is required for backfill)
- chain -> ..: [v1]
After #4529:
- dispatcher -> merge -> chain
- (non-backfill) …
```
=> refactor(streaming): only scan necessary columns in backfill

src/frontend/src/binder/expr/mod.rs, src/frontend/src/binder/mod.rs, src/frontend/src/expr/expr_mutator.rs, src/frontend/src/expr/expr_rewriter.rs, src/frontend/src/expr/expr_visitor.rs, src/frontend/src/expr/function_call.rs, src/frontend/src/expr/mod.rs, src/frontend/src/expr/parameter.rs, src/frontend/src/expr/utils.rs, src/frontend/src/optimizer/plan_expr_rewriter/const_eval_rewriter.rs
To complete #8112, We need to support infer the parameter and bind the parameter. This PR
- add Parameter expr
- infer param type and collect in param_types in binder 
Summarize the rule of infer the parameter:
1. param type provide by user explicitly
2. param type infer from cast. We will infer the type from the first cast, the latter will be consider as cast.
e.g. `select $1::int,$1::varchar`, $1 will be considered as INT4, the $1::varchar will be consider as cast int to varchar.
3. param as varchar …
=> feat(frontend): support infer param in binder

src/frontend/src/optimizer/plan_node/generic/agg.rs, src/frontend/src/optimizer/plan_node/generic/expand.rs, src/frontend/src/optimizer/plan_node/generic/filter.rs, src/frontend/src/optimizer/plan_node/generic/hop_window.rs, src/frontend/src/optimizer/plan_node/generic/join.rs, src/frontend/src/optimizer/plan_node/generic/mod.rs, src/frontend/src/optimizer/plan_node/generic/project.rs, src/frontend/src/optimizer/plan_node/generic/project_set.rs, src/frontend/src/optimizer/plan_node/generic/scan.rs, src/frontend/src/optimizer/plan_node/generic/share.rs, src/frontend/src/optimizer/plan_node/generic/source.rs, src/frontend/src/optimizer/plan_node/generic/top_n.rs, src/frontend/src/optimizer/plan_node/generic/union.rs, src/frontend/src/optimizer/plan_node/logical_agg.rs, src/frontend/src/optimizer/plan_node/logical_expand.rs, src/frontend/src/optimizer/plan_node/logical_filter.rs, src/frontend/src/optimizer/plan_node/logical_hop_window.rs, src/frontend/src/optimizer/plan_node/logical_join.rs, src/frontend/src/optimizer/plan_node/logical_project.rs, src/frontend/src/optimizer/plan_node/logical_project_set.rs, src/frontend/src/optimizer/plan_node/logical_scan.rs, src/frontend/src/optimizer/plan_node/logical_share.rs, src/frontend/src/optimizer/plan_node/logical_source.rs, src/frontend/src/optimizer/plan_node/logical_union.rs, src/frontend/src/optimizer/plan_node/mod.rs, src/frontend/src/optimizer/plan_node/plan_base.rs, src/frontend/src/optimizer/plan_node/stream.rs, src/frontend/src/optimizer/plan_node/stream_derive.rs
=> refactor(optimizer): move fd derive into core

src/storage/src/hummock/sstable/mod.rs
This PR changes the layout of a SST object to encode the sst meta offset at the end of the object so that the object can be self-explained. This is a breaking change.
Related to #8252 
Please keep the types that apply to your changes, and remove the …
=> fix: move sst meta offset to the end of the object

src/meta/src/hummock/manager/compaction_group_manager.rs, src/meta/src/hummock/manager/versioning.rs, src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
avoid SST ID gap when generating SST IDs in group split
</details>
=> feat(sst id): avoid SST ID gap when generating

Cargo.lock, ci/scripts/java-binding-test.sh, java/com_risingwave_java_binding_Binding.h, java/java-binding-integration-test/src/main/java/com/risingwave/java/binding/HummockReadDemo.java, java/java-binding-integration-test/src/main/java/com/risingwave/java/binding/StreamChunkDemo.java, java/java-binding-integration-test/src/main/java/com/risingwave/java/binding/Utils.java, java/java-binding/src/main/java/com/risingwave/java/binding/BaseRow.java, java/java-binding/src/main/java/com/risingwave/java/binding/Binding.java, java/java-binding/src/main/java/com/risingwave/java/binding/HummockIterator.java, java/java-binding/src/main/java/com/risingwave/java/binding/KeyedRow.java, java/java-binding/src/main/java/com/risingwave/java/binding/StreamChunkIterator.java, java/java-binding/src/main/java/com/risingwave/java/binding/StreamChunkRow.java, src/common/src/row/owned_row.rs, src/java_binding/Cargo.toml, src/java_binding/make-java-binding.toml, src/java_binding/run_demo.sh, src/java_binding/src/bin/data-chunk-payload-generator.rs, src/java_binding/src/hummock_iterator.rs, src/java_binding/src/iterator.rs, src/java_binding/src/lib.rs, src/java_binding/src/stream_chunk_iterator.rs
In this PR, we add java binding support to read rust `StreamChunk` from java. We can now access rust `StreamChunk` via `StreamChunkIterator.java`.
Besides, the PR involves the following changes.
- Introduce `StreamChunkRow` in rust, and combine `StreamChunkRow` and `KeyedRow` into an enum as the return type for all row types returned to java so that the `StreamChunkRow` and `KeyedRow` can share the same java binding method to access row. `BaseRow.java` is introduced to support the `get<Type>` method for `StreamChunkRow` to share row acess method with `KeyedRow`.
- Rename the previous `Iterator.java` to …
=> feat(java-binding): support java binding on stream chunk

dashboard/proto/gen/data.ts, proto/data.proto, src/common/src/hash/dispatcher.rs, src/common/src/types/mod.rs, src/common/src/types/postgres_type.rs, src/common/src/util/value_encoding/mod.rs, src/connector/src/parser/common.rs, src/expr/src/expr/expr_binary_nullable.rs, src/expr/src/vector_op/cast.rs, src/frontend/src/binder/expr/mod.rs, src/frontend/src/expr/literal.rs, src/frontend/src/optimizer/rule/index_selection_rule.rs, src/tests/sqlsmith/src/sql_gen/types.rs, src/utils/pgwire/src/pg_extended.rs
https://github.com/risingwavelabs/rfcs/pull/45
This pull request introduces a new logical data type called `SERIAL` to the codebase. This new type is defined in  `proto/data.proto` files, and instantiated in `common/src/types/mod.rs`. Additionally, the code is updated to handle this new data type in various functions.
- Added the `SERIAL` data type definition to `proto/data.proto`.
- Defined the `SERIAL` data type in `common/src/types/mod.rs`.
- Updated various functions to handle the `SERIAL` data type.
- Added support for the `SERIAL` data type in `common/src/hash/dispatcher.rs`.
- Mapped the `SERIAL` data type in …
=> feat(common): Add support for DataType::Serial

src/frontend/planner_test/tests/testdata/distribution_derive.yaml, src/frontend/planner_test/tests/testdata/join.yaml, src/frontend/planner_test/tests/testdata/nexmark.yaml, src/frontend/planner_test/tests/testdata/nexmark_source.yaml, src/frontend/planner_test/tests/testdata/stream_dist_agg.yaml, src/frontend/planner_test/tests/testdata/temporal_filter.yaml, src/frontend/planner_test/tests/testdata/tpch.yaml, src/frontend/planner_test/tests/testdata/union.yaml, src/frontend/planner_test/tests/testdata/watermark.yaml, src/frontend/src/optimizer/plan_node/stream_global_simple_agg.rs, src/frontend/src/optimizer/plan_node/stream_hash_agg.rs, src/frontend/src/utils/stream_graph_formatter.rs
- add distinct table in stream agg executor
- add read_pk_prefix_len_hint in table's explaination 
</details>
=> fix(explain): add missed fields in explain streaming dist plan

Cargo.lock, src/expr/src/vector_op/round.rs
As discussed in #7819 , this unit test should be modified after upgrading `rust_decimal` to fix the rounding issue.
=> fix(common): decimal round digits test

e2e_test/batch/types/interval.slt.part, src/common/src/hash/key.rs, src/common/src/types/interval.rs
Intervals have non-trivial rules for their equality and ordering. The previous implementation does not handle overflows carefully and may result in panics or wrapping to a wrong result (and panic in later stage #8355). This PR fixes all such issues during **comparison**.
Note there are other issues in **arithmetic** and **parsing**. This PR only focuses on comparison.
The previous implementation relies on `justify_interval`, which is not a total function that selects a representative from each equivalence class.
The new implementation uses `usecs: i128` and an alternate representative as complement to this. All …
=> fix(common): interval overflow panic / wrap during comparison and justify

src/connector/src/source/base.rs, src/connector/src/source/datagen/source/generator.rs, src/connector/src/source/datagen/source/reader.rs, src/connector/src/source/manager.rs, src/source/src/connector_source.rs
This pull request adds a new field `is_visible` to the existing `Column` struct and new enum variants `Invisible` and `Visible` with associated fields to the `FieldDesc` enum.
The `is_visible` field in `Column` is used in `DatagenSplitReader` to decide whether a field should be included in the generated data. It is set when creating `Column` from `SourceColumnDesc`.
- Added `is_visible` field to `Column` struct.
- Added `Invisible` and `Visible` enum variants with associated fields to `FieldDesc` enum.
- `is_visible` field used in `DatagenSplitReader` to control data generation.
- `Column` created from …
=> chore: add is_visible in column for connector

src/frontend/planner_test/tests/testdata/over_window_function.yaml, src/frontend/planner_test/tests/testdata/predicate_pushdown.yaml, src/frontend/src/optimizer/plan_node/logical_over_agg.rs, src/frontend/src/optimizer/plan_node/logical_project_set.rs
Because our predicate push-down and column pruning use a top-down visitor pattern. Every plan node's implementation should take responsibility to call its input's method recursively.
fix https://github.com/risingwavelabs/risingwave/issues/8573
</details>
=> fix(optimizer): projectSet && overAgg should call input's predicate push down && prune col

src/frontend/planner_test/tests/testdata/join.yaml, src/frontend/src/optimizer/plan_node/batch_hash_join.rs, src/frontend/src/optimizer/plan_node/eq_join_predicate.rs, src/frontend/src/optimizer/plan_node/logical_join.rs
- Fix hash join distribution. #8537
</details>
=> fix(optimizer): fix hash join distribution

src/frontend/src/catalog/system_catalog/pg_catalog/mod.rs
- As titled.
Example:
```sql
dev=> select * from pg_class where relkind = 'n';
oid  |                  relname                  | relnamespace | relowner | relkind | relam | reltablespace
------+-------------------------------------------+--------------+----------+---------+-------+---------------
1005 | __internal_v_7_globalsimpleaggresult_1005 |            0 |        1 | n       |     0 |             0
(1 row)
```
- SQL commands, …
=> feat(meta): add internal table to pg_class

src/storage/src/table/batch_table/storage_table.rs, src/storage/src/table/mod.rs, src/stream/src/common/table/state_table.rs, src/stream/src/executor/sort.rs
=> chore: remove dist_key_indices in state table and storage table

src/tests/state_cleaning_test/data/join.toml, src/tests/state_cleaning_test/data/temporal_filter.toml
=> test(stream): add join and temporal_filter state-cleaning test

e2e_test/batch/basic/dml.slt.part, e2e_test/ddl/invalid_operation.slt, e2e_test/ddl/table.slt, src/frontend/planner_test/tests/testdata/update.yaml, src/frontend/src/binder/update.rs
ban `update` statements modifying pk columns
A bind error is returned if the binder finds any pk column is to be assigned by `update` statements;
</details>
With this pr, users cannot have `update` …
=> feat(frontend): ban `update` statements modifying pk columns

Cargo.lock, src/common/src/array/jsonb_array.rs, src/connector/src/macros.rs, src/connector/src/source/base.rs, src/connector/src/source/cdc/split.rs, src/connector/src/source/datagen/split.rs, src/connector/src/source/filesystem/file_common.rs, src/connector/src/source/google_pubsub/split.rs, src/connector/src/source/kafka/split.rs, src/connector/src/source/kinesis/split.rs, src/connector/src/source/nexmark/split.rs, src/connector/src/source/pulsar/split.rs, src/frontend/planner_test/tests/testdata/nexmark_source.yaml, src/frontend/planner_test/tests/testdata/watermark.yaml, src/frontend/src/optimizer/plan_node/generic/source.rs, src/meta/src/stream/source_manager.rs, src/storage/hummock_sdk/src/key.rs, src/stream/Cargo.toml, src/stream/src/executor/source/state_table_handler.rs
This PR uses Jsonb to store source split state instead of Bytea for better observability.
This PR also changes the column name `offset` to `offset_info` since `offset` is a pg keyword,
Note that this is a **breaking change** and old source states cannot be parsed after this PR.
```sql
dev=> show internal tables;;
Name             
-----------------------------
__internal_s1_2_source_1003
(1 row)
dev=> describe __internal_s1_2_source_1003;
Name     |     Type     
--------------+--------------
partition_id | Varchar
offset_info  | Jsonb
primary key  | partition_id
(3 rows)
dev=> select * from …
```
=> feat(source): store source split state as jsonb

src/common/src/field_generator/mod.rs, src/common/src/field_generator/timestamp.rs, src/connector/src/source/datagen/source/reader.rs
add a new field for datagen connector to prevent use `now` when generating times
the field is only valid when generating `DataType::Timestamp`.
* `fields.{}.basetime`: Optional. if set, datagen will see the given time as `now`. the format is subject to [rfc3399](https://docs.rs/chrono/latest/chrono/struct.DateTime.html#method.parse_from_rfc3339) (example `1996-12-19T16:39:57-08:00`)
~~- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track …
=> feat: make gen timestamp deterministic

java/connector-node/risingwave-sink-iceberg/src/main/java/com/risingwave/connector/SinkRowMap.java, java/connector-node/risingwave-sink-iceberg/src/main/java/com/risingwave/connector/SinkRowOp.java, java/connector-node/risingwave-sink-iceberg/src/main/java/com/risingwave/connector/UpsertIcebergSink.java, java/connector-node/risingwave-sink-iceberg/src/test/java/com/risingwave/connector/SinkRowMapTest.java
As titled. The sink row is supposed to be closed after it has been processed and should not be stored in somewhere with longer lifetime. However, the current iceberg upsert sink hold the sink row in a buffer and will access the sink row after the row has been closed, which will cause segfault for stream chunk row. …
=> fix(conector-node): do not store sink row inside upsert iceberg sink

src/stream/src/executor/actor.rs, src/stream/src/executor/dispatch.rs, src/stream/src/executor/subtask.rs
Logically the actor is dropped after we send the barrier with `Drop` mutation to the downstream，thus making the `drop`'s progress asynchronous. However, there might be a considerable amount of data in the executors' in-memory cache, dropping these structures might be a CPU-intensive task. This may lead to the runtime being unable to schedule other actors if the `drop` is called on the current thread.
Note: There's no evidence for this to be related to #8474. :(
- …
=> fix(streaming): drop actor on another blocking thread

ci/scripts/s3-source-test-for-opendal-fs-engine.sh, ci/workflows/main-cron.yml, risedev.yml
This test use s3 source to generate a slightly larger amount of data, which will last about ten minutes and will cross the checkpoint. And it will run daily on main-cron.
part of https://github.com/risingwavelabs/risingwave/issues/8266
</details>
=> feat(test): test opendal fs engine on main cron with large dataset

src/frontend/planner_test/tests/testdata/subquery_expr_correlated.yaml, src/frontend/src/optimizer/rule/apply_agg_transpose_rule.rs, src/frontend/src/optimizer/rule/apply_filter_transpose_rule.rs, src/frontend/src/optimizer/rule/apply_offset_rewriter.rs, src/frontend/src/optimizer/rule/apply_project_transpose_rule.rs, src/frontend/src/optimizer/rule/mod.rs
Fixes #4762
We used to only support `agg(inputs)` but later extended it to `agg(inputs ORDER BY exprs) FILTER (WHERE cond)`. When constructing the `LogicalAgg` node, all complex expressions in `inputs` and `order_by` are all extracted to a child `LogicalProject`, so that they are pure `InputRef`s in later stages. However, the `filter condition` remains unchanged in this process.
During subquery decorrelation, a common operation is to transpose with `LogicalApply`, where the original expressions need to shift their `InputRef` to accommodate extra columns on the left, and map their `CorrelatedInputRef` to a normal …
=> fix(optimizer): `ApplyAggTransposeRule` should handle `CorrelatedInputRef` in agg filter

src/common/src/hash/consistent_hash/mapping.rs, src/meta/src/barrier/command.rs, src/meta/src/manager/catalog/fragment.rs, src/meta/src/stream/test_scale.rs
Correctly resolve the updates of vnode mapping after scaling. Resolve #8615.
Previously we resolve this based on the `upstream_dispatcher_mapping`, but this only exists if there's upstream fragment and the current fragment is hash-sharded. In this PR, we derive this through vnode bitmaps of all actors.
- Other (please specify in the release note …
=> fix(meta): correctly resolve update of vnode mapping after scaling

e2e_test/ddl/alter_table_column.slt, src/frontend/src/catalog/root_catalog.rs, src/frontend/src/catalog/schema_catalog.rs, src/frontend/src/observer/observer_manager.rs, src/meta/src/manager/catalog/mod.rs, src/meta/src/rpc/ddl_controller.rs
- DDL updates a table with its indexes together.
- To resolve https://github.com/risingwavelabs/risingwave/issues/8649.
</details>
=> fix(meta): fix alter table add/drop column with indexes

src/frontend/planner_test/tests/testdata/subquery_expr_correlated.yaml, src/frontend/src/optimizer/plan_visitor/plan_correlated_id_finder.rs
Fixes #7574
Similar to #8650, there is one more place that need to be enhanced to handle the `AGG(...) FILTER (WHERE ...)` syntax when a `CorrelatedInputRef` is used inside `filter`.
We have a simple unnesting rule which matches the pattern `Apply - Project - Filter`, and the decedents do not contain more `CorrelatedInputRef`.
#8650 only fixed the issue when `AGG(...) FILTER (WHERE ...)` is used in `SELECT` for general unnesting. When it appears in `HAVING`, the original plan would look like `Apply - Project - Filter (for having) - Agg` and attempt to match simple unnesting first. During the decedents …
=> fix(optimizer): `PlanCorrelatedIdFinder` should be aware of agg filter

src/batch/Cargo.toml, src/batch/benches/expand.rs, src/batch/benches/filter.rs, src/batch/benches/hash_agg.rs, src/batch/benches/hash_join.rs, src/batch/benches/limit.rs, src/batch/benches/nested_loop_join.rs, src/batch/benches/sort.rs, src/batch/benches/top_n.rs, src/cmd/Cargo.toml, src/cmd/src/bin/compactor.rs, src/cmd/src/bin/compute_node.rs, src/cmd/src/bin/ctl.rs, src/cmd/src/bin/frontend_node.rs, src/cmd/src/bin/meta_node.rs, src/cmd_all/Cargo.toml, src/cmd_all/src/bin/risingwave.rs, src/common/src/jemalloc.rs, src/compute/src/memory_management/mod.rs
It's said that `jemalloc-ctl` reports inaccurate statistics on macOS, but it's not bad to just enable the allocator itself on macOS since it performs much better even for some local tests.
</details>
=> fix: also enable jemalloc on macOS

src/compute/src/rpc/service/stream_service.rs, src/stream/src/executor/subtask.rs, src/stream/src/task/stream_manager.rs
In the last PR (#8624), we fail to handle the drop of subtasks (😢): when we get `None` from the input stream, the local variables in the generator are already dropped (like executor caches). Thus, we also need to check whether it's a `to_drop` barrier to drop it earlier.
This PR also avoids calling `abort` on graceful-exiting actors.
After this PR, one should find the `DROP` command to be more responsive even if there's a large amount of data.
- Connector …
=> fix(streaming): drop subtask on another blocking thread

src/frontend/planner_test/tests/testdata/watermark.yaml, src/frontend/src/optimizer/plan_node/stream_hash_join.rs
avoid panic in watermark derivation in `StreamHashJoin`
</details>
=> fix(watermark): avoid panic in watermark derivation (close #8689)

Makefile.toml, e2e_test/streaming/bug_fixes/issue_8570.slt, src/common/src/array/stream_chunk.rs, src/common/src/row/mod.rs, src/stream/src/executor/managed_state/top_n/top_n_state.rs, src/stream/src/executor/top_n/group_top_n.rs, src/stream/src/executor/top_n/group_top_n_appendonly.rs, src/stream/src/executor/top_n/top_n_appendonly.rs, src/stream/src/executor/top_n/top_n_cache.rs, src/stream/src/executor/top_n/top_n_plain.rs, src/stream/src/from_proto/mod.rs, src/stream/src/from_proto/top_n.rs
Quick fix #8570 -- without performance in mind! @@BugenZhao mentioned there's a `sync` flag in the Min/Max aggregation cache. I'm not sure whether we should do the same (or other methods) here. 
I manually tested the original case in #8570, and didn't find problem yet.
Also added some debug utilities.
- I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- SQL commands, …
=> fix(stream): fix TopN cache by only inserting into high if the row is top

src/stream/src/executor/aggregation/agg_group.rs, src/stream/src/executor/global_simple_agg.rs, src/stream/src/executor/hash_agg.rs
A preparation for `emit on window close` for group agg.
</details>
=> refactor(hash agg): split building change and applying change

docker/docker-compose.yml, risedev.yml, src/common/src/system_param/reader.rs, src/compute/src/lib.rs, src/compute/src/server.rs, src/risedevtool/src/compose.rs, src/risedevtool/src/service_config.rs, src/risedevtool/src/task/compactor_service.rs, src/risedevtool/src/task/compute_node_service.rs, src/risedevtool/src/task/meta_node_service.rs, src/storage/compactor/src/lib.rs, src/storage/compactor/src/server.rs, src/tests/compaction_test/src/compaction_test_runner.rs, src/tests/simulation/src/cluster.rs
As title. In risedev, the sanity checks are moved to `MetaNodeService::apply_command_args`.
Remove `--state-store` from the CLI of compute nodes and compactors. Now it must be specified on the meta node.
=> deprecate(config): deprecate state store url on worker nodes

dashboard/proto/gen/task_service.ts, proto/task_service.proto, src/batch/src/rpc/service/task_service.rs, src/batch/src/task/task_execution.rs, src/batch/src/task/task_manager.rs, src/frontend/src/scheduler/distributed/stage.rs, src/rpc_client/src/compute_client.rs
As title.
Fix a bug where  clean up task may propagate error.
=> fix(batch): Cancel task should not propagate error.

src/batch/src/task/task_execution.rs
=> chore: Remove unnecessary spawn

src/stream/src/executor/hash_join.rs
- evict hash join cache every n messages.
#8723
</details>
=> fix: evict hash join cache every n messages.

src/common/src/array/column.rs, src/common/src/array/data_chunk.rs, src/common/src/array/mod.rs, src/common/src/array/vis.rs
=> docs(common): add more docs for `DataChunk`

risedev.yml, src/meta/src/rpc/server.rs, src/risedevtool/src/task/etcd_service.rs
hotfix for etcd election client
</details>
=> fix: use a separate etcd option for election client

Cargo.lock, src/batch/src/executor/test_utils.rs, src/common/src/field_generator/mod.rs, src/common/src/field_generator/numeric.rs, src/connector/src/source/datagen/source/generator.rs, src/connector/src/source/datagen/source/reader.rs, src/stream/Cargo.toml, src/stream/src/executor/source/source_executor.rs
as title, change a test case, related to #7888 
& bug fix: datagen seq can start generating from an offset …
=> chore: fix unstable unit test

src/config/ci-compaction-test-meta.toml, src/config/ci-compaction-test.toml, src/tests/compaction_test/src/compaction_test_runner.rs
Fix failing compaction test caused by config refactor.
</details>
=> chore(test): fix config for compaction test

src/meta/src/lib.rs
as title
This pull request involves adding new code changes that expand the functionality of a previously implemented mechanism. Specifically, the changes add a new match statement designed to handle cases where a leader_lost_handle is present. When a leader_lost_handle is present, the code will utilize tokio::select! to handle several different scenarios. These include completing the join_handle, receiving a leader lost signal and completing the join_handle, or receiving a ctrl+c signal, completing the join_handle, and aborting the leader_lost_handle.
If a leader_lost_handle is not present, the code will instead use …
=> fix: correctly handle graceful shutdown after losing leader

src/common/src/array/data_chunk.rs, src/common/src/array/stream_chunk.rs, src/stream/src/executor/integration_tests.rs, src/stream/src/executor/project.rs, src/stream/src/from_proto/project.rs
I mean for q0, there can be no compact at all. The existing compact is done in the first project right after the filter, taking 10% of the flame graph.
_Originally posted by @lmatz in https://github.com/risingwavelabs/risingwave/issues/8742#issuecomment-1482308867_
https://github.com/risingwavelabs/risingwave/issues/8712
add some very simple strategy to not compact the chunk all the time.
I introduce a magic `materialize_selectivity_threshold` in this PR, but I do **NOT** think we should do any fine-tuning on the parameter now. …
=> perf(stream): add simple strategy for if the stream project compact the chunk

src/stream/src/common/table/state_table.rs
When we delete all data where column_data < watermark, state clean should not delete data where column_data == NULL
</details>
=> fix(state clean): state clean should not delete NULL

batch-ddl-debug-junit.xml, e2e_test/ddl/table/generated_columns.slt.part, src/frontend/src/optimizer/plan_node/logical_source.rs
- cast generated column expr by user-specified type
</details>
=> feat(generated_columns): cast expr by user specified type

src/batch/src/executor/project.rs
As title
Please do some benchmark @wangrunji0408 
</details>
=> perf(stream): make Project concurrent to accelerate async exprs

src/meta/src/lib.rs, src/meta/src/rpc/server.rs
This pull request includes two changes to the shutdown mechanism in a Rust library. The first modification alters the shutdown behavior when leadership is lost. The second change adds support for the simultaneous shutdown of multiple sub-tasks. As part of these changes, a vector is used to store handles to each sub-task, the `join_all` function is implemented to wait for all sub-tasks to complete, and the timeout behavior for shutting down the `barrier manager` has been modified. …
=> chore: refine the logic for meta after losing leadership

src/common/benches/bitmap.rs
=> feat(common): add benchmark for `BitmapIter`

src/batch/benches/filter.rs, src/batch/benches/hash_join.rs, src/batch/benches/nested_loop_join.rs, src/batch/src/executor/filter.rs, src/batch/src/executor/join/hash_join.rs, src/batch/src/executor/join/local_lookup_join.rs, src/batch/src/executor/join/nested_loop_join.rs, src/batch/src/executor/sort_agg.rs, src/common/src/array/data_chunk.rs, src/common/src/array/stream_chunk.rs, src/common/src/types/mod.rs, src/expr/src/expr/build.rs, src/expr/src/expr/expr_binary_nonnull.rs, src/expr/src/expr/expr_binary_nullable.rs, src/expr/src/expr/expr_case.rs, src/expr/src/expr/expr_some_all.rs, src/expr/src/expr/expr_unary.rs, src/expr/src/expr/mod.rs, src/expr/src/vector_op/agg/filter.rs, src/stream/src/executor/filter.rs, src/stream/src/executor/hash_join.rs, src/stream/src/executor/now.rs, src/stream/src/executor/project.rs, src/stream/src/executor/watermark_filter.rs
This PR introduces a simple DSL for expressions, so that we can build expressions painless in unit tests. (resolve #7881)
The language is defined as follows:
```
inputref := #<index>:<type>
constant := <value>:<type>
function := (<name>:<type> <child1> <child2>...)
```
For example:
```
#0 % 2 == 0
(equal:boolean (modulus:int8 #0:int8 2:int8) 0:int8)
```
The overall design follows the [egg](https://docs.rs/egg/latest/egg/index.html#simple-example). Except that we have to explicitly specify the return type of each node. It might not be the best and is subject to be changed if anyone has a better idea.
This PR contains a …
=> feat(expr): build expression from pretty string

src/common/src/array/list_array.rs, src/common/src/array/struct_array.rs, src/common/src/util/value_encoding/mod.rs
add function to estimate the value encoding size of the datum
prepare for https://github.com/risingwavelabs/risingwave/issues/8683
</details>
=> perf(encoding): add estimate size for value encoding

e2e_test/batch/catalog/issue_8791.slt.part, src/frontend/src/binder/query.rs, src/frontend/src/binder/relation/mod.rs, src/frontend/src/binder/set_expr.rs, src/frontend/src/handler/query.rs
fix #8791
Previously, setops like `UNION`, and subquery are not considered.
</details>
=> fix: run complex query containing system tables in local mode

Cargo.lock, src/ctl/Cargo.toml, src/ctl/src/cmd_impl/meta/cluster_info.rs, src/ctl/src/lib.rs
This PR adds a simple command-line tool to display basic split allocation information of actors in source fragments within risingwave.
```
CREATE table bid (auction BIGINT, bidder BIGINT, price BIGINT, "channel" VARCHAR, "url" VARCHAR, "date_time" TIMESTAMP, "extra" VARCHAR)
with (
connector = 'nexmark',
nexmark.table.type = 'Bid',
nexmark.split.num = '50',
nexmark.min.event.gap.in.ns = '1000000000'
);
```
then 
```
Table #1002
Fragment #2
Actor #37 (2): [50-7,50-28]
Actor #38 (2): [50-9,50-10]
Actor #39 (1): [50-12]
Actor #40 (1): [50-6]
Actor #41 (1): [50-16]
Actor #42 (1): [50-13]
Actor #43 (1): [50-31]
Actor #44 …
```
=> feat: add a command to risedev to display source split information

src/compute/src/server.rs
As title.
Related issues:
- #8696
- #8822
</details>
=> fix: use total memory instead of compute memory for memory control

proto/stream_plan.proto, src/frontend/planner_test/tests/testdata/watermark.yaml, src/frontend/src/expr/mod.rs, src/frontend/src/optimizer/plan_node/eq_join_predicate.rs, src/frontend/src/optimizer/plan_node/logical_join.rs, src/frontend/src/optimizer/plan_node/stream_hash_join.rs, src/frontend/src/optimizer/rule/push_calculation_of_join_rule.rs, src/frontend/src/scheduler/distributed/query.rs, src/frontend/src/utils/condition.rs, src/stream/src/executor/hash_join.rs, src/stream/src/executor/test_utils.rs, src/stream/src/from_proto/hash_join.rs
Leverage band conditions in hash join.
Emit watermarks by band conditions in non-equi conditions in join condition of streaming hash join.
Clean state by band conditions in non-equi conditions in join condition in streaming hash join executor.
</details>
=> feat(join): leverage band conditions in hash join

src/frontend/src/optimizer/plan_node/generic/dynamic_filter.rs
Redundant duplication of dist key
=> chore(frontend): dedup dist key from pk

src/common/benches/bitmap.rs, src/common/src/buffer/bitmap.rs
- Before this PR, bitmap iter is shown to be expensive: https://github.com/risingwavelabs/risingwave/issues/7792#issuecomment-1481305388
- In this PR, we call it once for each usize, copy it into the iterator, and reference that instead.
- Save division calls by a factor of `usize`.
- Save calls to `get_unchecked` by a factor of `usize`.
- Incur cost of copy `usize` on to stack for buffering reads from memory
- Incur cost of conditional check of whether to fetch usize from memory or use the one buffered.
- Also fix benchmark inaccuracies.
Overall maybe save about 1% 🤣 
Saves about 17% for bitmap iter itself. See below: …
=> perf(common): optimize `BitmapIter`

ci/workflows/docker.yml, ci/workflows/main-cron.yml, ci/workflows/main.yml, ci/workflows/pull-request.yml
The automatic retry of ci is removed because:
1. timeout and agent-lost will trigger retry, which may miss some faults;
2. Can save a lot of buildkite job minutes；
3. If the pipeline fails, you should troubleshoot the problem or manually retry；
=> chore(ci): remove ci auto retry

src/meta/src/hummock/manager/mod.rs
fix(hummock manager): preserve SST order in `commit_epoch`
</details>
=> fix(hummock manager): preserve SST order in `commit_epoch` (close #8875)

src/frontend/src/optimizer/plan_node/batch_hash_join.rs, src/frontend/src/optimizer/plan_node/batch_lookup_join.rs, src/frontend/src/optimizer/plan_node/batch_nested_loop_join.rs, src/frontend/src/optimizer/plan_node/generic/join.rs, src/frontend/src/optimizer/plan_node/logical_join.rs, src/frontend/src/optimizer/plan_node/stream_delta_join.rs, src/frontend/src/optimizer/plan_node/stream_hash_join.rs, src/frontend/src/optimizer/plan_node/stream_temporal_join.rs
Deduplicate structures. This is a followup of #8870
=> refactor(plan_node): simplify more structures

src/frontend/src/optimizer/plan_node/logical_join.rs
This is a follow-up of #8898, #8870
=> refactor(plan_node): Further simplify join-related plan nodes

src/common/src/row/mod.rs
close #8877
bench:
```
basic encoding on Int16 time:   [5.6287 ms 5.6303 ms 5.6320 ms]
change: [-5.4826% -5.4502% -5.4183%] (p = 0.00 < 0.05)
Performance has improved.
basic encoding on Int16 and String
time:   [10.036 ms 10.037 ms 10.038 ms]
change: [-22.249% -22.226% -22.205%] (p = 0.00 < 0.05)
Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
3 (3.00%) high mild
1 (1.00%) high severe
basic encoding on Int16 and String (Only need String)
time:   [10.061 ms 10.069 ms 10.081 ms]
change: [-22.094% -21.948% -21.819%] (p = 0.00 < 0.05)
Performance has improved.
Found 4 outliers among 100 …
```
=> perf(encoding): use estimate size to reserve memory in row encoding

docs/checkpoint.md, docs/metrics.md
Credit goes to @BugenZhao for most of the content here.
I have just added some tweaks.
</details>
=> docs: add metrics doc on barrier

src/source/src/connector_source.rs, src/stream/src/executor/stream_reader.rs
related #7192 
prev, if the connector reader encounters an error, we will stop polling the branch and will stop forever. 
- Connector (sources & …
=> fix: propagate connector reader error to the upper layer

src/stream/src/executor/temporal_join.rs
Attempt to evict cache and update vnodes on every epoch for the temporal join executor.
</details>
=> fix(stream): Better cache handling for temporal join.

ci/scripts/e2e-iceberg-sink-test.sh, ci/scripts/e2e-sink-test.sh, ci/scripts/e2e-source-test.sh
Kill cluster before connector node to prevent broken pipe error in compute node.
Test run: https://buildkite.com/risingwavelabs/main/builds/3658#01874256-a6f0-45c2-b701-7a4cab842ffb
After https://github.com/risingwavelabs/risingwave/pull/8920, CN will print full stack trace of connector errors. The error report log should be improved, it is verbose to print full stack trace.
=> fix(ci): quick fix for main cron ci

src/tests/regress/data/schedule, src/tests/regress/data/sql/strings.sql
Enabled:
* `E`-style literals
* `trim`
* `substring`
* `overlay`
* `like`
* `||`
* `length`
* `strpos`
* `replace`
* `split_part`
* `to_hex`
* `md5` on varchar
* `initcap`
* `lpad` / `rpad`
* `ltrim`
* `ascii` / `chr`
* `repeat`
Unsupported (tracked by #8831):
* #8949
* `trim` omitting char
* `position`
* `translate`
* `substring` regexp form / `SIMILAR TO` / regexp functions
* `like` with escape, on bytea, `ilike`
* `substring` / `trim` / `overlay` on bytea
* `md5` / `sha2*` on bytea
* `encode` / `decode`
* `get_bit` / `get_byte`
* `bit_count`
* `unistr`
* `drop table a, b;`
* string continuation
* `U&` strings
* …
=> test(regress): enable `strings`

src/expr/src/vector_op/string.rs, src/tests/regress/data/sql/strings.sql
fix #8949
Note that for `lpad` and `rpad` function:
```
lpad(string text, length int, fill text)
rpad(string text, length int, fill text)
```
If `fill` is given an empty string and `length` > length of `string`, the function will return `string` directly.
</details>
=> fix(expr): fix `lpad` and `rpad` on empty fill string

e2e_test/batch/basic/dml.slt.part, src/frontend/planner_test/tests/testdata/update.yaml, src/frontend/src/binder/update.rs, src/sqlparser/src/ast/mod.rs, src/sqlparser/src/parser.rs, src/sqlparser/tests/sqlparser_common.rs
This is a Postgres syntax -> https://www.postgresql.org/docs/15/sql-update.html
Currently, the default value is always transformed to literal `NULL`. This should be replaced by a real default expression after we support non-NULL default values. 💦💦💦
</details>
=> feat(frontend): support update column to default value

e2e_test/ddl/table/watermark.slt.part, src/meta/src/rpc/ddl_controller.rs
Remove the assert when dropping the table since the watermark filter has an additional internal table.
close #8922
</details>
=> fix: drop table with watermark panic

src/common/benches/bench_hash_key_encoding.rs
Cases with:
- 8 group keys (medium)
- 16 group keys (large)
</details>
=> chore(common): add more benchmark cases for hash key

src/frontend/src/binder/expr/function.rs, src/frontend/src/binder/expr/mod.rs, src/tests/regress/data/sql/float4.sql, src/tests/regress/data/sql/float8.sql, src/tests/regress/data/sql/strings.sql
* `translate` is implemented but not exposed by frontend
* `@` is the same as `abs`
* `ceiling` is the same as `ceil`
Support `translate`, `@` and `ceiling`.
=> feat(binder): support some alternate names for existing exprs

src/expr/src/expr/expr_udf.rs, src/udf/src/lib.rs
This PR fixes a bug with row numbers in UDF. Since we are sending the entire chunk to UDF server, regardless of visibility, the number of rows should be obtained by `capacity` rather than `cardinality`.
We also added a check to make sure the input and output chunk have the same number of rows. It should return an error and never panic no matter what the UDF server returns, following the principle in #9002.
=> fix(udf): fix wrong number of rows

Makefile.toml
Build connector node if the source code changed.
</details>
=> fix(risedev): auto build connector node

src/stream/src/executor/hash_join.rs
hash join state table should not store non null-safe rows because they will never be matched.
</details>
=> perf(hash join): do not store null rows (close #9009)

ci/scripts/e2e-sink-test.sh, e2e_test/sink/remote/types.slt, src/connector/src/sink/remote.rs, src/frontend/src/optimizer/plan_node/stream_sink.rs
ban unsupported types when creating remote sink
resolve #8676 
from the latest change #8740 , the acceptable types for remote sink are `Int16, Int32, Int64, Float32, Float64, Boolean, Decimal, Timestamp, Varchar` …
=> fix: ban types when creating sink

Cargo.lock, src/common/Cargo.toml, src/tests/e2e_extended_mode/Cargo.toml, src/utils/pgwire/Cargo.toml, src/workspace-hack/Cargo.toml
Adjust the features of dependency `rust_decimal`:
* `db-tokio-postgres` = `db-postgres` + `tokio-postgres`. So we do not need both. Actually it only needs `postgres-types`.
* `maths` would enable `pow`, `exp`, `ln`, etc.
=> chore: `rust_decimal` feature -db-tokio-postgres +maths

src/frontend/src/optimizer/plan_node/batch.rs, src/frontend/src/optimizer/plan_node/batch_hop_window.rs, src/frontend/src/optimizer/plan_node/generic/hop_window.rs, src/frontend/src/optimizer/plan_node/logical_hop_window.rs, src/frontend/src/optimizer/plan_node/mod.rs, src/frontend/src/optimizer/plan_node/plan_base.rs, src/frontend/src/optimizer/plan_node/stream_hop_window.rs
Follow up of #8898, #8870, #8905, #8930, #8932, #9011.
- Yes
=> refactor(plan_node): create `BatchPlanRef`, simplify `HopWindow` nodes

src/connector/src/lib.rs, src/connector/src/sink/kafka.rs
- Fix the bug that Kafka sink's `force_append_only` and `properties.retry.max` cannot be parsed correctly.
- Refine the unit test to cover more circumstances.
</details>
=> fix(sink): allow parsing `bool` and `u32` for kafka sink config

e2e_test/batch/catalog/pg_attribute.slt.part, e2e_test/batch/catalog/pg_index.slt.part, e2e_test/ddl/alter_table_column.slt, e2e_test/ddl/index.slt, src/frontend/planner_test/tests/testdata/index_selection.yaml, src/frontend/src/catalog/index_catalog.rs, src/frontend/src/handler/create_index.rs, src/meta/src/manager/catalog/mod.rs, src/meta/src/manager/catalog/utils.rs
- Support functional indexes creation. (only limited functions are accepted right now e.g. `lower`, `upper`, `JsonbAccessInner`, `JsonbAccessStr`).
- Support functional indexes creation.
</details>
https://github.com/risingwavelabs/risingwave/issues/8975
=> feat(frontend): support functional indexes creation

Cargo.lock, e2e_test/batch/functions/sqrt.slt.part, proto/expr.proto, src/expr/Cargo.toml, src/expr/src/vector_op/arithmetic_op.rs, src/frontend/src/binder/expr/function.rs, src/frontend/src/binder/expr/mod.rs, src/tests/regress/data/sql/float8.sql
fixes: https://github.com/risingwavelabs/risingwave/issues/8899
enable the the sqrt  calculation of a decimal or a float.
according to [postgres  doc ](https://www.postgresql.org/docs/current/functions-math.html) sqrt function can take either numeric or double precisions
```
sqrt ( numeric ) → numeric
sqrt ( double precision ) → double precision
Square root
sqrt(2) → 1.4142135623730951
```
- …
=> feat(expr): support for sqrt function

e2e_test/batch/functions/substr.slt.part, src/expr/src/vector_op/substr.rs, src/tests/sqlsmith/src/validation.rs
=> fix(expr): correctly handle unicode for substr

e2e_test/batch/aggregate/stddev_and_variance.slt.part, src/frontend/planner_test/tests/testdata/agg.yaml, src/frontend/src/optimizer/plan_node/generic/project.rs, src/frontend/src/optimizer/plan_node/logical_agg.rs
Fixes #9063, or a simpler example:
```
select count('') + stddev_samp(1+2);
```
The issue is, during `Agg::create`, we would build an inner `Project` that contains inputs to aggregate calls. Here they would be `''` and `1+2`, and then `Agg` would just reference them as `$0` and `$1`. For `stddev`, it also needs `(1+2)*(1+2)` as an input after rewrite. However, the old implementation puts `$1*$1` into the `Project`, effectively referencing itself.
**Note this PR does not fix other issues in the `stddev` rewrite**, for example:
* The `stddev` after rewrite currently returns `double precision` rather than `decimal`, …
=> fix(planner): `stddev`/`var` rewriter panic due to mix use of pre/post project index

src/batch/src/executor/group_top_n.rs, src/batch/src/executor/order_by.rs, src/batch/src/executor/top_n.rs, src/common/src/util/memcmp_encoding.rs, src/expr/src/vector_op/agg/array_agg.rs, src/expr/src/vector_op/agg/string_agg.rs
- Remove `unwrap` from `memcmp_encoding`
- Change order parameter type of `encode_row` from `ColumnOrder` to `OrderType`
</details>
=> refactor(common): remove `unwrap` from `memcmp_encoding` and improve `encode_row`

src/connector/src/sink/mod.rs
=> fix: timestamptz type mismatch

src/meta/src/telemetry.rs
=> refactor(telemetry): avoid backtrace in TrackingId::from_meta_store error

e2e_test/batch/aggregate/stddev_and_variance.slt.part, src/frontend/planner_test/tests/testdata/agg.yaml, src/frontend/src/optimizer/plan_node/logical_agg.rs
A `stddev` aggregate may return `decimal` or `double precision`. But in the last step of taking square root, we used to be restricted to `power(double precision, 0.5) -> double precision` and cannot support decimal correctly. This PR switches to the newly supported `sqrt` function directly.
=> fix(agg): `stddev` uses `sqrt` for decimal support

src/stream/src/executor/mview/materialize.rs
This is previously disabled in https://github.com/risingwavelabs/risingwave/pull/8394#discussion_r1129182626. However, for tables (materialized views) that do not support schema change (determined by `version` field), we can still enable it for better debugging (like #9082).
</details>
=> fix(streaming): only disable sanity check for schema changable table

src/frontend/planner_test/tests/testdata/nexmark.yaml, src/frontend/planner_test/tests/testdata/nexmark_source.yaml, src/frontend/src/optimizer/plan_node/batch_group_topn.rs, src/frontend/src/optimizer/plan_node/batch_topn.rs, src/frontend/src/optimizer/plan_node/generic/top_n.rs, src/frontend/src/optimizer/plan_node/logical_topn.rs, src/frontend/src/optimizer/plan_node/stream.rs, src/frontend/src/optimizer/plan_node/stream_group_topn.rs, src/frontend/src/optimizer/plan_node/stream_topn.rs, src/frontend/src/optimizer/plan_visitor/max_one_row_visitor.rs, src/frontend/src/optimizer/rule/top_n_on_index_rule.rs
1. Merge `limit` and `with_ties` info in top N plan node. The `with_ties` in a top-n operator should be an attribute of `limit`.
2. Add planner tests for nexmark q18 using `RANK()` instead of `ROW_NUMBER()`.
Intend to resolve scaling test failure in #9082.
</details>
=> refactor(optimizer): merge `limit` and `with_ties` info in top-n plan node

src/common/src/types/postgres_type.rs, src/frontend/src/handler/extended_handle.rs
1. a quick fix for #8821
2. remove uncorrect assert in extended mode 
</details>
=> fix(common): set struct oid -1

ci/workflows/main-cron.yml, ci/workflows/main.yml
re-enable it after madsim fix, otherwise the notification in Slack is essentially not providing 0 information
</details>
=> chore(ci): temporarily disable recovery test

Cargo.lock, src/prost/Cargo.toml, src/tests/simulation/Cargo.toml, src/tests/simulation/src/slt.rs, src/tests/simulation/src/utils/timed_future.rs
This PR updates madsim to fix #8868 and a more serious leak introduced by madsim v0.2.19. 🥵
There are two sources of memory leaks:
- Madsim v0.2.19 introduced a circular reference to task, resulting in all task structures being leaked.
- RPC servers like tonic and etcd did not handle client disconnection. For example, for etcd campaign, observe, and other server streaming RPCs, if the client is disconnected, the server's RPC task will not be canceled.
Detailed fixes in madsim:
https://github.com/madsim-rs/madsim/pull/138
https://github.com/madsim-rs/madsim/pull/139
=> fix(test): fix memory leak in simulation

e2e_test/batch/types/int256.slt.part, e2e_test/batch/types/number_arithmetic.slt.part, src/common/src/types/num256.rs, src/expr/macro/src/types.rs, src/expr/src/vector_op/arithmetic_op.rs
This pull request introduces new arithmetic operations for performing division between int256 and floating point numbers, resulting in a float64 scalar. Changes include the addition of new operations to "general_div" in arithmetic_op.rs and "int256" in types.rs, as well as new tests to verify arithmetic operations with Int256 values. Finally, new conversion routines were added in num256.rs to enable conversions between Int256 and float64 Scalar types.
<details><summary>Click here for …
=> feat(common): impl division of `Int256` and `double precision`

src/frontend/src/optimizer/plan_node/batch_hash_agg.rs, src/frontend/src/optimizer/plan_node/batch_sort_agg.rs, src/frontend/src/optimizer/plan_node/generic/agg.rs, src/frontend/src/optimizer/plan_node/logical_agg.rs, src/frontend/src/optimizer/plan_node/logical_union.rs
Follow up of #8898, #8870, #8905, #8930, #8932, #9011, #9044.
- Yes
=> refactor(plan_node): simplify batch agg-nodes

src/common/src/types/num256.rs, src/common/src/util/memcmp_encoding.rs
The previous encoding is treating 32-byte big endian as variable length byte slice, so the serializer inserts extra marker bytes. This PR uses exactly 32 bytes representing the number in big endian, making it compact, easier to understand and debug.
This is a backward incompatible change, in the sense that data encoded by old version cannot be decoded by this new version. But this is within the same release as previous PR, and would only impact nightly.
related: #9158
=> refactor(common): memcomparable encoding of i256

src/batch/src/executor/hash_agg.rs, src/batch/src/task/hash_shuffle_channel.rs, src/common/Cargo.toml, src/common/src/array/data_chunk.rs, src/common/src/hash/consistent_hash/vnode.rs, src/common/src/hash/key.rs, src/common/src/row/mod.rs, src/common/src/row/owned_row.rs, src/common/src/util/hash_util.rs
Resolve the long-standing issue of #5579. Also, add a generic for `HashCode` to avoid misusing between different hashers.
We may perform some benchmarks to see whether...
- xxHash is fast enough,
- and there are frequent key conflicts before (cc @kwannoel)
This PR does not introduce breaking changes, as this only affects the hash code for hash maps and the hasher of hash-shuffle or consistent hash is still `Crc32`.
Close #5579.
- Installation and …
=> fix(streaming): use xxhash64 for hash key in cache

proto/catalog.proto, proto/ddl_service.proto, src/connector/src/common.rs, src/ctl/src/cmd_impl/meta/connection.rs, src/ctl/src/lib.rs, src/frontend/src/handler/create_connection.rs, src/meta/src/rpc/cloud_provider.rs, src/meta/src/rpc/service/ddl_service.rs
- Support new syntax to create a Kafka source with the private link.
```sql
CREATE CONNECTION my_connection with (
type = 'privatelink',
provider = 'aws',
service.name = 'xxx'
);
CREATE SOURCE tcp_metrics_rw (
device_id VARCHAR,
metric_name VARCHAR,
report_time TIMESTAMP,
metric_value DOUBLE PRECISION
) WITH (
connector = 'kafka',
topic = 'tcp_metrics',
properties.bootstrap.server = 'ip1:9092,ip2:9092',
connection.name = 'my_connection',
privatelink.targets = '[{"port": 8001}, {"port": 8002}]',
scan.startup.mode = 'earliest'
) ROW FORMAT JSON;
```
- And since users have to enable the cross-zone load balancing to allow …
=> feat(source): Use a private link connection to create Kafka source

Cargo.lock, src/prost/Cargo.toml, src/tests/simulation/Cargo.toml
This PR updates madsim again to fix the [panic](https://buildkite.com/risingwavelabs/main/builds/3808#01877eb4-587e-4403-bcdb-826ffd1f1113/180-1425) in scaling recovery test since #9168.
Also added `madsim::time::advance` API to simulate spin loop in #9135. 
Related PR: https://github.com/madsim-rs/madsim/pull/140
=> fix(test): fix panic on scaling test

e2e_test/batch/types/int256.slt.part, src/expr/src/sig/agg.rs, src/expr/src/vector_op/agg/aggregator.rs, src/expr/src/vector_op/agg/mod.rs, src/expr/src/vector_op/agg/non_primitive.rs, src/expr/src/vector_op/agg/non_primitive_sum.rs
This PR implements a separate, rough `sum` function for non-primitive types such as `Int256`. This should be considered and removed during future refactoring of the aggregation functions.
</details>
=> feat: separate handling for `sum` aggregation function of `Int256`.

src/storage/src/hummock/compactor/shared_buffer_compact.rs
- When merging imms, it is possible to encounter an imm with 0 key counts which has range tombstones.
</details>
=> fix(storage): fix merge imms assert

src/udf/src/lib.rs
This PR fixes the bug that caused inconsistent result between select item and having clause.
```sql
SELECT some_udf(array_agg(traces::varchar))
FROM ...
GROUP BY ...
HAVING some_udf(array_agg(traces::varchar))
--- expect: t,t,t,t,t...
--- actual: t,t,f,t,f...
```
It turned out to be a bug in arrow-flight v36.0. When encoding a chunk before sending to UDF server, the encoder will split it into multiple chunks smaller than 2MB. However, the subsequent chunks are repeating the first one if there's a column of `VARCHAR[]`.
A minimal reproducible example is:
```python
@udf(input_types=['VARCHAR[]'], result_type="INT")
def …
```
=> fix(udf): fix bad data sent to UDF server

Cargo.lock, src/storage/hummock_sdk/Cargo.toml, src/storage/hummock_sdk/src/compaction_group/mod.rs, src/storage/hummock_sdk/src/lib.rs
So that we can enable some lints about correct usage of `AsPrimitive` vs `FromPrimitive` vs `ToPrimitive` later. It seems this should not be relevant to hummuck.
=> refactor: removed unused num-traits in hummock_sdk

src/connector/src/sink/kafka.rs
no longer support write messages in txn mode. 
related https://github.com/risingwavelabs/risingwave/pull/7500 & https://github.com/risingwavelabs/risingwave/issues/7499 …
=> chore: disable kafka sink txn by design

src/meta/src/hummock/manager/compaction_group_manager.rs, src/meta/src/manager/streaming_job.rs, src/meta/src/rpc/ddl_controller.rs, src/meta/src/stream/stream_manager.rs
Previously `CompactionGroupManager` infers mv table id from `TableFragments::table_id`, aka `StreamingJob::id`. It's incorrect because: 
- Sink doesn't get a mv table, but its `TableFragments::table_id` is set as well. We shouldn't register it to `CompactionGroupManager`.
- Index's `TableFragments::table_id` is actually `Index::id`. We just get lucky so far cause it's equal to `Table::id`.
This PR adds a `StreamingJob::mv_table` to make it explicit for `CompactionGroupManager`.
- Installation …
=> fix(meta): correctly specify mv_table for compaction group manager

src/frontend/src/optimizer/plan_node/batch_source.rs, src/frontend/src/optimizer/plan_node/generic/source.rs, src/frontend/src/optimizer/plan_node/logical_source.rs, src/frontend/src/optimizer/plan_node/stream_source.rs, src/frontend/src/optimizer/plan_visitor/relation_collector_visitor.rs, src/frontend/src/scheduler/plan_fragmenter.rs
Follow up of #8898, #8870, #8905, #8930, #8932, #9011, #9044, #9176.
- Yes
=> refactor(plan_node): reorganize and simplify source-related nodes

src/frontend/planner_test/tests/testdata/batch_index_join.yaml, src/frontend/src/optimizer/plan_node/logical_join.rs
- Fix lookup join conversion.
</details>
=> fix(optimizer): fix lookup join conversion

proto/hummock.proto, src/meta/src/hummock/manager/mod.rs
add new task status `TaskStatus::InputOutdatedCanceled` to replace some usage of original `TaskStatus::InvalidGroupCanceled`
</details>
=> refactor(compact task): add new task status `InputOutdatedCanceled`

src/meta/src/hummock/manager/compaction_group_manager.rs, src/meta/src/hummock/manager/mod.rs, src/meta/src/rpc/server.rs
- Similar to #9211, when purging stale compaction group member tables, catalog table should be the source of truth, rather than table fragments.
- Also fix a corner case when initializing hummock manager.
</details>
=> fix(meta): fix corner case during initialization

e2e_test/udf/python.slt, src/expr/src/expr/expr_udf.rs
Fixes #9066
```
async fn eval_row(&self, input: &OwnedRow) -> Result<Datum> {
let chunk = DataChunk::from_rows(std::slice::from_ref(input), &self.arg_types);
let output_array = self.eval(&chunk).await?;
```
In this previous implementation, it converts an input row to an input chunk and reuses `eval`. However, the data types of columns are not `arg_types`. We have to evaluate children expressions to get arrays / datums of `arg_types`.
This always fails, but the `eval_row` code path executes rarely, mostly only during stream error tolerating (and frontend constant folding). Similar issues: …
=> fix(udf): eval_row panic due to misuse of input row as arg row

Cargo.lock, Cargo.toml, src/common/Cargo.toml, src/frontend/Cargo.toml, src/tests/simulation/Cargo.toml, src/tests/sqlsmith/Cargo.toml, src/tests/state_cleaning_test/Cargo.toml, src/utils/pgwire/Cargo.toml, src/workspace-hack/Cargo.toml
This PR is a regular update for madsim-patched dependencies:
- tokio-postgres v0.7.7 to v0.7.8
- tokio-stream v0.1.11 to v0.1.12
- postgres-types v0.2.4 to v0.2.5
- getrandom v0.2.7 to v0.2.9
=> chore(deps): update madsim-patched dependencies

src/frontend/src/catalog/system_catalog/mod.rs, src/frontend/src/catalog/system_catalog/pg_catalog/mod.rs, src/frontend/src/catalog/system_catalog/rw_catalog/mod.rs, src/frontend/src/catalog/system_catalog/rw_catalog/rw_relation_info.rs
- Support `rw_catalog.rw_relation_info`. Resolve https://github.com/risingwavelabs/risingwave/issues/8264.
Example
```sql
dev=> select  schemaname, relationname, relationowner, definition, relationtype, relationid, relationtimezone from rw_catalog.rw_relation_info;
schemaname | relationname | relationowner |                                             definition                                             |   relationtype    | relationid | relationtimezone
------------+--------------+---------------+----------------------------------------------------------------------------------------------------+-------------------+-- …
```
=> feat(frontend,meta): support rw_catalog.rw_relation_info

src/frontend/src/lib.rs, src/frontend/src/optimizer/plan_rewriter/mod.rs, src/frontend/src/optimizer/plan_rewriter/share_source_rewriter.rs, src/frontend/src/optimizer/plan_visitor/execution_mode_decider.rs, src/frontend/src/optimizer/plan_visitor/input_ref_validator.rs, src/frontend/src/optimizer/plan_visitor/max_one_row_visitor.rs, src/frontend/src/optimizer/plan_visitor/mod.rs, src/frontend/src/optimizer/plan_visitor/plan_correlated_id_finder.rs, src/frontend/src/optimizer/plan_visitor/relation_collector_visitor.rs, src/frontend/src/optimizer/plan_visitor/share_parent_counter.rs, src/frontend/src/optimizer/plan_visitor/side_effect_visitor.rs, src/frontend/src/optimizer/plan_visitor/sys_table_visitor.rs, src/frontend/src/optimizer/plan_visitor/temporal_join_validator.rs
Allow customizing the default behavior of the plan visitor:
- `Merge`: The original behavior. Inherits the result if there's only single input, or `reduce` them with the `merge` function.
- `DefaultValue`: Always return the default return value if `visit_xxx` is not implemented.
Defaulting to `Merge` can be dangerous. Takes `MaxOneRow` as an example: if we introduce a new operator that behaves like a set-returning function while forgetting to add it to the visitor, then the `MaxOneRow` property of the input will automatically be inherited, which is wrong. We should use `DefaultValue` for those not implemented, which is …
=> refactor(optimizer): customize default behavior of plan visitor

src/common/src/util/column_index_mapping.rs, src/frontend/src/optimizer/plan_node/generic/agg.rs, src/frontend/src/optimizer/plan_node/generic/expand.rs, src/frontend/src/optimizer/plan_node/generic/hop_window.rs, src/frontend/src/optimizer/plan_node/generic/join.rs, src/frontend/src/optimizer/plan_node/generic/project.rs, src/frontend/src/optimizer/plan_node/generic/project_set.rs, src/frontend/src/optimizer/plan_node/logical_scan.rs, src/frontend/src/optimizer/rule/apply_join_transpose_rule.rs, src/frontend/src/optimizer/rule/apply_offset_rewriter.rs
- Inverse the mapping. If a target corresponds to more than one source, return `None`. Resolve https://github.com/risingwavelabs/risingwave/issues/8600.
</details>
=> refactor(optimizer): refactor the column index mapping's inverse method

src/common/src/test_utils/rand_bitmap.rs, src/stream/src/executor/aggregation/agg_impl/foldable.rs
=> feat(test_utils): use seed in rand_bitmap

docker/docker-compose.yml
Because of this #9170 we must add --data-directory when starting the meta node
This is why the integration test failed yesterday
=> fix(docker): add data-directory config in docker compose meta node

src/ctl/src/cmd_impl/hummock/sst_dump.rs, src/storage/src/hummock/compactor/compactor_runner.rs, src/storage/src/hummock/compactor/shared_buffer_compact.rs, src/storage/src/hummock/shared_buffer/shared_buffer_batch.rs, src/storage/src/hummock/sstable/builder.rs, src/storage/src/hummock/sstable/delete_range_aggregator.rs, src/storage/src/hummock/sstable/mod.rs, src/storage/src/hummock/sstable/multi_builder.rs, src/storage/src/hummock/sstable/writer.rs, src/storage/src/hummock/store/version.rs, src/storage/src/hummock/test_utils.rs
Monotonic event is all you need.
In #8927, we replaced delete ranges with monotonic delete events in hummock read interface.
However, we did still save original delete ranges for compaction use.
In this PR, to further reduce cost, we do not save the original delete ranges and directly use the collection of monotonic delete events of input SSTs in compaction.
The proof of correctness in this PR is the same as that in #8927 :
> we only need to keep the smallest epoch of the overlapping range tomstone intervals since the key covered by the range tombstone in lower level must have smaller epoches
Implementation: trivially …
=> perf(delete range): monotonic event is all you need

src/common/Cargo.toml, src/common/benches/bench_data_chunk_compact.rs
as title
benchmark
```
data chunk compact: 1 column, 128 rows, vis rate 0.05
time:   [434.29 ns 434.44 ns 434.58 ns]
data chunk compact: 1 column, 1024 rows, vis rate 0.05
time:   [2.8380 µs 2.8391 µs 2.8402 µs]
data chunk compact: 1 column, 128 rows, vis rate 0.25
time:   [555.29 ns 555.84 ns 556.41 ns]
data chunk compact: 1 column, 1024 rows, vis rate 0.25
time:   [4.1308 µs 4.1315 µs 4.1323 µs]
data chunk compact: 1 column, 128 rows, vis rate 0.5
time:   [719.37 ns 720.03 ns 720.71 ns]
data chunk compact: 1 column, 1024 rows, vis rate 0.5
time:   [6.2182 µs 6.2233 µs 6.2293 µs]
data chunk compact: 1 column, 128 rows, …
```
=> perf(data_chunk): add benchmark for `DataChunk::compact()`

src/meta/src/manager/cluster.rs
Revert a change in #8825.
</details>
=> fix(notification): notify risectl node expiration

proto/hummock.proto, src/ctl/src/cmd_impl/hummock/compaction_group.rs, src/ctl/src/lib.rs, src/meta/src/hummock/compaction/compaction_config.rs, src/meta/src/hummock/compaction/picker/tier_compaction_picker.rs, src/meta/src/hummock/compaction_schedule_policy.rs, src/meta/src/hummock/manager/compaction_group_manager.rs, src/meta/src/hummock/test_utils.rs
1. level0_sub_level_compact_level_count for limiting the count of compaction level
2. increase the compaction size for overlapping level compact task
3. support update level0_sub_level_compact_level_count config 
</details>
=> feat(storage): adjust pick_overlapping_level strategy

src/common/src/array/data_chunk.rs, src/common/src/array/mod.rs, src/common/src/array/stream_chunk.rs
optimize Array::compact() and StreamChunk::compact()
benchmark
```
data chunk compact: 1 column, 128 rows, vis rate 0.05
time:   [176.25 ns 176.27 ns 176.29 ns]
change: [-59.548% -59.454% -59.396%] (p = 0.00 < 0.05)
Performance has improved.
data chunk compact: 1 column, 1024 rows, vis rate 0.05
time:   [483.28 ns 483.69 ns 484.09 ns]
change: [-82.976% -82.946% -82.891%] (p = 0.00 < 0.05)
Performance has improved.
data chunk compact: 1 column, 128 rows, vis rate 0.25
time:   [351.29 ns 351.41 ns 351.54 ns]
change: [-37.091% -36.825% -36.588%] (p = 0.00 < 0.05)
Performance has improved.
data chunk compact: 1 column, 1024 …
```
=> perf(array): optimize array compact with Bitmap::iter_ones()

src/tests/sqlsmith/src/sql_gen/expr.rs
=> refactor(sqlsmith): cleanup agg repeated code

src/expr/src/function/window/call.rs, src/expr/src/function/window/kind.rs, src/stream/src/executor/over_window/mod.rs, src/stream/src/executor/over_window/partition.rs, src/stream/src/executor/over_window/state/aggregate.rs, src/stream/src/executor/over_window/state/buffer.rs, src/stream/src/executor/over_window/state/lag.rs, src/stream/src/executor/over_window/state/lead.rs, src/stream/src/executor/over_window/state/mod.rs
This PR
- Adds a common `WindowBuffer` structure to maintain buffered entries for a window frame.
- Implements `AggregateState` which is a `WindowState` to support aggregate function over window. …
=> feat(stream,over-window): implement `AggregateState` to allow aggregate function over window

e2e_test/streaming/bit_agg.slt, src/frontend/src/optimizer/plan_node/generic/agg.rs, src/stream/src/executor/aggregation/agg_impl/foldable.rs, src/stream/src/executor/aggregation/agg_impl/mod.rs
#9281 
We only add a `bit_xor` in streaming aggregation because it is trivial.
`bit_and` and `bit_or` are left undone.
`BitXorable`.... is this name even legal?
<details><summary>Click …
=> feat(streaming): add bit_xor aggregation

src/expr/src/vector_op/ascii.rs, src/expr/src/vector_op/overlay.rs, src/tests/sqlsmith/src/validation.rs
Fixes #9118
Support multibyte Unicode for `overlay` and `ascii`.
=> fix(expr): support multibyte Unicode for `overlay` and `ascii`

src/stream/src/cache/managed_lru.rs, src/stream/src/executor/aggregation/distinct.rs, src/stream/src/executor/dedup/append_only_dedup.rs, src/stream/src/executor/hash_agg.rs, src/stream/src/executor/lookup/cache.rs, src/stream/src/executor/lookup/impl_.rs, src/stream/src/executor/mview/materialize.rs, src/stream/src/executor/temporal_join.rs, src/stream/src/executor/top_n/utils.rs
Every streaming executor which uses the LRUCache will call the `evict` at least for every chunk, which will make state eviction more timely
This PR is just a quick fix and we need some refactoring later.
</details>
=> feat(stream): evict cache more frequently

src/storage/src/hummock/compactor/shared_buffer_compact.rs, src/storage/src/hummock/shared_buffer/shared_buffer_batch.rs, src/storage/src/hummock/sstable/delete_range_aggregator.rs, src/storage/src/hummock/sstable/mod.rs, src/storage/src/hummock/store/version.rs, src/storage/src/hummock/test_utils.rs, src/storage/src/hummock/utils.rs
As described in #9348 ,`filter_single_sst` does not take `right_exclusive` property of SST Key Range into consideration, so this PR fixes it by let `filter_single_sst` receive `std::ops::Bound` as end_key.
In addition, immutable memtables should also use `std::ops::Bound` as end_key because there will be indefinite range delete in the future.
- Other …
=> refactor(end key): use bound to represent end key (close #9348)

ci/scripts/e2e-source-test.sh
We also needs to kill the connector node when we kill the cluster before recovery. Otherwise, we may encounter the following issue in the recovery scenario：
```
metrics.Metrics:92 - Unable to register metrics as an old set with the same name exists, retrying in PT5S
```
Fix #9312 
~- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to …
=> fix(ci): fix source e2e test main ci failure

src/meta/src/hummock/compaction/picker/ttl_reclaim_compaction_picker.rs, src/storage/hummock_test/src/compactor_tests.rs, src/storage/hummock_test/src/hummock_storage_tests.rs, src/storage/src/hummock/compactor/compaction_filter.rs, src/storage/src/hummock/iterator/forward_user.rs, src/storage/src/hummock/mod.rs, src/storage/src/hummock/shared_buffer/shared_buffer_batch.rs, src/storage/src/hummock/store/version.rs
As title.
Currently there are 2 bugs on `retention_second`:
* `Epoch` consists of `time || seq`, and both part need to be considered in filter.
* Read result of merged imm is not checked when `retention_second` is set.
</details>
=> fix(storage): fix some bugs in retention second in read option

risedev.yml, src/compute/src/lib.rs, src/compute/src/memory_management/memory_manager.rs, src/compute/src/memory_management/mod.rs, src/compute/src/memory_management/policy.rs, src/compute/src/server.rs, src/risedevtool/src/service_config.rs, src/risedevtool/src/task/compute_node_service.rs
Fix #9383.
This PR also reverts #8253 and #8475 but keeps the `trait MemoryControlPolicy` (renamed to "MemoryControl") for possible future usage.
The reason of that is, we are not actually ready for such "MemoryControlPolicy" right now. Back to that point when we wrote #8253 and #8475, we didn't realize that these policy cannot work at all without a better memory estimation.
After that, when #8827 merged, things become worse. Code of #8827 mixed up 2 things: 
- the **machanism of measuring** current memory usage 
- and the **policy** about how the memory should be used
... which made that part of code become quite …
=> fix(memory-manager): should not use prev_memory_stats.streaming_memory_usage

Makefile.toml, risedev
For example, changes introduced in #9006 use a recent functionality `files_modified" of `cargo-make`.
</details>
=> chore(risedev): bump cargo-make version

src/utils/runtime/src/lib.rs
Enable info logging by default to avoid missing logs in release build
</details>
=> chore: enable info logging by default for release build

e2e_test/batch/types/interoperate_decimal_float.slt.part, src/common/src/types/decimal.rs, src/common/src/types/ordered_float.rs, src/expr/src/vector_op/arithmetic_op.rs, src/expr/src/vector_op/cast.rs, src/expr/src/vector_op/cmp.rs
Fix #9214. Replace `From<F64> for Decimal` with `TryFrom<F64> for Decimal`.
This PR also moves unit tests of arithmetic and comparison between decimal and float4 to e2e tests. In reality, they are not compared directly using the `T1: Into<T3>` and `T2: Into<T3>`, but by implicit cast expressions inserted by frontend. It also benefits the separation of fallible and infallible expression, so that comparison remain infallible while casts can fail.
This PR focuses on fixing this specific float to decimal issue. There will be more refactor PRs to follow, to clarify when frontend implicit casts (decimal < float4) or backend …
=> fix(common): panic during large f64 to decimal conversion

e2e_test/udf/python.slt, src/frontend/src/catalog/schema_catalog.rs, src/frontend/src/handler/show.rs, src/sqlparser/src/ast/mod.rs, src/sqlparser/src/keywords.rs, src/sqlparser/src/parser.rs
Support new sql commands `show functions`, i.e:
```sql
dev=> show functions;
Name       |         Arguments         |                                Return Type                                | Language |         Link
------------------+---------------------------+---------------------------------------------------------------------------+----------+-----------------------
jsonb_concat     | jsonb[]                   | jsonb                                                                     | python   | http://localhost:8815
array_access     | varchar[], integer        | varchar …
```
=> feat: support show functions

src/storage/src/hummock/event_handler/hummock_event_handler.rs
There can be many read version and this log can be overwhelming.
</details>
=> chore(log): suppress spill log

README.md
This pull request fixes an issue in README.md where the RisingWave Cloud URL was being incorrectly parsed as a relative path instead of a full URL. As a result, the link was not working properly. This commit updates the URL to "https://risingwave.com/cloud", ensuring that the correct absolute URL is being used. 
As an example:
-RisingWave Cloud is the fully managed service of RisingWave Database. It is now in Beta. Feel free to try out at: [risingwave.com/cloud](risingwave.com/cloud).
+RisingWave Cloud is the fully managed service of RisingWave Database. It is now in Beta. Feel free to try out at: …
=> chore: Fix invalid URL that was being parsed as a relative path in README.md

src/storage/hummock_sdk/src/key.rs, src/storage/src/hummock/compactor/compactor_runner.rs, src/storage/src/hummock/iterator/delete_range_iterator.rs, src/storage/src/hummock/iterator/test_utils.rs, src/storage/src/hummock/shared_buffer/shared_buffer_batch.rs, src/storage/src/hummock/sstable/builder.rs, src/storage/src/hummock/sstable/delete_range_aggregator.rs, src/storage/src/hummock/sstable/mod.rs, src/storage/src/hummock/sstable/multi_builder.rs, src/storage/src/hummock/test_utils.rs
We will need to support delete range type other than the typical left-closed-right-open range due to watermark on desc columns.
We introduce `ExtendedUserKey` in our `MonotonicDelete` design. We treat the right neighbourhood space of a user key as a new user key, and both type of user key are called `ExtendedUserKey`.
`ExtendedUserKey` represents the user key itself if `is_right_neighbourhood_of_key==false`
while represents the right δ Neighborhood of the user key if `is_right_neighbourhood_of_key==true`.
Simply replacing `UserKey` with `ExtendedUserKey` helps us resolve queries and compaction on the new type of delete …
=> feat(delete range): open interval range delete

ci/workflows/main.yml
Sometimes docker compose and starting dependencies step takes a little longer (1min). Then it will lead to timeout, since the e2e binding test itself takes about 4min+.
Closes https://github.com/risingwavelabs/risingwave/issues/9423.
</details>
=> fix(ci): java binding test timeout

clippy.toml, e2e_test/batch/types/jsonb.slt.part, src/common/src/array/mod.rs, src/common/src/lib.rs, src/common/src/types/ordered_float.rs, src/connector/src/parser/avro/util.rs, src/expr/src/vector_op/cast.rs, src/expr/src/vector_op/timestamptz.rs, src/tests/e2e_extended_mode/src/test.rs
Similar to #9411
|| into F32 | into F64 | from F32 | from F64 |
|-|-|-|-|-|
|i16|lossless|lossless|TryFrom|TryFrom|
|i32|approx|lossless|TryFrom|TryFrom|
|i64|approx|approx|TryFrom|TryFrom|
|f32|ordered|NA|inner|NA|
|f64|NA|ordered|NA|inner|
|F32|noop (A)|lossless (B)| dup with (A) | dup with (C) |
|F64|TryFrom (C)|noop (D)| dup with (B) | dup with (D) |
* The lossless ones are implemented via rust builtin `From`.
* The approx ones are implemented via rust [`as` operator](https://doc.rust-lang.org/reference/expressions/operator-expr.html#numeric-cast).
* The `TryFrom` ones are implemented via preprocessing + `as`.
* …
=> refactor(common): use `From`/`TryFrom` rather than `ToPrimitive`/`FromPrimitive` for floats

e2e_test/source/basic/ddl.slt
Add some e2e test cases for dbz mongo source.
=> test(dbz_mongo): add tests

e2e_test/batch/functions/round.slt.part, e2e_test/batch/types/decimal.slt.part, e2e_test/batch/types/interval.slt.part, e2e_test/batch/types/timestamptz_utc.slt.part, src/common/src/types/interval.rs, src/expr/src/lib.rs, src/expr/src/vector_op/round.rs, src/tests/regress/data/sql/float4.sql, src/tests/regress/data/sql/float8.sql, src/tests/regress/data/sql/int2.sql, src/tests/regress/data/sql/int4.sql, src/tests/regress/data/sql/int8.sql
Fix #5576
For context, there are 5 rounding modes in IEEE 754:
* towards `-Infinity` aka `floor`
* towards `+infinity` aka `ceil`
* towards zero aka `trunc`
* rust builtin float `as` int
* to nearest, ties to even
* PostgreSQL float to int cast, and float round
* native to x86 / arm
* rust builtin int `as` float and f32 `as` f64
* to nearest, ties away from zero
* PostgreSQL decimal to int cast, and decimal round
* rust builtin round
=> fix(expr): float should round ties to even

src/frontend/src/binder/update.rs
- report an error when trying to update a table with generated column
</details>
=> fix: ban update a table with generated column

src/compute/src/memory_management/mod.rs
Reverts risingwavelabs/risingwave#9125 
Anyway, it didn't take effect at all. 
In future, PRs like #9125 must be verified before merging into main branch.
=> revert: "fix: Increase reserved memory temporarily"

clippy.toml, src/common/src/field_generator/numeric.rs, src/common/src/types/mod.rs, src/common/src/types/ordered_float.rs, src/common/src/util/memcmp_encoding.rs, src/expr/src/vector_op/arithmetic_op.rs, src/expr/src/vector_op/exp.rs, src/expr/src/vector_op/trigonometric.rs
See #9411 #9439 for more context.
=> refactor(common): disallow `ToPrimitive`/`NumCast` in favor of `From`/`TryFrom`

src/connector/src/source/kafka/private_link.rs
As title.
The log only print one time when constructing a producer and consumer.
</details>
=> chore(log): print PrivateLink rewrite mappings for Kafka

src/common/src/util/epoch.rs, src/expr/src/expr/expr_proctime.rs, src/expr/src/expr/mod.rs, src/stream/src/executor/mod.rs, src/stream/src/executor/project.rs, src/stream/src/executor/wrapper.rs, src/stream/src/executor/wrapper/epoch_provide.rs
Epoch changes periodically in streaming executors, while providing a correct value is crucial to several components like `LruCache`, `StateTable`, `PROCTIME()`. For the simplicity of the interface design, we do not pass the value everywhere. Instead, we make these components to hold other copies of the value and let the executor call `update_epoch` when it needs to be updated.
This could be really error-prone if we accidentally forget to call that! For example, in #9459 we find that a lot of executors forget to update the epoch for the LRU cache, so the eviction will be …
=> refactor(streaming): retrieve epoch from task local storage

ci/scripts/flamegraph-env-build.sh, ci/scripts/gen-flamegraph.sh, ci/workflows/gen-flamegraph.yml, ci/workflows/main-cron.yml
Workflow to trigger adhoc flamegraph generation on arbitrary branch and commit.
You can trigger it via buildkite api, or via buildkite gui after this PR.
---
After #9421 
This will be very useful for https://github.com/risingwavelabs/risingwave/issues/9285.
1. We can `curl` to trigger a build: https://buildkite.com/docs/apis/rest-api/builds#create-a-build.
2. Upload throughput as meta data https://buildkite.com/docs/apis/rest-api/builds#get-a-build.
3. Use that to determine whether tps regressed.
Please keep the types that apply to your changes, and remove the …
=> feat(ci): Support adhoc flamegraph generation + Support `main-cron` flamegraph generation for all queries

src/storage/src/hummock/error.rs, src/storage/src/hummock/state_store.rs
Fix #8561.
Now when query fails due to cluster being recovering,
- psql will see `Storage error: Hummock error: Barrier read is unavailable for now. Likely the cluster is recovering.`.
- compute node log will show failure reason: `invalid barrier read {} > max seal epoch {}` or `invalid barrier read {} < min current epoch {}`.
- Other (please specify …
=> refactor: improve error message when read barrier fails

Makefile.toml, src/frontend/src/handler/explain.rs, src/frontend/src/optimizer/optimizer_context.rs
This PR makes it possible to peek at the partial outputs of `EXPLAIN` if there's an error during plan generation and optimization. This may be helpful for us to develop a new feature or optimizer rule.
```
dev=> create table t (v int);
CREATE_TABLE
dev=> explain(trace) select (select v from t), 1 from t;
QUERY PLAN                                     
-----------------------------------------------------------------------------------
Begin:
LogicalProject { exprs: [t.v, 1:Int32] }
└─LogicalApply { type: LeftOuter, on: true, correlated_id: 1, max_one_row: true }
├─LogicalScan { …
```
=> feat(frontend): print partial explain traces if there's error

src/common/src/system_param/mod.rs, src/frontend/src/handler/variable.rs, src/meta/src/manager/system_param/mod.rs
As title. Closes #9505 
```
Name           |     Value      | Mutable 
--------------------------+----------------+---------
barrier_interval_ms      | 1000           | f
checkpoint_frequency     | 10             | t
sstable_size_mb          | 256            | f
block_size_kb            | 64             | f
bloom_false_positive     | 0.001          | f
state_store              | hummock+memory | f
data_directory           | hummock_001    | f
backup_storage_url       | memory         | f
backup_storage_directory | backup         | f
telemetry_enabled        | true           | t
(10 rows)
```
Please keep the types that …
=> feat(frontend): show if system parameters are mutable

ci/scripts/gen-flamegraph.sh, ci/workflows/gen-flamegraph.yml, ci/workflows/main-cron.yml, ci/workflows/pull-request.yml
Add heap profiling to ci. I don't know how essential this is to run regularly, so just adding it to pull request and manual workflows.
We can run it on `main-cron` if needed.
---
Future improvements tracked here: https://github.com/risingwavelabs/risingwave/issues/9426.
1. Increase nexmark events so we have more allocations.
2. Get multiple snapshots of the heap flamegraph and render them.
- …
=> feat(ci): Add adhoc heap flamegraph generation

Cargo.lock, src/risedevtool/Cargo.toml, src/risedevtool/src/bin/risedev-docslt.rs
risedev-docslt is a handy tool to extract slt blocks from Rust docs. However, it runs very slow since it has to wait for rustdoc to build the whole project. This process takes over 2 mins in my env, which significantly blocks the dev workflow.
This PR refactors the extraction with plain text processing. It no longer depends on rustdoc, therefore can complete immediately.
I also removed support for setup and teardown, since it's not used and I don't think it will be in the future. 🤔
=> refactor: make docslt faster

e2e_test/udf/python.slt, src/frontend/src/catalog/root_catalog.rs, src/frontend/src/catalog/schema_catalog.rs, src/frontend/src/handler/drop_function.rs, src/sqlparser/src/parser.rs
As title. `drop function foo;` will succeed only when there's exactly one function named `foo`.
Here are some examples:
```sql
dev=> create function foo() ...;
dev=> create function foo(int) ...;
dev=> drop function foo;
ERROR:  QueryError: Catalog error: function name "foo" is not unique
HINT: Specify the argument list to select the function unambiguously.
dev=> drop function foo();
DROP_FUNCTION
dev=> drop function foo;
DROP_FUNCTION
```
This PR also improved the error message when function is not found.
```diff
dev=> drop function gcd(int);
-ERROR:  QueryError: Catalog error: function not found: gcd
+ERROR: …
```
=> fix(frontend): support `drop function` without arguments

e2e_test/ddl/alter_rename_relation.slt, src/frontend/src/handler/alter_relation_rename.rs
As explained in https://github.com/risingwavelabs/risingwave/issues/9540#issuecomment-1534155805. Close #9540.
</details>
=> fix(frontend): reject `ALTER SOURCE` on table with connector

src/frontend/src/handler/create_mv.rs, src/frontend/src/handler/query.rs, src/frontend/src/optimizer/optimizer_context.rs, src/utils/pgwire/src/pg_extended.rs, src/utils/pgwire/src/pg_protocol.rs, src/utils/pgwire/src/pg_response.rs
- support notice multiple times for a query
```
dev=> create materialized view mv as select * from t where y > now() order by x;
NOTICE:  Your session timezone is UTC. It was used in the interpretation of timestamps and dates in your query. If this is unintended, change your timezone to match that of your data's with `set timezone = [timezone]` or rewrite your query with an explicit timezone conversion, e.g. with `AT TIME ZONE`.
NOTICE:  The ORDER BY clause in the CREATE MATERIALIZED VIEW statement does not guarantee that the rows selected out of this materialized view is returned in this order.
It only indicates the …
```
=> refactor(pgwire): refine the interface of notice

src/frontend/planner_test/tests/testdata/agg.yaml, src/frontend/planner_test/tests/testdata/index_selection.yaml, src/frontend/planner_test/tests/testdata/limit.yaml, src/frontend/src/optimizer/plan_node/batch_limit.rs, src/frontend/src/optimizer/plan_node/batch_topn.rs, src/frontend/src/optimizer/rule/min_max_on_index_rule.rs, src/frontend/src/optimizer/rule/top_n_on_index_rule.rs
- Two-phase limit shouldn't require input to satisfy an order, because it would result in `MergeSortExchange`. SQL `select * from t limit 1` doesn't need `MergeSortExchange` at all.
- `TopNOnIndexRule` and `MinMaxOnIndexRule` should use `LogicalTopN` instead of `LogicalLimit`, since `LogicalLimit` has no order guarantee.
- Two-phase topn can utilize partial limit if its input's order satisfy the order of the topn
- SQL commands, …
=> feat(batch): optimize batch limit and topn

src/common/src/util/resource_util.rs
Container Aware APIs should not trigger an error when max value is set, or if there is no limit, instead it should return system default values/limits. The behaviour and the return value is same as before but a warning will not be triggered in the case of max.
</details>
=> fix: container aware api 

src/common/src/array/data_chunk.rs, src/common/src/hash/key.rs
closes https://github.com/risingwavelabs/risingwave/issues/9305.
</details>
=>  perf(hashkey): refine the memory reserving for SerializedKey

src/frontend/src/expr/mod.rs, src/frontend/src/expr/utils.rs, src/frontend/src/optimizer/plan_node/col_pruning.rs, src/frontend/src/optimizer/plan_node/logical_filter.rs, src/frontend/src/optimizer/plan_node/logical_join.rs, src/frontend/src/optimizer/plan_node/logical_project.rs, src/frontend/src/optimizer/plan_node/logical_project_set.rs, src/frontend/src/optimizer/plan_node/logical_scan.rs, src/frontend/src/optimizer/rule/apply_join_transpose_rule.rs, src/frontend/src/optimizer/rule/distinct_agg_rule.rs, src/frontend/src/utils/condition.rs
- refine the `col_prune` for Project and ProjectSet
- use `Conditon::collect_input_refs` instead of use `CollectInputRef` visitor diectly
</details>
=> chore(optimizer): refine collect input ref logic

e2e_test/ddl/table/generated_columns.slt.part, proto/expr.proto, src/frontend/src/expr/mod.rs, src/frontend/src/expr/pure.rs, src/frontend/src/optimizer/plan_expr_rewriter/const_eval_rewriter.rs, src/frontend/src/optimizer/plan_node/logical_over_agg.rs, src/frontend/src/optimizer/plan_node/logical_source.rs, src/frontend/src/optimizer/rule/always_false_filter_rule.rs, src/frontend/src/optimizer/rule/over_agg_to_topn_rule.rs, src/frontend/src/utils/condition.rs
Previously we treat an expression tree that only consists of `InputRef`s and function calls as constant evaluable. This is incorrect if there are impure function calls, for example, `PROCTIME()`. (#9572)
This PR also makes `eval_row_const` return an `Option` to avoid calling `is_const` multiple times.
- Other …
=> fix(expr): do not const-eval impure expressions

.github/workflows/connector-node-integration.yml
- previously, the connector node integration workflow is triggered if the files in `java/**` or `proto/**` have been modified
- if the files in `java/**` or `proto/**`  are not modified, the workflow will be skipped. however, if we change the workflow to be `required`, merging pr's will blocked if the workflow was skipped (since no status was reported)
- therefore, the workflow was modified such that:
- the workflow is run no matter the files in `java/**` or `proto/**` are modified or not
- the integration test will only run if the files in `java/**` or `proto/**` are modified
- if the integration test is skipped, the …
=> fix(ci): connector integration test trigger condition

e2e_test/streaming/eowc/eowc_over_window.slt, src/frontend/planner_test/tests/testdata/emit_on_window_close.yaml, src/frontend/planner_test/tests/testdata/over_window_function.yaml, src/frontend/src/optimizer/plan_node/generic/over_window.rs, src/frontend/src/optimizer/plan_node/logical_over_agg.rs, src/frontend/src/optimizer/plan_node/stream_sort.rs, src/stream/src/from_proto/eowc_over_window.rs
This PR enables [Over Window](https://github.com/risingwavelabs/rfcs/pull/8) feature with `EMIT ON WINDOW CLOSE`. Tracked in #9124.
Support Over Window (a.k.a Over Aggregation or Window Function) with `EMIT ON WINDOW CLOSE`. Currently only support windows partitioned by at least one column and ordered by only single watermark column.
Example:
```sql
CREATE SOURCE t (a TIMESTAMP, b INT, WATERMARK FOR a AS a - INTERVAL '5 minutes') WITH ...;
CREATE MATERIALIZED VIEW mv EMIT ON WINDOW CLOSE AS
SELECT
window_start,
lag(b) OVER (PARTITION BY window_start ORDER BY a),
max(b) OVER …
```
=> feat(over window): generate EOWC stream plan from `LogicalOverAgg`

src/compute/src/memory_management/memory_manager.rs
#9509 didn't work without this...
</details>
=> fix(mem-mgr): fix jemalloc_active_bytes metrics

src/meta/src/hummock/manager/mod.rs, src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
=> fix(sub level): insert sub level into correct pos in `HummockVersion`

proto/hummock.proto, src/meta/src/hummock/compaction/mod.rs, src/meta/src/hummock/compaction_schedule_policy.rs, src/storage/benches/bench_compactor.rs, src/storage/src/hummock/compactor/compaction_utils.rs, src/storage/src/hummock/compactor/compactor_runner.rs, src/storage/src/hummock/compactor/mod.rs, src/storage/src/hummock/compactor/shared_buffer_compact.rs, src/storage/src/hummock/sstable/multi_builder.rs
Do not split compaction output by size when the output is already split by state table in L0 and Lbase to make code more clear.
</details>
=> feat(compaction): do not split compaction output by size in L0 and Lbase

src/common/src/config.rs, src/config/example.toml
As @fuyufjh suggested, 1024 seems too large for extreme agg cache size.
- ~~[ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)~~ …
=> perf(minor): change `stream_extreme_cache_size` from 1024 to 10

src/meta/src/hummock/manager/compaction_group_manager.rs, src/meta/src/hummock/manager/mod.rs, src/meta/src/hummock/manager/versioning.rs
Previously, when accessing a compaction group's compaction config:
1. If it has been set explicitly (and persisted) before, it's used.
2. otherwise, a hard-coding `default config` is used.
The problem with this approach is, if the `default config` is changed later (e.g. hard-coding default value is changed), case 2 may start to use a different compaction config unconsciously. This can be risky especially for configs expected to be immutable for a group, e.g. `split_by_state_table`.
With this PR, whenever a new compaction group is created, it's guaranteed its compaction config is persisted as well. So that only case 1 is …
=> refactor(meta): always persist compaction config.

e2e_test/batch/basic/range_scan.slt.part, src/frontend/planner_test/tests/testdata/range_scan.yaml, src/frontend/src/utils/condition.rs
1. complete the `TODO: simplify bounds:` in condition:
- merge lower bound and upper bound 
- filter eq conds using lower bound and upper bound
2. try to refine the split_to_scan_ranges by seperate out subprocess from it. ( Not sure whether it's a positive refine. I try make it look more tiny because I think its original len is so long to impact the readbility. …
=> refactor(frontend): simplify condition by merging lower bound and upper bound 

src/meta/src/manager/streaming_job.rs, src/meta/src/rpc/ddl_controller.rs, src/meta/src/stream/stream_graph/actor.rs
=> chore: only persist definition in stream actor when debug assertion enabled

src/stream/src/executor/over_window/state/aggregate.rs
At title.
- ~[ ] I have written necessary rustdoc comments~~
- ~~[ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)~~
- Connector (sources …
=> perf(over-window): store `agg_call` instead of `agg_state_prototype` in `AggregateState` to reduce memory consumption

src/object_store/src/object/disk.rs, src/object_store/src/object/error.rs, src/object_store/src/object/mem.rs, src/object_store/src/object/opendal_engine/opendal_object_store.rs, src/object_store/src/object/s3.rs
Previously when ObjectStore::read returns a error, we cannot tell whether it's "object does not exist" or any other error kinds (maybe transient/recoverable ones). We encounter several cases to distinguish them.
This PR add `is_object_not_found_error` method for `ObjectError`.
</details>
=> feat(storage): support identifying "object not found" error kind

Cargo.lock, proto/hummock.proto, src/meta/src/hummock/compaction/compaction_config.rs, src/meta/src/hummock/compaction/mod.rs, src/meta/src/hummock/compaction_schedule_policy.rs, src/storage/Cargo.toml, src/storage/benches/bench_compactor.rs, src/storage/hummock_test/src/hummock_storage_tests.rs, src/storage/hummock_test/src/state_store_tests.rs, src/storage/src/hummock/compactor/compaction_utils.rs, src/storage/src/hummock/compactor/compactor_runner.rs, src/storage/src/hummock/compactor/mod.rs, src/storage/src/hummock/compactor/shared_buffer_compact.rs, src/storage/src/hummock/sstable/backward_sstable_iterator.rs, src/storage/src/hummock/sstable/forward_sstable_iterator.rs, src/storage/src/hummock/sstable/multi_builder.rs, src/storage/src/hummock/test_utils.rs, src/storage/src/storage_failpoints/test_sstable.rs
Support partition in compaction group.
State table will be partitioned by vnode.
View https://github.com/risingwavelabs/risingwave/pull/5335 as reference.
Partition setting can either be static or be dynamic.
</details>
=> perf(compaction): support partition in compaction group

src/meta/src/backup_restore/meta_snapshot_builder.rs, src/meta/src/backup_restore/restore.rs, src/meta/src/manager/env.rs, src/meta/src/model/cluster.rs, src/meta/src/rpc/server.rs, src/meta/src/rpc/service/telemetry_service.rs
Cluster id should be restored when restoring meta node from backup. Otherwise it will fail with "data directory is already used by another cluster with id", because the restored meta node is treated as a newly created one unexpectedly.
</details>
=> fix(backup): restore cluster id

src/frontend/src/handler/create_mv.rs, src/frontend/src/handler/create_table.rs, src/frontend/src/handler/query.rs, src/frontend/src/optimizer/optimizer_context.rs, src/frontend/src/optimizer/plan_node/convert.rs, src/frontend/src/session.rs, src/utils/pgwire/src/pg_protocol.rs, src/utils/pgwire/src/pg_server.rs
In the previous notice implementation https://github.com/risingwavelabs/risingwave/pull/9577, we can not notice user when the optimizer throws an error. 
- add the warning messages in the `SessionImpl` and add a interface on the `trait pgwire::Session`
- rename the `warn` to `warn_to_user`
</details>
=> feat(fe): refine notice framework

.config/hakari.toml, Cargo.lock, src/workspace-hack/Cargo.toml
Because it's a dev-dependency for bench, and won't be needed most of the time. BTW, we can also avoid compiling clap v3. 😄 
</details>
=> build: ignore criterion in hakari

src/frontend/src/optimizer/plan_node/batch_update.rs, src/frontend/src/optimizer/plan_node/generic/mod.rs, src/frontend/src/optimizer/plan_node/generic/update.rs, src/frontend/src/optimizer/plan_node/logical_update.rs, src/frontend/src/planner/update.rs, src/frontend/src/scheduler/plan_fragmenter.rs
Follow up of #8898, #8870, #8905, #8930, #8932, #9011, #9044, #9176, #9715.
This PR simplifies batch-update nodes.
- Yes
=> refactor(plan_node): use generics in update nodes 

docker/docker-compose.yml, integration_tests/debezium-postgres/create_mv.sql, integration_tests/debezium-postgres/create_source.sql, integration_tests/debezium-postgres/data_check, integration_tests/debezium-postgres/docker-compose.yml, integration_tests/debezium-postgres/postgres/postgres_bootstrap.sql, integration_tests/debezium-postgres/postgres/postgres_dbz.sh, integration_tests/debezium-postgres/postgres_prepare.sql, integration_tests/debezium-postgres/query.sql
The entire docker compose workflow for debezium + postgres cdc has been runnable, but not fully functional due to the bug in our debezium source: https://github.com/risingwavelabs/risingwave/issues/9673 I will enable this workflow once we resolve this issue.
=> test: add debezium-postgres demo in integration tests

src/stream/src/common/table/state_table.rs
In `state_table.rs`, we didn't handle watermark on descending columns correctly in state cleaning.
</details>
=> feat(watermark): handle watermark on desc column (close #9730)

ci/scripts/run-e2e-test.sh, src/meta/src/hummock/manager/mod.rs
Skip the data_directory check in e2e compaction test
</details>
=> fix(ci): fix compaction test ci

src/meta/src/hummock/manager/compaction_group_manager.rs, src/meta/src/hummock/manager/mod.rs, src/meta/src/hummock/manager/tests.rs, src/meta/src/hummock/manager/versioning.rs, src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs, src/storage/hummock_sdk/src/lib.rs, src/storage/src/hummock/local_version/pinned_version.rs
In our current code of HummockVersionExt, we have many methods with `Vec` as return type, while in most cases we only use the return value as an iterator, which means it is unnecessary to return as a `Vec`. In this PR, we turn the return type of these methods to `impl Iterator` so that we can avoid some unnecessary memory allocation.
- Other (please …
=> refactor(storage): reduce Vec return type to avoid unnecessary allocation

src/frontend/planner_test/tests/testdata/range_scan.yaml, src/frontend/src/optimizer/plan_node/logical_scan.rs
After `predicate_pull_up`, the new `Scan` may have a different schema from the original one. Previously we ignore this if we find an always-false condition, which lead to a mismatched schema.
Actually, there's no need to check this **after** `pull_up` since `always_false` property does not change if only column mapping changes. So this PR makes it a separate code path.
Close #9677.
- …
=> fix(optimizer): use correct schema for always-false condition on table scan

src/tests/sqlsmith/src/sql_gen/expr.rs
See the following link for a failing occurrence:
https://buildkite.com/risingwavelabs/pull-request/builds/23391#01880b50-0166-4067-8c63-72c0f69ab0d2
The failing query at bottom contains `HAVING (count(DISTINCT ) >= (SMALLINT '478'))`, despite the surfaced error at the beginning was:
```
---- run_sqlsmith_on_frontend_434 ----
Error Reason:
internal error: Scalar subquery might produce more than one row.
```
I have tried the create table + create materialized view statements before the last batch query and they all succeeded without the subquery error.
Btw, sqlsmith was only able to generate unary aggregates until #9432, …
=> fix(sqlsmith): avoid generating `count(distinct *)`

src/utils/pgwire/src/pg_protocol.rs, src/utils/runtime/src/lib.rs
- Refine the query log format.
`query.log:`
```
2023-05-12T06:40:19.157835Z risingwave-main ThreadId(05) (simple query) session: 0, status: ok, time: 52ms,  sql: create table t1 (v1 int, v2 int, v3 int);
2023-05-12T06:40:19.190056Z risingwave-main ThreadId(03) (simple query) session: 0, status: ok, time: 31ms,  sql: create table t2 (v1 int, v2 int, v3 int);
2023-05-12T06:40:19.221089Z risingwave-main ThreadId(03) (simple query) session: 0, status: ok, time: 30ms,  sql: create table t3 (v1 int, v2 int, v3 int);
2023-05-12T06:40:19.256399Z risingwave-main ThreadId(07) (simple query) session: 0, status: ok, time: 35ms, …
```
=> refactor(frontend): refine query log

Cargo.toml
This profile is confusing: It’s never modified, and many options are the same as [default](https://doc.rust-lang.org/cargo/reference/profiles.html#release). 
I guess this is only used by `cargo bench` micro-benches. I prefer to remove it if no one knows why we have the settings. Just let it inherit `release` profile. If some options are useful, it might be also included in `release` profile.
- …
=> build: remove `profile.bench`

src/frontend/src/optimizer/plan_node/batch_delete.rs, src/frontend/src/optimizer/plan_node/generic/delete.rs, src/frontend/src/optimizer/plan_node/generic/mod.rs, src/frontend/src/optimizer/plan_node/logical_delete.rs, src/frontend/src/planner/delete.rs, src/frontend/src/scheduler/plan_fragmenter.rs
Follow up of #8898, #8870, #8905, #8930, #8932, #9011, #9044, #9176, #9715, #9740.
This PR simplifies batch-update nodes.
- Yes
=> refactor(plan_node): simplify batch-delete

src/cmd/Cargo.toml, src/cmd_all/Cargo.toml
- enable feature `unprefixed_malloc_on_supported_platforms` for tikv-jemallocator
Previousely jemalloc is not used for C/C++ code that use `malloc`, after this, the stats can be more accurate.
#9669
</details>
=> fix: enable tike-jemallocator unprefixed_malloc_on_supported_platforms

src/frontend/src/binder/bind_param.rs, src/frontend/src/handler/extended_handle.rs, src/frontend/src/handler/query.rs, src/frontend/src/session.rs, src/utils/pgwire/src/pg_protocol.rs, src/utils/pgwire/src/pg_server.rs, src/utils/runtime/src/lib.rs
- Only print logs when handling `parse` and `execute` messages for prepare statements. Related issue https://github.com/risingwavelabs/risingwave/issues/9710.
```
2023-05-15T04:44:32.59611Z risingwave-main ThreadId(11) (extended query parse) session: 17, status: ok, time: 6ms, sql: SELECT c FROM sbtest1 WHERE id=$1
2023-05-15T04:44:32.603533Z risingwave-main ThreadId(11) (extended query execute) session: 17, status: ok, time: 6ms, sql: SELECT c FROM sbtest1 WHERE id = $1, params = Some([Some(Int64(4992))])
2023-05-15T04:44:32.616455Z risingwave-main ThreadId(05) (extended query execute) session: 17, status: ok, time: …
```
=> feat(frontend): refine prepare statement query log

src/tests/sqlsmith/src/sql_gen/expr.rs
=> fix(sqlsmith): output `count(*)` correctly

src/frontend/src/scheduler/distributed/stage.rs
Since the issue in madsim has been resolved in https://github.com/madsim-rs/madsim/pull/133, we can remove this workaround now which was introduced in #8399 .
</details>
=> chore(frontend): remove workaround for query hang in frontend

e2e_test/ddl/show.slt, src/frontend/src/catalog/index_catalog.rs, src/frontend/src/handler/describe.rs, src/frontend/src/handler/show.rs, src/frontend/src/handler/util.rs, src/sqlparser/src/ast/mod.rs, src/sqlparser/src/keywords.rs, src/sqlparser/src/parser.rs, src/sqlparser/tests/testdata/show.yaml
- Support `SHOW INDEXES FROM t`. Resolve https://github.com/risingwavelabs/risingwave/issues/9046?notification_referrer_id=NT_kwDOAI61WLI2MDkzODU5NzY1OjkzNTI1MzY&notifications_query=reason%3Aparticipating.
```sql
dev=> show indexes from sbtest1;
Name |   On    |      Key      | Include | Distributed By
------+---------+---------------+---------+----------------
k_1  | sbtest1 | k ASC, id ASC | c, pad  | k
ck_1 | sbtest1 | k ASC, id ASC | c, pad  | k
(2 rows)
```
- SQL commands, functions, and …
=> feat(frontend): support show indexes

e2e_test/s3/json_file.py, src/connector/src/source/filesystem/s3/enumerator.rs
Our S3 connector uses `list_objects_v2` API to list objects of a bucket, but this API returns up to 1000 objects once. I have improved it to break the limit.
</details>
=> fix(connector): s3 source up to 1k objects

src/frontend/planner_test/tests/testdata/nexmark.yaml, src/frontend/planner_test/tests/testdata/nexmark_source.yaml, src/frontend/planner_test/tests/testdata/nexmark_watermark.yaml, src/frontend/planner_test/tests/testdata/share.yaml, src/frontend/planner_test/tests/testdata/tpch.yaml, src/frontend/src/optimizer/plan_node/stream_share.rs, src/meta/src/stream/scale.rs, src/tests/simulation/src/ctl_ext.rs, src/tests/simulation/tests/it/scale/mod.rs, src/tests/simulation/tests/it/scale/no_shuffle.rs
As mentioned in https://github.com/risingwavelabs/risingwave/pull/9381/files#r1174785930. This PR makes `Share` always be transformed into a `NoShuffle` exchange.
After that, I also found an issue of not handling multiple no-shuffle upstream fragments when scaling (like the topology below, fragment 4 has two no-shuffle upstreams 5 and 7). This PR also fixes that.
Since we've introduced more no-shuffles in nexmark chaos scaling test, this PR also makes `can_reschedule` more general to avoid trying to reschedule a non-upstream-most no-shuffle fragment.
<details><summary>Click …
=> feat(streaming): use no-shuffle exchange for share & fix scaling

src/connector/src/parser/protobuf/parser.rs
Fixed support for `sint32`/`sint64` to pb parser, as `prost_reflect` already [supported these types](https://github.com/andrewhickman/prost-reflect/blob/main/prost-reflect-tests/src/decode.rs#L358).
close #9856
</details>
=> fix: sint support for protobuf

src/frontend/planner_test/tests/testdata/distinct_on.yaml, src/frontend/planner_test/tests/testdata/nexmark_source.yaml, src/frontend/planner_test/tests/testdata/nexmark_watermark.yaml, src/frontend/planner_test/tests/testdata/tpch_variant.yaml, src/frontend/planner_test/tests/testdata/watermark.yaml, src/frontend/src/optimizer/plan_node/generic/dedup.rs
- Print column names instead of column indexs for `Dedup`.
</details>
=> chore(frontend): refine dedup display

e2e_test/batch/basic/table_with_default_columns.slt.part, src/frontend/src/handler/create_table.rs
`default` exprs are casted when creating table, if applicable.
</details>
=> fix(frontend): cast `default` exprs when creating table

e2e_test/source/basic/kafka.slt, src/frontend/src/handler/create_source.rs
Fix #9872 according to the discussion in #9771. Reject req if pk is not provided.
</details>
=> fix(frontend): force user specify at least one pk when create upsert json source 

src/meta/src/stream/scale.rs, src/meta/src/stream/source_manager.rs, src/stream/src/executor/source/source_executor.rs, src/stream/src/executor/source/state_table_handler.rs
This PR experimentally supports split reduction.
When the source in the source manager enables the split scale-in function, the source manager will treat the split reduction as a change instead of ignoring it during the tick, leading to an in-place removal and pushing the assignment downstream. Upon receiving this, the source executor will consider the split reduction as a state change and delete the removed split's state during the commit phase.
Please note that the changes in this PR will need complex testing. cc @tabVersion 
This Pull Request introduces several key changes across the `scale.rs`, `source_manager.rs`, …
=> feat(source): experimental support for split reduction.

src/frontend/src/session.rs
```
psql -h localhost -U root -p 4566 -d non
psql: error: connection to server at "localhost" (::1), port 4566 failed: Connection refused
Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 4566 failed: ERROR:  Startup Error when connect to session: database "non" does not exist
```
More consistent to pg than before.
Fix #6635
- SQL commands, functions, and …
=> chore(session): refine non-existent database error

src/expr/src/expr/expr_udf.rs, src/expr/src/expr/mod.rs, src/expr/src/table_function/user_defined.rs
This PR adds a global map to cache all UDF clients, so that we can make sure there's at most 1 connection from a CN to a UDF service.
This should be able to avoid the problem in #9074.
=> fix(udf): reuse client for the same UDF service

java/connector-node/assembly/pom.xml, java/connector-node/risingwave-connector-test/pom.xml
- Connector node logging failed because `SLF4J: Class path contains multiple SLF4J bindings`.
- Logging for the `risingwave-connector-test` module failed for the same reason.
- Excluded unused `slf4j` bindings in `pom.xml` so that logging can work properly.
Related:
- https://github.com/risingwavelabs/risingwave/pull/9617
- https://stackoverflow.com/questions/22896243/maven-slf4j-class-path-contains-multiple-slf4j-bindings
~~- [ ] I have demonstrated that backward compatibility is not broken by …
=> fix(connector): multiple logging bindings

src/frontend/planner_test/tests/testdata/agg.yaml, src/frontend/planner_test/tests/testdata/order_by.yaml, src/frontend/planner_test/tests/testdata/tpch.yaml, src/frontend/src/optimizer/plan_node/batch_sort_agg.rs, src/frontend/src/optimizer/plan_node/generic/agg.rs, src/frontend/src/optimizer/plan_node/logical_agg.rs
Because the number of input rows is a lot larger than the number of output rows, sorting before aggregation can cause huge waste. This PR switches the behavior to only generate `BatchSortAgg` when input provides order on group keys.
Also closes #9838 cuz arbitrary group key type is supported in #9850 and this PR unlocks it in frontend.
- ~~[ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. …
=> refactor(batch agg): simplify batch agg generation

src/connector/src/source/base.rs, src/connector/src/source/kinesis/mod.rs, src/connector/src/source/kinesis/source/reader.rs, src/meta/src/stream/source_manager.rs
=> feat(source): Add support for split reduction in Kinesis connector.

Cargo.lock, src/meta/Cargo.toml, src/meta/src/rpc/election_client.rs, src/meta/src/storage/wrapped_etcd_client.rs, src/tests/simulation/Cargo.toml
This PR adds the resign functionality to the etcd election client. The etcd election client actively resigns after the planned stop is executed, preventing downtime when `meta_leader_lease_secs` is too long.
This pull request adds a new `ResignOptions` parameter to the `ElectionClient` in the `etcd_client` library, enabling the provision of the correct `LeaderKey` which is used for the `resign` call. Additionally, it extends the `impl_etcd_client_command_proxy` macro to include `resign` and `ResignResponse` functionality. 
The test cases have also been updated to include tests for the newly added `resign` function.
~- [ …
=> feat: Add resign functionality to the etcd election client.

src/frontend/src/optimizer/plan_node/logical_over_window.rs, src/frontend/src/optimizer/plan_node/stream_eowc_over_window.rs, src/stream/src/executor/over_window/eowc.rs, src/stream/tests/integration_tests/eowc.rs
I found that the watermark produced by `EowcOverWindow` can be totally wrong. E.g.
```
lead(x) over (partition by $1 order by $0)
(1, 'a')
(2, 'b')
(3, 'b')
(7, 'b')
```
For the above input, the result of `'a'` won't be emitted until next `'a'` which may come several years later. Hence, no watermark can be produced on the `order by` column.
After some discussion with @st1page, we decided to not produce watermark in `EowcOverWindow`.
- …
=> fix(over-window): don't produce watermark from eowc over window

src/frontend/planner_test/tests/testdata/input/over_window_function.yaml, src/frontend/planner_test/tests/testdata/output/over_window_function.yaml, src/frontend/src/optimizer/plan_node/logical_over_window.rs
```sql
create table t(x int, y int, z int, w int);
select * from (
SELECT x, y, z, avg(z * z) OVER (PARTITION BY y + 1 order by abs(w)) as res FROM t
)
WHERE z > 0 and y > 0 and x > 0 and res <= 3;
```
=> feat(planner, overagg): support expression in the agg args

src/frontend/src/binder/expr/function.rs, src/frontend/src/catalog/system_catalog/mod.rs, src/frontend/src/catalog/system_catalog/pg_catalog/mod.rs, src/frontend/src/catalog/system_catalog/pg_catalog/pg_constraint.rs, src/frontend/src/catalog/system_catalog/pg_catalog/pg_inherits.rs
As titled, this can reduce the errors shown when using Postgres connector to connect to RisingWave in DBeaver.
SQL commands, functions, and operators
System Tables:
- …
=> feat(pg_catalog): support pg_constraint, pg_inherits, pg_tablespace_location

e2e_test/database/timezone.slt, src/sqlparser/src/parser.rs, src/sqlparser/tests/testdata/set.yaml
Allow `set time zone 'utc';` (in addition to `set time zone utc;` without quotes).
see https://github.com/risingwavelabs/risingwave/pull/8572#discussion_r1138158571
used by cube #9946
=> fix(sqlparser): allow single quoted value for `set time zone`

Cargo.lock, Makefile.toml, src/cmd_all/Cargo.toml, src/cmd_all/src/bin/risingwave.rs, src/cmd_all/src/playground.rs, src/compute/src/lib.rs, src/ctl/src/lib.rs, src/frontend/src/lib.rs, src/meta/src/lib.rs, src/storage/compactor/src/lib.rs, src/workspace-hack/Cargo.toml
Use `clap` builder for multi-call dispatching of all-in-one binary.
This PR also refactors the playground's profile arguments with `clap`.
Pros: perfectly consistent CLI style with other components
- All-in-one executable help
```
❯ target/debug/risingwave help      
All-in-one executable for components of RisingWave
Usage: risingwave <COMPONENT>
Components:
compute     The worker node that executes query plans and handles data ingestion and output [aliases: compute-node, compute_node]
meta        The central metadata management service [aliases: meta-node, meta_node]
frontend    The stateless proxy that parses SQL …
```
=> refactor: use clap for multicall of all-in-one binary

ci/scripts/gen-flamegraph.sh, proto/stream_plan.proto, src/common/src/hash/consistent_hash/bitmap.rs, src/frontend/planner_test/tests/testdata/output/distribution_derive.yaml, src/frontend/planner_test/tests/testdata/output/emit_on_window_close.yaml, src/frontend/planner_test/tests/testdata/output/except.yaml, src/frontend/planner_test/tests/testdata/output/intersect.yaml, src/frontend/planner_test/tests/testdata/output/join.yaml, src/frontend/planner_test/tests/testdata/output/nexmark.yaml, src/frontend/planner_test/tests/testdata/output/over_window_function.yaml, src/frontend/planner_test/tests/testdata/output/share.yaml, src/frontend/planner_test/tests/testdata/output/stream_dist_agg.yaml, src/frontend/planner_test/tests/testdata/output/temporal_filter.yaml, src/frontend/planner_test/tests/testdata/output/tpch.yaml, src/frontend/planner_test/tests/testdata/output/union.yaml, src/frontend/src/optimizer/plan_node/stream_table_scan.rs, src/meta/src/manager/catalog/mod.rs, src/meta/src/rpc/ddl_controller.rs, src/meta/src/stream/stream_manager.rs, src/stream/src/executor/backfill.rs, src/stream/src/from_proto/chain.rs, src/tests/simulation/tests/integration_tests/main.rs, src/tests/simulation/tests/integration_tests/recovery/backfill.rs, src/tests/simulation/tests/integration_tests/recovery/mod.rs, src/tests/simulation/tests/integration_tests/scale/cascade_materialized_view.rs
Many thanks to @chenzl25 who has provided lots of advice, discussion and review around it.
---
Backfill state is persisted. There are still further changes before #8051 can be fully supported, specifically allowing meta to persist partially complete state, implementing the logic to recover from partially complete state, and defining valid partially complete states.
This also means pretty much all queries become stateful. This is due to StreamTableScan becoming stateful (if backfill is used).
Persist backfill operator state. This is encoded in the following form:
```
| vnode | pos (upstream_pk) | backfill_finished |
``` …
=> feat(backfill): Persist backfill operator state

src/connector/src/source/base.rs, src/connector/src/source/kinesis/mod.rs, src/connector/src/source/kinesis/source/reader.rs, src/meta/src/stream/source_manager.rs
as title, revert due to unstable behavior
Please keep the types …
=> fix: Temporarily rolling back the Kinesis split reduction feature

e2e_test/batch/basic/boolean.slt.part, src/frontend/src/binder/expr/mod.rs, src/meta/src/manager/catalog/utils.rs, src/sqlparser/src/ast/mod.rs, src/sqlparser/src/parser.rs, src/tests/regress/data/expected/boolean.out, src/tests/regress/data/sql/boolean.sql
Resolves #8933
Support `IS [NOT] UNKNOWN` ([pgdoc](https://www.postgresql.org/docs/15/functions-comparison.html))
=> feat(sqlparser): support `IS [NOT] UNKNOWN`

src/frontend/src/catalog/system_catalog/pg_catalog/mod.rs, src/frontend/src/catalog/system_catalog/pg_catalog/pg_attribute.rs
fix https://github.com/risingwavelabs/risingwave/issues/10019
</details>
=> feat(frontend): add atttypmod column on pg_attribute table

e2e_test/batch/catalog/version.slt.part, src/frontend/src/binder/expr/function.rs, src/utils/pgwire/src/pg_protocol.rs
- Currently, our pg version is inconsistent and also too high to make it compatible with JDBC. (e.g. jdbc PostgreSQL connector will use over window sql to fetch columns metadata). So downgrade version to 8.3 is more appropriate right now. 
- Part of https://github.com/risingwavelabs/risingwave/issues/10021
- Other (please specify in the release note …
=> fix(frontend): downgrade pg version

e2e_test/batch/functions/pow.slt.part, src/common/src/types/decimal.rs, src/common/src/types/mod.rs, src/expr/src/vector_op/arithmetic_op.rs, src/tests/regress/data/sql/float8.sql
Previously, `pow(decimal, decimal)` would be implicitly casted and handled by `pow(double precision, double precision)`.
This PR:
* Handles decimal directly and returns decimal in this case.
* Handles special values the same way as PostgreSQL (same as posix [math.h](https://www.open-std.org/JTC1/SC22/WG14/www/docs/n2310.pdf)).
Fix `pow(decimal, decimal)` return type, and `pow(double precision, double precision)` on special values.
=> fix(expr): `pow` behavior for decimal and special values

src/expr/macro/src/lib.rs, src/expr/src/expr/mod.rs, src/expr/src/lib.rs, src/expr/src/vector_op/arithmetic_op.rs
As title.
It's generated by GPT4 based on my draft.
=> doc(expr): add docs for `#[function]` macro

Cargo.toml
close #9107
tested:
- `ci-dev` 1.4G -> 764M (zstd compressed CI artifact 204M -> 130M)
- `release` 1.3G -> 761M 
</details>
=> build: debug=1 -> "line-tables-only"

e2e_test/batch/functions/like.slt.part, src/frontend/planner_test/tests/testdata/input/index_selection.yaml, src/frontend/planner_test/tests/testdata/output/index_selection.yaml, src/frontend/src/optimizer/rule/rewrite_like_expr_rule.rs
Fix #10018 
The rule doesn't handle escape correctly.
It's still incorrect in some UTF-8 inputs, but the PR doesn't make it worse :(
</details>
=> fix(optimizer): handle escape correctly in RewriteLike

src/tests/sqlsmith/src/runner.rs, src/tests/sqlsmith/src/validation.rs
Problem:
1. If stream query has error, it triggers recovery later on.
2. Then subsequent queries encounter `cluster is in recovery` error when they run.
Solution: On sqlsmith side we need to retry until it recovers, and permit recovery error.
</details>
=> fix(sqlsmith): tolerate recovery error

src/meta/src/hummock/manager/mod.rs
As title, it's wired that origin code pass `cargo fmt`, anyways, modify manually.
~~- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the …
=> chore(fmt): fix code that escapes cargo fmt inspection

src/expr/src/expr/build.rs, src/expr/src/expr/expr_array_remove.rs
Similar to `array_positions` (https://github.com/risingwavelabs/risingwave/pull/9152#discussion_r1164970363)
=> refactor(expr): simplify `array_remove`

src/meta/src/barrier/command.rs, src/meta/src/barrier/mod.rs
As title, while running an issued canceling command for streaming job, the target command is possibly stashed in `finished_commands` and waiting for checkpoint, we should clear it rather than finish it.
</details>
=> fix: fix cancel of streaming job when create command is stashed

src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml, src/frontend/src/optimizer/plan_node/stream_hash_agg.rs
`emit_on_window_close` seems to imply `append_only` property.
- ~~[ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)~~
Please keep the types that apply to your changes, and remove the …
=> fix(eowc): mark stream hash agg as `append_only` if eowc

src/frontend/planner_test/tests/testdata/output/append_only.yaml, src/frontend/planner_test/tests/testdata/output/emit_on_window_close.yaml, src/frontend/planner_test/tests/testdata/output/nexmark.yaml, src/frontend/planner_test/tests/testdata/output/nexmark_source.yaml, src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml, src/frontend/planner_test/tests/testdata/output/share.yaml, src/frontend/planner_test/tests/testdata/output/stream_dist_agg.yaml, src/frontend/planner_test/tests/testdata/output/temporal_join.yaml, src/frontend/planner_test/tests/testdata/output/tpch_variant.yaml, src/frontend/planner_test/tests/testdata/output/watermark.yaml, src/frontend/planner_test/tests/testdata/output/window_join.yaml, src/frontend/src/optimizer/plan_node/stream_delta_join.rs, src/frontend/src/optimizer/plan_node/stream_dynamic_filter.rs, src/frontend/src/optimizer/plan_node/stream_exchange.rs, src/frontend/src/optimizer/plan_node/stream_hash_agg.rs, src/frontend/src/optimizer/plan_node/stream_hash_join.rs, src/frontend/src/optimizer/plan_node/stream_hop_window.rs, src/frontend/src/optimizer/plan_node/stream_materialize.rs, src/frontend/src/optimizer/plan_node/stream_now.rs, src/frontend/src/optimizer/plan_node/stream_project.rs, src/frontend/src/optimizer/plan_node/stream_sink.rs, src/frontend/src/optimizer/plan_node/stream_sort.rs, src/frontend/src/optimizer/plan_node/stream_source.rs, src/frontend/src/optimizer/plan_node/stream_table_scan.rs, src/frontend/src/optimizer/plan_node/stream_temporal_join.rs, src/frontend/src/optimizer/plan_node/stream_union.rs, src/frontend/src/optimizer/plan_node/stream_values.rs, src/frontend/src/optimizer/plan_node/stream_watermark_filter.rs, src/frontend/src/optimizer/plan_node/utils.rs
We now have many bool properties for each stream plan node, including `append_only` and `eowc` for many nodes and `window`/`interval` for `StreamHashJoin`. Previously we display these properties by change the node name, e.g. `StreamAppendOnlyHashAgg`, but this approach cannot handle nodes with multiple properties. This PR changes the display behavior to `StreamHashAgg [append_only, eowc]`, and introduces a macro to ease the construction of the property list:
```rust
let mut builder = formatter_debug_plan_node!(
f, "StreamHashJoin"
, { "window", self.left().watermark_columns().contains(ljk) && …
```
=> refactor(explain): introduce `formatter_debug_plan_node` for convenient display of plan node properties

ci/workflows/integration-tests.yml
- add tidb-cdc-sink integration test to ci
- close https://github.com/risingwavelabs/risingwave/issues/9376
~~- [ …
=> feat(ci): add tidb-cdc-sink integration test to ci

e2e_test/batch/basic/func.slt.part, e2e_test/batch/functions/array_concat.slt.part, src/expr/src/vector_op/cast.rs, src/frontend/planner_test/tests/testdata/input/concat_op_dispatch.yaml, src/frontend/planner_test/tests/testdata/output/concat_op_dispatch.yaml, src/frontend/src/binder/bind_param.rs, src/frontend/src/binder/expr/binary_op.rs, src/frontend/src/binder/expr/function.rs, src/frontend/src/binder/expr/value.rs, src/frontend/src/expr/function_call.rs, src/frontend/src/expr/literal.rs, src/frontend/src/expr/mod.rs, src/frontend/src/expr/type_inference/cast.rs, src/frontend/src/expr/type_inference/func.rs
Expected:
* `pg_typeof('a')` -> `unknown`
* `pg_typeof('a'::varchar)` -> `varchar`
Actual:
* `pg_typeof('a')` -> `unknown`
* `pg_typeof('a'::varchar)` -> `unknown`
The distinction is more noticable in the following PostgreSQL expressions https://github.com/risingwavelabs/risingwave/pull/10122#discussion_r1212903168:
* `array['a'] || null` -> `{a}`
* `array['a'] || null::varchar` -> `{a,NULL}`
It is fixed by making `Literal::data_type: Option<DataType>`.
* Most existing use cases can just `unwrap_or(DataType::Varchar)`. And for places where it is needed to distinguish the two, the `is_unknown` helper is available.
* …
=> fix(binder): distinguish `'a'::varchar` from untyped `'a'`

src/frontend/planner_test/tests/testdata/input/nexmark.yaml, src/frontend/planner_test/tests/testdata/input/nexmark_source.yaml, src/frontend/planner_test/tests/testdata/input/nexmark_watermark.yaml, src/frontend/planner_test/tests/testdata/output/nexmark.yaml, src/frontend/planner_test/tests/testdata/output/nexmark_source.yaml, src/frontend/planner_test/tests/testdata/output/nexmark_watermark.yaml
`REGEXP_EXTRACT` is not a Postgres function. It can be replaced with `REGEXP_MATCH` with array accessing just like what we did in e2e test and benchmarks.
BTW, we should really find a way to extract these common SQLs. 😕
</details>
=> test: enable nexmark q21 in planner test

src/frontend/src/optimizer/plan_node/generic/agg.rs, src/frontend/src/optimizer/plan_node/generic/dynamic_filter.rs, src/frontend/src/optimizer/plan_node/generic/filter.rs, src/frontend/src/optimizer/plan_node/generic/hop_window.rs, src/frontend/src/optimizer/plan_node/generic/intersect.rs, src/frontend/src/optimizer/plan_node/generic/mod.rs, src/frontend/src/optimizer/plan_node/generic/project.rs, src/frontend/src/optimizer/plan_node/generic/union.rs
This is a folllow up of #10132.
- Yes
-
=> refactor(plan_node_fmt): further prepare generic code where they use `fmt_with_builder`

e2e_test/batch/join/left_join_with_non_equi_cond.slt, src/batch/src/executor/join/hash_join.rs
- Resolve https://github.com/risingwavelabs/risingwave/issues/10148
</details>
=> fix(batch): fix left join with equi-conditions

e2e_test/batch/catalog/pg_tables.slt.part, src/frontend/src/catalog/system_catalog/mod.rs, src/frontend/src/catalog/system_catalog/pg_catalog/mod.rs, src/frontend/src/catalog/system_catalog/pg_catalog/pg_tables.rs
Part of #10131 , introduce system catalog `pg_tables`.
Introduce system catalog `pg_tables`, which includes columns `schemaname`, `tablename`, `tableowner` and `tablespace`.
</details>
=> feat(frontend): introduce system catalog pg_tables

src/common/src/config.rs, src/common/src/session_config/mod.rs, src/common/src/session_config/visibility_mode.rs, src/config/example.toml, src/frontend/src/handler/explain.rs, src/frontend/src/handler/query.rs, src/frontend/src/lib.rs, src/frontend/src/scheduler/hummock_snapshot_manager.rs, src/frontend/src/scheduler/worker_node_manager.rs, src/frontend/src/session.rs, src/meta/src/manager/cluster.rs
Previously the default value of visibility_mode session var is hard coded. It's inconvenient for a user who wants a different visibility_mode, because it need be set per session. And usually user always use the same visibility_mode for the same cluster.
This PR adds support for setting default visibility_mode for all sessions from a frontend node via its config.
- For a new session, visibility_mode session var is `Default`, which is interpreted as reading from config.
- If visibility_mode session var is set (`All` or `Checkpoint`), it overrides config one.
#8940 …
=> feat(config): support for setting default visibility_mode via config

src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
We meet some error when try to insert sstable files to sub level for an intra-l0 compaction task. We need more log information to locate the problem root cause.
</details>
=> fix(meta): add more log for insert sub level

proto/expr.proto, src/expr/src/vector_op/array_positions.rs, src/expr/src/vector_op/array_replace.rs, src/expr/src/vector_op/mod.rs, src/frontend/src/binder/expr/function.rs, src/frontend/src/expr/pure.rs, src/frontend/src/expr/type_inference/func.rs, src/tests/regress/data/sql/arrays.sql
Support the following array functions in PostgreSQL:
* `array_position ( anycompatiblearray, anycompatible [, integer ] ) → integer`
* `array_remove ( anycompatiblearray, anycompatible ) → anycompatiblearray`
Limitation:
* We do not support recursively replacing the base element of a multidimensional array yet. (`select array_replace(array[array[array[0, 1], array[2, 3]], array[array[4, 5], array[6, 7]]], 3, 9);`)
Support the following array functions in PostgreSQL:
* `array_position ( anycompatiblearray, anycompatible [, integer ] ) → integer`
* `array_remove ( …
=> feat(expr): support `array_position` and `array_replace` for 1d scenario

java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzCdcEngineRunner.java
=> chore(connector-node): assign id to cdc engine runner thread

src/frontend/src/handler/create_table.rs
We have actually 2 kinds of bind error's here
1. user writes a sql with syntax that we do not support (such as unique key, foreign key)
2. user writes a syntax illeagle (such as multiple pk definition)
This PR split them to different functions.
</details>
=> refactor(binder): refactor the logic to valid constraints

src/common/src/config.rs, src/config/example.toml, src/storage/src/hummock/event_handler/hummock_event_handler.rs, src/storage/src/opts.rs
As titled.
With this PR, we can set the storage config `shared_buffer_flush_ratio` to set the ratio that starts spilling data to object store when ratio of the current memory usage exceeds the shared buffer capacity.
Default value is the previous `0.8`.
</details>
=> feat(storage): enable setting the flush threshold in storage

e2e_test/source/cdc/cdc.check.slt, e2e_test/source/cdc/cdc.load.slt, java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/common/PostgresValidator.java, java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/SourceHandlerFactory.java, java/connector-node/risingwave-connector-service/src/main/resources/mysql.properties
- related issue: https://github.com/risingwavelabs/risingwave/issues/10206
- the debezium property `database.server.name` should be unique for each connector
- otherwise the metrics within debezium cannot be registered properly, causing a delay
- now for mysql connectors, `database.server.name=RW_CDC_${database.name}.${table.name}.${source.id}` since `source.id` is unique in rw
reference:
- https://groups.google.com/g/debezium/c/a2HE1Zgd6sQ?pli=1 …
=> fix(cdc): unique `database.server.name` for dbz mysql connector

src/frontend/src/binder/relation/join.rs, src/frontend/src/expr/function_call.rs, src/frontend/src/expr/mod.rs, src/frontend/src/expr/type_inference/cast.rs, src/frontend/src/expr/type_inference/func.rs
This PR contains 2 candidate solutions to simplify the repeated pattern below. **We only need one of them.**
```
let expr_owned = std::mem::replace(expr_mut_ref, new_dummy_expr());
*expr_mut_ref = expr_owned.cast_implicit(target_data_type)?;
```
Two straightforward but less desired approaches are:
* Extract this into a reusable `cast_mut` utility function
* `impl Default for ExprImpl` so that we can just `take` rather than `replace` with a dummy value
The first is not a proper abstraction because it may leave the input partially mutated. When the cast fails, the input is already replaced by the dummy expression. It is …
=> refactor(binder): in-place `cast_mut` or `ExprImpl::take`

src/cmd_all/build.rs, src/cmd_all/src/bin/risingwave.rs, src/common/src/lib.rs
After #10228, we will fail to compile if there's no `git` context.
- Leave `VERGEN_GIT_SHA` unset if there's no `git` CLI or not in a git repository.
- Treat empty `GIT_SHA` as unset as well.
</details>
=> fix(build): do not fail if there's no `git` context

src/expr/src/vector_op/array_length.rs, src/expr/src/vector_op/cardinality.rs, src/frontend/planner_test/tests/testdata/output/concat_op_dispatch.yaml, src/frontend/src/binder/expr/function.rs, src/frontend/src/expr/mod.rs, src/frontend/src/expr/type_inference/func.rs
Use `ExprImpl::ensure_array_type` to reject untyped (`null` or `'{1,2}'`) or non-array inputs to array functions:
* `array_ndims`
* `array_lower` (forwards to `array_ndims`)
* `array_upper` (forwards to `array_length`)
* `array_dims`
* `array_length`
* `cardinality`
* `array_to_string`
* `trim_array`
* `array_distinct`
Note the following functions are declared with `anycompatiblearray` rather than `anyarray`, thus using a different rule `align_array_and_element` (done before this PR):
* `array_cat`
* `array_append`
* `array_prepend`
* `array_remove`
* `array_replace` (1d only)
* `array_position`
* `array_positions`
This …
=> refactor(binder): unify array function type checking

ci/scripts/run-fuzz-test.sh, ci/workflows/pull-request.yml
Sometimes it fails and blocks PRs. Unlike random fuzz test, once deterministic test fails, it keeps failing and blocks the PR. We can't re-run it to try and unblock.
Random fuzz test will still run for PRs with changes to sqlsmith source files or scripts.
</details>
=> chore(sqlsmith): disable deterministic tests being run per PR

Cargo.lock, src/expr/Cargo.toml, src/expr/src/sig/func.rs, src/expr/src/vector_op/array_length.rs, src/expr/src/vector_op/cardinality.rs, src/frontend/src/expr/type_inference/func.rs
Since this commit, the frontend will generate plans with `int32`.
For backward compatibility, the backend will run both `int32` and `int64` variants as requested by the query plan.
Note: Having both `cardinality(list) -> int32` and `cardinality(list) -> int64` in the function signature map means the type inferring logic cannot find a unique match. But we have them covered in `infer_type_for_special` to always return `int32`. Eventually it is still better to clean them up from the function signature map.
`array_length` and `cardinality` returns int32 as in PostgreSQL
=> fix(expr): `array_length` and `cardinality` returns int32 as in PostgreSQL

src/frontend/src/optimizer/plan_node/batch_seq_scan.rs, src/frontend/src/optimizer/plan_node/batch_source.rs, src/frontend/src/optimizer/plan_node/batch_table_function.rs, src/frontend/src/optimizer/plan_node/batch_union.rs, src/frontend/src/optimizer/plan_node/batch_update.rs, src/frontend/src/optimizer/plan_node/batch_values.rs, src/frontend/src/optimizer/plan_node/logical_table_function.rs, src/frontend/src/optimizer/plan_node/logical_values.rs
This is a folllllow up of #10132, #10155, #10157, #10253, #10280.
- Yes
=> refactor(plan_node_fmt): 7 more impls for `Distill`

src/frontend/src/optimizer/plan_node/logical_apply.rs, src/frontend/src/optimizer/plan_node/logical_insert.rs, src/frontend/src/optimizer/plan_node/logical_join.rs, src/frontend/src/optimizer/plan_node/logical_multi_join.rs
This is a folllllow up of #10132, #10155, #10157, #10253, #10280, #10281.
- Yes
=> refactor(plan_node_fmt): 4 more impls for Distill

src/object_store/src/object/s3.rs
Fix incompatibility between MinIO and AWS SDK of new version.
See https://github.com/awslabs/aws-sdk-rust/issues/727
</details>
=> fix(storage): force_path_style for minio

src/config/ci-iceberg-test.toml, src/config/ci-recovery.toml, src/config/ci.toml, src/storage/src/hummock/validator.rs
As we're free from uniqueness/order violation bugs for a long time, this PR disable this sanity check in CI, hopefully accelerate its execution.
</details>
=> chore(ci): disable commit SST sanity check in CI

src/storage/backup/integration_tests/common.sh
Adapt test script to #10279 "make private".
</details>
=> fix(test): adapt to cargo make private

ci/scripts/build-other.sh, e2e_test/udf/udf.slt, java/pom.xml, java/udf-example/README.md, java/udf-example/pom.xml, java/udf-example/src/main/java/com/example/UdfExample.java, java/udf/README.md, java/udf/pom.xml, java/udf/src/main/java/com/risingwave/functions/TableFunction.java, java/udf/src/test/java/com/risingwave/functions/TestUdfServer.java, java/udf/src/test/java/com/risingwave/functions/UdfClient.java, src/frontend/src/handler/create_function.rs
- added a simple developer guide for Java UDF.
- split the examples into a new project as a template where users can start from.
- allow `language java` in create function statements.
Please refer to the document itself.
</details>
=> doc(udf): document Java UDF

src/batch/src/executor/top_n.rs, src/common/benches/bench_encoding.rs, src/common/src/util/memcmp_encoding.rs, src/stream/src/executor/aggregation/agg_state_cache.rs, src/stream/src/executor/aggregation/minput.rs, src/stream/src/executor/over_window/eowc.rs, src/stream/src/executor/over_window/mod.rs, src/stream/src/executor/over_window/state/mod.rs, src/stream/src/executor/sort_buffer.rs
Just for better readability. Fixes #8606.
~~- [ ] My PR contains user-facing changes.~~
- …
=> refactor(common): add `MemcmpEncoded` struct to represent memcmp encoded data

Cargo.toml
https://github.com/risingwavelabs/risingwave/pull/10029#issuecomment-1591316116 It harms profiling, as the function name is less readable. Module path information is lost.
Still uses "line-tables-only" for CI.
Comparison:
`debug = "line-tables-only"`
```
thread 'main' panicked at 'Oh no!', src/bin/hello.rs:14:5
stack backtrace:
0: begin_panic_handler
at /rustc/a97c36dd2e6f711949fc9b790476e93bd9e6d1f4/library/std/src/panicking.rs:593:5
1: panic_fmt
at /rustc/a97c36dd2e6f711949fc9b790476e93bd9e6d1f4/library/core/src/panicking.rs:67:14
2: foo
at ./src/bin/hello.rs:14:5
3: {async_block#0}
at ./src/bin/hello.rs:4:5
4: …
```
=> build: use debug=1 back for release

proto/stream_plan.proto, src/connector/src/sink/catalog/desc.rs, src/frontend/planner_test/tests/testdata/output/nexmark.yaml, src/frontend/src/optimizer/mod.rs, src/frontend/src/optimizer/plan_node/stream_sink.rs, src/stream/src/executor/sink.rs, src/stream/src/from_proto/sink.rs
Previously, we insert a `Project` node before the sink executor if the sink's output columns are a subset of its input columns. After we introduce the log store in sink, however, we'll have to compute the vnode (i.e. distribution) within the sink executor. In this PR, we thereby input all columns into the sink executor for the sake of vnode computation, and do the column pruning within the sink executor instead of using a `Project` node.
- Connector (sources & …
=> refactor(sink): prune out hidden columns within sink executor

docker/Dockerfile
As title. Added `build-essentail`, `gdb` (for analyzing core dump) and `jeperf` (for analyzing heap profiling) into the Docker image.
This is both for online debugging and offline analyzing. These tools need to be used in the same system environment as the process, so the most convenient way is to put them in the Docker image as well.
Off-line debugging example:
```bash
docker run -it --entrypoint=bash -v ~/coredump:/coredump ghcr.io/risingwavelabs/risingwave@sha256:9cdfaa9972dbe85e8276301aae7ce41736b124d3b3f8eea51734a6759c7049ce
gdb /risingwave/bin/risingwave coredump
``` 
Also reorganized the file a little bit to …
=> feat: add debug profile tools in docker image

Cargo.lock, proto/monitor_service.proto, src/compute/src/rpc/service/monitor_service.rs, src/compute/src/server.rs, src/ctl/src/cmd_impl/trace.rs, src/rpc_client/src/compactor_client.rs, src/rpc_client/src/lib.rs, src/storage/compactor/Cargo.toml, src/storage/compactor/src/lib.rs, src/storage/compactor/src/rpc.rs, src/storage/compactor/src/server.rs, src/storage/hummock_test/src/compactor_tests.rs, src/storage/src/hummock/compactor/context.rs, src/storage/src/hummock/compactor/iterator.rs, src/storage/src/hummock/compactor/mod.rs, src/stream/src/task/stream_manager.rs, src/tests/compaction_test/src/delete_range_runner.rs
Enable async trace for compactor node. Note that this PR adds as many verbose instrument as possible, e.g. even for iter.next. We can modify RW_ASYNC_STACK_TRACE for compactor if it's too much.
</details>
=> feat(trace): enable await tree trace for compactor

.github/workflows/cherry-pick-to-release-branch.yml
https://github.com/risingwavelabs/risingwave/pull/10388 as an example
but wish to auto-select the reviewer as the committer or @ the person...?
~- [ ] My PR contains user-facing changes.~
=> chore: use github action to auto cherry pick pr to release branch

src/frontend/src/binder/expr/function.rs, src/frontend/src/binder/expr/mod.rs
#10134 , this PR implements system function `user`. Another bug found in #10367 .
Implements system function `user`, `current_user` and `current_role`.
```sql
dev=> select user;
user
------
root
(1 row)
```
=> feat: add system function user, current_user and current_role

src/risedevtool/kafka.toml
=> fix(risedevtool): try download kafka from archive.apache if downloads.apache does not work

ci/scripts/run-fuzz-test.sh, src/tests/sqlsmith/README.md, src/tests/sqlsmith/src/runner.rs, src/tests/sqlsmith/src/sql_gen/mod.rs, src/tests/sqlsmith/src/sql_gen/query.rs, src/tests/sqlsmith/src/sql_gen/relation.rs, src/tests/sqlsmith/src/sql_gen/time_window.rs
It can lead to logic errors, previously we expect columns are already qualified.
If we forgot to qualify columns, it can lead to ambiguity, e.g. in equal join: `select ... join c on c`.
Instead we just don't return columns for table factor, if we need qualified columns just call `get_qualified_columns`.
Resolve error in https://github.com/risingwavelabs/risingwave/pull/10343/files
---
Additionally we:
- Reduce recursion weight at each successful `is_recursive` check.
- Ensure that table subquery does not have unbounded recursion.
Please keep the types that apply …
=> fix(sqlsmith): don't compute columns and table schema separately

e2e_test/batch/basic/range.slt.part, src/frontend/src/binder/relation/mod.rs
~- [ ] My PR contains user-facing changes.~
=> fix: use alias as table function's column name (#10311)

Cargo.lock, src/utils/runtime/Cargo.toml, src/utils/runtime/src/lib.rs, src/workspace-hack/Cargo.toml
- Fallback to default levels for most of the RisingWave crates.
- Introduce back local time for logging. See [comment here](https://github.com/risingwavelabs/risingwave/pull/6152#discussion_r1234783018). Close #6034.
- Simplify env-var overrides without relying on `EnvFilter`. …
=> refactor: refine logging configuration

Cargo.lock, src/ctl/Cargo.toml, src/ctl/src/cmd_impl/meta/reschedule.rs, src/ctl/src/lib.rs
This PR adds the `--from` option to the reschedule command, allowing the configuration to be read from a file. It also modifies the rules for the subcommand, making `--from` conflict with the `--plan` parameter.
</details>
=> feat: supports `--from` option for reschedule command

src/compute/tests/integration_tests.rs, src/connector/src/parser/debezium/simd_json_parser.rs, src/connector/src/parser/unified/util.rs, src/connector/src/source/manager.rs, src/source/src/source_desc.rs, src/stream/src/executor/source/source_executor.rs, src/stream/src/from_proto/source.rs
See #10416
This PR changes the source behaviour when encountering a missing column from skipping the message to filling in null.
Caveat: I think the correct behavior is to only allow missing non-pk columns and we should skip the message if any of the pk column is missing. However, after #8841, we cannot get source pk info easily when creating the source executor so this PR still allows missing pk columns. I leave a TODO for this and will address it in a separate PR.
~~- [ ] I have added necessary unit tests and integration tests~~ I tested locally in my env with pg cdc.
~~- [ ] I have added fuzzing tests or opened an …
=> feat(source): fill in null value on missing column instead of skipping

integration_tests/ad-click/docker-compose.yml, integration_tests/ad-ctr/docker-compose.yml, integration_tests/cdn-metrics/docker-compose.yml, integration_tests/clickstream/docker-compose.yml, integration_tests/debezium-mongo/docker-compose.yaml, integration_tests/debezium-mysql/docker-compose.yml, integration_tests/debezium-postgres/docker-compose.yml, integration_tests/delivery/docker-compose.yml, integration_tests/iceberg-sink/docker-compose.yml, integration_tests/kafka-cdc-sink/docker-compose.yml, integration_tests/livestream/docker-compose.yml, integration_tests/mysql-cdc/docker-compose.yml, integration_tests/mysql-sink/docker-compose.yml, integration_tests/pinot-sink/docker-compose.yml, integration_tests/postgres-cdc/docker-compose.yml, integration_tests/postgres-sink/docker-compose.yml, integration_tests/presto-trino/docker-compose.yml, integration_tests/prometheus/docker-compose.yml, integration_tests/schema-registry/docker-compose.yml, integration_tests/superset/docker-compose.yml, integration_tests/tidb-cdc-sink/docker-compose.yml, integration_tests/twitter-pulsar/docker-compose.yml, integration_tests/twitter/docker-compose.yml, integration_tests/upsert-avro/docker-compose.yml
Reverts risingwavelabs/risingwave#10428
The docker-compose.yaml has been restored #10467
=> fix(integration-test):  restore docker compose file directory name

src/storage/src/hummock/compactor/mod.rs
Previously when a compaction task is cancelled in compactor node, the task's splits' futures are not aborted. This PR aborts them as well.
</details>
=> fix(compaction): abort split futures when cancelling

src/batch/src/executor/hash_agg.rs, src/batch/src/executor/join/hash_join.rs, src/common/src/memory/mem_context.rs, src/common/src/metrics.rs
=> fix: Memory counter leak (#10358)

src/tests/sqlsmith/src/runner.rs
https://github.com/risingwavelabs/risingwave/pull/10430 changes timeout to 6s while generating, and 12s when actually running them in pre-generated queries to allow some buffer. It may take a while to review #10430. So adding this as workaround first.
We have already re-generated the snapshot in #10430, hence main-cron is failing with timeout error.
As we can see in the recent main-cron, tests are timing out as a result:
- SQL …
=> chore(sqlsmith): bump timeout temporarily

src/ctl/src/cmd_impl/scale/resize.rs, src/meta/src/stream/scale.rs, src/tests/simulation/tests/integration_tests/scale/schedulability.rs
PR #10143 introduced modifications for Worker's Schedulablility. This PR is to adapt the `get_reschedule_plan` to refuse cordoned worker id during generating reschedule plan, and to skip cordoned workers when generating a migration plan for a single fragment.
</details>
=> feat: adapt `get_reschedule_plan` with `cordon`

Cargo.lock, src/object_store/Cargo.toml
This PR will bump OpenDAL to v0.37 for bug fixes.
Changelogs: https://docs.rs/opendal/0.37.0/opendal/docs/changelog/index.html
No need for release note.
=> chore: Bump OpenDAL to v0.37

src/meta/src/hummock/compaction/picker/tier_compaction_picker.rs, src/meta/src/hummock/manager/compaction_group_manager.rs, src/meta/src/hummock/manager/mod.rs, src/meta/src/hummock/manager/tests.rs, src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs
pick https://github.com/risingwavelabs/risingwave/pull/10541
</details>
=> fix(meta): check whether input sstable of compact task exist

src/meta/src/manager/catalog/fragment.rs, src/meta/src/rpc/ddl_controller.rs, src/meta/src/rpc/service/scale_service.rs, src/meta/src/stream/stream_manager.rs
This PR upgrades the reschedule lock to a rwlock, and also locks during the create mv stage, which will help in preventing occasional race conditions.
</details>
=> chore: refine reschedule lock

Cargo.lock, ci/scripts/sqlsmith-differential-test.sh, ci/workflows/main-cron.yml, ci/workflows/pull-request.yml, src/tests/sqlsmith/Cargo.toml, src/tests/sqlsmith/README.md, src/tests/sqlsmith/src/bin/main.rs, src/tests/sqlsmith/src/lib.rs, src/tests/sqlsmith/src/runner.rs
Closes #10427 
- Adds differential testing executable.
- Differential testing works by generating stream query, extracting the inner query of it, and running it as a batch query.
- It is expected that after sorting, the results of most queries should match.
- Add to main-cron and PR workflow, but soft fail it, currently seems like there are some unresolved errors.
- Adds `similar` as a dependency.
---
Further improvements:
- Perhaps this mode should have more inserts? 🤔 
- If there are exceptions to differential testing, we can add them later. For now it seems the tests usually pass.
- Support session variable fuzzing. …
=> feat(sqlsmith): differential testing

src/ctl/src/cmd_impl/meta/reschedule.rs, src/ctl/src/lib.rs, src/rpc_client/src/meta_client.rs
This PR implements the "delete-workers" command. It requires a list of worker IDs. Before executing the specific "delete_worker_node" RPC, this command calls "get_cluster_info" and performs a thorough check for any occupied fragments. Additionally, it prompts for confirmation with a "yes/no" message before deletion. …
=> feat: implement the delete-workers command for risectl

src/common/src/session_config/mod.rs, src/frontend/src/handler/variable.rs, src/frontend/src/session.rs, src/utils/pgwire/src/pg_extended.rs, src/utils/pgwire/src/pg_protocol.rs, src/utils/pgwire/src/pg_response.rs
Related #10339 
Now the BeMessageStatus will be set when the application_name was changed dynamicly.
</details>
=> feat(frontend): send application_name when set changed

ci/workflows/main.yml
After implementing java-udf, the running e2e test implicitly depends on the `build-other` of CI, which builds the java-udf jar. After https://github.com/risingwavelabs/risingwave/pull/10552, the time of `build-other` increases, and therefore running e2e test will fail if starting before `build-other` finishes. 
In this PR we added the dependency on build-other for e2e test …
=> fix(ci): add build-other dependency for running e2e test

ci/scripts/release.sh
- maven version bump 3.9.3
- store this tar package in s3
=> fix(ci): maven version bump 3.9.3

src/common/src/util/stream_graph_visitor.rs
- Since the meta node will periodically visit the stream graph to collect metrics, we need to change the `Chain` state table assert for the backward compatibility.
</details>
=> fix(stream): fix chain assert for the graph visitor

.github/workflows/cherry-pick-to-release-branch.yml
Was looking at the wrong documentation of a same-name github action....
=> fix: use github event number instead

.github/workflows/cherry-pick-to-release-branch.yml
add a hashtag before the pull request number so that we can click into the PR.
see a examepl https://github.com/risingwavelabs/risingwave/issues/10644 without `#`
=> fix: add hashtag to link to the old PR

Cargo.lock, src/common/Cargo.toml, src/common/src/array/list_array.rs, src/common/src/types/mod.rs
This PR fixes a bug in encoding when a bytea value is used as primary key.
To reproduce:
```sh
./risedev p
```
```sql
CREATE TABLE b(i bytea primary key, id int);
INSERT INTO b VALUES ('abc', 3);
SELECT * from b;
```
```
thread 'risingwave-compaction' panicked at 'range start index 8 out of range for slice of length 6', 
/Users/wangrunji/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.4.0/src/buf/buf_impl.rs:1354:18
```
The reason is that the bytea value is [encoded](https://github.com/risingwavelabs/risingwave/blob/8ef743f56b1655ee7731bf885b5428421322eaba/src/common/src/types/mod.rs#L1073) through …
=> fix: fix memcomparable encoding for bytea type

.github/pull_request_template.md, CONTRIBUTING.md
Some contributor-facing documentation and changes to the pull request template.
=> chore: provide details of cherry pick github action and remind contributors

e2e_test/batch/functions/session_timezone.slt, e2e_test/batch/types/bytea.slt.part, e2e_test/batch/types/timestamptz_utc.slt.part, src/common/src/types/interval.rs, src/expr/src/vector_op/cast.rs, src/expr/src/vector_op/cmp.rs, src/expr/src/vector_op/length.rs, src/expr/src/vector_op/timestamptz.rs
Added:
* `timestamptz - timestamptz = interval` (resolves #9906)
* `bytea CMP bytea = bool` where `CMP` is `=`, `<>` (`!=`), `<`, `<=`, `>`, `>=`, `is [not] distinct from`
* `cast(bytea) = varchar`
* `octet_length(bytea) = int32` (same as `length(bytea)`)
* `bit_length(bytea) = int32`
Not added:
* `jsonb CMP jsonb` (not meaningful, and our `Ord` is different from PG)
* `cast(struct) = varchar` (buggy #4769)
* `cast(varchar) = struct` (less useful #7369)
* other `bytea` functions (eg `position`, `substr`, `||`)
Support some basic exprs for `timestamptz` and `bytea`:
* `timestamptz …
=> feat(expr): add missing basic exprs for `timestamptz` and `bytea`

src/expr/src/expr/expr_array_to_string.rs, src/tests/regress/data/sql/arrays.sql
Fixes #8680. See https://github.com/risingwavelabs/risingwave/issues/3811#issuecomment-1556656529 for rationale.
This is consistent with `unnest` and `cardinality` (and `array_replace` in the future).
Note the following (with `::text[]` rather than `::text[][]`) is still different from PostgreSQL:
```
select array_to_string(array[array['one', 'two'], array['three', 'four']]::text[], ',');
```
This is not related to the `array_to_string` function. In PostgreSQL, `::text[]` still returns a 2d array with 4 elements, while we return a 1d array with 2 elements, first of which is a result of `array['one', 'two']::text`. This …
=> fix(expr): `array_to_string` should handle multidimensional array recursively

Cargo.lock, src/tests/simulation/Cargo.toml
Closes https://github.com/risingwavelabs/risingwave/issues/10494
</details>
=> chore(deps): update `madsim-aws-s3-sdk`

risedev.yml, src/object_store/src/object/opendal_engine/opendal_object_store.rs
This pr is a workaround for azblob, as OpenDAL does not support unsized write for it now. Will implement unsized write and remove this logic later.
</details>
=> refactor(object_store): use in-memory buffer for storage that does not support unsized write

ci/scripts/integration-tests.sh
Let me test once on buildkite, I copied from risingwave-test's scripts
https://buildkite.com/risingwavelabs/integration-tests/builds/173#01891e6e-e0f1-47b9-b9d7-7841ee8da9c2 without variable set
https://buildkite.com/risingwavelabs/integration-tests/builds/174#01891e76-dda3-4557-bb49-687319d48728 with `RW_IMAGE_VERSION` set to `nightly-20230628`.
seems working now …
=> fix: unbounded variables in integration test

src/meta/src/barrier/command.rs, src/meta/src/barrier/mod.rs, src/meta/src/barrier/recovery.rs, src/meta/src/barrier/schedule.rs, src/meta/src/lib.rs, src/meta/src/manager/catalog/mod.rs, src/meta/src/manager/catalog/user.rs, src/meta/src/rpc/ddl_controller.rs, src/meta/src/stream/stream_manager.rs
#10000
Follow-up of #10660. This PR further adds tracing for the execution of barrier commands, and the recovery progress. RPC calls to compute node will be included as well.
- DML with implicit `FLUSH`
- Create table
- Bootstrap recovery
=> feat(meta): add tracing for barrier commands & recovery

e2e_test/streaming/bug_fixes/hop_window_update_10495.slt, src/common/src/array/data_chunk_iter.rs, src/common/src/array/stream_chunk.rs, src/stream/src/executor/hop_window.rs, src/stream/src/from_proto/hop_window.rs
As explained in https://github.com/risingwavelabs/risingwave/issues/10495#issuecomment-1619370490. This PR reorganizes the output of the hop window executor to group multiple output rows of a single input row together to avoid `Update` interfering with each other.
Previous:
```
dev=> create table t1 (k int primary key, ts timestamp);
CREATE_TABLE
dev=> create materialized view mv as select * from hop(t1, ts, interval '10' minute, interval '30' minute);
CREATE_MATERIALIZED_VIEW
dev=> insert into t1 values (1, '2021-01-01 10:15:00');
INSERT 0 1
dev=> select * from t1;
k | …
```
=> fix(streaming): reorganize output of hop window

src/storage/hummock_trace/src/collector.rs
Tests may fail if they run concurrently. This PR disable them.
</details>
=> chore(test): disable flaky unit tests

src/common/src/system_param/mod.rs, src/config/example.toml
As title. 
The major motivation is to make the system more stable. We have observed more than once that the system fluctuates more under `checkpoint_frequency = 10`. For example, the SST uploader consumes more memory and uses more time to upload one checkpoint.
Performance tests show that there is no difference between `checkpoint_frequency = 1` and `10`. 
- [Performance dashboard: bench-checkpoint-interval](http://risingwave-perf-test-dashboard-metabase.us-west-2.elasticbeanstalk.com/dashboard/36-risingwave-cn-compactor-2-8c16g-nexmark-blackhole-source-throughput-history?namespace=bench-checkpoint-interval&start_date=20 …
=> refactor: set checkpoint frequency to 1

src/stream/src/executor/aggregation/agg_impl/mod.rs
Fixed a bug introduced by #10477:
The return type should be `int64` rather than `timestamptz`. The following still crashes
```
create table t (x timestamp, y timestamptz);
create materialized view mv1 as select count(y) from t;
```
_Originally posted by @xiangjinwu in https://github.com/risingwavelabs/risingwave/pull/10477#discussion_r1252547869_
- …
=> fix(agg): fix count timestamptz

src/expr/src/vector_op/string.rs, src/risedevtool/src/bin/risedev-docslt.rs
Fix #10749
- ~~[ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the …
=> fix(docslt): panic on malformed slt block

e2e_test/batch/join/issue_10037.slt, src/frontend/planner_test/tests/testdata/input/predicate_pushdown.yaml, src/frontend/planner_test/tests/testdata/output/predicate_pushdown.yaml, src/frontend/src/optimizer/plan_node/logical_join.rs
=> fix(optimizer): avoid equi-join predicate substitution when types mismatch

src/frontend/src/scheduler/worker_node_manager.rs
Due to asynchronism of serving vnode mapping updating, it's expected that query may not find serving fragment mapping immediately after DDL, and subsequently client is responded with `ServingVnodeMappingNotFound` error. This error is transient. Client may retry the query and succeed a few moment later.
This PR eliminates the transient error: when encountering `ServingVnodeMappingNotFound`, frontend node will fall back to a temporary serving vnode mapping, instead of failing query with `ServingVnodeMappingNotFound`.
Fix #10808 …
=> fix(batch): workaround serving fragment mapping absence due to asynchronism

risedev.yml, src/stream/src/executor/wrapper.rs, src/stream/src/executor/wrapper/trace.rs
- enable tracing for streaming executors under release profile (forgotten in #10315)
- enable "release-verbose" await-tree option for RiseDev by default
</details>
=> fix(streaming): enable tracing for executors under release profile
